### ISSUE TITLE
Crashes when signing in?

### ISSUE THREAD

**Issue by mew351** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1]
Can't even sign in without it crashing D;

**Comment by MarshallOfSound** [comment]
Please provide more details.
The exact process you took to cause it to crash
Your OS
And if possible what .NET versions you have installed

**Comment by MarshallOfSound** [comment]
Issue has been identified, replicated and fixed in Version 1.1.1
