### ISSUE TITLE
Resizeable mini player

### ISSUE THREAD

**Issue by hndmrsh** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#10]
The mini player implementation is great! I'd really love the ability to resize it though, as it's a little bit too big for my liking - and I can see it being an issue for people with lower resolution screens (unless it's resolution independent).

**Comment by MarshallOfSound** [comment]
Lots of the styling of the mini player is very tightly squeezed into it's current size.  The CSS uses hard coded values to make everything fit in.

I'll look around for alternatives but at the moment making it any smaller will be quite tricky.  I might be able to trigger zooming or something inside CEF.

**Comment by MarshallOfSound** [comment]
Triggering the zooming in CEF appears to work.  I've set a maximum size of 300 by 300 (current default) and a minimum size of 100 by 100.  The aspect ratio is being enforced as 1.0 because of the album art dimensions.

Will be pushed to repo soonish

**Comment by MarshallOfSound** [comment]
In master
