### ISSUE TITLE
Update notification makes mini-player non-interactive

### ISSUE THREAD

**Issue by tyates** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1002]
**OS:**
Windows 10 (OEM/stable)

**Issue Descriptions:**
If the update notification box appears while in mini-player mode, it isn't possible to scroll the notification, close it, or get back to the full player. Music continued to play as normal. I had to quit via the system tray icon to get the app back to a state where I could interact with it/

**Steps to Reproduce:**
Obviously a little difficult for me to verify since it updated now but I would image if you install the old version and immediately put it mini-player before it does the update check, that should reproduce it.

**Comment by MarshallOfSound** [comment]
Interesting, there are a few possible behaviors I could implement here.

1. Wait to be out of the mini player before showing the update notification
2. Force the player to full size and then show the update notification

Thoughts on either?

I'm thinking the first one is the way to go, interested in opinions though

**Comment by tyates** [comment]
First option seems sensible. If I'm in mini player it means I want the app to stay out of the way and am probably not interested in messing around with updates at that moment.

**Comment by berryelectronics** [comment]
Got that same problem here. But i was able to scroll and close it, but not to update it. First option seems nice

**Comment by MarshallOfSound** [comment]
As of the latest update I verified that a new mobilish version of the modal popup is used. Hooray for third party library magical fixes.  We can minimize code usage by accepting a scrollable mobile modal
