### ISSUE TITLE
Provide native translations for GPMDP

### ISSUE THREAD

**Issue by MarshallOfSound** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1003]
I recently refactored a significant portion of the app to allow for translations.

This means that all you people in non-english countries can start using GPMDP in your native language instead of English. However, I have zero faith in Google Translate so I'm looking for volunteers to translate a bunch of strings (there are about 90 of them) into the following languages.
- [x] German (@MetalMatze)
  - [x] #1004 - Review Needed
- [x] Russian (@LuckyKort)
  - [x] #1009 - Review Needed
- [x] French (@emilecantin)
  - [ ] #1082 - Review Needed
- [x] Spanish (@n4k1)
  - [ ] #1032 - Review Needed
- [x] Dutch (@Jespiee)
  - [x] #1007 - Review Needed
- [ ] Italian (@n0f3)
- [x] Polish (@Kun2210)
  - [x] #1094 - Review Needed

If you want to translate into another language, by all means :+1: just comment below and I will add it to the list.
## Translation Instructions
1. Copy the `en-US.json` file --> [here](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/_locales/en-US.json)  
2. Look up your language locale code [here](https://developer.chrome.com/webstore/i18n#localeTable)
3. Name the new JSON file `{yourLocaleCode}.json`
4. Translate all the values in the JSON file into your language.
5. Push to GitHub and make a Pull Request

All translation PR's will need to be submitted by one person and verified by another.
## Release Process

Before each release or throughout development I will ping the volunteers here to keep the translations up to date.  So please ensure that if you volunteer to translate a language you will be able to keep translating it for a while.

**Comment by berryelectronics** [comment]
I could do the german Translation. Got some spare time tomorrow.

**Comment by MarshallOfSound** [comment]
@berryelectronics Could you simply review #1004

**Comment by n4k1** [comment]
I already started spanish translation. I'll upload for review during the day

**Comment by emilecantin** [comment]
I'm about halfway through the French one, I'll upload it soon!

One question though: What do we mean by "System Default Communications"? I can't find this string anywhere in context... (I'm on Mac)

**Comment by jostrander** [comment]
In Windows this is the default sound devcie for communication.

**Comment by n0f3** [comment]
What about Italian? I can provide translation for that language :)

**Comment by MarshallOfSound** [comment]
@n0f3 Sure, I'll add it to the list

**Comment by SolarLiner** [comment]
I went my way and created my own French translateion, without seeing that @emilecantin did one as well. I'll refrain from making my pull request in case he has his own done and if he wants to push his own.

**Comment by emilecantin** [comment]
Yeah, sorry about that, I was about 3/4 of the way through, and more pressing matters got in the way. I just completed it: #1082

@SolarLiner I believe a second set of eyes on this would be good!

**Comment by Kun2210** [comment]
@MarshallOfSound I think I can take on polish translation ;)

**Comment by jpsacheti** [comment]
I'll be working on a pt-BR translation :)

**Comment by WolfangAukang** [comment]
I can help with both Spanish and Portuguese.

**Comment by olback** [comment]
I'm working on the Swedish translation. ^

**Comment by laurentiuonac** [comment]
@MarshallOfSound I can help with the Romanian translation.

**Comment by Kun2210** [comment]
@MarshallOfSound OK, so it's been released, now how do I actually change the display language? I don't see an option in Settings :O

**Comment by MarshallOfSound** [comment]
@Kun2210 it should just read your system language and display the translations based on that

**Comment by Kun2210** [comment]
@MarshallOfSound Ouch, my company forces en-US on our OS.
Funny thing, GM-native elements in GUI are in the same language as Chrome - as I can set Chrome to use Polish as a UI language, I right now have GM-native strings in Polish, and those GPMDP-native are still in English, as my OS is in English.

**Comment by jostrander** [comment]
We should have an option to grab the language string from the HTML tag in
the web view. That would solve this type of problem.

**Comment by SolarLiner** [comment]
Windows 10 set in French, however the GPMDP strings are still displayed in English. A drop down in the settings would indeed be better.

**Comment by MarshallOfSound** [comment]
@SolarLiner The french PR was not merged, I don't think it was updated so French is not available

**Comment by Kun2210** [comment]
@MarshallOfSound @jostrander Is there any way I can force GPMDP to use specific display language?

**Comment by MarshallOfSound** [comment]
Not currently

**Comment by Kun2210** [comment]
@MarshallOfSound couldn't we identify the language by the GM-native elements instead of using OS language? That way we can have consistent translations throughout the app. Not sure if this is exactly what @jostrander suggested (not sure what web-view is in this case).

**Comment by jostrander** [comment]
That's exactly what I was suggesting @Kun2210.

**Comment by laurentiuonac** [comment]
@MarshallOfSound I can help with the Romanian translation.

**Comment by RedDragonx** [comment]
I can help you with the Vietnamese translation if you want to.

**Comment by ja-som** [comment]
I'm working on Slovak translation, I´ll send pull request soon ;)

**Comment by ja-som** [comment]
Hi, when will my Slovak translation available in your app? I have v3.5.0, the JSON file is in \GPMDP_3\app-3.5.0\resources\app\build\_locales, but app has still English language.

Thanks

**Comment by MarshallOfSound** [comment]
@ja-som The app detects your system language.  Maybe you used the wrong language code in your PR?

**Comment by ja-som** [comment]
@MarshallOfSound thanks, Slovak language has code "sk", so I used sk-SK.

**Comment by MarshallOfSound** [comment]
@ja-som Looks like the language code is just `sk`

**Comment by ja-som** [comment]
@MarshallOfSound yes, you´re right, I also figured it right now, I tried to rename the JSON file only to "sk.json" (new pull request sent), the settings window is now in Slovak, but the whole menu in the tray icon is still in English, I also tried to restart the app few times.

**Comment by vskochko** [comment]
@MarshallOfSound  I want to help with Ukrainian translation!

**Comment by Animakozak** [comment]
@vskochko me too 😄

**Comment by MarshallOfSound** [comment]
@vskochko @Animakozak Just send a PR 👍

**Comment by ihiroaki** [comment]
Please, add Czech lng. :) I already have *.json file :)

**Comment by MarshallOfSound** [comment]
@ihiroaki Just end a PR 👍

**Comment by GoodWillN1** [comment]
I can verify the Czech translation once it is up (once ihiroaki does the PR).

**Comment by WolfangAukang** [comment]
Do you still need reviewing for Spanish?

**Comment by jony0008** [comment]
@MarshallOfSound I want to help with Swedish translation!

**Comment by LuShoARG** [comment]
Hello everyone, I am a user of GPMDP, I speak Spanish and I would like to be able to contribute to the translation of this incredible software into Spanish. If this is possible, please give me an answer. Greetings from Argentina
