### ISSUE TITLE
Need to kill GPM via task manager after using "Reset & Close application" button.

### ISSUE THREAD

**Issue by szeichorn** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#101]
This isn't a big issue, but when using the "Reset & Close application" button, I needed to find GPM in the task manager & kill it before GPMDP would open again.
[screencaps](http://www.gfycat.com/ConstantUnacceptableLamprey)

**Comment by MarshallOfSound** [comment]
I think I'm just going to remove this button altogether, not very useful and far too much hassle
