### ISSUE TITLE
New icon in tray looks bad

### ISSUE THREAD

**Issue by Nxt3** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1010]
**OS: OSX 10.11.3**

**Issue Descriptions: See attached screenshot**

![screen shot 2016-05-01 at 12 32 59 pm](https://cloud.githubusercontent.com/assets/2940826/14942898/edc374cc-0f98-11e6-8cd1-b0b63a09c634.png)

I think it should just be the Dorito logo instead of the Dorito and vinyl track.

**Comment by berryelectronics** [comment]
Maybe switch to the [GPM Favicon](http://puu.sh/oDKZ0/78190777bc.png) would be a neat idea

**Comment by MarshallOfSound** [comment]
@berryelectronics I like that idea.  For use when someone or I do this

```html
<svg viewBox="0 0 24 24" preserveAspectRatio="xMidYMid meet" class="style-scope iron-icon" style="pointer-events: none; display: block; width: 64px; height: 64px;"><g class="style-scope iron-icon">
  <path d="M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10 10-4.5 10-10S17.5 2 12 2zm3 7.6h-1.8v4.9c0 1.1-1.1 2-2.2 2s-2-.9-2-2 .9-2 2-2c.4 0 .7.1 1 .3V7.5h3v2.1z" class="style-scope iron-icon"></path>
</g></svg>
```

That is the vector code for the GPM Favicon

**Comment by berryelectronics** [comment]
@MarshallOfSound [How it should look on MacOS](http://puu.sh/oEXF5/fa680e8eff.png) and  [Look of it in Windows](http://puu.sh/oEXAV/965ddda7eb.jpg) (thought would be better to change it across all platforms. But i can leave that out if you want.

**Comment by berryelectronics** [comment]
#1027 Got it. Guess we could call it a day
