### ISSUE TITLE
Equalizer not found - OSX

### ISSUE THREAD

**Issue by erikcgarneau** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1011]
Unable to locate equalizer in OSX, I noticed the issue had been previously reported and closed although I still can't find the feature.

**Comment by MarshallOfSound** [comment]
If you read the issue that it was originally reported in

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/419

You can see why you can't find it, it's still disabled pending an Upstream bugfix
