### ISSUE TITLE
Left Windows and Right Ctrl/Alt/Windows keys not supported in shortcuts

### ISSUE THREAD

**Issue by lf-** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1013]
**OS:** Windows 10

**Issue Descriptions:** Shortcuts using the Windows (super) key, nor right alt/ctrl/windows are supported. This would be pretty tremendously useful for avoiding conflict with other apps while defining global shortcuts.

**Steps to Reproduce:** Attempt to use right alt/ctrl/windows key in a shortcut.

**Comment by jostrander** [comment]
This is detailed in #413, and that is the parent issue for all things hotkey related.

**Comment by MarshallOfSound** [comment]
As @jostrander mentioned.  The super for these issues is #413
