### ISSUE TITLE
Websocket API playState renamed

### ISSUE THREAD

**Issue by LoKaDah** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1014]
The websocket channel playState seems to have been replaced after the initial connect with a channel named "state" that performs the same function and is not listed on the API.

**Comment by MarshallOfSound** [comment]
@LoKaDah This appears to be a regression from an attempt at simplifying the WebSocket API code.  I'm going to split this issue into multiple parts and move it to a super.
