### ISSUE TITLE
Last.FM login issue on Windows

### ISSUE THREAD

**Issue by speedyxvn** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1016]
****OS:**
**
Windows 7 x64

****Issue Descriptions**:
**
After clicking Last.FM login button, status changes to "Authorization in progress" and the button says "..." without anything else. No login page opens.

****Steps to reproduce**:
**
Open app 
Go to settings
Click log in to Last.fFm

**Comment by MarshallOfSound** [comment]
Are you running on master?  Or a release version?

**Comment by speedyxvn** [comment]
Latest release version. 3.2.4.

**Comment by MarshallOfSound** [comment]
Do you have a VPN or a proxy?

**Comment by MarshallOfSound** [comment]
Closing this in favor of #921

**Comment by speedyxvn** [comment]
Indeed, proxy was present.
