### ISSUE TITLE
Feature request: Track info in the system tray icon's tooltip

### ISSUE THREAD

**Issue by Jura** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1018]
**OS:** Windows

**Issue Descriptions:** It would be nice to have current track info (song title, album/artist) in the tooltip for the GPMDP icon in the system tray (currently showing only app name):

![image](https://cloud.githubusercontent.com/assets/417604/14961844/e274db0c-1069-11e6-9e8e-131655f36493.png)

**Comment by berryelectronics** [comment]
Like that idea

Would be as easy as to just change 'appIcon.setToolTip("Google Play Music");' into 'appIcon.setToolTip("Google Play Music" + "\n" + "Title" + "\n" + "Artist");' only gotta find a easy way to parse those.

I might do it if @MarshallOfSound doesnt has anything against it and if i find some spare time

**Comment by jostrander** [comment]
You might be able to use code from my hidden window titles PR.

**Comment by Jura** [comment]
@MarshallOfSound, is this part of 3.2.5 release? In this case it hasn't been fixed - there is no tooltip at all on Windows 10 x64

**Comment by jostrander** [comment]
This is probably another regression that came with 3.2.5. The code is there for this to work in 3.2.4 and 3.2.5, but weird bugs have surfaced with 3.2.5 causing numerous things to not work properly. Should be fixed in 3.3.0.

**Comment by MarshallOfSound** [comment]
@Jura @jostrander No this was not part of `3.2.5`

Important to remember that `3.2.5` DID NOT CONTAIN ANY NEW FEATURES.  It was purely a reverse patch to apply a critical commit to `3.2.4`.

New features like this will arrive in `3.3.0` as has always been indicated.  This project follows semver so new features will result in a minor version bump.

**Comment by jostrander** [comment]
I was aware, I thought this feature was implemented before 3.2.4, but
apparently not.

**Comment by MarshallOfSound** [comment]
@jostrander Commit was May 3rd, release was May 1st 😆 

Close but not close enough
