### ISSUE TITLE
Many errors when starting `google-play-music-desktop-player `, blank screen

### ISSUE THREAD

**Issue by certik** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1020]
**OS:**

Ubuntu 16.04, I installed `google-play-music-desktop-player_3.2.4_amd64.deb`.

**Issue Descriptions:**

```
$ google-play-music-desktop-player
error: ################### !! Update server down !! ##################
Failed to encode dictionary
Failed to encode reply value
Failed to encode dictionary
Failed to encode reply value
```

and the screen is empty. No login, nothing. I don't know how it is supposed to look like, but it looks like something broke.

**Steps to Reproduce:**

Run `google-play-music-desktop-player ` from the terminal.

**Comment by jostrander** [comment]
Have you tried starting with `--disable-gpu`? The update server error I haven't seen on Ubuntu, but wouldn't matter because there's no auto updating on that platform. The encode lines are junk printed by the node-dbus module.

**Comment by MarshallOfSound** [comment]
```js
error: ################### !! Update server down !! ##################
```

That error is interesting as the update server is DEFINITELY not down.  Can you try going to https://update.gpmdp.xyz/api/versions

Also do you use a proxy or a VPN?

**Comment by certik** [comment]
I am behind a proxy. The http_proxy and https_proxy environment variables
are set properly though. I will try the website tomorrow.

**Comment by MarshallOfSound** [comment]
@certik Running `electron` applications behind a proxy requires you pass in the command line parameter

`--proxy-server="socks5://localhost:8089"`

Just ensure that the socks5 URL is correct for your system.

**Comment by certik** [comment]
@MarshallOfSound Thanks! I didn't realize that. I'll try it tomorrow and report back.

**Comment by MarshallOfSound** [comment]
@certik All good, not many people do.

**Comment by certik** [comment]
@MarshallOfSound is that a rowing boat on your profile photo? I used to row competitively.

**Comment by certik** [comment]
Ok, so I tried this on a laptop not behind a proxy and everything works, the music page loads etc.

However, when behind the proxy, it won't work. We don't have a socks5 proxy, just a regular http proxy. I tried the `--proxy-server`, but the output is exactly the same as I reported above, and a blank window.

**Comment by certik** [comment]
Got it working, by using: `google-play-music-desktop-player --proxy-server="proxy.xxx.xx:8080"`. Not using the `socks5://` prefix. It now connects properly.

**Comment by certik** [comment]
I spoke too soon. I see the login screen, but when I try to login, the terminal prints one more time:
```
error: ################### !! Update server down !! ##################
```
and the window becomes blank again... I assume that the `--proxy-server` setting is not honored by the whole application, just parts of it?

Either way, it looks like broken to me behind a proxy.

**Comment by MarshallOfSound** [comment]
The login screen issue is in the FAQ

On linux you need to run the program with the `--disable-gpu` flag

**Comment by certik** [comment]
Now it works! Thanks a lot. For reference, here is how to get it working in Ubuntu 16.04 behind a proxy:
```
google-play-music-desktop-player --proxy-server="proxy.xxx.xx:8080" --disable-gpu
```

**Comment by MarshallOfSound** [comment]
@certik Can you add this to the FAQ please :+1:
