### ISSUE TITLE
Feature request: Pandora support

### ISSUE THREAD

**Issue by tigre7575** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1022]
Just wondering if Pandora support might be added. Thanks for the awesome program.

**Comment by jostrander** [comment]
Pandora is out of the scope of this particular project, however maybe another project could tackle implementing Pandora the same way @MarshallOfSound did here.

**Comment by MarshallOfSound** [comment]
@tigre7575 As @jostrander said, supported another media service is well out of scope for this project.  Feel free to use the code as a starting point for make a separate program for Pandora though :+1:
