### ISSUE TITLE
No documentation on how to open GPM Url's from the app menu

### ISSUE THREAD

**Issue by kerber** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1024]
**OS:**
Windows 7
**Issue Descriptions:**
Unable to open GPM Url's from the app menu. This feature was listed in Version 3.1.0 release notes, but I cannot figure out how to use it. It would be excellent for opening links shared from other GPM users.

**Comment by MarshallOfSound** [comment]
"Control + Shift + G"

There will be a help link in the next version

**Comment by kerber** [comment]
Thank you!
