### ISSUE TITLE
Inspect webview tag content in electron

### ISSUE THREAD

**Issue by MCManuelLP** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1025]
So, currently I haven't found a way to inspect the actual play.google.com page directly in the application, I know it is in theory possible but currently there seems to be no obvious way to access it...  
I'm not sure if it's possible to make a special shortcut to open a popup(?) to `chrome://inspect` to be able to inspect the content of the webview tag as described in this doc page https://developer.chrome.com/apps/tags/webview

**Comment by MarshallOfSound** [comment]
Open devtools for the main application and run the following in console

```js
document.querySelector('webview').openDevTools();
```
