### ISSUE TITLE
MiniPlayer unmovable

### ISSUE THREAD

**Issue by softfruit** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1026]
When in mini player format the mini player can go outside of screen bounds and none of the windows shortcuts can bring it back. (in my case dual screening a 4k display and a not-4k)

win+arrow
minimize
maximize etc

nothing works.
only way to get it back is to uninstall and reinstall so it revers to normal player.

a.k.a I cannot miniPlayer on my computer or it disappears and cannot be returned...

**Comment by berryelectronics** [comment]
Maybe a tray option to maximize it (or on a specific screen if multiple are in use) would be helpful. Generally i find the behavior of the mini player bit strange. It can be arranged at the top right and left with windows + arrows, but not to the bottom
