### ISSUE TITLE
Maintain ordering of "Songs" view

### ISSUE THREAD

**Issue by AlecRobertson** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1029]
On the "Songs" tab, I like to order the songs by Artist and hence I choose this option. When changing tabs or closing the app though, the setup is lost and I have to set it up again. Is there anyway to add an option to maintain ordering on the "Songs" view?

**Comment by MarshallOfSound** [comment]
This is the kind of thing that Google should probably fix on their end.  I'll leave it open to think about it but at the moment I feel as though this is a feature that Google should be implementing
