### ISSUE TITLE
Javascript errors + can't open program

### ISSUE THREAD

**Issue by kaceycalhoon** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1030]
**OS:** Windows 10 Pro 64bit

**Issue Descriptions:** Player used to work fine, errored out with Javascript messages and crashed, has refused to reopen for a month now. Restarted computer, uninstalled Windows Updates, deleted & reinstalled player, etc. no fix. Trying to open now results in this: http://i.imgur.com/PixdcEE.png

**Steps to Reproduce:**

Don't know what caused it but it happened out of the blue, I left the app open overnight and came back, played Graduation by Kanye West and it started erroring but continued working, crashed and then wouldn't work anymore.

**Comment by jostrander** [comment]
Looks like your settings file is corrupt, maybe try deleting it and restarting the app?

**Comment by kaceycalhoon** [comment]
where is the settings file located?

**Comment by jostrander** [comment]
I was trying to recall, but it's either in `%appdata%` or `%localappdata%` and then under `GPMDP_3` or `Google Play Music Desktop Player` and its called .settings.json

**Comment by MarshallOfSound** [comment]
I've had enough of these issues, I'll try patch this with a bunch of `try { .. } catch { .. } `
