### ISSUE TITLE
Javascript error + cannot open 'Desktop Settings'

### ISSUE THREAD

**Issue by rgavs** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1031]
**OS:** Archlinux 64 bit

**Issue Descriptions:** Upon attempting to open, receive the following error message: [link](http://bit.ly/1rvPQt4). I have been building directly from Github, alternately with `npm run build` and `gulp package:linux:64` and have tried both, It is up to date with commits as of **05/04/16 22:47**. It runs fine aside from the error message, and not allowing the `Desktop Settings` window to popup.

It had been running fine until I believe earlier today. Due mostly to the recency, I wonder if it is related to #1030, and as suggested there I did delete the `settings.json` and also the entire containing directory just to see if it would have any effect.

**Comment by jostrander** [comment]
Uh, try running `npm install` again, you have a missing module.

**Comment by rgavs** [comment]
Ok yeah that did it. Just wondering is that due to a module being added that I needed to update for? Should  I be rerunning `npm install` before each build? And you can close, thanks.

**Comment by jostrander** [comment]
If you are doing it automatically, yes, if not I would check the commit log for any updates to package.json first.

**Comment by MarshallOfSound** [comment]
@rgavs As of latest there is a module `pre-flight` that should warn you when you run `npm start` that you are missing dependencies.

**Comment by rgavs** [comment]
Sorry if this has been addressed elsewhere, but does this mean the startup command should be `npm start` because I had been directly using the executable `dist/*x84/Google\ Play\ Music\ Desktop\ Player` without issue until this issue came up

**Comment by jostrander** [comment]
If you are packaging it every time you should just run npm install before
packaging, which should fix any module issues with the dist/ executables.
Otherwise if you are developing run npm start.
