### ISSUE TITLE
Audio device resets to default when enabling particles

### ISSUE THREAD

**Issue by kacgal** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1035]
**OS:** Windows 10 

**Issue Descriptions:** Audio device resets to default when enabling particles

**Steps to Reproduce:**
1. Set audio device to any but the default
2. Play a song
3. Enable particles visualizer (bottom left corner)
4. Music starts playing through the default audio device

**Comment by MarshallOfSound** [comment]
This is a bug caused by Google Play Music.  When you start the particle visualizer, it seizes control of the audio element from me.  There is nothing I can do about this, it just claims it so my code no longer affects it.
