### ISSUE TITLE
Player stopped showing up at all.

### ISSUE THREAD

**Issue by cartersteven** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1036]
**OS:**
Mac OSX 10.11.14
**Issue Descriptions:**
Player window is not showing up at all. In the screenshots the app is playing. Only controls are on the tray. I have tried reinstalling, and I have tried using the show button on the tray.
**Steps to Reproduce:**
I can't make the issue stop, so I cannot reproduce it.
<img width="1440" alt="screen shot 2016-05-05 at 5 24 44 pm" src="https://cloud.githubusercontent.com/assets/7764629/15057799/b9211ea8-12e6-11e6-9bd6-67db352d8002.png">
![screen shot 2016-05-05 at 5 24 44 pm 2](https://cloud.githubusercontent.com/assets/7764629/15057800/b9228842-12e6-11e6-95fb-95ce5db29257.png)
<img width="1440" alt="screen shot 2016-05-05 at 5 25 06 pm" src="https://cloud.githubusercontent.com/assets/7764629/15057801/b922a372-12e6-11e6-8ddc-f463f934fdf6.png">
![screen shot 2016-05-05 at 5 25 06 pm 2](https://cloud.githubusercontent.com/assets/7764629/15057802/b922c7ee-12e6-11e6-97fc-fba767a7032f.png)

**Comment by datanotion** [comment]
I'm also seeing the same issue all of a sudden.  The only thing I'm able to bring up is the settings, and it's shows as disabled.

![screen shot 2016-05-05 at 5 49 03 pm](https://cloud.githubusercontent.com/assets/4722782/15060623/ad6c0f02-12e9-11e6-80ae-169556f52a50.png)

**Comment by MarshallOfSound** [comment]
@datanotion It looks like you have glitched during an update process. Can you redownload the latest release :+1:

**Comment by datanotion** [comment]
Worked like a charm, thanks

**Comment by MarshallOfSound** [comment]
Yeah, the OS X updater is a bit temperamental, it's an upstream thing :cry:

**Comment by datanotion** [comment]
Just as an FYI, it happened again this morning.  But I somehow figured out a way to get it to show up on the screen again through a combination of using the top menu to maximize, 3 finger swipe up, then click on the restore button - that (I believe) caused it to show up as a tiny window, just large enough for me to grab an edge and restore it's size.  Hope that helps - thanks for an awesome product!
![screen shot 2016-05-06 at 9 36 01 am](https://cloud.githubusercontent.com/assets/4722782/15077959/2d7398d0-136e-11e6-8d58-78ba4707445f.png)
