### ISSUE TITLE
Blank screen after updating - Arch Linux

### ISSUE THREAD

**Issue by evenme** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1037]
**OS:** Arch Linux

**Issue Descriptions:** It was working perfectly until the last update. Yesterday I updated to last version available on AUR (3.2.4.27.g8b2d584-1 from git), after opening the app, just get a blank screen. Menu from the icon on tray works, going to desktop settings changes colors and other configurations, but nothing appear on the main window. 

Things I tried and didn't work:

- running with --disable-gpu
- deleted .config/Google Play Music Desktop Player
- deleted .cache/Google Play Music Desktop Player
- reloaded WM (Cinnamon)
- updated all packages + rebooted

All I got is a blank page attached.

![screenshot from 2016-05-06 10-40-19](https://cloud.githubusercontent.com/assets/117922/15076292/f2f7b034-1376-11e6-966f-21149d047627.png)

**Comment by MarshallOfSound** [comment]
I think you need to trigger a rebuild of the AUR package, new dependencies probably weren't fetched for the new update.

@BrianAllred might know more?

**Comment by evenme** [comment]
Already uninstalled and installed from scratch. Same blank screen.

**Comment by MarshallOfSound** [comment]
Can you launch it with the `--dev` argument and try opening the chromium dev tools to look at the error console

**Comment by evenme** [comment]
How can I do that? I don't have chromium, but chrome, but pressing F12 on the app doesn't do anything and inside the browser doesn't allow me to inspect the app.

**Comment by jostrander** [comment]
Dev tools can be opened with Ctrl Shift I, or I believe under the help menu bar you can open dev tools.

**Comment by jostrander** [comment]
Just an update to this, the dependencies for building were updated which is what is causing your issue. @BrianAllred probably hasn't had time to update the AUR package for the proper build dependencies.

**Comment by evenme** [comment]
﻿The only error showing on console is this:
/usr/share/google-play-music-desktop-player/resources/electron.asar/renderer/web-view/web-view.js:282 ::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.

And that's on the command line output:
$ google-play-music-desktop-player --disable-gpu --dev
info: Application started.
error: Last.fm API keys have not been set!
debug: Renderer process logger initialized.
debug: Renderer process logger initialized.
[27207:0506/113657:ERROR:CONSOLE(684)] "Children are longer than parent at 84594076.29 (499.308) by -2.499", source: chrome-devtools://devtools/bundled/timeline_module.js (684)

**Comment by MarshallOfSound** [comment]
@evenme Inside that console please run the following

```js
document.querySelector('webview').openDevTools()
```

Another dev tools window should appear, do any more errors appear in that one?

**Comment by evenme** [comment]
﻿Yes, that appeared on the other window:
/usr/share/google-play-music-desktop-player/resources/app/build/inject/GPMWebView/interface/pauseAfter.js:6 Uncaught ReferenceError: GPM is not defined

**Comment by MarshallOfSound** [comment]
Is that the only error :confused:

**Comment by evenme** [comment]
Unfortunately that's the only one.

**Comment by MarshallOfSound** [comment]
@evenme Do you use a proxy or VPN?

**Comment by evenme** [comment]
No, nothing.

**Comment by MarshallOfSound** [comment]
I'm going to leave this until @BrianAllred swings by, he knows more about what could have gone wrong with the AUR side of things than I do

**Comment by evenme** [comment]
I also downloaded the package directly from Github of previous versions (3.3, 3.4) and had the same behavior. My previous version was: (3.1.0.23.gbd7ca4d-1 -> 3.2.4.17.g3332fcd-1)

**Comment by BrianAllred** [comment]
Have you tried installing the [stable version](https://aur.archlinux.org/packages/gpmdp)? I'm wondering if it has something to do with the build process.

**Comment by jostrander** [comment]
Generally speaking the GPM not defined error meant something went wrong with the inclusion of modules in the pre-inject script. I noticed this error quite a bit when I was helping with the chromecast integration.

**Comment by evenme** [comment]
@BrianAllred yes, tried to uninstall git version and install stable, same problem.

**Comment by BrianAllred** [comment]
I can't get this to happen, even on a fresh Arch install in a VM. I'll continue working it, but at the moment, I'm stumped.

Some things that might be relevant for weird reasons:

- Video card
- Video driver version
- Sound card (or motherboard, if integrated)
- Audio backend and version
- Also, any non-standard make flags in your `/etc/makepkg.conf ` or anywhere else

If you can provide these, I might be able to pin the issue down, or at least narrow the search.

**Comment by evenme** [comment]
After a lot of testing, deleting folders, uninstalling, updating, trying several versions, today I opened it again and it asked my Google credentials. After a few seconds, it opened the app again and looks like everything is working again!
One thing that I noticed is the config folder (still) appears here as a weird name: 'Google Play Music Desktop Player', with the quotes. Even inside the folder, other folders also has that single quotes, probably because the folders have spaces between words. I would suggest changing spaces for dashes (-) like most of other apps (like: google-chrome). I still don't know how it's working now, since I haven't tried to open this for the past few days and were using a tab on Chrome. If I can help with identifying something, let me now (here is my config you asked anyway).

$ lspci|grep VGA
00:02.0 VGA compatible controller: Intel Corporation Broadwell-U Integrated Graphics (rev 09)
04:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Opal PRO [Radeon R7 M260] (rev ff)

I switch between Intel and AMD drivers, but they are both updated.

$ lspci|grep Audio
00:03.0 Audio device: Intel Corporation Broadwell-U Audio Controller (rev 09)
00:1b.0 Audio device: Intel Corporation Wildcat Point-LP High Definition Audio Controller (rev 03)

Using pulseaudio as backend:
pulseaudio 8.0-3
pulseaudio-alsa 2-3

/etc/makepkg.conf is default.

**Comment by jostrander** [comment]
I suppose that could be the cause of the issue, because if the folder structure is different than what GPMDP thinks it will be then the modules will fail to load and you'll be stuck with a white screen.

**Comment by evenme** [comment]
I've been using it since yesterday, it's playing, however, it takes a long time to start the app plus I get this error for many options on menu (and also on terminal if I launch from there):


An uncaught exception was reported.  
#### Info:
**OS:** linux
**Arch:** x64
**GPMDP Version:** 3.2.4
**Time:** Wed May 25 2016 10:33:35 GMT-0400 (EDT)

#### Error:
*dns service error: unknown*
```js
Error: dns service error: unknown
    at Error (native)
    at new Advertisement (/usr/share/google-play-music-desktop-player/resources/app/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/usr/share/google-play-music-desktop-player/resources/app/node_modules/mdns/lib/advertisement.js:64:10)
    at Server.<anonymous> (/usr/share/google-play-music-desktop-player/resources/app/build/main/features/core/websocketAPI.js:56:25)
    at Server.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at Server.emit (events.js:185:7)
    at emitListeningNT (net.js:1279:10)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
This issue was created automatically inside the `uncaughtException` handler

Also tried to run with --disable-gpu and it won't launch, just the loading wheel.

**Comment by hellboy1975** [comment]
Not much to add to this problem really, except that I have the same issue running on Centos 7 (albeit a black screen as I'm running the dark theme).

I've found that deleting `~/.config/Google Play Music Desktop Player/json_store/.settings.json` fixes the problem (though you lose your settings!)

**Comment by unkani** [comment]
I've got the same problem with the blank screen on load, except on Windows 8 x64.
Any tips to troubleshoot?

**Comment by MarshallOfSound** [comment]
@unkani. Do you use a VPN or a proxy?

**Comment by unkani** [comment]
Sure do. Where do I put my proxy?

**Comment by MarshallOfSound** [comment]
@unkani  https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md#--proxy-serveraddressport

**Comment by vendion** [comment]
I'm had a similar problem, I just recently installed Google Play Music Desktop Player and when I tried to sign in I would get a white screen after inputting my password, I have two factor enabled on my Google account.  When I installed this on my Mac I knew it asked for a token, but under Arch that wasn't happening.

I had to launch the application with the `--dev --disable-gpu` flags just to be able to complete the signin process.  After that launching normally works just fine.  I'm not behind a VPN or proxy and the only output when launching from the terminal is

```
error: Last.fm API keys have not been set!
*** WARNING *** The program 'Google Play Music Desktop Player' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=Google Play Music Desktop Player>
*** WARNING *** The program 'Google Play Music Desktop Player' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=Google Play Music Desktop Player&f=DNSServiceRegister>
error: Could not initialize bonjour service with error: {"errorCode":-65537}
```

OS: Arch Linux
Arch: x86_64
Kernel: 4.5.3-1
```
[vendion@Baldr][~]% lspci |  grep VGA
01:05.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] RS880 [Radeon HD 4250]
[vendion@Baldr][~]% lspci |  grep Audio
00:14.2 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] SBx00 Azalia (Intel HDA)
01:05.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] RS880 HDMI Audio [Radeon HD 4200 Series]
```

Using Pulseaudio 8.0-3 with the ALSA plugin installed.
