### ISSUE TITLE
MiniPlayer unusable after receiving 'Update Available' notification

### ISSUE THREAD

**Issue by bretthysuik** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1038]
**OS:** Windows 7 SP1

**Issue Descriptions:**

MiniPlayer becomes unusable after receiving an 'Update Available' notification while in MiniPlayer mode. 
- Can't use the song navigation controls 
- Can't switch back to normal mode
- Can't scroll the 'Update Notification' panel to start the update
- Right clicking on the tray icon and selecting 'Show' doesn't do anything
- App has to be exited and restarted and left in normal mode until the update is performed.

Here's what it looks like for me (complete with the orange border bug!)

![untitled](https://cloud.githubusercontent.com/assets/2490331/15078208/4a1ff13a-136f-11e6-81fe-3eec4a98c6e3.png)

**Steps to Reproduce:**

1. Open the app
2. Switch to MiniPlayer mode
3. Wait for an 'Update Available' notification

**Related Feature Request:**

Add a 'Show Full Mode' item in the tray icon's context menu so you can switch out of MiniPlayer mode.

**Comment by MarshallOfSound** [comment]
Duplicate #1002

**Comment by bretthysuik** [comment]
My bad, didn't do a thorough search before submitting
