### ISSUE TITLE
Mini Player controls occasionally offset

### ISSUE THREAD

**Issue by StephenBrown2** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1039]
**OS:** Arch Linux

**Issue Description:** Sometimes, when I send the player into Mini view, the controls go off to the side, so that I can't access them anymore and make it big again.
![google play music desktop player_003](https://cloud.githubusercontent.com/assets/1148665/15079096/2316fc66-137c-11e6-939a-90be64d27ee2.png)
To get around this, I kill the player and restart (often with a git pull and rebuild in between, because why not), and then it starts again as the big player. Then sending it to mini-mode is better:
![3 to 1 feat mike relm rob swift - blue man group_004](https://cloud.githubusercontent.com/assets/1148665/15079158/777842e2-137c-11e6-81ab-07f545270dd1.png)
Perhaps, if this isn't a terrible thing to fix, one could add a "Switch mode" option to the taskbar menu. I presume it might fix itself if resized, but I can't test since the mode button is out of bounds.

**Steps to Reproduce:**
1. Open GPMDP
2. Start Playing Music
3. Click the Mini mode button from the interface.
4. Mini mode controls shifted
5. Quit program from taskbar or killing the process
6. Rebuild/Restart
7. Repeat 1-3
8. Mini mode controls normal

**Comment by MarshallOfSound** [comment]
@StephenBrown2 This is an issue that was fixed a looong time ago, you must be quite out of date.  On arch things are handled differently and I don't think the script calls `npm update` correctly @BrianAllred  so you might have to reinstall to get the fixed dependencies.  I don't know :+1:

**Comment by StephenBrown2** [comment]
Yup, hadn't run npm update, ever.

Thanks for the help on gitter.

**Comment by BrianAllred** [comment]
The pkgbuild does

```
npm install
npm run build
npm run package:linux:$arch
```

Where does `npm update` need to fall in there?

**Comment by MarshallOfSound** [comment]
After `npm install`

**Comment by BrianAllred** [comment]
When I add the update command, I get the following in the terminal during a build.

```
npm ERR! Linux 4.5.2-6-lqx
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "update"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.9
npm ERR! code EBADPLATFORM

npm ERR! notsup Not compatible with your operating system or architecture: ll-keyboard-hook-win@3.0.0
npm ERR! notsup Valid OS:    win32
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     /home/brian/Documents/google-play-music-desktop-player-git/src/Google-Play-Music-Desktop-Player-UNO
[npm-debug.txt](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/253493/npm-debug.txt)

FFICIAL-/npm-debug.log
```

Looks like it's trying to build the windows keyboard hook, for some reason. Attached is the debug log.
[npm-debug.txt](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/253494/npm-debug.txt)

**Comment by MarshallOfSound** [comment]
That's a known issue I raised over at NPM

https://github.com/npm/npm/issues/11992

This might involve someone fixing that issue first :cry:

**Comment by BrianAllred** [comment]
Ah, okay. In that case, is there a way to force `npm install` to install updated dependencies? Like, if there was an uninstall command that cleaned the modules out, would the install command then grab the updated versions? Kind of a crappy solution, but it would at least be a workaround until that issue is fixed.

**Comment by StephenBrown2** [comment]
But I like running from git HEAD... ;-)

/me installs google-play-music-desktop-player-git
