### ISSUE TITLE
Taskbar song info

### ISSUE THREAD

**Issue by SicariusNoctis** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1040]
It would be nice if the titlebar contained the "Artist - Song Title" so that I could hover over it to check the current song.

![2016-05-07 02_47_50-](https://cloud.githubusercontent.com/assets/721196/15091445/5afdc812-13fe-11e6-8601-dfeb2ba1d751.png)

For comparison, here's what MusicBee does:

![2016-05-07 02_51_15-](https://cloud.githubusercontent.com/assets/721196/15091461/bb4e1316-13fe-11e6-8abb-d7d6754d4a6f.png)

**Comment by MarshallOfSound** [comment]
Always on in master.
