### ISSUE TITLE
Music keeps playing after app has been told to close.

### ISSUE THREAD

**Issue by Sp4rkR4t** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1041]
**OS:** Windows 10 x64

**Issue Descriptions:** Occasionally when closing the app while music is playing the music will continue for several seconds after the app has closed. To be clear it is only the music playback that continues the ui closes and none of the media keys can control the music.

**Steps to Reproduce:** Play music, close app, issue seems to get more pronounced the longer you have had the app open.

**Comment by MarshallOfSound** [comment]
I leave mine open for sometimes up to 24hours at a time and have never noticed this issue, can you post your computer specs *(CPU, RAM, HDD)* it could just be a slow hardware issue

**Comment by berryelectronics** [comment]
Noticed that when i worked on auto startup. it takes like 5 seconds until
the music stops. But i dont think that a FX-6100 is too slow (with 16GB of
RAM and a SSD)

Samuel Attard <notifications@github.com> schrieb am Sa., 7. Mai 2016 um
17:59 Uhr:

**Comment by MarshallOfSound** [comment]
@berryelectronics OK, so it turns out I was testing this on an older release (Had a old release installed for some reason).  When I ran latest it the issue appeared.

This is probably either a chromium or electron bug.  I'll raise it over there

**Comment by MarshallOfSound** [comment]
OK, so I quick bit of research indicates this is an HTML5 Audio bug in Chromium 49

When electron updates to Chromium 50 this will be fixed :+1:

**Comment by berryelectronics** [comment]
When will is the next release going to be? After the electron update or when you finished the chromecast implementation?

**Comment by MarshallOfSound** [comment]
Who knows :smile: 

I normally release every few weeks and there's quite a way to go yet :+1:
