### ISSUE TITLE
Feature Request: Hotkey to bring the Player up

### ISSUE THREAD

**Issue by berryelectronics** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1042]
How about a Hotkey Setting to bring the player to the front. It kinda bothers me to go to the tray, open it up and double click on the tiny icon there. Atleast I would find it helpfull, but I dont know how others think about it :)

**Comment by Gamers-Creed** [comment]
Just a suggestion: If you un-check the "minimize to tray" box in the desktop settings in the app the icon will remain on your taskbar when the app is open (I have it pinned to my taskbar), you also also get quick access to the play/pause and skip buttons with aero peek just like iTunes and spotify do.

**Comment by SicariusNoctis** [comment]
What's wrong with good old Alt-Tab? If you want to quickly skip the song, just bind a Hotkey in the Desktop Settings menu.

If you really want this behavior, there are ways of doing it with AHK which work with other software:

http://lifehacker.com/5468862/create-a-shortcut-key-for-restoring-a-specific-window

(You'll probably need to bind it to the executable path of GPMDP, rather than window title.)

**Comment by MarshallOfSound** [comment]
What @SicariusNoctis has said makes sense, I can't think of another program that uses a hotkey to bring to the foreground.  It isn't a common design pattern.

**Comment by chadbaum** [comment]
Came here to request the same thing but saw this post already.  For what it's worth, this functionality is what I expect from all of my native desktop experiences.  It is the big thing missing from using a hybrid experience like this one.  While I have play/pause and next song bound to my mouse, I find it highly useful to have a quick shortcut to activate the music player window if I want to dive in further.  This is much easier than sorting through my active windows open or virtual desktops.

For reference, Foobar and MusicPlayer both support this feature as standard keybindings.  Without it, I'm less productive, especially given all the rewards for interacting with GPM vs your own offline music (station/music discovery).

Anyway, good app, makes GPM bearable for me, but I hope you reconsider this feature request in the future.  Thanks!

**Comment by SicariusNoctis** [comment]
As I mentioned earlier, you can use AutoHotKey. Install AHK, plug the following code into a .ahk file, right click and compile it, then create a shortcut to your .exe in your Start Menu's `Startup` directory.

```
ToggleWinMinimize(WindowTitle)
{
	SetTitleMatchMode,2
	DetectHiddenWindows, Off

	IfWinActive, %WindowTitle%
	{
		WinMinimize, %WindowTitle%
	}
	Else
	{
		IfWinExist, %WindowTitle%
		{
			WinGet, winid, ID, %WindowTitle%
			DllCall("SwitchToThisWindow", "UInt", winid, "UInt", 1)
		}
	}

	Return
}

; Ctrl + Alt + G to toggle
^!g::ToggleWinMinimize("ahk_exe Google Play Music Desktop Player.exe")
```

Modifiers are given as follows:

```
^ Ctrl
! Alt
+ Shift
# Win
```

You can do this with any number of programs.
