### ISSUE TITLE
SetPoint Compatability?

### ISSUE THREAD

**Issue by Gamers-Creed** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1043]
OS: Windows 7

I checked the FAQ before posting this and recognise that you have stated that we have to disable SetPoint, I can confirm that this does work but unfortunately SetPoint is extremely useful with the mouse that I am using.

My Media keys work fine with other players such as iTunes with SetPoint running.

Is there a possibility that in the near future media keys will work alongside SetPoint?
Is this something you are already working on or could consider?

My Keyboard: Logitech K520

**Comment by MarshallOfSound** [comment]
Unfortunately there is nothing I can do at my end, SetPoint only outputs media key presses for specific applications.  This is documented for players such as [MediaMonkey](http://www.mediamonkey.com/support/index.php?/Knowledgebase/Article/View/49/2/multimedia-keyboard-buttons-dont-work)

Unless logitech add this application to there list or you add it to the list manually SetPoint will continue to break our media keys.

**Comment by Gamers-Creed** [comment]
I appreciate the reply, is there any chance you know how to add it to the list manually?

**Comment by MarshallOfSound** [comment]
@Gamers-Creed Unfortunately I don't have a logitech keyboard so I can't test with different configs.  If you google around a bit though I think there is a generic tutorial that explains how to do it

**Comment by Steinerd** [comment]
NOTE: This solution's implementation is entirely at your own volition, the Google Play Desktop Player dev team nor I (which I'm not a part of) take no responsibility for any issues that may arise.  This is a solution that worked for a single scenario and my not work for you. 

@Gamers-Creed  Add these to your _**C:\Program Files\Logitech\SetPointP\players.ini**_ file.
```ini
[Players]
GPMDP=key,Google%20Play%20Music%20Desktop%20Player.exe,Chrome_WidgetWin_1,xxx,xxx,&0xB3,&0xB3,&0xB2,&0xB1,&0xB0,0,1,GPMDP

[Players.Display]
GPMDP=Google Music Play Desktop Player
```

You'll also need to add some paths to your registry: (You can save this to a file and save it as a .reg and merge it... AT YOUR OWN RISK)  
```
Windows Registry Editor Version 5.00

; The following registry inputs App Path in the registry for the Google Play Music Desktop Player - http://www.googleplaymusicdesktopplayer.com
;  Due to the nature of the REG_EXPAND_SZ properties we're importing, they'll need to be in hex. The clear-text version looks as follows...  
;	@="%APPDATA%\Microsoft\Windows\Start Menu\Programs\Samuel Attard\Google Play Music Desktop Player.lnk"
;	Path="%userprofile%\AppData\Local\GPMDP_3\"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\Google%20Play%20Music%20Desktop%20Player.exe]
@=hex(2):22,00,25,00,41,00,50,00,50,00,44,00,41,00,54,00,41,00,25,00,5c,00,4d,\
  00,69,00,63,00,72,00,6f,00,73,00,6f,00,66,00,74,00,5c,00,57,00,69,00,6e,00,\
  64,00,6f,00,77,00,73,00,5c,00,53,00,74,00,61,00,72,00,74,00,20,00,4d,00,65,\
  00,6e,00,75,00,5c,00,50,00,72,00,6f,00,67,00,72,00,61,00,6d,00,73,00,5c,00,\
  53,00,61,00,6d,00,75,00,65,00,6c,00,20,00,41,00,74,00,74,00,61,00,72,00,64,\
  00,5c,00,47,00,6f,00,6f,00,67,00,6c,00,65,00,20,00,50,00,6c,00,61,00,79,00,\
  20,00,4d,00,75,00,73,00,69,00,63,00,20,00,44,00,65,00,73,00,6b,00,74,00,6f,\
  00,70,00,20,00,50,00,6c,00,61,00,79,00,65,00,72,00,2e,00,6c,00,6e,00,6b,00,\
  22,00,00,00
"Path"=hex(2):22,00,25,00,75,00,73,00,65,00,72,00,70,00,72,00,6f,00,66,00,69,\
  00,6c,00,65,00,25,00,5c,00,41,00,70,00,70,00,44,00,61,00,74,00,61,00,5c,00,\
  4c,00,6f,00,63,00,61,00,6c,00,5c,00,47,00,50,00,4d,00,44,00,50,00,5f,00,33,\
  00,5c,00,22,00,00,00
  
  
[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\App Paths\Google%20Play%20Music%20Desktop%20Player.exe]
@=hex(2):22,00,25,00,41,00,50,00,50,00,44,00,41,00,54,00,41,00,25,00,5c,00,4d,\
  00,69,00,63,00,72,00,6f,00,73,00,6f,00,66,00,74,00,5c,00,57,00,69,00,6e,00,\
  64,00,6f,00,77,00,73,00,5c,00,53,00,74,00,61,00,72,00,74,00,20,00,4d,00,65,\
  00,6e,00,75,00,5c,00,50,00,72,00,6f,00,67,00,72,00,61,00,6d,00,73,00,5c,00,\
  53,00,61,00,6d,00,75,00,65,00,6c,00,20,00,41,00,74,00,74,00,61,00,72,00,64,\
  00,5c,00,47,00,6f,00,6f,00,67,00,6c,00,65,00,20,00,50,00,6c,00,61,00,79,00,\
  20,00,4d,00,75,00,73,00,69,00,63,00,20,00,44,00,65,00,73,00,6b,00,74,00,6f,\
  00,70,00,20,00,50,00,6c,00,61,00,79,00,65,00,72,00,2e,00,6c,00,6e,00,6b,00,\
  22,00,00,00
"Path"=hex(2):22,00,25,00,75,00,73,00,65,00,72,00,70,00,72,00,6f,00,66,00,69,\
  00,6c,00,65,00,25,00,5c,00,41,00,70,00,70,00,44,00,61,00,74,00,61,00,5c,00,\
  4c,00,6f,00,63,00,61,00,6c,00,5c,00,47,00,50,00,4d,00,44,00,50,00,5f,00,33,\
  00,5c,00,22,00,00,00
  
```

Exit the SetPoint program and reload it.  Go to your keyboard settings, find the hotkey/function key for your Media Player, Google Music Play Desktop Player should on the list, click apply,   You should now be able to open the player from the hotkey as well as use the prev, play, skip.  I have not figured out seek and have no intentions to.
