### ISSUE TITLE
Uncaught Exception: dns service error: unknown

### ISSUE THREAD

**Issue by misterjupiter** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1048]
An uncaught exception was reported.  
#### Info:
**OS:** linux
**Arch:** x64
**GPMDP Version:** 3.2.4
**Time:** Sun May 08 2016 16:28:50 GMT 0200 (CEST)

#### Error:
*dns service error: unknown*
```js
Error: dns service error: unknown
    at Error (native)
    at new Advertisement (/usr/share/google-play-music-desktop-player/resources/app/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/usr/share/google-play-music-desktop-player/resources/app/node_modules/mdns/lib/advertisement.js:64:10)
    at enableAPI (/usr/share/google-play-music-desktop-player/resources/app/build/main/features/core/websocketAPI.js:60:25)
    at Object.<anonymous> (/usr/share/google-play-music-desktop-player/resources/app/build/main/features/core/websocketAPI.js:142:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by jostrander** [comment]
@marshallofsound looks we have some errors to catch :+1:

**Comment by MarshallOfSound** [comment]
@jostrander This is actually related to f4dc0847f41751484172c01f35a7f9bc795db44f

Not sure what actually causes this error though, I think it is because the user's machine needs `libavahi-compat-libdnssd-dev` installed on linux.  On windows and OS X the Bonjour headers are compiled into the application, apparently not on linux.

Personally however this does bring up an underlying issue, people running unstable versions of the client and raising these automatic issues.  We need to either stop people raising them or mark them in the application as running an **unsigned** or **unstable** version.

**Comment by jostrander** [comment]
Can we set the version to the current hash with a git hook, and in CI set the version to the tag number if its available? I hadn't realized you had built in zeroconf with mdns. On Linux you are right the headers are needed separately for most packages.

**Comment by misterjupiter** [comment]
The error occured on my Arch-Linux machine. Installing the avahi-package seems to fix the issue. I installed the google-play-music-desktop-player-git package from the AUR. I wrote on the AUR about the missing dependency, so the the package manager can update the build script.

**Comment by jostrander** [comment]
Thanks @misterjupiter, @BrianAllred is usually good about updating dependencies when he knows about them, but sometimes we sneak new dependencies in without notifying him.. :8ball:

**Comment by MarshallOfSound** [comment]
We enjoy keeping @BrianAllred on his toes :+1: 

To be honest though, it's a new experience having non-project devs running latest master.  It's a bit dodgy IMO still not sure how I feel about it, but apparently it's an arch thing :laughing:

**Comment by BrianAllred** [comment]
Yeah, I try to stay up-to-date on commits, but I totally missed that one. Package is updated now, though! :D
