### ISSUE TITLE
Bug: Snap feature fails in the mini player when using multiple Virtual Desktops

### ISSUE THREAD

**Issue by berryelectronics** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1051]
Win10 x64

When using multiple virtual desktops and trying to snap the mini player onto the right side on the first desktop it wont get the borders right. The anchor point of the mini player doesnt seem to be correct. [This results into the player being of the screen](http://puu.sh/oKHoC/4bad862772.jpg)

Steps to reproduce:
-Create at least two virtual desktops
-move the mini player onto the first desktop
-press win+right arrow so it "snaps" to the right side

Also what i noticed: You cant snap it in the lower corner. It just snaps to the upper right or upper left. When pressing win+up it moves the player into its normal position (cant maximize it). When pressing win+down doesnt do anything if its already snapped, not moving to the lower corner or into the tray. It only moves to the tray if it isnt snapped

**Comment by MarshallOfSound** [comment]
The snapping bug is an issue with WIndows itself not handling windows with a maximum size correctly.

The anchor point issue can't be produced on my Windows 10 machine running the latest insider preview so I'm putting that down to a Windows bug that will be fixed soon in the mainstream channels
