### ISSUE TITLE
Feature Request:  Google Play Connect

### ISSUE THREAD

**Issue by maxideus** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1052]
This is a long shot request, but I used this feature quite a bit in Spotify (called Spotify Connect), so I just wanted to ask. 

Is there a feature in the road map to include connecting a smart phone (using a Google Play compatible app) to compatible devices (like my PC or Laptop with Google Play Music Desktop Player installed).  Connecting my phone to these available devices (via an app) will allow me to use my phone as a remote controller.  

It's a long shot but would be a very cool feature for a future added functionality.

Thank you for the great app.

**Comment by jostrander** [comment]
There is someone building an app for this based on the WebSocket API. There
was an open Issue from the developer a while back about it but I don't
think his app is published yet.

**Comment by maxideus** [comment]
Thank you Jesse, that's great news that someone's developing this feature.  Do you know if the project has a name or a Github?  How can I follow the progress of this app?

**Comment by jostrander** [comment]
Here is the GitHub project https://github.com/mmazzarolo/google-play-music-desktop-remote

**Comment by MarshallOfSound** [comment]
@maxideus This won't be something officially supported by this repository, it is however the main reason we provide the JSON and WebSocket API's.  So that someone else can do this :+1: 

Please track this request on the repository @jostrander mentioned :grin:
