### ISSUE TITLE
Turning on "Particles" changes non-Default audio output

### ISSUE THREAD

**Issue by mcow** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1053]
**OS:** 64-bit Windows 7 Home Premium

**Issue Descriptions:** With non-default music device, if the Particles display is selected while playing, the music stops playing on the non-default device and cuts over to the default (e.g. now on desktop speakers instead of thru stereo DAC).

**Steps to Reproduce:**
1) Set up to play to non-default music device. (Thanks so much for making this an option.) Play music. Yay, it's playing on stereo.
2) Poke around the UI, see that hovering over the album art of what's playing gives a "Particles" option. Select it. Boo, music is no longer on the stereo, but coming thru mediocre desktop speakers.
3) Exit the Particles display so I can see the options. Look at the options: non-default selection is still selected. Try changing selection there, and changing it back. no effect.
4) Quit program, restart: audio option still set to non-default, and it plays again through the stereo.

**Comment by MarshallOfSound** [comment]
Duplicate #1035
