### ISSUE TITLE
Last.fm logged out after update

### ISSUE THREAD

**Issue by niekp** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1054]
After an update last.fm scrobbling was logged out. This is the second time it happend to me.
It happend on windows 10 and on a macbook. 

I'm not sure it's related too the update, but that seems logical since both times there was an update the day before.

If it's not possible too keep the login can you display a notification? That way users don't find out a couple days later when checking last.fm

**Comment by MarshallOfSound** [comment]
That last.fm API is the most dodgy API I have ever used.  Unfortunately there is no real way to "check" if the key I have still works with your account until I try to send a request, and sending a request might actually work so I don't want to send bad data.

Also a user could manually revoke our key from the settings page so asking for access again would be a bit dodgy :+1: 

The best I can say is.  *Sorry about last.fm's API, it shouldn't happen too often*
