### ISSUE TITLE
Javascript error at installation

### ISSUE THREAD

**Issue by povovo** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1055]
**OS:**
Windows 10

**Issue Descriptions:**
First of all, thanks for an awesome application! I've been using it for a couple of months and it's been working great. However during an update a couple of weeks (or so) ago it stopped working. I can't remember exactly what happened, but I uninstalled it and tried to do a fresh install instead, and now whenever I try to do that, I get the splash screen saying it's installing and this will show for maybe 15 seconds then suddenly I get a popup alert window saying exactly this:

A JavaScript error occured in the main process
Uncaught Exception:
SyntaxError: Unexpected token

I have tried both the 32 and 64-bit versions and it happens with both of them.

**Steps to Reproduce:**
1. Uninstall application.
2 Try to install application.

**Comment by povovo** [comment]
Actually it seems like it might be that starting the application is the problem rathern than installing it (I'm guessing it tries to auto-launch once the installation is complete). Because it seems like it gets installed (I have it in the start menu) and when I try to launch it I get this popup javascript error. I can also see that there are 2 background processes running (which keeps running even after I click ok on the popup error).

**Comment by MarshallOfSound** [comment]
Please navigate to the install directory and delete the `json_storage` folder.  It should fix the error

**Comment by povovo** [comment]
I can't find any such directory. It looks like the entire application is located in C:\Users\<myuser>\AppData\Local\GPMDP_3 (let me know if this is wrong) but I can't find a directory with that name anywhere in there.

**Comment by berryelectronics** [comment]
There are multiple folders of GPMDP in the appdata (i think 3 folders). You
have to delete all of them and then it should work again

povovo <notifications@github.com> schrieb am Mi., 11. Mai 2016, 09:21:

**Comment by povovo** [comment]
I found another one in the Roaming directory and deleted it and now it works! Thanks a bunch!
