### ISSUE TITLE
Improve the menu bar icon on the Mac

### ISSUE THREAD

**Issue by danielandrews** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1056]
The icon isn't the best on the Mac.  Maybe just remove the top 'lump' on the play icon?

**OS:**

Mac OS X 10.11.4

**Issue Descriptions:**

The menubar icon looks 'wrong':

https://www.dropbox.com/s/tgau0wlu8w1thd3/Screenshot%202016-05-09%2009.04.10.png?dl=0

**Steps to Reproduce:**

Open the application on Mac
View the menu bar icon
It looks like a black "blob" that matches the new icon.

**Comment by MarshallOfSound** [comment]
This has been fixed on master.  This is a duplicate issue
