### ISSUE TITLE
Upload music feature broken

### ISSUE THREAD

**Issue by ccolorado** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1059]
**OS:**
Archlinux

**Issue Descriptions:**
There seems to be a partial support for uploading music
**Steps to Reproduce:**
Go to Settings > Musif from this computer > Add your music
You get requested to install the google chrome app and there is no way to exit out of the "feature" without closing the client. 

I wouldn't have an issue installing from the browser but it also requires the google play app.
If I understood correctly this app is required NOT to be insalled if one want's keyboard shortcuts to work.

**Comment by MarshallOfSound** [comment]
There is 0 support for upload, there shouldn't even be a button / way to start it?

**Comment by ccolorado** [comment]
Sorry, accidentally hit enter when entering the title. This posted the issue, when it wasn't yet ready to post it.

**Comment by BrianAllred** [comment]
You should be able to go to Play Music, open the side menu, hit Upload Music, and then drag and drop music without installing the Chrome app.

**Comment by jostrander** [comment]
Afaik the extension is what does the client side conversion to mp3 from
whatever format you drag in so technically you would need it in order to
upload music. However I haven't uploaded any music since the first upload
client they released for Windows so YMMV.

**Comment by MarshallOfSound** [comment]
@all 

Uploading is not supported due to another obfuscated extension which is a pain to replicate.  The button to which @ccolorado refers to "Upload Music" should be hidden and is hidden on my client and all clients I have tested with.

I'm going to put this down to a strange GPM UI glitch that gave @ccolorado access to a page I attempt to block
