### ISSUE TITLE
CefSharp and Gma

### ISSUE THREAD

**Issue by iskenxan** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#106]
How do install CefSharp and Gma libraries? I tried installing CefSharp.Common package but it's not the one program is asking for. Thanks

**Comment by MarshallOfSound** [comment]
I'm assuming you're trying to get developer tools working?  If you are using Visual Studio just go to "Manage Nuget Packages" in the tools menu, and click "Restore All Packages"

**Comment by iskenxan** [comment]
I am trying to compile Google Play Music project from the solution , I did as you said but CefSharp library is still missing, I am getting an error on line "using CefSharp" in CoreMusicApp.cs

**Comment by MarshallOfSound** [comment]
Once you have restored nuget packages you may have to close VS2015 and reopen it.  Also if you installed the wrong version by accident you might have to delete / uninstall that version before the correct ones can be fetched from Nuget

**Comment by iskenxan** [comment]
I am using 2013, but yeah restarting visual studio solved that problem, thanks for quick response

**Comment by amaitland** [comment]
> Once you have restored nuget packages you may have to close VS2015 and reopen it.

If you migrate to `Automatic Package Restore` then this will no longer be necessary :smile: 

https://docs.nuget.org/consume/package-restore/migrating-to-automatic-package-restore
