### ISSUE TITLE
LastFM scrobbles aren't properly recorded when using Repeat 1

### ISSUE THREAD

**Issue by gricha2380** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1061]
**OS:**
10.11.3

**Issue Descriptions:**
When tracks from the Music library are played on loop ("Repeat 1"), only the initial play is recorded on LastFM.

**Steps to Reproduce:**

_Prerequisite: Ensure that LastFM scrobbling is enabled in Settings_

1. Navigate to Music Library
2. Play any owned track
3. Press Repeat icon twice (to active Repeat 1 functionality)

**Comment by jostrander** [comment]
I'm guessing that the Repeat 1 functionality doesn't fire a song changed event which is required in order to scrobble. Quite an interesting problem as it would require a check if the song position has moved from its end point back to the beginning in another event. @MarshallOfSound thoughts?

**Comment by gricha2380** [comment]
For some of us scrobblers accurate play count tracking is treated with a religious stringency. If I fail to report all my Repeat 1 plays to LastFM I'd have to, you know, listen to a day's worth of Justin Beiber as repentances or something.

**Comment by jostrander** [comment]
_If you put it on Repeat 1 it'd look like you only listened to one song... heh_ :laughing: 

In all serious, there might be an easy fix for this or their might not be, but either way it wouldn't be available until the next release anyway.

**Comment by MCManuelLP** [comment]
If there is an easy fix, I just want to add that 'pause after this song' would benefit from that too, as it doesn't work on repeat 1 either.  
I never thought about testing that but it's not worth opening another issue now.

**Comment by MCManuelLP** [comment]
As another solution we could remove the `song changed` event and add two new events instead:

 - `song started`: fired when time is 0
 - `song ended`: fired when time is song length

That might fix some latency issues with pause after too...

**Comment by MarshallOfSound** [comment]
It's early and I haven't put much thought into this yet but initial reaction 

>remove the song changed event and add two new events instead:

> song started: fired when time is 0
> song ended: fired when time is song length

This is not going to happen, too many thing rely on `change` not duplicating

It should however be as simply as combing `change:time` with `change:song` and doing some fancy math :+1:
