### ISSUE TITLE
[Linux] Ubuntu notifications stack

### ISSUE THREAD

**Issue by Zeyckler** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1063]
**OS:**
Ubuntu 16.04

**Issue Descriptions:**
I found an issue, but I don't know if is a problem about Ubuntu notifications instead of the app. The bug/issue that I found is that if you skip songs several times, you are going to see one notification per every song that you skipped, so if you skip 5 songs, you are going to see one by one, until every notification animation is completed (a few seconds), so you don't see the song that you are playing while the previous notifications are gone.

**Steps to Reproduce:**
Skip songs several times

**Comment by jostrander** [comment]
I agree, but both electron and Ubuntu are to blame for this if I'm not mistaken. However I do believe there was a bug fix being pushed via electron that would allow for "tagging" of the notification so matching tags would stack. I'll see if I can find the issue on electrons side.

**Comment by MarshallOfSound** [comment]
I have Ubuntu 16.04 and am not experiencing this on latest (With electron `1.0.1`).  I think something was fixed somewhere :thought_balloon:
