### ISSUE TITLE
Windows 7 32 bit - where is the desktop shortcut?

### ISSUE THREAD

**Issue by djigscott** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1068]
I had no problems installing the program on the windows 10 machine, but my work laptop is windows 7 based & when I go through the installation process it installs fine, but I have no shortcut to the program to reload when the system shuts down. I've checked in the usually locations and no luck. It seems that I have to reinstall the program every time the computer shuts down. Any chance someone could point me the right direction?

**OS:**

**Issue Descriptions:**

**Steps to Reproduce:**

**Comment by berryelectronics** [comment]
Although i cant help you with the problem why there isnt a shortcut, but the installation folder of GPMDP is under%appdata%\..\Local\GPMMD_3

**Comment by jostrander** [comment]
Is this a work managed computer? Do you have anything set up that might be preserving the state of %appdata% or %localappdata%?

**Comment by BrianAllred** [comment]
This is anecdotal, but having worked IT professionally in the past, I'd bet money that his work set it up to sandbox one or both of those folders, wiping changes on boot.

**Comment by MarshallOfSound** [comment]
I can confirm the comments above, your work laptop is almost certainly resetting / deleting unrecognized appdata directory folders.  You'll have to talk to your IT department about getting it whitelisted :+1:
