### ISSUE TITLE
Network-based remote control, like Clementine.

### ISSUE THREAD

**Issue by digitalextremist** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1069]
A network-based remote similar to this, or even based on this code, would be amazing:

* https://github.com/clementine-player/Android-Remote/wiki
* https://play.google.com/store/apps/details?id=de.qspool.clementineremote

**Comment by MarshallOfSound** [comment]
See our PlaybackAPI and a WIP remote control

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/docs/PlaybackAPI_WebSocket.md

https://github.com/mmazzarolo/google-play-music-desktop-remote
