### ISSUE TITLE
Ubuntu Repo

### ISSUE THREAD

**Issue by beli3ver** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1072]
Hi, 

is it ok, when I great a Ubuntu Repo for that wonderful piece of software?

Thanks for your work.

**Comment by MarshallOfSound** [comment]
@beli3ver As far as I am aware, (assuming you are referring to a PPA) it is not currently possible with electron.  Launchpad requires you build from source, and that is too much to ask for when it comes to customized electron builds

**Comment by beli3ver** [comment]
Ok Thanks for the answer
