### ISSUE TITLE
"Update Available" Message won't go away

### ISSUE THREAD

**Issue by juschu** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1075]
When the "Update Available" message shows up, in most cases I choose to restart later.
But when I do that 15 or 20 seconds later the message shows up again. No matter how often I click on "Not rigth now" it always shows up after 15 or 20 seconds.
I'm running Windows 10.

**Comment by MarshallOfSound** [comment]
The ironic thing is.  This issue was fixed.  In the update :laughing:
