### ISSUE TITLE
Feature Request: Add to Playlist from Mini Player

### ISSUE THREAD

**Issue by DAI479** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1076]
Be great to have a button to allow to **Add to Playlist** somewhere on the **Mini Player** that way you wouldn't have to jump back to the big player to do it.

Thanks for a great program! I love it!

**Comment by MarshallOfSound** [comment]
I'm going through a mini player redesign at the moment.  And unfortunately this is currently impossible due to the way GPM internally handles playlists.
