### ISSUE TITLE
JavaScript error when starting the programm without admin rights

### ISSUE THREAD

**Issue by sausau** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1077]
**OS: Windows 7

**Issue Descriptions: I can´t start the programm since 5 days. every time i want to start it i get the following error. It only happens when i want to start it as normal non-admin-rights-user. as admin it works. 

![unbenannt](https://cloud.githubusercontent.com/assets/6482506/15268249/d1598d7c-19d8-11e6-8c2f-3930ef7305cd.PNG)

**Comment by MarshallOfSound** [comment]
Please go to

```
%APPDATA%\Google Play Music Desktop Player\json_store
```

And delete the `.settings.json` file.  This issue has been fixed in master

**Comment by sausau** [comment]
thank you!
