### ISSUE TITLE
Error notification on switching back to GPMDP from another window. Did not exist in previous versions.

### ISSUE THREAD

**Issue by aakash94** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1079]
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.1
**Time:** Sun May 15 2016 14:24:35 GMT 0530 (India Standard Time)

#### Error:
*Attempting to call a function in a renderer window that has been closed or released. Function provid*
```js
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: Object.<anonymous> (C:\Users\THIS-PC\AppData\Local\GPMDP_3\app-3.0.1\resources\app\build\inject\GPMInject\interface\mouseButtonNavigation.js:8:8.
    at BrowserWindow.callIntoRenderer (C:\Users\THIS-PC\AppData\Local\GPMDP_3\app-3.0.1\resources\atom.asar\browser\lib\rpc-server.js:201:19)
    at emitTwo (events.js:92:20)
    at BrowserWindow.emit (events.js:172:7)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
Mate, you are so far out of date it's not even funny.

The latest version is `3.2.4`.  Please update and this issue will stop

**Comment by aakash94** [comment]
funny thing, because I just updated it 2 hours back when it notified me to do so.
Anyways, thanks for pointing it out. will fix it.
