### ISSUE TITLE
Uncaught Exception: DNSServiceRef is not initialized

### ISSUE THREAD

**Issue by chrisfilo** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1088]
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.2.4
**Time:** Tue May 17 2016 13:14:42 GMT-0700 (Pacific Daylight Time)

#### Error:
*DNSServiceRef is not initialized*
```js
Error: DNSServiceRef is not initialized
    at Error (native)
    at supportsInterfaceIndexLocalOnly (C:\Users\filo\AppData\Local\GPMDP_3\app-3.2.4\resources\app\node_modules\mdns\lib\avahi.js:28:10)
    at Object.<anonymous> (C:\Users\filo\AppData\Local\GPMDP_3\app-3.2.4\resources\app\node_modules\mdns\lib\avahi.js:32:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by jostrander** [comment]
That's a new one...

**Comment by MarshallOfSound** [comment]
@chrisfilo We do not currently have a release that uses `mdns`.  What are you currently running?

Is it a custom build from master?

**Comment by MarshallOfSound** [comment]
Also @jostrander it looks like this error is because Bonjour isn't installed on the users machine.  We'll probably have to detect this and ask them to install it.

I just spun up a VM on azure to test this and it definitely looks like we need to somehow install Bonjour during the install process

**Comment by MarshallOfSound** [comment]
Actually @jostrander I think we should move away from the `mdns` library completely.  And switch to using this https://www.npmjs.com/package/bonjour

It is an entirely JS implementation of the bonjour standards.  This means no install and no native dependencies are required.

**Comment by jostrander** [comment]
As long as it works I'm okay with switching. mDNS seems like a native dependency nightmare anyway.

**Comment by chrisfilo** [comment]
I'm on the bleeding edge of Windows 10 Insider Preview edition. Hence the
problems. I'll try installing bonjour

**Comment by MarshallOfSound** [comment]
Our current implementation is fixed.  We can discuss moving to `bonjour` (the JS package) somewhere else :+1:
