### ISSUE TITLE
Mac - Window is nonexistent or tiny

### ISSUE THREAD

**Issue by Smashman** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1089]
**OS:** Mac OSX - El Capitain

**Issue Descriptions:**
When opening the player, the window is randomly nonexistent. I can make the player Full screen which works, but then when undoing fullscreen, the player disappears again. When showing all app windows, a tiny circle is highlighted, with the player's name beneath.

**Steps to Reproduce:**
Open the player once, quit the player. The player is then no longer visible until next restart.

**Comment by Smashman** [comment]
Fixed by quitting when in fullscreen.

**Comment by Smashman** [comment]
This issue is still present. A workaround exists, but it's not ideal.

**Comment by MarshallOfSound** [comment]
> randomly nonexistent

This isn't very helpful when trying to replicate the issue.

1. Are you using a custom window manager
2. What **specifically** are you doing when it *"randomly"* becomes nonexistent
3. Do you have any secondary screens?

**Comment by Smashman** [comment]
Annoyingly I cannot reproduce the issue at the moment.

It seemed to occur when I quit while an audio stream was playing. A beachball came up and then when next opening, the window was 'nonexistent'.

Apologies for the vague issue, I just cannot get it to reproduce reliably, hence the 'randomly'.

**Comment by maltejanosch** [comment]
I have the exact same issue. I've figured out the workaround by myself, but there seems to be no other way than going into full screen and then cmd+q-ing the app.

The reproducing worked for me. If I play a song and cmd-q it, the window disappears after I open it again. 

Are you guys using a external screen?
