### ISSUE TITLE
Unrecoverable crash, JavaScript token error

### ISSUE THREAD

**Issue by PuffShr1k3** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1090]
**OS:** Windows 10 1511
**Version:** 3.2.4

**Issue Descriptions:**
2 days ago, when I clicked play on a song, and as soon as it started playing, the audio hitched, and my PC immediately restarted. I tried relaunching GPMDP after it started again, though it threw the following error:
![2016-05-18](https://cloud.githubusercontent.com/assets/19437394/15373782/7c602926-1d47-11e6-89c3-fe92c0480dd5.png)
Any further attempts to open it give me no error, but it will simply not launch. I tried installing it again, but it only throws that error once more.

Any idea how I can get this working again please? Let me know if I can submit any further information.

**Comment by berryelectronics** [comment]
press win + r and enter `%appdata%\..\Local` and press ok. there you delete the GPMDP folder.
now press win + r again and enter `%appdata%\..\Roaming` and press ok. here you delete the Google play music desktop player folder. now you can reinstall it and it should work again

**Comment by MarshallOfSound** [comment]
@PuffShr1k3 Simply navigate to `%APPDATA%\Google Play Music Desktop Player\json_store` and delete the `.settings.json` file. 

Then the app should start.  This issue will be fixed in the latest release
