### ISSUE TITLE
Add Forward navigation button

### ISSUE THREAD

**Issue by enda7** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1092]
Feature request:
A small thing, but it would be nice to have a Forward navigation button - it's one thing lacking compared the browser player. And while I'm at it, the Back button isn't in the most intuitive location.

Other than that, great program. Keep up the good work!

**Comment by MarshallOfSound** [comment]
The back button and the potential of a forward button has been discussed in other places (other issues and Gitter)

UI wise adding a forward button is not as simple as one would hope.  (Google hasn't exactly left a "forward button" sized gap in their player layout.

You can go forward and back using standard OS shortcuts.  E.g. on windows you can use (Alt + Left/Right)
