### ISSUE TITLE
[Linux] White Screen logging in

### ISSUE THREAD

**Issue by niklasben** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1093]
**OS:** Linux Mint 17.3 "Rosa" - KDE (64 Bit)

**Issue Descriptions:**
White Screen while trying to Log-In with Linux like mentioned in the [FAQ](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ#i-am-part-of-the-glorious-linux-master-race-and-it-doesnt-go-past-the-sign-in-screen)  
**Steps to Reproduce:**
Starting the App via Terminal using `google-play-music-desktop-player --disable-gpu`
Removing and re-installing didn't help, same Issue occurs.

I tried it also on Linux Mint 17.2 (32 Bit) it works fine there.

**Comment by MarshallOfSound** [comment]
I'm going merge this into the "white screen on linux" issue over at #1037
