### ISSUE TITLE
Mac: menu bar icon

### ISSUE THREAD

**Issue by mattburton** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1096]
**OS:** OSX 10.11.5 (El Capitan)

**Issue Descriptions:** Just a minor thing - the menu bar icon shows up as just a black blob unfortunately:

![screen shot 2016-05-19 at 3 18 47 pm](https://cloud.githubusercontent.com/assets/42413/15406648/54d41a3c-1dd5-11e6-8c4f-42aa0978e554.png)

**Steps to Reproduce:** Open app, observe icon in menu bar. Happens on both Retina display (2x) as well as non-Retina external monitor (1x)

Love the app - thanks for all the hard work!

**Comment by berryelectronics** [comment]
fixed in master. should be in the next release

**Comment by mattburton** [comment]
Awesome - thanks!
