### ISSUE TITLE
Google Play Music.exe signed as TR/Spy.Gen by Avira

### ISSUE THREAD

**Issue by Darsh911** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#11]
https://www.virustotal.com/en/file/89b2cfbc6e49a7941d36ec1dfbfa8000e7824a15426469ec65358f54f07f2472/analysis/1445943964/

**Comment by MarshallOfSound** [comment]
I have no idea how to fix that, I can guaruntee it is not a virus though.  I'll look into that false positive and see if I can fix it.

It might be something to do with the global keypress listeners

**Comment by MarshallOfSound** [comment]
I believe the offending line is https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/Google%20Play%20Music/globalKeyboardHook.cs#L167

I really don't think this is possible to fix, I'll keep looking

**Comment by MarshallOfSound** [comment]
To clarify for anyone reading this in the future.  `TR/Spy.Gen` indicates that a global low level keyboard hook has been identified which is synonomous whith keyloggers.  Anyone interested can view the source code in `globalKeyboardHook.cs` to see what it is doing.

An example of another program with a similiar issue is "AutoHotkey" [Virus Total](https://www.virustotal.com/en/file/f2c600d3467713ae433153f9b7f268c1a5f7653316abf9f9992276b808e44411/analysis/)

I'm going to close this issue as it is an invalid issue report (The supposed "virus" is a false positive)

**Comment by MarshallOfSound** [comment]
Further investigation has isolated the issue as being a combination of the the update checker and the keyboard hooks.  Disabling either one removes the virus false positive.  Looking for work arounds

**Comment by MarshallOfSound** [comment]
@Darsh911 Good news, this false positive will be fixed in the next release.  The issue (strange as it sounds) was related to a JSON deserializing library

**Comment by MarshallOfSound** [comment]
Update for anyone in the future.  The new scan link is here https://www.virustotal.com/en/file/1c9987f7733a92e3cd9a3af05c2d52fe2687f9c2fa12fb9cf2174a1fb0132804/analysis/1446505072/

Showing 0 detections...

**Comment by Darsh911** [comment]
@MarshallOfSound thank you. Keep up the good work!

**Comment by DecoyJoe** [comment]
FYI, Looks like Windows Defender might be suspicious of the player.

![Screenshot](https://cloud.githubusercontent.com/assets/4836970/11402381/70a17412-934c-11e5-8827-351c09aa9468.JPG)

**Comment by MarshallOfSound** [comment]
Oh god, not another one....  I'll look into this one, although I think it is related to the installer being unsigned
