### ISSUE TITLE
Unable to add track to 'Favorites' playlist from the 'Currently Playing' bar.

### ISSUE THREAD

**Issue by MartialDiplomacy** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1101]
- I have checked that there are no issues with similar or the same content.
- I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there.
- I have double checked and can reproduce the issue.

**OS:** Windows 10 64bit

**Issue Description:** The option to add the currently playing track to your favorites playlist disappears upon opening the menu.

**Steps to Reproduce:** https://www.youtube.com/watch?v=LiRtrjBwfM8

**Comment by Evanito** [comment]
I experience this too, when playing music from <My playlist> radio, I am unable to add songs to <My playlist> even though I'm in the radio variant and the song itself is not present in the playlist.

**Comment by MarshallOfSound** [comment]
Thanks for the solid bug report.  Fix incoming
