### ISSUE TITLE
Feature Request: Crossfade

### ISSUE THREAD

**Issue by darrenswhite** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1103]
It would be amazing to have an option to crossfade songs (much like Spotify already has). This would allow for gapless playback and possibly allow to change how long the fade lasts.

**Comment by MarshallOfSound** [comment]
Unfortunately due to the way GPM works internally "crossfade" and "gapless playback" are currently impossible.  These features would have to be implemented on Googles side of things
