### ISSUE TITLE
Feature Request: Uploading Music

### ISSUE THREAD

**Issue by dbitter2** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1104]
Hey,

One of the main reasons I use Google Play Music over other streaming services is the ability to upload my own music so that I can stream it later. Currently there is no support for uploading music from GPMDP. Is this something that could be implemented?

**Comment by jostrander** [comment]
Unfortunately it's not possible within the app currently. The chrome extension that allows uploading isn't easy to port as it has quite a bit of obfuscated code and even some native modules that would be near impossible to port into this and/or rewrite.

**Comment by MarshallOfSound** [comment]
As @jostrander not feasible at the current moment in time.

Duplicate #1059
