### ISSUE TITLE
Same CPU as Google Chrome.... I think 

### ISSUE THREAD

**Issue by christianbearslyclark** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1106]
I really LOVE thus app !!!!  The best app ever for Google Music.

.... as I am watching the CPU....... the app makes the CPU go up as 75 celsius.

Kinda odd ???

**Comment by Steinerd** [comment]
That's because it is Chrome.  It's just wrapped in a native shell.

**Comment by christianbearslyclark** [comment]
Oh !  That's explains it of why it works so good ha ha
