### ISSUE TITLE
Voice commands not working on OS X

### ISSUE THREAD

**Issue by Mimmels** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1109]
I'm using a 2015 Macbook Pro 13 inch. The voice commands don't work, and I checked the box in the settings. I'm using OS X El Capitan 10.11.5, the newest update. 
Steps to recreate: 
- Open app
- check box 'Enable Voice Controls'
- Say voice commands

Thanks in advance! Really like your app though, besides the little problem. 

Emile

**Comment by MarshallOfSound** [comment]
Unfortunately the Voice Commands are hit and miss, it is a severely limited API and Google appear to randomly reject requests to it.

The best I can suggest is to keep trying.  There's a reason it says "Beta" next to the setting to turn it on and off :+1:

**Comment by Jonasori** [comment]
Any updates to this? This would be really amazing feature to have if you could get it to work! Still, I get that it's probably beyond your control. 

Great player, by the way!
