### ISSUE TITLE
nothing happens after build

### ISSUE THREAD

**Issue by Talor-A** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#111]
Hi, I first tried a fork of this project and uninstalled it because I wanted to use the master one here instead. The first worked fine, but attempting to reinstall isn't working. Visual Studio builds successfully, but the player isn't installed in either Program Files\ or Program Files(x86)\. Is there a step I'm missing? executing the Google Play Music in the bin\x86\ folder inside the project doesn't do anything either. I'm on Windows 10 x64.

**Comment by MarshallOfSound** [comment]
Couple of things
* The `master` branch is not guarunteed to be stable in any way
* Building in visual studio does not create an installer
* Running `Google Play Music Desktop Player.exe` in the output folder of Visual Studio *should* run it

If it doesn't I would reccomend clicking "run" in Visual Studio and choose to run in debug mode, that should give you more information

**Comment by Talor-A** [comment]
At one point, I did get an installer. It created a shortcut on my desktop,
too. I'll try debug mode.
On Mon, Dec 28, 2015 at 9:04 PM Samuel Attard <notifications@github.com>
wrote:

> Couple of things
>
>    - The master branch is not guarunteed to be stable in any way
>    - Building in visual studio does not create an installer
>    - Running Google Play Music Desktop Player.exe in the output folder of
>    Visual Studio *should* run it
>
> If it doesn't I would reccomend clicking "run" in Visual Studio and choose
> to run in debug mode, that should give you more information
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/111#issuecomment-167719503>
> .
>
-- 

-Talor

**Comment by MarshallOfSound** [comment]
Unless you have pulled my WIX installer branch I have no idea where your "installer" came from?  Let me know how debug mode goes :+1:

**Comment by Talor-A** [comment]
the installer was using @jogleasonjr's fork on the master branch. 

On running debug mode, a NuGet package Manager popup opens and runs. 
Then sometime during the build process the Github Desktop client crashes and restarts (probably unrelated). 
Then I get this error.
![screenshot 3](https://cloud.githubusercontent.com/assets/11509865/12031143/6ebf2f5a-adbd-11e5-901c-e1987031daee.png)
after clicking OK, the console output looks like this:

`<'Google Play Music.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Cannot find or open the PDB file.
'Google Play Music.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\taand\Documents\GitHub\Google-Play-Music-Desktop-Player-UNOFFICIAL-\Google Play Music\bin\x86\Release\Google Play Music.exe'. Symbols loaded.
'Google Play Music.exe' (CLR v4.0.30319: Google Play Music.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll'. Cannot find or open the PDB file.
'Google Play Music.exe' (CLR v4.0.30319: Google Play Music.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Cannot find or open the PDB file.
'Google Play Music.exe' (CLR v4.0.30319: Google Play Music.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll'. Cannot find or open the PDB file.
'Google Play Music.exe' (CLR v4.0.30319: Google Play Music.exe): Loaded 'C:\Users\taand\Documents\GitHub\Google-Play-Music-Desktop-Player-UNOFFICIAL-\Google Play Music\bin\x86\Release\MaterialSkin.dll'. Symbols loaded.
'Google Play Music.exe' (CLR v4.0.30319: Google Play Music.exe): Loaded 'C:\Users\taand\Documents\GitHub\Google-Play-Music-Desktop-Player-UNOFFICIAL-\Google Play Music\bin\x86\Release\System.Threading.Tasks.dll'. Cannot find or open the PDB file.
'Google Play Music.exe' (CLR v4.0.30319: Google Play Music.exe): Loaded 'C:\Users\taand\Documents\GitHub\Google-Play-Music-Desktop-Player-UNOFFICIAL-\Google Play Music\bin\x86\Release\Microsoft.Threading.Tasks.dll'. Cannot find or open the PDB file.
'Google Play Music.exe' (CLR v4.0.30319: Google Play Music.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Cannot find or open the PDB file.
The program '[39080] Google Play Music.exe' has exited with code 0 (0x0).>`

It's a sucessful build but Google Play Music.exe in \bin\x86\Release\ does nothing when run.

**Comment by MarshallOfSound** [comment]
Something is glitched somewhere
Can you try just wiping the lot and cloning from scratch?

**Comment by Talor-A** [comment]
I have, unfortunately. I suppose I'll try reinstalling Visual Studio later. I wonder if it's related to the mysterious installer. Weird.

**Comment by MarshallOfSound** [comment]
I'm about to push a whole bunch of stuff to master so I'd say wipe out your local, reinstall VS2015, fetch nuget packages and then try running

**Comment by MarshallOfSound** [comment]
Closing this for now as it does not appear to be an issue with the app rather a dev environment setup issue

**Comment by Talor-A** [comment]
Fixed.
