### ISSUE TITLE
Can't launch after update [Linux, Debian 64-bit]

### ISSUE THREAD

**Issue by timothymichaelclark** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1110]
Haven't been able to launch the player after update. I can run it as sudo, but not as a normal user. Here's the output running from the command line (home path omitted due to work / corp policy).

:~/.config$ google-play-music-desktop-player
A JavaScript error occurred in the main process
Uncaught Exception:
Error: EPERM: operation not permitted, chmod '[path to home]/.config/Google Play Music Desktop Player/json_store/playback.json'
    at Error (native)
    at Object.fs.chmodSync (fs.js:1055:18)
    at new PlaybackAPI (/usr/share/google-play-music-desktop-player/resources/app/build/main/utils/PlaybackAPI.js:34:20)
    at /usr/share/google-play-music-desktop-player/resources/app/build/index.js:107:24
    at Object.<anonymous> (/usr/share/google-play-music-desktop-player/resources/app/build/index.js:188:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Object.<anonymous> (/usr/share/google-play-music-desktop-player/resources/electron.asar/browser/init.js:184:8)

How can I resolve this?

**Comment by jostrander** [comment]
Run `tough '~/.config/Google Play Music Desktop Player/json_store/playback.json'`. The json API was turned off in a recent commit by default so the file is probably missing and another portion of the code is still trying to fix permissions on it. So until the patch that command should fix it.

**Comment by timothymichaelclark** [comment]
Hmm. That didn't resolve it.

As a workaround, I'm ok with running sudo for the time being until the patch.

**Comment by jostrander** [comment]
Did the file already exist? What were the permissions and ownership? The only chmod in that file is a 777.. If you ran it at sudo at some point it may be possible that file has the wrong permissions for an unprivileged user to do a chmod on it.

**Comment by timothymichaelclark** [comment]
Not sure if the file existed.

I had 777'ed the path leading to the file trying to debug it. I think the folders were 700 before that. 

The file is 777 right now.

**Comment by jostrander** [comment]
Hmm.. what about ownership?

**Comment by timothymichaelclark** [comment]
Ahh, I do not own playback.json, but I do own the folders leading to it. Should I chown it?

**Comment by mikicis** [comment]
I have the same problem on Windows 10 32-bit.  First, when the player was opened, it showed some toast saying to check github, now i can't open it receiving the same message as @timothymichaelclark

**Comment by timothymichaelclark** [comment]
FYI - chowning playback.json got me around the issue.

Thanks for the help @jostrander

**Comment by MarshallOfSound** [comment]
@timothymichaelclark It sounds like you changed some file system permissions or initially ran the app as `sudo` or `root`?

@mikicis That is a separate problem, basically your settings file (`'.settings.json'`) is corrupt (for whatever reason).  You just need to go delete it at

```
%APPDATA%\Google Play Music Desktop Player\json_store
```
