### ISSUE TITLE
Adding last.fm auth status/button to the player

### ISSUE THREAD

**Issue by rlevarski** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1112]
**OS:** 
Windows 10

**Issue Descriptions:**
Since I don't check last.fm as often as I used to, it sometimes happens that I'm left without scrobbles for days after an update - I just lose my auth token with last.fm and have to reauth. Since this thing usually goes unnoticed - I have to check on either last.fm or manually in settings, I am making a proposal, to add a last.fm status / button / indicator / something minimalistic, just so we know we're currently logged in and authorized on last.fm. Somewhere, I dunno, near our picture or whatever, just so we know when to reauth again if something goes bleh (maybe clicking the logo pops the auth window). 

**Steps to Reproduce:**
N/A

**Comment by Marwelln** [comment]
Happened to me aswell. For no reason Last.fm scrobbling is disabled from time to time and I have to reauth. Would like to at least have a notification if I'm not authed with Last.fm.
