### ISSUE TITLE
Arch Linux: Cannot log in to Last.fm

### ISSUE THREAD

**Issue by amrhassan** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1120]
**OS:** Arch Linux

**Issue Descriptions:** Cannot log in to Last.fm

**Steps to Reproduce:**
1. Launch program
2. Go to Desktop Settings from the sidebar or notification icon
3. Go to LASTFM tab
4. Click on Log In To Last.fm
5. Text changes from "Not Authorized" to "Authorization in progress" then back to "Not authorized". No windows pop up. No error output from the program.

**Comment by jostrander** [comment]
If you're using the git build it doesn't come with Last.fm keys. You can either get some API keys yourself and build them into the application or download the stable release.

**Comment by MarshallOfSound** [comment]
What @jostrander said :+1:
