### ISSUE TITLE
Javascript error in main thread

### ISSUE THREAD

**Issue by gatlinnewhouse** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1122]
**OS:** Windows 10 64-bit

**Issue Descriptions:** Whenever I try to start the program it gives me this error message: 
![sshot-11](https://cloud.githubusercontent.com/assets/10749793/15619653/5f954f1e-240a-11e6-8334-9bf866f0def0.png)

I've tried reinstalling, and running as administrator. I'll try rebooting when my shift ends later today.

**Steps to Reproduce:** Run the program on Windows 10 64-bit

**Comment by jostrander** [comment]
Unfortunately its a super simple fix, you have to delete your `.settings.json` file from `%appdata%\Google Play Music Desktop Player\json_store`.

**Comment by gatlinnewhouse** [comment]
Sweet! Thanks, it worked!
