### ISSUE TITLE
Feature Request: Share option that functions like earlier GPM

### ISSUE THREAD

**Issue by Noctimor** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1128]
In earlier versions of Google Play Music, the "Share" option for a song included an option to share it as YouTube video, and then it'd pull up YouTube results of the song you could copy the link of, as seen here:

![previous version](http://i.kinja-img.com/gawker-media/image/upload/t_original/h30uh1oypuuvaz5ilsaa.jpg)

It'd be very nice to have that functionality again, as it was far more convenient to share this with friends than a GPM link.

**Comment by jostrander** [comment]
Huh, I guess I never realized that got removed by Google. That's unfortunate, I'll look and see if there's an easy way to implement this, but it probably will take a bit of work.

**Comment by MarshallOfSound** [comment]
@Noctimor I believe this functionality has been superseded by the YoutubeRed integration into Google Play Music.  As a YoutubeRed subscriber I have access to youtube videos for songs and there is a share button in that interface.

Closing as wontfix
