### ISSUE TITLE
I'm not sure how I got this error(uncaught exception)

### ISSUE THREAD

**Issue by jacobhilker1** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1129]
I don't know what caused this error or how to reproduce it. I was listening to Coheed and Cambria when I got this message: "An uncaught exception was reported." I'm running Windows 10 64-bit on both a Lenovo Yoga 2 Pro with a Core-i5, 120GB SSD, and 4GB of RAM and I am also running it on a custom machine with a core i5-4460, GTX 950, 8GB RAM, 1TB HDD, and 500W PSU.

#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.2.4
**Time:** Mon May 30 2016 20:22:24 GMT-0400 (Eastern Daylight Time)

#### Error:
*listen EADDRINUSE 0.0.0.0:5672*
```js
Error: listen EADDRINUSE 0.0.0.0:5672
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by jostrander** [comment]
You already have a service running on that port. (5672). Thank you for the detailed bug report, however there's already about 30 of these that have been closed, so a simple search should have sufficed.

**Comment by jostrander** [comment]
For reference: #325
