### ISSUE TITLE
Getting "Javascript error occured in the main process" Win10 x64

### ISSUE THREAD

**Issue by wesruv** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1132]
**OS:**
Win 10 x64

**Issue Descriptions:**
I've been running this app for many months (love it) and yesterday it started throwing this error:
![image](https://cloud.githubusercontent.com/assets/5607236/15678773/7aa5804c-271d-11e6-9d57-e58b02f51c8d.png)

> Error
> A Javascript error occurred in the main process
> Uncaught Exception: SyntaxError Unexpected token

Then launching to a white screen.

I uninstalled, downloaded the latest from the site, and the installer is having the same issue :sob:
It does a cool load bar thing for a few seconds and pops the error.

**Steps to Reproduce:**
I'm guessing that I'm one of the lucky few running into this... since it's not even launching I'm not sure how to provide better info for debugging :disappointed:

**Comment by jostrander** [comment]
Go ahead and delete your settings file and it should clear right up. Same solution as #1122

**Comment by MarshallOfSound** [comment]
See https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/1122

**Comment by wesruv** [comment]
Fixed it! Thanks so much!
