### ISSUE TITLE
No sound in Windows 7

### ISSUE THREAD

**Issue by roryhewitt** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1136]
**OS:**

Windows 7 Enterprise

**Issue Descriptions:**

On occasion, GPMDP runs, but no sound is output. The Windows Sound mixer (SndVol.exe) shows a blank space.

**Steps to Reproduce:**

After listening to music all day, I pause the music (but don't shut down GPMDP) and put the computer into Hibernate mode at night. The next morning, I click Play, and the track starts playing, but there is no sound. If I open the Sound mixer (SndVol.exe), there is one (sometimes 2!) blank spaces where GPMDP should be. However, unlike #974, the volume and mute bars don't work at all (i.e. they're not there, rather than just hidden by an oversized icon).

![image](https://cloud.githubusercontent.com/assets/11558891/15718168/f6caf794-27de-11e6-8719-781dc1b32256.png)

The above image shows what I mean.

I can reliably recreate it by following the steps above. Completely stopping/restarting GPMDP solves the problem.

**Comment by MarshallOfSound** [comment]
This seems like an upstream chromium bug. I'll explore

**Comment by MarshallOfSound** [comment]
Reproduced in latest release on a VM by doing stupid sleeping and resuming till it broke.

Unable to reproduce on latest master, I'm assuming an update in Electron fixed it 👍
