### ISSUE TITLE
Add full theming.

### ISSUE THREAD

**Issue by SolarPolarMan** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1137]
This would involve letting the user make custom themes by choosing each color individually. This is possible due to the [updateTheme()](https://github.com/gmusic-utils/gmusic-theme.js#customizing-the-colors) function.

**Comment by MarshallOfSound** [comment]
> This is possible due to the updateTheme() function.

I am aware of this function, I wrote that library :laughing: 

> This would involve letting the user make custom themes by choosing each color individually

This is not something I am willing to allow for a few reasons

* What's the point...  It will involve adding four extra color selectors that will simply confuse your average user.
* The default dark/light themes are enough for 99.99% of users and I'm not keen on adding new functionality that requires maintainence for the fun of it
* At the moment the player looks nice, in general, it is aesthetically appealing.  If we allow a user to customize all the colors they could make it look terrible

**Comment by SolarPolarMan** [comment]
Well thanks for considering it :P
