### ISSUE TITLE
[Bug] Double clicking on the system tray icon doesn't bring the window to focus

### ISSUE THREAD

**Issue by Marwelln** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1138]
**OS:**
Windows 10

**Issue Descriptions:**
If you double click the system tray icon the Music Player window should be focused. As it is now, double clicking does nothing.

**Steps to Reproduce:**

1. Leave Music Player open, but not focused.
2. Double click the system tray icon.

`Minimize to tray` is disabled in the settings.

If `Minimize to tray` is enabled, double clicking works.

**Comment by jostrander** [comment]
Looks like it should be easy to fix with `win.show()`. I'll see if I can't commit this up in a few.
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/main/features/core/tray.js#L93-L112
