### ISSUE TITLE
[Keyboard shortcut] Add Alt-left (Cmd-Left on Mac) for navigating back in history

### ISSUE THREAD

**Issue by oscarfroberg** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1139]
I've only tried this on Mac so don't know how it behaves on Linux/Windows Cmd-left doesn't go back in history and I'm just guessing it's the same with Alt-left. Chrome has [recently discontinued](https://bugs.chromium.org/p/chromium/issues/detail?id=608016) the use of Backspace for navigating back so this should probably be addressed.

**Comment by jostrander** [comment]
Backspace for back is implemented in our code base and isn't part of electron. As for cmd+left, someone on mac will have to try and debug/fix as I have linux/windows.

**Comment by MarshallOfSound** [comment]
> Cmd-left doesn't go back

#1001

> guessing it's the same with Alt-left

Nope, alt+left works as expected

> Backspace

We implement this ourselves anyway :+1:
