### ISSUE TITLE
Ends Session / Logs Out in Xubuntu 16.04

### ISSUE THREAD

**Issue by karpantschof** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1146]
**OS:**
xubuntu 16.04 LTS in a Gnome Fall Back Environment

**Issue Descriptions:**
Will play the initial 3-7 seconds of a song, and then randomly terminate the session and bring me back to the lightdm log in screen.

**Steps to Reproduce:**

**Comment by jostrander** [comment]
Have you tried using `--disable-gpu`? I'm thinking maybe it's causing a crash?

**Comment by karpantschof** [comment]
Yaeh, it didn't seem to make it better. Actually it might even have
rendered even more unstable
ᐧ


*PS*. Have you read my recent articles on *the Thought Leadershift*
<https://medium.com/@karpantschof/the-thought-leadershift-567088fb6a22> or *the
Community Logic Tree*
<https://medium.com/@karpantschof/the-community-logic-tree-c64a00d321c0>?


*Mail *Daniel@MfNF.dk
*Cell* +1 (202) 525-6190
*About *About.me/Karpantschof <http://about.me/Karpantschof>
*Timezone *Eastern Standard Time/EST (UTC-4)

---

**Comment by jostrander** [comment]
Can you provide any kind of system logs? Kind of hard to reproduce this without mimicking your exact setup, and I have a ton of VM's already for different distros.

**Comment by MarshallOfSound** [comment]
@karpantschof Can you please provide the logs and details @jostrander requested

**Comment by karpantschof** [comment]
This is interesting. It was Gnome that kept crashing the session, and
started also doing it without the Player running. Using KDE I don't have
issues. However, I tried removing the Player and Gnome started running
stable again. How very odd.

Screw it, I'm using KDE now. Can't live without the Player anymore!
ᐧ


*PS*. Have you read my recent articles on *the Thought Leadershift*
<https://medium.com/@karpantschof/the-thought-leadershift-567088fb6a22> or *the
Community Logic Tree*
<https://medium.com/@karpantschof/the-community-logic-tree-c64a00d321c0>?


*Mail *Daniel@MfNF.dk
*Cell* +1 (202) 525-6190
*About *About.me/Karpantschof <http://about.me/Karpantschof>
*Timezone *Eastern Standard Time/EST (UTC-4)

---

**Comment by MarshallOfSound** [comment]
Strange.  Sounds like one of this "I clicked undo then redo and now it works" tricks :laughing:

Glad to hear you got it working

**Comment by jostrander** [comment]
This could be related to dbus/mpris? It's the only thing I can think of that's gnome specific. If you have a chance and are interested in still running gnome send me the logs and I'll take a look and see if there's anything I can do to fix it, either in the player or on your machine.

**Comment by karpantschof** [comment]
actually just killed gnome entirely :-/
ᐧ


*PS*. Have you read my recent articles on *the Thought Leadershift*
<https://medium.com/@karpantschof/the-thought-leadershift-567088fb6a22> or *the
Community Logic Tree*
<https://medium.com/@karpantschof/the-community-logic-tree-c64a00d321c0>?


*Mail *Daniel@MfNF.dk
*Cell* +1 (202) 525-6190
*About *About.me/Karpantschof <http://about.me/Karpantschof>
*Timezone *Eastern Standard Time/EST (UTC-4)

---
