### ISSUE TITLE
Tiny Navigation Buttons

### ISSUE THREAD

**Issue by Talor-A** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#115]
Back & Forward buttons next to the search bar are not scaled correctly. Making the window larger fixes it, but they go back after the window is made smaller again.

![screenshot 4](https://cloud.githubusercontent.com/assets/11509865/12058959/4a09989e-af07-11e5-993f-ca625fa346c5.png)

**Comment by MarshallOfSound** [comment]
Fixed on local, will push shortly
