### ISSUE TITLE
Dark theme: too low contrast for scrollbar

### ISSUE THREAD

**Issue by arvigeus** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1153]
When using dark theme on not so bright display with large collection the scrollbar is easy to get lost because it blends with the background. Can you change it for some more distinct color? (take hint from Play Midnight for Google Play Music™ dark theme)

**Comment by MarshallOfSound** [comment]
Personally, I am proud of that issue close time 😆

**Comment by MarshallOfSound** [comment]
(I actually had this in a stash somewhere, just needed to go find it 👍 )

**Comment by arvigeus** [comment]
Thank you! This was really annoying me.
