### ISSUE TITLE
Desktop Settings renders incorrectly until loss of focus happens

### ISSUE THREAD

**Issue by James-Perkins** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1155]
**OS:**
Windows 10 Enterprise
**Issue Descriptions:**
Desktop settings renders a settings box where everything is either black or minimal UI is produced. 
**Steps to Reproduce:**
1. Open GPMDP and then navigate to desktop settings. 
2. Screen will display incorrectly. 
3. Lose focus on either GPMDP or the settings box and normality resumes. Or click until something appears on screen. and selecting another tab renders the desktop settings correctly. 
**Other Notes**
Once screen has been successfully rendered, it will continue to render until user moves to a new screen e.g New releases and tries to open desktop settings again.

**Comment by MarshallOfSound** [comment]
A number of people have tried to reproduce this on different systems.

Unfortunately no one was successful and I don't see how this is possible 😢 

The best i can suggest is to do a clean reinstall and check that your GPU drivers are up to date.
