### ISSUE TITLE
Crashing windows 10

### ISSUE THREAD

**Issue by joeathome** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1159]
Great app, but finding is crashing windows 10, has crashed 4 times now.  I looked at the dump files and each time is pointing to your app.  The error I get is IRQL_Not_Less_or _equal .  I have the dump files available if needed, but just a bit of the dump log:

IRQL_NOT_LESS_OR_EQUAL (a)
An attempt was made to access a pageable (or completely invalid) address at an
interrupt request level (IRQL) that is too high.  This is usually
caused by drivers using improper addresses.
If a kernel debugger is available get the stack backtrace.
Arguments:
Arg1: 0000000000000028, memory referenced
Arg2: 0000000000000002, IRQL
Arg3: 0000000000000000, bitfield :
	bit 0 : value 0 = read operation, 1 = write operation
	bit 3 : value 0 = not an execute operation, 1 = execute operation (only on chips which support this level of status)
Arg4: fffff802236f9f5e, address which referenced memory

Debugging Details:
------------------

TRIAGER: Could not open triage file : e:\dump_analysis\program\triage\modclass.ini, error 2

READ_ADDRESS: unable to get nt!MmSpecialPoolStart
unable to get nt!MmSpecialPoolEnd
unable to get nt!MmPagedPoolEnd
unable to get nt!MmNonPagedPoolStart
unable to get nt!MmSizeOfNonPagedPoolInBytes
 0000000000000028 

CURRENT_IRQL:  2

FAULTING_IP: 
nt!MiInsertPageInFreeOrZeroedList+1ae
fffff802`236f9f5e 4c036e28        add     r13,qword ptr [rsi+28h]

CUSTOMER_CRASH_COUNT:  1

DEFAULT_BUCKET_ID:  WIN8_DRIVER_FAULT

BUGCHECK_STR:  AV

PROCESS_NAME:  Google%20Play%

**Comment by MarshallOfSound** [comment]
`IRQL_NOT_LESS_OR_EQUAL` is a driver fault which points to this not being an issue with this program but rather an issue with the underlying framework (Electron or Chromium).

Can you raise an issue over at https://github.com/electron/electron/issues explaining the Electron crashes on Windows 10 and provide those dump files.

Thanks

**Comment by joeathome** [comment]
Thank you for the help, I will go to the link and bring up there

**Comment by joeathome** [comment]
Just an FYI, electron got back, hardware issue with memory apparently the root issue
