### ISSUE TITLE
grey boxes on top of mini player

### ISSUE THREAD

**Issue by Talor-A** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#116]
![screenshot 5](https://cloud.githubusercontent.com/assets/11509865/12059170/e839ea5c-af0a-11e5-8531-6b39c966efc8.png)
![screenshot 6](https://cloud.githubusercontent.com/assets/11509865/12059171/e849fc12-af0a-11e5-88d6-538bc1ccbb0f.png)

two grey boxes appear on top of mini player album art. happened even after reinstall.

**Comment by MarshallOfSound** [comment]
Duplicate #87
