### ISSUE TITLE
Feature Request: (Turn off) Load last page

### ISSUE THREAD

**Issue by rgavs** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1163]
# Feature Request

_Load last page_

Currently this exists as a default setting, but I'd like to instead open [Main](https://play.google.com/music/listen)
If I wasn't so inexperienced with js, I'd do it myself - I doubt there'd really be much to this new settings option

**Comment by Devo7v** [comment]
I'd like to second this feature request.  I'd like to be able to load the artists page when opening the program for the first time.  My main issue with the current implementation is that if I close the program when viewing an album, the next time I open the program it loads the last view and I cannot use the back button to navigate back up to the individual artist page or artists page.  I think being able to set the default loading page when opening the program for the first time would be very useful.

**Comment by MarshallOfSound** [comment]
If someone wants to tackle this it's super easy, you just need a Settings check here

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/inject/generic/core/webviewLoader.js#L23

**Comment by GinoF** [comment]
I ran into an issue caused by this on Windows 10.
I clicked on a Unknown Album by an Unknown Artist in my Library, and I got stuck on a blank loading screen. When re-launching the app, I hit that same loading screen. Even after a reinstall I had this issue.
I ended up fixing it by hitting Alt+Left and Alt+Right in an attempt to go back or forward in the browser.

**Comment by rgavs** [comment]
@GinoF if you do see an issue like this again, I would suggest deleting the configs; specifically the `"lastPage": ...` line in the `json_store/.settings.json` file, which is where that is set

**Comment by MarshallOfSound** [comment]
@GinoF You must have hit a really strange Google Play Music bug, because we listen for `did-fail-load` events so something strange must have been going on. 😢
