### ISSUE TITLE
Feature Request: On library Songs page, jump to song when I start typing

### ISSUE THREAD

**Issue by jakelauer** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1168]
**OS:** Windows 7

**Issue Descriptions:** In the past, other desktop music players have supported the ability to jump to items in the library by typing the start of the name. Ideally, it'd jump to songs when starting to type the name of the song. Stretch goal would be to jump to the item currently sorted (i.e. if sorting by artist, jump to artist)

**Steps to Reproduce:**
1. Go to Music Library
2. Go to Songs
3. Start typing the name of a song
4. Jump to closest song matched, keystroke by keystroke (i.e. typing "Bes" highlights "Backyard", then "Believer" then "Best Friends"

Note: I suggested this feature because multiple friends asked if Google Music could do this because they want to switch from other platforms, but wouldn't until there was a player that could handle it. Just an idea!

**Comment by jostrander** [comment]
Unfortunately the best you're probably going to find is the search bar, which has a shortcut built in. You can see the rest of the built in GPM shortcuts here:

![image](https://cloud.githubusercontent.com/assets/760989/15914370/5bb99c58-2dae-11e6-9ddf-efc7f82f9537.png)

**Comment by jakelauer** [comment]
I know that's the best that exists now, but I imagine it'd be possible to add a key listener to that page and scroll to the item in question.

**Comment by jakelauer** [comment]
Scratch that, I just looked at how it works, and yeah, I see why that might not be possible.

**Comment by MarshallOfSound** [comment]
Due to Google's helpful but annoying "partial rendering" technique.  At any one time only 32 songs are rendered on screen.  This means we have no idea what other songs are in the current view which makes this kind of search impossible.

**Comment by jakelauer** [comment]
Understandable, thanks!
