### ISSUE TITLE
Program no longer opens - JS error

### ISSUE THREAD

**Issue by krozlink** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1171]
**OS:**
Windows 10 Home 64-bit

**Issue Descriptions:**
When I try to open the player I get the below error dialog box. The process continues to run but the screen never appears.
"A Javascript error occurred in the main process"
Uncaught Exception:
Syntax Error: Unexpected Token

**Steps to Reproduce:**
Happens every time I try to open the program. Have uninstalled/reinstalled with the latest version. 
The last time I used the program succesfully I linked my last.fm account.

**Comment by MarshallOfSound** [comment]
Delete the settings file found at

`%APPDATA%/Google Play Music Desktop Player/json_store`
