### ISSUE TITLE
Issues installing/running

### ISSUE THREAD

**Issue by LostInIgnorance** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1172]
**OS:**
Windows 10 Pro x64

**Issue Descriptions:**
Cannot start application with 2 different versions (3.2.1 & 3.2.4).  Attached are logs.
[SquirrelSetup.txt](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/308174/SquirrelSetup.txt)

**Steps to Reproduce:**
Launch installer

**Comment by LostInIgnorance** [comment]
For anyone elses reference it turned out to be a security issue with Kaspersky Antivirus blocking the app starting.

**Comment by MarshallOfSound** [comment]
@LostInIgnorance Couple of questions.

* Are you running this on a Work or Personal computer?
* Are you an administrator?
* Do you have A/V protecting your PC?

**Comment by LostInIgnorance** [comment]
Yep, only making it easier for the next searcher.
