### ISSUE TITLE
Process not closing, causes EADDRINUSE bug

### ISSUE THREAD

**Issue by jostrander** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1173]
An uncaught exception was reported.  
#### Info:
**OS:** linux
**Arch:** x64
**GPMDP Version:** 3.2.4
**Time:** Fri Jun 10 2016 03:58:41 GMT-0400 (EDT)

#### Error:
*listen EADDRINUSE 0.0.0.0:5672*
```js
Error: listen EADDRINUSE 0.0.0.0:5672
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
This issue was created automatically inside the `uncaughtException` handler

-----------------------------------------------------------------------------------------------------

I know we've seen this error a million times, but its happened a bit to me lately and I think it has something to do with the process not finishing entirely before another instance is relaunched. AKA the old "listener" in node is not taken down when the old app quits. I usually get it if for some reason GPMDP freezes and I kill it and start a new instance. 

If you've addresses this in master feel free to close, but I figured I'd add a drop of information in the sea of issues about this.

**Comment by MarshallOfSound** [comment]
Weow, changing the title to stop the Unicorn getting it. You sneaky bugger 😆 

In other news though, if your diagnosis is correct a simple

```js
app.on('will-quit', () => {
    if (server) server.stop();
});
```

Should do the job

**Comment by jostrander** [comment]
I knew if I didn't it would get closed like the other 500, but I was too lazy to go manually create an issue. As for the code, looks good to me :+1: I've just had it happen now on both windows and linux so I figured it probably was a constant issue for some people.

**Comment by MarshallOfSound** [comment]
I would test / push it but I currently have like 30 unstaged files from implementing spectron and I can't be bothered stashing 👍
