### ISSUE TITLE
Toolbar Icon Mac

### ISSUE THREAD

**Issue by danielmarino** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1174]
Is there a way to replace the toolbar icon on mac? I would like to redesign or adjust it and not sure where this icon is in the package.
![screen shot 2016-06-10 at 10 26 15 am](https://cloud.githubusercontent.com/assets/333118/15967449/c85e6198-2ef5-11e6-8dcf-2bf0ceefa8f8.png)

**Comment by MarshallOfSound** [comment]
That icon has been updated / changed in master.  Don't worry, it looks a lot better now 👍
