### ISSUE TITLE
Search with / shortcut breaks the mini-player

### ISSUE THREAD

**Issue by ikeeki320** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1175]
**OS:**
OS X 10.10.5
GPMDP 3.4.2 (just downloaded and installed for the first time)

**Issue Descriptions:**
When pressing the search shortcut key, /, while in the mini player the controls area of the player shift to the left so you can't see it all and the search function does not work (i.e. can't type anything or press enter or escape out of it). Besides not being able to get the controls back in the correct position, I am unable to press mini player button to get it back to the larger screen. And I can't go from mini player to larger player at any time whether I can see all of the controls or not.

**Steps to Reproduce:**
Start music playing
Click on mini player
Press / key on keyboard
![screen shot 2016-06-10 at 11 21 31 am](https://cloud.githubusercontent.com/assets/19860538/15971456/c2e7446a-2efe-11e6-820a-54de80421fa3.png)

**Comment by MarshallOfSound** [comment]
Interesting trick, surprised no one has tried this before.

FWIW I can replicate on my local version but I can use the mini player button to revert back to the full player.

I'll look into what's causing this when I get a change 👍
