### ISSUE TITLE
Feature Request: Add "Add to library" button to Mini player

### ISSUE THREAD

**Issue by veremenko-jav** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1176]
Hello and thanks for great app.

Is it possible to add "Add to library" button to Mini Player as I often listen to radio and like to add songs to my library during the process. Now I have to open big player and minimize it again.

Thanks

**Comment by MarshallOfSound** [comment]
I've looked into this before, and it's not currently possible with the architecture of GPM
