### ISSUE TITLE
Search bar goes default white

### ISSUE THREAD

**Issue by Pheoxy** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#118]
When searching the search goes default white color until you either delete what was written or click out of it.

**Comment by MarshallOfSound** [comment]
This is intended behavior 

If I change it to black the search UI becomes quite hard to use

**Comment by MarshallOfSound** [comment]
If you disagree with this decision please explain below :+1:

**Comment by Pheoxy** [comment]
Seems like a good idea, but you could also do a very light gray for people who use darker colors.
