### ISSUE TITLE
Keep search input focused after results

### ISSUE THREAD

**Issue by Noxalus** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1182]
**OS: Windows 10 (64 bits)**

**Issue Descriptions:**

You did an excellent work on this project, but there is something that make me made every time with the search bar: we loose the focus because of the automatic submission! :'(

**Steps to Reproduce:** Start typing some characters in the search bar, wait a few seconds, continue to type something => you are not in the search bar anymore.

**Comment by MarshallOfSound** [comment]
I can't reproduce this issue. I have tried searching from many different pages within GPM and searching many different things.

And FWIW even if I could replicate it this is something that Google would have to fix on there end 😄
