### ISSUE TITLE
couldn't install (installation log included)

### ISSUE THREAD

**Issue by tjxddt** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1186]
I try to install the latest Version 3.2.4 x64 variant. It keeps showing this error
![image](https://cloud.githubusercontent.com/assets/14345269/16019139/77b1a6b0-3175-11e6-81c7-2645475678c8.png)

**OS:**
Windows 10 Pro x64
**Issue Descriptions:**

https://gist.github.com/MarshallOfSound/44412b039cba1e6bad3c0077f54dcc1d

**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment]
This normally occurs on a work or group policy protected computer.

1. Perform a clean uninstall of the application
2. Delete all `Google Play Music Desktop Player` folders in `%APPDATA%`
3. Install the application again (DO NOT RUN AS ADMIN)

**Comment by MarshallOfSound** [comment]
@tjxddt I don't like these issues cluttering up github, if you need more help please head into the Gitter chat
