### ISSUE TITLE
Add song to playlist

### ISSUE THREAD

**Issue by ikeeki320** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1187]
**OS:**
OS X 10.10.5
GPMDP 3.4.2

**Issue Descriptions:**
I can only add a song to the playlist that is alphabetically first. My first playlist is "Alternative" and the second is "EDM". When I click on the three dot menu of a playing song. The only options I have in the Add to Playlist submenu are "New Playlist" and "Alternative". If I change "EDM" to "aEDM" it shows up under "New Playlist" instead of "Alternative". If I go to the three dot menu in the now playing queue, both playlists are visible.

**Steps to Reproduce:**
Play a song
Click on three dot menu
Go to Add to Playlist

**Comment by MarshallOfSound** [comment]
This issue has been fixed in master.

Although your description is interesting :smile:. The bug was actually just hiding the 3rd item in the list :P

**Comment by ikeeki320** [comment]
Please forgive me. I'm just a general user/music enthusiast so I don't really know how open source and github all works. Do I have to do something to get the master?

**Comment by MarshallOfSound** [comment]
@ikeeki320 You should probably just wait for the next release 👍   It will probably happen in 2 weeks or so, I'm currently doing exams so I'll try release the next version once those are sorted.

**Comment by ikeeki320** [comment]
sounds good. thanks for all the quick responses and great player
