### ISSUE TITLE
'Done' button doesn't obey the theme.

### ISSUE THREAD

**Issue by emancipateme** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1188]
**OS:** WIndows 10 x64

**Issue Descriptions:** When viewing more on an artist's bio, the 'done' button doesn't obey the theme colours.

**Steps to Reproduce:** View more on an artist's biography, then look at the 'done' button.

**Comment by MarshallOfSound** [comment]
As far as I am aware it does?  If you look at the button with the theme disabled it also has a transparent background and plain text.

Can you confirm what you expect it to look like

**Comment by emancipateme** [comment]
Here's what mine looks like with the blue theme:
![image](https://cloud.githubusercontent.com/assets/10497077/16098114/94a7970c-33a5-11e6-9c74-ab2332f29fcf.png)

I would assume that the word 'Done' should also be blue as the 'Read More' text was. I also tried with some of the other colours but they didn't work as expected either.

**Comment by MarshallOfSound** [comment]
Ahhhh, I see.  When I checked I took a look on the dark theme where it looks kinda normal 👍
