### ISSUE TITLE
Feature Request: More keybord shortcuts?

### ISSUE THREAD

**Issue by fgimian** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1194]
**OS:** OS X El Capitan
**Issue Descriptions:** Can you please consider adding keyboard shortcuts for rewind, fast forward, and back / forward (browser buttons) ?

Thanks so much and great job with the app!! 😄 
Fotis

**Comment by MarshallOfSound** [comment]
All of these shortcuts exist in the hotkeys menu or are enabled by default
