### ISSUE TITLE
Feature Request: Screensaver Functionality 

### ISSUE THREAD

**Issue by spennasaurus** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1195]
No issues with current release, just wanted to make a request. I'd love to have the option to have a screensaver build into the Desktop Player. 

**OS:**

**Issue Descriptions:**

**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment]
This request doesn't make much sense to me.  This is a music player, how do you expect it to be operate as a sceensaver?

**Comment by spennasaurus** [comment]
Sorry not sure if I explained that well. It's more so having the album art
and track title visible from the screen saver would be nice.

**Comment by MarshallOfSound** [comment]
On what OS?  I don't believe this is possible on any OS at the moment but I will take a look into it

**Comment by ChrisB9** [comment]
As there is a Playback-API, its not that difficult to write a screensaver (for linux) - but i dont think, that this is part of a music player..

**Comment by MarshallOfSound** [comment]
I agree with @ChrisB9 we have a a PlaybackAPI so other's can write applications that utilize the players internal playstate and a screensaver would be a perfect use case.  This shouldn't be part of the core application, but if someone wants to go ahead and make one 👍 Go right ahead 👍
