### ISSUE TITLE
Persistent sorting should be disabled on "Thumbs Up" playlist

### ISSUE THREAD

**Issue by rfuhrer** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1196]
**OS:**
Windows 10

**Issue Descriptions:**
Sorting of playlists or your library is persisted to your next session.  This is a great feature and should definitely not be disabled, however "Thumbs Up" is a special case where the initial sorting of that playlist is not a column that you can select.  It sorts descending based on date of you clicking thumbs up.  The issue is that once you sort this list with any other column, you can never return to this default sorting.  Normally you just close your browser and open it again and this will return you to the default sorting, but since this app persists sorting even after closing you can never get back.

My suggestion is to add an exemption to this one playlist and have it not persist the sorting anymore.

**Steps to Reproduce:**
- Navigate to Thumbs Up Auto-Playlist
- Click a column header to sort the list
- Close and reopen the application
- Thumbs up list is still sorted by the column you chose and can't be returned to default

Thanks again! Love the application

**Comment by MarshallOfSound** [comment]
@rfuhrer That seems like a flaw in UI Google Play Music more than a flaw in my code.

We don't technically "persist" the sorts, we simply save the last URL you were on before you left and restore that when you open the app again.

If you want to restore the Thumbs Up ordering you can simply close the app on a page that ISN'T the thumbs up playlist, and then re-open the app.

**Comment by iBrooks** [comment]
Unreal that the solution to this  is "Close and reopen" So user-hostile. No wonder everyone prefers spotify.

**Comment by rfuhrer** [comment]
@iBrooks yeah it's kind of a silly problem because auto-playlists don't have a `#` column.  Like if you sort a normal playlist by name, you can return it to it's original sort by then sorting by the `#` column.  Since that's not an option for Thumbs Up and Last Added you end up with this weird edge case.  As @MarshallOfSound  explained though, there's nothing he can do about it since it's googles code that does all of this and has nothing to do with the desktop player.  

As someone who switched to Spotify for a year and then switched back, there's definitely some nice stuff in their UI that google needs to catch up on.  The biggest one I miss is the quick filtering.  I could open my "thumbs up" playlist (cause of course Spotify doesn't have a thumbs up function which annoyed the crap out of me so I had to manually make a playlist and drag my favourite songs into it) and then filter by "The Bronx" and boom i'd see all my favourite songs by the Bronx and then I could shuffle those.
