### ISSUE TITLE
Version 3.2.5 Release is just Version 3.2.4?

### ISSUE THREAD

**Issue by berryelectronics** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1198]
Hey, just noticed that actually not a whole lot has changed since the update. I Also went through some files and tested if they are the same (with the Notepad++ Compare Plugin) and it seems like the Source code for the 3.2.5 and 3.2.4 are the same and dont match up with the Repos latest state. The only thing that seems that it changed that it doesnt includes Musixmatch anymore.

**Comment by MarshallOfSound** [comment]
Everything you have said is correct.

I'll be putting in a wiki entry explaining why shortly.

This is where the 3.2.5 came from FWIW

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/tree/v3.2.5-patch

**Comment by MarshallOfSound** [comment]
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/What-happened-with-3.2.5%3F

**Comment by berryelectronics** [comment]
Oh man, that is shitty, hope they didnt did anything more than just sending you that email

**Comment by berryelectronics** [comment]
http://about.musixmatch.com/apiterms
`7.2 You shall NOT:`
 `7.2.4 attempt to copy, collect or scrape data from the Site in any way other than through accessing the API with the User Authentication Key;`

Well, the only way seems to use their API.

**Comment by berryelectronics** [comment]
https://github.com/pilu/musixmatch-node

**Comment by jostrander** [comment]
That'd be fine and dandy berry if the license wasn't $25,000 minimum per year.

**Comment by berryelectronics** [comment]
Holy sh.....didnt knew that lel.
