### ISSUE TITLE
Will not launch on Surface 3

### ISSUE THREAD

**Issue by ninjustin** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#120]
I can't seem to get the program to launch at all on a non Pro Surface 3.  It works great in Windows 10 on my custom desktop though. Running specifically as an Admin does not help nor do any of the compatibility settings.

**Comment by MarshallOfSound** [comment]
Can you ensure that Visual Studio 2012 C++ Redist is installed.

Or use this beta installer from https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/75#issuecomment-167918215

**Comment by ninjustin** [comment]
That was it. Awesome app.  Thank you.
