### ISSUE TITLE
not seeing the update notification.

### ISSUE THREAD

**Issue by madLyfe** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1201]
win 10 64bit stable

didnt see an update notification for recent 3.2.5 even though its only been 15 hours since the release. does this app auto update through the app? also, in the settings page there should be a version number and maybe a check for updates button. ppl love buttons.

opened the app.

**Comment by berryelectronics** [comment]
you can see the current version if you right-click the tray icon and then under help -> About.
AFAIK it checks for updates when it starts, so you may need to restart it or just download the new installer.

**Comment by madLyfe** [comment]
i dont have the tray icon enabled so i guess thats why. ya ive closed and reloaded the app and didnt get a notification.

**Comment by MarshallOfSound** [comment]
Can you upload your squirrel log.  It is in the following folder

`%LOCALAPPDATA%/GPMDP_3`
