### ISSUE TITLE
Close the app turns into "no response, do you want do kill the tast"

### ISSUE THREAD

**Issue by Bohne13** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1204]
**OS:**
Linux Ubuntu 16.04 LTS

**Issue Descriptions:**
If you want to close the app, it's freezing and you need to close it with the dialog witch appears. It happens verry often but not every time I close the app. I always do the same, listen to musik an meanwhile it's playing music, I close the app.

**Steps to Reproduce:**
Close the app.

**Comment by MarshallOfSound** [comment]
Fixed in master, was an upstream Electron bug
