### ISSUE TITLE
Ubuntu Sound Indicator doesn't work since v.3.2.5

### ISSUE THREAD

**Issue by Bohne13** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1205]
**OS:**
Linux Ubuntu 16.04 LTS

**Issue Descriptions:**
Sound Indicator in the upper right corner shows the "Google Play Desktop Player" but the Buttons (Play/Stop, before, next) have no funktion. 
It's since I updatet from 3.2.4 to 3.2.5

**Steps to Reproduce:**
Every time the player is opened and played music

**Comment by MarshallOfSound** [comment]
I don't understand why it stopped working in `3.2.5` as realistically nothing changed 😕 

However it does work in master so I'm closing this as fixed.  The `3.3.0` release will be arriving shortly
