### ISSUE TITLE
Chromecast Support

### ISSUE THREAD

**Issue by MarshallOfSound** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1207]
I while ago we added Chromecast support through our new library https://github.com/GPMDP/electron-chromecast

Shoutout to the team (@jostrander) for nailing this library out with me.

Basically there are a few things we need to make.

* [x] UI for selecting target chromecast
* [x] UI for stopping the cast
    * [x] Methods inside `electron-chromecast` to stop the cast

And a few things we need to test.

* [x] Windows 7 without bonjour installed
* [x] Windows 8 without bonjour installed
* [x] Windows 10 without bonjour installed
* [x] Windows 7 **with** bonjour installed
* [x] Windows 8 **with** bonjour installed
* [x] Windows 10 **with** bonjour installed
* [x] OS X (Any version they all come with the same bonjour library)
* [x] Ubuntu 14.04 using the install image (should put a dependency on avahi)
* [x] Ubuntu 16.04 using the install image (should put a dependency on avahi)

/cc @jostrander

**Comment by berryelectronics** [comment]
About the UI:

How about making it in the Style of the Chrome Chromecast Plugin?

![ss 2016-06-25 at 06 19 43](https://cloud.githubusercontent.com/assets/12616124/16357809/6f67dfa2-3b01-11e6-8161-751e5e06fb49.png)

**Comment by jostrander** [comment]
Do you have an english version of that dialog? lol

**Comment by berryelectronics** [comment]
Dont know how the exact translation is in german, but here ya go:
"transmit to"
"device missing?" (because my chromcast isnt in my network anymore)
"search"

**Comment by jostrander** [comment]
Thanks, I'll see what I can do

**Comment by voldemarz** [comment]
Would this also add support for casting to Google Cast compatible devices?

**Comment by MarshallOfSound** [comment]
@voldemarz Yes

**Comment by jostrander** [comment]
Switching chromecast devices does not work with the latest changes.

**Comment by MarshallOfSound** [comment]
Hmmmm, I only have one chromecast.  So this will be tricky for me to debug 😆 

If I had to guess though, it is some kind of scoping issue or your chromcast labels are the same?

**Comment by jostrander** [comment]
They both have the same label... but you've got `trigID` to uniquely identify which one to return, so that doesn't make much sense.

**Comment by MarshallOfSound** [comment]
`trigID` uniquely identifies session requests, not individual chromecasts.

Do you chromecasts have the same `label`?

**Comment by jostrander** [comment]
Yes

**Comment by MarshallOfSound** [comment]
Oh, of course, that label is hardcoded in `electron-chromecast`....

Do they have an ID or something we can use.  I forgot 😆

**Comment by jostrander** [comment]
The IP address? lol

**Comment by MarshallOfSound** [comment]
I guess so, that would have to be unique 😆

**Comment by MarshallOfSound** [comment]
@jostrander Can you test either of the variations of Ubuntu, my VM's aren't playing nice with bonjour 😆

**Comment by jostrander** [comment]
Yeah, I can test 16.04, I don't have 14.04 currently available to me.

**Comment by voldemarz** [comment]
As far as understand this is only available in v3.3.0. Where can I get it to test? I don't see "cast" icon in v3.2.5.

**Comment by MarshallOfSound** [comment]
@voldemarz Come on Gitter and I can point you in the right direction of a test build

https://gitter.im/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-
