### ISSUE TITLE
Audio device is remembered but ignored when starting up.

### ISSUE THREAD

**Issue by Kruptein** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1209]
**OS:** Windows 10

**Issue Descriptions:**
When selecting an audio device, gpmd will correctly use that audio device.
However when I close gpmd and reopen it, it will use the default audio device again,
when going to the audio device selection it does show the prefered audio device though,
reselecting it does again use the correct audio device.

**Steps to Reproduce:**
1. Select non default audio device
2. close gpmd
3. reopen gpmd

**Images**:
When manually resetting the audio device: http://imgur.com/H3qVfWK
the music comes from the correct audio device as seen in voicemeeter

When restarting gpmd: http://imgur.com/WLC6Nqo
the music comes from the main audio device even though the gpmd audio device selection says it's using another one.

in both cases music was playing.  The audio devices, which are virtual, are at all times present.

**Comment by MarshallOfSound** [comment]
This is strange, because it works correctly on my machine and on other machines running Windows 10.

What audio device are you attempting to output to?

**Comment by Kruptein** [comment]
As can be seen in the linked images, it's just my builtin audio device with some virtual cables to be able to separate my audio in groups.  I'll try to test it on my laptop to see if it has the same behaviour.

**Comment by MarshallOfSound** [comment]
Hmm, I've never tried with Virtual Audio Cables.

I'll give that a go when I have time and if you can try on your laptop that would be great 👍

**Comment by MarshallOfSound** [comment]
Please update the issue with more information when you can
