### ISSUE TITLE
GPMDP makes wingpanel unresponsible and sometimes crashes

### ISSUE THREAD

**Issue by Maccer1** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1215]
**OS:**
elementaryOS Loki 64 bit (beta)

**Issue Descriptions:**
When opening your app the top bar indicators stop working until I close it. Terminal doesn't give any output besides `Gtk-Message: Failed to load module "pantheon-filechooser-module" ` which I think is unrelated since it's a usual warning with some other apps.

Changing settings inside the app, such as "use system window borders" or "minimize to tray" doesn't solve the problem.
Everything worked fine back in elementaryOS Freya.

**Steps to Reproduce:**
Install elementary OS Loki and install GPMDP. Wingpanel stops working and crashes after a while. App continues working as expected.

**Comment by MarshallOfSound** [comment]
Hmmmm, this sounds like either an Electron problem or a Loki problem.

Can you try running any other electron application that use tray icons and see if they also cause the crash

/cc Linux dude @jostrander

**Comment by Maccer1** [comment]
Can you give me an example of those apps? I've tried with Brave  and Mancy but I don't think those use tray icons.

By the way, if this is a tray icon issue it may be because the elementary made some changes and dropped support for Ayatana. From [their blog](http://blog.elementary.io/post/145881464631/loki-beta) :

> No More Ayatana
The brand new set of wingpanel indicators has landed and Ayatana is no more. If your app is making use of the Ayatana AppIndicator API, now is the time to stop. The FreeDesktop Actions spec is the proper way to have quick application actions. These appear in the dock, when right-clicking apps in the applications menu, and also in the applications menu search. If users want your app to be quickly accessible, they can pin it to the dock where you can use the LauncherEntry API to show badges and progressbars. Notifications from your app will now persist in the notifications indicator, and as always music players making use of MPRIS will show in the sound indicator. The focus here is on empowering users to choose which apps are allowed to be omnipresent on their desktops and keeping the indicator area useful and clutter-free. There is a Wingpanel API, but this API should be used only by permanently-running, system-level utilities (ie redshift); not applications (ie skype).

**Comment by MarshallOfSound** [comment]
@Maccer1 Try installing the desktop client for Slack

That has a tray icon

**Comment by Maccer1** [comment]
No problem with Slack.

**Comment by MarshallOfSound** [comment]
Can you give a good explanation of what wingpanel actually does.  I think I have a misunderstanding of it's purpose

**Comment by Maccer1** [comment]
Wingpanel is the [top bar](http://entornosgnulinux.com/wp-content/uploads/2015/11/Primer-contacto-App-Center-0.1-en-elementary-OS-Loki.jpg) of elementaryOS. From Loki beta they decided that developers shouldn't use it except for system-level apps.
I'm not sure how this app crashes with Wingpanel since there wasn't any icon in the top bar. I don't remember having any icon back in Freya. My guess it's that it has something to do with the way the app interacts with the media controls that are inside sound-indicator.
Does GPMDP use [MPRIS](https://specifications.freedesktop.org/mpris-spec/latest/) ? If not, that may be the issue I think.

If you tell me how, I can give you some logs about what is happening.

**Comment by MarshallOfSound** [comment]
Yes we follow the MPRIS spec

It works correctly with literally every other linux OS, so Loki must have a bad implementation of the MPRIS spec.  Are there any like crash logs or something?

**Comment by jostrander** [comment]
I'm not familiar with elementaryOS, however I believe it's a modified debian distribution. Maybe check /var/log/syslog for any errors related to the issue at hand?

**Comment by jostrander** [comment]
As a follow up to this, I tried getting a copy of the Loki beta, but my google-fu must be pretty bad because I couldn't find a download. Need some kind of log on this otherwise we can close it as distro specific upstream bug.

**Comment by Maccer1** [comment]
Thanks I didn't know where to find that log. I've been asking on their subreddit but I didn't got any response. Anyway here's the output related to the crash:

` Jun 25 18:56:03 Maccer-PC org.gnome.gedit[1253]: (gedit:10587): GVFS-WARNING **: can't init metadata tree /home/nicolas/.local/share/gvfs-metadata/root: open: Permission denied
Jun 25 18:56:12 Maccer-PC org.gnome.gedit[1253]: message repeated 2 times: [ (gedit:10587): GVFS-WARNING **: can't init metadata tree /home/nicolas/.local/share/gvfs-metadata/root: open: Permission denied]
Jun 25 18:56:12 Maccer-PC org.gnome.gedit[1253]: ** (gedit:10587): WARNING **: Set document metadata failed: Error setting file metadata: can't open metadata tree
Jun 25 18:56:17 Maccer-PC gnome-session[1172]: Gtk-Message: Failed to load module "pantheon-filechooser-module"
Jun 25 18:56:20 Maccer-PC gnome-session[1172]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x3a00001 (Google Pla)
Jun 25 18:56:37 Maccer-PC kernel: [ 7339.623540] show_signal_msg: 31 callbacks suppressed
Jun 25 18:56:37 Maccer-PC kernel: [ 7339.623547] wingpanel[1509]: segfault at 0 ip 00007f03eda8a770 sp 00007ffcc8ebf3d8 error 4 in libglib-2.0.so.0.4800.1[7f03eda51000+10f000]
Jun 25 18:56:38 Maccer-PC gnome-session[1172]: ** Message: ProcessWrapper.vala:99: Process 'wingpanel' watch exit
Jun 25 18:56:38 Maccer-PC gnome-session[1172]: ** Message: ProcessWrapper.vala:111: Process wingpanel is being terminated
Jun 25 18:56:38 Maccer-PC gnome-session[1172]: ** Message: ProcessWrapper.vala:123: ET = 7333.377349 secs#011Min allowed time = 3.500000
Jun 25 18:56:38 Maccer-PC gnome-session[1172]: ** Message: ProcessWrapper.vala:46: Crash count of 'wingpanel' has been reset
Jun 25 18:56:38 Maccer-PC NetworkManager[778]: <info>  [1466873798.6453] audit: op="device-autoconnect" arg="autoconnect:1" pid=10712 uid=1000 result="success"
Jun 25 18:56:39 Maccer-PC gnome-session[1172]: ** (process:10777): CRITICAL **: string_contains: assertion 'self != NULL' failed
Jun 25 18:56:39 Maccer-PC gnome-session[1172]: ** (process:10777): CRITICAL **: string_contains: assertion 'self != NULL' failed
Jun 25 18:56:40 Maccer-PC org.gnome.gedit[1253]: (gedit:10784): GVFS-WARNING **: can't init metadata tree /home/nicolas/.local/share/gvfs-metadata/root: open: Permission denied`


The elementaryOS beta is [here](http://elementary.io/developer#)

**Comment by Maccer1** [comment]
And, I think the problem is in this part:
>Jun 25 18:56:20 Maccer-PC gnome-session[1172]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x3a00001 (Google Pla)
Jun 25 18:56:37 Maccer-PC kernel: [ 7339.623540] show_signal_msg: 31 callbacks suppressed
Jun 25 18:56:37 Maccer-PC kernel: [ 7339.623547] **wingpanel[1509]: segfault at 0 ip 00007f03eda8a770 sp 00007ffcc8ebf3d8 error 4 in libglib-2.0.so.0.4800.1[7f03eda51000+10f000]**
Jun 25 18:56:38 Maccer-PC gnome-session[1172]: * Message: ProcessWrapper.vala:99: Process 'wingpanel' watch exit

**Comment by jostrander** [comment]
I think the "Buggy client" thing is the real issue, however this seems to be out of our control. Can you raise in issue in electron? The window manager libraries would be something on their end I believe.

**Comment by Maccer1** [comment]
Done

**Comment by Maccer1** [comment]
If you happen to have this same bug someday, this may be interesting:

>The "Window manager warning: Buggy client" warning comes from gnome-session and it happens for lots of popular apps. The real problem is wingpanel crashed, and I think you should report the bug to wingpanel, even though it may be caused by Electron sending wrong messages.

**Comment by jostrander** [comment]
So it seems like this is something that just _is_ with gnome-session. If you do submit this over to wingpanel add a link back to here so people that might stumble on this in the future might be able to follow it up. But seeing as other OS's with gnome-session work fine, I'd consider this to be an issue with loki specifically.

**Comment by MarshallOfSound** [comment]
@Maccer1 @jostrander I'm going to close this as an upstream issue that we have zero control over.  If you could update this issue if / when you get a response from the Loki team

**Comment by Maccer1** [comment]
Well I got some news. This issue is fixed on Loki beta 2. I didn't get any response on my bug posted in the elementary bug tracker but anyway its fine now.
