### ISSUE TITLE
Show loading graphic before playback starts

### ISSUE THREAD

**Issue by mstrelan** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1217]
Sometimes when I start "I'm feeling lucky radio" it takes a few seconds before playback starts. During this time the playback animation in the queue is displayed. This makes me wonder if my speakers are muted, or my default playback device is set to my headphones. Playback starts after a moment of fumbling around trying to fix it. I was thinking it might be nicer to display a loading graphic, eg from http://ajaxload.info, until the song has buffered enough for playback to begin. I have no idea if this is possible to determine.

**Comment by MarshallOfSound** [comment]
This is something that is out of my control (as I have no way to know when you attempt to load the radio or when the radio is started successfully), and very dependent on network speed.

I just tried your steps to reproduce and my "I'm feeling luck" loading immediately.

Best I can suggest is reporting this to google on their product forums

**Comment by mstrelan** [comment]
Thanks for your response. For what it's worth (probably not much) I just tried this on the web player and it actually has a loading graphic like I suggested.

**Comment by MarshallOfSound** [comment]
If there is a loading graphic on the web player there should be a loading graphic inside this player.  (At the lowest level we simply wrap the web client).

Did you have the dark theme turned on?

**Comment by mstrelan** [comment]
I do have the dark theme turned on. I just swapped over to the light theme
and the same result. The other difference is that when I hit pause the web
player shows a dotted line where the playback animation was, and the
desktop player is blank.

**Comment by mstrelan** [comment]
I'm happy for this to be wontfix due to being out of your control, but just in case it helps I've enabled network throttling in Chrome and taken screenshots inspecting the code where the loading and paused icons appear.

http://image.prntscr.com/image/d81036371aa2412fa09b51cef492cc5f.png
http://image.prntscr.com/image/ba6a0e4ded8d457aafb67edd39882898.png

**Comment by mstrelan** [comment]
Just realised that I still had "Custom Theme" checked when I switched to the light theme. Un-checking this shows the correct graphics.

**Comment by MarshallOfSound** [comment]
Please raise this as a theming issue over at https://github.com/gmusic-utils/gmusic-theme.js
