### ISSUE TITLE
Install Error[Windows 10]

### ISSUE THREAD

**Issue by Akhito** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1218]
Windows 10

Every time I run the install, regardless of version, I get an unexpected token error.  I checked my java version and everything seems up to date and running fine, so I don't know whats going on. :/

Unfortunately I don't know if this is able to be reproduced, but it has just occurred when I attempted to patch my 3.2.4 version of the application to 3.2.5.  My suggestion for reproducing would be to run the 64x .exe file and see if that has any issues, or if it's something I need to take care of on my end.  Thank you for your time.

**Comment by MarshallOfSound** [comment]
Well

1. This program has nothing to do with Java 😆 Java and Javascript are two different languages
2. Delete the `json_store` directory from `%APPDATA%/Google Play Music Desktop Player`

**Comment by Akhito** [comment]
Sorry, I didn't try to go into the code, didn't want to screw anything up.
Thanks, will do. :)

**Comment by Akhito** [comment]
Helped a lot! Thanks again!
