### ISSUE TITLE
Feature Request: Add a sleep mode

### ISSUE THREAD

**Issue by fkrauthan** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1219]
The music player Songbird used to have a extension that automatic fades music after a certain time and then executes a command.

This was perfect to just listen for e.g. 30min to music and then the music slowly fades out (or it waits until the current song is finished) and then turns off my computer. I would love to see something like that integrated here.

**Comment by MarshallOfSound** [comment]
Merging into #211
