### ISSUE TITLE
GPMDP not starting up

### ISSUE THREAD

**Issue by viniboyBR** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1221]
**OS:** Windows 10

**Issue Descriptions:** Whenever I start the GPMDP program, an error comes up stating, 
"A JavaScript error occurred in the main process
Uncaught Exception:
Syntax Error: Unexpected token"
If I close the error, it shows the program as still running in task manager, and clicking the icon to run does nothing. This was after update 3.2.5, the first day of this update it worked fine, but when I opened the program again it displayed this error. Attempting to reinstall the desktop player from http://www.googleplaymusicdesktopplayer.com/ causes it to display the same error when I click the installer. Google Play music works fine on my computer in a browser.

**Steps to Reproduce:** Clicking the installer/icon displays the error.

**Comment by berryelectronics** [comment]
Same as #1171 

> Delete the settings file found at

> %APPDATA%/Google Play Music Desktop Player/json_store

That will be fixed in the next version
