### ISSUE TITLE
Feature Request: Thumbs Up/Down buttons on Windows mouse-over

### ISSUE THREAD

**Issue by DerekFroese** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1222]
Hello! Love the player. 

I regularly use the controls that appear when you mouse-over the app icon in the taskbar. While working, I often want to thumb-up a song, which currently requires me to open the full app and hit the button. I do this a bunch in a day, and I'd rather have a quicker method. 

Would it be possible to add thumb-up/down buttons to the mouse-over player in Windows?

Thanks!

**Comment by berryelectronics** [comment]
How about shortcuts?

**Comment by berryelectronics** [comment]
Oh, also available via the task icon.

**Comment by MarshallOfSound** [comment]
As @berryelectronics mentioned you can set global shortcuts to perform these actions and you can use the tray icon.

There is actually a limit to the number of buttons I can put in that hover section (I believe it's 4) so I can't add 2 more buttons 😆

**Comment by DerekFroese** [comment]
Thanks guys
