### ISSUE TITLE
No Window on MacOSX El Capitan

### ISSUE THREAD

**Issue by Linkmaster08** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1225]
**OS:** Mac OSX El Capitan

**Issue Descriptions:**
The GMP Desktop Player worked fine until recently. Suddenly no window appeared on starting the app. 
The Menu Bar is working, but no main window is showing up. I can access the about window as well as the settings window. 

The Problem is still here after a fresh reinstall. :/

**Steps to Reproduce:**
- no special steps, suddenly stopped working
- appears even after reinstall

**Comment by MarshallOfSound** [comment]
Delete the settings file.

```js
~/Library/Application\ Support/Google\ Play\ Music\ Desktop\ Player/json_store
```
