### ISSUE TITLE
[Linux] Main window moves upon leaving mini player when using system window borders.

### ISSUE THREAD

**Issue by CyanJDroid** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1226]
**OS:**
Antergos Linux

**Issue Descriptions:**
When using system window borders, upon exiting mini player, the main window moves itself down slightly from where it was before entering mini player mode.

**Steps to Reproduce:**
Switch to using system window borders, note current window position, switch to mini player, switch out of mini player, note window has moved downward slightly, repeat if desired.

**Gif:**
![gpmdpbug](https://cloud.githubusercontent.com/assets/5077450/16257300/444f7866-381d-11e6-817d-bb32884e07a4.gif)

**Comment by MarshallOfSound** [comment]
This is an OS issue on some linux platforms whose window managers incorrectly report the window position.

In this case it appears that the window origin is being reported as the top left of the embedded player not the top left of the control bar.

You should report this to your OS or Chromium (It's one of them 😆 )

**Comment by CyanJDroid** [comment]
Alrighty, thanks!
