### ISSUE TITLE
Feature - Lyrics Display

### ISSUE THREAD

**Issue by Xedecimal** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1229]
Since such effort was put into creating a lyric display, it kinda sucks that you have to right click on the song, show lyrics and then you disable the player when they're visible. How about embedding them as the miniplayer background, or putting them somewhere where you can see them and still use the app ?

**Comment by MarshallOfSound** [comment]
@Xedecimal The less windows we launch the more resource efficient the app is.  If we launch another window then it spawns another renderer process.

We have a PlaybackAPI that exposes the lyrics we fetch so if you want the lyrics in a separate window it would be best if you or someone else wrote a dedicated lyrics viewing application.

The goal with this application is too keep it small and lightweight, spawning multiple renderer processes doesn't help with that mission 😆
