### ISSUE TITLE
Feature Request: Optional persistent sidebar

### ISSUE THREAD

**Issue by fgimian** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1231]
Hello there, thanks again for your wonderful app 😄 

Would it be possible to implement an option that opens the left sidebar by default when the app starts similar to the [Play Midnight](https://chrome.google.com/webstore/detail/play-midnight-for-google/ljmjmhjkcgfmfdhgplikncgndbdeckci) Chrome extension?

Also, is there a keyboard shortcut to open that left sidebar?

Thank you
Fotis

**Comment by MarshallOfSound** [comment]
@fgimian I've discussed this elsewhere (possibly in Gitter) I believe, and the consensus ended up being that there were no advantages to having an option that made it always open.  It adds extra complexity to the settings page for a feature that takes the effort of a single click.

RE: Keyboard shortcut

You can hit "m" on your keyboard to open the menu.

**Comment by fgimian** [comment]
OK, thanks for your quick reply 😄
