### ISSUE TITLE
SyntaxError on startup

### ISSUE THREAD

**Issue by rsht** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1233]
On my **Ubuntu 16.04 x64 (linux 4.4.0-24)** I'm unable to launch the app (all of the sudden). Got the following output when launching from CLI:

> A JavaScript error occurred in the main process
> Uncaught Exception:
> SyntaxError: Unexpected token �
>     at Object.parse (native)
>     at Settings._load (/usr/share/google-play-music-desktop-player/resources/app/build/main/utils/Settings.js:73:31)
>     at new Settings (/usr/share/google-play-music-desktop-player/resources/app/build/main/utils/Settings.js:38:12)
>     at /usr/share/google-play-music-desktop-player/resources/app/build/index.js:106:21
>     at Object.<anonymous> (/usr/share/google-play-music-desktop-player/resources/app/build/index.js:188:3)
>     at Module._compile (module.js:413:34)
>     at Object.Module._extensions..js (module.js:422:10)
>     at Module.load (module.js:357:32)
>     at Function.Module._load (module.js:314:12)
>     at Object.<anonymous> (/usr/share/google-play-music-desktop-player/resources/electron.asar/browser/init.js:184:8)

Steps to reproduce on my machine:

- Launch it :)

Have this issue for quite a while now. Reinstalling/Installing new version, when completely deleting old app with settings (although I'm not 100% I have delete _ALL_ old files) doesn't seem to help.

Being software engineer myself, I believe I can try to find a reason/fix it myself, just need some gentle guidance on where to look 'cause JavaScript/NodeJS are quite far from my specialization.

**Comment by MarshallOfSound** [comment]
> although I'm not 100% I have delete ALL old files

Yup, you almost certainly missed the culprit here.

Delete the folder `json_store` found at in the apps data folder.  Which on linux, I have no idea where it is...

/cc @jostrander

**Comment by MarshallOfSound** [comment]
Jokes, found the docs

$XDG_CONFIG_HOME or ~/.config on Linux

**Comment by jostrander** [comment]
Yep, just need to delete the settings file which is in `~/.config/Google Play Music Desktop Player/json_store/.settings.json` and then launch the app.
`

**Comment by rsht** [comment]
Yep, this fixes the problem.
Danke!
