### ISSUE TITLE
[Debian]  Hotkeys does not work

### ISSUE THREAD

**Issue by raulpinpla** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1235]
Hello! 
Thnks for read this Issue, 
I have a problem with the HotKeys, I can not configure it, I tried to reset with "Escape" key but it does not work, I have a keyboard with Special  Keys (multimedia) but neither I can use it.

I tried running with sudo and reconfigure the Multimedia Keys.

Raul Pinedo

SO = Linux Debian 7 

Problem = Can not set the HotKeys

**Comment by rgavs** [comment]
I would close this and merge into #413 - it seems to be the home for hotkey issues

**Comment by MarshallOfSound** [comment]
@raulpinpla Multimedia keys do not need to be configured, they should work by default.

Hotkeys are set by typing the hotkey while you are focused in the hotkey box.

So click in a box, and perform a hotkey like "Control + Shift + "P" and it will set the hotkey

**Comment by raulpinpla** [comment]
@MarshallOfSound Hi thanks for your answer, let me see the thread 413, is there a limitation of the keys that we can use for the HotKeys?

I can set it with control, thnks, but I prefer to use the Multimedia keys and it does not work.

Thnks

**Comment by jostrander** [comment]
Multimedia keys should work by default via dbus. What version of the player are you using, and how did you install it?
