### ISSUE TITLE
Media keys regression in v3.2.5

### ISSUE THREAD

**Issue by mcg** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1237]
**OS:**
Ubuntu 16.04

**Issue Descriptions:**
Media keys no longer function in version 3.2.5

**Steps to Reproduce:**
Install 3.2.5, attempt to play/pause/next/prev using your OS assigned media keys. Nothing happens.
I have rolled back to 3.2.4 and the keys are working again.

**Comment by jostrander** [comment]
What installation method did you use?

**Comment by mcg** [comment]
Official debs. 64bit.

**Comment by MarshallOfSound** [comment]
This is a non-issue.  It appears that the build dependencies were modified for the 3.2.5 build agent that work on master but not in the 3.2.5 tag.

TLDR:. Works in master

**Comment by mcg** [comment]
Does that mean once 3.2.6 hit's it will be fixed or that it's simply not an issue?

**Comment by jostrander** [comment]
3.3.0 should have everything working again as usual.
