### ISSUE TITLE
Media Keys

### ISSUE THREAD

**Issue by shutitdown** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1238]
Having an issue with getting the media keys to work on OS X 10.11.5. I've tried deleting my Chrome shortcut and restarting chrome, restarting my computer and deleting and reinstalling the app. None of these steps have worked, the media keys don't respond to the app.

**Comment by francma** [comment]
I'm having the same issue on Linux and gpmdp 3.2.5-1.

**Comment by MarshallOfSound** [comment]
@francma Linux media keys somehow broke on `3.2.5` (no idea how nothing changed) but they work in master. 

@shutitdown I just tested on macOS and it works correctly for me.  Do you have any other media players open or do you have google play music installed as an extension inside chrome?

**Comment by shutitdown** [comment]
No other media players open, no extension installed. I'm not sure what's going wrong. @MarshallOfSound

**Comment by shutitdown** [comment]
@MarshallOfSound Tried once more to reinstall the app, restart my computer, double check chrome and whether there were any open media players. Media keys still will not work on OS X El Capitan (10.11.5) Also I've discovered I can't assign hot keys. The fields are unresponsive.

**Comment by mcg** [comment]
Confirmed issue in v3.2.5, see #1237 . I reverted to 3.2.4 and thing seem fine.

**Comment by Bohne13** [comment]
v.3.2.4 works much better than v.3.2.5. It was promised to me that the version 3.3.0 have a lot of bug fixes and it will comming soon.

**Comment by MarshallOfSound** [comment]
I have no idea how 3.2.5 broke as it literally changed nothing (I deleted one file nothing to do with media keys).

`3.3.0` will fix these issues.
