### ISSUE TITLE
Hotkeys issue

### ISSUE THREAD

**Issue by edshevsky** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1239]
Just installed GPMDP in Fedora 24 and have issue with hotkeys - application didn't recognize mediakeys of my A4Tech keyboard (Model: KL-23MU). 

In Windows 10 all works fine.

**Comment by MarshallOfSound** [comment]
Are you trying to assign them as hotkeys in desktop settings?  Because that won't work.  The hotkeys should "just work" natively.

However on linux, they appear to be broken in `3.2.5`

If you want them fixed, grab the latest beta.  https://685-40008106-gh.circle-artifacts.com/3//home/ubuntu/Google-Play-Music-Desktop-Player-UNOFFICIAL-/dist/installers/redhat/google-play-music-desktop-player-3.2.5.x86_64.rpm

**Comment by edshevsky** [comment]
Nothing change :(

**Comment by MarshallOfSound** [comment]
@edshevsky Hmmm, can you try running it from master (I.e. cloning and installing)

**Comment by edshevsky** [comment]
Sorry, but I don't know how to do it... I clonning GIT and which file need to
run?

  

  
Sent from [Nylas N1](https://link.nylas.com/link/2da7ivo4yn5qq1dil7b99d9w6
/local-
5fc60dd0-084c/0?redirect=https%3A%2F%2Fnylas.com%2Fn1%3Fref%3Dn1&r=cmVwbHkrMDBjMmVjZTVmODlkNjFjZTI5NzFjNTg4Yjk5YjEwMGZmZWY2MGQ4OWNiM2Q5OTI3OTJjZjAwMDAwMDAxMTM4NzM4N2M5MmExNjljZTA5YWNiOTBlQHJlcGx5LmdpdGh1Yi5jb20=),
the extensible, open source mail client.  

![](https://link.nylas.com/open/2da7ivo4yn5qq1dil7b99d9w6/local-
5fc60dd0-084c?r=cmVwbHkrMDBjMmVjZTVmODlkNjFjZTI5NzFjNTg4Yjk5YjEwMGZmZWY2MGQ4OWNiM2Q5OTI3OTJjZjAwMDAwMDAxMTM4NzM4N2M5MmExNjljZTA5YWNiOTBlQHJlcGx5LmdpdGh1Yi5jb20=)

On черв 26 2016, at 9:30 ранку, Samuel Attard &lt;notifications@github.com&gt;
wrote:  

>
[@edshevsky](https://github.com/edshevsky&r=cmVwbHkrMDBjMmVjZTVmODlkNjFjZTI5NzFjNTg4Yjk5YjEwMGZmZWY2MGQ4OWNiM2Q5OTI3OTJjZjAwMDAwMDAxMTM4NzM4N2M5MmExNjljZTA5YWNiOTBlQHJlcGx5LmdpdGh1Yi5jb20=)
Hmmm, can you try running it from master (I.e. cloning and installing)

>

> —  
> You are receiving this because you were mentioned.  
> Reply to this email directly, [view it on
GitHub](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-
UNOFFICIAL-/issues/1239#issuecomment-228586797&r=cmVwbHkrMDBjMmVjZTVmODlkNjFjZTI5NzFjNTg4Yjk5YjEwMGZmZWY2MGQ4OWNiM2Q5OTI3OTJjZjAwMDAwMDAxMTM4NzM4N2M5MmExNjljZTA5YWNiOTBlQHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the thread](https://github.com/notifications/unsubscribe
/AMLs5V26BZ1idpq6JJQLYq-f_2MtCeD3ks5qPhx8gaJpZM4I-
ftF&r=cmVwbHkrMDBjMmVjZTVmODlkNjFjZTI5NzFjNTg4Yjk5YjEwMGZmZWY2MGQ4OWNiM2Q5OTI3OTJjZjAwMDAwMDAxMTM4NzM4N2M5MmExNjljZTA5YWNiOTBlQHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon
/AMLs5eEWW6gk7X0mTOFIGSW10C2bx1Kyks5qPhx8gaJpZM4I-ftF.gif)
