### ISSUE TITLE
Feature Request: Currently Playing song to Text File

### ISSUE THREAD

**Issue by livejamie** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1240]
For those of us who do live streaming games and events, it's nice to be able to display the currently playing song on the screen.

It would be awesome if we could enable that, just a file where GPMDP writes the currently playing song to a TXT file somewhere on the hard drive.

Thanks so much!

**Comment by MarshallOfSound** [comment]
This exists.

It is the PlaybackAPI

**Comment by MarshallOfSound** [comment]
Sorry was on a train when I replied to this issue.  Kinda speed typed the response.

To turn it on enable the PlaybackAPI in the settings window.  Then current song information is outputted in a JSON format to the programs AppData folder

**Comment by berryelectronics** [comment]
Maybe OT, but i hope you know that most of the songs in GPM arent royality
free..

Samuel Attard <notifications@github.com> schrieb am Mo., 27. Juni 2016,
07:07:

> Sorry was on a train when I replied to this issue. Kinda speed typed the
> response.
>
> To turn it on enable the PlaybackAPI in the settings window. Then current
> song information is outputted in a JSON format to the programs AppData
> folder
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/1240#issuecomment-228655033>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AMCBvBec7YYJ6kAfGnAyPO1_5sb4uBxwks5qP1qggaJpZM4I-qIJ>
> .
>
-- 
Matjas

**Comment by livejamie** [comment]
@MarshallOfSound Thanks for the response.

Do you know how I can extract the Artist - Song only?

Would it be possible to output a file called currentsong.json or something in that folder? I could see other uses for it as well.

I'd be happy to toss a donation your way if it helps. :)

**Comment by MarshallOfSound** [comment]
@livejamie What streaming tool are you trying to use.  Many have plugins that read JSON files

**Comment by livejamie** [comment]
Latest version of OBS Studio

On Mon, Jun 27, 2016 at 2:35 AM, Samuel Attard <notifications@github.com>
wrote:

> @livejamie <https://github.com/livejamie> What streaming tool are you
> trying to use. Many have plugins that read JSON files
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/1240#issuecomment-228697860>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AADBac9JKVAJKCWuRrEYZ0Eonz7J5hqRks5qP5lfgaJpZM4I-qIJ>
> .
>



-- 
Work: http://jamiemart.in
Play: http://livejamie.com
Twit: http://twitter.com/livejamie

**Comment by MarshallOfSound** [comment]
OK so I can't find a JSON plugin for OBS...  

I'll look into this a bit more
