### ISSUE TITLE
lastPage in settings file

### ISSUE THREAD

**Issue by thepaperpilot** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1245]
**OS:** 

Linux, Debian 64-bit (XUbuntu 16.04)

**Issue Descriptions:** 

The settings file has an entry for lastPage, so it can load the last page on startup. But I like to sync all my dotfiles, which I do using a github repo. Having a setting like lastPage that changes without my accord means I need to either revert that line before committing my work or resign myself to having my git history filled with changes to this file. I don't really like either of those options, so would it be reasonable to move that entry to the playback.json file? 

Or create a new file for previous sessions settings. I don't change my miniplayer position, but if I did then those lines would have a similar issue. So maybe put all the settings entries that aren't set manually by the player into a new file. That way people can sync or share their settings file and know it won't be changed without their approval.

**Comment by MarshallOfSound** [comment]
@thepaperpilot To be honest this isn't really a valid use case for the `.settings.json` file.  It's purpose is to store **all** user specific information regarding the player including window position, min / max state and the last URL visited.

I'm not really keen on splitting this up into two files as it introduces a lot of code overhead (two different methods) that would have to be added and maintained throughout the codebase.  All our IPC events would have to be changed to handle "user" and "player" settings.

This is an awful lot of overhead to sync player settings through git which was never an intended purpose of the `.settings.json` file.  It was hidden away in `.config/json_store` so it would be hard for users to modify it.  The player also wouldn't react very well to the file changing while it is open.

I personally would handle this with a pre-commit hook to automatically unstage lines you don't want to commit.  You could write a very simply bash or node script to do this for you 👍 

P.S.  You will soon be able to turn off "saveLastPage" anyway https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/commit/ae8ec76d2c8b201d4c43bc339af4d5e69552cda7
