### ISSUE TITLE
A Java script error occurred in the main process

### ISSUE THREAD

**Issue by Greggho** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1246]
**OS:**
Windows 10 Pro x64
**Issue Descriptions:**

"
A Java script error occurred in the main process

Uncaught exception 
SyntaxError: Unexpected Token
"
![image](https://cloud.githubusercontent.com/assets/20175112/16397333/2656e930-3c9a-11e6-9c2e-ace9eca4adbf.png)

**Steps to Reproduce:**
Open app - from fresh install even... nothing works.
Google play works fine in browsers.

**Comment by MarshallOfSound** [comment]
Delete your settings file at `%APPDATA%/Google Play Music Desktop Player/json_store`
