### ISSUE TITLE
Add song information in the OS X bar controls

### ISSUE THREAD

**Issue by chamini2** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1247]
**OS: OS X**

I was wondering if song information could be added to the OS X bar controls menu:

<img width="170" alt="screen shot 2016-06-27 at 7 06 34 pm" src="https://cloud.githubusercontent.com/assets/2745502/16398688/4c18a1ae-3c9a-11e6-8496-a80366f65063.png">

I don't know if this qualifies as a dupe of #701.

**Comment by MarshallOfSound** [comment]
I don't see how I could possibly fit song information inside that menu?

**Comment by chamini2** [comment]
How about non-clickable rows containing:
<img width="170" alt="screen shot 2016-06-27 at 7 06 34 pm" src="https://cloud.githubusercontent.com/assets/2745502/16399059/3d8f8474-3c9d-11e6-9fa7-cb78e9c03941.png">

**Comment by MarshallOfSound** [comment]
That makes the menu quite large 😆 

What's wrong with using the mini player if you want to see the song info?

**Comment by jostrander** [comment]
I'm not opposed, I use the mpris menu in gnome in a similar way, but obviously that's not available on OS X.

**Comment by chamini2** [comment]
Well, I find the mini player intrusive, but I guess it's just an opinion.

**Comment by chamini2** [comment]
Also, I think the last part of rows could be dropped. I think `Settings` and `Help` (I don't know about `Audio Device`) are not used enough to justify the place there.

**Comment by jostrander** [comment]
Maybe for you, but those are probably widely used by others, especially in other platforms.

**Comment by chamini2** [comment]
That's true, I understand.

**Comment by MarshallOfSound** [comment]
@chamini2 On platforms that aren't OS X the audio device menu is used a lot (I use it far too much on windows too switch between headphones and speakers).  Help is kind of a critical menu as well.

I think it's safe to say (IMO) that if you want to find out what song is playing and you are willing for the process to include a click (the menu would require a click).  Then you can just open the app from the dock 👍

**Comment by chamini2** [comment]
**I** find annoying having to change desktop (music in another one) to get a song's name. But if you think it makes the menu too large, it's OK. Thanks for the discussion 😁.
