### ISSUE TITLE
Thumbnail buttons are dark and almost impossible to see

### ISSUE THREAD

**Issue by TheSpuc** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1248]
**OS:** Windows 10 (64 bit)
**Application Version:** 3.2.5
**Issue Description:** The media controls are dark and almost invisible on dark background
**Steps to Reproduce:** Hover mouse over GPMDP on taskbar
**Expected Result:** Clear media buttons like VLC Media Playeryer
![gpmdp mediacontrol](https://cloud.githubusercontent.com/assets/5766695/16407147/73019d2a-3d12-11e6-9e54-0f35afca85c6.png)
![vlc mediacontrol](https://cloud.githubusercontent.com/assets/5766695/16407146/730186dc-3d12-11e6-8190-7e8374dcfc0f.png)

Suggestion: Maybe have it follow the dark/light theme of the player?

**Comment by MarshallOfSound** [comment]
Not much I can do about this when some people have light backgrounds and I can't read their color preferences.

That dark/light theme of the player doesn't affect the windows color scheme so I don't think I can deal with this
