### ISSUE TITLE
Weird scaling issue on 2.0.0 - maybe 4k related

### ISSUE THREAD

**Issue by RemyFV** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#125]
I just installed the new version and everything's scaling randomly when moused over, screenshot : http://i.imgur.com/VeGbLMJ.jpg

maximizing or restoring the window resets everything for a second but it soon rescales weirdly.

I uninstalled the 2012 VC++ redist I installed to use v1.9.2, uninstalled the 2013 redist included with 2.0, uninstalled and reinstalled the software, nothing helps.

I'm using GPMD on a 4k display, but it worked correctly with the previous version.

also, thanks a lot for this - using it every day :)

**Comment by eddielement** [comment]
Same issue on a 1920x1080 display - maybe it has to do with windows display scaling? I have mine set at 125%.

**Comment by joelpereira** [comment]
Same issue here on a surface pro 2 (1920x1080)

**Comment by MarshallOfSound** [comment]
I'll try look into this later today, but I'll ping @amaitland who might know if this is a CEF bug?

**Comment by MarshallOfSound** [comment]
@joelpereira Do you have display scaling turned on?

**Comment by jwfitt** [comment]
Same issue here on a surface pro 4. Disabling windows high DPI scaling on the .exe properties solves it, but the previous versions scaled just fine on higher res displays.

**Comment by MarshallOfSound** [comment]
The temporary fix for you guys is this
<img width="184" alt="581323765-cefdpibug" src="https://cloud.githubusercontent.com/assets/6634592/12124569/fc45a6cc-b44a-11e5-875a-cf8ee793cacf.png">

**Comment by RemyFV** [comment]
on a 15.6" 4k display it's way too small to be usable, so I reverted to 1.9.2 =)

**Comment by joelpereira** [comment]
Clicking the "Disable display scaling on high DPI settings" fixed the weird display issues, but now things are smaller for my fat fingers. =)
Thanks!

**Comment by MarshallOfSound** [comment]
@RemyFV @joelpereira If it is now too small for you to use you can use the shortcut "Ctrl +" to zoom in.  Not quite the same as DPI scaling but I think it will have the same affect till I can fix this.

Your zoom level is saved on exit aswell so its not going to be annoying :+1:

**Comment by erolfox** [comment]
4K display w/ 150% scaling
x64

symptom: 
  scrolling with wheel, display seem correct scale. 
  but as soon as mouse is moved, scale enlarges,

**Comment by MarshallOfSound** [comment]
@erolfox Have you tried enabling that compatabilty mode option?

**Comment by eturk1** [comment]
@MarshallOfSound where?

did try 100% scaling on Win10, same scaling issue

**Comment by MarshallOfSound** [comment]
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/125#issuecomment-169097043

**Comment by eturk1** [comment]
ah, windows compatibility

that takes care of the flashing and scaling dynamically. now just static too large (see pic)
<img width="540" alt="untitled" src="https://cloud.githubusercontent.com/assets/525280/12132086/3d4ed234-b3cd-11e5-806d-4901eff75465.png">

**Comment by MarshallOfSound** [comment]
Now try the zooming trick in this comment  
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/125#issuecomment-169118970

You can use "Ctrl +" and "Ctrl -" to zoom in and out

**Comment by amaitland** [comment]
@MarshallOfSound You may need to add a call to `Cef.EnableHighDPISupport()`, it's a new method introduced in `45.0.0`

https://github.com/cefsharp/CefSharp/blob/cefsharp/45/CefSharp.Core/Cef.h#L458

Should probably be called in `Program.cs`, somewhere early on, like https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/Google%20Play%20Music/Program.cs#L24

**Comment by MarshallOfSound** [comment]
Thanks @amaitland I'll get a build running now so these guys can test it and I can push out a fix ASAP

**Comment by MarshallOfSound** [comment]
@RemyFV @eddielement @joelpereira @jwfitt @FuzzAU @eturk1 

Can you guys all please try this beta build
64 Bit: https://mega.nz/#!LFdCgQwD!aRcAtkrVgXnbw2Klu6tu2hfWZ2VMoWP_r33EdJJZC1o
32 Bit: https://mega.nz/#!2YkT0DCa!VHDZG3W2LDruQR95-6AWBkkc8mn1JpisWu1_Lrt4NCw

**Comment by eturk1** [comment]
ctrl +/- scales the base graphics, but it graphics quickly redraw.
move the mouse over app and that causes redraw to double scale

vid of error: https://vid.me/rX2C
pressed ctrl- 5 times then scrolled

**Comment by MarshallOfSound** [comment]
@eturk1 Woah, thats actually awful.  Sorry for pushing this out.  I really need a high DPI screen to test though :cry: 

Have you tried the beta builds I just posted

**Comment by FuzzAU** [comment]
When I run the beta build it tells me I need to update, I take it I skip that for now?

**Comment by jwfitt** [comment]
Just tried the beta build, looks like the weird flickering stuff I was getting before that etruk illustrated is gone, BUT the UI is not scaling like it used to in 1.9.6

**Comment by MarshallOfSound** [comment]
@FuzzAU Yeah, ignore the update.  It's just a bit confused

@jwfitt Is your DPI scaling turned off in the compatibility settings still?  Might want to double check that :+1:

**Comment by eturk1** [comment]
no worries @marshall...
I wrote code for 14 years. (last century LOL). I know what it's like. maybe we have a beta test crew to help out?

fresh beta killded the mad continual redraws. well done!
now we just have the scaling issue. mouseover, scroll, interaction doesn't cause any redraws.

now just the scale :)

**Comment by jwfitt** [comment]
Yeah, scaling was enabled in the exe properties, also killed the user data folder the preferences get saved in to be sure.

**Comment by FuzzAU** [comment]
@eturk1 can you explain some steps that cause your scaling to fail?
I can't reproduce. I've got a 3440x1440

**Comment by MarshallOfSound** [comment]
@eturk1  Thats good to hear
I'm assuming that now the zoom does work as a temporary fix for the scaling issues though correct?

@jwfitt Can we try a complete uninstall and reinstall? Sorry for putting you through this but you are basically my guinea pig at the moment :cactus:

**Comment by jwfitt** [comment]
Sorry for not mentioning it, but I did a full windows uninstall and cleared my appdata/roaming prefs directory for the program when it didn't appear to be working and then reinstalled. Same results.
Great program btw! Thanks for the efforts!

**Comment by MarshallOfSound** [comment]
Wait a sec guys
@jwfitt and @eturk1 

If you guys messed around with the zooming shortcuts.  It is very possible that that setting was preserved through an uninstall.  Can you try reseting the zoom with "Ctrl 0" (I think)

**Comment by eturk1** [comment]
win10 x64
4K 3840x2160 @ 150% scaling

@MarshallOfSound , yes, pressing Ctrl- 21 times seems to get it close. ;)
w/ some mad tiny text
<img width="701" alt="untitled" src="https://cloud.githubusercontent.com/assets/525280/12132753/ddd63ca0-b3d3-11e5-8b3c-5348afa24326.png">

**Comment by jwfitt** [comment]
Never messed with the ctrl +/- scaling

It's the core UI as you can see in the main control bar at the top of the program:
![gmp_example](https://cloud.githubusercontent.com/assets/3819172/12132796/31af1086-b3d4-11e5-8667-a1fa916739b4.PNG)

**Comment by eturk1** [comment]
did an uninstall with iobit. should remove any reg entries. 
reinstalled and everything is tiny as @jwfitt 
so, scale of UI and draw surface are similar.

**Comment by MarshallOfSound** [comment]
I think I know how to fix the UI scaling.  But not sure about the scaling inside Google Play Music.  I'm actually at work still so I'll look into this in a few hours when I get home.  Everything I've done so far is through SSH :+1:

**Comment by MarshallOfSound** [comment]
@RemyFV @eddielement @joelpereira @jwfitt @FuzzAU @eturk1 

Got another beta build coming through

**You will have to uninstall the old version before installing this one**
**I didn't increment the version**

Can you guys please try this
64 Bit: https://mega.nz/#!jNFyXZBK!A-q0HxNPwbnbp_S2Yd7HQH1zMG0TGrfM4tIHsBZebWM
32 Bit: https://mega.nz/#!TENWQKTD!CeSkvf3muv4A8kMR-s-HhcvAnHA4Pm66g1pc-dcm5bo

**Comment by eturk1** [comment]
latest build unchanged. still tiny interface.
<img width="701" alt="2016-01-05 8" src="https://cloud.githubusercontent.com/assets/525280/12136907/051b737a-b401-11e5-868d-d82c8fd8e0e1.png">

**Comment by MarshallOfSound** [comment]
@eturk1 Have you reset the zoom?

**Comment by jwfitt** [comment]
Yeah, still mini for me - uninstalled and manually wiped all folders like before. Same tiny UI :/

**Comment by MarshallOfSound** [comment]
@eturk1 @jwfitt 
Another build, this one might look a bit funky
64 bit: https://mega.nz/#!KE9yRQBa!nOKdudFUn7FpZZCd621JovNZ1QNz0CsaGL3oKopi1cA

**Comment by jwfitt** [comment]
Afraid not, same results on clean install

**Comment by MarshallOfSound** [comment]
@jwfitt Can you double check compat settings and everything, Cos it definitely looks different on all 3 computers I have access to

**Comment by jwfitt** [comment]
Double-checked:
![gmp_example2](https://cloud.githubusercontent.com/assets/3819172/12137810/96fa7d70-b408-11e5-8b0b-d5c4f3607dfc.PNG)

**Comment by MarshallOfSound** [comment]
Can I see a screenshot of the player

**Comment by jwfitt** [comment]
Main player controls seem ok, I was primarily noticing the core menu bar being microscopic:
![gmp_example3](https://cloud.githubusercontent.com/assets/3819172/12137987/166e13ae-b40a-11e5-9dad-4af3b32108f0.PNG)

**Comment by MarshallOfSound** [comment]
Did the previous bets look like that as well?

**Comment by jwfitt** [comment]
Yeah, they have all looked essentially the same as far as I could tell. 1.9.6 was the last version where all the UI scaling being handled by windows seemed to work normally with the program.

**Comment by MarshallOfSound** [comment]
OK, so I'm removing the breaking bug tag as it appears to be working properly at the moment apart from the top bar being a bit small.  Pushing out 2.0.1 to handle the buggy DPI thing

**Comment by RemyFV** [comment]
okay I just woke up, so I did not try anything before now. I downloaded and installed the last link you posted here @MarshallOfSound and the scaling seems to work correctly : http://i.imgur.com/qqjt3gS.jpg

the app started up sized for 1/4th the screen (correct for 1080p), but resizing the window didn't break anything and zoom in/out/reset works perfectly like it would in chrome.

the only thing that doesn't resize is the 3 buttons block in the top right windows title bar, but it's really not important.

in that state, for me, the bug is mostly solved and the software perfectly usable - win 10, 4k screen resolution, no compatibility options, windows base scaling at 200%.

I can give you remote access to my laptop on a clean testing session if you want as well, Ammyy or Teamviewer...

**Comment by MarshallOfSound** [comment]
@RemyFV thanks for the detailed report, that clarified what I suspected.  I'm about to push a pre-release and will link it here when I do.  Could you test that in a few minutes and then I'll make the release public.

The remote thing is a nice offer but maybe another time, I'm heading off for the night soon :+1:

**Comment by RemyFV** [comment]
still one last funny bug in that scaling thing : http://i.imgur.com/aymtWmR.jpg
this is the maximum size of the mini player now, it feels all alone and lost in a cruel, cruel desktop x)

anytime for the remote access, thanks for your work!

**Comment by MarshallOfSound** [comment]
Lol, I suspected that would be the case with the mini player because I use hard coded pixel values for it.  I'll have to interpret the DPI manually with that.

**Comment by MarshallOfSound** [comment]
@RemyFV Just published the pre release, could you take a look :+1:

**Comment by RemyFV** [comment]
downloaded, installed, works exactly the same for me (no scaling issue that is, but functionally not different from the megaupload file)  - I even get the "high DPI breaking update" warning at start. should I uninstall everything before reinstalling or is it normal ?

**Comment by MarshallOfSound** [comment]
The DPI warning will be there until I make this release final :)

**Comment by RemyFV** [comment]
and one additional thing : until the mini player can be resized there is no other way to close it and go back to the large UI than killing the entire app since the controls are over the restore button :(

**Comment by MarshallOfSound** [comment]
@RemyFV I just updated the pre-release with a fix that I think will fix the mini player issue.  Could you test them ASAP so I can push out this release.

Cheers

**Comment by RemyFV** [comment]
nope, exactly the same behavior - I can shrink it to almost nothing but the max size is 1/4th what it should be on a 4k display (if you keep the same ratio), controls extend outside the box and over the restore button.

**Comment by MarshallOfSound** [comment]
@RemyFV  did you uninstall the old one first?  You need to completely remove the old ones for these debug builds

**Comment by RemyFV** [comment]
no I didn't, so I did it now - everything works :)

zoom level reset at start and everything was very small but ctrl+ works to resize to whatever you like, and scaling works on the mini player as well. is the maximum size limit really needed though ?

maybe you should put those zoom keys in the startup warning once so people know and are not stuck with a very small UI.

**Comment by MarshallOfSound** [comment]
Will do, releasing now

**Comment by MarshallOfSound** [comment]
@RemyFV Can you do one final test of a version for me.  I just put out a pre-release of 2.0.2

**Comment by RemyFV** [comment]
uninstalled, downloaded, reinstalled - first start with a HUGE scale (~200% of your new base scale apparently), ctrl-0 reset to a usable size which seems to be the same scale as on a 1080p resolution.

mini player controls are huge as well, and resizing the box does not affect them.

**Comment by MarshallOfSound** [comment]
So to clarify @RemyFV 
Initial Load everything was far too big (This was due to your previous zoom value)
After resetting the zoom everything was correct

Mini player controls are correct or incorrect??

**Comment by RemyFV** [comment]
> Initial Load everything was far too big (This was due to your previous zoom value) After resetting the zoom everything was correct

yes.

> Mini player controls are correct or incorrect??

incorrect, attaching screenshot soon.

**Comment by RemyFV** [comment]
and actually key combinations work on the mini, ctrl-0 reset to standard size - window might not have been active when I tried the first time... sorry about that, wasting your time :(

**Comment by MarshallOfSound** [comment]
Can we ensure that resizing the mini player doesn't screw with the sizing?

**Comment by RemyFV** [comment]
just tried it, reopening the mini player and resizing the window goes back to the huge scaling even if I reset the zoom in between every action.

the main window does not display this behavior and keeps zoom level consistent between app launchs, though.

**Comment by MarshallOfSound** [comment]
@RemyFV Fix incoming on the 2.0.2 pre-release

**Comment by RemyFV** [comment]
everything works fine with the last 2.0.2 release :)

any address I can use to paypal you a beer or two ?

**Comment by MarshallOfSound** [comment]
There is a paypal button on the README if you want to :+1: 

:beer:

**Comment by MarshallOfSound** [comment]
@RemyFV @eddielement @eturk1 @joelpereira @FuzzAU @yopspanjers @FuzzAU 
Hey guys,

I think I have completely nailed this fix now.  UI Scaling on all components seems to be working.
Check out the builds below:  
[x86 Build](https://ci.appveyor.com/api/buildjobs/k169oa7gx74willf/artifacts/Google%20Play%20Music.Bootstrapper/bin/x86/Release/Google%20Play%20Music%20Desktop%20Player%20x86.exe)
[x64 Build](https://ci.appveyor.com/api/buildjobs/58g0xct0kkaty6fd/artifacts/Google%20Play%20Music.Bootstrapper/bin/x64/Release/Google%20Play%20Music%20Desktop%20Player%20x64.exe)

Hopefully these builds work perfectly :+1:
