### ISSUE TITLE
Windows crashed. Now I can't open the app, even after an uninstall and reinstall?

### ISSUE THREAD

**Issue by conzorz** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1251]
**OS: Windows (10)**

**Issue Descriptions: I just get a popup saying "Javascript: Error on Main Thread."**

**Steps to Reproduce: Keeps happening every time I try to open the program now, and Player then just doesn't open.**

**Comment by MarshallOfSound** [comment]
Delete your settings file found at

`%APPDATA%/Google Play Music Desktop Player/json_store`

**Comment by conzorz** [comment]
Can't find the directory... Found a packages.json and deleted it but no luck..?

**Comment by jostrander** [comment]
Well, you probably shouldn't have deleted that. The Location above should exist, and it should contain a file called `.settings.json`. If you have to remove the entire `%APPDATA%\Google Play Music Desktop Player` directory and reinstall.

**Comment by conzorz** [comment]
It's just in recycle bin, I'll restore and search that now, thanks.
