### ISSUE TITLE
Instaler error on Windows 10 

### ISSUE THREAD

**Issue by rsinuhe** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1252]
**Windows 10 64 bit - Build 10586.420 :**

**Installer error**
[squirrelLog.txt](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/339960/squirrelLog.txt)

The Installer for Windows doesn't work and generates an error log. I downloaded the installer from the web page on June 23 2016. When the installer runs it only shows an error (attached log)

**Comment by MarshallOfSound** [comment]
```
Access to the path 'C:\Users\rafaer\AppData\Local\GPMDP_3\app-3.2.5\squirrel.exe' is denied.
```

That sounds like you are installing on a work computer with an access policy set to disable APPDATA access.

Unfortunately there is nothing I can do about this 😢
