### ISSUE TITLE
WebView Fails to load contents of: https://play.google.com/music/listen

### ISSUE THREAD

**Issue by pchertok** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1256]
**OS:**
Windows 7

**Issue Descriptions:**
In an environment with a corporate proxy - launching the player will display the loading spinner but then will just go to a full white view - never loading the contents of https://play.google.com/music/listen . Visiting that URL in any browser works as expected.

**Comment by pchertok** [comment]
Tried using the following lines and all failed:

  _electron.app.commandLine.appendSwitch('proxy-auto-detect', 'true');
  _electron.app.commandLine.appendSwitch('proxy-server', '
http://myproxy.serverver');
  _electron.app.commandLine.appendSwitch('proxy-pac-url', '
http://myproxypacfile.pac');

I got the list from here:

https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md

On Thu, Jun 30, 2016 at 10:50 AM, Samuel Attard <notifications@github.com>
wrote:

> Can you try running it with the --proxy-auto-detect flag?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/1256#issuecomment-229682150>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABWs7R5yJkJKP_z4FcLtPi-U3752AEegks5qQ9fIgaJpZM4JCJ1m>
> .
>



-- 
Phillip Chertok

**Comment by MarshallOfSound** [comment]
If those URL's don't work I don't know what to say 😢 

Are you sure you are using the correct proxy URL's, others have reported success with those flags?

**Comment by pchertok** [comment]
Yeah i'm sure.  It's the same proxy I use for npm

On Thu, Jun 30, 2016 at 11:04 AM, Samuel Attard <notifications@github.com>
wrote:

> If those URL's don't work I don't know what to say 😢
>
> Are you sure you are using the correct proxy URL's, others have reported
> success with those flags?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/1256#issuecomment-229686943>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABWs7fPJeqUJHDNl91mdvq8oNen94glIks5qQ9sUgaJpZM4JCJ1m>
> .
>



-- 
Phillip Chertok

**Comment by pchertok** [comment]
Could it be possible I'm adding the code in the wrong location?  I was
modifying 'index.js' of the main process.  Do you have an example of where
the proxy could should go?

On Thu, Jun 30, 2016 at 11:07 AM, Phillip Chertok <pchertok@gmail.com>
wrote:

> Yeah i'm sure.  It's the same proxy I use for npm
>
> On Thu, Jun 30, 2016 at 11:04 AM, Samuel Attard <notifications@github.com>
> wrote:
>
>> If those URL's don't work I don't know what to say 😢
>>
>> Are you sure you are using the correct proxy URL's, others have reported
>> success with those flags?
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/1256#issuecomment-229686943>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/ABWs7fPJeqUJHDNl91mdvq8oNen94glIks5qQ9sUgaJpZM4JCJ1m>
>> .
>>
>
>
>
> --
> Phillip Chertok
>



-- 
Phillip Chertok

**Comment by MarshallOfSound** [comment]
They need to be actual command line params.

I.e. Launch the program from CMD

`Google Play Music Desktop Player.exe --proxy-auto-detect`  
or
`Google Play Music Desktop Player.exe -- --proxy-auto-detect`

**Comment by MarshallOfSound** [comment]
Merging in to #921
