### ISSUE TITLE
Add volume control in mini player

### ISSUE THREAD

**Issue by chrismccracken** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1258]
**OS:**
Mac OSX El Capitan (10.11.5) 

**Issue Descriptions:**
The volume control slider is a critical control in the full player, and should be added to the mini player. When using a digital-out audio device, the system volume controls are neutered and volume control needs to be adjustable at the app level.

**Steps to Reproduce:**
Switch to mini player. No volume control is present.

**Comment by jostrander** [comment]
The current mini-player doesn't have the ability currently to add a visible volume control, however there is an optional but default enabled scroll based volume. If you hover the mini-player and scroll the volume should

**Comment by chrismccracken** [comment]
Cool, the scroll volume is nice. I'm glad you mentioned that, it would have scared the crap out of me if I found it accidentally and blasted the volume.

**Comment by jostrander** [comment]
That was an issue a while back, and it was requested to be made optional, which I believe will be released in 3.3.0 actually.

**Comment by MarshallOfSound** [comment]
Scrolling is the current way to change volume.

When I rebuild the mini player in will try to find a way to add a volume slider.
