### ISSUE TITLE
Clicking fullscreen button fails to make it full screen; causes screen to rapidly flash instead

### ISSUE THREAD

**Issue by 0ffkilter** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1261]
Operating System:  Antergos Linux, using i3-wm

GPMDP built from AUR here : https://aur.archlinux.org/packages/gpmdp/

Issue: Clicking the fullscreen button fails to work, instead the entire screen rapidly flashes until program is exited.

Screen recorded here (warning for flashing lights) https://gfycat.com/LikableMatureFunnelweaverspider

Reproduction Steps:
  Assuming same operating system
1.  Click full screen button
2.  Cover eyes before you get a headache.

**Comment by MarshallOfSound** [comment]
That is not a full screen button.  That's the mini player button and it's because i3 refuses to listen to our window size change calls.

We attempted to work around this by calling undock on the window when in mini player mode.  But other than that, nothing we can do

**Comment by 0ffkilter** [comment]
Oh okay, thanks for the reply.
