### ISSUE TITLE
[OSX] Can't get out of mini-player without quitting

### ISSUE THREAD

**Issue by necrogami** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1262]
**OS:** macOS 10.11.5 El Capitan

**Issue Descriptions:**
After clicking the mini player icon in the bottom right i can no longer get to the full sized player without quitting.

**Steps to Reproduce:**
Press mini player icon in lower right and try and go back.

I've tried going back by clicking mini player again (expected result)
Also i've gone to window and slected mini player and then full player and neither are allowing the window to go back to full sized.

**Comment by necrogami** [comment]
After re-sizing the window now it's functioning properly. 
Both Window menu and button function now. This is an odd bug.

**Comment by MarshallOfSound** [comment]
Sounds like a one off IPC socket glitch, unless you can reproduce consistantly 👍
