### ISSUE TITLE
Mini Lyrics

### ISSUE THREAD

**Issue by dehen** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1263]
Wonderful work. I love this app for its desktop integration and lyrics mode especially.

I just wanted to recommend a Mini-Lyrics mode of some sort. Mainly, the way I use lyrics mode is to turn it on while I'm working on something else. The current mode is great while I'm cooking, for instance.

But when I'm working on my computer, I like to place the lyrics in a thin window to the right of my working window:

![screenshot from 2016-07-03 13-21-41](https://cloud.githubusercontent.com/assets/10331141/16547180/e8dff664-4121-11e6-894b-8769c3f6cdcf.png)

This ends up being clunky for a couple reasons. The font is so big you get lots of line-wrapping. Also, when the full window is made this small, you lose access to play buttons and it ends up leading to a lot manual resizing.

Is there any chance you could add some sort of lyrics/miniplayer hybrid in the future? Maybe just making the fonts in lyricsmode react to the window width, and adding the miniplayer overlays would be enough?

Either way, thanks again for your work.

**Comment by MCManuelLP** [comment]
I think I'll look into it... Maybe there's an easy way to make the font size somewhat variable...

**Comment by MarshallOfSound** [comment]
@MCManuelLP Only look into the font-size variablility.

I'm completely overhauling the mini player so there is no point targetting that 👍

**Comment by MCManuelLP** [comment]
Okay, so I have something...
```css
@media (max-width: 600px) {
  p {
    font-size:4.5vw !important;
  }
}
```
I'm not quite sure about the exact values, 600px seems fine for me (It's about ½ of my screen width)
So is there some way to get the screen width?
And 4.5 viewport width as text size seems to be the best middle ground altogether...
![screenshot-2016-07-04-10-07-06](https://cloud.githubusercontent.com/assets/5896952/16554436/2a59d774-41cf-11e6-96a8-54abfbf4e264.png)
![screenshot-2016-07-04-10-07-34](https://cloud.githubusercontent.com/assets/5896952/16554450/3e4b0000-41cf-11e6-8f38-2514ac247544.png)

**Comment by MarshallOfSound** [comment]
Can we add a few more breakpoints.

maybe 1/3 your screen
1/4 your screen
and the width you have now.


Just so people with strange resolutions aren't caught out

**Comment by MCManuelLP** [comment]
Hmm, how do you mean..? I currently have this:
```css
@media (max-width: 550px) { //~40%
  p {
    font-size: 4.5vw;
  }
}
@media (max-width: 250px) { //~20%
  p {
    font-size: 12px;
  }
}
```
I'd have to replace the width px numbers with variable ones... 
But otherwise this should cover most 'weird' display resolutions and ensure that the font doesn't get too small...

**Comment by MarshallOfSound** [comment]
Just replace `px` with `em` then it depends on users font sizes, which is what matters here 😆

**Comment by MCManuelLP** [comment]
Hmm, `#lyrics p` also uses px, so I didn't think about that, let's see...
