### ISSUE TITLE
Instalation Failed on Windows 10 64bits

### ISSUE THREAD

**Issue by santidavel** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1264]
**OS:**
Windows 10 64 bits

**Issue Descriptions:**
Instalation Failed

**Steps to Reproduce:**
1. Open Google.Play.Music.Desktop.Player.exe
2. After the Installing Screen with the Animation, an error screen appears with the following:
http://imgur.com/ij3Ywil

Setup Log:
http://pastebin.com/MWL91j8g

Thanks in advance (:

**Comment by MarshallOfSound** [comment]
Please delete the install folder and try again.

if that fails, try running the installer as admin

**Comment by santidavel** [comment]
I'm not sure which is the installation folder, but I've removed everything from C:\Users\Santiago\AppData\Local\SquirrelTemp
and from C:\Users\Santiago\AppData\Local\GPMDP_3 but without solution. I've tried looking for everything named GPMDP and google music, I've deleted everything I could but without success. Also done it and try to ran it with administrator but still having the same issue as before :/

Thank you!

**Comment by santidavel** [comment]
I managed to solve it! just had to change the default installation settings in storage options to the C drive. As I'm using an SSD only for my OS files, I changed the default location to D. Here's the screenshot with where it can be modified.

http://imgur.com/a/FGTX8

Thanks to the developer for such an amazing app!
Cheers.

**Comment by MarshallOfSound** [comment]
Hmmm, this seems like an issue with Squirrel.Windows.

I'll raise it up there
