### ISSUE TITLE
Request: Add option to hide system tray icon

### ISSUE THREAD

**Issue by YuukiMinoru** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1266]
There is an option to minimise to system tray, but no option to not use the system tray at all.

**Comment by MarshallOfSound** [comment]
This has been raised a few times and declined every time.  Lots of functionality depends on the tray icon and it plays a critical role in controlling the app

**Comment by YuukiMinoru** [comment]
Perhaps this should be added to the FAQ? If its coming up frequently.
