### ISSUE TITLE
When playing a Podcast the window title bar does not update.

### ISSUE THREAD

**Issue by knowspick** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1267]
**OS:**
Windows 10

**Description:**
When playing a Podcast the window title bar does not update.

**Steps to Reproduce:**
Play a podcast episode. Notice that the windows title bar does not change

**Comment by MarshallOfSound** [comment]
Gonna need someone in the US to look into this.  I'm pretty sure out `gmusic.js` library isn't ready to handle podcasts.

**Comment by walteranderson** [comment]
Being from the US, I thought I'd poke around at this to see if I found out anything useful.

Looks like when you play a podcast episode it triggers the `change:state` event. That will fetch the current song information using `PlaybackAPI.currentSong()`. When I examine the return object while playing a podcast, I get:

```
{ title: null, artist: null, album: null, albumArt: null }
```

In this use-case the title updates to "Unknown Song - Unknown Artist". If I play a song first and then switch to a podcast, the song object won't update so the title stays as that initial song.

It seems like whatever is updating `this.data.song` within `PlaybackAPI.js` just doesn't know how to handle podcasts.

**Comment by jostrander** [comment]
This is an issue in the underlying library, which is currently under a transition to es6. As soon as that's complete I'll add in a fix for the podcasts.

**Comment by jostrander** [comment]
Fixed in f2aee26049a0950fd5d921a49b492f40c3f38523 recently, or technically speaking efbfa55f1106eb09b4733ecccc0c6f9b71cebaa3 originally.
