### ISSUE TITLE
Controls

### ISSUE THREAD

**Issue by shutitdown** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1270]
Unfortunately still having an issue with the controls in version 3.0 on OS X El Capitan 10.11.5 (running on a Macbook Pro Retina mid 2014)

- Media keys still don't respond (they do in other apps), I don't have Chrome installed so that eliminates interference from the extension. Even so I didn't have the extension installed while I had Chrome.

- Still unable to reset hot keys, page is completely unresponsive once opened.

- Voice controls never worked (but I expect that from this experimental feature so thats not really an issue)

I've uninstalled the app and installed once more and reset my computer. Neither helped.

**Comment by MarshallOfSound** [comment]
I really hope you mean `3.3` 😆 

> Media keys still don't respond

The media keys will not work if another Chromium based application has "claimed" them.  You might want to check any other Electron based applications.

> Still unable to reset hot keys, page is completely unresponsive once opened.

These issues are starting to get annoying, a quick search of the pre-existing issues explains how to use that page.  But I'll put them here to save time...

1. Click the box for the shortcut you want to set
2. Perform the shortcut (Something like "Control + Shift + P")
3. Tada

**Comment by MCManuelLP** [comment]
Maybe we should expand that disclaimer on the hotkeys settings tab to include those restrictions...
