### ISSUE TITLE
System tray icon does not show: Uncaught Exception: Error processing argument at index 0, conversion failure from /usr/share/google-play-music-desktop-p

### ISSUE THREAD

**Issue by sasha-** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1271]
An uncaught exception was reported.  
#### Info:
**OS:** linux - Ubuntu 14.04
**Arch:** x64
**GPMDP Version:** 3.3.0
**Time:** Mon Jul 04 2016 14:14:26 GMT-0300 (ADT)

#### Error:
*Error processing argument at index 0, conversion failure from /usr/share/google-play-music-desktop-p*
```js
TypeError: Error processing argument at index 0, conversion failure from /usr/share/google-play-music-desktop-player/resources/app/build/assets/img/main.ico
    at TypeError (native)
    at Object.<anonymous> (/usr/share/google-play-music-desktop-player/resources/app/build/main/features/core/tray.js:9:837)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/google-play-music-desktop-player/resources/app/build/main/features/core/index.js:9:178)
```
This issue was created automatically inside the `uncaughtException` handler

I worked around this by replacing /usr/share/google-play-music-desktop-player/resources/app/build/assets/img/main.ico file with my own png icon sized png icon.  I guess I am missing something that can covert ico image.

Also, clicking on the tray icon does not bring up app when it is minimized to the tray or to the taskbar.
Right-clicking on the tray icon > Show, shows app but minimized to the taskbar, so another click on the taskbar tile is needed to bring it up.
I worked around those by having another taskbar/launcher tile which simply calls google-play-music-desktop-player which starts the app, or if it is already started and minimized, brings it to the foreground.

**Comment by MarshallOfSound** [comment]
Lol wut, why is Ubuntu claiming to be KDE?

**Comment by jostrander** [comment]
KDE is a window manager, kubuntu is just Ubuntu with KDE preinstalled as
the main window manager. Not totally uncommon.

**Comment by MarshallOfSound** [comment]
Well regardless this error appears to be because this tray manager doesn't support `.ico` files as tray images....

**Comment by jostrander** [comment]
That's also entirely possible. Maybe we do a try catch and fall back to the PNG? Welcome to Linux lol
