### ISSUE TITLE
Only one Chromecast speaker appears in list

### ISSUE THREAD

**Issue by budge999** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1272]
**OS:**
MacOS 10.11.4 El Capitan

**Issue Descriptions:**
When trying to connect to a Chromecast audio device only one device is shown.  In Chrome on the same computer, all my speakers appear in the list.  All speakers appear from the Google Play Music app on my phone/tablet.

When you connect to the speaker it does work though.

**Comment by MarshallOfSound** [comment]
@budge999 What do you mean "speakers".  I don't think I am familiar with this use case for Chromecast.  Can you explain in detail what you mean.

**Comment by budge999** [comment]
Sorry, maybe should have said all my 'chromecast audio devices and groups' appear in the list.  So for example, I would choose to cast to 'downstairs', which would be a group of 3 chromecast audio devices connected to speakers.

In the desktop player, you click the Cast icon, and only one device is displayed in the 'Choose Cast Device' list.

**Comment by MarshallOfSound** [comment]
@budge999 I assume the one device that appears is the group?

**Comment by jostrander** [comment]
Sorry, didn't have any audio only casts to play with when redeveloping the
cast extension. We'll probably need some device specifics (or some cast
audios ourselves)  in order to properly figure out what is missing from our
discovery API.

**Comment by MarshallOfSound** [comment]
@jostrander Purely taking a guess, the cast devices probably all emit a group with some TXT fields identifying themselves.

@budge999 Do you have `node.js` installed on your system so we can attempt to debug this?

**Comment by jostrander** [comment]
https://github.com/thibauts/node-castv2/issues/26 I was looking into the libraries we use, and even if we get them all showing up I'm not sure the groups will work without this being fixed,

**Comment by MarshallOfSound** [comment]
I want to move this issue upstream to `electron-chromecast`
