### ISSUE TITLE
[Windows] Program is blank on startup and nothing ever shows up except for the settings screen and the loading circle

### ISSUE THREAD

**Issue by nzgamer41** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1273]
**OS:**
Windows 8.1 fully up to date

**Issue Descriptions:**
When I open the program, nothing appears in the window. It is just blank, unless I right click on the tray icon and click settings, then the settings window appears.

**Steps to Reproduce:**
1) Run the latest version of the program from the www.googleplaymusicdesktopplayer.com site on Windows 8.1
2) Watch it not load

**Comment by MarshallOfSound** [comment]
Do you have a proxy or VPN?

**Comment by nzgamer41** [comment]
Nothing on my PC switched on, we do have the LineWize software installed on our school network though which could be the reason, although Google Play Music loads fine on the website on Google Chrome and the Android app on my phone.

**Comment by MarshallOfSound** [comment]
@nzgamer41 Your symptons sound exactly like what happens when your system is using an HTTP proxy.

I'm going to merge this in to #921 

Can you try running the program with the `--proxy-auto-detect` flag?

**Comment by nzgamer41** [comment]
Nope, still a blank screen. I could try switching a VPN on and retrying it

**Comment by nzgamer41** [comment]
Ok, with Ultrasurf on and that proxy auto detect thing, the login page shows up.

**Comment by nzgamer41** [comment]
It's almost like the network proxy blocks that page that comes up first, as if I use ultrasurf until the google play music homepage pops up then switch it off it loads fine. The only issue is that my school has a strong stance on VPNs where if we are caught using them our internet connection is switched off
