### ISSUE TITLE
Album Art Added In App Puts Mini Player In Bad State

### ISSUE THREAD

**Issue by Cistoran** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1278]
**OS:** Windows 10

**Issue Descriptions:**  Album Art Added In App Does Not Populate In Mini Player

**Steps to Reproduce:**

1. Navigate to a playlist that has a song with no album art.
2. Right click the song and click 'Edit Info'
3. Hover over the Album Art section and click 'Change'
4. Browse to and select an image.
5. Click 'Save'
6. Play the song.
7. Click the Mini Player button

**Result:** The album art and song information is not displayed for the song in the mini player.

**Notes:** I've also had it break album art and song information for the song previous to the song changed in a playlist.

**Comment by NoahAndrews** [comment]
Ha! I was just about to report a related issue. When a song comes up in the mini player that doesn't have any album artwork at all, it continues to display the artwork from the previous song.

**Comment by jostrander** [comment]
It should be pulling in an orange default album art. I'll investigate
further if @marshallofsound doesnt get to it first.

**Comment by Cistoran** [comment]
@jostrander 

I've had it do that in relation to this issue, but it will also break and not display song information (Title/Artist).

> It should be pulling in an orange default album art. I'll investigate
further if @marshallofsound doesnt get to it first.

**Comment by jostrander** [comment]
Does it break anything in the full player, or mini player only?

**Comment by Cistoran** [comment]
As far as I can tell, it only breaks things in the mini player.

**Comment by MarshallOfSound** [comment]
Hey guys,

1. I confirmed that the orange art is pulled in when the song doesn't have an albumArt
2. The steps to reproduce don't obviously "break" anything.  The mini player still works normally.

This sounds suspicously like
> I tried to upload a new album art but it ruined my tracks metadata instead

This is nothing to do with GPMDP 👍 We don't manage the metadata or change the albumArt, that is all handled by Google.  If when you upload the image something goes wrong that is on their side not ours.
