### ISSUE TITLE
enableWindowTitleInfo secret setting not respected

### ISSUE THREAD

**Issue by DecoyJoe** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1279]
**OS:**
Windows 10

**Issue Descriptions:**
On version 3.3.0, window title is being changed to name of currently playing track by default, even though ".settings.json" contains `"enableWindowTitleInfo": false`

**Steps to Reproduce:**
Set `"enableWindowTitleInfo"` to `false` in `%USERPROFILE%\AppData\Roaming\Google Play Music Desktop Player\json_store\.settings.json`, window title will still be changed to currently playing track info.

**Comment by jostrander** [comment]
That secret setting was deprecated and the window titles should be present
at all times now. Afaik.

**Comment by MarshallOfSound** [comment]
That secret setting was temporary and as @jostrander said, now dpreceated
