### ISSUE TITLE
2.0 severly borked: scaling too large

### ISSUE THREAD

**Issue by erolfox** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#128]
v2.0 was just offered when I launched. upgaded. Not usable now. need to revert

pic shows bloated scaling. the app now flashes when loading, extra windows come and go. scale about double and not usable.

<img width="810" alt="2016-01-05" src="https://cloud.githubusercontent.com/assets/525280/12131712/fe27a07a-b3c9-11e5-8817-13586d5ab104.png">

**Comment by MarshallOfSound** [comment]
See #125 for temporary workaround, I'm considered a official rollback release but trying to figure out how widespread the issue it
