### ISSUE TITLE
Update and About dialogs block all controls in mini mode

### ISSUE THREAD

**Issue by valrus** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1280]
OS: Windows 7

Issue Descriptions: I got an update dialog when the player was in mini mode and there's no good way to accept or dismiss it; clicking on the text to try to scroll it down just moves the window. See screenshot. 
![screenshot 88](https://cloud.githubusercontent.com/assets/343665/16602198/03daf8e6-42c7-11e6-98f6-6f8b87672176.jpg)
I managed to fix it by clicking erratically a bunch and eventually getting it to select the text so I could scroll the dialog box down and reach the buttons, but that probably shouldn't be necessary. The scroll wheel doesn't work in the dialog box either.

Just noticed this happens with the Help > About dialog box too, though I could dismiss that with Esc; I couldn't do so with the update box.

Steps to Reproduce: Be in mini mode when an update dialog comes up. Or have the player in mini mode and select Help > About from the system tray menu.

**Comment by MarshallOfSound** [comment]
This was fixed in the latest release 😆  But unfortunately it sill happened for this release (if you think about it it makes sense) 👍
