### ISSUE TITLE
Not all Chromecast devices found

### ISSUE THREAD

**Issue by Khordes** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1285]
**OS:Ubuntu 16.04 LTS

**Issue Descriptions:**
I have 3 chromecast devices on my network that chrome is able to pick up.  I have a v1, v2, and Chromecast Audio.  In phone apps and chrome across devices these can all be found.

When using the cast button in GPMDP v3.3 it only detects the v2 chromecast.  I don't care so much about the v1 chromecast, but i was surprised it didn't detect the chromecast audio.  That would be the one I'd most likely cast to so I noticed it was missing straight away.

I did see another chromecast bug report but this seemed sufficiently different to justify a differnt bug report.  Let me know if I should just consolidate on that thread.  Known issue with Chromecast Audio maybe?

**Steps to Reproduce:**
Open GPMDP 3.3 and try to cast.  Only see 1 cast device.

**Comment by MarshallOfSound** [comment]
I'm going to merge this into the issue that doesn't exist yet on `electron-chromecast` 😆 

The CC audio thing is a known issue, but v1 is something I wasn't aware of.

Unfortunately fixing these things requires actually having one of the devices, so considering @jostrander and I only have CC v2 this might take a while to track down

**Comment by MarshallOfSound** [comment]
@Khordes Do you have `avahi` installed and running?

**Comment by Khordes** [comment]
Hi, I do have it installed and running:
`$  systemctl list-units | grep avahi`
`avahi-daemon.service                                                                                  loaded active running`
` avahi-daemon.socket                                                                                   loaded active running`

Thanks for the response!  Let me know if I can provide any additional info to make it easier to test?

**Comment by MarshallOfSound** [comment]
Can you follow the instructions in this comment

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/1265#issuecomment-230197771

**Comment by MarshallOfSound** [comment]
@jostrander This issue appears to be related to the JS library not finding castV1 devices.  When someone in gitter installed bonjour (on windows) it started finding the older device

**Comment by Khordes** [comment]
I tried the instructions last night and got a series of errors to work through.  I'll try again after work today to go through them if still needed.....
