### ISSUE TITLE
Uncaught Exception: Attempting to call a function in a renderer window that has been closed or released. Function provid

### ISSUE THREAD

**Issue by justinhilles** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1287]
An uncaught exception was reported.  
#### Info:
**OS:** darwin
**Arch:** x64
**GPMDP Version:** 3.3.0
**Time:** Thu Jul 07 2016 08:10:24 GMT-0700 (PDT)

#### Error:
*Attempting to call a function in a renderer window that has been closed or released. Function provid*
```js
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: mouseButtonNavigation.js:9:1249.
    at BrowserWindow.callIntoRenderer (/Applications/Google Play Music Desktop Player.app/Contents/Resources/electron.asar/browser/rpc-server.js:186:19)
    at emitOne (events.js:101:20)
    at BrowserWindow.emit (events.js:188:7)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by justinhilles** [comment]
Tell me what im doing wrong and ill gladly not submit these, but so far today, I opened the app and it threw this again

**Comment by MarshallOfSound** [comment]
We are doing everything we can to stop the error being thrown... But I have no idea what more we can do.  Closing as "cantfix"....

These issues make me cry 😢

**Comment by justinhilles** [comment]
Sounds good
