### ISSUE TITLE
Play Music Desktop Client Issues

### ISSUE THREAD

**Issue by leadinurface** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#129]
![play music issues 2](https://cloud.githubusercontent.com/assets/16569108/12134015/978c42b8-b3f0-11e5-9749-c2d99a49e5c7.png)
![play music issues 3](https://cloud.githubusercontent.com/assets/16569108/12133910/9d457f90-b3ef-11e5-8e61-b96ee24dff07.png)
![play music issues](https://cloud.githubusercontent.com/assets/16569108/12133913/9d46f0f0-b3ef-11e5-9141-5d7d4490565e.png)
![play music when it works 1](https://cloud.githubusercontent.com/assets/16569108/12133912/9d467eb8-b3ef-11e5-87a2-75281612db6c.png)

       

       So it does this and wont click on the buttons correctly when i click right in the middle of the selected button all the way to slightly below and to the left of each either minimize maximize and exit. When i click on minimize in the center of the button it maximizes the program.  It does this regardless of the position on the screen and whether it is windowed or
full screen
However when i click right near the top of the screen, within maybe a millimeter, each button works and highlights correctly.  I am running windows 7 home premium service pack 1, GTX 675m, core i7-3610QM, 16 GB ram.  
Thanks for taking a look Samuel, hope your new years is going well.

**Comment by leadinurface** [comment]
So it does this and wont click on the buttons correctly when i click right in the middle of the selected button all the way to slightly below and to the left of each either minimize maximize and exit. When i click on minimize in the center of the button it maximizes the program.  It does this regardless of the position on the screen and whether it is windowed or full screen
However when i click right near the top of the screen, within maybe a millimeter, each button works and highlights correctly. I am running windows 7 home premium service pack 1, GTX 675m, core i7-3610QM, 16 GB ram.

Thanks for taking a look Samuel, hope your new years is going well.

edit: formatting was weird

**Comment by MarshallOfSound** [comment]
Ahh, this is an ongoing issue that's being tracked in #31 

I keep looking for solutions but its quite tricky.  Windows 7 is the problem :100: 

I'll close this as its  a duplicate, you can "follow" issue #31 if you want updates on this

**Comment by leadinurface** [comment]
:D thanks sorry bout that

**Comment by MarshallOfSound** [comment]
All good :smile:
