### ISSUE TITLE
Cast function only sees one of the two Chromecasts active in area

### ISSUE THREAD

**Issue by hadesgamma** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1292]
OS : Windows 10 Home 
I have two Chromecasts active on the ground floor of my house, one normal Chromecast plugged into a TV, and a Chromecast audio plugged into the aux input of a stereo system. When both Chromecasts are active, the player only displays one of them. This seems to be random, as yesterday I could only select the Chromecast audio and today I can only select the one connected to the TV. Unplugging the Chromecast connected to the TV allowed me to select the Chromecast Audio.

**Comment by MarshallOfSound** [comment]
Can you please download and run the `mdns-test.exe` file inside this folder.

https://mega.nz/#!GFVCTawS!hIUyunn8xaZfYCMIIywTyTwYEU5gXyCScp6xHreFBqg

Then copy and paste whatever appears in the application into a comment here 👍

**Comment by hadesgamma** [comment]
I'm just getting a blank white screen when I run it.

**Comment by MarshallOfSound** [comment]
Hmmm, can you install bonjour real quick.  It might be that our JS fallback is a bit buggy.

samuelattard.com/files/bonjourcore2.msi

**Comment by hadesgamma** [comment]
{
	"interfaceIndex": 3,
	"type": {
		"name": "googlecast",
		"protocol": "tcp",
		"subtypes": [],
		"fullyQualified": true
	},
	"replyDomain": "local.",
	"flags": 3,
	"name": "Alec's Chromecast",
	"networkInterface": "Ethernet",
	"fullname": "Alec's\\032Chromecast._googlecast._tcp.local.",
	"host": "Alec's\\032Chromecast.local.",
	"port": 8009,
	"txtRecord": {
		"id": "05fef22fa8e4cb57f6e639e6dcaafdfc",
		"rm": "",
		"ve": "05",
		"md": "Chromecast Audio",
		"ic": "/setup/icon.png",
		"fn": "Alec's Chromecast",
		"ca": "4100",
		"st": "1",
		"bs": "FA8FCA90BBFE",
		"rs": "Google Play Music"
	},
	"addresses": [
		"10.0.0.13"
	]
}

{
	"interfaceIndex": 3,
	"type": {
		"name": "googlecast",
		"protocol": "tcp",
		"subtypes": [],
		"fullyQualified": true
	},
	"replyDomain": "local.",
	"flags": 3,
	"name": "Mom's Chromecast",
	"networkInterface": "Ethernet",
	"fullname": "Mom's\\032Chromecast._googlecast._tcp.local.",
	"host": "Mom's\\032Chromecast.local.",
	"port": 8009,
	"txtRecord": {
		"id": "e60e1528ae306d566560af1cdcb7d5d1",
		"rm": "CBBA228AF48D95A0",
		"ve": "05",
		"md": "Chromecast",
		"ic": "/setup/icon.png",
		"fn": "Mom's Chromecast",
		"ca": "4101",
		"st": "0",
		"bs": "FA8FCA934798",
		"rs": ""
	},
	"addresses": [
		"10.0.0.15"
	]
}

{
	"interfaceIndex": 4,
	"type": {
		"name": "googlecast",
		"protocol": "tcp",
		"subtypes": [],
		"fullyQualified": true
	},
	"replyDomain": "local.",
	"flags": 3,
	"name": "Alec's Chromecast",
	"networkInterface": "Wi-Fi",
	"fullname": "Alec's\\032Chromecast._googlecast._tcp.local.",
	"host": "Alec's\\032Chromecast.local.",
	"port": 8009,
	"txtRecord": {
		"id": "05fef22fa8e4cb57f6e639e6dcaafdfc",
		"rm": "",
		"ve": "05",
		"md": "Chromecast Audio",
		"ic": "/setup/icon.png",
		"fn": "Alec's Chromecast",
		"ca": "4100",
		"st": "1",
		"bs": "FA8FCA90BBFE",
		"rs": "Google Play Music"
	},
	"addresses": [
		"10.0.0.13"
	]
}

{
	"interfaceIndex": 4,
	"type": {
		"name": "googlecast",
		"protocol": "tcp",
		"subtypes": [],
		"fullyQualified": true
	},
	"replyDomain": "local.",
	"flags": 2,
	"name": "Mom's Chromecast",
	"networkInterface": "Wi-Fi",
	"fullname": "Mom's\\032Chromecast._googlecast._tcp.local.",
	"host": "Mom's\\032Chromecast.local.",
	"port": 8009,
	"txtRecord": {
		"id": "e60e1528ae306d566560af1cdcb7d5d1",
		"rm": "CBBA228AF48D95A0",
		"ve": "05",
		"md": "Chromecast",
		"ic": "/setup/icon.png",
		"fn": "Mom's Chromecast",
		"ca": "4101",
		"st": "0",
		"bs": "FA8FCA934798",
		"rs": ""
	},
	"addresses": [
		"10.0.0.15"
	]
}

{
	"interfaceIndex": 3,
	"type": {
		"name": "googlecast",
		"protocol": "tcp",
		"subtypes": []
	},
	"replyDomain": ".",
	"flags": 3,
	"networkInterface": "Ethernet"
}

{
	"interfaceIndex": 3,
	"type": {
		"name": "googlezone",
		"protocol": "tcp",
		"subtypes": []
	},
	"replyDomain": ".",
	"flags": 3,
	"networkInterface": "Ethernet"
}

{
	"interfaceIndex": 4,
	"type": {
		"name": "googlecast",
		"protocol": "tcp",
		"subtypes": []
	},
	"replyDomain": ".",
	"flags": 3,
	"networkInterface": "Wi-Fi"
}

{
	"interfaceIndex": 4,
	"type": {
		"name": "googlezone",
		"protocol": "tcp",
		"subtypes": []
	},
	"replyDomain": ".",
	"flags": 2,
	"networkInterface": "Wi-Fi"
}

**Comment by MarshallOfSound** [comment]
Oooooh, this is actually really interesting.  Can you move into [gitter](https://gitter.im/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-) for a quick chat?

**Comment by Alipoodle** [comment]
{
	"interfaceIndex": 10,
	"type": {
		"name": "GPMDP",
		"protocol": "tcp",
		"subtypes": []
	},
	"replyDomain": ".",
	"flags": 3,
	"networkInterface": "Wi-Fi"
}

**Comment by Alipoodle** [comment]
This picture will show that it can be seen on my computer.
![Image](http://puu.sh/q3UNo/42093606f2.png)

**Comment by MarshallOfSound** [comment]
@Alipoodle .... That's your mistake...  That isn't a cast device.  That's a DLNA device.........  I can't use Chromecast protocols to stream Google play music to it....

**Comment by Alipoodle** [comment]
>.< Oh. From before you said that i could.

**Comment by MarshallOfSound** [comment]
I also seem to remember asking if Sonos was Google Cast enabled and someone saying "Yes" and they were wrong 😆

**Comment by ccicchitelli** [comment]
Hi All, does Sonos currently work with this cast from this app? It's working fine from my Play Music app for Android, but the speaker does not appear as a cast device in the desktop app. Thanks!!
