### ISSUE TITLE
Media keys not working on Ubuntu 16.04

### ISSUE THREAD

**Issue by knnnrd** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1294]
OS: Ubuntu 16.04 with Linux kernel 4.6.2-040602-generic

Plain and simple, none of my media keys are working.

**Comment by jostrander** [comment]
- Were they working before?
- Which version of the app are you using?
- Which version of the app _were_ you using (if applicable)?
- Do you media keys work in other programs like rhythmbox/vlc/etc?

**Comment by knnnrd** [comment]
No they have never worked so far.
I am using version 3.2.5.
My media keys do work for programs such as rhytmbox, vlc, etc..

**Comment by jostrander** [comment]
Can you update to version 3.3.0 and see if they still are not working?

**Comment by knnnrd** [comment]
Ok that fixed it! Sorry about that.. should have checked for an update myself first.
Thanks!
