### ISSUE TITLE
GPM Favicon No Longer Displayed In Icon Tray

### ISSUE THREAD

**Issue by Church185** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1295]
OS:  Windows 10 Pro, 64-bit

Stated Fix: "FIX: Tray icon is now the GPM favicon" actually broke the displayed icon in the tray.  3.2.5 had the GPM favicon.  Now in 3.3.0 tray icon is back to the orange music note.

**Comment by berryelectronics** [comment]
The favicon is the lil icon you would see in a browser tab
![ss 2016-07-03 at 01 21 38](https://cloud.githubusercontent.com/assets/12616124/16710247/3076db22-4628-11e6-9a2a-0ddf36e65852.png)
Its the same thing (although not quite finished, i will do that when im back from vacation)

**Comment by MarshallOfSound** [comment]
@Church185 If you go to GPM and look at the favicon in the browser you will see that that is the icon we now use.
