### ISSUE TITLE
Launch failure

### ISSUE THREAD

**Issue by alaneje** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1296]
**OS:**
Windows 10 64 bit

**Issue Descriptions:**
Massive loads of errors and crashes on boot of software, will now launch, will put links to error print screens bellow 
http://i.imgur.com/gyJdWDz.png
http://i.imgur.com/Xqpd2cY.png
http://i.imgur.com/ZfmFCV1.png
http://i.imgur.com/rVtARly.png
http://i.imgur.com/Xjapbcs.png
http://i.imgur.com/OKnTIDp.png
http://i.imgur.com/8eklnbu.png

**Comment by jostrander** [comment]
Can you completely remove the program and try reinstalling it? There are two folders, one in `%localappdata%` and one in `%appdata%`.

**Comment by alaneje** [comment]
Was the %localappdata% folder, tried earlier and deleted the appdata folders but nothing changed, thank you :)
