### ISSUE TITLE
Double switches at settings page

### ISSUE THREAD

**Issue by kybarg** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#13]

**Comment by MarshallOfSound** [comment]
Please provide more information, what do you mean "double switches".  If it is a UI bug please provide screenshots and steps to replicate.

**Comment by MarshallOfSound** [comment]
Bug just appeared in my install, appears as though Google pushed out another change to GPM that broke my switch insertion technique.  Working on a fix now

**Comment by MarshallOfSound** [comment]
This has been resolved but as this is not a breaking bug I don't think it's worth a pushed release.  It'll go out with the next release.  I'm trying to put releases on a 14 day cycle :smile_cat:
