### ISSUE TITLE
Dark theme color issues

### ISSUE THREAD

**Issue by Talor-A** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#130]
Using dark theme, when an item in the sidebar is selected, the grey highlight color is the same color as the subtitle text, looking like this:
![screenshot 8](https://cloud.githubusercontent.com/assets/11509865/12136572/1b859fe4-b3fe-11e5-9f66-e3cdb2faf553.png)
![screenshot 7](https://cloud.githubusercontent.com/assets/11509865/12136573/1b86e390-b3fe-11e5-85e7-47d440c92466.png)
Why not replace the grey highlight color with the theme's custom color(blue in my case) and change subtitle text to white when selected?

![screenshot 9](https://cloud.githubusercontent.com/assets/11509865/12189774/f725c15a-b575-11e5-8681-aa6c561794f2.png)
![screenshot 10](https://cloud.githubusercontent.com/assets/11509865/12189775/f87c3282-b575-11e5-9fab-73d44d87b0eb.png)

EDIT: Here's some more issues with color. The shuffle icon doesn't follow custom theme, and the music visualizer for the currently playing song is not very visible for me.

**Comment by MarshallOfSound** [comment]
- [ ] Fix shuffle icon
- [ ] Fix visualizer color
- [ ] Fix sub-title text in the nav bar

**Comment by Devo7v** [comment]
To add to this topic, the vertical lines for the pause icon should be white to match the other icons.

**Comment by MarshallOfSound** [comment]
Fixed issues upstream in `gmusic-utils/gmusic-theme.js`
