### ISSUE TITLE
No 64-bit RPM package for 3.3 release

### ISSUE THREAD

**Issue by Lord-Phoenix** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1300]
Web-site link for 64-bit RPM package is not working. I assume due to naming change in a file name:

../v3.3.0/google-play-music-desktop-player-3.3.0.x86_64.rpm for 3.3 release
and it used to be ...3.2.5.amd64.rpm for 3.2.5 release.

**Comment by MarshallOfSound** [comment]
It was renamed and the website was updated

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/releases/tag/v3.3.0

Looks like a caching issue.  I'll just clean out the caching service now

**Comment by Lord-Phoenix** [comment]
Yeah, thanks, I was just updating description :)

**Comment by MarshallOfSound** [comment]
Caching service has been cleaned and the website appears to have been updated
