### ISSUE TITLE
Can't install distributive

### ISSUE THREAD

**Issue by somejet** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1301]
Windows 10 (x64) Enterprise

Can't install distributive. Logs attached

[SquirrelSetup.txt](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/356818/SquirrelSetup.txt)

Tried to delete \AppData\Local\GPMDP_3\, but still can't install. Previous version was uninstalled correctly via windows native uninstaller

**Comment by MarshallOfSound** [comment]
Looks like you have anti virus interfering with the install.  Try running as admin to override the issue
