### ISSUE TITLE
Windows "Speaker Fill" Enhancement doesn't work with GPMDP

### ISSUE THREAD

**Issue by DRSXS** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1303]
**OS:**
Windows 10

**Issue Descriptions:**
Pretty much what the title says. When I use WMP the "Speaker Fill" Enhancement in the Realtek HD Audio Manager works, so that I get sound on all speakers with 5.1. But with GPMDP it sadly doesn't work and only plays sound on front left and right.

**Steps to Reproduce:**
Use 5.1 System and activate Speaker Fill in Realtek HD Audio Manager.

**Comment by jostrander** [comment]
There is an option in chrome called "--try-supported-channel-layouts". Try running GPMDP with this option to see if it fixes the audio for you.

**Comment by DRSXS** [comment]
I tried this by adding the parameter to my desktop shortcut. However, it did not fix my issue.

**Comment by jostrander** [comment]
Does it work in chrome?

**Comment by MarshallOfSound** [comment]
This one is quite simply nothing to do with us 😆 

If it works in Crhome as @jostrander asked then it is an Electron problem if it doesn't it is a Chromium problem.

Neither of which will probably want to invest a lot of time into fixing a borked feature of a third party audio driver. 😆 

Have you tried changing your audio output device?

**Comment by DRSXS** [comment]
I just tried it out with Chrome and it is as you thought. Same problem, I will try and find a solution online because I'm sure I'm not the only one bothered by this. I mean you don't wanna listen to music on just your Left and Right, without the center and Sub it just doesn't sound as good. Rears are not that important for music and youtube. Anyway, thanks for your input.
