### ISSUE TITLE
Malware warning Windows 10

### ISSUE THREAD

**Issue by Pheoxy** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#131]
I get a malware warning as soon as I try to install 2.0.1.

Are you able to upload .md5 to verify?

**Comment by MarshallOfSound** [comment]
It's signed with a verified cert, let me check

**Comment by MarshallOfSound** [comment]
@Pheoxy windows is just being stupid.  Here is a scan of the latest `2.0.2` version

https://www.virustotal.com/en/file/a9a404f6ad2c918c0b6d4190466b619b4404d3bd1f4d89ed412cfff795bfe610/analysis/1452076453/

The SHA256 hash of the file is there if you want to verify it that way, also literally all the executable I ship are signed with my code signing cert that verifies the files haven't been tampered with.

**Comment by MarshallOfSound** [comment]
And here is an MD5 hash of the same file

http://sha1md5checksum.bugaco.com/cryptocalc/index.html

**Comment by Pheoxy** [comment]
I just got a hash that doesn't match, I'm going to re download.

**Comment by MarshallOfSound** [comment]
FYI, that is the hash of the installed file, not the executable.  The executable is technically just a wrapped MSI and therefore should be verified by windows itself.  If you want I could hash the installer?

**Comment by Pheoxy** [comment]
Please.

**Comment by Pheoxy** [comment]
Here's a SHA-256:
F7803B4765912DF367C5C772C2FCC76FB2061F40A5A94EC9BB39EC7B996C8D2B

MD5:
CC31C3483E55469D23111B645D8BCC2C

**Comment by MarshallOfSound** [comment]
OK, this is the hash of the 2.0.1 release x64 installer

MD5:
cc31c3483e55469d23111b645d8bcc2c

**Comment by Pheoxy** [comment]
Just finished the redownload I'll do virus check on my end with an uploaded setup.

**Comment by MarshallOfSound** [comment]
Anything @Pheoxy ??  Heading off for the night and don't want to leave a fresh update with a potential virus sitting on it

**Comment by Pheoxy** [comment]
Sorry, I'm back on slow ADSL...
https://www.virustotal.com/en/file/f7803b4765912df367c5c772c2fcc76fb2061f40a5a94ec9bb39ec7b996c8d2b/analysis/

**Comment by Pheoxy** [comment]
Yea it failed 3/54

**Comment by Pheoxy** [comment]
Downloading your 2.0.2 update to see if its got anything. I may be getting MITM.

**Comment by Pheoxy** [comment]
Whats the MD5 and sha-256 of 2.0.2?

**Comment by MarshallOfSound** [comment]
Hold up, I just scanned the installer with all my local scanners (Windows Defender, Zone Alarm and Malwarebytes) and it got nothing.  But uploading it to virustotal triggered some hits....

Looks like a whole bunch of false positives

**Comment by Pheoxy** [comment]
Hmm. why's it trigger them though?

**Comment by MarshallOfSound** [comment]
If you look through my issues here I think #11 we had a false positive before that I resolved by changing a JSON library I was using.....  False positives are the bane of small developers like myself because we can't do anything about them.

You can build from source if you want or scan the installed files.  The installers are clean, and just to have a transparent build process they are actually build on appveyor.com and are publicly available.  All I do is download them, sign them and reupload them

**Comment by Pheoxy** [comment]
Thanks I'll take a look.

**Comment by Pheoxy** [comment]
Here's the check on 2.0.2 by the way:
https://www.virustotal.com/en/file/cbf8cd373a6d63781f3761ad201a4b8821b6a7bbe557a181b92b0a8b3f7e7e1e/analysis/1452081269/

Might be some changes that are causing it.

**Comment by MarshallOfSound** [comment]
I'm running a complete system scan now to ensure nothing is piggy backing onto the installer

**Comment by Pheoxy** [comment]
I'll do my own scan to check as well.

**Comment by Pheoxy** [comment]
Sorry for lateness completely forgot about this. My system check was fine, it's probably some of your code when you have keybindings or some other piece. Good luck on finding a way around that when you have the time.

**Comment by Pheoxy** [comment]
On current GMDP 2.1.0 I'm not getting the malware warning anymore.
