### ISSUE TITLE
Provide a way to get back to the Google play music site

### ISSUE THREAD

**Issue by jcgruenhage** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1310]
**OS:** Fedora 24

**Issue Descriptions:** Chrome Web Store Only, no way to get back to GPM.

**Steps to Reproduce:** When you sign in and your account has a u2f key active, it will offer you to install a extension from the chrome web store, if you click on that there is no way (in the app) to get back to GPM.

**Simple Workaround:** Delete config files

**Comment by MarshallOfSound** [comment]
Actualy solution use the Window -> Go to URL option.

Or the shortcut "Control + Shift + G"

**Comment by jcgruenhage** [comment]
The shortcut is working, thank you, I can't find the first option though, where will I find that?

**Comment by jostrander** [comment]
It really depends on the DE/Window Manager your using @jcgruenhage. Generally speaking "Window" is a menu bar item, so wherever your menu bar is, either in the top panel of your desktop, or on the top of the window. If you have them set to hide by default you might have to press alt or whatever your hotkey would be to get it to show up.

**Comment by jcgruenhage** [comment]
Ahh, okay, did not think of alt :D thank you very much, and sorry for opening an issue for that 😳
