### ISSUE TITLE
Mini player album cover and song information bug

### ISSUE THREAD

**Issue by DRSXS** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1311]
**OS:**
Windows 10

**Issue Descriptions:**
When playing music on shuffle with the minimized player the album cover and song information doesn't update when a self uploaded song that doesn't have an album tagged starts playing. Instead it just stays on the album cover and song information of the previously played song. It works fine with songs that have an album tag.

**Steps to Reproduce:**
Upload song without album tag. Add it to playlist with a song from Google Play Music. Start playing the normal GPM song and switch to the minimized player and then skip to the next song (the uploaded one).

**Comment by MarshallOfSound** [comment]
This makes very little sense 😢 

Can you enable the JSON api and see if the song information is updated in the JSON file?  Just need to try determine the point of failure

**Comment by DRSXS** [comment]
I just tested it and the information the JSON file also doesn't update. In the JSON it also doesn't matter whether the player is in mini mode or normal mode. It doesn't update either way, even though the correct information gets displayed in the normal view. The only values which update in the JSON are the time variables.

**Comment by MarshallOfSound** [comment]
This bug has been identified and fixed upstream 

gmusic-utils/gmusic.js/pull/46
