### ISSUE TITLE
Allow multi select of songs within album view

### ISSUE THREAD

**Issue by alanjeeves** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1312]
Hi,
i would like to easily remove a list of songs from an album from my library.

But currently i have to right click on each song and select Remove from library, it would be nice to have a select checkbox next to each song and be able to click this and then have a "Remove all selected from libarary" option.

**Comment by MarshallOfSound** [comment]
This feature is built in to Google Play Music.

Hold down control when you selectron songs and it will multi select
