### ISSUE TITLE
The player stops streaming radio station after ads - Mac OSX

### ISSUE THREAD

**Issue by arismendi2gil** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1313]
It started happening a few days ago, after a certain number of cycles of streaming and ads (around  3) the player window goes black, the app does not crash but it won't allow you to use next track to get it going. Only choice is to restart app.

**Comment by MarshallOfSound** [comment]
Can you be specific about your macOS version and what type of GPM account you have

**Comment by arismendi2gil** [comment]
Sure:
Mac OSX El Capitan Version 10.11.5 (15F34)
Google Play Music Free

**Comment by dstaff159** [comment]
This also happens in Windows
Windows 7 Professional: Service Pack 1
Google Play Music Free

**Comment by MarshallOfSound** [comment]
This appears to be an issue in Chromium and as such will be fixed when Electron bumps their version
