### ISSUE TITLE
npm install fails on Gentoo

### ISSUE THREAD

**Issue by Silent-Hunter** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1314]
My OS is Gentoo with kernel 4.4.6.

My issue is this: `silent@TERMINAL-BMRF-9 ~/Google-Play-Music-Desktop-Player-UNOFFICIAL- $ npm install

> mdns@2.3.3 install /home/silent/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/mdns
> node-gyp rebuild

make: Entering directory '/home/silent/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:0:
../src/mdns.hpp:32:20: fatal error: dns_sd.h: No such file or directory
 #include <dns_sd.h>
                    ^
compilation terminated.
dns_sd_bindings.target.mk:145: recipe for target 'Release/obj.target/dns_sd_bindings/src/dns_sd.o' failed
make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
make: Leaving directory '/home/silent/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/mdns/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib64/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.4.6-gentoo
gyp ERR! command "/usr/bin/node" "/usr/lib64/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/silent/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/mdns
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
google-play-music-desktop-player@3.3.0 /home/silent/Google-Play-Music-Desktop-Player-UNOFFICIAL-
+-- abbrev@1.0.9 
+-- aproba@1.0.4 
+-- fstream@1.0.10 
+-- glob@7.0.4 
+-- has-unicode@2.0.1 
+-- node-gyp@3.4.0 
+-- npm-package-arg@4.2.0 
+-- npm-user-validate@0.1.4 
+-- read-package-tree@5.1.5 
+-- readable-stream@2.1.4 
+-- which@1.2.10 
`-- wrappy@1.0.2 

npm WARN optional Skipping failed optional dependency //ll-keyboard-hook-win:
npm WARN notsup Not compatible with your operating system or architecture: ll-keyboard-hook-win@3.0.0
npm ERR! Linux 4.4.6-gentoo
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE

npm ERR! mdns@2.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.3.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mdns
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/silent/Google-Play-Music-Desktop-Player-UNOFFICIAL-/npm-debug.log`

Steps to reproduce: cd into cloned directory, type "npm install"

[npm-debug.log.txt](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/362862/npm-debug.log.txt)

**Comment by MarshallOfSound** [comment]
It looks like you are missing `avahi` on your system.  Please install and try again

I don't normally help people with dev issues in GitHub issues (not an issue with the program rather an issue with your setup).  So if you need further assistance please ask in Gitter.

**Comment by Faalentijn** [comment]
You need to compile avahi with the mdnsresponder-compat USE flag
