### ISSUE TITLE
Ugly Plasma System Tray Icon

### ISSUE THREAD

**Issue by titanente** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1318]
For some reason the system tray icon of gpmdp looks really ugly on KDE.
It shows as a big orange/white square.

![](https://i.imgur.com/SC6NPT4.png)

I tried some different Plasma Themes, but can't get a regular looking tray icon.

I'm running KDE Plasma on Manjaro.

**Comment by MarshallOfSound** [comment]
This is fixed in master (I think)

It's because KDE doesn't scale the tray images (their fault really 😆 )
