### ISSUE TITLE
Windows 10 "zoom flicker"

### ISSUE THREAD

**Issue by jprivard** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#132]
Hey there,

I don't know how to explain the issue I currently have, but on my Windows 10 Surface Book, the latest version of the application is buggier than the one before. When I hover some links, there's like a part of the application screen that zoom and it flickers on and off. It's disturbing. 

![Here's how it looks like to me](https://cloud.githubusercontent.com/assets/1730158/12142482/74e80552-b446-11e5-89cb-ef990149e1a8.png)

**Comment by RemyFV** [comment]
uninstall completely, download the latest 2.0.2 release, reinstall - it should work properly :)

**Comment by MarshallOfSound** [comment]
Can confirm @RemyFV is correct
