### ISSUE TITLE
Chromecast Audio option not visible

### ISSUE THREAD

**Issue by philthynz** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1320]
I am using v 3.3.0 on win10x64. The release says there is chromecast support included. Does this include chromecast audio? I have checked the issues and wiki. The wiki says chromecast is in beta, and there are no issues for chromecast audio.

**Comment by MarshallOfSound** [comment]
Our JS bonjour fallback is a bit buggy.  Can you please install Bonjour.  

Easiest way to get it is to install Bonjour print services

**Comment by philthynz** [comment]
ok, i did that, and restarted. it's only showing 1 out of the 5 devices

**Comment by MarshallOfSound** [comment]
The only showing 1 device issue will be fixed in the next release
