### ISSUE TITLE
Playback API doesn't show "Unknown" for Album or Artist.

### ISSUE THREAD

**Issue by Alipoodle** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1321]
**OS:**
Win 10 (GPM  - 3.2.5 Developer)

**Issue Descriptions:**
If this has already been solved i'm sorry, when searching for Playback.json or Playback API you get alot of the automatic problems!

The Playback API doesn't update when the Track doesn't have an Album AND an Artist.
Before: It displayed Unknown, although this only works when there is No Title, but Album and Artist.
This also effects the Mini Player (which i found on accident). Here is how it looks in all different things. The picture looks Terrible because i had to show it in all different ways.

![image](https://cloud.githubusercontent.com/assets/17199186/16896572/1b79544e-4b90-11e6-8ec5-96e9e37a552c.png)
As you can see the Json and the Mini player shows the song before (which is a random song), while the Notification shows the currently playing song!

**Steps to Reproduce:**
Have a song which doesn't have an Album / Arist. Then Check the playback.json or the Mini player!

**Comment by MarshallOfSound** [comment]
This was an upstream issue that has been fixed

**Comment by Alipoodle** [comment]
I've just tested this on 3.3.0 and it's still not working.

**Comment by MarshallOfSound** [comment]
Sorry, should have been clearer.  It has been fixed in master and will be pushed out next release

**Comment by Alipoodle** [comment]
Ok. ^.^ i'm also a little sleepy so i can't understand much.
