### ISSUE TITLE
"Let's go" button in update info popup invisible and scrolling unobvios

### ISSUE THREAD

**Issue by voldemarz** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1323]
The "Let's go" button in update info popup invisible and scrolling unobvious unless app windows is expanded.
![image](https://cloud.githubusercontent.com/assets/1264210/16896982/17bb1324-4ba4-11e6-9600-720a22e604b8.png)

**Comment by MarshallOfSound** [comment]
@voldemarz Your window is smaller than average.  We actually chunked a bit off the changelog so that the button fitter on most peoples displays.

Not much we can do about this.

**Comment by voldemarz** [comment]
@MarshallOfSound I have 1920x1080 display, just tend to use smaller windows. Can't you add a scroll bar? Add button on top or next to title? Allow closing it by pressing Escape? It definitely is confusing currently.

**Comment by MarshallOfSound** [comment]
@voldemarz There is a scroll bar, it is just unfortunately quite hard to see.

I'll add a flex rule to the changelog so the button is always visible
