### ISSUE TITLE
Windows 10 Start Menu Folder Name

### ISSUE THREAD

**Issue by lech** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1324]
I just noticed that when searching for the Google Play Music Desktop Player within my start menu on Windows 10 that the folder name is titled "Samuel Attard". I'm going to go out on a limb here and say that's unintentional.

**Comment by MarshallOfSound** [comment]
Nope, that's 100% intentional.

Standard on Windows is

Publisher Name -> App Name

I am the publisher therefore it is my name.  It's just how windows does it

**Comment by lech** [comment]
Ahh, it just seems weird to me as far as start menu goes… but I'll accept that.
