### ISSUE TITLE
"A JavaScript error has occurred in the main process"

### ISSUE THREAD

**Issue by williamtech814** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1325]
OS:
Windows 10 64-bit

Issue Descriptions:
When opening the application after a hard shutdown the following JavaScript error windows shows, no way to fix or open the application after. 
![screenshot_22](https://cloud.githubusercontent.com/assets/6900433/16902667/153808d8-4c34-11e6-8c6e-0191e7868095.png)

Steps to Reproduce: Hard shutdown while Google Play music is open.

**Comment by MarshallOfSound** [comment]
This is two things

1. A perfect example of why you shouldn't hard shutdown 😆 
2. A simple thing to fix

Simply go to `%APPDATA%/Google Play Music Desktop Player/json_store` and delete the `.settings.json` file.

As for an explanation you probably force shutdown just as GPMDP was trying to flush the Settings file to the file system.  #badtiming

This particular case is now handled in master
