### ISSUE TITLE
Last.fm does not go past Authenticating

### ISSUE THREAD

**Issue by dannymichel** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1326]
https://usercontent.irccloud-cdn.com/file/6HJidX7s/lfm.mp4

**Comment by MarshallOfSound** [comment]
Looks like you are either running your own version or you are running behind a proxy.

Are either of those the case?

**Comment by dannymichel** [comment]
Neither is the case

**Comment by MarshallOfSound** [comment]
VPN, fancy DNS settings?  Using the last.fm hostname trick?

(Running out of ideas here)

**Comment by MarshallOfSound** [comment]
And just to be sure you aren't behind a proxy (possibly a corporate one you aren't aware of) can you please run.

http://amibehindaproxy.com/

**Comment by dannymichel** [comment]
https://i.imgur.com/jvxZv3N.png

**Comment by MarshallOfSound** [comment]
Can you please upload your log file found at

`~/Library/Application Support/Google Play Music Desktop Player/gpmdc.log`

**Comment by dannymichel** [comment]
All default everything on a new OSX install and ran your installer default.
https://googledrive.com/host/0B1RBzGZgb1CfVHJDQjdYS3p6Vzg/gmusic.txt

**Comment by dannymichel** [comment]
```
{"level":"info","message":"Application started.","timestamp":"2016-07-17T20:18:57.842Z"}
{"level":"error","message":"Last.fm API keys have not been set!","timestamp":"2016-07-17T20:18:58.128Z"}
{"message":"Failed to setup auto update.","sender":{},"level":"error","timestamp":"2016-07-17T20:19:05.370Z"}

```

**Comment by MarshallOfSound** [comment]
Where did you get the `.app` file from??

Because I am 100% sure that the files I distribute (found online at http://www.googleplaymusicdesktopplayer.com) work for Last.FM.

It also appears as though the app you are running is not signed correctly.  Hence `Failed to setup auto update.`.

I would recommend deleting that app and downloading it again from my website

**Comment by dannymichel** [comment]
That worked. The manual build .app is broken though. Thanks

**Comment by MarshallOfSound** [comment]
@dannymichel So you built your own version....

So when I asked at the beginning....

> Looks like you are either running your own version

And you said you weren't?????

**Comment by dannymichel** [comment]
I thought you meant forked - sorry

**Comment by MarshallOfSound** [comment]
Lol, if you are building from source you need to set your own Last.FM API keys as I don't push my key and secret into version control.

You can look at the `constants.js` file to see what variables have to be set.

**Comment by dannymichel** [comment]
Ok cool cool
