### ISSUE TITLE
Issues with miniplayer while maximized in Linux

### ISSUE THREAD

**Issue by nlabrad** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1327]
**OS:**
CentOS 7 64 bit
Gnome desktop
1980x1200 display.
NVIDIA GTX960 with propietary drivers (latest as of July 17 2016).

**Issue Descriptions:**
While the player is maximized, when enabling the miniplayer, this will show up with some glitching covering the whole area the maximized player used to cover, as if there was a void the miniplayer left.

Now that could be my display drivers, so I need confirmation about the glitching, but the main problem is: 
when you can finally click on the button to go back to the normal player, the normal player will be zoomed in as if the screen was the size of the miniplayer. No way out of this. Also no way to close the player because it will minimize to tray, but it doesn't show in the gnome notification area. Must be killed with top.

**Steps to Reproduce:**
Start the player (If using system window border notice that there are no minimize or maximize buttons, only close. Double click on title bar to maximize.)

Now click in the bottom right corner to go to the miniplayer.
Miniplayer will show up while there is some glitching covering the whole screen where the full player used to be.

http://i.imgur.com/wB63d30.jpg
(The art work behind the miniplayer either flashes or stays on).

Attempt to click in the bottom right corner of the miniplayer to go to the full player.
Full player will appear zoomed in.

As in here http://i.imgur.com/JsdntiE.png

To prevent this, miniplayer must be opened while the player is NOT maximized, or the window must be restored (un maximized) BEFORE going back to the full player.

If anybody want's to throw me a bone on what should I know to attempt to fix this I'd appreciate it a lot, I'm trying to get myself involved in the project but my knowledge could (or could not) be limited.
Thanks!

**Comment by MarshallOfSound** [comment]
This was fixed in Master in `3.3.0`

What version are you running?

**Comment by nlabrad** [comment]
3.3.0

**Comment by MarshallOfSound** [comment]
@nlabrad Can you set up the dev environment and add a new line here

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/inject/GPMWebView/interface/mini.js#L25

```js
mainWindow.unmaximize()
```

And see if that fixes it

**Comment by nlabrad** [comment]
I'll try. Installing dependencies for the development environment now. Thanks.

**Comment by jostrander** [comment]
I'm not sure whether or not @nlabrad got around to testing your fix. However I do notice that when maximized in windows and pressing the mini player causes the mini to show with the full height of the original maximized window (if not larger?). On linux what usually happened would be the miniplayer would stay "maximized" but the drawable area flashed between the new dimensions (300x300?) and the full screen size. I'll have to check if that's still happening in 3.3.0 on linux.

**Comment by nlabrad** [comment]
I did apply the fix, but brings another little nuisance. After going back to big the window doesn't resize to what it was.  There is a fix in the works.
