### ISSUE TITLE
flash player

### ISSUE THREAD

**Issue by MRTrololololo** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#133]
Keeps asking me for flash player, When i already  have flash installed.

**Comment by MarshallOfSound** [comment]
Are you up to date?  Flash player is actually included in the latest release...

**Comment by MRTrololololo** [comment]
Yes

**Comment by MarshallOfSound** [comment]
Can you ensure that their is a folder called "Resources" with a flash ppapi DLL file inside it in your install folder

**Comment by MRTrololololo** [comment]
there's no folder called Resources

**Comment by MarshallOfSound** [comment]
.....  Doesn't sound like you are on version 2.0.2

Can you redownload the installer and install again.  Uninstall the old one first

**Comment by MRTrololololo** [comment]
THANK U, it finally works

**Comment by eturk1** [comment]
congrats on a stable release!
1. still tiny UI on my 4K 
2. mini player scale is off
<img width="150" alt="2016-01-06" src="https://cloud.githubusercontent.com/assets/525280/12151298/4bb8dedc-b463-11e5-9992-2614e6a48589.png">
<img width="150" alt="2016-01-06" src="https://cloud.githubusercontent.com/assets/525280/12151302/5001a0aa-b463-11e5-8dd2-46f7b0abe3cf.png">
(see pics) 

for future, maybe a check box on first install to opt in to beta ring? this way regular users by default don't get update notice until tested? (is there a UI element for seeing a settings panel?)

**Comment by MarshallOfSound** [comment]
Confirm the version number you downloaded.  Was it 2.0.2

**Comment by eturk1** [comment]
@MarshallOfSound I assume it's 2.0.2 as I uninstalled old, install from: https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/releases/tag/2.0.2

exe file is 1.0.0.0 though so can't confirm (see pic)
<img width="301" alt="2016-01-06 2" src="https://cloud.githubusercontent.com/assets/525280/12152054/15b5519a-b467-11e5-9364-cb429bcfacd2.png">

**Comment by MarshallOfSound** [comment]
Hmmm, that's strange.  Could you check control panel it should have the right version in the programs list.

And I think I will start up a beta stream, just looking at the best way to do it

**Comment by eturk1** [comment]
yes, 2.0.2 in uninstaller

(see pic to better show scale between outlook UI & GM player)

<img width="469" alt="2016-01-06 3" src="https://cloud.githubusercontent.com/assets/525280/12152339/e7c24502-b468-11e5-8081-2cf2f906f6c7.png">

**Comment by MarshallOfSound** [comment]
I'm going to ping @amaitland again, there is definitely some strange DPI things going on here still

**Comment by amaitland** [comment]
> . still tiny UI on my 4K (ignoring display 150% scale)

Can you clarify `Tiny UI`? Do you mean the `Titlebar buttons`?

> And I think I will start up a beta stream, just looking at the best way to do it

`GitHub` allows you to tag a release as `Pre-release`. You may wish to consider having a `Stable` branch.

@MarshallOfSound Likely need some sort of diagnostic information/logging, get some more information about the hardware/environment. Can even be as simple as a key sequence that copies information to the clipboard so users can paste into their issue.

**Comment by MarshallOfSound** [comment]
@amaitland I think he is referring to the text inside CEF, if you look on the screenshot it is visibly much smaller than the example given in outlook.

And yeah, I'm tempted to move away from using github as a update platform though because it isn't the most user friendly platform for people who have never been to github before.  I can messages all the time on reddit asking how to download because they can't find the release section :+1:

**Comment by amaitland** [comment]
> @amaitland I think he is referring to the text inside CEF, if you look on the screenshot it is visibly much smaller than the example given in outlook.

A couple of point sizes smaller at most. Anyway, if it's supposed to be bigger then I guess that's a problem still. 

@eturk1 Are you up for helping us out a little? If your up for it, I'd like you to download `cefclient`, it's a reference implementation of the `Chromium Embedded Framework (CEF)` for which powers the web browser. The exact version is important, so please pay attention.

![capture](https://cloud.githubusercontent.com/assets/307872/12157633/d90aa110-b51e-11e5-9f16-18cd8d4dad97.PNG)

- Open https://cefbuilds.com/#branch_2454
- Download the `Windows 32bit Test App` as shown in the screen shot above (You'll be prompted for a captcha)
- Unzip to a temp location
- Run `cefclient.exe`
- Navigate to the `Google Play Music` website, login if required, compare.
- Provide some screen shots if possible.

This will help us isolate the problem, if the result is consistent then likely upgrading to a newer version of `CEF` is requird.
