### ISSUE TITLE
Can't open GPMDP v3.3.0 on Windows 10

### ISSUE THREAD

**Issue by Turbotailz** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1333]
**OS:**
Windows 10 Pro 64-bit

**Issue Descriptions:**
I just updated to v3.3.0 yesterday, everything worked fine after that. But when I went to open the program today I was greeted with a bunch of JavaScript errors:

http://i.imgur.com/3XPVwob.png
http://i.imgur.com/Xno4Qmy.png
http://i.imgur.com/mTKdyxh.png
http://i.imgur.com/tW6ZE3h.png
http://i.imgur.com/u6tNF49.png
http://i.imgur.com/xvCcWTm.png

All these errors would pop up after clicking OK on the previous one. The last error left me with nothing. The program was still running in task manager, the only way to close it was to end task.

Trying to open the program again just gets the same errors.

Reinstalling did not fix. Same errors. Also tried removing the GPMDP_3 folder from .appdata/Local/ and reinstalling again, still errors. Finally, a system restart still hasn't solved the issue.

**Steps to Reproduce:**
Not sure? I simply tried opening the program after upgrading to v3.3.0.

**Comment by MarshallOfSound** [comment]
Sounds like your settings file is corrupt.  See #1319

**Comment by Turbotailz** [comment]
Works perfectly now, thank you.
