### ISSUE TITLE
Can't cast to Chromecast Audio

### ISSUE THREAD

**Issue by kingamajick** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1335]
**OS:**
Ubuntu 16.04
Kernel: x86_64 Linux 4.4.0-31-generic

**Issue Descriptions:**
When attempt to Chromecast Audio, it doesn't appear as an option.  I can only see my Chromecast (not audio only).

I've check that both of the Chromecast are detectable from Google Music using my Chrome browser.

**Steps to Reproduce:**
1. Have Chromecast Audio on network
2. Attempt to cast to Chromecast Audio

**Comment by MarshallOfSound** [comment]
This is actually the issue.

The issue currently is only one Chromecast appears in the list.  If you reopen it enough times your Chromecast audio will be the one that appears.

Tbis issue will be fixed in the next relesse

**Comment by kingamajick** [comment]
Great news, thanks :)
