### ISSUE TITLE
Scrolling

### ISSUE THREAD

**Issue by Kameechewa** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1336]
**OS:**
Windows 10 Pro
**Issue Descriptions:**
Scrolling is very janky and very fast. I'm using the trackpad on my Dell XPS 13 (9343) with the high res screen and just by barely scrolling it scrolls about a third of the page at like 2 fps.
**Steps to Reproduce:**
Scroll anywhere.

**Comment by MarshallOfSound** [comment]
@Kameechewa This is an issue with Chromium itself, we don't control how much you can scroll.  If I had to guess your laptop scrollpad drivers aren't playing nice with chromiums interpretation of "scroll lines".

Did you always have this problem, or just on the latest version?

**Comment by Kameechewa** [comment]
It would be the latest version since I just got it the day of posting. So I haven't had the opportunity to test other versions.

**Comment by MarshallOfSound** [comment]
@Kameechewa Ah, well, welcome to the party 👍 🎉 

But yeah, unfortunately scroll speed issues raised with Chromium have usually been closed with "fix your drivers" or "the scroll speed is managed by the OS" kind of responses.

So if you can, adjust your scroll speed in your drivers, otherwise not much I can do 😢

**Comment by Kameechewa** [comment]
Alright I'll try that. No big deal if it doesn't work, it works if I school really slow so it manageable haha. I'm just happy you have put this wonderful program together. Ever since Play Music I've been wanting a desktop client. Thanks.

**Comment by Kameechewa** [comment]
Scroll*
