### ISSUE TITLE
App freezes/crashses

### ISSUE THREAD

**Issue by Eno423** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1337]
**OS:**
win10 on surface pro 4
**Issue Descriptions:**
since latest update, the app will play a handful of songs, then stop playing them, & the screen/app will just be black
**Steps to Reproduce:**
run the app for a while, then it happens

I am going to start looking into it a bit more, as its really starting to urk me

**Comment by MarshallOfSound** [comment]
This is an upstream Chromium issue and will be fixed in the next release.

Quite a few apps including some big ones like Franz are having this issue as well.
