### ISSUE TITLE
Usable hotkeys limited

### ISSUE THREAD

**Issue by ZakStrassberg** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1340]
**OS:**  Ubuntu

**Issue Descriptions:** I am unable to set hotkeys to anything using number keys, plus/minus or function keys. I don't believe I have intellitype or setpoint.

**Steps to Reproduce:** Go into hotkeys section of settings, try to enter ctrl alt + or ctrl alt F2 as a keybind.

**Comment by rgavs** [comment]
Hotkeys are a known issue. See #413
