### ISSUE TITLE
Chromecast selection does not update

### ISSUE THREAD

**Issue by mathus13** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1342]
**OS:**
Ubuntu 16.04

**Issue Descriptions:**
When changing networks (an location) the listing of network chromecasts does not update. It continues to list whatever chromecast was discovered on the previous network until GPMDP is restarted.

**Steps to Reproduce:**

1. Open GPMDP on while connected to network 1 with chromecast A present.
2. Open the chromecast dialog and note chromecast A is displayed 
3. Change to network 2 (with chromecast B) while keeping GPMDP open
4. Open the chromecast dialog. The listed device will continue to be chromecast A
5. Quit and restart GPMDP, note the update in the chromecast listing

**Comment by MarshallOfSound** [comment]
@jostrander I think this can be called an actual issue and we should add some kind of refresh action when inside the UI

**Comment by jostrander** [comment]
This is an issue we discussed a while ago and hadn't really come to a definite solution on. 

There are a couple of initial thoughts I'd like to jot down with regards to fixing this:

1. Requesting a session (pressing the cast icon) should also repopulate the list of cast devices before display the list. This will fix this particular issue. I believe this is _similar_ to how the official Cast extension works.
2. With that, it still would need a way to refresh devices when GPMDP is opened and no devices are found initially. I'm not sure if the GPM UI is responsive to new casts being discovered after it's initial check. If it is, then we can simply restart the mdns browser on an interval pending whether or not there are any receivers in the current list.

**Comment by jostrander** [comment]
Also this was originally brought up over at gpmdp/electron-chromecast#9.

**Comment by MarshallOfSound** [comment]
Moving to the referenced issue
