### ISSUE TITLE
Can't exit mini player when update notice pops up.

### ISSUE THREAD

**Issue by cmfrolick** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1343]
**OS:**
Windows 7 Pro

**Issue Descriptions:**
When the update notice pops up while in mini player, the only way to get back to the main screen is the quit the app from the sys tray icon and restart.

**Steps to Reproduce:**
Receive an update notice while in the mini player.

**Comment by toekneebullard** [comment]
Same issue with Windows 10. The only way I can get the player working again is to end tack it and restart the whole thing.

**Comment by MarshallOfSound** [comment]
This issue was fixed in this release (ironically in the update that you couldn't see)
