### ISSUE TITLE
Can only see 1 chromecast when there are 7 on the network

### ISSUE THREAD

**Issue by lelandcope** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1344]
**OS:**
OS X 10.11.5

**Issue Descriptions:**
I can't ever get more then 1 chromecast to show up in the list of cast devices.

**Steps to Reproduce:**
Have more then 1 chromecast on your network and click the chromecast button in the app. Only 1 is listed when there are more then 1 on the network.

**Comment by MarshallOfSound** [comment]
Tbis is a known issue and has been fixed in master
