### ISSUE TITLE
App goes black and music stops

### ISSUE THREAD

**Issue by cmfrolick** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1345]
**OS:**
Windows 7 Pro

**Issue Descriptions:**
The app is working fine, and suddenly the screen goes black and if music is playing, it stops. Must quit via the systray icon. It happened a couple times while in the mini player, so I tried without switching to the mini player, and it happened in the main screen. Once it happened while music was playing, twice while it was paused.

**Steps to Reproduce:**
Unsure, did not try timing it to see if it is consistent or not.

**Comment by jcady** [comment]
Same exact issue has happened to me many times on both Windows 10 Home and OS X 10.11.5.

**Comment by MarshallOfSound** [comment]
This is an upstream issue in Chromium.  When electron updates Chromium we can push out an update to fix this issue.  

Thanks for your perseverance 😆

**Comment by jcady** [comment]
For what it's worth this has started happening to me a lot more frequently, maybe once every half hour. v3.3.0.

**Comment by cmfrolick** [comment]
Does v3.4.0 include the Chromium fix or are we still waiting on them?

**Comment by MarshallOfSound** [comment]
@cmfrolick It includes the fix

**Comment by alxzh** [comment]
The same happens on Linux. If I pause music for some time and try to play it again later application windows just dark. Menu Play/Pause/Next/Prev don't work. Only right click -> Quit closes the app and restart fixes it.
