### ISSUE TITLE
Program Crashes Immediately

### ISSUE THREAD

**Issue by RNMKRJNPR** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1348]
**OS:** Windows 10 x64

**Issue Descriptions:** I've been trying to get the program working for the last couple days, but it crashes immediately upon trying to sign in. I've tried all the solutions I could find in the forums, running as admin, installing as admin, disabling AV temporarily, everything, and it just refuses to work at all. It doesn't even give me any sort of error window or alert or anything. Just loads for a couple secs, and crashes immediately.

**Steps to Reproduce:** Literally just double clicking to run it.

**Comment by MarshallOfSound** [comment]
@RNMKRJNPR This is almost certainly an AV issue.

Are you attempting to run the installer or the program itself?

**Comment by RNMKRJNPR** [comment]
The installer works just fine, and it'll let me get to the email and password entry screens, but when it goes to load my library it crashes immediately.

**Comment by MarshallOfSound** [comment]
Are you using a proxy or VPN?

**Comment by RNMKRJNPR** [comment]
Nope, not at all. Brand new PC too.

**Comment by MarshallOfSound** [comment]
Might seem like a strange question but does Chrome let you get past the sign in screen?

**Comment by RNMKRJNPR** [comment]
I actually don't use chrome, it's working perfectly on Firefox though. Lemme give this a try though.

**Comment by MarshallOfSound** [comment]
I'm going to put this down to the whole "Black Screen" issue that others are getting.  The chromium render process must be crashing for some reason.

The next chromium version bump in Electron should fix this.

**Comment by RNMKRJNPR** [comment]
So as of the new release, this is still happening. I'm starting to honestly wonder if there's some issue with my account and this app, because if I'm not logged in, the app stays up, but as soon as I log in and it gets about a third of the way through loading my library, boom, crashed.

**Comment by jostrander** [comment]
I'm not going to rule it out, but it's highly unlikely. What if you log in to a different account? Have you tried it on a different computer with the same account?

**Comment by RNMKRJNPR** [comment]
It logged into a different account, got to the main GPM screen, and then immediately crashed like my main account.

**Comment by jostrander** [comment]
I would say it's not related to any particular account. What are your system specs? Is this a work laptop or personal use? Have you tried completely removing the installation by deleting GPMDP from `%localappdata%` and `%appdata%`? What anti-virus software are you using? Any other "real time" protection software?

**Comment by RNMKRJNPR** [comment]
It's a brand new gaming rig, Windows 10 anniversary, personal, and using Avast, which I tried temp disabling while installing and running as well.

I DID see these pop up in the GPMDP folder though. Maybe this'll help?

{"level":"info","message":"Application started.","timestamp":"2016-08-08T15:33:56.527Z"}
{"level":"error","message":"Failed to load bonjour with error: {}","timestamp":"2016-08-08T15:33:56.858Z"}
{"level":"info","message":"Application exiting...","timestamp":"2016-08-08T15:34:18.818Z"}
{"level":"info","message":"Application started.","timestamp":"2016-08-08T15:34:24.729Z"}
{"level":"error","message":"Failed to load bonjour with error: {}","timestamp":"2016-08-08T15:34:25.079Z"}

**Comment by jostrander** [comment]
Try installing bonjour? That shouldn't cause a crashing issue, but I guess we'll see.

**Comment by RNMKRJNPR** [comment]
I can't find any way to do that for Windows.

**Comment by MarshallOfSound** [comment]
@RNMKRJNPR Find the GPMDP installed exe and run the following.  A crash log should appear on screen when it crashes

```bash
set ELECTRON_ENABLE_STACK_DUMPING =true
set ELECTRON_ENABLE_LOGGING=true
path\to\executable.exe --dev -- --dev
```

**Comment by RNMKRJNPR** [comment]
I just do that via command prompt right? I've tried pasting everything exactly as you said and I'm still not having anything pop up.

I am so sorry for being such a pain.
