### ISSUE TITLE
Tray icon is too large under KDE Plasma 5

### ISSUE THREAD

**Issue by CyanJDroid** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1350]
**OS:**
Arch Linux with KDE desktop enviroment

**Issue Descriptions:**
This appears to be a common issue with Electron apps (see [here](https://github.com/stanfieldr/ghetto-skype/issues/46) and [here](https://github.com/sindresorhus/caprine/issues/58)). Basically the system tray icon is so large it gets cut off and is just a square. The half orange, half white icon in the photo below is GPMDP in my system tray.
![selection_011](https://cloud.githubusercontent.com/assets/5077450/17087256/7092cfdc-51cb-11e6-9515-0d59f7b257db.png)

**Steps to Reproduce:**
Run GPMDP on a Linux install with the KDE desktop, observe strange system tray icon size.

**Comment by jostrander** [comment]
Personally I'd raise this as an issue over in KDE Plasma. It seems to be a common issue for that DE. We've looked at this issue before, however not sure if it ended up getting resolved.

**Comment by MarshallOfSound** [comment]
As @jostrander please raise this with KDE-Plasma, Electron apps are experiencing this problem because KDE doesn't resize our icons.

**Comment by CyanJDroid** [comment]
Alrighty, I'll go ahead and report this as an issue for KDE Plasma!
