### ISSUE TITLE
Disable "Automatically Scroll lyrics while playing" does not work correctly

### ISSUE THREAD

**Issue by MiguelCTorres** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1351]
**OS:**
Windows 10 64 bit

**Issue Descriptions:**
Automatic scrolling does not work properly. It is activated again even though it is turned off.

**Steps to Reproduce:**
Case 1:
Open the player.
Put a song and put the lyrics of the song.
Turn off automatic scrolling.
The lyrics of the song actually does not move automatically.
Wait to change the lyrics of the song, while changing song.

Case 2:
Open the player.
Put a song and put the lyrics of the song.
Turn off automatic scrolling.
The lyrics of the song actually does not move automatically.
Close the player and reopen it.
Put a song and the lyrics will scroll automatically again.

**Comment by techuck** [comment]
I am able to reproduce Case 2 (intermittently), but not Case 1. @MCManuelLP looks to have setup the scrolling and @MarshallOfSound pushed a related fix 10 days ago, maybe they can chime in with some insight, possibly related to changes from #1214 or #1322 ? Interestingly enough, the lyrics scrollbar seems to always behave (show/hide) as expected when autoscroll is disabled/enabled.

Win 10, 64 bit, v3.3.0

**Comment by MarshallOfSound** [comment]
@techuck Thanks for pinging me, this slipped through my inbox somehow....  Too many github notifications 😆 

This appears to have a root cause of animating the scroll regardless of the setting.  I can reproduce both cases 100% of the time.  Looking into why it always animates now
