### ISSUE TITLE
Issue With Alt Tabbing

### ISSUE THREAD

**Issue by thecoopster20** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1352]
I love everything about this player except for one small issue I have noticed. Usually I'll leave the player open on one monitor, and the game I am playing on the other. Even with borderless window enabled in games, briefly clicking on the player to thumbs up a song will force my otherwise borderless game to windowed mode which requires an alt enter.

**Comment by jostrander** [comment]
Yeah that usually happens with multi-monitor with most programs. Why not set up some key binds for thumbs up/down?

**Comment by MarshallOfSound** [comment]
This is an OS level problem or a game implementation problem or both.

If you are giving focus to another application how the previously focused application reacts is out of my control
