### ISSUE TITLE
Add the possibility to change te default behavior when exiting

### ISSUE THREAD

**Issue by Kirogo** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1353]
Hi,
As said in the title, would it be possible to change the default behaviour when exiting (meaning, Alt+F4 or anything like that depending on your OS/DE/WM/etc.) ? Right now, it minimises the player as a widget icon, and I'd prefer to have it quit straight away.

Many thanks for this very nice player though !
Cheers, Alexandre.

**Comment by MarshallOfSound** [comment]
This is an option.

Go to settings and disable "Minimize to Tray"
