### ISSUE TITLE
Text in Play Music window is blurry

### ISSUE THREAD

**Issue by SaylorTwift** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1354]
**OS:** Win10, 64 bit

**Issue Descriptions:**
The text in the main window is blurry. I can hardly describe the issue any differently. The text doesn't seem to be scaling correctly or at all, which makes it hard to see from even a little further off. I've included two images, one on my main monitor in 1080p and one on my secondary monitor in 1280x1024.

I have also tested it with the windows scaling option set to 150% to definitely enlarge the text but it still stayed blurry. I've also included images from both monitors for that test.

No other Windows apps are affected by this, including the main Chrome installation. When I open Play Music in a normal browser window, all looks fine.

**Steps to Reproduce:**
Start the app. That's about it.

**Images:**
1280x1024, scaling 100%:
![img1](https://cloud.githubusercontent.com/assets/20637606/17099553/628f5baa-5269-11e6-89dc-2eeaeb555b06.png)

1080p, scaling 100%:
![img2](https://cloud.githubusercontent.com/assets/20637606/17099556/651842ba-5269-11e6-8ab1-efea148a2c83.png)

1280x1024, scaling 150%:
![img3](https://cloud.githubusercontent.com/assets/20637606/17099557/66c2298c-5269-11e6-8fc9-1b461b400961.png)

1080p, scaling 150%:
![img4](https://cloud.githubusercontent.com/assets/20637606/17099558/67fdfdd0-5269-11e6-9f43-9efebeed809d.png)

**Comment by SaylorTwift** [comment]
Here is another update: Sometimes I can see fluctuations in quality, where it gets ridiculously blurry to the point of being illegible. Here is another screenshots from one of the worse times:
![img 5](https://cloud.githubusercontent.com/assets/20637606/17099812/de31c6ca-526a-11e6-839d-162351412bb6.png)

**Comment by MarshallOfSound** [comment]
@SaylorTwift This is one of two things

1. Your graphics drivers are broken 😢 
2. It is related to the AA bug on Electron at the moment electron/electron/issues/6344

If your graphics drivers are up to date then it is probably the second one and I would subscribe their for updates 👍
