### ISSUE TITLE
Allow option to upload music

### ISSUE THREAD

**Issue by zacjanes** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1357]
In Chrome browser, you can upload music through the website. Is this possible to implement for the Desktop Player?

**Comment by MarshallOfSound** [comment]
TLDR: Not easily 😆 

The upload logic is heavily minified and very hard to isolate in the Chrome plugin

**Comment by zacjanes** [comment]
Okay. Wish I knew coding to help :)

**Comment by zacjanes** [comment]
Done with my suggestions for now. Thanks for the app :)

**Comment by leocaseiro** [comment]
Hi @MarshallOfSound, I was wondering if there's a way to add a button to upload that goes to The Chrome plugin app perhaps or to the Google Website?
