### ISSUE TITLE
PlaybackAPI JSON file intermittently blank

### ISSUE THREAD

**Issue by heru-ra** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1358]
**OS:**

Debian

**Issue Descriptions:**

Randomly the player will throw a blank playback.json file, for a brief second until updating it again. I cannot tell what causes this, it just seems to be at random while a song plays.

This became an issue for me, when I was writing a script that monitors the file in real-time, to display the info via conky. I had to write in a workaround that monitored the playback.json file to see if it was blank at any given moment, and to not try to read it at said moment.

Obviously this is not a huge issue, but it was a headache for me for a while, trying to figure out why at random my conky display didn't have any info to work with.

**Steps to Reproduce:**

Play a song, monitor the playback.json file contents.

**Comment by MarshallOfSound** [comment]
I'll look into this but it sounds like a file system issue where your OS isn't correctly locking the file while we write to it.  This means there is a split second where we are writing to the file that it is considered blank and your file system shouldn't allow access during this time.

In the meantime can you use the WebSocket API instead?

**Comment by heru-ra** [comment]
You could be quite right, that this isn't technically a bug on the player's end, and that would mean my workaround is actually the proper approach in handling the file.

I have no tried using the WebSocket API. I would have to rewrite my script to do so, but it might be the cleaner approach in the long run.

**Comment by MarshallOfSound** [comment]
OK, so a bit of rapid testing later I can say that

* This doesn't happen on windows
* This doesn't happen on OS X
* This does happen on Ubuntu

(I tested by reading the file with node every millisecond and printing true if it was empty)

I think the best thing I can do is add this to the docs saying it might be blank on some linux OS's
