### ISSUE TITLE
[Feature request] Native Dark title bar on macOS

### ISSUE THREAD

**Issue by FezVrasta** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1359]
**OS:** macOS

**Request**:

I'd like the title bar to be dark to match the dark theme of the player instead of being gray.

![image](https://cloud.githubusercontent.com/assets/5382443/17173506/89dd6c5e-53fb-11e6-8152-3ba674826c8f.png)

**Comment by MarshallOfSound** [comment]
I'm monitoring this upstream here.

https://github.com/electron/electron/issues/1582

But until this kind of option gets implemented upstream in Electron you can use our custom window borders by disabling the "Native Window Borders" option in Desktop Settings 👍 

Hopefully that fits your needs for now 😆

**Comment by FezVrasta** [comment]
It helps but the buttons are on the wrong side and have not the OS X style, maybe you could detect the OS and display the right buttons style.

**Comment by MarshallOfSound** [comment]
> It helps but the buttons are on the wrong side and have not the OS X style

That is by design, their are two modes  
* Native Borders -> For people who like the native feel of their OS
* Custom Borders -> For the fully themed experience but non native borders

Currently electron doesn't allow us to modify the title bar colors and replicating the macOS title bar in HTML and CSS just feels horribly wrong to me.

**Comment by FezVrasta** [comment]
Ok as you prefer, I'll stick with Radiant till Electron introduces this feature then. Thanks

**Comment by FezVrasta** [comment]
You may want to take a look at https://github.com/atom/atom/pull/11790

The window control buttons aren't replicated with CSS but are the native ones, just the titlebar is with CSS.

**Comment by MarshallOfSound** [comment]
Interesting, a combination of the `hidden-inset` frame option and custom CSS.  Native but also not native.

I'll look into it.

**Comment by MarshallOfSound** [comment]
Implemented in master

![screen shot 2016-08-25 at 12 47 41 pm](https://cloud.githubusercontent.com/assets/6634592/17955021/577500dc-6ac2-11e6-89a7-ddf184b4781a.png)
![screen shot 2016-08-25 at 12 47 47 pm](https://cloud.githubusercontent.com/assets/6634592/17955020/57674730-6ac2-11e6-9877-2da45412110c.png)
![screen shot 2016-08-25 at 12 47 55 pm](https://cloud.githubusercontent.com/assets/6634592/17955019/57652022-6ac2-11e6-80e7-0309ca75f261.png)

**Comment by FezVrasta** [comment]
So nice! Why the dark titlebar isn't seamless like the colored ones?

**Comment by MarshallOfSound** [comment]
@FezVrasta Dark theme has a concept of primary and secondary colors to add some contrast to the darkness.  That way looked better than just straight black 👍

**Comment by FezVrasta** [comment]
Chances to have a way to decide between the contrast version and the seamless one? 😞

**Comment by MarshallOfSound** [comment]
See #1475
