### ISSUE TITLE
Radio playback app crash

### ISSUE THREAD

**Issue by RPYoshi** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1360]
**OS:**
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
Kernel: 4.4.0-30-generic

**Issue Descriptions:**
Bug: During radio playback, after the second commercial the app freezes and stops working.
Additional Info:
Bug between version 3.2.4 -> 3.3.0
Running version 3.2.4 does not have this issue. The first commercial works fine, and music playback works fine. However once the second commercial finishes playing, the app does not continue to play and stops completely. I have tested on both this linux machine and my windows 7 64bit desktop.

**Steps to Reproduce:**
1. No google music subscription.
2. Must have 3.3.0 installed
3. Choose radio from either the "Listen Now" featured stations or an artist radio.
4. Allow playback of first commercial and additional songs.
5. Wait for second commercial and watch for app failure once completed.

P.S. I love your app keep up the good work.

**Comment by MarshallOfSound** [comment]
This is an upstream chromium crash and will be fixed in the next release when we update Electron versions
