### ISSUE TITLE
gpmdp will not launch 

### ISSUE THREAD

**Issue by bryan1545** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1363]
If you have done those 3 things go ahead and fill out the information below.
Once again, thanks for taking the time to submit an issue
-->

**OS:**
windows 10 home 64 bit
version 1511
OS Build 10586.494

**Issue Descriptions:**
when I try to open the app I start to get a swarm of error from what I think is java it started after I was playing music and it when silent and the app just when black I closed it and tried starting it and I just got a bunch of error I restarted my computer and even tried reinstalling when I reinstalled the  app It when well but ass soon as it tried launching the app it gave me the same errors 
* I screenshotted all the errors in the order they came as the files are numbered I think they are 2 error that keep repeating but just to be sure I am uploading all of the errors in the order they came by file name
**Steps to Reproduce:**
try launching app 
![error 1](https://cloud.githubusercontent.com/assets/18205274/17197556/f39844b4-542a-11e6-8a24-92db73f01d25.png)
![error 2](https://cloud.githubusercontent.com/assets/18205274/17197554/f395a3d0-542a-11e6-9ba4-2cdce6924db2.png)
![error 3](https://cloud.githubusercontent.com/assets/18205274/17197557/f3984d2e-542a-11e6-9ca1-cead4d9f94da.png)
![error 4](https://cloud.githubusercontent.com/assets/18205274/17197558/f398b1f6-542a-11e6-9777-7155fb4f8577.png)
![error 5](https://cloud.githubusercontent.com/assets/18205274/17197555/f396c7d8-542a-11e6-903b-f33ef33010c5.png)
![error 6](https://cloud.githubusercontent.com/assets/18205274/17197559/f39b66c6-542a-11e6-826c-97ef68cfef2e.png)

**Comment by MarshallOfSound** [comment]
Please delete the `%APPDATA%/Google Play Music Desktop Player/json_store` folder
