### ISSUE TITLE
[Feature Request] Show song name on taskbar when paused

### ISSUE THREAD

**Issue by RedDragonx** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1364]
Windows 7 & 8.1 &10

Can you add a feature that show the song name & artist on GPM taskbar when it's paused. It'll be like: 
(Paused) Orbion - Armin van Buuren

**Comment by MarshallOfSound** [comment]
What is the purpose of this?  Currently we only show song title and artist in the taskbar when the song is playing so streaming software can detect the currently playing song.

**Comment by RedDragonx** [comment]
It's just to let me know what song is paused. I config my foobar2000 to have this feature so I think it'll be cool if GPM have this this feature also.

I know this feature is not necessary, but it's very nice to have it.
