### ISSUE TITLE
[Feature Request] Smooth play/pause

### ISSUE THREAD

**Issue by RedDragonx** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1368]
Another feature I miss from foobar is smooth play/pause, can you add this feature to GPM?

**Comment by jostrander** [comment]
What is smooth play pause for those of us who have never used it?

**Comment by gholtslander-va** [comment]
IIRC, it will stop or start the music by fading out or in (respectively) over 1s or so, so that it isn't an abrupt shut off of the music.

**Comment by RedDragonx** [comment]
Thank you @gholtslander-va it's exactly that, but over 1 second is too long, I think less than 0.5 second is enough :)

**Comment by MarshallOfSound** [comment]
I've had this request before and determined after some research that it is impossible.

Basically we can fade songs in, but fading out is harder.  Think of it like this  

The required steps are as follows:  
Play Command -> Fade In  
Pause Command -> Prevent Pause -> Fade Out -> Actually Pause  

The key part being **Prevent Pause** if we prevent it internal GPM things break beyond your wildest imagination.

**Comment by mmcc-xx** [comment]
What if a new "smooth pause" command was added that perhaps could only be accessed via hotkey? Executing this command would handle the fades and then issue the real pause command.
