### ISSUE TITLE
[Feature Request] Disable Background Image / Animation

### ISSUE THREAD

**Issue by patrickhills** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1369]
This is a GPM issue, but while the image is mostly okay, the background animating is super distracting.

Would is be possible to either add an option to disable the animation/image or perhaps to allow a Greasemonkey/Stylish section to alter visual elements? I do this in my browser, but would love this in the app!

Great work everyone! # #

**Comment by jostrander** [comment]
Can you share more detail as to what you're specifically talking about? I'm assuming your talking about the full screen album art visualization? Do you have a link to how you are currently scripting this?

**Comment by jostrander** [comment]
@patrickhills If you have more information please reply and we will reopen the issue.
