### ISSUE TITLE
BUG: Mini player not updating timestamp after moving window

### ISSUE THREAD

**Issue by ThomasLewis1028** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1371]
So I ran into a bug where, after launching the mini-player and moving it around to put it in a place I want, it doesn't update the timestamps or the pause/play buttons.  Not only that, but if you move the window while it's "stuck", it updates the timestamp when you let go of the window.  I'm running Windows 10, and I SHOULD be running the latest version of the app as I've updated it every time I see the update notification, though I'm not 100% positive.

The steps to reproduce it are basically just launch the mini-player, doesn't matter if the original window was maximized or not, and then try to move the window.

I took a short video, without sound, where I showed Google Play Music's mini-player from the website and how it works fine, and then I showed me playing music in the app, the timestamp changing, and then dragging the window slightly and it stops updating.  [Here's the video](https://youtu.be/OOlDy99GpKs)

Also, in the midst of messing around and trying to test it, I clicked the actual settings menu and it paused the music, I resumed it and when I clicked back onto "listen now" it paused it again.  I "fixed" that by force quitting the app and relaunching it, and it didn't seem to happen again from the five seconds I messed with it.

In the same vein, occasionally, music will randomly pause/unpause.  I paused my music and then left my computer for a few hours, and when I got back my music had been unpaused like 27 minutes before I sat down (according to when Last.FM logged the first song in the bunch).  And then a few minutes ago, while clicking around in Chrome, my music paused itself.  I can't seem to replicate it, and it just seems to happen, but I'm not sure.

**Comment by jostrander** [comment]
Hmm, oddly enough I can reproduce this, not exactly, but probably worse than your case. 

@MarshallOfSound Do you have any idea if this is an upstream issue in electron or strictly something broken in your mini player implementation?

**Comment by ThomasLewis1028** [comment]
Uh oh, I guess it's good I decided to bring it up and not deal with it like I do most software bugs I encounter :/

So how are you reproducing it that ends up being worse than mine?

**Comment by MarshallOfSound** [comment]
Upstream chromium bug fixed in Electron `1.3.0` I believe.  They had some interesting rendering issues
