### ISSUE TITLE
[[FEATURE REQUEST]] Batch Edit: Add to Library function // Playlist: Add to Library function

### ISSUE THREAD

**Issue by blorblehbloo** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1373]
Awesome app, been following for a while. 

Quick suggestion about adding a new functionality.  Selecting an individual song not in your "My Library", you can select "Add to library" as an option.  But when you select more than one song, that option disappears.  This is true for both GPMDP and Google's own web player.  

There is also currently no option to "Add to Library" for entire playlists. 

Is there any way to add songs in groups or by entire playlist, to the My Library?

This would make my music browsing so much easier, because then I can just stay in the "My Library" pane and sort/browse the contents of playlists as well.

Thanks!!!

**Comment by jostrander** [comment]
This is something that should be directed at Google Play Music itself. Unfortunately adding code for this would be very challenging, and the code would break spontaneously for even minor changes to the music web service.  Overall not something that would be supported by this project.

**Comment by blorblehbloo** [comment]
Cool, thanks for the quick reply! Cheers man.

**Comment by MarshallOfSound** [comment]
In agreement with @jostrander
