### ISSUE TITLE
[Feature Request] Crossfade

### ISSUE THREAD

**Issue by yannick9906** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1374]
It would be really nice to have a crossfade option with a slider to adjust the time for crossfading.

**Comment by jostrander** [comment]
Unfortunately this is a limitation of the original GPM player that we can't override. The best we could probably do is fade out near the end, and fade in for the beginning by adjusting the volume, but not sure that constitutes cross-fading.

**Comment by MarshallOfSound** [comment]
^^

**Comment by groovenectar** [comment]
Is technically impossible to open the next stream while the first one is playing? Even partially? I would figure that could be an approach, any idea what specifically makes it impossible?

**Comment by MarshallOfSound** [comment]
@groovenectar Google generates stream URL's as HTML5 `Blob` data uri-s dynamically for each song.  We can't get the next data-uri to start playing until Google has fetched it for us (through their obscure and secure methods).

As such we only have access to a song's data-uri once it has started playing (which is too late to fade out the old song).

**Comment by groovenectar** [comment]
Would it be feasible to have a hidden instance of GPM in the background, that starts the next song based on the queue?

**Comment by jostrander** [comment]
Not really. The queue's aren't shared between web page instances unfortunately.

**Comment by groovenectar** [comment]
Dang.  Well this is getting to be a stretch, but here's another idea... if the track position can be controlled.. what if the just next song in the queue starts in a hidden instance (without knowing the rest of the queue)... then once the main queue instance song has faded out... it jumps the track to the same point as the hidden instance, then fades back in while the hidden instance fades out :)

**Comment by kahlju** [comment]
So I can see what @groovenectar is saying but the HTML 5 Blob is for two reasons I think, to keep people from hotlinking and for data packaging (binaries are more efficient).  However, I do believe this is possible with two methods.

1.  It works playing different songs on my phone and my computer through my Google play account.  So the browser or device mapping (not sure how it works in the background) is the trick here.  Even one of the fixed recently for logging in was to set a fake browser for login, just have it run off of two browser spoofs, essentially, should work.  Worst case, you could use real device mapping to emulate another program.  

2. And I think this is the lowest computation per second.  Just have an echo program within it. Have the program load up the stream and play it muted in the background and redistribute them manually to the speakers later.  You'd have a delay built in so it can keep up, but after the first song good to go.  Or.... Same thing with a different route. Possibly even better, take advantage of the backend for the Google play downloaded offline feature.  It plays offline without relying on the HTML.  Run a dual instance with one version you allow to be online and one offline.  Then control what's playing in this app but change the sources and volume levels

**Comment by kahlju** [comment]
And best case, if people finally beat Google's app blockade for the purpose of crossfade it may actually make them add the feature.  I'd really like to see their business case for not adding it already.  I was just told they acquired songza in 2015, but it seems they only integrated the radio features similar to Pandora and left out the parts people actually liked.  I don't understand what they are doing with the gapless playback, I know they supported it in 2017, again in 2012, 2014, etc and now I don't see options for it anymore so it's so odd they keep going back and forth.  The issue for crossfade no one has gotten through since 2012 actually.  Love the service and app interface, hate this inability to satisfy users needs. Perhaps we are the smaller end of their target market.

**Comment by kahlju** [comment]
By the way, I should add I'm not working on this atm.  I have 3 jobs and pick up programming as quickly as I can on the side to assist in the other three (research).  I'd like if this were opened back up though.
