### ISSUE TITLE
Chromecast not showing up on Arch

### ISSUE THREAD

**Issue by brentluna** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1375]
**OS:**
Arch Linux
**Issue Descriptions:**

I have both a chromcast 2 and chromecast audio on my network and i'm not finding an option for chromecast on gdmp. I can cast fine using GP in a browser. 

**Steps to Reproduce:**

Start GDMP and there is no chromecast selector to be found.

**Comment by jostrander** [comment]
Known issue that is fixed in master:

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/1335#issuecomment-234106545

**Comment by MarshallOfSound** [comment]
@jostrander This appears to actually be a missing dependency (linked issue is RE only one chromecast appearing)

@brentluna Can you please ensure that your firewall allows communication on port `5353` and you have `avahi` installed and running
