### ISSUE TITLE
mini player thumbs up missing

### ISSUE THREAD

**Issue by FreshieGeek** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1377]
I searched for "mini player thumbs up missing" and didn't find anything.
Windows 10x64
I regularly go from my thumbs up playlist to a radio station to listen to something new.
When I go from mini player thumps up to full program to find a station, and back to mini player, I find that my thumbs up and down are missing. The only way I have found to get them back is to close and re-open the program.

**OS:**

**Issue Descriptions:**

**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment]
I can reproduce with the following steps

1. Play an album
2. Enter mini player mode
3. Enter full player mode
4. Play a radio
5. Enter mini player mode

After those steps the thumbs up and down buttons disappear.

**Workaround**
Simply pausing and playing the music brings the buttons back.  This appears to be an issue with `gmusic-mini-player.js`
