### ISSUE TITLE
[Mac] AirPlay support?

### ISSUE THREAD

**Issue by dingbat** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1379]
**OS:** Mac

**Issue Descriptions:** AirPlay support

**Steps to Reproduce:**

Hey - Thanks for the awesome player! I was wondering if there were any plans to integrate AirPlay casting on Mac before I take a shot at it, and if anyone has any tips if it's been attempted before (the documentation for it on Mac seems lacking, as usual).

**Comment by jostrander** [comment]
Feel free to take a shot at it, we haven't tried implementing it to the best of my knowledge due to the GPM stream being hard to take over and retain control of.

**Comment by MarshallOfSound** [comment]
> the GPM stream being hard to take over and retain control of.

Impossible actually 👍 Pending an upstream implementation such as electron/electron/issues/4776

Though you might be able to come up with a funky way to try do it.  In which case go for it!!  I'm not familiar with how AirPlay works though so you're on your own here 😆

**Comment by MarshallOfSound** [comment]
Closing this out to clean up the issues section.  Anyone is welcome to still attempt this
