### ISSUE TITLE
2.0.2 doesn't like being installed over an earlier version

### ISSUE THREAD

**Issue by NuclearFej** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#138]
See title, when I installed 2.0.2 over my previous version (didn't note which one, sorry!) it refused to run. I had to reinstall in order for the player to run.

**Comment by MarshallOfSound** [comment]
Which previous version did you have?

**Comment by MarshallOfSound** [comment]
I have tested the upgrade path from `1.7`, `1.8` and `1.9` on both x86 and x64.  I actually spent ages making sure these upgrade paths worked :smile:

**Comment by NuclearFej** [comment]
I'm sorry, don't know which version I had. On Windows 10, what OS are you running?

**Comment by MarshallOfSound** [comment]
Windows 10 as well, but I tested on 7, 8, and 10

**Comment by ShepherdJerred** [comment]
Occurring to me as well

**Comment by MarshallOfSound** [comment]
Closing as it appears to be a limited issue.  And not much I can do about an already released installer :/
