### ISSUE TITLE
Error opening GPMSP

### ISSUE THREAD

**Issue by MiguelCTorres** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1381]
Hello, I can't open GPMDP. Sent me the following errors. I tried to reinstall and still broken (@MarshallOfSound):

![error 1](https://cloud.githubusercontent.com/assets/11237854/17306415/f65a1354-57fd-11e6-985f-4400c377498b.PNG)
![error 2](https://cloud.githubusercontent.com/assets/11237854/17306419/f65ec8f4-57fd-11e6-857f-ef85a95f13e0.PNG)
![error 3](https://cloud.githubusercontent.com/assets/11237854/17306417/f65d9178-57fd-11e6-8b9f-8328c3151aa3.PNG)
![error 4](https://cloud.githubusercontent.com/assets/11237854/17306418/f65e1a80-57fd-11e6-9aca-5e0d2622a733.PNG)
![error 5](https://cloud.githubusercontent.com/assets/11237854/17306416/f65d4c90-57fd-11e6-9dbe-48c5966aba65.PNG)
![error 6](https://cloud.githubusercontent.com/assets/11237854/17306420/f66047b0-57fd-11e6-9ad4-7a126ab40f83.PNG)

**Comment by bryan1545** [comment]
in search type %appdata% and hit enter Then open The Google Play Music Desktop player foler and delete the Json_store Folder and try to open it again

**Comment by jostrander** [comment]
> In search type `%appdata%` and hit enter Then open The `Google Play Music Desktop player` folder and delete the `json_store` Folder and try to open it again. 

If this doesn't work, completely remove the program by deleting `%localappdata%\GPMDP_3\` and reinstalling. For reference this was already answered here:

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/1325#issuecomment-233201945

Thanks @bryan1545

**Comment by MiguelCTorres** [comment]
Thank you! With both answers is solved
