### ISSUE TITLE
I need help POKEMONGoMap

### ISSUE THREAD

**Issue by Chirinos19** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1382]
I need help with PokemonGoMapWin program, install it tells me the error below (Put the link of the image) and can not start properly, by placing my ID did not load maps tells me there is an error with the javascrit and not and fix it.
I hope you can help me ...
Windows 10 PRO 64b
[http://oi65.tinypic.com/2ec0ynd.jpg](url)

**Comment by jostrander** [comment]
Unfortunately this has nothing to do with Google Play Music or GPMDP and I fail to see why your asking for help here. I would ask for help wherever you received that software.
