### ISSUE TITLE
Bug: Freezes/Crashes on OSX after ~1hr 

### ISSUE THREAD

**Issue by Grantimus9** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1389]
GPMDP quits, screen goes black and music stops after ~1 hour of play. 

**OS:**
OS: OSX 10.10.5 Yosemite 
MBP Mid-2015 15" with Intel Iris Pro 1536 MB graphics 
GPMDP: 3.3.0 

**Issue Descriptions:**
Today (1 August 2016) is the first day that I have noticed this issue. The music player will go black and stop playing music after ~1hr of playback. This occurs while listening to a station, in my case "Today's Biggest Hits." The app works fine after quitting and restarting. 

**Steps to Reproduce:**
In my case, playing the "Today's Biggest Hits" station will trigger the bug after ~1hr of playing in the background while I am doing other things. 
I do not cast to an external speaker. 

I realize this bug is likely due to a hard-to-find memory leak or something of its ilk, but want to bring it to your attention and err on the side of over-reporting. Thanks for packaging the app - it's pretty handy.

**Comment by MarshallOfSound** [comment]
Fixed in Electron `1.3.x`

This was an upstream Chromium GFX bug. 👍

**Comment by MarshallOfSound** [comment]
I'll push a release at the weekend probably 👍
