### ISSUE TITLE
JavaScript error on install

### ISSUE THREAD

**Issue by conzorz** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1393]
**OS: Windows 10**

**Issue Descriptions: In screenshot: http://imgur.com/v06R9xS**

**Steps to Reproduce: Every time I try to install**

**Comment by conzorz** [comment]
5 more error popups after that too...

**Comment by bryan1545** [comment]
it looks like this problem was addressed in #1325

**Comment by MarshallOfSound** [comment]
It has been addressed in #1325
