### ISSUE TITLE
Lyrics revert to scrolling when turned off.

### ISSUE THREAD

**Issue by delurfnags** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1394]
**OS: window 10 x64**

**Issue Descriptions:When turning lyric scrolling off every few minuets scrolling turns back on and i have to go back into settings turn on scrolling and then turn it back off. Issue has persisted though multiple installs of google play desktop player and re installs of windows 10 x64 with a few different installation medias. **

**Steps to Reproduce:Turn off lyric scrolling in settings > play album > turn on lyrics view confirm scrolling works > wait a few minuets until scrolling starts.**

**Comment by MarshallOfSound** [comment]
This has been fixed in master
