### ISSUE TITLE
Add way to disable showing album art in miniplayer

### ISSUE THREAD

**Issue by jrj2211** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1396]
Hey, the mini player is great but you can only make it so small before it stops letting you shrink it.  It would be nice for there to be a hide album art button so that it would only be the controls kind of like how Skype has control window open on top of everything. Maybe hovering over the controls could make a preview window appear below it that would show the album art and the song/band.

**Comment by jostrander** [comment]
I agree, but we have an issue for this already: #701.
