### ISSUE TITLE
UWP version for streaming on Xbox?

### ISSUE THREAD

**Issue by ryaniskira** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1397]
Feature request.
Is it possible to develop a UWP version so that people who own an Xbox can stream Google Music on their Xbox while gaming? If needed I can donate my Windows Store developer account.

**Comment by MarshallOfSound** [comment]
@ryaniskira Unfortunately Electron is a win32 framework and can't be ported to UWP.  I'm not keen for a UWP rewrite in another framework so until something changes this is a wontfix.
