### ISSUE TITLE
Additional auto-playlists, such as songs we've never listened to before?

### ISSUE THREAD

**Issue by tgp1994** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#14]
A really awesome feature I'd like to see is the ability to have additional auto-playlists, such as one that can pull up music we've never listened to yet in our library, or perhaps music we haven't listened to in a long time. This is something I was hoping Google would implement, but is it possible it can be implemented on the client-side with this app?

**Comment by MarshallOfSound** [comment]
Unfortunately this is not realist from a client side application.  Some libraries could be upwards of 10000 songs (Mine is over 12000) and manually fetching all the songs with HTTP requests would take literally hours.

This is the kind of feature that has to be implemented server side.

**Comment by tgp1994** [comment]
Ah, that's unfortunate, but I guess I'm not surprised. :( I was hoping Google had some sort of API that could make this a reality, but maybe later...
