### ISSUE TITLE
4K UI broken Ver. 2.0.2

### ISSUE THREAD

**Issue by adajan** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#140]
Hey,

It looks like the scaling of the window doesn't seem to happen, yet the web UI in the window seems to scale properly. Just need a few stuff tweaked

Mini player (Needs fixing):
https://gyazo.com/6b14ce9cb1f07fd31aef247843dfe238

Main Window (Fine):
https://gyazo.com/1de8c4555963af75abc96878e7e6b508

Desktop Settings (Fine): 
https://gyazo.com/ed5b1a04f7a8b12b9b29e5c058aa1f7f

Side Notifications (Needs readjustment):
https://gyazo.com/f0d06bd0915776431301dd92c0e0c8e7

**Comment by MarshallOfSound** [comment]
I was aware of the mini player issue but not of the notification one.  Though thinking about it they are the same problem just in two different places.  I have ideas on how to fix these issues but unfortunately I actually have no way to test them... :cry: 

Without a high res screen with DPI scaling turned on all I can do is guess and hope for the next release.  Hopefully I'll guess good :cactus:

**Comment by adajan** [comment]
I'm downloading visual studios now to fix it for you. I will request a pull once I'm done.

**Comment by eturk1** [comment]
just checking back in (going to this open issue to continue)
still on 2.0.2 (reported in uninstall) from when I first noted the 4K scaling issue.

image of where we left off. tiny interface elements in upper right and font for music:
![image](https://cloud.githubusercontent.com/assets/525280/12245726/295a7602-b85f-11e5-87b9-019bcc787169.png)

**Comment by MarshallOfSound** [comment]
Scaling Issues
--------------------
- [ ] Custom title bar (Minimize, Maximize, Close)
- [ ] Interior font sizing
