### ISSUE TITLE
Installation does not work

### ISSUE THREAD

**Issue by cimnine** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#141]
The installation did not work on my PC, with or without uninstalling the previous version (which was the latest before 2.x).

It's my work PC and I do not have admin privileges, which was no problem for the old installer. For me, a zipped version would be enough, actually. I don't need an installer.

Here's the log of the installer:
https://gist.github.com/cimnine/24a49b70e3b2e46ba3be

~Chris

**Comment by MarshallOfSound** [comment]
I don't officially provide a ZIP installer for usability reasons.  Mainly there are quite a few dependencies that need to be installed and I don't have the time to field the "I used the ZIP and now its not working" issues.

If you really want a ZIP you can get builds from AppVeyor  
https://ci.appveyor.com/project/MarshallOfSound/google-play-music-desktop-player-unofficial/build/1.9.2-100

Just follow that link, choose the build you want (x86 or x64) and click "Artifacts".  There will be two available for download.  A `.exe` and a `.zip`, you probably want the `.zip`.

**Comment by cimnine** [comment]
Alright, the ZIP did not work. Whatever. But it's too bad that I can't use the software anymore because the installer does not work either. See https://imgur.com/tCSAELp .
