### ISSUE TITLE
Provide AppImage builds for Linux

### ISSUE THREAD

**Issue by lbssousa** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1412]
**OS:** Linux

Please consider building this project in [AppImage](http://appimage.org) format for Linux (cross-distro). You could achieve it easily by e.g. migrating your build system to https://github.com/electron-userland/electron-builder, which has native AppImage output support.

**Comment by MarshallOfSound** [comment]
Providing AppImage builds is a "possibility" but there is no way I am migrating our build system to `electron-builder`.  It forces you to make certain app architecture decisions which I fundamentally disagree with and the builder itself has made several design decisions which I consider wrong.

I'll have to look into how we can add this to our build tooling, and more importantly where it will be built (currently our build system uses like 6 build machines every time 😢 )

**Comment by MarshallOfSound** [comment]
> Note that the binaries must not be compiled on newer distributions than the ones you are targeting

This is going to be a problem.  Our build machines for linux (Circle CI) are currently running Ubuntu 16.04, this kills a lot of distributions.  Not sure if this is the right way to go for us.

**Comment by probonopd** [comment]
No system in the world will allow you to compile on newer systems than you are targeting, without shipping a "runtime" that essentially bundles all dependencies from the newer system.

Could you use a chroot of e.g., debian oldstable or CentOS 6 on your Ubuntu 16.04 build machine, and build inside that?

**Comment by MarshallOfSound** [comment]
@probonopd Technically I could spin up a docker image and build inside that, the core thing to figure out here is not **how** to build an AppImage (that seems fairly straight forward ish)

It's where to add the concept of AppImages to our current build scheme as I don't see them replacing `.deb` and `.rpm` rather sitting alongside them and unfortunately CircleCI only gives 4 concurrent machines at a time.  This means I can build x64 and x86 against debian and fedora but nothing else.

We'll either have to add another CI provider to a automated build tooling or take a 10 minute CI time increase (which I don't want to do)

**Comment by probonopd** [comment]
if you build the `.deb` and `.rpm` on the same build system as the AppImage, might that help? I imagine they should run on "later" versions of the OSes just fine.

**Comment by MarshallOfSound** [comment]
The problem is pure build time.  It doesn't matter where I "tack on" the AppImage build, it's going to extend that build by 10+ minutes.

Recompiling native modules alone takes 6 minutes.

**Comment by probonopd** [comment]
If you have a deb built e.g., on oldstable, then it can be converted easily to an AppImage without recompilation in << 6 minutes.

**Comment by MarshallOfSound** [comment]
I was incorrect about our build agent.  It is currently running Ubuntu 14.04.

Is this old enough that we can reuse the `.deb` files we are creating?

**Comment by probonopd** [comment]
I think yes, in practice this should be fine for most systems. See [this](https://github.com/probonopd/AppImages/blob/6b582cb8535b381f7ddb5fa816af2a827d797f5c/recipes/upwork/Recipe) for an example of how to convert a deb to an AppImage. Let me know if you are stuck and I can help further.

**Comment by ParaplegicRacehorse** [comment]
:+1: 

Although I suppose a snap could work if we can ever figure out how to install a snap in user-space instead of system-space.

**Comment by Bohne13** [comment]
I don't completely understand all of what you guys discuss. But would it be helpful if you bild a snappy app image. You can put all app dependencys into the snappy "container" build.
Also the snappy build can used on ubuntu 16.04+ on Arche, Fedora, Debian, Gentoo, OpenSuse and some more.
I don't know if this is a solution for the problem here but I appreciate a snappy build definitely.

**Comment by ParaplegicRacehorse** [comment]
I don't have administrative rights on all systems I use so I want a way to "install" the program without the need for admin rights. AppImage suits that purpose wonderfully. I'm not so sure about snappy. 

[adapt](http://packages.ubuntu.com/xenial/adapt) is a possible solution for me (and some others), though getting GUI apps wording in containers is hard and don't know if it's been ported to other distros. Lots of reading on provisioning LXC instances would be needed for installing a .deb or .rpm without a repository somewhere.

[Vagrant](https://www.vagrantup.com/) is interesting. Most of the boxes I work on without administrative privileges have vagrant installed but there is, again, the issue of provisioning.

Still, the overhead of VMs makes AppImage a much better solution.

**Comment by MarshallOfSound** [comment]
I'm going to close this out as at some point in the future I will be porting our build tooling to `electron-forge` and then we will be limited by the build targets we support over there.  There is an open issue on that repo to add support for AppImage.

**Comment by probonopd** [comment]
One and a half years later, what is the status on this @MarshallOfSound?

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.
