### ISSUE TITLE
Track Skipping with GPMDP 3.3.0

### ISSUE THREAD

**Issue by obguy** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1415]
**OS:**
Windows 7 64-bit
**Issue Descriptions:**
3.3.0 release skips tracks and reports that it can't play the track.  Rolling back to 3.2.5 solves the problem.  Behind corporate firewall and can't play through chrome browser either (same track skipping, always has been that way).  I'm just wondering what is different about 3.2.5 (from 3.3.0) that enables playback to work.

**Steps to Reproduce:**
Install GPMDP v. 3.3.0 at my workplace.

**Comment by jostrander** [comment]
As far as I'm aware there is nothing in the code that would effect that. Are you using a proxy? If so are your proxy settings the same, and are you using a reliable proxy?

**Comment by MarshallOfSound** [comment]
> can't play through chrome browser either (same track skipping, always has been that way)

This sounds like a network issue that flukily didn't occur in `3.2.5`.  If it works, stick with `3.2.5`.

Nothing has changed in the two versions apart from the Chromium versions.

**Comment by obguy** [comment]
Thanks for the response, I'll stick with 3.2.5.
