### ISSUE TITLE
Window overflows onto second monitor

### ISSUE THREAD

**Issue by dregimbal** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1416]
**OS:** 
Windows 10, 64 bit
Version 1511
OS Build 10586.494

**Issue Descriptions:**
When the Google Play Music Desktop Player is open fullscreen in a multiple monitor setup, a white bar appears on the monitor to the left of the monitor with GPMDP
visual: http://imgur.com/EW5e3Wl

**Steps to Reproduce:**
Set up two monitors in windows as "extend these displays"
Open GPMDP on the monitor on the right
Fullscreen GPMDP
Observe the desktop on the monitor on the left

**Comment by jostrander** [comment]
Are you using native window borders or the GPMDP styled borders?

**Comment by MarshallOfSound** [comment]
This is an upstream issue in Electron that is currently marked as blocked.  There is nothing we can do about it here.
