### ISSUE TITLE
JSON API doesnt update track when album is missing

### ISSUE THREAD

**Issue by kanrrra** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1417]
Im on windows. When you play a track that is not in an album the .json file doesnt get updated. I guess its the same if "artist" isnt set but I didnt check. The time updates still work fine.

**Steps to Reproduce:**
Play a track with all attributes set
Play a track with no album set
The json file will still show the info from track 1

**Comment by jostrander** [comment]
Upstream issue in gmusic.js, is fixed in the latest release over there but needs to be updated here to use the new API. Paging @MarshallOfSound :stuck_out_tongue_winking_eye:

**Comment by MarshallOfSound** [comment]
The dependency on `gmusic.js` has been updated internally, just need to push out a release.

If we're lucky I might be able to get that sorted today
