### ISSUE TITLE
Feature Request: Option to disable desktop notifications

### ISSUE THREAD

**Issue by simonarons** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1419]
Every time the next song starts, a desktop notification pops up in the lower right corner of the screen. And every time I excitedly think it’s someone sending me a message, and I happily look to the lower right corner of the screen just to realize it’s not, leaving me with a slightly empty feeling inside. 

So I would love **an option to disable desktop notifications** altogether. 

OS: Windows 10
Version: 3.4.0

**Comment by MarshallOfSound** [comment]
You can.  This is an option built on to Google play music

**Comment by simonarons** [comment]
Well that's embarrasing. Only looked under the desktop settings. Sorry and thanks!
