### ISSUE TITLE
Version 3.4.0 no cast button on Windows 10

### ISSUE THREAD

**Issue by philthynz** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1420]
Thanks for the new version :grin: 

In the new version on Windows 10, there is no cast icon. What is required for this to work? Bonjour?

**Comment by MarshallOfSound** [comment]
> In the new version on Windows 10, there is no cast icon. 

In the previous version, was there a cast icon?

**Comment by philthynz** [comment]
Yea it worked in the previous version. And in v 3.4.0 the icon is missing

**Comment by MarshallOfSound** [comment]
Do you have bonjour installer?

**Comment by philthynz** [comment]
Yes. Bonjour print services

**Comment by MarshallOfSound** [comment]
Can you restart your computer while I try get my chromecast working 😆

**Comment by philthynz** [comment]
I restarted and it was still missing. Then reinstalled bonjour printer services and restarted. its back and working. It doesn't work with chromecast groups though. I guess your aware of that?

**Comment by MarshallOfSound** [comment]
Sounds like Bonjour decided to kill itself.  Glad to hear it's working now.

> It doesn't work with chromecast groups though. I guess your aware of that?

https://github.com/GPMDP/electron-chromecast/issues/8
