### ISSUE TITLE
Zoomlevel isn't persistent after last update

### ISSUE THREAD

**Issue by tuur29** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1421]
**OS:** Windows 10

**Issue Descriptions:**
Zooming in or out with ctrl+ or ctrl- works but the zoom level resets after you close the program. It also resets every xx minutes. I'm guessing the website reloads every now and again to stay recent.

**Comment by Alipoodle** [comment]
With me, when i try to resize it, it then puts it back to what it was + the action i did!

**Comment by MarshallOfSound** [comment]
Hey guys,

I've been looking into this quite a lot and it appears to be an issue in Electron but I can't narrow it down to a minimum reproducible example so I can't raise the issue yet.

I'll try work on this some moe today.

**Comment by Triloworld** [comment]
Yes, on mac is the same error:
Step to reproduce:
1. Run app.
2. Hold CTRL and + 
3. After it is big enough, close app.
4. Start app.
5. Zoom level is 100% than declared previous.
6. Hold CTRL and click once + or - to restore previous zoom level with additional change based on clicked + or -
Version: 3.5.0

**Comment by MarshallOfSound** [comment]
Some news, I have tracked the issue upstream to Electron

https://github.com/electron/electron/issues/6958

**Comment by MartijnGP** [comment]
For the time being, here's a workaround. In the desktop settings, you can supply an additional CSS file. Use that feature, create a file somewhere, and just put a CSS scale in there.

`html { zoom: 0.75; }`

**Comment by jostrander** [comment]
No longer an issue?

**Comment by Alipoodle** [comment]
Not 100% sure, as I believe I've had some zoom issues, although I'll leave it at some stupid zoom for a while so I can see if it has changed after using it for about an hour / 2.

**Comment by Alipoodle** [comment]
Been using for last 2 hours (and been fixing an issue for the theme) and Zoom is still persistant, even with Refresh and Restart.

**Comment by tuur29** [comment]
I can confirm this issue is resolved. Zoomlevel stays the same after hours.
