### ISSUE TITLE
Back/Forward navigation broken. About screen broken

### ISSUE THREAD

**Issue by brhermon** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1423]
**OS:**
Windows 10 
v3.4.0 (I think, see below)

**Issue Descriptions:**
Issue 1. The Back and Forward buttons on my mouse navigated back and forth in previous versions of the program. v3.4.0 broke this functionality.

Issue 2. The "About" screen in the app no longer displays. (So I can't check which exact version I just updated to)

**Steps to Reproduce:**
Issue 1. Self explanatory. 

Issue 2. 
1. Right click the Windows 10 notification icon.
2. Click Help > About.
3. Nothing pops up.

**Comment by jostrander** [comment]
I'm unable to reproduce issue 2, and I can't reproduce 1 because of lack of buttons on the mouse.

**Comment by brhermon** [comment]
My sincere apologies. Issue 2 seems to have not been an issue. The "about" screen displays _IN_ the software, rather than as separate, pop up window. My mistake. Issue 1 however was still relevant. Although now the bug has been marked closed and looks to have been addressed.
