### ISSUE TITLE
BUG: Miniplayer + Update notification renders window unusable

### ISSUE THREAD

**Issue by Jed-Giblin** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1424]
**OS:**

Windows 7  - 64 Bit

**Issue Descriptions:**

When the app is in miniplayer mode and a new update is made available, the notification windows takes control of the app and you can't leave mini mode or proceed with the update

**Steps to Reproduce:**

1. Launch old version of app.
2. Switch to mini-mode
3. Wait for update notification

**Comment by MarshallOfSound** [comment]
This was fixed in the last release.  However this issue will still appear in the current update notification as it is launched in the old release (a bit confusing but yeah)

👍
