### ISSUE TITLE
Mini player - mouse buttons not working

### ISSUE THREAD

**Issue by wefacd2wedcs** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1425]
**OS:**
Win 10
**Issue Descriptions:**
When I'm in the mini player, I can't adjust the volume with the scroll button. I've checked and the setting is checked for the mini player. The next/previous buttons don't skip songs anymore.
**Steps to Reproduce:**
in mini player, hover cursor over lower part of mini player. use scroll button up and or down. use previous/next buttons. songs don't skip

**Comment by MarshallOfSound** [comment]
The scroll does not work when over the mini player controls.  Please scroll on the image or somewhere else 😆

**Comment by wefacd2wedcs** [comment]
It's not working, no matter where I put the mouse.

**Comment by wefacd2wedcs** [comment]
You also told me to hover over the controls when I asked before, when I asked how to adjust audio in the miniplayer. That's the only way it used to work for me at that time.

"You can scroll up and down when hover over the player controls"
