### ISSUE TITLE
mini player and update notification

### ISSUE THREAD

**Issue by wefacd2wedcs** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1426]
**OS:**
win 10
**Issue Descriptions:**
when you're in the mini player and there's a new update, the notification block covers all the controls, so the only way to maximize it or hit any of the controls is to completely close out of the program
**Steps to Reproduce:**
download an older version, start it, mini player, wait for the notification

**Comment by MarshallOfSound** [comment]
Duplicate #1424
