### ISSUE TITLE
Miniplayer buttons are active, but invisible.

### ISSUE THREAD

**Issue by notasmartman** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1427]
**OS:** 
Windows 10

**Issue Descriptions:**
The miniplayer button (play/pause, next track, etc.) are active, in that if I mouse over where they should be, they are functional. However, the actual buttons are invisible and don't pop up from autohide as intended. 

Also, the miniplayer image will remain static and not progress to match the track until I hit the maximize button on the miniplayer. This causes the correct song to display. 

**Steps to Reproduce:**
This issue happens probably 80% of the time when I just open GPMDP and enable the miniplayer. Occasionally it will work properly but not regularly. 

I'm a user, no development experience, but attempting to use the preferred method of bug reporting. Be kind if I screwed it up!

**Comment by MarshallOfSound** [comment]
Do you have system borders enabled or are you using the custom borders?

**Comment by jostrander** [comment]
Confirmed. System border, win 10.

**Comment by MarshallOfSound** [comment]
Yeah, for an unknown reason.  System borders breaks the mini player.

I think this comes back to the "let's redesign the mini player" thing I had going a while back

**Comment by MarshallOfSound** [comment]
@notasmartman The current workaround is to enable the custom window borders in Desktop Settings.

This is an upstream issue being tracked here electron/electron/issues/6783

**Comment by notasmartman** [comment]
@MarshallOfSound @jostrander Yes, I was using system borders. Changing that has fixed my issue. Thanks!
