### ISSUE TITLE
BUG: Back/forward buttons on side of mouse no longer work with latest update

### ISSUE THREAD

**Issue by Beebou2** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1429]
Running Windows 10,  has always worked until this latest update

**Comment by MarshallOfSound** [comment]
Fixed in master

**Comment by Beebou2** [comment]
still not working?

**Comment by jostrander** [comment]
"Fixed in master" means it's fixed in an unreleased version of the app, and will be available when the next release is published.
