### ISSUE TITLE
Desktop notifications on Windows 10 have incorrect app name

### ISSUE THREAD

**Issue by ZephireNZ** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1430]
**OS:** Windows 10 Pro Build 14393.10

**Issue Descriptions:**
Desktop notifications have an an incorrect app name in the notification bubble
![image](https://cloud.githubusercontent.com/assets/1644496/17498930/6e6cd1f8-5e1e-11e6-958a-ec9d1fe21136.png)

**Steps to Reproduce:**

1. Enable Desktop notifications in Settings -> Labs
2. Restart
3. Play/Skip song - notification will appear with wrong app name

**Comment by MarshallOfSound** [comment]
@ZephireNZ It looks like you are running an old version, did you get the update a few days ago?

**Comment by ZephireNZ** [comment]
Hmm, that's odd. I definitely did update the other day - I noticed in the changelog about the Windows 8 notifications. Yet, this morning it must have somehow reverted to the previous version - it's currently set as "start with Windows". A quick restart and it's working... No idea what's happening, but it's fixed for now at least xD

**Comment by ZephireNZ** [comment]
Not sure whether I should make another issue for it, but it seems that I have two different versions. When windows starts up the 3.3.0 welcome message shows, however when I stop and start it manually 3.4.0 welcome is shown instead. Something is fishy for sure...

**Comment by ZephireNZ** [comment]
Note that I upgraded using the prompt within the app, not by reinstalling the setup exe

**Comment by jostrander** [comment]
@MarshallOfSound mentioned an issue with the startup script in another thread earlier today. I believe you need to open 3.3.0, disable auto start, and then close it, open GPMDP again and enable it.

**Comment by ZephireNZ** [comment]
If that's fixed should I close this issue, or shall I keep it open (and rename it for version mismatching)?

**Comment by jostrander** [comment]
Does 3.4.0 show the correct notifications? Did what I suggest fix 3.3.0 auto launching?

**Comment by ZephireNZ** [comment]
Yep, the startup script was launching 3.3.0 instead of 3.4.0, and disabling helped. I was just asking if it'd been fixed in upstream so that when it updates to, say 3.5.0, it won't happen again. Otherwise may as well keep this around as a tracker of fixing that.

**Comment by jostrander** [comment]
Ah, well if 3.4.0 has fixed notifications I'd close this and open a new issue about the start up script. If @MarshallOfSound has fixed that already he'll swing by and close it.

**Comment by MarshallOfSound** [comment]
@ZephireNZ I'll save you some time it was fixed in https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/commit/80010fc98511af44c32c1593889b5171781240f7
