### ISSUE TITLE
No Right-Click Menu from Search input area [OS X 10.11.4]

### ISSUE THREAD

**Issue by jwmann** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1431]
I find it a little strange that you can't right-click and copy/paste from the search input area.

This may not technically be a bug but I do feel like this breaks certain usability standards for an OS. Would be very useful. 👍

**Comment by MarshallOfSound** [comment]
You can use the keyboard shortcuts and the Edit menu from your OS.

Unfortunately implementing our own context menu is a lot of effort and maintenance, and the electron implementation of custom context menus is still a bit buggy.

I'm going to close this out for now as solutions exist (the menu and keyboard shortcuts) until Electron's context menus are not as buggy
