### ISSUE TITLE
Monochrome Notification Icon on Linux

### ISSUE THREAD

**Issue by davilera** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1432]
**OS:** Linux / Ubuntu 16.04

**Issue Descriptions:** In Unity (and probably other desktop environments), notification icons are supposed to be monochrome. This is how the icon looks like, though:

![image](https://cloud.githubusercontent.com/assets/12100954/17507293/384df4d0-5e0f-11e6-93a5-3f745f6db583.png)

which clearly doesn't match the appearance of other icons.

**Steps to Reproduce:** Just start the app and look at the notification area.

**Solution:** Is it possible to create a monochrome icon for Linux?

**Comment by MarshallOfSound** [comment]
If someone PR'ed a linux only monochrome version of the tray icon I would accept it 👍

**Comment by SolarLiner** [comment]
Someone's also using the Paper theme! I was thinking the same thing. Maybe a transparent SVG could do it (make it resolution independant) ?

**Comment by MarshallOfSound** [comment]
@SolarLiner Electron doesn't support SVG icons as tray icons.  Only PNG

**Comment by SolarLiner** [comment]
Then it becomes a simple reason job. The circle becomes white and the note
becomes transparent.

Le ven. 12 août 2016 à 15:14, Samuel Attard <notifications@github.com> a
écrit :

**Comment by berryelectronics** [comment]
I'll take that one

**Comment by berryelectronics** [comment]
#1457

**Comment by MarshallOfSound** [comment]
Closed in #1457

**Comment by Pilot-Pirx** [comment]
You forgot about those users who have a light theme enabled.
They need a dark icon... ;-)

![bildschirmfoto vom 2016-08-19 23-08-14](https://cloud.githubusercontent.com/assets/6442166/17824419/2a228a14-6662-11e6-84d3-a1319fbcee5f.png)

**Comment by berryelectronics** [comment]
@MarshallOfSound any way to get the standard Desktop icon color and apply it to the icon within nodejs?
