### ISSUE TITLE
macOS Sierra Beta Unable to play music

### ISSUE THREAD

**Issue by crtunematt** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1434]
**OS:**
macOS Sierra 10.12 Beta (16A270f)

**Issue Descriptions:**
Every time I open it, it successfully loads music, even allowing me to search for music. The problem does not occur until I attempt to play a song. When I click on a song to play it, the little audio bars start to move, but the bottom area showing the progress of the song and the play/skip buttons are all grayed out and it tells me that it couldn't play the song and skipped it.

**Steps to Reproduce:**
Open the app. Go to a song. Click play. It will give the error.

<img width="1200" alt="screen shot 2016-08-09 at 11 28 59 am" src="https://cloud.githubusercontent.com/assets/12954311/17524518/9b6b3eaa-5e24-11e6-8c37-e8c7a6810c27.png">
<img width="1193" alt="screen shot 2016-08-09 at 11 29 16 am" src="https://cloud.githubusercontent.com/assets/12954311/17524528/a1cb65a4-5e24-11e6-89bd-74bbd4ee657b.png">

**Comment by MarshallOfSound** [comment]
Unfortunately I'm going to follow the pattern of CEF and Electron issues here.  Basically until Chromium supports Sierra I can't put any effort into bugfixing it.

This appears at first glance to be a DRM MP3 issue on Sierra.  But yeah, I can't fix that Chromium need to.

Closing as Upstream and out of scope.

**Comment by crtunematt** [comment]
Thank you for your quick response. :)
