### ISSUE TITLE
Volume control hotkeys no longer working [Win 10][3.4.0]

### ISSUE THREAD

**Issue by Varelse4** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1435]
**OS: Windows 10**

**Issue Descriptions: My volume control hotkeys no longer work. It is not solved by restarting my computer or doing what is suggested in the FAQ.**

**Steps to Reproduce: Set volume down/up hotkeys and observe how they don't work.**

**Comment by MarshallOfSound** [comment]
Fixed in master.  Duplicate #1422
