### ISSUE TITLE
Feature request: Option for single-click restoring from tray [Windows]

### ISSUE THREAD

**Issue by vanushah** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1437]
I wish I could restore the minimized player to tray with a single click. It is handier and faster.

**Comment by MarshallOfSound** [comment]
It is also non-standard and therefore I don't really want to implement it.  Think about every other tray icon application.  You have to double click to restore.

Skype
Chrome
Steam

Etc.
