### ISSUE TITLE
Unable to Re-Subscribe, Breaks the App, Uninstall Broken

### ISSUE THREAD

**Issue by greynewell** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1439]
**OS:**
Windows 10
**Issue Descriptions:**
After clicking the "Re-subscribe" button on an account after its active subscription has lapsed, you are taken to the signup area, which errors out (after google charged my credit card but before my subscription got updated to active- I ended up having to upgrade my subscription on Google's website, currently am double charged, I'm certain between Google and AmEx I can sort this out). Then, you can't get back into the music portion of the app. Then, when I try to remove the program in the Apps & Features window, the program simply doesn't respond and won't remove from the list.
**Steps to Reproduce:**
Log in with an expired account and attempt to re-subscribe. Uninstallation issues may occur across windows 10.

**Comment by MarshallOfSound** [comment]
Yeah, not a good plan.  I thought we disabled the resubscribe button as I didn't want users to be putting payment details into the app (or even given the option to do so) for security reasons.

I.e. It freaked some people out so I hid the button 😕 

I'll make sure that button is gone.

As for the uninstall issues, can you try force quitting the app (through task manager and then uninstalling)

**Comment by greynewell** [comment]
I have force quit, uninstalled and reinstalled and it's still stuck on the family subscribe page and I can't get back to music :/

Grey Newell, M.S.E.
Software Engineer
www.Cloud9Ortho.com<http://www.cloud9ortho.com>
(706) 669-1218




On Thu, Aug 11, 2016 at 3:52 AM -0400, "Samuel Attard" <notifications@github.com<mailto:notifications@github.com>> wrote:


Yeah, not a good plan. I thought we disabled the resubscribe button as I didn't want users to be putting payment details into the app (or even given the option to do so) for security reasons.

I.e. It freaked some people out so I hid the button ?

I'll make sure that button is gone.

As for the uninstall issues, can you try force quitting the app (through task manager and then uninstalling)

-

**Comment by MarshallOfSound** [comment]
@greynewell This might be related to #1441
