### ISSUE TITLE
Play music home screen spinning indefinitely - can't logout

### ISSUE THREAD

**Issue by shawnwall** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1441]
**OS:**
macOS 10.11.5

**Issue Descriptions:**
When opening the app, the home screen of play music loads, but contains a spinner that never goes away. I can't do anything. It was working yesterday.

For scenarios like this, perhaps an option to log out or reset the client via settings would be helpful.

**Steps to Reproduce:**
Re-open app at some point after successfully logging in

**Comment by ja-som** [comment]
I have the same issue on Windows 10, most of the time it only spins...

**Comment by jadengore** [comment]
I have this same issue.

**Comment by Nekrozys** [comment]
Same here. It worked fine until yesterday and now it spins: 
http://i.imgur.com/0THKC5f.png

**Comment by mrmagician8787** [comment]
Does closing and reopening work? I've noticed this happens sometimes if I'm away for awhile and come back and unlock the computer. But restarting the application has always fixed it.

**Comment by MarshallOfSound** [comment]
This is a Google Play Music issue (nothing to do with us).  People have been reporting it on Reddit since yesterday.

Clearing cache may help (but probably won't).

You can do it manually by deleting the `%APPDATA%/Google Play Music Desktop Player` folder
