### ISSUE TITLE
Back Button Functionality Broken

### ISSUE THREAD

**Issue by mrmagician8787** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1442]
**OS:** Windows 7

**Issue Description:** Mouse navigation buttons (back/forward) no longer work for navigation by default. Expected them to bring me to the previous/next page by default, as they did in 3.3.0. Issue first noticed in 3.4.0 after updating.

**Steps to Reproduce:** Navigate to any page within the application. Click something. Click back button. No response noted.

**Comment by MarshallOfSound** [comment]
Fixed in master.  Please check closed issues before raising duplicates

**Comment by mrmagician8787** [comment]
Fixed in master but not redeployed yet? I checked closed issues, this seemed to be something new in 3.4.0. I did not encounter it before updating.

**Comment by MarshallOfSound** [comment]
#1429 #1425 #1423 

A quick look at the first page of closed issues revealed those ones from the last few days.

And yes, fixed in master but not in a released version

**Comment by mrmagician8787** [comment]
My bad, hope to see a new release out soon. Thanks for the awesome tool, it's become my daily driver for  music lately.
