### ISSUE TITLE
3.4.1 and 3.4.2 keep the loading animation on start

### ISSUE THREAD

**Issue by bondt** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1445]
**OS:** Mac OSX Yosemite 10.10.5

**Issue Descriptions:** After the initial loading animation (the bigger one), a smaller loading animation blocks me from accessing my albums that are visible in the back. When I focus the search field (by hitting slash (/) on the keyboard, because of the loading layer) and enter 1 (one) character, the layer is gone and all _seems_ well, but isn't. When I enter 2 (two) characters, the layer comes back and blocks everything again.

**GPMDP version:** 3.4.1 and 3.4.2 where I noticed it.

**Steps to Reproduce:** Start GPMDP and wait for the albums to appear.

**Comment by MarshallOfSound** [comment]
3.4.2 is intended to fix this issue

**Comment by MarshallOfSound** [comment]
3.4.2 is intended to fix this issue

**Comment by bondt** [comment]
I am running 3.4.2 and it still happens to me. 😭 
I can enter the Google Music URL with Cmd + Shift + G, but when I interact (double click an album), it blocks again.

**Comment by MarshallOfSound** [comment]
I don't get this issue but I few others are.  Can you come to gitter to discuss

**Comment by bondt** [comment]
I'm in.

**Comment by miguelcostaUI** [comment]
I'm getting this issue too. It doesn't get past the loading animation. Version 3.4.2

**Comment by guiJedi** [comment]
Same on Windows 10 :(
3.4.2

**Comment by miguelcostaUI** [comment]
Also the app is opening 3 Helpers.. I don't think that should be right..

<img width="912" alt="screen shot 2016-08-11 at 11 19 20" src="https://cloud.githubusercontent.com/assets/20951805/17585761/743712e0-5fb5-11e6-9c49-04d08b9955a4.png">

**Comment by MarshallOfSound** [comment]
@miguelcostaUI That is correct.

**Comment by MarshallOfSound** [comment]
Thanks to @bondt the (hopefully final) issue has been identified and a fix will be rolling out shortly.

**Comment by MarshallOfSound** [comment]
Fixed in `3.4.3`

If it isn't, I'm done... 😆

**Comment by bondt** [comment]
Thanks a billion!

**Comment by guiJedi** [comment]
Thx, it's fixed for me!

**Comment by Russta** [comment]
Can confirm I had this problem and the new build has fixed it. Thanks!

In case it helps anyone, I had to close the player through task manager to get it to detect the update.

**Comment by MarshallOfSound** [comment]
@Russta You only check for updates ever so often 👍 But when you open it checks right away, you found a quicker way to get an update 😆

**Comment by miguelcostaUI** [comment]
It is fixed for me too. thanks
