### ISSUE TITLE
feature: Permit searching of songs in a Playlist

### ISSUE THREAD

**Issue by Zarthus** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1446]
**OS:**
Windows 10

**Issue Description:**
I would like to be able to type while in a playlist to find the song matching those keystrokes. 

In Spotify, when in a playlist, you can for example type "C" and it will find the first song that starts with a "C". You can continue typing to get more refined results.

In GPMDP several hotkeys have other assignments, so perhaps the search input area should be used instead. Perhaps a small checkbox for "search in playlist" or having a `in:playlist` keyword similar to google search. The implementation does not matter a whole lot, but I'd appreciate being able to find a song quickly in my larger playlists.

Thanks!

**Comment by MarshallOfSound** [comment]
This is currently not possible due to Google's unique way of rendering playlists.  They render only a few songs at a time which means we can't figure out what other songs are in the current playlist without scrolling all over the page.
