### ISSUE TITLE
My Library button not working on Windows 10 with Anniversary Update

### ISSUE THREAD

**Issue by DRSXS** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1447]
**OS:**
Windows 10 with Anniversary Update

**Issue Descriptions:**
https://gyazo.com/79a77c35edb4c053207463762b122589
The "My Library" button shows as undefined and when I click it nothing happens. When I then close GPM-DP and open it again it opens with the my library tab when I clicked it before.

This must be an issue that came with the new Windows Anniversary Update as this issue was not present before.

I'm using the newest version of GPM-DP with the new update that just came out and the issue persisted before the newest update and after.

**Comment by MarshallOfSound** [comment]
This is almost certainly nothing to do with the Anniversary update.   I'm been on the insider preview channel for months and I have had no issues like this at all.

I think it is just a GPM glitch that can be fixed by clearing the cache.  Just delete the `%LOCALAPPDATA%/Google Play Music Desktop Player` folder and restart the app.

**Comment by DRSXS** [comment]
Thanks for the quick response. I cleared the cache by completely deleting the folder and then I launched GPM-DP and the button is working again 😄 But it still showed as undefined

Alright, I uninstalled Bonjour. (gpmdc.log always showed an error loading Bonjour). And now the button displays normally too 👍 

Anyway, thanks for making a really awesome program 😃

**Comment by Thor77** [comment]
Still showing as `undefined` for me after an update to the latest version and removing `.config/Google Play Music Desktop Player` on Archlinux (using `gpmdp-git` aur-package)

**Comment by DRSXS** [comment]
@Thor77 Yeah, it just happened again for me too. But I think it's an issue with GPM itself. So I guess we'll just have to wait for Google to fix it.

**Comment by Thor77** [comment]
Oh, right. It's also wrong on GPM's webinterface oO
