### ISSUE TITLE
Feature Request: More options for title click action.

### ISSUE THREAD

**Issue by Martermann** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1449]
It would be great if there was a switch so that you could chose what happens if you click a title.
By default play music creates a new playlist. I would love it, if it was possible to change this with a switch, so that play music ads the selected title to the queue **or** plays it as next title **or** does the default thing.

OS: Win 10
Version: 3.4.3

**Comment by MarshallOfSound** [comment]
Please explain what you mean by "title"

**Comment by SolarLiner** [comment]
I'd say track title? And by "playlist" he means the play queue?

**Comment by MarshallOfSound** [comment]
@SolarLiner I'm confused, because they say "by default play music creates a new playlist" but I am not aware of **any** title that when clicked performs this action.  Hence the clarification request

**Comment by Martermann** [comment]
I have to explain myself a little bit better i guess. 
First I'm sorry for my problems causing English.

What I mean is that Play Music creates a new queue if you double click any title (e.g. a searched one) .
This new queue overwrites the current queue. 
What I want is a function to set Play Music to play the clicked title as next song or to add it to the current queue.

I used my poor MS-Paint (yes shame on me) skills for an example of the menu:

![unbenannt](https://cloud.githubusercontent.com/assets/18559453/17625659/162d3f9e-60aa-11e6-870b-b605c1b49562.PNG)

**Comment by MarshallOfSound** [comment]
The alternate actions you have listed are currently abstracted inside GPM and we have no way to access or influence them in any way.  This is an architectural thing of GPM that we have no control over.
