### ISSUE TITLE
Error 10 (BadAccess (attempt to access private resource denied)): request 28.0

### ISSUE THREAD

**Issue by yochaigal** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1450]
Arch Linux 64bit; Nvidia drivers. 
Essentially what happens is that I launch GPMDP and it hangs at the sign-in screen. Deleting local config makes the app work once; then it does it again.

Running with --disable-gpu doesn't help.

Output from Terminal:
error: Last.fm API keys have not been set!
*** WARNING *** The program 'Google Play Music Desktop Player' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=Google Play Music Desktop Player>
*** WARNING *** The program 'Google Play Music Desktop Player' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=Google Play Music Desktop Player&f=DNSServiceRegister>
Error 10 (BadAccess (attempt to access private resource denied)): request 28.0
Error 10 (BadAccess (attempt to access private resource denied)): request 28.0

**Comment by jostrander** [comment]
Did you check the FAQ? You may need to disable gpu rendering.

**Comment by jostrander** [comment]
My bad I just saw you tried that.

**Comment by MarshallOfSound** [comment]
@yochaigal It looks like you have some interesting file system permissions set up and / or are attempting to run the app in some kind of sandbox.

Do you have an FS log which shows which files it is trying to access?

**Comment by yochaigal** [comment]
File permissions are as expected (e.g. /home/yochai/.config is owned by
yochai:users) and I'm not trying to sandbox anything!
Further proof of weirdness: the problem occurs on *another* Arch Linux
64bit desktop with a different nvidia card - my work PC. It does the exact
same thing!

**Comment by jostrander** [comment]
Can you confirm this is still an issue on 3.5.0?

**Comment by yochaigal** [comment]
It appears to be fixed.
Thanks!
