### ISSUE TITLE
Java Script error

### ISSUE THREAD

**Issue by bryan1545** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1451]
**OS:**
Windows 10 1511
**Issue Descriptions:**
i'm getting the java script error from #1325  after the update i dont know if this was fixed in the latest update (which i am running) i know how to fix it i was just wondering if this was supposed to be fixed in the latest update
**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment]
Are you sure it was that **exact** error and are you sure it happened after you had updated and not during the update process.

**Comment by bryan1545** [comment]
yes i got those same errors again. i am sure i was running the newest version for more than one dayit thing it happened after my computer restarted (idk how it did) and started configuring windows update

**Comment by st33ly** [comment]
I'm having the same issue. Installed yesterday and was working fine. Started up this morning and [this ](https://i.imgur.com/RwAEqv9.png)popped up

**Comment by st33ly** [comment]
Nevermind, I fixed it by deleting the directory %APPDATA%\Google Play Music Desktop Player\json_store

**Comment by MarshallOfSound** [comment]
@bryan1545 I know for a fact it can't be those **exact** errors because quite simply can't possibly appear anymore 😆 

However, they could look **VERY** similar.  Could you provide a screenshot of these errors?

**Comment by bryan1545** [comment]
I actually deleted the json_store folder like people did in the #1325 issue and it worked fine again

**Comment by bryan1545** [comment]
I am going to see if I can make them appear again

**Comment by MarshallOfSound** [comment]
Closing till it can be reproduced
