### ISSUE TITLE
"Music Library" menu item text `undefined` after last update

### ISSUE THREAD

**Issue by Marwelln** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1452]
**OS:**  Windows 10, English language

**GPMDP Version:** 3.4.3

**Issue Descriptions:**

The "Music Library" menu item text `undefined` after last update.

[https://imgur.com/a/W3xS6](https://imgur.com/a/W3xS6)

**Comment by NotAdam** [comment]
This is actually an issue with the actual google play music website, not the app itself. Go to https://play.google.com/music/listen?u=0#/now and open the menu and you'll see it's the same there.

**Comment by Marwelln** [comment]
You're right.
