### ISSUE TITLE
Page never stops loading when update server can't be reached

### ISSUE THREAD

**Issue by SolarLiner** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1454]
**OS:** Linux / Ubuntu 16.04

**Issue Descriptions:** Upon launching, the page has a semi-transparent layer, on top of which is a spinner. Google Play Music loads fine under Chrome and Nuvola Player. Running with `--disable-gpu` doesn't resolve the issue. I've gather it's the update server preventing the app to finish loading the page from the stdout when launching from the terminal.
![screenshot from 2016-08-12 14-51-36](https://cloud.githubusercontent.com/assets/4302963/17622884/6405dcc4-609d-11e6-9536-7cffa1001996.png)

**Steps to Reproduce:** Open the application through the terminal and watch the stdout. Might be hard to reproduce unless sloppy internet connection, like where I am right now :/

**Comment by MarshallOfSound** [comment]
Please update to version `3.4.3` which was released a while ago that fixes this problem

**Comment by MarshallOfSound** [comment]
Also

> I've gather it's the update server preventing the app to finish loading the page from the stdout when launching from the terminal.

This is wrong.  So so wrong, the logs you see are just that. Logs, they aren't preventing the app from starting.

**Comment by SolarLiner** [comment]
I haven't said logs prevented the app from starting. I said that when
starting the app from the terminal, I observed that the connection to the
update server was what was preventing the page to finish loading.

**Comment by MarshallOfSound** [comment]
@SolarLiner 

> I observed that the connection to the
update server was what was preventing the page to finish loading.

Dodgy observation, more of a correlation / coincidence 😆 

However it is interesting that you can't ping the update server.  Are you behind a proxy / firewall

**Comment by SolarLiner** [comment]
True that ! 😅

Well I don't really know I was out camping and the place had hotspots all
over the place, and the connection wasn't really stable. Maybe it hit a
connection reset error... AFAIK there were no blacklists on those.

Le sam. 13 août 2016 à 18:22, Samuel Attard <notifications@github.com> a
écrit :
