### ISSUE TITLE
Play Button doesnt change in dark mode its inner color

### ISSUE THREAD

**Issue by berryelectronics** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1458]
![ss 2016-08-12 at 05 25 31](https://cloud.githubusercontent.com/assets/12616124/17628724/1879614e-60b7-11e6-9d9d-5be1ed7d9856.png)

When nothing is in the queue. doesnt seem right to me. Maybe make the inner Triangle dark in the dark mode?

**Comment by MarshallOfSound** [comment]
This is correct, it is the "stop" position and is identical to the light theme (this was considered correct by the `gmusic-utils` team)
