### ISSUE TITLE
Smartscreen

### ISSUE THREAD

**Issue by chrismou** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#146]
Not sure if this is even an issue, downloaded the latest installer and when I ran it it popped up with the smartscreen warning, telling me something about trying to run an unrecognised file downloaded from the internet and had to confirm with my password before it'd run.

Generally I'd just assume this was normal, but I recall reading something on your release notes about an Microsoft signed key, so just an FYI in case this isn't expected behaviour.

**Comment by MarshallOfSound** [comment]
It's expected for a while and appears to be only on some machines, smart screens works based on a "trust" system.  So the more people that install it the higher a "trust" level it gets.  The certificate actually reset my trust level as previously I was using a personal self signed cert (which apparently had a trust level.......)

Normally it takes a few weeks for microsoft to figure out that a cert is legit and its only been about 8 days I think.  So I'll close this for now, but if it still happens in a couple of weeks when I do my installation tests for V2.1 I'll take it up with Microsoft Dev Support.

**Comment by chrismou** [comment]
:+1: No worries, like I say, was just a heads up in the case the cert was borked or something

If I spot it again after say Feburary, I'll let you know :smile:

**Comment by d-rez** [comment]
Just dropping by to let you know that I had the same appear on mine today (22.07.2016)
