### ISSUE TITLE
Google Play Music Desktop Player crashes immediately

### ISSUE THREAD

**Issue by chefreinhold** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1460]
Hi,

Whenever I open Google Play Music Desktop Player on my Windows 10 machine it crashes and closes immediately after loading. I can only avoid this issue if I completely delete GPMDP from my system. After a  new install and I log in it will run, however, once I close the program and reopen it again... crash. 

This has been an ongoing issue for me  since Version 3.3.0

Thanks.

**Comment by MarshallOfSound** [comment]
Please provide your log file found at `%APPDATA%/Google Play Music Desktop Player`

**Comment by st33ly** [comment]
try deleting the directory %APPDATA%\Google Play Music Desktop Player\json_store

**Comment by chefreinhold** [comment]
@MarshallOfSound 

Hi,

Thanks for being so quick to reply. Hope I'm copying the correct file. If not, please let me know where I can find a more thorough log. Otherwise here is what I got from _gpmdc.log_ located at 

> C:\Users\*username*\AppData\Roaming\Google Play Music Desktop Player

http://pastebin.com/zhmErX1W

**Comment by chefreinhold** [comment]
@st33ly 

Thanks for helping me out. Unfortunately, that didn't help. It behaved the same way and just recreated the folder upon loading.

**Comment by Abhishek2309** [comment]
Hi 
Whenever I open the app, a white screen popups. 
![file](https://cloud.githubusercontent.com/assets/21009537/17643881/6546d604-6194-11e6-82dc-1a9925c25104.png)
please Fix this.
I really Want to use this app

**Comment by MarshallOfSound** [comment]
@Abhishek2309 Looks like your GPU drivers are a bit broke 😆 Try updating or reinstalling them

@chefreinhold As this is likely to be an Anti Virus issue or system specific issue I'm going to close this out.  I do want to help you get it working though so when you're up and have some time to go through some debugging steps with me msg me on Gitter. (Link in the README).  Just be aware I am currently running on AEST (Melbourne Time).
