### ISSUE TITLE
Old icon shows up in list of programs

### ISSUE THREAD

**Issue by pcjl** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1463]
**OS:** Windows 10

**Issue Descriptions:** In the window for "Programs and Features", the listing for the Google Play Music Desktop Player is still using the old icon.

**Steps to Reproduce:** 

Picture: 
![image](https://cloud.githubusercontent.com/assets/15951072/17645940/44f6ce52-6182-11e6-9786-5d33a4c9df2c.png)

**Comment by MarshallOfSound** [comment]
Unfortunately current installs won't get the new icon unless they reinstall (I just updated the icon on the server)

**Comment by pcjl** [comment]
I tried uninstalling and then reinstalling but it still shows the old icon. Version 3.5.0.

**Comment by MarshallOfSound** [comment]
@pcjl Probably cached at some level, either on your machine or in my servers cache. Will look into it a bit later
