### ISSUE TITLE
[macOS] No update after notification

### ISSUE THREAD

**Issue by dkohtes** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1465]
**OS:**
macOS 10.11.6

**Issue Descriptions:**
Updates are not working. I do get a notification for a new version and click to start the update. GPMDP quits - and after a pause the "old" version is started again. No update.

This happened already with several older versions. I just download the latest version from your website to stay up to date.

**Steps to Reproduce:**
When ever a new version is available I get the notification each time I start GPMDP. And every time when I click to start the update it doesn't get updated.

Hint: I am working on a user account without admin rights. Usually I get asked for my admin password when updates need to get installed.

**Comment by MarshallOfSound** [comment]
This was an issue of Squirrel.Mac which I believe was fixed with the latest update due to the Electron version bump internally.

If this happens on the next update please re-raise this issue (or reopen) 👍
