### ISSUE TITLE
Lyrics: let the user scroll to the text and go on to auto-scroll from there

### ISSUE THREAD

**Issue by dkohtes** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1466]
It would be great if I could scroll through the lyrics by myself and the auto-scroll would just go on from where I stop to scroll.

Sometimes the auto-scroll is to fast, sometimes it is to slow and then sometimes I just want to have a look around faster or slower. :-)

**Comment by MarshallOfSound** [comment]
This would make the maths involved insanely complicated.  And it is already pretty tricky to figure out what's going on with the scroll calculation code.

I know the scrolling is sometimes off, but there is nothing realistically we can do about it 😢
