### ISSUE TITLE
Player icon tray in KDE looks weird

### ISSUE THREAD

**Issue by karaushu** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1468]
**OS:** Kubuntu 16.04 LTS x64

**Issue Descriptions:**  in KDE player tray icon looks strange, 
screenshot - http://storage4.static.itmages.com/i/16/0815/h_1471254472_3190177_4efa742b69.png

**Steps to Reproduce:**

**Comment by berryelectronics** [comment]
Problem with KDE.
#1350

**Comment by karaushu** [comment]
Thanks, got it!

**Comment by sasha-** [comment]
This was dirty fix that worked for me on ubunutu and plasma 5 after installing GDMP 4:

```
cd
mkdir tmp
cd tmp
npm install asar
```
If npm is not installed then apt install npm
```
./node_modules/asar/bin/asar e  /usr/share/google-play-music-desktop-player/resources/app.asar app
find app/build/assets/img/ -name '*tray*png' -exec convert {} -resize 32x32 {} \;
```
32x32 looks good in my tray. Original size is 128x128
```
./node_modules/asar/bin/asar p app/ app.asar
sudo cp app.asar /usr/share/google-play-music-desktop-player/resources/app.asar 
```
