### ISSUE TITLE
Maximized window obscures auto-hidden task bar

### ISSUE THREAD

**Issue by DavidDuwaer** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1470]
**OS:** Windows 10

**Issue Descriptions:** I use the auto-hide task bar feature of Windows. When in "hidden" mode, the task bar sticks out a single pixel deep into the screen. When hovering over this, the task bar shifts back into view. The Google Play Desktop Music Player, when maximized, however obscures the remaining bit of task bar so that the hovering doesn't work anymore. Compare this with, say, Google Chrome, which leaves single row of task bar pixels unobscured. I think Microsoft did a shitty job by even allowing maximized windows to obscure it, but this is how it is.

**Steps to Reproduce:** Just select 'auto-hide the tasbar in desktop mode' in the taskbar settings (or taskbar properties in older versions of Windows 10) and maximize the player.

**Comment by MarshallOfSound** [comment]
This comes down to how Windows has implemented chromeless windows.  We (through Electron) simply call win32 API's to maximize and there is nothing we can do if Winodws is telling us to be bigger than we should be.  Sorry this is annoying you, but I've reported it to the Insider bug tracker on Windows 10 as I can reproduce the issue with a borderless WinForm.
