### ISSUE TITLE
Translation Problem

### ISSUE THREAD

**Issue by Matheus-de-Souza** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1472]
**OS:**
Windows 10

**Issue Descriptions:**
I can't change the language to english.
The portuguese translation is partial and buggy. 

**Steps to Reproduce:**
Just open the program with the SO language in portuguese (pt-br).

![captura de tela 2016-08-16 13 35 59](https://cloud.githubusercontent.com/assets/865597/17707428/c7980566-63b6-11e6-9786-54aff2058398.png)

**Comment by MarshallOfSound** [comment]
@Matheus-de-Souza PR's are welcome to fix the translations, they are community sourced.

**Comment by Matheus-de-Souza** [comment]
@MarshallOfSound Ok. But, there'

**Comment by Matheus-de-Souza** [comment]
@MarshallOfSound Ok, but I still miss the feature to change the program language to english if I want to. I would like to use the program in english, but unless I remove the pt-BR.pak file I can't do it.

**Comment by MarshallOfSound** [comment]
Subscribe to #1414

**Comment by Matheus-de-Souza** [comment]
:+1:
