### ISSUE TITLE
Feature: User stylesheet

### ISSUE THREAD

**Issue by Alanaktion** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1475]
The custom theme is nice for the simple changes like dark mode and custom accent color, but a full user stylesheet feature would be great for allowing more detailed UI changes. For example I would love to be able to decrease font sizes and padding throughout the app. I would see this as an additional tab in the Desktop Settings with just a `<textarea>` that added the contents to a `<style>` tag in the webview.

**Comment by MarshallOfSound** [comment]
Working on this at the moment.  Current implementation will allow you to choose two CSS files on your local filesystem.

One will be injected into all application windows to allow styling of the actual GPMDP windows and features.

The other will be injected into Google Play Music itself.

Pretty sure this implementation covers all requirements and is a lot nicer than just a `textarea` sitting in the settings menu.

**Comment by Alanaktion** [comment]
My only thought with that implementation is that it would be nice to either watch the files for changes in the background or allow re-applying them from the Desktop Settings to avoid having to restart the application to see changes.

**Comment by MarshallOfSound** [comment]
@Alanaktion Yeah, I'll be adding a refresh button 👍

**Comment by MarshallOfSound** [comment]
This has been implemented and will be out in the next release.  For those who want to write CSS that depends on the current theme.

Good news, you can 👍 

Familiarize yourself with our strange, custom and magical theming library syntax.

https://github.com/gmusic-utils/gmusic-theme.js/blob/master/lib/full.css#L14

All colors available can be found on the README https://github.com/gmusic-utils/gmusic-theme.js

Whenever the user updates their theme your custom CSS will be reloaded automatically
