### ISSUE TITLE
Cannot close the application from the Ubuntu unity launcher

### ISSUE THREAD

**Issue by Gontran08** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1476]
**OS:**
Ubuntu 16.06.1 with Unity
**Issue Descriptions:**
I cannot close Google Play Music Desktop Player from the unity launcher. Nothing happens. I must use the system tray icon to quit.
**Steps to Reproduce:**
Just open the application normally and try to close it with the launcher, nothing happen.

**Comment by jostrander** [comment]
I believe there is an option in settings for minimize to tray on close. When enabled closing the application in the tray is equivalent to pressing the close icon in the title/menu bar. Is that option enabled?

**Comment by MarshallOfSound** [comment]
@Gontran08 This has come up before and it a unity issue.

Basically they are firing window close requests instead of application quit requests.  If you disable "minimize to tray" in settings.  The button will work for you.

**Comment by Gontran08** [comment]
I see. In that case, the problem is that you minimize the window instead of closing it. The window stay in the launcher. If I compare the behavior with Skype, when I close the window, it is closed and the only way to open Skype again is to use the system tray icon. The window do not stay in the launcher, so the context menu is not accessible. It's a trivial problem, but I think it explains my misunderstanding.

**Comment by jostrander** [comment]
The program tries to skip the task bar on linux, but unity doesn't play nicely. 

See here: https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/main/features/core/controlBar.js#L27
