### ISSUE TITLE
Uncaught Exception: Attempting to call a function in a renderer window that has been closed or released. Function provid

### ISSUE THREAD

**Issue by ethaksus** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1478]
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.3.0
**Time:** Tue Aug 16 2016 20:03:23 GMT-0400 (Eastern Daylight Time)

#### Error:
*Attempting to call a function in a renderer window that has been closed or released. Function provid*
```js
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: Object.<anonymous> (C:\Users\USER_NAME\AppData\Local\GPMDP_3\app-3.3.0\resources\app\build\inject\GPMWebView\interface\customNavigation\mouseButtonNavigation.js:9:1167.
    at BrowserWindow.callIntoRenderer (C:\Users\Daniel\AppData\Local\GPMDP_3\app-3.3.0\resources\electron.asar\browser\rpc-server.js:186:19)
    at emitTwo (events.js:111:20)
    at BrowserWindow.emit (events.js:191:7)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
You are quite a few version behind.  Latest is `3.4.3`, please update as this issue is fixed

**Comment by ethaksus** [comment]
Alright, also, is there a proper way to anonymize the codeblock? I don't really want to disclose my name publically.

**Comment by MarshallOfSound** [comment]
No one's really mentioned that before, but I'll see if I can strip out usernames from the the report
