### ISSUE TITLE
Library now reads as "undefined"

### ISSUE THREAD

**Issue by paulietheboss** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1479]
I noticed that since the last update, the Library button (left panel, between Listen Now and shop) now reads as "undefined"

Not a biggie as everything still works, but just thought I'd let you know.

**Comment by MarshallOfSound** [comment]
This is a google issue.  Check in chrome, the same thing will happen

**Comment by paulietheboss** [comment]
My bad, it shows music library in my app on the phone, but I didn't think to check in chrome because... GPMDP is too excellent to look there any more :) thanks for quick response, sorry about confusion!
