### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by Devo7v** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#148]
I didn't see a good place for feature requests so I figured I'd post here.

1.  Double clicking anywhere on the miniplayer opens the full player.  Depending on how small someone makes the miniplayer it can be difficult to click the even smaller expand button.
2. The ability to change how long the splash screen is shown or even disable it completely.  It just seems that between 1.9.2 and 2.0 the program takes longer to start up and I've attributed that to the time the splash screen is shown without knowing the root cause.  Maybe that's not the case and you are using the splash screen to let the user know that the program is loading a lot of resources in the background.

If there's somewhere else I should be posting feature requests I will gladly do that.  Keep up the great work.

**Comment by MarshallOfSound** [comment]
@Devo7v I'll take a look at this a bit later but quickly now.  The splash screen is not in `2.0.0` as far as I am aware...

Are you on a beta?

**Comment by Devo7v** [comment]
Sorry, I'm on 2.0.2

**Comment by MarshallOfSound** [comment]
@Devo7v Still doesn't make sense, the splash screen was added between the 2.0.2 release and now.

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/compare/2.0.2...master

**Comment by Devo7v** [comment]
It looks like I am using a beta version. It was the first version labeled
as 2.0.2 on AppVeyor for my portable installer, which included the splash
screen. Sorry for the confusion.

**Comment by eturk1** [comment]
BTW, what is the latest version. 
tuned out when 4K DPI made app have super tiny txt

is that fixed?
is there a beta channel build(s) to test and offer feedback?
is version now in exe to see what ver we've got?

**Comment by MarshallOfSound** [comment]
@eturk1 4K DPI issues have been entirely fixed but not released yet, you can enjoy that fix if you jump on to the betas from appveyor.

A proper opt in beta channel will open up in the next release

**Comment by eturk1** [comment]
Thanks!
Where to find appveyor beta?

**Comment by MarshallOfSound** [comment]
@eturk1 

Here is a link to the latest build, choose a platform (x86 or x64) and then choose "artifacts"

https://ci.appveyor.com/project/MarshallOfSound/google-play-music-desktop-player-unofficial

**Comment by eturk1** [comment]
ah, thanks a bunch @MarshallOfSound !

screen cap to compare scaling. Looks like app is still scaling smaller than what people will expand in a standard window:
![2016-01-21 1](https://cloud.githubusercontent.com/assets/525280/12491171/5eda4dd0-c02e-11e5-9521-1a92cae1f6ba.jpg)

**Comment by MarshallOfSound** [comment]
@eturk1, that doesn't look like the beta did you uninstall the old one first.

**Comment by eturk1** [comment]
I downloaded from here: https://ci.appveyor.com/project/MarshallOfSound/google-play-music-desktop-player-unofficial/build/job/mxujbwkg8nffk4l0/artifacts
is that correct place?

(uninstalled and deleted C:\Program Files\GPMDP as well before install)

**Comment by eturk1** [comment]
sure would be great to have a build # in exe properties/details :)

**Comment by MarshallOfSound** [comment]
OK so I've looked into these feature requests and here is my response

1. Not possible, in order to make the mini player draggable windows absorbs all click events on the window.  No way to determine a double click.
2. The mini player opening does not add any delay, it simply hides the initialization of Google Play Music therefore (wontfix)
