### ISSUE TITLE
Scroll wheel volume adjust still not working on miniplayer

### ISSUE THREAD

**Issue by Popinaodude** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1480]
I raised this issue here -> https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/1428

I was thankful for the quick response and after waiting for the last update the issue is still happening even after reinstalling.

OS: Windows 10

**Comment by MarshallOfSound** [comment]
Sorry, didn't publish a new release of `gmusic-mini-player.js` when I fixed it in `gmusic.js`

Published now will be fixed next release
