### ISSUE TITLE
Radio cards are super large and push others off screen

### ISSUE THREAD

**Issue by SimulatedGREG** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1481]
**OS:**
macOS 10.11.5
Google Play Music Desktop Player v3.4.3

**Issue Descriptions:**
Radio material cards are very large and push others off screen.
![image](https://cloud.githubusercontent.com/assets/8327811/17750686/52c2e7e6-6489-11e6-978e-7f791847ccb6.png)

**Steps to Reproduce:**
Simply opening the app and scrolling to the "Recommended for you" section on the "Listen Now" view.
Checked to see if this was a Google Music bug, but visiting music.google.com doesn't produce the same issue as all cards are sized appropriately.

**Comment by jostrander** [comment]
I just cycled through all the different theme settings, and with/without custom theme I can't reproduce this. I don't have access to OS X to test that platform but I'm not sure its limited to OS X.

**Comment by SimulatedGREG** [comment]
It's definitely the first time I've seen this, so maybe it is some sort of random occurrence. I'll report back if it is still happening later tonight.

**Comment by SimulatedGREG** [comment]
Well it would seem it was some sort of random occurrence. Thanks for the fast reply @jostrander. Closing
