### ISSUE TITLE
White Screen Window After Updating the Google Play Music Desktop Application on Windows 10 --disable-gpu Does Nothing, Sadness

### ISSUE THREAD

**Issue by eRobotson** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1483]
**OS:** Windows 10

**Issue Descriptions:**  The application is unusable, because the main window is a blank, white box.

**Steps to Reproduce:** The application takes a long time to do anything at all, and when it finally shows up, the main window is all white. Strangely, I can right-click on the system tray icon and load the settings window, but the actual player window is always all white. I have tried everything I've found online. I've tried several re-installs. I've scoured my machine to remove all related files. I even tried going back to the previous version, but the result is always the same, blank white screen.

**Comment by MarshallOfSound** [comment]
Sounds like a GPU issue, but just in case it isn't, have you deleted the following folders (at once) then reinstall.

```bash
%APPDATA%\Google Play Music Desktop Player
%LOCALAPPDATA%\GPMDP_3
```

**Comment by eRobotson** [comment]
I don't seem to have that path, but I have this path, and I deleted that and tried a re-install with the same white box result. Any other ideas? I love this app. It's a tragedy to see it like this...

C:\Users\me\AppData\Local\GPMDP_3

**Comment by MarshallOfSound** [comment]
Can you come on Gitter to discuss this, almost certainly a system specific issue.

**Comment by eRobotson** [comment]
I've never used Gitter. I'm trying to find you there.

There has been a strange development.
It's gone from an all white box to an all black box.
I disabled the firewall on this machine, and the application allowed me to
login. I got excited thinking it was going to work, but after logging in,
the application became a plain, black box. Not sure if this is progress
from a plain white box or not.

**Comment by emorisch** [comment]
I'm currently having this same issue. I've used this in the past and when I launched it today, it mentioned the movement of the playlists to the other side. when I went to open my music library, it sits and does nothing for about 30 seconds, then white screen and nothing more.

**Comment by jostrander** [comment]
This is probably an issue with our script and the theming library with
Google's new changes. @Marshallofsound is working on a fix atm.
