### ISSUE TITLE
Player buttons missing from hovered taskbar

### ISSUE THREAD

**Issue by roryhewitt** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1486]
OS: Windows 7 Enterprise

When I hover over the taskbar item, when it pops up, I used to see Previous, Play and Next buttons, but now I just see the song title:

![image](https://cloud.githubusercontent.com/assets/11558891/17791895/b6ba5080-6552-11e6-9286-5f34e29e7753.png)

Steps to Reproduce: Hover over the taskbar.

**Comment by roryhewitt** [comment]
Dupliactes #1427

**Comment by MarshallOfSound** [comment]
#1427 is not the duplicate for this issue.

But this is a duplicate that is getting fixed Upstream.

I PR'ed the fix recently https://github.com/electron/electron/pull/6829
