### ISSUE TITLE
Mini Player key command ?

### ISSUE THREAD

**Issue by christianbearslyclark** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1487]
how to get the Mini Player ? What's the key command because I have no clue. I would love to use the Mini Player... someday LOL

Google Play Music Desktop Player is the GREATEST ... since WimAmo !!!!

**Comment by MarshallOfSound** [comment]
Please ask question on Gitter.  This isn't technically an issue... :cry:

But the is a mini player button in the bottom right of your screen.

**Comment by christianbearslyclark** [comment]
Oh wow !!!  Thanks SMH  ha ha Thanks !!!!

Peace!
Christian
http://christianbearslyclark.net/
---------------------------------------
"He is no fool who gives what he cannot keep to gain what he cannot lose."
- Jim Elliot
