### ISSUE TITLE
Window control buttons glitch

### ISSUE THREAD

**Issue by seeb0h** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#149]
A gif says everything. 
![window_controls](https://cloud.githubusercontent.com/assets/4989990/12482908/8171f9dc-c052-11e5-97b8-e90215a58dca.gif)

I cannot click them and ugly (win32?) controls appear.

Win7, 2.0.2

**Comment by MarshallOfSound** [comment]
This has been fixed in master and will be pushed in the next release.  If you can't wait, there is a beta build available here

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/31#issuecomment-170509781

**Comment by seeb0h** [comment]
Ok. Sorry for the duplicate. I didn't checked closed issues.
The beta works fine.
