### ISSUE TITLE
Black screen on Windows 10 after new update

### ISSUE THREAD

**Issue by 19007361** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1490]
Computer; Dell Inspiron 15, 3000 series
OS: Windows 10 (not the Anniversary Update yet)

I only see an all black screen when opening the app. Yes, it is reproducible.

**OS:**

**Issue Descriptions:**

**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment]
@19007361 This is a GPU driver issue, please update your GPU drivers and GPMDP

**Comment by 19007361** [comment]
This is a brand new computer and I have the latest update of your app.
