### ISSUE TITLE
Can't go back to Full size player

### ISSUE THREAD

**Issue by Miamoto-Musashi** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1491]
**OS:**
OSX El Captain 10.11.5

**Issue Descriptions:**
the player stays mini the only way to bring it back to maxi is to restart it
relates to: issues #1262 #492

**Steps to Reproduce:**
Start Program
Window-MiniPLayer: the player goes mini
Window-Full Size Player: the player stays mini

**Comment by MarshallOfSound** [comment]
This has been fixed in master, it is due to an error being thrown inside the `mini-player.js` code
