### ISSUE TITLE
Remember full-screen mode setting on OS X

### ISSUE THREAD

**Issue by amancevice** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1492]
**OS:** 

OS X

**Issue Descriptions:**

When using this app, I often keep it in full screen mode as its own desktop space. Some OS X apps have the ability to remember this setting when starting up ([Atom](https://atom.io/) is an example). It would be nice to add that capability to this app so that it starts up in the same mode it was in when it quit.

**Steps to Reproduce:**

Open app, go full screen with `⌃⌘F`, quit app with `⌘Q`, open app again -- app is not full screen

**Comment by MarshallOfSound** [comment]
This was a design decision I made very early on, mainly because as a user I don't expect to open a media player and it to instantly go full screen.

That isn't normal, standard or done anywhere else I believe 👍 

Marking as `wontfix` due to design decision.  If you disagree I welcome alternative viewpoints but you'd have to provide examples of media apps doing it already in the wild before I would consider it.

**Comment by amancevice** [comment]
I do disagree, I think it's reasonable to assume that a user would like the state of the app to remain consistent. To be clear, I'm *not* saying *every time* the app starts it should be in full screen mode. Rather, that it should start in the mode it was in when it was last open.

Many OS X apps do this. The terminal app, Chrome, and Atom are examples. If you open Chrome on OS X, make it full screen, quit, and re-open it will open as a full screen app again. I don't think the fact that this app is a media app is relevant in this context -- it's behavior that I think could apply to all OS X apps.

**Comment by amancevice** [comment]
I should clarify -- the apps that I mentioned (Chrome, Terminal, Atom) behave this way if you adjust your OS X settings in `System Preferences > General > Uncheck "Close windows when quitting an application"`, which I don't believe is the default state of that checkbox.

Apologies; I've had that setting disabled for so long I forgot about it.

So perhaps what I am asking for is that GPMDP not close its window on quit so that OS X can take advantage of this setting.

**Comment by amancevice** [comment]
@MarshallOfSound Any response to the above? Apologies if you've already seen it.
