### ISSUE TITLE
Google Cast Issue after Long Pause

### ISSUE THREAD

**Issue by PolymorphicEngineeringSolutions** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1493]
-- OS & Platform --
MacOS Sierra Developer Beta 5 on a MacBook Pro 15" Retina (Late 2014)

-- Description --
It seems after a long pause for Google Cast (seems to be greater than 4-hours...), that the player has a difficulty re-establishing the Casting and sometimes requires a shutdown and restart of the application --> It is almost like GPMDP thinks that it is still connected to the Good Cast device/sink whereas the Google Cast device/sink has disconnected due to inactivity.  The Symptoms are a "greyed out" play button after the initial push/click to start the music again after which there is no movement on the progress bar for the track that should be playing.  Switching tracks does not have an effect either, the UI updates with the new track information however it does not play.  Sometimes this issue can be resolved by clicking on "Stop Casting", but more times than not it requires restarting the software.

-- Steps to Reproduce --
1.  Start Playing any track locally (Preferences set to default audio device)
2.  Click on the "Cast" button and select the destination/sink (Chromecast Audio Puck in this case)
3.  Enjoy hours of uninterrupted music ( I normally listen all day while working, but I really don't think the length of listening time has anything to do with the bug)
4.  Finish work for the day and click on the Pause Button
5.  Come back more than a few hours later and click the Play Button (Short spans seem fine [e.g. <30-minutes] but longer periods is where this issue creeps in that is why I think it has something to do with the Google Cast device's idle timeout...)
6.  Note the "greyed out" button and no music even after several minutes

-- Note to the Team --
I just wanted to thank all of your for your efforts on this software, I simply could not function without it and I have tried a lot of the competitor apps before finding yours.  The overall stability, ease of use, platform integration (media keys!) and features makes this  better, at least to me, than running Google Play natively inside of a Chrome browser window.

**Comment by MarshallOfSound** [comment]
Yeah, so, I'm sure this is a problem.

But there is no way I have the time required to reproduce this, let alone test and fix this.  This is going to be one of those bugs that will just have to exist unless someone finds a few days of there life to fix it 😆
