### ISSUE TITLE
Request: Change default podcast view to 'Your Podcasts'

### ISSUE THREAD

**Issue by notasmartman** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1494]
**OS:**
Windows 10

**Issue Descriptions:**
I'd really prefer (or have the option) to make 'Your Podcasts' the default option. I know what I want to hear and having to click past Joe Rogan's huge face every day on the Top Charts is annoying! ;)

**Steps to Reproduce:**
Feature request. Thanks!

**Comment by MarshallOfSound** [comment]
If you exit the program on "Your Podcasts".  It will launch again on "Your Podcasts".

It's clever like that 👍 There are two many pages to support setting one as default, so simply quitting on the one you use will open that one by default next time

**Comment by notasmartman** [comment]
Ah, I hadn't picked up on that. Thanks!

**Comment by BenjaminHCCarr** [comment]
Mine does not do that, if I close with a podcast open, it reopens that page, but if I close with "Your Podcasts" open, I get dumped to the "recent activity" page, which tends to not list podcasts. Is it possible to switch the placement of "Top Charts" and "Your Podcasts" so the "Podcasts" window defaults to Yours? Happy to debug and work with you on this, haven't looked at the codebase.
