### ISSUE TITLE
Going back from the "Upgrade to family plan" window

### ISSUE THREAD

**Issue by Extazium** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1495]
Hello, 
I clicked on "Upgrade To Family Plan" in the left menu because I was curious as to what it was (never seen it before). The only way to go back from this window is to hit the "Backspace" key.

**OS:**
Win 8.1
**Issue Descriptions:**
The left menu disappears once you display the "Upgrade to family plan" window. 
![image](https://cloud.githubusercontent.com/assets/2089620/17813268/fcd90a42-662a-11e6-984e-68a6ca497546.png)

![image](https://cloud.githubusercontent.com/assets/2089620/17813152/73b30ab0-662a-11e6-932c-3a931bfc8e8f.png)
The only way to go back is to hit the "backspace" key.

(Also, the styling of this page is weird. The Google logo goes black, and there's a purple bar on the bottom side, don't know if we need another issue for this)
**Steps to Reproduce:**
1. Click on the menu on the top left side of the window
2. Click on "Upgrade to family plan"
3. Menu disappears suddenly. Esc key does nothing. Only backspace works to land you back where you were.

**Comment by MarshallOfSound** [comment]
You can use "backspace" or "Alt + Left" or "Control + Left"

Or you can wait a few hours for the fix for this and the new google playlist bar to be released
