### ISSUE TITLE
Playlist titles are unreadable when mousing over in the Dark theme

### ISSUE THREAD

**Issue by steven-nichols** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1497]
**OS:** 
Windows 10

**Issue Descriptions:**
When using the Dark theme, the playlist labels are unreadable when hovering over them.

![playlist-hover-color](https://cloud.githubusercontent.com/assets/394972/17816841/42930ffa-6609-11e6-8f2e-3811dd67c8aa.gif)

**Steps to Reproduce:**
Running latest (v3.4.3). Under Desktop Settings -> General, enable Custom Theme and select Dark. Then open the playlist drawer and hover over any playlist in the list.

![dark-settings](https://cloud.githubusercontent.com/assets/394972/17816989/ffdac9a4-6609-11e6-8ae9-cafe2fc78da3.JPG)

**Comment by MarshallOfSound** [comment]
An update will be coming out shortly to fix this issue.  It has already been fixed in master.
