### ISSUE TITLE
Blank black screen when starting the app

### ISSUE THREAD

**Issue by pbeaumier** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1498]
Running in Windows 10, I just get a black screen with a orange frame and nothing happens

**Comment by compil3** [comment]
Run it as Admin, worked for me.

**Comment by hailwood** [comment]
Hasn't fixed it for me.

**Comment by MarshallOfSound** [comment]
This sounds like an AntiVirus, Firewall or Graphics Driver problem and unfortunately there is nothing I can do to fix it on my side.  You have to track down whatever is blocking the app and disable it.

I have had reports that using Avast Firewall has done this before

**Comment by hailwood** [comment]
@MarshallOfSound it's none of those things as a full reinstall just fixed it, so perhaps there's something getting corrupt in the upgrade?
