### ISSUE TITLE
Desktop Notification cut off

### ISSUE THREAD

**Issue by MTRougeau** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#15]
Looks like the notifications are cut off. Perhaps it is because my taskbar is on the right? Also, for long song info, the text is very small, nearly unreadable.

**Comment by MarshallOfSound** [comment]
Well that's awkward :smile_cat: 

I can replicate the issue on my computer, you are correct that it is due to the position of the taskbar.  I'll work on a fix and it will go out with the next release.

**Comment by MarshallOfSound** [comment]
@MTRougeau  The positioning issue has been fixed, the unreadable text is a more complex issue.  Can you provide an example of a song that becomes unreadable.  The notification is only so big, I'm not sure how I would fix that

**Comment by MTRougeau** [comment]
Yeah, I looked through the code.....I mean, if you're dealing with a fixed size for the notification window, it's going to be difficult. I believe Chrome's notifications scale, don't they? More text, slightly bigger window. Don't know if you want to look into something like that or not.

**Comment by MTRougeau** [comment]
Here is an example of the same track with both notifications. It actually looks like chrome DOESN'T scale the window....it just uses more the the space instead of squishing the text down.

![web player](https://cloud.githubusercontent.com/assets/15477491/10862321/6cc408ee-7f71-11e5-857a-c9ab43fb02e8.PNG)
![desktop player](https://cloud.githubusercontent.com/assets/15477491/10862322/6cc7b412-7f71-11e5-8514-aff07a2db43f.PNG)

**Comment by MarshallOfSound** [comment]
I did some quick modifications to allow the song album/artist to take up two lines instead of one.  Appears to more closely resemble the chrome notification now

![mod](https://cloud.githubusercontent.com/assets/6634592/10862370/318df05e-7ff9-11e5-8b91-ad4fb38d620b.PNG)

**Comment by MTRougeau** [comment]
Awesome! Thanks
