### ISSUE TITLE
Music stuttering

### ISSUE THREAD

**Issue by adinklotz** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#150]
What the title says.  In the latest version (as of about a week ago), audio has been stuttering and skipping a lot as it's playing. 
It doesn't seem to be a problem with my internet or anything, since the browser player still works fine; the audio's only weird in the desktop player.

I am on Windows 10 x64

**Comment by MarshallOfSound** [comment]
Does this happen all the time or randomly?

**Comment by adinklotz** [comment]
It will play fine for ~30 seconds, then skip and stutter for a few seconds, then play fine for ~30 seconds, etc.

**Comment by MarshallOfSound** [comment]
Sounds like a bug with flash on your specific hardware, can you post your specs and I'll see what I can piece together

**Comment by PandawanFr** [comment]
Same for me, I haven't tried updating flash yet, don't know if there's an update.

Will get back to you.

I am on Win 10 x64

**Comment by MarshallOfSound** [comment]
You can't update flash, on the latest version it is embeded (PPAPI)

**Comment by PandawanFr** [comment]
Yeah, just found out it's browser based... So seems like it's a problem only you can fix

**Comment by eladavron** [comment]
Having same issue, but less frequent than stated above.
Windows 10 x64 as well.
Yikes I hate Flash.

**Comment by Jespiee** [comment]
I'm having the same problem. On my laptop when I skip to a part that hasn't buffered yet it stutters for 30 seconds and then plays fine again. In my browser it plays fine.
It isnt the problem of my laptop because I'm playing from a SSD and my specs are: i7-4710HQ; 16GB memory; enough free space on both disks.

**Comment by MarshallOfSound** [comment]
Can you guys @Jespiee @eladavron @PandawanFr check that this doesn't happen in chrome.  And then post the flash version in chrome.  To find that out go to `chrome://plugins/` and look for the "Adobe Flash Player" version string.  Should look something like `Version: 20.0.0.286`

**Comment by Jespiee** [comment]
Adobe Flash Player - Version: 20.0.0.286
Shockwave Flash 20.0 r0

**Comment by eladavron** [comment]
Indeed does not happen in Chrome.
It's worth mentioning though that my issue seems to be far less severe than other people are having it. It only stutters in the beginning of playback, and after about a minute or so settles down and everything works flawlessly thereon out.

Adobe Flash Player - Version: 20.0.0.286
Shockwave Flash 20.0 r0

**Comment by PandawanFr** [comment]
Nope, have tried on Chrome and Edge, it works fine...
Also, it seems that when I load the song on chrome and then move on to the desktop one, the stuttering stops, maybe because the song is stored in the cache or some sort of memory? 

Adobe Flash Player - Version: 20.0.0.286
Shockwave Flash 20.0 r0

**Comment by MarshallOfSound** [comment]
Closing as it is an upstream bug related to Adobe flash player, I will update our PPAPI flash ASAP though

**Comment by kennethmac2000** [comment]
Hi @MarshallOfSound,

I'm now experiencing this issue on macOS (10.12.3). Playback in the Spotify client is flawless, but playback in GPMDP has intermittent but very obvious periods of micro-stuttering.

Should I reopen this bug or create a new one?

**Comment by AndrewStobie** [comment]
@MarshallOfSound  I am also now experiencing this issue. It is driving me crazy that it is seemless in spotify but so choppy on this player. Any thoughts?

**Comment by kennethmac2000** [comment]
I also don't understand why it's not choppy in the Chrome browser, only in GPMDP.
