### ISSUE TITLE
Buttons not active on Mac

### ISSUE THREAD

**Issue by sharadkap** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1500]
**OS:** Mac OSX El Capitan

**Issue Descriptions:** Buttons not active

**Steps to Reproduce:** Open player and none of the buttons seem to be working for playing the songs.

**Comment by MarshallOfSound** [comment]
The latest updates `3.4.3` and `3.5.0` contain fixes for this issue

**Comment by sharadkap** [comment]
Thanks @MarshalOfSound. Its working now.
