### ISSUE TITLE
After resuming from sleep queue, playing song and it's position are reset

### ISSUE THREAD

**Issue by vanushah** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1501]
Also, I've noticed the default loading screen of the Google Play Music (as in browser tab), immediately after logging in. Is a bug or a feature? And can you fix this?

**Comment by kevinmirsky** [comment]
I'm finding when I resume from sleep mode, the whole window is blank. I have to restart the whole program to get it to work again.

**Comment by vanushah** [comment]
It seems that a reloading of the page is initiated. And not by GPMDP.

**Comment by trakhov** [comment]
Also. I enter a sleep mode with a miniplayer. After logging in player's contents seem to be being from the default player, not the mini one.

**Comment by MarshallOfSound** [comment]
I've noticed this on my mac whenever I resume from sleep.  I'll look into it when I get the chance

**Comment by ryanstrat** [comment]
I have noticed the same thing on Linux (Ubuntu 16.04 x64)

**Comment by AdmiralAsshat** [comment]
I can confirm the same problem within Linux (Fedora 24, 64-bit, Cinnamon DE).

On mine, waking from sleep causes the whole window to appear blank and largely unresponsive. Can't resume, skip, or do anything, really. It requires that I restart the app.

**Comment by zorinlynx** [comment]
Confirming this issue on Mac OS 10.11.6.

Basically, the state of the player is all out of whack when you resume from sleep. If there's a way to detect waking up from sleep, I suggest doing so, and initiating a reload.
