### ISSUE TITLE
Disable autoupdate

### ISSUE THREAD

**Issue by Zipfer** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1506]
**OS:**
Windows
**Issue Descriptions:**
No possibility to disable update
**Steps to Reproduce:**
download 4.3 version. wait 2 min it will force updated

**Comment by jostrander** [comment]
Unfortunately updates include fixes that are reactive to changes in the VPN service and more often than not, not updating will leave the ayer in a broken state. This has been asked before and @marshallofsound had a more thorough explanation but basically wontfix.

**Comment by Zipfer** [comment]
What about warning before update?
Bad thing it spend traffic when you using cellular data for example.
Update it's good but automatic download is bad

**Comment by MarshallOfSound** [comment]
> Bad thing it spend traffic when you using cellular data for example.

There is no way for us to prevent the download on the Electron side of things

**Comment by Zipfer** [comment]
In osx player not update automatically and works well.
New version for example shows white screen when OS returns from sleep in older version it's not happen.

**Comment by MarshallOfSound** [comment]
> In osx player not update automatically and works well.

Yes it does, the player updates automatically on macOS and Windows

**Comment by Zipfer** [comment]
<img width="1280" alt="screen shot 2016-08-21 at 14 22 56" src="https://cloud.githubusercontent.com/assets/1160859/17836892/52058840-67b3-11e6-860c-f24cd8d113ec.png">
Maybe I'm wrong but version is 3.4.3

**Comment by MarshallOfSound** [comment]
Your update is either pending, failed or you have some kind of firewall blocking the update request.

**Comment by Zipfer** [comment]
No, each time it asking me for update and I decline it. And after restarting player it's doesn't update automatically.
That's why I asked do the same thing for windows.

**Comment by MarshallOfSound** [comment]
@Zipfer 

a) Declining the update is a **really** bad plan, the updates contain security fixes inside Chromium that could cause you serious security issues.
b) Declining updates means eventually updates might not even work (It's feasible a GPM bug could prevent the update popup if you don't update to fix it)
c) The decision to not auto update on macOS is a decision made by Squirrel.Mac not us

**Comment by Zipfer** [comment]
New version broke after sleep mode. 
Previous version works fine.
Updates good - fully agree. But until it broke something
Force update always bad, look on windows 10. All people from internet trying to disable it.
My proposal was - autoupdate automatically by default but let for user change it from settings.
I liked this app I just wanted little improve it
