### ISSUE TITLE
Player UI freezes after ~5 seconds of playback

### ISSUE THREAD

**Issue by reaczz** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1507]
**OS:**
Windows 10

**Issue Descriptions:**
When I start a song the UI is responsive and okay for 5 seconds then it freezes. The song keeps playing, and the UI is fine again for the first 5 seconds on the next song that plays,

**Steps to Reproduce:**
This happens every single time I play a new track.

**Comment by MarshallOfSound** [comment]
Google is having quite a few upgrade bugs at the moment.  I'm closing out all UI bugs until at least a few days have passed from their latest update.

**Comment by ViRGiL175** [comment]
Hi. Thanks for pretty nice app.

I also faced it. Tray program control menu also freezes sometimes. 
And sometimes the interface freezes when changing the window focus.

I'm on Windows 10, Acer Laptop with Intel and Nvidia 860M.

**Comment by MarshallOfSound** [comment]
@ViRGiL175 Disable desktop notifications 👍

**Comment by ViRGiL175** [comment]
It works... But why :)

Thank you anyway.
