### ISSUE TITLE
Cannot assign hot keys to specific buttons

### ISSUE THREAD

**Issue by trakhov** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1509]
**OS:** Windows 10, Ubuntu 16.04

**Issue Descriptions:** Can't assign hot keys to "back" and "forward" buttons on Microsoft Ergonomic 4000 keyboard (key codes are 166 and 167).

**Steps to Reproduce:** Open desktop settings/hot keys. Try to assign any hot key to "back" or "forward" buttons. 

Thanks.

**Comment by MarshallOfSound** [comment]
These are claimed at an OS level by our application to trigger forward and back navigation inside the app.  We don't allow you to reassign them
