### ISSUE TITLE
lastfm login not working on beta version

### ISSUE THREAD

**Issue by seeb0h** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#151]
Right credentials => login failed.

With this version : https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/31#issuecomment-170509781

Worked with 2.0.2

Win7 x64

**Comment by MarshallOfSound** [comment]
That is to be expected on a beta appveyor version.  No last.FM API key
