### ISSUE TITLE
Music pauses automatically on window close

### ISSUE THREAD

**Issue by FezVrasta** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1511]
**OS:** macOS El Capitan 10.11.6 (15G31)

**Issue Descriptions:**
When the window is closed, the music pauses automatically. I wouldn't expect the music to pause when I close the window. I have to press the "play" key on my keyboard to resume the music execution.

**Steps to Reproduce:**
1. Open GPMDP
2. play a song
3. click the close button (the red one)

**Comment by MarshallOfSound** [comment]
What is your "minimize to tray setting"?

**Comment by FezVrasta** [comment]
Disabled/unchecked

**Comment by MarshallOfSound** [comment]
That's your problem then.  This is expected behavior.

If you aren't minimizing to tray we assume you actually want to close the window (so it is closed).  On macOS though this means it is just hidden until we receive an `activate` event.

For the behavior you want you need to enable Minimize to Tray

**Comment by FezVrasta** [comment]
Actually I would love to completely disable the traybar.

Traybar minification is not a common behavior on macOS.

On iTunes or any other Mac app, closing the window doesn't quit/stop the app, it just closes the window.

This is the expected behavior on macOS

**Comment by MarshallOfSound** [comment]
@FezVrasta The thing with Electron though is that we can't keep the app running if there isn't a window open.  And minimization to tray is definitely a thing.

Docker, SonicWall, Skype and a bunch of other apps I use every day minimize themselves to the tray and keep running

**Comment by FezVrasta** [comment]
Sorry but if I close the Skype window the call is not paused... Same for iTunes. What do you mean?

**Comment by MarshallOfSound** [comment]
@FezVrasta Yes, our default is the same as Skype and Itune.

You have chosen to turn off "minimize to tray".  If you turn it back on again (like it was by default).  You will get the experience similar to Skype and Itunes.

**Comment by FezVrasta** [comment]
Ok I see, maybe it's just the option name that is confusing... Actually the app always sits on both the Dock and the Traybar, with that option I thought I could disable the traybar icon.

Maybe rename it to "Pause when window is closed" and invert the value?

**Comment by MarshallOfSound** [comment]
The "Pause when window is closed" thing only happens on macOS and is the only way we can "close" the window without actually quitting the application.

On all other platforms the option makes sense.

I'm also slightly confused how "Minimize to tray" can be confused for "Don't show tray icon" 😕 😆

**Comment by FezVrasta** [comment]
If I read "Minimize to tray" option, I think that disabling it, the app will not go in the traybar. I think it's what most people would expect. Especially on macOS where lot of legacy apps have such option. 

![image](https://cloud.githubusercontent.com/assets/5382443/17847540/c613ba04-684e-11e6-84c1-7d25a4f1ce5a.png) (copied)

![image](https://cloud.githubusercontent.com/assets/5382443/17847545/d25663d4-684e-11e6-9f75-213e5e0063f8.png) (Adobe CC)

![image](https://cloud.githubusercontent.com/assets/5382443/17847565/ebb9d68a-684e-11e6-8215-55b37a177aa1.png) (HandsOff!)

And so on...

So, I would have expected that option to have the same effect of those.

**Comment by FezVrasta** [comment]
More generically, seems like this app needs some love to integrate better with macOS.
