### ISSUE TITLE
Gpmdp remote app Shuffle

### ISSUE THREAD

**Issue by bryan1545** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1515]
**OS:**
Windows 10 1511 and android lollipop
**Issue Descriptions:**
when using the remote control app the shuffle button will stay as if scuffle is not active even though shuffle is active on the desktop (also this makes it impossible to remove shuffle from app as it just reshuffles the playlist instead of unshuffleing
**Steps to Reproduce:**
choose a playlist hit shuffle on app it will stay white instead of changing blue like the repeat button

**Comment by MarshallOfSound** [comment]
Please report remote app bugs to the correct repository

https://github.com/GPMDP/google-play-music-desktop-remote

Also this bug has been reported upstream https://github.com/gmusic-utils/gmusic.js/issues/6
