### ISSUE TITLE
Json api liked/disliked randomly not working

### ISSUE THREAD

**Issue by jakibaki** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1517]
OS:  Fedora

Issue Descriptions:
The json api randomly (or at least somewhat randomly) claims the current playing song has not been liked/disliked (![screenshot](https://cloud.githubusercontent.com/assets/5159436/17895312/039dab56-694d-11e6-9131-8a9270ba2725.png));  
when I unlike and then like the song again the api properly returns true as the value.

Steps to reproduce:
Not sure; I was playing a private playlist when I took the screenshot.

**Comment by MarshallOfSound** [comment]
> randomly not working

This isn't very helpful, without specific steps to reproduce I'm not going to spend time attempting to track this issue down

**Comment by jakibaki** [comment]
Ok, sorry for the unhelpful bug-report ,I think I found a way to reproduce it:

Close google play music desktop client

Open it again

Open a terminal with a simple "cat ~/.config/Google\ Play\ Music\ Desktop\ Player/json_store/playback.json" loop

Click on play randomly on a playlist where you liked all (or many) songs

(you will see that the "liked" value is correct the first time)

Now press the next button until the "liked" value is false while the song is actually liked (1 to 5 times in my experience)
