### ISSUE TITLE
After been disconnect from the network and reconnected the player view turn to white.

### ISSUE THREAD

**Issue by lcsvcn** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1519]
I have attached a print screen that show how my player screen turn after been disconnected and reconnected from the network. Note that the moment that I print screen I was reconnected and the app didn't come back to normal.

![capture](https://cloud.githubusercontent.com/assets/6011385/17913698/58bc3308-6972-11e6-8350-f3ae20e880a0.PNG)

**OS:**

**Issue Descriptions:**

**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment]
Fixed in latest Electron build
