### ISSUE TITLE
Main window resizing problems (beta version)

### ISSUE THREAD

**Issue by seeb0h** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#152]
Two bugs :
1. Arrow cursor appears on every edges and borders but there are useless. Upper left/right and top one move the window. Other ones do nothing.
2. Using win → or win ← does nothing. win ↑ and win ↓ works

With this beta version : https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/31#issuecomment-170509781

Win7 x64

**Comment by MarshallOfSound** [comment]
Fixed in master
