### ISSUE TITLE
Unresponsive after resuming computer from sleep.

### ISSUE THREAD

**Issue by thisisterk** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1520]
**OS:**
Windows 10 Pro N

**Issue:**
Mostly* unresponsive after computer resuming from sleep. Started happening within the last few releases.

*doesn't happen everytime. Main window is just blank/black. Task manager doesn't say it's unresponsive. The menu items in the tray mostly work. Hotkeys won't restart music. Can open settings from tray.

**Steps to Reproduce:**
1. put computer to sleep.
2. resume some time later. (shortest I let it sleep is ~4hrs usually)

**Comment by boulund** [comment]
I've had this issue for some time now and decided I would report it here today, but @thisisterk already did! :) 
I'm on Windows 10 Enterprise Insider Preview build 14905.10000. I have exactly the same symptoms.

**Comment by MarshallOfSound** [comment]
Fixed in latest Electron build
