### ISSUE TITLE
Can't log in into Last.fm

### ISSUE THREAD

**Issue by zimenskiy** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1521]
**OS:**
Windows 10
v3.5.0 from https://www.googleplaymusicdesktopplayer.com/
**Issue Descriptions:**
Click on the "Let me in" button causes only message "You appear to have left the authorization process..."
![](http://image.prntscr.com/image/c6fbbd9e984c4dca8e9e3ffcf8b17df2.png)
**Steps to Reproduce:**
- Open Desktop settings
- Choose Last.fm tab
- Click "Log in to Last.fm"
- In the opened window enter any credentials or don't even enter anything and then press "Let me in" button.

**Comment by MarshallOfSound** [comment]
I have tested this just now and it appears to be **yet another** bug in last.fm itself.  They are losing the API key transaction during the login process.  Nothing I can do about this one
