### ISSUE TITLE
Will not play through Logitech G933 Headphones 

### ISSUE THREAD

**Issue by MrsBlinkie** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1524]
**OS:**
Windows 10

**Issue Descriptions:**
I just purchased a set of Logitech G933 headset, I have them hooked up everything's working fine. When I open Google play Music Desktop Player and play the sound persist to come through my speakers even though my sound is set to come through my headphones and it's working on spotify web player and the computer in general.

If I watch a video of a song in the player it will come through my headphones but as soon as I switch back the the play list it goes back to the speakers.

**Steps to Reproduce:**
Play the playlist, switch to video from youtube, switch back to playlist

**Comment by MrsBlinkie** [comment]
After switching to Run as administrator I found some extra options and have it working now

**Comment by mountswolmore** [comment]
If anyone else ends up here wondering wtf he found, I had this exact same issue and under DESKTOP SETTINGS and the PLAYBACK tab, there's a setting for EXPERIMENTAL SUPPORT FOR MULTIPLE AUDIO CHANNELS.

After disabling that and rebooting I had music in my headphones again.
