### ISSUE TITLE
Feature Request: prevent Windows going into Sleep mode when songs playing

### ISSUE THREAD

**Issue by tetronomis** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1526]
Hi. 
I'm using a Surface Book and my biggest problem is that the OS goes into sleep mode and stops the music playing. Seems like Windows doesn't care if Chrome has a tab playing music and shuts off. On the Mac Book I didn't have that problem.
Now if I play a youtube video full screen or have VLC playing a movie it'll prevent the sleep mode, so there's may be a way. 
Do you think you could try to have a setting in the desktop player to prevent the computer to go into sleep mode when a song is playing?
I searched in MSDN and [maybe that could help](https://msdn.microsoft.com/en-us/library/aa373208%28VS.85%29.aspx?f=255&MSPPError=-2147217396)?

Thanks

**Comment by MarshallOfSound** [comment]
I think I've discussed this elsewhere before, and stopping a PC going to sleep because media is playing is quite simply bad practice and in fact somewhere in their docs Microsoft specifically say don't do it.

If you want to do it you should disable your computers sleep timer yourself.

**Comment by tetronomis** [comment]
Disabling sleep completely is not a solution. The solution is to go back to back to Chrome and the [Sleepless extension](https://chrome.google.com/webstore/detail/sleepless-in-system/cnenegfehjcmoginiijjgmchcfllmmbp?hl=en) which is what I'll be doing.
But given that not only Apple does it but even Windows does it too for videos, and that I requested it as an optional setting and not a default behaviour, the "bad practice" argument is surprising.
If you think it's a useless feature fine, just I'm not the only one, [Spotify users ask the same thing](https://community.spotify.com/t5/Live-Ideas/Desktop-Prevent-Windows-from-sleeping-when-Spotify-Premium-is/idi-p/1183087)
