### ISSUE TITLE
Sidebar menu not a toggle

### ISSUE THREAD

**Issue by smvoss** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1527]
ENHANCEMENT 

**OS:** Windows

**Issue Descriptions:** The sidebar is not a toggle anymore, or stop acting as one. This should be a togglable setting if this is intended, as it is the wrong workflow for a computer. This becomes increasingly frustrating after switching around more than a few times.

**Steps to Reproduce:** Click the menu button

**Comment by MarshallOfSound** [comment]
I'm not sure I understand what you mean.

Can you be more specific about the UI component that has changed or doesn't work as intended.  Possibly providing screenshots.

**Comment by smvoss** [comment]
I am currently on my work computer which isn't being effected by this, but basically, this used to be a toggle:

open:
![image](https://cloud.githubusercontent.com/assets/1350045/17971880/423390b4-6aa2-11e6-9c23-64203517e2b4.png)
closed:
![image](https://cloud.githubusercontent.com/assets/1350045/17971921/67052966-6aa2-11e6-8d3d-ca0b368114fe.png)

After installing the newest version on my home PC, this is no longer a toggle. When pressing the menu button 
![image](https://cloud.githubusercontent.com/assets/1350045/17971949/86e32e40-6aa2-11e6-8735-b9ea0c6b8ca6.png) it opens for as long as you click within the menu, but once you click outside of it, it closes itself again. 

Hopefully this helps!

**Comment by MarshallOfSound** [comment]
@smvoss This was a change made by Google in their UI design not by us.  We can't and won't change / fix this
