### ISSUE TITLE
Menu appears when rearranging the order of songs

### ISSUE THREAD

**Issue by JoshuaGarrison27** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1531]
OS: Windows 7 : 64 Bit

Issue Descriptions: When attempting to re-order songs in the queue, you can see the menu slide out to the right of the queue. I even reinstalled the application just to see if it was only me.

Steps to Reproduce:
1. Add songs to the queue
2. Go to reorder the list
3. See the menu to the right of the queue window

**Comment by MarshallOfSound** [comment]
This is a new UI feature of Google Play Music.  If you drag the song over to that menu it will slide out fully and allow you to drop songs onto a playlist.

It's a cool new feature that Google added to GPM

**Comment by JoshuaGarrison27** [comment]
Oh neat. Didnt know that.
