### ISSUE TITLE
Unreadable font in "New Playlist" window (dark theme)

### ISSUE THREAD

**Issue by stevenrau** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1532]
**OS**: Linux (Ubuntu 16.04)

**Issue Descriptions**: When using the dark theme, the font in the "New Playlist" window's text fields is (basically) unreadable. The font is a dark grey colour just a few shades lighter than the background. The issue does not exist for the light theme.

I've attached a screenshot to show what I'm seeing.

![newplaylist](https://cloud.githubusercontent.com/assets/6550193/17978530/d354a2d4-6ab3-11e6-82a2-18d54be69908.png)

**Steps to Reproduce**:
(1) Turn on dark theme
(2) Click the "Create a playlist" plus icon in the playlist menu.
(3) Type some text into the Name and/or Description boxes.

**Comment by MarshallOfSound** [comment]
This is fixed in the latest versions, please update.
