### ISSUE TITLE
App crashes immediately upon signing in

### ISSUE THREAD

**Issue by sgreig** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1533]
I'm running Windows 10 and I just downloaded the app from your website about 10 minutes ago. When I launch the app it asks me to sign in, then to provide my security code (I have 2-step authentication enabled) and then when I enter that and submit, the spinning circle appears for a couple of seconds and the whole app crashes. I've tried 3 times now. Here is the output of the log file as mentioned in a previous closed thread where someone was having a similar issue:

{"level":"info","message":"Application started.","timestamp":"2016-08-25T20:45:19.151Z"}
{"level":"error","message":"Failed to load bonjour with error: {}","timestamp":"2016-08-25T20:45:24.201Z"}
{"level":"info","message":"Application started.","timestamp":"2016-08-25T20:50:55.034Z"}
{"level":"error","message":"Failed to load bonjour with error: {}","timestamp":"2016-08-25T20:50:55.550Z"}
{"level":"info","message":"Application started.","timestamp":"2016-08-25T20:55:43.187Z"}
{"level":"error","message":"Failed to load bonjour with error: {}","timestamp":"2016-08-25T20:55:46.188Z"}

**Comment by MarshallOfSound** [comment]
This log file doesn't contain any actual errors 😢 

The bonjour thing is pretty standard.

It sounds like you are experiencing electron/electron/issues/6836

Please monitor that issue for an upstream fix
