### ISSUE TITLE
Weird request

### ISSUE THREAD

**Issue by FedoraTipper** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1534]
I know this is kinda way off topic. I am trying to create a electron app for plex to register hotkeys for playback. I'm currently getting a really mixed experience trying to do so. I have no clue what's going on, as I have only used js for web development. 

From what I have picked up, I pulled Emitter which injects js commands and mediakeysDBus which handles the hotkeys. I'm at an issue of not knowing how to import these libraries. (This I can sort out by myself hopefully) All I want to know is, are there any resources to help me out?

**Comment by jostrander** [comment]
Feel free to join us on gitter, but please keep the issues section for issues related to this project.
