### ISSUE TITLE
blacked out when launching

### ISSUE THREAD

**Issue by rsapp23** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1537]
I just loaded this player yesterday and all seemed well. I went to launch it and it's giving me the boarder but no content. Its just blacked out. I tried to uninstall/reinstall, but the issue is still going on. Any ideas? 
![blacked out](https://cloud.githubusercontent.com/assets/21263515/18008869/166e3342-6b67-11e6-9ad2-a7ae292b1ee3.JPG)

**Comment by MarshallOfSound** [comment]
Delete your `%APPDATA%\Google Play Music Desktop Player` folder and reinstall.

This is a Chromium bug that is being fixed upstream
