### ISSUE TITLE
Error message: Google Play Music is currently available in select territories.

### ISSUE THREAD

**Issue by jeetkundostyle** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1539]
**OS:** Win 10

**Issue Descriptions:** When opening the app, but all I get is a blank page with the message: "Google Play Music is currently available in select territories." I also see that I'm properly logged on at top-right. It worked fine for a few days, but now, nothing. I'm not on a VPN, and I live in the USA.

**Steps to Reproduce:** Open the app.

**Comment by berryelectronics** [comment]
Did you tried to use GPM in your web browser?

**Comment by MarshallOfSound** [comment]
Whatever this is it will be an issue on Google's side not on ours.

You can try wiping the cache and starting again by deleting the `%APPDATA%/Google Play Music Desktop Player` folder

**Comment by jeetkundostyle** [comment]
It works fine in the browser. I'll try wiping the cache. thanks.

**Comment by jeetkundostyle** [comment]
Wiping the cache did nothing. Looks like I sent you my $10 prematurely. Live and learn. And thanks for closing the thread on me. Very helpful.
![2016-08-26_16-33-05](https://cloud.githubusercontent.com/assets/21266007/18019590/d5869204-6baa-11e6-98f1-707a799ab6ca.jpg)
