### ISSUE TITLE
feature request: a visualisation

### ISSUE THREAD

**Issue by superjase** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#154]
i would love a visualisation(s) for in the app. i don't use chromecast and i can find no way to show a visualisation on my pc while playing music. it would be grand for when the player is filling the screen.

thanks :)

**Comment by MarshallOfSound** [comment]
This issue is not possible with adobe flash.  I'll keep this in mind with Nucleus Player
