### ISSUE TITLE
App "blanks out" after computer wakes up from sleep

### ISSUE THREAD

**Issue by hollowimage** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1540]
**OS:** 
Win7 Pro

**Issue Descriptions:** 
After the computer wakes up from sleep, (usually prolonged, overnight) the app that is left running at the time of entering stand-by mode comes back as "blank". all i see is the grey background. Closing/reopening window does not help, I have to kill the process and restart. Will procure screenshots at next event.

**Steps to Reproduce:**
put machine into standby for 8 hours, and then resume.

**Comment by MarshallOfSound** [comment]
Duplicate #1520
