### ISSUE TITLE
GPMDP Remote doesn't work, because Windows Firewall can't add the app to the firewall rules.

### ISSUE THREAD

**Issue by derray** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1542]
Hi,
I've a problem with the new released GPMDP Remote.
It can't connect to the Google Play Music Desktop Player.

I'm using Windows 10 Pro x64.

It looks like the problem isn't the remote itself, i can't add the player to the Windows Firewall.
When i try to add it to the allowed apps i get the error message: "The application can not be added to the list of exceptions,"
When i try to add a new incoming, outcoming rule I get the error message: "The application name could not be resolved." 
I'm german, maybe my translation is wrong, sorry for that.

Now the solution for me
1. Disable the firewall
or
2. Rename the .exe file

It looks like the Windows Firewall can't add the characters "%20" from the url encoding.
When i rename the .exe file located in "USERNAME\AppData\Local\GPMDP_3\app-3.5.0\",
from "Google%20Play%20Music%20Desktop%20Player.exe"
to "Google Play Music Desktop Player.exe"
I can add it to the firewall without a problem, it even asks me to add it,

I hope it's not a problem of my computer and there will be a fix for it.

Thanks for this awesome project!
Greetings from germany,
Ray

**Comment by MarshallOfSound** [comment]
@derray In an upcoming update we will remove the `%20` from the exe name.

Until then you can do what we do internally and simply set the firewall rule for **alll** applications not just a specified executable.

**Comment by derray** [comment]
@MarshallOfSound nice to hear, thank you! 
Rename the exe file removes the problem too. That's a lil bit better for security
