### ISSUE TITLE
Error Message: Google Play Music is currently available in select territories

### ISSUE THREAD

**Issue by jeetkundostyle** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1543]
**OS:** Windows 10

**Issue Descriptions:** Wiping the cache did nothing. Looks like I sent you my $10 prematurely. Live and learn. And thanks for closing that thread on me. Very helpful.

**Steps to Reproduce:** Open the app.
![2016-08-26_16-33-05](https://cloud.githubusercontent.com/assets/21266007/18019660/1f0d4bb6-6bab-11e6-9984-018a83f03c68.jpg)

**Comment by berryelectronics** [comment]
btw. you can still write even if the thread was closed. its just that there isnt much to do than to check proxy/vpn settings, restarting your router or reinstalling the app because its basically the webpage as a program. if these things wont help, its due to an error with GPM itself or with your device/ISP.

**Comment by jeetkundostyle** [comment]
Okay. Maybe it's a Google glitch. I'll wait it out. Thank you.

**Comment by MarshallOfSound** [comment]
@jeetkundostyle 

Basically there is no way that this can be something to do with our code.  I'm sorry if I didn't make that clear in the first issue.

Google display this message when they detect an incoming connecting from an IP address that **they think** is from an unsupported country.  If your ISP / Proxy / VPN is giving you one of those IP addresses there is nothing we can do.

You can try turning your router off and on again (this will assign you a new IP address) and turning off all VPN's and proxies.

But as mentioned before, there is nothing that this program can do to influence this in any way as it is at a why higher level than we have control over 👍
