### ISSUE TITLE
[Windows] Error on install

### ISSUE THREAD

**Issue by SpectralKH** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1544]
Now, I´m quite a noob when it comes to Windows. But I tried installing GPMDP, and I ended up with this error: http://pastebin.com/bfaJiauM

Windows also warns me about the app not having a trusted cerificate.

**Comment by TGSoftware** [comment]
GPDMP doesn't work for me either. I get a black screen and re-installing the same version does nothing :disappointed: 

> Windows also warns me about the app not having a trusted certificate.
This app isn't officially signed with a certificate authority (CA), but that's okay. The app doesn't modify your system internally. This message is normal across most unsigned apps.

**Comment by TGSoftware** [comment]
The GPDMP interface now works, no more black screen. This issue has been fixed.

**Comment by MarshallOfSound** [comment]
> This app isn't officially signed with a certificate authority (CA), but that's okay. The app doesn't modify your system internally. This message is normal across most unsigned apps, including Windows apps I've developed myself.

This is incorrect, all of our windows installers are signed with a code signing certificate.

That error appears to be a standard AV issue.  Just disable your antivirus when installing and try again 👍 

Let me know how that goes

**Comment by SpectralKH** [comment]
Okay, that was it. I didnt even know I had anti virus enabled, this darn bloatware.

**Comment by TGSoftware** [comment]
Same worked for me.
