### ISSUE TITLE
Minimize to tray in cinnamon

### ISSUE THREAD

**Issue by TurbaVladimir** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1545]
I have enabled "Minimize to Tray" feature, but it's kinda glitchy.
After starting, player not hiding to tray properly with close button, it just minimizes window to "window buttons".
![image](https://cloud.githubusercontent.com/assets/6495967/18027342/df7a0c18-6c69-11e6-84d5-08104f3e9b1b.png)
I found the way to solve that by restarting cinnamon with rmb click on the free space in panel->troubleshoot->restart, after that player minimizes to tray as it should.
![image](https://cloud.githubusercontent.com/assets/6495967/18027372/98bc9434-6c6a-11e6-88fc-9bed8c4f8131.png)
But after player restart it won't hide again until next cinnamon restart, which is very annoying. 
Also i used xfce before and in it player worked without any "dancing with drums".
Here is the system info, if it helps 
![image](https://cloud.githubusercontent.com/assets/6495967/18027455/4a8c2958-6c6c-11e6-8a5a-887eca57c61f.png)

**Comment by MarshallOfSound** [comment]
So this is an OS specific issue with Electron's tray icon implementation.

I would ask you to report it upstream to Electron but it will just be merged into something like electron/electron/issues/259

There is very little I can do to fix this, (in fact absolutely nothing).  The best I can suggest is reporting it upstream to cinnamon as it appears to be more of an issue with them than with Electron.
