### ISSUE TITLE
[Windows 10] 5.1 sound doesn't work. Possible solution inside.

### ISSUE THREAD

**Issue by RaporLoLpro** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1546]
**OS:**
Windows 10
**Issue Descriptions:**
I have installed your app today and find it amazing except one thing.
It doesn't provide 5.1 sound, since it works using web interface at some point, i guess it doesn't support 5.1, so stereo only. I did some workaround an found a key to resolve this issue.
In order to make 5.1 work with web interfaces(chrome example) you need to enable Speaker Virtualization or Dolby Surround 5.1 in your Audio Driver settings, however this is not enough.
For chrome adding "--try-supported-channel-layouts --force-wave-audio" at desktop icon properties has fixed an issue and made a sound work in 5.1, since chrome is obviously a web interface based. 
Could you please, take a look at it and fix it in the existing app, so people could get 5.1 sound? I'm a complete zero at coding, but i guess it's based on chrome api to achieve a web interface.
Thanks in advance. I really appreciate your work and love your app, but can't make it to work with 5.1.
If you have any other advices so i can fix it on my side, please, share. But i highly doubt you have, cause i have been looking around for a solution for a week or so.

**Comment by MarshallOfSound** [comment]
The CLI flags you have listed are known to break audio and cause crashes on several devices (including my own).

You can however enable this flags yourself manually just like you can with Chrome.  I will explain how to do so below.

1. Navigate to `%LOCALAPPDATA%\GPMDP_3\app-3.5.0`
2. Right click on `Google Play Music Desktop Player.exe` and click "Send to Desktop as Shortcut"
3. Find the shortcut on your desktop and "Right Click" -> "Properties"
4. The "target" attribute should be set to the path of "Google Play Music Desktop Player.exe"
5. Add the following to the end of the target ` --try-supported-channel-layouts --force-wave-audio`

This should be a very similar process to what you did to support it in Chrome.

**Comment by dreamcatcher95** [comment]
This either never worked or doesn't work anymore. I'm assuming it has something to do with the way that the actual `Google Play Music Desktop Player.exe` opens up the update program which then starts the exe?

**Comment by ViRGiL175** [comment]
Hi. This flags help me too on Acer laptop.

Maybe it makes sense to add to the configuration option to enable these flags?
With marked "at your own risk" and "for Dolby Digital".
Because sound without these flags is very bad and quiet. And so it becomes over the entire operating system. 
It is will be very helpful to people, I think.

Have a nice day.
