### ISSUE TITLE
Feature Request: An option for the location path where cache is stored.

### ISSUE THREAD

**Issue by nscerri** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1547]
Hi,

I have noticed that all the files used for playback are downloaded under C:\Users\\_**username**_\\AppData\Roaming\Google Play Music Desktop Player\Cache. This happens to be where my SSD is and would love to have the option to use another drive so to save the lifetime of my SSD.

Thank you in advance and keep up the good work.

Noel Scerri
nscerri

**OS:**
Windows 10

**Issue Descriptions:**

**Steps to Reproduce:**

**Comment by MaxRink** [comment]
> is and would love to have the option to use another drive so to save the lifetime of my SSD.

even if you have a crappy drive with 16nm planar TLC this doesn't matter in any significant way. lets assume the music you listen to would be 10GB / day and you write another 15gb with other applications. a average 500gb ssd with the worst NAND that you can get (16nm TLC) has roughly an endurancerating of 70TB, but realisticly lasts waay longer. So even if you consider worst-case scenarios you would look at a lifetime of over 7 years

**Comment by MarshallOfSound** [comment]
I've been thinking about this for a while (you may notice I haven't tagged it yet).  And I've come to a similar conclusion to @MaxRink 

Basically, although it is technically possible for us to choose a new folder to store the Chromium cache in.  I don't think it's a good idea as it can lead to side affects a user doesn't know about.

Also, the core reasoning in your request is to increase the life of an SSD which in terms of the Chromium cache is barely a reason at all 👍 .  The Chromium cache is very inactive, especially when just playing music and not loading multiple pages.

Closing this out as wontfix
