### ISSUE TITLE
Feature request: ability to like/dislike song from mini player.

### ISSUE THREAD

**Issue by danielandrews** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1549]
**OS:** 10.11.6

**Issue Descriptions:**

I'd love to see the ability to like/dislike tracks from the miniview:

![screenshot 2016-08-29 12 16 41](https://cloud.githubusercontent.com/assets/791336/18058468/78f16c8c-6de2-11e6-8bce-39356c56d6bc.png)

Space is kind of tight currently, so maybe the entire bottom bar could be made flush with the right and left margins to free up space?

**Comment by berryelectronics** [comment]
That mini player is actually the native one that you also can use through the browser.

But there is already a re-design from within the GPMDP in the works (if im not wrong)

**Comment by MarshallOfSound** [comment]
This slots into another issue which I can't find right now but basically

> there is already a re-design from within the GPMDP in the works (if im not wrong)

However it might be worth pointing out for historical sake that   
> That mini player is actually the native one that you also can use through the browser.

Is incorrect, the mini player we currently have is provided by a series of JS and CSS transform magics that I have implemented in https://github.com/GPMDP/gmusic-mini-player.js
