### ISSUE TITLE
Is there a back button? 

### ISSUE THREAD

**Issue by michaelsammler** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1550]
Sorry if I did not find it, but it is really hard to navigate with out a back or forward button. I have it on my mouse for chrome and explorer, but it does not work in here for some reason. 

(the shortcut settings saved me and my ancient keyboard. Thanks so much)

**Comment by MarshallOfSound** [comment]
Yes 👍 

There is a back button is is position on the right of the search box, it only appears though when you can actually go back.
