### ISSUE TITLE
Update notification in mini player could be improved

### ISSUE THREAD

**Issue by SimenB** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1551]
**OS:**
OSX

**Issue Descriptions:**
The update notification doesn't look look with the smal player. Maybe just have the heading and the buttons, with some text ("see more..." or something) expanding the full player and showing the current full text?

![image](https://cloud.githubusercontent.com/assets/1404810/18082113/a82ffc3c-6e9d-11e6-9c50-7fbc3dc79035.png)

**Steps to Reproduce:**
Have mini player open when an update notification arrives

**Comment by MarshallOfSound** [comment]
This was fixed in the latest release
