### ISSUE TITLE
Installed on new SP3 Machine(Win10) Getting blank screen (White/Black). 

### ISSUE THREAD

**Issue by Esparzva** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1553]
**OS:** Windows 10 (AU)

**Issue Descriptions:**
Installed on a new Surface Pro 3 (SP3) When launching the application for the 1st time I get a Blank Screen and I can't get the log in screen. Have tried restarting after installation, running as administrator mode, and uninstalling and reinstalling. Still get a blank screen on launch. 

**Steps to Reproduce:**
Simply Launch App

**Comment by MarshallOfSound** [comment]
As per other issues this is fixed in latest Electron and will be fixed in next release
