### ISSUE TITLE
Getting stuck on Configuring Google Play Music - Win 10

### ISSUE THREAD

**Issue by michiel3773** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1554]
Windows 10

When first setting up the desktop app, I tried "adding my music collection" and clicked "install" on the next step. However the app gets stuck in the "Configuring Google Play Music" with the spinning music icon and never leaves this state.

Translated from dutch so names of the features might not be 100% the same as they are in english.

**Comment by MarshallOfSound** [comment]
@michiel3773 You have to add your music collection from a web browser currently as GPM attempts to install a Chrome Extension (which we do not support).

Once you have added your library though you can come straight back to the application and it will work perfectly 👍 

See #706 for more information
