### ISSUE TITLE
[Enhancement] Android Wear support for companion apps.

### ISSUE THREAD

**Issue by Alexandroid99** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1556]
The title says it all. It would be a neat little feature. I'm currently testing Android Wear and I now noticed how much I am missing this feature. Remote controlling the playback from my wrist is a pleasure on Android, so why not for the desktop? :D

**Comment by MarshallOfSound** [comment]
Please raise remote issues on the correct repository

https://github.com/GPMDP/google-play-music-desktop-remote

But don't raise this one as it is already implemented and will be out next release
