### ISSUE TITLE
Chromecast icon only shows on Windows if player window is maximized

### ISSUE THREAD

**Issue by RomneyWhite** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1557]
**OS:**

**Issue Descriptions:**

**Steps to Reproduce:**

**Comment by jostrander** [comment]
Screenshots? Anything?

**Comment by RomneyWhite** [comment]
![capture 1](https://cloud.githubusercontent.com/assets/21370816/18151431/15e479cc-6fbd-11e6-9841-ea471b5b545e.PNG)
![capture 2](https://cloud.githubusercontent.com/assets/21370816/18151432/18ff835e-6fbd-11e6-9b04-c5f10a5bc46f.PNG)

**Comment by RomneyWhite** [comment]
Look in the lower right corner.

**Comment by MarshallOfSound** [comment]
Wut...

So you're saying that when the player is a normal size the chromecast icon isn't there.

You maximize it and it then appears?

And then you make it smaller again and it disappears?

Is that accurate?

**Comment by RomneyWhite** [comment]
Precisely.

**Comment by MaxRink** [comment]
i can confirm that behaviour
Here is a gif of it:
http://i.imgur.com/8hbpBzr.gifv
OS:
Win 10x64 Build 14915

**Comment by MarshallOfSound** [comment]
<img width="322" alt="screen shot 2016-09-02 at 8 57 11 am" src="https://cloud.githubusercontent.com/assets/6634592/18187231/4175177a-70eb-11e6-8024-1d6497ed0f39.png">

Looks like Google have done something stupid....  I'll override it for next release
