### ISSUE TITLE
Minimized player maximizes every time Internet reconnects

### ISSUE THREAD

**Issue by danafergan** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1559]
If Desktop Player is open and minimized, once an Internet connection is established, it maximizes and shows the "Loading Music Library..." splashscreen.

**OS:**
OS X 10.11.6
Google Music Desktop Player 3.5.0

**Issue Descriptions:**
Maximization is annoying, especially with a laptop that gets opened/closed or loses connection frequently. 

**Steps to Reproduce:**
It's most reliable when music is not playing. Open Music Desktop Player, but do not select a song or playlist. Minimize the player. Turn Wi-Fi off. Turn Wi-Fi on.

**Comment by MarshallOfSound** [comment]
Duplicate #1501
