### ISSUE TITLE
Feature: Playback Information API

### ISSUE THREAD

**Issue by rynti** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#156]
Currently there's no way for an external application of determining whether the player is playing a song or not. A possible solution would be to create a file that contains this information, and continuously update that file whenever playback changes. Furthermore we could also store additional information about the currently played song, etc. in the file.

Related pull request: #155 (Implements a new setting that users can use to instruct the player to store a JSON-formatted playback information file)

**Comment by MarshallOfSound** [comment]
PR is now at #157

**Comment by MarshallOfSound** [comment]
PR merged
Thanks @rynti

**Comment by MarshallOfSound** [comment]
@rynti You might be interested in the new PlaybackAPI in `3.0.0`.  Whatever scripts you wrote to use it might need to be updated for the new version.

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/dev/3.0.0/docs/PlaybackAPI.md

You get a whole lot more information with the new API though :+1:

**Comment by rynti** [comment]
Thanks for the heads-up! New API looks great, especially the WebSocket API :smiley:
