### ISSUE TITLE
Add option to freely set hotkeys

### ISSUE THREAD

**Issue by nmoorthy1** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1560]
Currently, I am only able to set hotkeys by including ctrl or alt (like ctrl + right arrow), but i'd like for it to be actually any key I want.

**Comment by MarshallOfSound** [comment]
This will not be implemented as it is (a) Probably Impossible and (b) Not a very good idea.

These hotkeys are **global**, that means you can use the hotkey from any program.  If you can set it to whatever you want, let's say "P" then anytime you type "P" the key would be absorbed (not be effective) and play pause the program...

When you think about it, this is definitely not what you want.

**Comment by nmoorthy1** [comment]
For the sake of argument, I completely understand what you're saying and it's basically up to the user to not set it to a key that is used often. However, in my case at least, in foobar, I set it to to the ` key because I literally never use that key. It makes it super easy to play/pause music. But I understand why you don't want to implement it.

**Comment by MarshallOfSound** [comment]
If all you want to do is set it to be "`" you can manually set it to that yourself by editing your settings file.

Just find the shortcut key value pair in your settings file and manually adjust it to be an accelerator in the Electron format.

https://github.com/electron/electron/blob/master/docs/api/accelerator.md

**Comment by nmoorthy1** [comment]
Gotcha, thanks!
