### ISSUE TITLE
Feature Request: Remember mini-player position when switching to full player and back

### ISSUE THREAD

**Issue by FrankEBailey** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1561]
**OS:**
Windows 10

**Issue Descriptions:**
When the mini-player is maximised to the full player and then back to mini player, the on-screen position of the mini player reverts to the centre of the screen. It would be useful for it to remember its position.

**Steps to Reproduce:**
Switch to mini player. Drag mini player to bottom left of screen. Switch back to full player. Switch to mini player. Observe that mini player is now centred on screen instead of resuming its previous position

**Comment by MarshallOfSound** [comment]
The min player position is reverted when the window is considered off screen.

If the origin (top left) of your window is out of the screen bounds (or close to being out, the math allows for some errors) then we will revert the position we saved so that you don't end up with an inaccessible window.

**Comment by FrankEBailey** [comment]
Awesome. I just noticed this. The left-hand bound of the mini player window must have been a pixel or two off the left edge. Sorry for opening a non-existent issue, and thanks a stack for all your hard work!
