### ISSUE TITLE
Feature request: Hide taskbar icon to system tray

### ISSUE THREAD

**Issue by holytimes** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1563]
Not even sure if possible, but could there be an option to remove the taskbar icon when the player is shrunk down? As in have the mini player with the controls open and on the desktop but with out having the taskbar icon and instead having it in the system tray. 

The taskbar gets extremely full very fast and while i love the mini player just even an option to hide it to the system tray would be a huge quality of life change.

**Comment by MarshallOfSound** [comment]
I believe that this is possible.  However it violates Microsoft's design guidelines.

You shouldn't have a window that exists without a TaskBar indicator.  This is one of the reasons Skype for Desktop now doesn't minimize to tray when the window stays open.  It now minimizes normally to your taskbar.

From a design standpoint this makes sense, as if I have nothing on my taskbar I wouldn't expect to see a window floating around the place.

As always up for discussion below, but for now from me.  It's a `wontfix`

**Comment by holytimes** [comment]
The application already has an icon that it is tied to in the system tray so while it is weird to have duplication of icons one in the sys-tray and one on the task bar i can see where Microsoft is coming from. Having the standard of if its on the desktop it has an icon on the bar makes sense, this prevents computer challenged people from having problems. 

On the other hand it is extremely frustrating to have this duplication and clutter. An option to consolidate the icons into one. Just haveing the program tie it self to the system tray icon it already has would be nice. But in the end i can not fault you for stick to the guidelines how ever much i think it causes needless clutter.

**Comment by MarshallOfSound** [comment]
> Too bad widget/gadgets where more or less nixed making the mini player a gadget would be literally a dream come true :(

Someone made a Rainmeter script for this a while back.  Quick google search should find it if a desktop widget is what you're after 👍

**Comment by holytimes** [comment]
At least there is an option floating around never touched rainmeter either so this will be "fun" to learn.
