### ISSUE TITLE
Remove the spaces from the process name

### ISSUE THREAD

**Issue by gwmzh** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1564]
**OS:** Windows

**Issue Descriptions:** Remove the spaces from the process name:
 "Google%20Play%20Music%20Desktop%20Player.exe" =>  "GooglePlayMusicDesktopPlayer.exe" ?
**Steps to Reproduce:**

![image](https://cloud.githubusercontent.com/assets/21304615/18168636/f5fd4522-7056-11e6-9dc3-032948c05a96.png)

**Comment by MarshallOfSound** [comment]
TLDR: This is an upstream fixed that will one day be fixed and I am actively working towards it.

See `Squirrel.Windows` for more info
