### ISSUE TITLE
Display progress of song on taskbar icon

### ISSUE THREAD

**Issue by nmoorthy1** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1567]
Other programs, like MPC-HC or foobar2000 show the current song progress on their icon in the windows taskbar (see image). The green also changes to yellow if it is in a paused state. It would be great if this could also display this information.
![screenshot 11](https://cloud.githubusercontent.com/assets/6493496/18178541/9fb3acce-7033-11e6-8c32-cf91baf429e8.jpg)

**Comment by MarshallOfSound** [comment]
Hmmm, I thought this was used to show download progress or something else.  Never personally seen it used for media progress.

Electron has an API for it, I just need to think about it for a bit.  It seems like a strange usage of the API.
