### ISSUE TITLE
Enforce a minimum window width of 960px

### ISSUE THREAD

**Issue by cjthompson** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1568]
**OS:**
OS X 10.11.6

**Issue Descriptions:**
The Google Play website enforces a minimum width of 960px.  The desktop player allows the window to be resized to a significantly smaller size, which makes the content not render correctly.

Another possible solution would be to implement custom CSS to remove the minimum width contraints on the `<html>` element and the playlist.

**Steps to Reproduce:**
1. Resize the window to have a width of less than 960px

**Comment by MarshallOfSound** [comment]
> Freedom

👍 If the user wants to make the window smaller, I don't see why we shouldn't let them.  I used to enforce this minimum width and a multitude of users asked for it to be removed.  So I did because I agreed with them
