### ISSUE TITLE
JPEG artifacts is now visible in the artwork

### ISSUE THREAD

**Issue by vanushah** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1570]
Hi. I've noticed that quality of album art has substantially degraded. Both on the thumbnails and enlarged ones. I've attached some examples.

Also, it's seems that Google Play Music on the web is not affected.

![2016-09-02_08-09-23](https://cloud.githubusercontent.com/assets/188117/18190487/720b240e-70ed-11e6-9ff4-224cd4d15513.png)
![2016-09-02_08-09-36](https://cloud.githubusercontent.com/assets/188117/18190488/720e4350-70ed-11e6-9855-d9abfd455501.png)

**Comment by MarshallOfSound** [comment]
> Also, it's seems that Google Play Music on the web is not affected.


This seems very unlikely, as this basically is Google Play Music on the web.  Can you post a side by side comparison that clearly shows the visual degradation.

**Comment by vanushah** [comment]
Whoops... I didn't notice it, now I can see the same degradation on the web.

**Comment by MarshallOfSound** [comment]
Closing as it's a GPM issue.  Probably in the server side image compression
