### ISSUE TITLE
OSX chromecast no longer showing up

### ISSUE THREAD

**Issue by kselby** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1571]
OSX 10.11.6

**Issue Descriptions:** 
I can no longer use my chromecast with the app, the button to stream to my chromecast is no longer showing up. I can still stream from the web browser google play music website though.

**Comment by MarshallOfSound** [comment]
This is a bug in GPM.  The chromecast button is hidden on windows less than 1096px wide.

I do not know why, but I have patched the change in master and will be pushing a release this weekend.
