### ISSUE TITLE
Unreadable font under "venue" in "Upcoming concerts" section

### ISSUE THREAD

**Issue by jwcardenas** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1573]
OS: 10.11.6

Issue Descriptions: Text color for venue font in "Upcoming concerts" section is unreadable. The font is white and background color is white.

Steps to Reproduce: Go to any artist and view "Upcoming concerts" section
https://drive.google.com/file/d/0B_jfiMgdPz54VW4zZE94aFMwd1U/view?usp=sharing

**Comment by MarshallOfSound** [comment]
@jwcardenas Can you please go and raise this over at https://github.com/gmusic-utils/gmusic-theme.js
