### ISSUE TITLE
Minimize, Maximize, Close buttons overlap and do not work

### ISSUE THREAD

**Issue by Waveharp** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#158]
The three window buttons - minimize, maximize, and close - do not work. When one of them is clicked, the icon for the adjacent button appears and displays the button press animation, but nothing happens.   Pressing minimize makes a small, gray maximize button appear just to the right of it. Pressing maximize reveals a close button, and if I click just to the left of the minimize button, a similar minimize button appears. None of these buttons do anything.

![play music desktop buttons](https://cloud.githubusercontent.com/assets/6983719/12624432/a84b1916-c4f4-11e5-8eed-3540f1b3d234.png)

**Comment by MarshallOfSound** [comment]
This is a known issue and fixed in master.  Please see for instance #137 #31 

The next release will contain a fix for this or you can download the latest beta from appveyor

**Comment by Waveharp** [comment]
Awesome, thanks.
