### ISSUE TITLE
Preserve zoom level

### ISSUE THREAD

**Issue by Wikiwix** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1580]
I reduce the size of the elements by "Strg" + "-" to fit more content. But after a restart one gets the standard size again, but when I insert "Strg" + "-" then, it gets smaller as it was before the restart. So somewhere the zoomlevel is stored but not applied.  

I guess it would be nice to furthermore access the zoomlevel in the app settings for users not familiar with the shortcuts.

**Comment by MarshallOfSound** [comment]
Duplicate #1421
