### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by hoferrier** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1582]
put the buttons in the window thx

**Comment by MarshallOfSound** [comment]
Not sure what you mean by this request.

Please follow our [Contributing Guidelines](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/CONTRIBUTING.md) when making issues
