### ISSUE TITLE
Player display goes black [Windows 10]

### ISSUE THREAD

**Issue by elwooha6** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1583]
**OS:**
Windows 10

**Issue Descriptions:**
When I start the player I am able to login but clicking "Music Library" causes the app to go all black. I've waited for it to come back but had no luck. If I start the player again it works temporarily but eventually goes black again. I'll update here if I find anything of use.

**Steps to Reproduce:**
Start the player and wait?

**Comment by elwooha6** [comment]
Back at it again, after shutting down last night and coming back today I have not had the issue again. Guess it fixed itself?

**Comment by MarshallOfSound** [comment]
This will be a GPU specific issue that Chromium will have undoubtedly fixed and will therefore end up upstream inside Electron shortly.

Bear with the sporadic black screens for now and wait for the next release 👍
