### ISSUE TITLE
App loses queue whenever internet connection is lost

### ISSUE THREAD

**Issue by lcohen16** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1584]
**OS:** OS X 10.11.6 

**Issue Descriptions:** Any time the computer wakes up from sleep or regains internet connection the app refreshes itself, thus losing the queue.

**Steps to Reproduce:** Turn off internet connection and back on again, or put computer to sleep, or turn off.

**Comment by MarshallOfSound** [comment]
Duplicate.

Fixed in master
