### ISSUE TITLE
Music Library shuffle doesn't work

### ISSUE THREAD

**Issue by deefrawley** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1586]
Windows 10 Home. Version 1607. Build 14393.105 64 bit

Shuffle play on "My Library" plays the one track over and over.

**Steps to Reproduce:**
Go to Music Library.
Click Shuffle.
Wait until end of song. Song is repeated. Clicking Shuffle again moves to a different track.

**Comment by MarshallOfSound** [comment]
This is almost certainly a bug inside GPM not a bug inside the desktop player.  Can you check if you can reproduce this issue inside Chrome. 👍

**Comment by deefrawley** [comment]
Issue doesn't occur in the Android version of GPM. How do I check with Chrome?

**Comment by MarshallOfSound** [comment]
Navigate to http://music.google.com

**Comment by deefrawley** [comment]
Behaviour is the same in Chrome. Happy to close issue as it is with the Google service *sigh*.

**Comment by MarshallOfSound** [comment]
> Behaviour is the same in Chrome. Happy to close issue as it is with the Google service sigh.

😢 They'll fix it soon hopefully 👍
