### ISSUE TITLE
App hangs occasionally when using Full Screen Album Art Mode

### ISSUE THREAD

**Issue by CoffeeistheNewBlack** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1589]
**OS:**
Windows 10 Anniversary Update

**Issue Descriptions:**
When you play music and use Google's Full Screen Album Art Mode, it will play fine for a while but then suddenly hang. Google Play Music Desktop Player appears to be open, but the screen is white and no music plays.

**Steps to Reproduce:**

1. 
2. Play an album.
3. Click on the Album Art Full Screen Mode on Now Playing
4. Wait, but ensure that Full Screen Mode is on during the entire time. When it happens is inconsistent.
5. Will hang, screen goes white, music stops.

Errors in the attached log file. 
[crashlog.txt](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/457582/crashlog.txt)

**Comment by MarshallOfSound** [comment]
That error log is for Squirrel which is independent of the application UI.

This issue is probably the Chromium black screen issue that has been fixed upstream and will be fixed in the next release
