### ISSUE TITLE
Clicking the current playlist icon does not bring up playlist view

### ISSUE THREAD

**Issue by pchertok** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#159]
I am on Windows 7 - Sometime when I click the playlist icon in the lower right you can see the playlist menu "open" but once the maximize animation complete the playlist is no longer visible.  Clicking on the playlist icon again will show the playlist doing its minimize animation.  The only way to bring everything back to normal is to quit the app and reopen it.

**Comment by MarshallOfSound** [comment]
Please add screenshots to this issue, I can't quite understand what parts of the UI you mean

**Comment by pchertok** [comment]
Here are the requested shots.  Hopefully this clarifies things.

![playlist_1](https://cloud.githubusercontent.com/assets/1420525/12653410/6e107e7a-c5bd-11e5-9b62-6e1e1df7879f.png)

![playlist_2](https://cloud.githubusercontent.com/assets/1420525/12653416/71c015e4-c5bd-11e5-8d7a-8ed1a8bbf88d.png)

**Comment by MarshallOfSound** [comment]
Ahhh, other players have experienced this problem as well I believe.  It is actually a bug in GPM not GPMDP.  I'll see if I can replicate the issue, but for now, if it does happen, you can force a browser redraw by simply resizing the window.  That should trick it into working again

**Comment by MarshallOfSound** [comment]
I can't replicate this issue at all, appears to be a user specific / setup specific bug.  Without reproducible steps I can't proceed with this issue.
