### ISSUE TITLE
OS X - unable to switch back to main window from mini-player

### ISSUE THREAD

**Issue by t-readyroc** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1592]
**OS:** OS X 10.11.6

**Issue Descriptions:** Unable to change back from mini-player to normal size

**Steps to Reproduce:** Play music, switch to mini player via button on bottom right.  Can function normally in mini-player (all other buttons functional).  Attempt to click button in bottom-right to go back to playlist does nothing.

**Comment by MarshallOfSound** [comment]
Can you try using the "Full Player" option in the "Window" menu?

**Comment by t-readyroc** [comment]
@MarshallOfSound Oddly, the Window menu lists the player in "full size player" when the player is in mini.

**Comment by MarshallOfSound** [comment]
@t-readyroc I can't reproduce this issue.  Which version of the app are you running?

**Comment by t-readyroc** [comment]
@MarshallOfSound 3.5.0

**Comment by t-readyroc** [comment]
@MarshallOfSound looks like it's fixed in 3.6.0!

**Comment by MarshallOfSound** [comment]
Urghh, I didn't do anything 😆 

Probably a cache glitch somewhere

**Comment by gennarocc** [comment]
Im currently running into this issue currently on macOS 10.13.1. Any thoughts?
