### ISSUE TITLE
OS X - Options thumb up and thumb down are switched

### ISSUE THREAD

**Issue by sengmann** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1593]
When i use the hotkeys to vote a song up and down, the action triggered by the hotkey is the opposite direction.

**Comment by jostrander** [comment]
Just to confirm, your thumbs down hotkey is triggering thumbs up? Are you 100% sure you're using the right hotkeys?

**Comment by sengmann** [comment]
Yes 100% my hotkey is alt-cmd-arrow up and it votes the song down and the other direction vice versa. My interface is translated in german. Perhaps the issue is not on the player itself but in translation...

**Comment by Juburin** [comment]
I can't confirm this, my hotkeys work.
OS X: 10.11.6 (15G1004)
GPMDP: 3.5.0

**Comment by MarshallOfSound** [comment]
This appears to be the translations being the wrong way round 😢 

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/_locales/de.json#L58

**Comment by jostrander** [comment]
More than likely. I dont use those hotkeys but I just set them and they
seem to work fine. I believe (can't look now) that thumbs up is on the left
and thumbs down is on the right.
