### ISSUE TITLE
Choice of port ?

### ISSUE THREAD

**Issue by mrdj07** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1595]
Hello,

As a fellow developper, I noticed that you use the port 5672 for your application.

Could you maybe change that ? This port is commonly used for applications such as RabbitMQ.

Thanks !

**Comment by jostrander** [comment]
Not sure it's documented, so if not it would be great if someone would add this to the Wiki. 

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/main/features/core/websocketAPI.js#L105

We have the option via environment variable for a non-standard port via `GPMDP_API_PORT`,  as well as non-standard listening address via `GPMDP_API_HOST`.
