### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by lray801** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1596]
**OS:**
Windows 10
**Issue Descriptions:**
Pretty consistent high CPU usage while streaming.
**Steps to Reproduce:**
Run the program :) I'd debug but there aren't debug instructions on the FAQ page. It's a fairly consistent issue.

![image](https://cloud.githubusercontent.com/assets/22059382/18323105/4d470980-74f3-11e6-953d-275fa1cec2fd.png)

**Comment by jostrander** [comment]
How long has the player been open for? Does it happen pretty consistently? System specs? Total memory?  I know that @MarshallOfSound's usage is typically under 10% from other similar issues. I generally only get up to 15 or 20% but I'm not sure on memory usage stats.

**Comment by MarshallOfSound** [comment]
Tbh my usage is typically under `2%` across all processes.  But my hardware is slightly above typical 😆 

But yeah,

> System specs?

**Comment by lray801** [comment]
@jostrander The player had been open for a couple hours. As soon as I start playing, the processor usage goes up. I'm not worried about memory usage ATM. My computer's running an i7550 with 2.4GHz, 12GB of RAM, Windows 10, running up to date,
Thanks for the help :)

**Comment by lray801** [comment]
Just want to also add on that first open after a reboot results in a white screen:
![image](https://cloud.githubusercontent.com/assets/22059382/18362568/775b4dd2-75c3-11e6-8867-8ee440110537.png)
I have to close, then re-open the application to get it to run.

Thanks!
Luke

**Comment by MarshallOfSound** [comment]
This sounds like another manifestation of the GPU bug that Chromium 51 has been having.  Probably causing quite a few wasted CPU cycles.  Closing this out pending the Electron `1.4.0` release 👍

**Comment by k1sul1** [comment]
I have the same problem, running the latest version (3.6.0) on OSX, very high memory and cpu usage. Currently using 800MB of RAM and the CPU utilization is varying between 10-60%. 

Though it has been open for 58 hours, same kind of problems arise when having a tab like Facebook open in Chrome for too long. 

I'm going to setup a cronjob to restart the app more frequently as a workaround. OSX never closes the app if I don't force quit it.
