### ISSUE TITLE
Feature Request: Possibility of a standard app?

### ISSUE THREAD

**Issue by berryelectronics** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1597]
Ok, pressing control+shift+g does also the job, but being able to set GPMDP as a standard app for google links would be nice (if its possible at all). According to a friend its possible with the spotify desktop app.

**Comment by jostrander** [comment]
So you're saying we should register a link handler for https://play.google.com/music/listen ?

**Comment by berryelectronics** [comment]
yeah, but i dont know if (atleast in windows) it triggers uac (probably?)

**Comment by berryelectronics** [comment]
oh well, about the spotify thing: 
IIUC if you set in the settings that you want the desktop app to open and you open a normal http link, it will redirect to spotify://, and spotify:// links will open the app automatically, so they made their own uri scheme which makes it possible to set a standard app.

so yeah, doubt that google will implement that one.

One thing that would be possible: when you press the share button that it shows to links: one for the browser and one for the web. (http and gpmdp maybe). but then there will be a problem if you try to open the gpmdp link in the desktop (i guess).
if we had access to the google url we could then setup a webserver that redirects it to https if the app isnt installed. and that again wont work.

so yeah, control shift g will be the go-to option

**Comment by jostrander** [comment]
I don't think this is possible currently with our current installation method. 
https://github.com/electron/electron/issues/2795
We would need to register a protocol handler in the windows registry, which is probably a little bit of security concern for most. 
Also it looks like spotify registers a URI: `spotify:` which google doesn't have anywhere in the web interface so we'd have to have browser extension to convert links on all pages over to the `gpmdp:` URI. All in all this would be a nice feature to have be would be a _lot_ of trouble to get working.

**Comment by jostrander** [comment]
Ah, and you beat me to the punchline.

**Comment by MarshallOfSound** [comment]
@jostrander Making a protocol handler = easy and not much of a security concern.  Electron actually has an API for it 👍 

But you are correct in saying it would require a companion chrome extension of some kind, which is beyond the scope of this app 👍

**Comment by jostrander** [comment]
As I understood that issue I posted, it seemed like the protocol handler was only internal to the app, not system wide.

**Comment by MarshallOfSound** [comment]
@jostrander 
Electron has an internal `protocol` module **and** a few `protocolClient` API's on the `app` module.

See https://github.com/electron/electron/blob/master/docs/api/app.md#appsetasdefaultprotocolclientprotocol-path-args-macos-windows
