### ISSUE TITLE
Can we get a 64 bit build?

### ISSUE THREAD

**Issue by MTRougeau** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#16]
Any CPU seems like it is always building 32 bit.....can we get a dedicated 64 bit version in addition to 32? Thanks!

**Comment by MarshallOfSound** [comment]
I believe it would require a separate project as CefSharp requires a specific build target.  I chose 32bit as it will work on 64bit systems whereas the reverse is not true.  Is there any particular reason for the 64bit request?

**Comment by MTRougeau** [comment]
I built it in 64 bit and if compiled correctly and worked great. I mostly
want it because I'm OCD and want everything that can run in 64 bit to do
so. :)

**Comment by MarshallOfSound** [comment]
I only tried to build in 64 back when this project was using CefSharp 41.0

I guess since then they have changed it a bit and now it does indeed work.  It'll take a bit of work (mostly on the update mechanism) but I'll try upload 64 bit builds from now on
