### ISSUE TITLE
Feature Request: Ability to see playlist in mini view

### ISSUE THREAD

**Issue by pchertok** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#160]
It would be nice if we could still access the current playlist even in the mini view.

**Comment by MarshallOfSound** [comment]
I do not think there is physically enough space in the mini player to show the upcoming playlist.  Can you please raise this issue on https://github.com/MarshallOfSound/gmusic-mini-player.js instead and I'll look into it
