### ISSUE TITLE
Currently playing song displaying incorrectly with dark theme

### ISSUE THREAD

**Issue by ZephireNZ** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1600]
**OS:** Windows 10 Pro Build 14393.105

**Issue Descriptions:**

Looks like Google may have changed some web player CSS, as the dark theme breaks on the highlighted song.

![image](https://cloud.githubusercontent.com/assets/1644496/18342120/4a410a60-7601-11e6-9fce-cf1c4ae1a57b.png)

**Steps to Reproduce:**

1. Be running v3.5.0
2. Change to dark theme in settings
3. Play a song in a playlist, or open now playing queue - the current song has strange artefacts where theme is badly applied

**Comment by MarshallOfSound** [comment]
Please raise over at https://github.com/gmusic-utils/gmusic-theme.js
