### ISSUE TITLE
Feature Request: Wheel on tray icon for volume

### ISSUE THREAD

**Issue by njaard** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1603]
When you use the mouse-wheel on the tray icon, you should be able to adjust the volume.

This definitely will work on Linux, but I don't think on Windows.

**Comment by MarshallOfSound** [comment]
> This definitely will work on Linux, but I don't think on Windows.

Unfortunately this is one of things that isn't cross platform and at least on linux is very window manager specific.  As such Electron won't implement an API for it so we can't implement a feature with it

**Comment by yaeuge** [comment]
Is it also unavailable to play/pause with middle-click the tray icon?
It's so handy in DeaDBeeF...
