### ISSUE TITLE
Feature Request: Left click on tray shows/hides window

### ISSUE THREAD

**Issue by njaard** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1604]
When you left click on the tray icon, the visibility of the main window should be toggled, at least in "minimize to tray" mode, which actually should be called "close to tray".

Also, middle click for pause/resume.

**Comment by MarshallOfSound** [comment]
I don't know what OS this is but.

1. On windows double click toggles
2. On linux it depends if your window manager supports click event (most don't)
3. On macOS it is an OS limitation and you can't listen for click events

**Comment by njaard** [comment]
My window manager supports click and doubleclick, yet the GPMDP tray icon doesn't reply at all.

**Comment by njaard** [comment]
Linux, KWin is the WM.

**Comment by njaard** [comment]
Virtually all WMs in Linux support the click action. Also, it works in Electron despite the documentation being wrong: https://github.com/electron/electron/issues/1715

**Comment by MarshallOfSound** [comment]
We have the code for it but as mentioned before.  Linux doesn't support it in Electron.

> My window manager supports click and doubleclick, yet the GPMDP tray icon doesn't reply at all.

Just because your WM supports it doesn't mean anything.  There isn't a generic linux way of doing it so it's not possible

```js
  case 'linux':
  case 'freebsd': // <- for the hipsters
  case 'sunos':   // <- in case someone runs this in a museum
    appIcon.on('click', toggleMainWindow);
    break;

```
