### ISSUE TITLE
Cannot set shortcut keys

### ISSUE THREAD

**Issue by passive-sinner** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1605]
I hate to submit an issue, but I've tried everything I can think of and I still cannot set shortcut keys. Every time I try to set one, the cursor will blink next to the "Not Set" text but literally not do anything. 

I've made sure I don't have any conflicting software like Intellipoint, I've closed and restarted both just the app and my computer multiple times, and the keyboard is a plain-as-can-be Dell keyboard - no built-in media hotkeys of any sort. I went to %APPDATA%\Google Play Music Desktop Player\gpmdp.log and didn't see anything that jumped out at me... in fact, I didn't really see a whole lot of anything in there other than Bonjour failure messages. I also made sure that I didn't have the Chrome extension installed, and just to be safe, even restarted Chrome. I also visited the FAQ (which is where I got the tip about the Chrome extension) to see how to make a Debug log, but I didn't see anything there that actually mentioned how to do that...

I'm on Windows 7 Professional with the latest version of the app downloaded.

**Comment by passive-sinner** [comment]
Never mind - just saw there must've been an update from 3.5.0 to 3.6.0 today. The update seems to have fixed this issue.

**Comment by WorstIdeaEver** [comment]
I'm getting the same issue. Don't have chrome and/or any key-modifying software (autohotkey). Tried restarting and reinstalling. Running latest build (3.6.0) on windows 10 (surface 4).

**Comment by passive-sinner** [comment]
This problem showed up for me again the other day, but a reboot fixed mine.

One think I've noticed: There are still certain keys it will not let me bind as hotkeys. For instance, I wanted Pause/Break to be my, well, pause hotkey, but it wouldn't work. I ended up using CTRL + [insert key here] for them all, and that worked perfect.

You might give that shot.
