### ISSUE TITLE
Last.fm Not Authorized 

### ISSUE THREAD

**Issue by jjanusch** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1606]
**OS:** macOS 10.11.6

**Issue Descriptions:** After upgrading this morning to 3.6.0, the player stopped scrobbling. This has happened before and usually just requires unauthorizing and re-authorizing in the Preferences. So I did that and now I can't authorize. I will click "Log In to Last.fm", it will briefly flash "Authorization in Progress", and then go right back to "Not Authorized".

I also cleared out relevant files in `~/Library/Preferences` and `~/Library/Application Support` and restarted the application. This made no difference.

**Steps to Reproduce:** Unauthorized Last.fm, try to re-authorize it

No relevant logs were found in `~/Library/Application Support/Google Play Music Desktop Player/gpmdc.log` and I could not find any other log files. If there is one, I can provide the contents if requested

**Comment by gricha2380** [comment]
I am experiencing the same issue. Mac OS X 10.11.6, and GPMDP v3.6.0.

**Comment by MarshallOfSound** [comment]
Looks like Squirrel hit an update glitch and corrupted the LASTFM constants file.  Please download the latest version `3.6.0` from the website again.  

www.googleplaymusicdesktopplayer.com

Sorry for the hassle, something strange happened in the latest mac update.

**Comment by jtiala** [comment]
Seems like I'm having the same issue with GPMDP v4.0.1 (just installed the app for the first time) and macOS 10.12.1.
If I click the "Login to last.fm" button, the title changes to "Last.fm status: Authorization in progress" and just freezes there.

**Comment by MarshallOfSound** [comment]
@jtiala The issue you are experiencing was fixed in master and will be out next release

**Comment by hmalaud** [comment]
Is it possible to get/compile the latest .app from the master branch?

**Comment by niall-byrne** [comment]
I'm seeing this 4.0.2 after I logged out of last.fm, I'm unable to log back in (hangs and with the authorization in progress warning)

**Comment by MarshallOfSound** [comment]
> coincidental

👍 😆

**Comment by nilsonsfj** [comment]
I'm facing this same issue on Linux.
