### ISSUE TITLE
Apparent queue modal redesign needs a minor tweak for dark themes

### ISSUE THREAD

**Issue by shakeelmohamed** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1607]
**OS:** OS X 10.11.6, using v3.6.0

**Issue Descriptions:**

Dark theme needs to be applied to at least one more DOM element, probably because Google tweaked the UI slightly.

<img width="733" alt="capturfiles_4" src="https://cloud.githubusercontent.com/assets/1480063/18365805/f5b75d6a-75c8-11e6-8716-71b1c588fd28.png">

**Steps to Reproduce:**

Start playing from a playlist, or start a radio playlist with dark theme enabled.

**Comment by MarshallOfSound** [comment]
This was fixed in `3.6.0`?

**Comment by shakeelmohamed** [comment]
@MarshallOfSound is there a way to force clearing the cache? After quitting and re-launching it's still there

**Comment by MarshallOfSound** [comment]
@shakeelmohamed The update glitched for a few people on macOS.  Please manually redownload from www.googleplaymusicdesktopplayer.com

**Comment by shakeelmohamed** [comment]
Looks good after manually upgrading!
