### ISSUE TITLE
Blank screen after updating - OS X

### ISSUE THREAD

**Issue by rameezv** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1608]
**OS:**
OS X 10.11.6

**Issue Description:**
The app shows a blank screen on startup after the latest update (3.6.0), even after reinstalling. It's appears the same as https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/1037 except that it's on OS X. 
Can still open settings.

EDIT: ALSO - there are no Audio Devices in the Audio Devices menu. Not sure if it's related.

**Steps to Reproduce:**
- Start app
- Wait for circle loader to spin a couple times
- See blank screen

![image](https://cloud.githubusercontent.com/assets/5344115/18367094/ad908d5a-75d6-11e6-8803-1023446a8dc1.png)
![image](https://cloud.githubusercontent.com/assets/5344115/18367107/bd381ab6-75d6-11e6-8efa-13b7f09b873a.png)

**Comment by sippi90** [comment]
I've the same problem with version 3.6.0.
- Windows 10 x64

**Comment by MarshallOfSound** [comment]
Still haven't made to jump to the next Chromium version and there are known bugs RE GPU acceleration in this version.  This is pending the Electron `1.4.0` release

**Comment by bigtreeworld** [comment]
@MarshallOfSound Cool, is there something we can do to use the app in the meantime? I don't know how to turn off GPU acceleration on OS X.

**Comment by rameezv** [comment]
Cool, is there something we can do to use the app in the meantime? I don't know how to turn off GPU acceleration on OS X.

**Comment by MarshallOfSound** [comment]
@rameezv You should be able to get it to work by resetting the cache.  Open terminal and type in 

```bash
m -rf ~/Library/Application\ Support/Google\ Play\ Music\ Desktop\ Player/
```

This will completely reset the application but it should make it work 👍

**Comment by jostrander** [comment]
@MarshallOfSound fixed your command to be `rm` instead of just `m` :+1:
