### ISSUE TITLE
Installing Custom CRX Chrome Extension

### ISSUE THREAD

**Issue by cbluth** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1609]
**OS:** Ubuntu 16.04

**Issue Descriptions:** I would like to install a custom crx chrome extension. Is this in the realm of possibility?

**Comment by cbluth** [comment]
Seems as though it may be possible, if GPMDP is based on electron:
https://github.com/electron/electron/issues/1498#issuecomment-230096165

**Comment by MarshallOfSound** [comment]
@cbluth The API you link to is to install Chrome DevTools extensions.

Unfortunately this is not the same thing as a standard chrome extension.  Chrome extensions expect a lot of API's to be available (chrome.*) which are not available in Electron.

This is a wontfix as it is technically impossible
