### ISSUE TITLE
Feature request: Sound Search History

### ISSUE THREAD

**Issue by maarten1055** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#161]
Play Music doesn't show us the sound search history playlist by default. Would it be possible to implement this?

https://play.google.com/music/listen#/ap/sound-search

This thing is awesome btw, great work!

**Comment by MarshallOfSound** [comment]
Technically it would be possible, but it's a limited use case feature.  It might make more sense for you "the user" to use the "add playlist to playlist" button so that songs in `sound-search` get added to one of your pinned playlists

**Comment by MarshallOfSound** [comment]
Not saying I wouldn't accept a PR for this feature, but it's not something I'm going to spend time on

**Comment by maarten1055** [comment]
No worries, I understand what you mean. Maybe I will look into it myself sometime.
