### ISSUE TITLE
Graphic glitch

### ISSUE THREAD

**Issue by ja-som** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1611]
**OS:**
OS X 10.11.6

**Issue Descriptions:**
With new GPMDP v3.6.0 I have a ugly graphic glitch with dark theme. In the playlist, on the playing song are white rectangles (see screenshot).

**Steps to Reproduce:**
Set dark theme in settings, play a song in a playlist

![snimka obrazovky 2016-09-09 o 12 53 55](https://cloud.githubusercontent.com/assets/5942380/18384936/d943dea4-768d-11e6-8155-4141f0946982.png)

**Comment by darxmorph** [comment]
+1 on Linux (openSUSE Leap 42.1)

![screenshot from 2016-09-09 13-09-37](https://cloud.githubusercontent.com/assets/13508882/18385140/0e57aeee-768f-11e6-8af9-9f7d31ed9adf.png)

**Comment by MarshallOfSound** [comment]
@darxmorph You aren't on the latest version.

@ja-som The macOS update glitched this time, the first couple of hundred people got an incomplete update and it partially rolled back the changes.  Redownload from the website to get a proper `3.6.0`

**Comment by ja-som** [comment]
OK, thanks
