### ISSUE TITLE
Menu in tray icon is not translated

### ISSUE THREAD

**Issue by ja-som** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1612]
**OS:**
OS X 10.11.6 and Windows 10 x64

**Issue Descriptions:**
The translation (SK) for the whole menu in the tray icon is not used, the settings window is OK

**Steps to Reproduce:**
Set other language and click on the tray icon :)

![snimka obrazovky 2016-09-09 o 13 13 18](https://cloud.githubusercontent.com/assets/5942380/18385309/13d7f288-7690-11e6-860c-4a8e3bf4d29a.png)

**Comment by MarshallOfSound** [comment]
I can't replicate this issue.  I hard coded my language code to be `sk` and my tray menu was translated correctly.

![noconfirm](https://cloud.githubusercontent.com/assets/6634592/18399344/bd630d50-7713-11e6-876e-fb6962eea2a5.PNG)

Possibly failing to determine your locale in the main process and this is causing it to default to `en-US`
