### ISSUE TITLE
The menubar icon for Ubuntu(/Linux?) is still using the old icon

### ISSUE THREAD

**Issue by GreenTurtwig** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1613]
The menubar icon for Ubuntu(/Linux?) is still using the old icon, probably should be updated to match Windows and MacOS with the "circle icon".

**Comment by MarshallOfSound** [comment]
I don't think that is possible 😕 

Can you confirm you have `3.6.0` installed

**Comment by GreenTurtwig** [comment]
Huh, nevermind, I've got it now. It appeared after a complete reinstall. Guess it didn't change when I updated.  
It does look a *little* bit big there though :-P https://puu.sh/r5iau.png

**Comment by MarshallOfSound** [comment]
Bigger the better 😉 

Yeah, the problem with linux is it looks right on some machines and wrong on others.  Gonna have to leave it standard there I think 😆

**Comment by GreenTurtwig** [comment]
:+1:
