### ISSUE TITLE
Visual artifacts in dark theme

### ISSUE THREAD

**Issue by gunslingerfry** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1616]
**OS:**
This is happening on both my work machine and my home machine
Ubuntu 14.04.5 (Gnome 3.12.1) & 16.04 (Gnome 3.20)
Kernel 4.4.0-36

**Issue Descriptions:**
Visual artifacts on the currently playing song.

**Steps to Reproduce:**
As far as I can tell, just turn on the dark theme and play a song. Highlighting (hovering over) the song  looks normal. Image attached.

![bug](https://cloud.githubusercontent.com/assets/4825657/18400210/19deb890-7692-11e6-9ebf-7bcf2004be22.png)

**Comment by Kun2210** [comment]
Yup, confirmed on Windows 7 64-bit as well, version 3.5.0

**Comment by Alipoodle** [comment]
Needs to be closed.
Was already placed on GPMDP Theme and is fixed in 3.6.0

**Comment by gunslingerfry** [comment]
Verified fixed in 3.6.0
