### ISSUE TITLE
Feature request: Surround sound support

### ISSUE THREAD

**Issue by heoconxz** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1617]
**OS: windows 10 anniversary edition

**Issue Descriptions: No surround sound with speaker fill by realtek

**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment]
This is not something we can provide by default as it is a non standard realtek driver issue.  There are chromium flags you can use to enable support for realtek surround but we won't be using these by default inside GPMDP.  You can however enable these yourself manually 👍
