### ISSUE TITLE
Heavy scroll lag when using large playlist

### ISSUE THREAD

**Issue by Resaltare** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1619]
Heya,

FIrst thanks for this very nice piece of software 😃 

Now I got a performance issue: when using a large playlist (around 1k songs), the scroll is very laggy. It basically makes the software unusable.

For information, I use am using a decent laptop (dell xps 13 2015) with win 10.
The CPU usage is around 35% with 150 MB ram used.

Everything is fine with small playlists.

Thanks!

**Comment by MarshallOfSound** [comment]
This is due to how GPM renders track lists.  They only render what is on screen, this does mean that when scrolling it has to work hard to update what is on screen.

There is nothing we can do about this unfortunately 😢

**Comment by Resaltare** [comment]
Shame :( What about caching the current playlist?
