### ISSUE TITLE
Small bug in PlaybackAPI

### ISSUE THREAD

**Issue by maarten1055** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#162]
I was playing around with this trying to get it to work in rainmeter and I noticed that the artist and album are switched.

in JSBound:

`PlaybackAPI.Instance.UpdateCurrentSong(song, album, artist, url); `

And the method itself in PlaybackAPI is:

`public void UpdateCurrentSong(string song, string artist, string album, string imageURL)`

**Comment by MarshallOfSound** [comment]
That's a bit awkward..
*Stares pointedly at @rynti* 

Just kidding, I missed it in the review, I'll push out a fix for this soonish

**Comment by rynti** [comment]
Oops, opened a pull request with the appropriate fix, sorry for the inconvenience :smile:

**Comment by MarshallOfSound** [comment]
This is really why we need unit tests for functionality like this, it just seems really hard to write :/
