### ISSUE TITLE
... mm ..... BLACK screen ??? !!!

### ISSUE THREAD

**Issue by christianbearslyclark** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1621]
... since the new update this week .... the app will not load. It will try to load into Google's music page ... but it will become all Black page. 

Any suggestions ?????

**Comment by MarshallOfSound** [comment]
This almost certainly the same GPU issue others are facing.  You can try clearing the cache or you will have to wait until the release with Electron `1.4.0` is out.
