### ISSUE TITLE
[MAC] Double click expand

### ISSUE THREAD

**Issue by jwjames83** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1624]
Prior to 3.6.0 we were able to double click on the title bar and player would go nearly fullscreen -in the sense of expanding to the entire screen, but not going to its own workspace.

Seems that using the custom titlebar broke this.

**Comment by MarshallOfSound** [comment]
Example upstream solution https://github.com/atom/atom/pull/12327/files
