### ISSUE TITLE
Lots of tearing

### ISSUE THREAD

**Issue by timpauvictor** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1627]
**OS:** Arch Linux

**Issue Descriptions:** Massive Screen Tearing

**Steps to Reproduce:** When I first run the app there is lots of screen tearing on the text. If I were to resize the windows it works fine. I believe this may be an issue because I'm using a tiling window manager and it forces the size/resolution to something the app doesn't like. For reference, I'm using the awesomewm. If there's any more info I can give you just let me know 

http://i.imgur.com/UoQG5W6.jpg

**Comment by jostrander** [comment]
There's plenty of reasons that could be happening. Have you tried with --disable-gpu? It could be an upstream bug with electron. I'm sure @MarshallOfSound will drop by with the debugging commands to start GPMDP with debugging outputs.

**Comment by MarshallOfSound** [comment]
Welcome to the world of fixed Chromium bugs 👍 

This flew through on the Electron issue tracker a few weeks back I think.  Should be fixed in Electron `1.4.0`
