### ISSUE TITLE
Unable to set media hotkeys to numpad

### ISSUE THREAD

**Issue by BitVortex** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1628]
**OS:** Windows 7 Home Premium

**Issue Descriptions:** Unable to set media hotkeys to numpad.

**Steps to Reproduce:**
Open Desktop Settings, switch to Hotkeys tab and try to set any hotkey to a key on numpad.
Numlock is on, but disabling it doesn't fix this issue.

**Comment by jostrander** [comment]
Unfortunately a limitation of electron is that all hot keys must use a modifier key such as ctrl, command, alt, etc. Can you it with one of those modifiers?

**Comment by BitVortex** [comment]
Thank you for the response. With numlock on, I am unable to set the media keys on numpad regardless of additional modifiers. Without numlock, the keys with additional functions (direction keys, PgUp etc.) work, but the plus sign, which I used in foobar2000 as global pause/play, as well as other arithmetic symbols, does not.

Since the hotkey functionality is outsourced to electron, I guess this is a wontfix for now and changes, if desired, would have to be committed to the electron repository?

**Comment by jostrander** [comment]
You are correct about this being an upstream bug that we really have no control over. @MarshallOfSound wrote some higher level keyboard interceptors for windows that use native bindings in node, but those still only capture the same keys that electron does as far as I'm aware. I just did a check on the browser side of things and they are definitely separate key codes, 

However if you roll over to Chrome's extension page and go to keyboard shortcuts at the bottom you'll notice that you can't set number pad shortcuts in their keyboard event listeners either, so this is further out than electron, and is actually an issue with chromium itself it seems.
