### ISSUE TITLE
Feature request: don't close lyrics dialog on left-mouse-key click 

### ISSUE THREAD

**Issue by agrml** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1630]
It would be nice to have ability to copy text from the lyrics dialog without closing it. Thus users will can use dictionaries to understand texts. Now we need to open the lyrics dialog again after selecting the text.

**Comment by jostrander** [comment]
This could be easily implemented, and I see the use case, but I'm not sure on the use case for exiting the lyrics screen at that point. I'd like to maybe see some discussion on this.

**Comment by agrml** [comment]
Hm... An "X" exit button on the top right corner of the lyrics screen?

**Comment by agrml** [comment]
And `esc` key support too.

**Comment by MarshallOfSound** [comment]
> Hm... An "X" exit button on the top right corner of the lyrics screen?

Average users would be confused that there are now 2 "close" buttons in their window near the top of the screen.

> And esc key support too.

This is non-obvious and again average users will get confused by the lack of obvious way to leave the lyrics view.

Copying lyrics was never intended to be supported, if anything we should be making it harder for you to copy the lyrics.  We wanted to make it as easy as possible to leave lyrics view without adding any extra UI.  Closing this out as wontfix
