### ISSUE TITLE
Mini Player window slowly falls down the screen until only the title bar is visible

### ISSUE THREAD

**Issue by ric2b** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1631]
**OS:**
Fedora 24 with XFCE

**Issue Descriptions:**
The mini player window slowly falls down the screen until I can only see the title bar. I can drag it back up but as soon as I let go it starts falling back down, which makes it pretty much impossible to exit the mini player without restarting the whole gpmdp

**Steps to Reproduce:**
With a song playing, switch to the mini player.

**Comment by MarshallOfSound** [comment]
This is undoubtedly a WM bug, without installing Fedora in a VM it sounds like your WM will be emitting resize events without realizing that the window is frameless (doesn't have native borders).

Unfortunately nothing we can do about this on our side of things, if you can preproduce the issue with Electron then feel free to raise an issue over their or possible raise an issue against your WM if you can.
