### ISSUE TITLE
Volume control no longer working with external speakers

### ISSUE THREAD

**Issue by Dillie-O** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1632]
**OS:**
MAC

**Issue Descriptions:**
After a recent update it appears that the volume controls on my macbook pro no longer work with my USB speakers that I have plugged in. In the past they've worked fine, and the play/pause controls work fine as well. When I change the output (the OSX values, not in the app) to my internal speakers, the volume control adjustment works just fine, but when I switch it to the external speakers, they don't work. I've even tried changing the settings in the app to specifically use the USB speakers instead of the default with no luck.

**Steps to Reproduce:**
1. Connect a pair of USB speakers to your Macbook Pro (I suspect Mac as well)
2. Launch the app, start a song
3. Use the volume controls on the keyboard (either MBP or external) to adjust volume

Expected result: Volume level changes. 
Actual result: Volume level does not change.

**Comment by jostrander** [comment]
I think what you're seeing may be circumstantial without further evidence proving otherwise. Does the same happen when GPMDP isn't open, for example while playing YouTube in Chrome? Are you using the native volume keys or programmed hot keys?

**Comment by Dillie-O** [comment]
I'll test it out and let you know. Thanks for the quick response!

**Comment by Dillie-O** [comment]
I'm using the native volume controls on my Microsoft Keyboard Elite and not the MBP. I've rebooted my laptop since I was having issues with other apps.

Interestingly enough when I use Google Music directly in Chrome volume control seems to do nothing

**Comment by jostrander** [comment]
If that's the case, I'm going to go ahead and say it's definitely not application specific and it's something to do with your system, drivers, etc. If circumstances change or you have more information feel free to reply, but for now I'm going to close this issue.
