### ISSUE TITLE
Dark theme currently playing track incorrectly styled

### ISSUE THREAD

**Issue by nheath** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1633]
Running OSX Version 3.6.0

Attached screenshot shows the issue, the currently playing track having an incorrectly styled partial white background. I've selected the dark theme, and an accent color. Not using any custom style injection. The issue seems to have come up in this latest release that adds custom styles support. Chosing the light theme or disabling themes entirely obviously hides/avoids the issue. I could not reproduce the issue on windows.

<img width="945" alt="screen shot 2016-09-13 at 8 45 48 am" src="https://cloud.githubusercontent.com/assets/1778613/18481140/f32535a2-798f-11e6-86d8-c2b1064bae1d.png">

**Comment by MarshallOfSound** [comment]
The first couple of hundred people to update to 3.6.0 hit an upgrade issue (some dodgy perm file).

Manually downloading 3.6.0 will resolve this issue
