### ISSUE TITLE
Using Music Controls in the Volume Control tab freezes system for 10-15 secs

### ISSUE THREAD

**Issue by poxeyfox** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1634]
**OS:**
elementary OS 0.4 Loki Stable

**Issue Descriptions:**
When press the fast forward or rewind buttons in the Sound Tab on elementary OS while listening to music on GPMDP it just freezes the system. I can still move my mouse, but nothing reponds.

**Steps to Reproduce:**
1. On GPMDP, pick any song that's in a playlist.

2. While it's playing, press the fast forward button (or rewind button).

**Comment by jostrander** [comment]
I'm not sure what the exact issue was, but there was quite a bit on Loki's end with regards to the sound applet the last time I looked it. I'll leave this open until I can get a look at it.

**Comment by poxeyfox** [comment]
Thank you! This bug has been annoying me xD.

**Comment by MarshallOfSound** [comment]
I've seen a lot of issues fly through the Electron repository RE Elementary OS Loki, and I think I'm going to have to take the stance that we appear have taken over there.

Elementary OS appears to have implemented a lot of features in non-standard ways, I.e. Their fancy new tray icon system, all very fancy, but it doesn't report at an OS level that it even exists 😢 

So while I would love to support every flavor of linux that exists, I can't see us being able to handle issues such as this one.

This sounds like Elementary expecting some kind of response or update the MPRIS spec doesn't require.  I would attempt to reproduce with other music players and then report to Elementary 👍 

@jostrander You can take a look into this if you want, but I'm going to close this out as I can't feasibly support all these linux variations.

**Comment by poxeyfox** [comment]
Ahh ok. Thanks for looking into it though.
