### ISSUE TITLE
Bug: Selected track shows a different album than what's playing

### ISSUE THREAD

**Issue by kevinbrotz** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1635]
**OS:**
OS X El Capitan
Version 10.11.6

**Issue Descriptions:**
GPMDP Version 3.6.0

When playing a track, it shows a different album (and artist in this case).  Every time I make a selection on a different track it shows that different album (Incubus - Science). I quit the app and relaunched it, it still persists.

**Steps to Reproduce:**
Unknown. This happens when I select any track.

![screen shot 2016-09-13 at 1 01 08 pm](https://cloud.githubusercontent.com/assets/11526845/18485605/2c1a451e-79b3-11e6-9dd1-2470e8f88a8b.png)

**Comment by jostrander** [comment]
Unfortunately this is something with GPM the service its self, and nothing that our code would have control over.
