### ISSUE TITLE
Dark Mode - Ugly White blocks appearing around playing song.

### ISSUE THREAD

**Issue by Harmelodic** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1638]
**OS:** Windows 7 Professional 64-bit 

**Issue Descriptions:** On the song that is currently playing, some ugly white blocks are surrounding the song. It looks like it might be that something is highlighted/selected but if I click in an open space, it doesn't disappear.I'm in Dark mode.
![googleplaymusicappissue](https://cloud.githubusercontent.com/assets/9994373/18523152/d7ed2422-7aaa-11e6-97e4-71ccd8261944.png)
This happens on every song, not just on Michael Buble. 

**Steps to Reproduce:** Open Google Play Music app. Be in dark mode. Click on a song to play.

**Comment by MarshallOfSound** [comment]
This was fixed in the latest release.  If you are on a proxy or VPN the update won't come through automatically so you might have to download it manually.
