### ISSUE TITLE
[Issue] Autostart

### ISSUE THREAD

**Issue by Martermann** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1639]
OS: Windows 10-64 bit
GPMDP Version: 3.6.0

Issue:
At first (auto)start the player has a whitescreen. Even the window around is missing. However the little icon in the taskbar is expanding and except of help->about, Thumbs and media control fully working. GPMDP Settings are working too.

Workaround:
Use the quit button in the task icon and start it again.
Reinstalling GPMDP didn't help at all.

Reproduce:
Settings are:
   general:
      -minimize to tray
      -own color
      -Voice-control
      -JSON API
      -Playback API
      -start with last opened site
      -scroll song text
   mini player:
      -nothing

**Comment by MarshallOfSound** [comment]
This sounds like auto-start is still pointing to an old version, please toggle the auto start setting (with an app restart in the middle)
