### ISSUE TITLE
[Issue] Remote connect

### ISSUE THREAD

**Issue by Martermann** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1640]
OS: Windows 10-64 bit
GPMDP Version: 3.6.0

OS: Android 6.0 Marshmallow
Device: Huawei PLK-L01 (Honor 7)
App version: 1.0.0

Issue:
The app doesn't connect to GPMDP. Not automatically nor through manual IP address.

Playback API is activated, both devices are in the same network. As IP address I used the IPv4 address of the Win 10 device.

**Comment by jostrander** [comment]
Do you have a firewall on the PC? Is it set to allow incoming connections for GPMDP?

**Comment by MarshallOfSound** [comment]
@Martermann There is currently a bug where non-english language computers don't automatically set up the firewall.

Run this command as administrator to setup the firewall exception.

```bash
netsh advfirewall firewall add rule name="GPMDP PlaybackAPI" dir=in action=allow protocol=TCP localport=5672
```
