### ISSUE TITLE
WebSocket Playback API has an empty return value for methods that invoke promises

### ISSUE THREAD

**Issue by arilotter** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1641]
**OS:**
Ubuntu 16.04

**Steps to Reproduce:**
   `{
      'namespace': 'search',
      'method': 'performSearch',
      'arguments': ['test search'],
      'requestID': 2
    }`
Sending the above message gives this result:
`{ namespace: 'result', requestID: 2, type: 'return', value: {} }`

GPMDP might need to make an effort to resolve promises and return through WebSockets only then.

**Comment by MarshallOfSound** [comment]
@arilotter Thanks for the report 👍 

Always cool to see people using the API :D
