### ISSUE TITLE
Opens with a black screen

### ISSUE THREAD

**Issue by onlyonthursdays** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1644]
**OS:** Windows 8.1 and Windows 7.

**Issue Descriptions:** 3.6.0 Just doesnt work for me.  Opens up to a black screen.  I can interact with the window, minimize, resize etc, but clicking anything inside doesnt do anything.

**Steps to Reproduce:** Tried it on two different computers, one running windows 7, one running windows 8.1.  3.5.0 and previous works fine.

**Comment by MarshallOfSound** [comment]
Duplicate #1618
