### ISSUE TITLE
Playlist button hidden when window width < ~1200px

### ISSUE THREAD

**Issue by zskamljic** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1645]
**OS:**
OS X and Arch Linux

**Issue Descriptions:**
![image](https://cloud.githubusercontent.com/assets/14160663/18597884/6198eda4-7c50-11e6-94a4-8f4905173abb.png)

The button to open the playlist is not there, unless the window width is more than ~1200px

**Steps to Reproduce:**
Reduce the width of the player to ~1200 pixels

**Comment by MarshallOfSound** [comment]
The exact value is `1020px` and this is a google design decision due to their queue UI not fitting into that screen size.  Overriding this CSS rule will cause thing to break
