### ISSUE TITLE
Visual glitch on song that is currently playing

### ISSUE THREAD

**Issue by DRSXS** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1647]
**OS:**
Win 10

**Issue Descriptions:**
There is a visual glitch when the song that is currently playing in a list of songs is not selected. See screenshot. ( https://gyazo.com/e0ada21b50bcdbf791184b1b0fbf4212 ) This happens in any list of songs, be it a playlist or just the list of all song or an album.

**Steps to Reproduce:**
Play song in a list of songs and select a different song. Although, it might be that this glitch is not actually caused by GPMDP, but that is hard to tell for me.

**Comment by jostrander** [comment]
This was fixed in 3.6.0. Please update.

**Comment by DRSXS** [comment]
My bad, I guess it didn't update automatically... weird. Sorry for the bother
