### ISSUE TITLE
Can't use after update to v 3.6.0

### ISSUE THREAD

**Issue by joaopedrosantos** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1650]
**OS:**
Windows 10
**Issue Descriptions:**
Black screen window
**Steps to Reproduce:**
Open Google play music desktop player
Loading interface appears
Black'ed

I already reinstalled multiple times, dunno how to make it work. Maybe the next version will work, i don't know

![capturar](https://cloud.githubusercontent.com/assets/11588994/18618036/68bfdbc8-7de6-11e6-9b75-d7a46e0cd44b.JPG)

**Comment by MarshallOfSound** [comment]
Duplicate #1618
