### ISSUE TITLE
Feature Request: Desktop remote

### ISSUE THREAD

**Issue by bernikr** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1652]
It would be great to have the possibility to control a running GPMDP in the network via a fully featured remote. This could be implemented either as a standalone application or as kind of "output device" in the settings, so that you can use GPMDP to control another instance of it.

The primary use case for this would be a setup where GPMDP is running on a media centre at all times and you want to control it from any device including PCs.

**Comment by MarshallOfSound** [comment]
So you mean

This

https://play.google.com/store/apps/details?id=com.marshallofsound.gpmdp.remote

**Comment by bernikr** [comment]
Well, I meant a Desktop version of this...

**Comment by jostrander** [comment]
I think this is something that could be added in with the 4.0 plugins feature. Basically all that's needed is a client that connects to the web socket interface. Could be accomplished very easily as a standalone web page as well.  @MarshallOfSound thoughts?

**Comment by MarshallOfSound** [comment]
@jostrander @bernikr Yeah, I definitely see this as a third party kind of thing.  You could easily make a small mock UI for GPMDP and use the websocket API but it doesn't belong in this repo natively I don't feel.

The plugins feature could also help here (hosting an internal HTTP server or something like that)
