### ISSUE TITLE
Visible only navigation bar in socks5 proxy, nothing else

### ISSUE THREAD

**Issue by wu360463231** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1655]
OS:Windows 10.14393

Application Version:3.6.0

System Language:Simplified Chinese

Issue Descriptions:
After running only see the navigation bar, the page is not displayed play music
Applications operating parameters:
 --proxy-server="socks5://127.0.0.1:7070" --disable-gpu
I was in a country that was unable to access Google, so use a socks5 proxy, Using a VPN can be used normally
![20160920022409](https://cloud.githubusercontent.com/assets/11737422/18643876/99e2dd56-7ed9-11e6-8749-02e510d9aa37.png)

**Comment by jostrander** [comment]
Does the same happen if you load the page in chrome via that same proxy? Unfortunately I'm not convinced just yet that this is an issue specifically with this application as the page loads partially.

**Comment by MarshallOfSound** [comment]
I just tested GPMDP with my own socks5 proxy and it works perfectly (albeit a bit slowly 😆 )

This must be an issue with either your network stack or your proxy
