### ISSUE TITLE
Hotkey Mappings not working

### ISSUE THREAD

**Issue by wolfblitzer** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1658]
**OS:**
OSX 10.11.6

**Issue Descriptions:**
Native Hotkeys stopped working after application update

**Steps to Reproduce:**
update, then use hotkeys

**Comment by MarshallOfSound** [comment]
I just double checked and my hotkeys still work on macOS even after downgrade and update again.

Can you double/triple check that they actually aren't working and provide they hotkey that isn't working.

**Comment by wolfblitzer** [comment]
I think Chrome may have been intercepting the mediakeys. I've chnaged the mediakey settings in the Google Music Media Keys on Chrome from Global to In Chrome. I will do a restart at EOD and try it again.

**Comment by MarshallOfSound** [comment]
> I think Chrome may have been intercepting the mediakeys

Yep, this is almost certainly the issue.  See https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ#my-media-keys-dont-work
