### ISSUE TITLE
UI highlighting bug

### ISSUE THREAD

**Issue by djmally** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1662]
**OS:** OSX, Windows 10

**Issue Descriptions:**  Clicking & dragging on a song in an album causes it to become partially highlighted, and clicking elsewhere does not cause the highlighting to disappear. This appears to only be visible with the dark theme enabled, since the highlighting is white.

**Steps to Reproduce:** See above, just click & drag next to a song in an album or playlist.

Screenshot:
<img width="1110" alt="screen shot 2016-09-21 at 2 18 15 pm" src="https://cloud.githubusercontent.com/assets/2838865/18729592/44a65f0a-8007-11e6-8845-509d9491b4b0.png">

**Comment by jostrander** [comment]
I've seen this screen shot before but never heard of that description for repro. Can you confirm this was fixed @MarshallOfSound ?

**Comment by berryelectronics** [comment]
looks similar to #1647 . maybe try to download the newest version from the website?

**Comment by MarshallOfSound** [comment]
Just conifrmed for like the 20th time this bug has been fixed.  If you are on macOS you might have got a bugged update and you will need to download the player manually again.  On windows the auto update to 3.6.0 will fix this
