### ISSUE TITLE
HotKeys on Ubuntu 16.04

### ISSUE THREAD

**Issue by sebastienserre** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1665]
**OS:**
Ubuntu 16.04
**Issue Descriptions:**
impossible to map keys
**Steps to Reproduce:**
Hello

I can't map hotkeys on my GPMDP, nothing happened when I try to set them in the settings

**Comment by jostrander** [comment]
Are you using a modifier such as ctrl?

**Comment by sebastienserre** [comment]
nop I didn't and try with key from num pad...
Thx,

**Comment by jostrander** [comment]
Number pad is an upstream issue with electron/chromium, nothing we can do there in the forseeable future.

**Comment by sebastienserre** [comment]
ok, thx for info
