### ISSUE TITLE
installed on Ubuntu 16.04, it removed chrome

### ISSUE THREAD

**Issue by LiamDawe** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1666]
So i'm not sure if this is an issue with your packaging, or with the new software store on Ubuntu 16.04.

I installed the 64 bit .deb file and google-chrome uninstalled itself as it did it.

**Comment by jostrander** [comment]
Pretty sure that's a fluke, can you reproduce it?

**Comment by LiamDawe** [comment]
Tried it again, and yes it removed Chrome again.

**Comment by LiamDawe** [comment]
My fuck up, don't worry.
