### ISSUE TITLE
Keyboard media keys have stopped working since custom controls were introduced

### ISSUE THREAD

**Issue by elihorne** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1667]
<Read all instructions in pre-amble>

**OS:**
Macbook Pro running 10.11.6 (15G1004)

**Issue Descriptions:**
Laptop media keys (play/pause, back, forward) no longer work.

Opening preferences and trying to reset those keys via the UI does nothing.

**Steps to Reproduce:**
Press keys with music playing, observe nothing happens.

**Comment by jostrander** [comment]
Those keys are not programmable, and should react independently of the hotkey settings. Can you make sure chrome hasn't attached to those keys via extensions -> keyboard shortcuts?

**Comment by MarshallOfSound** [comment]
> since custom controls were introduced

I don't know what feature you are referring to here.  Custom controls isn't part of any changelog that I'm aware of.

> Can you make sure chrome hasn't attached to those keys via extensions -> keyboard shortcuts?

This is almost certainly the issue, Chrome or another Chromium based application has requested the global shortcut and therefore we can't get it as well.  You need to remove the GPM extension from Chrome and/or any other application that is using global shortcuts that interfere with the media keys.

**Comment by haggs** [comment]
I'd like to +1 this bug. I'm on a 10.11.6 Macbook Pro, media keys quit working on this app. I'm aware of how Chrome can intercept the keys, but this issue doesn't happen for Spotify, for example.

**Comment by MarshallOfSound** [comment]
@haggs @elihorne So I just updated to `10.11.6` and I'm running `3.6.0` and my media keys work fine.  I've also asked around and I have a bunch of people on varying macOS versions who aren't reporting any issues.

Something else on your computer must be stealing the media keys and this isn't something I'm prepared to fix for macOS.

> but this issue doesn't happen for Spotify

I don't know how Spotify works but I do know that it isn't limited by the Chromium API's we use.

>  I've tried disabling the GPM extension, and removing it entirely. 

Once you have removed it entirely you have to properly quit Chrome and relaunch GPMDP in order for Chrome to actually release the hotkeys.
