### ISSUE TITLE
Feature Request: Windows Media Transport controls

### ISSUE THREAD

**Issue by TotalCalamity** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1669]
Hey There,
Was just thinking it would be cool to have windows media integration in the form of Media Transport controls.  An example is outlined below:
![7127 start_screen_thumb_44729e00](https://cloud.githubusercontent.com/assets/8054510/18770248/91ed42b2-8177-11e6-9539-3413fee209b1.png)

A blog post shows how to achieve this : 
[Here](https://blogs.msdn.microsoft.com/windowsappdev/2012/08/23/media-playback-what-you-need-to-know-about-playing-media-to-make-your-app-shine-in-windows-8/)

Thanks for all your hard work

**Comment by MarshallOfSound** [comment]
Unfortunately this API is for UWP apps only.  Electron is still win32 based so we don't have access to these API's.
