### ISSUE TITLE
Music stops after connecting with Remote Desktop (RDP)

### ISSUE THREAD

**Issue by perceival** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1670]
**OS:** Windows 10

**Issue Descriptions:** connecting with RDP to session where GPMD is playing causes music to stop (although player is showing like it is still playing). Only after some time and switching songs back and forth it is possible to resume playback. I believe the same applies to opposite scenario (GPMD running in RDP session and connection is established from console). Please note RDP profile is set to leave sound with the server.

**Steps to Reproduce:** logon locally -> run GPMD -> logon using RDP with the same credentials to the same session

**Comment by MarshallOfSound** [comment]
@perceival I can't debug this (as I don't have W10 pro and therefore can't RDP into my machine).  However this sounds like a Chromium / RDP bug.

Can you test the following two scenarios.

* Windows Media Player -> Play Music -> RDP -> What happens?
* Google Chrome (on gpm) -> Play Music -> RDP -> What happens?

**Comment by perceival** [comment]
Groove Music gets killed (but not every time) with em: Package Microsoft.ZuneMusic_3.6.25021.0_x64__string_here+Microsoft.ZuneMusic was terminated because it took too long to suspend. The rest (vlc, WMP) encounter aprox 1 sec break in audio playback but then they proceed to play by themselves.
Dont't have Chrome installed yet.

**Comment by MarshallOfSound** [comment]
@perceival This sounds like somewhat unpredicatable behavior and after some research it appears that RDP attaches a virtual audio driver to your computer while the session is in progress.

You could probably work around this issue by pointing GPMDP at the virtual audio device instead of the whatever device it is normally pointed at.  I would reccomend chasing this up with Microsoft support as they might have more knowledge about the audio driver they use.

But for me at least, this is a `cantfix` as I have no way to handle things at the audio driver level. 👍

**Comment by perceival** [comment]
Actually I believe it might not be related to RDP audio driver. Based on my understanding RDP audio driver kicks in if you choose Play on this computer option within RDP client (instead of Play on remote computer which is my case).
I ahve in addition tested it with IE and gpm and it bahaves like WMP or vlc (just short break).
What is interesting GPMDP appears like it is trying to play still but no progress nor audio. After some time it gives up and skips to the next track. After few of them there is EM: Can't reach Google Play. Reload the page and try again. And after pressing OK audio and playback are back available.

**Comment by jostrander** [comment]
I'm pretty sure what is happening here is still driver related, but some applications are capable of handling it and electron is not. That "pause" in music is the reconfiguration of audio devices, which causes GPMDP to lose access to the device it's streaming to. I've had this same thing happen when using DTS audio drivers where plugin in headphones creates a new device and removing removes the device.
