### ISSUE TITLE
HotKey

### ISSUE THREAD

**Issue by mbrgrg** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1672]
I can't change the hotkey and default hotkey don't work

**Comment by jostrander** [comment]
What have you tried? What system are you on? What version of GPMDP?

Hotkeys need a modifier key and number pad keys won't work. Default _media keys_ should work out of the box unless something else has grabbed them like chrome.

**Comment by mbrgrg** [comment]
I have tried to change the default keys with my custom keys and no changes. i'm on a desktop pc with windows 10 pro 64 bit and GPMDP v 3.6.0

**Comment by mbrgrg** [comment]
I've restarted the application and now works well =D

**Comment by jostrander** [comment]
Awesome!
