### ISSUE TITLE
3.6.0 No Chromecast icon on Antergos Linux

### ISSUE THREAD

**Issue by rittbys** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1673]
It shows up fine on play.google.com/music as well as my installation of Windows 10.

**Comment by MarshallOfSound** [comment]
@rittbys Please ensure that `avahi` is installed and running on your machine.  If that doesn't help please post your screen resolution 👍

**Comment by rittbys** [comment]
Yep it's installed. My resolution is 1920x1080

**Comment by MarshallOfSound** [comment]
@rittbys I've got to ask, are you sure you are up to `3.6.0`?

And can you ensure that the `avahi` service is actually running?  Also can you upload your debug information by following the below steps.

1. Open GPMDP
2. Perform the shortcut "Control + Shhift + G"
3. Type in the goto box "DEBUG_INFO"
4. Click "Let's Go!"
5. Upload the ZIP file that was generated

**Comment by rittbys** [comment]
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/491882/debug_info.zip)
![screenshot from 2016-09-25 15-27-05](https://cloud.githubusercontent.com/assets/5205015/18818045/b5b99d08-8334-11e6-9b14-c423933fbfae.png)

**Comment by MarshallOfSound** [comment]
@rittbys Is your firewall blocking MDNS transactions?  Port `5353`?

**Comment by rittbys** [comment]
Nope

**Comment by twisted-space** [comment]
I've got it working on Arch.

Install nss-mdns 
edit /etc/nsswitch.conf and append "mdns4" to the line that starts with "hosts:"
enable avahi-daemon.service and avahi-daemon.socket
Reboot

**Comment by appetterson** [comment]
Can confirm that @twisted-space's fix works for me on Arch. Don't need to reboot either. Just restart the avahi-daemon service.

**Comment by yochaigal** [comment]
Arch user; followed twisted-space fix but icon still doesn't appear for me. 
Running  avahi-browse _googlecast._tcp does reveal all of my Chromecast devices.  Restarted services & reboot; still no icon.

**Comment by yochaigal** [comment]
@twisted-space can I see the relevant parts of your nsswitch.conf file?

Thanks

**Comment by appetterson** [comment]
@yochaigal I'm not Twisted but here is mine on Arch that works with chromecast. All other lines in nsswitch.conf are at their default values.

`
hosts: files dns myhostname mdns4
`

**Comment by yochaigal** [comment]
Thanks - it still doesn't work, unfortunately. Here are the contents of my nsswitch.conf:

# Begin /etc/nsswitch.conf

passwd: files
group: files
shadow: files

publickey: files

hosts: files dns myhostname mdns4

networks: files

protocols: files
services: files
ethers: files
rpc: files

netgroup: files

# End /etc/nsswitch.conf

**Comment by yochaigal** [comment]
OK, I figured it out. I was running  - google-play-music-desktop-player-git-3.2.4.85.g2d9c143-1 (from AUR) and at some point they must have changed the package name to gpmdp; removing and upgrading to 4.0 made everything work.

Sorry for wasting all your time. Thanks!

**Comment by BrianAllred** [comment]
I'm the maintainer for the Arch package. Admittedly, I haven't been keeping up with issues specific to Arch and Arch-based distros as well as I should. I'll add nss-mdns as a dependency and also include instructions on how to configure it.
