### ISSUE TITLE
Feature Request: Scrolling in the lyrics to change volume

### ISSUE THREAD

**Issue by berryelectronics** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1677]
So that you dont have to go out of the lyrics.

Plus maybe that you cant select the lyrics, because if you accidentally select them you  are directly thrown out

**Comment by MarshallOfSound** [comment]
@berryelectronics This doesn't really much sense as scrolling currently allows you to scroll the actual lyrics.  The issue brought up when making an option to scroll to change volume in the mini player is relevant here.

As a user when I see a wall of text I think I can scroll it, the default in GPMDP is to auto scroll, which means if users attempted to scroll it their volume would sky rocket and users would be **quite** annoyed 👍 

Closing this out as wontfix

**Comment by berryelectronics** [comment]
didnt noticed, probably because the lyrics i saw wasnt long enough lol. 
What about control+Scroll? Doubt you would think that you would have to press control to scroll through them

**Comment by MarshallOfSound** [comment]
Control+Scroll standard is zooming so again not expected behaviour
