### ISSUE TITLE
Executable filename format incompatible with Windows Firewall

### ISSUE THREAD

**Issue by jletria** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1678]
**OS:**
Windows 10 (I'm sure it applies to previous versions too)

**Issue Descriptions:**
While using Windows Firewall, it's not possible to add a firewall rule regarding the application main exe file due to the filename containing the %20 character. I realize this is a Windows Firewall problem more than it is yours, but since we all know Microsoft isn't fixing this any time soon, I was hoping you guys could provide a workaround. There's also the issue of the EXE path changing with each update, but I can get around that. The character issue though, is a complete showstopper. 
This computer has outbound connections blocked by default, and I won't be able to grant internet access to your application unless I'm able to add a rule to the firewall.
I cannot disable the Windows Firewall on this computer, and it's completely preventing me to use your software, which is a terrible shame.

**Steps to Reproduce:**
Just try to create a Windows Firewall rule regarding Google%20Play%20Music%20Desktop%20Player.exe

Thank you guys.

**Comment by MarshallOfSound** [comment]
The file naming issue is a known issue and is annoying (windows is sooooo clever.....)

There is an upstream fix available in `Squirrel.Windows` that I am working on making compatible with our releases, it is a long and heavy process.

In the meantime there are two workarounds.

1. Do what GPMDP attempts to do by default, just open the port and ignore what executable is attempting to use it
2. Rename the executable manually and launch it once to update all shortcuts.  Once renamed and launched GPMDP will attempt to auto-fix all shortcuts it can find and point it at the new `exe` name.
