### ISSUE TITLE
Chomecast not showing friendly names, but device numbers.

### ISSUE THREAD

**Issue by exemmer** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1681]
Windows 10 

All my Chromecast devices (and groups) aren't being shown with their names, but some internal device numbers (and duplications):

(however, they do still seem to work!)

![image](https://cloud.githubusercontent.com/assets/9574727/18815550/4d607fb2-832d-11e6-8974-2436325e542f.png)

Here's the list in Chrome:

![image](https://cloud.githubusercontent.com/assets/9574727/18815561/7a80056c-832d-11e6-9cd2-a016cdb4be99.png)

**Comment by jostrander** [comment]
I have a feeling this is an issue with the underlying electron-chromecast library we built, we'll have to look into it and see what's been updated.

**Comment by MarshallOfSound** [comment]
Hmmmm, do you see this on your machine @jostrander ?  I still have proper device names appearing on mine

@exemmer Do you have Bonjour installed on your machine?

**Comment by exemmer** [comment]
Bonjour? Nope. Don't do Apple;)

**Comment by MarshallOfSound** [comment]
@exemmer Please install Bonjour print services and restart.  The names should be resolved then

**Comment by exemmer** [comment]
Install an Apple product to make a Google product work? <irony>

**Comment by jostrander** [comment]
It's almost as if Google uses existing technology instead of reinventing the wheel...

**Comment by MarshallOfSound** [comment]
Although bonjour is apple, it is the cross platform standard for MDNS.  Even Chrome implements a version of Bonjour

**Comment by exemmer** [comment]
Now that's it ironic, Alanis..

**Comment by aetha** [comment]
I'm getting this bug too. I suspect it's because I opted into the Chromecast preview firmware.

**Comment by jostrander** [comment]
I'll have to get one of my three casts joined into that so I can test this out.

**Comment by jostrander** [comment]
Fixed up stream, @MarshallOfSound can we add this to a minor future release?

**Comment by MarshallOfSound** [comment]
This will go out with `v4`

**Comment by adambregenzer** [comment]
I'm on OSX and v4 of the app and still seeing this.
