### ISSUE TITLE
Program would sometimes Freeze?

### ISSUE THREAD

**Issue by Agash28** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1682]
Hello, I've noticed that the program often freezes on the Windows version when I pick a new song or type in a song to search. Didn't have this problem on Linux though, what could be the problem? Could it be that I'm not using Flash player? Thanks.

**Comment by MarshallOfSound** [comment]
> Could it be that I'm not using Flash player?

Flash player is not, and will never be required

As for the freezing, it is probably a GPU bug which will be resolved next release as I am disabling hardware acceleration across the board.
