### ISSUE TITLE
Feature Request: Basic UI

### ISSUE THREAD

**Issue by mnsr** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1684]
I use this app all the time. It's great overall. But i think it's let down by google's ghastly mobile centric UI.

It'd be great if this app had a 'basic' version. ie, no images, huge icons, etc, but just a list of your songs and a sidebar with your playlists/other options.

**Comment by MarshallOfSound** [comment]
There is adjusting the UI and then attempting to recreate the UI

Adjustments are easy, but the overhaul you want it simply not possible.  If you want to make it slightly more minimal you can use the custom CSS feature to customize the layout yourself
