### ISSUE TITLE
Hiding in tray doesn't work in Cinnamon DE (Linux Mint 18)

### ISSUE THREAD

**Issue by susancalavera** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1686]
**OS:**
Linux Mint 18 (Cinnamon desktop)
**Issue Descriptions:**
Hiding in tray doesn't work at all - player stays both in the tray and the applications panel.
**Steps to Reproduce:**
I think it's a Cinnamon desktop related issue - tried to install XFCE desktop and there it works fine (but I use Cinnamon primarily).

**Comment by MarshallOfSound** [comment]
> I think it's a Cinnamon desktop related issue

It is, and there is nothing we can do about it.  You need to get cinnamon to fix it 👍
