### ISSUE TITLE
Updating GPMDP breaks shortcuts

### ISSUE THREAD

**Issue by xdpirate** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1687]
I have GPMDP pinned to the start menu. Every time GPMDP is updated, it breaks that shortcut and its icon along with any and all other references to it not updated by the installer/updater, because the install location (AppData\Local\GPMDP_3\ **app-3.6.0**) changes for every new version that is installed.

Desirable and commonly used behaviour would be to install to the same folder every time, there is no reason to tag the install folder with the application version, neither is there a reason to keep two or more separate versions installed. 

Admittedly, I haven't looked at the code, so I don't know how everything is set up. So if for some reason it's undesirable or not possible to have a static install location, at least place an executable in \GPMDP_3 that always launches the newest installed version. Shuffling executable locations around for every update doesn't make much sense.

Aside from that, GPMDP is a great piece of software that I use every day. Thank you! :smile: 

(Windows 7 x64)

**Comment by MarshallOfSound** [comment]
@xdpirate 

> neither is there a reason to keep two or more separate versions installed.

There is actually a very good reason to keep the last version installed when updating, basically it comes down to the entire update methodology that Squirrel.Windows uses.

> at least place an executable in \GPMDP_3 that always launches the newest installed version. 

There is one, that's how all of our shortcuts work.  It's called `Update.exe`, if you setup your shortcut to have the following target

```bash
Update.exe --processStart "Goolge%20Play%20Music%20Desktop%20Player.exe"
```

It should launch the latest version automatically.

> I have GPMDP pinned to the start menu.

Darn, we have code that automatically fixes peoples shortcuts if they are in any of the following places
* Taskbar
* Desktop
* Start Menu

However, I guess being "pinned" to the start menu places the shortcut in a different folder.  I'll find out what that folder is and add it to our [Shortcut Manager](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/main/utils/_shortcutManager.js)

**Comment by xdpirate** [comment]
>There is one, that's how all of our shortcuts work. It's called Update.exe, if you setup your shortcut to have the following target
I wasn't aware that the update program could do that, thank you! :+1: :smile: 

Start menu pinned items location (on Win 7, at least), is 
`AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\StartMenu` :grinning:

**Comment by christianbearslyclark** [comment]
... as an daily User with the most awesome app,  I just Deleted the Update exe file so I may use the 3.5.0 version. 

The 3.6.0 version still have Sll Black screen.
