### ISSUE TITLE
Suggestion, Not BUG

### ISSUE THREAD

**Issue by mattspew** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1695]
Not a bug, just a suggestions, and a very small one.

Please include the app version number in either the installer file name or somewhere inside the app.

**Comment by MarshallOfSound** [comment]
You can see the version in different ways depending on the platform

#### macOS
Use the standard `about` menu

#### Windows
Tray Menu -> Help -> About

#### Linux
Same as windows, or use the `--version` arg from the command line
