### ISSUE TITLE
Can't install/update since updated to Windows 10 1607; broken permissions.

### ISSUE THREAD

**Issue by mattspew** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1696]
OS: Windows 10 Pro 1607 "Anniversary Update"
Issue: Install/update fails, even with "Run as Admin".

Log file attached
[SquirrelSetup.txt](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/497104/SquirrelSetup.txt)

**Comment by MarshallOfSound** [comment]
> Access to the path 'resources' is denied.

This is your anti virus getting in the way, normally running as admin gets around this issue but you might have to disable A/V during install

**Comment by mattspew** [comment]
Stupid AV, snoozing fixed the issue. Thanks for the fast response.
