### ISSUE TITLE
Keyboard shortcut issues with mini player.

### ISSUE THREAD

**Issue by MTRougeau** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#17]
Seems like the mini player does not like to skip more than 1 or 2 songs using the arrow keys. Regular window does not have this issue. Also, the spacebar does not pause tracks in the mini player like it does in the regular window. Instead, spacebar makes the mini player revert back to the standard window.

**Comment by MarshallOfSound** [comment]
The arrow key issue appears to be due to the song change notification stealing focus and the web app not reveiving the keyboard input until the alert has disappeared.

Looking more into the spacebar issue now

**Comment by MarshallOfSound** [comment]
- [ ] Stop the notification stealing focus
- [ ] Give it focus on deactiviation
- [ ] Blur the mini player button on click
