### ISSUE TITLE
Feature Request: Support for multiple services

### ISSUE THREAD

**Issue by Dazzel** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1701]
Yeah, I know this is an GPM player and supporting other streaming services like Soundcloud, Spotify could be an huge amount of work.

Besides that it would be really great to have ONE piece of software which can be used for all those services instead relying on their shitty software or using the browser for playing music.

**Comment by MarshallOfSound** [comment]
> Yeah, I know this is an GPM player and supporting other streaming services like Soundcloud, Spotify could be an huge amount of work.

You hit the nail on the head right there, it is a lot of effort and code maintenance supporting a single service.  There is no way we will support anything else.

To put it into context to support Google Play Music we need the following
* An abstraction library to control GPM `gmusic.js`
* An abstraction library to control the UI of GPM `gmusic-ui.js`
* A mini player transformation library `gmusic-mini-player.js`
* A theming library `gmusic-theme.js`
* All the code that hooks those libraries together.

To support another service we would need to not only write code to allow service switching or similar, we would need to write those modules (with identical API's) for any service we wanted to add.
