### ISSUE TITLE
Desktop Settings And Media Keys Not Communicating With Player

### ISSUE THREAD

**Issue by timmyleahy** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1705]
**OS:**
macOS 10.11.6

**Issue Descriptions:**
I noticed on a recent update that my dark theme had stopped working in the player window. I also noticed that my in-app link to desktop settings was gone and the media keys stopped working. Then I noticed that the GPMDP menu on the menu bar still had a Desktop Settings link. It seems that any function in that menu bar (aside from Quit) has no effect on the Player.

There was a recent security update to all Macs at my company and while GPMDP has been whitelisted and the player works fine I feel like this may be the root cause (I see the same behavior on both my corporate Mac Pro and Macbook Pro). I have not checked this on my personal hardware but I will when I get a chance. If this is a security problem I'd like to know how I can diagnose it.

**Steps to Reproduce:**

* Uninstall existing application
* Deleting all files found by running: mdfind -name "Google Player Music Desktop Player"
* Download latest version of GMPDP and install
* Launch application and authenticate
* Go to Menu Bar->GPMDP->Desktop Settings
* Select Custom Theme and toggle light/dark or change color. The only affected area will be the application title bar.

**Comment by timmyleahy** [comment]
Sample of changing desktop settings with only title bar changes to Player window:

![gpmdp1](https://cloud.githubusercontent.com/assets/1167725/18966690/068ba690-8637-11e6-8271-45d964ab37e1.png)
![gpmdp2](https://cloud.githubusercontent.com/assets/1167725/18966693/0b0b6a98-8637-11e6-8b1e-20073c929d1b.png)

**Comment by MarshallOfSound** [comment]
@timmyleahy Looks like an error is being thrown somewhere in our injected JS that is causing some issues.

Can you screenshot the devtools console and upload it here.  You can access the required devtools by doing the following

1. Open GPMDP
2. Use the shortcut Command + Shift + G
3. Type in "DEV_MODE" and click "Let's Go"
4. Open GPMDP
5. Use the dev tools shortcut "Command + Alt + I"
6. Typing in to the console `openGPMDevTools()` and hit enter
7.  Screenshot the devtools console that just appeared

**Comment by timmyleahy** [comment]
![screen shot 2016-09-29 at 12 41 28 pm 2](https://cloud.githubusercontent.com/assets/1167725/18969461/2512df56-8642-11e6-90eb-9d740d8b0e31.png)

**Comment by MarshallOfSound** [comment]
@timmyleahy Looks like GPM have pushed out an update of some kind and your progress bar isn't visible.  Do you know why that is?

Like when I load google play music in GPMDP or in the browser the progress bar is visible at the bottom (and the play button is visible in the button middle but greyed out).  Your screenshot does not have this, can you confirm if that is what it looks like in Chrome aswell.

/cc @jostrander @chrismou Stay on alert, google might be pushing out some breaking updates

**Comment by jostrander** [comment]
I still have the player controls at the bottom in GPM.

**Comment by timmyleahy** [comment]
The controls are there but only after I play a song. It's the same in both the browser and GPMDP.
![screen shot 2016-09-29 at 3 53 44 pm](https://cloud.githubusercontent.com/assets/1167725/18975183/28b2342a-865d-11e6-9bb2-041ede2fd500.png)
![screen shot 2016-09-29 at 3 53 44 pm 2](https://cloud.githubusercontent.com/assets/1167725/18975184/28b53198-865d-11e6-9c94-8ac8d7517636.png)

**Comment by MarshallOfSound** [comment]
@timmyleahy Woah, wtf is that.  That is either one hell of a UI bug or one hell of a UI change

**Comment by jostrander** [comment]
That is one hell of a UI change @MarshallOfSound. This will be a fun upgrade.

**Comment by jostrander** [comment]
What's in the footer there? music_frontend_caterpie_2016...etc. Are you using a chrome extension?

**Comment by timmyleahy** [comment]
I'm not using a chrome extension. Sorry, had to take down the screenshots of the app. Need to check something.

**Comment by MarshallOfSound** [comment]
@timmyleahy Can you confirm the status of this, it looks like you are getting an internal preview of GPM at Google which includes these changes.  Can you message me on Gitter so we can perhaps clean this issue up and get a clear idea what is going on.

**Comment by timmyleahy** [comment]
Hi, sorry, yes, that's correct, I seem to have been using an preview release without knowing it. I need to make sure I'm allowed to talk about stuff like this, waiting on some feedback from legal.

**Comment by chrismou** [comment]
Ooof, this is going to be fun.

Incidently, I would have replied earlier, but I've been googling "how to get on the google music beta" all morning with no luck :joy:

**Comment by chrismou** [comment]
Also paging @jacobwgillespie so he's got some background for if all the desktop apps suddenly explode one day in the near future

**Comment by Lokatana** [comment]
Not sure if this is related, but I noticed tonight that though i've sent my audio to a different audio device, it's still playing out the windows default audio device, which is messing up my ability to do various kinds of mixing.

**Comment by MarshallOfSound** [comment]
@Lokatana Not related, that audio output bug I just picked up today (google made a change somewhere) and has been fixed in 06a1757bd22b2be1642bd6c4588bc0b5785c73af

**Comment by Lokatana** [comment]
Not to familiar with how you do releases... is there a way to get it early (without compiling it at home?), since i see the main release on the website doesn't have the fixes yet?

**Comment by MarshallOfSound** [comment]
@Lokatana The next release probably won't be till `v4` and you can monitor the project progress for `v4` over here --> https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/projects/1

If you want an early build you can normally get them from the CI builds.  All three services provide build artifacts however the tests are currently failing 👍 so no artifacts have been generated for a few days.  I'll try fix the build shortly.

**Comment by MarshallOfSound** [comment]
@timmyleahy Is their any update on this, can you say anything about the version of GPM you were using?

**Comment by timmyleahy** [comment]
Nothing yet, sorry. I seem to have been cleared of leaking stuff by legal but I haven't heard anything back from the Google Play Music team.

**Comment by timmyleahy** [comment]
Okay, just heard back from the Google Play Music team, they've assured me that I'm using the production version of the player. The version info that was in the screen shots is just something they always show internally.

I'm re-adding the screenshot of the devtools console. 
![screen shot 2016-10-06 at 1 16 20 pm 2](https://cloud.githubusercontent.com/assets/1167725/19169000/61ac49f4-8bc7-11e6-8327-28ed5fe85616.png)

**Comment by jebeld17** [comment]
Same thing here
Dell Inspiron 13 5000

**Comment by jostrander** [comment]
Can you produce the same console scree shot as above?

**Comment by MarshallOfSound** [comment]
@timmyleahy Sorry, missed this thread, I don't see how that can be a production version.  The player UI is completely different.  I explored around reddit and the web looking for reports of this UI change and no one has said anything.  Pretty sure you are on some kind of preview channel.

**Comment by timmyleahy** [comment]
No worries. I think you're right. I just jumped off our corporate network and on to the guest network and, ta da, everything is working again.

I have a feeling that the internal group here might be mistaken.

**Comment by MarshallOfSound** [comment]
@timmyleahy Oh how much I would love to get on that network 😆

**Comment by tbraeutigam** [comment]
Hi all,

Facing a similar issue -- media keys not working, not able to access desktop settings & the minimize, maximize, close buttons don't work -- on a windows 8.1 machine (with gpmdp 4.0.1) that's definitely not on the internal google network.

Also confirmed that looks wise at least it's the same version of the webplayer that works fine on my linux (ubuntu 16.04) machine.

I can't even provide a console screenshot as I can't enter DEV_MODE as described above. While on my linux machine ctrl+shift+g works just fine to get the prompt, it doesn't seem to work on that workstation.

Tried the following:
 * Uninstall/Reinstall
 * Reboot of the machine
 * Closing all chrome & other possibly related processes and relaunching gpmdp

None of the above brought any success.

Is there anyway to get a debug bundle/the console without going through the ctrl+shift+g method mentioned above?

**Comment by MarshallOfSound** [comment]
@tbraeutigam If you locate the executable you can launch it from command line with the `--dev` argument it will launch in dev mode

**Comment by wolfblitzer** [comment]
@timmyleahy I'm on campus too- have you found a way to get the mediakeys to work while on the corp wifi network?

**Comment by jostrander** [comment]
@wolfblitzer, here's the issue, you are on a private version of GPM in which our (unofficial) API library doesn't work with. It makes assertions that certain elements in the page exist in order to make sure the functionality of the API will work correctly, and when those assertions fail GPMDP fails to load future modules, such as media keys, themes, etc. 

Since we don't have access to the version you are using and neither does the general public, we'd have a hard time implementing changes upstream that would fix this for you.

**Comment by MarshallOfSound** [comment]
@wolfblitzer As a work around I feel if you opened GPMDP on the guest network that @timmyleahy mentions and then switch back to the corporate network everything would be fine as it would have loaded the public version of GPM.

**Comment by tbraeutigam** [comment]
@MarshallOfSound 

Thanks for the tip. Tried starting it with --dev, but still didn't provide me with the console when trying to use the keyboard shortcut for it (nor could I find a menu that would've popped it up, unlike on linux).

Found an interesting error on startup though that might explain this:
![gmusic dev startup](https://cloud.githubusercontent.com/assets/6705705/19469105/bbfdadf0-9511-11e6-8ae6-83d5cd77970c.PNG)

**Comment by MarshallOfSound** [comment]
@tbraeutigam That looks like you're anti virus deleted / prevented access to my keyboard hook module.

At least, that's the only reason I can come up with for it to "not be there".

I was wondering who the unfortunate person was when I saw this error come through on Sentry 😆 

The best I can suggest, is uninstalling GPMDP.  Whitelisting it in your A/V (or turning it off completely), install GPMDP and launch it and then enable your AV again.  Hopefully that will let the module through

**Comment by tbraeutigam** [comment]
@MarshallOfSound Alright, worth giving a try. Was this module not in 3.4.3? 3.4.3 is working just fine on the same machine.

**Comment by MarshallOfSound** [comment]
@tbraeutigam It was but in a different location and it was a different version

**Comment by timmyleahy** [comment]
@wolfblitzer The only way I've been able to work around it and keep the media keys working is to switch back and forth between networks and keep GPMDP up and running with the public version.

**Comment by wolfblitzer** [comment]
@timmyleahy @MarshallOfSound Yeah, that works, thanks guys!
@jostrander I totally get it- no worries, glad we figured out why it was happening, I was going a little crazy closing/restarting/enabling/disabling media keys/hot keys in Chrome and stuff!

**Comment by Devo7v** [comment]
I'm having the exact same issues @tbraeutigam mentioned, media keys don't work, desktop settings won't open, maximize/minimize/close buttons do not work and I cannot access the DEV mode using the shortcut.  I've provided  the debug logs using the command line parameter you mentioned above.  I'm assuming it's an antivirus issue since my company just made a bunch of changes to our a/v policies, so I won't be able to make any changes/whitelist anything.  The frustrating part is that everything was working perfectly with 3.6.3, but I can't stay on that version because GPMDP automatically updates itself.  Any help would be appreciated.

![gpmdp error](https://cloud.githubusercontent.com/assets/15945504/19648146/3265993c-99cf-11e6-84e7-252e49a069cd.png)

**Comment by jostrander** [comment]
@Devo7v That looks like your AV is blocking access to the app data folders for this app. If you can't get your company to whitelist this program in your AV I don't believe there's much we can do to help you. However it is an entirely different issue than the issue in this thread.

**Comment by jostrander** [comment]
Closing this as there's nothing we can do for the original issue as well except wait it out until changes get released.

**Comment by timmyleahy** [comment]
Hey @wolfblitzer, short update on this. The newest version of the GPMDP and the internal version we have access to seems to be working fine with the media keys now. I don't have to do the network switcharoo anymore.

**Comment by wolfblitzer** [comment]
Same! Very happy :) haha
