### ISSUE TITLE
"Your account has changed, please refresh"

### ISSUE THREAD

**Issue by lhclack** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1706]
**OS:**

**Issue Descriptions:**

I don't think I've used the player yet today, so not sure if there has been an update since I last used the player (yesterday) but upon opening, after about 10-15 seconds, I get a pop up that says "Your account has changed, please refresh the page to continue" with a refresh button. No matter how many times I refresh, it keeps popping up. I've rebooted my computer and logged out of my google account and back in. Still pops up. Has not interfered with music play and if I click off the pop up it seems to go away for the most part?

**Steps to Reproduce:**

Logging in

**Comment by MarshallOfSound** [comment]
@lhclack Sounds like an issue on Google's side of things.  Just wait it out and hopefully they will fix it soon 👍
