### ISSUE TITLE
Changing Audio Device not working

### ISSUE THREAD

**Issue by GarettM** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1707]
**OS:** Windows 10 Pro

**Issue Descriptions:**  Cannot change audio device in desktop settings.  Always on default device.

**Steps to Reproduce:**   

- Go to "Desktop Settings"
- Click on "Audio" Tab
- Choose Audio Device

**Comment by MarshallOfSound** [comment]
This will only occur if we fail to change the audio device at the driver level.  This normally means an application has requested exclusive access to the device.

I just confirmed my audio output selector works still so it's highly likely this is the case on your machine

**Comment by jostrander** [comment]
Mine works as well, just to confirm, use it quite regularly.

**Comment by GarettM** [comment]
Alright, not sure then.  Tested it with other applications prior and it works fine.  Only application I'm having an issue with is Google Play Music Desktop Player.
