### ISSUE TITLE
Lag and CPU Usage

### ISSUE THREAD

**Issue by joewidd** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1712]
**OS: Windows 10 Anniversary Update**

**Issue Descriptions: So The issue I'm running into is the amount of CPU usage this app hogs. I usually enjoy listening to music while I game, but it takes a toll so I've been having to close the app. I don't know if this is specific to me or if other people have run into this, but it's a pain. It's also pretty slow when I go from an artist page or album page back to the Listen Now page.**

**Steps to Reproduce: Launching the app and watching my CPU usage almost max out. Clicking on Listen Now and waiting a good amount of time before it reacts.**

**Comment by sahenders** [comment]
Can confirm the lag and CPU issues after upgrading to Anniversary Update.  Media keys are almost unusable.

**Comment by MarshallOfSound** [comment]
I can't reproduce this on either Windows 10 pre anniversary update or with the anniversary update.

If I had to guess there is something defunct in your cache that is causing Chromium to do something stupid.  I would reccomend a completely clean install.

1. Uninstall from Control Panel
2. Delete `%APPDATA%/Google Play Music Desktop Player`
3. Delete `%LOCALAPPDATA%/GPMDP_3`
4. Download latest installer
5. Run installer with all fingers crossed 👍

**Comment by sahenders** [comment]
I ran through the instructions, but no luck.

After a little more testing, it looks like the app starts to lag when desktop notifications are presented.  When I disable notifications the problem clears up.

**Comment by MarshallOfSound** [comment]
@sahenders That's interesting, it's google code that does the JS side of the notifications so I'm not sure what I can do about it.  I'll keep trying to reproduce 👍

**Comment by jebeld17** [comment]
I can confirm, as well.
The app takes far too long to even open.

I'm attaching some files below:
MsSystem32 Report:
[msinfo32.txt](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/504418/msinfo32.txt)

Problem Steps Recorder Log:
[GPM.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/504419/GPM.zip)

**Comment by joewidd** [comment]
When I get a chance I'll try the instructions you provided and get back to you.

**Comment by joewidd** [comment]
Alright so I tried the above steps and it didn't clear up the issue.

**Comment by MarshallOfSound** [comment]
@joewidd Can you test @sahenders notification diagnosis.  I.e. Disable desktop notifications and see if the CPU usage lowers.

@jebeld17 Your issue appears to be separate from the other issues mentioned here, can you try relaunching in development mode and screenshotting the console errors.

To launch in DEV MODE
1. Open GPMDP
2. Perform the shortcut "Control + Shift + G"
3. Type in "DEV_MODE"
4. Click "Let's Go"
5. Click OK
6. Open GPMDP
7. Perform the shortcut "Control + Shift + I"
8. Open the "console" tab
9. Screenshot the errors present there and post it here.

**Comment by joewidd** [comment]
@MarshallOfSound what do you mean desktop notifications? For the app itself or just notifications in general?

**Comment by MarshallOfSound** [comment]
@joewidd From the app itself

**Comment by joewidd** [comment]
Gotcha. Will try later and report back.

**Comment by joewidd** [comment]
@MarshallOfSound I don't see where to disable desktop notifications for the app.

**Comment by MarshallOfSound** [comment]
@joewidd In the normal GPM settings, not desktop settings.

**Comment by joewidd** [comment]
@MarshallOfSound Okay so they've been off since I've had the app, so that has nothing to do with the performance.

**Comment by MarshallOfSound** [comment]
@joewidd Can you run a CPU profile of the application for about 20 second while the CPU usage is high.

To get to the profiling tools you need to open the dev tools.

1. Open GPMDP
2. Use the shortcut "Control + Shift + G"
3. Type in "DEV_MODE"
4. Hit "Let's Go"
5. Use the shortcut "Control + Shift + I"
6. Type in the console `openGPMDevTools()`
7. In the new dev tools window navigate to "Profiles"
8. Click "start" when you want to start the profile

Then upload the profile file here so I can examine it :+1:

**Comment by joewidd** [comment]
Will do!

**Comment by joewidd** [comment]
Here's the link to the file, it wouldn't let me upload it straight to GitHub. @MarshallOfSound 
https://drive.google.com/file/d/0B1sZhc17QjFdajNNZ1hPc0ZnRWM/view?usp=sharing

**Comment by MarshallOfSound** [comment]
@joewidd It looks like you missed out step 6

That CPU profile was from the main dev tools not the GPM dev tools

**Comment by joewidd** [comment]
I did all the steps, that's just what came up for me. I can try it again though.

**Comment by joewidd** [comment]
https://drive.google.com/file/d/0B1sZhc17QjFdR0R0RXN2MU9FT28/view?usp=sharing

**Comment by MarshallOfSound** [comment]
@joewidd Looking at those CPU snapshots you provided I can see tha tsome of googles code (in particular something called `normalize` and `c` is accounting for upwards of 70% of GPMDP's CPU consumption.

When comparing these to by numbers on a variety of platforms I see my code consuming the majority of the CPU usage.

Based on this it looks like you have hit some kind of internal GPM bug, the CPU profile actually reports the top CPU user as being the result of an unoptimized `try {} catch {}` statement.  You are probably somehow in an infinite error loop inside GPM's JS code.

Unfortunately I have no control over this so I would reccomend reporting the high CPU usage to Google through either the `chrome` or `play music` support channels.

**Comment by joewidd** [comment]
Gotcha, well thanks for all the help.
