### ISSUE TITLE
3.6.0 blank screen or crash on launch (3.5.0 still works)

### ISSUE THREAD

**Issue by brendonrapp** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1713]
**OS:** Windows 10

**Issue Descriptions:** Since updating to 3.6.0, my client launches and ends up at either a blank black screen (after the spinner animation stops and disappears), or crashes entirely. The 3.5.0 version is still present alongside 3.6.0, and launching the executable from the 3.5.0 folder instead provides a working client.

(Side note: your bug template says to attach DEBUG information ZIP and provides a FAQ URL for instructions, but the word "debug" appears nowhere at that URL)

**Steps to Reproduce:** Launch 3.6.0 client, wait for spinner animation to cease, observe either crash or blank window.

**Comment by MarshallOfSound** [comment]
Known issue that I am tracking upstream.  It's a memory thing, possibly language specific.  Closing as upstream but what is your system language?

**Comment by brendonrapp** [comment]
English (US)

**Comment by MarshallOfSound** [comment]
@brendonrapp Can you try the most recent CI build from AppVeyor?

**Comment by brendonrapp** [comment]
I installed the [most recent successful build](https://ci.appveyor.com/project/MarshallOfSound/google-play-music-desktop-player-unofficial/build/1.0.1321/artifacts), and there is a slight change of behavior, in that I now get the "Loading Music Library" loading bar after the spinner animation goes away, but after that, I get the same behavior as before: either a black screen or a full crash.
