### ISSUE TITLE
Audio Device selector doesn't seem to be working.

### ISSUE THREAD

**Issue by rmthamer** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1714]
**OS:** Windows 7 Pro SP 1

**Issue Descriptions:** It appears that the audio device selector no longer works, as the audio is only playing from the default device.  I'm not sure if this is related to issue #1705, as this is a different OS and the menus all appear to be working properly.

If you change the default device via window settings, the music will play from the newly selected default device regardless of what is selected  in Desktop Settings.

**Steps to Reproduce:**
1) Open GMDP.
2) Play music on the default device and notice the music is playing.
3) Select a new audio device from either Desktop Settings or from the taskbar icon.
4) The music will continue to play from the Default device.

**Comment by MarshallOfSound** [comment]
Fixed in 06a1757bd22b2be1642bd6c4588bc0b5785c73af

Will be out in the next release
