### ISSUE TITLE
Small window widths not handled well

### ISSUE THREAD

**Issue by semininja** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1716]
**OS:**
- Windows 10, probably all

**Issue Descriptions:**
Current media bar handles narrow window sizes poorly:
- position of right-side controls (volume, chromecast, current playlist) don't compress toward play/pause/skip buttons completely - large padding remains even as buttons are pushed off-screen
- Current Playlist button disappears as window size is decreased, but chromecast button stays until pushed off-screen (reverse would be preferred, but no disappearing controls would be better)
- This also occurs with GPM itself, unfortunately.

**Steps to Reproduce:**
Shrink the window width.

**Comment by MarshallOfSound** [comment]
This is due to how Google's GPM UI works at the lowest level.  Their entire UI design is built around certain minimum widths so unless they make their UI more mobile / small screen friendly there is nothing I can do here.
