### ISSUE TITLE
Cosmetic: Playing song in lists surrounded by visual glitches

### ISSUE THREAD

**Issue by nermolov** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1719]
**OS:** macOS El Capitan

**Issue Descriptions:** Currently playing song element in albums/other lists is surrounded by UI glitches while in Dark Theme.

![screen shot 2016-10-03 at 1 27 43 pm](https://cloud.githubusercontent.com/assets/6175137/19048862/a70ab3ca-896d-11e6-8d95-831b979a4d19.png)

**Steps to Reproduce:** Install latest release, switch to Dark Theme, go to album or playlist and start playing a song.

**Comment by MarshallOfSound** [comment]
This was a glitch that persisted after an update for only a few users (couple of thousand I think)

> Install latest release, switch to Dark Theme, go to album or playlist and start playing a song.

If you actually do that now the glitch will go away as the update file was fixed.
