### ISSUE TITLE
Code Signing Questions

### ISSUE THREAD

**Issue by wjk** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#172]
I just stumbled onto your program via and I must say, I am impressed. I noticed while browsing your source code that you sign your executables using a VeriSign key. Good for you! My question is, how did you arrange that? Conventional wisdom in Windows programming is that commercial code signing certificates are ungodly expensive to acquire. If there is some program or offer you utilized to get a discount on a code signing certificate, would you mind sharing what it is? (You can email me at the address listed on my GitHub profile if you don't want to share it publicly.)

I also noticed while browsing some of the virus-scan false-positive issues (#131, #11) that you mentioned signing your program with a self-signed certificate at one point. What has been your experience with that? As I understand it, Windows won't honor self-signed certificates, and may in fact treat code signed with such a certificate worse than code that isn't signed at all. However, if Windows (and virus scanners, and SmartScreen) treats self-signed programs decently, I may start signing my programs with a self-signed cert for extra security and tamper protection (at least until I can afford a commercial cert, of course).

**Comment by MarshallOfSound** [comment]
Self signed certificates as far as I am aware can still accumulate trust, but it takes a lot longer than a pre verified cert.  I managed to acquire a code signing cert for "Open Source" developers from `http://www.certum.eu`.  Great place, its a bit hard to navigate as the site is in polish but it was like $10 for a cert so I'll go through the pain :+1:
