### ISSUE TITLE
Set pulseaudio stream name

### ISSUE THREAD

**Issue by adnidor** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1720]
In pavucontrol the stream from gpmdp is listed as Chromium. Because of this, I can't permanently move Chromium (e.g. Youtube) audio and Google Play audio to different sinks.

It would be nice if the stream had a more unique name.

**Comment by jostrander** [comment]
I'm not sure that it can be set to something more unique, unless electron exposes a way to do this, but I have a feeling it may be much deeper than that.

**Comment by MarshallOfSound** [comment]
Raised upstream to see what people have to say.

https://github.com/electron/electron/issues/7470

Closing this out as an upstream issue.  Please track progress on the linked issue
