### ISSUE TITLE
Unable to route sound to other audio devices

### ISSUE THREAD

**Issue by trasee** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1722]
**OS:** Windows 10 Home 64-bit (Version 1607)

**Issue Descriptions:** Music is not routing to the selected audio driver, but always routing to my default driver. It doesn't matter which audio device that I choose, it always goes to the default. This was working properly up until a week ago. I tried a clean install of the latest version, deleting the files in Local and Roaming and the results were the same. Audio continued to come from my default device, not the selected audio driver.

**Steps to Reproduce:** Select an alternate audio device from the default audio and play music.

**Comment by MarshallOfSound** [comment]
Fixed in 06a1757bd22b2be1642bd6c4588bc0b5785c73af
