### ISSUE TITLE
Player stuck in "setting up google play music"

### ISSUE THREAD

**Issue by shankru5** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1723]
I am stuck at "setting up google play music" stage. I saw the FAQ and saw that it had asked me to run with --disable-gpu option. But still couldn't go past that stage. Please have a look at the attached screenshot which has both system info and issue reproduced. Let me know if I am missing something.

Linux mint 18 cinnamon 64 bit. 
![screenshot from 2016-10-04 08-15-50](https://cloud.githubusercontent.com/assets/16060623/19061018/d24a01f6-8a0a-11e6-8635-a8b21ac75067.png)

![screenshot from 2016-10-04 08-10-51](https://cloud.githubusercontent.com/assets/16060623/19060996/96f7860a-8a0a-11e6-9109-a1bc28c785d4.png)

**OS:**

**Issue Descriptions:**

**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment]
See #706 you clicked a bad button :laughing: 

Delete your settings file, setup GPM in a browser and then launch the app.  We don't support uploading music and such from the app so you will need to set up your collection from a browser first anyway.

**Comment by shankru5** [comment]
Thanks for the info. Will try and let you know.

**Comment by shankru5** [comment]
Hi,

How do i delete the settings file ? Where can i find it ?
