### ISSUE TITLE
Win 10 Computer won't sleep while app is open

### ISSUE THREAD

**Issue by kbrohkahn** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1724]
**OS:**
Windows 10 x64

**Issue Descriptions:**
It looks like the app is creating multiple wake locks which prevent the computer from sleeping. The first is for playing media (which is only on when music is playing, the media playing) the command 'powercfg -request' returns

[PROCESS] \Device\HarddiskVolume1\Users\kbkrunner\AppData\Local\GPMDP_3\app-3.6.0\Google%20Play%20Music%20Desktop%20Player.exe
Playing audio

which makes sense, but the second is 

[DRIVER] Intel(R) Display Audio (HDAUDIO\FUNC_01&VEN_8086&DEV_2806&SUBSYS_80860101&REV_1000\4&1d2c9eed&0&0301)
An audio stream is currently in use.

which is always on, even when music is paused, until I fully quit the app. Here are some screenshots:

-Open and playing (2 power requests): 
![image](https://cloud.githubusercontent.com/assets/12955305/19061117/fd0e42a2-89bb-11e6-8fa8-f8b9ced2b4a1.png)

-Open, not playing (1 power request):
![image](https://cloud.githubusercontent.com/assets/12955305/19061145/29eba6ac-89bc-11e6-94ee-98c560064e17.png)

-Closed, no power requests, now computer can sleep:
![image](https://cloud.githubusercontent.com/assets/12955305/19061162/4799436c-89bc-11e6-9287-df6974d93f45.png)

**Steps to Reproduce:**

To reproduce this, just open the app in windows 10 and it should keep your computer awake. To see the process that's doing it open command prompt in admin mode and run 'powercfg -requests' it looks like you're locking the audio driver.

**Comment by MarshallOfSound** [comment]
@kbrohkahn Correct me if I'm wrong here.  But the SYSTEM level power request is coming from the audio driver not GPMDP correct?

> [DRIVER] Intel(R) Display Audio (HDAUDIO\FUNC_01&VEN_8086&DEV_2806&SUBSYS_80860101&REV_1000\4&1d2c9eed&0&0301)

To me that indicates that your driver is not releasing the audio stream when it receives an empty stream from Chromium.

This behavior can also be replicated with Chrome and Chromium so I would suggest reporting this as an issue on the Chromium bug tracker so that they can fix it upstream.

**Comment by kbrohkahn** [comment]
Wow thank you, I'm sorry I didn't even think to check the web player for the same issue.
