### ISSUE TITLE
[minor] Adjust Set Alarm to expected behavior

### ISSUE THREAD

**Issue by rgavs** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1727]
**OS:**
 All (_as far as I know_)

**Expected Behavior:**
While setting an alarm, if user changes their mind and presses `<ESC>` or `"Cancel Alarm"`, it does not actually does not cancel.
`"Cancel Alarm"` clears the time field, though I believe it should exit the Alarm popup window.

**Actual:**
Must instead press `"OK"` with the time field empty.

**Steps to Reproduce:**
`Menu -> Alarm -> <ESC> OR "Cancel Alarm"`

**Comment by MarshallOfSound** [comment]
I don't normally accept (or leave open) issues for unreleased code in master.  There is still quite a bit to do RE the alarm the feature.

**Comment by rgavs** [comment]
Ok sure, I've just been pulling from master and building so I didn't realize/haven't exactly been paying attention to actual release schedule
