### ISSUE TITLE
GPMDP does not consistently load correctly when "Automatically launch when I turn my computer on" is checked

### ISSUE THREAD

**Issue by LovedByTheLord** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1731]
**OS:** 
Windows 7

**Issue Descriptions:**
When my computer starts up, GPMDP starts up automatically.  However, more often than not it shows the spinning loading indicator, then shows a white screen with the "Welcome to version X.X.X" popup.  The version number on that popup is the previous version, though, not the most recent version that is installed.  For example, it is showing 3.5.0 when I have 3.6.0 installed.  Once I close that popup, it shows nothing but a white screen.  So I have to close the app and reopen it.  At that point it shows the "Welcome to version X.X.X" popup with the correct version this time (even though it's not the first time I've run that version) and everything loads properly.  Once in a while, it will start automatically without any problems but that is the exception.

**Steps to Reproduce:**
Have the "Automatically launch when I turn my computer on" option enabled.
Start your computer and see if the app loads correctly

**Comment by MarshallOfSound** [comment]
This is a bug that was fixed in `3.6.0`

Unfortunately to apply the fix you have to turn off `auto-launch` and then re-enable it

It's due to how `auto-launch` launches the old version instead of the updated version

**Comment by LovedByTheLord** [comment]
Hi, following your suggestion fixed the issue with the new version dialog popping up.  However, I continue to get a white screen occasionally with the "Automatically launch..." option enabled.  I wonder if it has to do with home fast my internet connects upon startup. 
 
![image](https://cloud.githubusercontent.com/assets/17475836/19598757/3092ee4e-9762-11e6-8bc4-890d6c95c6cd.png)
