### ISSUE TITLE
Can't change sound device - only uses default

### ISSUE THREAD

**Issue by xprs** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1732]
**OS:**
Windows 10 - Update 1607 (Anniversary)

**Issue Descriptions:**
Choice of sound device doesn't do anything, it only uses the default one.

I was afraid that there was something wrong with my desktop, even though i.e Kodi can still use a specific sound device, and so can certain video games that I've tried which include the option.
I checked my laptop that is running the same version of Windows and it had the same issue, so it's not isolated to one computer.

**Steps to Reproduce:**
Attempt to change sound device on the latest version of GPMD in Windows 10.

**Disclaimer:**
I've barely used GitHub and I'm anything but an experienced dev, so please excuse me if I'm not using this right.

**Comment by MarshallOfSound** [comment]
Fixed in https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/commit/06a1757bd22b2be1642bd6c4588bc0b5785c73af

Will be out in the next release

**Comment by xprs** [comment]
Sweet! Cheers, man!
