### ISSUE TITLE
Last.fm signin doesn't work

### ISSUE THREAD

**Issue by matthewdias** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1735]
**OS:** macOS 10.12

**Issue Descriptions:** Clicking the login button doesn't do anything.

**Steps to Reproduce:** Click the last.fm login button

**Comment by MarshallOfSound** [comment]
@matthewdias When did you download the player / when did it last update?

Also are you using a VPN or a proxy?

**Comment by matthewdias** [comment]
I downloaded it quite awhile ago, and don't remember when it last updated, but I checked the version and I have the latest (3.6.0). I am not using a VPN or proxy.

**Comment by MarshallOfSound** [comment]
@matthewdias Can you redownload and see if it works, there was an issue for the first few hundred people who updated.

**Comment by matthewdias** [comment]
That fixed it, thanks.
