### ISSUE TITLE
Feature Request: Add Refresh Shortcut / Menu Button

### ISSUE THREAD

**Issue by Malcolmest** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1738]
Windows 10 Pro

I leave my computer on pretty much all the time to run as a server for several things. I also have GPMDP running in the background most of the time for quick access. I have noticed that if you leave GPMDP running the podcasts section will not update when new podcasts are released. For me to see the newest podcasts I need to shut down the app completely and then re open the app and let it load up again. Sometimes I can press the back button on my mouse a few times and it will refresh but it doesn't work all the time. And sometimes when that does work it will bug out and refresh a couple more times before functioning properly.

**Comment by MarshallOfSound** [comment]
I think just adding a generic reload shortcut (F5 or Control/Command + R) should do the job here
