### ISSUE TITLE
Playback Buttons Vanish When Playback Queue in Focus

### ISSUE THREAD

**Issue by AdmiralAsshat** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1742]
* I have checked that there are no issues with similar or the same content
* I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* I have double checked and can reproduce the issue

## OS:  Fedora 24
`uname -a`
`Linux  4.7.4-200.fc24.x86_64 #1 SMP Thu Sep 15 18:42:09 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

## Symptoms observed:
*  GUI elements will disappear from the playback bar
*  Certain elements will pop in and out on mouse hover, but disappear again when focus is lost
*  Pressing the "hamburger" menu icon to bring the sidebar will briefly pull the sidebar into view, but it will immediately retreat, For the time it is within view, it is blank.

## Steps to Reproduce
1.  Queue an album to play.
2.  While it is playing, open another album in the main program window.
3.  While the album information and tracks are available in the main window, click on the "Open Queue" button in the bottom-right corner to bring up the current playlist.
4.  When both album and playlist are displayed on the screen, move the mouse towards the bottom left of the screen to cause various GUI elements to disappear.

### Screenshot failed to attach. Uploading it [here](http://imgur.com/a/oXxHv) for the time being

**Comment by MarshallOfSound** [comment]
@AdmiralAsshat You appear to be the victim of Google changing some things on their side.  Hopefully they will fix this bug soon.
