### ISSUE TITLE
can't minimize, hide or toggle fullscreen in i3

### ISSUE THREAD

**Issue by scharc** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1743]
**OS:**
Linux scharc-x250 4.4.0-38-generic #57~14.04.1-Ubuntu SMP Tue Sep 6 17:20:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Google Play Music Desktop Player Version: 3.6.0 installed through deb-file

**Issue Descriptions:**
Open GPMDP panel, with or without system windows decorations. Sometimes there is a menu-bar sometimes not... 

when I try to minimize the app, it just toggle the menu-bar. Tried to use every possible shortcut. 

any suggestions?

**Comment by MarshallOfSound** [comment]
> any suggestions?

I no longer have the standard reply for this.  Basically some linux window managers do strange things with tray icon orientated applications.  I'm perfectly happy to accept PR's to improve the situation but I won't be backlogging any issues regarding it.

Without any detail such as the exact messages being sent to the window and the exact action that is / isn't occuring.  There is no more advice I can give 😢

**Comment by SicariusNoctis** [comment]
i3 does not support minimizing windows. (Nor do most other tiling WMs.)

One way to handle this would be a **"minimize to tray on close"** option.
