### ISSUE TITLE
Brazilian Portuguese Encoding

### ISSUE THREAD

**Issue by brunogeronimo** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1745]
**OS:**
Ubuntu 16.04 LTS

**Issue Descriptions:**
When using Ubuntu in Brazilian Portuguese, we have an encoding problem. Every accentued character is being displayed wrongly, like you can see on the image below:
![image](https://cloud.githubusercontent.com/assets/5928885/19225119/03844592-8e6b-11e6-8078-26c2364207a4.png)

**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment]
Fixed in #1736
