### ISSUE TITLE
Steals focus on load

### ISSUE THREAD

**Issue by arkon** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1749]
**OS:**
macOS 10.12

**Issue Descriptions:**
The GPMDP window steals focus away from the active window when it loads.

**Steps to Reproduce:**
1. Launch GPMDP.
2. Shift focus to any other window.
3. GPMDP will steal focus (and come to the top of your window stack) once it's loaded its content (i.e. you see the spinner for about a second, then the GPM contents show up).

**Comment by MarshallOfSound** [comment]
This is intended behvaior as we only ask for focus when GPM has finished loading, if you are in a different window or program the intention is to let you know that the application has finished loading completely.

If I disable this the window will either show when it isn't ready or not show every again 😢

**Comment by arkon** [comment]
Hmm, seems a bit counterintuitive to me. I imagine the user would be aware that the app is loading (since there's the spinner), and would just check if it's done loading at some point if they did shift away to some other program.

**Comment by MarshallOfSound** [comment]
@arkon Hm, I think we are referring to two different issues.  Are you saying the spinner appears and then some time after that we attempt to steal focus?

**Comment by arkon** [comment]
@MarshallOfSound Yup. If you launch the app, you'll see the spinner of course. If I Alt+Tab to a different window (so it appears on top of GPMDP), GPMDP will eventually refocus itself on top of the previously focused window, if that makes any sense.

**Comment by MarshallOfSound** [comment]
@arkon Define "eventually" is it a matter of seconds, minutes, hours?

**Comment by arkon** [comment]
@MarshallOfSound Seconds. It refocuses just before the GPM page content shows up.

**Comment by arkon** [comment]
I'm trying it now, and it seems to only happen if you Alt+Tab away from it right after opening it. Here's a video: https://www.youtube.com/watch?v=g-sjql8FYBo

**Comment by MarshallOfSound** [comment]
@arkon I can't replicate this on master, so I'm going to assume I fixed it in the massive `v4` refactor
