### ISSUE TITLE
Feature Request: Publish Now Playing Info

### ISSUE THREAD

**Issue by collinjackson93** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#175]
I think it would be nice to make data for the currently playing song available (title and artist at the least). I use Rainmeter for desktop customization, which supports displaying the currently playing track for several media players (documentation found [here](https://docs.rainmeter.net/manual/plugins/nowplaying/)).

I'm not totally sure how the data has to be presented in order for Rainmeter to pick it up, but if this is a feature that others are interested in, I'm fine with doing some research. I imagine that there is some standard format that could be utilized by other programs, as well.

After the migration to electron, I can also take a look at implementation. I've done a decent amount of work with Node.js, so I may be of some help.

**Comment by MarshallOfSound** [comment]
Right so...........

This was released as a feature a few days ago...

See here for some details
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/docs/PlaybackAPI.md

And even better, a rainmeter thread about how to use it :+1: 

https://www.reddit.com/r/Rainmeter/comments/43q0t2/ocgoogle_play_music_desktop_player_song_info/

Have fun :cactus: :cactus:

**Comment by collinjackson93** [comment]
Wow. What a fast response! Sorry I didn't see this already.
