### ISSUE TITLE
Windows 10 - First launch after starting computer always causes White Screen

### ISSUE THREAD

**Issue by theFisher86** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1750]
**OS:** Windows 10

**Issue Descriptions:** When my computer is restarted and GPMDP starts at launch when I first open up the program it is just a white box, I've let it "load" for over an hour before and it never changes.  If I close the app and re-open it everything is fine.  I noticed on the FAQ there was a mention of --disable-gpu as a possible fix for a different problem which leads me to believe that maybe GPMDP when set to launch at startup puts itself ahead of the graphics drivers necessary?  Just an idea though.

**Steps to Reproduce:** Restart computer with GPMDP set to launch at startup, double click tray icon.

**Comment by MarshallOfSound** [comment]
`v4` will be released with crash monitoring so I will actually be able to help more but until then this just sounds like a weird windows thing.  😆 

Without a crash dump it's super hard to figure out what's going on 👍
