### ISSUE TITLE
Freezes immediately after playing a song

### ISSUE THREAD

**Issue by Snowpigeon** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1753]
**OS:**
Windows 10
**Issue Descriptions:**
After playing a song, the program freezes while the song continues to play.
**Steps to Reproduce:**
Open program, play song, program freezes.

**Comment by stasguy** [comment]
Same thing happens on my computer running windows 10. After a bit it will unfreeze again, but as soon as you do anything it will freeze up again and again and again.

**Comment by MarshallOfSound** [comment]
Assuming this is an issue with Chromium that will be fixed on an Electron version bump 👍
