### ISSUE TITLE
Setup cant run windows 10

### ISSUE THREAD

**Issue by omkar9496** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1754]
[GPMDPError.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/523822/GPMDPError.zip)

**OS: Windows 10 anniversary update 14393.187**

**Issue Descriptions: Setup cannot install**

**Steps to Reproduce: run the setup. crash**

**Comment by MarshallOfSound** [comment]
Please disable your A/V and run as admin to work around this issue.

Basically your A/V is isolated the installer for whatever reason
