### ISSUE TITLE
GPMDP not respecting audio device settings

### ISSUE THREAD

**Issue by ibigfire** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1755]
**OS:**
Windows 10 64bit

**Issue Descriptions:**
GDMPD is just playing out of my default audio device no matter which option I choose.  I would include a debug information zip file, but the method for doing so is not in the FAQ like it says it should be.  So I guess that's a separate issue, the FAQ not having instructions for including debug information, heh.

Below are the steps that I have tried to use to correct it:
I reinstalled over the program.
I uninstalled the program and reinstalled it.
I uninstalled the program, deleted the program's folder in %appdata% so as to remove all settings, and reinstalled it.

**Steps to Reproduce:**
Go to Desktop Settings.  Then Audio.  Then change the Audio Device and listen to see if it actually changed or not.

**Comment by MarshallOfSound** [comment]
Fixed in master.  Will be out next release

**Comment by ibigfire** [comment]
You're awesome.  Thank you!
