### ISSUE TITLE
GPMDP intercepts Alt-Space window shortcut and toggles playback

### ISSUE THREAD

**Issue by paulcbetts** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1757]
**OS:** Windows

Because I am an Old, I use `Alt-Space, n` to minimize windows (this is a standard Windows feature since at least Win3.1). In GPMDP however, the "Space" part of `Alt-Space` gets picked up simultaneously and the music gets paused. If the Alt modifier is down, we should ignore this keystroke.

**Comment by MarshallOfSound** [comment]
Heh, just spent 10 minutes looking for this shortcut before realizing it is Google's shortcut not mine 😢 

This could be a fun one to solve

**Comment by mdsecurity** [comment]
Hi can I take this one ?

**Comment by MarshallOfSound** [comment]
Sure, give it a shot @mdsecurity

**Comment by MarshallOfSound** [comment]
@paulcbetts @mdsecurity This appears to be an issue upstream with Electron.  I tested in Chromium and the raw Electron app and in Chromium doing the "alt+space" shortcut does not send the "space" key event to the window.

Whereas in Electron the "space" key event is sent.  I believe we can workaround the issue, but I'll probably raise this upstream as well 👍
