### ISSUE TITLE
Blank artists pictures

### ISSUE THREAD

**Issue by MMRomanov** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1759]
**OS:** Windows 7x64

**Issue Descriptions:** https://yadi.sk/i/FcTwRLBvwmpDL

**Steps to Reproduce:** suddenly appears

**Comment by jostrander** [comment]
Quite frankly, if you're not going to take the time to write out a valid issue, I'm not going to take the time to even look into it. However this is more than likely an issue with GPM based on previously opened issues.

**Comment by MMRomanov** [comment]
The message was sent by accident before I attached description. But ok, thank you for such a prompt response.

**Comment by jostrander** [comment]
Apologies then, reopened.

**Comment by MMRomanov** [comment]
Thank you. Already tried to reinstall the program, re-login to Google music - the problem is not solved.

**Comment by MMRomanov** [comment]
No VPN, no proxy

**Comment by MarshallOfSound** [comment]
@MMRomanov I have personally observed this issue before and it appeared to be an issue with Googles caching layer for artist / album images.  When it was happening to me I ran a whole bunch of tests and it appeared as though googles image servers were returning `304 - Not Modified` when the image in GPMDP's cache was partial, incomplete or incorrect.  As such the browser fails to render it.

Can you try clearing the cache of GPMDP by deleting the `%APPDATA%\Google Play Music Desktop Player` folder.

**Comment by MMRomanov** [comment]
Thanks! That solved the problem. But for the future and for those who may be faced with this problem. Perhaps is it possible not remove all the% APPDATA% \ Google Play Music Desktop Player folder, but only some subfolders in it to save the settings?

**Comment by jostrander** [comment]
Technically you only need to copy your settings file out before deleting the directory to save your settings. However if it happens again you might try first deleting only the `Cache` sub folder.

**Comment by MarshallOfSound** [comment]
@MMRomanov I normally say "delete the whole folder" because it is easier than explaining how to surgically remove the chromium cache files from the directory.  If you want your settings back just pull the `json_store` folder from the trash 👍

**Comment by MMRomanov** [comment]
Thank you!
