### ISSUE TITLE
Another Crash to Desktop...

### ISSUE THREAD

**Issue by ckhericks** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#176]
Slightly different from the other issue that is posted.

I was previously using 2.0.2, and it worked fine. I uninstalled it completely, and cleaned my CPU with a registry cleaner (Piriform/CCleaner). I then installed the new 2.1.1 version directly download from GitHub. From installation, the program immediately closes when I open it. I opened the task manager, and am able to see the task running for a brief moment when I start it, but it closes less than a second later.

There is no splat screen, sound, or error message of any kind. It must be failing on some fundamental level. Maybe I'm missing a dependency? I know you don't claim there were any other than Windows 7 and above. It also may bear worth mentioning that I am a programmer, so there is MVC/ASP.NET/Visual-Studio and other software installed on this computer that the average user may not have.

I also tried running the program as Admin, and disabled my anti-virus.

My stats are beefy:
Win 10 Pro,
i7-5820K @ 3.3Ghz
16 GB DDR4
1/2 TB SSD

**Comment by MarshallOfSound** [comment]
Closing as dup of #178 

Please close yourself if you repost an issue
