### ISSUE TITLE
Audio Devices

### ISSUE THREAD

**Issue by polloconadobo** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1761]
Hey don't really see a thread about this problem. I'm not even sure if anyone else is having the same issue. After the recent update, now my virtual cable is not taking any audio. I checked the desktop settings, it's on the right cable, and I see nothing going through on VoiceMeeter. Just stays on the default audio device which is my whole system. Hopefully someone has a fix, I would like to separate my audio for the live stream.

**Comment by MarshallOfSound** [comment]
Fixed in master, will be out next release.  Please check closed issues before raising a new one...
