### ISSUE TITLE
GPMDP constantly hangs on Windows 10 anniversary edition

### ISSUE THREAD

**Issue by CrackTheSkye** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1764]
**OS:**
Windows 10 Home
Version 1607
Build 14393.321

**Issue Descriptions:**
I've been having this issue on my desktop PC and on my laptop. Both run the same version of Windows 10.

Basically whenever I start up GPMDP, I can search any artist, play any song, it works perfectly. However, when I try to pause it later on, sometimes even immediately after I start playing a song, the program will hang, not respond to anything and just keep playing. Nothing works, so it's not just play/pause, I can't minimise, choose next song, quit,... The only thing that works is just waiting, as the action I chose will happen a minute or so later. I tried uninstalling with Revo uninstaller and even tried getting an earlier version (3.5.0), but the issue still persists.

EDIT: my laptop is an Asus G501JW (i7-4750HQ, 16GB RAM) and my desktop has 8G RAM and an i5-3570k, so performance shouldn't be an issue I think.

**Steps to Reproduce:**
1. Install Windows 10 anniversary edition
2. Install GPMDP
3. Try doing anything after initially starting a song

**Comment by MarshallOfSound** [comment]
This issue could quite possibly be fixed in `v4` due to the massive rewrite that has occurred.

Is the UI just freezing or is there a massive CPU burst?

**Comment by beegary** [comment]
*Windows 10 Enterprise 1607 (anniversary)*
Installed GMDP (3.6.0)

Started a song, paused, play, access playlists etc. etc: i.e. I cannot recreate the problem

**Comment by MarshallOfSound** [comment]
I'm gonna say this will be fixed by the rewrite and hope for the best

**Comment by RealityExit** [comment]
I've also been experiencing this issue constantly after downgrading from Windows Insider builds to the standard Anniversary build.  Unfortunately there seem to be no change with v4 for me.

To answer your previous question it does not seem to be correlated with a CPU spike on my end.

_Windows 10 Pro
Version 1607
Build 14393.321_

**Comment by CrackTheSkye** [comment]
Sorry for the late reply. I did not notice any CPU spikes either. I'll upgrade to v4 today, let's see if it helps on my end.
