### ISSUE TITLE
Unable to Change Audio Output Source

### ISSUE THREAD

**Issue by Ezalis** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1769]
**OS:** Windows 10 w/ Cumulative Update

**Issue Descriptions:** Cannot override Windows sound output device through audio device settings.  Previous versions allowed Windows default sounds to route through coax out while Desktop Player would route audio through a USB DAC.  Now any audio output source selection will default to the system output.

**Steps to Reproduce:** Set Windows sound output to source different from Desktop Player source output

**Comment by MarshallOfSound** [comment]
These are starting to annoy me now.  This is fixed in master and will be out next release.

See these duplicates that you should have found before raising this issue:
#1761 #1755 #1722 #1714 #1707
