### ISSUE TITLE
Feature Request:  Single Click on Tray Icon makes music play/pause

### ISSUE THREAD

**Issue by ibigfire** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1774]
**OS:**
Windows 10

**Issue Descriptions:**
Right now single clicking the tray icon does nothing.  That seems like a waste.  I personally think it would be best if single clicking on the icon play/paused the music, especially given the way the icon works as of 4.0.0 with it showing the play/pause status.  This is totally just an idea, and if you don't like it feel free to completely disregard.  Either way, thank you for your work put into the music player, I absolutely love it and appreciate it.

**Comment by MarshallOfSound** [comment]
> Right now single clicking the tray icon does nothing.

Only on windows, on both Linux and macOS single click is the standard for opening the menu.  I don't think that a single-click to play/pause is expected or intuitive so I'm going to say no to this for now 👍
