### ISSUE TITLE
error: Last.fm API keys have not been set

### ISSUE THREAD

**Issue by saneklad** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1775]
**OS:** macOS Sierra

**Issue Descriptions:** Cannot Login in LastFM section v 4.0.0

**Steps to Reproduce:** Click "Log in to Last.Fm" button and get stick "Authorization in progress" message.

I pulled & ran project locally, so I got startup error as I described in the title.

**Comment by lkhrs** [comment]
I am also having this issue.

**Comment by MarshallOfSound** [comment]
> I pulled & ran project locally, so I got startup error as I described in the title.

I mean, I'm not sure what to say here.  The API keys aren't in version control so if you build from source you need to provide your own.  I would have thought the error was pretty self explanatory.  Maybe I should add this to the FAQ or something 👍

**Comment by saneklad** [comment]
@MarshallOfSound 
The first time I discovered this problem was at production after fresh install on my MacBook. 
Windows 10 PC is everything OK with LastFm, but after update to 4.0.0
