### ISSUE TITLE
4.0.0 still has Black Screen

### ISSUE THREAD

**Issue by christianbearslyclark** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1779]
I had this problem since 3.6.0  with Black Screen. I see nothing else.  I am waiting Windows 10.

Is there something else I must do before install new updates ?

I have to deleted the Update.exe ...so I may use the app of 3.5.0. version.

I really HOPE that you may fix this issue?
Thanks !

**Comment by MarshallOfSound** [comment]
Please follow debug steps in #1778
