### ISSUE TITLE
Feture request: color of tray icon

### ISSUE THREAD

**Issue by ostapch** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1780]
I'm using radiance theme on ubuntu. It is bright and tray icon hard to see. Maybe it will be enough to add some shadow to current icon

**Comment by MarshallOfSound** [comment]
@ostapch The current icon works nicely on the default themes of most linux distros.  Adding a shadow goes against the white and flat style that is default on most window managers.

The best thing to do here I think is add a linux only option to change between a white and black tray icon.  Should be relatively easy.

Just need to modify `vendor/svg_raster.js` to produce a dark tray icon as well and add some toggle logic to the settings.

**Comment by ostapch** [comment]
Thanks :) I'm waiting for this feature
