### ISSUE TITLE
Last.fm authorization doesn't work

### ISSUE THREAD

**Issue by GSmanXVI** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1782]
**OS:** Windows 10 build 14946

**Issue Descriptions:** After "LOG IN TO LAST.FM" button click I have a message "Last.FM Status: Authorization in Progress" and nothing happens.

**Comment by MarshallOfSound** [comment]
Last.FM appears to "yet again" be having some issues.  Please wait for them to fix their API **again**

**Comment by pauly4it** [comment]
I've been experiencing this issue as well for at least the past 5 days. Is [this](http://status.last.fm/) where we can check the API status? Everything seems to be OK other than submissions.

**Comment by MarshallOfSound** [comment]
> Everything seems to be OK other than submissions.

Last.FM are notoriously bad at updating their API status.
