### ISSUE TITLE
MDNS blocks app from loading when firewall denies traffic.

### ISSUE THREAD

**Issue by jostrander** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1784]
**OS:** _Windows_

**Issue Descriptions:**

When loading the application for the first time and using a firewall, the application starts, but then hangs until the MDNS request times out. Once it times out the error message (in --dev) prints, but then the program still hangs. Is this something we can mitigate by doing asynchronously, or at least let the rest of the UI load, but not the web frame?

**Comment by MarshallOfSound** [comment]
I managed to dive into this but there is actually nothing we can do without completely rewriting `mdns` to be asynchronous.  I think we're just going to have to take the hit with this one
