### ISSUE TITLE
 Extra option under the 'General' tab

### ISSUE THREAD

**Issue by galenasphaug** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1785]
**OS:**
Ubuntu 16.10
**Issue Descriptions:**
There is an extra option under the 'General' tab, "This allows other applications to interface with GPMDP".
**Steps to Reproduce:**
Open the desktop settings, switch to the 'General' tab.

**Comment by jostrander** [comment]
I thought this too, and was about to report it, however after diving into the code, it seems that it's just a mislabeled setting. This I believe actually turns on the WebSocket API.
