### ISSUE TITLE
User shortcuts fail after GPMDP app update on Windows

### ISSUE THREAD

**Issue by nickk-io** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1788]
**OS:** 
Windows 10 64-bit (Version 1607)

**Issue Descriptions:** 
After updating to 4.0.1 and a system restart the application failed to load, spewing the error below. I checked the shortcut I had created in the windows startup folder and noticed that it was just pointing to an old version (3.6.0) that I guess was missing files. The underlying issue is that I don't want to have to manually update my shortcuts every time the application updates.
```
A Javascript error occurred in the main process

Uncaught Exception:
Error: Unable to find a valid app
    at object.<anonymous>
(C:\Users\Nickk\AppData\Local\GPMDP_3\app-3.6.0\resources\electron.asar\browser\init....:9)
    at Module._compile(module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:360:7)
    at startup (bootstrap_node.js:152:9)
    at bootstrap_node.js:479:3
```

**Possible solution:**
Upon installation/update of GPMDP create/update a symbolic link for the most recent .exe at the root of GPMDP_3\. Shortcuts can then point at the symlink.

**Comment by MarshallOfSound** [comment]
>  I checked the shortcut I had created in the windows startup folder 

Why do this, we have an option in settings to launch at start up which we then do in a much nicer way than putting in a shortcut in a start up folder.

> Upon installation/update of GPMDP create/update a symbolic link for the most recent .exe at the root of GPMDP_3. Shortcuts can then point at the symlink.

There is already a system like this.  Running `Update.exe --processStart "Google Play Music Desktop Player.exe"` will always launch the newest version of the application and the path to `Update.exe` never changes.

Any shortcuts you put in normal places (Desktop, Taskbar, Start Menu, pinned in the start menu) are automatically corrected by GPMDP.  You were just unfortunate and put a shortcut in a non-standard / unexpected place 😆

**Comment by nickk-io** [comment]
Thanks for the quick response!

Funny thing is that I already had the option to launch at start up set on another machine.. ¯\\_(ツ)_/¯

I don't use the start menu search to launch programs because windows does not seem to like the way I form my queries. Instead I use launchy indexed on a folder I manually add apps and locations to, so the information about the update.exe option is really helpful, thanks.
