### ISSUE TITLE
UI Bug with Surface Pro 3

### ISSUE THREAD

**Issue by alohadude3** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1789]
**OS:** Windows 10

**Issue Descriptions:** When moving the cursor about the program the highlights that appear when hovering over various objects is inconsistent with the actual cursor position.
In more precise detail, when moving the cursor from one song to the one below it let's say, the highlighting will appear to slide much further than the cursor's actual movements and the program seems to think the mouse is at a position different than to where it actually is.
I have this issue with my Surface Pro 3 and the symptons of the bug seems to suggest it might be a problem with the high DPI scaling.
I do not experience this bug with my desktop computer.

**Steps to Reproduce:** Move the cursor around in the program on a Surface Pro 3 (Not sure what other devices can reproduce this) and observe the UI highlighting be inconsistent with the mouse cursor's position.

**Comment by MarshallOfSound** [comment]
A PR was just merged to fix touch screen / DPI / accessibility issues in Electron. Going to assume this is the bug it fixed 👍
