### ISSUE TITLE
Mouse causes UI to spasm

### ISSUE THREAD

**Issue by hydrocane** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1790]
**OS:**
Windows 10

**Issue Descriptions:**
Whenever I move my mouse to select something, the UI thinks I am selecting something else and spasms out. It will not let me select the song unless I hit it a few times. This occurs everywhere in the UI aside from the settings.

**Steps to Reproduce:**
I just installed the new update at 5:30 AM in the morning EST so that may have caused it.

**Comment by MarshallOfSound** [comment]
Duplicate #1777

**Comment by hydrocane** [comment]
Oh, whoops sorry. Thank you for the quick response though.
