### ISSUE TITLE
'Go to URL' doesn't do anyhting

### ISSUE THREAD

**Issue by pierrenaude** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1791]
**OS:**
MacOS Sierra 10.12

**Issue Descriptions:**
When I use the 'Go to URL' dialog it does nothing (GPMDP Version 4.0.1)

**Steps to Reproduce:**
Tried to load a URL a friend shared with me, nothing happened.

Thought maybe they did something wrong, but nothing works.

Select any Song/Album/playlist, click on More Options, Share and copy the URL.

Paste the URL into 'Go to URL' dialog and click 'Let's go'. Visual indication shows that the button has been clicked but GPMDP does nothing.

**Comment by MarshallOfSound** [comment]
@pierrenaude Can you provide the URL it doesn't work for?

**Comment by pierrenaude** [comment]
This was the one provided:
https://play.google.com/music/r/m/Lmfbcdi7lg4inxvv3nydqyzor4y?t=Peaceful_Stroll_

These are ones I tried for myself, that also don't work:
https://play.google.com/music/m/Bht4xedkica6rpnk3n46kgf4fnm?t=Blue_Sky_Red_Guitars_-_Erik_Wollo
https://play.google.com/music/m/B7sufqhlqnj76bqn6dwbvzsqu5u?t=WALLS_-_Kings_Of_Leon
https://play.google.com/music/m/T6n3mipznhfdfb2bimto4gxzp4y?t=Closer_feat_Halsey_-_The_Chainsmokers

**Comment by pierrenaude** [comment]
Thank you!
