### ISSUE TITLE
Sort Arrows point in the wrong direction

### ISSUE THREAD

**Issue by shunkwugga** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1796]
**OS:**
Windows 10, but should be OS agnostic

**Issue Descriptions:**
The sort arrows point in the wrong direction. When sorting the track numbers for instance, the arrow points downward when the numbers are increasing along the y-axis; also known as in ascending order. The opposite is true, and this also impacts other columns within the playlist view.

**Steps to Reproduce:**
1. Click a column header to sort in any playlist/album view. 
![ascenddescend](https://cloud.githubusercontent.com/assets/22931463/19511575/c215c0b6-95b5-11e6-873a-594921dd7c30.PNG)
![descendascend](https://cloud.githubusercontent.com/assets/22931463/19511576/c215a9c8-95b5-11e6-9681-e2f1f48dbfa1.PNG)

**Comment by MarshallOfSound** [comment]
This is googles decision and it's up for debate as to which way is "the right way up" even simple things like excel and google sheets have different ways of showing the arrows.  Take it up with google's feedback forums 👍
