### ISSUE TITLE
Cannot log into Last.fm

### ISSUE THREAD

**Issue by nsnyder** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1797]
**OS:** Windows 10

**Issue Descriptions:** Can't login to Last.fm (and it wasn't scrobbling before, which is why I tried logging out of Last.fm and back in). I was previously logged in, so not sure if that has anything to do with it.

**Steps to Reproduce:**
1. Be logged out of Last.fm
2. Open desktop settings
3. Try to login to Last.fm
4. Nothing happens

**Debug Log:**
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/539367/debug_info.zip)

**Comment by thezoid** [comment]
I have this same issue. I was just checking this repo to see if someone else was experiencing this. Based on how long ago this was posted, maybe it's on LastFMs end

**Comment by berryelectronics** [comment]
#1787

**Comment by nsnyder** [comment]
Ah, I didn't see that when I searched for some reason. I'll close this as a duplicate.

**Comment by nsnyder** [comment]
Closing as a duplicate of #1787
