### ISSUE TITLE
Last.fm 'love' linked to 'thumbs up'

### ISSUE THREAD

**Issue by allsorts46** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1799]
Thanks for this wonderful player, it really improves the experience of using Google Play Music!

I just got upgraded to the new v4.1 (I think? Can't find the version number anywhere now), and saw you've extended the Last.fm integration to automatically 'love' tracks when you give them thumbs up. Can I suggest that you make this optional? I love the Last.fm integration, but don't really want to 'love' everything there, only my real favourites. On the other hand, I'm pretty liberal with giving out 'thumbs up', in the hopes of influencing Google's recommendations.

**OS:**

**Issue Descriptions:**

**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment]
Can't please everyone can you :cry:

**Comment by allsorts46** [comment]
Aw, you really made me feel guilty now with that sad face!

Seriously, just a suggestion. GPMDP is great 😄

**Comment by parthsdoshi** [comment]
@MarshallOfSound Trying to fix this issue but for whatever reason, I can't login to Last.FM through the app if I build it manually -- always flashes Authorization in Progress but always comes back to Not Authorized within seconds. Can you or someone else build this branch: https://github.com/parthsdoshi/Google-Play-Music-Desktop-Player-UNOFFICIAL-/tree/lastfmheart to see if my changes worked?

Sincerely,
Parth Doshi

**Comment by jostrander** [comment]
@parthsdoshi I never saw this or I would have tried it sooner. I believe that's all that's required in order to make this work. Just so you know, you have to bake in your own API keys when using the dev version of the app.

**Comment by parthsdoshi** [comment]
@jostrander ah I see xD. Unfortunately I don't have a GPM subscription anymore which kinda demotivates me from doing this; however, anyone is free to just copy what I've done so far since it's a really easy fix.

**Comment by AlexDEVpro** [comment]
The app is awesome. Just one moment about this topic. Unfortunately, the linkage is unidirectional, not bidirectional.
I mean, if I turn on a track that was already pre-marked in Last.fm as a favorite, the thumb up button in the application does not light up.
