### ISSUE TITLE
Thumbs Up and Down buttons missing in Mini Player

### ISSUE THREAD

**Issue by MTRougeau** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#18]
There are no thumbs up and down buttons in the Desktop Mini Player. The web player places them prominently, then includes the shuffle and and repeat buttons above them. Also, it looks like text is cut off when the album title is too long. However, the web mini player omits the album title completely, only showing the song and artist names. Thoughts?

![desktopminiplayer](https://cloud.githubusercontent.com/assets/15477491/10864985/19f6c51a-7fcc-11e5-9e7a-ca5616573b8b.PNG)
![webminiplayer](https://cloud.githubusercontent.com/assets/15477491/10864986/1c034cd4-7fcc-11e5-8c23-ef9d4de1f151.PNG)

**Comment by MarshallOfSound** [comment]
I consider this more of a design choice than a "bug".  I went for the easiest and most cut down mini player I could make while using the rendering JS that GPM already utilised.  The styling of the mini player is literally entirely done though CSS.

I personally don't use the thumbs at all, I'm not sure how many people actually do but in the mini player I just wanted the music controls and thats it.

Do you consider the thumbs a core part of GPM or do you just want feature parity between the two mini players?

**Comment by MTRougeau** [comment]
Not concerned with feature parity, just parity with the features I use. :) Yes, I do find myself using them occasionally. The keyboard shortcuts for thumbs up and down still work in the mini player, but if I ever want to SEE if I've already thumbed up a song or not, I have to exit the mini player and go back to the regular window, which is kind of annoying.

**Comment by Darsh911** [comment]
I second that. 
I use them a lot while listening the "I'm feeling lucky Radio" and will be so great to have them also into the mini player.

**Comment by FISHunderscore** [comment]
I also use them often while listening to station. They'd be a handy addition to the mini player.

**Comment by spr0k3t** [comment]
The thumbs are what I use on the radio stations, helps weed out the junk in the long run.

**Comment by cboseak** [comment]
I agree, I use the thumbs up to add to googles auto-playlist named thumbs up. Kind of a way to keep a dynamic constantly changing playlist without having to manually add things. This is a great project by the way, really excited at how this is turning out.

**Comment by MarshallOfSound** [comment]
OK guys I get the message, you are want it and I haven't done it for a month...

*hangs head in shame*
*self assigns*

**Comment by MarshallOfSound** [comment]
So how do you guys @cboseak  @spr0k3t  @FISHunderscore @Darsh911 @MTRougeau feel about only having the thumbs available during radio playback?

Design restrictions (seemingly google JS related are preventing much fiddling with the thumbs styling, but I can make them visually fit and work while the radio is playing.  Is this OK?  (I can see that all of you claim the radio as the reason you want this?)

**Comment by FISHunderscore** [comment]
I'm fine with thumbs just for the radio. All of the music that I've uploaded/bought I already know I like anyway.

**Comment by spr0k3t** [comment]
Removing "repeat" and "shuffle" in favor of thumbs would be perfect for me on the radio section.
