### ISSUE TITLE
Feature Request: Add to playlist in mini player

### ISSUE THREAD

**Issue by Taeon** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#180]
Title says it all -- I have to open the full player to add a track to a playlist. Perhaps I'm being stupid but I don't see a way to do this in the current version (2.1.1).

**Comment by MarshallOfSound** [comment]
Duplicate
https://github.com/MarshallOfSound/gmusic-mini-player.js/issues/2
