### ISSUE TITLE
Lyrics track progress bar color is backwards from GPM UI track progress bar

### ISSUE THREAD

**Issue by Cyndre** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1800]
Windows 10 Home, Build 1607

Lyrics overlay seems to cause an issue with the playback scrubber. It appears below the shutter for lyrics, but does not have the timestamp nor media controls. I would assume this is the playback scrubber as it is the only orange element I have on the player that would move to the right in this fashion.
Here is a video of it.
https://www.dropbox.com/s/3hpyedcbevjjp4y/Desktop%2010.19.2016%20-%2018.57.08.01.mp4?dl=0
(sorry for choppy video, Dropbox didn't retain the 50mbps bitrate and 1440p60 resolution)

**Steps to Reproduce:**
Open GPMDP v4.0.1 (latest as of 10/19/16)
Play a song.
Click the 3 dots and select "Show Lyrics (Beta)"
Look at bottom of screen, you can see this:
![View](https://cloud.githubusercontent.com/assets/22947247/19541654/92029eee-962d-11e6-848e-84826c38e880.png)

**Comment by jostrander** [comment]
That's not a scrubber, but more less just an visual indication of the current track time.

**Comment by Cyndre** [comment]
Sorry for my miswording. I meant the track progression bar, but Scrubber is just simpler.

**Comment by jostrander** [comment]
Either way, what I meant was, that's not part of the original playback controls. The lyrics overlay is 100% covering GPM and the bar you are seeing is something that was added as an extra feature so you could see the track progression.

**Comment by Cyndre** [comment]
That makes more sense. In the video I attached, I showed the bar going backwards, so the grey area is the progress bar. Would it be better if the orange was the color that progresses towards the right side?

Anyways, thank you for clarifying.

**Comment by jostrander** [comment]
I do agree the progress bar is counter-intuitive to what one would expect, maybe we should switch that around so the color is on the past side of the current time.

**Comment by Cyndre** [comment]
Sounds like a good idea. Thanks for the help!
