### ISSUE TITLE
Mini Player and Taskbar media controls are lacking in features and useability

### ISSUE THREAD

**Issue by Cyndre** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1801]
**OS:** Windows 10 Home, Build 1607

**Issue Descriptions:** Mini player cannot be shrunk to only show the media controls. Mini player is also lacking the 3 dots with extended information. The 3 dots in the mini player should have things like Thumbs up and down, music options, and Start Radio. (when EQ is added, add to list)

◉ The mini player should have an option in Desktop Settings to "Only show media controls".

◉ The media controls found in the taskbar preview should be more advanced. There should be an option to enable this feature. The taskbar media controls should be translated into the media controls found on the mini player (shrunk), but with things like the 3 dots and thumbs.

The Mini player settings are lack lustered. These additions will breathe new life into them.
![screenshot 38](https://cloud.githubusercontent.com/assets/22947247/19542986/0ec38ba4-9639-11e6-8728-d66e5cf0ea54.png)

**Steps to Reproduce:**
Open the mini player.
Reduce the window size. (graphical convulsions occur, image distorted temporarily)

**Comment by MarshallOfSound** [comment]
Duplicate #701 

^^ That's the all-encompassing "please improve the mini player" issue

**Comment by Cyndre** [comment]
Can those setting additions be considered? I would like to see improvements to the Taskbar player, as I use that more than the Mini player. There is basic Pause/Play, Skip fwd/bck, but there is nothing after that.

**Comment by MarshallOfSound** [comment]
@Cyndre The taskbar is heavily limited by windows API's.  All I can do is add buttons and I am limited to a maximum of 5 buttons.  The buttons can only do things on click and can't pop up extended menus.

The settings option you describe would be solved by the "mini-mini player" proposed in that ticket.

**Comment by Cyndre** [comment]
5 Buttons would include Rpt, Skpbck, Play/Pause, Skpfwd, and Shfl? That is an improvement.
I understand that the API limits the potential, but two more buttons would make opening the app less of a necessity. I know that there is an icon on the right side of the task bar with these controls when left clicking arrow > right click icon, but simply hovering over the program icon to access the media controls is faster and easier.
