### ISSUE TITLE
Application UI flickers with white patches when mousing over songs in playlist.

### ISSUE THREAD

**Issue by stevebissett** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1803]
**OS:**
Mac OS X El Capitan - 10.11.6

**Issue Descriptions:**
When mousing after different songs in a playlist, the screen flickers while loading the images.

**Steps to Reproduce:**
Open the application. 
Play a playlist. 
Scroll mouse over a song. 
Notice flickering. 

This doesn't happen in the browser version of Google Play Music.

TODO: I can add screenshots and/or video if necessary.

**Comment by MarshallOfSound** [comment]
Regardless of the underlying issue for this it would be an Electron issue that would probably be traced to a Chromium / Blink issue.  It would almost certainly be fixed in the Chromium 54 bump that is coming to Electron 1.5
