### ISSUE TITLE
Duplicate song numbers in Roxette "The 30 Biggest Hits XXX"

### ISSUE THREAD

**Issue by cfsmp3** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1805]
**OS:**
Windows 10 64 bits

**Issue Descriptions:**
The album by Roxette "The 30 Biggest Hits XXX" (I assume others, but this is the one I'm listening to now) has 30 songs . However the player numbers them from 1-15, 1-15 (instead of 1-30). This is a new thing, by the way - didn't happen in the previous version.

**Steps to Reproduce:**
Just look for that album, nothing special needed.

**Comment by jostrander** [comment]
I think were looking at coincidence here because we don't do any kind of modification to the playlists or numbering or anything. Please try this request over at the google product forums for GPM.

**Comment by Alipoodle** [comment]
This is a 2 disc CD
https://play.google.com/store/music/album/Roxette_The_30_Biggest_Hits_XXX?id=B25x5yo6fva33dntgx3i5nhklae
