### ISSUE TITLE
Feature: Integration with Libre.fm

### ISSUE THREAD

**Issue by MossmannInc** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1807]
I'm aware of the issue #769 

With that in mind, I've been looking for a nodejs interface with LibreFM and wasn't lucky.
But, I've found a Python one, called [pyLast](https://github.com/pylast/pylast). Which also interfaces with LastFM.
I don't know how viable is to run Python code from nodejs. Or even to rewrite pyLast in nodejs.
I've also found [python-shell](https://github.com/extrabacon/python-shell) that, supposedly, runs Python scripts from nodejs in a simple and efficient way.

Particularly, I use both Libre and LastFM.
I scrobble to LibreFM which, then, scrabbles to LastFM.
LibreFM gives you the option to link your LastFM account and forward scrobbles.

Again, I don't know how viable this "solution" is. I don't have the required expertise to analyse this.
It would be much appreciated if someone could take a look.

**Comment by jostrander** [comment]
If you don't mind me asking, why do you scrobble to both?

**Comment by MossmannInc** [comment]
I have more scrobbles on my LibreFM (~500k) than my LastFM (~200k) account.
It's hard to give up those numbers. lol
Plus, I like both services.

**Comment by MarshallOfSound** [comment]
As always I'm going to say this is out of the scope I'm prepared to support for this player.  If someone PR's in to add libre I'd be more than happy to review and accept it but I am not going to add two service myself
