### ISSUE TITLE
Last.fm button does nothing

### ISSUE THREAD

**Issue by kingweee** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1808]
**OS:** 

Windows 10 x64

**Issue Descriptions:**

Log in to last.fm button does nothing. I saw a similar issue from people using proxies, I am not using a proxy or VPN.

**Steps to Reproduce:**
1. Open app
2. Click desktop settings
3. Click last.fm tab
4. Click "LOG IN TO LAST.FM"
5. Wait.....
6. Hangs on Authorization in progress, no prompts or any interaction.

**Comment by MarshallOfSound** [comment]
I'm going to start crying at these last.fm duplicates soon.

This will be fixed in the next release
