### ISSUE TITLE
Macbook keybindings

### ISSUE THREAD

**Issue by Nikki1993** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1809]
Hey there,

I was wondering how can I set the function keys, F7-F12 to use with the app? Currently when I try to set it, nothing happens :P running 4.0.1 version on macOS 10.12

**Comment by MarshallOfSound** [comment]
All accelerators need to use the "Control" key (for safety purposes) the global hotkeys are absorbed by GPMDP so other apps won't get the key press if it is a hotkey.  Hence the combination requires a "Control" key.

I know this doesn't make much sense on macOS but there isn't much I can do about that unfortunately 😢

**Comment by Nikki1993** [comment]
No problem, thanks a lot for the answer :)
