### ISSUE TITLE
Sidebar above main content after updating to 2.1.1

### ISSUE THREAD

**Issue by Shebo** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#181]
Hi there, just want to say it's a great app, I'm using it on a regular basis and enjoying it, so thank you for it!

On the buggy side of things, after I updated to 2.1.1 it looks like the sidebar is always open (hamburger is not responding) and it's fixed above the content.

![music](https://cloud.githubusercontent.com/assets/299232/12976812/5abe06ea-d0cf-11e5-9289-afa903783bb7.png)

**Comment by MarshallOfSound** [comment]
Interesting, no idea what's causing that...  It looks like that when you are on a smaller screen and you "drag" out the side bar, like you would on a mobile device.

Can you try like "dragging" it shut and see if it works :P

**Comment by Shebo** [comment]
Yeah, dragged it and it animated to the left and the bug went away! Now it works with toggle click and without the sidebar hovering the content. It's even persistent after restarting the app.

Thanks!

**Comment by Jespiee** [comment]
It's an issue with GPM, when you slide to open you are unable to close it with the hamburger button..
