### ISSUE TITLE
Prevent Auto-Update

### ISSUE THREAD

**Issue by Devo7v** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1810]
GPMDP was recently updated from 3.6.0 to 4.0.1.  While I'm sure this is great for most users it has caused my installation nothing but problems.  I'm assuming this is due to the fact that my access to the TEMP folder is restricted.  Because of this in GPMDP I am unable to open the Desktop Settings, I cannot minimize to the mini player, and I cannot play more than 15 seconds of any song.

Downgrading back to 3.6.0 fixes all these issues, but everytime I close and reopen GPMDP it has been updated to 4.0.1 again and nothing works.  Is there any way I can prevent the auto-updates?

**Comment by MarshallOfSound** [comment]
I don't feel comfortable telling users how to disable updates as this can cause security and compatability issues if the user is not vigilant enough to maintain updates themselves.

You'd be better off filing a more accurate bug report about the actual issues you are experiencing. "nothing but problems" doesn't help anyone
