### ISSUE TITLE
Track progress not shown when casting to Chromecast

### ISSUE THREAD

**Issue by enda7** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1815]
**OS:**
macOS Sierra

**Issue Descriptions:**
Track progress bar does not show progress when using Chromecast

**Steps to Reproduce:**
1. Update to player Version 4.0.1 (4.0.1)
2. Launch player
3. Connect to Chromecast 2nd Gen
4. Play a track

Result: The progress bar does not update during playback.

![screen shot 2016-10-22 at 14 22 36](https://cloud.githubusercontent.com/assets/1726214/19619592/0db9fc44-9863-11e6-9035-77c09152378b.png)

**Comment by MarshallOfSound** [comment]
Does the problem persist after restarting GPMDP?

@enda7

**Comment by bernikr** [comment]
I have the same issue on windows, running the same version (4.0.1). Restarting the player does not fix the problem.

**Comment by MarshallOfSound** [comment]
@bernikr Just so I can assign this the right priority in my head, everything else still works right?  So the track plays and everything updates **apart from** the progress bar?

**Comment by bernikr** [comment]
Yes, if the next song starts playing, everything is updated. You can even use the progress bar to jump forward and backward in the song, after a fraction of a second, however, the progress bar jumps back to 0:00. (Besides the progress bar the timer on the right is also affected.)

Another thing I have noticed is that while connecting to the Chromecast it doesn't list the name anymore but "Chromecast-Audio-[a 32 char hex number]". This may or may not be connected to the issue.

**Comment by jostrander** [comment]
Are you using preview firmware on your chromecast?

**Comment by jostrander** [comment]
Confirmed broken on preview firmware and current firmware.

**Comment by bernikr** [comment]
If it still matters, I'm using the normal firmware on the Chromecast Audio.

**Comment by MarshallOfSound** [comment]
Possible fixed in https://github.com/GPMDP/electron-chromecast/commit/d438a47c6e1cc4f0c92a323288d0b2b94d5d9d61

Pending some proper testing
