### ISSUE TITLE
Crackling Sound With Every Mouse Movement

### ISSUE THREAD

**Issue by LeftEyeNine** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1816]
Hello,

I am on:

MSI GS60 6QE Ghost Pro (4K) model laptop of which detailed specification you can find [here](https://www.msi.com/Laptop/GS60-6QE-Ghost-Pro.html#hero-specification) which runs on Windows 10 x64 Anniversary Update.

I had used a certain version prior to 4.0 and I had to reformat my PC then so I do not know if 4.0 introduced this issue or not but I've been using 4.0.1 for a week now and even though the system is not loaded, the power plan is maximum performance and  AC is plugged in, crackling in sound occurs as you move the Mouse cursor across the screen, or say scroll a web page down.

It gets even heavier with every movement you make if you have your Google Chrome open with around 20 tabs like mine. The thing is neither iTunes or, say, another audio-source using website like Youtube does that.

This particular app has clearly issues with delegating or efficiently using the resources - I don't know, I'm no expert.

I can provide further information should you tell me how to - I am not computer illiterate, quite the opposite actually.

All this to have a flawless version of this huge work you've put into this.

Thank you.

**Comment by MarshallOfSound** [comment]
@LeftEyeNine I have an MSI laptop as well and they are notorious for having "interesting" audio drivers.  Can you try the following few things

1. Try disabling Nahimic (MSI audio driver thingy) and restarting your computer and trying again
2. Try Google Play Music in Chrome and see if the same situation occurs
3. Try running windows in safe mode and see if the same situation occurs.

Tbh this sounds like a driver or even a hardware issue but try the above and see what happens

**Comment by LeftEyeNine** [comment]
You were so right on.

Exiting Nahimic 2 just made the problem go away. I loved it so, that's a shame.. Only if they could work with those too.

Anyway, this issue is clearly in relation with Nahimic, not this software alone, if not totally independent.

Thank you for the quick repsonse.

**Comment by MarshallOfSound** [comment]
@LeftEyeNine There are some beta versions of Nahimic floating around and their might be an update available for your laptop so you might want to go looking for that 👍

**Comment by LeftEyeNine** [comment]
The current one I am using actually is a beta. So that might be why.

Thanks again for the awesome app.
