### ISSUE TITLE
Update message blocks mini-player

### ISSUE THREAD

**Issue by draugmot** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1817]
**OS:**
 Win10 x65

**Issue Descriptions:**
Update notification gets in mini-player and doesn't allow any interaction with it.
![2016-10-24_01-01-58](https://cloud.githubusercontent.com/assets/23019003/19629926/14f81f24-9988-11e6-8f6a-3429610aea4b.png)

**Steps to Reproduce:**
Receive an update while UI's in mini-player form

**Comment by MarshallOfSound** [comment]
Has been fixed in latest update
