### ISSUE TITLE
Player prevents PC from going into auto timed sleep/hibernate even when not playing music

### ISSUE THREAD

**Issue by mrlog101** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1819]
**OS: Windows 7 Professional 64x**

**Issue Descriptions: Player prevents PC from going into automatically timed sleep due to a powercfg request, even when there is no music playing**

**Steps to Reproduce: Open command prompt with the player open, and enter "powercfg /requests", you can see under the "system" list there is an audio driver preventing the system from going into sleep / hibernate mode automatically, as "An audio stream is currently in use.", despite the fact that it always says this with or without music playing.**

The only workaround I have found is to manually override the audio driver's power request, however, this is undesirable as applications such as Netflix and Youtube use the same method to prevent automatically timed sleep, although they seem to remove the request when nothing is playing.

![9e2d45bb67](https://cloud.githubusercontent.com/assets/23029849/19643846/6afed6f4-99e4-11e6-8a48-3ef9e2df1e27.png)

**Comment by MarshallOfSound** [comment]
Duplicate #1724
