### ISSUE TITLE
Building for Linux

### ISSUE THREAD

**Issue by ItsiAdam** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#182]
Edit: I'm an idiot.
Can this be built for Linux as it stands? I'm going to try to run in wine and see how it performs but native support would be nice :)

**Comment by MarshallOfSound** [comment]
Not at the moment

@ItsiAdam Hold out a few weeks for Version `3.0.0`

It has been completely rewritten in Electron which is a cross platform framework for desktop apps.  Once released it will just "work" on linux... :+1:
