### ISSUE TITLE
Lyrics dont jump back if you pause and rewind

### ISSUE THREAD

**Issue by berryelectronics** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1821]
*_OS: Windows 10 64bit *_

**Issue Descriptions:**

Just noticed: if you're in the middle of a playlist and have the lyrics open, you can pause and press the rewind button (shortcut, media key OR jump out of lyrics and do it with the UI button) to jump to the start of the song, but the lyrics wont do the same, they will stay in place.
Same happens if you listen to the first song of the playlist, but you dont have to pause anymore.

**Steps to Reproduce:**
- Play a song in the middle of the playlist and open the lyrics
- Pause the song and use the "previous track" shortcut (jumps back to the start of the song)
- Lyrics stay at their position, start scrolling from there on

**Comment by MarshallOfSound** [comment]
Hmmm, we have jump detection but looks like it only detects positive jumps (greater than 2000 milliseconds I believe).   Pretty sure we just have to call `Math.abs` on that jump detection

**Comment by parthsdoshi** [comment]
Hm, Math.abs is already called but doesn't fix the problem if you rewind to the start of the song. I can fix this by removing

`&& $(findDOMNode(this)).find('#lyrics p').attr('data-scroll')`

from

LyricsViewer.js Line 60: `if (Math.abs(timeObj.current - jumpDetect) > 1000 && $(findDOMNode(this)).find('#lyrics p').attr('data-scroll')) {`

Was this just an extra unneeded check to be sure the lyrics should be animating or am I missing some edge case?
