### ISSUE TITLE
Enhancement: Move language Dropdown List a bit up

### ISSUE THREAD

**Issue by berryelectronics** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1822]
**Issue Descriptions:**

The language dropdown list goes to the end of the viewport, which makes it look like its still not the end and that you can scroll the settings menue down. Would be better if it would only go to 10px above the lower settings border, so that you can see the border and dropshadow of the dropdown list

How it is:
![](https://puu.sh/rU7zR/3730b14cba.png)

How it looks better:
![](https://puu.sh/rU8cM/9367b61b17.png)

**Comment by MarshallOfSound** [comment]
> Would be better if it would only go to 10px above the lower settings border, so that you can see the border and dropshadow of the dropdown list

This is out of our control, you would have to PR upstream to `material-ui` to get this fixed.  IMO though it's not really a big issue, it's not like the scrollbar is invisible. 😆
