### ISSUE TITLE
No back button

### ISSUE THREAD

**Issue by poohlty** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1823]
I saw #1550. Unfortunately the back button doesn't appear anywhere on the Mac client.

**OS:**
MacOS

**Issue Descriptions:**
No back button

**Steps to Reproduce:**
Go to any album, see that there's no back button.

**Comment by MarshallOfSound** [comment]
I just checked on macOS and the back button definitely appears.  Can you provide a screenshot of your player window so I can point out the back button 👍

**Comment by jostrander** [comment]
It's in the search box and only when you can navigate backwards.

**Comment by albertsj1** [comment]
Just wanted to thank @jostrander for pointing out where the back button is.  I'm used to it being on the left side of the search box and didn't even realize there was a left arrow inside the right side of the search box.  I saw it there, but it just didn't click for some reason since it was inside the search box.

**Comment by jimmyodonnell** [comment]
With the latest update, I can no longer find the back button (on Windows; I can check on Mac at home). Did it move or disappear?

**Comment by jostrander** [comment]
It's broken in the current release (4.6.0), will be fixed in the next release.

**Comment by jimmyodonnell** [comment]
@jostrander thanks for the quick response! Can you venture a guess as to when the next release will happen? If it will be a while I might revert to an older version. GREAT product, by the way!

**Comment by jostrander** [comment]
I have no idea when the next release will be out. Hopefully soon.
