### ISSUE TITLE
high cpu usage while playing music

### ISSUE THREAD

**Issue by VenomXII** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1825]
**OS:** 
Windows 10 Home

**Issue Descriptions:**
After 30 to 45 mins of listening to music, the CPU usage goes really high and causes mouse stutter on machine . 
the cpu usage drops after force closing the app. 

**Steps to Reproduce:**
listen for long periods of time

**Comment by MarshallOfSound** [comment]
See #1777
