### ISSUE TITLE
Gnome tray icon to big

### ISSUE THREAD

**Issue by OlegKrikun** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1828]
**OS:**
Ubuntu 16.10 with Gnome 3.22

**Issue Descriptions:**
Gnome tray icon to big

![gpmdp-icon-gnome](https://cloud.githubusercontent.com/assets/429351/19691016/5a569150-9adb-11e6-947a-3d4960c1b22a.png)

This problem affects the previous version of Gnome Ubuntu, too.

**Comment by MarshallOfSound** [comment]
There's nothing we can do about this.

I'm not going to ship a tray icon for different distributions of linux, that will simply increase the package size for very little quality gain.  If the flavor of linux wants a certain size of tray icon then it should correctly display larger ones and scale appropriately.
