### ISSUE TITLE
Chromecast Names missing

### ISSUE THREAD

**Issue by max929292** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1829]
Mac OS X 10.11.5
Desktop Player: 4.0.1

Chromecast devices do not appear with their names anymore but just their ID, like:

Google-Cast-Group-fe20bb04f2892eef34b96

**Comment by MarshallOfSound** [comment]
Fixed in the latest `electron-chromecast` which is now in master and will be out next release

**Comment by MarshallOfSound** [comment]
Also duplicate: #1681
