### ISSUE TITLE
Why not release this on Windows Store?

### ISSUE THREAD

**Issue by nigeljoy** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#183]
This app is really cool. Why is that it is not made available as an app?

**Comment by lucaboox** [comment]
probably legal reasons and it probably has to be accepted and stuff

**Comment by MarshallOfSound** [comment]
Hardly an issue, please have this discussion in Gitter rather than as a github issue

**Comment by MarshallOfSound** [comment]
But FYI it's because its much easier and less legally awkward to release externally
