### ISSUE TITLE
Remote app connection fails

### ISSUE THREAD

**Issue by dmitriypavlov** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1835]
**OS:** 

Windows 10 x64 / macOS 10.12.1 / Android 6.0.1 

**Issue Descriptions:**

Can't connect the Android remote app neither automatically nor by direct IP.

**Steps to Reproduce:**

Disabled firewall in both cases, same WLAN network.

**Comment by MarshallOfSound** [comment]
Ensure your playbackAPI is enabled.  Please also raise issues for the remote in the correct repository 👍

**Comment by VitorFrost** [comment]
So, Where is this repository? There is no link to it, anywhere!
