### ISSUE TITLE
Opening mini-player causes the window to continually grow and zoom in. Reverting causes main window to be extremely zoomed.

### ISSUE THREAD

**Issue by the-white-light** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1837]
**OS:** Windows 7

**Issue Descriptions:** Opening the pop-out miniplayer causes the window to continuously grow. Changing back to the normal window leaves it zoomed in, until the program is quit fully (not just window closed). The size of the mini-player when reverting back to the main window seems to affect how zoomed-in (or out) the main window becomes. 

Attempting to resize the miniplayer by the edges is ineffective in this state: Top and left sides will cause the window to be pushed over, the right and bottom cannot be dragged due to their movements. Dragging by top-left corner works.

**Steps to Reproduce:** Open pop-out player, watch it grow. Close pop out player, see it in an unusable state.
https://vid.me/SqA1 
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/557699/debug_info.zip)

**Comment by MarshallOfSound** [comment]
Errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr

Your system is clearly haunted 😆 

Do you have some kind of third party window manager or workspace organizer?

**Comment by the-white-light** [comment]
Yes, I use Windowblinds to theme everything, and putting in a specific exclusion for GPMDP stops this from happening, but this wasn't happening in previous versions. Odd, but at least that solved the issue.

**Comment by squallyfungus32** [comment]
I'm having this issue on Windows 10 with a SurefaceBook since version 4.0.

**Comment by blacj** [comment]
I also have this same issue. 

Windows 7. No third party window manager or workspace organizer.

If I toggle back to the full size player, it is tiny and can be stretched out to a normal size - No full quit required.
