### ISSUE TITLE
Tray icon disappears on screen lock

### ISSUE THREAD

**Issue by kpuljek** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1838]
**OS:** A clean install of Ubuntu 16.10, using the latest build from https://www.googleplaymusicdesktopplayer.com

**Issue Descriptions:** When my session locks automatically or I lock it manually, the tray icon gets replaced by the "icon missing" icon.

**Steps to Reproduce:**
Run GPMDP
Lock session
Unlock session
![screenshot from 2016-10-28 18-36-59](https://cloud.githubusercontent.com/assets/9851336/19814206/8890db5c-9d3d-11e6-9fdd-7dfc0a5155e0.png)

**Comment by MarshallOfSound** [comment]
I tried to repro this on Ubuntu 16.10 and I couldn't.  Also tried on all the other linux VM's I have and some friends linux installs, none of them could repro.  Probably a corrupt file during an upgrade or initial install.  Might be worth updating / reinstalling 👍
