### ISSUE TITLE
Set correct application title in notifications

### ISSUE THREAD

**Issue by adnidor** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1840]
**OS:** Arch Linux

**Issue Descriptions:** When displaying a notification the originating application is shown as electron instead of something like "Google Play Music Desktop Player"

**Steps to Reproduce:** Do something that will display a notification, then look at the originating app. May not be displayed by all DEs

Purely cosmetic bug, no inpact on functionality

**Comment by MarshallOfSound** [comment]
@adnidor This is because you are using `gpmdp-git` on arch.  This is a package not supported by us and actually runs the github repository in development mode so it doesn't rebrand the Electron executable.  Nothing we can do about it
