### ISSUE TITLE
Feature Request: Stream to UPnP/DLNA

### ISSUE THREAD

**Issue by yanus** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1843]
Would it be possible to add the ability to stream the audio to UPnP/DLNA devices (renderers) in addition to chromecasts?

**Comment by MarshallOfSound** [comment]
This is currently impossible.  Chromecast is implemented through a secure private API that Google manages.  I don't actually have access to an open media stream from the client.

**Comment by Hoerli1337** [comment]
Die Frage wurde zwar schon beantwortet, ich würde sie aber gerne anders herum stellen.
Wäre es möglich, eine Unterstützung für Snapcast zu integrieren?
https://github.com/badaix/snapcast
