### ISSUE TITLE
Rendering issue with mouse movement

### ISSUE THREAD

**Issue by rensnest** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1849]
Windows 10 latest update 
V 4.0.1 GDMP
**Issue Descriptions:
 When moving the mouse anywhere with the desktop player open there seems to be a rendering issue. several components flicker when moving mouse anywhere on screen. The album art, three-dot hash, thumbs up thumbs down and volume control will flicker If I move my mouse in particular below the track progression bar.

Further, With the track queue open and moving mouse over various tracks there is flickering of album art and the dark highlight intended with current mouse hover jumps around from multiple tracks in the list when moving mouse.

**Steps to Reproduce: happens all the time music playing or not. It seems specifically to occur when mouse moves over a selectable object.

I hope I explained this well enough.

**Comment by dantinho** [comment]
Glad to know I'm not the only one! When I'm highlighting a song, it rapidly switches between the song four or so spaces down and the one under my cursor. The mini player behaves the same way, and I can't pause/play/rewind etc. from it.

**Comment by MarshallOfSound** [comment]
Duplicate #1777 

Currently the theory is that this is partially to do with touch screens.

**Comment by rensnest** [comment]
@MarshallOfSound just a note. My laptop does not have any touch screen functionality. Samsung Series 9. I will look at #1777
