### ISSUE TITLE
Feature Request: Change search results order

### ISSUE THREAD

**Issue by Taeon** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#185]
I don't even know if this is possible with the Google Music API, but it would be nice to be able to change the order of search results. For example, I listen to Armin Van Buuren's new State of Trance show each week, and when I search for it, it doesn't necessarily return the most recent first (presumably it's trying to sort by relevance?). In this case it would be handy to sort by 'date added'.

**Comment by MarshallOfSound** [comment]
TLDR: There is no Google Music API.  Messing with search results order is out of scope for this application, I would suggest using playlists or suchlike to get to your favourite songs quickly
