### ISSUE TITLE
Last.fm authorization window not showing

### ISSUE THREAD

**Issue by gonzalo-rodriguez** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1854]
**OS:** 
Windows 7

**Issue Descriptions:** 
I noticed this morning that the tracks I was playing were not being scrobbled to last.fm, so I went to the Desktop Settings window, deauthorized last.fm and try to authorize it again. When I click on the "LOG IN TO LAST.FM", the button turns to "...", the mouse cursor changes for a fraction of a second as if it was trying to open something... but it doesn't. The button keeps showing "..." until I close the Desktop Settings window and open it again, when it becomes again "LOG IN TO LAST.FM".

**Steps to Reproduce:**
- Deauthorize Last.fm
- Try to Log in to Last.fm again
(not sure if it will fail if it's the first time that the user tries to log in to last.fm)

**Comment by MarshallOfSound** [comment]
Please check closed issues before raising a new one.

This has been fixed in master 👍

**Comment by gonzalo-rodriguez** [comment]
Thanks! (and sorry, I searched, but I didn't realise that by default it only checks opened issues).
