### ISSUE TITLE
Consistent UI Flickering in 4.0.1

### ISSUE THREAD

**Issue by DericMcDerpy** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1858]
**OS:**
Windows 10

**Issue Descriptions:**
Most UI elements flicker like my mouse is moving to parts of the screen where it is not, examples attached:
https://gyazo.com/92dee974ad89a8c62b3ff5ac3ecf8179
https://gyazo.com/89d846f3fedf6e3fb56010f7d921df9e

**Steps to Reproduce:**
Not sure if I'm the only one having this issue but no steps aside from opening GPMDP are required, this has been a persistent issue for a while now.

**Comment by MarshallOfSound** [comment]
Duplicate #1777

**Comment by MarshallOfSound** [comment]
Out of interest through.  Touchscreen or no touchscreen?

**Comment by DericMcDerpy** [comment]
No touchscreen, I looked over #1777 and the issue he describes sounded somewhat different, did he ever post any video of the issue?

**Comment by DericMcDerpy** [comment]
Never mind I see the similarity in the comments now, I'll try and follow that thread for a solution.

Thanks
