### ISSUE TITLE
Can't authorize last.fm

### ISSUE THREAD

**Issue by chrismou** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1860]
OS: Ubuntu 64-bit
Version: 4.0.1

Am trying to link GPMDP to last.fm on an Ubuntu PC, and it doesn't seem to be working - specifically, I click the LOG IN TO LAST.FM link, the text changes to "Last.fm Status: Authorization in progress" and then nothing happens. No popup window like I've seen on previous versions.

Can anyone else confirm if they're seeing this issue, or if it's just something screwy happening on my box before I dig too far into debugging it?

**Comment by MarshallOfSound** [comment]
@chrismou Version `4.0.2` (released this morning) fixed this issue 👍

**Comment by chrismou** [comment]
Well on top of things, as always :joy: 

Cheers dude!
