### ISSUE TITLE
text/plain mimetype is associated with this application

### ISSUE THREAD

**Issue by jorti** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1861]
**OS:** Linux - Fedora 25

**Issue Descriptions:** This app is used when trying to open plain text files.

**Steps to Reproduce:** Double click on a plain text file.

I have installed GPMDP from the official 64 bit RPM, and every time I try to open a plain text file, this application is used and fails. I think this is because this line is present in the `/usr/share/applications/google-play-music-desktop-player.desktop` file:

`MimeType=text/plain;`

Could you remove that file association?

Thank you.

**Comment by MarshallOfSound** [comment]
> Could you remove that file association?

I have no idea how 😆 

I've probably set a bad option in one of the packagers I use. I'll look in to it 👍
