### ISSUE TITLE
Focus on Media Keys

### ISSUE THREAD

**Issue by Xedecimal** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1865]
**OS:**

Windows 10

**Issue Descriptions:**

When using media keys, now the window is activated. This started happening the moment I upgraded.

**Steps to Reproduce:**

When the window isn't hidden, press play/pause and the window will take focus. This can get annoying if you're doing something else while listening to music.

**Comment by MarshallOfSound** [comment]
I can not reproduce the issue on Windows 8 or Windows 10

Can you provide a screen capture of what you see occurring

**Comment by k1sul1** [comment]
I'm running W10 on one of my devices too, but couldn't reproduce. 

Media keys work just fine, and there are no issues with focus.

Might be worth mentioning that media keys set to my mouse from Logitech Gaming Software do not work at all on this app (for me), but do work on Spotify. 

Native media keys on my keyboard do work just fine.

**Comment by Xedecimal** [comment]
Sorry, I'm a moron. This was due to software on my laptop. Your app is still flawless!
