### ISSUE TITLE
YouTube Button in Mini Player

### ISSUE THREAD

**Issue by Preston159** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#187]
In the controls in the mini player is the same YouTube button which appears in the full-sized music player.  However, when clicking this button, the YouTube video begins to play, but audio only (which isn't only broken behavior, but against the YouTube API's ToS).  It then becomes impossible to pause the YouTube audio without first switching back to the full-sized player.  In addition, upon switching to the full-sized player, the YouTube video is anchored to the top left of the player rather than being centred as it is when clicking the button in the full-sized player.
![image](https://cloud.githubusercontent.com/assets/7246571/13162834/31be9e64-d66d-11e5-8d8d-ca642e50c7f0.png)

**Comment by MarshallOfSound** [comment]
OK so first off, casually landing the YouTube API ToS reference wasn't cool man... I don't even use the YouTube API so lets slow down with the ToS nonsense.

With that out of the way, this is semi relevant to 
https://github.com/MarshallOfSound/gmusic-mini-player.js/pull/1

The logic required to fix this would have to go into https://github.com/MarshallOfSound/gmusic-mini-player.js but unfortunately I do not have access to this "youtube button" so can't test anything....

If you want to take a shot at a PR into that mini player library I'll take a look and review it.  Other than that, not much I can do here.  If you don't want to try fix it please raise it again as an issue on [this repo](https://github.com/MarshallOfSound/gmusic-mini-player.js/)

**Comment by Preston159** [comment]
I apologize for trying to be helpful, I'll be sure to refrain from it in the future.

**Comment by MarshallOfSound** [comment]
@Preston159 And sarcasm like that really isn't needed.  My point was simply that you basically accused me of publicly breaking the ToS of a product I don't even use...

**Comment by Preston159** [comment]
That wasn't my intent; my intent was to politely warn you in case you were because I hadn't checked.
