### ISSUE TITLE
Add Logarithmic volume controls

### ISSUE THREAD

**Issue by Mishkun** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1870]
I'm hearing music on very loud speakers (~150W) and previously I was using AIMP3, which let me to adjust volume in logarithmic scale so I could use more robust volume control. Now with GPMDP I need to wiggle the slider between 1 and 2 to not get deaf.

I found this article explaining the issue in average.
https://www.dr-lex.be/info-stuff/volumecontrols.html

**Comment by MarshallOfSound** [comment]
I'm like 99.99% sure this can't be done (HTML5 Audio elements are built to have a linear volume scale) also Google handles the volume side of things internally.

I'll look into it when I get a chance but I wouldn't hold much hope 👍

**Comment by MarshallOfSound** [comment]
So I was correct, HTML5 + logarithmic scaling just isn't going happen when GPM is tied to the events coming off the Audio element.  If you have full control of everything you can fake the logarithmic control, but we don't, so we can't 😢

**Comment by brainstorm42** [comment]
Sad to see this isn't possible. Can't the slider position be faked instead?
