### ISSUE TITLE
Updates reset "On" setting for icons in taskbar/notification area.

### ISSUE THREAD

**Issue by akanimh** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1872]
**OS:**
Windows 10
**Issue Descriptions:**
Updates reset "On" setting for icons in taskbar/notification area.
**Steps to Reproduce:**
Go to Settings, Personalization, Taskbar. Scroll down and click on "Select which icons appear on the taskbar". Locate Google Desktop Player in the list. Choose "On." Wait till, or update Google Desktop Player. Return to Settings, and a new Google Desktop Player will be on the list with the default "Off" selected.

**Comment by MarshallOfSound** [comment]
This is how Windows works.  The update is technically a new executable so it doesn't "reset" the setting.  It simply thinks it is a new exe file.

Nothing I can do about it on my side of things 👍
