### ISSUE TITLE
[req] Hotkey for I'm Feeling Lucky

### ISSUE THREAD

**Issue by brandinimp** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1874]
Hi,

I usually have my player minimised to the tray, and it would be nice to start music without actually maximising it.
Please could you add the ability to map a hotkey to trigger the I'm Feeling Lucky button?

Thanks,
B

**Comment by MarshallOfSound** [comment]
See #1307 for reasons as to why this can't be done
