### ISSUE TITLE
Lyrics BETA - Matching wrong lyrics for songs with the same name from different artists

### ISSUE THREAD

**Issue by gabrielchites** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1879]
**OS:**
Windows 10 Pro

**Issue Descriptions:**
The lyrics being shown are from a music of the same name from a different artist. 

**Steps to Reproduce:**
Play Hearts on Fire by Hammerfall. (https://play.google.com/music/listen#/album/B5vvdmtfi55k354z7kbj722tiqa)

Lyrics displayed:
https://play.google.com/music/preview/Tuuwgqyraka5ragzuuzqts7ujoy?lyrics=1&utm_source=google&utm_medium=search&utm_campaign=lyrics&pcampaignid=kp-lyrics

Lyrics expected:
https://play.google.com/music/preview/Tmxhv5526vni572mrmbqt2pn2x4?lyrics=1&utm_source=google&utm_medium=search&utm_campaign=lyrics&pcampaignid=kp-lyrics

This program rocks! 😄

**Comment by MarshallOfSound** [comment]
There is nothing we can do about this.  We don't use a lyrics API to fetch lyrics we have basically a lyrics spider in every client that attempts to find the lyrics on a number of sites.  On some sites we can't verify the artist so we use them as last resort and hope that we're right.  It's quite rare that we're wrong but as you can see in some cases it pulls the wrong lyrics.

Unless someone has a clever heuristic to analyze these lyrics sources for the artist their isn't much we can do.
