### ISSUE TITLE
Zillya virus?

### ISSUE THREAD

**Issue by scheidell** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#188]
you never know, and I guess I could take the source and compile it myself, if I loaded all the tools, but virustotal.com reports this might have the zillya virus.

https://www.virustotal.com/en/file/3e74a4ec4594209ab507e99ad68de4a37ce29dc038ea3df2c6c719d616b3992d/analysis/

**Comment by MarshallOfSound** [comment]
Yet another false positive.

Similar to #131 and #11 

To be honest virus total gets more false positives than accurate readings....

And you are correct, if you lack the faith that I'm not malicously infected thousands of computers you can build it yourself from source :+1:

**Comment by nicballarini** [comment]
+1, due to zika virus, all pregnant women should avoid installation.
