### ISSUE TITLE
Mini player control doesn't stay adjusted

### ISSUE THREAD

**Issue by Brodieman** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1880]
![capture](https://cloud.githubusercontent.com/assets/13592675/20143042/eb0aaede-a65c-11e6-94e5-3d8799e9118b.PNG)
As shown in the attached picture, the mini player controls are off screen.

**Comment by MarshallOfSound** [comment]
It looks like you may have zoomed in manually (With Control +).

I can't repro this on my machines without manually zooming in exactly once, and then it looks identical to your image.  Can you ensure you don't have any thrid part window scaling activated and you haven't zoomed the window.

**Comment by Brodieman** [comment]
I don't believe I did zoom in. I noticed it comes and goes too. Sometimes I
hover and it's right the next time it's not.

**Comment by Brodieman** [comment]
I just tried to use control + and control - and it doesn't even zoom in or
out.

And as I said last night, it comes and goes.

If it helps I am running Win 10 x64 enterprise

**Comment by MarshallOfSound** [comment]
> I just tried to use control + and control - and it doesn't even zoom in or
out.

That implies it is the same zoom / scale /weirdness I just fixed in #1777.  Next release should handle the weird scaling.

**Comment by Brodieman** [comment]
Awesome, thanks!
