### ISSUE TITLE
Weird screen flicker bug on my Windows 10 machine

### ISSUE THREAD

**Issue by TristanP13** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1884]
**OS:** Windows 10 Enterprise (x64) on version 1607

**Issue Descriptions:** I attempt to hover over certain elements and it does a strange thing where it flickers and selects other elements at the same time.

I can explain this bug better with a video, which is below:
https://www.youtube.com/watch?v=ac3kv7CpDBk

Debug info below:
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/584866/debug_info.zip)

**Steps to Reproduce:** I'm not entirely sure how it wound up doing this, but I've tried uninstalling and reinstalling on the machine multiple times and have wiped anything I could find from AppData to no avail.

**Comment by MarshallOfSound** [comment]
Duplicate #1777

Fixed in master
