### ISSUE TITLE
Feature Request/Bug: Close/Minimize to Tray

### ISSUE THREAD

**Issue by VuthMuul** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1887]
**OS:**
Windows 10 64bit

**Issue Descriptions:**
The "minimize to tray" setting is misleading as it is actually close to tray, minimize just minimizes. Either changing it to say "close to tray", or have the minimize button go to tray, and close actually close would be appreciated.

**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment]
Minimize to tray is what most other application call it even though you are correct that it technically "closes" to tray.  I feel sticking with the standard is what people will expect.  Just googling "Minimize to tray" and "Close to tray" will yield basically the same results (that all say "minimize to tray")

Although not literally correct I believe it should stay as is.

**Comment by MarshallOfSound** [comment]
As a further note, the action is explained the first time you click the close button 👍

**Comment by PunchyRascal** [comment]
I think @VuthMuul  is right, I just wanted to report a bug that "minimize to tray" does not work until I read this. I would indeed expect it to hide to tray when minimized. Closing to tray is fine as well.
