### ISSUE TITLE
Last.fm Not Authorizing, Won't Let Me Sign In

### ISSUE THREAD

**Issue by DorkChopDX** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1888]
OS: Windows 10 Home
Running the latest version of the GMDP (4.0.2) 

Issue Descriptions: Noticed this morning that my scrobbles were not being counted. This has happened before and the solution was usually to just reauthorize my account. When I've tried to do this with the latest version of the program, it simply hangs and after 30-45 seconds, continues to ask me to log into my account. 

Have reinstalled & tried clearing all temporary files a few times now, with no success.

**Comment by MarshallOfSound** [comment]
Mine works still and even un-authorizing and authorizing again works as expected.  I suspect either last.fm is having issues (again) or your net is playing evil tricks on you.   My logs also only show a few last.fm errors mostly to do with DNS resolution and those error counts are within normal ranges.

I would suggest trying again tomorrow 😆 or uninstall and reinstall and see if blasting the cache helps 👍
