### ISSUE TITLE
Non-topmost splashscreen

### ISSUE THREAD

**Issue by abluescarab** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#189]
It's not that big a deal, but the splashscreen on top of everything is kind of a minor annoyance. I'm not sure if anyone agrees with me, but I figured I would submit it as a request anyway. Plenty of applications have splashscreens that are _not_ above other windows.

Thanks!

**Comment by MarshallOfSound** [comment]
The splash screen is not there in version `3.0.0` so I am going to mark as fixed.

`3.0.0` will be releasing soon
