### ISSUE TITLE
Prevents Macbook from Sleeping

### ISSUE THREAD

**Issue by agzam** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1890]
**OS:**
ProductName:    Mac OS X
ProductVersion: 10.11.6
BuildVersion:   15G1004

**App ver:**
4.0.2

**Issue Descriptions:**
App seems to be preventing Macbook from sleeping, even when it's not playing anything:

this is pmset's output:

    pmset -g assertions
    2016-11-13 20:47:31 -0800
    Assertion status system-wide:
      BackgroundTask                 0
      ApplePushServiceTask           0
      UserIsActive                   1
      PreventUserIdleDisplaySleep    0
      PreventSystemSleep             0
      ExternalMedia                  0
      PreventUserIdleSystemSleep     1
      NetworkClientActive            0
    Listed by owning process:
      pid 198(coreaudiod): [0x000030f200010230] 01:17:57 PreventUserIdleSystemSleep named: "com.apple.audio.AppleHDAEngineOutput:1B,0,1,1:0.context.preventuseridlesleep"
            Created for PID: 11635.
      pid 106(hidd): [0x0000432a00090479] 00:00:12 UserIsActive named: "com.apple.iohideventsystem.queue.tickle"
            Timeout will fire in 887 secs Action=TimeoutActionRelease
    Kernel Assertions: 0x10c=USB,BT-HID,MAGICWAKE
      id=501  level=255 0x4=USB mod=12/31/69, 4:00 PM description=com.apple.usb.externaldevice.14100000 owner=Kinesis Keyboard Hub
      id=502  level=255 0x4=USB mod=12/31/69, 4:00 PM description=com.apple.usb.externaldevice.14130000 owner=2.4G Wireless Mouse
      id=503  level=255 0x8=BT-HID mod=12/31/69, 4:00 PM description=com.apple.driver.IOBluetoothHIDDriver owner=BNBTrackpadDevice
      id=504  level=255 0x100=MAGICWAKE mod=12/31/69, 4:00 PM description=en0 owner=en0
    Idle sleep preventers: IODisplayWrangler

**Comment by MarshallOfSound** [comment]
This is standard Chromium behavior (it does a similar audio lock on windows) so there isn't anything we can do about it

**Comment by agzam** [comment]
Oh, ok. Although I think this is somewhat recent. Do you think it could be related to this bug?
https://bugs.chromium.org/p/chromium/issues/detail?id=664462

**Comment by MarshallOfSound** [comment]
I doubt it, that appears to be WebRTC not the audio lock
