### ISSUE TITLE
4.0.2 no scrobbling to last.fm

### ISSUE THREAD

**Issue by slano** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1891]
**OS:**
Linux Mint 18 Sarah MATE 64-bit

**Issue Descriptions:**
Even though Last.FM Status is Authorized songs are not scrobbled to Last.FM service.

[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/588897/debug_info.zip)

**Comment by MarshallOfSound** [comment]
Do you have a proxy / VPN?

**Comment by slano** [comment]
No proxy/VPN, I'm using direct connection.

**Comment by KristupasSavickas** [comment]
Working fine for me.

**Comment by cristianmtr** [comment]
Had the same issue yesterday evening. Had to log out of last fm and log back in

**Comment by MarshallOfSound** [comment]
Normally just logging out and logging in will help.  Last.FM sporadically kills off access tokens so there isn't much I can do :{
