### ISSUE TITLE
Packaging for Solus

### ISSUE THREAD

**Issue by FedoraTipper** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1892]
**OS:**
Solus 

Hey Guys,

Is it possible to build for Solus's eopkg manager? Josh, the community manager, has tried but he gets an error when attempting to package it. [link](https://dev.solus-project.com/T469) There are few of us really wanting to use this on Solus.

**Comment by MarshallOfSound** [comment]
@FedoraTipper I have 0 clue how `eopkg` or Solus operates and to be honest I don't have the time / energy to find out 😆 

> Closing as WONTFIX because it falls on its face during build by creating recursive directories to the point it is actually creates a ENAMETOOLONG.

That seems like he is trying to build with an old version of `npm` / `node` that doesn't have flat pacakging.  If you can explain (or he can explain) what I need to do to generate an `eopkg` I can try make one as a release artifact

**Comment by MarshallOfSound** [comment]
Closing out, any discussion RE this can take place in Gitter

**Comment by saintdev** [comment]
For what it's worth, I was able to reproduce this attempting to build in a Ubuntu (16.10) docker container. Using node v6.9.1 from the official installer. `electron-packager` recursively extracts itself until into its own directory. During that, it attempts to remove some files and runs into `ENAMETOOLONG` while unlinking some files.
