### ISSUE TITLE
debug.log file gets HUGE

### ISSUE THREAD

**Issue by mchonan1996** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1893]
**OS:**
Windows 10

**Issue Descriptions:**
The debug.log file is **HUGE**, mine took up around 1.4GB on disk.

**Steps to Reproduce:**
Simply use the app as intended. I've had it installed for around 1.5 weeks.

**Comment by KristupasSavickas** [comment]
Working fine for me.

**Comment by MarshallOfSound** [comment]
heh

You must be the poor sod taking up all of my Sentry bandwidth.  Can you upload a small portion of the error file (maybe the first 1000 lines) so I can see the error you are getting.  You are almost certainly getting stuck in a recursive error loop somewhere 😢

**Comment by MarshallOfSound** [comment]
ping

**Comment by MarshallOfSound** [comment]
Closing until the information is provided
