### ISSUE TITLE
Dark Theme + New Google Play - Unreadable top menus

### ISSUE THREAD

**Issue by trashhalo** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1897]
**OS:**
Mac OS X

**Version:**
4.0.3

**Issue Descriptions:**
Dark theme with new google play music 11/14 has unreadable text.
![screen shot 2016-11-14 at 11 01 55 am](https://cloud.githubusercontent.com/assets/177491/20271823/0a43183a-aa5a-11e6-82fc-eed6f6bd85e7.png)

**Steps to Reproduce:**
1. Make sure you are using the new google play
2. Change your theme to dark
3. Click Music Library

**Expected Behavior:**
I can read text.

**Actual Behavior:**
Darkness.

**Comment by MarshallOfSound** [comment]
See https://github.com/gmusic-utils/gmusic-theme.js/issues/60
