### ISSUE TITLE
The "forward" and "back" buttons on a mouse do not function.

### ISSUE THREAD

**Issue by MTRougeau** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#19]
The side buttons on a mouse, commonly used to navigate forwards and backwards on websites, do not function in GPMDP. The user is forced to use the backspace key to navigate backwards. This issue does not exist in the web version of Google Play Music.

**Comment by hndmrsh** [comment]
Importantly, the Back button no longer exists in the title bar of the new theme, so there is no way to go back.

**Comment by MarshallOfSound** [comment]
The back / forward buttons in the UI have been added back in.  The forward and back buttons on the mouse appear to be stolen by whatever browser is open.  I can't seem to receive the keypress events.

**Comment by MarshallOfSound** [comment]
The lines to add and try make work are

`gkh.HookedKeys.Add(Keys.BrowserBack);` and `gkh.HookedKeys.Add(Keys.BrowserForward);`

**Comment by MTRougeau** [comment]
@MarshallOfSound Interesting....I can't get the forward/back buttons on the mouse to work, even with the browser completely closed.

**Comment by MarshallOfSound** [comment]
@MTRougeau Well the version installed isn't trying to listen to them.  But when I add them as keys to listen to in `CoreMusicApp.Hooks.cs` it doesn't recieve the keypresses no matter what I do.  If you want  you can play around and see if you can get it to listen to those keys.

**Comment by MTRougeau** [comment]
Yeah, I'll pull of the project and see if I can figure something out.
