### ISSUE TITLE
Glitches in mouseover/focus for Google Play Music UI elements.

### ISSUE THREAD

**Issue by infernocloud** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1901]
**OS:**
Windows 10

**Issue Descriptions:**
Mouseover CSS effects and hover states seem to be having lots of problems. I believe this started 2 or 3 updates previous and none of the subsequent updates have fixed this. When trying to mouseover anything in the main Google Music interface (track, album, playlist, etc.) the interface will sometimes show the correct item as being targeted but then it will constantly glitch between it and another item in the interface as the mouse moves. This makes knowing if I've selected the correct item(s) very difficult.

I've uploaded a video capture of what is happening: https://www.youtube.com/watch?v=scq1PATEbn8

[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/590004/debug_info.zip)

**Steps to Reproduce:**
For me, it happens with every interactive element in the main GPM interface every time I open the Desktop app. See video for example.

**Comment by MarshallOfSound** [comment]
4.0.3 released today fixed this issue.  Your debug file indicated you are still on 4.0.2

**Comment by infernocloud** [comment]
Just got it! Thank you.
