### ISSUE TITLE
Changelog in different languages

### ISSUE THREAD

**Issue by ChrisB9** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1906]
**OS:**
Every OS
**Issue Descriptions:**
At the moment there is a language medley of for example german and english in the changelog popup.
It would be nice, if there could be a changelog translation file to give non english speakers the possibility understanding each change

**Comment by MarshallOfSound** [comment]
> It would be nice

It would be nice but I don't have the time or resources to make it happen.  Sometimes I have to push updates out instantly (last night for instance) and I don't have time to wait for the changelog to be translated.  It's a nice to have, but I don't see it happening 😢
