### ISSUE TITLE
Search Library/Playlist

### ISSUE THREAD

**Issue by LiquidMechanix** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1907]
It would be awesome to be able to search your music library or a playlist for a certain song or artist. I'm thinking the functionality would work some thing like this:

- Hit Ctrl+Shift+F and/or have a slide up/down.
- It brings up a separate search box in the bottom right corner of the play list or top right of the play list.
- As soon as you start typing it will start narrowing down your current playlist or if you are in the music library to songs, artists, or albums that match.
- Double click to play what ever song as normal.
- Closing the search box returns you to the full playlist or music library in the sort order that you had it before.

**Comment by MarshallOfSound** [comment]
Here's the problem.

1. Shortcut - We can do that
2. Open a search box - We can do that
3. Filtering the playlist / library - We can't do that

The problem with (3) is that google dynamically renders tracks, artists and albums themselves with a strange "only render what is onscreen" rule.  As such we only ever have access to DOM representations of songs that are currently on screen.

On another note, the entire search thing you describe though seems to me exactly how search operates at the moment though.
