### ISSUE TITLE
Not scrobbling the albums information to Last.fm

### ISSUE THREAD

**Issue by Discreto** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#191]
This is a very small bug.

Although the musics are being scrobbled to Last.fm, the album information is not.
So when I go to my Last.fm profile I can see the songs I've listen to but not the albums to which they belong.

Thanks

**Comment by MarshallOfSound** [comment]
This is currently by design, my interpretation of the last.fm API was that it would "fill in the blanks" as it were...

Is this not the case?

**Comment by Discreto** [comment]
Since the album name is an optional field I guess you did not include it.

From last.fm API:
album[i] (Optional) : The album name.

In any case it would be nice as an improvement :)

**Comment by MarshallOfSound** [comment]
I'll try slot this in to the `3.0.0` release

**Comment by MarshallOfSound** [comment]
Lol, turns out it is already implemented in the new `3.0.0` release code.

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/dev/3.0.0/src/main/features/core/lastFM.js#L104

Keep an eye out for that release :+1:

**Comment by Discreto** [comment]
:+1: 
Thanks!
