### ISSUE TITLE
No Thumbs Up/Down Icons in Miniplayer

### ISSUE THREAD

**Issue by livejamie** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#192]
I love everything about GPMDP but one of the larger annoyances is a lack of thumbs up/thumbs down in the miniplayer. 

Is there a fix for this? Right now I have to expand it to normal size, thumbs up, then make it mini again.

It appears that Google moves the shuffle and repeat icons outside of the bar in their version.

For reference

GPMDP:
![image](https://cloud.githubusercontent.com/assets/49513/13319323/c6109d44-db75-11e5-99d6-e20a6f65fa30.png)

Google's Official Chrome App:
![image](https://cloud.githubusercontent.com/assets/49513/13319395/41a5ee00-db76-11e5-892a-762dbbe70450.png)

Would appreciate any help/attention to this.

Thanks!

**Comment by MarshallOfSound** [comment]
This was a design decision, the thumbs up and down buttons appear only when you are listening to a "radio".

There was a long discussion in another issue that I now can't find but the short of it is the thumbs only made sense to have in radio stations.

**Comment by MarshallOfSound** [comment]
As a note though, I believe the thumbs up / down shortcuts still work

**Comment by livejamie** [comment]
Thanks for the prompt response!

I indeed see the issue you're talking about, #18 

The problem with this approach is I'm unable to see if I've given a song thumbs up or not. 

Is there a way I could toggle the "Radio view" as the default view or the view when listening to a playlist? Perhaps in the settings. I don't need shuffle and repeat as often as I need thumbs.

**Comment by MarshallOfSound** [comment]
I'm happy to look into that kind of options :8ball: 

And I'd be even happier if someone took a crack at it :smile: 

Could you please raise this issue as a feature request on https://github.com/MarshallOfSound/gmusic-mini-player.js

**Comment by livejamie** [comment]
You're awesome, thank you!
