### ISSUE TITLE
Logs me out when it is completely closed

### ISSUE THREAD

**Issue by odce1206** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1923]
**OS: Arch Linux**

**Issue Descriptions:**
App works completely fine but when I close the app from the taskbar and open it again, I have to log in again, the app never stays logged in. I have gnome keyring, kde wallet and use Kde Plasma 5.

**Steps to Reproduce:**
Close the app and terminate it from the task bar, open again

**Comment by MarshallOfSound** [comment]
This shouldn't be the case and if it is you probably have something wiping the cache / session data directory.  Unfortunately I have no idea where that is on linux and I can't reproduce this on any of the supported distros I list in the README.  It is probably a OS config issue specific to yourself, I would recommend testing out the raw Electron binary or asking around the AUR package comment section for help from your fellow arch users.  It's not something I am equipped or prepared to help with 👍
