### ISSUE TITLE
Windows Audio Device Graph Isolation High CPU/High RAM

### ISSUE THREAD

**Issue by Avangel27** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1927]
OS: Windows 10

Issue Descriptions:  Windows Audio Device Graph Isolation is eating CPU and RAM when GPMDP is running. It usually sits at 3.6 gb of RAM when I notice it. It happens every time  I use the program.

Steps to Reproduce: Using the GPMDP and listening to music causes high RAM usage. I think it also may have something to do that I have Dolby Digital Plus on my Laptop. I have Lenovo Y50-70.

**Comment by MarshallOfSound** [comment]
This is one of those "Out of my control can't really fix" issues.  You're probably correct and it is something to do with DDP or your audio drivers or maybe even an issue at the Windows level.  But if it isn't even one of my processes eating up the resources there is absolutely nothing I can do about it 😢
