### ISSUE TITLE
White flickering on Retina screen

### ISSUE THREAD

**Issue by SlashmanX** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1928]
**OS:** Mac OS Sierra

**Host OS:** Mac OS Sierra

**Host OS Version:** 10.12.1

**Display Resolution:** 2560 x 1600

**Display DPI:** 227

**Touchscreen:** No

**Issue Description:** Large amount of white flickering in the UI when scrolling or clicking (transitions I think)

**Steps to Reproduce:** Open app on a Retina screen (I'm using Macbook Pro Retina) and basically just use it.

**Video:** https://streamable.com/wa70 (Note that this understates the issue, when not recording it really is a lot worse. Also it happens when 'unthemed' also )

**Version:** 4.0.3

(This is essentially the issue that the #1777 thread was turning into)

**Comment by MarshallOfSound** [comment]
Can you please provide the information I requested at the bottom of #1777 

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/1777#issuecomment-260600459

**Comment by SlashmanX** [comment]
Sorry, I used the issue template instead, my bad.

**Host OS:** Mac OS Sierra

**Host OS Version:** 10.12.1

**Display Resolution:** 2560 x 1600

**Display DPI:** 233 (I think)

**Touchscreen:** No

**Comment by xenio** [comment]
Same problem on Mac Osx Sierra 10.12.1 there was also on Yosemite.
Resolution 2560x1440, hidpi.
If the player is full screen it is unusable, lag, white flash, scrolling is very laggy, some part of the screen is missing.
In a small windows it is much better, but still some lag and white flash.

**Comment by burkeshartsis** [comment]
I'm having the same issue as well. Scrolling on the home screen is pretty janky with a lot of screen flickering. You can see it without any user interaction if you click the album image in the player on the bottom left. 

v. 4.0.3
MacBook Pro (Retina, 15-inch, Late 2013)
macOS Sierra 10.12.1
2560x1440 scaled to 1920x1200 (system preferences > displays > more space)

The flickering appears to go away if opened in "[low resolution mode](https://support.apple.com/en-us/HT202471)." Scrolling is still pretty janky however. Your using Electron so my guess is there is either a paint performance issue or something to do with gpu acceleration.

**Comment by coleHafner** [comment]
+1 for this.

**OS:** OSX El Capitan
**Host OS:** OSX El Capitan
**Host OS Version:** 10.11.6
**Display Resolution:** 1280 x 800
**Display DPI:** 227
**Touchscreen:** No
**Issue Description:** Large amount of white flickering in the UI when doing anything. No scrolling or clicking required. Also does it on my external monitor
**Steps to Reproduce:** Open the app, play a song, bring up the playlist (bottom right playlist icon), wait.
**Video:** Nope, sorry
**Version:** 4.0.3

**Comment by MarshallOfSound** [comment]
Got my new mac today and immediately noticed this issue.  Fix will be out next release 👍

**Comment by justinswart** [comment]
I still have this issue unfortunately:

**OS**: macOS Sierra 10.12.1
**Display Resolution**: 2880 x 1800 (scaled)
**Issue Description**: As above
**Video**: https://drive.google.com/file/d/0B4IKKP-gjxaGZFRFNE42VGV1cWs/view?usp=sharing
**Version**: 4.0.3

This is on a 15" Retina MBP mid-2012 with Intel HD Graphics 4000

**Comment by MarshallOfSound** [comment]
@justinswart Fix is in master, will be out next release (probably going to be `4.0.4`)

**Comment by justinswart** [comment]
@MarshallOfSound awesome! thanks, great app 👍
