### ISSUE TITLE
Add setting to prevent sleep while music is playing.

### ISSUE THREAD

**Issue by will528** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1929]
When a lot of Windows systems sleep, they disable audio output either because the computer is locking or because their audio routes with their HDMI connection. Can there be a setting that keeps Windows from sleeping or turning off the display while music is actively playing in GPMDP? I believe that when you are using the web player in Google Chrome it is able to prevent the computer from sleeping/locking. Thanks!

**OS:**
Microsoft Windows 10 64-bit Build 14393
**Issue Descriptions:**
Computer sleeps when playing audio.
**Steps to Reproduce:**
N/A, dependent on Windows settings.

**Comment by MarshallOfSound** [comment]
Just to be clear, this would stop the device from turning off the display entirely.  It wouldn't be implementing the background audio feature found on some Surface Pro and other windows devices.

**Comment by will528** [comment]
Yes, that is correct. Just a checkbox with something along the lines of "Prevent this device from entering sleep mode while audio is playing."
Chrome already does this passively with YouTube and GPM; so it would be a nice option to have on GPMDP.

**Comment by MarshallOfSound** [comment]
If anyone wants to tackle this all you have to do is add another `ToggleableOption` to a settings page somewhere and use the `powerSaveBlocker` in the main process 👍
