### ISSUE TITLE
Possible but difficult to select text in miniplayer

### ISSUE THREAD

**Issue by ScottBeeson** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1930]
https://i.imgur.com/qnCqizy.png

I initially did it as an accident and couldn't figure out how to deselect it.  Only after coming here and trying to reproduce it did I figure out you have to click and drag at a very specific location.  Essentially, _just below_ where you get the vertical resize arrow.  Or, as it turns out, just _inside_ the borders on any edge.

I can post a gif if absolutely necessary.

**Comment by MarshallOfSound** [comment]
Yeah I noticed this a while back when testing a dragging thingy.  I can't stop it happening 😢 

I've added the `user-select: none` CSS but for some reason there is an element that is selectable still.  I believe it is something to do with GPM's auto-injected shadow DOM and will hopefully be fixed as they slowly but surely remove their shadow-dom usage 👍
