### ISSUE TITLE
Windows notification/toast includes namespace?

### ISSUE THREAD

**Issue by ScottBeeson** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1931]
![image](https://cloud.githubusercontent.com/assets/108358/20402772/b9843214-acc3-11e6-8dce-7ca94efad4b3.png)

Should either be replaced with "Google Play Music" or removed?

**Comment by MarshallOfSound** [comment]
This is a bug with windows where sometimes it doesn't translate the AppUserModelID to a Application Name correctly.  Normally a relaunch or a reboot clears up the issue 👍
