### ISSUE TITLE
Bose QC25 center media button (play/pause) no longer working

### ISSUE THREAD

**Issue by lsim** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1932]
**OS:**
macOS Sierra (10.12.1)

**Issue Descriptions:**
I used to be able to control this app (play/pause - and I think skipping worked too) with the media button on the cable of my Bose QC25. The headset broke and my replacement came with an android cable - so for some months I was unable to use the buttons at all. Today I swapped the cable with a colleague. Connecting with the apple cable and pressing the center button brought up a prompt to enable siri :/

I eventually enabled siri to get rid of the prompt, but now nothing happens when I short press the button. Long pressing brings up siri. 

The headset volume buttons are working (turns OS volume up/down)

My feeling is that apple screwed you over somehow - maybe something to do with siri.

**Steps to Reproduce:**
Connect headset with play/pause button (Bose QC25 with apple cable) -> press button

Thanks for an awesome app. I waited for years for a working desktop player for google music .. this player works so well!

**Comment by MarshallOfSound** [comment]
> My feeling is that apple screwed you over somehow - maybe something to do with siri.

You are correct 👍 Apple does not allow third party applications to listen for headset buttons 😢
