### ISSUE TITLE
Iconography on the task bar is incorrect

### ISSUE THREAD

**Issue by Chromelon** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1935]
**OS:** Windows 10 Pro

**Issue Descriptions:** Icon has what looks like broken pixels on the taskbar but not on any other iconography.

**Steps to Reproduce:** Launch the program.

Pic: http://i.imgur.com/KOwOrAz.png (zoom in to view the "broken" pixels)

**Comment by MarshallOfSound** [comment]
Welcome to the world of Windows rendering bugs.  Nothing we can about this, we are providing a valid and complete icon file to the OS and if the OS renders it incorrectly on some systems I can't fix that.  You should possibly raise this through Windows 10's feedback portal

**Comment by Chromelon** [comment]
Oh, damn it windows.
