### ISSUE TITLE
Audio stops after a few minutes

### ISSUE THREAD

**Issue by N3oNoi2** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1939]
Since the latest updated the audio will stop every few minutes or so.... then, sometimes, I'd also have to go into the player-settings and change my audio output back to default, because it switched to an entry at the top of the list.
This does NOT happen all the time. Sometimes it just stops and easily restarts after hitting the playbutton again.... though it's kinda annyoing, since you're not able to listen to a song in full.... 

As this has happened never before... anyone else having the same problem?

**Comment by MarshallOfSound** [comment]
The only reason the the audio device would change is if the audio device was "removed" and "added" again.  This can happen without you even knowing when you have poor drivers or if you are using virtual audio devices.  I would suggest looking at updating your audio drivers 👍
