### ISSUE TITLE
[Bug] When using dark custom theme, artist background image is not shown

### ISSUE THREAD

**Issue by Marwelln** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1940]
**OS:** 

Windows 10
GPMDP version: 4.0.3

**Issue Descriptions:**

When using dark custom theme, artist background image is not shown.

Dark: http://i.imgur.com/XgCU0Hw.png

Light: http://i.imgur.com/ENKkPq3.png

**Steps to Reproduce:**

Go to `Desktop Settings` -> `General` and choose `Dark` theme, artist background is then hidden.

**Comment by MarshallOfSound** [comment]
Duplicate #1938
