### ISSUE TITLE
Horizontal tab menu text hard to see in Dark theme

### ISSUE THREAD

**Issue by scprek** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1946]
**OS:**
MacOS - Sierra 10.12
MacBook Pro (Retina, 13-inch, Early 2015)
Tried on laptop screen, and 2 other monitors. Issue persisted. 

**Version Info:**
About Google Play Music Desktop Player
Version: 4.0.3

**Issue Descriptions:**
In the views "Music Library", "Podcasts", and "Browse stations" I noticed the horizontal tab selection text and underline indicator does not modify with the theme. That's fine, but in dark theme the text is really hard to read. For "Music Library", the issue goes all the way across to the right side that has "N Playlists" and "Shuffle"

_For reference in description of issues:_
- Select the 3 horizontal bars in upper left and pick a view say "Music Library"
- Horizontal tab selection text = "PLAYLISTS", "STATIONS", "ARTISTS", "ALBUMS", ....

**Steps to Reproduce:**
1. Open say "Music Library"
2. Open up preferences
3. Select Custom Theme
4. Select Light mode
5. Change colors and notice the underline indicator under the horizontal tab text doesn't change color. (Not a big deal)
6. Switch to Dark theme and see how hard it is to read the horizontal tab text.

Screenshot: Underlined text is near unreadable "Playlists" to "Shuffle"
![screen shot 2016-11-21 at 4 27 25 pm](https://cloud.githubusercontent.com/assets/2783947/20503266/701a5f6c-b007-11e6-9608-0f00c3202b57.png)

**Comment by MarshallOfSound** [comment]
Duplicate / fixed in master.  Please check closed issues before posting
