### ISSUE TITLE
Desktop Setting Issue Ver. 4.0.3

### ISSUE THREAD

**Issue by axv136** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1948]
**OS:** Microsft Windows 10

**Issue Descriptions:** When updated from previous version GPMDP theme was broken, background was white and text for some playlists were illegible. When I tried to fix the color issue Desktop Settings, when clicked would not appear. I reinstalled GPMDP and the back color reverted to the dark theme, however Desktop Setting still will not appear.

Additionally,  taskbar icon not appearing.

**Steps to Reproduce:**
Open menu click Desktop Settings. 

![image](https://cloud.githubusercontent.com/assets/23661890/20532782/27ff7ae4-b0a9-11e6-82b5-8cda316425f3.png)

**Comment by MarshallOfSound** [comment]
Please provide the debug zip file.  Instructions to generate the file can be found in the FAQ

**Comment by axv136** [comment]
Hey, 

I am on a Windows PC and am unable to generate the debug file using ctrl+shift+g. 

Please advise.

Thanks

**Comment by andrewgraff** [comment]
I can second this issue. It occurs when using the dark theme. Album/radio station names and the back button aren't visible against the grey background. Here's the debug_info.zip for mine.
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/607212/debug_info.zip)

**Comment by MarshallOfSound** [comment]
Please upload the error log found at `%APPDATA%\Google Play Music Desktop Player`.  The log file should be called `gpmdp.log`

**Comment by axv136** [comment]
Hello,

Sorry for the delay.

Attached.
[gpmdp.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/615358/gpmdp.zip)

**Comment by MarshallOfSound** [comment]
Closing out as `4.1.1` had a bump that should / might / could handle this (and this is now a stale issue)
