### ISSUE TITLE
Proxy Authentication Required (407) causes crash at startup

### ISSUE THREAD

**Issue by zigfreid5** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#195]
When behind a proxy, a 407 error is returned, and the application is unable to continue. This occurs right at the splash screen.

System.Net.WebException was unhandled
Message: An unhandled exception of type 'System.Net.WebException' occurred in System.dll
Additional information: The remote server returned an error: (407) Proxy Authentication Required.

![gpmdp crash](https://cloud.githubusercontent.com/assets/4284140/13466169/0532281e-e056-11e5-8611-b4174908be5d.png)

**Comment by MarshallOfSound** [comment]
This issue has been around for a while, but it will be fixed in the move to electron as part of 3.0.0

If you want to test those builds to be sure (I've checked but you can as well if you want).  Just join the gitter room from the readme and scroll up to the latest beta link.
