### ISSUE TITLE
Debian package seems ancient

### ISSUE THREAD

**Issue by egh** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1950]
**OS:**
- Debian
- Ubuntu

**Issue Descriptions:**
- Debian repo out of date

**Steps to Reproduce:**

- Follow the steps in https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/docs/Installation_On_Debian.md

**Actual result**
- Old version (3.2.4) installed

**Expected result**
- Latest version (4.0.3) installed

**Comment by jostrander** [comment]
t appears that Debian is fine, however trusty is outdated. I'm not sure how bintray handle's that as @MarshallOfSound set it up. However https://dl.bintray.com/marshallofsound/deb/dists/debian/main/binary-amd64/Packages is showing the 4.0.3 Version and trusty is not.

**Comment by egh** [comment]
I just retried on debian testing and 3.2.4 is installed. I believe this is because multiple versions are listed in the `Packages` file.

**Comment by MarshallOfSound** [comment]
Handles in #1951

Basically use the `trusty` channel 👍

**Comment by egh** [comment]
Fixed, thank you!

**Comment by rattboi** [comment]
Can we get this updated to current (4.0.5)?
