### ISSUE TITLE
Full Player Window Position Resetting After Exiting Mini Player

### ISSUE THREAD

**Issue by Something7894** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1952]
**OS:** 
Windows 10 Pro 1607 x64

**Issue Descriptions:**
When exiting the mini player and showing the full player, the full player does not remember where it was last positioned and its position is reset.
I made a [thing](https://gfycat.com/SophisticatedSecondKitfox) in an attempt to show what I mean.
You can see the full player's position has changed while the mini player's position remained where it was last positioned.

**Steps to Reproduce:**
1. Show mini player.
2. Show full player.

[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/610199/debug_info.zip)

**Comment by MarshallOfSound** [comment]
Your big player is quite close (and possibly over the edge of the screen).  We reset the position if we think the position of the player is off-screen to stop the player disappearing.

👍

**Comment by DyKrass** [comment]
My full play is exactly mesh with the corner of the screen as that is how it snapped to it.
[Here](http://i.imgur.com/szakANv.png) is a screenshot of it.
