### ISSUE TITLE
Don't force on Mac hotkeys

### ISSUE THREAD

**Issue by birgit-gyg** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1954]
**OS:**
macOS Sierra
**Issue Descriptions:**
Please only bind GPMDP to the keyboard's music keys, if it has been the latest program in focus. Right now it forces the binding to the keys, therefore, switching to other music programs and using the keys for them doesn't work.
**Steps to Reproduce:**
Run GPMDP and make sure the keyboard's music keys work. Switch to e.g. iTunes and start a song. Try to pause the song using the keyboard's pause key.
Expected behaviour: Now the keys are bound to iTunes, because it was the latest program in use.
Current behaviour: The keys still only influence GPMDP.

**Comment by seanbeaton** [comment]
This wouldn't work if you, for example:

- Were using GPMDP
- Switched to chrome
- Switched to a text editor
- Tried to pause your music

Instead, it would need to somehow detect if any of the more recent programs are media programs, and if so, unbind the keys.

**Comment by MarshallOfSound** [comment]
> Instead, it would need to somehow detect if any of the more recent programs are media programs, and if so, unbind the keys.

Which is impossible 👍 This request is somewhat impossible.  The idea of global hotkeys is that only one application can use them at a time.  Otherwise hitting the play/pause button would cause all your applications to trigger.  The best I can suggest is if you want to use both quit one before opening the other.

**Comment by birgit-gyg** [comment]
It's working for switching between iTunes, Spotify and any other non-music programs, so I don't think it's impossible. However, I can't find a documentation about the functions they use. If you don't know either, it's fine to close the issue. 
Thanks for replying :)
