### ISSUE TITLE
Hide/disable song title notification

### ISSUE THREAD

**Issue by sadortun** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1955]
**OS:**  
Windows 10

**Issue Descriptions:**
Hi,

We do not always want to have to song information displayed on screen on every new songs, and there is currently no way to disable the notification on screen.

Would it be possible to : (one of the following)
- Add a configuration option to disable all notifications and pupup when a new songs start.
- or; When clicking on the X to hide the notification, stop to display them until the application restart.

**Steps to Reproduce:**
1. Press play
2. Wait for a new song
3. Notification display with the new song title

Thanks,
Samuel

**Comment by MarshallOfSound** [comment]
This setting is controlled by Google play music itself.  Turn it off in their settings

**Comment by sadortun** [comment]
Awesome, thanks !
