### ISSUE TITLE
Please add recurring alarm option

### ISSUE THREAD

**Issue by KruyKaze** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1956]
Thanks

**Comment by MarshallOfSound** [comment]
I'm sorry, I'm normally quite lenient on the whole issue template / contributing guidelines thing.  But this issue takes the cake.

* It doesn't follow the template
* The title isn't a title, it's barely a request
* The description is a single word....

Please familiarlize yourself with the [contributing guidelines](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/CONTRIBUTING.md) and open a new feature request issue with better information.
