### ISSUE TITLE
Feature request: Add "I feel lucky" button to the small player like in Google's mini player

### ISSUE THREAD

**Issue by electrolobzik** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1958]
**OS:** 
Mac

**Issue Descriptions:**
Google standard mini player contains "I feel lucky" button which reloads I feel lucky radio without need to open main page. Is it possible to add the same to the mini player in the app?

**Comment by MarshallOfSound** [comment]
@electrolobzik This can be tracked over in https://github.com/gmusic-utils/gmusic.js/issues/16
