### ISSUE TITLE
Mini player album art low resoulution

### ISSUE THREAD

**Issue by Poiii** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1959]
OS: Windows 10

Issue Descriptions: When I open the mini player the album looks fine, high quality, but after not long the album cover gets all pixelated and bad looking.

Steps to Reproduce: When listening to a song open Mini Player and wait for atmost 30 seconds and the cover gets all pixelated.

**Comment by MarshallOfSound** [comment]
This is a known Chromium issue on some systems.  It will be fixed in the next major bump in chromium
