### ISSUE TITLE
Cannot zoom anymore

### ISSUE THREAD

**Issue by tuur29** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#196]
The ability to zoom in or out with ctrl+ or ctrl- was removed in the 3.0 update

**Comment by MarshallOfSound** [comment]
Thanks for the report.  I'll look into this and get back to you :+1:

**Comment by Filip013** [comment]
Thank you for fixing this issue. However, I’d just like to point out that using the +/- sign on the numeric keyboard doesn’t work. I can only manage to zoom in and out using the +/- signs in the second row of the keyboard.
