### ISSUE TITLE
Hovering over cast button gives hint text as "undefined" (en-us)

### ISSUE THREAD

**Issue by charlesdurham** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1960]
**OS:** Windows 10

**Issue Descriptions:** Hover over the cast icon to see the hint text as "undefined"

**Steps to Reproduce:** Hover over the cast icon to see the hint text as "undefined". I assume en-us is translated first, but in-case it's only missing there I reproduced using en-us.

**Comment by MarshallOfSound** [comment]
This isn't our side of things.  The cast button is generated by google.

If we are ever missing a translation we fall back to `en-US` and if it is missing there as well we will return `TRANSLATION NOT FOUND` (or something similar).

This undefined issue is coming from Google's JS
