### ISSUE TITLE
Enable Developer Tools or Inspect for theming

### ISSUE THREAD

**Issue by ronilaukkarinen** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1964]
A Front End Developer here. I would love to have an option to be able to use developer tools to make it easier to make a custom CSS theme, since I'm not an app developer and you have already provided a way to upload your own theme. I didn't see Inspect feature anywhere, so could you add it? If not, what methods do you recommend for creating your own theme?

**Comment by MarshallOfSound** [comment]
Use "Control + Shift + G" (or command on macOS) and type in "DEV_MODE" then click "Go"

The program will relaunch and you can then use the standard dev tools shortcut to launch the dev tools.  To open the devtools for Google Play Music you need to run the command `openGPMDevTools()` in the console of the first dev tools window 👍

**Comment by ronilaukkarinen** [comment]
Oh. Didn't found this in the documentation. Enlightening, thank you!

**Comment by MarshallOfSound** [comment]
Yeah I should probably add it to the FAQ somewhere
