### ISSUE TITLE
Touchbar support for macOS Sierra

### ISSUE THREAD

**Issue by izacus** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1965]
macOS Sierra now has new APIs for global playback control for MacBook models with touchbar. Using them lets users control playback position and skip tracks from anywhere (effectively replacing the missing media keys). See GIF: https://cnet4.cbsistatic.com/img/UsolysTQYPgPtMiSWTK-Dc24JGY=/fit-in/370x0/2016/11/22/190aaf99-eda0-4624-9e7e-8f15aad7f088/scrub-itunes-touch-bar.gif

Having that support in Desktop Player would be great.

**Comment by MarshallOfSound** [comment]
This should be tracked upstream with my PR's up there.

https://github.com/electron/electron/pull/8095

**Comment by izacus** [comment]
Umm, not really since you're not supposed to use the NSTouchBar API for that - but the new global multimedia API added in Sierra (similar to the iOS one), where you need to signal to the OS what you're playing and then handle multimedia events back.

The TouchBar APIs listed in the upstream won't work for that :/

**Comment by MarshallOfSound** [comment]
Okay, totally didn't know that existed.  I'll raise an upstream issue for supporting that new API then :D

**Comment by MarshallOfSound** [comment]
FYI I just got this working in Electron and I'll be raising a PR shortly 👍

**Comment by MarshallOfSound** [comment]
<img width="1085" alt="touch bar shot 2016-12-25 at 10 30 24 am" src="https://cloud.githubusercontent.com/assets/6634592/21468821/09cacec6-ca8e-11e6-8ad2-5de8528403cd.png">

**Comment by allvintage** [comment]
Any news on the touchbar support? The screenshot looks amazing!

**Comment by MarshallOfSound** [comment]
Pending an upstream PR https://github.com/electron/electron/pull/8280
