### ISSUE TITLE
UI broken at 4K resolution

### ISSUE THREAD

**Issue by TheSinding** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1966]
**OS:** Antergos

**Issue Descriptions:** UI Broken at 4K

**Steps to Reproduce:** Get a 4K screen ?

https://ptpb.pw/ysqj

**Comment by MarshallOfSound** [comment]
Appears to be a chromium rendering issue. I saw a fix fly through for an issue similar to this in Chromium 55 so let's see if that helps when Electron gets it.
