### ISSUE TITLE
Feature Request: Auto-playlists

### ISSUE THREAD

**Issue by frenchiejnr** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1967]
Would it be possible to implement the ability to generate smart playlists in the app. Possibly by integrating this chrome extension: https://github.com/simon-weber/Autoplaylists-for-Google-Music

Seems to be open-source, so shouldn't be any legal issues.

**Comment by MarshallOfSound** [comment]
If someone ports that to not require extension API's and makes a PR I would probably accept it.  I am very wary of spoofing GPM rest calls though (which is how that extension works).  I can see it ending badly if google changes their rest URL's at some point.

TLDR:  If someone does it I'll take it, but I'm not going to look into it myself
