### ISSUE TITLE
Media Keys on the Logitech Wave dont work with it. They used to, but after some update it stopped. Tried on mutiple PCs.

### ISSUE THREAD

**Issue by beardofbeespool** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1969]
Windows 10 Pro x64 - Both PCs had this that I tried it on.
This is the keyboard Im talking about:
http://www.logitech.com/en-us/product/wireless-wave-combo-mk550

I have reinstalled the OS on my primary recently, after it stopped working, that did not help.

If I disable the "setpoint software" it will work again, but then I cant setup the additional buttons to thumbs up and down, using the SS.

**Comment by MarshallOfSound** [comment]
Unfortunately there is nothing I can do about this.  SetPoit interferes with media buttons and such in a way that makes be unable to capture them.  I would suggest providing feedback to Logitech about there software.

**Comment by beardofbeespool** [comment]
Thanks for the quick reply @MarshallOfSound. I will do that. Like I said the keys DO work if I disable setpoint.

**Comment by DaveSmith-1** [comment]
You can actually modify the .xml file SetPoint uses for your keyboard so media key presses will pass through to Windows while continuing to use your other SetPoint settings. Details: http://superuser.com/a/888413

**Comment by beardofbeespool** [comment]
@DaveSmith-1 thanks so MUCH. That worked. I have a Logitech Wave K350. That confix xml was located at: C:\ProgramData\Logishrd\SetPointP\Devices\Keyboard\200006D

Hope this helps anyone else with this issue.

**Comment by oharrison72** [comment]
@DaveSmith-1 This needs to be stickied. Worked perfectly on my K800. 

In my case it was here: C:\ProgramData\Logishrd\SetPointP\Devices\Keyboard\2000074\2000074.xml

**Comment by gakera** [comment]
I'm having this problem with my MX Master mouse, I assigned one of the buttons to "Play/Pause" and it works perfectly with the Spotify app but not this. I do not have any SetPoint folder in the Logishrd (durr?) folder, only LogiOptions and Unifying. The Logitech settings app I use to select the options for the MX Master is called Logitech Options.

**Comment by DaveSmith-1** [comment]
@gakera You could search through the files in LogiOptions to see if there is an entry for you mouse model (the file name likely won't match you model#, it will be inside the .xml file). However, I don't know if this fix will work for a mouse button. Unless the button is labeled Play/Pause and Windows recognizes it as such, this fix will only serve to break the button's functionality in your other media apps (Spotify, etc.). More likely, you need to add GPMDP as a recognized media player in one of the other Logitech configuration files.

**Comment by nielsbaan1992** [comment]
I found that turning on these two options solved my problems, my media keys work. They work with Logitech Options as well, haven't tested Setpoint though. I will test that Tuesday at work.
![afbeelding](https://user-images.githubusercontent.com/37951470/38161206-bf8240c6-34ca-11e8-8a8c-4241a0e6eb0e.png)
(Works only in Windows I reckon.)

**Comment by thanosasimo** [comment]
> I found that turning on these two options solved my problems, my media keys work. They work with Logitech Options as well, haven't tested Setpoint though. I will test that Tuesday at work.
> ![afbeelding](https://user-images.githubusercontent.com/37951470/38161206-bf8240c6-34ca-11e8-8a8c-4241a0e6eb0e.png)
> (Works only in Windows I reckon.)

Hi @nielsbaan1992 where are these options? Looking to find a way to use my media keys again with logitech options.
