### ISSUE TITLE
Make lyrics available in app itself

### ISSUE THREAD

**Issue by Meegooo** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#197]
So, I looked into an API and apparently you have lyrics available for third-party apps, but i couldn't find any button that would show that lyrics in app itself. And that feature is not on the [list](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/171) (unless Ctrl+F failed me).

**Comment by MarshallOfSound** [comment]
So yeah, this is like a realllyyy long story but I'll shorten it for you.

TLDR: The lyrics part of the API was an afterthought and is completely unreliable.  It doesn't work for any song newer than late 2015.  Also I'm rubbish at UI design and couldn't come up with a nice way to show the lyrics.

TLDR2: If you / someone else wants to have a go at this by all means.  I'd be interested to see what people come up with. :+1:

**Comment by delold** [comment]
I believe Musixmatch has a API for developers (I think Shuttle uses it internally for lyrics).

**Comment by MarshallOfSound** [comment]
Yeah, but do you have like $10,000 a month or something like that :+1: :cry:

**Comment by delold** [comment]
Oh! Didn't read the TOS carefully. There is also the [Genius API](https://docs.genius.com/) (should have a lot more than wikia).

**Comment by MCManuelLP** [comment]
So I have no real idea how to implement this but I think I have an idea for the UI... I think the lyrics could be displayed like another visualizer, so filling the whole screen, that would give them enough space and they're relatively easily accessible.

**Comment by tehloxely** [comment]
Could the lyrics possibly be overlayed when only showing the album art in fullscreen?

**Comment by MarshallOfSound** [comment]
I've looked into this and as far as I can tell my lyrics "thing" has about an 80% success rate with finding lyrics.  This is probably too low too implement a solid lyrics feature

**Comment by emphaticpuma** [comment]
What if when the lyrics search fails, it just doesn't give the option to view the lyrics in the application, so if the lyrics are available, its good, but if not, nothing bad happens?

I think the best way would be to have a toggleable overlay over everything but the UI (button could be near the queue button or hidden in the radio/instant mix dropdown) that displays the lyrics (could also scroll based on time of the song).

If this is worth implementing I could give it a try, but it would probably take me a long time.

**Comment by SicariusNoctis** [comment]
I don't know if you've looked at this but [this may or may not be helpful](http://stackoverflow.com/a/12158162/365102).
