### ISSUE TITLE
Playlist Switching Colors

### ISSUE THREAD

**Issue by Xedecimal** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1970]
I've noticed that the colors on the playlist switcher aren't caught up in the dark theme. Shouldn't these bit a bit lighter and readable ?

![image](https://cloud.githubusercontent.com/assets/99204/20719227/22bef1ec-b610-11e6-852b-6d625eb0423a.png)

OS: Windows 10
Theme: Dark

**Comment by MarshallOfSound** [comment]
This has been fixed upstream in the turning library
