### ISSUE TITLE
Make possible to use custom theme without forced styles

### ISSUE THREAD

**Issue by ronilaukkarinen** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1972]
After spending couple of hours theming I find it frustrating that some of the styles are predefined. Could you add third option for custom themes, instead of light and dark there would be "default" option or something? that way every single thing is customizable because original styles are inherited.

Right now if I want a dark theme with some white backgrounds I need to replace many things in dark theme applies and vice versa. I hope I explained this well enough.

PS. What is the best way for developing a theme? just making CSS changes with devtools, adding them to a css file and readding it in Settings? Not very familiar developing with Electron apps alltogether.

**Comment by MarshallOfSound** [comment]
> After spending couple of hours theming I find it frustrating that some of the styles are predefined. Could you add third option for custom themes, instead of light and dark there would be "default" option or something? that way every single thing is customizable because original styles are inherited.

Can't you just turn the custom theme off?  I'm not sure I understand the context of your request 👍 

As for developing a theme personally I change the I just code in a `setInterval(reloadStyles, 5000)` when I'm messing around with styles, but if you're running prod not building yourself that isn't an option 😆 .  The best bet is probably just "change in devtools", "change file", "reload styles"

**Comment by ronilaukkarinen** [comment]
Oh, that's true, I thought that Custom theme needs to be enabled to use Custom styles - my bad. However, if I develop a dark theme, the title bar is still screaming orange. I guess that cannot be changed with just CSS? And then again, dark Custom theme changes too much...

Yeah, not familiar with developing the whole electron thingy, even though npm, gulp and other js stuff are part of my toolbox.

**Comment by Alipoodle** [comment]
by Title bar, are you talking about the Border of the application or the Top bar where the search is.
As both can be themed with CSS
I have a repository that themes it to your custom colour, however you can use the tags to edit it for your chosen colour or the Themes colour using the GPMDP Theming.

**Comment by MarshallOfSound** [comment]
@ronilaukkarinen The title bar can only be affected by the "app" CSS file not the "gpm" CSS file.  Don't forget their are two sets of devtools you can open.  One for GPM and one for the app itself.

**Comment by Alipoodle** [comment]
`.title-bar {
    background-color: <<DARKEN 0.1>><<FORE_SECONDARY>><</DARKEN>> !important;
}

.window-border {
    border-color: <<DARKEN 0.1>><<FORE_SECONDARY>><</DARKEN>> !important;
}`
That will theme your Borders to your chosen colour within GPMDP.
Although put this into another file for the the `Main App` section

**Comment by ronilaukkarinen** [comment]
Thanks! I'll try it as soon as I can :)

Lähetetty mobiililaitteesta

**Comment by ronilaukkarinen** [comment]
Tried that and it did nothing... what gives?

**Comment by ronilaukkarinen** [comment]
Any tips for moving forward with this? the orange bar is quite irritating :) I'm 100% sure I did as instructed. @Alipoodle @MarshallOfSound

**Comment by MarshallOfSound** [comment]
@ronilaukkarinen GitHub removed some of the comment, I have fixed it.  Try again now

**Comment by ronilaukkarinen** [comment]
Doesn't seem to help, or then I'm missing something. I can only change styles on **Google Play Music button**, but whatever css I apply from **Main App** button I get no changes.

**Comment by Alipoodle** [comment]
Do you want this bar to be themed? https://puu.sh/sG4rE/f2030c28bc.png
Or the Border around..? https://puu.sh/sG4wp/b0640d64fa.png

**Comment by ronilaukkarinen** [comment]
The border around.

See:
![Screenshot](https://dl.dropboxusercontent.com/u/18447700/Screen%20Shot%202016-12-06%20at%2015.20.58.png "Screenshot")

**Comment by Alipoodle** [comment]
Using the CSS i gave you, it will use the chosen colour.
![image](https://cloud.githubusercontent.com/assets/17199186/20926966/2e5d375a-bbb7-11e6-8a18-00c821b2373b.png)

**Comment by ronilaukkarinen** [comment]
Right, but the point was to theme desired parts without having **Custom Theme** option ticked on, because it will theme all the other parts too, which I don't want. I just need the title bar right now. **Dark** forces backgrounds dark, **Light** forces them light. Is there any way to theme borders without **Custom Theme** option on. Or what do you suggest?

**Comment by Alipoodle** [comment]
I kinda expected it to be like that.
so it would be `.darwin-title-bar` instead of `.title-bar`

**Comment by ronilaukkarinen** [comment]
That did the trick! Thank you very much. :) going to release the full + minified version of the theme in GitHub very soon. Based on Spotify-black on [radiant-player-mac](https://github.com/radiant-player/radiant-player-mac).

![Screenshot](https://dl.dropboxusercontent.com/u/18447700/Screen%20Shot%202016-12-06%20at%2015.57.47.png "Screenshot")

I needed default styles as base, because for example the new Home page is with white/scrolling background and cannot be forced.

Excellent player, great support. ❤️
