### ISSUE TITLE
Once inslalled, Itunes hotkeys don't work anymore 

### ISSUE THREAD

**Issue by GinoLandi** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1973]
**OS: **
Osx Yosemite
**Issue Descriptions:**
I have installed version 4.0.3, then play\back\next hotkeys (F7- F8 - F9) don't work with itunes (12.5.3)
Uninstall google play music player doesn't fix the problem.
I have no google play extension  on chrome.
I can't change hotkeys in google music player preference 'cause doesn't work.

**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment]
> Uninstall google play music player doesn't fix the problem.

I don't see how this is an issue with the player then.  Your issue is your hotkeys don't work on iTunes??
