### ISSUE TITLE
Feature Request: Auto pause/play when screen locked/unlocked

### ISSUE THREAD

**Issue by swfreak18** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1976]
It would be great if a feature could be added that, when enabled, would automatically pause the music when the computer screen is locked (Win Key + L) and automatically unpaused when you log back in again.

**Comment by jostrander** [comment]
I believe similar things like this have been requested before, such as muting when locked, and unfortunately there is no API to check whether or not the screen is unlocked in electron yet. So please feel free to raise this issue again when the API is available, but until then there's nothing we can do.

**Comment by swfreak18** [comment]
Thanks for the quick response. It looks like the powerMonitor API allows
the detection of the screen locked state but as you mentioned, the unlocked
state can't be detected.  Even just adding an option to pause or mute when
the screen is locked, without resuming when unlocked, would be helpful.

**Comment by jostrander** [comment]
I don't see that in the documentation, can you point me to where you see that?

**Comment by swfreak18** [comment]
Someone mentioned that it detects the screen locked state as a suspend
event.  But maybe that is only on Macs.
https://discuss.atom.io/t/how-do-i-detect-screen-unlocked-state-using-electron-api/35098
