### ISSUE TITLE
Optionally use electron dark mode API for toggling theme 

### ISSUE THREAD

**Issue by jostrander** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1977]
Electron somewhat recently added the ability to easily read the system preferences for dark mode, and we should add the feature as an option so it follows the system theme.

https://github.com/electron/electron/blob/master/docs/api/system-preferences.md

**Comment by MarshallOfSound** [comment]
Using `systemPreferences` currently breaks global shortcut handling on windows.

**Comment by jostrander** [comment]
Upstream Issue #?

**Comment by MarshallOfSound** [comment]
Tada electron/electron/issues/7859

**Comment by jostrander** [comment]
Thanks
