### ISSUE TITLE
Tabs on "Music Library" section is dark grey on black theme

### ISSUE THREAD

**Issue by KevinNguyen298** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1978]
**OS:** Windows 10

**Issue Descriptions:** On the "Music Library" section, the text for the tabs are grey, while the background is black.

**Steps to Reproduce:** Go to "Music Library"

**Comment by MarshallOfSound** [comment]
By making this issue you claimed to have read this...

> * I have checked that there are no issues with similar or the same content
  YOU SHOULD CHECK CLOSED ISSUES ASWELL

Apparently you forgot to do that.

#1946 #1897

Handling issues like this consumes my time and other contributors time as well.  Please ensure you follow the ISSUE_TEMPLATE and the contributing guidelines in the future.  It makes github a much better place 👍
