### ISSUE TITLE
Typo in 4.0.4 changelog

### ISSUE THREAD

**Issue by Marwelln** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1982]
> This is a patch release of Google Play Music Desktop Player Here is a quick run down of all things that have changed.

Should be a dot after `Desktop Player`.

> FIX: Update dialog now doens't block the mini player

Should be `doesn't`.

**Comment by MarshallOfSound** [comment]
Haha, I can fix it on GitHub but I can't change the update packages :laughing:
