### ISSUE TITLE
Preventing Sleep on MacOS despite "Stop Your Computer from Sleeping While GPMDP is open" unchecked

### ISSUE THREAD

**Issue by xiexieeric** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1983]
**OS: MacOS**

**Issue Descriptions: In activity monitor, GPMDP is listed as preventing sleep, which causes higher than usual standby drain. **

**Steps to Reproduce: Just use the app on a macbook. **

**Comment by MarshallOfSound** [comment]
@xiexieeric This has come up before I added this option.  This option being **on** explicitly tells the system not to sleep.  The option being **off** accepts the default behavior.

On macOS this is to prevent sleep when an app is using the audio device.

As I have mentioned in previous issues, there is nothing I can do about this 😢
