### ISSUE TITLE
Last.fm Authorization Hangs and Doesn't Work

### ISSUE THREAD

**Issue by Night-Man** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1985]
**OS:**
Elementary OS (but I also experienced the issue on a recent previous Windows 10 install as well
**Issue Descriptions:**
Last.fm authorization won't work, it just hangs at the "Authorization in Progress" screen forever

**Comment by MarshallOfSound** [comment]
This was fixed several versions ago.  Linux doesn't have auto update so ensure you are up to date

**Comment by MarshallOfSound** [comment]
If you are on `4.0.4` and this issue is still here I'll reopen but I just tested on *nix, macOS and windows and they all work on my machines.  It's actually part of my manual tests before release now 👍

**Comment by nsnyder** [comment]
I'm still having the issue on my machine. (Windows 10)

Is there a way to blow away any caching I have and reinstall it to see if that fixes it?
