### ISSUE TITLE
Typo (or charset issue) in the "Music for where you are" dialog

### ISSUE THREAD

**Issue by quinncomendant** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1986]
`Youâve` should be `You’ve` in the "Music for where you are" dialog. See below.

<img width="433" alt="screen shot 2016-12-05 at 15 35 36" src="https://cloud.githubusercontent.com/assets/6884276/20880921/85c3a980-bb0c-11e6-9da6-8eab55513f69.png">

**Comment by MarshallOfSound** [comment]
This is an issue on Google's side of things.  I don't control or influence that dialog in any way.
