### ISSUE TITLE
Feature request: "Edit Info" window should have a control to move up/down playlist

### ISSUE THREAD

**Issue by zexpe** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1987]
This is something the iTunes desktop app has and the Google Play Music website has never supported, but it would be nice to integrate into the Google Play Music Desktop Player if possible.

When you have a playlist of music and you select a track to edit song info the "Edit Info" window on iTunes gives you a "<" and ">" button to move to the previous/next song in the playlist then when all the edits have been made pressing "Save" saves them all (or it could be implemented that they save as soon as you move to the next track in the playlist). When you want to browse the more detailed information presented in the "Edit Info" window it is much faster doing it with these buttons than having to open and close the "Edit Info" window for each track individually. Alternatively, it would be good to have all of this extra information available as columns in the playlist table (possibly even have the tabular data editable), but it seems to me that the previous/next buttons in the "Edit Info" window would be simpler and easier to implement quickly.

**Comment by MarshallOfSound** [comment]
Advanced feature adjustments of Google Play Music are out of scope for this player.  I think I need to make that standing more clear somewhere.  This is a very complex piece of functionality which hacking on to GPM would cause more issues than it would solve.

**Comment by zexpe** [comment]
So you wouldn't even consider a keyboard shortcut just to move to the next track in the playlist when in the "Edit Info" window?

**Comment by MarshallOfSound** [comment]
What you write sounds simple but in fact would require a lot of UI simulation some of which no one has found a way to do yet (interacting with song based context menus).  It is difficult, would break frequently and would add debt that I am not in a position to take on 👍

**Comment by zexpe** [comment]
OK, thanks, I considered it may be out of the scope of this particular app. I'll send my request directly to Google. Thanks for the quick response.
