### ISSUE TITLE
Mini player can't be moved

### ISSUE THREAD

**Issue by Strawberry-Nug** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1988]
**OS:**
Windows 10 Home
**Issue Descriptions:**
Can't move the mini player, can drag from edge, but resizing it is also janky and can cause it to get stuck off screen.
**Steps to Reproduce:**
1. Open mini player
2. Borders of window are used to resize, but not move.

**Comment by MarshallOfSound** [comment]
If you have the custom window theme on just click and drag on the album art in the middle of the window.  Otherwise use the title bar as normal.
