### ISSUE TITLE
Feature request: Add song info to tray or dock title

### ISSUE THREAD

**Issue by ronilaukkarinen** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1989]
I noticed there's no currently playing song info either tray or dock title. If I want to know what's playing, I have to open minimized app. Dock title is currently "Google Play Music Desktop Player" whcih makes sense, but you could add some info on the tray at least. What do you think? Radiant Player has quite cool tray "miniplayer", but I guess that's only possible for Mac?

![Screenshot](http://radiant-player.github.io/radiant-player-mac/images/mini-player.png "Screenshot")

**Comment by MarshallOfSound** [comment]
> Radiant Player has quite cool tray "miniplayer", but I guess that's only possible for Mac?

Technically possible anywhere but we already use the tracy icon to fulfill another purpose.

We can't add the info to the tray as it just overflows the bounds and becomes quite useless.  We also can't put it on the Dock title as I'm 99% sure it violates the mac design guidelines.

**Comment by MarshallOfSound** [comment]
Maybe during a rework one day we can repurpose the tray icon, but that won't be any time soon.

**Comment by ronilaukkarinen** [comment]
Ok, thanks for the response. Appreciate it. 👍
