### ISSUE TITLE
Media buttons no longer working

### ISSUE THREAD

**Issue by eladavron** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#199]
As of updating to version 3.0.0 the media buttons on my keyboard (Play/Pause/Next/Prev) no longer work.
I'm using a Microsoft X4 keyboard with IntelliType.

**Comment by MarshallOfSound** [comment]
**FYI this is a prewritten copy paste response**

So your media buttons aren't working aye???  
Let's try fix that.

1. Are you using the Google Play Music chrome plugin?  If yes, remove it, and reboot your pc (sorry) and see if it works
2. Are you using a logitech keyboard?  If yes, turn off logitechs stupid software that manages your keyboard and try again?
3. Is there any other program that could possibly be "stealing" the keypresses?  (keyloggers, other media players Etc.)?  If so, close them and try again :+1: 

Good luck, if this doesn't work please respond

**Comment by eladavron** [comment]
Wow, thanks for the very quick response :+1: 

1. I do not use the chrome plugin, not since I found this program :-)
2. I do not use a logitech keyboard (I use Microsoft)
3. None that I can think of.

Thanks!

**Comment by MarshallOfSound** [comment]
OK, time for a personalized response :smile: 

Can you go into the settings window and try adding a custom Play / Pause shortcut for a random key combination.  Maybe something like "Ctrl + Shift + P"

And see if that works?

**Comment by eladavron** [comment]
Ok, I'm sorry I wasted your time since all it took was a reboot and everything's working again.
If I had to guess, I'd say that updating from 2.* to 3.* also requires a reboot to 'release' the media-keys.
I really should have rebooted the computer BEFORE filing the issue, sorry again and thanks for the awesome application!

**Comment by MarshallOfSound** [comment]
Not time wasting at all, a reboot was next on my list to reccomend.  Sometimes software can randomly lay claim to keyboard shortcuts and it takes a reboot to "unregister" them.  Version `2.X` doesn't have this behaviour but other programs might.

I think I'll add a standard message into the app when the keyboard shortcut fails to register that tells the user to reboot and try again :+1:

**Comment by eladavron** [comment]
Thanks, I'm really loving the new version!
It has since locked again, but since a restart again solved it - I'm assuming it's something on my computer that's stealing the media keys, so I"ll look for it internally.

**Comment by eladavron** [comment]
Sorry to bug you (no pun intended) but I'm gonna have to ask to re-open this issue. Turns out the 'fix' only works temporarily and as soon as you minimize the player or transfer focus to another window, the media keys stop working until you restart the computer again.
