### ISSUE TITLE
FR: Keyboard shortcut to open main application window after it has been closed

### ISSUE THREAD

**Issue by elihorne** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1990]
**OS:**
Mac OS 10.12.1

**Issue Descriptions:**
Please add a keyboard shortcut that allows for the application window to be re-opened in the foreground.  Most Mac apps do this via cmd+1 or cmd+0 or sometimes opt+cmd+1.  Currently (as far as I can tell) the only way to re-open the GPMDP main window after closing (cmd+w) is to navigate to the dock and click the icon. Toggling "full size player/mini player" and clicking "bring all to front" does not do it.  

I primarily use GPMDP because of the keyboard shortcuts, and after starting a song will close the window. This would vastly improve the workflow, and bring it in sync with other desktop application patterns.

**Steps to Reproduce:**
1 - Open GPMDP and play a song
2 - Close GPMDP window (cmd+w) with song still playing in the background
3 - Try to re-open GPMDP window (to change songs, search, whatever) via keyboard.

**Comment by MarshallOfSound** [comment]
> Most Mac apps do this via cmd+1 or cmd+0 or sometimes opt+cmd+1

I've never seen this before, can you provide an example?

FWIW the current behavior is just to be consistent with other platforms.

**Comment by MarshallOfSound** [comment]
Closing until a response is given
