### ISSUE TITLE
Videos don't play to selected audio output

### ISSUE THREAD

**Issue by wikLiA** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1991]
**OS:** Windows 10

**Issue Descriptions:** Regardless of which audio output you select the desktop player will only play videos using the default audio device.

**Steps to Reproduce:** Change audio output (something not default), play a video, hear the video through default device.

[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/634829/debug_info.zip)

**Comment by MarshallOfSound** [comment]
This is just because I never implemented it.  I don't think videos were a thing at the time when I wrote the AudioOutput selector.

**Comment by MarshallOfSound** [comment]
@wikLiA Unfortunately the HTML5 video elements for YouTube videos appear to be pulled in through sandboxed iframes.  This makes it impossible for us to modify the content or acquire the `AudioContext` we need to set the sinkID.
