### ISSUE TITLE
Newest version breaks playback

### ISSUE THREAD

**Issue by deafened1962** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1993]
-->

**OS:**
Win 10

**Issue Descriptions:**
Playback stops and cannot be restarted until player is relaunched,

**Steps to Reproduce:**
Launch player. Choose album. Hit play.

**Comment by MarshallOfSound** [comment]
I can't reproduce and logs indicate that most people are still playing music just fine.  I would suggest reinstalling or logging out and logging in of Google Play Music.

**Comment by banduccm** [comment]
I'm having this same issue on Win7 - I'll be playing music and GPMDP will (seemingly at random) stop playing and blank out the window. I'll try reinstalling as recommended, but I grabbed debug info and thought it might be helpful:
![image](https://cloud.githubusercontent.com/assets/5399545/21054599/f243418a-bdf3-11e6-9e87-3e95d1c85793.png)
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/642556/debug_info.zip)
