### ISSUE TITLE
Debian/Ubuntu Repository

### ISSUE THREAD

**Issue by sebastienserre** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1994]
Hello,

Thx for your great player.
WIll it be possible for you to create a deb repository to manage upgrade with apt-get ?

Many thx

**Comment by MarshallOfSound** [comment]
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/docs/Installation_On_Debian.md
