### ISSUE TITLE
Bonjour/avahi not initliazing properly

### ISSUE THREAD

**Issue by Darling13** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1995]
**OS:** 
Ubuntu 16.04

**Issue Descriptions:**
Issue with avahi/bonjour/gpmdp remote

**Steps to Reproduce:**
Launching the app open it but gives me this error in the linux terminal and it doesnt show up in the gpmdp remote app for my phone. The packages that has to do with avahi that i installed are the avahi-daemon, avahi-utils and libavahi-compat-libdnssd1
Here's the output when launching gpmdp 
>$ google-play-music-desktop-player

>Gtk-Message: Failed to load module "canberra-gtk-module"

>Starting Sentry

>*** WARNING *** The program 'Google Play Music Desktop Player' uses the Apple Bonjour compatibility layer of Avahi.

>*** WARNING *** Please fix your application to use the native API of Avahi!

>*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=Google Play Music Desktop Player>

>*** WARNING *** The program 'Google Play Music Desktop Player' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.

>*** WARNING *** Please fix your application to use the native API of Avahi!

>*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=Google Play Music Desktop Player&f=DNSServiceRegister>

>error: Could not initialize bonjour service with error: {"errorCode":-65537}

>*** WARNING *** The program 'Google Play Music Desktop Player' uses the Apple Bonjour compatibility layer of Avahi.

>*** WARNING *** Please fix your application to use the native API of Avahi!

>*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=Google Play Music Desktop Player>

>*** WARNING *** The program 'Google Play Music Desktop Player' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.

>*** WARNING *** Please fix your application to use the native API of Avahi!

>*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=Google Play Music Desktop Player&f=DNSServiceRegister>

**Comment by jostrander** [comment]
That is entirely normal and completely unrelated to why GPMDP remote may not be working. Check your firewall and make sure it's allowing mDNS (udp port 5353) through.

**Comment by MarshallOfSound** [comment]
As @jostrander those are warnings about the usage of the MDNS compat layer and are expected.

Just check your firewall and if required type you IP in manually.

Also issues for the remote in the future should be raised on the remote repo
