### ISSUE TITLE
Songs/albums not added to playlists on the server

### ISSUE THREAD

**Issue by Proggie** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1996]
**Version of Google Play Music Desktop Player** 4.0.4

**OS:** Mac OS Sierra 10.12.2 Beta (16C60b)

**Issue Descriptions:** Songs/Albums added to a playlist are added in the app, but when I go to play.google.com they are not there, and when I relaunch/refresh the app (cmd-r), they are also gone. And if I try to remove those songs from the app, I get an error that the songs could not be removed (presumably because they actually don't exist in the playlist). I can play those "added" songs though in the app.

**Steps to Reproduce:** Add songs/albums to a playlist. Notice they are in the playlist in the app, but they are not in the same playlist on the website.

Here's what the end of the playlist looks like on google's site:
<img width="1361" alt="screen shot 2016-12-08 at 12 14 40 pm" src="https://cloud.githubusercontent.com/assets/2626514/21026107/0ee5fd46-bd40-11e6-8b9d-510552d013c0.png">

Here's what the same playlist looks like in the app. Notice I added more songs after song 963:
<img width="1172" alt="screen shot 2016-12-08 at 12 15 13 pm" src="https://cloud.githubusercontent.com/assets/2626514/21026106/0ee11e3e-bd40-11e6-8881-99f23b83eb38.png">

**Comment by Proggie** [comment]
hmmm... maybe it's an issue with Google. Same thing seems to now be happening when adding to playlists on google's site. After a while the songs disappear :/

**Comment by jostrander** [comment]
Yeah this is not something we have any control over. Must be something will their service.
