### ISSUE TITLE
Auto add to record library on like

### ISSUE THREAD

**Issue by Niklan** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1997]
Hi, I am not sure how this feature named on English. But on 'record library' I mean this thing:

![image](https://cloud.githubusercontent.com/assets/2356744/21043809/9489a288-be1a-11e6-8af8-574b42993211.png)

I think this will be very good feature, to make possibility to auto add to library on press thumbs up button (hotkey or mouse click on button).

I found that I need to select all tracks from "Liked playlist" and then add them to library, otherwise they are missing or I need it to do every time I press like button. 

Maybe my experience with Google Music is wrong, but I'm trying to keep my library clean with only tracks what I liked.

**Comment by MarshallOfSound** [comment]
The user flow for this is already as expected.   You can add the "Thumbs Up" playlist to your library whenever you want.  I'm not keen on changes like this that would require UI interaction emulation as it would not be a good experience for the user.

**Comment by Niklan** [comment]
Also i think will be good to add advice to hotkey config page where you can set hotkeys for like, volume and prev\next tracks about multimedia keys.

I drop in issue that sometimes they works, sometimes is not. This is only change by system reboot just for random. I start thinking this is app problem but found that Google Music chrome extension blocks access to multemedia keys if crome is starts faster then GPMDP. 

So this advice about to remove this extension if people have troubles with multimedia keys.
