### ISSUE TITLE
V4.0.4 mini player - can't get back to main player

### ISSUE THREAD

**Issue by adm1263** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1998]
**OS:** 

win7

**Issue Descriptions:**

updated to v4.0.4
go to mini-player
can't get the option to get back to the main window view - used to get pop-up bottom menu, no more

**Steps to Reproduce:**

as above

**Comment by Buggsy2k** [comment]
Win10 - having the same issue.
Is there a hot key or a setting that can be edited somewhere... pretty unusable once mini player is the only interface available.

**Comment by godey4me** [comment]
Same here. In mini player view missing Play/pause thumbs up/down  buttons and can't go back to main view. Have to exit and start again. Tested on both win 7 and 10.

**Comment by jacobmischka** [comment]
Same here on Linux, no controls are showing up on the mini player for me at all.

**Comment by woodmoat** [comment]
Same issue on OS X. Only getting song and artist information, no bottom control panel and no ability to go back to the full player without quitting the application.

**Comment by jacobmischka** [comment]
I created an issue in the mini player repo as well: GPMDP/gmusic-mini-player.js#9

**Comment by MarshallOfSound** [comment]
Guys.

This has already been fixed in master #1992.  Please check closed issues before raising new ones

**Comment by jacobmischka** [comment]
Ah, whoops. Well to be fair, we did check for existing issues and found this one, but yeah we should have checked to be sure it wasn't already fixed. :disappointed:

**Comment by MarshallOfSound** [comment]
I would have pushed out a release already to fix this but I'm holding out for the Electron 1.4.12 release which should be happening any minute now.
