### ISSUE TITLE
Memory Management

### ISSUE THREAD

**Issue by SpectralKH** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1999]
After weeks of having the application open, it seems like the memory usage really is piling up - Right now it was running on 1gb of RAM.

OS: macOS

**Comment by MarshallOfSound** [comment]
Memory leaks in Chromium / GPM happen all the time in Chromium 51 - 53.  Supposedly this has been fixed in Chromium 54 / 55 which Electron is upgrading too soon.
