### ISSUE TITLE
After choosing different language, the language of Google Play Music itself doesn't change 

### ISSUE THREAD

**Issue by vanushah** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2004]
Hi.

I've noticed that after changing the interface language, the language of the player doesn't change. I have my account set to Russian language in browser, and if I open Google Play Music in it, the language of the player is Russian.

I'm attaching the screenshot of the app, after I switched the language. (Note the only menu item in Russian.)

Can you implement the support of changing the locale of Google Play Music? Thanks.

![2016-12-10_21-57-21](https://cloud.githubusercontent.com/assets/188117/21074476/39e98f68-bf24-11e6-8d67-844102dae00b.png)

PS This is how I've expected the app to look:
![2016-12-10_22-09-20](https://cloud.githubusercontent.com/assets/188117/21074526/5fb51ba8-bf25-11e6-88e9-aeade625ca4b.png)

**Comment by vanushah** [comment]
AFAIK this issue can be solved just by adding "hl=ru" to the GET request. Am I right?

**Comment by MarshallOfSound** [comment]
@vanushah Not completely correct, other requests will still be your system language AFAIK.  This would be solved by this API.

https://github.com/electron/electron/issues/5649

**Comment by adkuca** [comment]
if on windows 10
region & language -> and set country or region
uninstall the app
delete "Google Play Music Desktop Player" folder in AppData
ex: C:\Users\UserName\AppData\Roaming\Google Play Music Desktop Player
you can also delete C:\Users\UserName\AppData\Local\GPMDP_3
