### ISSUE TITLE
Feature Request: Silent Automatic Updates

### ISSUE THREAD

**Issue by warinthestars** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2006]
**OS:**
Win 10 x64
**Issue Descriptions:**
In the FAQ, it states the updates must stay on. This is fine, however, could the updates have an option to do them silently. Such as "Update without notification and apply update upon next launch of the application."

Sometimes I don't want to update right then and there and being constantly notified that there is an update can be annoying after awhile. 

**Steps to Reproduce:**
Launch App
Be notified of update
Be Reminded Later
Be notified of update
Be Reminded Later
Be notified of update
Be Reminded Later
Be notified of update
Be Reminded Later
Be notified of update
Be Reminded Later
Be notified of update.

**Comment by MarshallOfSound** [comment]
Maybe just adding another button "Update on restart" or something

**Comment by jostrander** [comment]
Should name it "next century", and have it actually update on the next restart.
