### ISSUE TITLE
App window overlaps to other monitors and under the taskbar when in fullscreen mode

### ISSUE THREAD

**Issue by JGlover-DV** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2008]
**OS:** Windows 10

**Issue Descriptions:** When in fullscreen mode using multiple monitors, the app will consistently display a white "bar" on the right side of any monitors to the left of the one being used for GPM. Additionally, the bottom of the window overlaps under the taskbar, which is noticeable when the taskbar is set to "transparent". This issue applies no matter what theme is being used.

Both are in the screenshot below, let me know if you have any more questions!

![screenshot 2016-12-12 10 31 51](https://cloud.githubusercontent.com/assets/12235254/21104993/a15d5548-c056-11e6-8b68-146b0c5838ae.png)

**Comment by MarshallOfSound** [comment]
Upstream

https://github.com/electron/electron/issues/5267
