### ISSUE TITLE
Automatic time-based dark theme

### ISSUE THREAD

**Issue by jakemoritz** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2011]
I like using the light theme during the day and the dark theme at night. It would be convenient to be able to set a specific time of day when to automatically turn on the dark theme, and another time of day to turn on the light theme. These times should also be checked when opening the app to set the correct theme based on the current time. 

Side feature: Some may also appreciate an automatic dark theme based on sunset/sunrise times based on user location.

**Comment by FezVrasta** [comment]
I use this app to automatically change the Mac theme on sunrise:
https://github.com/timomeh/Dunkl.app

It would be nice to:

1. Make the app respect the Mac theme (if dark mode is on, enable it on the app)
2. Use the same script used by Dunkl to decide when to switch to dark theme (https://github.com/kevinboone/solunar_cmdline)

**Comment by MarshallOfSound** [comment]
@FezVrasta @jakemoritz In master there is now an option to make GPMDP respect the macOS "dark mode" setting for whether the dark theme is enabled or not.  If you are already using Dunkl, does that solve this issue?

**Comment by jakemoritz** [comment]
@MarshallOfSound Sorry I forgot to specify, I am on Windows so the solution @FezVrasta proposed would only be for Mac users.

**Comment by FezVrasta** [comment]
@MarshallOfSound yes it should solve the issue for macOS users.

**Comment by MarshallOfSound** [comment]
I don't want to be determining a users location to implement a feature like this as I (like many users) don't think a music app should be accessing or requesting a users location which is what is required to get sunrise / sunset information.

On macOS this is already released, I don't think I can viably support windows or linux for the above mentioned privacy reasons.  This could be implemented yourself however through the settings endpoint in the websocket API
