### ISSUE TITLE
Current track info in macOS notification center

### ISSUE THREAD

**Issue by simmtodd** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2014]
I'd love to see the currently playing song in the macOS Notification Center. Radiant Player does this and it's quite handy.

GPMDP shows a notification when a new song starts, but I don't see a way to enable persistent banners in Notification Center. There's no entry for GPMDP in the system notification preferences (and no related settings in the app itself). Thanks for your help!

**Comment by MarshallOfSound** [comment]
This is currently not possible due to Chromium Notification logic.  When `sticky` becomes a thing in Chromium I think we can do this.

I've already subscribed to upstream Electron and Chromium issues regarding this feature and I'll implement it as an option when it becomes available 👍
