### ISSUE TITLE
Can't go to shortlinks

### ISSUE THREAD

**Issue by rattboi** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2015]
**OS:**

Linux (although should be the same across all OS's)

**Issue Descriptions:**

Friends often share shortlinks to GPM content with me, but there's no way to go to them from GPMDP, as there's a regex on the url that obviously won't match. In a perfect world, the url would be followed to make sure it's not a 301, and whatever the resolved url is would be matched against the regex.

Here's the offending line:
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/d85ede4c771fb95bc9ae9e8bdf120953d5aac265/src/renderer/ui/components/modals/GoToModal.js#L58

**Steps to Reproduce:**

Here's a shortlink to some GPM content: https://goo.gl/T5j49Q

You can't follow that in GPMDP using ctrl+shift+g.

**Notes:**

I'd be willing to write up a PR for this, but wanted to see if it would be accepted first. I understand that this is sorta niche, but it would be nice for me and my friends.

**Comment by MarshallOfSound** [comment]
> I'd be willing to write up a PR for this, but wanted to see if it would be accepted first. I understand that this is sorta niche, but it would be nice for me and my friends.

If you came up with a good way of knowing if the URL eventually resolves to a URL that matches the RegExp I would accept that 👍

**Comment by bronsona** [comment]
Not sure if this is related - but the original share link from the menu next to each original song provides a share link that cannot be navigated to through GPMDP. E.g I share a Sigur Ros song (https://play.google.com/music/m/Tx2j6gb3ffzm7qbh7lhmstekbxu?t=Flugufrelsarinn_-_Sigur_Ros) from this application to a friend who also uses GPMDP, but this link cannot be opened.

When opened in a browser, it redirects multiple times before ending up at https://play.google.com/music/listen#/album/Bbuc22qzl5uo6iirdtqvzbrvmuy (the album page) which can be opened in GPMDP. Cheers!

**Comment by rattboi** [comment]
I think a fix for shortlinks would fix this too. I've got a patch in the
works, so hopefully this should be solved soon.
