### ISSUE TITLE
Space bar doesn't Play/Pause when GPMD is open

### ISSUE THREAD

**Issue by vovokrall** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#202]
It may be a silly request, since global media keys are working, but to play/pause when the app is open, I need to click in it before I can do it.

**Comment by vovokrall** [comment]
By the way, it was working fine on the previous version.

PS: THANK YOU SO MUCH FOR THIS AMAZING APP.

**Comment by MarshallOfSound** [comment]
I'm confused as to what you mean.  So you're saying the app is NOT in focus and you want to spacebar to play pause?

That would involve making the spacebar a global hotkey which is BEYOND bad???

Can you please explain in more detail

**Comment by vovokrall** [comment]
Sorry, english is not my first language, so it is kind of hard to express myself.

If I open the app by clicking on it on taskbar or using Alt+TAB, it seem not to be focused, cause I need to click anywhere on it to be able to use spacebar to play/pause.

**Comment by MarshallOfSound** [comment]
That is very interesting.  Small usecase but a bug none the less...

I'll look into it.  Thanks for the report

**Comment by MarshallOfSound** [comment]
Closing as unfixable in the current state of electron.  Sorry, I tried :cry:

**Comment by mindthetic** [comment]
Just leaving a note to say that I also experience the same bug. I didn't realised until reading this that you have to select the window of the app before the spacebar key works.
