### ISSUE TITLE
Cannot do anything with mini player

### ISSUE THREAD

**Issue by LePopNoisette** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2020]
Once I have the mini player in use, I can no longer do anything with it, as in I can't bring back the main screen to change album/playlist etc. The 'maximise' icon (or whatever it is called) that used to appear at the bottom-right of the mini player window no longer appears. My hotkeys still work, though, and I can still use the system tray icon menu, but that only allows me to do certain things. What I have to do now if I want to listen to something else is quit the app from the system tray icon and then re-open the app. I would say I have only noticed this in the last two months or so.

**Comment by MarshallOfSound** [comment]
This has been fixed in master.  If you are on linux you will need to update manually.
