### ISSUE TITLE
Playlist played in reverse changes direction after a few tracks

### ISSUE THREAD

**Issue by RowanBurgess** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2021]
**OS:**

Windows 10 Pro

**Issue Descriptions:**

If you play a playlist in reverse order (order descending by track number and play from top), it changes the order to ascending after a few tracks, and continues to play in normal order, rather than reverse.

Means that you get a few tracks in, then end up listening to the same tracks again and then the playlist reaches the end (where it started).

**Steps to Reproduce:**

Play playlist in reverse.

**Comment by MarshallOfSound** [comment]
This sounds very much like a GPM issue and not an issue on our side of things.  I would recommend raising this with Googles product support.
