### ISSUE TITLE
Static sidebar/Mac gestures 

### ISSUE THREAD

**Issue by D-Garney** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2022]
Is it possible to add the option of having a static sidebar and playlist bar like Play midnight does? It makes navigating the interface much easier in my opinion.

Would it also be possible implement swipe gestures? For instance, on a mac, a two finger swipe gesture on a mouse or trackpad would take you forward or back a page making it faster than hitting the back button on the top bar. 

![screen shot 2016-12-15 at 16 53 34](https://cloud.githubusercontent.com/assets/24592061/21233594/a4acdd98-c2e7-11e6-9ca5-a3cd4de00001.png)
#

**Comment by MarshallOfSound** [comment]
> Would it also be possible implement swipe gestures? 

Swipte gestures are implemented and do work (I just double checked)

> Is it possible to add the option of having a static sidebar and playlist bar like Play midnight does?

Personally I'm not a fun of that static sidebar I much prefer it being hidden.  That said if someone wants to PR in an option for that setting I would accept it but it's not something I'm going to look into.

**Comment by EzraLopez** [comment]
Swipe gestures are not working for me. :/
