### ISSUE TITLE
Can't Set Hotkeys

### ISSUE THREAD

**Issue by caitlinfitzgibbons** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2025]
Hello!

Just downloaded the desktop player for Mac this morning - very excited! However, the "pause/play" button on my headphones does not work with the app, as it does on my iPhone. I went to set a hotkey, and I am unable to edit or delete any text under the hotkey fields. They all just say "not set". 

*EDIT* I did download https://github.com/7hil/mac_ear_control as a remedy

**OS:**

**Issue Descriptions:**

**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment]
All hotkeys must contain the "Control" key

**Comment by stasparshin** [comment]
Please consider adding a notice about it. Had to arrive here to discover the requirement. Thx! Awesome app!
