### ISSUE TITLE
Accent Color Light Theme

### ISSUE THREAD

**Issue by jaaimino** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#203]
Would it be possible to enable changing the accent color from orange to one of the selectable colors in the light theme?

**Comment by MarshallOfSound** [comment]
There is an open issue for this on  
https://github.com/gmusic-utils/gmusic-theme.js

**Comment by MarshallOfSound** [comment]
@jaaimino Just pinging here to say this has been implemented in the latest version

**Comment by jaaimino** [comment]
Wonderful, thank you!
