### ISSUE TITLE
Custom Styles and CSS cannot be reset to default

### ISSUE THREAD

**Issue by jebeld17** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2031]
Something that I have noticed in GPMDP(u) is that in the Desktop Dettings < Custom Styles tab, the custom styles or CSS settings cannot be reset back to default. This presents the user with a problem: What if the user installs a bad or faulty CSS file? There is no current way to backtrace and fix the issue.

Please take a look at the attached .ZIP created through the Windows Problem Steps Recorder for more finite detail.
[CSS_NoReset_Bug_STEPS.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/661210/CSS_NoReset_Bug_STEPS.zip)

**Comment by MarshallOfSound** [comment]
@jebeld17 Click in the CSS file selector input box and hit the "Escape" key

**Comment by jebeld17** [comment]
Why is this closed?
Not everyone knows the "Esc" trick. Where is this documented?

**Comment by MarshallOfSound** [comment]
It is closed because there is no issue?  Using the escape key to clear in an input field is relatively standard :/

**Comment by jebeld17** [comment]
What if the user already applied a CSS?
There is no way to clear the field after that.
I believe this should be patched.
[EscDoesntWork.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/663915/EscDoesntWork.zip)

**Comment by lorthirk** [comment]
@MarshallOfSound I don't want to sound pedant, but honestly this is an issue. I just stumbled across the same situation, and pressing ESC is honestly the last thing that came in my mind. For sure it's a counterintuitive user experience.

**Comment by jebeld17** [comment]
Thank you Lorthirk.
Also, pressing "ESC" after the setting has already been set does not do anything, and does not reset the CSS settings back to normal.

**Comment by TokenRing** [comment]
@jebeld17 - I had the same issue. I had to completely close out GPMDP entirely and then reload it after I removed a faulty bit of css. After reopening the problem had gone away.

**Comment by mfintonis** [comment]
Just ran into this issue as well, it really should have a "Clear" button or at least let the user know that the Escape key clears the text box.
