### ISSUE TITLE
Pin Playlists Open

### ISSUE THREAD

**Issue by mikeasage** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2032]
**Windows**

**Issue Descriptions:**
I would love the ability to pin the list of playlists open to make it easier to drag and drop songs into a playlist.
**Steps to Reproduce:**

**Comment by mikeasage** [comment]
Love the app.  Great job.

**Comment by breatheloud** [comment]
This is a windows only issue right? 
I want to help but not sure where to begin, on Mac as soon as I drag a song the playlist bar auto-slides out of the right for me to pop it into one of my playlists. Is that the kind of functionality you want?

**Comment by MarshallOfSound** [comment]
@breatheloud That behavior is the same on all platforms, not sure what the original intent of this issue was.

@mikeasage Can you elaborate on why this is required?

**Comment by MarshallOfSound** [comment]
Closing out till more information is provided 👍
