### ISSUE TITLE
cast icon is not visible if target is SHIELD

### ISSUE THREAD

**Issue by stgarf** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2034]
re: #72 and in lieu of https://chromeunboxed.com/chromecast-support-gaining-steam-on-macos-airfoil-adds-google-cast-support/

**Comment by jostrander** [comment]
Chromecast support exists? Closing this as a non-issue, unless you're having a specific problem.

**Comment by stgarf** [comment]
@jostrander Yeap, having a specific problem then. I don't see the Cast icon anywhere.

OS: macOS 10.12

Issue Description: Unable to cast/see cast icon.

Steps to Reproduce: Use GPMDP... sorry I can't really be more specific.

[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/662697/debug_info.zip)

**Comment by MarshallOfSound** [comment]
@stgarf Does the cast icon appear in Chrome on the GPM UI for you?

**Comment by stgarf** [comment]
@MarshallOfSound 

Not as far as I can see...

![screen shot 2016-12-20 at 12 47 58 am](https://cloud.githubusercontent.com/assets/1694002/21343915/fdb46d3e-c64d-11e6-8222-3f321d26097e.png)

**Comment by stgarf** [comment]
(I am on the network w/ my shield, my shield works... because I can cast this tab to it :)

<img width="855" alt="screen shot 2016-12-20 at 12 49 05 am" src="https://cloud.githubusercontent.com/assets/1694002/21343955/293a791c-c64e-11e6-8087-5318dc9ace11.png">

**Comment by MarshallOfSound** [comment]
If you are on Windows install Bonjour Print Services and restart GPMDP 👍

**Comment by stgarf** [comment]
Sorry @MarshallOfSound, up there ^ macOS 10.12 ... and more logs or debugging  you'd like?

**Comment by stgarf** [comment]
@MarshallOfSound any other debugging I can do?

**Comment by MarshallOfSound** [comment]
@stgarf SHIELD probably advertises on a different MDNS service name

Can you log all the output of running this command in the dev tools console

```js
var browser = require('mdns').browseThemAll();
browser.on('serviceUp', function(service) {
  console.log(JSON.stringify(service));
});
browser.on('serviceDown', function(service) {
//  console.log("service down: ", service);
});
browser.start();
```

**Comment by stgarf** [comment]
@MarshallOfSound sure.

In my Chrome while visiting music.google.com?
If you mean in GPMDP, how do I open the dev tools console while inside it?

Also, can you re-open the bug...?

**Comment by MarshallOfSound** [comment]
I'm not comfortable reopening a bug that is probably a network of electron-chromecast issue

You can open the Dev tools with the stand shortcut after following these steps.

1. Control + Shift + G
2. Type in "DEV_MODE"
3. Click OK
4.  Wait for app to relaunch
5. Launch Dev tools with the normal shortcut.

**Comment by stgarf** [comment]
Looks like it might be the `nvstream` interface...

```
{"interfaceIndex":4,"type":{"name":"workstation","protocol":"tcp","subtypes":[]},"replyDomain":".","flags":3,"networkInterface":"en0"}
{"interfaceIndex":4,"type":{"name":"nfs","protocol":"tcp","subtypes":[]},"replyDomain":".","flags":3,"networkInterface":"en0"}
{"interfaceIndex":4,"type":{"name":"1password4","protocol":"tcp","subtypes":[]},"replyDomain":".","flags":3,"networkInterface":"en0"}
{"interfaceIndex":4,"type":{"name":"homekit","protocol":"tcp","subtypes":[]},"replyDomain":".","flags":3,"networkInterface":"en0"}
{"interfaceIndex":4,"type":{"name":"googlecast","protocol":"tcp","subtypes":[]},"replyDomain":".","flags":3,"networkInterface":"en0"}
{"interfaceIndex":4,"type":{"name":"sleep-proxy","protocol":"udp","subtypes":[]},"replyDomain":".","flags":3,"networkInterface":"en0"}
{"interfaceIndex":4,"type":{"name":"mediaremotetv","protocol":"tcp","subtypes":[]},"replyDomain":".","flags":3,"networkInterface":"en0"}
{"interfaceIndex":4,"type":{"name":"appletv-v2","protocol":"tcp","subtypes":[]},"replyDomain":".","flags":3,"networkInterface":"en0"}
{"interfaceIndex":4,"type":{"name":"touch-able","protocol":"tcp","subtypes":[]},"replyDomain":".","flags":3,"networkInterface":"en0"}
{"interfaceIndex":4,"type":{"name":"airplay","protocol":"tcp","subtypes":[]},"replyDomain":".","flags":3,"networkInterface":"en0"}
{"interfaceIndex":4,"type":{"name":"raop","protocol":"tcp","subtypes":[]},"replyDomain":".","flags":3,"networkInterface":"en0"}
{"interfaceIndex":4,"type":{"name":"spotify-connect","protocol":"tcp","subtypes":[]},"replyDomain":".","flags":3,"networkInterface":"en0"}
{"interfaceIndex":4,"type":{"name":"androidtvremote","protocol":"tcp","subtypes":[]},"replyDomain":".","flags":3,"networkInterface":"en0"}
{"interfaceIndex":4,"type":{"name":"nvstream","protocol":"tcp","subtypes":[]},"replyDomain":".","flags":3,"networkInterface":"en0"}
{"interfaceIndex":4,"type":{"name":"udisks-ssh","protocol":"tcp","subtypes":[]},"replyDomain":".","flags":2,"networkInterface":"en0"}
```

**Comment by MarshallOfSound** [comment]
@stgarf I wonder if it is advertising under `nvstream` 😕 That would be quite strange.

Just to clarify does the Chromecast button appear at all in GPMDP?  I can see at least one `googlecast` record being broadcasted.

**Comment by stgarf** [comment]
@MarshallOfSound to clarify, no, the chromecast button doesn't even appear at all in GPMDP

(I can see it in my browser... here's two more screenshots, one from browser and one from GPMDP).

<img width="1517" alt="Google Music in Chrome Browser" src="https://cloud.githubusercontent.com/assets/1694002/21497527/7507ced0-cbda-11e6-9fd7-9d470c17329c.png">

![GPMDP missing ChromeCast icon?](https://cloud.githubusercontent.com/assets/1694002/21497548/9738f218-cbda-11e6-9068-8913c8efe90e.png)

**Comment by MarshallOfSound** [comment]
@stgarf Being a bit picky but I can't see the Chromecast icon in the screenshot of your browser.  It should appear in the GPM UI in the bottom right in between the volume and queue icons.

**Comment by stgarf** [comment]
@MarshallOfSound yeap... sure! It's there...

![screen shot 2016-12-27 at 2 21 03 am](https://cloud.githubusercontent.com/assets/1694002/21497650/5aa5e9ae-cbdb-11e6-9bd1-c3ff11aa74ae.png)

**Comment by MarshallOfSound** [comment]
OK so typing this out so I can cry about the situation.

1. It works fine in Chrome
2. Manually scanning finds the `googlecast` service
3. But the button still doesn't appear...

This is quite strange, can you jump on Gitter real quick

**Comment by stgarf** [comment]
We've done debugging over Gitter. Here's a summary:
```
Samuel Attard @MarshallOfSound Dec 27 02:37
/Applications/Google Play Music Desktop Player.app/Contents/Resources/app.asar/node_modules/node-mdns-easy/dist/browser.js:46 Error: dns service error: no such record(…)(anonymous function) @ /Applications/Google Play Music Desktop Player.app/Contents/Resources/app.asar/node_modules/node-mdns-easy/dist/browser.js:46
That seems relevent
Let me check that line
```

Starting an mDSN browser instance failed
```
var browser = require('mdns').createBrowser(require('mdns').tcp('googlecast'));
browser.on('serviceUp', function(service) {
  console.log(JSON.stringify(service));
});
browser.start();
```

```
events.js:160 Uncaught Error: dns service error: no such recordon_get_addr_info_done @ resolver_sequence_tasks.js:72MDNSService.self.watcher.callback @ mdns_service.js:18
```

I can properly find and resolve Chromecast instances via mDNS on my laptop:
```
$  dns-sd -B _googlecast._tcp
Browsing for _googlecast._tcp
DATE: ---Wed 28 Dec 2016---
14:07:00.107  ...STARTING...
Timestamp     A/R    Flags  if Domain               Service Type         Instance Name
14:07:00.108  Add        3   4 local.               _googlecast._tcp.    SHIELD-Android-TV-7e3a9a0e05b7707090805ed1091c7149
14:07:00.108  Add        2   4 local.               _googlecast._tcp.    Chromecast-c1180a60d6c72e0c855ef8904d9d6597
^C
```

```
$  dns-sd -L SHIELD-Android-TV-7e3a9a0e05b7707090805ed1091c7149 _googlecast._tcp. local.
Lookup SHIELD-Android-TV-7e3a9a0e05b7707090805ed1091c7149._googlecast._tcp..local.
DATE: ---Wed 28 Dec 2016---
14:12:28.511  ...STARTING...
14:12:28.512  SHIELD-Android-TV-7e3a9a0e05b7707090805ed1091c7149._googlecast._tcp.local. can be reached at 7e3a9a0e-05b7-7070-9080-5ed1091c7149.local.:8009 (interface 4)
 id=7e3a9a0e05b7707090805ed1091c7149 rm=39A8C42C1066FD3A ve=05 md=SHIELD\ Android\ TV ic=/setup/icon.png fn=SHIELD ca=2053 st=0 bs=FFFFFFFFFFFF rs=
^C
```

This does seem somewhat similar to this issue: agnat/node_mdns#181, however the "fix" in that issue doesn't work for my case. and to reiterate some other facts:
1. It works fine in Chrome (i.e. Cast button appears)
1. Manually scanning (via mDNS / dns-sd command line) finds the googlecast service
1. But the button still doesn't appear within GPMDP, however

**Comment by jostrander** [comment]
Do you have IPv6 disabled? I think that can play into this a little. Also we may have to change the resolver sequence to the preferred resolver for mac, only on mac. Needs more testing though, and I don't have a mac to test on.

**Comment by stgarf** [comment]
IPv6 is enabled and working AFAICT

```
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 80:00:6e:c5:d4:ea
	inet6 fe80::2a:ea6d:44f7:84f%en0 prefixlen 64 secured scopeid 0x4
	inet 192.168.1.137 netmask 0xffffff00 broadcast 192.168.1.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
```

@jostrander Let me know what you'd like to test and I'd be happy to perform the testing... :)

**Comment by MarshallOfSound** [comment]
@stgarf Maybe try with IPV6 disabled?

**Comment by stgarf** [comment]
Disabling v6 (setting to link-local on OS X) has no effect..

**Comment by deletescape** [comment]
Maybe the title of this issue should be changed :blush: because generally casting works on osx (atleast for me it does). Seems to be a specific issue with the Shield.

**Comment by MarshallOfSound** [comment]
As mentioned previously I'm going to close this out as there it literally nothing I can do to fix this (and it may not even be an issue with the app rather a more likely network issue).

If you continue to have issues attempting to fix in `electron-chromecast` would be your best bet
