### ISSUE TITLE
Update Debian package to 4.0.5 

### ISSUE THREAD

**Issue by rattboi** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2037]
**OS:**
Linux (Ubuntu Xenial, specifically)

**Issue Descriptions:**
Have the debian repo set up, and am currently running 4.0.3. Current is 4.0.5, and yet is unavailable through the repo.

**Steps to Reproduce:**
'apt-get install google-play-music-desktop-player' should give you version 4.0.5
It instead gives you 4.0.3

**Comment by MarshallOfSound** [comment]
Just uploaded now 👍 

Not sure why my release script didn't upload them the last few times 😢
