### ISSUE TITLE
"Show mini player" leads to install option dead end with no exit

### ISSUE THREAD

**Issue by abrammer** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#204]
From the triple dot menu left of play/pause controls "Show mini player" leads to a install mini player screen.  There's no apparent way out without installing the mini player.  Had to quit and reopen to get out of the dead end

**Comment by MarshallOfSound** [comment]
Lol, that must be a new button.  Haven't seen it before.  Will hide with custom CSS

**Comment by 206airmail** [comment]
If that's not how to being up the mini player then how do I? I don't see the little button for it that there was in the old version

**Comment by abrammer** [comment]
Yeah, I think the problem is the lack of a back button now. Means if it's not installed and you don't want to install you're stuck in a dead end. There are other dead ends because of the lack of a back button as well.

**Comment by 206airmail** [comment]
So how do I install the mini player? I found your Repo for it, but not quite sure as how to install it

**Comment by MarshallOfSound** [comment]
The mini player is already there
There should be a button in the bottom right of the player to open it

Should look like a little arrow
