### ISSUE TITLE
API Possibilities?

### ISSUE THREAD

**Issue by stuntguy3000** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2042]
Hi there,

I was wondering if there was an API for the desktop client. A way to do things like see the current playing song, pause/skip controls etc.

I couldn't find any existing issues talking about this.

**Comment by MarshallOfSound** [comment]
...

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/docs/PlaybackAPI_WebSocket.md

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/docs/PlaybackAPI_WebSocket.md

**Comment by stuntguy3000** [comment]
Totally read that.

Thanks mate!
