### ISSUE TITLE
Keys unavailable as Hot Keys

### ISSUE THREAD

**Issue by nwalasek** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2043]
**OS:** Windows 10 x64

**Issue Descriptions:** Unable to set play/pause (or other) hotkey actions to Print Screen, Scroll Lock & Pause/Break keys, even while combining with the CTRL key.

Is it possible to set a hotkey to an "F" key or Print Screen, Scroll Lock & Pause/Break keys without using a CTRL modifier?

**Comment by MarshallOfSound** [comment]
> Is it possible to set a hotkey to an "F" key or Print Screen, Scroll Lock & Pause/Break keys without using a CTRL modifier?

No, these are global hotkeys and absorb the key events when activated.  I.e. if you set "F" as a hot key the F key would not work in any other applicaiton.

> Unable to set play/pause (or other) hotkey actions to Print Screen, Scroll Lock & Pause/Break keys, even while combining with the CTRL key.

This is as expected, the play/pause keys are set by default and are seperate from the hotkey settings.  The other keys simply shouldn't be used as global hotkeys IMO (bad practice to absorb key events for something like the break key)
