### ISSUE TITLE
[Enhancement Request] COMMAND-L/CTRL-L/ALT-D Should select the search bar

### ISSUE THREAD

**Issue by itbuildcharacter** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2045]
OS: 
Apple OS X/macOS 10.1X.X; Windows 7, 8.1, 10; Linux distros

Issue Description: 
As a power Google Play Music Desktop Player user I would like to be able to select the search bar using the same keyboard shortcuts that I use in a web browser (Chrome/Firefox/et al) to select the address bar. 

Benefit: 
Those of us that do a lot of text editing would find this enhancement useful as it increases efficiency, precision, and improves the complementarity of the advantages of using the keyboard and mouse.

Steps to Reproduce: 
On the keyboard press COMMAND-L or CTRL-L or ALT-D

**Comment by MarshallOfSound** [comment]
The search bar is a "search / find" field and therefore I have associated the Control/Command+F shortcut with it as this is the "standard" for search boxes.

I won't be taking on this request as I don't see the need to add an alternate, less intuitive hotkey.

Merry Christmas!

**Comment by stgarf** [comment]
I second @itbuildcharacter's suggestion for ⌘+L since it mirrors "less intuitive" browser standards such as Chrome, Firefox, and Safari 👍

**Comment by MarshallOfSound** [comment]
> since it mirrors "less intuitive" browser standards such as Chrome, Firefox, and Safari

No it doesn't, in browsers (which GPMDP is not) Command + L focuses the URL bar not a search box.  In modern browsers the URL bar doubles as a web search entry point but that searches the entire web not the current website.

On the other hand in most application (not just web browsers) Command + F is universally accepted as searching in the current application / context.

Hopefully that explains my opinion a bit better 👍
