### ISSUE TITLE
Bug - Whole window shifts to left side

### ISSUE THREAD

**Issue by Alipoodle** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2047]
**OS:**
Windows 10

**Issue Descriptions:**
![image](https://cloud.githubusercontent.com/assets/17199186/21473074/0390b6ca-caf1-11e6-8099-a48a7b7f2813.png)
As you can see by the sides of the program, it's randomly Shifted over, this has happened to me a few times, _on my laptop and not my desktop_. 

However, the left side menu still will hold to the left side, but the playlist will leave the gap.
![image](https://cloud.githubusercontent.com/assets/17199186/21473086/7e71ea8a-caf1-11e6-9805-daf329288aec.png)
While the playlist menu still shifts along.
![image](https://cloud.githubusercontent.com/assets/17199186/21473087/86cb6440-caf1-11e6-901e-010272f161d7.png)

**Steps to Reproduce:**
This generally seems to happen when i open the Playlist or side menu.

**Comment by MarshallOfSound** [comment]
This is a known Electron issue to do with guest resizing.  If it happens a quick resize wiggle should force a redraw 👍 

This will hopefully be fixed in an upcoming Chromium bump (55 off the top of my head)

**Comment by Alipoodle** [comment]
Thanks! It's generally not a problem as i can still reach everything!
