### ISSUE TITLE
run powershell script error

### ISSUE THREAD

**Issue by zhouhong** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2048]
**OS:**

**Issue Descriptions:**
所在位置 C:\Users\hongzhou\Desktop\setup_windows.ps1:48 字符: 1
+ }
+ ~
子表达式中缺少右“)”。
所在位置 C:\Users\hongzhou\Desktop\setup_windows.ps1:92 字符: 1
+ } else { Write-Host "Node is already installed and up-to-date! (No
+ ~
子表达式中缺少右“)”。
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingEndParenthesisInSubexpression
**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment]
The powershell script still runs on my machine 😕 Can you verify you haven't modified the script in any way.

**Comment by MarshallOfSound** [comment]
Closing as no response in 2 weeks
