### ISSUE TITLE
Menu bar icon OSX

### ISSUE THREAD

**Issue by albergrbg** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#205]
Ability to remove/hide the menu bar icon or a better integration with de OS.

**Comment by MarshallOfSound** [comment]
The menu bar icon is an intergral part of the app and as such I don't think it should be treated as a toggleable feature.  Other opinions welcome but for now the icon is going to stay.  If the look and feel of icon is the issue that has already been handled
