### ISSUE TITLE
Interface hangs for a minute after startup

### ISSUE THREAD

**Issue by Nemo64** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2052]
**OS:**
Windows 10 Pro (10.0.14393)

**Issue Descriptions:**
The Interface hangs and can't be controlled anymore. Shortcuts don't work either.
It seems to recoverer after a minute or so after which it works fine.

**Steps to Reproduce:**
- Start the app for the first time (or after killing it in the task manager).
- Then play a song (might be optional)
- Hover over the minimize button on the top right.
- Interface hangs.

**Comment by MarshallOfSound** [comment]
Disable desktop notifications.

It's a known issue on newish Windows 10 installs
