### ISSUE TITLE
High Load under Fedora 25

### ISSUE THREAD

**Issue by utahcon** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2053]
**OS:**
Operating System Details:
OS: linux
OS Version: 4.8.14-300.fc25.x86_64
OS Arch: x64
System Memory: 16687939584

**Issue Descriptions:**
Dump Details:
Timestamp: Tue Dec 27 2016 14:07:04 GMT-0700 (MST)

App Details:
Version: 4.0.3
Electron Version: ^1.4.5
Development Build: false

**Steps to Reproduce:**

1) Run GMPDP, then monitor load on system. Consistently running at 4.x-5.x load with JUST GMPDP running. Memory looks fine, just CPU usage seems out of control. Seems really off beat with Chrome + GMP. 

I am happy to provide any details you need.

**Comment by stuartsoft** [comment]
I've been having a similar issue on MacOS 10.12.2. htop says it's using 8-9% load even when just idling the app, not even playing music or anything.

**Comment by utahcon** [comment]
After a day of using just the web client, in Chrome, I am seeing that the "native" player is really take some serious resources too. I wonder if this isn't in fact an upstream problem.

**Comment by MarshallOfSound** [comment]
> I wonder if this isn't in fact an upstream problem.

It is, the GPM web player is notoriously resource hungry.  I've discussed this before and investigated in depth and it always comes back to GPM code.
