### ISSUE TITLE
Twice rendering icon tray on Linux

### ISSUE THREAD

**Issue by varlesh** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2054]
Icon rendered twice
when start gpmdp - icon draw and looks fine.
![image](https://cloud.githubusercontent.com/assets/8083855/21510500/936f71a6-ccad-11e6-8c0a-6109bf665552.png)
But after some seconds - icon rendered again and blurred
![image](https://cloud.githubusercontent.com/assets/8083855/21510506/a18ac47a-ccad-11e6-92ff-c80a01691a61.png)

OS: elementaryOS Loki (Ubuntu 16.04)

**Comment by MarshallOfSound** [comment]
The file being used is identical but is being dynamically set during runtime on certain events.  I assume that this is an issue with Loki as my OS's are fine.  (Ubuntu 16, macOS and Windows 7/10).  Please raise this with Loki, if required point them to Electron's tray code to explain how the tray icon is being dynamically set

**Comment by varlesh** [comment]
but this not happene with other Electron apps (wire, skype4linux alpha and etc)

**Comment by MarshallOfSound** [comment]
They do not dynamically set there app icon.  We do
