### ISSUE TITLE
Mini Player Controls change size

### ISSUE THREAD

**Issue by cbluth** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2055]
OS:
Linux AMD64

Issue Descriptions:
Mini Player Controls change size

Steps to Reproduce:
Enter Mini Player mode and adjust bigger the size of the window, hover mouse on and off repeatedly on the window. The controls will snap back to the very small size.

Suggested Solution:
Always keep controls centered in window at bottom (or provide the option), or keep controls relative size  to width of window.

**Comment by MarshallOfSound** [comment]
Can you provide a screenshot or screencast of this issue.

**Comment by cbluth** [comment]
![image](https://cloud.githubusercontent.com/assets/6709636/21530085/d11bb04a-cd03-11e6-8e84-e93e39cd5fc8.png)

![image](https://cloud.githubusercontent.com/assets/6709636/21530092/e088eaa2-cd03-11e6-88c7-bc0f782e0e48.png)

**Comment by MarshallOfSound** [comment]
This appears to be the good ol' zoom reset issue we had before.  There is an upstream fix for this in Electron somewhere that we will pull in in an upcoming version.
