### ISSUE TITLE
Display will not sleep while program is running

### ISSUE THREAD

**Issue by z3rods** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2057]
Running Windows 10 Pro 64-bit. EDIT: Forgot to add that I am using the latest version (4.0.5 as of this post).

While the program is running, whether in the background or in focus, and regardless of the play state, it will keep my displays on. 

As you can see in the image, it's sending requests for the display. Even manually sleeping the monitors (done by setting the power button to put the displays to sleep in Windows Power Options) has no effect; they either immediately come back on or will come back on within moments. 
![image](https://cloud.githubusercontent.com/assets/15926276/21566233/3c8677b8-ce6f-11e6-992a-c06c694bd955.png)

I never noticed the issue before since I'd just turn the TV I was using as a primary monitor off, but now that I have actual monitors, it's become apparent. Please let me know if you need any other info.

**Comment by jostrander** [comment]
You don't have the setting for preventing sleep turned on do you?

**Comment by z3rods** [comment]
Well I'm an idiot. I wasn't even aware there was such an option. Welp, thanks!
