### ISSUE TITLE
Global hotkeys no longer work

### ISSUE THREAD

**Issue by smartmarke** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#206]
Just got the latest update this morning, and my keyboard's global hotkeys seem to have stopped functioning. I used to be able to use punch in the keystrokes Fn+F10, F11, or F12 (Skip back, Pause/Play, Skip forward). Now these do nothing in GPMDP, whether I have the window in focus or not.

**Comment by gganno** [comment]
This is also broken for me, It works for all other applications except ver. 3.0

**Comment by sippi90** [comment]
I've a Microsoft Sidewinder X4 and global media keys worked for me with version 2.x but since 3.x it's no longer working.

**Comment by francoislg** [comment]
Just installed this, and can confirm play/pause doesn't work.

On Windows 10 latest build.

**Comment by isick1e** [comment]
Agreed. Windows 10 x64 installed both x86 and x64 version of 3.0.0 and hotkeys are all shown as 'Not Set' and cannot change them or use the default global media keys either. Tried the more basic troubleshooting stuff like running as admin and changing compatibility options to no avail.

**Comment by flakeparadigm** [comment]
On Ubuntu 15.10 I'm also not getting any of the Play/Pause/Next/Prev/Stop keys working.
This issue is both on the master and PR #209 branch.

**Comment by spacewolf9** [comment]
I've just found out about this player and had been desperately waiting for a desktop solution to Play Music. So awesome job. However, I'm also running Win10 x64 and can confirm that the hotkey section is non functional on 3.0 for me.

**Comment by MarshallOfSound** [comment]
**FYI this is a prewritten copy paste response**

So your media buttons aren't working aye???  
Let's try fix that.

1. Are you using the Google Play Music chrome plugin?  If yes, remove it, and reboot your pc (sorry) and see if it works
2. Are you using a logitech keyboard?  If yes, turn off logitechs stupid software that manages your keyboard and try again?
3. Is there any other program that could possibly be "stealing" the keypresses?  (keyloggers, other media players Etc.)?  If so, close them and try again :+1: 

Good luck, if this doesn't work please respond

**Comment by gganno** [comment]
> Are you using the Google Play Music chrome plugin? If yes, remove it, and reboot your pc (sorry) and see if it works

This fixed it, thank you!

**Comment by MarshallOfSound** [comment]
That GPM chrome extension for some release "steals" all media key inputs.  It's really annoying

**Comment by isick1e** [comment]
I'd like to confirm that is indeed a fix for standard media keys to work again. Might want to sticky that for people with the Google Play Music extention still installed, just disable or uninstall the extension and close chrome through the task manager. 

Unfortunately I still can't set any of the hotkeys with any key on my keyboard in the desktop settings. They still show 'Not Set' regardless of what is used for input. Not sure what to try to fix that on my end but thanks for the media key fix!

**Comment by MarshallOfSound** [comment]
You need to have a "Ctrl" key somewhere in the hotkey you try to make

Click the "Not Set" box and try "Ctrl + Shift + P"

That should work :+1:

**Comment by isick1e** [comment]
> You need to have a "Ctrl" key somewhere in the hotkey you try to make

Thanks again man, any way that the hotkeys can be enabled on keys other than A-Z and Arrows eventually? Such as Page Up and Page Down.

**Comment by MarshallOfSound** [comment]
@isick1e Technically yes, but I had to write a shortcut parser myself to make that feature so I was keen to keep it nice and simple.

PR's are welcome :+1:

**Comment by smartmarke** [comment]
I've removed the GPM Chrome extension, made sure I don't have Logitech's keyboard software running, and have no other media key-using apps running. I am still not able to get media keys working.

**Comment by MattJeanes** [comment]
I removed GPM chrome extension and it worked after restarting but then it stopped working a few minutes later as other apps started up - I guess one of those is capturing it. It worked just fine in 2.x though :cry:

**Comment by MarshallOfSound** [comment]
Closing as the solution is out there, hopefully electron will see this as a problem and implement better shortcut handling

**Comment by yuranos** [comment]
I use Ubuntu 18.04 and 4.6.1 version of the app. While I can use Ctrl+.. keys as hotkeys, I can not set functional buttons.
At the same time I have the same app version installed via flathub and all hotkeys work there by default.
Anyone knows why?
