### ISSUE TITLE
Enabling dGPU on MacBook Pro

### ISSUE THREAD

**Issue by professionaljones** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2060]
**OS: macOS**

**Issue Descriptions:**
After having the app open and listening to some music, a new helper is created, PID:98477, enabling the dGPU in my 2015 MacBook Pro. I am confused as to why it needs the extra horsepower since it sits in the background most of the time.

**Steps to Reproduce:**
Open app
Start listening to media
15 to 20 mins pass
Helper is initialized

I only know this happens due to the gfxcardstatus app. [https://developer.apple.com/library/content/qa/qa1734/_index.html] Hope this helps.

**Comment by MarshallOfSound** [comment]
On all other platforms hardware acceleration is disabled, the issue on macOS is that on newer macbooks you get some really nasty render artifacts (white flashes everywhere) if you don't let it use hardware acceleration.  This unfortunately means that every now and again (even if the app is in the background) it will call on the dGPU for some meaningless task (Chromium plz).  These render issues should be handled in a Chromium update and then we can disable hardware acceleration on all platforms again.

Until then I'm sorry if it launches your dGPU but you really would hate the nasty looking alternative 😆 

Gonna close this as a wontfix as it is the lesser of two evils.

**Comment by MarshallOfSound** [comment]
On another note I'm pretty sure there is an app somewhere that can stop other apps requesting the dGPU

**Comment by professionaljones** [comment]
Fair enough. Thank you for quick reply!
