### ISSUE TITLE
Building on armhf fails

### ISSUE THREAD

**Issue by cbluth** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2061]
**OS:**
Ubuntu 16.04 armhf (armbian) on orange pi zero

**Issue Descriptions:**

> root@orangepizero:~/Google-Play-Music-Desktop-Player-UNOFFICIAL-# npm run build
> 
> > google-play-music-desktop-player@4.0.5 build /root/Google-Play-Music-Desktop-Player-UNOFFICIAL-
> > gulp build
> 
> [05:49:14] Requiring external module babel-register
> [05:49:32] Using gulpfile ~/Google-Play-Music-Desktop-Player-UNOFFICIAL-/gulpfile.babel.js
> [05:49:32] Starting 'clean-material'...
> [05:49:32] Starting 'clean-utility'...
> [05:49:32] Starting 'clean-internal'...
> [05:49:32] Starting 'clean-images'...
> [05:49:32] Starting 'clean-less'...
> [05:49:32] Starting 'clean-fonts'...
> [05:49:32] Starting 'clean-html'...
> [05:49:32] Starting 'clean-locales'...
> [05:49:32] Finished 'clean-material' after 337 ms
> [05:49:32] Starting 'materialize-js'...
> [05:49:32] Finished 'clean-utility' after 260 ms
> [05:49:32] Starting 'utility-js'...
> [05:49:32] Finished 'clean-internal' after 321 ms
> [05:49:32] Starting 'transpile'...
> [05:49:32] Finished 'clean-images' after 331 ms
> [05:49:32] Starting 'copy-static-images'...
> [05:49:32] Finished 'clean-less' after 342 ms
> [05:49:32] Starting 'less'...
> [05:49:32] Finished 'clean-fonts' after 369 ms
> [05:49:32] Starting 'fonts'...
> [05:49:32] Finished 'clean-html' after 419 ms
> [05:49:32] Starting 'html'...
> [05:49:32] Finished 'clean-locales' after 428 ms
> [05:49:32] Starting 'locales'...
> [05:49:36] Finished 'materialize-js' after 3.89 s
> [05:49:38] Finished 'utility-js' after 5.88 s
> [05:49:39] Finished 'html' after 6.49 s
> [05:49:50] Finished 'less' after 18 s
> [05:49:51] Finished 'locales' after 18 s
> [05:49:51] Finished 'copy-static-images' after 19 s
> [05:49:51] Starting 'images'...
> [05:49:57] Finished 'images' after 5.92 s
> [05:50:02] Finished 'fonts' after 30 s
> [05:50:44] Finished 'transpile' after 1.18 min
> [05:50:44] Starting 'build'...
> [05:50:44] Finished 'build' after 492 μs
> root@orangepizero:~/Google-Play-Music-Desktop-Player-UNOFFICIAL-# npm start
> 
> > google-play-music-desktop-player@4.0.5 prestart /root/Google-Play-Music-Desktop-Player-UNOFFICIAL-
> > pre-flight && node vendor/mac_patch_dev.js
> 
> Starting pre-flight checks
> Processing production dependencies
> Processing development dependencies
> Processing optional dependencies
> Dependencies are all up to date, looking good!
> Monkey patching your Info.plist
> 
> > google-play-music-desktop-player@4.0.5 start /root/Google-Play-Music-Desktop-Player-UNOFFICIAL-
> > electron . --dev
> 
> fs.js:557
>   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
>                  ^
> 
> Error: ENOENT: no such file or directory, open '/root/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/electron/path.txt'
>     at Object.fs.openSync (fs.js:557:18)
>     at Object.fs.readFileSync (fs.js:467:33)
>     at Object.<anonymous> (/root/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/electron/index.js:4:42)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.require (module.js:498:17)
>     at require (internal/module.js:20:19)
> 
> npm ERR! Linux 3.4.113-sun8i
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
> npm ERR! node v7.3.0
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> npm ERR! google-play-music-desktop-player@4.0.5 start: `electron . --dev`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the google-play-music-desktop-player@4.0.5 start script 'electron . --dev'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the google-play-music-desktop-player package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     electron . --dev
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs google-play-music-desktop-player
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls google-play-music-desktop-player
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /root/Google-Play-Music-Desktop-Player-UNOFFICIAL-/npm-debug.log
> root@orangepizero:~/Google-Play-Music-Desktop-Player-UNOFFICIAL-# npm run make:deb
> 
> > google-play-music-desktop-player@4.0.5 make:deb /root/Google-Play-Music-Desktop-Player-UNOFFICIAL-
> > gulp make:linux:deb
> 
> [05:51:42] Requiring external module babel-register
> [05:51:52] Using gulpfile ~/Google-Play-Music-Desktop-Player-UNOFFICIAL-/gulpfile.babel.js
> [05:51:52] Starting 'deb:linux'...
> [05:51:52] Starting 'clean-dist-linux-32'...
> [05:51:52] Starting 'clean-material'...
> [05:51:52] Starting 'clean-utility'...
> [05:51:52] Starting 'clean-internal'...
> [05:51:52] Starting 'clean-images'...
> [05:51:52] Starting 'clean-less'...
> [05:51:52] Starting 'clean-fonts'...
> [05:51:52] Starting 'clean-html'...
> [05:51:52] Starting 'clean-locales'...
> [05:51:52] Finished 'clean-dist-linux-32' after 401 ms
> [05:51:53] Finished 'clean-material' after 1.09 s
> [05:51:53] Starting 'materialize-js'...
> [05:51:53] Finished 'clean-utility' after 1.09 s
> [05:51:53] Starting 'utility-js'...
> [05:51:53] Finished 'clean-less' after 1.11 s
> [05:51:53] Starting 'less'...
> [05:51:53] Finished 'clean-html' after 1.18 s
> [05:51:53] Starting 'html'...
> [05:51:54] Finished 'clean-images' after 1.54 s
> [05:51:54] Starting 'copy-static-images'...
> [05:51:54] Finished 'clean-fonts' after 1.55 s
> [05:51:54] Starting 'fonts'...
> [05:51:55] Finished 'materialize-js' after 1.52 s
> [05:51:55] Finished 'clean-locales' after 2.91 s
> [05:51:55] Starting 'locales'...
> [05:51:55] Finished 'utility-js' after 2.23 s
> [05:51:56] Finished 'html' after 2.36 s
> [05:51:57] Finished 'less' after 4.14 s
> [05:51:58] Finished 'copy-static-images' after 3.8 s
> [05:51:58] Starting 'images'...
> [05:51:58] Finished 'locales' after 2.54 s
> [05:51:58] Finished 'fonts' after 4.18 s
> [05:51:58] Finished 'clean-internal' after 5.93 s
> [05:51:58] Starting 'transpile'...
> [05:52:04] Finished 'images' after 6.21 s
> [05:53:06] Finished 'transpile' after 1.12 min
> [05:53:06] Starting 'build'...
> [05:53:06] Finished 'build' after 536 μs
> [05:53:06] Starting 'build-release'...
> [05:53:07] Finished 'build-release' after 1.6 s
> [05:53:07] Starting 'package:linux:32'...
> Rebuilding native modules for electron
> Couldn't find electron-prebuilt and no --node-module-version parameter set, always rebuilding
> 
> 
> > electron@1.4.12 postinstall /root/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/electron
> > node install.js
> 
> 
> > mdns@2.3.3 install /root/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/mdns
> > node-gyp rebuild
> 
> make: Entering directory '/root/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/mdns/build'
>   CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
> dns_sd_bindings.target.mk:149: recipe for target 'Release/obj.target/dns_sd_bindings/src/dns_sd.o' failed
> make: Leaving directory '/root/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/mdns/build'
> 
> 
> g++: error: unrecognized command line option ‘-m32’
> make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/root/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
> gyp ERR! System Linux 3.4.113-sun8i
> gyp ERR! command "/usr/bin/nodejs" "/root/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /root/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/mdns
> gyp ERR! node -v v7.3.0
> gyp ERR! node-gyp -v v3.4.0
> gyp ERR! not ok 
> 
> npm ERR! Linux 3.4.113-sun8i
> npm ERR! argv "/usr/bin/nodejs" "/root/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/npm/bin/npm-cli.js" "rebuild" "--runtime=electron" "--target=1.4.12" "--arch=ia32" "--update-binary"
> npm ERR! node v7.3.0
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> npm ERR! mdns@2.3.3 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the mdns@2.3.3 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the mdns package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs mdns
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls mdns
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /root/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/npm-debug.log
> 
> 
> Process exited with code: 1
> Error: Process exited with code: 1
>     at ChildProcess.<anonymous> (/root/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/electron-rebuild/lib/spawn.js:55:26)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:885:16)
>     at Socket.<anonymous> (internal/child_process.js:334:11)
>     at emitOne (events.js:96:13)
>     at Socket.emit (events.js:188:7)
>     at Pipe._handle.close [as _onclose] (net.js:501:12)
> 
> Rebuild failed
> 
> npm ERR! Linux 3.4.113-sun8i
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "make:deb"
> npm ERR! node v7.3.0
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> npm ERR! google-play-music-desktop-player@4.0.5 make:deb: `gulp make:linux:deb`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the google-play-music-desktop-player@4.0.5 make:deb script 'gulp make:linux:deb'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the google-play-music-desktop-player package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     gulp make:linux:deb
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs google-play-music-desktop-player
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls google-play-music-desktop-player
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /root/Google-Play-Music-Desktop-Player-UNOFFICIAL-/npm-debug.log
> root@orangepizero:~/Google-Play-Music-Desktop-Player-UNOFFICIAL-# cat /root/Google-Play-Music-Desktop-Player-UNOFFICIAL-/npm-debug.log
> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'make:deb' ]
> 2 info using npm@3.10.10
> 3 info using node@v7.3.0
> 4 verbose run-script [ 'premake:deb', 'make:deb', 'postmake:deb' ]
> 5 info lifecycle google-play-music-desktop-player@4.0.5~premake:deb: google-play-music-desktop-player@4.0.5
> 6 silly lifecycle google-play-music-desktop-player@4.0.5~premake:deb: no script for premake:deb, continuing
> 7 info lifecycle google-play-music-desktop-player@4.0.5~make:deb: google-play-music-desktop-player@4.0.5
> 8 verbose lifecycle google-play-music-desktop-player@4.0.5~make:deb: unsafe-perm in lifecycle true
> 9 verbose lifecycle google-play-music-desktop-player@4.0.5~make:deb: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/root/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
> 10 verbose lifecycle google-play-music-desktop-player@4.0.5~make:deb: CWD: /root/Google-Play-Music-Desktop-Player-UNOFFICIAL-
> 11 silly lifecycle google-play-music-desktop-player@4.0.5~make:deb: Args: [ '-c', 'gulp make:linux:deb' ]
> 12 silly lifecycle google-play-music-desktop-player@4.0.5~make:deb: Returned: code: 1  signal: null
> 13 info lifecycle google-play-music-desktop-player@4.0.5~make:deb: Failed to exec make:deb script
> 14 verbose stack Error: google-play-music-desktop-player@4.0.5 make:deb: `gulp make:linux:deb`
> 14 verbose stack Exit status 1
> 14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
> 14 verbose stack     at emitTwo (events.js:106:13)
> 14 verbose stack     at EventEmitter.emit (events.js:191:7)
> 14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
> 14 verbose stack     at emitTwo (events.js:106:13)
> 14 verbose stack     at ChildProcess.emit (events.js:191:7)
> 14 verbose stack     at maybeClose (internal/child_process.js:885:16)
> 14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> 15 verbose pkgid google-play-music-desktop-player@4.0.5
> 16 verbose cwd /root/Google-Play-Music-Desktop-Player-UNOFFICIAL-
> 17 error Linux 3.4.113-sun8i
> 18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "make:deb"
> 19 error node v7.3.0
> 20 error npm  v3.10.10
> 21 error code ELIFECYCLE
> 22 error google-play-music-desktop-player@4.0.5 make:deb: `gulp make:linux:deb`
> 22 error Exit status 1
> 23 error Failed at the google-play-music-desktop-player@4.0.5 make:deb script 'gulp make:linux:deb'.
> 23 error Make sure you have the latest version of node.js and npm installed.
> 23 error If you do, this is most likely a problem with the google-play-music-desktop-player package,
> 23 error not with npm itself.
> 23 error Tell the author that this fails on your system:
> 23 error     gulp make:linux:deb
> 23 error You can get information on how to open an issue for this project with:
> 23 error     npm bugs google-play-music-desktop-player
> 23 error Or if that isn't available, you can get their info via:
> 23 error     npm owner ls google-play-music-desktop-player
> 23 error There is likely additional logging output above.
> 24 verbose exit [ 1, true ]
> root@orangepizero:~/Google-Play-Music-Desktop-Player-UNOFFICIAL-# 
> 

**Steps to Reproduce:**
Follow these steps to attempt a build:
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/README.md

**Comment by MarshallOfSound** [comment]
Looks like `electron` failed to download to your local clone.  Can you wipe your node_modules and try again.

For dev related things you'll probably get a faster resolution from chatting in [Gitter](https://gitter.im/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) so if you head in there I'll try help you get it going.
