### ISSUE TITLE
Desktop Player Crashes

### ISSUE THREAD

**Issue by Amiral7224** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2064]
**OS:**
Windows 10 (Pro)
Version: 1607
OS Build: 14393.576

**PC Info**
RAM: 8.00 GB
Processor: Intel Core i5-5200U (2.20GHz)
- 64 Bit
- Google Play Desktop Player Version 4.0.5

**Issue Descriptions:**
When playing music, after manually switching song, or the player automatically switching song; The entire interface freezes yet the music continues to play, a manual "End Task" is needed.

**Steps to Reproduce:**
Play music, then tap next.

**Comment by MarshallOfSound** [comment]
> When playing music, after manually switching song, or the player automatically switching song; The entire interface freezes yet the music continues to play, a manual "End Task" is needed.

FYI I would refer to this as a "freeze" 😆 

And with that in mind this issue has been reported before, basically just disable Desktop Notifications in GPM settings.  It's a bug somewhere in the dependency chain
