### ISSUE TITLE
Mini player with no borders

### ISSUE THREAD

**Issue by Amiral7224** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2065]
**Enhancement Request**

**OS:**
Windows 10

**Issue Descriptions:**
It would be nice to have a miniplayer (same as right now) without any borders, much like apple has now, where just the artwork is visible.

Example: http://cdn.osxdaily.com/wp-content/uploads/2014/11/itunes-album-art-player-view.jpg

**Comment by MarshallOfSound** [comment]
The borders are currently required as a work-around to a visual bug to do with hovering events.  You can track generic enhancements to the mini player here #701
