### ISSUE TITLE
No Audio Device Detected

### ISSUE THREAD

**Issue by bfaria** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2069]
**OS:**

Ubuntu 16.04.1

**Issue Descriptions:**

It is not possible to get to the initial screen of Google-Play-Music-Desktop-Player. I can open the settings dialog via the tray-icon and it seems it may lie on the fact, that no audio device is listed. The tray-icon option for audio devices remains at "loading devices". 

![image](https://cloud.githubusercontent.com/assets/2026153/21610583/2a67046e-d1c9-11e6-9d2b-a50d001c6f5e.png)

Audio is working as expected in all other applications, including Chrome and Firefox.

**Steps to Reproduce:**

Opening the application on my system is enough to reproduce the error.

Let me know if there is any log-information I can provide to help with the problem hunt.

**Comment by MarshallOfSound** [comment]
The audio device list is only fetched when the main window of GPMDP is launched.  Whatever is causing the issue it is not the audio device list.

Can you please provide your error log / debug zip file.

**Comment by bfaria** [comment]
I found the issue. A new firewall rule was preventing the connection to the server.
