### ISSUE TITLE
Lyrics auto scrolling preferences reset on resize

### ISSUE THREAD

**Issue by nirmalspeed** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2070]
**OS: OSX**

**Issue Descriptions: My preferences have lyrics set to NOT auto scroll. However, I keep finding the lyrics scrolling after I resize the window of the player.**

**Steps to Reproduce:
1) Set lyrics auto scrolling to be unchecked
2) Open lyrics with a song playing
3) Resize window and observe lyrics start scrolling**

**Comment by delurfangs** [comment]
same occurring on windows 10. After window resize the scroll lyrics option is still shows unchecked in settings and must be checked and then unchecked to return to static lyrics.
