### ISSUE TITLE
Error loading DBUS version change from 50 to 51

### ISSUE THREAD

**Issue by ZenHarbinger** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2071]
**OS:** Ubuntu 16.10 64-bit

**Issue Descriptions:** Error loading DBUS

**Steps to Reproduce:** Compile and run on Ubuntu

error: Uncaught Exception. Error: Module version mismatch. Expected 50, got 51.  
https://gist.github.com/ZenHarbinger/a57f053709e4bf8786b83bc720534327  
I am also not seeing chromcast options, may be related?  
Also not working through mpris.

**Comment by MarshallOfSound** [comment]
If you are running it manually `electron-rebuild` is currently having some issues (which I am fixing).  Please try again in a few hours when a new release of rebuild is out 👍

**Comment by saintdev** [comment]
Is this supposed to be fixed?

I'm experiencing the same issue compiling from latest git HEAD with the latest version of node. If I use the latest LTS version (`6.9.4`), I get
```
error: Uncaught Exception. Error: Module version mismatch. Expected 50, got 48.
```
instead.

On another box I am getting an undefined symbol instead, but with the same backtrace
```
error: Uncaught Exception. Error: /tmp/.org.chromium.Chromium.98jfmO: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEi
```
