### ISSUE TITLE
Request: toggle task bar icon off

### ISSUE THREAD

**Issue by PierBover** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2072]
I'm on macOS and the task bar icon bothers me.

I don't see the option in preferences so I'm assuming this isn't possible.

Would a PR request with this feature be accepted? I could implement this myself.

**Comment by berryelectronics** [comment]
this has been discussed often
#300 #636 or #1563 are some examples

TL;DR: Nope

**Comment by MarshallOfSound** [comment]
#300 is more of an example on how to be annoying that a deep discussion on this issue 😆 

But yeah, until the window management logic is fundamentally decoupled from the tray icon (this is harder than it sounds), we can't remove the tray icon 👍
