### ISSUE TITLE
Music Library -> Shuffle Keyboard Shortcut

### ISSUE THREAD

**Issue by jwmann** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2075]
I know this isn't technically the Google Play Music Desktop Players fault but I've always found it pretty cumbersome to always have to open the left sidebar, then choose Library from the left and then move my mouse to the complete opposite side of the screen to hit Shuffle. Doing this every time you start the app gets very tiresome after a while.

Google should really put a gosh dang Library Shuffle button on the home page or something. Unless I'm missing something.

Is there a way to make a custom keyboard shortcut or something to just start Library Shuffle? 
Thanks.

**Comment by MarshallOfSound** [comment]
GPM has shortcuts for this kind of thing, hit your "/" key to see the list.

The shortcut to toggle shuffle is "s"

**Comment by jwmann** [comment]
I'm already aware of these shortcuts. ( It's the `?` key to find the list by the way ).
The things is, the `s` key doesn't initiate shuffle the same way that shuffle button does.

Pressing `s` merely toggles the shuffle feature, this only affects the current song queue.
It doesn't pre-shuffle your entire library of music and start auto-playing it.

Seriously, try it.

1. Start GPM from nothing. (Beginning from the Home page)
2. Press `g` and then `s`
3. Press `s`

Nothing happens, there's no ability to even start playing the current list.  
Toggling Shuffle on an empty song queue isn't going to shuffle anything.

I'm still open to suggestions to get the desired affect of that Shuffle button in the top right.
