### ISSUE TITLE
Lyric display not resetting as it should

### ISSUE THREAD

**Issue by ntowl24** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2076]
**OS: Windows 10** 

**Issue Descriptions: Show Lyrics option does not reset to the beginning at the end of a song.**

**Steps to Reproduce: Play any song on repeat. On the first run through, the lyrics will work wonderfully. If you repeat the song, however, the lyrics don't reset. They remain scrolled all the way to the bottom.**

**Comment by MarshallOfSound** [comment]
Duplicate #1821
