### ISSUE TITLE
Feature request: Touch bar Song Title

### ISSUE THREAD

**Issue by Gabegmb** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2077]
**OS:** Mac OS 12.1

**Issue Descriptions:**
Can you add touch bar capability for the app. I would like to be able to see the song title in the touch bar.

**Comment by MarshallOfSound** [comment]
Blocked by upstream PR's

https://github.com/electron/electron/pull/8280
https://github.com/electron/electron/pull/8095
