### ISSUE TITLE
Auto plays music on Cast pause timeout

### ISSUE THREAD

**Issue by primeinc** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2078]
**OS:**
Windows 10 Enterprise 1607 (Build 14393.576)

**Issue Descriptions:**
When casting to my chromecast it works great, but if I pause the music for an extended period of time it seems like the chromecast will auto disconnect me. However, when auto disconnected GPMDP will start playing music on my PC again. This has lead to quite a few awkward moments when my PC starts blaring music while on the phone.

**Steps to Reproduce:**
Start casting to a chromecast dongle (or any cast device?) let it start playing and pause GPMDP. Eventually you'll get auto disconnected and GPMDP will start auto playing from your PC again, without any interaction.

**Comment by MarshallOfSound** [comment]
What GPM does when the cast is disconnected is 100% up to GPM.  We simply provide a Cast API, GPM's JS code actually interfaces with it.

**Comment by MarshallOfSound** [comment]
@primeinc There is different logic in the phone app and GPM web client
