### ISSUE TITLE
Show mini player in song menu

### ISSUE THREAD

**Issue by ctrlaltd1337x** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#208]
When you click on the menu button beside the song playing, and click "Show mini player" (http://i.imgur.com/wwbU6m4.png) you are greeted with the online add-on install page (http://i.imgur.com/YeqiRUl.png). When you get here, you cannot go back, and you have to close and re-open the app for it to disappear.

Not sure if this can be removed or re-directed to your own mini player, just something I saw that I thought I would mention.

**Comment by MarshallOfSound** [comment]
Fixed in master
