### ISSUE TITLE
Feature Request: Thumbs up/down all tracks on album

### ISSUE THREAD

**Issue by kevorkien** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2080]
Pretty straight forward - currently we can assign thumbs up / down to individual tracks. Would be nice to just be able to give a thumb up / down to the whole album.

Thanks

**Comment by MarshallOfSound** [comment]
Google Play Music has no concept of this, nor can we add this concept.  If you wish a core feature to be added to Google Play Music you should request it through the Google Product Forums
