### ISSUE TITLE
Side buttons of mouse not working

### ISSUE THREAD

**Issue by bendardenne** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2081]
Hi,

I have seen several closed issues about this and it was supposed to be fixed at the time (Aug 2016  - #1429  #1425  #1423  #1442 ), however I can still replicate under 4.0.5 (Linux).

Issue is still the same: side buttons do nothing.

Thanks

**Comment by jostrander** [comment]
So for linux this was kind of a hack because nothing existed to grab these in chromium itself or electron. It specifically targets mouse buttons 8 and 9, so if you can test your buttons to see if that's what they are reporting that would help.

**Comment by bendardenne** [comment]
They do map to buttons 8 and 9 indeed.


```
ButtonPress event, serial 32, synthetic NO, window 0x5200001,
    root 0x2f5, subw 0x0, time 24853249, (372,454), root:(1336,494),
    state 0x10, button 8, same_screen YES

ButtonPress event, serial 32, synthetic NO, window 0x5200001,
    root 0x2f5, subw 0x0, time 24854289, (372,454), root:(1336,494),
    state 0x10, button 9, same_screen YES
```

**Comment by jostrander** [comment]
Not sure how savvy you are, but care to try and test the native library
itself? https://github.com/jostrander/mouse-forward-back

**Comment by bendardenne** [comment]
Sure. I'm currently at work, I'll have a look this evening.

**Comment by bendardenne** [comment]
Trying to get a small test app running but I can't seem to get mouse-forward-back to play nice with electron:

`App threw an error during load
Error: Module version mismatch. Expected 50, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at bindings (/home/bdardenn/test-mouse/node_modules/bindings/bindings.js:76:44)
`

**Comment by MarshallOfSound** [comment]
@bendardenne You need to install and run `electron-rebuild` on your test app folder.

**Comment by bendardenne** [comment]
I tried that, I get a syntax error:

> % ./node_modules/.bin/electron-rebuild 
> /home/bdardenn/test-mouse/node_modules/spawn-rx/lib/index.js:139
>     let cmdArgs = ['/C', exe, ...args];
>                               ^^^
> 
> SyntaxError: Unexpected token ...

**Comment by MarshallOfSound** [comment]
You need node.js v6+ for electron-rebuild

**Comment by bendardenne** [comment]
Upgraded to v6.9.4, "Rebuild complete" but sill module version mismatch.

I tried reinstalling both electron and mouse-forward-back and now I get "Error: Module version mismatch. Expected 50, got 48"

**Comment by MarshallOfSound** [comment]
Ensure that mouse-forward-back is declared as a prod dependency in your package.json and then run electron-rebuild again.

**Comment by bendardenne** [comment]
Alright, it's working thanks for the help.

I get :
Error 10 (BadAccess (attempt to access private resource denied)): request 28.0
Error 10 (BadAccess (attempt to access private resource denied)): request 28.0

Which is also present on the output of GPMDP.

**Comment by jostrander** [comment]
That doesn't sound good. Is that only when you click the buttons or upon startup?

**Comment by bendardenne** [comment]
Upon startup.

**Comment by jostrander** [comment]
@MarshallOfSound The XLib docs state:

>>> If some other client has issued a XGrabKey() with the same key combination on the same window, a BadAccess error results. When using AnyModifier or AnyKey, the request fails completely, and a BadAccess error results (no grabs are established) if there is a conflicting grab for any combination.

Did electron implement native button 8/9 binding?

**Comment by MarshallOfSound** [comment]
I do not believe so, I may have missed it or it might have slipped through in a Chromium update

**Comment by MarshallOfSound** [comment]
@jostrander Is there a resolution path for this issue or are we dead in the water?

**Comment by jostrander** [comment]
If this is broken in the test app as well, we can test with older versions of electron until we find one that works and see what changed, otherwise we'll need more system specific info to see if its an edge case.

**Comment by bendardenne** [comment]
I have been able to go back to 1.3.1 and the problem was already there.
What information would you like me to provide?

**Comment by MarshallOfSound** [comment]
This issue has been marked as awaiting response for over a month so I'll be closing it out as it appears to have stalled out.  If this issue gets more active I will reopen below 👍
