### ISSUE TITLE
Setup do not open

### ISSUE THREAD

**Issue by veinersilva** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2082]
Hello,

I'm with some issue to install the player on my Windows 10 'cause the lastest setup of player (v4.0.5) don't even open on my computer. When I double click on the exe file nothing happens, no warning, nothing open, and when the setup is opened with administrator feature, it just says that the program can't reproduce on PC. How can I fix it?

**Comment by MarshallOfSound** [comment]
Your anti-virus is probably blocking the install for some reason.  This is definitely an issue on your side though as we have smoke tests to ensure the installer works.

You should probably check the windows event logs to look for the issue
