### ISSUE TITLE
BUG: Adding an item to the library scrolls the page upwards.

### ISSUE THREAD

**Issue by gwgwhc** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2083]
**OS:** Windows 10
V4.0.5

**Issue Descriptions:**
Adding an item to the library causes the page to scroll upwards slightly. This is annoying when adding multiple items from the same page.

**Steps to Reproduce:**
1. Add item to library on a page that is scrolled down adequately.

**Comment by jostrander** [comment]
Does this happen on the web interface as well?

**Comment by gwgwhc** [comment]
@jostrander Ah yes, it's on Google's part.
