### ISSUE TITLE
Installs to GPMDP_3 

### ISSUE THREAD

**Issue by zwh2** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2084]
**OS:** WIN 7

**Issue Descriptions:** installs to %APPDATA%/GPMDP_3 even though it is now on version 4. I would suggest just removing the number from install directory or increment to 4.

**Steps to Reproduce:** default install on windows

**Comment by MarshallOfSound** [comment]
Although semantically the number doesn't make much sense now we are on v4 we can't change it
