### ISSUE TITLE
Add option for removing tray icon

### ISSUE THREAD

**Issue by wa4557** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2085]
**OS:**
Ubuntu 16.04

**Issue Descriptions:**
It would be great if there was an option to hide the tray icon. On Ubuntu (and other linux desktop environemtns) you have SoundMenu integration so having both is a bit redunandant (tray and soundmenu). Could you add an option to remove the tray icon completely, which means that the app is no longer closing to the tray but rather closing to the soundmenu

**Steps to Reproduce:**
Open the app :)

**Comment by jostrander** [comment]
Unfortunately this just isn't in the cards at the moment. 

See #1563 #1574 #1269 #1266
