### ISSUE TITLE
Clicking the Shop link opens two browser tabs instead of one

### ISSUE THREAD

**Issue by Marwelln** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2086]
**OS:** Windows 10
**GPMDP Version:** 4.0.5
**Custom Theme:** Disabled (Unticked)

**Issue Descriptions:** 

When I click the Shop link it opens two browser tabs instead of one.

**Steps to Reproduce:** 

Click the Shop link.

**Comment by aaalvaro** [comment]
Same happens on macOS.
