### ISSUE TITLE
fresh install does not create start menu launcher

### ISSUE THREAD

**Issue by zakisaad** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2087]
**OS:**

Windows 10 Home (fully updated)

**Issue Descriptions:**

It looks like the latest installers aren't creating a start menu item for the player, on Windows 10 at least. I have had to navigate to C:\Users\\[redacted]\AppData\Local\GPMDP_3 in order to access the exe and listen to music.

Works fine on my Arch install, however.

**Steps to Reproduce:**

1. Have a fresh install of Windows 10
2. Download and install GPMDP
3. Search for the application in the start menu (it won't be there)

**Comment by MarshallOfSound** [comment]
This issue has come up before and it has been an issue with the folder structure on users devices.  I.e. Your desktop / start menu folders aren't in the traditional place.

> Search for the application in the start menu (it won't be there)

I uninstalled and reinstalled and the start menu item was there.  Without a more explicit step to reproduce (as in why it doesn't work on your specific machine) I have to mark this as `wontfix` with the rest.

**Comment by zakisaad** [comment]
Everything is stock, they are in traditional locations. Fresh installs of Windows.

One thing that I can think of is having whitespace in the file path. 

Does your username in the file path have a space, or is it something like "firstlast"? Mine is "First Last" in the path to the executable.

This issue has happened multiple times for me with the space in the name, however on my desktop I have no space ("firstl"); it works fine there.

**Comment by MarshallOfSound** [comment]
Hmmm, this is interesting.  I don't want to run around renaming my user on my machine, would you be open to a quick teamviewer session so I can test a few things?

**Comment by BrianAllred** [comment]
I also have this problem on Windows 10. My username is 5 characters, no space.

I'm open to a teamviewer session. I also have a development environment setup and the latest code checked out, if you wanted to try any code changes.

**Comment by MarshallOfSound** [comment]
> My username is 5 characters, no space.

Well that obliterates the theory :(

@BrianAllred I'm pretty busy for most of this week but depending on times I might be able to sort something out next weekend.  I can also try to reproduce in a variety of VM's so we'll see where that goes.

**Comment by bazhip** [comment]
My username is 3 characters and doesn't generate a start icon as well. It drove me nuts trying to find the install. For a bit I thought it was just a standalone executable. Speaking of, where the heck is it installed? I can't even find it to make a shortcut myself.

**Comment by Roundaround** [comment]
This issue actually doesn't seem to be specific to this app in particular. I've seen similar behavior out of other Electron apps (GitKraken in particular comes to mind). Perhaps it's a bug with the npm packages used for creating the installers or maybe with Squirrel?
