### ISSUE TITLE
NOT an issue, wondering if you can integrate a button that adds songs to a favorites playlist or something of that nature.

### ISSUE THREAD

**Issue by beardofbeespool** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2093]
I LOVE this app btw. I was wondering if there would be a way for us to set a "hotkey" for addings songs to a "favorites" playlist. I am listening to my songs, all of them, on shuffle. Would be cool to identify, besides the thumb up and down what ones I particularly liked. I have 7k to go through. :P

**Comment by jostrander** [comment]
I'm not sure if our playlists API has the ability to do something like this, but either way I think it would need to be PR'd by someone in order to make it in.

**Comment by beardofbeespool** [comment]
@jostrander what is "PR'd"?

**Comment by jostrander** [comment]
Pull Request, as in, someone would need to contribute the code to create this functionality.

**Comment by Juburin** [comment]
You can give songs a thumbs up and google will add the song to the Thumbs up playlist.

**Comment by MarshallOfSound** [comment]
This issue should be moved upstream to `gmusic-ui,js` to implement a method `playlist.addTrack`.  This wouldn't be implemented at our level.  That library would accept a PR to add the method.

I raised https://github.com/gmusic-utils/gmusic-ui.js/issues/7
