### ISSUE TITLE
Blurry Album Art in Mini Player

### ISSUE THREAD

**Issue by joe1134206** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2094]
**OS:**
Windows 10 Pro 64 bit Insider Preview Build 14986.1001
**Issue Descriptions:**
My album art is blurry in the mini player after a while, while initially perfectly normal. It seems to only happen occasionally. Toggling mini player on and off does not help. Pausing playback and manually restarting the song fixes it.
**Steps to Reproduce:**
It happens when a song transitions to another one, even when the artwork is the same.

**Comment by MarshallOfSound** [comment]
Zoom issue on high DPI screens that affects Chromium 53.  Will be fixed in the next electron bump

**Comment by joe1134206** [comment]
To confirm, my resolution is 2560x1440 at 100% scaling
