### ISSUE TITLE
Fresh Installment ???? !!!!

### ISSUE THREAD

**Issue by christianbearslyclark** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2096]
How to completely delete ALL the files of GPMDP? I want & need to do a real Fresh installment of GPMDP.

GPMDP always remember my login information. That is why I  want & need to do a real Fresh installment of GPMDP.

I think it's the registry keys but I can't anything for  GPMDP / your name.

Any suggestions ?

Thanks !!!!

**Comment by jostrander** [comment]
I'm assuming windows.

Delete `%localappdata%\GPMDP_3`
Delete `%appdata%\Google Play Music Desktop Player`

Reinstall.

**Comment by MarshallOfSound** [comment]
> GPMDP always remember my login information. 

FYI you can just logout? 😆
