### ISSUE TITLE
no way to remove hotkeys

### ISSUE THREAD

**Issue by wiiareonfire** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2098]
MacOS, running GPMDP 4.0.5 

Right now (unless I'm dumb and overlooking something) there doesn't seem to be a way to remove a keybinding from the hotkeys. I accidentally set one, and I can make due with setting it to some weird key combo I'd never accidentally hit, so it's not an extreme issue but I think it's something that users should be able to easily control.

**Comment by MarshallOfSound** [comment]
I believe the help text explains this as well. But hit the "escape" key to reset a hotkey
