### ISSUE TITLE
Unable to Stop casting

### ISSUE THREAD

**Issue by hahn-kev** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2099]
Hi, Great work on the Chromecast support, one minor issue I have is that when I start casting music there's no reliable way to stop casting, Ideally a Stop Casting button on the cast list that pops up would be great.

**Comment by jostrander** [comment]
There is a "stop" button on the cast list?

**Comment by hahn-kev** [comment]
Not that I can see.
![image](https://cloud.githubusercontent.com/assets/4575355/21946802/e733ef1a-d996-11e6-964c-2e79ebe29b0a.png)

**Comment by jostrander** [comment]
Can you switch to the dark theme and see if its visible? It should be in the lower section, which is extending way down further than it should.

**Comment by hahn-kev** [comment]
Ok, I'm not sure what happened, I remembered when I went into settings that I had the language set to Pirate, so I changed it to English, relaunched and the buttons showed up. So I set it back to Pirate and relaunched it again, but they're still here. So I'm not sure what's going on, I can confirm that it also works with the dark theme. Should I report again if I have this issue again?

**Comment by jostrander** [comment]
Just reopen this if you can reproduce it reliably, until then its sort of an anomaly.
