### ISSUE TITLE
Cannot resize from the top edge of the window

### ISSUE THREAD

**Issue by hndmrsh** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#21]
It is not possible to resize the window vertically from the top edge of the window (including diagonally from the top-left and top-right corners). This is surprisingly important when the window is larger than the screen size (this can happen frequently in certain multi-monitor setups), as you cannot drag the window up in order access the bottom  edge of the window.

**Comment by MarshallOfSound** [comment]
Untill a figure out the best way to do this, the work around I have sometimes used it to

1. Right click on the title bar of the window
2. Choose size
3. Press the arrow key on your keyboard corresponding to the direction you want to resize in (in this case up)
4. Move your mouse around until you like the size then click
