### ISSUE TITLE
Player doesn't scrobble when album is empty

### ISSUE THREAD

**Issue by patryk-kawalarz** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2101]
as in title.

**Comment by MarshallOfSound** [comment]
> Player doesn't scrobble when album is empty

This sounds expected?  The `album` is required by lastfm to perform song matching

**Comment by patryk-kawalarz** [comment]
But apps like:
https://chrome.google.com/webstore/detail/google-play-lastfm-scrobb/llpepekkleeoeiloijhcafgpjdnhhcbl
or
https://chrome.google.com/webstore/detail/lastfm-scrobbler/hhinaapppaileiechjoiifaancjggfjm

can do that.

**Comment by MarshallOfSound** [comment]
We send the raw data to lastfm (see https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/main/features/core/lastFM.js#L105) if last.fm fails to determine the song on their side and ignores the scrobble request that is out of our control
