### ISSUE TITLE
Casting resets volume level to the maximum

### ISSUE THREAD

**Issue by philh7456** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2104]
If you have set the volume level to something other than the maximum, and then cast, the volume level gets reset to the maximum. I would expect the volume level to stay at the set value.
Specifically this is with version 4.0.5 on Ubuntu 16:10 64bit, casting to a Chromecast Video.
I cannot test with 4.1.1 due to issue 2103, but have looked through the open and closed issues and have not found this listed.

**Comment by MarshallOfSound** [comment]
@philh7456 Any casting actions are configured by Google not by us, we simply provide a fake Electron side Chromecast API (see [`electron-chromecast`](https://github.com/GPMDP/electron-chromecast).

If Google change the volume (probably to some user specific persisted value) that's on them not us.
