### ISSUE TITLE
Enhancement: Windows Store

### ISSUE THREAD

**Issue by Silvenga** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2105]
Love this project, it has replaced every GMusic app that I've tried with the inclusion of Windows Media Service integration. I believe it would advantageous to both users and this project to consider inclusion into the Windows Store as a Win32 application via the Desktop Bridge. 

## Why?

Many applications, like Slack (an Electron app) and even Photoshop are making their way into Windows Store. I would think the reviews of almost iconic CrystalDiskMark on the Windows Store speak for themselves:

> This is a very nice addition to the Windows store. Not only do you get most, if not all of the functionality of the Win32 counterpart, you get the benefits of security (sandboxing), ease of installation/uninstallation (no registry mod), and auto updates! Big thanks to the folks for porting this wonderful app!

> I use this a lot both for work and play. .... It's great to know that it can be downloaded here now, making it much more accessible to users, and you know it's a safe source. Thanks converting this!

> Installed and it worked, just like the Win32 version. I will be using this on all my Windows systems. Thank you for supporting UWP! Keep up the great work!

> Used for years, convenient to have it autoupdate and install from the windows store.

> Nothing wrong with this tool to begin with, now it's packaged as UWP and has never been this simple or fast to grab, use, and remove. And now I don't have to worry about grabbing the newest version ever again either.

For the user:

- Simplification of installation
- Streamlined upgrades
- Simplification of, and completely clean, uninstalls
- Deeper integration into Windows
- Exposure to this project from the Windows Store
- Confidence of application integrity / security

For the project:

- Simplification of deployments (although Squirrel helps greatly with this)
- Wider adoption - which may lead to more community contributions and support

## Implementation

> TODO

#### Notes:

- With the help of `electron-windows-store` I've successfully constructed an `appx` package for GPMDP - and it appears to function correctly without modifcation
  - https://github.com/felixrieseberg/electron-windows-store
- Removal (or disabling) of Squirrel hooks
  - Windows will handle updates in the background, including verification of updates
- Windows Store account logistics
  - I can sponsor for a developer account

**Comment by MarshallOfSound** [comment]
I was actually aiming to beat Slack to the Windows Store (but @felixrieseberg beat me by a matter of days 😆 ) I have done all the heavy lifting to get GPMDP in a UWP compatible state including all the TODO's you have mentioned.

Some of the work can be seen here: https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/commit/24387e4f1c5a0c67cc004194c70ab8f60ad3c35c

I have also gone through the verification process to get permission to publish an appx package created through Project Centennial to the Windows Store.  The `4.1.1` release was supposed to make it's way onto the store (see the sneaky unchecked box on the release issue #2097) but I hit a small snag (literally internet died and failed to upload the file) so my plan is to upload on monday on better wifi.

**Comment by MarshallOfSound** [comment]
Also to be clear for anyone coming across this issue, Windows Store deployments will be **in addition** to the existing Squirrel update infrastructure.  Both paths will be updated at the same time with the same versions of GPMDP.  However it is worth noting that the two channels in the future might differ slightly due to the ability to use some UWP API's from the UWP side of the bridge.

**Comment by Silvenga** [comment]
@MarshallOfSound that is freaking awesome! 

Thanks for your time in this project.

**Comment by MarshallOfSound** [comment]
For people staring at this issue and thinking something like "he said monday..."

I've pushed this back till I get back to Uni (end of feb) and have an internet connection that is fast enough to deal with issues if they arise, uploading a fixed build could take literally hours on my current connection 😢

**Comment by Silvenga** [comment]
Thanks @MarshallOfSound - although, for the record, you never did say which Monday. 😸

**Comment by xblitz** [comment]
any news on this 😄 

awesome work by the way 👍

**Comment by Cyndre** [comment]
Its March :) update?

**Comment by MarshallOfSound** [comment]
Uploaded to the store and currently in "processing".  Should be green lit soon I hope 👍

**Comment by Cyndre** [comment]
Did you name it "GPMDP"? or what?  "Google Play Desktop Player"?

**Comment by MarshallOfSound** [comment]
@Cyndre GPMDP to reduce the usage of "Google", still under review I think 🌵

**Comment by Cyndre** [comment]
@MarshallOfSound still under review? No luck finding it.

**Comment by MarshallOfSound** [comment]
@Cyndre Was approved yesterday, will click the big blue button shortly 👍

**Comment by Silvenga** [comment]
For anyone looking for it

https://www.microsoft.com/en-us/store/p/gpmdp/9nblggh3zpph
