### ISSUE TITLE
UI freezes after playing song

### ISSUE THREAD

**Issue by caseif** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2109]
**OS:** Windows 10 Update 1607

### Issue Description
The UI freezes entirely exactly 5 seconds after starting a song, and it is impossible to interact with the window. However, it seems to return to normal after exactly 2 minutes. While frozen, media hotkeys (standard and custom) also fail to function (although the play/pause button in the Windows UI still works). A reinstall does not resolve the issue (with both the Local and Roaming data folders cleared).

This is similar to #1776, but in that case Google resolved whatever problem was on their end within a day or so - this has been persisting for a week or so and is likely not a regression for reasons I'll outline below.

### Hypothesis
I suspect my bluetooth radio is causing the issue. Disabling it in the device manager causes the UI freeze to become more of a "hiccup," lasting for about a second. Also, not sure of the relevancy of this, but it is possible that the program is having issues displaying the device-control toast. The reasoning is that [this line](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/944c3f8/src/renderer/windows/GPMWebView/interface/toast.js#L26), is the only reference I can find to a 5000ms timeout.

**Edit:** It may not be related to Bluetooth. I still suspect it but it appears my trials may have just been coincidences - it's no longer freezing with the first song regardless of Bluetooth status, but after waiting a bit and starting a new song it freezes again. [Relevant xkcd of course.](https://xkcd.com/1457/)

**Comment by jostrander** [comment]
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/1507#issuecomment-270574044

Something fishy with win 10 desktop notifications. Also are you on latest?

**Comment by caseif** [comment]
Yep, 4.1.1. This seems like it should stay open if the solution is to disable the feature causing the problem, though.

**Comment by jostrander** [comment]
There is a longer answer somewhere by @MarshallOfSound, although I can't seem to find where he left it, basically its something with upstream electron, chromium, windows 10 or all of the above, and it's either been fixed upstream and needs to be ported down, or is blocked upstream etc etc.

**Comment by caseif** [comment]
I'd propose this be left open as a tracker for that, then.

**Comment by MarshallOfSound** [comment]
There is no tracker for this issue as it is actually an issue in Windows 10 and Microsoft does not have a public facing bug tracker.  It has been reported to them along with the relevant stack traces.

There is nothing we can do about it at this level and therefore we do not maintain an open issue for tracking it.  My general philosophy is like so:

* Can we fix it in any way anywhere in our dependency tree and is it reasonable to expect us to fix it?
  * Yes --> Leave open
  * No --> Close as `wontfix`

This fits into the "no" category as there is literally nothing I can do to fix issues in Windows itself.

The only thing we can do in this situation is wait for an update to patch this in Windows.
