### ISSUE TITLE
No notification on linux desktop

### ISSUE THREAD

**Issue by tangb** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2111]
Hi

First of all thank you for this Google music player, I love it !

Maybe I missed something but I have no notification on my linux desktop.
I'm running debian stable on XFCE.

Thank you for your answer ;-)

**Comment by MarshallOfSound** [comment]
You need to enable them in GPM settings.

**Comment by tangb** [comment]
Thank you, I didn't see GPM settings :S
