### ISSUE TITLE
Small Window Width is Clipping Icons

### ISSUE THREAD

**Issue by nerdkid93** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2112]
**OS:**
Windows 10 Home (Version 1607, Build 14393.693)

**Issue Descriptions:**
Icons start to hide offscreen when the program window shrinks to below 962px in width. Specifically, the currently playing list hide first. This is particularly an issue on Win 10 when using the window snapping functionality to screen corners.

**Steps to Reproduce:**
Snap the GPMDP window to the left (or right) by pressing `Win` + `←` (or `Win` + `→`), then shrink to the top or bottom corner by pressing `Win` + `↑` or `Win` + `↓`. If your screen is smaller than 1920 px wide, the icons will start to get clipped off the right side of the window. I've included a screenshot of the icons getting clipped ![here](https://cloud.githubusercontent.com/assets/6289786/22027220/25ae898c-dca1-11e6-9807-54a86519231f.png)

This might be an issue on Google's side if they aren't properly observing small window size changes and dynamically scaling content to fit.

**Comment by MarshallOfSound** [comment]
This is due to GPM not being responsive and Google enforcing a minimum width
