### ISSUE TITLE
Default App for handling media control buttons?

### ISSUE THREAD

**Issue by SpectralKH** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2114]
[macOS] Any way to have GPMDP to be the default for handling the play/pause, skip and previous buttons? I know the app will work with the buttons if you have the app open, but if it's closed it seems to just open iTunes.

**Comment by jostrander** [comment]
I don't believe mac OS gives you the option to pick. However I don't have a mac to test with.

**Comment by SpectralKH** [comment]
@jostrander No, it does not. I should've worded myself differently; I wanted a way for it to do so, which I know is not there at the moment.

**Comment by jostrander** [comment]
Unfortunately it's not something we can implement, it has to be something Apple creates and implements, which is highly unlikely.
