### ISSUE TITLE
Function Keys as hotkeys?

### ISSUE THREAD

**Issue by Multipixelone** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2116]
**OS:** Windows 10 x64

**Issue Descriptions:** Can't use function keys (F4) as a hoykey

**Steps to Reproduce:** Click on hotkeys, can't select F4

**Comment by jostrander** [comment]
You have to use a modifier key, specifically ctrl. Unfortunately thats the only way the underlying shortcut receiver will accept hot keys because it surrenders the key sequence from any other application.

**Comment by Multipixelone** [comment]
I read about some settings file? Is that a thing?

**Comment by jostrander** [comment]
For some keyboard shortcuts you can manually set them in the settings file. I don't recall which ones you couldn't set in the settings page that you can set in the file itself.
