### ISSUE TITLE
Linux Download Buttons Don't Work [Website]

### ISSUE THREAD

**Issue by MichaelWhitehill** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2117]
**OS:**
Ubuntu -Mate (Also tried on Windows)
**Issue Descriptions:**
The Linux download buttons do nothing, in firefox or chrome (I also tried chrome on Windows). None of the linux flavors seem to do anything.
**Steps to Reproduce:**
Go to main website, click Linux, click any download version.

**Comment by MarshallOfSound** [comment]
This is currently intended due to the breaking linux bug.

See https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/2103

If you want to download for linux, download `v4.0.5`
