### ISSUE TITLE
Missing Debian builds for 4.1.1

### ISSUE THREAD

**Issue by andreisusanu** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2118]
**OS:** Debian

**Issue Descriptions:** Missing builds for i386 and amd64

**Steps to Reproduce:** One step forward, two steps backwards

**Comment by MarshallOfSound** [comment]
See #2117 and #2103 

> One step forward, two steps backwards

I don't know what you are trying to say with this 🌵

**Comment by andreisusanu** [comment]
It meas that the Linux builds are missing, and this is sad :(

**Comment by andreisusanu** [comment]
Closing this issue won't solve the missing builds, sorry.

**Comment by ClydeDroid** [comment]
@andreisusanu Give the man a break, he is giving you free software. He clearly stated his awareness of the issue and will fix the Linux builds in due time. Have patience.

**Comment by higgiefresh** [comment]
Any way to install the 4.0.5 ver for amd64 and 1386?

**Comment by ClydeDroid** [comment]
@higgiefresh https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/releases/tag/v4.0.5
