### ISSUE TITLE
Hotkeys not working

### ISSUE THREAD

**Issue by wmedina1991** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2119]
Trying to set hotkeys to pause and play. nothing works.

**OS:**Windows 10

**Issue Descriptions:**Unable to program hotkeys

**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment]
> Trying to set hotkeys to pause and play. nothing works.

You don't need to set the hotkeys to play/pause they are set up by default.

**Comment by abrambailey** [comment]
This doesn't work for me. On MacOS.

**Comment by wmedina1991** [comment]
Yeah I definetly cannot set these on my machine.
