### ISSUE TITLE
OSX issues

### ISSUE THREAD

**Issue by ValentinDenis** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#212]
Just listing here my remarks made on the reddit post:
 - better tray icon (and a white one for dark mode)
![image](https://cloud.githubusercontent.com/assets/6633654/13549710/14986382-e30c-11e5-90fc-1bc3a7d5d5c0.png)
 - Full screen
 - Voice commands not working for me

**Comment by snigel1** [comment]
Also, setting hotkeys does not seem to work

**Comment by wiiareonfire** [comment]
when "built in audio" is selected as the playback device, changing the system volume does not change playback volume

close, minimize, and full screen are on the right side of the window bar (typically on left side in mac applications)

**Comment by MarshallOfSound** [comment]
@ValentinDenis Voice commands are off by default, you have to enable them from the "General" section of the settings menu.

I'll take a look at that PR real quick

**Comment by MarshallOfSound** [comment]
Closing as the icon has been fixed, the voice controls is user error and full screen is incoming in another PR
