### ISSUE TITLE
Show Latest on Mac breaks background color

### ISSUE THREAD

**Issue by kwelch** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2120]
**OS:**
Mac
**Issue Descriptions:**
I am using v4.1.1 with the custom theme dark and highlight color or red. When I click the "Show Latest" button it clears the dark background on the page. I have no custom styles set. This can be fixed by refreshing the app with Command + R, but this will stop playback. 

**Steps to Reproduce:**
- Set Theme to Dark
- See "Show Latest"
- Click "Show Latest"
- Upon page refresh, you should notice the background image is now light and make test difficult to read.

I will attach a screenshot on the next occurrence. 

**Screenshot with Button** 
![Screenshot with Button](https://cloud.githubusercontent.com/assets/1295580/22072055/af78999e-dd66-11e6-9d47-9f40b3693fb3.png)

**Screenshot with broken background**
![Screenshot with broken background](https://cloud.githubusercontent.com/assets/1295580/22072071/b6ec41c6-dd66-11e6-9c16-bb903720a3d4.png)

**Comment by MarshallOfSound** [comment]
See https://github.com/gmusic-utils/gmusic-theme.js/issues/61
