### ISSUE TITLE
Dark Theme Incorrectly Changing All Black Text

### ISSUE THREAD

**Issue by atbigelow** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2121]
**OS:** Windows 10

**Issue Descriptions:** CSS changes for the dark theme are over-aggressively changing black text to white. This includes the titles on lighter boxes, making them either harder or impossible to read.

Incorrect black text
![gpmdp_dark](https://cloud.githubusercontent.com/assets/1435706/22081977/a997e548-dd7a-11e6-8e82-086bee0e3c74.jpg)
Correct black text
![gpmdp_light](https://cloud.githubusercontent.com/assets/1435706/22081981/aeae1c0a-dd7a-11e6-871f-e042df16588c.jpg)

**Steps to Reproduce:** Turn on dark theme and look at any album/suggestion box with a lighter background.

**Comment by MarshallOfSound** [comment]
I believe I ignored the current text color as GPM actually dynamically changes the text color during redraws.  (Can't remember the specifics)

Anyway, please raise upstream here https://github.com/gmusic-utils/gmusic-theme.js
