### ISSUE TITLE
Windows media provider service integration no longer working

### ISSUE THREAD

**Issue by Codepixl** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2122]
**OS:** Windows 10 (Anniversary update)

**Issue Descriptions:** The windows media provider integration (Where the media name and album art is shown when changing tracks or adjusting volume) no longer works in the latest version of GPMDP. (4.0.3)

**Steps to Reproduce:** Be on Windows 10 and adjust volume while music is playing. The music HUD is not shown.

**Comment by jostrander** [comment]
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/releases/tag/v4.1.1

It wasn't released until version 4.1.1, you are on 4.0.3.

**Comment by Codepixl** [comment]
...That's weird. I got an update the other day saying it added WMP integration, and then I got an update today and it's no longer there. Guess I somehow got updated to an unreleased version for some reason... Thanks!

**Comment by dolsem** [comment]
I'm having the same issue on Windows 10 version 1709. I'm using the latest version of GPMDP, 4.5.0.
