### ISSUE TITLE
Linux download link is broken

### ISSUE THREAD

**Issue by SiriusCrack** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2125]
**OS:** Ubuntu GNOME, Windows 10, Android

**Issue Descriptions:** The Linux download links on your site aren't working. I tried on multiple devices and networks, so there must be an issue with the site. Hope this gets fixed soon; I'm looking forward to trying this out! :)

**Steps to Reproduce:** Visit https://www.googleplaymusicdesktopplayer.com/#!, click "DOWNLOAD LATEST - V4.1.1", click "LINUX", click any of the four options.

**Comment by this-is-angus** [comment]
Latest version broke. Download this: https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/releases/tag/v4.0.5

**Comment by MarshallOfSound** [comment]
Do people not read the issue template?

#2118 #2117 #2103 #2124

> * I have checked that there are no issues with similar or the same content
  YOU SHOULD CHECK CLOSED ISSUES ASWELL

^^ I mean, it's right there.... Please guys, the issue template is there so that I don't have to waste time managing duplicate issues.
