### ISSUE TITLE
search area white

### ISSUE THREAD

**Issue by Llewe** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2129]
search bar still works but the design is broken...

![image](https://cloud.githubusercontent.com/assets/16879918/22121613/0caead64-de85-11e6-819c-5e3614a88a44.png)

![image](https://cloud.githubusercontent.com/assets/16879918/22121654/2d53138e-de85-11e6-8a15-9ecb0fbfd127.png)

![image](https://cloud.githubusercontent.com/assets/16879918/22121682/42123d40-de85-11e6-91d0-47a9f9aa7f78.png)

**Comment by Alipoodle** [comment]
This should go into the theming repo, I've made a post in there already and referenced this! 
https://github.com/gmusic-utils/gmusic-theme.js/

**Comment by MarshallOfSound** [comment]
This is expected behavior, if you think it should be changed as @Alipoodle mentioned, raise it on the theming library
