### ISSUE TITLE
Potentially interesting solution to high CPU on macOS, brining it down to 7% when not shown

### ISSUE THREAD

**Issue by hubez** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2130]
**OS:**
macOS Sierra 10.12.2

**Issue Descriptions:**
The high CPU due to the rendering of the Google Music page is well documented in these bugs, but I have a method in which every time I do it, it solves the high CPU and brings it down to 7%. What I have found is that if I follow the reproduction steps below, it's like it finally realizes it doesn't need to render the window and CPU drops to 7%.

My annoyance is that just closing the Full Window (with the red X, or CMD+W) still consumes the same amount of (high) CPU as if I have the window open. Which in total is ~37% (which eats battery). Even the mini-player (while better) is still pretty bad. Switch to the mini-player via Window -> Mini reduces CPU to 22%. Closing the mini window only reduces it to 11%.

What I hope is that someone understands what goes on behind the scenes on macOS, and can trigger this same situation when we simply click the red X (or CMD+W), regardless of if it is in Full or Mini mode so we can achieve 7% CPU usage when the window is closed.

**Steps to Reproduce:**

1. Show GPMDP and put it in Mini Mode, using Window -> Mini
2. Close the GPMDP with the red x.
3. The menu should still be in the context of GPMDP, so go to Window -> Full
4. Then Window -> Mini

CPU will now be super low at 7% (for my Mid 2014 Macbook Pro)

**Comment by ehmjaysee** [comment]
Worked for me

**Comment by MarshallOfSound** [comment]
> What I hope is that someone understands what goes on behind the scenes on macOS, and can trigger this same situation when we simply click the red X (or CMD+W), regardless of if it is in Full or Mini mode so we can achieve 7% CPU usage when the window is closed.

This sounds like a peculiarity in the Chromium rendering engine (that has probably been fixed elsewhere).  Electron will have a Chromium 54 build shortly that I can generates betas for (I'll post them here for you to try).

Unfortunately the exact order of operations you did isn't doable in code (without the UI flashing all over the place as we simulate actions).  Just need to put some faith in Chromium 54's "efficiency improvements" 👍

**Comment by cprpopqual** [comment]
Linux workaround: putting GPMDP in Mini mode (Window > Mini Player) then closing the mini window puts the player at 3-5% CPU.

**Comment by FoxxMD** [comment]
This worked great for me 👍 thanks

**Comment by pippo0312** [comment]
Just reporting that I see the same high CPU usage on ubuntu-gnome 16.04.
The CPU goes down closing the GPMDP window (and leaving it playing in the tray/background).
It seems related to a bug (feature??) in displaying the small equalizer animation in the google player  (also web player in chrome has the same "feature")
