### ISSUE TITLE
Requires high performance GPU

### ISSUE THREAD

**Issue by BonzTM** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2136]
**OS:**
macOS
**Issue Descriptions:**
Application requires "High Performance GPU" on MacBook Pro 15".  This results in severe battery loss when running on battery.  It's more battery efficient to run it in a Chrome tab if this is the case.  The workaround is to use a GPU switcher and force onboard only before launching the application.
**Steps to Reproduce:**
Run on macOS with Dedicated GPU model MacBook.

**Comment by MarshallOfSound** [comment]
This is due to a rendering issue discovered on macOS that can be negating by enabling hardware acceleration.  I'm hoping I can disable hardware acceleration when we hit Chromium 54 *soon*.

**Comment by MarshallOfSound** [comment]
There is a more complete response regarding this in another issue but I'm on my phone and can't find it right now :P

**Comment by Leefblowa** [comment]
Chromium 56 is out, does that allow you to enable hardware acceleration?

**Comment by jostrander** [comment]
https://github.com/electron/electron/releases

Electron is still only in beta and pre-release stage for chromium 54+. When Electron puts out a stable release and if everything this app requires is tested to be working we can then update the dependency.

**Comment by Leefblowa** [comment]
Once this update drops, all my problems are solved

**Comment by cwre** [comment]
Just wondering what others have done to mitigate this issue, as it's a pretty large issue.

**Comment by Leefblowa** [comment]
When i'm on battery, I use gfxCardStatus to force my system into iGPU only mode. Other than that, I don't.

**Comment by cwre** [comment]
That's a real shame. I'm probably just gonna wait for this to get fixed and then start using it.

**Comment by sykosoft** [comment]
@MarshallOfSound @jostrander As near as I can tell, Electron 1.6.2 is considered stable, and has Chromium 56. They merged the 56 branch into master a bit back, and it's not tagged as a pre-release.

**Comment by dsedivec** [comment]
FYI I just rebuilt HEAD with an [unconditional call to `disableHardwareAcceleration`](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/main/configureApp.js#L12-L14) and in my five minutes of use it seems fine.  Discrete GPU no longer kicks in when I mouse over the album art at bottom left!  Mac OS 10.11.6, late 2013 rMBP 15".

**Comment by michael-moody-bloomip** [comment]
@MarshallOfSound checking in on this again?

Thanks in advance.
