### ISSUE TITLE
Surface type cover play/pause media key not recognised

### ISSUE THREAD

**Issue by eksime** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#214]
On the Surface Type cover the play/pause media key is not recognized.
The key is not bindable in the hotkeys menu either.
The keyCode reported for the key is 179 if that helps.

Edit: possible duplicate of #206?

**Comment by xenokira** [comment]
Experiencing the same issue on my Surface Book. Play/Pause (Fn+F3) input is ignored.

**Comment by flakeparadigm** [comment]
This issue was reported a little earlier as well, perhaps it will solve your problem?
#199

**Comment by MarshallOfSound** [comment]
**FYI this is a prewritten copy paste response**

So your media buttons aren't working aye???  
Let's try fix that.

1. Are you using the Google Play Music chrome plugin?  If yes, remove it, and reboot your pc (sorry) and see if it works
2. Are you using a logitech keyboard?  If yes, turn off logitechs stupid software that manages your keyboard and try again?
3. Is there any other program that could possibly be "stealing" the keypresses?  (keyloggers, other media players Etc.)?  If so, close them and try again :+1: 

Good luck, if this doesn't work please respond

**Comment by eksime** [comment]
Removing the GPM chrome plugin worked for me, even though it wasn't enabled in chrome.

**Comment by MarshallOfSound** [comment]
Welcome to the world where Googles code breaks my code :+1:
