### ISSUE TITLE
Installation Error (Will not install)

### ISSUE THREAD

**Issue by coolluck321** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2141]
**OS:**
Windows 10 pro

**Issue Descriptions:**
I try to install the application and gives me an error.
 Error Pic: https://puu.sh/ttBQz/4eca964bd2.png 
Setup Log Doc: http://pastebin.com/60UL735n 

**Steps to Reproduce:**
Went into appdata\local and deleted GPMDP_3
Restarted installation to get the same error

**Comment by MarshallOfSound** [comment]
Looks like the standard error for when AntiVirus gets in the way and blocks access to certain files.  Try disable AV or running as admin and trying again

**Comment by coolluck321** [comment]
Wow... I don't know why i didn't think of that....
Fixed.
Thanks;;
