### ISSUE TITLE
Does not show all my chromecast devices when i have a large no of devices. 

### ISSUE THREAD

**Issue by frazered** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2142]
**OS:**

**Issue Descriptions:**

**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment]
No OS details
No issue description
No explicit steps to reproduce
No details as to what a "large no. of devices" is, 2, 5, 100???

Please fix your issue and I will re-open.
