### ISSUE TITLE
Fonts too small

### ISSUE THREAD

**Issue by hugorossi** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2144]
Hi!

On my screen (1920 x 1080, scaled to 125 %) the fonts in the Google Play Music Desktop player are too small. Can I make them any bigger?

Thank you!

Hugo

**Comment by MarshallOfSound** [comment]
You can use the standard zoom shortcuts to increase / decrease scaling.

Control + = zoom in
Control - = zoom out
