### ISSUE TITLE
Link for download of the version for Linux doesn't work

### ISSUE THREAD

**Issue by Z4yon** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2145]
I'm try install the player in a Linux debian version, but the link in site (googleplaymusicdesktopplayer.com) doesn't work.
I'll be very grateful, if this is fixed.

**Comment by MarshallOfSound** [comment]
Another one...

Do people not read the issue template?

#2118 #2117 #2103 #2124 #2125

> * I have checked that there are no issues with similar or the same content
  YOU SHOULD CHECK CLOSED ISSUES ASWELL

^^ I mean, it's right there.... Please guys, the issue template is there so that I don't have to waste time managing duplicate issues.
