### ISSUE TITLE
Scrolling in MacOS seems laggy

### ISSUE THREAD

**Issue by LoveKC94** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2149]
In fact even swiping away from the app in full screen seems kinda laggy. I'm running a mid2012 13" MacBook Pro. Maybe it's the Intel HD Graphics 4000? The official browser player runs fine (but I don't want to use chrome and I like the desktop player much better). Also in Windows it runs fine. Hopefully there's something I can do to fix this? Thanks

**Comment by MarshallOfSound** [comment]
Unfortunately "seems laggy" is not a performance measure I can use to determine if something is actually wrong 😆 

There are currently performance issues to do with Guest View resizing in Electron which we are looking at addressing (this could explain your swiping in and out of full screen issues).  However on my 2015 and 2016 macbooks I do not notice any performance issues when performing that transition.

The bump to Chromium 54 will include some performance / rendering improvements so the best I can suggest is to hope those will address some of the things you have noticed.

The only other thing this could be the the hardware acceleration being enabled on macOS (and it is not on other platforms).  This should be disabled again once Chromium bumps internally so look out for that change as well.
