### ISSUE TITLE
Windows notification tray icon resolution

### ISSUE THREAD

**Issue by pcjl** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#215]
The icon for the player in the Windows notification tray is extremely low-resolution on my laptop. The resolution of my laptop is 1920x1080.

For reference here is a photo comparing the icon to other programs that I have in my notification tray:

![](http://i.imgur.com/zezLJ3z.png)

OS Version: Windows 10
Program Version: 3.0.0

**Comment by MarshallOfSound** [comment]
That's actually really strange as the icon itself is 256x256. I'll have to look into why it looks so crappy....

**Comment by Koveryl** [comment]
Can confirm it's like this for me too

**Comment by MarshallOfSound** [comment]
@Koveryl All planned :+1: 

Just kidding, what kind of icon do you want?

**Comment by Koveryl** [comment]
I was thinking an orange circle with the Play Music Headphones inside of it, but white. Like this

![image](https://cloud.githubusercontent.com/assets/3173241/13551591/14628e32-e30d-11e5-932c-1bffeb9fc01d.png)

**Comment by MarshallOfSound** [comment]
If this app had less users, I would totally just use that image for a laugh.  But I can guaruntee I'd get hundreds of complaint emails so i won't :cry: 

I like the idea though

**Comment by Koveryl** [comment]
Maybe it could use that on April 1st, haha. If you want I'll design the icon real quick

**Comment by MarshallOfSound** [comment]
If you could spin something up that would be amazing.

**Comment by Koveryl** [comment]
Sweet, I'll try to upload it in less than an hour. I don't do tray icons ever, so what filetype and res should it be?

**Comment by Koveryl** [comment]
![google play music](https://cloud.githubusercontent.com/assets/3173241/13551935/996b7aca-e318-11e5-8c78-b43906978cc6.png)
Here it is! The logo isn't pixel perfect or anything, I might fix that later t(shouldn't matter much if it's only being used as a tray icon though)

**Comment by eXtreme** [comment]
Aren't headphones too small comparing to the circle? I mean, when you downsize it, you would barely see any details.

**Comment by FlyingGoats** [comment]
Reading quickly online, 32x32 seems to be recommended size for system tray icons. Perhaps the downscaling algorithm is bad for larger sizes.

Try this?

![gpmdp icon 32x32](https://cloud.githubusercontent.com/assets/17249361/13554497/0353596c-e3f5-11e5-9d23-06141c62a437.png)

I can supply as an .ico file or use http://convertico.com/. Failing that perhaps 16x16 or 64x64 sizes may be better?

**Comment by Koveryl** [comment]
![google play music 256](https://cloud.githubusercontent.com/assets/3173241/13555243/274eb094-e389-11e5-946a-45ef0c638700.png)
![google play music 32](https://cloud.githubusercontent.com/assets/3173241/13555244/274fcf1a-e389-11e5-92ba-a5b625ee27a5.png)
![google play music](https://cloud.githubusercontent.com/assets/3173241/13555245/2750a85e-e389-11e5-9b35-631c88a1a9c0.png)

Here's a couple different versions. Big one has a shadow, bottom two don't because they'll be small.

**Comment by Nxt3** [comment]
Same thing on OSX v10.11.3
Also, I think the icon should be white on OSX--it stands out as no other app has a colored menu icon.

<img width="317" alt="screen shot 2016-03-06 at 5 43 34 pm" src="https://cloud.githubusercontent.com/assets/2940826/13557652/fbd250e4-e3c2-11e5-9c12-492e4785fcc1.png">

**Comment by MarshallOfSound** [comment]
@Nxt3 The icon has been white/black since this PR yesterday #228 

:cactus: :+1:

**Comment by Nxt3** [comment]
ayy. :P Thank you!

**Comment by MarshallOfSound** [comment]
OK, after looking into this some more it appears as though no matter how high quality the icon I use somewhere the quality is being killed.

I'll raise this with electron
