### ISSUE TITLE
Linux download links not working

### ISSUE THREAD

**Issue by CorruptComputer** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2156]
**OS:** Fedora 25, 64bit

**Issue Descriptions:** The download links for linux on the (website)[https://www.googleplaymusicdesktopplayer.com] don't work. The windows and mac downloads are fine, however none of the linux files are available.

**Steps to Reproduce:** Try to download the linux files.

**Comment by ak11234** [comment]
v4.1.1 is broken on linux as explained here: [https://gitter.im/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-](url) You can download a working version here: [https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/releases/tag/v4.0.5](url)

**Comment by MarshallOfSound** [comment]
Another one...

Do people not read the issue template?

#2118 #2117 #2103 #2124 #2125 #2145

> * I have checked that there are no issues with similar or the same content
  YOU SHOULD CHECK CLOSED ISSUES ASWELL

^^ I mean, it's right there.... Please guys, the issue template is there so that I don't have to waste time managing duplicate issues.

**Comment by CorruptComputer** [comment]
@MarshallOfSound Ah, sorry man. I forgot to look at the closed issues and I figured #2103 was an entirely different issue.
