### ISSUE TITLE
Command line feature?

### ISSUE THREAD

**Issue by erickxs** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2157]
OS:Windows
Descriptions: there is a currently command line to manage this beautiful program on windows 10? thanks.

**Comment by MarshallOfSound** [comment]
There is a bash CLI somewhere but that only runs on *nix and macOS.  It shouldn't be that hard to make one and integrate with the WebSocketAPI.  But it's out of scope for this project.

**Comment by luislobo** [comment]
@MarshallOfSound Do you know where I can find this bash script? I want to customize my play buttons in i3

**Comment by luislobo** [comment]
nvm, it wasn't working with my current setup using `playerctl` but for some reason, now it `just works`
