### ISSUE TITLE
Only Certain Hotkeys Bindable

### ISSUE THREAD

**Issue by wowwood** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2158]
**OS:**

Windows 10 Pro

**Issue Descriptions:**

Can only bind certain keys as hotkeys. I can only bind certain keys as hotkeys, like ctrl-s, ctrl-shift-w, etc. I cannot bind other keys like Space, ` or Print Screen

I think this is more of a feature than a bug though.

Thanks.

**Comment by abrambailey** [comment]
Confirmed that I can only use ctrl+whatever on macos.

**Comment by MarshallOfSound** [comment]
This is intended behavior, this hotkeys are global and prevent the original action of the keys when used.  If we let you set "space" as your global hotkey you would never be able to hit "space" in another application.  We're protecting you guys by enforcing this criterea.

**Comment by abrambailey** [comment]
I just want to be able to use my mac play/pause button but it will not work.

**Comment by MarshallOfSound** [comment]
@abrambailey If they do not work then another application has seized control of them, possibly Chrome itself.

Check out the FAQ https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ#my-media-keys-dont-work

**Comment by nerotic** [comment]
CTRL-SHIFT + whatever is working beautifully for me.

**Comment by isocuda** [comment]
@MarshallOfSound Bit of an oddball here, but I play music when I'm in iRacing or other racing games.
The wheel I have along with the button boxes show up as their own game controllers. 

Since it's not related to the keyboard, could game controllers bypass the CTRL lockout?
![games](https://cloud.githubusercontent.com/assets/8029534/23991841/1cbd994c-0a11-11e7-9936-5e26885bd8c7.PNG)

**Comment by aiguofer** [comment]
This behavior is really annoying. I use Emacs, so I extensively use Ctrl for keybindings there. I would much prefer to use the Super (windows) key for 'global' keybindings. Although I can do that just fine for playback (using Gnome's media keys), I can't do the same for Thumbs Up, which is the main reason I use a desktop client (don't really want to interrupt what I'm doing to give a song a thumbs up).

I've been using Nuvola for a while; I love their keybindings, but it's nowhere near as stable or pretty as GPMDP. I want to make the switch, but until I can use more keys for keybindings I can't really do it.

Although unrelated, another awesome hotkey would be to 'bring up' the client if it's minimized/closed to tray/behind another window.

**Comment by aiguofer** [comment]
Just in case it's useful for anyone, I wrote some python scripts to 'like' songs and to bring the player forward so I could assign any keybindings :)

https://gist.github.com/aiguofer/bcc3fbc899d162ff3e69a13db18e1ebe
