### ISSUE TITLE
[Feature Request] Tray Icon should be optional

### ISSUE THREAD

**Issue by imarkskinner** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2160]
So I love this program but I wish you could minimize to tray without actually showing a tray icon. Plenty of desktops have centralized music/audio applets which make the need for a separate tray icon obsolete. Take Cinnamon as an example desktop (But I think KDE Unity and Gnome Shell all have something similar) it has this beautiful audio applet which controls all my music players and general sound settings, the extra applet just for GPMDP is redundant. Please allow us to turn it off and just have the one icon like I can do with Nuvola, Banshee, Rhythmbox etc.

**Comment by MarshallOfSound** [comment]
See #1574 #1269 #1266 #300 #1563 #636
