### ISSUE TITLE
Windows 10 Audio Devics not detected.

### ISSUE THREAD

**Issue by nerotic** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2161]
**OS:**
Win10Pro Build 14393

**Issue Descriptions:**
No sound device is detected

![program_manager_2017-01-25_02-02-49](https://cloud.githubusercontent.com/assets/487809/22273712/763cb02a-e2a2-11e6-8d22-95d4dd4204a5.jpg)

![settings_2017-01-25_02-06-48](https://cloud.githubusercontent.com/assets/487809/22273794/f2887a92-e2a2-11e6-8c3c-c241fe0ddb5e.jpg)

I've read some of the issues on Github, so I'll anticipate that don't use Chrome at all, Firefox is my workhorse.

**Steps to Reproduce:**
Just opening the application

**Comment by nerotic** [comment]
I should add that I did see https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/2069 but that my firewall is completely disabled while debugging this so that can't be the issues.

**Comment by MarshallOfSound** [comment]
The audio devices not being detected appears to be due to your GPM not actually loading, if you are using a VPN / proxy please disable it.

This is a non-issue as we require the GPM page to load before the audio devices can be read in.

**Comment by nerotic** [comment]
I don't use either VPN or Proxy

**Comment by nerotic** [comment]
I have no explanation as to why it started working but it just did after I restarted the app for the 5th or 6th time.  I didn't restart my machine or change any other configuration.

And thank you for this...it looks absolutely awesome!
