### ISSUE TITLE
Add ability to disable Windows 10 music controls

### ISSUE THREAD

**Issue by cascer1** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2165]
Hi!

While I understand why the app now supports the native music controls in Windows 10 (the ones that pup up next to the volume slider), I really dislike this popup. When I'm typing or something and pause my music using a media button on my keyboard, the stupid popup shows up and covers what I'm doing for a few seconds and I can't make it go away faster.

Being able to disable this would be awesome.

If is is already possible to disable this popup entirely, I'd love to hear it.

**Comment by jostrander** [comment]
#2100 Fixed, just waiting for release.
