### ISSUE TITLE
Application does not retain update after closing

### ISSUE THREAD

**Issue by evosyn** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2166]
**OS:** Win10

**Issue Descriptions:** Upon closing the application, the application does not retain its update (I.e going from 4.0.5 to 4.1.1. Once closing the app and re-opening, it has rolled back to version 4.0.5)

**Steps to Reproduce:** Run application from .exe. Update application. Close application. Run application from .exe again.

Also, I've noticed it doesn't actually install anywhere, even though you're calling it an installer. Tried running as admin, same results.

**Comment by MarshallOfSound** [comment]
@evosyn It doesn't appear to retain the update because you are rerunning the installer every time.  It installs to `%LOCALAPPDATA%`.

Shortcuts should be created on your desktop and start menu.

If they are not please follow progress in #2087
