### ISSUE TITLE
Cannot go forwards or back between pages on Windows and OSX Version

### ISSUE THREAD

**Issue by joslak** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#217]
If you click onto another section of GPM you cannot go backwards using either a back button or macro on a mouse. Not sure if a bug or missing feature but definitely affects usability of program. Confirmed to be issue on OSX and Windows version of program.

**Comment by DougieNeish** [comment]
Just wanted to second this feature request.

**Comment by flakeparadigm** [comment]
This seems to be a design choice made for v3. #198

**Comment by jheiselman** [comment]
Man, I wish GitHub would implement the star system that Google has for issues so I can voice my interest in this issue without having to comment.

Anyway, definitely going to follow this one as it's the only one huge issue for usability for me.

**Comment by mstrelan** [comment]
Menu > Settings > Add your music. This gets you stuck on "Add your existing music collection to Google Play". Clicking "Install" does nothing, and there are no links or buttons to go back. Can't press backspace, or alt+left or any other "back" shortcut. Have to kill the app or right click on the systray icon to close it.

**Comment by eXtreme** [comment]
Well for me it is also a step backwards (in overall a great piece of software). 

Saying that: 

>  if you can't use a website without forward/back navigation buttons the website is doing something wrong. 

is IMHO a little bit wrong, using websites with back/forward buttons is a natural thing to do and doing that in browser is always possible (well, when page changes url, history works). And with such UI design which GPM has, having a back button is a must. On android you have a hardware button for that. On iOS app designers have to include back button in UI. The screen on mobile devices is small, you cannot add more parent "context" to the view because there is no space. With large workspace like webpage or desktop app like this, with material design there is loads of wasted space.

The problem with GPM UI is that the whole view changes with no context of previous view. Consider searching a playlist, then clicking on an artist (to see more his/her songs). You can't easily get back to that playlist, you have to search it again (and good luck if it wasn't like one of the first, and all playlists have almost the same name). There are many more examples where back button is helpful. 
Spotify desktop app has back/forward button as well.

**Comment by MarshallOfSound** [comment]
OK guys, maybe on this one I started out with the wrong opinion.  Idk...  But clearly a lot of people rely on those navigation arrows so I'll look at implementing them.

*Falls to peer pressure of github issues*

**Comment by joslak** [comment]
@MarshallOfSound Issue isn't necessarily lack of buttons, but more that even when i use my mouse's side buttons for going forward and back between pages it does not work within the program, thank you for responding quickly and keep up the great work!

**Comment by joeynotjoe** [comment]
That's great news, man! I just discovered this on Reddit, and immediately was needing the back functionality. To be honest, I don't need it in the UI, but I would love the keyboard shortcuts.

It seems to be missing some default OS X keyboard functionality, as well. At least, cmd+a to select all.

**Comment by MarshallOfSound** [comment]
Yeah, I think I missed out on Select All :cry: 

Can you raise another issue for Select All missing? Plz? Thanks :smile:

**Comment by DougieNeish** [comment]
@joslak, I've just made a ticket for the mouse side button feature request. https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/224

**Comment by FlyingGoats** [comment]
Just commenting in support of the back/forward buttons being part of the UI again.

**Comment by SicariusNoctis** [comment]
+1

**Comment by MarshallOfSound** [comment]
Update: Progress has been made, but still not the best implementation.  They did strange things in small windows.  Should be good to go soon.

Not sure when it will actually be released, maybe next week some time :+1:

**Comment by jheiselman** [comment]
I'm aware of the design decision, but wanted to make my voice heard that it
breaks usability and should probably be reviewed.

On Saturday, March 5, 2016, Tyler <notifications@github.com> wrote:

> This seems to be a design choice made for v3. #198
> <https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/198>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/217#issuecomment-192742979>
> .
>


-- 
-- 
Jerry

google+: +Jerry Heiselman <https://plus.google.com/+JerryHeiselman/posts>
email: jerry@heiselman.com

**Comment by greghesp** [comment]
@MarshallOfSound - Perhaps just implement it like Radiant did.  Add a forward and back button next to the Menu icon

**Comment by MarshallOfSound** [comment]
@greghesp That's kinda what used to be there, but I'm trying to find a nicer way than injecting HTML into the page.  We'll see what I come up with :P

**Comment by jheiselman** [comment]
I haven't actually looked at the code for this (not sure that I'd understand it all if I did), but assuming you are using some sort of webview control, couldn't you add some chrome buttons to the UI and hook them into the webview's back/forward location methods?

**Comment by MightyPork** [comment]
I may have a solution. If you like it, I'll send a pull request.
We can also adjust stuff like size of the button, even color, anything.

I decided to add only the Back button, as it's the one that's needed most of the time.

![screenshot_2016-03-07_20-28-33](https://cloud.githubusercontent.com/assets/2041118/13580606/5c9ffdbe-e4a3-11e5-96ca-46c3fef90d16.png)

**Comment by MightyPork** [comment]
eh I did anyway. If it's not merged, I'll at least use it for my fork for personal enjoyment ;-)

**Comment by MarshallOfSound** [comment]
Back button added
