### ISSUE TITLE
Using Keyboard Media Forward/Back Skips Two Songs

### ISSUE THREAD

**Issue by OSDevon** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2172]
Hey, I'm not sure how to best display the issue I'm facing as it is best seen in "motion".

Basically, when I either Skip or Rewind using one of my keyboard's media hotkeys, instead of just going ahead one song, or restarting the current song, it makes it go two whole songs forward or back.
When that happens, it also rapidly skips tracks for as long as I hold the button down, as if it were a tape cassette stuck on fast forward.

Should I hold it down for more than a few tracks, the application completely locks up because of all the thinking it has to catch up to.

I have only started experiencing this after the newest update.

**Comment by MarshallOfSound** [comment]
I swear people don't even read the issue template let alone follow it 😢 

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/2107
