### ISSUE TITLE
Last.FM Scrobbling: Not Authorized

### ISSUE THREAD

**Issue by McButch** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2173]
Edit: Please Note that I am behind a Corporate Proxy. Is there a way to make scrobbling work with the proxy activated?

Hi,

I am using Version 4.1.1 of GPMDP and can't login into Last.FM on windows 10. In the desktop settings when I click on "login to LAST.FM" it only says "not authorized". 

I already tried reinstalling the program several times but I think I failed to completely delete the app because I am already logged into google when I install it again. 

Is there a workaround for this issue? I have attached a debug zip to my post. 

[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/735054/debug_info.zip)

best regards

**Comment by MarshallOfSound** [comment]
This normally occurs due to you running a proxy or VPN.

See https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/921
