### ISSUE TITLE
Seeing 40% cpu usage on my brand new 2015 15 inch mbp.

### ISSUE THREAD

**Issue by wilomgfx** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2175]
**OS:** macOs 10.12 

**Issue Descriptions:** 40% cpu usage

**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment]
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/2130  
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/2053  
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/1947  
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/1927  
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/1825  
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/1697  
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/1596  

The bump to Electron `1.5` and Chromium 54 / 56 will bring some performance improvements.  See those issues for potential workarounds / discussions.

**Comment by wilomgfx** [comment]
Thanks! I really love your app, so it felt weird that it got high cpu usage on my mbp, but not on my windows pc at home :P. Thanks to #2130 i got it down to 7-8%!
