### ISSUE TITLE
GPM disables itself mid-song

### ISSUE THREAD

**Issue by Jacobaw** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2177]
**OS:** Windows 10

**Issue Descriptions:** While listening to music. it will just randomly pause and wont play at all. And when attempting to click the play button, its grey.

**Steps to Reproduce:** Play a track.
https://gyazo.com/ef72ae6825eab91982c9ed244b2277cc

**Comment by jostrander** [comment]
This can happen for numerous reasons. Sometimes its due to audio device configuration changes, a bug with windows notifications, or an unknown bug. You didn't mention which version of GPMDP you are using. Are you on latest?

**Comment by jostrander** [comment]
Just want to add, this happened to me today, but was only momentary while the song was buffering.

**Comment by jostrander** [comment]
@Jacobaw Is this still an issue?

**Comment by MarshallOfSound** [comment]
Putting this down to network issues, if it is consistently reproducible on multiple networks (and different devices) please comment below with specifics 👍
