### ISSUE TITLE
Chromecast Groups

### ISSUE THREAD

**Issue by jamiehall123** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2178]
Hey

Not a massive issue but thought worth noting. When trying to play to a group of chromecast devices, for one reason or another GPMDP only plays to one device in the group rather than all devices at once.

Windows 10 Pro 14393 x64
GPMDP 4.1.1

Thanks
Jamie

**Comment by jostrander** [comment]
Unfortunately neither @MarshallOfSound or I have chromecast groups available to develop with, so were unable to debug and figure out how to fix this. Were hoping someone with a chrome cast group can step in and contribute some knowledge or code.

**Comment by jamiehall123** [comment]
Ah I see, would the debug info be of any help at all?
Btw great job with the app, love it!

**Comment by jostrander** [comment]
There is a way to turn logs on for the electron-chromecast module, but you would likely need to download and install gpmdp from source to enable it.

**Comment by MarshallOfSound** [comment]
This should be tracked on https://github.com/GPMDP/electron-chromecast/issues/8

**Comment by GitTom** [comment]
I"ve seen the same thing happen (repeatedly) when playing from the official GPM for Android, so this issue might not be specific to GPMDP.
