### ISSUE TITLE
Skips after 2 seconds on every song

### ISSUE THREAD

**Issue by ForexTaurus** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2179]
first off, GREAT APP.  I like it better than using chrome.

only one issue, whenever I play a new song, or first song of a playlist, radio station etc, there is a skip after the first 2 seconds for a half a second.

When I use the chrome version of google play music, there is no skip.

**Comment by MarshallOfSound** [comment]
This is either a network issue (unlikely as you say Chrome works) or a GPM issue (quite likely 😢 )

Give it a few days and the bugged file will probably rotate out of your local cache.

**Comment by MarshallOfSound** [comment]
Also might be vaguely relate to #2107 although it doesn't quite sounds the same
