### ISSUE TITLE
Album on mouse over menu is hidden when using a custom theme

### ISSUE THREAD

**Issue by DougieNeish** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#218]
When mousing over an album with a custom theme applied, the menu does not show. See image below.

![gpmdp_menu](https://cloud.githubusercontent.com/assets/7462084/13550509/3a259d8a-e317-11e5-8a09-a0519a8f2e2c.png)

**Comment by MarshallOfSound** [comment]
Can you please move this issue to the https://github.com/gmusic-utils/gmusic-theme.js library. 

Thanks!

**Comment by DougieNeish** [comment]
Done. https://github.com/gmusic-utils/gmusic-theme.js/issues/12 for reference.
