### ISSUE TITLE
Can't resize window from top

### ISSUE THREAD

**Issue by mroosen** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2180]
**OS:**
Windows 10 1607 64bit 

**Issue Descriptions:**
You can resize the main window from the left, right and bottom but not from the top.  This doesn't make sense to me and in order to resize I keep struggling resizing the window, mainly because the bottom often falls easily outside the visible screen.

**Steps to Reproduce:**
Dragging from the top window pixels drags the whole window instead of resizing the window vertically.

**Comment by MarshallOfSound** [comment]
This is a limitation of the frameless window API in Electron.  You can however resize diagonally from the top right and top left window corners.

**Comment by MarshallOfSound** [comment]
Jokes, we can hack around this :+1:
