### ISSUE TITLE
Multiple Processes in Task Manager

### ISSUE THREAD

**Issue by ForexTaurus** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2183]
I noticed there are multiple processes in task manager for Google Play Desktop Player.exe and wondering why that is and if it's normal or is there a way to reduce them?

![image](https://cloud.githubusercontent.com/assets/25408618/22436657/d42115b0-e6d9-11e6-91b7-623bcd295f45.png)

**Comment by MarshallOfSound** [comment]
This is 100% normal (this is how electron apps are architectured)

One process is the "main" process, one process is the renderer for the window, one process is the renderer for GPM, one process would be the renderer for the settings window.

There is not way to reduce the number of processes
