### ISSUE TITLE
Custom Hotkeys have disappeared and can no longer set them [v4.1.1]

### ISSUE THREAD

**Issue by jwmann** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2184]
**OS:** OS X 10.11.6

**Issue Descriptions:**
After recently upgrading to 4.1.1 I can no longer use my custom hotkeys.
Investigating further I've found that my hotkeys no longer exists at all. Empty.
I can't even set any new hotkeys.

**Steps to Reproduce:**
1. Open GPMDP
2. Open Preferences/Settings.
3. Select Hotkey Tab
4. Select a Hotkey to Set (input section will underline/ change colour)
5. Input and combination of keys, _nothing happens_.
6. Click outside / Press `Esc` to cancel hotkey input.

Reference to this closed issue with comments of people with the same issue.
#2119 

Debug info incase you need it. Though there's not much information in it.
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/740358/debug_info.zip)

**Comment by paulkarcher** [comment]
Same issue with Linux Mint 18.1 64-bit(Kernel: 4.8.0-34) using Cinnamon 3.2.7.

**Comment by gregflynn** [comment]
came across this today testing this app out, debian-testing on kernel 4.9

**Comment by jostrander** [comment]
In order to set hot keys you need to use a modifier key as the keys are stolen from the global scope. For example, if you were to just press "N" it would make it so GPMDP is the only program that would be able to see that key, period. The preferred modifier key is either `cmd` in mac, or `ctrl` in windows. 

If you can confirm that you can't set hotkeys this way then we can look into it further. 

@MarshallOfSound I notice mac and linux are present, but I checked windows and it's fine. Maybe your windows hack is working but something broke with the electron global shortcuts?

**Comment by jwmann** [comment]
@jostrander 
I'm using the same hotkey I was using previously which was `Cmd + Shift + J` and `Cmd + Shift + K`

This hotkey worked perfectly fine for a long time. Now all hotkeys have been cleared and are unsettable. 

I've also tried many alternative key combinations to no avail.

**Comment by gregflynn** [comment]
@jostrander 
Oh I was trying to set the shortcut to my global hotkeys, does this not work yet?

**Comment by jostrander** [comment]
Media hot keys are already set to work in GPMDP, (such as play, pause, forward, back, etc). @gregflynn

**Comment by gregflynn** [comment]
@jostrander Ah, my apologies, I had to remove the shortcuts from chrome, kill all chrome windows, then open GPMDP for it to get control of those key events. Thanks

**Comment by MarshallOfSound** [comment]
I'm making a few assumptions here but I don't think there is actually an issue here

@gregflynn All standard media player hotkeys can be stolen by Chrome / Chromium, I think you discovered this yourself 👍 

@jwmann 

>This hotkey worked perfectly fine for a long time.

That's impossible, we never supported "Command" hotkeys....

Everyone else.  As @jostrander said all hotkeys **must** contain the "Control" key.

Unless someone can demonstrate this not working or give some kind of reproduction scenario so I can see it not work I'll close this out shortly.

I have tested on Windows 8, 10 and macOS Sierra along with Ubuntu 14.04

**Comment by jwmann** [comment]
I can confirm that my hotkeys work.

I incorrectly assumed `ctrl` and `cmd` were synonymous (windows / mac) after reading @jostrander's comment.

After seeing @MarshallOfSound's comment, I double-checked my original hotkey by checking my Karabiner config. My original hotkey did infact start with `ctrl` not `cmd`. My apologies.
```xml
<?xml version="1.0"?>
<root>
  <item>
    <name>Remap System Volume keys</name>
    <appendix>These will be set to a custom mapping in the Google Play Music Desktop Player for Volume Up and Volume Down</appendix>
    <identifier>private.remap_system_volume</identifier>
    <autogen>
      __KeyToKey__
      ConsumerKeyCode::VOLUME_UP,
      KeyCode::K, ModifierFlag::CONTROL_L | ModifierFlag::OPTION_L | ModifierFlag::SHIFT_L
    </autogen>
    <autogen>
      __KeyToKey__
      ConsumerKeyCode::VOLUME_DOWN,
      KeyCode::J, ModifierFlag::CONTROL_L | ModifierFlag::OPTION_L | ModifierFlag::SHIFT_L
    </autogen>
  </item>
</root>
```

I think the real issue here was that my hotkeys were cleared after the upgrade, but as long as I can still set them, it doesn't bother me.

Thanks for the help.

**Comment by phord** [comment]
Two recommendations: 
1. Display some help on the hotkeys page that indicates the Ctrl-key requirement. 
2. Display the Media Key assignment instead of "Not Set" when there is no setting. 

I was expecting to have to set my media keys here and was frustrated that they didn't "work" on this page.  I tried them after reading this issue (#2184) and was pleasantly surprised to find they just worked.

**Comment by MarshallOfSound** [comment]
@phord Definitely makes sense to bit a little bit of help text on that page 👍
