### ISSUE TITLE
Player stopped working on Windows 10 (black screen)

### ISSUE THREAD

**Issue by artem-nefedov** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2185]
**OS:**

Windows 10 x64

**Issue Descriptions:**

Player suddenly stopped working altogether (was working fine before) and now only shows black screen.
Reinstalling and using other version (tried 4.1.1 and 4.0.5) does not seem to help.

On attempt to run exe from command line, an error log is printed.
The first line of the log is:

> Unexpected result while probing for avahi: { Error: dns service error: unknown error code

The last line is:

> error: ################### !! Update server down !! ##################

I am not using a proxy.
I thought it could be an issue on my end, but this app is the only one that does not work.

**Steps to Reproduce:**

Attempt to launch a player.

**Comment by MarshallOfSound** [comment]
> I thought it could be an issue on my end, but this app is the only one that does not work.

It is an issue on your end, I don't know how or why but that error messages indicates that the app can't obtain a network connection.  Check your antivirus, firewall, VPN (double check you aren't using a proxy).  The works.

The update server is up so if your network / computer can't hit it then you are having a network issue.  Sorry I can't be of more help 😢
