### ISSUE TITLE
Fails to run, libXss.so.1 missing on Fedora 25

### ISSUE THREAD

**Issue by emdog4** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2188]
**OS:** 
Fedora 25 Workstation Edition  Linux 4.8.6-300.fc25.x86_64

**Issue Descriptions:**

Fails to run. Need to install libXScrnSaver.

**Steps to Reproduce:**

Download Fedora 64 'google-play-music-desktop-player-4.0.5.x86_64.rpm'
sudo dnf install redhat-lsb
sudo rpm -ivh google-play-music-desktop-player-4.0.5.x86_64.rpm
google-play-music-desktop-player

> google-play-music-desktop-player: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory

**Workaround:**

sudo dnf whatprovides libXss.so.1

> libXScrnSaver-1.2.2-10.fc24.i686 : X.Org X11 libXss runtime library

sudo dnf install libXScrnSaver

**Comment by MarshallOfSound** [comment]
I believe this is due to `rpm` not installing dependencies and your OS not already having `libXScrnSaver` is pretty rare tbh 👍 

This is something we can't handle as it is the `rpm` tool not installing required deps.

This was explored in #883

**Comment by troycurtisjr** [comment]
Encountering this same issue on Fedora 26.  Surely the `npm run make:rpm:64` command has some form of configuration such that you can add `libXScrnSaver` to the list of required RPMs.  It certainly worked for many other packages!
