### ISSUE TITLE
GPMDP randomly skip 2 songs when I only press next once

### ISSUE THREAD

**Issue by BernaudFrancois** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2189]
**OS:**
Windows 10 pro 64 bits | i5 6600k | 16go ram | keyboard logitech G910

**Issue Descriptions:**
When I press the multimedia "next" key it skip/jump 2 songs instead of 1, like the command it interpreted 2 times.
Doesn't have any problems with other music players (groove music and media player classic)
**Steps to Reproduce:**
it's random but happends very often

**Comment by crockerfilm** [comment]
I have the same problem however it isn't random. It happens every time.

**Comment by morbidxbean** [comment]
Same Issue Here;  I would like to add that this is when using the media keys on keyboard.  Moving songs within the App with the mouse does not skip songs.

Windows 10 / i7 7700k / 32gb RAM / Logitech G710

**Comment by MarshallOfSound** [comment]
See https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/2107
