### ISSUE TITLE
Warning about minimizing to tray is displayed even if minimize to tray is disabled

### ISSUE THREAD

**Issue by DougieNeish** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#219]
The warning about the application minimizing to the tray is displayed when clicking the 'X' to close even if the minimize to tray option has been turned off in the desktop settings. This requires you to have _not_ clicked "don't show this again" in the warning dialog.

Just a very minor thing, but I used to be a test engineer so I notice things like this! Thought I'd mention anyway. :)

**Comment by MarshallOfSound** [comment]
Thanks, I'll definitely consider this a bug!

**Comment by MarshallOfSound** [comment]
Fixed
