### ISSUE TITLE
Feature request: moodbar

### ISSUE THREAD

**Issue by dbkaplun** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2190]
See https://en.wikipedia.org/wiki/Moodbar for more info and examples.

**Comment by jostrander** [comment]
Unfortunately I don't think is possible and falls sort of in the same scope of downloading music. We don't have access to the raw track data ahead of time so we can't process the whole track and display it. I'm closing this as `wontfix` but if someone engineers a way to make this work we'd gladly accept it.
