### ISSUE TITLE
Shuffle State for Websocket API broken when selecting a specific song from playlist

### ISSUE THREAD

**Issue by tjhrulz** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2193]
**OS:**
Windows 10
**Issue Descriptions:**
ALL_SHUFFLE payload and playback.toggleShuffle() not working as intended.
Shuffle state does not update if you select in individual song in a playlist or album or hit the play button in the top right on a playlist/albums landing page. If you select to play the whole playlist/album from the icon in on the bottom right before you select it or select a song from the song tab it works as intended.
**Steps to Reproduce:**
1. Open websocket
2. Open playlist
3. Select any song and play it
4. Websocket is now receiving bad shuffle data and any shuffle commands do not work as intended

On further inspection it sends the ALL_SHUFFLE payload with a value of NO_SHUFFLE when this happens and then never updates again. If you use the playback.toggleShuffle() command  it does not toggle shuffle on and off but instead does the same as if you pressed the shuffle button at the top of the playlist/album which shuffles all songs in the current playlist and picks a new song to play. 

My guess is that google changed an id around in the webpage and the automatic error detection figured it was still okay.
I should note that the shuffle button in GPMDP is still correct it is just not reported correctly in the Websocket API.

**Comment by MarshallOfSound** [comment]
I looked into this and I don't know why you still have this problem.  What version of GPMDP are you on?

**Comment by tjhrulz** [comment]
Latest, let me try reinstalling

**Comment by tjhrulz** [comment]
Yeah it is still doing it.

**Comment by MarshallOfSound** [comment]
@tjhrulz Theme color isn't documented for a reason (let's call it a private API).  The volume not being documented is just a bit of missing docs.  (PR's welcome) 😆
