### ISSUE TITLE
Windows Media Controls status doesn't update for podcasts

### ISSUE THREAD

**Issue by eladavron** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2195]
Using Windows 10 64bit, playing podcasts does not update the media controls status but instead just displays the last played non-podcasty song:

[Screenshot](http://imgur.com/GrNfFz9.png)

**Comment by jostrander** [comment]
@MarshallOfSound Did podcasts ever get merged in the gmusic API?

**Comment by MarshallOfSound** [comment]
@jostrander I don't think they did.  You had a PR for it somewhere though right?
