### ISSUE TITLE
The Desktop Player occasionally stops responding

### ISSUE THREAD

**Issue by rapdactyl** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2198]
**OS:**
Windows 10
**Issue Descriptions:**
The program will stop responding when playing a song..sometimes. It will continue playing music. Often, it'll start responding once more at a random point during the song, only to stop responding once more when the next song starts.

I started having this issue after rebuilding my PC with a new processor (i7-6850K, GTX 1070, 32GB of DDR4) - it was working great before.

**Steps to Reproduce:**
Start playing music on the system listed above.

**Comment by Calignis** [comment]
I have the same issue, using a laptop with Windows 10. i5-6300HQ, GTX 950M, 8GB of DDR4. I started having this problem after I got it back from being fixed by the manufacturer, getting the motherboard replaced.

**Comment by jostrander** [comment]
Do you have native window borders enabled or disabled?

**Comment by Calignis** [comment]
I have it disabled.

**Comment by jostrander** [comment]
Try enabling it and seeing if that helps. I've had freezing issues on windows with it disabled.

**Comment by Calignis** [comment]
It still freezes for me, if I minimize it and pull it back up it turns completely white.
![frozen gpm](https://cloud.githubusercontent.com/assets/25519186/22577856/1f3ae8f2-e98a-11e6-8ad3-2b1cd234f1d7.png)

**Comment by rapdactyl** [comment]
Didn't work for me either. The window doesn't turn white for me, but it does freeze up.

**Comment by MarshallOfSound** [comment]
@rapdactyl Please disable desktop notifications and try again 👍

**Comment by rapdactyl** [comment]
@MarshallOfSound  Whoa, that worked! Thanks :]
