### ISSUE TITLE
Maximized window is 1px too small

### ISSUE THREAD

**Issue by mstrelan** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#220]
On Windows 7 with all visual effects disabled the application is 1px too short after maximizing.
![One pixel too short](http://i.imgur.com/y1DDqBh.png)

![Visual effects](http://i.imgur.com/SJUGplo.png)

**Comment by MarshallOfSound** [comment]
Lol, wow.

Not sure what to say about that.  Would you mind terribly raising this as an issue against https://github.com/atom/electron/ as it is probably an issue with the framework rather than my implementation.

Cheers
