### ISSUE TITLE
"Close" Needs to Quit

### ISSUE THREAD

**Issue by firephreek** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2200]
**OS:**
Ubuntu 14.04.5

**Issue Descriptions:**
Unable to exit the application

**Steps to Reproduce:**
- Right click on the taskbar and select 'Close'
or 
- With the application open, use Alt-F4
or
- Click on the red 'x' in the upper right corner of the application.

All of the methods above only minimize the application.  There is no way to actually quit the application.  This is a problem when the application fails to log the user in properly and you're trying to restart the application.

**Comment by jostrander** [comment]
There is a default option to minimize to task bar, which you can right click on and quit the application.

**Comment by firephreek** [comment]
No, there isn't.  And if there was, I would still argue that the behaviour of the other interactions is 'broken'.  As you can see in the attached screen shots, the only place where 'minimize' appears, when right-clicked upon, just causes the application to be minimized.

Alt-F4 quits applications everywhere else. Generally speaking, so do 'Close' and so does that red x.  Minimize is the purview of options that are declared 'minimize' and that little underscore symbol that sits next to the x. 

![screenshot from 2017-02-03 12 22 24](https://cloud.githubusercontent.com/assets/1778998/22601163/b46c9b60-ea0b-11e6-82df-151b7dc740ae.png)
![screenshot from 2017-02-03 12 23 21](https://cloud.githubusercontent.com/assets/1778998/22601164/b476f5d8-ea0b-11e6-8136-f6b52a04b3dd.png)

**Comment by jostrander** [comment]
So task bar and tray are two terms I mixed up in my last comment. In Ubuntu I don't think the task bar hides the window when you "minimize to tray". You can close the application via the tray menu, which has other options such as play, pause etc.

**Comment by firephreek** [comment]
Ok, I found that. But that leaves the user with 1 non-obvious method for quitting the application. From a UX perspective, shouldn't the functionality presented by the application cause the application to perform in a manner consistent with other applications?  i.e. Close Closes and Minimize Minimizes?

**Comment by firephreek** [comment]
That just bring to light another bug:  'Show' from that menu doesn't actually show the application if it's minimized.  It just leaves it hidden. Would you like me to create a new bug for that?

**Comment by jostrander** [comment]
I think there should be a point of separation for the functionality. Before the user is signed in closing the app should definitely close the app, because there is no way music is playing. However when music is playing then the option to close to tray would take effect. As far as the show I think that might be an issue with electron and the window manager. I don't have my Ubuntu machine with me to verify.

**Comment by firephreek** [comment]
I get that. I just really feel that applications should conform to expected behaviour though. If I want to minimize I'll minimize, but when I click on the red X in the upper right hand corner or I press Alt-F4, I expect an application to quit just like every other application.  When I do it out of habit and an app doesn't and instead makes me jump through hoops (use the mouse, click here, then here, then here), it makes for a more frustrating experience.

**Comment by jostrander** [comment]
Then just disable the setting to minimize to tray and it will work exactly how you are describing, unless I'm missing something.

**Comment by firephreek** [comment]
Had to hunt around for that. That fixes the issue. I kept going to
'settings' from the main app which only present settings for Music, not for
the app.
