### ISSUE TITLE
Chromecast screensaver timeout

### ISSUE THREAD

**Issue by ohlenec** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2201]
**OS:**
Windows 10 (1607 build 14393.693)
Music Player 4.1.1
Chromecast Firmware 1.22.78337

**Issue Descriptions:**
As expected, when casting each song to Chromecast the album art is zoomed to fill the width. The track information is displayed on a transparent bar at the bottom of the screen. While better than a blank screen, it cuts off half the album art on a widescreen TV.

This used to time out after a short while (I never timed it, so i'm guessing 10-20 seconds.) then switch to a screen saver mode where the Album art was zoomed out with the song information underneath.

It now times out after the song timer reaches 5:00 minutes.

I don't know if google changed something on their end or a recent update changed this timeout. No matter the reason, is it possible to expose this variable to users so that we can have it as short or as long as we want? Or maybe the ability to chose the fill type for the art?

**Steps to Reproduce:**

Cast a song longer than 5:00 minutes and start playing at 4:58 to see the timeout.

**Comment by jostrander** [comment]
It must have been a recent update with Google as we don't control that at all, and I don't think we have the ability to. That's all done in the chromecast receiver app which is downloaded straight from Google.

**Comment by ohlenec** [comment]
Shucks! That's too bad. 

Thanks for the fast reply!
