### ISSUE TITLE
GPMDP freezes after ~10 seconds of playing music

### ISSUE THREAD

**Issue by TheCakepan** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2205]
**OS:**
Windows 10 build 14393.693

**Issue Descriptions:**
The desktop player keeps freezing when I play music and go to another program (e.g., Chrome) for about 10 seconds.

**Steps to Reproduce:**
1. Go to any album from any artist
2. Press the play button on the left side of the song
3. Unfocus on GPMDP for about 10-15 seconds
4. Go back to GPMDP and notice that it's frozen and will not respond

**Comment by TheCakepan** [comment]
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/752577/debug_info.zip)

**Comment by MarshallOfSound** [comment]
Disable desktop notifications.  This is a windows bug

**Comment by TheCakepan** [comment]
Thanks
