### ISSUE TITLE
Feature Request - Add GPMDP or Google Play Music to Window Title

### ISSUE THREAD

**Issue by ForexTaurus** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2206]
I'm using voicemacro.net to control my computer with macros and when trying to find GPMDP in the list of current windows the snag is that the Window title is equal to the song and artist and it changes all the time obviously, so it would be great if you added GPMDP or Google Play Music to the beginning or end of the window title so one can search for it.

**Comment by MarshallOfSound** [comment]
This goes against the feature requests / issues for changing the title to be the currently playing song.  We can't have both.

**Comment by ForexTaurus** [comment]
Why can't you have both?  Could be a setting, include GPMDP in Windows Title and if checked then Window Title = {Song} + " - " + {Artist} + " - " + {GPMDP}

**Comment by MarshallOfSound** [comment]
I want to avoid the solution to all differences of opinion between users to be "make it an option".  It makes GPMDP more complicated for limited gain

**Comment by ForexTaurus** [comment]
that's a shame.   http://play.google.com/music does use that format... S{ong} + {Artist} + "Google Play Music".....  nothing complicated about that at all well about your app anyway....

**Comment by jostrander** [comment]
I'm not opposed to adding GPMDP to the end of the title. I don't think the original issue was specifically to remove the application name from the title, but to add the song info to the title for programming purposes similar to this.

**Comment by MarshallOfSound** [comment]
@jostrander It was requested originally so that third party apps could identify the song name / artist of the current track.  If we add "- GPMDP" to the end of it that would break anyone that is doing that.  I feel that this doesn't belong in core, I started up #1623 again so this might fit into that one?

**Comment by MarshallOfSound** [comment]
Moving to super ticket #2216
