### ISSUE TITLE
Feature Request - Setting to disable Windows 10 Volume OSD

### ISSUE THREAD

**Issue by ForexTaurus** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2207]
I know it's a Windows issue and there is a HideVolumeOSD app out there so the volume control and track info doesn't display on the top left of the screen, but it would be nice if you had this feature in your program.

**Comment by MarshallOfSound** [comment]
This issue is caused by windows itself but I have already implemented this option in master.  Will be out next release
