### ISSUE TITLE
Feature Request: Shuffle by album

### ISSUE THREAD

**Issue by adeben** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2214]
**OS:**
Windows 10 pro
**Issue Descriptions:**
I would love to see a "shuffle by album" feature in the player. This would play albums in their entireties (and in order), but after completing one album, the player would randomly select the next album to be played from the music library. For reference, iTunes has this feature.
Also, if implemented, it might be handy to have a keyboard shortcut to skip to the next album instead of to the next song.
Thanks,
**Steps to Reproduce:**

**Comment by jostrander** [comment]
I don't think this is possible currently. I'm going to close as won't fix, if its possible in the future we can look into it then.

**Comment by mstrelan** [comment]
#2216
