### ISSUE TITLE
Share YouTube Video

### ISSUE THREAD

**Issue by brandinimp** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2215]
Hi,

So the "share" feature in GPM is pretty redundant if your friends don't have GPM accounts, and you wanna share new music to people.

For a time there was a "YouTube video" feature in GPM, that tried to match the current song to a YT video and then play the video instead via GPM.

Perhaps a feature could be added to GPMDP that can resolve a song to a YouTube video (YT API query, and roughly match GPM track length and YT track lengths for best match?), and offer to share it to a social platform? ( maybe even with a hotkey ;) )

Thanks,
B

**Comment by jostrander** [comment]
This will probably be something that depends on the new plugin system pending in #2216.

**Comment by MarshallOfSound** [comment]
Moving to super ticket #2216
