### ISSUE TITLE
Media keys double-skip

### ISSUE THREAD

**Issue by pitaj** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2217]
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/762337/debug_info.zip)

**Version:** 4.1.1

**OS:** Windows 10

**Issue Descriptions:** Pressing the "skip forward" media key on my keyboard results in GPMDP skipping to the next song, and then immediately skipping to the one after that.

**Steps to Reproduce:** 

1. Press media key "skip forward" or "skip backward"
2. Watch as GPMDP skips to next song, then skips again so it's two songs ahead (or behind, respectively)

**Comment by MarshallOfSound** [comment]
Duplicate, please check closed issues

**Comment by pitaj** [comment]
My bad. I searched but it didn't show up. Will await 4.1.2, thanks!

**Comment by pitaj** [comment]
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/2107
