### ISSUE TITLE
Main window size problem. 

### ISSUE THREAD

**Issue by warinthestars** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2218]
**OS:**
Win 10x64

**Issue Descriptions:**
When player is sized less than 900px wide (used on vertical monitor,) I lose the icon for opening the playlist as the control buttons don't resize.

**Comment by MarshallOfSound** [comment]
This minimum width is enforced by Google Play Music for UI reasons, overriding it will make their UI stop working correctly 👍
