### ISSUE TITLE
Prev and Next buttons activate twice

### ISSUE THREAD

**Issue by Herbstein** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2221]
**OS:**
Windows 10 Insider Preview Version 1607

**Issue Descriptions:**
The media keys on my keyboard are activated twice when I press them. This only happens in GPMDP and Spotify doesn't have the problem. Only the Next and Prev keys are affected. The play button works normally.

**Steps to Reproduce:**
No clue

**Comment by MarshallOfSound** [comment]
Duplicate, please check closed issues 👍

**Comment by Herbstein** [comment]
Doh. I always forget that.
