### ISSUE TITLE
Hovering over song info.

### ISSUE THREAD

**Issue by SheinH** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2223]
**OS:**
MacOS Sierra
**Issue Descriptions:**
What the app does when I hover over song info on the bottom left is quite unintuitive. I am unable to click on the album's name to go to the album despite it being visible because the like/dislike/menu icons show up on top of the song info when I hover over that area. Perhaps the like/dislike can be moved into the three button menu when the window is resized to be small/narrow.

Before hovering over song info:
![screen shot 2017-02-09 at 4 25 33 pm](https://cloud.githubusercontent.com/assets/5853497/22804090/8502cfc8-eee5-11e6-819c-4a723dbec01a.png)

After hovering:
![screen shot 2017-02-09 at 4 25 35 pm](https://cloud.githubusercontent.com/assets/5853497/22804102/912725ce-eee5-11e6-81b5-afed04397f1b.png)

**Steps to Reproduce:**
Simply hover over song info when the window is in low resolution.

**Comment by MarshallOfSound** [comment]
@SheinH This is a feature / issue of GPM itself, not something we have control over.  Please raise it on the Google Product Forums
