### ISSUE TITLE
Feature Request: Add setting to keep the hamburger menu always open

### ISSUE THREAD

**Issue by Keavon** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2224]
Play Midnight has this feature and it's really convenient. I have a giant screen and plenty of room to keep the hamburger menu/left menu open at all times. Adding a setting for this improvement would be quite helpful!

**Comment by arkon** [comment]
Seems like if the `force-narrow` and `narrow` attributes are removed from the `<paper-drawer-panel>` element, it'll stay opened. It does result in there being two Google Play Music logos though when not using a theme.

**Comment by jostrander** [comment]
Thanks for the info @arkon, if someone wants to PR this in that'd be great!
