### ISSUE TITLE
Feature Request: Add Visualizer

### ISSUE THREAD

**Issue by EBH602** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2225]
I used to use the browser version and got it to look amazing but obviously GPMDP  is 1000x better and I would like to request this chrome extension I used to use to be added to GPMDP

Music Visualizer for Google Play™ Music
https://chrome.google.com/webstore/detail/music-visualizer-for-goog/ofhohcappnjhojpboeamfijglinngdnb?hl=en-US

This is how my chrome google music looks like with the extension I am requesting to be added
http://i.imgur.com/PwW4MlH.jpg
![pww4mlh](https://cloud.githubusercontent.com/assets/25693646/22840930/b141b408-ef8c-11e6-91c5-62804d1c1edd.jpg)

I am only interested in the equalizer visualizer that overlays thescreen it looks amazing on a ultrawide overhead monitor and well hope we can get this feature added.

**Comment by jostrander** [comment]
This has come up before and unfortunately were stuck on this one for the time being. I built the code to make this work but unfortunately the default visualizer and/or the output selector are blocking the integration.

**Comment by MarshallOfSound** [comment]
Duplicate #2005
