### ISSUE TITLE
Media Key Issue

### ISSUE THREAD

**Issue by amh58** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2226]
**OS:** Windows 10

**Issue Descriptions:** Using the Media keys on my Logitech G510s (I.E skip) it duplicates the action. So it will skip two songs when I press this button.

This happened when Windows Media Service Integration was implemented.

**Comment by EBH602** [comment]
Do a seach next time this is a duplicate topic and has already been addressed and corrected and will be rolling out in the next version updated.

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/2107

**Comment by jostrander** [comment]
Duplicate #2107

**Comment by amh58** [comment]
Ohh sorry I didn't see anything when I looked around. Thanks for the link 👍
