### ISSUE TITLE
Stretch sidebar to fit Italian menu item

### ISSUE THREAD

**Issue by lorthirk** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2227]
**OS:** Windows 10, MacOS

**Issue Descriptions:** Having an Italian account, there's an item with a rather long text (Upgrade to family plan). As you can see in the screenshot, the icon gets resized, and the text takes all the space possible without leaving any right margin.

![sidebar2](https://cloud.githubusercontent.com/assets/8140139/22855985/6a398056-f089-11e6-9c27-4f231a9fdb07.PNG)

It would be great if it could be stretched a bit, 20 pixels or so could be enough.

**Steps to Reproduce:**
1- Start Play Music Desktop Player
2- Log in with an Italian account
3- Open the sidebar

**Comment by MarshallOfSound** [comment]
This is a GPM issue that doesn't really give us many "safe" options to fix.  

However you can fix this yourself with the custom styles settings in "Desktop Settings".  A CSS file with this in it

```css
#drawer {
  width: 300px !important;
}
```

Should do the trick for you 👍

**Comment by lorthirk** [comment]
I would have loved a more "permanent" solution, but that's ok. By the way, I preferred to use
```
#drawer {
  min-width: 310px;
}
```

Anyway, while importing the CSS, I had another idea, but I'd like to ask an opinion before I start a new issue.

I think it would be easier to allow direct input of CSS instead of reading it from file. I don't know how long are the content of these files usually, but for a simple fix like this it really makes little sense to create a file just for it.

**Comment by MarshallOfSound** [comment]
@lorthirk Inputting CSS directly into a text box means we would have to support things like CSS indenting / highlighting and other such things for it to be good UX.

If we only allow files (which aren't too hard to create let's be honest) then it's up to the user to choose an editing experience that helps with that.  Also normally people use custom CSS for a lot more than a 3 line fix 😆

**Comment by lorthirk** [comment]
Well, I didn't say that creating a file is hard, but that I think that there are easier way :)

Anyway, I agree with your other reasons.
