### ISSUE TITLE
Opening on all desktops on 2016 MBP w/ TouchBar

### ISSUE THREAD

**Issue by litgvng** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2228]
Hey guys, new to GitHub so forgive me if I'm doing anything wrong, but I am having an issue where the Desktop Player is staying open on all desktops (unless I put it in full screen mode). This just started happening today. I have tried rebooting the computer, force quitting the app, resetting the NVRAM, and everything else I can think of. To better describe the problem, I have 8 separate virtual desktops on my MacBook Pro. Normally, I can have 8 different applications open on separate desktops and swipe between them with the 3 finger gesture on the trackpad. However, what is happening now is when I swipe between them, the application stays open. No matter what I try. Thanks in advance for any help.

Edit: The version of Google Play Music Desktop Player that I am using is 4.1.1

-->

**OS:**
macOS Sierra 10.12.3
2016 MacBook Pro with TouchBar

**Issue Descriptions:**
See above

**Steps to Reproduce:**
Issue occurs every time I open the application.

**Comment by MarshallOfSound** [comment]
Sounds very much like an OS (sierra) bug, I can't reproduce on either of my macs, can you provide a screencast of what you are seeing?

**Comment by litgvng** [comment]
Thanks for the very quick response. Here is a link to a screencast I just recorded. It could be a bug with Sierra but it doesn't occur with anything else.

https://www.youtube.com/watch?v=tkAcJxt9AAY

**Comment by MarshallOfSound** [comment]
Can you try the default Electron application and see if it exhibits the same behavior

https://github.com/electron/electron/releases/download/v1.4.12/electron-v1.4.12-darwin-x64.zip

**Comment by litgvng** [comment]
How does one do that?

**Comment by litgvng** [comment]
If this is what you are referring to I'm having trouble getting it to work.

<img width="1440" alt="screen shot 2017-02-12 at 2 33 20 am" src="https://cloud.githubusercontent.com/assets/25717759/22860430/b1c9c09c-f0cb-11e6-85c9-d8a995791b16.png">

**Comment by MarshallOfSound** [comment]
@litgvng I linked the download before, simply download that zip file and launch the application

**Comment by litgvng** [comment]
Ok, I did that and it is not exhibiting the same behavior.

**Comment by MarshallOfSound** [comment]
I've investigated this as far as I can and I can't reproduce on any machine I have available to me (including the 2016 MBP).  The best I can suggest is turn off any custom Window Managers if you are using them and if not hope that a Chromium update will handle the issue.
