### ISSUE TITLE
Bringing GPMDP(u) to the Windows Store and Mac AppStore. [Universal App]

### ISSUE THREAD

**Issue by jebeld17** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2229]
Having the app accessible for download just on a site and some tech news articles online is not enough.<br />Today, when someone wants to download an app, more and more people are looking through the app stores pre-installed with their devices than ever before. I really believe it would be an asset to both development of the app and the general public to bring Google Play Music Desktop Player (unofficial) to both the Windows Store and Mac AppStores, the first of which can be brought to easily - Microsoft has a tool for developers to easily port x86 and x64 System32 apps to the Universal Windows Platform. <br /><br />It's definitely worth looking into.

**Comment by MarshallOfSound** [comment]
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/2105
