### ISSUE TITLE
Media Keys Skipping multiple songs

### ISSUE THREAD

**Issue by whipflash191** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2232]
**OS:**
Windows 10 64bit 
**Issue Descriptions:**
When using my media keys the it skips 2 songs instead of one. Have unistalled google play extension in chrome as well
**Steps to Reproduce:**
Use media keys to skip song (im using a blackwidow)

**Comment by MarshallOfSound** [comment]
This is literally all you had to search [skip songs](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues?utf8=%E2%9C%93&q=is%3Aissue%20skip%20songs%20is%3Aclosed%20)

You would have quickly found #2226 #2217 #2189 #2107 #2100 amongst others

TLDR: This is a duplicate, please follow the issue template and ensure you aren't raising already closed issues

**Comment by ogyct** [comment]
4.4.1, windows 10, logitech g413 keyboard, issue still exists
