### ISSUE TITLE
Play Count Is Very Inaccurate

### ISSUE THREAD

**Issue by Varelse4** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2233]
**OS:** Windows 10

**Issue Descriptions:** The play count is often very inaccurate. This previously occurred with just a single song, which you can see [here](http://i.imgur.com/QQb1dBb.png), but it's now happening with an entire album, which you can see [here](http://i.imgur.com/PsdWNSf.png).
**Steps to Reproduce:** I don't know how to reproduce this. As you can see, there's no correlation with song length or placement on the album or anything. Only the first song on Demon Days is affected, and only the last two on Good Kid, M.a.a.d City aren't.

**Comment by jostrander** [comment]
This is an issue directly with GPM and has nothing to do with GPMDP. File an issue on the Google Product Forums for this.

**Comment by Varelse4** [comment]
OK, thanks for the response
