### ISSUE TITLE
Inconsistent shuffle state in playback.json

### ISSUE THREAD

**Issue by slowbro** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2234]
**Version**: gpmdp-4.0.5-2 (AUR package)

**OS:** Arch Linux: Linux xb 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux

**Issue Descriptions:** Oftentimes, when toggling shuffle, the playback.json file does not get updated. It seems to 'break' for the album you are listening to, but reverts back to working on a different album. I have not found a consistent reproduction for this as it changes so much.

It actually shuffles - based on the state of the icon - but sometimes the json file is not updated with that fact.

**Steps to Reproduce:**
When it's happening:

1. Play an album without shuffle.
2. Click the shuffle button or hit the hotkey 's'
3. Examine ~/.config/Google\ Play\ Music\ Desktop\ Player/json_store/playback.json and note that 'shuffle' does not match the shuffle setting visually.

**Comment by MarshallOfSound** [comment]
This is fixed in master see https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/commit/151e97a236da591419efe96c186deb131b5a06c2
