### ISSUE TITLE
Fullscreen & Second Monitor

### ISSUE THREAD

**Issue by briancalderon** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2235]
**OS:** Mac OS X 10.11.6

--

**Issue Descriptions:** The app does not _Resume_. See [User Interface Preservation on The Core App Design](https://developer.apple.com/library/content/documentation/General/Conceptual/MOSXAppProgrammingGuide/CoreAppDesign/CoreAppDesign.html#//apple_ref/doc/uid/TP40010543-CH3-SW26).

When quitting the application on Mac, it does not appear to use the Resume functionality (or custom window sizing, window state of fullscreen, display window was on restoration).

I have a second monitor and definitely use the app on the second screen in Fullscreen `⌘ + ⌃ + F` all the time. The app is never out of Fullscreen and on my main iMac display.

While it's a pain to always have to move the app over and put it in Fullscreen it's not the biggest deal if it can't automatically do this. I do wonder if this is an issue with the site-to-native-app framework being used. Meaning it's not directly GPMDP's fault.

With that, is it possible to add Mac's native Resume functionality for managing the player window upon quit and launch?

--

**Steps to Reproduce:**

(This requires a second display and a macOS device)

1. Launch GPMDP
2. Move the main player window to the second display
3. Enter Mac's native fullscreen mode (Using Mission Control, maximize button, `⌘ + ⌃ + F`, Menu Bar > View > Toggle Fullscreen)
4. Quit the application
5. Observe that the app _"Resumes"_ on the main display and not in Fullscreen

**Comment by MarshallOfSound** [comment]
Size, location and screen are all persisted by GPMDP. The only thing we don't persist is full screen state as I didn't feel it was appropriate (other apps didn't appear to do it).

The follow up issue you are experiencing is that when in fullscreen the X, Y coords and size are "invalid" for normal usage so are reset on relaunch of the app.

I can look into supporting persisted full screen state but I still think the UX will be janky at best.

**Comment by MarshallOfSound** [comment]
So I just had a go at persisting the full screen state and I stand by my initial guess that it would be janky UX.  I personally don't like it doing it, and I don't think others will either.

Although this experience is sub-optimal there isn't much I can do about it, newer versions of macOS appear to report fullscreen coords a little more logically though so if you can update your macOS you should see a small improvement in window position restoration. 👍

**Comment by briancalderon** [comment]
That is not correct. Which is why I linked to the documentation. The Restore functionality is for both window coordinates and window state, including Fullscreen.

I don't know what janky UX means. I do know that every single app I use on my computer is in Fullscreen. Apps that don't do this I do submit to the developer to support Resume correctly.

If this is an issue for you, then please add an option to turn it off for yourself, but leave Resume on by default as that is the expected behavior on any Mac version.

I see no reason to not implement the correct behavior of a Mac application even if it's "janky." Even the dying Chrome apps opened as windows as their own application support Resume for display, position, and Fullscreen.

**Comment by briancalderon** [comment]
As it currently is, an update recently broke the UX. So I see no reason why not to have Fullscreen support when the app is already broken.

The window chrome at the top is not displayed anymore and it shows a black bar at the bottom.

When the UI refreshes on the homepage, it's blaring white and not the dark theme.

When the app is in dark mode—albums with light backgrounds don't show the appropriate contrasting overlay to make text readable.

So, janky UX is already a thing as of the current state. I can ignore those above, but the Fullscreen thing is starting to bug me as I am tired of having to move it over when it's just a music app; no reason to have a complicated window system. I know it's a free app, but I might as well not use it since the Fullscreen thing is breaking it entirely to show up on the wrong display anyways.

**Comment by MarshallOfSound** [comment]
> That is not correct. Which is why I linked to the documentation. The Restore functionality is for both window coordinates and window state, including Fullscreen. As seen in apps that quit in Fullscreen, will Resume in Fullscreen.

That certainly isn't the case in several of the apps I tested, it appears to be developer prerogative as to whether or not the fullscreen state is restored. Also the documentation is for macOS apps only and specifically targets macOS native API's.  This change would affect all platforms.

> The window chrome at the top is not displayed anymore and it shows a black bar at the bottom.

Fixed in master

> When the UI refreshes on the homepage, it's blaring white and not the dark theme.

Fixed in master

> When the app is in dark mode—albums with light backgrounds don't show the appropriate contrasting overlay to make text readable.

Fixed in master

> I might as well not use it since the Fullscreen thing is breaking it entirely to show up on the wrong display anyways.

That is entirely your choice to make, if you truly feel that the fullscreen state of this app is "breaking it entirely" then you do what you must 😄 

> I see no reason to not implement the correct behavior of a Mac application

Nowhere in the documentation you linked does it say that macOS apps **have** to use the resume functionality, if they did it would be enforced at an OS level, not be an optional API that people can use.  That API isn't even accessible in our codebase anyway and we use a custom window state preserver: https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/main/features/core/persistAppState.js#L12

**Comment by MarshallOfSound** [comment]
All that being said I can sense this becoming a thorn in my side so I'm just going to do it anyway...  If **any** issues get raised about this being unexpected (as I believe it is) it will be removed 👍

**Comment by amancevice** [comment]
Thanks for doing this
