### ISSUE TITLE
Dark theme loading problems on Home screen

### ISSUE THREAD

**Issue by brendonrapp** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2236]
**OS:** MacOS 10.12

**Issue Descriptions:** When using the Dark theme, elements of the theme will often fail to load correctly on the Home page. This tends to occur not on initial use, but when browsing back to the Home page after an indeterminate period of use.

Issues tend to include the dark background missing, or the dark background present but dark text for the hover text on the Recent Activity items.

**Steps to Reproduce:**
- enable Dark theme
- play music for an period of time (a few songs)
- return to the Home page

Examples:
<img width="1349" alt="screen shot 2017-02-15 at 10 40 13 am" src="https://cloud.githubusercontent.com/assets/170030/22989565/37f35790-f36b-11e6-91b8-b4dc0fa36d4c.png">
![screen shot 2017-02-15 at 10 17 23 am](https://cloud.githubusercontent.com/assets/170030/22989574/3e0d8f24-f36b-11e6-9e3d-c7626334b632.png)

**Comment by MarshallOfSound** [comment]
Please raise over at the theming repo, I noticed this the other day but haven't had time to look into it 👍
