### ISSUE TITLE
Issue: Descriptions in dark mode unreadable

### ISSUE THREAD

**Issue by jeffrin** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2240]
**OS: Windows 10 64-bit

**Issue Descriptions: Station descriptions are not shown in white text as are the titles, making them difficult to read in the dark mode.

**Steps to Reproduce: Enable dark mode.
![2017-02-16_1638](https://cloud.githubusercontent.com/assets/15200426/23047717/6b805f8a-f466-11e6-93c9-f488c469f0dd.png)

**Comment by MarshallOfSound** [comment]
Please raise on the theming repo 👍 😄
