### ISSUE TITLE
Pressing the hotkey for previous/next track makes it jump over one track in the playlist.

### ISSUE THREAD

**Issue by PokaLXIV** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2242]
I'm having some issues with the global hotkey for next/previous track when using GPMDP. When I press the hotkey for next/previous it skips over one track in my playlist. This doesn't happen when I use Play music with Chrome directly.

OS: Windows 10

**Comment by MarshallOfSound** [comment]
This is like the seventh duplicate, please check closed issues before raising new ones
