### ISSUE TITLE
Media Control Keys issue

### ISSUE THREAD

**Issue by DonJubsi** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2249]
**OS:**
Windows 10 Pro 64 bit
with latest updates (as of 19/02/2017)

**Issue Descriptions:**
Media Keys for Next Song and Previous Song react twice (like pressing them twice). I can only go back and forth in steps of 2. 
Note: It only happens with the Buttons on my keyboard not when I press the next song in the windows thingy next to the volume bar nor the buttons directly in the Music Player.
Keyboard: Corsair Strafe RGB Silent (German Keyboard Layout)
Software: Corsair Cue 2.9.53 - Keyboard Driver Version 2.05

I tried the same instructions that were given for not working media keys (removing chrome music extension visit chrome://restart and restart computer)

**Steps to Reproduce:**
Press Media Control Keys for Next Song or Previous Song

[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/786011/debug_info.zip)

**Comment by jostrander** [comment]
Duplicate. Please search closed issues.
