### ISSUE TITLE
Feature Request: ability to disable Windows 10 media controls popup on volume control

### ISSUE THREAD

**Issue by adinklotz** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2250]
**OS:  Windows 10**

**Issue Descriptions:  When changing the volume using the volume keys on my keyboard, a big media control windows appears next to the volume slider.  If possible, please add the ability to disable this popup.**

**Steps to Reproduce:  While music is playing in GPMDP, press one of the keyboard volume hotkeys**

![example](https://cloud.githubusercontent.com/assets/16441122/23107763/2ebab524-f6d1-11e6-897f-f1fb6c380891.png)

**Comment by jostrander** [comment]
This has been address and is fixed in master. Please search closed issues.
