### ISSUE TITLE
Hijack AirPods Controls (Double Tap to Play/Pause) So They Don't Route to iTunes

### ISSUE THREAD

**Issue by fronc** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2252]
**OS**
OS X El Capitan

**Issue Descriptions:**
The new AirPods have a play/pause function if you double tap them. But they open up iTunes and control from there. Can you figure out a way to intercept commands to iTunes in order to allow Play Music to play/pause?

**Steps to Reproduce:**
Start playing music in GPlay Music Player. With iTunes fully quit out, pair the AirPods with the Mac. Then double-tap the airpod. iTunes will launch, and Google Play Music will keep playing.

**Comment by jostrander** [comment]
Unfortunately I don't think it's possible on mac OS to intercept those commands. This has been discussed before but they only allow their media player to open. If I'm wrong or something has changed and you have documentation please let me know. Until then we can't fix this in any way.

**Comment by dm3ch** [comment]
@jostrander Just have tested controlling of Youtube Music playback via AirPods pro controls on macOS Catalina.

When I opens youtube music via Chrome Browser (Version 89.0.4389.114 (Official Build) (x86_64)) I can play/pause and switch tracks with AirPods controls.
But in desktop app it doesn't work.

Suddenly I haven't yet tried to found how Chrome implemented that, but as far as I understand Electron based on Chrome and should have same functionality. Maybe we need just rebuild application with fresh Electron to make that working?
