### ISSUE TITLE
New GPM features break custom themes

### ISSUE THREAD

**Issue by EpicWolverine** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2254]
**OS:** Windows 10

**Issue Descriptions:** It looks like Google is tweaking the website again, meaning custom themes need to be updated. I've noticed two main changes so far:

1. GPM logo appears for playlists without a background image
With logo and without background:
![firefox_2017-02-21_20-54-58](https://cloud.githubusercontent.com/assets/2897970/23193854/f9ea2fe2-f878-11e6-9e1f-5af6b5b8f7fa.png)
Without logo and with background:
![firefox_2017-02-21_20-51-36](https://cloud.githubusercontent.com/assets/2897970/23193858/fc080650-f878-11e6-89e0-de1b3847461b.png)
This logo gets hidden when any theme is applied, but it is still clickable (brings you back to Home)
![firefox_2017-02-21_20-55-40](https://cloud.githubusercontent.com/assets/2897970/23193932/37143462-f879-11e6-8348-cfed16387e50.png)

2. The search bar displays results differently now. This shows up fine in light themes (see above), but breaks down in dark themes.
![firefox_2017-02-21_20-55-57](https://cloud.githubusercontent.com/assets/2897970/23193954/5f20a382-f879-11e6-8057-3b0ec95c3da4.png)
![firefox_2017-02-21_20-56-11](https://cloud.githubusercontent.com/assets/2897970/23193956/60fa681e-f879-11e6-877f-6a56cd961a65.png)

**Steps to Reproduce:** I'm not sure if this has been rolled out to everyone yet. When it does, it should be pretty obvious how to reproduce it based on the pictures 😉.

**Comment by MarshallOfSound** [comment]
@EpicWolverine I don't have an account with access to this feature yet, as soon as I do I can work on a fix 👍

**Comment by leocaseiro** [comment]
Another issue is within the "Select the genres that you like" page which are full of dark text.

To reproduce, go to Settings > Improve your recomendations:

![screen shot 2017-03-02 at 12 41 33 pm](https://cloud.githubusercontent.com/assets/940070/23489309/a026cffa-ff45-11e6-89d8-07687920fffe.png)

**Comment by MarshallOfSound** [comment]
> Another issue is within the "Select the genres that you like" page which are full of dark text on the default Dark Theme.

This one I can see so I'll fix it up 👍 😄

**Comment by theVDude** [comment]
I just stopped by to report this as well, I noticed it first on the search bar. Of course someone else already saw t!
