### ISSUE TITLE
Installer or Standalone?

### ISSUE THREAD

**Issue by greghesp** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2258]
From what I can gather, GPMDP is a **standalone** application.

The reason I bring this up is that I referred quite a few people to this application, and almost every single one of them has asked me if I know why it does not appear in their apps after installing it.

The exe name of _Google.Play.Music.Desktop.Player.Setup_ implies that this is installing an application, as does the installation screen when running this.

To confirm...

Should there be an installed application, or is this a standalone exe with a confusing name and start up window

**Comment by MarshallOfSound** [comment]
The exe file should install itself and add relevant app listings / shortcuts.  A bug prevents this working correctly on Windows and I will be releasing a new version soon that fixes this issue :+1:

**Comment by MarshallOfSound** [comment]
Though tbh you can just use the installer as a launcher :P

**Comment by greghesp** [comment]
I do, I just keep getting asked the same question by people I've recommended it to :)
