### ISSUE TITLE
Link in releases is for 4.0.5

### ISSUE THREAD

**Issue by y2kbadbug** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2259]
Hello,

It appears that the link for 4.1.1 is actually linking to the release for 4.0.5

![image](https://cloud.githubusercontent.com/assets/6489750/23319666/2b933130-fa9d-11e6-8970-f47ad1c21dbc.png)

**Comment by MarshallOfSound** [comment]
This is correct for Linux, was temp workaround to some issues
