### ISSUE TITLE
Dual switching

### ISSUE THREAD

**Issue by SevereCloud** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2261]
**OS:** Windows
**Version:** 4.1.1

When you press the function key(⏮ or ⏭), the music switches twice.

![gif](https://cloud.githubusercontent.com/assets/14944123/23331766/9aaa6206-fb7d-11e6-904e-3f448d90b8c3.gif)

**Comment by MarshallOfSound** [comment]
Fixed in master, release imminent.  Please check closed issues
