### ISSUE TITLE
How to open inspector?

### ISSUE THREAD

**Issue by FezVrasta** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2262]
**OS:** macOS

**Issue Descriptions:** I can't find a way to open the inspector to read the classnames I want to use inside a custom stylesheet. I remember there was an option but I can't find it anymore?

**Comment by MarshallOfSound** [comment]
Command + Shift + G

Enter "DEV_MODE"

Click "Go"

When it relaunches you can use standard devtool shortcuts to open them.  To open the devtool for GPM itself run "openGPMDevTools()" in the first devtool window

**Comment by CEbbinghaus** [comment]
Can this be Pinned for Theme Developers? It would be helpful to be able to Inspect the HTML to style the CSS

**Comment by CEbbinghaus** [comment]
as a Follow up. It seems that you cannot use the Inspector to Select HTML Elements making it harder to figure out the css classes for specific parts.

Also it would be Helpful if it Remained in Developer mode until it was disabled again so it doesn't have to be toggled every Time the PC Restarts / The App Crashes
