### ISSUE TITLE
Version Number

### ISSUE THREAD

**Issue by logictom** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2264]
I am not seeing a version number any where in the application, Windows 10.

I keep checking back to see if the 'doesn't install in Windows' bug has been fixed but I'm also not sure if I have the latest version so I download every now and then for any other feature upgrades.

Could this be added to the top of the Desktop Settings page or somewhere else applicable?

**Comment by jostrander** [comment]
Version number is under Help-> About

![image](https://cloud.githubusercontent.com/assets/760989/23345173/6b65a980-fc57-11e6-8c1f-4e5e524bdf63.png)
![image](https://cloud.githubusercontent.com/assets/760989/23345178/95182a78-fc57-11e6-9a19-c1a91ab2f54b.png)

**Comment by MarshallOfSound** [comment]
`4.1.2` should be going out tonight :+1: (If I get time)

**Comment by logictom** [comment]
Thanks @jostrander, that was about the only place that I didn't check.
There is no link to help in the main application and F1 doesn't work, I didn't think to try the tray icon.

Thanks @MarshallOfSound, looking forward to it!

**Comment by MarshallOfSound** [comment]
@logictom Hit some issues on my local, not sure if they will be widespread when I update so delaying update for now till I figure out what's going on.
