### ISSUE TITLE
Play/Pause doesn't work anymore

### ISSUE THREAD

**Issue by clementlamoureux** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2265]
Hey everybody,

It seems that since today (27/02/2017) play/pause action doesn't work anymore, the key shortcut and the tray action Play/Pause.

Maybe Google change something and the desktop no longer can inject media action anymore, anybody else having this issue ?

**OS:** Ubuntu 16.04

**Issue Descriptions:** Play/Pause feature

**Steps to Reproduce:** Try to Play/Pause from the Tray dropdown, or try your keyboard shortcut

**Comment by r04r** [comment]
For what it's worth I'm on Windows and do not have this issue. Both the tray icon and the keyboard shortcut work just fine.

**Comment by clementlamoureux** [comment]
Okay, it's strange, I have restarted the app later in the day and now it's working, I close the issue, but maybe there is something to investigate in.
