### ISSUE TITLE
Cannot use Security Key 2FA Verification Method - 'An unexpected error occured.'

### ISSUE THREAD

**Issue by dshin198** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2266]
**OS:** Windows 10

**Issue Descriptions:**
Attempting to login to an account with Security Key 2FA enabled, I get 'An unexpected error occurred' message. 
![security key gpmdp login error](https://cloud.githubusercontent.com/assets/8847894/23366764/f1c0aa1a-fcd5-11e6-8386-ee504d0cb8c6.png)

**Steps to Reproduce:**

1. Start GPMDP (not logged in)
2. Click 'SIGN IN'
![image](https://cloud.githubusercontent.com/assets/8847894/23366853/3f507aa8-fcd6-11e6-8430-fc7145b9b97c.png)
3. Sign in using the information for the account with Security Key 2FA

**Comment by MarshallOfSound** [comment]
Electron itself does not support u2f keys yet.  You should use either the authenticator code fallback or one of your backup codes

**Comment by dshin198** [comment]
@MarshallOfSound Got it. Thanks for the clarification!
