### ISSUE TITLE
Library drop-down active font color

### ISSUE THREAD

**Issue by RajahBimmy** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#227]
In the library section, there's an "ALL MUSIC" drop-down next to shuffle which allows you to toggle Purchased vs. Uploaded content. When open, the text of the active element will turn orange upon mouse-over, regardless of theme modifications. (Just found this app by the way, it's absolutely killer.)

**Comment by MarshallOfSound** [comment]
Can you please move this issue to https://github.com/gmusic-utils/gmusic-theme.js

Cheers
