### ISSUE TITLE
Dock icon stops working after a while and shows question mark

### ISSUE THREAD

**Issue by calmandniceperson** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2270]
**OS:**
macOS
**Issue Descriptions:**
Clicking on the dock icon does not work anymore after a while. It seems like the application can't be found.

![Example screenshot](http://i.imgur.com/Gdw3jas.png)
Example screenshot taken seconds after closing the application and trying to open it again.

**Steps to Reproduce:**
When moving the app's icon to the dock and clicking it, the application opens up. However, when clicking the icon again after a while (e.g. after doing something else or closing the laptop), it shows a question mark and doesn't open up the application anymore. Seemingly it can't find it. Opening the app from the search and moving it to the dock again works.

**edit**: Seemingly this only happens when adding the icon to the dock through opening the app and then right-clicking it and choosing "Keep in dock". When adding it to the dock from the application directory or through search, it stays in the dock and clicking it opens the application with a new icon on the dock that disappears again when closing the application.

**Comment by MarshallOfSound** [comment]
This normally indicates a filesystem issue or rarely a macOS bug.  I would suggest repairing your FS or just moving the application around and trying from different locations.

If the macOS dock can't find the application for some reason I'm not sure how that can be our fault.  If I'm wrong with this please comment below 👍

**Comment by calmandniceperson** [comment]
@MarshallOfSound You might be right. It might also be a problem with Electron? Could that be? I couldn't find anything about it, which is why I reported the issue here.

**Comment by MarshallOfSound** [comment]
@calmandniceperson Looks like Hyper is working fine on your dock there so probably not an Electron issue 👍

**Comment by MarshallOfSound** [comment]
Woops, meant to close in the first comment.  Will reopen if it can be determined to be our fault / something we can fix or if others start reporting the same thing.  For now calling it a dock issue not an us issue.
