### ISSUE TITLE
Can't download

### ISSUE THREAD

**Issue by Magnus512** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2272]
**OS:** Fedora 64b

**Issue Descriptions:**
I can't download the package to install it https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/releases/download/v4.1.1/google-play-music-desktop-player-4.0.5.x86_64.rpm
**Steps to Reproduce:**

**Comment by Doigt** [comment]
Had the same problem earlier with another download on github, it seems like some download servers are temporarily offline.

**Comment by MarshallOfSound** [comment]
AWS is experiencing massive outages across their US regions.  As GitHub's releases are powered by S3 you will be struggling to download things today.
