### ISSUE TITLE
Lack of Desktop Notifications

### ISSUE THREAD

**Issue by TheKingdomofShenan** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2273]
**OS:**
Window 7 Pro
**Issue Descriptions:**
Lack of desktop notifications.
**Steps to Reproduce:**
Google Music Settings have desktop notifications enabled and they are functional in the web app as well.
GPMDP desktop notifications are enabled in Control Panel.

**Comment by MarshallOfSound** [comment]
Windows 7 does not have official support for Desktop Notifications.  We have a shim that fakes the notifications on windows 7 but it's possible that has broken as Windows 7 is old enough for none of my devices to be running it.

It's virtually impossible to support an OS that is being progressively depreceated by everything 😆 
I'll try see what's going on but no promises 👍

**Comment by MarshallOfSound** [comment]
Windows 7 notifications work fine when tricked into activating on other OS's.  Ensure you have notifications enabled in GPM
