### ISSUE TITLE
BOSE QC35 Media controls over bluetooth

### ISSUE THREAD

**Issue by Alstar983** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2277]
Hi,

**OS:**
mac 10.10.5
I am running version 4.1.1 of the desktop player.

**Issue Descriptions:**
Im not sure if this can be fixed based on the below issue that has been closed.
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/1932

I have my QC35 headphones linked to my phone (Android) and my mac via bluetooth. every time i get a call the headphones try to pause the player (on my mac) which instead of pausing the music opens iTunes. This also happens if you press the central button in the controls on the QC35s.

This function works correctly when i play music through spotify.

**Steps to Reproduce:**
press the middle music control button on the QC35s.

**Comment by MarshallOfSound** [comment]
> This function works correctly when i play music through spotify.

Spotify uses hax as far as I know to reroute the media button to their own application instead of itunes.  I don't think we have the ability to do that hence the closed issues you linked 👍

**Comment by Alstar983** [comment]
thanks.
