### ISSUE TITLE
Ampersands not rendered in tray icon tooltip

### ISSUE THREAD

**Issue by bhaelochon** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2278]
**OS:** Windows 10 Pro x64

**Issue Descriptions:** When a song title (and presumably an artist name, but not tested) contains an ampersand (_&_), it isn't rendered in the tray icon's tooltip.

![image](https://cloud.githubusercontent.com/assets/179590/23522311/1700b77e-ff48-11e6-9477-1044332f0ad8.png)

![image](https://cloud.githubusercontent.com/assets/179590/23522331/2323e2a6-ff48-11e6-9e79-47d24d313c4d.png)

**Steps to Reproduce:** Play a song that has an ampersand in the track title, then hover over the tray icon.

**Comment by MarshallOfSound** [comment]
This appears to be a windows thing 😆 "&&" as "&" will render and "&" will not 😕 ....

Will add a simply replace to fix this 😆

**Comment by fraserhaer** [comment]
Hey I've never helped with open source, can I give this a whirl?

**Comment by MarshallOfSound** [comment]
@fraserhaer Sure, you probably want to look at the two lines in this file where we set the tooltip

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/40ee551fef2520b928d2175b3ab4b885d6dd51f8/src/main/features/core/windowTitleInfo.js#L13

And then do string replacement on the generated string to replace all "&" with "&&" 👍
