### ISSUE TITLE
Feature Request: open player with single-click in system tray icon

### ISSUE THREAD

**Issue by tomcpc** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2279]
Currently, when minimized to the system tray, it is necessary to double-click the player to open it. Instead of a double-click, please allow the player to be opened with a single-click.

**Comment by MarshallOfSound** [comment]
This changes from OS to OS, we try to follow the standard behaviour on each OS which at least on windows is double click to open.

**Comment by tomcpc** [comment]
What about placing an option in the settings and letting the user decide?
