### ISSUE TITLE
Feature Request: keyboard shortcuts that work only when player is focused

### ISSUE THREAD

**Issue by tomcpc** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2280]
The ability to create keyboard shortcuts that work only when the player is focused would allow users to create more simple shortcuts, like the ones from Winamp, for example:

```
Z 	Previous Track
X 	Play/Restart/Unpause
C 	Pause/Unpause
V 	Stop
B 	Next Track
```

This is very handy — among other situations, it goes very well with an always-on-top mini player.

**Comment by MarshallOfSound** [comment]
GPM has lots of these built in, hit the "?" key when in GPM to get the full list.  Slightly different keys but I don't want to have conflicting shortcuts as we can't unbind GPM's bindings
