### ISSUE TITLE
Feature Request: Playlist Cacheing for Subscribers

### ISSUE THREAD

**Issue by Deastrom** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2282]
**OS:** Windows 10 Pro, would love to see the caching option for Linux as well as I think this would be great for any raspberry pi car stereo projects.

**Issue Descriptions:** The android app allows for google play music subscribers to cache playlists for offline play.  Is it possible to implement such a feature on your software?

**Steps to Reproduce:**

**Comment by jostrander** [comment]
This has been discussed numerous times, and unfortunately no.
