### ISSUE TITLE
Casting Icon Disappeared

### ISSUE THREAD

**Issue by sanjay228** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2283]
**OS:** Windows 10 

**Issue Descriptions:** The player used to display the casting icon in order to cast music to either Chromecasts, Chromecast Audio, or Google Home. Now it does not, even though I'm connected to a network with multiple casting options. I have tried uninstalling and reinstalling the app as well. The first screenshot is from: https://play.google.com/music/listen?u=0#/wmp

![issue 1](https://cloud.githubusercontent.com/assets/26171334/23563239/70352654-000b-11e7-876a-79c99dc84f81.jpg)

And the second is from the app itself. 

![issue 2](https://cloud.githubusercontent.com/assets/26171334/23563247/779c1d76-000b-11e7-8edd-f1384f5d6873.jpg)

 
**Steps to Reproduce:** Open Google Play Music Desktop Player while connected to a network with multiple casting options.

**Comment by MarshallOfSound** [comment]
I'm back on a network where testing Chromecast is exceedingly difficult.  Can someone else test this ( @jostrander )?

**Comment by BrianAllred** [comment]
My Google Home and Chromecast are both listed on my Windows 10 box.

Have you allowed GPMDP through your firewall?

![image](https://cloud.githubusercontent.com/assets/5847511/23576547/0a080686-006e-11e7-98fb-a8573ff74a2c.png)

**Comment by BeheSQ** [comment]
same here, no Cast icon.

- firewall checked with this settings
Allow Chromecast Outbound	32768-61000	TCP, 8008-8009	TCP
Chromecast SSDP	1900	UDP
Chromecast Inbound	32768-61000	UDP
also GPMDP is allowed to do whatever it wishes to do (in firewall)

- hapilly casting from Chrome

need to check anything else?

**Comment by MarshallOfSound** [comment]
@BeheSQ Assuming you are on Windows can you install Bonjour 👍

**Comment by BeheSQ** [comment]
@MarshallOfSound yes! although I was a bit reluctant to install anything Applish into my Windows, installing Bonjour and restart helped. thanks a lot.

PS: for those looking for Bonjour installation, it is included in Bonjour Printer Services (convenient, isn'it?) on this link: https://support.apple.com/kb/DL999?viewlocale=en_US&locale=en_US
BEWARE! during installation double check, that you have the autoupdate option unchecked. Apple auto update is a slippery slope into hell. BEWARE!

**Comment by jostrander** [comment]
@sanjay228 Do you have Bonjour installed? Can you test after installing Bonjour? I'm going to close this for now, but if that doesn't work please reply and we'll try to figure it out.

**Comment by kp37** [comment]
I'm running into the same issue. Chromecast works fine on version 4.0.4 of GPMDP but not on 4.2.0 of GPMDP. I have bonjour installed and nothing blocking it in my firewall settings. I am running Windows 10 on both computers.

![casting icon](https://cloud.githubusercontent.com/assets/21187665/24256941/e74c6068-0fbf-11e7-8739-782f86cfcd3e.PNG)

![no cast icon](https://cloud.githubusercontent.com/assets/21187665/24257036/1c8cf4d6-0fc0-11e7-8570-fc8e440595b0.JPG)

**Comment by augaug** [comment]
I am having this same issue even after re-installing Bonjour - Windows 8.1 - any suggestions?

**Comment by jostrander** [comment]
Check for firewalls. You need to allow in port 5353 UDP to GPMDP in order for the app to see casts on the network.

**Comment by kp37** [comment]
Everything is allowed for GPDMP and Bonjour. Can someone please post a screenshot of all the rules needed for Chromecast support to work?

**Comment by jostrander** [comment]
Does turning the firewall off temporarily fix the problem?

**Comment by aagha** [comment]
Installing Bonjour per @BeheSQ resolved this issue for me.
