### ISSUE TITLE
Remove tooltips

### ISSUE THREAD

**Issue by Koveryl** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#229]
Nobody really needs them, and they look _pretty_ ugly when they come out of nowhere. If somebody feels as though they need it, maybe there could be a setting in the options?

**Comment by MarshallOfSound** [comment]
Tooltips???

Please provide a screenshot

**Comment by Koveryl** [comment]
![image](https://cloud.githubusercontent.com/assets/3173241/13551505/5c49045e-e30a-11e5-8bf3-851ae0930dad.png)

On some objects, that happens if you mouse over them for a bit.

**Comment by MarshallOfSound** [comment]
Oh lol, they are required for "accessability"  E.g. Someone who is blind and uses a screen-reader

That and I'm pretty sure there is no way to turn them off, they are baked into Chromium

**Comment by Koveryl** [comment]
Aw, that sucks haha. Sure takes away from how beautiful the app looks. Still, thanks for the response! :)
