### ISSUE TITLE
What's New dialog box is persistent

### ISSUE THREAD

**Issue by benvddriessche** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2290]
**OS:** Windows 10

**Issue Descriptions:** "What's New" dialog box pops up every time the app is launched. Started in version 4.1.1, still there in 4.2.0

**Steps to Reproduce:** Laumch GPMDP, either from main executable or shortcut

**Comment by MarshallOfSound** [comment]
@benvddriessche Can you provide the DEBUG zip file as described here https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ#how-do-i-generate-this-debug-zip-file

**Comment by benvddriessche** [comment]
@MarshallOfSound 
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/821739/debug_info.zip)

**Comment by MarshallOfSound** [comment]
Is it showing every time you restart your app now?

I.e. If you restart GPMDP 5 times now does it appear all 5 times?

**Comment by benvddriessche** [comment]
It does, yes

**Comment by MarshallOfSound** [comment]
@benvddriessche How are you launching the app?

**Comment by benvddriessche** [comment]
Shortcut pinned to taskbar but the same thing happens if I launch directly from ../GPMDP_3/app-4.2.0/Google Play Music Desktop Player.exe

**Comment by MarshallOfSound** [comment]
This is really weird, your `settings.json` clearly has the correct "welcomed" value but you say it still welcomes you each time 😕 

It's hard to figure out what's going on without the ability to debug the actual machine 😆 

Will try repro locally but no idea how

**Comment by benvddriessche** [comment]
I just uninstalled the app and manually deleted all %appdata% traces. Upon reinstall, behavior of the welcome screen is as expected.

**Comment by MarshallOfSound** [comment]
@benvddriessche How strange 😖 

Gonna close this out as a weird occurance of weirdness 😆
