### ISSUE TITLE
Breaks desktop notifications in Ubuntu

### ISSUE THREAD

**Issue by hotice** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2291]
GPMDP breaks desktop notifications in Ubuntu (tested in Ubuntu 16.10 64bit with Unity, GPMDP 4.2.0). I'm not sure if it affects other Linux distributions / Ubuntu flavors too. 

While GPMDP is running, desktop notifications don't work for any application, even if notifications are disabled in GPM.

Steps to reproduce:
- launch GPMDP, then test some notifications. To quickly test it, install ``libnotify-bin`` using: ``sudo apt install libnotify-bin``, then run the following command from a terminal: ``notify-send test``. Normally this should display a desktop notification, but it doesn't while GPMDP is running.
- close GPMDP, then try sending a desktop notification with ``notify-send test``. The notification now shows up.

I've attached the debug info, but it doesn't seems to have any useful info regarding this issue.

[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/820886/debug_info.zip)

**Comment by MarshallOfSound** [comment]
I can't replicate this in Ubuntu 16.10 as described inside a VM.  Do you have any modifications on the standard environment?

**Comment by hotice** [comment]
I have quite a few things installed, indeed. I also tested it in a fresh Ubuntu 16.10 virtual machine and this issue didn't occur. I guess it's related to something specific on my machine... so you can close this if you wish.
