### ISSUE TITLE
I can't sign in.

### ISSUE THREAD

**Issue by wackydude1234** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2292]
**OS:** Windows 10

**Issue Descriptions:** I've just installed the program, it's asking me to sign in, I click sign in the button flashes and nothing happens, i can click it again and again but nothing happens

**Steps to Reproduce:** install program, run program, click sign in, nothing.

**Comment by wackydude1234** [comment]
Hmm after trying a tonne of times it's suddenly decided to load only after I ended up posting. sorry.

**Comment by MarshallOfSound** [comment]
The sign in button is not controlled or created by this application.  Can you ensure

* You can sign in correctly in Chrome
* You have tried after reinstalling
* You have tried on a different network

This is probably a temporary google issue 👍
