### ISSUE TITLE
No sound after new update

### ISSUE THREAD

**Issue by dumpdemon** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2294]
Ever since i have updated my windows client to the newest version and now when i click play on a song or whatever no sound plays.

I have checked my Volume Mixer and it  is at full volume but still nothing is happening

**Comment by MarshallOfSound** [comment]
Sounds like a windows issue.

Uninstall, Reboot, Reinstall, try again 👍
