### ISSUE TITLE
Main window is blank!

### ISSUE THREAD

**Issue by lordluzbel** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2298]
**OS:** Windows 10 Pro

**Issue Descriptions:** When opening the application first time in windows 10, the main window remain blank and I'm not able to do action on the screen.

**Steps to Reproduce:** Open the application right after that window first launching.

**Comment by MarshallOfSound** [comment]
Sounds, like Electron crashed for some reason.  Would recommend uninstalling and reinstalling, ensure you have a network connection and if you are using a proxy or a VPN turn it off 👍
