### ISSUE TITLE
Feature Request: Album sort by artist?

### ISSUE THREAD

**Issue by iamme101** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2299]
Hello

Got to say loving the app have just joined Google Play Music and was a bit miffed they didn't have a desktop app as I''m used to using the Spotify desktop app and then I cmae acorss yours and it's fantatsic you're doing a great job.

I'm not sure if it's possible or if I'm asking in the right place but something that I didn't like when joining Google Music was that albums are sorted by title where as on Spotify they can be sorted by Artist in the libary which I personally liked and wondered if it would ever be an option in the app?

**Comment by MarshallOfSound** [comment]
That's not something we have control over.  I would recommend asking on the Google Product Forums
