### ISSUE TITLE
Request: Option to disable Notification Toaster

### ISSUE THREAD

**Issue by F1am** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#23]
Hi, I would love to disable the notification toaster.

Thanks for your excellent app, I've been waiting for something like this for ages.

**Comment by MarshallOfSound** [comment]
I'm attempting to link the built in toaster to the GPM desktop notifications setting in their labs section.  Just attempting to determine the URL to request to retreive that setting
