### ISSUE TITLE
Miniplayer and Youtube video issues

### ISSUE THREAD

**Issue by Koveryl** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#230]
Youtube videos don't show in the miniplayer (audio still plays though. The video is seen in the top-left of the app when returning to normal view), and the button for it also looks extremely odd and out of place.

![image](https://cloud.githubusercontent.com/assets/3173241/13551531/50376736-e30b-11e5-9511-31951c367595.png)

**Comment by MarshallOfSound** [comment]
There is an open PR to deal with this on another repository.  I'll merge it and release in the next version

**Comment by MarshallOfSound** [comment]
FYI: https://github.com/MarshallOfSound/gmusic-mini-player.js
