### ISSUE TITLE
Debian repository is out-of-date

### ISSUE THREAD

**Issue by rattboi** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2301]
**OS:**
Ubuntu 16.04

**Issue Descriptions:**
Try to get latest version from repo. That version is 4.0.5 instead of latest.

**Steps to Reproduce:**
Add repository, apt-get update, apt-get install google-play-music-desktop-player

**Comment by MarshallOfSound** [comment]
Woops, uploaded and never clicked publish...........
