### ISSUE TITLE
Feature Request: Save / Restore Queue on App Exit

### ISSUE THREAD

**Issue by Iristyle** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2304]
Didn't see this request elsewhere, so filing an issue.

### OS: 

OSX

### Issue Descriptions:

When exiting the app and then reopening, any previous queue is deleted.

### Steps to Reproduce:

* Open player on OSX
* Queue some tracks up and start playing
* Exit player
* Re-open player

Note the queue is now gone.  I'm used to the behavior of Spotify or even the mobile Google music app, where the queue is remembered.

**Comment by MarshallOfSound** [comment]
This is not currently possible, we do not maintain the queue and we can't restore the queue to it's original form.
