### ISSUE TITLE
Window stop update after starting play a song.

### ISSUE THREAD

**Issue by nicka-cme** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2305]
**OS:** Windows 10 Pro

**Issue Descriptions:**
Main windows stop drawing and accepting mouse or keyboard input after starting music play. This has just started happening since the latest update. Music continues to play however it after playing for about 2 or 3 song it stops all together.
Version: 4.2.0.0

**Steps to Reproduce:**
1. Open GPMDP
2. Start playing song by hitting the feeling lucky button
Observe that after about 10s the main window stops updating. Even right clicking on the tray icon is very laggy and slow to open. It also the Windows 10 notification is blocked from displaying. However it will display if you right click on the tray icon.

At a guess something is executing on the main thread hence stopping the UI from processing events.

What I have tried:
Disabling
* Custom theme
* Enable Voice Controls
* Enable JSON API
* Enable Playback API
* Use system window borders
* Automicatalling load last viewed page on startup
* Scroll lyrics automatically while playing
* Show track progress in the traskbar
* Enable the Windows 10 System Media Service

**Comment by MarshallOfSound** [comment]
Disable Notifications from GPM settings 👍

**Comment by nicka-cme** [comment]
Perfect. Thank you. Keep up the awesome work.
