### ISSUE TITLE
Split-Second Volume Jump on Resume

### ISSUE THREAD

**Issue by JMarimon** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2306]
_(Windows 10 x64, latest version of GPMDP)_

I've been experiencing an issue with GPMDP where the volume jumps to maximum for a split second after resuming. I've found that it happens consistently if I'm in another application for a at least a minute and then use my keyboard or headphones to resume playback. The jump in volume is very short, but it's annoying over speakers and actually a bit painful with headphones on.

I've experienced this issue on my work laptop and my home desktop (with external DAC/Amp), both running Windows 10 x64.

**Comment by MarshallOfSound** [comment]
If this is happening, it's GPM itself doing it, however, I doubt it is actually the application or even your computer doing what you are hearing, it's probably your speakers receiving a surge of current each time they start playing.  (My theories are always this weird) 😆 

The only way to truly tell is to use a waveform analyzer on the audio output of your PC and see what the program is actually emitting.  But for now, this literally can't be something we are doing 👍
