### ISSUE TITLE
Debian repo no longer signed and outdated

### ISSUE THREAD

**Issue by G4Zz0L1** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2307]
**OS:**
LInux Mint 18.1 64bit

**Issue Descriptions:**
The repository is no longer signed, and the application version is outdated

**Steps to Reproduce:**
Add repository (https://dl.bintray.com/marshallofsound/deb) and apt-get update. For the second part apt-get install google-play-music-desktop-player

**Comment by MarshallOfSound** [comment]
The application version is `4.2.0` and bintray is still signing the releases, can you actually post any errors you are getting when installing?

(Closing out as it isn't an issue with GPMDP itself rather the install process)

**Comment by G4Zz0L1** [comment]
The error it gives me is:

E: The repository 'https://dl.bintray.com/marshallofsound/deb debian Release' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

While, for the version:

google-play-music-desktop-player:
  Installato: 4.0.5-1
  Candidato:  4.0.5-1
  Tabella versione:
 *** 4.0.5-1 500
        500 https://dl.bintray.com/marshallofsound/deb debian/main amd64 Packages
        100 /var/lib/dpkg/status
     4.0.3-1 500
        500 https://dl.bintray.com/marshallofsound/deb debian/main amd64 Packages
     3.2.5-1 500
        500 https://dl.bintray.com/marshallofsound/deb debian/main amd64 Packages
     3.2.4-1 500
        500 https://dl.bintray.com/marshallofsound/deb trusty/main amd64 Packages

**Comment by rattboi** [comment]
I get the same as above. Unsigned repo.

**Comment by MarshallOfSound** [comment]
Am contacting bintray support

**Comment by G4Zz0L1** [comment]
Any news from bintray?

**Comment by rattboi** [comment]
Any update?

**Comment by G4Zz0L1** [comment]
Now it updates to the 4.2.0-1, but it still gives the "no signed" error. Something's moving...

**Comment by Ocramius** [comment]
I'm getting 3.2.4 when downloading from the `trusty` channel on bintray. 

The warning I get is:

```
Reading package lists... Done
W: The repository 'https://dl.bintray.com/marshallofsound/deb trusty Release' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by sebastienserre** [comment]
same here:
`
Err:24 https://dl.bintray.com/marshallofsound/deb debian Release.gpg
  **404  Not Found**
E: The repository 'https://dl.bintray.com/marshallofsound/deb debian Release' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`

**Comment by fastcat** [comment]
bintray is signing the packages, but not the repository.  Newer versions of APT require the repository to be signed, resulting in the above errors.

**Comment by alessiogatto** [comment]
I have the same problem with ubuntu 17.04 final beta. 
![schermata del 2017-04-12 21-29-37](https://cloud.githubusercontent.com/assets/20967334/24975852/6d9578f0-1fc7-11e7-809a-80d904909270.png)

**Comment by luislobo** [comment]
Same problem here

```bash
E: The repository 'https://dl.bintray.com/marshallofsound/deb debian Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by luislobo** [comment]
@MarshallOfSound this should not be closed... or we should open a new one

**Comment by jwarkentin** [comment]
Just ran into this same problem. This is a big issue. I have to disable the repository for now as it's unusable and breaks my update process.

**Comment by MarshallOfSound** [comment]
Just a question here guys, still chasing this up but have you all followed the instructions and installed the public key as specified in the docs.

```bash
wget -qO - https://gpmdp.xyz/bintray-public.key.asc | sudo apt-key add -
```

**Comment by sebastienserre** [comment]
Yes I have... and still the same problem.

**Comment by jwarkentin** [comment]
Yes, I tried that several times yesterday. The key is definitely added.

**Comment by jasmines** [comment]
Why so much time to solve this issue? You're not the only one to use bintray...

**Comment by MarshallOfSound** [comment]
@jasmines Small things called work and uni sometimes consume time 😆

**Comment by dlakomski** [comment]
Same here.

**Comment by luislobo** [comment]
A workaround is adding '[trusted=yes]' to the apt source, so, instead of:
```
echo "deb https://dl.bintray.com/marshallofsound/deb debian main" | sudo tee -a /etc/apt/sources.list.d/gpmdp.list
```
you could do:
```
echo [trusted=yes] "deb https://dl.bintray.com/marshallofsound/deb debian main" | sudo tee -a /etc/apt/sources.list.d/gpmdp.list
```
BTW, @sebastienserre  the Install docs are here:
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/docs/Installation_On_Debian.md

@MarshallOfSound These other guys had the same issue and here's some reference on how to solve it: https://github.com/ponylang/ponyc/issues/1433

**Comment by sebastienserre** [comment]
@luislobo 
`echo [trusted=yes] "deb https://dl.bintray.com/marshallofsound/deb debian main" | sudo tee -a /etc/apt/sources.list.d/gpmdp.list`
give me a " unknown type [trusted=yes]  on line1 in the sources list " in  /etc/apt/sources.list.d/gpmdp.list"

**Comment by jasmines** [comment]
echo "deb  [trusted=yes] https://dl.bintray.com/marshallofsound/deb debian main" | sudo tee -a /etc/apt/sources.list.d/gpmdp.list

is the right syntax

but it should be the maintener to sign! He is not working on it since march... I prefer uninstall and wait for the official client...

**Comment by luislobo** [comment]
@jasmines thanks for the clarification, I just pasted it in the wrong place. About your comment, as any open source platform/software, it is AS IS, and the author has no obligation to do anything, specially since it's for free. Also, I don't think Google will make an 'official' desktop version for Linux

**Comment by G4Zz0L1** [comment]
Indeed. And I'll add that is the only client that works fine among the other that I've tried, without lacking any major function.

**Comment by MarshallOfSound** [comment]
For everyone watching this thread, I don't think I can retroactively fix this.  I uploaded a GPG key **ages** ago but after the last release.  I think it only signs new releases not old ones.  So when the next release goes out this should be fixed, until then I don't think I can tell bintray to sign old releases.

> but it should be the maintener to sign! He is not working on it since march...

If it makes you feel better I'll quote you and say **I have been actively following this up with bintray support and linux users in my community** just because I haven't been posting updates doesn't mean I haven't been chipping away at this over time and as @luislobo nicely said

> the author has no obligation to do anything

😄 

I'll try find a way to tell bintray to sign old releases but I don't think it can be done
