### ISSUE TITLE
Micro-stutters on macOS (10.12.3)

### ISSUE THREAD

**Issue by kennethmac2000** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2309]
Hi there,

I'm experiencing an issue which seems a little similar to issue #150.

For comparison, playback in the macOS Spotify client is flawless, but playback in GPMDP has intermittent but very obvious periods of micro-stuttering.

This is including in the latest version (v4.2.0).

**Comment by MarshallOfSound** [comment]
This is almost certainly some kind of HW acceleration decoding issue that will be fixed in the next Chromium bump.  Sorry for the issue for now but nothing I can do to fix until the next Chromium bump

**Comment by kennethmac2000** [comment]
Hey @MarshallOfSound,

This issue persists today, running the latest version of GPMDP on macOS 10.12.5. It is not present in the Chrome browser.

Any ideas?

**Comment by AndrewStobie** [comment]
@MarshallOfSound I am just reporting still experiencing this issue.

**Comment by kennethmac2000** [comment]
@MarshallOfSound I don't understand why playback is not choppy in the Chrome browser, only in GPMDP. Do you?

As you might understand, I am not going to force myself to suffer through stuttering music, so GPMDP is basically useless for me currently, regardless of whatever other cool features it has.

Should we not at least re-open this issue to track it until it is fixed, even if it's an upstream issue?

**Comment by MarshallOfSound** [comment]
> Should we not at least re-open this issue to track it until it is fixed, even if it's an upstream issue?

No, the upstream issue is fixed, we just can't update the internal Electron version at the moment due to other bugs

**Comment by AndrewStobie** [comment]
So what is the fix and what has to be done to get it to not be choppy?
