### ISSUE TITLE
Can't unhide auto-hiding taskbar in Windows when maximized

### ISSUE THREAD

**Issue by Koveryl** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#231]
I can't access my auto-hiding taskbar when this app is maximized. Right now I either have to un-maximize it or minimize it to access it. Inconvenient, and definitely a bug

**Comment by MarshallOfSound** [comment]
Can you please raise this issue against https://github.com/atom/electron/ as it is almost certainly a bug with the framework not my implementation.

Just use this app as an example and explain REALLY clearly
