### ISSUE TITLE
FEATURE REQUEST: Disable Desktop Overlay

### ISSUE THREAD

**Issue by Burningo** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2311]
**OS:**
Windows 10 Home

**Issue Descriptions:**
Could you enable a way in settings to disable desktop overlay for Google Play music? Like, have a setting where we can disable it. That'd be amazing. 

**Steps to Reproduce:**
Use media keys, raise or lower volume while using windows 10.

![desktop overlay](https://cloud.githubusercontent.com/assets/26387790/23864781/996113e8-07e1-11e7-9a04-66f2abd5d163.png)

**Comment by jostrander** [comment]
Literally just released this in 4.2.0. Check the settings for Disable windows media service integration.
