### ISSUE TITLE
Theme is not applied to Subscribe button in sidebar

### ISSUE THREAD

**Issue by karlding** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2312]
**OS:** macOS

**Issue Descriptions:** When using a Google Play Music account that doesn't have a GPM subscription, the Subscribe button in the sidebar does not take on the highlight colours. I'm not sure if this is intentional, but it feels like this should also change colour.

**Steps to Reproduce:**

1. Select a highlight colour
1. Log into an account without a GPM subscription
1. Press the menu icon
1. Notice the Subscribe button does not change colour. Hovering (when using a dark theme) makes the button almost invisible.

![screen shot 2017-03-13 at 4 29 12 pm](https://cloud.githubusercontent.com/assets/6836385/23884836/972a45fe-0845-11e7-8c9d-cd6bccb66724.png)
![screen shot 2017-03-13 at 4 29 27 pm](https://cloud.githubusercontent.com/assets/6836385/23884839/9b388a3e-0845-11e7-9492-8de34fda1b8c.png)

**Comment by MarshallOfSound** [comment]
Please raise on the theming library `gmusic-theme.js` 👍
