### ISSUE TITLE
Enable MacOS Scripting Bridge

### ISSUE THREAD

**Issue by Phylu** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2314]
**OS:**
macOS 10.12.3

**Issue Descriptions:**
I use the SIP application Telephone which can turn off music players whenever there is an incoming call. This works for iTunes and Spotify but not for the Google Play Music Desktop Player.
According to the Telephone developers this works by using the macOS Scripting Bridge that allows the sandboxed applications to talk to each other. Compare the output of the following commands which show the scripting bridge exports:
`sdef /Applications/iTunes.app`
`sdef /Applications/Google\ Play\ Music\ Desktop\ Player.app`

Is there any way to add the functionality for external programs to pause the music?

**Comment by MarshallOfSound** [comment]
@Phylu External applications can control GPMDP through the cross-platform PlaybackAPI.

I looked into the scripting bridge a while ago as AFAIC it will require a native module to be written in order to provide the native hooks required.

I will not spend time doing this but others are more than welcome to contribute.  Tentatively leaving open so other can find 👍

**Comment by jostrander** [comment]
Out of curiosity, ( I don't own a mac ), can you post the results of those two commands @Phylu?

**Comment by Phylu** [comment]
Here are the outputs:
[GPMDP.txt](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/842148/GPMDP.txt)
[iTunes.txt](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/842149/iTunes.txt)

**Comment by eofster** [comment]
Is it possible also to control the playback using the PlaybackAPI? The documentation mentions only getting the status:

> Google Play Music Desktop Player provides an interface for external applications to determine the currently played song and playback status.

**Comment by jostrander** [comment]
The WebSocket API allows for status and control. The JSON file is one way, as in it only outputs current info to a json file.

**Comment by eofster** [comment]
And that native module that @MarshallOfSound mentioned, how big should it be?

**Comment by jostrander** [comment]
That's really an arbitrary question. It's going to have to be as big as it needs to be to encapsulate the functionality required to work with apple's ScriptingBridge interface.

**Comment by eofster** [comment]
What exactly would you need from it? On one side it would know how to use Scripting Bridge. On the other side it would provide some Swift or Objective-C API. Is this Swift or Objective-C API what you need and could use?

**Comment by jostrander** [comment]
I think that's what is needed, to an extent. The native module would only need to provide the bridge between the internal GPM API for methods and properties, and the ScriptingBridge. From what I can tell the ScriptingBridge would need to allow track information, state of music, and the app. It would be up to other developers to utilize that bridge. I'm not sure what would be needed in order for the VoIP application mentioned by @Phylu to automatically pause music.

**Comment by eofster** [comment]
I’m the author of that [VoIP app](https://www.64characters.com/telephone/) and what is needed is a property like `isPlaying` and two methods like `play()` and `pause()` exposed via Scripting Bridge with so-called access groups. That’s how the VoIP app, being sandboxed, communicates with iTunes and Spotify apps.

**Comment by jostrander** [comment]
I see what you're asking now. We'd need the module work with NodeJS. So the module would need to be in C++, and your bridge would probably be in Swift/Objective-C. Somehow you'd have to glue the communication together between them. The C++ would be what communicates directly with NodeJS, and in Javascript we'd populate the properties and set callbacks for the methods.

**Comment by MarshallOfSound** [comment]
@eofster I have zero clue how to use the scripting bridge and little interest / investment in figuring it out right now 😆 

This is up for grabs if anyone wants to try it, I can coach you through getting a GPMDP development environment up or an Electron environment if that's what needed 👍

**Comment by jostrander** [comment]
Closing as a unique/stale feature. It doesn't appear there is a significant interest in this at this time.
