### ISSUE TITLE
notifications aren't working on macOS

### ISSUE THREAD

**Issue by squareclouds** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2319]
OS: macOS Sierra 10.12.3

-notifications at song change aren't showing/triggering

-either let the player play a list or changing songs with hotkeys, neither of those works.
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/844504/debug_info.zip)

**Comment by MarshallOfSound** [comment]
You have to enable the notifications inside GPM's settings 👍

**Comment by squareclouds** [comment]
wow, that got closed really fast. i obviously have tried this, could you pls at least tell me where they are? no success finding them

**Comment by MarshallOfSound** [comment]
They are in the Google Play Music Settings.  Not in the apps Desktop Settings 👍
