### ISSUE TITLE
Separate location on screen for mini player

### ISSUE THREAD

**Issue by FISHunderscore** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#232]
I noticed that in 3.0.0, the mini player now takes the place of the main window. This is annoying for users like myself who always have the mini player open on their secondary monitor, and want to be able to change what's playing without having to drag around windows.

If there is a way with Electron to make the mini player and main window store their locations separately, that would be awesome.

**Comment by MarshallOfSound** [comment]
Should be able to do that

**Comment by Maeldor** [comment]
+1

Can you also ensure it goes back to its previous size, please? I am having to resize it every time.

Thanks :)

**Comment by FISHunderscore** [comment]
@jacobmischka I just meant store their locations separately. However, the ability to have two independent ones could be a good toggle setting.

**Comment by MarshallOfSound** [comment]
@FISHunderscore two independent ones is a major task, two locations is much easier :+1:

**Comment by Kun2210** [comment]
+1 
Having two locations would be more than good :+1:

**Comment by MarshallOfSound** [comment]
Lol this was merged 5 days ago #closing
