### ISSUE TITLE
Feature Request: Output notification when playing song changed

### ISSUE THREAD

**Issue by rnitame** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2330]
such as iTunes...
https://wayohoo.net/images/2015/how-to-hide-the-notification-of-itunes4.jpg

**Comment by MarshallOfSound** [comment]
This is a thing already.

Just enable it in GPM settings

**Comment by rnitame** [comment]
@MarshallOfSound I've discovered the setting... X(
Thanks for reply!
