### ISSUE TITLE
Using media keys on XPS 15 9550

### ISSUE THREAD

**Issue by Tmarqu96** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2331]
**OS: Windows 10 x64

**Issue Descriptions: When playing tracks and trying to skip tracks or go back to a track using the media keys the application freezes and crashes and ceases to be operable. Once the app crashes it is unresponsive until a restart is done.

**Steps to Reproduce: play song, hit pause media key, use previous track media key, then hit play media key, Crash should have happened by now

**Comment by MarshallOfSound** [comment]
Disable desktop notifications and the windows media service.  One of them will be causing this 👍
