### ISSUE TITLE
Casting to a group does not work as expected

### ISSUE THREAD

**Issue by brendanheyu** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2333]
Howdy!

Love your work - I use this on every machine I own, and suggest it to all my fellow google addicts. :)

This bug: When I cast to my "Whole house" group (3x Chromecast Audio + 1x Google Home) it seems to connect only to one Chromecast ("Man Cave Chromecast A") - audio only emits from that Chromecast. However - all the other Chromecasts in the group seem to stop what they are doing (go silent), but don't emit any music...

I'm using GPMDP 4.2.0 on Windows 10.

I'm happy to list all device names and firmware versions of the Chromecasts if that will help.

Thanks again!

**Comment by MarshallOfSound** [comment]
See https://github.com/GPMDP/electron-chromecast/issues/8

**Comment by brendanheyu** [comment]
Ok - thanks for that. Sorry for the dupe!
