### ISSUE TITLE
Request: Transparent miniplayer (until you hover over it)

### ISSUE THREAD

**Issue by Koveryl** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#234]
It'd be nice if the miniplayer went transparent when not being used, then when you mouse over it it fully restores. It'd be nice as an option at least

**Comment by MarshallOfSound** [comment]
See here as to the strange limitiations of transparent windows

https://github.com/atom/electron/blob/master/docs/api/frameless-window.md#limitations
