### ISSUE TITLE
Inline search results not visible in dark mode

### ISSUE THREAD

**Issue by wwselleck** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2341]
**OS:**
macOS 10.11.6
GPMDP 4.2

**Issue Descriptions:**
When using dark mode, the inline search results (the ones that pop up while you type, apologies if using the wrong terminology) are not visible since the font is black.

**Steps to Reproduce:**
Use dark mode
Type something into the search bar

**Comment by MarshallOfSound** [comment]
Fixed in master, please check closed issues before raising new ones :+1:

**Comment by wwselleck** [comment]
Well don't I just look foolish. thanks!
