### ISSUE TITLE
Feature Request: Voice commands through Cortana

### ISSUE THREAD

**Issue by thenning** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2345]
I like the idea of how your voice commands work. Is there any way you can also implement those into Cortana so I can control it through there? I can't seem to get the voice working using the Enable Voice setting.

**Comment by MarshallOfSound** [comment]
The cortana skills kit is not available to everyone yet and it will require a lot of time investment for one specific platform.  When the skills kit becomes stable this may be revisited.

**Comment by saerynk** [comment]
I know this is closed...but Cortana commands work fine for pause, skip, previous and resume, and she can still control volume.  She just can't rate songs or play specific things, she's a decent remote control though.

**Comment by thenning** [comment]
Thanks. I think when I first tested it, trying to skip tracks seemed to stop playback.

**Comment by ShubhamPriyadarshi** [comment]
An integration would be awesome, I think it's possible.

**Comment by ShubhamPriyadarshi** [comment]
Please reconsider this.
