### ISSUE TITLE
Scroll with touchpad is Excessively responsive.

### ISSUE THREAD

**Issue by lorenzofollador** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2348]
**OS:**
Windows 10 Single Language
pc: Lenovo Ideapad 300
**Issue Descriptions:**
Double-finger touchpad scroll is too fast; changes with touchpad software are not effective; regular mouse scrollwheel works fine.
**Steps to Reproduce:**
Use two fingers to scroll the UI. UI scrolls uncontrollably fast.

DISCLAIMER: new to GitHub, please be kind.

**Comment by MarshallOfSound** [comment]
This sounds like a hardware thing, if your scroll wheel works fine but your trackpad scrolls to fast.  Just adjust the scroll speed on your track pad?

Regardless if it works for one and not the other no matter what i do it will never be the same for both :+1:

**Comment by lorenzofollador** [comment]
Thanks for the feedback. As an additional info, the issue happens with spotify too!

**Comment by lorenzofollador** [comment]
**UPDATE**
Found some fix in the Spotify forum. Documenting it here for people who may have the same problem:

*Open regedit.exe using run*
*Go to HKEY_CURRENT_USER -> SOFTWARE -> Elantech -> Smartpad*
*Change ScrollControl_Mode from 0 to 1*
*Open the elan software and click apply just to make sure the settings get applied*

*Source:*
*https://www.reddit.com/r/techsupport/comments/3lhmhq/win10_elan_touchpad_scrolling_issues/*

Source:
https://community.spotify.com/t5/Ongoing-Issues/Touchpad-scrolling-too-fast/idi-p/1301995#comment-on-this

**Comment by Shapovalov-Dmitry** [comment]
@lorenzofollador Thank you so much!!!! Fixed for me for lenovo ideapad 330.
