### ISSUE TITLE
Uncaught Exception: The request timed out.: (null)

### ISSUE THREAD

**Issue by brandonio** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#235]
An uncaught exception was reported.  
#### Info:
**OS:** darwin
**Arch:** x64
**GPMDP Version:** 3.0.0
**Time:** Sat Mar 05 2016 21:21:29 GMT-0800 (PST)

#### Error:
*The request timed out.: (null)*
```js
Error: The request timed out.: (null)
    at Error (native)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
Closing as caught exception appears to be a result of a dodgy internet connection
