### ISSUE TITLE
Uploaded music doesn't play in the player.

### ISSUE THREAD

**Issue by Garce78** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2350]
**OS:** Windows 10 Pro (x64)

**Issue Descriptions:** Music that has been uploaded to Google Play stalls (infinite loading) when attempting to play. If a non-uploaded song is available in the same song list, the player will eventually timeout and queue up the non-uploaded song.

**Steps to Reproduce:**
1. Upload a song to Google Play Music
2. Create a playlist with a native Google Play Music song and your uploaded song
3. Attempt to play your uploaded song
4. Observe that the song never loads
5. After a few minutes the player will skip the song and move on to the native GPM song.

**Comment by jostrander** [comment]
I have quite a few songs in my library that I uploaded and I don't have this issue.

**Comment by benmeroff** [comment]
I also upload my own music periodically but haven't run into this myself; do you upload your music via Chrome's Google Play Music extension through the website, or through their Music Manager?

**Comment by Garce78** [comment]
I've uploaded these songs prior using Chrome's GPM extension through the website. I'm not experiencing this issue on my Macbook. I'll attempt some other debugging steps as soon as I'm able to and report back. It was just a consistently reproducible issue on my main desktop, so I thought I'd file it.

**Comment by Garce78** [comment]
Okay, so I guess something was funky with the call being made (for whatever reason). I quit the app and restarted it and now all music is playable. Closing this issue as it appears to have been a heisenbug.

**Comment by Garce78** [comment]
Thanks for taking a look at the issue, @benmeroff and @jostrander. d('-'d)
