### ISSUE TITLE
Support custom genres in New Releases section

### ISSUE THREAD

**Issue by paulgendek** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2351]
The "New releases" sections used to have many genres available:
![image](https://cloud.githubusercontent.com/assets/644778/24200005/04219994-0ee2-11e7-990f-bb674ecf0391.png)

Now it looks like this:
![image](https://cloud.githubusercontent.com/assets/644778/24200038/175552a8-0ee2-11e7-8949-a21204853f58.png)

It would be a great enhancement to be able to inject custom genres into the list, or to add shortcuts to the sidebar. 

For example, the direct URL for Soundtracks still works: https://play.google.com/music/listen?authuser&u=0#/wnr/SOUNDTRACKS_CAST_ALBUMS

Thanks!

**Comment by jostrander** [comment]
This is interesting as I've recently realized that they had shortened the list. Do you have links to all of the previous genres that are now missing?

**Comment by paulgendek** [comment]
You can take the alias from the actual Store URLs:
https://play.google.com/store/music/category/METAL

Then append them to the Play app URL: 
https://play.google.com/music/listen?authuser&u=0#/wnr/METAL

The "wnr" in the URL is for New Releases; you can replace it with "wtc" for Top Charts:
https://play.google.com/music/listen?authuser&u=0#/wtc/METAL

**Comment by MarshallOfSound** [comment]
I have no doubt that if this front end change becomes permanent then a backend change will follow shortly to make the links you mention stop working.  Not sure if this is something we should take on given it's potential to break being outside our control.

If you can make something like this opt-in, and be safe from future UI / backend changes I'd accept a PR for it but I won't work on it myself 👍

**Comment by paulgendek** [comment]
If the feature is to add a custom links to the sidebar, that are validated to be anything within the play.google.com/music domain, then it would be fairly future-proof. 

That way, I can add my custom genre links, and other users could add whichever shortcuts they want (directly to an album, etc).

**Comment by MarshallOfSound** [comment]
@paulgendek I'm just concerned about future 404's breaking the GPM nav flow 👍

**Comment by paulgendek** [comment]
Since it's just a URL route, it doesn't 404. It just gives an error message that it couldn't retrieve the results.
https://play.google.com/music/listen?authuser&u=0#/wnr/ASDF

**Comment by jostrander** [comment]
I looked into this recently, having a hard time pin pointing where to inject the menu items via selector as I can't get chrome inspector to hit the menu when its open. Maybe we can just add our own extended menu here instead.

**Comment by paulgendek** [comment]
@jostrander it's the very last element on the page, before the end body tag:
![image](https://cloud.githubusercontent.com/assets/644778/24588604/6cd3c830-1799-11e7-8101-0c5730785881.png)

**Comment by MarshallOfSound** [comment]
That menu element is reused for all menus and it is only a container for this menu when it is open

**Comment by MarshallOfSound** [comment]
@paulgendek As predicted this change has now hit the back end and the links you supplied such as

https://play.google.com/music/listen?authuser&u=0#/wnr/SOUNDTRACKS_CAST_ALBUMS

no longer work and redirect to the standard "#/wnr"
