### ISSUE TITLE
Dark Mode - Search query text not visible in search results

### ISSUE THREAD

**Issue by benmeroff** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2354]
I'm currently using GPMDP 4.2.0 on macOS 10.12.3, and when Dark Mode is enabled search query text remains the default dark grey color and is therefore not visible; I tried switching back to Light Mode and back to Dark Mode, quitting and reopening GPDMP, and even uninstalling/reinstalling the app, but the issue seems to persist no matter what.

Here is what I'm referring to, the other unhighlighted results should show the search query on the first line:

![screen shot 2017-03-22 at 1 03 46 pm](https://cloud.githubusercontent.com/assets/13946393/24213538/c8f8d494-0f00-11e7-9b13-c44f7014c3f4.png)

**Comment by benmeroff** [comment]
After looking in Google Play Music, it appears this text answers to the CSS classes `style-scope sj-entity-suggestion`, but when I tried making a custom stylesheet to change the color for either of those classes and loaded it into GPMDP it didn't seem to take, so there seems be more at play than my limited CSS knowledge can grasp...

**Comment by MarshallOfSound** [comment]
See #2341
