### ISSUE TITLE
Bug with latest ver.

### ISSUE THREAD

**Issue by SuperLucho** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2358]
**OS:**
Windows 10 Home 64-bit
**Issue Descriptions:**
Hello the latest version freezes every time it starts playing  music. I was wondering if there was a way to install an earlier version.
**Steps to Reproduce:**
I tried completely uninstalling it, using iobitunistaller and removing all the residual files and rebooting the PC before reinstalling it, but still have the same problem.

**Comment by MarshallOfSound** [comment]
Disable desktop notifications in GPM settings 👍
