### ISSUE TITLE
Enhancement request: add to playlist in mini player

### ISSUE THREAD

**Issue by exenza** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2360]
**OS:** n/a

**Issue Descriptions:** is not possible to add a song to playlist from miniplayer

**Steps to Reproduce:**

If you listen to a radio or google mood playlists the miniplayer offer thumbs up and down, buttons to skip track and play/pause button but there is no way to add the song which is playing in a playlist.

I would love to have the "more option" icon (the three dots) available as well while in mini player to easily add playing song to any of my playlists. 

I understand the challenge may be the size of the mini player window not allowing to show the "more option" menu content but would be great if you find a way to have the option available despite that, maybe by make the options in the "more option" dialogue scrollable or have a second window manage the menu

**Comment by MarshallOfSound** [comment]
Discussed before, kind of not possible 😢 

See #701 for generic mini player enhancements 👍
