### ISSUE TITLE
Feature Request: Add a Recents button to the side menu.

### ISSUE THREAD

**Issue by kfrankic** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2361]
**OS:** Windows

**Issue Descriptions:** 'Recents' should be listed as an option between 'Home' and 'Top charts' within the side menu mirroring how it is displayed in the Google Play Android app.

**Steps to Reproduce:** Open the side menu and notice that 'Recents' is not listed.

**Comment by jostrander** [comment]
https://play.google.com/music/listen?u=1#/recents
