### ISSUE TITLE
Feature request: Universal App for Windows 10?

### ISSUE THREAD

**Issue by magic4got10** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2367]
Any chances to get this wonderful client on my Lumia too?
I love it on my Surface (almost perfect, there's only a strange behavior of the mini player in tablet mode), but on Windows 10 Mobile phones GPMDP would become the ONLY ONE app in the store to let us use Play Music.
It would be awesome!

**Comment by MarshallOfSound** [comment]
@magic4got10 This is not possible, it's a limitation of the bridge we use to put GPMDP into the Windows Store.  It requires project centennial which is only available on Windows 10

**Comment by magic4got10** [comment]
Thanks for the reply, even if honestly I'm not expert about these things and I didn't get the exact problem. Do you mean that for having a client on Windows 10 Mobile you would need to write it all again?

**Comment by jostrander** [comment]
It's really not even possible. This just uses the the web player, which is
not mobile friendly at all, and its not a UWP app which is what's required
for mobile as far as I know.

**Comment by magic4got10** [comment]
Why are you not using Project Centennial (aka Bridge)? I read it offers a lot of advantages and easy tools for devs to gradually integrate it in the OS.

**Comment by MarshallOfSound** [comment]
@magic4got10 We are using project centennial, please stop the issue spam

**Comment by magic4got10** [comment]
![immagine](https://cloud.githubusercontent.com/assets/23573130/26024988/87d8d124-37de-11e7-8e27-d02b4f34f92c.jpg)
This line said the opposite... Anyway, the purpose of Centennial is just to gradually integrate desktop applications like yours in the OS. Implementing back button (as I asked in the other post) or scaling or some other small things should not be "impossible". Obviously if you don't have enough resources or will for it, it's a different matter.
It's a suggestion, not a spam.

**Comment by MarshallOfSound** [comment]
@magic4got10 I believe you fundamentally misunderstand Project Centennial, it is used to bridge win32 applications into a sandboxed UWP environment, it does not convert win32 apps into UWP apps and it definitely doesn't allow you to run win32 apps on a windows phone which is what that quote is referencing.  Bridged apps still only run on Windows 10 for desktop.

And for what it's worth, branching out into other issues asking the same question as your original issue is the definition of spam....

**Comment by magic4got10** [comment]
Well yes, Centennial is just a bridge, but MS' purpose (or hope) is to persuade devs in converting their applications in UWP once they get in the store (and yes, I know it means to re-write it). I can understand you are not interested in UWP for W10 Mobile (since it's declining), but UWP means also Xbox, for example, and a music-streaming service like yours would be interesting on it.
I'm sorry you have no will do it now, but I hope you'll change your mind if your app succeeds in the Store!

**Comment by MarshallOfSound** [comment]
> I'm sorry you have no will do it now, but I hope you'll change your mind if your app succeeds in the Store!

You clearly aren't listening to me, I have repeatedly said it isn't lack of will, it's not possible to convert this app to UWP (a complete rewrite).  The app is based on the Electron framework, which is based on Chromium **which is win32**.

**Comment by jostrander** [comment]
Not to mention this just wraps the Google Play Music WEB UI which is not mobile ready and wouldn't scale to other devices besides desktop. It barely works on a tablet screen with how non-responsive the page is. This is literally not feasible. It's not lack of will, or for lack of trying, its been tried, it won't work. Even with a rewrite. Sorry.

**Comment by chuckfecht** [comment]
I think it would be a good idea to get this app into the store even if just using the Centennial Bridge and enabling some modern things (Like Media controls) by default. It would require no work to just get it into the store (I've already converted the App with the Desktop App Converter found in the store), and the immediate benefits are Discoverability of the app, easy installation/uninstallation, and the ability for people to run the app on Windows 10 S and in Windows Mixed Reality.

**Comment by 42xX** [comment]
Hi, 

It's already in the store under GPDMP.


________________________________

**Comment by Arlodotexe** [comment]
Oh, wow! I've looked for it but hadn't been able to find it. Maybe it would be a good idea to put the link on the Website.
