### ISSUE TITLE
GPMD freezes with Wallpaper Engine

### ISSUE THREAD

**Issue by blittzzo** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2373]
**OS:**
Windows 10

**Issue Descriptions:**
App completely freezes when opened while Wallpaper Engine is open. Music still plays. It unfreezes sometimes but usually stays frozen till closed via task manager.

**Steps to Reproduce:**
Open Wallpaper Engine with wallpaper applied. Then open GPMD and play a song. A couple seconds into the song and the entire app will freeze. Can only be closed by task manager.

**Comment by jostrander** [comment]
This sounds like an issue with windows 10 notifications that currently isn't capable of being fixed on our side. Try disabling desktop notifications in GPM settings.

**Comment by fraserhaer** [comment]
I use the music player and the wallpaper engine and haven't had any problems.

I also coincidentally have notifications turned off - so that very well could be it.

**Comment by Dryness** [comment]
Disabling desktop notifications did the trick for me - no more GPMDP freezing with an active wallpaper engine.

**Comment by blittzzo** [comment]
Looks like desktop notifications was the problem. I don't know how to close this but thanks for the help!
