### ISSUE TITLE
Dark theme search bar issue

### ISSUE THREAD

**Issue by dkleind** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2375]
**OS:** Mac OS 10.12.3

**Issue Descriptions:** When using the custom dark theme, search results for album names and artists are black until I hover over them. This bug is not present in the light theme (see screenshots).

**Steps to Reproduce:** Activate dark theme in preferences, then start typing using the search bar.

Screenshot 1: typing "The Beatles" in the search bar

<img width="798" alt="screen shot 2017-03-25 at 8 11 36 pm" src="https://cloud.githubusercontent.com/assets/6954342/24328171/f08c2fb2-1197-11e7-9449-a3f48748c309.png">

Screenshot 2: hover over the first search result

<img width="802" alt="screen shot 2017-03-25 at 8 13 55 pm" src="https://cloud.githubusercontent.com/assets/6954342/24328175/f736abd0-1197-11e7-829e-f77d4cac3bde.png">

This bug is not present in the light theme, see below:

<img width="799" alt="screen shot 2017-03-25 at 8 18 20 pm" src="https://cloud.githubusercontent.com/assets/6954342/24328204/4361e556-1198-11e7-862a-f94cc391e6e9.png">

**Comment by MarshallOfSound** [comment]
Duplicate #2354 #2341

Please check closed issues before raising new ones 👍

**Comment by dkleind** [comment]
Whoops, didn't see those! Thank you 👍
