### ISSUE TITLE
Full screen not working (OSX)

### ISSUE THREAD

**Issue by maharshmellow** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#238]
The maximize button works like expected but for some reason View --> Toggle Full Screen doesn't seem to do anything. Am I missing something or is this a feature that still needs to be added? Other than this, AMAZING APP! :smiley:

**Comment by MarshallOfSound** [comment]
Heh heh,

Who wrote that line of code :smile: 
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/main/configureBrowser.js#L20

Totally wasn't me :+1: 

Fix incoming

**Comment by MarshallOfSound** [comment]
Fixed
