### ISSUE TITLE
Speaker fill does not work with desktop app

### ISSUE THREAD

**Issue by sergesyrota** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2380]
**OS:** Windows 10

**Issue Descriptions:** Speaker fill on 5.1 system does not work, and only front L/R speakers are playing, while all others are silent.

**Steps to Reproduce:** Press Play. Disconnect front left/right speakers from amp. Ta da!

**Workaround:** Create a shortcut to "Google Play Music Desktop Player.exe" with "--try-supported-channel-layouts" flag. Ta da!

Unfortunately workaround does not work with the default shortcut to "Update.exe"

Would be nice to get this to work out of the box, or have this as a setting in the app itself.

**Comment by MarshallOfSound** [comment]
@duplicate-issue-bot[bot] Heh, those are a bit off the mark 😆 

@sergesyrota I would accept a PR to add an option to the "Audio" settings tab to append this launch flag at startup.

`--try-supported-channel-layouts`

Would be a simple `Settings.get` call inside this file https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/main/configureApp.js 👍

**Comment by sergesyrota** [comment]
@MarshallOfSound, I'll try this out, and if it works, will submit a PR.

**Comment by sergesyrota** [comment]
After an hour trying (first time with nodejs), can't get the build to work. I'll get back to this some time in the future when I have more time, but if anyone else can try it, please do :)

**Comment by MarshallOfSound** [comment]
@sergesyrota If you need help getting the build going feel free to ask in Gitter.

A good starting point is https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/Development-FAQ

**Comment by MarshallOfSound** [comment]
Fixed in #2715
