### ISSUE TITLE
BUG: Interface freeze when using Voicemeeter Banana/Virtual sound device 

### ISSUE THREAD

**Issue by azmodii** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2382]
**OS:**

Windows 10 Pro
Version 1607
Build 14393.953

**Issue Descriptions:**

When a virtual audio device (in particular, Voicemeeter Banana's virtual input) is selected as the default audio device, the application interface will freeze upon playing any music. This is regardless of which audio device is selected within the "Desktop Settings".

Music continues to play and cycle through the playlist. Interface remains frozen, application does not respond to media key input.

**Steps to Reproduce:**

Set default audio device to a virtual device. Open google play music and attempt to play any music.

NB: This issue was not present in the previous versions.
NB: Could not attach debug_info, git says "We don't support that file type" even though it clearly says .zip

**Comment by jostrander** [comment]
Try disabling desktop notifications and see if that fixes your issue.

**Comment by azmodii** [comment]
That solved it! Thanks @jostrander

**Comment by MarshallOfSound** [comment]
Weow @duplicate-issue-bot[bot] ... Miles off 😕 

I think I put the wrong numbers in 😆
