### ISSUE TITLE
'Notify current track' does not work

### ISSUE THREAD

**Issue by AlexiG42** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2383]
I am using GPMDP on Windows 8, and the 'Notify current track' keyboard shortcut does nothing for me. I have tried binding it to both Ctrl+Down and Ctrl+Alt+Shift+D. Normal track notifications (when a new track starts) still work. 

I have attached the debug files - the zipped folder wouldn't upload (it said it was the wrong type), so I had to upload the individual files as .txt files.

[gpmdp.txt](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/874341/gpmdp.txt)
[install.txt](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/874342/install.txt)
[settings.txt](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/874343/settings.txt)
[SquirrelSetup.txt](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/874344/SquirrelSetup.txt)

**Comment by meffect** [comment]
for the love of god, what does "notify current track" mean?! seriously I'm raging that you have such ambiguous function, no tooltip, not in the faq, not self descriptive, not self revealing. I spent 10 minutes making a macro to trigger it, only to find out i still dont know what the hell it does

**Comment by jostrander** [comment]
It sends a desktop notification of the current track that's playing in case you missed it...

**Comment by Lumpenstein** [comment]
Sorry for writing in an old Thread, but I'm on windows 7 still and would like to get notifications too, can You implement the Windows  TrayBallon Api ?

**Comment by SolarLiner** [comment]
There should normally be some DIY notifications popping up for Windows 7 and below.

**Comment by Lumpenstein** [comment]
Not sure what you mean by DIY notifications, but I have notification tooltips allowed for the player and still there is nothing popping up. :/
