### ISSUE TITLE
Feature Request: Equalizer (.DEB x64)

### ISSUE THREAD

**Issue by jebeld17** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2385]
Feature Request:

I would love to have a simple, easy to use EQ built into the (Unofficial) Google Play Music Desktop Player on my Ubuntu Linux box.
Reason why? There are no efficient EQ options for Ubuntu at this moment, besides a few apps that have long since been abandoned.

**Comment by jeremybras** [comment]
+1 would love to have this on OSX

**Comment by MarshallOfSound** [comment]
There is already an audio EQ in the code base, but it doesn't work when combined with other features or with some code that GPM uses.

So it's disabled, you can see it's code here 👍 

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/renderer/windows/GPMWebView/playback/audioEQ.js#L33

When there stops being issues with it, I will reenable it 👍
