### ISSUE TITLE
tmp folder cluttered with album covers

### ISSUE THREAD

**Issue by mgrottenthaler** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2387]
**OS:**
Linux Fedora 24 (64 bit)

**Issue Descriptions:**
The program saves album covers of played songs in the /tmp/ folder. My tmp folder is filled with album covers and it is hard to find any other files. This is especially a problem when listening to radios because every song has a different album cover and after every song a new album cover is saved in tmp. A subfolder should be created to avoid this situation.

**Steps to Reproduce:**
Play a song in google play music desktop player.

**Comment by MarshallOfSound** [comment]
This is where your system will be storing notification images when passed a URL, take it up with whatever WM you're using I guess.  You can replicate this by using any Electron application that creates notifications where the icon is a URL.  If your WM downloads the image to `/tmp` not much I can do to move it 👍
