### ISSUE TITLE
Scrolling too fast with touchpad

### ISSUE THREAD

**Issue by magic4got10** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2388]
Hello! I use a Surface Pro 3 with Surface Type Cover.
Scrolling by using the touchscreen is smooth and comfortable on GPMDP, but scrolling by using the touchpad of the keyboard is like a surgery operation. Too fast and not accurate.

PS: of course I tried to scroll Google Play Music in Edge and it was ok.

**Comment by MarshallOfSound** [comment]
Hey,

Scrolling sensitivity is determined by the OS or Chromium neither of which I can control.  I did find a few scrolling related bugs in Chromium marked as fixed in 57 so I believe you won't experience these issues when Electron goes above that Chromium version 👍 

Fixed upstream 😄
