### ISSUE TITLE
MPRIS "Stop" won't really stop the play queue

### ISSUE THREAD

**Issue by tdemin** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2389]
**OS:** Ubuntu 16.04.2, GNOME 3.18

Okay, we control GPMDP with those beautiful buttons on the screenshot.
![screenshot from 2017-03-28 22-57-56](https://cloud.githubusercontent.com/assets/26599554/24419850/1177a70a-140a-11e7-9e0e-928bd17bd13b.png)
The "Stop" button is meant to stop the playback and to reset the queue position in the playlist. As the queue and the playlist are different things in Google Play Music, "Stop" button should also reset the track position to zero and reset the queue, but at this time it behaves just like "Pause".

**Comment by MarshallOfSound** [comment]
GPM itself doesn't have a concept of stop so we mapped it to the closest thing we could.  If someone wants to submit a PR to change it's behavior somehow I would definitely look at it but for now I don't see this is a bug rather a limit of what GPM can offer.

When a stop button appears in GPM we can wire it up correctly 👍 

/cc @jostrander (for linuxy reasons) 😆
