### ISSUE TITLE
App disconnects from Chromecast Audio regularly

### ISSUE THREAD

**Issue by nikeshamin** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2392]
I am having an issue where I can start a radio playlist and then cast it to my Chromecast Audio. If I leave the computer for a while, it sleeps, and then I come back to the app, I find that, while the Chromecast has continued to play music, the app has disconnected from the Chromecast and I can no long control it. I then have to restart casting to the Chromecast which stops the music from playing and will sometimes give me the 2-location warning. I am attaching the debug info in case that helps. Thanks for the great app.

**OS:**
macOS Sierra 10.12.3
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/880144/debug_info.zip)

**Comment by jostrander** [comment]
Yeah this is a known issue and I'm not sure if there is a fix. Once the connection to the Chromecast is broken I'm not sure there is a way to reconnect it without reinitiating a cast session. Im pretty sure if you do this in chrome it will also break, but I haven't tried it.

**Comment by MarshallOfSound** [comment]
> Once the connection to the Chromecast is broken I'm not sure there is a way to reconnect it without reinitiating a cast session. 

This is correct and I've had this with Chrome / Android apps before as well.  The only way to continue is to create a new Cast session.

**Comment by nikeshamin** [comment]
I did a bit of research and came up with this:

https://developers.google.com/cast/v2/reconnection

This is how most apps restart the connection to the Chromecast device
without interrupting the current playback. I know that it is written up for
Android, but I think that the solution could be implemented on Chrome.
