### ISSUE TITLE
"Upgrade to Family plan" leaves no way to return back to the music app.

### ISSUE THREAD

**Issue by JadesterK** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2394]
This was extremely frustrating, as I was curious and opened the "Upgrade to Family plan" tab, which seemingly just takes you to a integrated browser in the app. This would be fine if it offered something like a back button to return to the music tab, but it doesn't. 

And because I had the load last page visited option on in the desktop options menu, even restarting left me soft locked in the browser page. The only way I managed to get back into the app was going through the system tray and opening the desktop settings from the apps icon there, then turning off the option to return to the last visited page, and restarting the app.

Please add a back button!

**Comment by MarshallOfSound** [comment]
The back button is traditionally in the search bar, on this page there is no search bar so there is no back button.  You can however always use the standard nav shortcuts Alt + Arrow
