### ISSUE TITLE
App skips songs when internet disconnects, instead of staying at same song

### ISSUE THREAD

**Issue by 19007361** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2399]
**OS:** Windows 10

**Issue Descriptions:** When my internet disconnects, the app keeps skipping to the next song to find one that works, instead of waiting for the connection to return.

**Steps to Reproduce:** As described above.

**Comment by 19007361** [comment]
@duplicate-issue-bot not even close :D

**Comment by MarshallOfSound** [comment]
This is a GPM design decision.  Whenever the current song fails to play it automatically skips to the next one to try that out.  We can't change this behavior

**Comment by 19007361** [comment]
I get it, thanks.
