### ISSUE TITLE
Minimize, Maximize, Close buttons popping up on Mini Player

### ISSUE THREAD

**Issue by MTRougeau** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#24]
![miniplayer buttons](https://cloud.githubusercontent.com/assets/15477491/10889903/5c7aa48a-815a-11e5-9e2f-6b4a69a1e834.JPG)
The minimize, maximize, and close window buttons appear in the Mini Player when it is not in focus. This is not happening on 1.60, but on the latest pulled version. Possibly related to Aero Snap or Resizing updates?

**Comment by MarshallOfSound** [comment]
Can you please ensure you have pulled down that latest commits.  I believe this issue was fixed in 21e955920b82e23bc9ed5c4b64bdc11a5905fb21.

**Comment by MTRougeau** [comment]
I just grabbed the latest .zip....is that right? Sorry, kind of new to
github.

**Comment by MarshallOfSound** [comment]
Here, have a getting started guide :cat: 

https://help.github.com/articles/set-up-git/
