### ISSUE TITLE
Settings Window Cuts Off Bottom Two Options in Settings

### ISSUE THREAD

**Issue by the1mann** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#240]
It isn't clear to the user this is a scrollable area, at least on Mac OS.
![screen shot 2016-03-06 at 5 55 07 pm](https://cloud.githubusercontent.com/assets/4213838/13552907/9aaa2fc4-e3c4-11e5-9562-7444974e7ed6.png)

Fix would be to force a scroll bar, or ideally have the default window size show all the available settings.

**Comment by MarshallOfSound** [comment]
Fair enough

**Comment by tf2manu994** [comment]
+1

Same problem in windows, no visible scrollbar, although I do agree that the best solution is to just make the window taller
