### ISSUE TITLE
RM-820 (Remote) media buttons doesn't work with GPMDP

### ISSUE THREAD

**Issue by f1xmAn** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2400]
**OS:**
Windows 10 Pro
**Issue Descriptions:**
GPMDP doesn't react on media keys on remote from **sound blaster x-fi surround 5.1 pro**. Remote model is **RM-820**. Key mappings attached. Another players work well with this remote (I tried Windows Media Player, Groove Music and Spotify (desktop application)).
**Steps to Reproduce:**
1. Connect sound card
2. Open GPMDP
3. Play any music
4. Press play/pause or previous/next buttons

[key-mappings.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/888060/key-mappings.zip)

**Comment by MarshallOfSound** [comment]
This is one of those things where there is nothing we can do about this.  We listen for keyboard events in the "correct" way, if this remote emits the wrong events or doesn't emit them in a standard way we can't handle that.

Try enabling the Windows 10 Media Service and see if that helps 👍

**Comment by f1xmAn** [comment]
Hi! Can you provide a list of events which is listen by the app? I'll see if I can emit them by remote.

**Comment by MarshallOfSound** [comment]
Taken from this list.

https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731(v=vs.85).aspx

We listen to 

* `VK_MEDIA_NEXT_TRACK`
* `VK_MEDIA_PREV_TRACK`
* `VK_MEDIA_PLAY_PAUSE`

And if the media service is enabled we listen to OS level media events

**Comment by f1xmAn** [comment]
Ok, thanks.
