### ISSUE TITLE
New search bar auto-fill on Dark Mode

### ISSUE THREAD

**Issue by matthewnlee** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2401]
When I type into the search bar, the auto-fill results (or whatever we call the lines that pop in below) only show the sub-heading, with the main heading only being visible on mouseover.

<img width="774" alt="screen shot 2017-04-02 at 10 07 45 am" src="https://cloud.githubusercontent.com/assets/24398709/24589255/680ed6bc-178c-11e7-9d5a-204297539bec.png">

**Comment by MarshallOfSound** [comment]
Fixed in master.  Please check closed issues before raising new ones
