### ISSUE TITLE
Windows Store App Taskbar Icon

### ISSUE THREAD

**Issue by PazerOP** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2402]
Hello,

Just a minor request. Is there any possibility that the icons used for the windows store app could be updated to match more closely with the overall theme of windows store apps? When pinned to the taskbar, the icon for GPMDP kinda clashes with other modern UI apps' icons due to the background plate:

![example](http://i.imgur.com/MOEi2sn.png)

**Comment by MarshallOfSound** [comment]
The Windows Store put that background there, I'm like 99% sure it put it there for a reason 😆 

If you want to get rid of the background you can install the non-UWP version 😆

**Comment by PazerOP** [comment]
The windows store did not cause that background to be shown. The problem is that you have provided a plated image where an unplated one was supposed be shown. Check your package.appxmanifest (this is an example from another windows store app):

![example](http://i.imgur.com/X6wrRyI.png)

**Comment by MarshallOfSound** [comment]
@PazerOP I don't know what to tell you mate, I never set that background up, and I definitely don't choose to provide a plated image.  I literally give it the same transparent background icon I give everything else.  What the Centennial converter or the Windows Store does with that icon is entirely up to it.

The manifest and assets are generated on the fly so I haven't set this up specifically

**Comment by zastrowm** [comment]
This does seem to be related to conversion process.  By default, it looks like desktop apps don't have "nice" icons:

> Additionally, if you don’t follow step 4, you don’t get proper support for unplated assets. What does it mean? That your converted app, by default, will apply a background to the icon that is displayed in the taskbar, even if you have set transparent as BackgroundColor in the <uap:VisuaElements> item in the manifest, like in the following sample:
> ...
> With a proper resources file, instead, you’ll be able to get an icon taskbar with a nice transparent background. You can see the difference between the two approaches in the following image (I apologize if they’re a bit blurry, but it’s just to give you an idea of the final effect).
> ![](https://msdnshared.blob.core.windows.net/media/2017/02/standard_icon_thumb.png)
> ![](https://msdnshared.blob.core.windows.net/media/2017/02/unplated_asset_thumb.png)

Sourced from <https://blogs.msdn.microsoft.com/appconsult/2017/02/21/an-easier-way-to-generate-the-packages-for-a-desktop-bridge-converted-app/>, section "Easier generation of the assets"

Not that I have any idea how to fix this, but useful information for anyone that might want to issue a PR to fix this.
