### ISSUE TITLE
Add live tile support in the UWP wrapper

### ISSUE THREAD

**Issue by Cypher1** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2403]
**OS:** Windows 10, Insider Build 15xxx+

**Issue Descriptions:** Live Tile on/off doesn't seem to make a difference, no updates / images or music information.

**Steps to Reproduce:**
- Install GPMDP from MSFT Store.
- Log in and setup
- Turn live tile on
- Play music
- Live tile does not update

I'm not sure if this is a bug or a feature request, I saw a couple of reviews on the MSFT store site requesting the feature so it seems like the current live tile isn't supported at all.
Thanks

**Comment by MarshallOfSound** [comment]
This is a pretty difficult task as it requires some kind of companion executable to manage the live tile and that executable must be spawned and controlled from inside our app.

Pretty tricky to pull off, don't think I'll be attempting it any time soon

**Comment by jostrander** [comment]
The nodeRT libraries have nothing for this?

**Comment by MarshallOfSound** [comment]
Not that I'm aware of, @felixrieseberg got live tiles working in an example app over here, https://github.com/felixrieseberg/electron-uwp-background

You can see the basic structure that is required to make this work, would require some shuffling and maybe even a separate project with this one as a submodule.  Not sure how that would work and don't have the time to really explore it myself.

**Comment by jostrander** [comment]
https://docs.microsoft.com/en-us/uwp/api/windows.ui.notifications

Took a peek at his code, we might be able to use nodeRT for this, if it can import the notifications portion of RT.

**Comment by Cypher1** [comment]
At the least, please disable the live tile, it is misleading to have the UI for enabling/disabling it but if it doesn't mean anything its a bad user experience.

(Love the rest of the App, thanks guys)

**Comment by MarshallOfSound** [comment]
@Cypher1 Can you screenshot where the option is to enable the live tile, I haven't explicitly said GPMDP supports it so idk where it's getting that info from

**Comment by Cypher1** [comment]
![live tile](https://cloud.githubusercontent.com/assets/1120798/24596640/d281174c-1883-11e7-9608-3182ef0a291b.png)

Here you go. Thanks for taking the time to see this through

**Comment by Kytech** [comment]
@Cypher1, that option is standard for any Windows Store App. You can't remove that option since it is built in to the OS. Disabling/Enabling the live tile doesn't do anything if the app doesn't ever update the tile, so it doesn't make a difference if it is enabled or not.

**Comment by MarshallOfSound** [comment]
This actually matches my research @Kytech 

Closing out for now as we can't remove this option 👍 

If / when someone implements live tile support then the option will actually do something 😆
