### ISSUE TITLE
Program UI freezes a couple of seconds after starting the playing of a song

### ISSUE THREAD

**Issue by pyrexed** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2404]
OS: windows 10 (Release previews program enabled)
GPMDP ver: 4.20 (noticed it on 4.1.1 also)

After 3-5 seconds from starting a song, the UI freezes entirely (even the taskbar icon), music continues playing regularly. The UI unfreezes after about 30-60 seconds later (like waiting on asynchronous service to resolve, maybe lyrics but not necessarily).
After each song change (whether automatically on the playlist or selecting another song) the UI freezes again.
Tried complete uninstall and deletion of all related files and reinstalling. same issue.
Tried unchecking all settings with no success either:
![image](https://cloud.githubusercontent.com/assets/23460576/24600616/2db1bff2-185e-11e7-8665-be2e46e404e0.png)

**Comment by MarshallOfSound** [comment]
@pyrexed Disable desktop notifications in GPM settings and try again 👍

**Comment by pyrexed** [comment]
Yeah that works, Thanks!
This should go into the FAQ

**Comment by calebmeyer** [comment]
This also happened for me. Glad the fix was easy, and I agree it should go in the FAQ

**Comment by calebmeyer** [comment]
I tried adding this to the FAQ
```
--------
### The application UI freezes on Windows 10
Turn off desktop notifications in the google settings. [Reference](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/2404). [Longer reference with explanation of bug](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/2109).
```
but the save changes button is disabled for me.

**Comment by jostrander** [comment]
Sorry, I just added it, so we were probably editing at the same time.
