### ISSUE TITLE
Add "Screen Saver pauses the playback" feature and setting

### ISSUE THREAD

**Issue by tandr** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2407]
**OS:**
MacOS (OSX)

**Issue Descriptions:**
As a user, I need playback to pause when screen saver kicks in (I am away from computer). Radiant Player (which uses the same Electron framework) has this functionality and I find it extremely useful for listening music at work. 

**Steps to Reproduce:**
1. Wait for Screen saver to kick in
2. Music is still playing.

*Desired outcome*
Music pauses

**Comment by MarshallOfSound** [comment]
This needs to be implemented at a native level and it's not a feature I'm interested or invested into getting into Electron.

If someone puts in the time to put a screen saver event into Electron I'll happily revisit this request but for now it's a `wontfix` from me 👍
