### ISSUE TITLE
Voice Command Unresponsive

### ISSUE THREAD

**Issue by maeglin0** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2408]
**OS:** Windows 10

**Issue Descriptions:** The voice commands do not function at all, no indication even if the prompts are being heard. 

**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment]
The voice API is heavily rate limited.  If nothing happens, then the rate limit had been exceeding.  Nothing i can do about that unfortunately
