### ISSUE TITLE
Feature Request: Album Artwork Fit Window

### ISSUE THREAD

**Issue by lmckeen** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2409]
I am looking to see if it is possible to add an option to allow the album artwork to fit the size of the window instead of it filling the window and slowly scrolling as I would like to be able to quickly just open and then close the artwork and be able to see it fully at a glance

**Comment by whizzer0** [comment]
Click the album art on an album page and it will expand. It doesn't fill the window, but it does appear full-sized.

**Comment by lmckeen** [comment]
yes I am looking to see if I could get an option so I can see the full album artwork at once and not like this 
![image](https://cloud.githubusercontent.com/assets/11928027/24760347/c578a0fa-1abe-11e7-9ee1-7cacfa5e87d5.png)

**Comment by whizzer0** [comment]
![image](https://cloud.githubusercontent.com/assets/6824972/24807561/963dfdf6-1bb0-11e7-9955-9e869b08e959.png)

Like this? This is already a feature.

**Comment by lmckeen** [comment]
yes! just like that except for when you click the album artwork of the song currently playing

**Comment by arkon** [comment]
I feel like this is feature creep. You could easily just click the album name and look at the album art, like what @whizzer0 is doing.
