### ISSUE TITLE
Audio does not play from Chrome while Desktop Player is open

### ISSUE THREAD

**Issue by donkerrigan** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2410]
**OS:**
Windows 7

**Issue Descriptions:**
Once the Desktop Player is opened audio does not play out of chrome.  Streaming video both while streaming through the desktop app or while the desktop app is paused.

**Steps to Reproduce:**
1. Open Chrome first.
2. Open YouTube and stream a video, you should be able to hear the audio.
3. Open the GPMDP and start streaming a song, should be able to hear both YouTube video and song.
4. Go back to YouTube in Chrome browser and click any other video to start streaming.  Audio should not be working from Chrome.  Even if you pause the GPMDP the audio from Chrome will still not work.
5. Even after closing GPMDP the audio will not work in Chrome until it is restarted.

**Comment by MarshallOfSound** [comment]
I can't reproduce on any platform or combination of headphones / speakers.  (Tried SPDIF, USB and 3.5mm)

Also tried jumping around Chrome versions and couldn't get it doing what you describe.  It sounds like an Audio Driver specific issue and will probably be fixed either by a Chrome update on your machine or more likely an Audio Driver update.  You should check with your manufacturer for driver updates :+1:
