### ISSUE TITLE
Support mac Touch bar

### ISSUE THREAD

**Issue by cheapsteak** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2412]
**OS:**
macOS

**Issue Descriptions:**
2016 MBPs's touch bar has a limit of only 4 buttons that can be shown by default
It would be great if we could show media related buttons on the touchbar when the app is in focus
Electron docs on touch bar:
https://github.com/electron/electron/blob/master/docs/api/touch-bar.md

**Comment by jostrander** [comment]
I'd just like to take a moment to point out that @MarshallOfSound, the creator of this app, also helped write the touch bar integration with electron, including the documentation. Also a duplicate issue #2411 and even further back #1965, though I don't see resolution in the original issue.

**Comment by cheapsteak** [comment]
ah, apologies, I did a search for "touch bar" but should have also searched for "touchbar"
closing as duplicate
