### ISSUE TITLE
Windows: MiniPlayer Mode exit

### ISSUE THREAD

**Issue by Xiandrios** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2413]
**OS:** Windows 10

**Issue Descriptions:** Each time i exit the MiniPlayer Mode i always have my Google Play Music menu open on the left. Even if i closed the left menu before switching to the MiniPlayer Mode. Which this issue make it a bit annoying when you listen to music in MiniPlayer Mode and you hear something you like and want to add to your playlist then you exit the MiniPlayer Mode and try to drag the song to the playlist but can't cause the left menu is open.

![beforeminiplayermode](https://cloud.githubusercontent.com/assets/4623317/24800025/ac14a31e-1b74-11e7-906c-bee4f21bcf13.PNG)
![exitminiplayermode](https://cloud.githubusercontent.com/assets/4623317/24800027/ac189cee-1b74-11e7-82d7-bb86539e8dcc.PNG)

**Steps to Reproduce:**

* Start Listening to some songs
* Ensure that the left menu is closed
* Switch to MiniPlayer Mode
* Exit the MiniPlayer Mode
* The app will automatically open the left menu for you each time #

**Comment by MarshallOfSound** [comment]
GPM does this automatically when the screen sizes changes between certain bounds at certain zoom levels.  I could try hack around it but it would be a nasty hack for not that of a significant issue.

Will see what the impact of this is and see if anyone else notices / finds it annoying.  IMO not a big deal and not worth a hax to fix 👍

**Comment by Xiandrios** [comment]
Thanks @MarshallOfSound for the clarification.
