### ISSUE TITLE
[Windows 10] Excessive CPU usage

### ISSUE THREAD

**Issue by d-rez** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2416]
* I have checked that there are no issues with similar or the same content
  I'm seeing other CPU usage issues, for Mac especially. Also checked closed issues, there's #1777 that's already closed but seems a little related... I guess
* I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* I have double checked and can reproduce the issue
every time

**OS:**
Windows 10 x64
GPMDP Version: 4.2.0
16 gigs of ram, i7 @3.4Ghz (4c,8t)
Screen resolution: 3200x1800 DPI: roughly 262 from my quick maths (14" screen)
Touchscreen: yes

**Issue Descriptions:**
I'm experiencing pretty big CPU hit when using the player (~10-20%). Noting that I have a 4-core 8-thread i7 clocked at 3.4GHz, that's a big chunk of CPU being utilised for music playback. Since I can't find other reports related, I'm thinking this may be related to UI drawing and my resolution which is 3200x1800. I'm happy to do troubleshooting if that would help, I'm loving the player.

~1% CPU when UI is closed using the X button after starting playback
~2-4% CPU when UI is minimized
![obraz](https://cloud.githubusercontent.com/assets/1719659/24848887/64e91872-1e0c-11e7-9e94-1bf7e8447796.png)

~8% when having the window open and not moving the cursor at all
![obraz](https://cloud.githubusercontent.com/assets/1719659/24848912/80c30c6a-1e0c-11e7-9232-aabbd0a6e87b.png)

~20% when moving the cursor over interactive elements in the window
![obraz](https://cloud.githubusercontent.com/assets/1719659/24848878/5a5cabc6-1e0c-11e7-8f8e-fa6729782d7b.png)

~20% when moving the cursor over empty, non-interactive space in the window
![obraz](https://cloud.githubusercontent.com/assets/1719659/24848948/ad9a066c-1e0c-11e7-90b3-803129f50660.png)
(looks like a different thread is hogging the resources here compared to the interactive elements one)

This has been going on for over 6 months and over different app versions

**Steps to Reproduce:**
Launch the app. Play a song. Minimize the player to see reduced CPU usage. Restore it and move cursor around inside the window to see abnormal CPU usage

**Comment by MarshallOfSound** [comment]
CPU usage on other platforms has the same cause as this, GPM is poorly optimized and I can do nothing about it, see those mac issues you mentioned for some tricks you could use on windows to get the usage down 👍

**Comment by AsherMaximum** [comment]
I'm having similar issues, although not quite to the same scale. 
No bump when moving over blank areas
~18% when moving over interactive areas
~50% bump when moving over the "related artists" section

And the biggest one: When playing music in Google Music in Chrome, my total CPU usage goes up by ~10 % points. When it's paused it goes back down.
When playing music in GMPDP, total CPU usage goes up by ~20%, again going back down when paused. 
Not sure if anything can be done about this, or if it's even a bug, but thought it at least worth mentioning here, since it doesn't seem worthy of a new issue.
