### ISSUE TITLE
Setting Hotkeys doesn't work on macOS

### ISSUE THREAD

**Issue by edinchez** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2417]
**OS:** macOS Sierra 10.12

**Issue Descriptions:** Setting up Hotkeys doesn't work whatsoever. I highlight the field, press on keyboard keys, and nothing happens.

**Steps to Reproduce:** Go to Settings > Hotkeys. Select a field, and press a key on your keyboard.

**Comment by MarshallOfSound** [comment]
All hotkeys need to contain the "Control" key

**Comment by vendion** [comment]
It in not possible to use the media control keys on the keyboard (I'm speaking on a general level as I use Linux not macOS)?

**Comment by MarshallOfSound** [comment]
@vendion We listen for the media keys by default at a global level on all platforms 👍

**Comment by jostrander** [comment]
@vendion Just to clarify, we listen for for mpris and dbus media key events in linux, so if you don't have dbus working then it won't work.

**Comment by vendion** [comment]
@MarshallOfSound @jostrander Then something isn't working as Dbus is running on my system... I'll create a new issue with more details.
