### ISSUE TITLE
googleplaymusicdesktopplayer.com does not work with JS disabled

### ISSUE THREAD

**Issue by wchristian** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#242]
Given that its main reason for existence is facilitating the download the installer, i think it's fair to ask for it to be minimally useful at least without JS. :)

**Comment by MarshallOfSound** [comment]
JS is required to fetch the latest version of the player from the GitHub API.

The site is designed to be static and completely cacheable.  This was in preparation for what turned out to be well over 200,000 requests in the last 24 hours.

**Comment by MarshallOfSound** [comment]
TLDR: Fair too ask, but maybe when the traffic dies down a bit and my server can handle serving the pages dynamically
