### ISSUE TITLE
Bug: App's menu opens when I change keyboard layout by Alt+Shift

### ISSUE THREAD

**Issue by DmitryNikonov** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2420]
Hello.

When I hit Alt+Shift to change my keyboard layout, app's menu opens so I can't type anything until I close it. It's really annoying.

Also I did some research and found that it seems to be a common problem for electron-based apps. 
The thing is when you have some high-level menu labels without "underscored" letters (these ones that allow you to activate menu item by hittimg alt+underscored_letter), they will be activated when you hit Alt+Shift.
I don't know if it's a bug or just a feature but probable workaround is to edit menu labels' definitions in this way: label: 'File' -> label: '&File'. It will add an 'underscore' to letter F and therefore prevent this menu item from being activated by hitting Alt+Shift.

GPMDP 4.2.0
Linux x64 4.6.4-1-ARCH
KDE Plasma 5.9.4

**Comment by MarshallOfSound** [comment]
Currently Alt+Space is by design both on the apps part and on the OS's.  If you want to change it to have menu specific hotkeys (&File) then I would accept a PR to do so

**Comment by DmitryNikonov** [comment]
Not sure if I understood you correctly.

When I hit Alt+Space, track pauses and that's OK with me.
The problem is, when I hit Alt+Shift (in order to change my keyboard layout, that's a common hotkey in different OS'es and DE's) app's menu opens and tell me that I shall not pass until I close it. 

That's a common scenario: I want to find some cool artist so I put a cursor in a search bar. 
But sometimes I'm getting bored from good ol' Гражданская Оборона and go for something completely different with Latin letters in it's name.
So I hit Alt+Shift in order to switch from Cyrillic to Latin layout and app menu opens (I never asked for this). Therefore, in order to continue my quest I should close menu manually because it won't let me to perform any search.
It's clearly a misbehaving.

Actually, I don't care about menu hotkeys, I just proposed a possible workaround.
Also I'd prefer that a single app wouldn't force me to change a global hotkey.

**Comment by romkaspb** [comment]
Same bug in XFCE. It's very popular bug in electron apps, for example:
https://github.com/meetfranz/franz/issues/1088
https://github.com/zulip/zulip-electron/issues/528
https://github.com/RocketChat/Rocket.Chat.Electron/issues/50
https://github.com/vector-im/riot-web/issues/4345

And there is a very easy to fix:
https://github.com/meetfranz/franz/pull/1323

@MarshallOfSound can I submit a PR?

**Comment by jostrander** [comment]
Feel free to PR @romkaspb

**Comment by romkaspb** [comment]
I'm really confused, the solution I've described is working in multiple electron apps and not working in Google Play Music Unofficial.
@jostrander may be we can investigate it together?
I'm only changing `src/main/features/core/applicationMenu.js`, and only adding `&` to each label (i. e. 'Edit' -> '&Edit').
Then, I'm running the following commands:
```bash
$ npm run build
$ npm start
```
And problem still reaching.
It's working at most electron apps, why it's not working here?
Are you using Electron on steroids? :)
May be a reason of it's behaviour that I already have installed this app from deb package to my ubuntu?

It seems that Atom had the same bug (https://github.com/atom/atom/blob/master/menus/linux.cson),
but atom guys solved it in very strange way. They have added `&` to random place of `label` (of course not random, but I did not reached the logic).

**Comment by jostrander** [comment]
I'm on Ubuntu 18.04.2 with Gnome and I can't reproduce this, however I only have the en_US keyboard layout enabled. I can bring the menu bar up by using <kbd>Alt</kbd> alone but unfortunately <kbd>Alt</kbd>+<kbd>Shift</kbd> has no effect. 

On another note, the & usually precedes the character you would hit to shortcut to that menu item, for example if you were trying to navigate the menus:
![image](https://user-images.githubusercontent.com/760989/54727059-2e6cf100-4b4c-11e9-8288-8ea77ab7b852.png)

You would use `&Edit`, `&View`, `&Playback`, `&Window`, and `&Help` to allow you to navigate using <kbd>Alt</kbd>+<kbd>E</kbd>, etc. 

I would try to uninstall the dpkg variant if you are running the development version, just as a precaution.

**Comment by romkaspb** [comment]
As I know this bug is not confirming on Gnome.
It's 100% confirmed on XFCE and in around a 50% confirmed on KDE.

**Comment by ngseer** [comment]
I can confirm that KDE is still affected.
