### ISSUE TITLE
Minor Bug around UI Feedback

### ISSUE THREAD

**Issue by harrymilne** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2422]
**OS:** Windows 10

**Issue Descriptions:** When window refocused, incorrect feedback is given around user input.
For example:
![Screenshot of bugged play button](http://i.imgur.com/Pwd7Dh8.png)
Above shows the incorrect feedback from GPM.

**Steps to Reproduce:**
1. Click a button - (I have tried the play/pause button and the volume control)
2. Minimise or focus another window
3. Refocus GPMDP

**Comment by MarshallOfSound** [comment]
This bug is caused by the UI framework that GPM uses not handling window level blurs correctly, they should catch on and fix this soon enough 👍
