### ISSUE TITLE
expired certificate on https://www.googleplaymusicdesktopplayer.com/

### ISSUE THREAD

**Issue by mkabischev** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2423]

**Comment by MarshallOfSound** [comment]
Thanks, getting on this right now 👍

**Comment by MarshallOfSound** [comment]
Weird, my setup for Let's Encrypt's `certbot-auto` wasn't running it's cronjob correctly... 😕 

Running it manually now, should get a new cert momentarily.

**Comment by MarshallOfSound** [comment]
RIP, my bad, the certbot was running, but it didn't restart nginx so the certificate wasn't refreshed 😢
