### ISSUE TITLE
Fullscreen Results in Very High Memory & CPU Useage

### ISSUE THREAD

**Issue by jameshiggins** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2427]
**OS:**
Ubuntu 16.04

**Issue Descriptions:**
When player window is maximized cpu and memory use skyrockets!

**Steps to Reproduce:**
I see CPU usage from 100%-150% while fullscreen and mini player at 25%-35%.

**Comment by MarshallOfSound** [comment]
Please check closed issues regarding resource usage
