### ISSUE TITLE
Preventing sleep also suppresses notifications on Ubuntu

### ISSUE THREAD

**Issue by ZeroKelvinKeyboard** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2429]
**OS:** Ubuntu 16.04.2 LTS

**Issue Descriptions:** Notifications do not appear when the option to prevent the computer from sleeping is selected. This means the keyboard shortcut that shows more information does not work if the option is enable and non-critical notification from other programs are not displayed.

**Steps to Reproduce:** 
1. Open GPMDP settings.
2. Check the box labelled "Stop your computer from sleeping while GPMDP is open".
3. The option works as intended but the program will no longer display and notifications.
![screenshot from 2017-04-13 16-51-54](https://cloud.githubusercontent.com/assets/8317883/24994787/85d092d4-206b-11e7-89e3-e22f4f550922.png)

**Testing:**
I tested if notifications were working by running the following command or by pressing the keyboard shortcut to display song information.
`notify-send "Notification!"`
A notification will appear in both cases unless the offending option has been enabled (box checked).

This does not affect critical notifications (e.g. low battery), running the following command will always produce a notification regardless of the sleep option.
`notify-send --urgency=critical "Notification!"`

**Comment by MarshallOfSound** [comment]
I will raise this upstream with Electron

https://electron.atom.io/docs/api/power-save-blocker/#powersaveblockerstarttype

**Comment by ZeroKelvinKeyboard** [comment]
Ah, it's an Electron bug.
Thanks for the quick response.
Be sure to link me to the electron bug report as soon you make it. I'd like to help them resolve this issue.
