### ISSUE TITLE
JSON API sets playing to FALSE when loading next track or track scrubbing

### ISSUE THREAD

**Issue by ThreeFold** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2430]
**OS: Windows 10 Pro ver.1607**

**Issue Descriptions:**

In working with the JSON API, I caught something that's more of annoyance in how to handle rather than a full on issue. In `playback.json` it sets the `playing` value to `false` when loading or scrubbing through tracks. I understand it's in a state that is not playing a song, but it's a little frustrating when trying to use it to stream and having custom overlays go along with it. Adding a playing state rather than a binary value for this would be easier to handle. 

To go along with this when playing is set to false, it does not clear out the values for the json file, I can handle this fine, as you just ignore the rest of the contents. Again this is more of annoyance than an actual problem.

Not sure if this is easy to fix or not, but cheers!

**Steps to Reproduce:**

1. Enable JSON API
2. Restart Application
3. Access file (I have it symlink'd to the location needed, but is a problem in general)
4. Gain Frustration

**Comment by MarshallOfSound** [comment]
> To go along with this when playing is set to false, it does not clear out the values for the json file

This is correct and intended in the JSON file.  `playing` indicates whether audio is correctly being emitted from the player.  I.e. Is the music playing or is it paused / stopped.

If you want to know if a song is active or not check the value of "track". Afaics this is all intended behavior
