### ISSUE TITLE
Not able to remove the hotkeys once set

### ISSUE THREAD

**Issue by emailprashanthvg** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2434]
**OS:** Ubuntu 16.04

**Issue Descriptions:** Not able to remove the hotkeys once set.

So yeah as the description says, By mistake, I set Ctrl+F for stop, Now I don't want that hotkey. I have changed it to Ctrl+L but not able to remove it. It's bothering me very much, Moreover, i am not able to set hotkeys with combinations like Shift + something or Alt + something, Hotkeys are set using Ctrl + something only.

**Comment by MarshallOfSound** [comment]
Hit the "escape" key and it will reset the hotkey to "Not Set"

**Comment by emailprashanthvg** [comment]
Oh thank you very much :+1: , And what about hotkeys with other key combinations? Anything on that?

**Comment by MarshallOfSound** [comment]
These hotkeys are global so to prevent users doing things they will later regret (like setting "Space" as a global hotkey which some people seem keen on) we enforce all hotkeys containing the "Control" key

**Comment by emailprashanthvg** [comment]
Ok, Thank you very much for your response. I Understand what you mean. I was asking that feature because I have this Lenovo laptop which has this 'Function' key. I was going to bind Fn+F9, F10 and F11, etc cause I don't use that key at all. Anyway thanks a lot.

**Comment by jostrander** [comment]
Just going to add in here, the Fn key is usually a hardware key modifier and as such isn't passed to the operating system in most (if not all) cases as with shift, and control etc.

**Comment by Hermanio** [comment]
I find that there should be some obvious way to remove a hotkey, like a red cross next to the set hotkey to remove it. Pressing escape in a situation where backspace or delete does not remove the hotkey is not intuitive. 

What I ended up doing (but not something that a normal user would do) was going to the configuration folder of this program and finding the json file containing the hotkey bindings, where I could finally set it to null again. 

Take for example GNOME 3 settings. 
![image](https://user-images.githubusercontent.com/8943361/32811817-59f5bb1a-c9aa-11e7-86f2-8f0b9777695c.png)
The red cross near the set hotkey is a clear indication that you can remove the hotkey by clicking on the cross.

Here is an example of what it should look like (example taken from Polymer paper-input element demo):
![image](https://user-images.githubusercontent.com/8943361/32811878-bf22b31c-c9aa-11e7-8a1b-6f1d0196ebf6.png)
