### ISSUE TITLE
Style change on detail pages breaks dark themes

### ISSUE THREAD

**Issue by EpicWolverine** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2437]
**OS:** Windows 10

**Issue Descriptions:** The styling at the top of detail pages such as those for albums, artists, playlists, and stations have been updated and it breaks dark themes.

Original style: 
![firefox_2017-02-21_20-54-58](https://cloud.githubusercontent.com/assets/2897970/23193854/f9ea2fe2-f878-11e6-9e1f-5af6b5b8f7fa.png)

New style: 
![firefox_2017-04-17_19-21-38](https://cloud.githubusercontent.com/assets/2897970/25108407/930a9860-23a3-11e7-9399-fe22ecbfd1a1.png)
![firefox_2017-04-17_19-22-36](https://cloud.githubusercontent.com/assets/2897970/25108418/a49ffaa2-23a3-11e7-86fb-cb7810e0cee8.png)
![firefox_2017-04-17_19-23-12](https://cloud.githubusercontent.com/assets/2897970/25108419/a5e9ca3c-23a3-11e7-8fcb-3682839a0ec4.png)

New Style with Dark Mode:
![firefox_2017-04-17_19-24-36](https://cloud.githubusercontent.com/assets/2897970/25108426/af2eb738-23a3-11e7-849b-7534b06e330b.png)
![firefox_2017-04-17_19-24-18](https://cloud.githubusercontent.com/assets/2897970/25108427/b02a3072-23a3-11e7-9f89-2bdd2c18f3a2.png)
![firefox_2017-04-17_19-23-42](https://cloud.githubusercontent.com/assets/2897970/25108428/b113bae4-23a3-11e7-979d-aed62aa18963.png)

**Steps to Reproduce:** 
1. Be in the group of users the change has rolled out to (assuming it's not simultaneous; I haven't seen another issue about this).
2. Go to a detail page.
3. Turn on a dark theme.

**Comment by lech** [comment]
I just got home and fired up GMPD and noticed the same and can confirm I'm seeing this as well. At first I thought an update had failed but it actually looks like Google has made some style changes.

**Comment by MarshallOfSound** [comment]
I'll work on a fix for this but the earliest I can get a release out is this sunday 👍 

I'm overseas atm and my windows machine I use for building is back home 😆

**Comment by emailprashanthvg** [comment]
Also, happens when the dropdown appears for the songs I have searched for eg: 

Once search gives dropdown you can only see the artist name, Not the song name
![selection_019](https://cloud.githubusercontent.com/assets/17903153/25116470/9ed72d48-242a-11e7-8de9-fe43d7414641.png)

But when on hover you can see the song name.
![selection_020](https://cloud.githubusercontent.com/assets/17903153/25116473/a24f64a4-242a-11e7-87cc-b846b23ef7da.png)

I guess even this needs to be fixed.

Hope this information was useful.

**Comment by Meegooo** [comment]
@emailprashanthvg Should be fixed in master. See #2341

**Comment by MarshallOfSound** [comment]
Will try to release this, this weekend

**Comment by giacomopaita** [comment]
HI everybody. Where do i set the dark mode?

**Comment by lech** [comment]
@giacomopaita left hand burger menu, it's in desktop settings.
