### ISSUE TITLE
Darkmode doesn't change the text color of titles, albums, artists to white when clicking on them.

### ISSUE THREAD

**Issue by K1ngjulien** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2439]
**OS:** 
Windows 10

**Issue Descriptions:** 
The title says it all, I think it is just an issue with the css file.
Although it is just a visual thing, it makes it really hard to read the text.

**Steps to Reproduce:**
Click on any artist or album while using dark mode.
I've added some screenshots to demonstrate the issue:

Dark Mode:
![image](https://cloud.githubusercontent.com/assets/16562333/25144807/5f54387e-246f-11e7-9ae6-9f99247b622a.png)

![image](https://cloud.githubusercontent.com/assets/16562333/25144899/b40716fc-246f-11e7-86bc-951373ae94c8.png)

Light Mode:
![image](https://cloud.githubusercontent.com/assets/16562333/25144856/84be8d62-246f-11e7-9198-8ce5604f70b1.png)

![image](https://cloud.githubusercontent.com/assets/16562333/25144915/c8daa7ec-246f-11e7-9b72-fb5ffc796454.png)

**Comment by jostrander** [comment]
Pretty sure this was fixed already in master. 2f0e2d9b002af054549d53fc214ee734e9cec325
