### ISSUE TITLE
Desktop notifications don't work

### ISSUE THREAD

**Issue by trzr23** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2444]
**OS:**
Windows 7 64-bit

**Issue Descriptions:**
I've turned on the option in the Settings, but I receive no notification when the song changes. I even tried assigning and using a hotkey, but no luck.

Is this just one of the downsides of it being an experimental feature?

**Comment by MarshallOfSound** [comment]
Not supported on windows 7.  Good news is this might be supported in the future

**Comment by kadrach** [comment]
Hey @MarshallOfSound, apologies for issue necromancy here. Is this supported on Windows10? The README does not specify what is supported where, and I can't seem to find a way to enable it.

Thanks for all your work on this player 👍

**Comment by jostrander** [comment]
@kadrach You need to enable desktop notifications in GPM settings, not the desktop player settings.

**Comment by kadrach** [comment]
Thank you @jostrander, got it working :)
