### ISSUE TITLE
Volume control from PlayBar doesn't work

### ISSUE THREAD

**Issue by mradermaxlol** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2445]
**OS:** Arch Linux KDE x86_64

**Issue Descriptions:** when using PlayBar (or, in fact, other Plasma widget for multimedia players) the volume slider does not change the volume at all:
![screenshot_20170421_232416](https://cloud.githubusercontent.com/assets/11138966/25294831/a7308446-26e9-11e7-9892-96d07a32cf42.png)
![screenshot_20170421_232434](https://cloud.githubusercontent.com/assets/11138966/25294841/b0982462-26e9-11e7-8c01-1156058556f9.png)
(look at the volume sliders in-app and in PlayBar)
Also, when trying to move the slider in PlayBar, it just chooses some random value and moves the slider there (although the volume doesn't change, as mentioned above). Changing the volume in GPMDP does not affect the widget.

**Steps to Reproduce:**
1) Get some Plasma 5 player-control-widget
2) Run GPMDP
3) Try to change the volume level
4) PROFIT

**Comment by BrianAllred** [comment]
I use Cinnamon and Gnome as my main DEs on Arch, but I will install KDE/Plasma and try to reproduce this.

**Comment by MarshallOfSound** [comment]
The volume event from the MPRIS service hasn't been implemented.

See https://github.com/emersion/mpris-service/blob/cdd02bbef4585f8259b029caf912f667e220bcbf/index.js#L286

Our code: https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/main/features/linux/mprisService.js

I can try to blindly implement this but I don't have a VM to try it out on (overseas atm) so it would be better if someone else could try this 👍
