### ISSUE TITLE
Cannot install Windows 10

### ISSUE THREAD

**Issue by RyanRistine** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2447]
OS:Windows 10

Issue Descriptions: Whenever I try to install I get a popup that says "The procedure entry point
?InstanceTemplate@FunctionTemple@v8@@QAE?AV?$Local@VObjectTemplate@v8@@@2@xZ could not be located in the dynamic link library C:\Useres\myname\AppData\Local\GPMDP_3\app-4.2.0\Google Play Music Desktop Player.exe" with a "installing Google Play music desktop player" box behind it

Once I click ok on that pop-up another one comes up that says "The application was unable to start correctly (0xc0000005). Click OK to close the application" when I click ok on that window it closes and nothing happens

The player is not installed I have tried restarting and that did not fix the issue.

Steps to Reproduce:I just install it from the exe that gets downloaded on the website

**Comment by MarshallOfSound** [comment]
You Windows is munted mate 😢 

You should try refreshing windows, it might repair / instantiate the DLL file you need.  Also worth manually installing the VC2015 C++ redists.  Other than that, not much I can do in this situation 👍
