### ISSUE TITLE
"Installation has failed" - Windows 10 x64

### ISSUE THREAD

**Issue by Gregass** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2448]
Hi,
When I try to install version 4.2.0, as well as a few other versions, it fails to open the installer. I have no idea what is causing this issue, it worked fine with my old PC. 
Any help would be highly appreciated! 

[SquirrelSetup.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/949118/SquirrelSetup.zip)

**Comment by MarshallOfSound** [comment]
@Gregass Looks like you have some AntiVirus software getting in the way here, try disabling anything you have running and then install GPMDP 👍

**Comment by Gregass** [comment]
Thank you!
