### ISSUE TITLE
Add screenshots to the website

### ISSUE THREAD

**Issue by tf2manu994** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#245]

**Comment by MarshallOfSound** [comment]
There are screenshot?

In the slideshow?

**Comment by tf2manu994** [comment]
I meant more along the lines of a full program screenie. The ones there are faded and have words on them. I thought maybe something like the one on the github page would fit quite well

**Comment by MarshallOfSound** [comment]
Ahh, right, umm, I'll see if I can fit something like that into the design I went with :+1:
