### ISSUE TITLE
Color off in big album cover view

### ISSUE THREAD

**Issue by CoreyCaldwell** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2450]
**OS:**
Win 10 64
**Issue Descriptions:**
Color balance is off (too green mostly) on the large album cover view. The colors seem fine on the album list view. Checked several different albums. Restarted. Have a side by side pic. Left is the music app, right is a chrome google image search version.
![2017-04-23 02_17_55-95eb9078 jpg 3000x3000](https://cloud.githubusercontent.com/assets/1700890/25311329/0c62d9d0-27cc-11e7-84fb-ba35a2da1a5f.png)
![2017-04-23 02_20_16-silverlake k s o f m - eagles of death metal](https://cloud.githubusercontent.com/assets/1700890/25311330/0c656484-27cc-11e7-8ba1-33a567f909b7.png)

**Steps to Reproduce:**
Listen to an album
Check the small thumbnail in the album track view
Expand to the big album cover view
Colors will be off between thumbnail and large version

**Comment by CoreyCaldwell** [comment]
nevermind, seems to be strange artifacting on my machine

**Comment by AlcaDesign** [comment]
After an app restart, I'm definitely getting this too:

![image](https://cloud.githubusercontent.com/assets/7132646/25317478/fd70e28c-283e-11e7-9f63-64a1aa8fc6a8.png)

**Comment by MarshallOfSound** [comment]
@CoreyCaldwell Why was this reopened?

**Comment by CoreyCaldwell** [comment]
I'm gonna reopen this one. With another user report and looking at this one a different pc and getting different artifacting, I'm wondering whats actually going on in the grey-ing out method thats being used for the full album view. The side-by-side pic had gotten some funny artifacts both on a TN and an IPS panel and those change based on the zoom making me think that the grey out method thats being used is applying some kind of pattern on top to the image to grey it out rather than just reducing the saturation. Not a deal breaker but certainly funky. Does the big album view need to be greyed out at all?

**Comment by AlcaDesign** [comment]
I'm thinking it's just a CSS change on Google's part.

**Comment by MarshallOfSound** [comment]
@AlcaDesign 's screenshot is a CSS issue that has already been fixed in master and will go out next release, whatever artifacts you are seeing are your machine specific and we've never had similar reports.  It's probably specific to your exact monitor / GPU combination and rendering glitches will almost certainly be fixed in the next Chromium bump (they typically are picked up quite quickly upstream)

**Comment by CoreyCaldwell** [comment]
Good deal, what turnaround. Looking forward to the next release
