### ISSUE TITLE
App switiching itself off on startup

### ISSUE THREAD

**Issue by feelfree101** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2451]
Hi

I love using this app but recently I havn't been able to use it. Everytime I try to start the app the app comes up but after the loading screen when it goes to loading the Google Music Libary the app keeps shutting itself down so can't get any further into it. Have you any idea what the problem may be have tried switching my firewall off but dosn't seem to make any difference

**Comment by feelfree101** [comment]
Just to add iv'e just tried uninstalling the app and installing it again but can't even install it now it keeps saying installation failed

**Comment by MarshallOfSound** [comment]
Sounds suspiciously like some AntiVirus program messing with you, can you post the contents of the SquirrelSetup.log file in `%LOCALAPPDATA%/GPMDP_3`

**Comment by jostrander** [comment]
Stale. If you have anymore information feel free to comment and we'll evaluate further.
