### ISSUE TITLE
Downgrade Avahi package dependency from 'Depends' to 'Recommends' or 'Suggests'

### ISSUE THREAD

**Issue by z0rc** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2452]
**OS:** Kubuntu 17.10

**Issue Descriptions:**
Right now avahi-daemon is a hard dependency of GPMDP debian package. According to https://www.debian.org/doc/debian-policy/ch-relationships.html#s-binarydeps `Depends` should declare absolute runtime dependency, while avahi is needed only for chromecast support and player can be used without it.

**Comment by MarshallOfSound** [comment]
This has been discussed before and the result was a hard depends because although you don't need it, it makes more sense to be installed for all than not installed at all.

**Comment by reinerh** [comment]
Downgrading the Depends to Recommends for avahi-daemon still installs it for all people by default (as recommendations are installed by default), but users also have the choice to manually opt-out of installing it.
It would be nice if this decision was reconsidered.
