### ISSUE TITLE
[Suggestion] Implement another platforms

### ISSUE THREAD

**Issue by lukasag** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2453]
This player is amazing, it would be great if we could implement support to another services like Tidal and Spotify.

Anyone wanna join me on this?

**Comment by MarshallOfSound** [comment]
@lukasag This is way beyond scope of this player as basically the entire codebase is built to serve GPM no other service, feel free to fork and modify how you please but extra services will almost certainly never be a thing in GPMDP
