### ISSUE TITLE
RBG Lighting Systems support

### ISSUE THREAD

**Issue by akabhirav** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2457]
**OS:** Windows, Linux(x64)

**Issue Descriptions:** Add support for RBG lighting systems such as AlienFX and/or any such systems whose support can be developed simultaneously.

**Steps to Reproduce:** NA

**Comment by MarshallOfSound** [comment]
This kind of setup is normally handled at the Audio Driver level, not sure what you want GPMDP to implement here?

**Comment by akabhirav** [comment]
I saw a repo [LightFX Extender](https://github.com/Archomeda/lightfx-extender), which you can include in you node project as an addon using node-gyp. I guess it is a little hard as you need to know C/C++ (I need to learn them again). A node wrapper needs to be built. This will let you add generic support for RBG systems(Alienware, Razer, Logitech, etc.). I am still reading up on how to do it so I can help you, but I don't think it will be soon enough

**Comment by MarshallOfSound** [comment]
I believe this is something out of scope for this player and should be implemented either through the playback API, through system sound drivers or through the upcoming plugins work
