### ISSUE TITLE
Player stops and mini player goes black

### ISSUE THREAD

**Issue by Brodieman** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2458]
**OS:**
Windows 10 Enterprise

**Issue Descriptions:**
While playing in mini mode the musis will stop and the player will be black.  No controls come up when hovering over.  Have to right click the notification icon and quit and relaunch

**Steps to Reproduce:**
None, appears to be random.  I started about a week ago, some days it will happen once some it will happen 4 times.  Sometimes it takes 10 minutes sometimes 2 hours.

**Comment by MarshallOfSound** [comment]
I've seen these renderer crash reports come through to my crash reporter and I've been following them upstream, they should be handled in a chromium update (the code that crashes doens't exist anymore after C58)

**Comment by Brodieman** [comment]
Any idea on when?  This player (both install Windows version and Windows app) are pretty much useless to me until it's fixed.  I could not get one song in this morning.
