### ISSUE TITLE
macOS: When main application is closed, stop playing music and can't be reopened

### ISSUE THREAD

**Issue by Rykian** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2462]
Hi,
Since 4.3.0, when I close the main windows, music is stopped and main windows can't be reopened by clicking on its dock icon. Don't know if it's related to #2461, but it's very uncomfortable.

I can't get debug zip, but I've made a video : https://cl.ly/0R1x2Q373p46

**Comment by MarshallOfSound** [comment]
@Rykian This is almost certainly #2461

I pulled the macOS update but exactly 349 users got the new version before I pulled it.  If you delete the app and redownload the latest release (4.3.0) it will work 👍

**Comment by Rykian** [comment]
Woops, still have the problem with the last version downloaded from http://googleplaymusicdesktopplayer.com and from Github Release tab (just in case...).

Music stop when I close main window, but I can relaunch play from the notification icon (and re-open main windows with the "Show" entry).

PS: There is also a Homebrew Cask problem :
```
$ brew cask install --force google-play-music-desktop-player
==> Downloading https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Pla
######################################################################## 100,0%
==> Verifying checksum for Cask google-play-music-desktop-player
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: 76b821eeb1c7560631cf2fe9f64d2bce2c559eaf48d2a3507b76729c9f5b29ec
Actual: 0b9ae207fbc9c38d7fddba5d7185be99d741d2b318e1933332f6cda7b48b3c6e
File: /Users/thibault/Library/Caches/Homebrew/Cask/google-play-music-desktop-player--4.3.0.zip
To retry an incomplete download, remove the file above.
```

**Comment by MarshallOfSound** [comment]
@Rykian I don't know who or what manages that brew cask but because I swapped out the ZIP file the hash would have changed.  If the hash is just local to your machine you should be able to wipe it away somehow.

> Music stop when I close main window, but I can relaunch play from the notification icon (and re-open main windows with the "Show" entry).

I can't remember what the setting is but there is an option for it, possible it got toggled at some point?

**Comment by Rykian** [comment]
If someone has the same problem: There is no toggle button, but removing preferences in `~/Library/Application Support/Google Play Music Desktop Player/` resolved the problem.

**Comment by chadxz** [comment]
> Music stop when I close main window, but I can relaunch play from the notification icon (and re-open main windows with the "Show" entry)

This is still happening to me after downloading for the very first time today (v4.3.0)

**Comment by chadxz** [comment]
This seems to be working fine now. I can CMD+W (close window) on mac and the music continues to play. 👍

**Comment by chadxz** [comment]
actually, it is still a problem for my work computer, but the fresh install of 4.4.1 on my home computer without having installed any previous version works fine.

**Comment by chadxz** [comment]
After clearing the settings directory at "~/Application Support/Google Play Music Desktop Player/" and re-opening the app, CMD-W no longer paused the audio.
