### ISSUE TITLE
Snap package

### ISSUE THREAD

**Issue by Ads20000** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2464]
Hey! I help out a bit with the Snappy people, I'm not a programmer just doing what I can to help them out, I notice you've got a `snapcraft.yaml` and an Edge Snap up, what's blocking this from being released to Stable?
I'm currently on 1mbps Internet so not really able to test at the moment...

- [ ] Promote a 4.3.0 build to Beta
- [ ] Promote a 4.3.0 build to Candidate
- [ ] Promote a 4.3.0 build to Stable
- [ ] Perhaps change the version identifier of the Edge build to 'Master' or '4.3.0+git' and build that straight from the Git repo, but the others should be built from the 4.3.0 release?

**Comment by MarshallOfSound** [comment]
This is more something for @RAOF to sort out 😆 

I bumped the version in the yaml file and AFAIK the snap is supposed to build automatically

**Comment by RAOF** [comment]
Yup, https://dashboard.snapcraft.io/dev/snaps/7258/ is happily autobuilding.

**Comment by Ads20000** [comment]
@RAOF How well does the Snap work (like I said, I'm not really able to test at the moment), and if it works well maybe you could do a build of a released version (rather than from Git), test, and eventually put in the Stable branch? :)
At the moment people won't see it in GNOME/Ubuntu Software or even by searching for it, since it's only in Edge.

**Comment by RAOF** [comment]
The snap works pretty much entirely; the icon is broken, and there are bugs/missing features in Unity that mean the tray icon and Sound Indicator don't quite work correctly, but  under GNOME Shell it's flawless modulo the icon being broken.

Publishing 4.3.0 to a real channel might be sensible. :)

**Comment by Ads20000** [comment]
To fix the tray icon and sound indicator you may need a dbus interface, could you test this?
This is the one used in the `corebird-diddledan` snap
```
slots:
  dbus-corebird:
    interface: dbus
    bus: session
    name: org.baedert.corebird
```
Presumably you'd want to call the `slot` `dbus-google-play-music-desktop-player` or something shorter(!) and you'd need a `name` too but I don't know what you'd put there. Perhaps you know more about dbus than I?

**Comment by RAOF** [comment]
There are two bugs here:
- For the sound indicator, the problem is that the sound indicator won't show anything it can't find a .desktop file for. As a snap, we can't install a desktop file anywhere it looks for; there's no workaround we can do for this. (Users can copy the .desktop file into a path the sound indicator looks for, though)
- For the application indicator, libappindicator needs to write the icon to a path that's not mangled by the snap confinement; it currently goes into `/tmp`, but that's actually a snap-local path that can't be sent over dbus.

**Comment by ogra1** [comment]
@RAOF have you checked the vlc snap ? it uses the mpris slot to hook into the sound indicator

**Comment by RAOF** [comment]
How does it work around the problem that indicator-sound will only display things it can find a desktop file for, and doesn't look in any of the snap paths?

As I say, mpris itself works fine, and the various GNOME Shell mpris extensions will happily control it/get album art/etc. It's just indicator-sound that has an extra, unsatisfyable, constraint.

**Comment by ogra1** [comment]
i dont know how/if it finds the .desktop file in case of vlc, but i know it works on my 16.04 desktop (vlc has an entry with controls in the indicator menu once i started it from the snap)

**Comment by Ads20000** [comment]
@RAOF Looking at VLCs thing the only unusual thing is their build process which they use some commands to edit the prime of the Snap before packaging, seems like they're doing something with the icon which could fix the icon issue here? https://github.com/videolan/vlc/blob/master/extras/package/snap/package.mak

**Comment by flexiondotorg** [comment]
@RAOF To fix the issue libappindicator not being able to write the icon export `TMPDIR=$XDG_RUNTIME_DIR` in the `command:`, something like this:

    command: env TMPDIR=$XDG_RUNTIME_DIR PATH=/usr/local/bin:${PATH} ${SNAP}/bin/desktop-launch $SNAP/usr/share/example/Example

**Comment by Ads20000** [comment]
@RAOF Any updates on this? I can see there's still only a snap in the `edge` channel (though good to see that it's up-to-date!)
