### ISSUE TITLE
Pressing Delete always navigates you back a page, even when it shouldn‘t

### ISSUE THREAD

**Issue by kylegach** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2465]
**OS:** macOS 10.12.4

**App Version:** 4.3.0

**Issue Descriptions:**
Pressing Delete always navigates you back a page, even when it shouldn‘t.

**Steps to Reproduce:**
1. Navigate to a playlist
2. Select a track
3. Press the Delete key

***Expected Result:***
Track is removed from playlist _and you stay on the page_.

***Actual Result:***
Track is removed from playlist and _you are navigated back one page_.

**Proposed Solution:**
There’s two aspects to this issue. The first is that the delete key’s event should be properly captured when a track is selected (and possibly in other areas it is used). The second is that it is likely a good idea to copy Chrome’s behavior and remove the Delete shortcut for navigating back.

**Comment by jostrander** [comment]
Such a controversial issue. Maybe switch to alt + left like Chrome did?

**Comment by kylegach** [comment]
Oh, sorry, was there an issue around this already? I searched and didn’t find anything. And good point, if my proposal to remove the Delete shortcut is accepted, Chrome’s alternative shortcut should also be implemented.

**Comment by jostrander** [comment]
For a while this shortcut was never implemented, but it was eventually implemented to appease the fact that there is no actual back button other than the search bar back arrow. I can see how that would be an issue if there are events that would actually use that key inside GPM.

**Comment by MarshallOfSound** [comment]
@kylegach @jostrander As mentioned this is a widely controversial issue that goes way beyond just this app.  Personally, I quite like the backspace button being a back shortcut but I understand why Chrome had to drop the shortcut.  That said, the reasons chrome had to drop the shortcut are not applied here.  This is issue is entirely down to GPM not called `stopPropagation` when they use the delete shortcut.  I'll look into a workaround for this use case.

FWIW that `alt+left/right` hotkeys are already implemented

**Comment by kylegach** [comment]
@MarshallOfSound — Understood. When I suggested removing the delete-to-go-back shortcut, I thought I was suggesting the easier of the two solutions. 😅 

> This is issue is entirely down to GPM not called stopPropagation when they use the delete shortcut. I'll look into a workaround for this use case.

Great!

**Comment by SpectralKH** [comment]
Getting this problem when deleting tracks from the queue.

Is this going to be fixed ever? GPMDP already has cmd-[ to go back, so it's not really necessary to have another one. GPM doesn't have the delete shortcut, and I don't know of any other macOS app that does, so it's not really following standards.

**Comment by MarshallOfSound** [comment]
@LiteSpecter Please check closed issues, it's fixed in master
