### ISSUE TITLE
Pressing the close window button on macOS makes the app unshowable.

### ISSUE THREAD

**Issue by wilomgfx** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2468]
**OS:**

MacOS sierra 10.12.4

**Issue Descriptions:**

After the latest update (yesterday), when clicking the red X button to close the screen, the app wont show again when clicking on the icon on the dock or accessing in the menu bar/window.

**Steps to Reproduce:**

![https://d2ppvlu71ri8gs.cloudfront.net/items/211P3Z1U0z1v2U0q3P41/Screen%20Recording%202017-04-26%20at%2010.33.gif?v=5dcf84d0](https://d2ppvlu71ri8gs.cloudfront.net/items/211P3Z1U0z1v2U0q3P41/Screen%20Recording%202017-04-26%20at%2010.33.gif?v=5dcf84d0)

**Comment by MarshallOfSound** [comment]
@wilomgfx You were one of ~300 people who got a dodgy update, redownloading the latest version from the website should fix this 👍

**Comment by wilomgfx** [comment]
it does ! Thanks :)

**Comment by kazak1377** [comment]
I was that lucky person too((((
