### ISSUE TITLE
4.3.0: Deleting from a playlist refreshes the whole page and scrolls to the top

### ISSUE THREAD

**Issue by Proggie** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2470]
**OS:**
Mac OS 10.12.5 Beta

**Issue Descriptions:**
If I select a few songs and remove them from the playlist the whole page refreshes and scrolls to the top of the playlist.

**Steps to Reproduce:**
1. Go to a playlist with lots of songs (I have about 200)
2. Select multiple songs
3. Click remove from playlist

**Comment by jostrander** [comment]
I don't think this behavior is any different in GPM itself.

**Comment by Proggie** [comment]
Hmm..you're right...just tried it. Sorry, for some reason I didn't remember it doing that before.
