### ISSUE TITLE
Feature request: "Enter" to save metadata edits

### ISSUE THREAD

**Issue by SpectralKH** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2474]
**OS:** macOS 10.12.4

Something that really annoys me is after clicking "Edit info" on a track, you can't press enter to save your changes - Instead it seems like you have to move your cursor to the save button every time, which is cumbersome when you edit every track you add to GMP.

I got it working with this code right here inside the GMP console;
```
// Add event listener to <body>
document.querySelector("body").addEventListener("keydown", function(event) {
  // Only continue if we're in <input> and "enter" is clicked. Might need to be filtered down to  filtering to solve conflicts
  if (event.target.tagName == "INPUT" && event.key=="Enter") {
    // Click the "save" button
    document.querySelector("paper-button[data-action='save']").click();
  }
});
```

If you're not accepting the feature request, it would be real nice to get a custom script feature, just like the custom CSS feature already implemented. Because there's no other way to do this than compiling my own version of the app (Which would be cumbersome to maintain), is there?

**Comment by MarshallOfSound** [comment]
Merging into #2216
