### ISSUE TITLE
Feature Request: Would there be anyway to add a genius integration?

### ISSUE THREAD

**Issue by SolarPolarMan** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2477]
I love reading through annotations on [genius](https://genius.com/) while listening through an album. I'm imagining, ideally, some way to see the genius page for the current playing song without having to click every time the song changes. They have an API [here](https://genius.com/developers)

**Comment by Double44** [comment]
It's an interpretational site, I wouldn't take any of what they say as fact. They seem rather partisan as well.

**Comment by MarshallOfSound** [comment]
Have looked into this before, there is not a reliable way to get a Genius song ID from the information we have available in GPM let alone match it up against the lyrics we fetch from other services.  Simply would be a sub-par buggy feature that I don't have the time to invest in implementing let alone maintaining.

It's the kind of thing that coiuld be a plugin in the future (see the plugin super ticket)
