### ISSUE TITLE
Promises

### ISSUE THREAD

**Issue by benjamingr** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#248]
Just some tips after reading some of the code:

 - Never `reject()`, always reject with an Error instance so you get a solid stack trace.
 - Add a `unhandledRejection` handler that (for the very least) logs so errors never go silent.

**Comment by MarshallOfSound** [comment]
1. Makes sense, solid advice
2. I was not aware that `unhandledRejection` and `uncaughtException` did not overlap.  I thought `uncaughtException` would catch unhandled promise rejections?  Am I wrong in that assumption?

**Comment by benjamingr** [comment]
2) they do not overlap, the current default node behavior is to silently ignore unhandledRejection events

**Comment by MarshallOfSound** [comment]
Interesting, thanks for the tips.  I'll go back and add errors to the rejects when I get time :+1: 

Closing though as not an issue persay rather some friendly advice :cactus: :+1:
