### ISSUE TITLE
Bluetooth headset play/pause not working

### ISSUE THREAD

**Issue by b1naryv1k1ng** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2483]
Hello,

Currently, skipping forward and backwards works via headset controls (for example, I'm using Sony mdr-xb950bt) but play/pause does not. When searching google about this issue to see if it was something related to Windows itself, I did see that the spotify app was having the same issue that the developers appear to have fixed in a release (https://community.spotify.com/t5/Desktop-Linux-Windows-Web-Player/Windows-10-Bluetooth-headset-PLAY-PAUSE-button-not-working/m-p/1392357#M161738).

Is this something you'd be able to add into this app as well?

**Comment by MarshallOfSound** [comment]
@b1naryv1k1ng Can you try enabling the windows media service in desktop settings?

**Comment by b1naryv1k1ng** [comment]
Aha, that did it!

**Comment by wvdhouten** [comment]
Enabling the windows media service settings allowed me to use the play-pause too, however, now my next/previous actions from my headset are executed double (They already worked before)

**Comment by StructureDr** [comment]
As above - enabling the windows media service sorts play/pause for me and results in double execution of previous/next. Any suggestions appreciated.
