### ISSUE TITLE
touchbar doesn't draw when GMDP has focus (works when it doesn't)

### ISSUE THREAD

**Issue by donaldguy** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2484]
**OS:** macOS 10.12.5 Beta 3

**Issue Descriptions:** As stated in title. It would be better to also draw when app has focus

**Steps to Reproduce:**
1. Open GMDP, play something
2. see nothing but black on touch bar
![img_0048](https://cloud.githubusercontent.com/assets/43136/25598003/41e77eb4-2ea0-11e7-8435-06b81f5d9bd6.JPG)

3. Switch to another app (with or without its own in-app touchbar set), push the bar graph button to expand touchbar context
4. see the pretty scrubber
![img_0049](https://cloud.githubusercontent.com/assets/43136/25598007/4d7ce02a-2ea0-11e7-91db-954af24c1fbc.JPG)
5. Switch back to GMDP
6. see black bar

**Comment by MarshallOfSound** [comment]
This is how the macOS media service works.  You can only use the controls when the app isn't in focus
