### ISSUE TITLE
Feature Request: Add an option to hide the player from the alt+tab list

### ISSUE THREAD

**Issue by jirkot** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2487]
**OS:** Windows 7 Professional

**Issue Descriptions:** Currently on Windows the player is always visible in the alt+tab list, even if it's minimized to the tray. It would be nice to have an option to hide it from the list because it gets in the way of other opened apps.

**Steps to Reproduce:** Not and actual issue, just a feature request.

**Comment by MarshallOfSound** [comment]
When minimized to the tray (the option must be enabled and you need to click the "close" button to trigger it) the app does not appear in the alt+tab list on any of my test machines 👍 

This is probably a limitation of Windows 7 as we are calling the API to hide it and it clearly works on W8 and W10 😆 Might be time to update that PC if this bugs you enough 😁
