### ISSUE TITLE
Touchpad Scrolling

### ISSUE THREAD

**Issue by alfwork** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2488]
**OS:**
Windows 10 (anniversary  Update)

**Issue Descriptions:**
Basically when I'm scrolling in the program with the touchpad on my laptop (Zenbook UX510), the scrolling is very inconsistent, as in, it goes very fast. I've discovered that if I change how many lines my "scrollwheel" scrolls (in settings), I can set that to "1" and it seems normalt. BUT when scrolling anywhere else but the program, it's very slow. 
So what I'm saying is that the "scroll-scaling" (might not be the right term) seems to be off when using a touchpad.. However when using a mouse on my desktop (same number of scrolling lines) everything is fine.
I have updated every driver on the laptop and checked the settings but I can't find anything helpful.. 

**Steps to Reproduce:**
Well, use it on a touchpad?

**Comment by MarshallOfSound** [comment]
Discussed before, determined to be an issue resulting from Chromium 57, the upcoming bump to C58 adds a flag to revert this behavior
