### ISSUE TITLE
Text colors do not match theme

### ISSUE THREAD

**Issue by BenAlderfer** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2489]
On windows at least, at least some of the text colors do not match my current theme. If I'm using the dark theme, most of the text is white like it should be, but some text like "Top songs" (only in expanded view, default Top songs is ok) is still grey and its really hard to read. The issue is worse for light themes. When choosing a dark theme color, the text color for items such as the artist play button, hamburger menu, and music library tabs are still black. These colors should be changed to white to better contrast the dark color. The easiest fix for this would probably be an option to use light text since automatically determining could be hard.

**Comment by MarshallOfSound** [comment]
Please raise theming issues on our theming repo gmusic-theme.js
