### ISSUE TITLE
Debian Repo not signed! 

### ISSUE THREAD

**Issue by sebastienserre** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2490]
`W: The repository 'https://dl.bintray.com/marshallofsound/deb debian Release' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`

Please make necessary to have a correct debian repo

**Comment by MarshallOfSound** [comment]
See closed issues, still chasing this up with bintray
