### ISSUE TITLE
cache is being written at BAD location on windows (Roaming, while it should be Local)

### ISSUE THREAD

**Issue by rdslw** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2493]
**OS: Windows 10 v1703
**GPMDP version: 4.3.0

GPMDP is writing it's cache at: %USERPROFILE\AppData\Roaming\Google Play Music Desktop Player\Cache. 

It must NOT write cache there. Roaming folder is not for local caches. App should use this path: %USERPROFILE\AppData\Local\Google Play Music Desktop Player\Cache

p.s. I have also strong suspiction that cache is DUPLICATED with media cache of chrome itself, resulting easily in hundreds of duplicated megabytes. I will fill separate issue after additional verification.

**Comment by jostrander** [comment]
Take this up over at https://www.github.com/electron/electron/issues. This is a standard for all electron based applications included Slack. Chrome and Electron are separate instances and do not share any data, including cache, so your investigation will probably find duplicated megabytes. Comes with the territory of having a separate application.

**Comment by jostrander** [comment]
Just did a quick search for you, and it appears to have been raised and closed there already as well. https://github.com/electron/electron/issues/1404

**Comment by rdslw** [comment]
Thanks, will read it. 

Here, GPMDP should use (like chrome) %LOCALAPPDATA%. Spamming roaming profile with MB of data (500 here) is a bad design. I don't know how your Roaming profile looks like, but in mine, 98% of data is consumed by cache of GPMDP.

**Comment by jostrander** [comment]
I've got about 2gb in my roaming folder, 350mb which is GPMDP. Not really an issue for me though. I did see that it's possible to change this, but I'll leave it up to @MarshallOfSound to decide whether or not it's worth changing.

**Comment by rdslw** [comment]
I read the discussion. Clearly guys did wrong choice - they even admitted it :)
* chrome and dropbox do differently (contrary to what @paulcbetts wrote)
* microsoft documentation states to use %localappdata% for caches, not %appdata%
* it's sensible to NOT store cache in roaming profiles
* funny to read how they wrote a year ago that it won't be a problem, as electron apps store only settings - and today gpmdp, discord, vscode and many others, happily use >1gb in %APPDATA% for **cache**. Clearly because of not seeing it by them. 640kb should be enough for everybody ;)

As to your roaming profile: check of that 2gb how much are the other electron apps. I suspect much :)

Anyway in terms of GPMDP, they said that app author can change it easily using app.SetPath - so I suggest reopen here and considering change? If I understood them correctly (https://github.com/electron/electron/issues/1404#issuecomment-212756838) it's not forced on you from electron as you said. 

p.s.2. Cache invalidation also didnt work for me. cache wasnt deleted after I clicked 'refreshed library' - is it a candidate for a bug?

**Comment by MarshallOfSound** [comment]
Regardless of what is "correct" and "incorrect" in your opinion, the core point that everyone was ignoring in that thread was changing this behavior after an app has been deployed will break literally everything unless a very clever migration script is used to move the relevant data from one folder to another.

It's asking for trouble changing it and I'm not going to take that risk

**Comment by sbhal** [comment]
I can't even use GPMDP due to this. In my corporate environment, roaming profile is restricted to 256MB. Is there any workaround to this?

**Comment by jespersh** [comment]
Opened `%appdata%\Google Play Music Desktop Player\Cache` and cleared it for 500MB of cache. Seems like quite a lot for a music player

**Comment by alexthefifth** [comment]
So it's clearly a bug but won't be fixed because it's too hard to fix?

Context: having gigabytes of cache in a roaming profile pretty much breaks roaming profiles and is a great way to piss off sysadmins, thus ensuring GPMDP will have a hard time surviving on corporate users' computers
