### ISSUE TITLE
Dark them and back button

### ISSUE THREAD

**Issue by magic4got10** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2496]
Hello! Again good job with your app!

1. In dark them there are often black texts and buttons very hard to read and see. Here you can see what I'm talking about.
![screenshot 25](https://cloud.githubusercontent.com/assets/23573130/25775109/b04cd6d2-329d-11e7-9fd1-f8a82e5ea3c7.png)
![screenshot 26](https://cloud.githubusercontent.com/assets/23573130/25775110/b0506d60-329d-11e7-8955-2f13d9ecd6e7.png)
![screenshot 27](https://cloud.githubusercontent.com/assets/23573130/25775111/b0519154-329d-11e7-82cd-4e6f14e2f351.png)
In another post I read of a guy reporting something about themes and you told him to write it elsewhere. If I was wrong to write it here, I ask you to give me a direct link where I can correctly write this issue.

2. The system's back button of Windows 10 in Tablet Mode doesn't work. Since the app's one is in an unusual position, I'd like to ask you if you were forced to put it there because it's not possible to let the app use the Windows' one or it was just a free choice of yours? In this case, can you at least consider the chance to let us use the system's back button?

**Comment by Alipoodle** [comment]
Which version are you currently running, as this should be fixed in ``4.3,0``
*Taskbar, right click, help, about*

**Comment by MarshallOfSound** [comment]
The user is running the UWP version which I personally forgot to click the last "publish new version now" button in the microsoft dev console.  The update should be rolled out on the store now as well 👍

**Comment by magic4got10** [comment]
Ok, with the new update the issue number 1 is solved, but what about the BACK button of Windows 10's tablet mode?
Here is a screenshot of what I'm talking about:
<img width="1053" alt="schizzo" src="https://cloud.githubusercontent.com/assets/23573130/25778881/7b2fb956-330b-11e7-88f4-f4e64ee5a517.png">

**Comment by MarshallOfSound** [comment]
@magic4got10 That's a UWP concept that we can't hook into

**Comment by magic4got10** [comment]
Does this mean you have no will to integrate the application with the OS or enhancing UI in a coherent way to Windows 10 in the future?

**Comment by MarshallOfSound** [comment]
I don't think you understand, it's not a case of me having no will.  It's a case of their being no way to do it from the win32 environment

**Comment by magic4got10** [comment]
Sorry, I thought you were using Project Centennial (aka Bridge). I hope you'll consider it, since I read it offers a lot of easy tools for devs.

**Comment by MarshallOfSound** [comment]
Centennial doesn't offer access to all APIs, and definitely not easily.
