### ISSUE TITLE
Clicking GPMDP dock icon does not show window if closed before

### ISSUE THREAD

**Issue by laurentiuonac** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2499]
**OS:** MacOS Sierra 10.12.5 Beta 4 
I know it's a beta, but it will be soon launched for everyone. I can try test versions of the player if needed to ensure compatibility.

**Issue Descriptions:** When I close the GPMDP window (by pressing the red x) the only way I can bring back the window is by tapping on the status bar icon and clicking Show. Clicking on the dock icon does not open back the player window.

**Steps to Reproduce:**
1. Open GPMDP
2. Close the window using the red x button
3. Click on the dock icon

**Comment by MarshallOfSound** [comment]
@laurentiuonac You might have been 1 of 300ish people who got a bad update resulting in this bug.  Can you redownload the app from the website and see if it fixes it 👍

**Comment by laurentiuonac** [comment]
@MarshallOfSound Works! Thank you!
