### ISSUE TITLE
Unnecessary orange borders and resize arrows on linux tiling wm's

### ISSUE THREAD

**Issue by dunxiii** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#250]
I just noticed this application from reddit and immediately liked it but I have a problem.

I use i3wm on linux and get really annoyed by the orange borders arround the application, both in normal tiling mode and in fullscreen (F11) mode. This also includes the top bar with minimize, maximize and close, these controlls should not be drawn at all forcefully upon the user.

It would be fantastic if we could have the option to disable those with an option, ether by:

- startup flag: google-play-music-desktop-player --no-borders
- or "in application" checkbox option

**Comment by MarshallOfSound** [comment]
Linux and OSX should start using native window borders from the next release

**Comment by dunxiii** [comment]
Thats great news! Looking forward to it and will use current release untill then. :-)
