### ISSUE TITLE
Please offer List View for Artist View

### ISSUE THREAD

**Issue by coreywaldron** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2500]
Hello, 

Google play music is awesome (almost) and this Desktop Player makes it even better.

However, the biggest issue is that the Artists View for my library presents a bunch of huge icons which makes it a real pita to try to scroll quickly and find the music you want to play (especially if you have a huge library, like me).

A list view of artists would be a godsend.  Many have requested this on the google play forum as well... all we hear in response is crickets.  

Thanks!

**Comment by MarshallOfSound** [comment]
You'll get a little better than crickets here but not much better, making a big UX change like that to GPM itself is quite complicated especially with GPM's view rendering logic.  It's not something that we could viably maintain.  Keep pounding on Googles door 👍
