### ISSUE TITLE
Adapt GPMDP to MPRIS2

### ISSUE THREAD

**Issue by WolfangAukang** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2503]
**OS:**
Arch Linux

**Issue Descriptions:**
I'm using `playerctl` to manage music related settings on i3, and all the keybinds work properly. But, the console is showing some warning messages that are important for some features on i3 status bar and such. It seems the application is sending the wrong type according to [this](https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html), which is the org.mpris.MediaPlayer2 protocol. I can make a pull request with the changes, if I can find the file where this is specified. 

**Steps to Reproduce:**
For example, when executing playerctl metadata artist, the following messages are shown:

(playerctl:13598): GLib-GIO-WARNING **: Received property Rate with type y does not match expected type d in the expected interface

(playerctl:13598): GLib-GIO-WARNING **: Received property Volume with type y does not match expected type d in the expected interface

(playerctl:13598): GLib-GIO-WARNING **: Received property Position with type u does not match expected type x in the expected interface

(playerctl:13598): GLib-GIO-WARNING **: Received property MinimumRate with type y does not match expected type d in the expected interface

(playerctl:13598): GLib-GIO-WARNING **: Received property MaximumRate with type y does not match expected type d in the expected interface
artist-name

But generally, the same will happen executing any valid playerctl command.

**Comment by WolfangAukang** [comment]
Excuse me, I just saw what is the issue. I checked the code with the mpris integration, and it actually seems the issue is related to node-mpris.

**Comment by jostrander** [comment]
https://github.com/GPMDP/mpris-service/blob/master/index.js

We forked this service and here are the types exported for each thing. Feel free to raise an issue over here if you see something we can fix.

**Comment by WolfangAukang** [comment]
Perfect! Will check it

**Comment by JasonLG1979** [comment]
I know this is a closed bug and more than likely an upstream issue but I'd also like to add that along with the above exceptions I also get this in my logs:

```
Ignored exception from dbus method: Gio.IOErrorEnum: Method 'org.mpris.MediaPlayer2.Player.Next' returned type '(u)', but expected '()'
```

Basically Next is returning an unsigned 32 bit integer when it shouldn't return anything.

I'm no Node expert but https://github.com/GPMDP/mpris-service/blob/master/index.js looks like a better implementation than the version you're currently using.

**Comment by JasonLG1979** [comment]
@jostrander - The only thing I would change/add to you implementation is that for some properties like Rate there is no way to tell clients that they can't be set by the client. In such cases you'll have to add setters even if they don't actually do anything to avoid exceptions.

**Comment by rosshadden** [comment]
I have the same issue and ended up just redirecting stderr to `/dev/null` (`playerctl metadata artist 2>/dev/null` for example).
