### ISSUE TITLE
Player freezes at notifications

### ISSUE THREAD

**Issue by gxcreator** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2504]
It seems issue have same sympthoms as #1866

**OS:**
Windows 10

**Issue Descriptions:**
Player UI freezes when new song starts

**Steps to Reproduce:**
Play any song with notifications enabled

Workaround: Disable desktop notifications in Play music settings

**Comment by MarshallOfSound** [comment]
This is a known issue and is even in the FAQ
