### ISSUE TITLE
Bluetooth device disconnection force onto device doesn't resume when connected again

### ISSUE THREAD

**Issue by sleepyxuras91** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2508]
**OS:**
Windows 10 1703 15063.296 Enterprise

**Issue Descriptions:**
I use Bluetooth headphones with my Windows 10 laptop and use the Playback setting to force it onto my Bluetooth headphones manually (Stops any speakers blurting out my music on bluetooth disconnect). But on the Web version this picks up my audio device again when I re-connect it but for your application I have to restart the App to able to pick up the audio device again. Common as I normally leave my Bluetooth headphones to auto turn off when popping to meetings and such.

**Steps to Reproduce:**
1. Select a audio device manually in the Desktop settings - Playback
2. Disconnect audio device which stops the playback
3. Plug/ connect device in again and click play 
4. No audio is played.

**Comment by MarshallOfSound** [comment]
We aren't going to constantly scan your computer for new audio devices, that is incredibly inefficient.  You can trigger a new search for media devices though by opening Desktop Settings and navigating to the "playback" tab.

The audio device list will refresh and your newly attached headphones should be on the list 👍
