### ISSUE TITLE
Windows 10 Cortana Implementation

### ISSUE THREAD

**Issue by kevinhynes95** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2509]
**OS:**

Windows 10

**Issue Descriptions:**

I was wondering if there was a way to set the default media player in Cortana to GPMDP and possibly implement voice commands through her?

**Steps to Reproduce:**

n/a

**Comment by MarshallOfSound** [comment]
I've looked into this before (in another issue) and it isn't possible because you need to be running a legit UWP app, even the UWP wrapper we have simply isn't good enough 👍
