### ISSUE TITLE
'Send Gift' tab doesn't work

### ISSUE THREAD

**Issue by tf2manu994** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#251]
Windows 10, 3.0.0

**Comment by MarshallOfSound** [comment]
I don't have a Send Gift tab, can you screenshot and explain what is wrong in more detail?

**Comment by tf2manu994** [comment]
sure
![](http://i.imgur.com/MwA4hRM.png)

and when i click it

![](http://i.imgur.com/PeDHkBK.png)

Tried uninstalling and redownloading from both github and the official website.

**Comment by MarshallOfSound** [comment]
Lol, I've never seen that button before.  Must be a US thing, I'll get a US mate to look at it :+1:

**Comment by tf2manu994** [comment]
I'm from Sydney mate

**Comment by MarshallOfSound** [comment]
Alrighty then :cactus: #harkward

My subscription is still NZ based though even though I'm in Australia.  I might just go ask one of my mates at Uni then :smile:

**Comment by MarshallOfSound** [comment]
You made the list :+1:  --> https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/graphs/contributors

**Comment by tf2manu994** [comment]
Sidenote: if you haven't seen Telstras prepaid plans, they're great, mine I pay 30 bucks a month, but included is 30 bucks in google play credit. So my gpmaa is free. Consider looking into it. 

Wayyyyy off topic but thought I'd let you know

**Comment by MarshallOfSound** [comment]
Lol I'm with Optus for the epic amounts of rollover data :+1:

**Comment by tf2manu994** [comment]
Rolls over here too :) 

Take a look at the freedom plus plans, the 30 dollar one comes with 30 dollars of google play credit every month, 40 dollar one comes with 40 dollars of it, etc

Pretty nice. 

Also the Telstra network is great

Anyway, wayyy off topic now, but it's not like github is srs bsns

**Comment by tf2manu994** [comment]
If you want, tomorrow I can fetch you the css handle for it

**Comment by tf2manu994** [comment]
![](http://i.imgur.com/v1PKVhQ.png) @MarshallOfSound

**Comment by tf2manu994** [comment]
fixed #309
