### ISSUE TITLE
Feature Request: navagation via mouse buttons

### ISSUE THREAD

**Issue by gosteev** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2517]
hey! is it possible to make this mouse buttons work as prev / next page?

![image](https://cloud.githubusercontent.com/assets/6203574/26026458/41c3fec2-3804-11e7-8810-4463c0877604.png)

like [alt+left arrow] / [alt+right arrow] in browser works? for example, i clicked on related artist, but want to go back. atm the only option to go back is the arrow inside search field or backspace button

thanks

**Comment by MarshallOfSound** [comment]
@gosteev They currently are implemented and working, if they aren't working for you ensure you haven't rebound the buttons in your logitech software

**Comment by MarshallOfSound** [comment]
@gosteev Yeah, unfortunately logitech software has a habit of doing annoying things like this, not much I can do if there software is messing with it
