### ISSUE TITLE
Windows x64 build not visible on official website

### ISSUE THREAD

**Issue by tf2manu994** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#252]
You have to grab it off the releases page.

**Comment by MarshallOfSound** [comment]
That's because **plot twist** the 64 bit build is not 64 bit....

It is a copy of the 32bit version named that way so 64bit windows users can update to `3.0.0`

**Comment by tf2manu994** [comment]
oh

i feel dumb now
