### ISSUE TITLE
Dynamic album artwork visualizer setting overheats OSX El Capitan to at least 41 degrees Celsius

### ISSUE THREAD

**Issue by zoeweinberg** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2523]
I went to Preferences and checked Static Visualizer and that stopped the fan from whirring (whereas it was audible over the music before) and the temperature went down to 40 degrees Celsius

**Comment by jostrander** [comment]
Yeah, nothing we can do about this. Google's album art visualizer is horribly inefficient, even in chrome.
