### ISSUE TITLE
Feature Request: Sort Music library by Last Added

### ISSUE THREAD

**Issue by jdrews** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2527]
Requesting means to sort "Music library" based on the last added item. Phrased another way, if I add an album to my library, I would like to sort the Music library Albums and see the last added item as the first item in the pane. 

Expecting a dropdown to select sort order (Alphabetical, Last Added). See below image for possible placement of dropdown:
<img width="727" alt="google play music desktop player_2017-05-16_22-46-28" src="https://cloud.githubusercontent.com/assets/172766/26136577/ee046ae0-3a8a-11e7-9d25-00ba1bcba826.png">

I'd be up for writing a Pull Request implementing this Feature Request. Do you know if something like this is possible given the framework?

**Comment by jostrander** [comment]
It's not really possible due to the polymer library Google uses for their UI rendering. You'd have to figure out a way to modify the root data source, including possibly server side code at Google. If you can make it happen I'll gladly reopen this to look over everything though.
