### ISSUE TITLE
Not really much of an issue, but is there a reason that the Mac build isn't a dmg?

### ISSUE THREAD

**Issue by tf2manu994** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#253]
They seem to compress much more nicely and are what most mac users are used to getting. Akin to a .exe or .msi installer on windows or a .deb package on linux.

**Comment by MarshallOfSound** [comment]
Yes, you cant auto update when you package into a dmg.  Whereas you can auto update a zip

**Comment by tf2manu994** [comment]
oh, never realised that.

TIL! :)
