### ISSUE TITLE
Feature Request: Meta Playlists?

### ISSUE THREAD

**Issue by dkulp2** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2537]
Thanks for your app! One feature that I really like in Spotify is the ability to nest playlists in folders. (Up until recently it was also possible to play all the songs in a folder of playlists, but they deprecated that feature on mobile apps. Grr.) For example, I might have a genre folder with playlists of different artists within.
Is it _possible_ to create meta-playlists, by combining multiple playlists according to, say, a common naming convention? In this way you could create a sort of folder of playlists and then shuffle play, etc. For example, if playlists were named "A_Band1", "A_Band2", then all the songs in the two playlists might be grouped through the GPMDP UI as a playlist "A" — even though under the hood the songs were played from the two actual playlists.
Thoughts? I'd be willing to delve into the code, if it were possible. But I'm guessing that without an actual API from Google that this might be more than GPMDP could do.

**Comment by jostrander** [comment]
Judging by the complexity of it, I'm not sure that it's possible. We are already jumping through hoops just to grab the information about the current playlist and even that's not full proof. It's a good idea, but not sure how possible it'd be at the moment.
