### ISSUE TITLE
GPMDP App Problems

### ISSUE THREAD

**Issue by iHildy** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2538]
**OS:** 
macOS 10.12.4 and Windows 10.
**Issue Descriptions:** 
I am trying to use the app and i have typed in both of my computer IPv4 address and nothing sows up. 
**Steps to Reproduce:**
Type my address into my Sprint LG Nexus 5X.
Press Check button.
Press back button.
Wait and nothing shows up.

**Comment by jostrander** [comment]
Feel free to open this over at the GPMDP app repo: https://github.com/GPMDP/google-play-music-desktop-remote
