### ISSUE TITLE
Crashing after signing in, fresh install

### ISSUE THREAD

**Issue by latringo** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2539]
**OS:**
Windows 10, Version 1703, Build 15063.296
**Issue Descriptions:**
Install application. Sign in. Starts to load library. Window closes. Nothing running in Task Manager
**Steps to Reproduce:**
See above

Thanks. Great idea!

**Comment by MarshallOfSound** [comment]
Saw the crash report come in and I believe it's fixed in upstream Electron now 😄 

Will see next release 👍

**Comment by latringo** [comment]
What is the fix? Your version numbers are the same.
Thanks
