### ISSUE TITLE
Add an FAQ on the website

### ISSUE THREAD

**Issue by tf2manu994** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#254]
here are some things to add

checksums, or .md5 or .sfv files

the "media keys dont work" bug

how to get past this dialog ![Windows Smartscreen](http://i.imgur.com/9Ssgkm1.png) 

(the answer is to click more info,then the screen looks like that and you can click run anyway)

**Comment by MarshallOfSound** [comment]
Ummmm, that should not be a thing.  All releases are signed with my authenticode key.

They are signed like 3 times.... (Literally 3 times)

Where did you get that `.exe` file from

**Comment by tf2manu994** [comment]
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/releases

**Comment by MarshallOfSound** [comment]
I just downloaded that release and it is signed, can you please right click on the downloaded file and click "Properties" then screenshot the "Digital Signitures" tab

**Comment by tf2manu994** [comment]
C028CEAFFF80B1D06EAFF7154B7C6A3B88993D2E is x64 sha1
C028CEAFFF80B1D06EAFF7154B7C6A3B88993D2E is x86 sha1 (seriously why are they the same)
![x64](http://i.imgur.com/BbwtBLM.png)
and 
![x86](http://i.imgur.com/1R87tUX.png)

Just to be sure, running webroot and MBAM right now to check if i managed to get a virus.

**Comment by MarshallOfSound** [comment]
It's dodgy as hell that the app is signed and you got a unknown publisher warning...

When you run as admin (and the prompt appears) what is in the "publisher" field?

**Comment by tf2manu994** [comment]
Open Source Developer something something

I think this was a one off. 

I am very confused, never seen this happen.

My other points still stand though.

**Comment by silverches** [comment]
I also had the same thing last night.

**Comment by j2ghz** [comment]
I got that today on both my PCs

**Comment by eygraber** [comment]
I got that yesterday; downloaded from same link as OP. FWIW I've deployed Authenticode signed binaries before, and all of my installs get flagged by SmartScreen.

**Comment by MarshallOfSound** [comment]
SmartScreenTM  <-- Proudly the second worst program on windows machines since 2009

(Second only to IE)

**Comment by MarshallOfSound** [comment]
FAQ added to the Wiki guys
