### ISSUE TITLE
Disable touchbar support for macOS?

### ISSUE THREAD

**Issue by wturnage** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2542]
**OS:**
macOS Sierra
**Issue Descriptions:**
Navigating away from the player adds new button to the collapsed touchbar control strip. While this is a great feature, I would love to be able to disable this as I like keeping only what is needed in my touchbar, and I already have the default media button which works great with the player.

I've checked and rechecked the settings and cannot find any option to disable it. 
**Steps to Reproduce:**
Navigating away or minimize GPMDP window.

**Comment by MarshallOfSound** [comment]
Adding an option to disable this makes very little sense IMO, if you want to customize your touch bar you can and remove / hide this button.  How to OS responds to our usage of the `MPRemoteCommandCenter` is entirely up to the OS not to us, so we can't remove the button without completely disabling the service.

**Comment by wturnage** [comment]
Thanks, I guess the fault is on the OS then. There doesn't appear to be an option to disable or remove the button at the OS level. Going to customize the control strip from the OS settings yields nothing as the button disappears right when you go to edit it.

**Comment by tikimo** [comment]
Hi, at first launch I got the controls on my touch strip. I love them. However they disappeared and I cant seem to get them back. Any help?
