### ISSUE TITLE
Bug: Playlist keeps randomly refreshing

### ISSUE THREAD

**Issue by jeetkundostyle** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2551]
**OS:** Windows 10, latest version as of May 25

**Issue Descriptions:** Playlist randomly refreshes back to top of page, making me need to scroll down to find my place. Usually happens after removing songs.

**Steps to Reproduce:** Remove songs from long playlist.

**Comment by jostrander** [comment]
Possible duplicate #2465

**Comment by MarshallOfSound** [comment]
Just trying doing what #2465 explained and got into exactly the same situation that @jeetkundostyle describes, merging into that issue 👍

**Comment by jeetkundostyle** [comment]
Cool. Thanks.
