### ISSUE TITLE
Feature request: Add I'm Feeling Lucky option to GPMDP Remote

### ISSUE THREAD

**Issue by perceival** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2555]
Hi,

I am missing I'm Feeling Lucky option in GPMDP Remote app (at least there is no within Android version). Is it possible to add it for example as one of playlists?

Regards,
percy

**Comment by MarshallOfSound** [comment]
Merging into https://github.com/gmusic-utils/gmusic.js/issues/16
