### ISSUE TITLE
Support nonstandard keys

### ISSUE THREAD

**Issue by lf-** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2556]
**OS:** Windows 10 1703 (build 15063.296)

**Issue Descriptions:** Unusual keys such as F13, F14 and F15 are unsupported in GPMDP. I'm generating these keycodes with an arduino based macro keypad and would like to bind them as like/dislike without interfering with any other things on the machine.

**Steps to Reproduce:** Produce F13/F14/F15 scancodes and try to bind them as things in the settings.

Note: I've tested these with [this thing](http://www.delphiforfun.org/programs/utilities/KeyCodes.htm) and they definitely are appearing.

**Comment by MarshallOfSound** [comment]
Should be an easy PR @lf- 😄 😉 

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/renderer/ui/utils/constants.js#L18

Currently we hardcode F1-12 in a range call.  I'm not sure if F13,14,15 are legit keycodes or not but if you can show that they are, change that range value and test it to make sure it works on your machine I'd accept that PR.

**Comment by davidsenk** [comment]
All F keys up to F24 are real

https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731(v=vs.85).aspx

Adobe references up to F15

http://help.adobe.com/en_US/AS2LCR/Flash_10.0/help.html?content=00000520.html


And going with Qt upto F35! is supported

http://doc.qt.io/qt-4.8/qt.html#Key-enum

**Comment by lf-** [comment]
I tested with a chrome key tester thing and it works. Need to get node dev environment working on windows (ew).
