### ISSUE TITLE
Feature: hotkey to add track to library

### ISSUE THREAD

**Issue by mkeedlinger** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2558]
Being able to have a hotkey to upvote the track AND add it automatically to the users library would be great.

This is an awesome project!

**Comment by mkeedlinger** [comment]
I would be happy to take this issue when I have time, BTW.

**Comment by sk0g** [comment]
I'm not sure how this would be done, but if @MarshallOfSound has any pointers I'd love to take a look at it!

**Comment by MarshallOfSound** [comment]
> add track to library

This is not currently possible due to the way google handles context menus, it's been discussed and looked into before.

There is already a hotkey through for upvoting the track 👍
