### ISSUE TITLE
Poor Hotkeys Support

### ISSUE THREAD

**Issue by SpectralKH** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2559]
**OS:** macOS 10.12.4

- CMD is not detected on macOS.
- Kunction keys F13-F20 don't seem to be detected.
- Would like to press function key without modifier keys held down (like only F8 for pause).

Currently trying to disable my media keys, and remap them to some GPMDP shortcut using Karabiner-Elements. Feels limiting when I can't use only F13-20 for this shortcut, since they're not on my (compact) keyboard.

**Comment by MarshallOfSound** [comment]
> CMD is not detected on macOS.

This is a framework limitation and documented in many other issues

> Function keys F13-F20 don't seem to be detected.

PR literally just went up for this and there is an existing issue

> Would like to press function key without modifier keys held down (like only F8 for pause).

That's a macOS thing, in order to use F1-12 you have to hold the "fn" key

**Comment by SpectralKH** [comment]
> That's a macOS thing, in order to use F1-12 you have to hold the "fn" key
@MarshallOfSound That's not true. In fact, GPMDP shortcuts will not work if you hold down fn, because fn+F# is reserved for the system. This is what lets applications use F# keys for shortcuts - Like GPMDP does currently.
So, again, could you implement the ability to use F# without holding down modifier keys (ctrl, alt, shift).

**Comment by Qyriad** [comment]
Also I can confirm that this is not a macOS specific issue, as on Windows 10 I can also not assign F# keys without a modifier to hotkeys. This issue should be reopened.

**Comment by MarshallOfSound** [comment]
All hotkeys require the Control modifier, this is not a bug and I don't have plans to change this
