### ISSUE TITLE
Scrolls to top after adding song to playlist

### ISSUE THREAD

**Issue by SpectralKH** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2560]
**OS:** macOS 10.12.4

**Issue Descriptions:**
Sometimes when adding a song to a playlist (either dragging or using context menu), the page will reload, fading out the page and showing a loading animation, then take you to the top of that page. I've noticed this most in the Last Added playlist.

This does not happen in the browser. However, when you are in a playlist, and remove an item from that playlist, this happens in both the browser and GPMDP.

**Steps to Reproduce:**
1. Go to Last Added, scroll down a bit
2. Add a song to a playlist (dragging or context menu)

**Comment by SpectralKH** [comment]
So, in the browser, when you add a track to a playlist, the loading animation shows, but afterwards it does not take you to the top of the page, like in GPMDP.

This is really really annoying when you go through a playlist, adding 50 songs.

**Comment by SupremeArmchair** [comment]
This isn't really a solution, but if you want to add a ton of songs to a playlist you can ctrl+click songs to select lots of songs, or shift+click with songs that are in a row that you want to select, and then from there add to playlist or whatever.

**Comment by MarshallOfSound** [comment]
@SpectralKH This is GPM throwing a navigation error and us handling it smoothly, (fading out, loading, fading in).  In the browser you may not even notice this error but just in case we handle them nicely for you.

This behavior is expected until GPM fix the error.

**Comment by SpectralKH** [comment]
@MarshallOfSound And it's not possible to scroll back into place?
