### ISSUE TITLE
Mini Player slowly expanding at a constant rate

### ISSUE THREAD

**Issue by Nikkislayer7** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2565]
OS: Windows 10 (Creators Update)

Issue Descriptions: Mini player is constantly attempting to grow in size for no reason. Zoom levels are also distorted during and after this.

Steps to Reproduce: Open application, click mini player

**Comment by MarshallOfSound** [comment]
Duplicate #2269
