### ISSUE TITLE
Bringing up a old problem: Windows Audio Device Graph Isolation eating RAM

### ISSUE THREAD

**Issue by DreadfulDrummer** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2566]
I noticed this on my new Lenovo Yoga 720.
Windows Audio Device Graph Isolation (audiodg.exe) kept rising until I noticed the laptop starting to get super hot, fans blaring, things were beginning to operate not so smoothly... audiodg was hogging over 11 GB of RAM!

After trying various methods I had found online, to no avail, I thought maybe some settings in GPMDP were causing it.
I switched each setting, one by one, until, eventually, I found that disabling Voice Control seems to stop the problem from occurring.

I hope this leads you in the right direction to addressing this issue because, while I don't use the Voice Controls at the moment, I image I'll be using this feature in the near future, what with the Google Assistant API out and devs like Joao from Join and AutoVoice doing what they do, I see myself speaking to my Lennie someday soon.
I named my laptop Lennie.

Sorry if this not news and there really ain't anything to be done about it; I had checked for issues with instances of the word "graph" and found three others with no mention Voice Controls causing it.

**Comment by MarshallOfSound** [comment]
This sounds like a memory leak in windows and there isn't much we can do about it, the voice controls simply call native API's to get access to an input stream from the microphone, if the controller for that stream has a memory leak we can't control that.
