### ISSUE TITLE
Chromecast icon not showing up

### ISSUE THREAD

**Issue by Stanzilla** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2568]
**OS:**
Windows 8.1 x64
Bonjour 3.0.0.10 is running
**Issue Descriptions:**
The Chromecast button is not showing up
**Steps to Reproduce:**
Start GPMDP
![google play music desktop player_2017-06-05_21-36-22](https://cloud.githubusercontent.com/assets/75278/26799738/0efd1358-4a37-11e7-9171-6e540e08b6bd.png)

Somewhere in the issues I read that the device string is hardcoded somewhere? I am trying to stream to a Google Home device, maybe that just needs to be added?

Edit: Turned on a Chromecast on the same network and it is not showing up either, meh. The website detects both devices just fine. Also checked Firewall rules and everything should go through, I'm only using the standard Windows Firewall.

**Comment by jostrander** [comment]
Do you have bonjour print services installed?

**Comment by Stanzilla** [comment]
OH, interesting. Does it say that somewhere in the docs? I allowed the app itself through but not Bonjour, that fixed it!

**Comment by jostrander** [comment]
I'm not sure that's in the docs. Chrome has bonjour built in, so you don't have to add it to the firewall separately. Since GPMDP is using bonjour to discover chromecasts it has to be added to the firewall so it can receive replies from the casts to know what's available.

**Comment by Stanzilla** [comment]
@jostrander nah, Chrome does not come with Bonjour afaik, and it only started working after I explicitly allowed Bonjour through the firewall. Now it's broken again and I have no idea why.

**Comment by MarshallOfSound** [comment]
@Stanzilla Make sure the bonjour service is running and the firewall is still open.  Restart your computer and hope.  Other than that there isn't much we can do to help

**Comment by Stanzilla** [comment]
I reinstalled Bonjour and it started working again. I did a service and computer restart before and that did not fix it. *sigh*
