### ISSUE TITLE
[Dark Mode] Browse stations theming broken

### ISSUE THREAD

**Issue by Stanzilla** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2569]
**OS:**
Windows 8.1 x64
**Issue Descriptions:**
Tab texts are a dark/black text color on black background
**Steps to Reproduce:**
Hamburger menu => Browse Stations => 
![google play music desktop player_2017-06-05_22-15-53](https://cloud.githubusercontent.com/assets/75278/26801295/b789d560-4a3c-11e7-9cc2-a55c4dfff13d.png)

**Comment by MarshallOfSound** [comment]
Please raise theming issues on the theming library repository

> Theming - https://github.com/gmusic-utils/gmusic-theme.js
