### ISSUE TITLE
Could we get an option to set a default zoom level in settings?

### ISSUE THREAD

**Issue by StateOfException** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#257]
It'd be helpful to have the option to set a default zoom level for displaying the player content- as things stand, it's almost unusable at resolutions below 1920x1080, and even then- it's got so much whitespace and large text/graphics that it's a bit of a chore to use. 

I've always set it at 90% or 75% in Chrome- it's a bit jarring to be jolted back to a forced standard zoom level with this player. Appreciate that the underlying design's Google's fault, but the zoom function's always been a way of working around the issue- it'd be nice to have the option to set it by default in the app's settings!

**Comment by MarshallOfSound** [comment]
Ctrl + and Ctrl - shortcuts will be implemented soon #196
