### ISSUE TITLE
App doesn't work on MacOS High Sierra

### ISSUE THREAD

**Issue by bkerensa** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2570]
App doesn't work at all on MacOS High Sierra it freezes and eventually responds again but does not load any content

**Comment by MarshallOfSound** [comment]
Well this is just brutal man 😆, the OS update has been out for developers for **literally** a matter of hours.  There is a multitude of things that need to be handled upstream to make this work.  Not the least of which is Chromium patching itself to get working on High Sierra.

Gonna leave this open but locked purely to stop duplicates.

**Comment by KnifeCat** [comment]
Maybe you have installed the wrong OS _(lol)_ . If it is the case, uninstall it OR delete the program files (don't ask me, i have Windows and Linux but no of this apple).

**Comment by MarshallOfSound** [comment]
Please note I have edited @KnifeCat 's comment to remove potentially misleading or incorrect information.

**Comment by LeavingGitHub** [comment]
Wow couldn't you do something else of doing this?!

By the way I am KnifeCat

_Sent from my Samsung SM-G920W8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by CrixuAMG** [comment]
I've just downloaded this application on my macbook running High Sierra, smooth playback and no issues!

**Comment by KarboniteKream** [comment]
It also works fine in my case.

**Comment by MarshallOfSound** [comment]
Yeah I borrowed a friends laptop yesterday who was already on High Sierra and it was working fine, whatever issue this issue experienced has probably been fixed in the stable version of High Sierra.
