### ISSUE TITLE
Electron is flash for desktop!!

### ISSUE THREAD

**Issue by sumitb** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2571]
The major with this app and other apps like Spotify is the amount of resource being consumed by them. This is a great blog post explaining it in details: https://josephg.com/blog/electron-is-flash-for-the-desktop/
What was the reasoning behind using Electron over React Native?

**Comment by MarshallOfSound** [comment]
@sumitb This is not the place to have this discussion, I firmly disagree with that blog post and almost everything in that post is either misleading or blatantly incorrect.
