### ISSUE TITLE
App Freezes when Adding/Removing songs from the Library

### ISSUE THREAD

**Issue by mlebeau11** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2572]
OS: 

Windows 10 Home, 64 Bit

Issue Descriptions: 

Any time I add/remove any music from my library the app temporarily freezes and I am unable to do anything. Not sure if this is a well known issue or not but it causes issues when I attempt to add multiple albums to my library using the desktop player. (The music that had been playing will continue to play though)

Steps to Reproduce: 

Go into any album and try to add to the library. There will be a slight pause for a few seconds and you will be unable to use any portion of the app.

[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/1053580/debug_info.zip)

**Comment by MarshallOfSound** [comment]
@mlebeau11 GPM appears to trigger a rapid sequence of redraws in this situation that can freeze the application, this is a GPM issue that hopefully they will pick up and fix on their end 👍
