### ISSUE TITLE
Mini Player "Grows" Until It Fills Whole Screen, then Content Grows until it won't fit container

### ISSUE THREAD

**Issue by SoonerLater** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2575]
**OS:**
Windows 10 Pro 64 bit.

**Issue Descriptions:**

I am running GPMDP on a system that has two 4k monitors. When I switch to the Mini Player, the player grows and grows until it fills all available space, then the content of the mini player outgrows its container. 

This is a screenshot of the Mini Player across both of my 4k monitors. I had to reduce the resolution of the photo in order to use PhotoBucket to host the image, but this is a faithful representation of what I see (but with the taskbar cropped out).

![image](http://i94.photobucket.com/albums/l100/graystrickland/3614fca2-b0ae-449f-9731-b4a845e156d2_zpsm6ltlgcp.png)

**Steps to Reproduce:**

Start GPMDP. Switch to Mini Player. Watch it grow like cancer at Chernobyl.

**Comment by MMRomanov** [comment]
I have this issue too!) Two monitors 1920x1080. Windows 10 Pro 64 bit.

**Comment by MarshallOfSound** [comment]
Merging into #2269
