### ISSUE TITLE
Darwin title bar visible in fullscreen after refresh

### ISSUE THREAD

**Issue by arkon** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2576]
**OS:**
macOS 10.12.15

**Issue Descriptions:**
The Darwin title bar remains visible while in fullscreen mode if the page is refreshed, or if the app is restarted immediately into fullscreen mode (e.g. after a computer restart).

Related to #2027.

**Steps to Reproduce:**
1. Have app open in fullscreen. Note that the custom title bar is hidden.
2. Refresh the page (i.e. Cmd+R).
3. Note that the custom title bar is visible.

**Comment by MarshallOfSound** [comment]
🎉
