### ISSUE TITLE
Current song title on touch bar

### ISSUE THREAD

**Issue by Hking0036** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2577]
**OS:**
MacOS 10.12.5

Is there any way that support could be added to have the current title (presumably optionally) on the touch bar? I don't really need the scrub bar too often but I'd really like to have the title and maybe even album art and progress/duration time on the touch bar controls. The scrub bar already sort of does that but there's no text, but I don't know if that's intentional or just a limitation of the touch bar.

**Comment by MarshallOfSound** [comment]
The scrubbing bar that we give users access to is part of the `MPRemoteCommandCenter` API.  I.e. we tell macOS what song is playing and it then displays that bar.

Unfortunately, we have 0 control over what it shows in place of that scrubber.
