### ISSUE TITLE
Some songs doesn't show

### ISSUE THREAD

**Issue by patryk-kawalarz** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2578]
Hello. I use your player on my Mac and since some time there is some problem with songs - some of them doesn't show in player. So for example I have some album with half of songs, but in oryginal web player I see all of them.

**Comment by MarshallOfSound** [comment]
This player literally is the web player so if some songs aren't showing up for you it's a GPM issue not an issue with this player
