### ISSUE TITLE
Extremely High CPU Usage When GPMDP Is In Focus

### ISSUE THREAD

**Issue by sonic2kk** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2580]
**OS:**
KDE Neon 5.10.1 (More Info [Here](http://imgur.com/a/RS9DO) If Required)

**Issue Descriptions:**
GPMDP uses an EXTREME amount of CPU usage when it's the application in focus. At one point usage hit 98% for me, but it usually hovers around 60-80%. Idle my system uses 1% mostly (sometimes there are random spikes up to 5-12%), see [this](http://imgur.com/a/ff3oY). I'm using an Intel Core i5-6500, so while not the most powerful processor in the world it handles everything else I do relatively okay. When I have a few Chrome windows open, Steam in the background, KSysGuard, and some background processes such as RedShift and KDE Connect, my system usage averages out at around 15-20%, see [here](http://imgur.com/a/o8PqS). When I open GPMDP, however... [The CPU Usage _spikes_](http://imgur.com/a/5hFvy). If you notice the dip, after the huge initial spike before shooting back up, this was when I put KSysGuard into focus to take a screenshot. The CPU usage is still higher than normal and is consistently high (notice all the cores are hovering around the same amount of usage), and when I close GPMDP [it drops back down again](http://imgur.com/a/dVV7V). [Here](http://imgur.com/a/N4K1v) is what CPU usage looks like when I open GPMDP when my computer is at the same idle state from earlier. When I look in the process table it says GPMDP is using 25% of my CPU and that plasmashell is using 25-27%. However when the application is not in focus it says the application is using about 20-25% and plasmashell is only using the standard 1-4%. CPU usage is not this high on Windows with GPMDP, which I find strange. I was using Ubuntu 16.10 before I switched to KDE Neon (which is based on Ubuntu 16.04), and I don't recall having these CPU issues.

I don't know much about how Electron works on a technical level apart from a few videos posted by GitHub, but I think it's to blame. Or at least the Linux side. [Discord](http://discordapp.com), another program which uses Electron, [has a similar issue](http://imgur.com/a/iAPoW). Again, the high CPU issue is not present on it's Windows counterpart either; and again I don't remember this being an issue on 16.10.

CPU usage doesn't increase when playing music or using the app, it just stays high. I don't experience any issues as a result of the high CPU usage but obviously having a processor at this kind of usage all the time is not a good idea.

I hope my report was detailed enough. I didn't see this issue anywhere else, but I'm sure I can't be the only one.

Thanks!

**Steps to Reproduce:**

- Install GPMDP on KDE Neon 5.10.1 User Edition
- Open GPMDP

**Comment by MarshallOfSound** [comment]
@sonic2kk Unfortunately I don't have the time (and in some cases the ability) to debug resource usage on every linux variant.  The only linux OS I test before release is the latest LTS of Ubuntu.

All I can suggest here is turning *everything* off and seeing if you can isolate a certain feature that is causing the CPU usage.  If discord has the same issue I'd start by turning off voice controls.

Another thing to try is to just open normal Electron and see if it *by itself* has the super high CPU usage, if it does I can follow it upstream to see if it can be isolated

**Comment by ChALkeR** [comment]
This is most likely caused by https://github.com/electron/electron/issues/8455.
