### ISSUE TITLE
When scrolling up too fast in a playlist, the screen goes back to the "My Playlists" section

### ISSUE THREAD

**Issue by SupremeArmchair** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2581]
**OS:**
Mac OS Sierra
**Issue Descriptions:**
Whenever I scroll up too fast in a playlist, it brings me back to the "My Playlists" section. 

It may have to do with the size of my playlists (the issue I have it most commonly in my "Thumbs up" playlist with 1500 songs...)

By scrolling up, I mean using the touchpad to scroll up with two fingers, not clicking and holding the scrollbar. 

With just one flick downwards to go up in the playlist its fine, but with a lot in succession is when it brings me back to my playlists. 

I think it may have to do with scrolling at an angle, ie not flicking your fingers in a straight line up-down, but instead angled slightly. If the issue is that I'm angling my fingers too much then this is not an issue with the software, its an issue with me (although I haven't experienced this issue in any other piece of software so I don't think that's the case)
**Steps to Reproduce:**
Simple!
1. Open the music player
2. Go to one of your playlists
3. Go to the bottom of the playlist
4. Scroll up with two fingers on the trackpad

**Comment by MarshallOfSound** [comment]
It'll be the two finger swipe navigation we have in this app.  You're super fast swipe is probably slightly angled and is being ndetected as a horizontal swipe because it's so fast.
