### ISSUE TITLE
Missing Chromecast button in interface

### ISSUE THREAD

**Issue by n-v-o** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2583]
I'm running the Version 4.3 of Google Play Music Desktop Player on Windows 10, version 1703 (build 15063.413). Windows is fully up to date as of today.  The ChromeCast button is missing from GPMDP. I've used this feature in the past quite often (in fact I was using it last week). I've checked and ensured my cast devices (two ChromeCast Audios, as well as a home group) are working . I'm able to cast to each of them from the same device (in chrome) and from other devices. I've tried uninstalling and reinstalling the application, as well as logging out and back in. I've scoured the settings to see if perhaps it got toggled off. I'm fairly certain I was using this version a week or two ago and casting was working just fine.
![untitled](https://user-images.githubusercontent.com/29506123/27254076-aa4e622e-534e-11e7-95d6-69ba37207dd9.png)

Any thoughts?

**Comment by MarshallOfSound** [comment]
On windows you need to have bonjour installed and enabled and port 5353 open in the firewall.  Any action in the last week to change either of those things will stop chromecast support working.

**Comment by n-v-o** [comment]
Thanks for response. I've got it working. Is this a recent change? I've
never had the Bonjour service installed on my system before. I know it gets
installed w/ iTunes suite but I don't use iTunes, and never installed the
stand alone variant either.

**Comment by MarshallOfSound** [comment]
>  Is this a recent change?

Nope, chromecast has always required bonjour on windows, you might have gotten bonjour through another program though, sometimes it's packaged up

**Comment by WyriHaximus** [comment]
Where can we find bonjour? Just installed itunes through the windows store and chromecasts aren't showing up.

**Comment by jostrander** [comment]
You can find it by searching for bonjour print services.
