### ISSUE TITLE
Stick Loading library. Solved/Fixed

### ISSUE THREAD

**Issue by decentpix** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2587]
**OS:**  
Windows 10

**Issue Descriptions:**
When launching the app, it gets stuck on loading library.

**Steps to Reproduce:**
![stuck](https://user-images.githubusercontent.com/9129754/27285051-a0d4cafc-553e-11e7-9982-7eef217cdecf.jpg)

To fix:
Close the App and make sure it's not running in the background.
navigate to your %appdata% folder (Windows key + R, type in "%appdata%")
delete the "Google Play Music Desktop Player" folder.
Now re-launch the app.
When the app opens it will prompt you to sign in again.
All should be fixed.

**Comment by MarshallOfSound** [comment]
Closing as user reported as fixed
