### ISSUE TITLE
Add jackd support 

### ISSUE THREAD

**Issue by aenertia** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2588]
* Hi there adding jackd support would be great. This is fairly minimal amount of work and would make it infinitely more useful given firefox jack support is experimental and chrome has none.

OS - Ubuntu 17.04 (but jack is cross platform)

**Comment by MarshallOfSound** [comment]
> chrome has none

This in itself is almost certainly a barrier to implementation considering GPMDP is based on Electron which is based on Chromium.

If someone puts together a PR for this I'd be happy to review it but this isn't something I'm prepared to have open as I have 0 intention of implementing this kind of thing.

**Comment by SolarLiner** [comment]
Why would you use JACK for everyday use is beyond me. There is ALSA and PulseAudio for that, and you can add the JACK module for PulseAudio.
