### ISSUE TITLE
Music fading in and out - not volume - not tracks

### ISSUE THREAD

**Issue by genm0ntana** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2594]
**OS:**
Windows 10
Version	10.0.15063 Build 15063

**Issue Descriptions:**
Latest/greatest version of GPMDP (and previous versions)
Music fades in and out. Gets softer/louder randomly. Thought it was the tracks at first. Checked all windows speaker/mic settings. It's not adjusting the actual volume.

It happens several times an hour.  Sometimes, several times in one song.

If play in Firefox via google's web interface, I do not notice it... so it happens VERY rarely or not at all.

**Steps to Reproduce:**
Have not clue but I have turned off any processing from windows and checked all my settings/quality of the audio files.

Please help! I love the app but can't take it any longer...

Also: I have recently built a brand new PC and it still happens... no shared components at all....

**Comment by MarshallOfSound** [comment]
Sounds like google broke something on there end, probably experimenting with track normalization.  We don't mess with the volume or anything like that so whatever is causing this is nothing to do with GPMDP.  You probably just got caught on the bad end of some A/B testing

**Comment by genm0ntana** [comment]
thanks for the quick reply!

So you haven't had any other complaints about this? I googled and couldn't find anything. It has been happening for months....

**Comment by MarshallOfSound** [comment]
@genm0ntana I've heard nothing about anything like what you describe

**Comment by genm0ntana** [comment]
Ok. Thanks! I guess I'll try again next time the browser option makes me made and maybe it'll be fixed. Thanks again for the app and the quick response! Looking forward to checking out the iOS app (if you guys are still planning on that).
