### ISSUE TITLE
Mini player gradually increases in size

### ISSUE THREAD

**Issue by iansan5653** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2596]
**OS:** Windows 10 on Surface Pro 4

**Issue Descriptions:** When I start the mini player, it opens at a normal size, but then gradually expands without stopping, as seen in this image: http://g.recordit.co/2okb2pJTqo.gif

**Steps to Reproduce:** Open the mini player.

**Comment by MarshallOfSound** [comment]
Duplicate #2269
