### ISSUE TITLE
Resizing mini-player results in zoom of desktop player

### ISSUE THREAD

**Issue by jwerbs1217** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2598]
If I shrink my mini-player to a small size, when I return to the normal desktop player everything is fine at first, but as soon as I click to go to a different page using the sidebar, the entire thing zooms out. The same issue happens but zooms in if I enlarge the mini-player. Below are images of my player zoomed in and zoomed out.

Separately, is there a way to make the Esc key close the mini-player and go back to the desktop player? When the mini-player is small it can be very hard to find and click the button to return.

Thanks!

**OS:** Windows 10

**Issue Descriptions:** The whole player is zoomed in or zoomed out if the mini-player is not the right size. 

**Steps to Reproduce:** Pop out mini-player, shrink (or enlarge) mini-player, revert to full window player, click to any new option on sidebar.

![gpmdp zoomed in](https://user-images.githubusercontent.com/26612392/27454755-0655a8a2-5769-11e7-9321-ad807927143a.png)
![gpmdp zoomed out](https://user-images.githubusercontent.com/26612392/27454756-065cc056-5769-11e7-9d32-094664ad507b.png)

**Comment by dstruct2k** [comment]
Just saw the exact same thing happen here. Win10 ver1703, Google Play Music Desktop Player 4.3.0.
...I also can't seem to find the advertised Equaliser, does this bug make it disappear somehow?

**Comment by MarshallOfSound** [comment]
Duplicate #2269
