### ISSUE TITLE
Chrome Cast Streaming

### ISSUE THREAD

**Issue by clydefrog10002** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#260]
Is there already a way for casting to Chromecast?

**Comment by MarshallOfSound** [comment]
There are ways and I am always looking into them but it is a long way off.

**Comment by Arffeh** [comment]
How long is a long way off? :D

**Comment by MarshallOfSound** [comment]
@Arffeh It's already done?  It's been in the app for ages?

**Comment by Arffeh** [comment]
Oooh, apologies.
Googling brought me here, as all I have when attempting to cast is a blank list. I thought it may have not been finished.
Everything else on the network can see my casting device. I'll keep faffing about and see if I can get it to work.
Sorry sir.
