### ISSUE TITLE
When will the didNavigateInPage method be executed?

### ISSUE THREAD

**Issue by Linbubin** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2600]
[this](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/efe908bb0e909851dfb2c36c34c0f688c5cfd482/src/renderer/ui/pages/PlayerPage.js#L119), have code 
` didNavigateInPage={this._didNavigateInPage}`,

i want to know what time this code will execute？
And what Effect is this  function?

```
_didNavigateInPage = (...args) => {
    if (this.ready) this._savePage(...args);
  }
```

**Comment by jostrander** [comment]
And the savePage saves the url to the preferences file so you can open the app where you left off.
