### ISSUE TITLE
Request: client side decoration

### ISSUE THREAD

**Issue by Feichtmeier** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2602]
**OS:**
Ubuntu 16.04.2 LTS GNOME 3.20 DE

**Issue Descriptions:**
Request: since ubuntu is moving to gnome could you implement an option to open your program without window decorations and add some window decorations in the client window?
Thanks anyways for this awesome app! Makes GPM a better desktop experience!

**Comment by MarshallOfSound** [comment]
There is an option, "Use native system borders" or something like that 👍
