### ISSUE TITLE
"pause after this song" does not work.

### ISSUE THREAD

**Issue by sk0g** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2604]
**OS**

Arch Linux (Manjaro 17.0.1 KDE Plasma 5.35.0)
 
**Issue Descriptions:**

When you have a queue of songs, the pause after this song option does nothing. At the end of the song, the next one plays (if there is another song in the queue.)

**Steps to Reproduce:**

1. queue songs, by playing an album
2. select the currently playing song, and in the burger menu press the "pause after this song" option
3. at the end of the song, the next one will start playing automatically

**Comment by kaipot** [comment]
Used to work for me, but this also just started happening to me (Windows 10).

**Comment by pillravi** [comment]
When will this update be available? I'm having this issue in 4.3.0 which is currently the latest from [the site](https://www.googleplaymusicdesktopplayer.com/).

**Comment by MarshallOfSound** [comment]
> When will this update be available

Planning on an update this week, it's a complicated process with lots of manual steps though so no promises.

**Comment by KS2Problema** [comment]
I started having this issue several weeks ago. Just installed the 4.4.0 update but it didn't fix any of my problems. Even though it was glitchy (presumably because of GPM sticking the front of the 'next' song on the end of the current song, leaving a second or three of interrupted music from that next track), I nonetheless used it all the time. TBH, I consider _pause_ and the remote two of the best features.

**Comment by pillravi** [comment]
@KS2Problema, you bring up another good point - how the feature, when it worked, played the beginning of the next song before pausing. I don't think it is the fault of GPM, however, but rather a separate bug with GPMDP. Case in point, if a user plays a single song from an album, the beginning of the next track does not play. I suppose we must wait until the bugfix for #2604 is released, then see if the glitch still affects the "Pause after this song" feature, at which point, if it does, we can open a new issue.

**Comment by pillravi** [comment]
I just downloaded and tested this issue with 4.4.0. #2604 is _not_ resolved.

**Comment by KS2Problema** [comment]
The bit of the next song glued to the currently ending song is, indeed, a problem in Google's Chrome-browser based application, as well. It started when they introduced gapless play. (Which really _is_ a nice feature; tradeoffs, eh?) In my experience, on my  system, the next-song-glitch  seems to occur if the next song is changed in the last half-minute to minute.

**Comment by egorshulga** [comment]
Windows 10, v4.4.1: does not work as well

**Comment by kion** [comment]
Ubuntu 17.10 here. Player version 4.4.1. Issue is still present.

**Comment by bdcarr** [comment]
Windows 10, v4.5.0. Been seeing this issue since I first installed GPMDP (v4.4.0), still occurring.

**Comment by pilot51** [comment]
I just discovered GPMDP and like it a lot. I was excited to see this feature because I would often wait until a song finished and pause before stepping away. Unfortunately, it doesn't work, as described in the issue description. I'm on Linux Mint 18.3.

**Comment by pillravi** [comment]
This feature is still non-functional on MacOS 10.13.4 using GPMDP 4.5.0
