### ISSUE TITLE
When did the WindowManager.getAll('main') method obtain results that were not unique?

### ISSUE THREAD

**Issue by Linbubin** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2605]
the code is [this](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/d40f511531e2966f9aa2917201a6cf6a9a7ff7a6/src/main/utils/Emitter.js#L39-L46)

```
  sendToWindowsOfName(name, event, ...details) {
    const windows = WindowManager.getAll(name);
    _.forEach(windows, (window) => {
      if (window) {
        this._send(window, event, ...details);
      }
    });
  }
```

I would like to ask under what circumstances, the result is not unique?
because i always find `WindowManager.getAll('main') ====> [object BrowserWindow]'

**Comment by MarshallOfSound** [comment]
With our uses, normally `getAll` returns a single window but the point is, in the future it is API safe to return multiple.
