### ISSUE TITLE
My library tabs difficult to read with Dark Theme

### ISSUE THREAD

**Issue by Stoppablemurph** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2606]
**OS:**
macOS Sierra 10.12.4
Desktop player version 4.3.0

**Issue Descriptions:**
Dark theme makes library tab text and background nearly the same color making it difficult to read. I use the "music library" page a lot so this must be a recent issue since I've never noticed it before.
![screen shot 2017-06-26 at 11 26 10 am](https://user-images.githubusercontent.com/5564311/27554442-4b236f30-5a63-11e7-8681-8b418eb5044c.png)

**Steps to Reproduce:**
Turn on dark theme in settings, go to "music library" page.

I've tried restarting the app and swapping between different themes, but no luck.

**Comment by MarshallOfSound** [comment]
See https://github.com/gmusic-utils/gmusic-theme.js/issues/73
