### ISSUE TITLE
How to verify the require file is successful

### ISSUE THREAD

**Issue by Linbubin** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2607]
i write the [code](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/2a67311f23cb991f2a15582df8f6ab279dc6bb97/src/renderer/windows/GPMWebView/index.js#L26-L28)
`require('./playback');`
to
`require('./playbackaaaaaa');`

When I ran the program again after compiling, why didn't show mistake in devtool ? How do I test whether the three require were really introduced?

Is something i miss?

**Comment by MarshallOfSound** [comment]
@Linbubin If you have Electron related questions can you please ask in the Electron Slack and people will answer.  In this case the error will show in the renderer dev tools not the console.

```
window.openGPMDevTools();
```

**Comment by Linbubin** [comment]
ok, thanks
