### ISSUE TITLE
code question

### ISSUE THREAD

**Issue by Linbubin** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2608]
[rendererEmitter.on](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/944c3f89635f26ab4ef693fca32cdb1f1e2fd13f/src/renderer/rendererEmitter.js#L102-L113) code is 
```
 on(event, fn) {
    const internalMethod = (internalEvent, ...internalDetails) => {
      if (this.ready) {
        this._call(fn, internalEvent, ...internalDetails);
      } else {
        this.q.push(this._call.bind(this, fn, internalEvent, ...internalDetails));
      }
    };
    if(event == 'navigate:gotourl'){console.log(this.q);}
    console.log('this.ready + ' + this.ready + 'event -- ' + event)
    this._internalEventWrappers[event] = this._internalEventWrappers[event] || {};
    this._internalEventWrappers[event][fn] = internalMethod;
    ipcRenderer.on(event, internalMethod);
  }

```

Why not use it directly
```
 on(event, fn) {
    ipcRenderer.on(event, fn);
  }
```

and  why set `the.ready` to `true or false`.

**Comment by MarshallOfSound** [comment]
I don't know why you keep asking questions about the code but githuh issues is not the place to ask such questions.  Ask in gitter not in the issues section.

**Comment by Linbubin** [comment]
Sorry, this is the first time I've heard about gitter. I apologize for the inconvenience.
next, i will ask question in gitter.
