### ISSUE TITLE
mac menu bar icon is too big

### ISSUE THREAD

**Issue by jbellenger** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#261]
Thanks for the great product! I'm loving it so far.
I feel silly saying this, but the menu bar icon is too big. Other icons have a small amount of vertical padding, whereas the gpmdp icon is flush with the top and bottom borders.

<img width="273" alt="screen shot 2016-03-06 at 4 49 30 am" src="https://cloud.githubusercontent.com/assets/1391805/13554224/32f2e474-e357-11e5-8c57-89e745ca9abb.png">

**Comment by MarshallOfSound** [comment]
Fixed in master already :+1:
