### ISSUE TITLE
Volume icon issue.

### ISSUE THREAD

**Issue by desilvakai** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2612]
**OS:** Windows 10 Pro

**Issue Descriptions:** Icon issue when lowering volume in app.

**Steps to Reproduce:** Lower the volume in the app.

---
**No Hover:**
![image](https://user-images.githubusercontent.com/29742319/27615306-171db0d4-5b5c-11e7-9e97-28e44b4290a8.png)

**Hover volume full:**
![screenshot_7](https://user-images.githubusercontent.com/29742319/27615315-27612034-5b5c-11e7-9582-1c932151ab7e.png)

**When volume lower than half:**
![screenshot_6](https://user-images.githubusercontent.com/29742319/27615241-a9ff50ac-5b5b-11e7-98c1-c9c25a0e2965.png)

**Comment by MarshallOfSound** [comment]
I don'y see a problem here, if you're talking about the slightly blured icon on the right, welcome to GPU rendering 😆

**Comment by desilvakai** [comment]
Not exactly blurred. It's two icons overlapping each other.

**Comment by jostrander** [comment]
I was just investigating. It is two icons being overlayed on the right. This is an issue on Google's end as they are not removing the right low volume icon on hover.

**Comment by jostrander** [comment]
@desilvakai Please raise an issue on the Google product forums https://productforums.google.com/forum/#!topicsearchin/play/category$3Amusic%7Csort:relevance%7Cspell:false

**Comment by desilvakai** [comment]
Ah, I do see the same thing is happening on the Google Play Music site. Nice one Google.

**Comment by MarshallOfSound** [comment]
Ah my bad, I was zooming in on my phone trying to see what was wrong 😆 

Another classic google bug 😄
