### ISSUE TITLE
Bug with scrobbling

### ISSUE THREAD

**Issue by nikita-nikiforov** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2615]
Hello! I've noticed a bug with scrobbling to last.fm. Sometimes player doesn't scrobble at all and can lose several tracks. And after that it began scrobble again, but scrobble a track twice. 
![screenshot](https://user-images.githubusercontent.com/19807104/27675808-2819e5de-5cb4-11e7-8243-c0bdc05f6db4.jpg)
![screenshot_1](https://user-images.githubusercontent.com/19807104/27675807-28171ae8-5cb4-11e7-8178-d3c470ddf425.jpg)

**Comment by nikita-nikiforov** [comment]
oops, I had 4.3.0 and haven't noticed a post about 4.4.0 update. will try it

**Comment by MarshallOfSound** [comment]
`4.4.0` will fix this 👍
