### ISSUE TITLE
Feature Request : Thumbs up in mini-player

### ISSUE THREAD

**Issue by Sdmulder** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2617]
OS: Windows 10

Issue Descriptions: As much as I love the mini-player, I really miss being able to 'like' a song or being able to see if the current song is 'liked'. Would this be something that can be added in the future? Thanks and keep up the great work!

Steps to Reproduce: Not and actual issue, just a feature request

**Comment by clambert11** [comment]
I just recently installed GPMDP and could have sworn it had this.  Today I was looking for it and it's not there.  It would we incredibly useful.

**Comment by clambert11** [comment]
So I noticed that this is indeed in the mini player but now I don't see it again.  There is a YouTube icon there now so maybe it's dependent upon that.

**Comment by MarshallOfSound** [comment]
Merging into https://github.com/GPMDP/gmusic-mini-player.js/issues/4

Note for people if you are listening to a radio station the thumbs will be visisble, for playlists and albums the shuffle / repeat buttons are visible

**Comment by Leviathan1753** [comment]
Any thoughts on putting thumbs up/down for playlists, too?  I add things to large playlists full of things I'm not sure I like just yet, so the thumbs are very useful not just for radio.

Perhaps just an option in the settings to allow choosing ourselves?

Thanks for all the hard work!

**Comment by Noggog** [comment]
Any thoughts on putting thumbs up/down for playlists, too? I add things to large playlists full of things I'm not sure I like just yet, so the thumbs are very useful not just for radio.

Perhaps just an option in the settings to allow choosing ourselves?

Thanks for all the hard work!
