### ISSUE TITLE
Duplicated tracks in last.fm

### ISSUE THREAD

**Issue by theLastOfCats** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2618]
**OS:** Windows 10 Pro with Latest Updates

**Issue Descriptions:** Duplicated songs in Last.fm without using Repeat1

**Steps to Reproduce:** Unstable
[Debug info](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/1114642/debug_info.zip)

![image](https://user-images.githubusercontent.com/3687591/27728906-643757b2-5d8c-11e7-933a-f394f80f854f.png)
![image](https://user-images.githubusercontent.com/3687591/27729013-d22754fc-5d8c-11e7-9b2a-03d990994a4c.png)
![image](https://user-images.githubusercontent.com/3687591/27729025-ddf3d4c2-5d8c-11e7-8443-28e2694dba52.png)

IMO, it's happens because track scrobble twice: after 50% passed and on the end.

**Comment by theLastOfCats** [comment]
Probably relates to #1614

**Comment by MarshallOfSound** [comment]
Fixed in master
