### ISSUE TITLE
It should be possible by clicking the notification to skip to next song.

### ISSUE THREAD

**Issue by KurrKurr** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#262]
It would be very nice to have a setting that enables, that when you click on the notification to skip to the next  song.
Since people also could like the curent behaviour of just dismissing the notification, the on-click-action of the ntification should be configurable.

**Comment by MarshallOfSound** [comment]
This is far too specific (not a large use case) and not very easily doable with electron

If/when electron supports click actions a bit better I'll look into it
