### ISSUE TITLE
Faint/non-existent text on dark mode

### ISSUE THREAD

**Issue by swanky9** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2620]
**OS:** 
Windows 8.1

**Issue Descriptions:**
Dark theme has display issues on certain text and back button on search bar.

**Steps to Reproduce:**
Whenever in dark mode.

Dark mode:
![image](https://user-images.githubusercontent.com/29820736/27764206-97418e40-5e61-11e7-98c0-e9159e8f06d0.png)

Light mode:
![image](https://user-images.githubusercontent.com/29820736/27764207-9df81a74-5e61-11e7-8897-88791a1f67f6.png)

**Comment by jostrander** [comment]
Fixed it in master. Will release in 4.4.0.
