### ISSUE TITLE
Album tiles shake when Hovered.

### ISSUE THREAD

**Issue by mohitkyadav** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2621]
**OS:Windows**

**Album tiles shake when hovered.**

**Steps to Reproduce:Review the hover property for all album tiles.**

**Comment by MarshallOfSound** [comment]
There is insufficient information in this issue report to act on, no screenshots, no reproduction steps and basically no information at all.

Please commend below with more information and this issue will be re-opened if appropriate, for now all I can assume is that it's GPM site bug.
