### ISSUE TITLE
Auto hide taskbar remains hidded.

### ISSUE THREAD

**Issue by mohitkyadav** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2622]
**OS:Windows**

**Issue Descriptions: I've enabled auto hide in taskbar settings. When I put my mouse down the screen as deep I can take, it never comes up and this happens only while using GPMDP.**

**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment]
Known upstream issue that will be fixed by an Electron bump
