### ISSUE TITLE
Feature Request: To play and maintain local library consisting of local music files.

### ISSUE THREAD

**Issue by tejaskasetty** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2624]
This issue has already been mentioned in  #2601 but I m mentioning it again.
Firstly, I know this is a wrapper for the web interface. But won't it be good to add a feature to support a library for the local music files. This way we don't have to keep playing the files from the server.
Even the mobile app supports the feature for playing just the downloaded only files (available locally). 
And on Linux based OS there are hardly any good music players. This would be the best player.
The player is really good and Linux based users would I think love it if it had the feature to play local files and maintain library on those files.

Secondly, I was using the app the other day and realised I opened the application while I was having connection problem. It was not able to establish connection and the whole app went white blank. 
I had to manually kill the process from terminal to start it over again after I connected it to the internet.
Instead, I woulld suggest to load the layout of the app even if we are offline and to then provide a prompt stating the problem in connection and may be then provide a button in the prompt to retry to establish the connection with the server.
This way there is something to look at and someway something to do  in a situation like this than just a blank screen. Once the connect is up  it can load the content for playing.

And if you are considering about adding the first feature that I mentioned, then you can allow the user to view and  access just the local library and make them available for playing when they are offline. Just like the mobile app.

**Comment by SolarLiner** [comment]
> And on Linux based OS there are hardly any good music players

[Lollypop](http://gnumdk.github.io/lollypop-web/) would like to have a word with you.

Also as I wrote in the other issue, playing local apps might be out of the scope of the project here, so local music might never be implemented.

**Comment by MarshallOfSound** [comment]
This has been discussed before, playing local music is not the intention of this player

**Comment by CorruptComputer** [comment]
Also, you don't have to restart the app. As with most electron programs you can just use `ctrl+R` to reload the window and it will connect.

**Comment by tejaskasetty** [comment]
@SolarLinear Thanks for the suggestion, I really didn't Know about it.

**Comment by tejaskasetty** [comment]
@MarshallOfSound Okay got it.. sorry for bringing it up again.

**Comment by tejaskasetty** [comment]
@CorruptComputer  `ctrl+R` does that fine. But I was suggesting a layout would be better instead of a blank screen for end users.
