### ISSUE TITLE
Wrong colors in dark scheme

### ISSUE THREAD

**Issue by dron247** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2625]
On dark theme there are some issues with content colors
![2017-07-04 16 24 31](https://user-images.githubusercontent.com/7688437/27821629-875b67d2-60d5-11e7-8903-1d01fc74dd38.png)

![2017-07-04 16 24 23](https://user-images.githubusercontent.com/7688437/27821647-9515955a-60d5-11e7-9356-577f798861ba.png)

**Comment by MarshallOfSound** [comment]
Fixed in master, will be released in 4.4.0
