### ISSUE TITLE
Occasional crash on startup

### ISSUE THREAD

**Issue by EudaldCardona** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2626]
I'm using windows 10 (creators update), and I've been experiencing occasional crashes when the app starts up. It mostly happens after my computer turns on (I have the option enabled in the desktop settings), but I recall it happening far less occasionally if I try to run it again. When it crashes, the window just disappears.

As suggested in #50, I can't find anything in the windows error logs, and Temp\GPMDP Crashes\debug.log doesn't exist. I already have `Microsoft Visual C++ 2012 Redistributable (x86)` installed.

This file generated at startup in the gpmdp crashes folder. I don't think it contains anything useful though.
[d5de9343-e235-43ec-bdd8-1c08670b7140.txt](https://github.com/MarshallOfSound/Google-Play,-Music-Desktop-Player-UNOFFICIAL-/files/1122740/d5de9343-e235-43ec-bdd8-1c08670b7140.txt)

**Comment by EudaldCardona** [comment]
http://www.osronline.com/page.cfm?name=Analyze gave this: https://gist.github.com/EudaldCardona/538287002e3ba8eb5109c65580b65a86

**Comment by jostrander** [comment]
I don't see anything of use here, what kind of crash are you looking at? White screen, "The program .. has stopped?"

**Comment by MarshallOfSound** [comment]
If the app crashes it is sending crash reports to my crashpad server which if significant enough I will either forward to the Electron repository or try to fix myself.  I haven't seen any major crashes on Windows recently, there have been a few network related things and a few bad memory things but nothing happening more than 10~ish times.

Without a crash dump appearing frequently for this issue I'm going to put it down to sporadic crashes which unfortunately just happen sometimes on windows 😆
