### ISSUE TITLE
Feature Request: option to hide tray icon

### ISSUE THREAD

**Issue by dansochor** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2627]
**OS:** Mac OS 10.12.5

**Issue Descriptions:** It would be nice to have the option to hide the tray icon on Mac OS. All of the controls I need are available on my keyboard, so I don't have much use for the tray dropdown.

**Steps to Reproduce:** Not a bug.

Thanks for the app. It's fantastic!

**Comment by SolarLiner** [comment]
+1 here on Ubuntu. I don't necessarily need that feature myself as I have enough horizontal space (or not enough tray icons?) but I can see how it could be useful.

**Comment by MarshallOfSound** [comment]
Discussed before, search through issues for reasoning as to why we keep saying no

**Comment by dansochor** [comment]
Ah, sorry, I should have known to look through the "Closed" issues. Thanks anyway!
