### ISSUE TITLE
How to open G.P.M.D.P. manually?

### ISSUE THREAD

**Issue by KnifeCat** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2628]
**OS** : Windows 10 Family (Quad-core 64-bits)

**Issue Descriptions** : So as you can see in the title, i cannot find a way out to open it manually. Like if it's closed (the PROCESS app), how do we open it back APART from restarting the WHOLE computer? I don't have it in my app list (in the G letter). Then when I search with Cortana (the search system), shows nothing. Is that normal? If it is not, should I yell in like : **AAAAAAAAAAAAAAAAAAAAA!!!!!** ? My ONLY question. About that app, I mean!

**Steps to Reproduce** : 

1. Close it

2. and there. you're in the same situation as me.

**Screenshots** : 
# Cortana Display (only)
![cortana](https://user-images.githubusercontent.com/29926671/27878186-5fb62f9e-618b-11e7-8419-4ca7c43d0701.png)
# App List (G Letter, useless info blurred)
![app list g letter](https://user-images.githubusercontent.com/29926671/27878187-5fcad412-618b-11e7-87e7-6758a3438504.PNG)

**Comment by jostrander** [comment]
Uninstall it like you would any other program, via Control Panel.

**Comment by KnifeCat** [comment]
I'll try it Sunday (i don't have it right now) Thanks!

**Comment by Alipoodle** [comment]
From previous issue like this!
It was a feature that was to check were about you have the shortcuts for GPMDP and it wouldn't recreate them!
For example when you first install the program it will create a shortcut on the home screen, some people don't like to keep it there, and will delete it. Upon updating the program will ignore updating / creating the file for the new patch.

Otherwise the shortcut's execution is 
`<USER>\AppData\Local\GPMDP_3\Update.exe --processStart Google%20Play%20Music%20Desktop%20Player.exe`

**Comment by KnifeCat** [comment]
Thanks!!

**Comment by KnifeCat** [comment]
By the way, thanks @jostrander and @Alipoodle , it helps me but I won't uninstall it. Preparing hell, and bla bla bla, having 11 000 songs, no. Maybe i have an idea..

## Feature Request ##
Maybe a 'Repair' function for in case it's broken or ;$+@+"&-# stuff. Please!

_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by KnifeCat** [comment]
One day, the creator might check this.
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz

**Comment by jostrander** [comment]
This is a free project supported by none other than volunteer efforts. If you have something constructive feel free to open an issue with detailed information about what you have tried, and what you are having a problem with. There is no need to voice your inner dialogue when creating an issue, just get to the point and state your case. Just to reiterate:

> A bug is a demonstrable problem that is caused by the code in the repository. Good bug reports are extremely helpful - thank you!

> Isolate the problem — try determine the cause or probable cause of the bug and maybe even include a reference to a line in the code.
 
From what it sounds like to me, you deleted the shortcut at some point, and during an update the shortcut will no longer be created. The solution is to uninstall the program and reinstall it, or create a shortcut using the path that @Alipoodle mentioned.

**Comment by KnifeCat** [comment]
I mean...no! I have NOT deleted the shortcut!! It REALLY did NOT create it...
I will open a new issue later about it...
(i hate when we miss respect on me)
