### ISSUE TITLE
Plantronics Voyager Focus UC headset has trouble communicating with GPMDP

### ISSUE THREAD

**Issue by henryb94** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2629]
**OS:**
Windows 7 64-bit

**Issue Descriptions:**
Using the Plantronics Voyager Focus UC headset with my phone or Spotify over bluetooth, the music pauses automatically when I remove the headset and plays again when I put it back on.  Neither this feature nor the play/pause, skip forward, and skip backward buttons on the headset communicate with GPMDP.

I tried running LLKeyboardTest, and saw no keypresses detected with any buttons or with removal of/putting on the headset.

**Steps to Reproduce the Problem**
1. Open GPMDP
2. Play music
3. Remove headset
4. Music doesn't pause

Thanks, HB

**Comment by KnifeCat** [comment]
If you are using a Realtek driver, that is why. Windows cannot access the headphones input when Realtek does. 

# What does this means?
Litterally i'm not saying that you will never be able to, but you have an audio board, and if you change it you might screw up the thing.

# What does this do?
It does that Realtek just transfer the PC audio to the headphones without communicating with Windows. (it may open you a window that asks you which type of headphones you have, then it send the info to the Realtek driver then boom) So Windows just thinks he's still on speakers but it does not know that it's on headphones.

# I'm on Bluetooth!
**Upgrade to Windows 10.**



# Have I missed anything? Comment me!

**Comment by henryb94** [comment]
Hi KC, I am connected through a USB dongle, which shows up as a USB audio device independent from Realtek HD Audio in devmgmt, and Windows correctly identifies the playback device as "Headset Earphone, Plantronics BT600."  I tried pairing through Bluetooth directly to the computer with no more success.  Unfortunately, I can't upgrade to Windows 10 as this is a work computer.

**Comment by KnifeCat** [comment]
Aww sorry man. I meant I was using the headphone plug and not the U.S.B. plug. Maybe installing the drivers? Or remove the device from your paired devices and pair it back **WITHOUT** disconnecting or whatever stuff!

**Comment by KnifeCat** [comment]
By drivers I mean maybe an BT600 app or a patcher or a..you know

**Comment by MarshallOfSound** [comment]
> I tried running LLKeyboardTest, and saw no keypresses detected with any buttons or with removal of/putting on the headset.

If no keypresses are being sent through then I have no idea how the headset would be sending a pause command (especially on windows 7).

It has probably been specifically implemented like logitech keyboards to recognize certain media players and only send keypresses / events when they are active.  GPMDP is probably not on that list.  (This is just a guess).

There isn't anything really we can do about this if the headset doesn't emit any events 😢
