### ISSUE TITLE
Feature request:  Add navigation buttons

### ISSUE THREAD

**Issue by JeffIsTheCorn** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2631]
**OS:**  Windows

**Issue Descriptions:**  There need to be forward and back buttons added so that if someone clicks on an album they don't have to go back to the very top of one of the sidebar pages to find their way back to where they were originally.

**Steps to Reproduce:**  Not an issue, just a feature request.

**Comment by MarshallOfSound** [comment]
There is a back button on the right of the search bar

**Comment by JeffIsTheCorn** [comment]
Oh I kinda see now, but with dark theme it is almost the exact same color as the search bar and pretty impossible to see, so I guess the color just needs to be changed.
