### ISSUE TITLE
"Browse stations" does not work with dark theme

### ISSUE THREAD

**Issue by JeffIsTheCorn** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2632]
**OS:**  Windows

**Issue Descriptions:**  The "Browse stations option is completely unusable when using the dark theme.  Perfectly fine with light theme.

**Steps to Reproduce:**  Desktop settings > Custom theme > Dark, then click on "Browse stations."

**Comment by MarshallOfSound** [comment]
Fixed in `4.4.0` release should be going out ASAP

**Comment by kmroz0991** [comment]
Any update on 4.4.0 for the MAC release?
