### ISSUE TITLE
Issue with starting app

### ISSUE THREAD

**Issue by matthewbrown1234** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2633]
I have an issue starting app after installing dependencies and running build.
**OS**: Distributor ID:	Ubuntu
      Description:	Ubuntu 16.04.2 LTS
      Release:	16.04
      Codename:	xenial

**NPM START LOGS**:

> google-play-music-desktop-player@4.4.0 prestart /home/matt/Workspace/JavaScript/Google-Play-Music-Desktop-Player-UNOFFICIAL-
> pre-flight && node vendor/patch_dev.js && electron-rebuild --types=prod,optional

Starting pre-flight checks
Processing production dependencies
Processing development dependencies
Processing optional dependencies
Dependencies are all up to date, looking good!
✖ Rebuild Failed
An unhandled error occurred inside electron-rebuild
Package expat was not found in the pkg-config search path.
Perhaps you should add the directory containing `expat.pc'
to the PKG_CONFIG_PATH environment variable
No package 'expat' found
gyp: Call to 'pkg-config  --libs-only-l --libs-only-other expat' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/matt/Workspace/JavaScript/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.8.0-58-generic
gyp ERR! command "/usr/local/bin/node" "/home/matt/Workspace/JavaScript/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/.bin/node-gyp" "rebuild" "--target=1.6.1" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd /home/matt/Workspace/JavaScript/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/dbus
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

Failed with exit code: 1

Error: Package expat was not found in the pkg-config search path.
Perhaps you should add the directory containing `expat.pc'
to the PKG_CONFIG_PATH environment variable
No package 'expat' found
gyp: Call to 'pkg-config  --libs-only-l --libs-only-other expat' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/matt/Workspace/JavaScript/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.8.0-58-generic
gyp ERR! command "/usr/local/bin/node" "/home/matt/Workspace/JavaScript/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/.bin/node-gyp" "rebuild" "--target=1.6.1" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd /home/matt/Workspace/JavaScript/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/dbus
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

Failed with exit code: 1
    at SafeSubscriber._error (/home/matt/Workspace/JavaScript/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/spawn-rx/lib/src/index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (/home/matt/Workspace/JavaScript/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/rxjs/Subscriber.js:238:16)
    at SafeSubscriber.error (/home/matt/Workspace/JavaScript/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/rxjs/Subscriber.js:197:26)
    at Subscriber._error (/home/matt/Workspace/JavaScript/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/rxjs/Subscriber.js:128:26)
    at Subscriber.error (/home/matt/Workspace/JavaScript/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/rxjs/Subscriber.js:102:18)
    at MapSubscriber.Subscriber._error (/home/matt/Workspace/JavaScript/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/rxjs/Subscriber.js:128:26)
    at MapSubscriber.Subscriber.error (/home/matt/Workspace/JavaScript/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/rxjs/Subscriber.js:102:18)
    at SafeSubscriber._next (/home/matt/Workspace/JavaScript/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/spawn-rx/lib/src/index.js:241:65)
    at SafeSubscriber.__tryOrSetError (/home/matt/Workspace/JavaScript/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/rxjs/Subscriber.js:247:16)
    at SafeSubscriber.next (/home/matt/Workspace/JavaScript/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/rxjs/Subscriber.js:187:27)

npm ERR! Linux 4.8.0-58-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! google-play-music-desktop-player@4.4.0 prestart: `pre-flight && node vendor/patch_dev.js && electron-rebuild --types=prod,optional`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the google-play-music-desktop-player@4.4.0 prestart script 'pre-flight && node vendor/patch_dev.js && electron-rebuild --types=prod,optional'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the google-play-music-desktop-player package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     pre-flight && node vendor/patch_dev.js && electron-rebuild --types=prod,optional
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs google-play-music-desktop-player
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls google-play-music-desktop-player
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/matt/Workspace/JavaScript/Google-Play-Music-Desktop-Player-UNOFFICIAL-/npm-debug.log

**NPM-DEBUG.LOG:**
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle google-play-music-desktop-player@4.4.0~prestart: google-play-music-desktop-player@4.4.0
6 verbose lifecycle google-play-music-desktop-player@4.4.0~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle google-play-music-desktop-player@4.4.0~prestart: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/matt/Workspace/JavaScript/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
8 verbose lifecycle google-play-music-desktop-player@4.4.0~prestart: CWD: /home/matt/Workspace/JavaScript/Google-Play-Music-Desktop-Player-UNOFFICIAL-
9 silly lifecycle google-play-music-desktop-player@4.4.0~prestart: Args: [ '-c',
9 silly lifecycle   'pre-flight && node vendor/patch_dev.js && electron-rebuild --types=prod,optional' ]
10 silly lifecycle google-play-music-desktop-player@4.4.0~prestart: Returned: code: 255  signal: null
11 info lifecycle google-play-music-desktop-player@4.4.0~prestart: Failed to exec prestart script
12 verbose stack Error: google-play-music-desktop-player@4.4.0 prestart: `pre-flight && node vendor/patch_dev.js && electron-rebuild --types=prod,optional`
12 verbose stack Exit status 255
12 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at EventEmitter.emit (events.js:191:7)
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at ChildProcess.emit (events.js:191:7)
12 verbose stack     at maybeClose (internal/child_process.js:852:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
13 verbose pkgid google-play-music-desktop-player@4.4.0
14 verbose cwd /home/matt/Workspace/JavaScript/Google-Play-Music-Desktop-Player-UNOFFICIAL-
15 error Linux 4.8.0-58-generic
16 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
17 error node v6.3.1
18 error npm  v3.10.3
19 error code ELIFECYCLE
20 error google-play-music-desktop-player@4.4.0 prestart: `pre-flight && node vendor/patch_dev.js && electron-rebuild --types=prod,optional`
20 error Exit status 255
21 error Failed at the google-play-music-desktop-player@4.4.0 prestart script 'pre-flight && node vendor/patch_dev.js && electron-rebuild --types=prod,optional'.
21 error Make sure you have the latest version of node.js and npm installed.
21 error If you do, this is most likely a problem with the google-play-music-desktop-player package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     pre-flight && node vendor/patch_dev.js && electron-rebuild --types=prod,optional
21 error You can get information on how to open an issue for this project with:
21 error     npm bugs google-play-music-desktop-player
21 error Or if that isn't available, you can get their info via:
21 error     npm owner ls google-play-music-desktop-player
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]

**Comment by jostrander** [comment]
Have you looked at the dev FAQ? I believe you are missing lib-expat dev which is required on Ubuntu.

**Comment by jostrander** [comment]
Closing due to lack of response. If you are still having issues feel free to let us know.
