### ISSUE TITLE
app stuck at loading music collection

### ISSUE THREAD

**Issue by maddanio** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2635]
**OS:**
OSX Sierra

**Issue Descriptions:**
App stuck at loading music collection ("Meiner Musik" in my case, german).

**Steps to Reproduce:**
Download and start.

Just realizing that not being able to use your app really lowers the overall value of google play for me. Google should really be paying you for this!

Is there anything else I can do to triage this?

**Comment by bsberry** [comment]
Hitting this too.

**Comment by jostrander** [comment]
Is this still an issue? I haven't had this happen to me yet so I can't really debug anything. Some times Google will push out A/B versions of the site to test things and you both may have been apart of one of those tests.

**Comment by bsberry** [comment]
Yeah, it stopped happening on its own for me.

**Comment by MarshallOfSound** [comment]
> Yeah, it stopped happening on its own for me.

Sounds like google broke something, and then fixed it 👍 Closing unless people are still experiencing this
