### ISSUE TITLE
Feature Request: Minimize to Mini Player

### ISSUE THREAD

**Issue by Nealon01** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2636]
Could you add the option to defaulting minimizing to going to the mini player instead of the taskbar?

**Comment by MarshallOfSound** [comment]
As an option this doesn't make much sense to me, normally options like this would be added to improve user experience.  In this case all it does is change which button you need to click.  It will still be a one click action to reach mini player mode.

Gonna say `wontfix` on this one for now 👍
