### ISSUE TITLE
can't install on win7

### ISSUE THREAD

**Issue by Linbubin** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2637]
when i run `npm install`

it throw error
![image](https://user-images.githubusercontent.com/19225429/28112204-b6f29212-672a-11e7-9658-0fe693be3a3e.png)

what should i do?

node -- v6.11.0
electron -- v1.6.11
win7

**Comment by MarshallOfSound** [comment]
You should read the [dependencies](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/Development-FAQ#dependencies) section of the development FAQ
