### ISSUE TITLE
Windows - Taskbar controls gone after minimizing to tray and restoring

### ISSUE THREAD

**Issue by KurrKurr** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#264]
I think I found a bug on Windows.

How to reproduce:

- Start the application.
- Hover over the taskbar icon, you'll see the taskbar playback controls
- Click on the "X" to minimize the application to the tray area.
- Double click on the tray icon, or right click the tray icon an select "Show" to restore the window.
- Hover over the taskbar icon again
- No playback controls are available anymore.

What's expected:
After restoring the window, the playback contrls should be available like they are before minimizing to tray.

**Comment by MarshallOfSound** [comment]
I have an open bug report on `atom/electron` regarding this

https://github.com/atom/electron/issues/4514
