### ISSUE TITLE
scrobble to last.fm broken

### ISSUE THREAD

**Issue by stvnjohnson** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2640]
**OS:** Windows 10

**Issue Descriptions:** Songs do not get scrobbled to last.fm unless you pause them sometime after the 50% milestone is hit.  If I look in last.fm at my recent tracks, i can see that my current song is correct, but when a new song begins to play, the current song changes without pushing the previously listened to track to the scrobble list.

This doesn't seem to be an issue with last.fm servers, since when I listen to music on my phone, the tracks scrobble correctly.

**Steps to Reproduce:**  Let songs play from an album back to back without stopping or pausing while watching the recent tracks list on last.fm.  You will see the current song update once the second song starts without the first song being added to the recent tracks list.

**Comment by MarshallOfSound** [comment]
Fixed in 4.4.0 which will be released asap

**Comment by stvnjohnson** [comment]
I've downloaded the most recent release this morning, but it actually seems to have made the scrobbling issue worse on my end.  Now, even if you pause the song after the 50% milestone it still doesn't ever scrobble to the recent tracks list, although "scrobbling now" still shows the song your currently playing.

**Comment by stvnjohnson** [comment]
Actually, what i'm noticing is that if the player is the active window, it appears it will scrobble to the recent tracks list correctly.  I've noticed that the track progress in the task bar doesn't update when the player isn't the active window, so I wonder if this is somehow related?

**Comment by jostrander** [comment]
Known issue, check #2630 for updates.
