### ISSUE TITLE
Feature request: Display options

### ISSUE THREAD

**Issue by CuraeL** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2642]
Sorry, I dunno if this can be done through CSS or something. I just wanted to ask if it was possible to do a bigger piece of artwork and possibly keep the song list on the one side of the player. I use the player on a portrait monitor and I thought "This song list sure takes up a lot of space!" Anyways. I love this player! I just wanted to ask if it's doable to do something like on my photo below? Rearranging the UI.

Thanks for reading.

![optional](https://user-images.githubusercontent.com/30218051/28250642-250b3362-6a6e-11e7-8e75-dd55548f2663.jpg)

![optional2](https://user-images.githubusercontent.com/30218051/28252211-f942c404-6a8e-11e7-8532-7cbe46c3a164.jpg)

**Comment by jostrander** [comment]
Feel free to play with the custom GPMDP css to see if you can build this, but at this time modifications such as this are beyond the scope of the project.
