### ISSUE TITLE
Tray icon is missing on Fedora 26

### ISSUE THREAD

**Issue by agurenko** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2644]
**OS:**
Fedora 26 KDE

**Issue Descriptions:**
After upgrading my laptop from Fedora 25 to Fedora 26 tray icon disappeared. I had same issue on my Fedora 26 during Beta stage, so I would assume some package update broke it.

**Steps to Reproduce:**
Install GPMDP on Fedora 26

**Comment by jostrander** [comment]
How did you install GPMDP? Did something change between Fedora 25 and 26 that would have effected the location the icon is in the installer package?

**Comment by agurenko** [comment]
I've installed it like I always did with sudo dnf install ./local_file.rpm. I have a system that was upgraded from F25 to F26 and it disappeared right after.

**Comment by MarshallOfSound** [comment]
This is an issue fixed upstream in Electron due to the window manager environment variable changing between versions (Assuming you are using gnome).  Will be fixed in an Electron update
