### ISSUE TITLE
Feature request: Upload music

### ISSUE THREAD

**Issue by winterstein** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2645]
Could you add an Upload Music feature?
The Google chrome app has this -- but it's slow and kind of flaky. Hopefully a desktop version can improve the flakiness.

PS - Thank you for making this.

**Comment by jostrander** [comment]
This has been discussed before and it's not something we want to tackle at this time. There are quite a few binaries and a ton of  obfuscated code to try and figure out.
