### ISSUE TITLE
"Browse stations" menu styles missed up. 

### ISSUE THREAD

**Issue by chrisroselli** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2649]
**OS:**
macOS Sierra 10.12.1
**Issue Descriptions:**
"Browse stations" menu styles missed up. Links are white on white background. With gray hover background-color.
**Steps to Reproduce:**
Top left burger menu icon, "Browse stations".

**Comment by MarshallOfSound** [comment]
Please check closed issues (as it says in the issue template) before raising new ones.  This has been fixed and will be out next release
