### ISSUE TITLE
Typo on Website

### ISSUE THREAD

**Issue by krumble1** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2651]
**Issue Description:**

On the googleplaymusicdesktopplayer.com website, under the heading **Open Source**, the first paragraph reads, "Google Play Music Desktop Player is open source on GitHub this means YOU, the community..."

It seems to me there is a missing period and capitalization and was intended to read as follows: "...open source on GitHub. This means..."

As an aside, I freaking love GPMDP and thanks so much for all the hard work you do!
--Krumble

**Comment by jostrander** [comment]
Fixed, just need @MarshallOfSound to sync the website to the repo.
