### ISSUE TITLE
No scrollbar for long list of chromecast devices on windows

### ISSUE THREAD

**Issue by meggiman** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2652]
**OS:** Windows 10 Pro N
Build: 14393.1480

**Issue Descriptions:** 
There is no scrollbar if the list of available chromecast devices entries fill up the available vertical space. The last visible entries are rendered outside of the list's borders (see screenshot).

**Steps to reproduce:** 
Resize the application to have less vertical space available than the number of list entries and click on the cast button. The issue exists as well in fullscreen mode when there are too many entries (17 enries in my case at display resolution 1920x1080).

Screenshot of resized window:
![gpmdp-issue](https://user-images.githubusercontent.com/7403253/28464675-8648f0f4-6e26-11e7-8c7a-d7b51b23b22a.PNG)

**Comment by jostrander** [comment]
Thanks for the concise bug report. This should be fairly simple to fix, I just never had 17 devices to test the UI with.

**Comment by MarshallOfSound** [comment]
Dayum, that's a lost of chromecasts 😆
