### ISSUE TITLE
Exiting from mini-player mode opens sidebar and increases font-size

### ISSUE THREAD

**Issue by alikashani** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2653]
**OS:**

Mac OS X - El Capitan

**Issue Descriptions:**

Maximizing from Mini-Player causes left-hand sidebar to open and font-size seems to increase as well.

**Steps to Reproduce:**

1. Select random song
2. Minimize to mini-player
3. Maximize to exit mini-player mode
4. Observe sidebar is now open and font-size has increased from previous size.

**Comment by jostrander** [comment]
Confirmed on the sidebar being opened. Can't confirm on the font-size.

**Comment by PunchyRascal** [comment]
Something like this happened to me to, the font and everything else was so huge I couldn't do anything about it. Had to restart the app.

**Comment by slugger7** [comment]
The font size is huge on mine after doing this. I have to close the application down and start up again to have it useable

**Comment by MarshallOfSound** [comment]
Merging into #2269
