### ISSUE TITLE
Add more help to the desktop-settings window

### ISSUE THREAD

**Issue by gitgetgot** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2655]
Hi,
some settings (actually, only one) lack information, the user could use to understand what he/she/it is changing.

example:
Enable JSON API (what happens, if disabled? what is ist good/bad for?)

**Comment by MarshallOfSound** [comment]
The JSON API and the playback API are two more advanced features of this applications and normally should only be enabled when told to by a third party wishing to use them (for instance the Android remote application).  Documentation on those two API's can be found here

* [JSON API](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/docs/PlaybackAPI.md)
* [Playback API](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/docs/PlaybackAPI_WebSocket.md)

In terms of not knowing what the setting does, there isn't enough space in a settings table to explain every option completely.  My general motto is if you don't know what the switch does, don't mess with it 😆 All the options users need to know how to use are self-explanatory, only the JSON and Playback API switches are more advanced

**Comment by gitgetgot** [comment]
Thank you!
