### ISSUE TITLE
Page refreshes when adding songs from one playlist to another

### ISSUE THREAD

**Issue by ntowl24** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2656]
**OS: Windows 10:**

**Issue: When adding songs from one playlist to another via right click or the 3 dot menu, This causes quite a few problems when trying to sort through songs to make a new playlist. This behavior does not occur in the browser version of Play Music.**

**Steps to Reproduce:**

1. Select on song or multiple songs in a playlist
2. Add songs to another playlist
3. Page refreshes and goes all the way to the top causing you to lose your place

**Comment by jostrander** [comment]
Can not confirm this one. Just tried multiple ways. I dragged from the current queue to the playlists slide out. I used the three dot menu, and added the song via right click menu.

**Comment by snhardin** [comment]
This is happening for me as well. See more specs and info at #2657.

**Comment by BLTsndwch** [comment]
Also happening for me, but I get the exact same refresh on changes to a playlist in browser (Chrome) as well. Usually doesn't happen until the 5th playlist "action" though. (Adding, removing, or re-ordering songs being an "action.")

**Comment by snhardin** [comment]
I just tried it in the browser. Yeah, it's doing it there as well. Probably not a GPMDP problem.

**Comment by MarshallOfSound** [comment]
> Probably not a GPMDP problem.

Sounds like unfortunate A/B testing, would just hold out for google to issue a fix for it 👍
