### ISSUE TITLE
Last.FM scrobbling only scrobbles the first song

### ISSUE THREAD

**Issue by andrejmk** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2658]
OS: Windows 10

Issue Description: Last.fm scrobling is still broken in version 4.4..0. Every song scrobbled to last.fm, except the first one, is not saved to last.fm.

I tried to log out and log in again to last.fm through the app, but it's still the same.

**Comment by whiplash159** [comment]
I think that this issue is connected with [https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/2609#issuecomment-314380558](url)

**Comment by jostrander** [comment]
I concur. If you leave the window open will it scrobble fine?

**Comment by MarshallOfSound** [comment]
Repro'ed and merging into #2630

the progress event isn't emitted while minimized so the scrobble will never happen
