### ISSUE TITLE
Progress not updated on taskbar icon

### ISSUE THREAD

**Issue by goszczynskip** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2659]
**OS:**
Windows 10 ver. 1703 build 15063.483
GPMDP version: 4.4.0

**Issue Descriptions:**
Progress on taskbar icon is not updated when app is minimalized.

**Steps to Reproduce:**
Minimalize application while it is playing music.

**Comment by jostrander** [comment]
Duplicate of #2630. Please track it there.

**Comment by MarshallOfSound** [comment]
Merging into #2630

**Comment by MarshallOfSound** [comment]
Dayum, beat me by milliseconds @jostrander 😆
