### ISSUE TITLE
Tray icon for Ubuntu 17

### ISSUE THREAD

**Issue by ostapch** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2660]
I can't see tray icon on Ubuntu 17. I know that it is electron bug and I also know that this bug fixed in latest electron version. So can you update electron?

**Comment by MarshallOfSound** [comment]
> So can you update electron?

This is a risky process that involves lots of manual testing (I'm currently in the process of doing this with `electron@1.7.5`).  If there aren't any blocking issues while I test it the next release will have `1.7.5` included
