### ISSUE TITLE
Ubuntu 17.04 install - missing dep + app not working

### ISSUE THREAD

**Issue by cprn** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2661]
**OS:**
Ubuntu 17.04 (up to date), behind proxy (never mattered before but now I see update server errors).

**Issue Descriptions:**
On freshly installed system installation process is painful and ends up with failure. Player opens but displays blank white window, can't play music or do anything else including quit, has to be killed.

**Steps to Reproduce:**

First of all, it's not in the official repos and I couldn't find any PPA. Installed by downloading .dep and then:
```sh
sudo dpkg -i google-play-music-desktop-player_4.4.0_amd64.deb
```

It complains about missing dependencies, so:
```sh
sudo apt install -f
```

Got installed but complains about missing `gconf2` lib, which I think should be listed as dependency, so:
```sh
sudo apt install gconf2
```

Now it runs but displays blank white window. With `--disable-gpu` it runs, shows the loader circle, then blank white window but at least its possible to open `DEBUG_INFO`:
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/1173464/debug_info.zip)

Fully reproducible.

**Comment by jostrander** [comment]
Have you tried following the install docs for deb/ubuntu?

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/docs/Installation_On_Debian.md

**Comment by cprn** [comment]
I didn't find it before, maybe it's my ignorance, sorry. Nevertheless, I removed everything and installed according to these instructions, I think it downloaded slightly newer version (`4.4.0-1`, no?) but the only difference is I don't have to use `--disable-gpu`. Other than that, nothing changes. There's still just blank white window.

I'm starting to think it's because there's some connectivity problem. It seems to complain about missing `avahi` but Ubuntu 17.04 comes with the following packages:

```sh
$ dpkg -l | grep -i avahi
ii  avahi-autoipd                                0.6.32-1ubuntu1                          amd64        Avahi IPv4LL network address configuration daemon
ii  avahi-daemon                                 0.6.32-1ubuntu1                          amd64        Avahi mDNS/DNS-SD daemon
ii  avahi-utils                                  0.6.32-1ubuntu1                          amd64        Avahi browsing, publishing and discovery utilities
ii  libavahi-client3:amd64                       0.6.32-1ubuntu1                          amd64        Avahi client library
ii  libavahi-common-data:amd64                   0.6.32-1ubuntu1                          amd64        Avahi common data files
ii  libavahi-common3:amd64                       0.6.32-1ubuntu1                          amd64        Avahi common library
ii  libavahi-core7:amd64                         0.6.32-1ubuntu1                          amd64        Avahi's embeddable mDNS/DNS-SD library
ii  libavahi-glib1:amd64                         0.6.32-1ubuntu1                          amd64        Avahi GLib integration library
```

Am I missing something? I'm using same proxy settings as with `16.04` and there was no problem then.

**Comment by jostrander** [comment]
I'm not sure, but generally the white screen of death is due to an exception being thrown and not handled. Usually it has something to do with network or firewall settings causing an exception in the main process which will cause it to fail to continue executing. As for what's causing that issue, I'm not sure.

**Comment by cprn** [comment]
How can I test connectivity or where do I find instructions on setting proxy in `gpmdp` or debugging it? I think I need to make sure it uses my connection settings and doesn't try to connect directly. It's office network and I can't test it without proxy to make sure that's an issue but I'm pretty convinced it is. I didn't had that problem on Ubuntu 16.04 but there might be due to some minor difference between my old and current config.

**Comment by MarshallOfSound** [comment]
@cprn The FAQ should be open to edits 👍 

That said Electron does try to automatically detect your proxy setup but sometimes it just can't figure it out
