### ISSUE TITLE
UI/Controls often persist after hover on mini-player.

### ISSUE THREAD

**Issue by ScottBeeson** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2663]
**OS:**
Windows 10 "Creator's Update"

**Issue Descriptions:**
Hover end/onMouseOut event doesn't always trigger the UI hide in mini mode.  Note that this is definitely intermittent behavior.  I have not been able to correlate any external factors (focus, idle, clicks, etc).

**Steps to Reproduce:**
Put player in mini mode.  Hover over to see song info, resume working.

**Comment by ScottBeeson** [comment]
Attaching video

[hover.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/1174306/hover.zip)

**Comment by jostrander** [comment]
Interesting. It seems the speed at which you enter/exit causes the UI to stick. I assume there's some sort of debounce and or smoothing going on that's preventing the right event from happening.

**Comment by ScottBeeson** [comment]
To me it seems like it could be when the mouseExit event happens at the very end of the fadeIn animation, but I can't be sure.

**Comment by MarshallOfSound** [comment]
This is a known issue with frameless Electron windows and currently has no plans to be fixed.  Other apps like slack also exhibit this issue with their custom window controls hover effect

**Comment by ScottBeeson** [comment]
That sucks a lot :(
