### ISSUE TITLE
Show Album Cover command not working in full music player

### ISSUE THREAD

**Issue by damiong28** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2666]
OS: macOS Sierra 10.12.5

Issue Descriptions: Show Album Cover command not working in full music player

Steps to Reproduce: While not in mini player, verify none of the following causes the album cover to appear or disappear (album cover expected to take up entire view). 

1. Click the album artwork in the bottom left. 
2. Hit the Shift+Command+C hotkey to show album cover.  
3. Go to View, click Show Album Cover.

I think there used to be white arrows that appeared when hovering over the mini album artwork, if so I don't see them now.

Great app, thanks for the hard work!

[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/1177866/debug_info.zip)

**Comment by jostrander** [comment]
Google has removed the album art visualizer as well as the particle effects visualizer and recent updates. We may be able to emulate the album art static viewer in future updates.

**Comment by damiong28** [comment]
That would be cool. What do you think about removing the View > Show Album Cover option until it is released?

**Comment by jostrander** [comment]
We'll add it to the to-do list.
