### ISSUE TITLE
Feature Request: Save song locally for use in other music playing apps or to burn CDs etc.. (unencrypted mp3)

### ISSUE THREAD

**Issue by ddarvish** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2667]
Pretty much like my title says, please allow us to save songs locally as an unencrypted mp3 for use in other apps.. possibly even add access to our library via GMusicFS implementation ..

**Comment by MarshallOfSound** [comment]
This goes against Googles ToC, we can't offer download services

**Comment by ddarvish** [comment]
ummm.. isnt this app technically against their TOS.. you are making use of
an API that is not publically available or meant to be used. why not make
it a hidden option that people can enable... you can let the individual
decide if they are going to violate the TOS or not..



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=ddarvish@gmail.com&idSignature=22>


*Davis Solomon Darvish*   Awesome Scientist Guy
[image: photo] Phone: 310.300.1337
Fax: 707.221.7039
Email: ddarvish@gmail.com
Website: DavisDarvish.com
<https://mailtrack.io/trace/link/8932507efb27f94844eda7cb5465265235ded602?url=http%3A%2F%2FDavisDarvish.com&userId=1202927&signature=3c0735053ec3352f>
Wiseintro: wiseintro.co/davisdarvish
<https://mailtrack.io/trace/link/aca61f216f94227e2d0d3da9d42f51e99d10fe86?url=http%3A%2F%2Fwiseintro.co%2Fdavisdarvish&userId=1202927&signature=4cbd15c3813c3244>
<https://mailtrack.io/trace/link/dd156121a690794fd74ff612286134971ef71624?url=http%3A%2F%2Fus.linkedin.com%2Fin%2Fdavisdarvish&userId=1202927&signature=196f8b5f6abc3f41>

<https://mailtrack.io/trace/link/803a91441975105b26362648a7a68e9644ff5f33?url=http%3A%2F%2Ftwitter.com%2Fdavisdarvish&userId=1202927&signature=f0532180970fb9ea>

<https://mailtrack.io/trace/link/c7ee3d3d32192a0d75e74aadde7bb87b5b552ef2?url=http%3A%2F%2Fwiseintro.co%2Fdavisdarvish&userId=1202927&signature=243a1c4c2571cf9e>
IMPORTANT: The contents of this email and any attachments are confidential.
They are intended for the named recipient(s) only. If you have received
this email by mistake, please notify the sender immediately and do not
disclose the contents to anyone or make copies thereof.

**Comment by MarshallOfSound** [comment]
>  you are making use of an API that is not publically available or meant to be used.

We don't use an private google API's??

**Comment by SolarLiner** [comment]
Actually the app isn't using any Google API at all; at least not for the music player directly. The app is just a native wrapper around the web version of Google Play Music. But I am pretty sure that crawling the website to download tracks is against some policy or ToS somewhere.
