### ISSUE TITLE
Broken Last.FM scrobbling since last update

### ISSUE THREAD

**Issue by FunFrog-BY** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2668]
OS: Win10x64
Issue Descriptions: Last FM scrobbling stopped working since last update. There was something about last.fm in the update description, so i checked my last.fm profile and "now playing" is working, but composition won't saving in last.fm history.
Steps to Reproduce: Just listen music with last.fm scrobbling enabled.

**Comment by MarshallOfSound** [comment]
See #2630
