### ISSUE TITLE
Linux config folder change

### ISSUE THREAD

**Issue by dpeukert** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#267]
The config folder on Linux should really be `~/.GPMDP_STORE` or `~/.config/GPMDP_STORE` instead of `~/GPMDP_STORE`. That way there wouldn't be an extra visible folder in the user's home directory, which many people (including me) don't like.

**Comment by MartijnBraam** [comment]
It should get put it in `$XDG_CONFIG_DIR/GPMDP` to store config (and use .config/GPMDP if the variable doesn't exist) and use `$XDG_CACHE_DIR/GPMDP` for cache

**Comment by ryux2** [comment]
Is this file cache or preferences? Looks to hold cached playstate.

Patched the paths to point to cache. Have only tested on Linux. 
750dc9bc6a7c8c37232ef41a5a0e73ff62fab482

**Comment by InAnimaTe** [comment]
I actually don't think this needs to be capitalized either. Following convention here, especially on Linux, is pretty important and should be done ;)
