### ISSUE TITLE
[macOS] I would like there to be an option to hide the dock icon

### ISSUE THREAD

**Issue by Evertt** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2672]
I know that this used to be a feature and that it's been removed because someone made issue #207. So obviously some people like to keep the dock icon and some people (like me) like to be able to hide the dock icon. I'm a programmer myself and for my work I use the app-switcher every few seconds and so I prefer my app-switcher to not be polluted with apps that I rarely need to switch to.

So uh, could that feature maybe come back, but as a separate check-mark in the preferences window?

**Comment by MarshallOfSound** [comment]
@Evertt That issue you linked wasn't the removal of a feature, it' was a legitimate bug.  The macOS design guidelines do not allow an application to have an active window and not have a dock icon.  (It's technically possible but goes against their guidelines).

I agree with those guidelines that this shouldn't be a thing and I think it will annoy more people than it will help when they enable it to see what it does.  For now, I'm going to close this issue out as a `wontfix`.

**Comment by Evertt** [comment]
@MarshallOfSound 

> The macOS design guidelines do not allow an application to have an active window and not have a dock icon.

Okay I'm totally fine with that. But that means that once the window is closed (and so there is not active window open) then the dock icon should be okay to remove right? I would still very much appreciate that. Because the window could still easily be opened using the menubar icon.

**Comment by MarshallOfSound** [comment]
@Evertt Afaik there is no way for GPMDP to be active but not have an open window somewhere, the window might be hidden or minimized, but it definitely exists somewhere

**Comment by Evertt** [comment]
@MarshallOfSound [Wavebox](https://github.com/wavebox/waveboxapp) does it though. Why can't this app do it then?

**Comment by MarshallOfSound** [comment]
@Evertt I'm not saying we can't do it, it's 100% possible, I just agree with the design guidelines here and say it shouldn't be done

**Comment by Evertt** [comment]
Okay :-(

**Comment by Frizi** [comment]
I'm heavily annoyed by that, as the music player goes in the way when i'm working. The music player constantly gets focus on cmd-tabs instead of my editor/browser window. It's annoying to the point that i'm often closing it and opening a background tab in chrome instead.

There are other apps (iTerm, Harvest for example) that allow excluding the app from the dock and that options proves to be very helpful.

Treat the guidelines as a helpful defaults when you would have no preference otherwise, but there are valid cases when it should be OK to break them. At least allow the user to decide, especially when it's so easy to do technically.

**Comment by Evertt** [comment]
@Frizi I think nobody is watching this issue anymore. :-(

**Comment by Frizi** [comment]
@MarshallOfSound Could you take a look? 😄

**Comment by Robula** [comment]
Thanks @angelo! This should be built into GPMDP!

**Comment by clayton-grey** [comment]
Came here to request this. I'll go with the terminal fix. Thank you @angelo!
