### ISSUE TITLE
Low visibility of back button in light themes

### ISSUE THREAD

**Issue by joelamos** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2673]
**OS:** Windows 10

**Issue Descriptions:** The back button just inside the right border of the search bar is very easy to miss. I didn't realize it was there until I searched "back button" in closed issues.

![2017-07-28 01_15_52-circlont14 152 97 shrymoming mix - aphex twin](https://user-images.githubusercontent.com/5117047/28703523-ad8ae012-7332-11e7-9a63-fe22e4f57a8e.png)

**Comment by jostrander** [comment]
Found the culprit:

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/3c91a72f5782c661a8b61f1a2fb7810f83182645/src/renderer/windows/GPMWebView/interface/customNavigation/hotkeyNavigation.js#L83

@MarshallOfSound added this so I don't know if we need to fix this to be a theme variable or what.

**Comment by MarshallOfSound** [comment]
Fixed in master
