### ISSUE TITLE
Feature request: if application can't find lyric ask to open web browser with google search page where auto add artist and song name

### ISSUE THREAD

**Issue by Stigmaleon** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2675]
**OS:** Win 10

**Issue Descriptions:**
For some songs, especially for russian or some exotics)),  app can't find lyric. So it will be good add some button or some link to open google search with added artist and song name.

For example:
![](https://image.prntscr.com/image/m2dOE_PMQ96E8_IJIra2Sg.png)

**Comment by dKab** [comment]
Working on it.

**Comment by MarshallOfSound** [comment]
Fixed in #2803
