### ISSUE TITLE
[MacOS] Top bar icon

### ISSUE THREAD

**Issue by romainp89** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2677]
**OS:**
MAC OS

**Issue Descriptions:**
Please, adding option for show/hide icon in top bar for macOS. Because the icon is really disproportionate compared to others and it is really awful ^^

**Comment by MarshallOfSound** [comment]
There is an existing issue regarding the slightly different size between our icon and other macOS tray icons.

As for hiding the tray icon, this is something that has been discussed before and will not be implemented
