### ISSUE TITLE
[Feature Request] macOS - Allow system shortcuts for hotkeys

### ISSUE THREAD

**Issue by joshmtucker** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2678]
I'd be awesome if I could set system/app shortcuts in System Preferences to hotkeys within the app on macOS (which would require each item to be in the app menu). I often have the player on another screen and I'd like to be able to do things like Thumbs Up/Down without switching focus.

Thanks so much for your hard work!

**Comment by jostrander** [comment]
If I'm not mistaken you can basically do this in the desktop settings. Assign a hotkey to thumbs up and thumbs down and you can do it when the app is in the background.

**Comment by joshmtucker** [comment]
@jostrander Wow, you're absolutely correct. This wasn't working at first. Just restarted the app, reset the keys, and now it seems to be working correctly. Thanks for the quick response Jesse!

I'll close this out :).
