### ISSUE TITLE
Weirdness with u2f login

### ISSUE THREAD

**Issue by lengau** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#268]
If your account has 2-step verification enabled with u2f (https://support.google.com/accounts/answer/6103523?hl=en), the Play Music Desktop Player ends up taking you to the Chrome web store to install the gnubbyd extension (https://chrome.google.com/webstore/detail/gnubbyd/beknehfpfkghjoafdifaflglpjkojoco/related?utm_source=chrome-app-launcher-info-dialog).

**Comment by mikeytusa** [comment]
I noticed that too.  It was really confusing.  I ended up just using a Google Authenticator code to get in.

**Comment by verandaguy** [comment]
Can confirm this issue exists on OS X  10.11.3 with a YubiKey Neo with the same behaviour as described by @lengau.

**Comment by MarshallOfSound** [comment]
I have a U2F key aswell, unfortunately I can't bring support for the keys into the app ( I don't think ) so for now it's just going to have to be an extra click to use Google Authenticator codes.

Sorry guys :)

**Comment by MarshallOfSound** [comment]
If anyone has any work around ideas I'm open but don't see how this can be fixed without injecting JS onto the logon page which I really don't want to do

**Comment by michaelphipps** [comment]
I use 2FA, and I've tried setting up an "app password" but for some reason it doesn't work.  https://security.google.com/settings/security/apppasswords?hl=en  it's painful because I don't actually know my google password (I use last pass) so I've gotta do a lot of stuffing around to login and use the app.
