### ISSUE TITLE
Wrong icon on Windows 10 taskbar

### ISSUE THREAD

**Issue by Zaelnorth** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2680]
**OS:**
Windows 10 Creators Update 1703

**Issue Descriptions:**
Wrong icon in taskbar after update

**Steps to Reproduce:**
Just launch the app, it shows no icon in the taskbar.

![image](https://user-images.githubusercontent.com/7588963/28767001-68e90408-7615-11e7-823c-933efc9d62e5.png)

**Comment by MarshallOfSound** [comment]
Sometimes windows gets super confused about pinned applications when they update.

Unpin the app and then repin the app (maybe close it in the middle) and windows should reload it's icon cache

**Comment by Zaelnorth** [comment]
Excellent, thanks a lot - worked by unpinning it. 

Whenever I pin, it shows bad icon again, will try to restart and hopefully that should fix the problem.
