### ISSUE TITLE
Feature Request: Mouse back button

### ISSUE THREAD

**Issue by ralcaidev** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2683]
Hey there!

I think it would be a great idea to add support for mouse's back button (as usual on file explorers or web browsers).

On the other hand, backspace on keyboard works.

I know there's a back button on search box, but mouse's shortcut is very useful.

**Comment by MarshallOfSound** [comment]
The mouse back button is supported on Windows and Linux.  Support on macOS is not possible afaik

**Comment by ralcaidev** [comment]
Well,for me it's not working, at least in Manjaro-XFCE, but works on any other app that should work.

**Comment by jostrander** [comment]
So linux uses a native wrapper I wrote, mouse-forward-back. Which grabs buttons 8 and 9 and maps them to forward and back inside GPMDP. You can try using `xev` to check that it's picking up buttons 8 and 9 appropriately if I recall correctly. If they are, I would check the console output of gpmdp for any errors mentioning mouse-forward-back.

**Comment by MarshallOfSound** [comment]
Will reopen for debugging / troubleshooting purposes

**Comment by MarshallOfSound** [comment]
As the reporter has not responded to the request for additional information this issue will be closed.  If further information can be provided at some point in the future, comment on this issue with the requested information and if appropriate the issue will be reopened.
