### ISSUE TITLE
Feature Request: "Add to library" keyboard shortcut

### ISSUE THREAD

**Issue by ivko1950** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2686]
I listen to radios and public playlists most of the time, so it would be very convenient to have a keyboard shortcut for adding songs to my library. I find myself constantly alt-tabbing to do just that. It would be nice to have an option to get some feedback after pressing the key as well, so that I don't have to worry about whether or not it actually added the song to my library. I'm personally fine with the regular "Added the song X to your library." pop up since I can see it on the second monitor, but I can see how it could become a minor annoyance to those that have a single monitor or keep the app minimized. It can just be some kind of an audio feedback or a pop up in the bottom right of the screen.

**Comment by jostrander** [comment]
Not entirely sure this is possible, but I'm not going to close it until I do some more research.

**Comment by MarshallOfSound** [comment]
Having looked into this in the past this isn't something we can do @jostrander 

The add to library button is inside a menu which is dynamically created when the user clicks a button or something.  It required levels of fake events and user simulation that I couldn't pull off inside `gmusic-ui.js`

**Comment by jostrander** [comment]
I'm having a hard time even trying to get this one. I figured I could clone it similar to the IFL button, but I can't even get the events to be picked up from the console for the original menu. I might still take a further look into it and see what I can come up with, but for now I'd consider it not possible.

**Comment by jwmann** [comment]
So it's uhh 2019 now, is it still impossible?
Would use this shortcut literally everyday.
