### ISSUE TITLE
Auto scrolling/jumping to the song that starts playing

### ISSUE THREAD

**Issue by jdotsdotp** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2689]
Not sure if it's a bug or intended, but if I'm browsing through a playlist towards the top of the playlist, the song I was listening to towards the bottom of the playlist ends and the next one starts, it will automatically jump the page to the song that just started playing. So then I have to scroll back to the top where I was.

Here's a video example of the issue:

https://streamable.com/rnl56

**Comment by jostrander** [comment]
Happens in the browser too, so not an issue with GPMDP, but with Google Play Music itself.
