### ISSUE TITLE
UI issue

### ISSUE THREAD

**Issue by edshevsky** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2690]
I use OS Windows 10.

There are a small UI issue after last update: "back" arrow have almost the same colour as search panel. Screenshot and debug file in attachment.

![bug](https://user-images.githubusercontent.com/12774629/29003363-1587772e-7abe-11e7-9bf3-1dc1e9e9e48f.png)
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/1203059/debug_info.zip)

**Comment by jostrander** [comment]
Duplicate. Merging into #2673.
