### ISSUE TITLE
Feature Request: Automatically skip explicit songs

### ISSUE THREAD

**Issue by miltador** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2691]
**OS:**
Windows 10

**Issue Descriptions:**
Feature Request: Automatically skip explicit songs

**Steps to Reproduce:**
There already is an option in the `Playback` tab to skip disliked songs. It would be nice to see another option here to skip songs that are marked as `E` (explicit).

**Comment by jostrander** [comment]
I don't believe there is a way to do this, at least easily. The thumbs up and down are in the player bar at the bottom which makes checking for that easy. The explicit icon is only in the playlist which isn't loaded into the DOM 100% of the time. Google does have an option in their settings to block explicit songs from radio, if that suites you however.

**Comment by miltador** [comment]
Ah, that is.. unfortunate.
Yeah, that option exists but only for radio..

**Comment by miltador** [comment]
But wait... There is always a queue! `queue-song-table` which is a playlist with items, and there is a way to detect current playing one, it's highlighted. And it renders `explicit` icon!

**Comment by jostrander** [comment]
The queue table is a data driven table that removes element if you scroll, so lets say for example you've played 100 songs, you go back to the beginning, but the list still is scrolled to the bottom. The currently playing track is no longer in the DOM. So you can no longer check for explicit tracks.
