### ISSUE TITLE
Oversized UI after going to menu

### ISSUE THREAD

**Issue by fredphoesh** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2692]
Hi 
Please see the image I uploaded, it shows what happens (twice out of trying twice) when I go to the pop out player, then back to main UI then to menu in my Win 10 version. The UI goes huge.
![gpm-oversized-after-menu](https://user-images.githubusercontent.com/5565996/29026668-e22cf9a0-7b74-11e7-94e1-e88a8ba00785.jpg)
-->

**OS:**
win10 
**Issue Descriptions:**
Clicking between pop out player then back to main interface, to menu to settings then all that again is what seems to cause this.
**Steps to Reproduce:**
See the video as I reproduce the bug.
[gpm-oversized-after-menu.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/1205189/gpm-oversized-after-menu.zip)

**Comment by MarshallOfSound** [comment]
Merging into #2269

**Comment by captainjim1** [comment]
Does this also take care of the opposite effect? Having a super zoomed out UI?
