### ISSUE TITLE
Feature Request: Share links using songlink.io

### ISSUE THREAD

**Issue by 42xX** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2694]
Hi, 

I know it's more pressing squash bugs but I thought this might be a good feature to add. There's a site called songlink.io that lets you share a link to another service like Spotify, Apple Music, etc. I was wondering if it was possible to integrate it or a similar service into GPMDP? There's a similar app for Android that works well as an example:
https://play.google.com/store/apps/details?id=com.sockpuppetapps.link&hl=en

Thanks,

**Comment by MarshallOfSound** [comment]
Merging into https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/2216
