### ISSUE TITLE
Changing Tracks on 4.4 and 4.3 using custom CSS crashes

### ISSUE THREAD

**Issue by andiohn** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2695]
**OS**
Windows 10 Pro build 1607 x64

**Issue Descriptions:**
I looked at the FAQs and this only started happening when I was playing around with custom CSS styles. Even though I disabled, then uninstalled then deleted all information of this program on my computer and then reinstalled, it still happens. I disabled notifications everywhere I could find, including in windows.

**Steps to Reproduce:**
Install fresh copy, login, play track, press skip track CRASH.

**Comment by jostrander** [comment]
What custom CSS are you using?

**Comment by MarshallOfSound** [comment]
As the reporter has not responded to the request for additional information this issue will be closed.  If further information can be provided at some point in the future, comment on this issue with the requested information and if appropriate the issue will be reopened.
