### ISSUE TITLE
Feature Request: Now that GPMDP is on Windows Store, is an Xbox version possible?

### ISSUE THREAD

**Issue by ryaniskira** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2696]
I know I submitted this last year initially and it was not possible at that time due to Electron not being compatible with UWP, but now that it is on the Windows Store I am just wondering if that changed. On the Windows store listing it does show that x64 is required (and I think newly submitted apps have to be UWP now).

**Comment by MarshallOfSound** [comment]
It's not possible, Electron is based on Chromium which is `win32` based not UWP
