### ISSUE TITLE
songs stop playing after toggling to different audio device 

### ISSUE THREAD

**Issue by tconley** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2697]
**OS:**  Win 10 1607  build 14393.1480

**Issue Descriptions:**  When switching audio sources multiple times via outside app the songs stop playing. I have and AHK script (autohotkey) that changes the default audio output source (I use this toggle between my receiver on optical-audio-out and my headphones plugged into 3.5mm jack). If I toggle between audio devices and am playing music in play.google in chrome, the audio continue to play no matter how many times i toggle. In desktop player the song pauses after the second audio device toggle.

**Steps to Reproduce:**   
1) Launch desktop player. 
2) Play a song. 
3) Toggle audio device via MMSYS.CPL by selecting "set as default device"  (Song keeps playing.)
4) Toggle audio device back to original device via MMSYS.CPL. (Song stops playing)

**Desired Behavior:**   
User should be able to toggle audio devices as many times as wanted via MMSYS (or other means) and song will keep playing until stopped by user.

![image](https://user-images.githubusercontent.com/1893207/29098476-672100cc-7c54-11e7-9a37-5501f23909b4.png)

**Comment by MarshallOfSound** [comment]
This was fixed in Chromium 59 (if I recall correctly) so once we update Electron to `1.7.x+` it shouldn't be a problem anymore
