### ISSUE TITLE
WebSocket API time channel does not update when player minimized to tray

### ISSUE THREAD

**Issue by tjhrulz** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2698]
**OS:**
Windows 10
**Issue Descriptions:**
When subscribed to WebSocket API time channel is never fired when minimized to desktop (Even on song change). All other channels do fire correctly. I have not tested the Playback API but I imagine it has the same issue.
**Steps to Reproduce:**
1.Open websocket connection
2.Minimize to tray (Normal minimize does not trigger)

I had a similar issue to this in the past with a personal project. Likely origin is that google does not update these values on the webpage if the page visibility is 0. You can either override the wrapper to say the page is always visible or you can extract both these values in the exact same format from the HTML5 music object.

**Comment by tjhrulz** [comment]
May be slightly related to PR #2688 depending on how you extract these values for the API

**Comment by J05HI** [comment]
Have the same Problem on Win10.

**Comment by J05HI** [comment]
Have the same problem on Win10.

**Comment by MarshallOfSound** [comment]
This has been fixed, not sure what #2688 is actually trying to solve.  My local build now emits stuff on the websocket even when minimized

**Comment by tjhrulz** [comment]
Wait are you saying this was fixed in a previous commit or is fixed in an upcoming commit?

**Comment by MarshallOfSound** [comment]
Fixed in a previous commit, but not released yet

**Comment by tjhrulz** [comment]
Ah my apologies on missing that, I guess my search for the bug was not vague enough.

**Comment by MarshallOfSound** [comment]
@tjhrulz https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/2630

**Comment by tjhrulz** [comment]
Lol shame I was not here when you were fixing it, I could have given you your exact fix.
