### ISSUE TITLE
Mini player controls are not centered.

### ISSUE THREAD

**Issue by jrfernandes** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2699]
**OS:** macOS Sierra v10.12.6

**Issue Descriptions:** When enabling the mini player, the controls area should be centred, which is not the case. See screenshot below.

**Steps to Reproduce:** Enable mini player.

![d-d-dance_-_the_royal_concept_and_slack_-_bevy](https://user-images.githubusercontent.com/638906/29130131-ef8d0fb2-7cf6-11e7-931d-8ee41742ffde.jpg)

**Comment by MarshallOfSound** [comment]
Merging into #2269 (mini player zoom issues)
