### ISSUE TITLE
Some issues with i3 tiling WM.

### ISSUE THREAD

**Issue by kminehart** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#270]
I'm not using a DE, only the WM called "i3".  See here:  https://i3wm.org/

I think the issues might be because of the custom window borders and not allowing the WM to control the application?  For example, I can't super+shift+q to exit, which executes `kill`.  Clicking the X, fullscreen, or minimize does nothing either.

I'll see if I can do anything to help with this, I made a fork for my changes:

https://github.com/pascalsoftware/Google-Play-Music-Desktop-Player-UNOFFICIAL-

**Comment by kminehart** [comment]
More specifically, the app is ignoring or SIGKILL.

**Comment by AnotherKamila** [comment]
Also seeing this in i3.

Additionally, if I switch to the miniplayer while in tiling mode, the window size is different than what the miniplayer expects, and it becomes very unhappy about this (constantly redrawing itself to the expected and actual size in a loop). As the miniplayer expects a fixed window size, probably telling the WM to float it is the most reasonable behavior (or you could make it resizable => me happy :D).

**Comment by kminehart** [comment]
Update: 
in `src/index.js` I added 
```
    // Emitted when the user tries to close the application.
    mainWindow.on('close', () => {
      console.log('close');
    });
```
and when I make an attempt to close the application, either with super+shift+q, or with the x, or ctrl+w, the event gets fired and 'close' is printed on the console.  At this point I'm not familiar enough with the application to correctly handle a close, but I'm working on it.

**Comment by kminehart** [comment]
Here's the perpetrator:

So at the moment if anyone else is having this problem, make sure to disable "minimize to tray" in the desktop settings, then it should work fine!  It looks like i3 and electron don't like to play nice when trying to hide a window, since i3 really has no way to hide a window.

```JavaScript
mainWindow.on('close', (event) => {
  if ((Settings.get('minToTray', true) || process.platform === 'darwin') && !global.quiting) {
    if (process.platform !== 'darwin') {
      mainWindow.minimize();
      mainWindow.setSkipTaskbar(true);
    } else {
      if (PlaybackAPI.isPlaying()) {
        Emitter.sendToGooglePlayMusic('playback:playPause');
      }
      mainWindow.hide();
    }
    event.preventDefault();
    return;
  }
```

**Comment by AnotherKamila** [comment]
Yes, this works. BTW, other applications (e.g. VLC or Gajim) can "minimize" to tray in i3, but it is possible that they actually destroy the window.

**Comment by kminehart** [comment]
Indeed, they would have to destroy the window.  i3 does not technically have a way to minimize a window.

As for the issue at hand, I am unable to find a good fix for it.  It would be easy, but Electron does not have `window.minimizable` implemented on Linux.  I opened an issue here:  https://github.com/atom/electron/issues/4696

**Comment by MarshallOfSound** [comment]
Did some quick research into this it's definitely an electron bug and should be tracked there :+1: 

I'll watch the issue there and chime in if needed

**Comment by zetxx** [comment]
i think that this issue should be reopened. issue exists at current version

**Comment by tekjanson** [comment]
I am also having this issue with i3 on current build

**Comment by Block81838** [comment]
same issue
