### ISSUE TITLE
"Apps for websites" (Windows only)

### ISSUE THREAD

**Issue by Mayhem93** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2700]
Hello guys,

This is a feature request, so please forgive me for bypassing the "standard" issue format (since it's not a bug).

Windows 10 since "I don't remember which update it was" has a feature called "Apps for websites" which basically is like "open in app" for Android when clicking http(s) urls. It would be nice if every link that starts with `play.google.com/music/listen` would actually open this app.

Not sure if it is actually possible, thought might as well give it a shot here.

**Comment by MarshallOfSound** [comment]
You need to have control of the site in order to do the linking, we cannot put this JSON file on google plays servers so we unfortunately can't implement this.

See https://docs.microsoft.com/en-us/windows/uwp/launch-resume/web-to-app-linking
