### ISSUE TITLE
Open player by clicking on Windows Media Service popup

### ISSUE THREAD

**Issue by flippinger** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2703]
**OS:** Windows 10 Pro 1703

**Issue Descriptions:** Clicking on the Windows Media Service popup (away from the next/prev buttons, for example in the album art area) does not open/focus GPMDP like it does normally with other players. Instead it does nothing.

![image](https://user-images.githubusercontent.com/3148313/29207728-84101990-7e87-11e7-8dc4-23afd1bf1a69.png)

**Comment by MarshallOfSound** [comment]
OK, so not as easy as first thought.  Basically other media players get the UWP "activate" event, we can't get that because we aren't UWP 😢
