### ISSUE TITLE
Back Arrow still an issue.

### ISSUE THREAD

**Issue by michaelsammler** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2704]
Back arrow is not always present, even though back is  possible. (I use the back button on my mouse. Works everytime, arrow present about half the time)

Will not start full screen although selected in properties to open full screen. Opens about %25 size window. This may be an issue on my side though.

Keep up the good work. Play Music Rainmeter skin also works and looks great with GPMDP.

**Comment by MarshallOfSound** [comment]
Merging into #2673
