### ISSUE TITLE
Terminal program stays open

### ISSUE THREAD

**Issue by Junebugg** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2705]
Is Terminal on Mac supposed to stay open after the program starts? I have "Automatically launch when I turn my computer on" checked.

**Comment by MarshallOfSound** [comment]
@Junebugg Nope, are you running high sierra?

**Comment by MarshallOfSound** [comment]
Brutally closing as can't reproduce on either Sierra or High Sierra and I'm in a cleanup mode right now 😆 

Comment below if it's 100% reproducable

**Comment by tehdef** [comment]
Same here. It's done it on both High Sierra, and Sierra. It's annoying, and when I force close Terminal GPM-D crashes and I have to reboot it. 100% reproducible.
