### ISSUE TITLE
Dell XPS 15 9560 Doubled Forward Song

### ISSUE THREAD

**Issue by zerospiel** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2707]
**OS:** Windows 10 home released

**Issue Descriptions:** when i tap on the next (previous) song key (default f6 w/o fn on the dell xps 15 9560 keyboard) then GPMDP goes forward (backward) song twice. as an addition issue, this can cause the lag to the app and i have to hard close the app.

**Steps to Reproduce:** media keys on the dell xps works another way (partly, as i know): if you want to go forward song you have to tap f4 key w/o using fn-key. in other hand, if you want to close the app (in default way), you have to tap alt+f4 w/o fn-key. therefore, i think that this positioning can cause the issue with GPMDP

**Comment by MarshallOfSound** [comment]
@zerospiel Disable the windows 10 media service in settings
