### ISSUE TITLE
Feature suggestion: choose installation drive

### ISSUE THREAD

**Issue by daimebaru** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2708]
I'd like to use the app, but install it on a different drive than the default C.
Please consider adding the ability to choose the install drive.

-->

**OS: Windows 10 64 bit

**Comment by MarshallOfSound** [comment]
GPMDP uses Squirrel.Windows which is designed to be promptless and a super easy user install process.  It will always install to `%LOCALAPPDATA%`.
