### ISSUE TITLE
Feature request: Always show thumbs/menu/song times in main player

### ISSUE THREAD

**Issue by ikeeki320** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2709]
I would like to request an option be added to always show the 3 dot menu, thumbs up & down, and time elapsed/total time features in the main player window. Right now the only way to see those things is to have the app window active and move the mouse down in to the player controls area.

Mac 10.11.6 with GPMDP 4.4

**Comment by MarshallOfSound** [comment]
I'm all for user preference but I also want to cut down on the options in the app (we have an awful lot of checkboxes at this point).

If you want to do this it's a relatively straightforward CSS hack you can add with our custom CSS option 👍
