### ISSUE TITLE
Pausing/playing via multimedia keyboard buttons while typing in search input loses the focus of that input

### ISSUE THREAD

**Issue by PunchyRascal** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2710]
**OS:**
win10

**Issue Descriptions:**

When I am in the search field and suddenly feel like pausing a song, the field loses focus.

**Steps to Reproduce:**

- enter search field while music is playing
- hit play/pause on the multimedia keyboard
- focus is lost from search field

**Comment by MarshallOfSound** [comment]
Simple fix I think, basically just have to remember `document.activeElement` before faking DOM interaction and restore it with `.focus()` after 👍
