### ISSUE TITLE
Clearing queue sometimes scrobbles when it should not.

### ISSUE THREAD

**Issue by jaccarmac** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2711]
**OS:**

Gentoo (`Linux 4.12.5-gentoo #1 SMP Tue Aug 15 20:38:48 CDT 2017`)
Windows 10

GPMDP `4.4.0`

**Issue Description:**

Clearing the queue scrobbles the currently "playing" (but paused and <50% played) song. Happens often enough to be easily noticed but not every time the queue is cleared. May be related to  #1614.

**Steps to Reproduce:**

1. Connect to Last.fm.
2. Start playing an album with two or more tracks.
3. Just after the first song ends/second song starts, pause the player.
4. Clear the queue from the queue interface in the bottom right.
5. The second song has been scrobbled despite only playing for a few seconds at most. If not, repeat the process until the issue is duplicated.

**Comment by jaccarmac** [comment]
Awesome, thanks much!

**Comment by MarshallOfSound** [comment]
Fixed in #2614
