### ISSUE TITLE
Taskbar icon (small) has visual defects

### ISSUE THREAD

**Issue by SycamoreFox** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2712]
# Windows 10

When taskbar icon is displayed on a small Windows taskbar, then player icon appears to have visual defects:

## 100% view:
![image](https://user-images.githubusercontent.com/18396681/29469141-04a2fdba-8415-11e7-9e7d-69b31017fcc3.png)

![image](https://user-images.githubusercontent.com/18396681/29469104-dfda0884-8414-11e7-80d3-ca920f7ff1bd.png)

## Zoomed pixel view:
![image](https://user-images.githubusercontent.com/18396681/29469076-c2350af4-8414-11e7-9a78-506c050f5e40.png)

**Comment by MarshallOfSound** [comment]
Welcome to windows 😆 

The icon we provide does not have these defects, windows does weird stuff to the icon and breaks it
