### ISSUE TITLE
Lyrics Scroll is too slow, can't scroll manually.

### ISSUE THREAD

**Issue by jwhipp** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2718]
**OS:**

Windows 10

**Issue Descriptions:**

When looking at Lyrics, the scroll speed doesn't follow the flow of the song, and is often too slow.  Scrolling manually doesn't work either. 

**Steps to Reproduce:**

1. Play a song
2. Click Three dot menu next to song information
3. Click "Show Lyrics (Beta)"
4. Observe speed, try to scroll

**Comment by MarshallOfSound** [comment]
> When looking at Lyrics, the scroll speed doesn't follow the flow of the song, and is often too slow. Scrolling manually doesn't work either.

The scroll speed is "best fit" for all songs, it's not going to work for everything.  You can enable manual scrolling in Desktop Settings

**Comment by jwhipp** [comment]
Awesome, thanks! I didn't know that setting was there.
