### ISSUE TITLE
Lyrics drawer instead of overlay

### ISSUE THREAD

**Issue by xaddict** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2719]
I would like the lyrics to be in a drawer or side panel instead of the overlay it is right now.
Also, the text is very big and it would help readability if it were black text on white.

**OS:** macOS 10.12

**Comment by MarshallOfSound** [comment]
Merging into #2216 this is something that wouldn't be implemented in core
