### ISSUE TITLE
Media keys stop working after long periods of time

### ISSUE THREAD

**Issue by pbsladek** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2723]
**OS:**
macOS Sierra 10.12.6

**Issue Descriptions:**
Searched through all the tickets and couldn't find anything quite like this. Media keys work fine, even without the fn key. However, if I leave the app open for long periods of time they stop working. A simple restart fixes the issue for the day. Don't know anything about the implementation, but some sort of periodic refresh( 3 -4+ hours ) would be great. Love the app! Use it everyday. Thanks for putting in the time! 

**Steps to Reproduce:**
Leave app open for long ( 12+ hours ) time. Close over night etc. 
Attempt to use media keys. They stop working.
Restart app. They work again.

**Comment by flippinger** [comment]
same on Windows 10 1703

**Comment by MarshallOfSound** [comment]
@pbsladek I tried to repro this and I couldn't, left my mac logged in for 12 hours then left it on overnight, next morning the hotkeys still worked.  Tried this a few different days as well.

That said, I can see this kind of thing happening, if macOS decides you don't get the hotkeys anymore, it's just gonna take them 😆 .  I can add like a loop that checks every 15 minutes or so whether the hotkey is still registered but this would

a) Have an impact on battery life (timers are not nice)
b) Still leave you with a period of time where the hotkey isn't working

I think the best thing to say here is, if the hotkey stops working, just quickly restart GPMDP 😆 It takes a few seconds and everything will be back working again 👍 

Sorry I can't do more with this one
