### ISSUE TITLE
Function key F4 disabled when running

### ISSUE THREAD

**Issue by mnestor** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2725]
**OS:**
Mac 10.12.6

**Issue Descriptions:**
When GPMDP is running function key F4 does not work in other applications but can still be assigned as an OS global hotkey.
Most noticeable when using byobu in terminal/iterm2. 

**Steps to Reproduce:**
Pick an application you use F4 in, for me it's a byobu session in iterm2/terminal.
Notice F4 works.
Start GPMDP.
Notice F4 no longer works.
Exit GPMDP.
Notice F4 works again.

**Comment by MarshallOfSound** [comment]
What is your F4 key supposed to do?

**Comment by mnestor** [comment]
Using byobu in terminal 
F2 = new window
F3/F4 = move prev/next window
F7 = enable scrollback

So when GPMDP kills my ability to use F4 is just makes byobu a little less easy to use. Not really a big thing I just don't see why it's doing that as I don't have any keybinding set in GPMDP.

**Comment by MarshallOfSound** [comment]
I can't reproduce this on any of my macs, Fn+F4 and just F4 work perfectly fine with GPMDP open and without it open.  We don't put any keybinds anywhere near F4.  I'd reccomend looking at how iterm2 binds that F4 key and see if for instance having an active media session on your device would stop it working
