### ISSUE TITLE
next song notification shows app ID instead of app name in UWP

### ISSUE THREAD

**Issue by flippinger** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2726]
**OS:** Win 10 pro 1703

**Issue Descriptions:** When GPMDP advances to the next song, the notification shows as a notification source the app ID (?) instead of the app name

App ID (com.marshallofsound.gpmdp.core)
![image](https://user-images.githubusercontent.com/3148313/29752727-abcdc570-8b63-11e7-9a3c-5d5d0339fad4.png)

instead of the app name (GPMDP)
![image](https://user-images.githubusercontent.com/3148313/29752729-b791bede-8b63-11e7-944a-2ab727fedd51.png)

I don't know if you can influence this without being an UWP app.

**Comment by MarshallOfSound** [comment]
That normally happens when a shortcut doesn't exist in the start menu with our app ID.  Can you check if a GPMDP shortcut exists and if it doesn't rerun the installer

**Comment by flippinger** [comment]
@MarshallOfSound it has a shortcut in the start menu, I am using the MS store version

**Comment by MarshallOfSound** [comment]
Have it on good authority that this was a temporary windows issue that has been fixed in an update 👍
