### ISSUE TITLE
[URGENT] Version 4.4.1 - Patch Release

### ISSUE THREAD

**Issue by MarshallOfSound** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2727]
This issue is for tracking progress on the release process.

- [x] Update MR_CHANGELOG
- [x] Version patch
- [x] Push to master
- [x] Build all platforms on CI
- [x] Check release process on staging update server `staging.googleplaymusicdesktopplayer.com`
- [x] Check operational on Windows
- [x]  Check operational on OS X
- [x] Check operational on Linux
- [x] Make release on GitHub
- [x] Upload to bintray
- [x] Upload to WinStore
- [x] Watch the world burn :fire: :fire_engine: 

This release is critical and will be going out faster than usual, the signing certificate currently in use on windows expires in 4 hours as of right now so pushing this out ASAP.

**Comment by MarshallOfSound** [comment]
Changeset https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/compare/v4.4.0...6ade05a

**Comment by jostrander** [comment]
Whoops...

**Comment by godey4me** [comment]
Windows store update not showing after 5 days @MarshallOfSound

**Comment by 42xX** [comment]
Same for me. Currently on 4.3.0

**Comment by MarshallOfSound** [comment]
@42xX @godey4me If you look very closely you'll see that this issue is still open and the "Upload to WinStore" task isn't marked as complete yet 😆 

The new version is still pending in the developer console for the Windows Store.
