### ISSUE TITLE
Is possible install in raspbian?

### ISSUE THREAD

**Issue by eagj** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2729]
Hi, i am a user of this great app in windows (at work) and in os x (Home) but i have a raspberry with raspbian and i wanna make a music server and used by remote control with the phone. 
I see a version for linux but im a newbie and i dont know if this version work with a raspberry 2 and raspbian jessie. Is possible? 
Thanks in advance!

**Comment by MarshallOfSound** [comment]
I am not too familiar with the installation of things on raspberry pi's.  

If you can install `.deb` or `.rpm` files for either `ia32` or `x64` architecture then yes it is compatible, otherwise no 👍
