### ISSUE TITLE
Unresponsive using open ATI drivers on linux

### ISSUE THREAD

**Issue by joytrekker** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#273]
I'm running Ubuntu 15.10 with the open ATI drivers. The player window fails to respond after opening it. In other words it is stuck on the start page with the sign in button. I found that if I use the closed ATI driver the program will work. However with the closed driver performance is bad for me over all so I had to revert back. It's possible this is a problem with electron since I have experienced the same issue with the election app Wmail. Although using Wmail allowed me to login before It would freeze on the main application screen.

**Comment by bogdanteleaga** [comment]
Can confirm this happens to me using intel drivers as well. Switching to the closed nvidia drivers let me log in, I checked remember and now it works using the intel drivers.

**Comment by MarshallOfSound** [comment]
Please raise this as an issue on `atom/electron`.  Rendering bugs such as this should go there
