### ISSUE TITLE
Update does not apply

### ISSUE THREAD

**Issue by Proggie** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2730]
**OS:**
Mac OS 10.12.3

**Issue Descriptions:**
This has happened for previous versions as well. Currently on 4.4.0.
-Update Available notice shows up
-click on "LET'S DO THIS!"
-app closes and nothing happens
-wait a few minutes
-start app back up and get the Update Available notice again.
-eventually have to download the latest version of the app from website and install that.

**Comment by MarshallOfSound** [comment]
Unfortunately, sometimes this kinda thing happens with updates, it's super rare but there's not much we can do about it here 😢 Best I can suggest is wiping out your `~/Library/Application Support/Google Play Music Desktop Player` folder and hoping it doesn't happen again

**Comment by MarshallOfSound** [comment]
@Proggie Are you an admin user?  Where is GPMDP (the .app file) actually located?

**Comment by Proggie** [comment]
Yes I am. It's located in the regular Applications folder

**Comment by Proggie** [comment]
I do use the app with two different accounts though. I just changed permissions for the app and those two folders to make sure both users can read and write to them.
I also get a dialog asking me for a password. It says: An update is ready to install. Google Play Music Desktop Player is truing to add a new helper tool. I enter my admin password and click on Add Helper. But the app just quits and nothing else happens.
