### ISSUE TITLE
last.fm scrobbling broken for uploaded songs

### ISSUE THREAD

**Issue by stvnjohnson** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2732]
**OS:** Windows 10

**Issue Descriptions:** Since the new update, scrobbling does not appear to work for songs that have been _uploaded_ to your library.  The "now playing" shows the correct song, but it is never scrobbled.  Scrobbling does work for songs that you add to your library from the Google Play Music library.

**Steps to Reproduce:** Play a song that you've uploaded to Google Play Music.

**Edit:** Unlike with the previous issue last version, this doesn't appear to still scrobble when you leave the window in focus.

**Comment by XanderXAJ** [comment]
I'm currently seeing this issue on macOS.  Was this issue closed because it was fixed?

**Comment by gonzalo-rodriguez** [comment]
Same here on Windows 7, using the latest version of the app.

Songs manually uploaded to your Google Play Library show as "Now scrobbling", but never get actually scrobbled.

**Comment by MarshallOfSound** [comment]
@XanderXAJ @gonzalo-rodriguez This issue is closed as it has been fixed in master
