### ISSUE TITLE
V 4.4.1 Mac OS: Stream to Choose Cast Device Problem

### ISSUE THREAD

**Issue by sausimausi** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2735]
Stream to Choose Cast Device Problem
I have 3 single devices - I can choose any of these: OK
I grouped this 3 devices to one group name: When I choose this group: no sound

**OS:**
10.12.6 Sierra
**Issue Descriptions:**

**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment]
Merging into https://github.com/GPMDP/electron-chromecast/issues/8
