### ISSUE TITLE
Lastfm not scrobbling

### ISSUE THREAD

**Issue by ajyates** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2736]
**OS:** Windows

**Issue Descriptions:**  The last.fm integration seems to have stopped working after the latest update to version 4.4.1.

I unauthorized the scrobbling and then reauthorized it and it still will not scrobble any songs to my account. 

Listening in Google Chrome with the scroblr extension does scrobble songs properly. 

**Steps to Reproduce:**  Open Google Play Music Desktop Player, connect to lastfm, play several songs. They do not show up as part of my scrobble history.

**Comment by TurbinoZ100000** [comment]
Why was this closed? Did you manage to fix it?

**Comment by ajyates** [comment]
I closed it because I did my original search on "lastfm" which is how the application references it. After I posted the ticket I did my search to include "last.fm" and found this ticket: 

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/2732
