### ISSUE TITLE
Music randomly stops playing and after a while fixes itself

### ISSUE THREAD

**Issue by spichkaa** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2738]
OS: Windows 10

Issue Descriptions: Pretty much the title, no matter what I play: radios, albums or playlists - from time to time (once an hour or even rarer). Looks like it happens on song switching. Player then looks like there is no connection, e.g. play button is grayed out, and I'm pretty sure that connection is fine at that exact moment. It stays like this for 2-5 minutes and starts playing the song it was going to play before this all happened. This all started after the 4.4.1 update.

Steps to Reproduce: happens randomly.

**Comment by petuhovskiy** [comment]
Happens for me also. 
App freezes sometimes (often on song switching). I've waited for 2-3 minutes, but app was still unresponsive.

**Comment by affinage** [comment]
i also have the same issue.

**Comment by MarshallOfSound** [comment]
This is a memory thing that was fixed with the timing fix I believe.  (I also had this issue till that fix went into master)

**Comment by spichkaa** [comment]
I kinda don't get it. How can it be fixed, if it happens all the time? I can get these lags 0-4 times for every hour of listening, and it simply ruins the listening experience.

**Comment by MarshallOfSound** [comment]
> How can it be fixed, if it happens all the time?

It's fixed in master, hasn't been released yet 👍
