### ISSUE TITLE
Player will freeze when trying to search for something.

### ISSUE THREAD

**Issue by IrishMash** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2739]
**OS:**
WIndows 10
**Issue Descriptions:**
When searching for songs, albums, or artists it gets stuck in loading and cannot do anything with the program. Can only fix the issue by restarting my system.
**Steps to Reproduce:**
Cannot willing reproduce. Just randomly happens.

**Comment by MarshallOfSound** [comment]
> Can only fix the issue by restarting my system.

This is due to OOM because of a weird timing bug that has been fixed in master.  (I had the same issue)  You can just quit GPMDP and relaunch it to fix the issue, no need to completely reboot your system

**Comment by IrishMash** [comment]
I have tried that. To the extent of killing the processes. But will have the same issues when relaunching the program.
