### ISSUE TITLE
Global Hotkeys for Volume Control

### ISSUE THREAD

**Issue by jwmann** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#274]
Something that I've seen missing from *EVERY* Google Music Player I've used is global volume control.
Yes, you can change the volume using `-` and `=` while inside the player but that requires me to find the app and focus it to control it.

It would insanely appreciated if a Global Volume control hotkeys could be added.

Thank you.

**Comment by MightyPork** [comment]
When my pull request gets merged, this will be possible ;-)

**Comment by jwmann** [comment]
Beautiful :+1: 
Thank you very much! :smile:
