### ISSUE TITLE
D-Bus wrong volume output

### ISSUE THREAD

**Issue by SicariusNoctis** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2741]
When the volume is at exactly 0% or 100%, the following command:

    qdbus org.mpris.MediaPlayer2.google-play-music-desktop-player \
          /org/mpris/MediaPlayer2 \
          org.mpris.MediaPlayer2.Player.Volume

outputs the raw byte 0x01:

    

Expected behavior is of course either the string 0 or 1, respectively.

All other numbers between 0 and 1 are outputted correctly.

**Comment by MarshallOfSound** [comment]
@jostrander Is this one of those weird int type issues from the node-dbus library?

**Comment by jostrander** [comment]
This is probably related, but I don't have my ubuntu machine anymore to test on.
