### ISSUE TITLE
Well then fucken fix it.

### ISSUE THREAD

**Issue by IrishMash** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2743]
**OS:**

**Issue Descriptions:**

**Steps to Reproduce:**

**Comment by BrianAllred** [comment]
Not speaking for @MarshallOfSound, this is just my opinion.

You're the kind of user developers despise. The software is free. If you have issues with it, don't use it. Free software devs usually develop as a hobby. They don't have all the time in the world, especially not to fix issues so small that all you have to do is restart the client. **On top of that**, the issue you're bitching about has been resolved in code, it just hasn't been released. Again, the software is free and the developer does not profit from it. He may not have time to make releases every few days. If you paid attention to the repository, you'll see that he supports many different operating systems with many different packaging processes. It's probably a huge hassle to make a release, and speaking for myself, I probably wouldn't go through that hassle for a bug as tiny as this.

You can feel as entitled as you wish, but the fact remains that the developer doesn't owe you anything. He provides the software free of charge, developed on his own time. Your entitlement will only bring you frustration.

**Comment by MarshallOfSound** [comment]
👏 @BrianAllred That is exactly what I was typing up but you said it perfectly.
