### ISSUE TITLE
Application UI is slow on Linux when GPU is busy

### ISSUE THREAD

**Issue by excieve** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2744]
**OS:**
Fedora Linux 26

**Issue Descriptions:**
Same as some other Chromium/Skia-based applications the UI is very sluggish on Linux when the GPU acceleration is off and GPU is busy with something heavy such as CUDA workload. This sluggishness paradoxically goes away when acceleration is on. There's probably some bottleneck when buffers are copied to the GPU by compositor eventually.

Note that the OS desktop performance in general is normal, native apps are fine, it's only GPMDP and some other Electron apps, which disable acceleration by default, being slow at these conditions.

Please consider adding an option to force GPU acceleration instead of [always disabling it on non-macOS](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/main/configureApp.js#L17-L19). This option might need to ignore Chromium's GPU blacklist too.

**Steps to Reproduce:**
Launch GPMDP when running something compute-heavy on the GPU (e.g. ML models training, BOINC, etc).

**Comment by MarshallOfSound** [comment]
>  when the GPU acceleration is off and GPU is busy with something heavy such as CUDA workload

This doesn't make sense to me, we've disabled GPU acceleration so why would the GPU being over-utilized cause an issue?  Because we disable GPU acceleration all work is offloaded to the CPU and if you're doing super resource intensive stuff on that then there's not much we can do.

The reason GPU acceleration is disabled for all non-macos is to (a) reduce power load and (b) stop graphical bugs and crashes on linux

**Comment by MarshallOfSound** [comment]
Woops, leaving open for discussion

**Comment by excieve** [comment]
There are several parts of moving the buffers from the application to the GPU, in which the application itself is just a starting point. Correct me if I'm wrong but my understanding is that when no GPU acceleration is used it pretty much means that all the graphics buffers are stored in the system RAM and then at some point transferred to the GPU anyway by the compositor, which can be not as efficient as if operated entirely in the GPU memory. This is not really noticeable if the application isn't doing anything graphically intensive or GPU's resources are freely available for excessive copying but becomes a problem otherwise.

This same issue happens with desktop Slack and Rambox applications, which are also Electron based. In case GPU acceleration is disabled (it's provided as an option) or blacklisted there's sluggishness under load, when enabled — it's fast and responsive. Similarly with Sublime Text 3, which is Skia based (Chromium's rendering engine), except there's no option to enable acceleration on Linux.

While the desktop itself (GNOME 3), Firefox and all the native applications are responsive if just a little bit less snappy under load, GPMDP is close to unusable.

So what I'm proposing is to provide GPU acceleration as an option, which may be off by default.
