### ISSUE TITLE
Main page lies about not using chrome

### ISSUE THREAD

**Issue by carlbennett** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2745]
>Being a lightweight, standalone framework we use FAR less resources than having Google Play Music open in a standard chrome tab. This frees up your computer's resources to do things you care about, instead of wasting them on playing music.
([main page](https://www.googleplaymusicdesktopplayer.com/))

Literally uses Electron GUI, which is just fancy words for Chromium.

OK.

[Electron apps all share common vulnerabilities because of Chromium](https://twitter.com/jacobrossi/status/851992646151278592)
[Electron is flash for the desktop](https://josephg.com/blog/electron-is-flash-for-the-desktop/)
[Electron main page](https://electron.atom.io/)

**Comment by MarshallOfSound** [comment]
@carlbennett So a few things

> Main page lies about not using chrome

Uhhh, no where on the web site does it say we don't use Chrome, regardless though I'll say it here **we don't use chrome**.  We don't even use Chromium in it's entirety, we use the [Content Module](https://www.chromium.org/developers/content-module).

> Electron apps all share common vulnerabilities because of Chromium

If you actually read down that thread you'll actually see me contest that theory, a Chromium vulnerability does not translate into an Electron vulnerability lots of the time.

> Electron is flash for the desktop

I've responded to this elsewhere but I'll summarize my opinion on this post here.

Incorrect and misleading...  Lot's of the comparisons drawn in that article are making Slack (which is known as not exactly resource efficient) as synonymous with all Electron apps which are simply incorrect, I would go as far as to say that 99% of Electron apps are more efficient than the Slack app.  Then there's the whole flash was closed source, full of non-fixed security flaws, required separate downloads and acted as a plugin.  None of which occur with Electron.
