### ISSUE TITLE
Remove track from playlist scrolls away and redraws

### ISSUE THREAD

**Issue by focusaurus** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2746]
**OS: macOS 10.12.6**

**Issue Descriptions:**
When removing a track from a long playlist, the playlist scrolls back to the top. This makes it hard to remove several tracks from a playlist in a row.

**Steps to Reproduce:**
- View a long playlist
- Scroll to a track, use the context menu to remove the track from the playlist
- Expected: Track disappears but nothing else about the screen changes
- Actual: scrolls to top of playlist and shows loading spinner

Note, multi-selecting several tracks and being able to remove them all would be an acceptable alternative, but it seems there is no menu option for that in the multi-track context menu.

**Comment by MarshallOfSound** [comment]
This has been raised before and it is a GPM issue ( the same thing occurs in browsers)

**Comment by focusaurus** [comment]
Understood. FYI I did search open and closed issues and didn't find a duplicate.

**Comment by MarshallOfSound** [comment]
@focusaurus Yeah, you kinda have to know what to search for sometimes.  It's the same thing as these two

#2657  
#2656
