### ISSUE TITLE
Feature Request: Move back button to top left on the Windows client

### ISSUE THREAD

**Issue by Hoahoo** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2747]
**OS:**
Windows 10 (1703)

**Issue Descriptions:**
I was wondering if it would be possible to move the Back Button in the Windows client from the Search box to the top left to be consistent with the UI? I know this design change may conflict with other OSs, but it just seems weird to have the back button embedded in the search field on the right

![screenshot](https://user-images.githubusercontent.com/17574723/30031529-e347b414-915f-11e7-9a72-87862a58d7b1.png)

**Comment by MarshallOfSound** [comment]
That's a verrryyy UWP thing and requires the app to have a UWP frame, technically we could implement this ourselves when our custom frame is enabled but it's not something I'm going to commit time to.  If someone wants to take a crack at this, by all means, give it a go and I'll review, but I don't think it fits with our current custom frame and we can't enable it at a windows level
