### ISSUE TITLE
Chromecast Groups - only sends audio to one speaker

### ISSUE THREAD

**Issue by flux1315** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2748]
**OS:**

**Issue Descriptions:**

**Steps to Reproduce:**

**Comment by flux1315** [comment]
saw that this has already been addressed multiple times.  Is there a solution?

**Comment by jostrander** [comment]
There's a fix on electron-chromecast repo that I don't think was merged here yet. Just needs someone to test and ck got it works.
