### ISSUE TITLE
Browser-style "Back button"

### ISSUE THREAD

**Issue by y-batsianouski** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2751]
As google play music is a web app for browsers with "back button: it is not usefull to navigate inside application without that button.

**Comment by jostrander** [comment]
This already exists in the search bar on the right hand side.

**Comment by y-batsianouski** [comment]
Wow! Really! I use app for 1.5 years and never seen it before! :-o

But this place isn't clear and not usefull. Hopefully you move it into top left corner.
