### ISSUE TITLE
Stopping the music results in no sound in the whole system

### ISSUE THREAD

**Issue by Frizi** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2754]
**OS:**
That happens on macOS 10.12.6 and I remember it happening even on earlier versions (both on Macbook and Macbook Pro).

**Issue Descriptions:**
Sometimes when I pause the music, the whole system sound is stopping. It seems to be happening at random. From videos on youtube (chrome/firefox) to system sounds like a bell notification sound, everything just goes silent.
Just closing the application doesn't help, I actually have to close it while playing. Reopening the application without full system restart reliably triggers the issue again (system goes silent until I play the music).

**Steps to Reproduce:**
As it seems to be happening at random, it's hard to tell. It usually happens for me once in a few days and I mostly notice that when pausing music to watch a video on youtube.

I can help debugging that next time it happens on my machine if you wish. Having no experience with the codebase though, I would need some general directions where to look.

**Comment by Frizi** [comment]
Here's the debug info btw.
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/1289851/debug_info.zip)

**Comment by MarshallOfSound** [comment]
I've seen reports of this before with other media applications, the theory is it's a Sierra issue.  I actually had it happen to me with VLC a few times.  It sounds like you've figured out a workaround that works for you though 👍 

Not much I can do with this, we're definitely not doing something like `os.muteAllThingsForTheLols()` 😆

**Comment by Frizi** [comment]
Sure thing, though what would be so special about music players here? I have plenty of audio applications and only music players are magically problematic. This also never happened with in-browser player.
