### ISSUE TITLE
Provide 64-bit Windows release

### ISSUE THREAD

**Issue by pedrogarcia** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2756]
Chrome 64-bit is fast and snappier. You can check by running the two versions of the browser on Windows, and all the animations on the Google Play Music website lag and stutter just as bad on Chrome 32-bit as on the GPMDP app. 
On Chrome 64-bit, the GPM website is way faster and animations almost never stutters. 
By providing a 64-bit version of the app on Windows, the app will feel as fast as the GPM website.

**Comment by MarshallOfSound** [comment]
See #2146 for why I'm not planning on releasing an x64 build.  Not saying it won't happen, just that I don't have any immediate plans for it.
