### ISSUE TITLE
Play random album

### ISSUE THREAD

**Issue by leeon-lee** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2757]
Please implement possibility to play random album from library. Instead of having Google native shuffle, playing random song, random album is selected, played from start to beginning in normal song order, than selecting another random album.
This is being requested from google like for many years already, but Google won't listen to that. I though this will be a major enhancement lot of people waiting for.
[Google Play Help Forum
](https://productforums.google.com/forum/#!msg/play/DtfUVQeKJrw/KNXXGMzKAwAJ)

**Comment by MarshallOfSound** [comment]
This is not a trivial feature to implement outside of core GPM and isn't something that's in scope for this player.  You could implement it yourself using our websocket API or the upcoming plugin functionality
