### ISSUE TITLE
Playback API bug with Monstercat Visualizer

### ISSUE THREAD

**Issue by AMDSY3D** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2758]
I got Monstercat Visualizer to go along with this, but a problem is that the visualizer doesn't read the progress of the song when the song automatically changes. It senses when I press next, but doesn't sense it when it automatically changes. It senses that the song changes, but the progress part of the song does not. I asked the devs for Monstercat and they said that it's a problem with the Playback API rn and that you will release a patch in your next update.

**OS:** Windows 10 Pro 64

**Issue Descriptions:** If a new song comes on, the progress of the new song is added on top of the progress/duration of the last song. ex: first song is 3:40, next song comes on but the progress says 4:50

**Steps to Reproduce:** Download Monstercat Visualizer, and let the song go on to the next

**Comment by MarshallOfSound** [comment]
>  I asked the devs for Monstercat and they said that it's a problem with the Playback API rn and that you will release a patch in your next update.

So why raise this issue? 😕 This is fixed in master and will be released in the next update
