### ISSUE TITLE
Ellipsis colour does not match custom theme text colour

### ISSUE THREAD

**Issue by hferrier** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2759]
**OS:** MacOS

**Issue Descriptions:** 
Ellipsis that appears when hovering over toolbar (i.e. extra buttons are shown) does not match the text colour set by the custom theme (dark, in this case).
See the image below. The ellipsis (three tiny li'l horizontal white dots) are white, but the text they are supposed to be matching is a shade of grey.
<img width="141" alt="gpmdp" src="https://user-images.githubusercontent.com/26944064/30331085-30872118-981a-11e7-927c-e20f46a3a345.png">

**Steps to Reproduce:**
1. Enable a dark theme
2. Play a track with a long-ish artist and album name
3. Hover over the playback control area
4. Be really anal about what constitutes an "issue"
5. Submit it anyway because it's Sam and he probably deserves it ❤️

**Comment by jostrander** [comment]
> Be really anal about what constitutes an "issue"

Heh, literally _unplayable_...

On a more serious note, can you raise this over in the [theme repo](https://github.com/gmusic-utils/gmusic-theme.js) ?
