### ISSUE TITLE
Windows 7 - Problem connecting to Google Play(?)

### ISSUE THREAD

**Issue by RodolfoSan** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2761]
I just got a new PC with Windows 7, installed the app and no problems in the process. But the moment I start playing a playlist it sometimes skips or lags when doing so. What I've seen that happens is that the play button goes to pause but greyed out and comes back to play button like five or six times and then skips the song. This goes for about four songs and then the error message "Cant connect to Google Play" appears. 

I've used the Play Music web app and I come across no issues. I've tried reinstalling to no avail. Is there some kind of clean install or what can I do to make this problem stop happening?

This is not the first time I use the app on Windows 7, as just recently had another Windows 7 machine and it worked flawlessly.

**Comment by MarshallOfSound** [comment]
@RodolfoSan It is either your network connection or you got hit with some bad A/B testing from google, give it a few days and everything should return to normal.  Can't do much about Google experimenting on users 😆
