### ISSUE TITLE
Lyrics skipping

### ISSUE THREAD

**Issue by pyskell** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2762]
**OS:** Windows 7

**Issue Descriptions:** Lyric scrolling does not track correctly when songs change. The time progress does not always reach the end.

**Steps to Reproduce:**

1. Play Song A all the way through.
1. Open up the lyrics and leave them open.
1. At the end of Song A but the progress bar has not reset (left at anywhere from 80-100% typically).
1. Song B starts, lyrics still left open.

The progress bar continues from that 80% point for Song B, despite being at the start of the song, and as a result most of the lyrics scroll by fast to match the progress bar.

It could likely be solved by ensuring that the progress tracking is reset to `0` at the start of each song.

**Comment by MarshallOfSound** [comment]
This is the time fetching issue that was fixed in master
