### ISSUE TITLE
5.1 doesn't work for me

### ISSUE THREAD

**Issue by Rikrius** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2763]
**OS:Windows 10**

**Issue Descriptions:5.1 doesn't work for me**

**Steps to Reproduce:5.1 doesn't work for me**

**Comment by jostrander** [comment]
5.1 is experimental and may not work for everyone, and is really not something we're actively looking to maintain or fix. If it works for you, great! If not, then sorry, but there's nothing we can really do. You can try troubleshooting your drivers, or try different audio settings on your computer. Obviously however more information in the original would lead me to give better suggestions. Either way, YMMV with _Experimental_ support for multiple audio channels.
