### ISSUE TITLE
"Track Progress in Taskbar" no longer working after 4.4.1 update

### ISSUE THREAD

**Issue by TokenRing** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2764]
**OS:**
Windows 10 x64
**Issue Descriptions:**
Ever since the 4.4.1 update, when "show track progress in the taskbar" is turned on, progress is no longer shown while song is playing. Instead, a green 'wave' pulses from the left to the right side of the icon, over and over again about once per second, and track progress is not shown at all.
![gpmdp_taskbar_issue](https://user-images.githubusercontent.com/10012384/30496786-22ffcea2-9a16-11e7-99dc-10b0c5fa842b.gif)

**Steps to Reproduce:**
 In Windows, I have "use small taskbar buttons" turned on, and "combine taskbar buttons" set to "never" - basically, I want Windows 10's taskbar to look like it did in Windows XP in terms of information density, if not the theme. I've also tried disabling this style to see if that makes GPMDP's track progress indicator work, but it does not seem to make a difference.

The only thing I know for sure is that the problem appeared immediately after the update to 4.4.1. It worked great with 4.4.0!

**Comment by MarshallOfSound** [comment]
This is the time fetching issue that was fixed in master

**Comment by TokenRing** [comment]
Thank you so much Marshall! :) I'm new to Github; I see that the public-facing website still lists 4.4.1 as the "release" - so it's fixed in the master here on github so if I were to download the 'current version' from github, I'd be getting something newer than 4.4.1 and newer than what is on the consumer-friendly website?

Or, do you just mean that it's fixed [in this list](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/compare/v4.4.1...master), and when you have enough fixes that you think warrants a public release to 4.4.2 (or whatever) then it will be patched?

Or lastly, if I wanted to, I could download the current master, compile it myself, and get the fix right away?

Sorry, I know those are total n00b questions but I promise I won't ask anymore!

**Comment by jostrander** [comment]
>Or, do you just mean that it's fixed in this list, and when you have enough fixes that you think warrants a public release to 4.4.2 (or whatever) then it will be patched?

> Or lastly, if I wanted to, I could download the current master, compile it myself, and get the fix right away?

This, and this are correct.
