### ISSUE TITLE
macOS: Mini Player doesn't shrink the window down, causing Album Art to stretch

### ISSUE THREAD

**Issue by nzgamer41** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2765]
**OS:**
macOS 10.12.6
**Issue Descriptions:**
Opening Mini Player doesn't shrink the window, but the UI elements either shrink to mini size, or if the program was running in full screen previously, the UI elements stretch to fit the size of the window, as does the album art. [Here](https://imgur.com/a/bC7Ht) is an example of the UI elements stretching and [Here](https://imgur.com/a/ifWg8) is an example of the UI elements not stretching but the Album art stretching.
**Steps to Reproduce:**
1. Open GPMDP on a Mac (I'm unsure whether this happens on Windows or Linux)
2. Play some music
3. Click on the mini player button on the bottom right of the window
4. Watch as the Album Art stays the same size but the UI elements either shrink down or stretch

**Comment by MarshallOfSound** [comment]
Duplicate #2269
