### ISSUE TITLE
First item under under Recent Activity on Home page, shows as playing after completion

### ISSUE THREAD

**Issue by whalingman** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2767]
**OS:** Win 7 - SP1

**Issue Descriptions:**
Playing the first item shown under Recent Activity on the Home page, shows as playing after it's finished playing in its entirety. You're unable to replay via the primary play button (shows grey), or the mini play button that shows on recent activity icon.

Must click into item in order to play.

**Steps to Reproduce:**
1. Play first item from Home page located under Recent Activity.
2. Let it play through in entirety
3. Try and replay, by repeating the above steps. Icon also shows as playing.

**[Photo](https://i.imgur.com/IQeupWH.jpg)**

**Comment by MarshallOfSound** [comment]
This UI is controlled by google, you should raise this feedback on their product forums
