### ISSUE TITLE
Some tracks don't scrobble on LastFM

### ISSUE THREAD

**Issue by mylesmyles** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2768]
I've noticed a lot of my tracks don't scrobble on LastFM. Tracks that have problems are from some of the more obscure albums I have on Google Play.

I think manually uploaded tracks are the ones that don't scobble, but I'll have to do some digging to make sure that is the case. The weird thing is that they show as "listening now" but don't actually scrobble once the track is finished.

Before using the desktop app, I used the "Google Play Last.fm Scrobbler" on the Chrome web store and that was able to scrobble almost all the tracks I played, so I know it is possible. If I find some time I might try and fix the issue myself and send a merge request. Cheers!

**OS:** Windows

**Issue Descriptions:** LastFM

**Steps to Reproduce:** Play obscure tracks/manually uploaded tracks. Not sure of a way to consistently reproduce at the moment

**Comment by MarshallOfSound** [comment]
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues?utf8=%E2%9C%93&q=is%3Aissue%20last.fm%20is%3Aclosed%20

This is a duplicate, please check closed issues before opening new ones 👍 Fix will be in the next release

**Comment by mylesmyles** [comment]
@MarshallOfSound Ha, sorry, I just checked open issues. Will look at the closed ones next time. Thanks!
