### ISSUE TITLE
Recursive copy or something?

### ISSUE THREAD

**Issue by z3ntu** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#277]
When I run 
```
npm install
npm run package:linux
```
in Arch Linux, the folder `electron-packager` contains `linux-ia32` -> `Google Play Music Desktop Player-linux-ia32` -> `resources` -> `electron` and then again `electron-packager` and this will continue until the filename is too long for ext4 to handle. My original `electron-packager` folder is now 5.7 GB big...

**Comment by MarshallOfSound** [comment]
Sounds like your node / npm is borked.

What node version are you using?

**Comment by dylanlesko** [comment]
I'll take a look at that later when I have my laptop on. Does running `npm run package:deb` have a similar result? It should produce usable binaries in `dist/Google-...`.

Also, what about `npm run make:linux`? I have an idea of what the issue might be, but I can't look at it right now.

**Comment by z3ntu** [comment]
```
$ node --version
v5.7.1
$ npm --version
3.8.0
$ gulp --version
[06:37:16] CLI version 3.9.1
```

**Comment by MarshallOfSound** [comment]
Can you try dropping to LTS node (4.3.1)

**Comment by z3ntu** [comment]
That isn't available for Arch Linux... :D

**Comment by z3ntu** [comment]
So with node version `v4.3.2` running `npm run package:linux` works and finishes and I have contents in the `dist` folder.
But with [this](https://gist.github.com/z3ntu/80fc7cd4a4bb5f15ea5a) PKGBUILD file it doesn't work (again this "loop" which happens after
```
[07:33:11] Starting 'package:linux'...
Packaging app for platform linux ia32 using electron v0.36.10```

**Comment by MarshallOfSound** [comment]
I have no idea how PKGBUILD works, I would assume it's buggered... :+1:

**Comment by MarshallOfSound** [comment]
Closing as PKGBUILD is not supported internally (someone else made it) and the build process has been proven to work

**Comment by z3ntu** [comment]
@dylanlesko `npm run make:linux` returns that the command `dpkg-deb` was not found.
