### ISSUE TITLE
Switching Last.fm login

### ISSUE THREAD

**Issue by wan-an** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2770]
**OS:**
Windows 10
**Issue Descriptions:**
Unable to change Last.fm account
**Steps to Reproduce:**
Once logged in to one Last.fm account, when you log out and attempt to sign-in it will use the stored history of the previous login to log back in.

I'm transitioning to a new Last.fm account but am unable to switch over on GPMDP. Tried uninstalling and re-installing. Seems wherever the cache file for GPMDP is persistent. I've done this on Mac (found where the cache file was and removed the last.fm share key in the config file so it reset everything). I can't seem to find the file on Windows.

Anyone know where the config is stored on Windows?

**Comment by jostrander** [comment]
`%appdata%\Google Play Music Desktop Player\` is the folder you're looking for I believe.

**Comment by wan-an** [comment]
Thanks jostrander!

To any future travelers wondering, it was here on my Win 10 installation:
\Users\[user]\AppData\Roaming\Google Play Music Desktop Player\json_store\.settings.json

**Comment by StNick** [comment]
> **OS:**
> Windows 10
> **Issue Descriptions:**
> Unable to change Last.fm account
> **Steps to Reproduce:**
> Once logged in to one Last.fm account, when you log out and attempt to sign-in it will use the stored history of the previous login to log back in.
> 
> I'm transitioning to a new Last.fm account but am unable to switch over on GPMDP. Tried uninstalling and re-installing. Seems wherever the cache file for GPMDP is persistent. I've done this on Mac (found where the cache file was and removed the last.fm share key in the config file so it reset everything). I can't seem to find the file on Windows.
> 
> Anyone know where the config is stored on Windows?

Can you share where you found the file on your Mac?
