### ISSUE TITLE
Featurerequest: Add function to check for update and notify if there is a new version released

### ISSUE THREAD

**Issue by jensskott** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2771]
Simular features are in this codebase where it automaticly checks for new updates and notifies me when there are new downloads available.

https://github.com/wavebox/waveboxapp

**Comment by MarshallOfSound** [comment]
We have auto update functionality on Windows and macOS and Debian has an apt repo for you to use
