### ISSUE TITLE
Feature Request: More information about track on Touchbar and context action buttons

### ISSUE THREAD

**Issue by yangwao** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2772]
**OS:** OSX Sierra

Would be really nice to have more information about actually playing track, thumbs up/down and switch to radio of current Artist i.e (some other context choices), I would definitely replace it for scrolling trackbar. 
Is this possible or scrollbar is only way for now? Probably can donate too.
Thanks for app, just found it today, great work!

**Comment by MarshallOfSound** [comment]
> Is this possible or scrollbar is only way for now? 

With other apps in focus all we can do is provide media metadata and macOS decides what to display, they normally just display the play/pause buttons and the progress scroller.  We do give them information like the current playing track but they don't do anything with it currently
