### ISSUE TITLE
Feature Request: Use suggestions for batches of songs, albums, entire library

### ISSUE THREAD

**Issue by nbroad1881** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2773]
No issues to report, but it would just be more convenient if you could apply the google suggestions for track/album metadata to batches of albums, artists, or songs instead of going one by one.

**OS:**

**Issue Descriptions:**

**Steps to Reproduce:**

**Comment by jostrander** [comment]
I don't believe this is possible, this is under a menu that we can't access, and if we could, accessing the songs, albums, and the entire library isn't something we can do via code. Sorry!
