### ISSUE TITLE
Bug; Feature Request: Adding a song to a playlist results in locking the player.

### ISSUE THREAD

**Issue by dhbuckley** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2774]
**OS:** Mac OS 10.12.4

**Issue Descriptions:** When adding a song to a playlist: Using mini player, lower right expand to full player, click 3 dots, choose playlist -- app locks up for 10 - 15 seconds, refuses input, music generally continues to play but sometimes pauses. Have you considered adding "add to playlist" directly from mini-player?

**Steps to Reproduce:** repeated all of above, happens every time.

Super grateful for your work; hope helpful. I am relatively non-techy so cannot help fix but this seemed worthwhile. I have attempted to attach the debug file, please lmk if not successful. dhbuckley@gmail.com

**Comment by MarshallOfSound** [comment]
> Have you considered adding "add to playlist" directly from mini-player?

This is not something we can do easily

> app locks up for 10 - 15 seconds

This sounds like some bad logic on googles end, probably some kind of synchronous lock while the song is added to the playlist.  We don't go anywhere near this functionality so any issues with it will come from GPM itself
