### ISSUE TITLE
Thumbs down song won't play when clicking play button on song; freezes UI

### ISSUE THREAD

**Issue by hentercenter** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2775]
**OS:**
Mac OS X Sierra (10.12.6)
**Issue Descriptions:**
Clicking play on a song that has a thumb down will not play the song. If this song is in a playlist/album of songs that are all thumbed down, the UI will freeze and you have to quit and re-open the application to get it working again.
**Steps to Reproduce:**
1. Click play on a thumb down song (song will not play; web client of GPM plays the song)
___
1. Have album or playlist full of thumb down songs
2. Click play on any song
3. Client UI will freeze, attempting to play next non-thumbed down song when there is none.

**Comment by MarshallOfSound** [comment]
Sounds like you have enabled

> Automatically skip disliked songs

You should disable it if you want to listen to those songs
