### ISSUE TITLE
Popping or crackling sound on macOS 10.12.6

### ISSUE THREAD

**Issue by briancalderon** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2776]
**OS:** macOS 10.12.6

**Issue Descriptions:** When listening in the browser, the music plays just fine. But when listening in GPMDP, there's a popping sound/crackling sound/almost as if the music is skipping. I've been noticing this for a few weeks since I got my new iMac in August.

**Steps to Reproduce:** I'm not sure how to really produce this as it doesn't happen on the website in the browser. But I still wanted to report it since I'm seeing no issues.

**Comment by lightlessfilms** [comment]
This does also happen on Windows 10 Pro Version 1703 Build 15063.608.
Google Play Music Desktop Player Version 4.4.1

**Comment by lightlessfilms** [comment]
@briancalderon While messing with the settings I found that when I disable the 'Experimental support for multiple audio channels such as 5.1 audio' and restart the program, the audio plays normal again.

How to disable the settings:
- Go to Main menu and select Desktop Settings
- Select Playback and uncheck 'Experimental support for multiple audio channels such as 5.1 audio'
- Restart Google Play Music Desktop Player


![image](https://user-images.githubusercontent.com/7137900/30783555-17fa8aac-a145-11e7-8631-b711e3fa3e9f.png)
![image](https://user-images.githubusercontent.com/7137900/30783562-28eafe78-a145-11e7-82e4-2592f7f7434e.png)

**Comment by jostrander** [comment]
Any confirmation as to whether that fixes this?

**Comment by briancalderon** [comment]
I'm on High Sierra now. I think lightlessfilms was right. Upon FDR-ing my computer and updating to 10.13—the setting is now off by default. I must have had it enabled before out of curiosity; at least we know it's definitely still experimental!

**Comment by jostrander** [comment]
Definitely experimental, only Google's end so not sure it will ever be out of experimental stage. Closing because there's really nothing we can do here except suggest disabling that option.
