### ISSUE TITLE
Autoscrolling re-enables itself

### ISSUE THREAD

**Issue by ChaseyLain** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2777]
**OS:Windows**

**Issue Descriptions:Auto scrolling re-enabled itself**

**Steps to Reproduce: Look at call #2603**

Hello! Please re-open ticket #2603, after it was closed myself and another user were able to reproduce it consistently, however there seems to be no way of flagging a ticket for re-opening, hence me creating this ticket.

Thanks again for your time. It is much appreciated!

**Comment by MarshallOfSound** [comment]
Fixes RE scrolling have gone in to master since that issue was raised, gonna close this out and will reopen the linked issue if the the issue persists after the next release

**Comment by ChaseyLain** [comment]
@MarshallOfSound As of April 1st 2018 the issue still persists. (Not! an april's fools! ;-) )

**Comment by ChaseyLain** [comment]
@MarshallOfSound As of 5th May 2019 the issue still persists.
