### ISSUE TITLE
Feature request? There is no warning when adding songs to playlist multiple times

### ISSUE THREAD

**Issue by tomster10010** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2778]
When adding a song to a playlist in the web app, if the song is already in the playlist it gives you a warning, allowing you to not add repeated songs to playlists.  This doesn't happen in GPMDP.

**Comment by jostrander** [comment]
This isn't something we can't fix as playlists are hidden way way deep in the code and are not easily accessible. You can raise this issue on the Google product forums and someone may pick it up if you're lucky.

**Comment by SolarLiner** [comment]
This doesn't happen on my end
![image](https://user-images.githubusercontent.com/4302963/30816357-12794d12-a216-11e7-8c5b-15bb227debe1.png)
