### ISSUE TITLE
KStatusNotifierItem/AppIndicator support

### ISSUE THREAD

**Issue by michaudg** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2779]
**OS:** ArchLinux

**Issue Descriptions:** GPMDP tray icon appears in the GNOME systray instead of the top panel as supposed with the KStatusNotifierItem/AppIndicator extension. This extension should be used by Ubuntu 17.10.

**Steps to Reproduce:** Install [this extension](https://extensions.gnome.org/extension/615/appindicator-support/) and launch GPMDP.

Ref: http://www.omgubuntu.co.uk/2017/08/ubuntu-sees-sense-will-support-indicator-applets-ubuntu-17-10

**Comment by jostrander** [comment]
Currently doesn't work with Electron based apps from the link you posted. I'm not sure what needs to be done upstream because I don't know exactly what that does from a technical standpoint.

**Comment by michaudg** [comment]
You're right: https://didrocks.fr/2017/08/23/ubuntu-gnome-shell-in-artful-day-7/

« However, we identified that some applications (like dropbox or Skype) don’t work yet. Part of the issue for electron apps is that the chromium framework is harcoding the Unity session name in XDG_CURRENT_DESKTOP. However, this is even invalid as of today in the unity session as its value is Unity:Unity7 (this environment variable is a list in the specification) since Ubuntu 16.10. We are thus working to push a proper fix upstream, and will reach to those application developers to rebuild their applications to get the indicator showing up in the incoming artful release. »

**Comment by jostrander** [comment]
Track upstream:

https://github.com/electron/electron/issues/10427

**Comment by SolarLiner** [comment]
Basically Electron uses GNOME's legacy sys tray to display tray icons. Unity implemented an App Indicator API that also allows icons to be used in the system tray (but in a much better structured API). GNOME with version 3.26 will drop the sys tray, and with Ubuntu 17.10 shipping with GNOME (+ extensions, including the App Indicator one), applications using the systray (but not the app indicator) won't show in the tray.

In the case of GPMDP it's not a big issue as MPRIS is supported and the systray would be duplicated anyways (both expose playback control and current track information). I would even go as far as having an option not to use a systray at all on Linux for those who don't want it.

**Comment by MarshallOfSound** [comment]
Closing out here, if / when Electron changes it's tray implementation GPMDP will get the change in an update 👍
