### ISSUE TITLE
Terminal Stays open after Booting Mac

### ISSUE THREAD

**Issue by tehdef** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2780]
**OS:** MacOS Sierra

**Issue Descriptions:** Whenever I reboot my machine, Terminal loads WITH GPM Desktop app and stays open. If I try to close Terminal, it only gives me the terminate option, and then also clears all data from the GPM app, and displays a blank screen.

I saw that you closed a previous bug. I responded to that bug awhile ago and you never responded again and I've had this issue for at least 4 months now.

**Steps to Reproduce:** Reboot device. GPM opens on launch. Terminal opens as well. Attempt to close terminal, get Terminate and Cancel. Terminate closes terminal but also greyscreens GPM, cancel leaves both working.

**Comment by MarshallOfSound** [comment]
> I feel you were not taking your due diligence to investigate the issue properly.

I investigated, the issue could not be reproduced, the issue appears to affect 1-2 users and therefore I made the fair assumption that it was down to the user specific environment on the machines in question.

I maintain this project in my free time, I is no level of "due diligence" required of me.  I always investigate **every single issue** and follow it through to resolution, even if I do not respond to comments on closed issues please believe me when I say I read them.  I get emails for every single one of them.

**Comment by tehdef** [comment]
I removed the due diligence comment because I realized it came off bad. I'm sorry about that. I find it funny that you decided to attack that portion of a removed comment rather than attempt to provoke more data from me. 

Here is picture of what happens when I load up my macbook. Can we try to fix this instead of focusing on something I removed? 

Thank you.

![screen shot 2017-09-25 at 11 29 30 am](https://user-images.githubusercontent.com/10883556/30819599-d7b2e836-a1e4-11e7-9b4b-824c232b4986.png)
![screen shot 2017-09-25 at 11 28 02 am](https://user-images.githubusercontent.com/10883556/30819598-d7b2e07a-a1e4-11e7-9f32-60b885838d23.png)

**Comment by MarshallOfSound** [comment]
@tehdef Removing something after the fact doesn't eliminate the fact it was your initial reaction 🤔 

That said, from that log it looks like you are running High Sierra, is that the case?

**Comment by tehdef** [comment]
Correct. This has been an ongoing issue since Sierra though. Been
experiencing it for the better part of 4-6 months.

**Comment by dzeikei** [comment]
![image](https://user-images.githubusercontent.com/377477/31105337-1d6b0098-a82f-11e7-903c-179a26738e34.png)
This is what I get
