### ISSUE TITLE
Possible to change App name is Windows Store

### ISSUE THREAD

**Issue by OpNop** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2781]
Love that this app has come to the windows store, but hate that its named GPMDP, with the non store version its so easy to find by just typing "play music" in the start menu, but with the store version I find myself trying to remember the order of the abbreviation is.

**Comment by MarshallOfSound** [comment]
Windows store will not allows trademarked works in the app name without owner permission.  In this case we can't use "Google" or "Google Play Music"

**Comment by OpNop** [comment]
I understand, and I know the "there are other apps on the windows store with google trademarks in the name (even paid ones)" isn't a real answer. But looking at the rules, a simple way to do it would be to rearrange the order of the name.

Looking at the Windows store policy [11.2](https://msdn.microsoft.com/en-us/library/windows/apps/dn764944.aspx#pol_11_2) they allow for "used as permitted by the rights holder", now looking at [Google Branding](https://www.google.com/permissions/trademark/rules.html) they give permission to use the brand names as an adjective.

A simple idea would be for the Windows Store, calling the app something like "Desktop Player for Google Play Music" should be a valid use of the trademark and also pass the Windows Store policy

**Comment by jostrander** [comment]
It's really treading a fine line though, and for what? The name doesn't change the way the software operates. There's really not a whole lot to gain by changing the name in comparison to what could happen if they decide we're violating the rules.

**Comment by OpNop** [comment]
Purely ease of use, I may be jaded coming from the standalone version where I can launch it really easily and then when I come home and try to launch the store version, I have to stop and think about what the stupid acronym is, just giving some input. But technically the logo you are using is a violation of google branding already. You could also just request permission from google to use the name, they have a form right on the branding page. Get user friendly and be safe legally, Win Win situation ;)
