### ISSUE TITLE
No TouchBar Support in High Sierra

### ISSUE THREAD

**Issue by Colecperrine** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2782]
Running MacOS High Sierra currently, public download. I have lost the playing music toggle with the playhead and pause, play, skip icons etc. 
- Macbook Pro 2017 13' on 10.13.0

To replicate: 
- Play any song and enter any other app
- The tiny playing music icon does not show in the Touch Bar, thus shortcuts can't be accessed.
![img_20170926_000039](https://user-images.githubusercontent.com/32288061/30843337-f2c1af2c-a24d-11e7-9b6a-6d33d8a97c3a.jpg)
<img width="1440" alt="screen shot 2017-09-26 at 12 00 00 am" src="https://user-images.githubusercontent.com/32288061/30843336-f2bf5a42-a24d-11e7-805f-65e04498e121.png">

**Comment by MarshallOfSound** [comment]
@Colecperrine I haven't updated my mac to High Sierra yet so I can't debug this for a while.  (I normally wait at least a month after public release for things to stabilize)

**Comment by MarshallOfSound** [comment]
Just tested this on a friends macbook with High Sierra and the touch bar stuff works fine.  I'd suggest giving your mac a quick reboot to see if that fixes it.

**Comment by parkerbrownxyz** [comment]
I am having the same problem with version 4.4.1 running on macOS High Sierra 10.13. Rebooting does not fix the issue. I also tried uninstalling and reinstalling the app, but that didn't help either.

**Comment by Colecperrine** [comment]
Same here, I got it to work for a few minutes but it went away immediately. The "Now Playing" item in notification center works for play, pause, and skip, but it doesn't show a timestamp and also says "undefined" for any metadata. Rebooting doesn't help.

**Comment by Colecperrine** [comment]
Update: The issue doesn't appear to happen on 10.13.1, it may have just been an error with 10.13.0 on the Macbook 13", any similar results from anyone else?

**Comment by parkerbrownxyz** [comment]
It's still not working for me on 10.13.1, unfortunately. ☹️

**Comment by Colecperrine** [comment]
Lost it again, seems to only work on the first try after rebooting.

**Comment by parkerbrownxyz** [comment]
When I play music in the app and open Notification Center, the Now Playing widget says "Undefined" as seen in this screenshot: 
![gpmdp_screenshot](https://user-images.githubusercontent.com/17183625/32855902-65787814-ca00-11e7-9bf3-ca2adef5a421.png)
![image](https://user-images.githubusercontent.com/17183625/32855897-619b24a8-ca00-11e7-81c6-17dc65919025.png)

I suspect the touch bar issue is a side effect of a bug in the Now Playing feature. Should I create a new issue for this @MarshallOfSound?

**Comment by tehdef** [comment]
Not trying to re-open a semi-oldish issue here, but I have a comment on this. Unfocused, seems to be working fine. Focused, it has no controls on the touch bar. I can use spacebar and arrow keys, but maybe it would be nice to have that bar present when the app is focused? 

Thanks!
