### ISSUE TITLE
Gnome notifications are not acting as expected

### ISSUE THREAD

**Issue by kevincianfarini** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2783]
**OS:**
Ubuntu Gnome 16.04, Gnome shell version 3.18.5

**Issue Descriptions:**
In my experience, on macOS, Ubuntu with the Unity desktop environment, and Windows, there is a persistent notification for the playing song as well as notification bubbles when a new song begins to play. 

On Gnome desktop environments, this is not the case. I'd expect the persistent notification to live in the notifications panel like other music players do. Furthermore, there is no notification bubble activated on song change. I have found no settings in the "Desktop Settings" panel that solves this issue. When running the Unity desktop environment, the desired result is the default behavior. 

**Steps to Reproduce:**
Run GPMDP on a Linux distro with Gnome

**Comment by kevincianfarini** [comment]
Turns out, enabling the experimental feature "allow desktop notification" in the actual Google Play Music settings allows notifications on song change. This however doesn't solve the persistent notification problem.

**Comment by jostrander** [comment]
If I'm not mistaken the persistent notification you're talking about is actually provided by MPRIS on linux, usually under the volume drop down or however that widget is designed in gnome.

**Comment by SolarLiner** [comment]
It's actually an extension: https://extensions.gnome.org/extension/55/media-player-indicator/

**Comment by kevincianfarini** [comment]
Interesting that Gnome doesn't have this feature OOB. Thanks for the saved effort. I was actually digging around to see if I could make a PR to solve this but was having no luck. Probably because nothing was wrong,,,,
