### ISSUE TITLE
linux machine still sleeps even if prevent sleep is checked in the player

### ISSUE THREAD

**Issue by gnowxilef** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2784]
**OS:**
App Details:
Version: 4.4.1
Electron Version: 1.6.1
Development Build: false

Operating System Details:
OS: linux
OS Version: 4.4.0-96-generic
OS Arch: x64

**Issue Descriptions:**
linux machine still sleeps even if prevent sleep is checked in the player

**Steps to Reproduce:**
1. check "prevent sleep" button in the desktop settings.
2. wait a few minutes for screensaver to not activate
3. screensaver activates

**Comment by MarshallOfSound** [comment]
The block sleep functionality comes directly from chromium and entirely depends on what your OS thinks it should do with the request.  Some OS's will allow the screensaver but not turn the display off.

https://github.com/electron/electron/blob/master/atom/browser/api/atom_api_power_save_blocker.cc#L77
