### ISSUE TITLE
Feature Request: Native macOS notifications with song information

### ISSUE THREAD

**Issue by mark-rodgers** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2785]
**OS:** macOS Sierra 10.12.6

Maybe this is already a feature that I just need to enable but it would be nice to get a notification whenever a new song comes on. Or at least have an option to trigger a notification displaying Artist and Track, would be extra nice to display thumbnail of album artwork but thats just eye candy. I frequently use the skip and pause/play keys on my keyboard and it would be nice to see name/artist of song coming on while cycling through music this way.

![screenshot](http://cdn.osxdaily.com/wp-content/uploads/2012/08/now-playing-song-itunes-notification-center-os-x.jpg "screenshot")

**Comment by MarshallOfSound** [comment]
You can enable notification in your Google play music settings

**Comment by mark-rodgers** [comment]
@MarshallOfSound are you sure? If so can you point me where this setting is at? I'm looking at the desktop settings for the macOS client and don't see this anywhere.

**Comment by jostrander** [comment]
Desktop notifications are under standard Google Play settings, not desktop settings.

**Comment by mark-rodgers** [comment]
@jostrander Thank you, for some reason I figured the functionality was added by this project, not a part of Google Music itself. Thanks!


![image](https://user-images.githubusercontent.com/2798202/31155316-0b9868dc-a862-11e7-9a5b-27e1b6d94805.png)
