### ISSUE TITLE
Feature request: add back and forward buttons outside search bar

### ISSUE THREAD

**Issue by ryofurue** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2786]
Hi,

Thank you for the useful application!

I found several past threads about the back button---I understand it's in the search bar. So, my first request is

1) It would be nice if the back button were available without clearing the current search. Currently, the back button isn't available unless you press the "x" symbol to clear the current search.

OR

2) It would be even nicer if the back button were outside the search box. --- This would more convenient because it's always available.

And my second request is

3) A forward button would be nice.

**Comment by kdawg1406** [comment]
Agree this is needed.  For now, you can press the "Backspace" button to go back.

**Comment by xdpirate** [comment]
+1, the back button as it is now is pretty useless.

**Comment by MarshallOfSound** [comment]
If someone can make a PR with decent UX for this I would accept it, but the button in its current state works as expected.
