### ISSUE TITLE
Clock will not work

### ISSUE THREAD

**Issue by applesea2** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2787]
**OS:**
Windows 10
**Issue Descriptions:**
Setting an alarm with any time does not trigger any alarm
**Steps to Reproduce:**
Click on three dots on the upper left corner and then click on alarm. Set any time and it will not work.

**Comment by MarshallOfSound** [comment]
This is due to the time issues currently in `4.4.1`, this issue can not be replicated on master
