### ISSUE TITLE
Feature Request: Register the app to open GPM links

### ISSUE THREAD

**Issue by artursmirnov** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2789]
**OS:** Windows 10

Wondows 10 has an ability to open certain links directly in apps. It would be nice to use this feature to open GPM links (`//play.google.com/music/*`) inside the app. When someone shares a song to me and sends me a link, it opens in browser, whereas I would prefer it to open inside the app.

**Comment by MarshallOfSound** [comment]
This can't be done because it requires you to validate the domain with Windows.  We can't prove we own the GPM domain so it won't open links in our app.  This is for safety reasons on windows

**Comment by artursmirnov** [comment]
Oh, that's sad. Thanks for quick feedback.
