### ISSUE TITLE
Text and images become invisible

### ISSUE THREAD

**Issue by PeterLustig** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2790]
**OS:** macOS 10.13 High Sierra

**Issue Descriptions:** Text and images become invisible after a while when a song changes.
Here's an image of how it looks: https://i.imgur.com/4qJE573.png
Everything else is still working and the settings window is displayed correctly.

**Steps to Reproduce:** Listen to the app for a while and after about the 5th or 6th song you listen to everything becomes invisible.

**Comment by MarshallOfSound** [comment]
@PeterLustig Looks like you got caught on the bad end of a google play music issue, give it a few days and it should right itself 👍 

That content isn't actually controlled by this app rather by google
