### ISSUE TITLE
Feature Request: Notification Widget for Mac

### ISSUE THREAD

**Issue by adarshv90** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2791]

**Comment by MarshallOfSound** [comment]
The issue template was deleted for apparently no reason, "Notification Widget for Mac" is not descriptive enough for us to know what you are asking for.  Please fill in the issue details and this will be re-opened if appropriate

**Comment by adarshv90** [comment]
@MarshallOfSound I've updated the description. I think it is a useful feature. Please re-open the issue if possible

**Comment by adarshv90** [comment]
@@MarshallOfSound please take another look at this feature request
