### ISSUE TITLE
Can't add artists to artists tab

### ISSUE THREAD

**Issue by scarletswalking** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2797]
**OS:** MAC OSX 10.11.6
GPMDP: Version 4.4.1 (4.4.1)

**Issue Descriptions:** 
-There is no way to add an artist to the artist tab under Music Library/Artist. 
-I also can't select an artist to play and see what songs are coming in the main window. 
--I have to click on open queue to see anything, nothing will show in main window. This also goes for playlists I haven't subscribed to, I cannot see any of the music on there unless I subscribe to the playlist. Cannot delete artists.

**Steps to Reproduce:** Find an artist, try and find a way to add to library. Go to My Library, select artist, and try and find a way to delete artist from Library. There are no drop downs, there are no clicks, or selections that will delete anything.

**Comment by MarshallOfSound** [comment]
This kind of thing is entirely controlled by Google not by this application, please raise it on their product support forums.
