### ISSUE TITLE
Application will not launch after playback API is enabled in settings

### ISSUE THREAD

**Issue by JamesAlexJensen** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2798]
OS:

App Details:
Version: 4.4.1
Electron Version: 1.6.1
Development Build: false

Operating System Details:
OS: win32
OS Version: 10.0.15063
OS Arch: ia32
System Memory: 17102647296

Issue Descriptions:

When enabling the playback API and restarting the application, the application will no longer launch. To get it to work I have to uninstall and delete all files associated with program and then reinstall it. Reproduced multiple times.

Steps to Reproduce:
1. Install program
2. Enable playback API
3. Restart program
4. Failure to launch even after system reboot

**Comment by MarshallOfSound** [comment]
@JamesAlexJensen Is this the windows store version?

**Comment by JamesAlexJensen** [comment]
@MarshallOfSound No it isn't, it was downloaded from the official website

**Comment by MarshallOfSound** [comment]
@JamesAlexJensen Is there anything non-standard about your machine?

* Are you connected to a network?
* Are you on an insiders track for Windows?
* Are you on some kind of locked down machine (a work machine for instance)?

**Comment by JamesAlexJensen** [comment]
My machine is completely standard. It is my personal computer, not used for work or anything and I'm using standard windows updates too.

**Comment by carosati3** [comment]
I am having the same issue starting today for some reason.

**Comment by MarshallOfSound** [comment]
I've tried a whole bunch of my VM's and my actual windows machines and can't reproduce this issue.  Considering their appears to be a few people who started experiencing this at the same time (ish) it's either a coincidence or you all got hit with a dodgy driver / windows update.  Perhaps searching through your update history will reveal what changed on your device.
