### ISSUE TITLE
Linux problem with 2-Step Verification

### ISSUE THREAD

**Issue by algerdby** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#280]
After typing password, windows freezes

**Comment by jeefberkey** [comment]
Does an app password work?

**Comment by maedox** [comment]
Same issue here. Haven't tried app password, but I'm pretty sure it won't work as it's basically a browser and they won't allow using an app password for a device that should support 2FA codes.

**Comment by MightyPork** [comment]
Running on Linux and no such issue. However, I didn't use the .deb, but rather run from git clone.

**Comment by ov1d1u** [comment]
Same issue here, using an app password doesn't work as GPMDP explicitly requests the account's password.

**Comment by MarshallOfSound** [comment]
This is the expected behaviour.  Imagine the login process for the player is the same as in any browser (Chrome, Firefox, Etc.)

Google's login process doesn't accept app passwords :)

If you want more security enable 2FA as that is supported during this login flow.

**Comment by ov1d1u** [comment]
The issue is actually that the player freeze after inserting password when 2FA is enabled.

**Comment by MarshallOfSound** [comment]
OK, I misread the issue.  Can you tell me **exactly** when the player freezes?

I.e. First keydown, first keyup, after submitting Etc.

**Comment by ov1d1u** [comment]
Immediately after pressing "Sign in" under the password field in the login screen (in the second stage, the first one is where you enter your email)

**Comment by MarshallOfSound** [comment]
Can you run the development environment and start the app with the flags `--enable-logging` to see what chromium is failing with in the background :+1: 

Also I'm going to close here and ask to move to the `atom/electron` repo when you find out what chromium is crashing at.

**Comment by ov1d1u** [comment]
Couldn't find exactly why Chromium is crashing but running Google Play Music Desktop Player with `--disable-gpu` flag workarounds the issue.
