### ISSUE TITLE
Blank app with no buttons?

### ISSUE THREAD

**Issue by pmuscarello** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2800]
**OS:**
Windows 10
**Issue Descriptions:**
When I open the app, I get a blank window with no buttons. I can change the desktop settings just fine, but the main app is a blank window. See attached picture.

**Steps to Reproduce:**
Just open file in windows 10. I downloaded app from windows store

Thanks!

![image](https://user-images.githubusercontent.com/32488084/31130111-b43f2a60-a813-11e7-8000-94e38c2e5e77.png)

**Comment by radutzp** [comment]
I had the same issue. I solved it by downloading the installer again and run it.

**Comment by pmuscarello** [comment]
I tried uninstalling and reinstalling, same issue :(. thanks for the help!

**Comment by DutchDogg54** [comment]
I can replicate this - it appears to be intermittent, but I see the same exact thing as shown in the screenshot above. I've attached the debug zip - let me know if I can help test in any other way.

I'm running Windows 10 Pro on a 64 bit system, up to date at time of report.

[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/1356197/debug_info.zip)

**Comment by MarshallOfSound** [comment]
This is normally because the renderer process crashed, there isn't much I can do to help with this as it crashes normally for reasons outside of my control.  As @radutzp indicated, this can normally be solved by simply relaunching or reinstalling GPMDP

**Comment by pmuscarello** [comment]
Sam,


Thanks for your help. I have it working on 1 machine and not the other. Thank you for making such a great program!


________________________________
