### ISSUE TITLE
Web App Loading Error on start

### ISSUE THREAD

**Issue by SolarLune** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2802]
**OS:** Solus OS 3 64-bit (Linux), fully updated

**Issue Descriptions:** The application states, "Web App Loading Error" on starting it up. The description to the dialog states, "The web application with id 'google_play_music' has not been found."

**Steps to Reproduce:** Start the application.

I'm using v4.4.0-5 of the desktop player, as well. Great work on the program, otherwise - I've used it before, and it's a really solidly put together program!

**Comment by MarshallOfSound** [comment]
> v4.4.0-5

That version looks suspect, `4.4.0-5` is not a released version.

Also whatever this issue is it would be a google issue, potentially with their infrastructure 👍

**Comment by SolarLune** [comment]
> That version looks suspect, 4.4.0-5 is not a released version.

Looks like that's just how they number it in the package manager - the description says it's the 4.4.0 update. 

> Also whatever this issue is it would be a google issue, potentially with their infrastructure :+1: 

Uninstalling and reinstalling the program fixed it for me (or maybe Google was tripping and they fixed it in the few hours between then and now). Thanks!
