### ISSUE TITLE
(Windows 10) After enabling Playback API, no sound is heard

### ISSUE THREAD

**Issue by professionaljones** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2804]
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/1356974/debug_info.zip)

**OS:**

Windows 10 Version 1709 Build 16291.0 (Currently in the Insider Program, Slow Ring)

**Issue Descriptions:**

GPMDP launches on start, I open it from the start menu and click play on a song. Even though the UI updates and music is presumably playing, there is nothing heard. A warning popped up before playing saying that there was a problem with the Playback API and a false flag with Windows Firewall that I accepted to fix but nothing changed.

**Steps to Reproduce:**

Install on Windows 10
Enable Playback API
Restart App
Play music
No audio is heard

**Comment by MarshallOfSound** [comment]
I would suggest this is something dodgy with your audio driver, never heard of this before.  The only new thing that enabling the playback API does is advertise a bonjour service which should have no affect on the audio output of a progrm.  I'd check your drivers for updates and see if you can find out what's going on 👍
