### ISSUE TITLE
Unable to play any song after a while

### ISSUE THREAD

**Issue by paul-freez** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2806]
**OS:** Windows 10 x64

**Issue Descriptions:**
After playing any ~6-10(or sometimes a bit more) songs (doesn't matter if they're from different/same playlist) player won't play any song at all (if it's in playlist it just go thru all the songs in the list trying and failing to play them immediately). Restarting the application does nothing - unable to play any song (however after reboot or re-installation I still can play few songs before the bug occur). Even after complete re-installation (and heck, even complete clean OS re-install) the bug still occurs. This issue appeared in spring-summer update, so not the last version bug.

**Steps to Reproduce:**
Randomly occurs

**Comment by Deckee** [comment]
I Can confirm this bug Is Occurring On the Windows 10 Client, if you skip 6-7 songs the client will stop working, The Debian client does not suffer from this issue with my uses on two ubuntu machines

**Comment by sammael86** [comment]
Confirm this annoying bug. Windows 10 x64 on different computers.

**Comment by jostrander** [comment]
I think this is an issue lately due to Google adding in gapless playback. They added multiple audio elements/streams to the page and after you skip enough times something breaks on their end. Unfortunately I don't have this issue on either my paid account/free account on windows or linux, which makes it hard to pin point.

**Comment by MarshallOfSound** [comment]
> I think this is an issue lately due to Google adding in gapless playback

I think this is accurate, I've seen quite a few reports of people using the web app experiencing this issue as well 👍
