### ISSUE TITLE
Feature Request: Integrate with MPD

### ISSUE THREAD

**Issue by cwre** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2807]
**OS:** Linux (Arch)

**Issue Descriptions:** I'd like a way to extract music data from GPMDP and display it on my i3status with MPD. I tried finding a way to do it, but could not. Am I missing something? If I'm not, I'd like the feature to be added to a wishlist, if you guys have it.

**Comment by Alipoodle** [comment]
I'm not a Linux wizard at all, so i'm not sure if this will help you, but check out the 2 [**Integrating with GPMDP from External Applications**](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#integrating-with-gpmdp-from-external-applications)

**Comment by MarshallOfSound** [comment]
We currently integrate with mrpis and dbus on linux systems, you should be able to pull information from the interfaces into MPD.
