### ISSUE TITLE
Volume can not be set using Websocket API

### ISSUE THREAD

**Issue by raicabogdan** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2809]
OS: Linux

Issue Descriptions: Setting volume using the websocket API, any volume namespace methos won't work

Steps to Reproduce: 
I'm using this to send to websocket and I can't seem to understand what I'm doing wrong.

`var cmd  = {
	"namespace": "volume",
	"method": "setVolume",
	"arguments": 60
};

WebSocket.send(JSON.stringify(cmd));`

From what I understood from here:
https://github.com/gmusic-utils/gmusic.js/blob/master/src/namespaces/VolumeNamespace.js

`setVolume` just wants a number between 0 and 100. However there's nothing happening.

**Comment by MarshallOfSound** [comment]
@raicabogdan The `arguments` property has to be an array of all the arguments.  So your command would look like this.

```js
var cmd = {
"namespace": "volume",
"method": "setVolume",
"arguments": [60]
};
```
