### ISSUE TITLE
Black window on Linux version.

### ISSUE THREAD

**Issue by GarlandKey** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#281]
OS: Arch Linux x86_64
    Kernel: 4.4.1-2
    DE: KDE Plasma 5
    GPU Driver: nvidia-361.28-2

I installed this using the AUR package listed [here](https://aur.archlinux.org/packages/gpmdp/).

When I run it, I get a black window with no decorations.  I get no errors when running it from cli.

**Comment by kminehart** [comment]
I have a feeling that the AUR package is not made very well.  It does not even list `node.js` or `npm` as dependencies.

**Comment by yochaigal** [comment]
Same Issue. I have nodejs package and npm installed, not sure if I need to do more though (within npm).

Distro: Arch Linux
Kernel: 4.4.3-1-ARCH x86_64 (64 bit gcc: 5.3.0) 
Desktop: Xfce 4.12.3 (Gtk 2.24.28)
Graphics:  Card: NVIDIA GM206 [GeForce GTX 960]

**Comment by kminehart** [comment]
@yochaigal what happens when you run:
`npm install && npm run build && npm start` in the repo directory?  Or is the issue occurring for you when you run the binary built by the aur package?

**Comment by yochaigal** [comment]
The latter, sorry - my issue is only building from AUR. I suppose I could build from source and then see if things work with the AUR package, but I'd love to help it get fixed - I'll assume that this issue is related to the AUR package and message the maintainer there instead!

**Comment by MarshallOfSound** [comment]
I don't know how AUR packages work, someone else set that up.  Your best bet is to find them and figure this out.  Try the gitter room I think they are in there :dart:

**Comment by steelbox** [comment]
This also happens on linux mint 64-bit, after installing `google-play-music-desktop-player_3.0.0_linux_amd64.deb` - here are my system details:
* Kernel: 3.13.0-37-generic x86_64 (64 bit)
* Desktop: Cinnamon 2.4.8  Distro: Linux Mint 17.1 Rebecca

I had gotten the first login correctly (with 2-step auth), though it froze on the 2-step window.

The login page seems to be open, though not visible, my cursor changes from the usual pointer to a "text cursor" (as when pointing an editable text box) - I copied all text `CTRL+A, copy+paste` and the login window text was captured:
```
One account. All of Google.
Sign in to continue to Google Play Music

Enter your email
Next
Need help?
Create account

One Google Account for everything Google

About Google Privacy Terms Help Change language  
```

---
Additional information  - login possible still

At the word `what` from the still-shown page (see @mccore 's screenshot), there is a field that if clicked, can still be filled and when I pressed "Enter", the same step could be taken to enter my password. I received a text with my 2-step password and entered it (both the password field and the text-message code field are selected by default). The code worked as I then closed the app and re-opened to a fully working app. :)

---
Additional information - system 

I had two lingering processes, which I killed, that seemed from the installation - this is after installation from the package installer (successfully) and start+close of application:

```
ps aux | grep music
$user   28136  1.2  0.1 390028 14920 ?        Sl   16:49   0:27 gksu --desktop /usr/share/applications/gdebi.desktop --message <big><b>You need to grant administrative rights to install software</b></big>   It is a possible security risk to install packages files manually. Install software from trustworthy software distributors only.  -- gdebi-gtk --non-interactive /home/$user/Desktop/google-play-music-desktop-player_3.0.0_linux_amd64.deb
root     28708  0.0  0.0  71440  2412 ?        Ss   16:52   0:00 /usr/bin/sudo -H -S -p GNOME_SUDO_PASS -u root -- gdebi-gtk --non-interactive /home/$user/Desktop/google-play-music-desktop-player_3.0.0_linux_amd64.deb
root     28714  0.6  3.2 650440 263712 ?       Sl   16:52   0:11 /usr/bin/python3 /usr/bin/gdebi-gtk --non-interactive /home/$user/Desktop/google-play-music-desktop-player_3.0.0_linux_amd64.deb
$user   32541  0.0  0.0  11764   932 pts/4    S+   17:24   0:00 grep --colour=auto music
```

Here is the output from my terminal showing the running process with its options:
```
/usr/share/google-play-music-desktop-player/Google Play Music Desktop Player --type=renderer --enable-experimental-web-platform-features=1 --enable-overlay-scrollbar=1 --enable-smooth-scrolling=1 --no-sandbox --lang=en-GB --node-integration=true --preload=/usr/share/google-play-music-desktop-player/resources/app/build/inject/generic.js --num-raster-threads=2 --content-image-texture-target=3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553 --video-image-texture-target=3553 --disable-accelerated-video-decode --disable-webrtc-hw-encoding --disable-gpu-compositing --channel=32460.0.1796462644 --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd```

I hope this helps.

**Comment by MarshallOfSound** [comment]
Can you guys try using the `--disable-gpu` flag when running the player.  Other users are reporting it fixes linux issues
