### ISSUE TITLE
Cannot login to last.fm

### ISSUE THREAD

**Issue by rlach** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2810]
**OS:** Ubuntu 16.04

**Issue Descriptions:**
![login](https://user-images.githubusercontent.com/5655000/31333901-29466df0-acec-11e7-9a8c-7a79092d0aee.png)
Pressing "Log in to last.fm" changes `Not Authorized` to `Authorization in progress` for a second and then comes back to `Not Authorized`. There is never any prompt to enter my last.fm credentials.

**Steps to Reproduce:**
1) Fresh install GPMDP
2) Login to google account
3) Enter desktop settings -> Last.FM
4) Press "Log in to Last.FM"

**Comment by proxemics** [comment]
I have the exact same issue.

**Comment by MarshallOfSound** [comment]
@rlach @proxemics Where did you install GPMDP from, if you built it manually or installed it from an unofficial source you will need to provide your own last.fm api keys

**Comment by proxemics** [comment]
I installed it from the official site. though now I'm thinking it might be due to my work vpn/proxy.

**Comment by rlach** [comment]
@MarshallOfSound I installed it trough Ubuntu Software, which seems pretty official. Only apt would be better on Ubuntu.

After you wrote my version might be wrong I downloaded debian 64bit version from the webpage which works, so the Ubuntu Software version is broken. Installing webpage version fixed some other issues I had, for example I couldn't upload images for albums, because the app had no access to my home folder, non of the icons for desktop player showed(I had blank images everywhere).

![ubuntu-software](https://user-images.githubusercontent.com/5655000/31706407-27bdd366-b3e9-11e7-83f2-17f324fb9d9c.png)

**Comment by MarshallOfSound** [comment]
The "Snap" version of the app is not maintained by me rather a third party user

**Comment by renegat59** [comment]
I have the same issue. Installed from official Solus repository. It's a fresh install of system. Any ideas how to fix it? Is there any log file where we could see whats happening?

**Comment by budkin** [comment]
I installed it from git master through AUR on Arch Linux, where do I put my last.fm api credentials?

**Comment by probedb** [comment]
@MarshallOfSound can you please reopen this? I installed from the download link for OS X.

There are no fields to input last.fm credentials yet there is an Authorize button. It just sits and later will revert to login to last.fm

However no ability to enter my credentials.

**Comment by lozanro** [comment]
Same issue on latest version 4.6.1 on Windows. Maybe a proxy/connection issue.
Is it possible to have a workaroung with API keys (as it's done for listenbrainz authentication)?
