### ISSUE TITLE
Tray icon is too sharp on Windows 10

### ISSUE THREAD

**Issue by Cosebdd** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2811]
**OS:**
Windows
**Issue Descriptions:**
![untitled](https://user-images.githubusercontent.com/7452950/31341121-c2c97c26-ad08-11e7-891a-bf8047cf6c13.png)
Icon of app in tray looks kind of sharp and edgy on Windows 10. Screenshot contains telegram icon, that in contrast looks well

**Comment by MarshallOfSound** [comment]
This has come up before, welcome to windows being bad 😆
