### ISSUE TITLE
Websocket event for advertisement

### ISSUE THREAD

**Issue by jptrsn** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2812]
It would be amazing to fire a websocket event when an advertisement plays. Currently, it fires an event for audio advertisements with a static track title and artist, but video advertisements only appear to fire a play state change from playing to paused.

I am using some logic to detect advertisements, and to automatically mute playback until the ad has finished. I'm currently unable to detect video ads, but audio ads are working as expected.

**Comment by MarshallOfSound** [comment]
> I am using some logic to detect advertisements, and to automatically mute playback until the ad has finished. I'm currently unable to detect video ads, but audio ads are working as expected.

We can't even entertain this use case for hopefully obvious reasons
