### ISSUE TITLE
JSON Playback API current time is incorrect

### ISSUE THREAD

**Issue by wwgray** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2814]
In the JSON Playback API the "current" time does not get reset to 0 when the song changes, it shows the total play time for all songs.  For example I am seeing:

        "current": 1164696,
        "total": 253000

Reproducing the issue is very easy in my setup, it always happens until you manually change tracks, then it resets to 0.

There was a similar/same issue to this logged as #2728, however it got closed for some reason even though the issue is still happening, at least for me.

Edit: It also looks like sometimes the current and total values get stuck and quit getting updated, despite the rest of the json file getting updated.  Reproducing this is harder, it's intermittent, but not exactly rare.

GPMDP: v4.4.1
OS: Ubuntu 17.04

**Comment by MarshallOfSound** [comment]
Fixed in master as per other issues regarding this 👍
