### ISSUE TITLE
Use different port than default HTTP port Play Music is using, or offline storage playback

### ISSUE THREAD

**Issue by zephus67** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2815]
There are issues on my network that arise sometimes when switching to the next song, as Google Play Music downloads the next track near the end of the current one.  This can cause network lag on low bandwidth internet.  I suggest that there is a feature that redirects the default port to one the user can define so routers can prioritize appropriately via QoS, or allow offline playback through downloading lists or libraries to a computer.  Thanks.

**Comment by jostrander** [comment]
This is not really possible, and offline playback has been mentioned numerous times in previous issues. It's not something we can fix, nor would fix, unless Google implemented it first in the web player.
