### ISSUE TITLE
Minimize to Tray acts as Close to Tray

### ISSUE THREAD

**Issue by geoffm** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2816]
**OS:**
Windows 10
**Issue Descriptions:**
When activating the Minimize to Tray option, the minimize button keeps sending the window to the taskbar but when we use the Close button then the window is hidden, removed from taskbar but kept in the tray. This is called "Close to Tray".

Both options should be offered, Close to Tray which defines the Close button action, and Minimize to Tray which affects the Minimize button action.
But the best would be to keep the minimize button to minimize and the close button to close the program, but add another button in between which does minimize to tray.
At the very least, rename the actual "Minimize to tray" setting to "Close to tray" which is what it does.

**Steps to Reproduce:**
Activate "Minimize to tray" button. Minimize window.

**Comment by MarshallOfSound** [comment]
>  At the very least, rename the actual "Minimize to tray" setting to "Close to tray" which is what it does.

This is the first time I've heard someone query the distinction between the two, as far as I am aware they are used interchangeably for the same concept.  Our "minimize to tray" does exactly that, you click close and it visually minimizes to the tray.  I don't want to change this behavior now as it would mess with lots of people who understand the existing behavior.

Also adding another button that isn't a standard window control would just confuse the heck out people 😄

**Comment by BrianAllred** [comment]
And to be fair, most of the language regarding this functionality says "minimize to tray on close" or something similar. I think I've only seen one or two applications actually use "close to tray". So really, it's not so much incorrect as it is incomplete, but even then, the wording is probably clear enough.

**Comment by spencermathews** [comment]
After returning to use GPMDP I found myself confused by this setting once again. So I'd like to second the suggestion that the name of this setting be rephrased as per the suggestions by @BrianAllred .
