### ISSUE TITLE
Crackling on Windows 7 with Logitech G430 headset using Logitech Gaming software

### ISSUE THREAD

**Issue by alfonsojon** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2817]
**OS:** Windows 7 Service Pack 1 x64

**Issue Descriptions:**
When listening to music using the Logitech G430 headset, there is very bad crackling. This only affects Google Play Music Desktop Player, and does not affect the web interface. It happens regardless of whether or not the multi-channel audio setting is enabled.

This issue does not happen if I disable the Logitech Gaming software, but that kind of defeats the purpose in a multi-channel head set. I'll upload an audio sample.

**Steps to Reproduce:**
Install Logitech Gaming software on Windows 7 Service Pack 1
Play a song with the software active
Take off headphones as popping is very loud

I've attached a sample MP3 inside of a ZIP to demonstrate the issue.

[Google Play Music Desktop Player Bug Demonstration.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/1377938/Google.Play.Music.Desktop.Player.Bug.Demonstration.zip)

**Comment by MarshallOfSound** [comment]
> This issue does not happen if I disable the Logitech Gaming software

This indicates it's an audio driver specific issue, all audio playing logic is either up to your drivers or deep inside Chromium logic both of which are out of the control of this application.  I'd recommend checking if you updates available for your logitech drivers

**Comment by alfonsojon** [comment]
@MarshallOfSound It turns out the issue persists if I close the software. The issue is happening any time I have it plugged into the USB DAC that my headset uses. My onboard audio works fine.

**Comment by alfonsojon** [comment]
@MarshallOfSound Working fine after a Windows update? Must have been drivers like you said. Thanks!

**Comment by phoenixviolet** [comment]
@MarshallOfSound Updating my drivers doesn't help. Google's web player works fine. I love gpmdp but I love my headphones more. I only have this issue while gpmdp is trying to play music.

**Comment by phoenixviolet** [comment]
I've used google's "desktop player" which requires the tab open with no issue as well. Run on chrome + a chromium browser. Only issue is with gpmdp
