### ISSUE TITLE
Double scrobbling to last.fm

### ISSUE THREAD

**Issue by nikita-nikiforov** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2819]
**OS:** Windows 10

**Issue Descriptions:** Hi! I've noticed a bug with last.fm. Sometimes player scrobbles a track two times or even three. I don't why, but I have been meeting this bug for nearly three weeks.

![screenshot_10](https://user-images.githubusercontent.com/19807104/31567337-afe8ccca-b077-11e7-8a5b-14f26b146fc9.png)

**Comment by MarshallOfSound** [comment]
This will be due to the timing issue currently fixed in master

**Comment by Intruder66** [comment]
For me, this happens again with release 4.5.0 on Win 10:

![image](https://user-images.githubusercontent.com/24815488/37550019-0d0c6442-2987-11e8-8bc3-8c1e4dc51009.png)
