### ISSUE TITLE
Not able to include space in global hotkey on macOS

### ISSUE THREAD

**Issue by linghutiantian** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2820]
**OS: macOS Sierra**

**Issue Descriptions: Not able to include space in global hotkey on macOS**

**Steps to Reproduce:**
I'm not sure this is by design or my own problem.
To reproduce, go to settings->hotkeys, and try to set any hotkey combination including a "space", e.g. "ctrl+alt+space", "ctrl+space" etc. And the new combination doesn't show in the box like I didn't press anything.
I checked very carefully in macOS's System Preference->keyboard->shortcuts, and those combinations are not used.
So, I tried to use "ctrl+alt+space" in another music app, and it works perfectly. So this proves that "ctrl+alt+space" is not blocked by the system.
Just wondering why I couldn't use "ctrl+alt+space" in this app. (If I try to set the hot key as other combinations, e.g. "ctrl+alt+p", it also works perfectly in this app.)
Thanks.

**Comment by MarshallOfSound** [comment]
We currently don't support the space key as an action key:
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/renderer/ui/utils/constants.js#L14

I don't have any strong feelings on it so if you want to add it, it's a super easy PR 😉
