### ISSUE TITLE
Voice command not responding even with a google api key set

### ISSUE THREAD

**Issue by NicusorFlorinBaluta** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2821]
**OS:** Windows 10

**Issue Descriptions:** I added an environmental variable for a google api key i created, but there is still no reaction from the player. I didn't try to run in command line with the key passed as a parameter for i do not know how. Can you help me?

**Comment by MarshallOfSound** [comment]
The API key is baked in at build time, you will have to build Electron yourself to use your custom API key

**Comment by NicusorFlorinBaluta** [comment]
this can be changed, i have seen similar electron apps, that expose a possibility to insert your own API key, at runtime
