### ISSUE TITLE
Pause/Break as Hotkey

### ISSUE THREAD

**Issue by mquevill** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2823]
**OS:** Linux Mint 18.2 (DE: Cinnamon)

**Issue Descriptions:** I have a global keyboard shortcut so that the Pause/Break key works as an audio pause button, which works for other audio applications. However, this does not translate to GPMDP. As a workaround, I tried to set a hotkey involving pause. Upon reading other issues, I also tried to add modifiers, such as Ctrl+Pause or Ctrl+Shift+Pause, but these combinations cannot be set for any hotkey.

**Steps to Reproduce:** Attempt to set any hotkey with Pause/Break key (including modifiers: ctrl+, ctrl+shift+, etc.)

**Comment by jostrander** [comment]
https://electron.atom.io/docs/api/accelerator/

Unfortunately it's not an available accelerator to us in the underlying framework we use.
