### ISSUE TITLE
Feature Request: List views for playlists, stations, artists, albums, and genres

### ISSUE THREAD

**Issue by AlexMStudioLabs** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2824]
Hello! First off I just want to thank you for building an amazing application. I just switched from Spotify and you made the transition much easier. Now here's my feature request:

I'm a power user and have thousands of artists in my collection. The grid view currently available in the above mentioned filters makes it frustrating to scroll through my collection when looking for music. Would it be possible to make it look a like a more traditional artist list instead of a grid? Similarly to how the song filter is laid out? That would be a huge help. Thanks!

**Comment by MarshallOfSound** [comment]
This is the kind of request that you'll have to ask google for on their product forums we don't create or control that UI in any way 👍
