### ISSUE TITLE
"Bug"; icon in menu bar in Mac OSX is much larger than all other menu bar icons and looks weird

### ISSUE THREAD

**Issue by Beebou2** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2826]
OS: Mac OSX High Sierra

Issue Descriptions: Exactly the title, [here's a screenshot](https://i.imgur.com/BZuoFDG.png), shit looks bad

Steps to Reproduce: n/a

**Comment by MarshallOfSound** [comment]
Duplicate #2050
