### ISSUE TITLE
After Editing an Album Info - the page fully reloads

### ISSUE THREAD

**Issue by psmod2** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2829]
Hi,

Whenever I edit an album info, the web view completely reloads. I then have to scroll down to the album again - which is actually quite time consuming since I have many edits to make.

Is there a way around this?

**OS:** Windows 7.

**Issue Descriptions:**

**Steps to Reproduce:**
- Scroll to middle of your album list
- Click Edit Album Info and Save
- The page reloads and jumps to the top.

**Comment by MrAureliusR** [comment]
The same is true with playlists, which makes them entirely useless as editing is a giant pain in the rear. Don't know if this a limitation restricted to GPMDP.

**Comment by jostrander** [comment]
Can you verify this doesn't happen in Chrome, either of you?

**Comment by MarshallOfSound** [comment]
This does occur in Chrome, when editing a playlist order or renaming an album or any other kind of metadata change my entire page reloads.  Closing as it isn't on GPMDP to sort this out 👍
