### ISSUE TITLE
Add an option to disable smooth scrolling

### ISSUE THREAD

**Issue by theFroh** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2830]
**OS:** Windows

**Issue Description:** 
In terms of a feature; unable to disable smooth scrolling. As an alternative, it appears that adding a shortcut with "--disable-smooth-scrolling" doesn't work either, unfortunately!

**Comment by MarshallOfSound** [comment]
> Add an option to disable smooth scrolling

One question, why?  I'm not going to go about adding features to disable other features it just increases code complexity.

**Comment by theFroh** [comment]
It really is just personal preference for me, both in normal desktop operation but doubly so on anything with a high precision trackpad. It tends to just make the interface feel sluggish and less responsive when scrolling around (because technically, that's what is happening).

I'd be fine with working out simply why the usual flag doesn't work; is there some JS scrolljacking going on?

**Comment by theFroh** [comment]
Ah, the Chromium flag is [forcibly appended](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/a8d35020266cd65f4e3c8cdbb62b835394a28d4c/src/main/configureApp.js#L4), I see.

Well, not overriding the behaviour of `--disable-smooth-scrolling` by effectively always specifying `--enable-smooth-scrolling` after should work. That could just be by throwing it into a conditional with `!process.argv.includes('--disable-smooth-scrolling')`, I suppose. Not too sure how involved the desktop settings side of things are, but that'd probably be the "best" way to do it. Might get some time to poke around tomorrow to check.

Anyway, great work with this application mate!
