### ISSUE TITLE
main player graphics shrink

### ISSUE THREAD

**Issue by jamieneefe** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2832]
My player text / graphics are tiny, If I minimize the window, and then maximize, it is full scale.  However, when I click on anything, it goes back to being small.

![gmdp-1](https://user-images.githubusercontent.com/32884043/31727779-75f17d08-b3f8-11e7-8ff1-3c39e44a99fe.png)
![gmdp-2](https://user-images.githubusercontent.com/32884043/31727780-75fd63ca-b3f8-11e7-9f4d-6aca65aaa90e.png)

**Comment by vishwasshrikhande** [comment]
Getting the same issue, but the player gets larger whenever I switch to mini player. Then the app refuses to go back to normal zoom levels, and keeps getting larger

**Comment by escoular** [comment]
This reliably happens to me on linux. Minimize, then maximize, then navigate anywhere and the font size and images scale down.

**Comment by MarshallOfSound** [comment]
Duplicate https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/2269
