### ISSUE TITLE
Playback speed seems a little fast

### ISSUE THREAD

**Issue by datawisecomputing** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2833]
I've only been using this for a week or so, and really like it. Listening to some music that I've played a lot previously and it seems to be playing back a little bit on the fast side - as if someone had turned up the speed. I noticed the pitch was on the high side for the voices. I tried playing back in the browser and noticed a difference.

The music I was playing are files that I've synced to my personal quota on Play Music.

Thanks :)

**Comment by jostrander** [comment]
The player doesn't make any attempt to modify the playback speed different from the browser version. Can you provide concrete evidence?

**Comment by jostrander** [comment]
Closing due to lack of response with evidence. If you can provide evidence that the playback speed is indeed increased we'll look into it., but it should be entirely normal.
