### ISSUE TITLE
Bug: Does not properly refresh ChromeCast devices

### ISSUE THREAD

**Issue by parabola949** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2834]
**OS:**
Windows 10 x64

**Issue Descriptions:**
Chromecast device list does not update properly.

**Steps to Reproduce:**
 - Have TV turned on, Chromecast ready and running, start GPMDP.  Device properly shows up, can cast. Yay!
 - Have TV turned off / Chromecast NOT ready, start GPMDP - device is not listed.  Start TV / Chromecast, then hit the Chromecast button again.... device still does not show up.
 - Have TV turned on, Chromecast ready and running, start GPMDP. Cast to Chromecast with no issue.  Shut down TV, but not GPMDP.  Turn TV back on, again attempt to cast to device, you'll see the original Chromecast name, plus blank slots.  None work.

**Expectation**
Clicking the Cast icon should repopulate / scan for devices, then show.

> I checked the debug zip, absolutely nothing related to this issue showed up :(

**Comment by jostrander** [comment]
Detecting when an mDNS device goes offline takes an extremely long amount of time in the library were using unfortunately. I don't think this is something we can fix, easily. 
On a different note, is there any reason you don't leave the chromecast plugged into constant power? On most TV's that have CEC it will allow the TV to turn on when you start casting.

**Comment by Maxr1998** [comment]
I also have issues with my Chromecast Audio (Google Home Mini, actually) not being found by the application. The Home Mini is running all the time, but GPMDP never sees it. When I open GPM in Chrome, I can cast to the device without issues..

**Comment by MarshallOfSound** [comment]
> Detecting when an mDNS device goes offline takes an extremely long amount of time in the library were using unfortunately. I don't think this is something we can fix, easily.

This is 100% accurate and unfortunately the only stance we can take on this, in my experience, it's pretty good at picking up new devices but this entirely depends on your network and how mdns is feeling on a certain day 😆

> The Home Mini

The Home Mini is a pretty new device and potentially implements a slightly different cast protocol to other devices.

**Comment by Maxr1998** [comment]
@MarshallOfSound awesome, will be looking forward to your reports/fixes :)
