### ISSUE TITLE
Whenever I add a new song to library on mobile app, it won't show up on desktop version

### ISSUE THREAD

**Issue by anthonylozada** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2835]
**OS:** MacOS Sierra 10.12.6 & Google Play Version 4.4.1 (4.4.1)

**Issue Descriptions:** Whenever I add a new song to the library playlist, it only shows up on the mobile version of the google play app, but when I check to see if it was updated and added on the desktop version, it isn't added. Also when I add songs to the library from the desktop version, it doesn't show up on the mobile version

**Steps to Reproduce:** Unsure if it can be reproduced, if so, simply add a song to the library on mobile, and see if it shows up on desktop

**Comment by jostrander** [comment]
This is unrelated to this project, and is something you should bring to Google's attention on their product forums.
