### ISSUE TITLE
Black screen when opening maximized on MacOS

### ISSUE THREAD

**Issue by liamdawson** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2836]
**OS:** MacOS 10.13 (17A405)

**Issue Descriptions:** When opening maximized, screen is black until I swap to mini player and back

**Steps to Reproduce:**

1. Open GPMDP
2. Maximize the app
3. Quit (cmd+q)
4. Open the app again

**Expected Behaviour:**

UI displayed

**Actual Behaviour:**

Screen is black, have to go to mini player mode and back again as the bar with the maximize button is hidden, and the "Toggle Full Screen" option does not work.

**Comment by nezorflame** [comment]
I second this.
10.13 on Pro 2017.

**Comment by liamdawson** [comment]
The problem seems to have gotten slightly worse for me - often I can't even see a black screen, have to cmd+tab to the player, mash the full screen/mini player keyboard shortcuts, and eventually I can get it to appear on the current desktop.

**Comment by jostrander** [comment]
Is this still an issue on the latest release?

**Comment by nezorflame** [comment]
Yep, nothing changed from version to version.
Got even worse - it doesn't get focus on any screen if icon gets pressed, except for home screen.

**Comment by jostrander** [comment]
Do you have system borders enabled or disabled?

**Comment by nezorflame** [comment]
Happened on both.
I'll try to reproduce tomorrow and be more precise.

**Comment by ggrell** [comment]
Just to chime in, I don't see this on a MBP 15" 2017 running 10.12.6, so probably a High Sierra issue.

**Comment by TomasTomasTomas** [comment]
Same here as well, 10.12.5 (16F73), when I play ANY song audio doesn't play then it turns to black.
