### ISSUE TITLE
Feature Request: Searchable Music Library

### ISSUE THREAD

**Issue by BMannell** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2837]
A feature to search for songs, artists or albums on the Songs page of the Music Library. If you use the main search bar to find and play a song it will build the playlist using similar songs instead of creating the playlist from your library.

**Comment by kdawg1406** [comment]
Strong agree this is common feature sorely missed.

Thank you for addressing it!

Best to you,

Karl

**Comment by jostrander** [comment]
This is something Google themselves would have to implement and not something we can change. I'd bring this up on their product forums.

**Comment by BMannell** [comment]
Understood, thanks!
Unfortunately it's a non-issue in the browser since you can simple use the page finder (ctrl-f). I will try the forum though.
