### ISSUE TITLE
Google sees app as separate device

### ISSUE THREAD

**Issue by jscheel** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2838]
I'm guessing that this is a part of how the google sign-in works, but I just noticed that the app is registered as a separate device in my google account. It's been a looooong time since I've messed with anything google sign-in related, so I'm not sure if this is expected behavior or not. I verified that the second device is the app by hard refreshing in the app, which caused the "last seen" field to update in google's recent devices list.

This isn't a major issue, but I do know that it can cause errors saying that playback on two or more devices is not allowed. This happens intermittently when I am listening to music and open youtube at the same time (paid google music + youtube red accounts).

![screen shot 2017-10-23 at 12 12 38 pm](https://user-images.githubusercontent.com/211478/31902870-f3dbb7be-b7eb-11e7-8e16-7c41e4e39c1c.jpg)

**Comment by jostrander** [comment]
That is standard behavior, and unfortunately there's really nothing we could do to fix this in a user friendly way.
