### ISSUE TITLE
Youtube video of song plays in background

### ISSUE THREAD

**Issue by theol0403** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2839]
**OS:** Windows

**Issue Descriptions:** Youtube Video does not stop

**Steps to Reproduce:**
I play a song. It buffers. I click play video. It opens the youtube video. I play it, while it is loading the song in the background finishes loading. The song starts playing. The video finishes loading and starts playing and now I hear the same song being played twice. I close the video window and pause the song. The sound from the video is still played in the background. I have to restart the software to stop it.

**Comment by jostrander** [comment]
This is more than likely a bug in the web app itself. You can verify by reproducing the same effect in Chrome or another browser. Nothing we can do to fix this as far as I'm aware.
