### ISSUE TITLE
Scrobbling does not work while casting to a Chromecast.

### ISSUE THREAD

**Issue by jaccarmac** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2840]
**OS:**

Linux (Gentoo)

**Issue Descriptions:**

Scrobbling does not work while casting. The playing track shows up as currently playing on Last.fm but never actually scrobbles.

Scrobbling works while casting from from the web version of GPM with a scrobbling extension in Chrome.

**Steps to Reproduce:**

1. Enable Last.fm scrobbling and verify that it works properly through the app.
2. Start casting to a device and verify that the app can control the device audio.
3. Scrobbling does not work while casting even though scrobbling and casting work independently.

**Comment by MarshallOfSound** [comment]
Scribbling issues are due to timing issues that have been fixed in master
