### ISSUE TITLE
WebCam being accessed in MacOS

### ISSUE THREAD

**Issue by hashken** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2841]
**OS:**
MacOS Sierra

**Issue Descriptions:**
The App seems to be accessing the WebCam

**Steps to Reproduce:**
When the app is open, run the following command in the Terminal

    sudo lsof -Fc +D /L*/Cor*/*/*/*Camera.plugin | sed -n '/^c/s/.//p'

This will list all the programs using the Web Cam. The output list will contain "Google Play Music Desktop Player".

Can you please confirm why the Music Player App is using the camera?

**Comment by jostrander** [comment]
I believe the webcam and microphone API's are one in the same, and the app utilizes the microphone for voice controls if that's enabled. @MarshallOfSound would have to confirm.

**Comment by MarshallOfSound** [comment]
@jostrander Would be correct, if you turn off voice controls it should stop using the camera/microphone

**Comment by hashken** [comment]
In my case, the "Voice Controls" are turned off, but still webcam seems to be accessed. Could it be some other issue?
