### ISSUE TITLE
Web Socket API sending incorrect "current" time

### ISSUE THREAD

**Issue by jhayden4** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2842]
**OS**: Windows 10

**Issue Descriptions:** When receiving "time" channel messages through the Web Socket API the "current" time does not reset when the song changes.  The "current" time will continue to increase while the "total" time changes to the correct value for the new song.

**Steps to Reproduce:** Look at the "time" channel Web Socket API message after a song change and you will see the "current" time is greater than the "total" time.

**Comment by jostrander** [comment]
Known issue which is fixed in master and will be published in the next release, please check closed issues.
