### ISSUE TITLE
Dragging mini-player causes it to grow slightly

### ISSUE THREAD

**Issue by chafla** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2843]
**OS:** 
Windows 8.1 x64

**Issue Descriptions:**

https://i.imgur.com/OeDhM7i.gif

Dragging the mini-player causes it to slightly grow. This happens each and every time I do so, and so the window slowly creeps larger and larger with each individual resize. [It looks like the option bar doesn't fit fully within, either,](https://imgur.com/AbksK9z) maybe hinting at what's wrong.

**Steps to Reproduce:**

- Open mini player
- Drag and release
- Window grows

**Comment by jpanged** [comment]
+1

**Comment by MarshallOfSound** [comment]
Weird mini player sizing issues go to --> https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/2269 😄 When I get a chance one day I'll just rewrite the mini player logic
