### ISSUE TITLE
Un-pausing music is incredibly loud

### ISSUE THREAD

**Issue by Yurlungur** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2845]
**OS:** 

Debian Testing (Linux, amd64)

**Issue Descriptions:**

If I pause playback and leave for a while, when I restart, the volume is incredibly loud and maxed out. This only happens with this application---If i use another music app or if I use the web browser, no problem.

**Steps to Reproduce:**

Simply pause the song and wait an hour or so.

**Comment by jostrander** [comment]
I've never had this issue, however I don't use Debian. Can you pin point what audio is creeping up in volume? Is it at the mixer level or inside the application on the UI?

**Comment by MarshallOfSound** [comment]
As the reporter has not responded to the request for additional information this issue will be closed.  If further information can be provided at some point in the future, comment on this issue with the requested information and if appropriate the issue will be reopened.
