### ISSUE TITLE
Pulling Old Thumbnails when starting with last opened page

### ISSUE THREAD

**Issue by cre841self** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2850]
**OS:** Sierra 10.12.6

**Issue Descriptions:** After starting the app with the last opened page, it pulls old thumbnails for the playlist under "Recent Playlists".

**Steps to Reproduce:** Start with last opened page (being: "Music library/Playlist tab"). The images in the last playlist I played will be the same old ones until I open it.

**Comment by jostrander** [comment]
This is likely just a caching issue, and may not even be on our end. There's not much we can do here as far as I'm aware.

**Comment by cre841self** [comment]
Ok. Makes sense. How can I clear the cache?

**Comment by MarshallOfSound** [comment]
@cre841self This will also log you out, but deleting the `~/Library/Application Support/Google Play Music Desktop Player` directory will reset all cache and such 👍

**Comment by cre841self** [comment]
I don't see the folder. Could there be another location for the cache?
