### ISSUE TITLE
Scrobbles are not being sent (only now playing)

### ISSUE THREAD

**Issue by Kxze** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2851]
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/1428937/debug_info.zip)

**OS:** Windows 10 (latest)

**Issue Descriptions:** Tracks are not scrobbled after they're finished. Only Now Playing notifications are sent to Last.FM.

**Steps to Reproduce:** Play any track.

**Comment by jostrander** [comment]
Duplicate. Fixed in master.

**Comment by Kxze** [comment]
Not sure if this is fixed, I'm on the latest build and it's still happening.

**Comment by ajyates** [comment]
It's been fixed but nothing has been released yet.
