### ISSUE TITLE
How hard would making a UWP version be?

### ISSUE THREAD

**Issue by areyouokani** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2854]
I understand the appeal of Electron, but it is an absolute murder on touch devices and laptops. The interface lags (like horribly lags, we are talking a couple frames per second here) on an i3 Surface Pro 3 with 4 GB RAM - which, admittedly, is not the newest device, but can handle much more resource intensive tasks than playing some music! And UWP apps are butter smooth even when handling much more resource intensive tasks - like watching a 1080p/60fps video.

How hard would developing a UWP version be? Or should I just stick with Tidal, since there already is an unofficial client for it on the MS Store?

**Comment by MarshallOfSound** [comment]
We have a UWP release through Project Centennial on the Windows Store.  In terms of writing from scratch a purely UWP app, that's not going to happen.

And for the record, Tidal is Electron 😉 

https://github.com/electron/electron-apps/blob/master/apps/tidal/tidal.yml
