### ISSUE TITLE
I'm Feeling Lucky

### ISSUE THREAD

**Issue by Ckrunch** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2855]
**OS:** Windows 10

**Issue Descriptions:**
I'm Feeling Lucky button on the home page goes to the same station, even if you select a new different station (example the home page recommended stations). I've attempted to clear my music history for the past few months and it still has the same problem
Note: The Google Play Music Android app has recently in the past few months changed the way the I'm feeling lucky works as well. You must wait a period of time before starting the I'm Feeling Lucky button to get a new station, or play another station then switch back (It's really annoying), so I'm not sure if that has anything to do with this issue or not. The desktop player has been working fine for a while even after the android app change.

**Steps to Reproduce:**
Click I'm feeling lucky dice button on home page. (Note the first few songs in the list)
Play another station
Click I'm feeling lucky dice button on home page, same station starts with the same playlist.
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/1435328/debug_info.zip)

**Comment by jostrander** [comment]
This is all logic handled on Google's end and there's nothing we control or change with this. Please raise this issue with Google on their product forums.
