### ISSUE TITLE
[Feature] Like-Dislike (scriptable?), does it exist, if not, can I bribe you with kitten pics?

### ISSUE THREAD

**Issue by manavortex** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2856]
Hey there, 
first of all, beautiful piece of software that you created there. It works very well on both Mac El Capitan and Windows 10, that's not an easy thing to achieve. Keep up the good work.

However, since I'm a perfectionist, I have an overly specific requirement that I hope you can help me with. I'd like to be able to like/dislike songs per key bind, optimally globally.
Could you perhaps add menu commands "Like current song" and "dislike current song"? That way, I could write myself an apple script that I could toggle via Keyboard Maestro from everywhere. 

If the feature already exists, feel free to pour ash on my head.

**Comment by MarshallOfSound** [comment]
![image](https://user-images.githubusercontent.com/6634592/32324700-60a76924-c020-11e7-9852-e04f8863c38f.png)

_Insert ash pouring here_

**Comment by manavortex** [comment]
*brushes off ash, coughs*
Are the hotkeys global? Otherwise I suppose I would have to write an AppleScript that sends key presses to the music player

**Comment by MarshallOfSound** [comment]
They are indeed global 🎉

**Comment by manavortex** [comment]
Oh! Awesome! 
The page doesn't say clearly. Thank you very much.

**Comment by manavortex** [comment]
Uh - it doesn't let me set any hotkeys. I can click into the field, and it says "Not set", and that's it. What am I doing wrong?

**Comment by MarshallOfSound** [comment]
Click in the field and perform the hotkey, their is a limitation at the moment that the hotkey has to use Control (not Command on a mac), sorry 'bout that but haven't found a workaround yet

**Comment by manavortex** [comment]
Oh - all right. You might want to add a descriptor to the key bind for the mac version?
Is there something I can do to help you come up with a workaround? Key codes? Anything?
