### ISSUE TITLE
When picking a song, it takes A LONG time for it to load. Between 4 to 6 seconds.

### ISSUE THREAD

**Issue by Iceprincess92** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2858]
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/1448714/debug_info.zip)

**OS:** Windows 10 Pro x64

**Issue Descriptions:** I pick a song, any song, and it takes between 4 to 6 seconds to load.

**Steps to Reproduce:** Click any song I wanna play, wait for it to buffer. Shouldn't it be instant?

**Comment by MarshallOfSound** [comment]
Not sure what you want us to do about this, the time it takes for a song to start playing is 100% dependent on your internet speed.  If it takes your network 4-6 seconds to buffer the song that you want to play that's how long you'll have to wait.
