### ISSUE TITLE
Add setting to choose display language

### ISSUE THREAD

**Issue by MCManuelLP** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#286]
In theory it should be quite easy, just append the php variable `hl=<language code>` to the url and reload...
The language code syntax is: 
`<lang_code>[_<country_code>]`
where `lang_code` can be one of these: http://www.w3schools.com/tags/ref_language_codes.asp
and the optional `country_code` one of these: http://www.w3schools.com/tags/ref_country_codes.asp
I'm really bad at ui stuff and don't feel like digging into the code right now so this is no pull request, sorry :/

**Comment by MightyPork** [comment]
Also don't forget about the hard-coded strings in the settings page, taskbar menu etc...

**Comment by MarshallOfSound** [comment]
In a perfect world the app would have translations but it doesn't...

At some point I might implement some form of locale/translations but as @MightyPork that would involve replacing a lot of hard coded strings.

If you want to change the country/language of GPM it by default takes your google accounts language so you can change it there?

**Comment by vladgolubev** [comment]
@MarshallOfSound personally I crave changing language as my default is Ukrainian so Google translates some artists names and it's is scrobbled to my last.fm

I can live with it, just informing there is such scenario.

**Comment by MarshallOfSound** [comment]
@vladgolubev This has since been implemented.

#1414

I don't believe we have Ukrainian translations yet though

**Comment by Landen13** [comment]
I have set my account main language to English. I've also set to English player itself. But anyway, some parts are in old language yet (Russian). What can i do to fix this? It's really bad, because scrobbling bands in russian translation is not good for last.fm statistic.

**Comment by MarshallOfSound** [comment]
@Landen13 GPM will always display in your google accounts language, unfortunately nothing I can do about that.  You can change your account language in your settings somewhere though I believe.

**Comment by vladgolubev** [comment]
@MarshallOfSound I use `?hl=en` query string in my browser to override language. Is it possible in Electron?

**Comment by MarshallOfSound** [comment]
@vladgolubev Copy the URL you use in your browser to get the english version into the "GoTo" dialog in GPMDP and see if it works 😄

**Comment by vladgolubev** [comment]
@MarshallOfSound works like a charm!! Thanks! 💯
