### ISSUE TITLE
Can't bind numpad keys as hotkeys

### ISSUE THREAD

**Issue by JPLeBreton** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2863]
**OS:** Windows 10

**Issue Descriptions:** Can't bind any numpad keys (numeric or operators) to play control in the Hotkeys section of Settings.

**Steps to Reproduce:**
1. open Desktop Settings
2. select the Hotkeys tab
3. click in one of the command fields
4. press any numpad key, with or without mod keys and with or without numlock on eg ctrl-*, shift-enter

result: key doesn't seem to be recognized.

**Comment by MarshallOfSound** [comment]
@JPLeBreton This is a limitation of the Electron `globalShortcut` API.  Basically if the accelerator is `Control+1` how do we know which "1" you mean (numpad or number row) 😄 On some platforms they are mirrored so if you set a shortcut to be Control+1 and use the numpad 1 it will work
