### ISSUE TITLE
Add a clear, obvious way to remove hotkeys to improve UX

### ISSUE THREAD

**Issue by Hermanio** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2867]
I find that there should be some obvious way to remove a hotkey, like a red cross next to the set hotkey to remove it. Pressing escape in a situation where backspace or delete does not remove the hotkey is not intuitive at all, especially to a new user. 

What I ended up doing (but not something that a normal user would do) was going to the configuration folder of this program and finding the json file containing the hotkey bindings, where I could finally set it to null again. 

Take for example GNOME 3 settings. 
![image](https://user-images.githubusercontent.com/8943361/32811817-59f5bb1a-c9aa-11e7-86f2-8f0b9777695c.png)
The red cross near the set hotkey is a clear indication that you can remove the hotkey by clicking on the cross.

Here is an example of what it should look like (example taken from Polymer paper-input element demo):
![image](https://user-images.githubusercontent.com/8943361/32811878-bf22b31c-c9aa-11e7-8a1b-6f1d0196ebf6.png)

What this view currently looks like to me:
![image](https://user-images.githubusercontent.com/8943361/32816225-4c1bc122-c9c0-11e7-8d94-f55b19afa846.png)

What it could look like (but prettier):
![image](https://user-images.githubusercontent.com/8943361/32816350-db64e822-c9c0-11e7-8242-3003362b0c04.png)

**Comment by jostrander** [comment]
Makes sense. There is nothing denoting escape as the way to unset a hotkey, so having that and/or the X (albeit maybe not red). PR's welcome.

**Comment by MarshallOfSound** [comment]
Fixed in master
