### ISSUE TITLE
Lyrics no longer scroll

### ISSUE THREAD

**Issue by JustinBivens** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2869]
Lyrics dont scroll on Mac player like they used to although they never scrolled correctly anyway. 
Just make it where I can scroll my own lyrics at a rate I want to

-->

**Mac 10.12.6**

**Issue Descriptions:**

**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment]
You can turn off automatic scrolling in your desktop settings
