### ISSUE TITLE
GPMDP changes both virtual desktops on dual monitor macOS

### ISSUE THREAD

**Issue by zacharyrs** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2871]
**OS**
macOS 10.13.1
GPMDP 4.4.1

**Issue Description**
Opening fullscreen on a dual monitor setup moves both desktops back to a blank virtual desktop.

**Steps to Reproduce**
1. Open GPMDP and fullscreen it.
2. Quit.
3. Relaunch.

**Comment by MarshallOfSound** [comment]
This is how macOS restore state works, entering fullscreen vs resuming fullscreen changed behavior in high sierra.

**Comment by zacharyrs** [comment]
How do other applications (e.g. Atom, Hyper, Firefox, etc) not suffer from this?

To clarify my issue, say I have my first monitor on a blank desktop, and the second on fullscreen Firefox, opening GPMDP on monitor one opens full screen as expected, but monitor two swaps over to a blank desktop.

In contrast, take the above example, but with Atom instead of GPMDP, monitor two doesn't change at all.

**Comment by zacharyrs** [comment]
@MarshallOfSound Not sure if you got a notification as the issue was closed, but I feel can be improved.
