### ISSUE TITLE
Feature request: Add multiple albums to library at once

### ISSUE THREAD

**Issue by sgabler** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2875]
First post here, so let me show my appreciation for this amazing piece of open source in emojis: 💯 🌹 👍 😸 🍾 

I often find myself adding all albums of an artist to my library by right-clicking on each of them and then selecting "Add album to library". Is there any way this could be done in bulk, e.g. for all albums of an artist or by selecting a few of them and then adding them. The latter option would probably be harder, as I don't see a way to select multiple items in the album view currently.

Google probably doesn't offer this functionality right now, but I wonder if there could be some sort of workaround. I would be happy to try implementing this myself, but would first want to check with you if you think it's doable or not.

**Comment by MarshallOfSound** [comment]
This kind of thing can probably only be implemented on googles side of things, we can do small UI tweaks and interaction changes.  But anything that involves the custom right click context menus or emulating actions on those menus is out of our reach
