### ISSUE TITLE
unable to remap hotkeys on OSX and unable to use command + Key

### ISSUE THREAD

**Issue by jon-zimperium** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2876]
after setting a hotkey on OSX player (4.4.1) I cannot remap or clear.  Attempting to change the key displays an addition to the hotkey - example:

thumbs up hotkey is ctrl+G  attempt to change to ctrl+T - UI shows ctrl+g+t

additionally, command key mapping on OSX does not seem to work at all.

**Comment by MarshallOfSound** [comment]
@jon-zimperium You need to hit "Escape" to reset the key 👍

**Comment by jon-zimperium** [comment]
thanks Samuel!  I still cannot use the command key on the mac - is this a
known issue?

**Comment by MarshallOfSound** [comment]
@jon-zimperium Yep, there are some other issues on here about it.  It's basically a limitation of how we receive key events in the shortcut settings panel.  You can manually set accelerators using the Command key by editing the settings file yourself if you want.

**Comment by jon-zimperium** [comment]
could you point me to the instructions for the file change?
