### ISSUE TITLE
Missing Equalizer?

### ISSUE THREAD

**Issue by deinlandel** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2878]
**OS:**
Win 7
**Issue Descriptions:**
App's site mentions built-in equalizer, but it's nowhere to be found in the app itself.
**Steps to Reproduce:**
1. Open app
2. Play some music
3. Panic because EQ isn't in app.

**Comment by snhardin** [comment]
This is the first thing covered in the [FAQ](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ). 😛

**Comment by SolarLiner** [comment]
Actually I'd say it'd be better to remove the feature on the website, as it is effectively false advertisement. Also, since there are no visualizers anymore, maybe we could try experimenting again?

**Comment by jostrander** [comment]
It's actually the device chooser that's still in conflict with the EQ not the visualizer. There can only be one AudioContext attached to an audio element at a time.l from what I understand.

**Comment by deinlandel** [comment]
Is there any statistics about which feature (outpus select or equalizer) is more useful/requested?

In fact, EQ was the only reason I decided to try standalone player, because inside Chrome equalizer addons sometimes glitch out and cause stuttering.

**Comment by MarshallOfSound** [comment]
> There can only be one AudioContext attached to an audio element at a time.l from what I understand.

This is still the case, `setSinkId` and attaching an `AudioContext` does not work as expected

**Comment by Seetth** [comment]
Same as deinlandel I just downloaded this cause the web says it have an EQ... At least edit that info from the web if EQ wont be supported anymore...

**Comment by Kukunin** [comment]
Same as other guys, I just downloaded this cause the web says it have an EQ...

**Comment by JasonBunting** [comment]
Very odd to continue advertising that this "feature" exists, then put in the FAQ that it doesn't really exist. Why not simply remove the claim of the feature's existence until such a time that it truly does? Why confuse people? It's like dating someone who's all "oh, yeah - I love hiking!" and then, when you finally start dating them seriously, you find they never like going, but now you're into this relationship without the features you want, and you feel trapped. At least with an audio player, I can very easily quit using it without hurting anyone.
