### ISSUE TITLE
Feature request: Android's Adaptive Icon.

### ISSUE THREAD

**Issue by RacingJayson** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2879]
Please consider adding the new Android Adaptive Icon support for Android 8.0+
[Image](https://i.imgur.com/njdnU7U.png) It stick out pretty bad compared to my other apps.

https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html

**Comment by WillPresley** [comment]
This is the UNOFFICIAL (see repo title) _Desktop Player for_ GPM, not the official Android app.

**Comment by MarshallOfSound** [comment]
This issue should be (and has been) raised on the android app repo
