### ISSUE TITLE
Building RPM packages fails

### ISSUE THREAD

**Issue by Wintervenom** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#288]
Hello,

I am attempting to use ``npm run make:rpm`` to build RPMs for Fedora 23.
``gulp make:rpm`` fails during the packaging process.
I have the ``rpm`` Node.js package as well as the RPM Development Tools ``dnf`` group installed.

---

**Attachments:**
- [``npm run make:rpm`` output](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/160615/npm-run-build-make_rpm.log.txt)
- [``npm-debug.log``](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/160614/npm-debug.log.txt)

**Comment by MarshallOfSound** [comment]
Have you run `npm install` recently?
You can also try running `npm prune && npm i && npm upgrade` to fix dependencies.

As a last resort you can delete your `node_modules` folder and try `npm install` again.  Sometimes it just breaks randomly (node.js that is) :+1:

**Comment by Wintervenom** [comment]
I ended up having to reinstall the ``node_modules``.  This solved the issue.
Thank you!

**Comment by esbennn** [comment]
@Wintervenom did you manage to create an rpm? If so, could you share it?

**Comment by MarshallOfSound** [comment]
rpm files are availible directly from Circle CI

https://circle-artifacts.com/gh/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/110/artifacts/0/home/ubuntu/Google-Play-Music-Desktop-Player-UNOFFICIAL-/dist/installers/fedora/google-play-music-desktop-player-3.0.0.amd64.rpm

https://circleci.com/gh/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/110#artifacts

**Comment by esbennn** [comment]
Fantastic - thanks!
