### ISSUE TITLE
Feature request: Option to display Artist/Track title directly in the tray next to the icon

### ISSUE THREAD

**Issue by cazssiew** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2880]
**OS:** macOS

**Issue Descriptions:** I would love to be able to see what track is playing at a glance directly in the menu bar/system tray, next to the icon. Is this possible? 

Thanks for the awesome app!

**Comment by MarshallOfSound** [comment]
> Is this possible?

No, we can only put icons in most system trays, the artist / track is visible when you right click / click on the tray icon however 👍
