### ISSUE TITLE
Feature Request: Batch Edit in playlist.

### ISSUE THREAD

**Issue by vyablonskyy** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2881]
Would be good to have some sort of selection checkboxes near tracks in playlist, so user can select multiple tracks and for example Remove selected tracks from Playlist at once. For now user have to remove every track one by one and after every remove Playlist is refreshed.

Thanks.

**Comment by xdpirate** [comment]
This functionality is already present. You can select multiple tracks by holding down Ctrl as you click, and Shift to select a range of tracks.

**Comment by vyablonskyy** [comment]
@xdpirate thank you.
