### ISSUE TITLE
Dark Side Of The Moon album's page doesn't show

### ISSUE THREAD

**Issue by MrJECL** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2884]
Hey, I was playing some good rock to relax and suddenly  I felt like hearing Pink Floyd's Dark Side Of The Moon, but when I wanted to get to the album, it said that an error occurred and that the album couldn't get opened up. Then, it threw me back to the main page. 
I really want this issue to be fixed as soon as possible. 
Anyways, the app works great. 
To make this clear, I can play the separated songs, but I can't get to the album's page. 
Thank you.
 Mac OS Sierra 10.12.6

**Comment by MarshallOfSound** [comment]
This will be an issue on googles end, you should reach out to the product support forums 👍
