### ISSUE TITLE
Bug Report: Last.fm scrobbling not working

### ISSUE THREAD

**Issue by mcmatthew** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2885]
**OS:**
Reproduced on OS X 10.12.6 and 10.13.1

**App Version:**
Fresh install of 4.4.1

**Issue Descriptions:**
Last.fm scrobbling not working consistently.

**Steps to Reproduce:**
1) Log into Last.fm -> View Profile -> Overview / Recent Tracks
2) Open up Google Play Music Desktop Player and play a song.
3) See the song appear in the 'Recent Tracks' with a status of 'Scrobbling now'
4) Let the song play in entirety and move to the next track.
5) Refresh the Profile Overview / Recent tracks page and see the next track as 'Scrobbling now' but the first track is *not* in the list anymore.  It is missing in the history.

Please let me know if I can provide any more information.

Thanks

**Visuals:**

- I opened the GPDP and played Pearl Jam's Grievance.  It appeared in 'Recent Tracks' while playing.

<img width="817" alt="screen shot 2017-11-29 at 4 13 46 pm" src="https://user-images.githubusercontent.com/2907989/33409026-f85093b2-d53e-11e7-9d23-69da04030806.png">

- It finished playing and the next song up started, Pearl Jam's Leaving Here.  You can see it appears in the list as 'Scrobbling now' but the previous track is no longer listed and the song count hasn't changed:

<img width="792" alt="screen shot 2017-11-29 at 4 14 24 pm" src="https://user-images.githubusercontent.com/2907989/33409091-3bd5cce2-d53f-11e7-836a-0684b1a4efd8.png">

- The next several songs in order, all played through completion and none stick around in the recent tracks:

<img width="797" alt="screen shot 2017-11-29 at 4 17 02 pm" src="https://user-images.githubusercontent.com/2907989/33409114-608e3c7c-d53f-11e7-8a21-fdd85e41f541.png">

<img width="785" alt="screen shot 2017-11-29 at 4 19 07 pm" src="https://user-images.githubusercontent.com/2907989/33409136-6d79ed82-d53f-11e7-880b-15c3994ab36a.png">

<img width="785" alt="screen shot 2017-11-29 at 4 23 11 pm" src="https://user-images.githubusercontent.com/2907989/33409153-7d53287c-d53f-11e7-87a5-8444cf8e4b5e.png">

**What do I expect?**
The same behavior as when I play songs in iTunes and use the Last.fm scrobbler.

- 3 songs played in a row in iTunes:

<img width="565" alt="screen shot 2017-11-29 at 4 57 33 pm" src="https://user-images.githubusercontent.com/2907989/33409190-aedac788-d53f-11e7-9415-7df2d397eac3.png">

- All are in the recent tracks after playing:

<img width="823" alt="screen shot 2017-11-29 at 4 57 42 pm" src="https://user-images.githubusercontent.com/2907989/33409193-b4be3f68-d53f-11e7-9d12-b2f4bafe0388.png">

**Comment by jostrander** [comment]
Duplicate #2740
