### ISSUE TITLE
Hide some buttons in the UI

### ISSUE THREAD

**Issue by seiyria** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2888]
Not a bug.

In google play music web, I created a web script to hide "start radio" and "start instant mix" because I can't think of something more annoying than a misclick that wrecks my current playlist. The script is something like this:

```
(function() {
    'use strict';

    // Your code here...
    
    window.removeBadFeatures = function() {
        console.log('init removeBadFeatures InstantMix and Whatever');
        
        var startRadio = document.getElementById(':3');
        var shuffle = document.getElementById(':4');
        startRadio.remove();
        shuffle.remove();
    };
    
    setTimeout(window.removeBadFeatures, 5000);
})();
```

Now, I notice you have a way to inject custom CSS, but I'm not at all sure how to get a hold of what elements these are in the app. Can you tell me what the selectors are so I can make some CSS for this? I tried:

```
#:3, #:4 {
    display: none;
}
```

but that does not seem to do anything.

Thanks in advance, and I love the app so far!

**Comment by MarshallOfSound** [comment]
@seiyria If your ID's are current that CSS should work, are you sure you injected it into the Google Play Music stylesheet and not the "Main App" stylesheet?

**Comment by seiyria** [comment]
Yeah, I tried this: https://i.imgur.com/JtmYSk4.png

Where the CSS was as above. That script works for the current version of google music, but trying to do it in CSS via the app does not seem to work correctly.

**Comment by MarshallOfSound** [comment]
> document.getElementById(':3')

This code returns `null` for me indicating no such element exists, can you send a screenshot of the elements you are trying to remove.

Going to close this but will continue trying to help out 👍

**Comment by seiyria** [comment]
Trying to remove start radio and start instant mix: https://i.imgur.com/JHToddn.png

I accidentally click them all the time so I prefer to just not have them there, since I never use them.

**Comment by MarshallOfSound** [comment]
@seiyria I think your issue here is `#:3` isn't a valid CSS selector, `:3` is a valid DOM element ID but using `#` the CSS selector is invalid because of the special meaning of `:` in CSS land.

You're best bet is trying to find another way to select those elements 👍
