### ISSUE TITLE
[Tip] [Linux] The the app icon themed

### ISSUE THREAD

**Issue by SolarLiner** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2889]
**OS:** Manjaro Linux / Ubuntu 17.10

**Issue Description:** In order to get the icon themed, we can fool the icon theme into thinking the app is actually the Google Play Music Chrome extension, which is themed by several icon themes (Arc-Maia on Manjaro, Papirus too).

**Steps to Reproduce:** On an editor with root privileges:
* Edit `/usr/share/applications/gpmdp.desktop`
* Replace the value of the 'Icon' key with `chrome-fahmaaghhglfmonjliepjlchgpgfmobi-Default` (the chrome extension icon 'name')

Example edited `.desktop` file:
```
[Desktop Entry]
Name=Google Play Music Desktop Player
Comment=An electron wrapper for Google Play Music
GenericName=Google Play Music Desktop Player
Exec=gpmdp %U
Icon=chrome-fahmaaghhglfmonjliepjlchgpgfmobi-Default
Type=Application
StartupNotify=true
Categories=AudioVideo;Player;Audio;
StartupWMClass=Google Play Music Desktop Player
```

Sorry if this doesn't belong here, but I thought some might appreciate this little tip on getting the GPM icon to fit in with their theme.

**Comment by MarshallOfSound** [comment]
See #2890
