### ISSUE TITLE
Windows 10 Taskbar icon not scalable

### ISSUE THREAD

**Issue by icurate** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2891]
**OS:** Windows 10

**Issue Descriptions:** On a 4K monitor, the GPMDP icon in the taskbar does not scale above 125%. I have my system scaling set to 150% which causes the GPMDP icon to appear much smaller than the others in my taskbar. Screenshot attached

**Steps to Reproduce:** Go to 'Settings' > 'Display' and set the size to 150%. All icons change size except for GPMDP.
![gpmdp-4kicon](https://user-images.githubusercontent.com/34200757/33521673-91fd3448-d78d-11e7-862a-4ce550c5c153.jpg)

**Comment by jostrander** [comment]
Did you install out of the windows store?

**Comment by icurate** [comment]
No, I downloaded it from your website.

**Comment by MarshallOfSound** [comment]
@icurate That icon is the one from the windows store, please uninstall all instances of GPMDP from your computer and install the `.exe` file you can download from our website 👍
