### ISSUE TITLE
Music loops when I am doing other tasks

### ISSUE THREAD

**Issue by Stretchman** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2895]
**OS:**
Linux Mint 18.2

**Issue Descriptions:**
Music will loop when I open other apps, and seems to get stuck until the OS settles. 

**Steps to Reproduce:**
Clicking on anything that needs to open from the taskbar, or opening up something from the launch menu will reproduce it. 

There is another issue which causes the wrong album cover to be displayed when hovering over the volume button on the taskbar. IDK if the 2 are related.

**Comment by jostrander** [comment]
This may be just a memory issue. Computer specs?

**Comment by MarshallOfSound** [comment]
As the reporter has not responded to the request for additional information this issue will be closed.  If further information can be provided at some point in the future, comment on this issue with the requested information and if appropriate the issue will be reopened.
