### ISSUE TITLE
Feature request: Discord Rich Presence

### ISSUE THREAD

**Issue by Turbotailz** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2896]
So Discord have just buffed their "Now playing" section on a user's profile which lets developers of games/apps push more information to Discord about what the user is doing in that game/app.

It'd be really awesome if GPMDP sent info to Discord about what I'm listening to.

Here's the documentation on Rich Presence in case you're interested in pursuing this:
https://discordapp.com/developers/docs/rich-presence/how-to

**Comment by Alipoodle** [comment]
I doubt that this will be added into the program directly!

However there are other programs that will easily be able to do this job. [SimplePresence](https://github.com/justdotJS/SimplePresence) is one of the ones I have been using, and supports other media services!

**Comment by SolarLiner** [comment]
This would be perfect using the plugin system in development #2216 .

**Comment by MarshallOfSound** [comment]
This is another thing to go into the "potential plugin list" #2216
