### ISSUE TITLE
Installation on Ubuntu

### ISSUE THREAD

**Issue by sevku** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2897]
Is there a way to install GPMDP on Ubuntu? I understand that Fedora and Debian are not Ubuntu, however I tried to install the .deb file on Ubuntu and this was the result:

```
sudo dpkg -i Downloads/google-play-music-desktop-player_4.4.1_amd64.deb 
(Lese Datenbank ... 223208 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../google-play-music-desktop-player_4.4.1_amd64.deb ...
Entpacken von google-play-music-desktop-player (4.4.1-1) über (4.4.1-1) ...
dpkg: Abhängigkeitsprobleme verhindern Konfiguration von google-play-music-desktop-player:
 google-play-music-desktop-player hängt ab von libappindicator1; aber:
  Paket libappindicator1 ist nicht installiert.

dpkg: Fehler beim Bearbeiten des Paketes google-play-music-desktop-player (--install):
 Abhängigkeitsprobleme - verbleibt unkonfiguriert
Trigger für gnome-menus (3.13.3-6ubuntu3.1) werden verarbeitet ...
Trigger für desktop-file-utils (0.22-1ubuntu5.1) werden verarbeitet ...
Trigger für bamfdaemon (0.5.3~bzr0+16.04.20160824-0ubuntu1) werden verarbeitet ...
Rebuilding /usr/share/applications/bamf-2.index...
Trigger für mime-support (3.59ubuntu1) werden verarbeitet ...
Fehler traten auf beim Bearbeiten von:
 google-play-music-desktop-player
```

**Comment by SolarLiner** [comment]
could you type "export LANG=en_US.UTF-8" before starting the install again?

Also, this looks like dependencies are missing. For some reason `dpkg` doesn't install dependencies by default.
In this case, simply run `sudo apt -f install` and it should resolve everything by itself.

**Comment by sevku** [comment]
Seems like `sudo apt -f install` resolved the issues. I didn't see any effect of `export LANG=en_US.UTF-8` however, assuming this should have changed the output language in the terminal.

Thank you very much for your help.
I'm amazed that even Chromecast is working well.

**Comment by SolarLiner** [comment]
Indeed, the `LANG` line was for me to understand something from that error message 😹

**Comment by sevku** [comment]
I think it would be a good idea to not just write Fedora and Debian on the Download page. It was a little confusing for me as a beginner.

**Comment by SolarLiner** [comment]
Linux's fragmentation problem is partly due to that. You have to know that Ubuntu is based on Debian, and as such the inner workings of the OS are the same. Generally, Debian packages are compatible with Ubuntu.

**Comment by MarshallOfSound** [comment]
Appears to have been resolved 👍
