### ISSUE TITLE
Feature request: Volume Control from status bar menu when connected to Chromecast

### ISSUE THREAD

**Issue by sevku** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2898]
It would be awesome if the volume could be controlled from the status bar even when playing via Chromecast.

**Comment by MarshallOfSound** [comment]
The apps volume controls do control the volume of the Chromecast while casting.  We can't link your system volume to chromecast volume as this will lead to unknown states
