### ISSUE TITLE
Volume Icons / Stepping not present.

### ISSUE THREAD

**Issue by KyleSanderson** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2899]
**OS:**
Win10 2016 LTSB x64
**Issue Descriptions:**
Clicking on the volume icons do nothing in the desktop player. One would expect there to be stepping present based on the icons...
**Steps to Reproduce:**
Click on the volume icons, nothing happens.

**Comment by jostrander** [comment]
This isn't present on the web application either, which this is just a wrapper for. It could probably be added, at the cost of having to update any time the UI updated on Google's end.

**Comment by WillPresley** [comment]
This needs backported to the web app ASAP, haha, very handy when your mouse is already nearby. Great work on this little QoL feature too, gentlemen.
