### ISSUE TITLE
Feature Request: Share to Contact and Notification List

### ISSUE THREAD

**Issue by Gloryboy811** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2900]
So if we could share a song/album and it would show a drop down where we could type the name of a google contact of ours. Then it would send them a notification in the app. So they dont have to leave the app to see it. just click the notification and it would navigate to that song.

**Comment by jostrander** [comment]
This would require maintaining a server for messaging other users and storing personal information about users (email, songs, etc). I don't think this is something we're going to implement.
