### ISSUE TITLE
Feature request: Star Ratings Option

### ISSUE THREAD

**Issue by stevephillips** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2901]
The past few years I have been using the Prime Player Google Chrome extension (https://chrome.google.com/webstore/detail/prime-player-for-google-p/npngaakpdgeaajbnidkkginekmnaejbi) for my music fix but the author announced in July that it will no longer be maintained. The plugin still works but has developed a few issues such as the track progress bar stops working.

One of the main features of this plugin that I used was the 5 star rating system that the author kept in even after Google removed the official Labs option. Like many others my feelings about music are more complicated then just thumbs up or down, E.g.

**5 Stars** - Awesome tune (must listen to again)
**4 Stars** - Good tune (add to mobile playlist)
**3 Stars** - Liked it (Mainly to mark it as rated so it can be potentially filtered out in an unrated playlist)
**2 Stars** - Not a fan but maybe listen to again
**1 Stars** - Don't like it, don't play again

Since finding this app and liking the look of it I would like to request that this functionality is added as a optional toggle so I can migrate over to it. I especially like the skip disliked songs feature that you have so I'd hope this would integrate into it too (like a drop down to select the minimum stars before skip).

For anyone wondering, yes Google removed the 5 star rating system but their API still supports receiving them and they are still stored as officially confirmed here https://productforums.google.com/forum/#!topic/play/HwKmVF5N5YA. FYI the Prime Player source is here if anyone wants to know how they implemented it https://github.com/svenackermann/Prime-Player-Google-Play-Music. I am assuming the official web player just sends 1 for thumbs down and 5 for thumbs up.

Thanks

**Comment by jostrander** [comment]
Duplicate #1355. As far as I know we have no plans to implement this directly. This may be a good candidate for the plugin system in the future.
