### ISSUE TITLE
Unreadable text in dark theme

### ISSUE THREAD

**Issue by SpectralKH** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2902]
![screen shot 2017-12-08 at 7 57 34 pm](https://user-images.githubusercontent.com/11315492/33783839-ae0d0a5c-dc5e-11e7-8eb4-8114bb37b570.png)
Would be nice if this text was more readable in dark theme. It's suggestions for what fields should be in the edit dialog - Pops up if GPM recognizes a song you've uploaded.

Here the element is in the element inspector:
![screen shot 2017-12-08 at 9 31 02 pm](https://user-images.githubusercontent.com/11315492/33783949-216d0060-dc5f-11e7-9ccb-d3d979f6e521.png)

**Comment by MarshallOfSound** [comment]
Theming issues should be raised on our theming repository

https://github.com/gmusic-utils/gmusic-theme.js
