### ISSUE TITLE
Feature Request/Bug: Cast-To List Overflow

### ISSUE THREAD

**Issue by vibbix** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2903]
I live in a dorm building, where the amount of Castable devices significantly overflows the list. It would be great to either have it scroll properly, and/or implement a filter on top to filter through the available targets
![image](https://user-images.githubusercontent.com/1731900/33800303-21df55dc-dd0b-11e7-9322-f0843aa4d138.png)

**Comment by jostrander** [comment]
This was fixed in #2794, but I don't believe has been published yet.
