### ISSUE TITLE
Lyrics don't scroll when casting to a device

### ISSUE THREAD

**Issue by Grayda** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2906]
**OS:** 
Windows 10

**Issue Descriptions:**
When casting to an external device, lyrics don't scroll

**Steps to Reproduce:**
1. Open GPMDP. Play a song that has lyrics
2. Click the overflow dots and click "Show Lyrics (Beta)".
3. Note how the lyrics scroll as the song progresses
4. Click the Chromecast icon and select a device (I'm using a Google Home in this instance). Play a new song.
5. Click the overflow dots and click "Show Lyrics (Beta)"
6. Now how the lyrics don't scroll as the song progresses.

Given that the lyrics don't "scroll back" if you rewind the song, my guess is that scrolling and / or the position of the lyrics isn't tied to the elapsed / total time. Tying it to that would (I'd presume) scroll when casting, but also shift around as you fast forward / rewind the song.

**Comment by MarshallOfSound** [comment]
General timing things are a bit broken in the current release and work fine in current master
