### ISSUE TITLE
Feature Request: Downloading of Playlists

### ISSUE THREAD

**Issue by Johnston524** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2907]
I know the actual web browser doesn't support downloading of playlists (but does albums and individual songs which strikes me as a very peculiar decision) but would there be a way of pseudo circumnavigating the restriction? The only way I can think of getting around this would be to have the app 'play' the playlist and cache to AppData/ProgramFiles and then when playing a song have it check for it in cache first before streaming.

Cheers

**Comment by jostrander** [comment]
Unfortunately this isn't something we can or want to tackle. Downloading music in the application is not something supported by this player.
