### ISSUE TITLE
pause music when headphone is disconnected

### ISSUE THREAD

**Issue by jan-schulz-k24** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2908]
**OS:** 

Linux (Ubuntu 17.10)

**Issue Descriptions:**

I use a Bluetooth headphone and every time the headphone disconnects the whole room hears my music. It would be nice if the music player could pause when the current "target" is disconnected. 

**Steps to Reproduce:**
Use a headphone
Play music -> nothing is heard outside of the headphones
Disconnect the headphones -> everybody hears my music

**Comment by MarshallOfSound** [comment]
This is something that should be configured at the OS level, if we are just pointing at the OS's default sound output device we have no way to know if the end target of that "default" id has changed.  The OS on the other hand can both issue pause requests and know if the device changes.  Android for instance does this by default, you should look into a way to do it on Ubuntu 👍
