### ISSUE TITLE
Make tray icon smaller

### ISSUE THREAD

**Issue by rrmhearts** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2909]
**OS:**
Ubuntu / Debian / Elementary with Gnome
**Issue Descriptions:**
The tray icon is twice as large as all other icons in the tray. It looks strange and unnatural. The height and width could shrink by approximately 30%! Thanks!
**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment]
Duplicate #2050
