### ISSUE TITLE
Request: Hotkey for I'm Feeling Lucky

### ISSUE THREAD

**Issue by geor9** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2910]
![image](https://user-images.githubusercontent.com/30334744/33956318-0788a004-dff3-11e7-8db7-4d9638cba6a2.png)

This button's great and I use it almost as often as Thumbs Down and Next Track. I'd be grateful if it was added it to the hotkeys.

**Comment by jostrander** [comment]
This should be possible, and I might take a stab at it soon.
