### ISSUE TITLE
Plays are not being saved to last.fm scroble

### ISSUE THREAD

**Issue by danemorgan** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2912]
**OS:**
Windows 10 Insider Preview 17025.1000 (rs_prerelease)

**Issue Descriptions:**
Beginning yesterday (20171212) the current song I'm playing shows as "Scrobbling now" on my last.fm account page, but when the next song starts it shows as "Scrobbling now" and the last song is not saved to my scroble list. It doesn't seem to be a problem with my last.fm account because I am scrobling music through my Android scrobler right now and those are being saved.

**Steps to Reproduce:**
Open Google Play Music Desktop Player and play music then look at [my profile page on last.fm](https://www.last.fm/user/dane-morgan).

[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/1560622/debug_info.zip)

**Comment by hyperspacey** [comment]
For what it's worth, I encountered this and one or both of updating to the latest version of GPMDP and logging out and back into Last.FM in the Desktop Settings section of the menu seems to have resolved it.

**Comment by MarshallOfSound** [comment]
Timing issues fixed in current master, see closed issues RE this

**Comment by hyperspacey** [comment]
Reproduced again on 4.4.1, Windows 10 Pro. Restarting the application restored scrobbling functionality.

**Comment by jostrander** [comment]
This is fixed in master. It will be reproducible until the next release.

**Comment by hyperspacey** [comment]
D'oh. Sorry, I thought 4.4.1 had the fix in. Disregard.

**Comment by danemorgan** [comment]
Any projection on when that release will go out?

**Comment by jostrander** [comment]
It's up to @MarshallOfSound to release so whenever he's available to build, sign and publish everything.
