### ISSUE TITLE
Album artwork visualization doesn't display

### ISSUE THREAD

**Issue by purajit** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2913]
**OS:** MacOS

**Issue Descriptions:** Unable to show album artwork visualization. Hotkey, using the menu bar option does nothing, and hovering over the mini-artwork next to the progress bar doesn't show the option to start the artwork visualization

**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment]
Google removed this from GPM itself, not much we can do about this 😢
