### ISSUE TITLE
Feature Request: Show Now Playing on Discord using Rich Presence

### ISSUE THREAD

**Issue by matthileo** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2915]
Discord has a new, fancy now playing view. It'd be cool if GPMD supported this. https://discordapp.com/developers/docs/rich-presence/how-to

https://camo.githubusercontent.com/3d78fc17760565cf3949a140adb00254b7e9d03b/68747470733a2f2f732e7068696e6561732e696f2f73686172652f446973636f726450726f66696c652d52525f35302e706e67

**Comment by SolarLiner** [comment]
inb4 it gets closed so fast it ionizes air into plasma, #2896 already proposed such a feature, to which it was already said "This is a feature for the plugins #2216 "

**Comment by MarshallOfSound** [comment]
> inb4 it gets closed so fast

Was in a good mood tonight, have an early christmas present folks who wanted this 😄

**Comment by SolarLiner** [comment]
Still a very good feature. I wish my Electron/React skills allowed me to get my hands a little more dirty 🤣
