### ISSUE TITLE
macOS don't scrobble to Last FM even it's connected to the app

### ISSUE THREAD

**Issue by nutcracker2099** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2919]
**OS:** OS X El Capitan – 10.11 macOS High Sierra – 10.13

**Issue Descriptions:** even Last FM it's connected to the app, just scrobble a few ones of all the items played, and can't see what's your live playing on your LastFM Profile, the few scrobbles appears suddenly .

I tried to log out and login to the Last FM service, but don't work as a solution.

**Steps to Reproduce:**

**Comment by jostrander** [comment]
Duplicate #2740 and many others.
