### ISSUE TITLE
Vertical Scrollbars appearing on top of Full Album Art View 

### ISSUE THREAD

**Issue by irriadin** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#292]
The issue: http://puu.sh/nxr0i/4d533a599d.jpg

Seen above, the vertical scollbars are being layered on top of the full album art view. I did notice that while playing a different album, they didn't appear, so I'm not sure exactly what is causing the issue.

**Comment by MarshallOfSound** [comment]
This is a bug in chromium / electron at the moment.

It should be fixed soon enough :+1:
