### ISSUE TITLE
Feature Req: Thumbs up/down on mini player

### ISSUE THREAD

**Issue by Jahfry** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2922]
**OS:**
Windows 10

**Issue Descriptions:**
Not a bug. Feature request. Thumbs Up/Down UI on mini player when mousing over

**Steps to Reproduce:**
none

**Comment by Jahfry** [comment]
PS. Thank you. Been wanting this standalone client for awhile so I can close Chrome but still listen.

**Comment by MarshallOfSound** [comment]
Discussed this in many issues, those thumbs buttons are there on radios and not on normal queues, this is just to allow normal queues to have shuffle / repeat controls as most users expect
