### ISSUE TITLE
Miniplayer Size keeps increasing automatically

### ISSUE THREAD

**Issue by Dr-Xperience** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2923]
#2269 
**OS:**
Windows 10 and Centos7

**Issue Descriptions:**
On switching to mini player, the player keeps increasing it's window size continuously the only way to stop is either stopping the player from task manager or somehow going back to the main player. Where everything now looks humongous (My machine is Dell 7559, with Nvidia Optimus graphics)

**Steps to Reproduce:**
I just installed and switched to mini player in both the oses

**Comment by SolarLiner** [comment]
Why opening a new issue? The issue you linked is still opened. There is no need for duplicate issues.

**Comment by jostrander** [comment]
Yep, duplicate. Track in #2269
