### ISSUE TITLE
Playback quality falls apart under high CPU load on Linux

### ISSUE THREAD

**Issue by skmkenn** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2924]
**OS:** Linux Mint 18.3 MATE 64-bit, Linux Kernel 4.10, PulseAudio 8.0

**Issue Descriptions:** When the system is under high CPU load or experiences a CPU spike, the audio playback from Google Play Music Desktop Player becomes distorted and stutters, pops, and skips. Other players such as VLC and Spotify do **not** experience this issue.

**Steps to Reproduce:** Open a lot of tabs in Firefox or Google Chrome at the same time while audio is playing through GPMDP, run `stress --cpu <number of threads>` from a Terminal, or perform any other task that causes the CPU to run under high load.

**Comment by MarshallOfSound** [comment]
I can't speak as to how resource intensive the DRM that GPM implements is to "undo" on your machine, all I can say is (a) this is out of my hands 😢 and (b) it should get better with the performance improvements an Electron update will give 👍
