### ISSUE TITLE
Backing up and restoring machine id to prevent dings to "authorized devices" number.

### ISSUE THREAD

**Issue by pauldotknopf** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2926]
Google only allows 10 devices to be used with your account. I have many machines and devices, exceeding the maximum allowed.

It there a config file or something that I can backup and restore to a new machine that will be seen from google as the same as the old machine?

**Comment by jostrander** [comment]
You can deauthorize devices as needed in your GPM settings. There isn't an I'd or anything stored in settings that can be backed up.

**Comment by MarshallOfSound** [comment]
See @jostrander's comment 👍
