### ISSUE TITLE
High Disk Write when streaming

### ISSUE THREAD

**Issue by Deckee** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2927]
**OS:**
Linux Mint 18.3 (Ubuntu 16.04)&win 10
**Issue Description**
High Amount of Data Written to Disk when Streaming. GPMDP has written 1 Tb of data to my Linux ssd(chrome has writen 60gb)over a 300 hundred day span. My calculations put the amount of data written at~3.68gb every day at 8 hours of music and I use my linux workstation daily for ~9 hours and listen to music using it for ~8 hours a day. Its a small mount of data in a hour but it adds up and ssds have a limited write limit. A fix would be to write to ram on machines with ssd or use a hdd as a cache disk.
**Steps to Reproduce:**
stream music and open a disk monitor

**Comment by MarshallOfSound** [comment]
If this is the chromium cache there is nothing we can do about this, if it's the JSON API just turn it off :+1:
