### ISSUE TITLE
Where do I ask if I can submit a pull request?

### ISSUE THREAD

**Issue by shbmira** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2928]
Hey, guys!

First of all, sorry for opening an issue! This is definitely not a bug!

In your Contributing Guide, in the Pull Request section, you recommend **to ask first**, before spending time working in a feature/improvement that you may not be interested to merge into the project. Ok.

But where do I ask? Am I doing right here?

I suggest you put a link to this, or clarify to the new possible contributors.

And, congratulations!!!! Excellent desktop app and open source decision!
😄

**Comment by MarshallOfSound** [comment]
For large features / changes you should raise an issue here explaining what you want to do and why you want to do it.  If it's just a small change submit a PR and I'll take a look, anything bigger and we should discuss first to make sure you aren't wasting your time 👍
