### ISSUE TITLE
Take bitcoin donations, instead of only paypal

### ISSUE THREAD

**Issue by ccolorado** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2929]
Happily will show you how if you don't know.
Also If you can add a HOTKEY to go in and out the mini player would be awesome.

Happy holidays.

**Comment by MarshallOfSound** [comment]
Although a cool concept, selling / trading bitcoins for NZ'ers is quite difficult so gonna stick with paypal for now 😆
