### ISSUE TITLE
Uncaught Exception: Update check failed: (null)

### ISSUE THREAD

**Issue by Tanzimrashid** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#293]
An uncaught exception was reported.  
#### Info:
**OS:** darwin
**Arch:** x64
**GPMDP Version:** 3.0.0
**Time:** Sun Mar 06 2016 19:46:53 GMT-0500 (EST)

#### Error:
*Update check failed: (null)*
```js
Error: Update check failed: (null)
    at Error (native)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
Raised on electron
