### ISSUE TITLE
Scrobbles do not "stick"

### ISSUE THREAD

**Issue by im-sean** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2931]
**OS:**
MacOSX

**Issue Descriptions:**
Last.fm recognizes the track I am currently listening to (scrobbling now), but once the song is complete, the track is not recorded in Last.fm. In other words, songs are always "scrobbling" but never "scrobbled". I've tried deauthorizing and reauthorizing, and restarting, obviously. 

**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment]
Fixed in master, goes with the other timing issues. Please checked closed issues before raising new ones 👍
