### ISSUE TITLE
No audio over Bluetooth on mac

### ISSUE THREAD

**Issue by jaredkotoff** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2932]
**OS:** macOS 10.12.6

**Issue Descriptions:**
No audio over Bluetooth

**Steps to Reproduce:**
Connect to BT device, play music.

I have tried two separate pairs of Bluetooth headphones. 
All system audio comes through headphones, but not GPMD
I have also tried changing the Audio Device in the Playback settings to the headphone specifically
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/1593648/debug_info.zip)

**Comment by MarshallOfSound** [comment]
Unfortunately there's nothing I can do about this 😆 I've been using a variety of bluetooth headphones with multiple macs over the years and never had a problem.  I'd suggest ensuring headphone firmware and macOS updates are fully installed and up to date.

**Comment by jaredkotoff** [comment]
I feel pretty dumb but in case anyone else ever has the same issue it was being caused by Loopback
