### ISSUE TITLE
Flatpak support

### ISSUE THREAD

**Issue by giovannicaligaris** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2933]
Would it be possible to make a flatpak and host it in Flathub?

https://flathub.org/

That way more linux distros could have access to your app!

**Comment by jostrander** [comment]
I believe that was the point behind building for [Snapcraft](https://snapcraft.io/).  I guess there can never be one cross platform standard, but adding every system becomes a nightmare for releasing.

**Comment by giovannicaligaris** [comment]
I didn't realize there was a snap package. I believe flatpaks are a bit more popular than snaps but I could be wrong.

**Comment by SolarLiner** [comment]
I don't know, but flatpak's reputation got a dent with the inability for apps to use system theming, among other things, and still a lack of good GUI (or even CLI) options. Snapcraft is much better in this category, despite having its own share of problems.

The journey to the one cross-distro standard is long and twisted. Who knows what lies ahead...

**Comment by MarshallOfSound** [comment]
This may be reviewed at some point in the future after the flatpak vs snap vs appimage vs _who knows what_ war ends and the dust settles with hopefully one cross platform standard.  For know, we'll hedge our bets on snapcraft.
