### ISSUE TITLE
Sonos cast support

### ISSUE THREAD

**Issue by niklasjohannes** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2934]
**OS:**
Win 10, 64-bit

**Issue Descriptions:**
Whereas chromecast audio works (thanks a ton btw!), Sonos speakers do show up as cast option on the Android app of play music, but not on the desktop player. Any chance you're planning to tackle this in foreseeable future? Thanks!

**Steps to Reproduce:**
Desktop player does not recognize any Sonos speakers as cast option.

**Comment by MarshallOfSound** [comment]
This is due to SONOS integration in the Android app for GPM, SONOS doesn't use the chromecast protocol for communication.  Adding support is neither easy nor feasible as I don't even own a SONOS device.  This is probably just not going to happen 👍

**Comment by samomar** [comment]
@niklasjohannes 
https://www.makeuseof.com/tag/stream-computer-audio-output-sonos/

http://www.streamwhatyouhear.com/download/
