### ISSUE TITLE
Unusually high CPU usage on Linux

### ISSUE THREAD

**Issue by nermolov** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2936]
**OS:** Arch Linux

**Version:** Release 4.4.1

**Issue Descriptions:**

Oddly high CPU usage under linux: ~20% utilization on 4/4 threads when playing (both when window is in focus and when it is out of sight)

Normal-ish CPU when paused (15% on 1/4 threads with 2% on others).

Doesn't seem to be an issue with electron apps in general as Discord and Atom sit at reasonable usage (~5% on 2-3 cores) even when actively used/interacted with. Discord did have some issues in the past with lag when GPU acceleration was on (using xf86-video-intel driver) and switching that off reduced lag in Discord, but did not change CPU usage, stayed at the same 5%. Tried running gpmdp with `--disable-gpu` but the issue persisted. Thought that it might be an issue with my install so tried a clean Arch install with only i3, xf86-video-intel and gpmdp but the issue persisted. Thought it might be an issue with i3 but running gpmdp in GNOME gives the same issue. 

I will gladly open a PR if someone can help lead me to where the issue lies.

**Steps to Reproduce:**

Don't have any other hardware such as this to try it out on, have a very powerful desktop also running Arch but gpmdp doesn't make a dent in the CPU usage there (difference in systems: desktop uses amd gpu).

* Hardware: Intel i7-6500U (4) @ 3.100GHz with iGPU
* Install Arch + i3 + xf86-video-intel and start Xorg (also tested with gnome, issue persists)
* Install gpmdp and run

**Comment by MarshallOfSound** [comment]
This isn't an issue Electron apps as you've discovered rather Google Play Music's JS code, (which is out of my control).  If you do performance analysis it isn't our code that is causing the CPU usage 👍
