### ISSUE TITLE
Moving GPMDP in fullscreen mode to an external monitor freezes computer, causes log out

### ISSUE THREAD

**Issue by hentercenter** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2937]
**OS:** macOS 10.13.2

**Issue Descriptions:** Moving GPMDP, while in fullscreen mode, to an external monitor causes computer to freeze and forces a log out of the current user. Cannot reproduce with any other fullscreen application.

**Steps to Reproduce:**
1. Open GPMDP in fullscreen mode
2. Open Mission Control
3. Move the GPMDP fullscreen to external monitor

**Comment by jostrander** [comment]
Is this still an issue with 4.5.0?

**Comment by hentercenter** [comment]
@jostrander appears to be fixed

**Comment by jostrander** [comment]
Glad to hear.
