### ISSUE TITLE
Cannot replace the pinned taskbar icon as possible in other apps

### ISSUE THREAD

**Issue by jwbrobst** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2938]
**OS:** Windows 10

**Issue Descriptions:** Generally when an application is pinned you can visit the icon shortcut in the taskbar folder buried in Windows and permanently change the icon just on the taskbar. I can change the icon but it returns to it's old orange and yellow look as soon as I reopen the app. Probably runs that icon check on every startup. I would like to be able to use a custom icon.

**Steps to Reproduce:** Open Run: "%APPDATA%\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar" and with GPMDP right-clicked select properties, change icon. Wait for Windows to update icon cache or use a program to force it. Custom icon will be shown. Open program. Custom icon is now gone.

**Comment by MarshallOfSound** [comment]
@jwbrobst You need to change the icon for the actual executables `Update.exe` and `Google Play Music Desktop Player.exe` not the shortcut itself.  This is because of the way Windows resolves icons and how we use `Update.exe` as a launch trampoline
