### ISSUE TITLE
Hangs if Google 2-Step Verification is enabled

### ISSUE THREAD

**Issue by Gerry2k5** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#294]
I have 2-Factor Verification enabled on my Google account, and when I run the app, it hangs after entering my password, at the point when the authenticator code would normally be requested.

Environment:
PC, Arch Linux, downloaded zip from Git repo

**Comment by MarshallOfSound** [comment]
Duplicate #280
