### ISSUE TITLE
Back screen on Windows 10

### ISSUE THREAD

**Issue by moritzm** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2943]
**OS:**
Windows 10

**Issue Descriptions:**
The desktop app got black screen when opeing it freshly. It doeas not alway happen, but in most cases. When the screen is not black, it got black after some minutes using the app. It doeas not matter if i maximize screen like in issue https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/283
Will update with detailed app and OS version when i am at home again.

**Steps to Reproduce:**
Just open the app fresh from start menu. It is not running on background. It is not always black, but most of the time.

**Comment by MarshallOfSound** [comment]
This will be a graphics driver issue, it will almost certainly be fixed by an Electron upgrade
