### ISSUE TITLE
Feature request: Show song + artist in OSX menu bar

### ISSUE THREAD

**Issue by nick-allen** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2944]
**OS:** Mac

**Issue Descriptions:** would like to see the song and artist displayed in the menu bar next to the icon without having to open the player or click the dropdown.

**Comment by MarshallOfSound** [comment]
This is not something we can do easily, PR's welcome but this isn't going to get done any time soon.
