### ISSUE TITLE
Time from previous track overflows into next in json data

### ISSUE THREAD

**Issue by Phoenixthedoggo** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2946]
**OS:**
Windows 10
**Issue Descriptions:**
Time Overflow? 
Basically, the time into the song carries over from the last track to the next when playing music in albums.
https://imgur.com/a/vij8Z
**Steps to Reproduce:**
Play an album, then wait for 2nd track to come up and watch .json data as it overflows the actual time into the song.

**Comment by jostrander** [comment]
This is fixed in master. Will be published in the next release.

**Comment by Phoenixthedoggo** [comment]
Thanks!
I was doing some stuff with Discord Rich Presence and noticed the issue!
