### ISSUE TITLE
Resizing Mini-Player causes UI in main display to change size too.

### ISSUE THREAD

**Issue by ThisIsSet-L** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2947]
**OS: Windows 10 x64 1706**

**Issue Descriptions: Resizing Mini-Player causes UI in main display to change size too.**

**Steps to Reproduce: Open mini-player, make it huge, escape back to main UI, open a link or another page. Resizing the mini-player smaller has the inverse result.**

The video explains it better:
https://set-l.space/bug.webm

**Comment by MarshallOfSound** [comment]
Merging into #2269
