### ISSUE TITLE
Installation/Cache location

### ISSUE THREAD

**Issue by Lister50** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2948]
Hi,
I couldn't find anything in the FAQ/wiki or looking through the source, but was wondering if it would be possible to add the option of specifying an install location and/or a cache location.  I think it would be good to be able to keep the cache away from roaming profiles in Windows if at all possible.

Thanks - the application itself is absolutely fantastic.

Cheers.

**Comment by MarshallOfSound** [comment]
This is how Squirrel.Windows is designed to work, we can't and won't be changing it 👍
