### ISSUE TITLE
Windows 10: Back button is white on gray with the default theme

### ISSUE THREAD

**Issue by acerspyro** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2949]
Using Windows 10 build 16299.192, the back button when using the default theme is white, rendering it barely visible. See the screenshot below:

![image](https://user-images.githubusercontent.com/4400999/34854425-a126208a-f707-11e7-8658-d7023c01b004.png)

I am using the "Use system window borders" option if it makes any difference.

**Comment by MarshallOfSound** [comment]
Fixed in master
