### ISSUE TITLE
Feature Request: Icon on Albums Already in User Library

### ISSUE THREAD

**Issue by disquiet** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2951]
This is a feature request. I think this is the right place to submit one. Would it be possible to have album graphics display whether or not an album is already in a user's library? I believe Rdio used to have this feature, and it's a great way when pulling up a favorite artist to see if any albums have newly appeared in their catalog recently. It could be as simple as having a little colored dot appear in the lower right corner of a given album if it's already in a user's library.

Thanks for considering this request.

**Comment by SolarLiner** [comment]
AFAIK this is out the scope of the app, and even out of the possibilities. Doing this requires getting the user library contents, which is not possible/very hard.

**Comment by jostrander** [comment]
Yeah, this won't be possible because we don't have a method of retrieving and matching the user library to the album, as google keeps that information pretty guarded. You can try raising this on their product forums though.

**Comment by disquiet** [comment]
Gotcha. Thanks. I thought the library/album match is possible, since each album's three-dot menu changes based on whether or not an album is in one's library (that is, if it isn't, the album-specific menu has the "add to library" option, and if it is, the menu changes to have the "remove from library" option). Thanks having clarified it.

**Comment by jostrander** [comment]
Yeah unfortunately that three dot menu isn't static, so in order to actually generate the menu you have to click the three dots. Once the menu disappears so do the menu items. The same three dot menu is shared through the entire application, which makes it a pain to do things such reading context from one.

**Comment by disquiet** [comment]
Gotcha. Thanks for that. I'm really enjoying using GPMDP.
