### ISSUE TITLE
Feature Request: Display thumbs up in menu bar icon

### ISSUE THREAD

**Issue by JosNun** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2952]
**OS:** macOS

**Feature Proposal:** In many instances, I will have GPMDP minimized while playing music. When I want to like a song, I have to open the window, then hover over the button only to find that the song has already been liked. If the like/dislike information was displayed in the menu bar (similar to the playback information), it would only take a glance instead of having to open/close the window. 

Thanks!

**Comment by MarshallOfSound** [comment]
Fitting a lot of information into an icon will most likely confuse more users than this would help, this isn't something I'm prepared to add at this point.
