### ISSUE TITLE
Feature Request: Enhanced but still small player

### ISSUE THREAD

**Issue by MultiDJRoni** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2953]
Hey

I wish there was an option to only show the "play pause bar". 
I have marked it in the Screenshot: [https://prnt.sc/i2s8d6](url)
I would like to use it on my third screen. But with the already great small player wich only shows the Cover i cant control the volume etc. 

Also, is it possible to controll it via the media keys on the Keyboard? (Play, Pause, Skip etc.)

(I hope you can understand what i mean, im form switzerland but i try my best to write understandable in English :D)

Thanks!

**Comment by MarshallOfSound** [comment]
Merging into #701
