### ISSUE TITLE
Hotkeys dont work

### ISSUE THREAD

**Issue by MultiDJRoni** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2954]
Hello

**OS:** Windows 10.0.16299, Build 16299

**Issue Descriptions:** The Hotkeys dont work for me.

**Steps to Reproduce:**
Theres nothing really to reproduce, if i click on "Nicht Gesetzt" nothing happens, even if i press a key. 
Rightclick doesnt work either.

**Comment by jostrander** [comment]
Sorry, which hot keys? The media keys on your keyboard, or the hot keys that are set in settings?

**Comment by MultiDJRoni** [comment]
Im sorry, i meant the hotkeys in the settings of the app.

**Comment by dooreelko** [comment]
same here on mac os (recently upgraded to latest)

**Comment by dooreelko** [comment]
So looks like it's only the UI that doesn't work.

So workaround.
Locate your app's settings folder. On macos it will be "~/Library/Application Support/Google Play Music Desktop Player/json_store". Other systems will have other paths, but the directory to look for is "json_store". It will have ".settings.json" file.

In the json's root put the hotkeys config
```
{
    "auto-launch": true,
... PUT HOTKEYS HERE

    "fullscreen": false
}
```
i only needed play/pause, so did like this:
```
{
    "auto-launch": true,
    "hotkeys": {
        "playPause": "MediaPlayPause"
    },
    "fullscreen": false
}
```

Available keys:
```
  playPause,
  stop,
  previousTrack,
  nextTrack,
  thumbsUp,
  thumbsDown,
  increaseVolume,
  decreaseVolume,
  infoTrack,
  imFeelingLucky,
```
Available key-codes:
https://github.com/electron/electron/blob/master/docs/api/accelerator.md

**Comment by jostrander** [comment]
Media hot keys should "just work" across platforms. Special key bindings are also available for the things listed in the settings as well in case you don't have media keys. Those hot keys require ctrl or command based on platform due to the player taking exclusive control of those hotkeys.

**Comment by dooreelko** [comment]
The hotkeys work, but the settings UI tab controls (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/renderer/ui/components/settings/HotkeyInput.js) don't capture them key presses, i.e. you cannot specify hotkeys.

**Comment by jostrander** [comment]
That's intended, as we automatically bind media keys (play, playpause, pause, next, previous) to the application. The hot keys area is only intended for keyboard shortcuts such as `ctrl`+`shift`+`n` for next for example.

**Comment by dooreelko** [comment]
aha. i see.

i've tried to use media keys today and nothing worked. checked the settings, all binding were empty, tried to set them to anything (FN+PlayPause, just random single keys) - nothing was happening.

now i've tried and combinations with ctrl are indeed captured by the settings tab.
So i guess at least in my case the issue is 2-fold:
OS: Mac OS High Sierra (10.13.2)
GPMDPU Version: 4.4.1 (did you know that the app has 2 different About dialogs?)

Issues:
- default mappings to media keys seem to be not working 
- (UX) Hotkey settings tab should 
    - mention that the user doesn't need to map "standard" playback keys
    - give user feedback on "unacceptable" key combinations. Like if only "a" is pressed, there should be message telling "'a' is insufficient for a system wide hotkey, please choose a combination with ctrl and/or shift" 
    - (minor) looks like on macs command is treated as ctrl, which is confusing (plus if you press command+n, nothing will be shown but if you focus out, focus back in and press shift, it will suddenly switch to shift+ctrl+n)

**Comment by jostrander** [comment]
Can you raise issues for the UX? They are more likely to be seen that way. As far as the hotkeys themselves not working I don't have a way to test mac unfortunately. Are you using a different keyboard by chance? Also @MultiDJRoni were you able to get it working? What keyboard are you using?

**Comment by MultiDJRoni** [comment]
@jostrander I got it working on my laptop. Ill try it on my PC (where i had the problem) in a sec and will get back to you again 👍

**Comment by Intruder66** [comment]
Not all Media Keys work for me. Previous/Next and PlayPause work. Stop is not Stop, but Pause. Volume Up and Down just change the overall device's volume.

**Comment by jostrander** [comment]
That's a separate issue @Intruder66, however it may be just your keyboard. Open a new issue following the template so we can have more details on your device.
