### ISSUE TITLE
Snap: Don't use an icon picture

### ISSUE THREAD

**Issue by Bohne13** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2955]
**OS:**
Ubuntu Linux 17.10

**Issue Descriptions:**
I habe two machines with Ubuntu Linux 17.10 and on both there is no picture for the icon. It's an installation over the ubuntu snap store.
Everithing is finde with the normal deb package installation.

**Steps to Reproduce:**
Install the application over the snap store

**Comment by prallin** [comment]
Same here!

**Comment by MarshallOfSound** [comment]
Although the snapcraft file is in this repo I don't personally maintain that distribution channel.  PR's are welcome to add whatever icon is required (you'll find the SVG's for our icons in the repo), but this isn't something I'm personally going to deal with 👍
