### ISSUE TITLE
[Linux][Elementart OS] Desktop Notifications Appear as coming from diffrent application

### ISSUE THREAD

**Issue by tankerkiller125** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2957]
**OS:**
Linux, Elementary OS Loki

**Issue Descriptions:**
Notifications Appear as if they are coming from a different application running in the notifications tray.

The Elementary OS Notifications Tray breaks down notifications based on the application that produced the notification. However it seems that this app doesn't do that correctly a notifications from this app show up under whatever the last notification I had running is instead of as its own separate application.

**Steps to Reproduce:**
1. Enable desktop notifications
2. Play some music, skip some songs
3. Open the Notifications Panel

**Comment by tf2manu994** [comment]
What application does it look like they are coming from?

**Comment by tankerkiller125** [comment]
One time phpstorm another time it was Firefox, another time with was the app center, it changes at random

**Comment by MarshallOfSound** [comment]
> One time phpstorm another time it was Firefox, another time with was the app center, it changes at random

This sounds like an OS bug, there's no real reason that we would be sending anything that looks like phpstorm or firefox 😆
