### ISSUE TITLE
Cannot sign into application under Ubuntu 15.10

### ISSUE THREAD

**Issue by bocajnotnef** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#296]
I'm having an issue with the player where I cannot login upon startup--it looks like it freezes up graphically. If I resize the window or close it and reopen it I get some odd artifacting: 

A screenshot:

![screenshot from 2016-03-06 20-20-24](https://cloud.githubusercontent.com/assets/2142082/13558808/f034afe6-e3d8-11e5-9bae-3a640f10ba31.png)

It looks like it's loading a page in the background and just hasn't redrawn the canvas--if I randomly click and drag I can copy elements out of the page ("Enter your email: ", "One account, all of google", etc) that aren't visible. I can access the language menu by clicking the rectangular white artifact in a corner of the screen; screenshot:

![screenshot from 2016-03-06 20-21-43](https://cloud.githubusercontent.com/assets/2142082/13558827/51bcb3a8-e3d9-11e5-92e6-96169d23e15e.png)

**Comment by MarshallOfSound** [comment]
Try starting the application with the `--disable-gpu` flag

**Comment by bocajnotnef** [comment]
It no longer freezes (and I can log in) but I have noticeable CPU usage (in the realm of 20%) when running animations (scrolling, opening albums, the 'playing' animation next to a song).

**Comment by MarshallOfSound** [comment]
Obviously lol, it pushes everything to the CPU :/

It's a work around until electron fixes linux things.  Other people have also said that different GPU drivers fix things

**Comment by ralphpig** [comment]
Just a note: I was able to run it **without** `--disable-gpu` once I was signed in.
