### ISSUE TITLE
[Linux][Ubuntu 17.10] No top menu

### ISSUE THREAD

**Issue by prallin** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2960]
**OS: Ubuntu 17.10**

**Issue Descriptions: No top menu**

**Steps to Reproduce: have tested both deb and snap**

**Comment by SolarLiner** [comment]
What do you mean by "top menu"? With Ubuntu 17.10 the application menu is back 'below' the window frame (because of the change from Unity to GNOME), and is accessible in the player by pressing Alt.

**Comment by jostrander** [comment]
I'm pretty sure @SolarLiner is on the money on this one. It doesn't display by default in 17.10 due to WM changes. If not respond and we'll discuss further.

**Comment by SolarLiner** [comment]
Actually after some further testing, it only works with system borders ON, which isn't the default IIRC. With the system borders off, the menu doesn't appear. Unity, and other DE with global app menu plugins circumvent the problem as the menu is still declared and shown outside the window.

**Comment by prallin** [comment]
Thanks, it  was the "Alt" I was looking for. Feeling a bit stupid not to find it myself @SolarLiner.
