### ISSUE TITLE
Upgrade electron to address CVE

### ISSUE THREAD

**Issue by ProjectFrank** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2961]
[Link](https://electronjs.org/blog/protocol-handler-fix)

> Electron apps designed to run on Windows that register themselves as the default handler for a protocol, like myapp://, are vulnerable.

> We've published new versions of Electron which include fixes for this vulnerability: 1.8.2-beta.4, 1.7.11, and 1.6.16. We urge all Electron developers to update their apps to the latest stable version immediately.

**Comment by jostrander** [comment]
This app doesn't register any default protocol handlers, so it doesn't effect this app. See https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/2950#issuecomment-359704021
