### ISSUE TITLE
remove overflow from .gpm-quick-nav-2

### ISSUE THREAD

**Issue by sirkuttin** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2964]
maybe simply add 

.gpm-quick-nav-2 {
    overflow: visible
}

**Comment by jostrander** [comment]
I'm not sure what this is for, there is a custom css area inside the player where you can add this.

**Comment by sirkuttin** [comment]
Hopping you can explain to me how to use that or point me towards documentation. 
I altered the CSS on the GPM website and verified this worked.
I attempted to create a CSS file with the above and added it to GPMDP, restarted the app and it didn't work.

**Comment by jostrander** [comment]
Did you load the CSS into the GPM css or the GPMDP css? There are two spots for CSS, one is for the wrapper UI, one is for the webpage itself.

**Comment by sirkuttin** [comment]
I attempted both. Also, there is no way to remove the CSS file which is silly.

**Comment by jostrander** [comment]
I agree. I've never used either, but it sounds like multiple bugs.

**Comment by Alipoodle** [comment]
![image](https://user-images.githubusercontent.com/17199186/35619289-75adcc82-0675-11e8-9216-9c0c9f9c95a4.png)
you shouldn't require a restart if you had added it in here?
The *reload styles* button is currently broken (Windows at least) but if you change the file it will update?
