### ISSUE TITLE
32 bit Debian installs but will not run on lubuntu 17.10

### ISSUE THREAD

**Issue by SRBogseth** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2965]
32 bit Debian installs but will not run on lubuntu 17.10

Any suggestions?

**Comment by jostrander** [comment]
Any particular error message? Install method? White screen of death?

**Comment by SRBogseth** [comment]
No, nothing, installed normally and also tried using gdebi, the app just never opens

**Comment by SRBogseth** [comment]
gdebi also says all dependencies are met as well

**Comment by jostrander** [comment]
What happens if you launch it from the command line? `google-play-music-desktop-player` or `gpmdp` I forget which is available.

**Comment by SRBogseth** [comment]
unable to locate package for either option

**Comment by jostrander** [comment]
You should have `google-play-music-desktop-player` at `/usr/bin/google-play-music-desktop-player`. If you don't then that's your issue. The desktop icon, which I assume is how you're attempting to launch the player specifically points to this to startup. I would reinstall if that's the case. Did you install using `dpkg` or `gdebi` via the release tab, or did you install via package manager, such as `apt` or `apt-get`?

**Comment by SRBogseth** [comment]
it is there, have tried reinstalling multiple times via package manager and via gdebi

**Comment by jostrander** [comment]
What happens when you launch it using the full path? can you `cat` that file?

**Comment by SRBogseth** [comment]
how can i launch it using the full path

**Comment by jostrander** [comment]
Open your terminal and type `/usr/bin/google-play-music-desktop-player`.

**Comment by SRBogseth** [comment]
/usr/bin/google-play-music-desktop-player: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory

**Comment by SRBogseth** [comment]
found the issue, ran "sudo apt-get install libgconf-2-4" in terminal, problem solved, it installed everything that was missing

**Comment by jostrander** [comment]
Awesome.

**Comment by qualidafial** [comment]
Shouldn't the .deb manifest declare a dependency on libgconf2?
