### ISSUE TITLE
Discord Rich Presence not working

### ISSUE THREAD

**Issue by CodyWarmbo** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2966]
**OS:** Windows 10 Pro v1709

**Issue Descriptions:** The new update is great, but when I enable Discord Rich Presence there is nothing shown in my Discord client whatsoever. It is not detected in the Games section of Settings whatsoever either.

**Steps to Reproduce:** Enable Rich Presence. Start Discord. Start GPMDP and play a song.

**Comment by MarshallOfSound** [comment]
@CodyWarmbo Sorry about this, looks like the App on discords developer site hasn't gone live yet.  Let me follow up with that

**Comment by MarshallOfSound** [comment]
It looks like this is working for people now, you may have to restart GPMDP to make it connect to discord successfully 👍

**Comment by CodyWarmbo** [comment]
Excellent. Thanks!

**Comment by Zyian** [comment]
I am encountering this issue on macOS and Windows 10 as well. I have tried different versions of Discord (Release, and Canary), checked settings, built app from scratch, and to no avail was I able to get the integration working.
