### ISSUE TITLE
Last.fm scrobbles dont complete/finalise 

### ISSUE THREAD

**Issue by privaydied** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2967]
**OS:**
Windows & Mac

**Issue Descriptions:**
Scrobbles don't finalise, I can listen to a song and it shows that it's scrobbling on my profile but when the song is complete it doesn't confirm itself as a scrobble, this issue is on Mac and Windows

**Steps to Reproduce:**
auth last.fm account
listen to a song

**Comment by MarshallOfSound** [comment]
This was fixed in `4.5.0` that was released yesterday 👍

**Comment by Maddieman** [comment]
Sorry, I can reproduce this in 4.5.0. :(

I'm listening to an album I uploaded, it scrobbled the first two tracks ok, then failed to scrobble the next 5 (now playing was sent). I'm not sure why yet.

I think it might be the old issue where it stops working if the player is minimised, but I haven't tested this thoroughly yet (I'm replaying the album).   I'm using Windows 7.

**Comment by AquaMorph** [comment]
I'm getting this problem as well on at this time the latest version `bb123156a7b05706e4f0ebd8d237dc8de0248ea0`
