### ISSUE TITLE
Discord Integration

### ISSUE THREAD

**Issue by SebastianRRasor** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2968]
Currently, the Discord Rich Presence feature shows "Playing **Google Play Music Desktop Player**".
I think it should show "Listening to SongName by Author", or something along those lines, and have the rich presence information still be presented.

Edit: My mistake, it may be possible to do the "Listening to" part but I doubt you could actively set the song and author like that.

**Comment by MarshallOfSound** [comment]
@SebastianRRasor I don't think we can change this text, the discord RP feature is really designed for games not music 😄 If you know a trick to make this look better PR's a welcome, otherwise I'm gonna close this out.
