### ISSUE TITLE
Cluttered Discord Rich Presences 

### ISSUE THREAD

**Issue by Alipoodle** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2970]
https://github.com/discordapp/discord-api-docs/blob/master/docs/rich_presence/Best_Practices.md#keep-it-short
On the Discord app API Docs it states that for best use of Rich Presences thinks should really be kept clean and short, and not overly show how much information you might have.

One example they say is _While Rank 9999 is impressive, it doesn’t present any actionable data for their friends_ This is mainly aimed at something like the current location in the queue, however nice of a feature it is, it doesn't really provide information that other people will really need to have!

Similarly I feel that maybe swapping the names for Google Play Music Desktop Player and Google Play Music might be better, as it shows up very long within the large profile model due to the application name being the full `Google Play Music Desktop Player`, and the icon for the Google Play Music Desktop Player is being shown where the hover text for it is `Google Play Music`.

Google Play Music Desktop Player Model
![Large Profile Model](https://puu.sh/zdwxU/ab50875e48.png)

Custom made Rich Presences I've made
![Custom Made Example](https://puu.sh/zdwru/606af51101.png)

Game Example
![Game Profile Model](https://puu.sh/zdwoA/2f8123d63d.png)

**Comment by MarshallOfSound** [comment]
The change of text (using emojis) is what we originally had, then someone PR'ed in the current style which tbh I like a bit better.   I don't think there is too much information there, it gives just enough information for anyone to find the song without being too noisy IMO

>  I feel that maybe swapping the names for Google Play Music Desktop Player and Google Play Music

This we can't do, don't really want to get in trouble
