### ISSUE TITLE
Abnormally high CPU consumption on Mac OS

### ISSUE THREAD

**Issue by app-knight** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2971]
**OS:** Mac OS High Sierra

**Issue Descriptions:** When starts GPMDP, it consumes 100+ percent of CPU resource. Device - MacBook Pro 13 2017, High Sierra with latest updates. Starts right after installing of app (version 4.5) on my Mac. The app is great, but it makes no sense to use it with such a big resource consumption.  Trying to delete and install again, same results.
Here's debug info, Mac specs, screens of activity monitor:
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/1681463/debug_info.zip)
[Mac_info.pdf](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/1681468/Mac_info.pdf)
<img width="1190" alt="screen shot 2018-01-31 at 1 03 14 pm" src="https://user-images.githubusercontent.com/34201084/35620314-789d917a-0689-11e8-98f0-521fdb36c140.png">
<img width="589" alt="screen shot 2018-01-31 at 1 03 54 pm" src="https://user-images.githubusercontent.com/34201084/35620311-76d53ea6-0689-11e8-9115-34f23134c4a5.png">
<img width="583" alt="screen shot 2018-01-31 at 1 04 03 pm" src="https://user-images.githubusercontent.com/34201084/35620309-76698774-0689-11e8-859f-1c797079931b.png">
After exiting app everything works great again.
<img width="803" alt="screen shot 2018-01-31 at 1 08 08 pm" src="https://user-images.githubusercontent.com/34201084/35620310-767d3620-0689-11e8-854d-4bd8f5ac95b7.png">

**Steps to Reproduce:** 

1. Start GPMDP, log in into account.
2. Open Activity monitor.
3. Enjoy)

**Comment by MarshallOfSound** [comment]
@app-knight Did you enable Discord Rich Presence?

**Comment by app-knight** [comment]
@MarshallOfSound Yes, it was enabled at Settings. Looks like it was by default, doesn't remember that I checked. Anyway, I disable it on settings, restart the app and result is pretty good:
![screen shot 2018-01-31 at 1 47 04 pm](https://user-images.githubusercontent.com/34201084/35621606-9c7a7848-068d-11e8-9822-64becf85611f.png)

Thanks!

**Comment by MarshallOfSound** [comment]
@app-knight It should be off by default, are you sure that you didn't enable it after the last update?

**Comment by MarshallOfSound** [comment]
Refs #2969
