### ISSUE TITLE
Snap build for 4.5.0 is missing on the snapstore

### ISSUE THREAD

**Issue by Bohne13** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2972]
I can't find someone who supports the snap package on snapstore. The snap version for 4.5.0 should be updated if it works as a snap.

**Comment by jostrander** [comment]
@RAOF What's the status on this?

**Comment by Bohne13** [comment]
I have tried to start the app after upgrading do the --edge snap channel. But the app doesn't start!

**Comment by jostrander** [comment]
Any error messages?

**Comment by Bohne13** [comment]
Nope, it only don't want to load the aplication.

**Comment by RAOF** [comment]
Hrm. Why didn't I see this?

Something screwy is going on with the naming of the binaries - it's coming through as `'Google Play Music Desktop Player'`, which is not what the launcher is expecting.

Let's see what's broken…

**Comment by Feichtmeier** [comment]
Hi - just wondering - why is the app only availible in 4.4.1 version in the snap store if not installed via edge?
