### ISSUE TITLE
Media Keys in Linux -> MPRIS Implementation

### ISSUE THREAD

**Issue by ZenHarbinger** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#298]
Running Ubuntu 16.04 64-bit, the media keys to not play/pause, next, or previous for me.

**Comment by MarshallOfSound** [comment]
Not a clue what could be going on here, I'll let a more linuxy person come up with some ideas :P

**Comment by parkerlreed** [comment]
Media keys can be implemented via MPRIS https://specifications.freedesktop.org/mpris-spec/latest/

This allows the player to publish metadata and be controlled from a central system.

**Comment by MarshallOfSound** [comment]
That's on a post-it note somewhere on my desk, there's a node module for it that didn't seem to hard to implement :)

**Comment by ZenHarbinger** [comment]
I'll try to take a look at it when I get a chance.  I've done a little bit w/ audio players and Ubuntu years ago; but this is magnitudes larger than anything I've done before.

**Comment by MarshallOfSound** [comment]
@ZenHarbinger Sounds great, anything you can do to help would be much appreciated :+1: 

Just imagine how I feel, a couple of years ago I was puzzling of year 11 algebra.....

**Comment by pszi1ard** [comment]
Media keys do  not work for me either on Ubuntu 14.04 (are they supposed to work at all?); the custom shortcuts do work, though.

**Comment by parkerlreed** [comment]
@pszi1ard It's only a pull request at the moment. It hasn't been merged.

**Comment by jostrander** [comment]
@pszi1ard Can you try doing this:

http://ubuntuforums.org/showthread.php?t=2241639&p=13110153#post13110153

and see if it helps?

**Comment by pszi1ard** [comment]
@jostrander Sure, it does, but it disables it for all other applications, so unfortunately it's not a solution that I can use.
