### ISSUE TITLE
Windows 10 Taskbar icon missing after update

### ISSUE THREAD

**Issue by zevisert** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2981]
**OS:** Windows 10 17083.rs_prerelease 180119.1645

**Issue Descriptions:** Electron App is missing app icon when window is open on desktop. 

**Steps to Reproduce:** Automatic update to 4.5.0 from 4.4.1. Reinstalling fixes issue.

**Comment by spikespaz** [comment]
This can be fixed by right-clicking the icon, and going to "Open file location..." Right click the shortcut, go to Properties, then click "Change Icon", and browse to the install location of GPMDP. There should be an ico file in there that is selectable.

**Comment by zevisert** [comment]
@spikespaz I was referring to the *Taskbar* Icon. Not a desktop shortcut.

**Comment by spikespaz** [comment]
@zevisert And I was answering about the taskbar shortcut. The taskbar uses the same shortcuts as the Windows Desktop and Start Menu, all `*.lnk` files, but in a special system folder. Chane the icon of that, and it fixes it in the taskbar.

**Comment by spikespaz** [comment]
I should add that you must pin it to start and right click to get the location from there. Then you can pin it to task bar after fixing the icon, and unpin from start.

**Comment by MarshallOfSound** [comment]
Sometimes the windows icon cache gets confused, rebooting or refreshing the cache would have also fixed the issue 👍
