### ISSUE TITLE
Spiking CPU ussage on MacOS

### ISSUE THREAD

**Issue by Jason-Keller** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2985]
**OS:**
Mac OS 10.13.3
**Issue Descriptions:**
When casually listening to music, the program lags HARD on my laptop, and drives up the CPU usage to 100%. If I'm on battery, it sucks the battery instantly.

**Steps to Reproduce:**
Open the program and simply play music, then go to the activity monitor and watch the cpu usage. It makes it very difficult to run this program altogether, and I often end up closing it and listening to nothing.

**Comment by luisfcosta** [comment]
Hey. I was about to open a ticket with a similar issue. I have searched this github page and found some other high cpu usage threads on osx, but I don't think my situation is the same.

I am seeing very high CPU usage on version 4.5.0. I speak of average CPU usage of 100% with some peaks going from 150 to 200%. This happens regardless of the fact that music is playing or not or if the window is minimized or not.

With version 4.4.1 I get an average CPU usage of 15/30% with peaks of 50 to 60%, which, while not being particularly low, are much better values altogether.

Did anything major change between these two versions?

I rolled back to 4.4.1 for now, but the thing keeps auto updating :P

Thanks for your support & great app.

**Comment by Jason-Keller** [comment]
Actually, yes, I did enable that feature to try it out. I'll disable it and then see if my battery life doesn't improve.

**Comment by luisfcosta** [comment]
Mee too. I'll disable and report back as soon as I get home!

**Comment by MarshallOfSound** [comment]
This will be Discord Rich Presence, see #2969 for more information and tracking this issue

**Comment by luisfcosta** [comment]
Just to confirm. I disabled that option and CPU went back to normal. Thank you!

**Comment by Jason-Keller** [comment]
I can also confirm this. Thanks Marshall! This is my #1 installed program on all my machines btw, so keep up the good work :)
