### ISSUE TITLE
Duplicate menus

### ISSUE THREAD

**Issue by jeffreywilcox** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2986]
What's up with the duplicate menu's? Not sure if this is a bug or enhancement request..  :)

<img width="320" alt="screenshot 2018-02-05 13 50 30" src="https://user-images.githubusercontent.com/32082126/35822868-a5769714-0a7b-11e8-9001-fbaa054a4b80.png">

-->

**OS:**
High Sierra 10.13.4 

**Issue Descriptions:**
2 duplicate navigation menus

**Comment by jostrander** [comment]
This is basically because that menu normally hovers over the secondary menu with the "keep sidebar menu" option disabled. This is an unintended side-effect of that option checked. I believe the only option we have here is to just deal leave it there, or hide it with CSS.

**Comment by jeffreywilcox** [comment]
Right, I understand now. I guess my suggestion here is if the "keep sidebar open" option is enabled then the floating menu should be hidden.

**Comment by meow81** [comment]
Hey, I opened this issue #2942 a little while ago and was kind of shut down.  Glad to see you didn't receive the same response I did.  It's a usability issue introduced by a previous feature request. I really wanted to keep the menu always displayed or pinned to the left, but not if the duplicate menu on the page is also displayed.
