### ISSUE TITLE
Voice recognition not working even with custom api key

### ISSUE THREAD

**Issue by nicusorflorin** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2987]
**OS:** Windows 10 x64

**Issue Descriptions:** I set a custom google api key, with speech recognition api enabled, and the voice controls still do not work at all. No error is thrown in the console, no response, nothing at all. Microphone work fine with any other app. No clue where to start debugging this issue myself.

**Steps to Reproduce:**

1. Set custom api key to electron
2. Enable voice controls
3. Try to issue any command
4. Nothing happens

**Comment by jostrander** [comment]
It was unnecessary to open a new issue and close the old one. Are you building the application from git? I believe the voice API key is "baked in" at build time. So you would have to be building from source to change it currently.

**Comment by MarshallOfSound** [comment]
> Set custom api key to electron

This is harder than you think especially with our building tooling, we bake environment variables in during the JS compilation stage

I personally don't consider this a bug (it's not intended behavior to allow people to customize this key) and while I'd accept PR's to implement this as an option, I wouldn't want it on the backlog as it's not something I'll ever get around to addressing.

**Comment by nicusorflorin** [comment]
@jostrander @MarshallOfSound yes I am building the project myself, I set a Logger event to check that my key is being used too

**Comment by Rone777** [comment]
> @jostrander @MarshallOfSound yes I am building the project myself, I set a Logger event to check that my key is being used too, also the bug isn't that the custom key is not working, but it seems the feature itself to not be working at all. Also as far as i can see it uses the Web Speech Api which doesn't require an Api Key as far as i know, and not the Google Speech Api. Am I Wrong? Please elaborate

Have you been able to figure this out? or is it a dud?
