### ISSUE TITLE
OS X: Media keys stop working after sleeping and resuming

### ISSUE THREAD

**Issue by udeyrishi** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#299]
Repro steps:

1. Play something, and then pause it
2. Put your Mac to sleep
3. Turn it on again
=> The play/pause, next, and previous keys will stop working with the app at this point.

Killing and restarting the app fixes the issue.

**Comment by MarshallOfSound** [comment]
Can't replicate this issue.  Please provide a screencast or something of it happening

**Comment by udeyrishi** [comment]
Neither can I. I think it was some random fluke.
