### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by sbelongie** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2990]
OS: Windows 10

Issue Descriptions: High CPU when playing music

After the latest upgrade there is very high CPU usage.  Not sure why.

![2018-02-07_11-09-57](https://user-images.githubusercontent.com/11724299/35930449-8c305da8-0bf7-11e8-9fb0-da30351caefb.png)

**Comment by sbelongie** [comment]
I think this issue can be merged with issue #2969 seems to be related. I turned off the discord integration and the issue went away.

**Comment by jostrander** [comment]
Agreed. More than likely this is the issue you're after. 

Duplicate #2969.
