### ISSUE TITLE
Some of the voice commands do not work

### ISSUE THREAD

**Issue by nicusorflorin** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2995]
**OS:** Windows 10

**Issue Descriptions:** Some voice controls commands do not work: Play Playlist, Play Artist, Previous (next works) and all volume Commands

**Steps to Reproduce:**

0. Clone Master Branch of the Project
1. Set custom api key
2. Build app
3. Run
4. Enable voice commands
5. Try to use any of the commands in the issue description
6. They Do not work

**Comment by MarshallOfSound** [comment]
Voice controls are severely rate limited, if you want to make sure yours work you'll have to launch GPMDP with a custom GOOGLE_API_KEY.  I don't have the resources to provide a key for unlimited API access.
