### ISSUE TITLE
Feature request: show player after clicking Help->About in tray icon menu 

### ISSUE THREAD

**Issue by ogroleg** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2998]
**OS:** 
MacOS High Sierra

**Issue Descriptions:** 
When I click tray icon -> Help -> About player doesn't show 

**Steps to Reproduce:**
1. Minimize player
2. Click tray icon
3. Help -> About
4. Player doesn't show

**Comment by donth77** [comment]
[https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/pull/3003](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/pull/3003)
