### ISSUE TITLE
Feature Request: last.fm Support

### ISSUE THREAD

**Issue by MarshallOfSound** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3]
A commonly requested feature is last.fm support.
Scrobbling current playing tracks

**Comment by MarshallOfSound** [comment]
Currently blocked by the state of the last.fm api.  API key sign up is disabled / unavailible due to a bug with the last.fm site.  Waiting for fix

**Comment by MarshallOfSound** [comment]
Closing until last.fm sort their stuff out...
:cry:

**Comment by MarshallOfSound** [comment]
As an update to everyone, last.fm recently reopened their API sign up so I know have access to their API.  I will start work on getting this integrated soon :)

**Comment by VladimirAmiorkov** [comment]
Adding my Last.fm information leads to "Login Failed" message. Am I missing something here.

**Comment by MarshallOfSound** [comment]
@VladimirAmiorkov Yes :cactus: 

I'm assuming here you pulled the repo and tried to build it yourself.  If you look at [these lines](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/Google%20Play%20Music/LastFM.Intergration.cs#L20-L21) you should see the both the `API_KEY` and `API_SECRET` are empty.  
This is because it is bad practice to push keys and secrets to a repo, mine are secret on my machine and will stay that way :smile:   
If you want it working on your machine, sign up for a API account on last.fm and use that key and secret during development

**Comment by VladimirAmiorkov** [comment]
Ohh ofc :). I guess it is way to early and I am way too sleepy. Thank you for the comment.

**Comment by MarshallOfSound** [comment]
No problem, I think I should document that somewhere, or perhaps make the build fail if they aren't present.  But that's an issue for another time :P
