### ISSUE TITLE
Needs flash update, but download cannot be accessed

### ISSUE THREAD

**Issue by retorquere** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#30]
When it starts up it says it wants a flash update, allows me to download it, but then I can't start it

**Comment by MarshallOfSound** [comment]
This is due to the sandboxes nature of the embedded player.  If you checkout the README of this repo you would see a link to download flash from here http://get.adobe.com/flashplayer/

**Comment by retorquere** [comment]
Sorry about that.
