### ISSUE TITLE
OSX: options to gray out and disable menubar icon

### ISSUE THREAD

**Issue by huyz** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#300]
The menubar icon for the player is the only one of mine that has color.  The OSX standard these days is grayscale.  Please provide a grayscale icon or an option to gray it out.
And also please provide an option to remove the menubar icon altogether.

**Comment by MarshallOfSound** [comment]
The icon is now greyscale, PR to fix that was merged yesterday.

And as mentioned in other places the menubar is a core piece of functionality and removing it would make convuluted logic for the benefit of not very many users

**Comment by huyl** [comment]
Hmmm, iTunes doesn't have a menubar icon.  How is that convoluted?

**Comment by huyz** [comment]
Hmmm, iTunes doesn't have a menubar icon. How is that convoluted?

**Comment by MarshallOfSound** [comment]
iTunes isn't this program, lots of functionality is very closely tied to the tray icon / menu.

**Comment by huyz** [comment]
Cool, thanks for letting me know I should go back to Radiant Player

**Comment by MarshallOfSound** [comment]
You're welome... :cactus: 

@chrismou You can have him

**Comment by huyz** [comment]
Love the maturity haha

**Comment by MarshallOfSound** [comment]
That maturity comment is beyond ironic....  I think I need to start adding community guidelines to this repository.

I think you don't understand @huyz this is not a business, I honstely don't care whether people use the program or not.  If you do **great** if you don't **woop woop**.  The app is here for the community, not individuals who want specific things and expect the maintainer/s to jump and perform....

**Comment by huyz** [comment]
You're stating the obvious.  Open source wasn't invented yesterday.

Answering with "iTunes isn't this program" is just unnecessary.  I'll give you a few years to mature and figure it out.  Cheers, good luck.

**Comment by MarshallOfSound** [comment]
You used a program as an example which is almost certainly written in a different language, on a different framework, with different goals...

This conversation is going nowhere, you seem to be under the impression my age affects my abilitiy / understanding of what you are saying....

Have fun with radiant...
