### ISSUE TITLE
Feature Request: Choose what text is displayed on discord

### ISSUE THREAD

**Issue by Onyxx666** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3000]
Hey!,

So thanks for adding this support as I saw Spotify and I and was jelly to see it come for GPMDP.

I was wondering if there was a way to edit what is shown in the text? I feel like showing the info like:
song 
artist
album 

Also any way you could show album artwork instead of the GPMDP logo by chance? 

Thanks ^.^!

**Comment by chinmaya1011** [comment]
Discord devs have to allow the developers of the app to do special things like the album art feature that Spotify has

**Comment by ruscur** [comment]
duplicate of #2975

**Comment by MarshallOfSound** [comment]
#2975
