### ISSUE TITLE
Position of off-screen window cannot be changed on Windows

### ISSUE THREAD

**Issue by caseif** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3002]
It's currently impossible to manipulate the Google Play window if it's off-screen, for instance if it's positioned on a monitor which is later disconnected. I've tried the following options:

- Shift+right-clicking the taskbar icon to select the move option (context menu doesn't open)
- Alt+space while focused on the window (the window doesn't respond to arrow keys after selecting the move option)
- "Cascade windows," "Show windows stacked," "Show windows side-by-side"

The interim solution is to delete the "position" key in .settings.json; however, this is far from ideal. I'm not sure if the root issue is something to do with Electron, but a possible workaround could be to simply detect when the window is off-screen. I'd be happy to create a PR for this if you find it to be an acceptable solution.

**Comment by jostrander** [comment]
This should already be working. Maybe you can take a look at the existing code and see if it has a bug. 

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/60649402bd2ee91e3766c31530df3e0051e9f2b5/src/index.js#L115

**Comment by caseif** [comment]
Thanks, didn't realize that was implemented. Correct me if I'm mistaken here, but I believe that if the window were positioned at x=1920 on a 1080p display, it would be technically be off-screen and thus inaccessible, but the referenced function would still return true.
