### ISSUE TITLE
4.5.0 mini-player expands by itself on 1920x1080 resolution

### ISSUE THREAD

**Issue by inkbot05** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3004]
**OS:**
Windows 10x64 version 1709 build 16299.192

**Issue Descriptions:**
I have a 3 monitor setup with my 2 main monitors connected via display port running at 1920x1200 and a tv connected by vga running at 1920x1080. When moving the mini-player to my 1920x1080 monitor it starts increasing in size.  I let it go and it started to cross over my other monitors.  This started happening when I updated to 4.5.0. I have restarted my computer and still occurs. It works fine on my 1920x1200 monitor.

**Steps to Reproduce:**
Open or move mini-player to a 1920x1080 resolution tv running over VGA.

**Comment by jostrander** [comment]
System borders or themed borders enabled?

**Comment by inkbot05** [comment]
I am using system boarders.  I turned them off and even changed the theme with the same result.

**Comment by inkbot05** [comment]
Well, I turned system boards back on and now it shrinks until it is at it's smallest size.

**Comment by MarshallOfSound** [comment]
Duplicate https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/2269
