### ISSUE TITLE
BootTime

### ISSUE THREAD

**Issue by raphael22** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3005]
Hi there Marshall.

Time to Boot went from about the same as the web version(2-3sec) to 20-30sec.
Didn't have this issue before christmas.
I checked for a similar one but can't find it so maybe it's just me ? (although i reinstall it)

Thanks.

**Comment by MarshallOfSound** [comment]
@raphael22 No update was released over that time, the only explanation is something changing on your machine.  Maybe a new anti-virus update or something 🤔
