### ISSUE TITLE
Apple earphones music control does not work in OS X

### ISSUE THREAD

**Issue by Sviests** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3006]
**OS:**
OS X High Sierra 10.13.3

**Issue Descriptions:**
When trying to pause a song using the apple earphones remote control, the song stops for a second but resumes automatically.

**Comment by ctrlrsf** [comment]
Also seeing this with the Apple 3.5 mm EarPods. 4.5.0 on OSX 10.13.3. I normally use Beats X (bluetooth) and doesn't have this problem. Pause, play, skip song all work as expected.

**Comment by MarshallOfSound** [comment]
Welcome to apple, where some bluetooth headsets don't emit correct media events at the OS level.  Had this before and there isn't much we can do about it on our end.

There are some bits of software that allow you to remap keys on headsets though so maybe you can give those a go 😄
