### ISSUE TITLE
Unstable since last patch

### ISSUE THREAD

**Issue by raphael22** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3008]
Second freeze in a row since new update :(

<img width="1420" alt="capture_play" src="https://user-images.githubusercontent.com/3912356/36166511-09d31ed0-10f3-11e8-87c4-33fca37320b9.PNG">

**Comment by jostrander** [comment]
Discord rich presence enabled?

**Comment by raphael22** [comment]
No, launch a playlist and click on artist name then freeze but music was still on.
Like if UI process was stuck by some process ?

**Comment by cryolithic** [comment]
I'm also running into stability issues. The UI will get stuck in loading sequence. The app will still respond to play pause hot keys, and it will update the playing track in the background, but the spinner stays forever and you can't interact with the app in any other way.
No discord RP enabled.

**Comment by MarshallOfSound** [comment]
Afaik we changed nothing that could have caused this (all code changes were main process facing, nothing touched the renderer).  Seems like coincidence rather than cause, if I had to guess your network is hanging up requests randomly so your UI enters a bad stare 🤔
