### ISSUE TITLE
Blank white screen when opening it.

### ISSUE THREAD

**Issue by gabagl** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3009]
OS: Windows 10

Issue Descriptions: When I open it, the window is blank (white with a lovely orange border). This happened as part of the recent update. As soon as the updated player opened itself when done updating, it was blank. The changelog was there, just not anything else.

Steps to Reproduce: Update to latest version from previous version. Click on Google Play Music Desktop player shortcut in my start menu.

**Comment by jostrander** [comment]
Can you try removing your settings temporarily by renaming them? `%appdata%\Google Play Music Desktop Player\json_store\.settings.json` rename to `.settings.old.json` and open the player and see if it's fixed.

**Comment by curtisgibby** [comment]
I'm having the same issue on Linux Mint 18. Renaming the file `/home/[username]/.config/Google Play Music Desktop Player/json_store/.settings.json` doesn't appear to change anything.

**Comment by jostrander** [comment]
White screen on linux may be a GPU issue. Have you tried launching with `--disable-gpu`?

**Comment by curtisgibby** [comment]
`--disable-gpu` loads with the blank white screen as well.

**Comment by jostrander** [comment]
Any console errors? Does `ctrl` + `shift` + `g` show a location dialog?

**Comment by curtisgibby** [comment]
> Any console errors? 

How do I open the console? `F12` and `ctrl+shift+i` don't seem to do anything in this case.

> Does ctrl + shift + g show a location dialog?

Yes. `ctrl+shift+l` also opens the lyrics screen with the error message "No song is currently playing"

**Comment by MarshallOfSound** [comment]
> How do I open the console?

Control + Shift + G

Type in `DEV_MODE` and click Go

Then the standard console shortcuts from chrome should work 👍

**Comment by jacobsturm** [comment]
Adding in that I just did a fresh install of v4.5.0 on Win10 and have run into the same issue so it's not necessarily an update issue.
Tried removing the settings file as suggested above with no improvement.

**Comment by curtisgibby** [comment]
Interestingly, I no longer see the blank white screen. As such, I won't be able to help with continued console debugging. I don't think that I downloaded a new version or anything, so I'm puzzled as to why it would suddenly start working.

**Comment by jacobsturm** [comment]
As soon as I typed at that I restarted my computer and it seems to have fixed the issue.
(Should have tried that before anything else.)

**Comment by MarshallOfSound** [comment]
Sounds like everyone is fixed

**Comment by mar-bre** [comment]
Having the same problem, and it turned out to be a certificate error.
We have an inline web-filter that does SSL inspection.  This requires us to have a trusted root certificate for our organization.  Mine had gone walkabout, which quickly became evident when opening chrome, but GPMDP didn't show anything.  Resolving my cert issue, fixed the problem.
