### ISSUE TITLE
Snap: Media keys doesn't work

### ISSUE THREAD

**Issue by datzuma** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3011]
OS: Ubuntu 17.10
Snapd: 2.30
GPMDP: 4.5.0

Media keys doesn't work (Logitech G610) when installed from a snap package, deb works fine.

1) sudo snap install g-p-m-d-p --edge
2) Open it
3) Play a song
4) Press pause 
5) song stops playing
6) press play
7)nothing happens when it should continue playing the song

**Comment by jostrander** [comment]
I wasn't aware 4.5.0 was available via snap yet. @RAOF did this get fixed? The only thing I can think of is that node-dbus built in the deb package and not in the snap package.

**Comment by datzuma** [comment]
Oh, my bad, I accidentally (ehh) installed it from edge -channel. Stable (4.4.1) works without a problem.

**Comment by RAOF** [comment]
Yup! This is issue #2993
