### ISSUE TITLE
Next/Previous Media Keys causing double-skipping

### ISSUE THREAD

**Issue by smokelore** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3014]
**OS:**
Windows 10
GPMDP v4.5.0
Corsair K70 LUX

**Issue Descriptions:**
I've gone through Closed Issues and seen that there was a fix for this problem in v4.1.2, but I'm experiencing this issue again in v4.5.0. At first, all of my media keys were sending twice, but I removed the Google Play Music chrome extension/app and that fixed the Play/Pause button, which no longer skips. My Next/Previous buttons, however, are still sending duplicate signals to GPMDP. 

**Steps to Reproduce:**
Behavior is very consistent; can't find a situation in which this issue does not occur.

Thanks y'all. Love this app. <3

**Comment by jostrander** [comment]
Does your Corsair keyboard have software that also sends key presses? Logitech has software that also causes double button presses.

**Comment by smokelore** [comment]
@jostrander Good question! Just double-checked and I don't have any such software installed.

**Comment by adrianjord** [comment]
I am still getting this issue as well on Windows 10, GPMDP v4.5.0 on a Vortex Race3
If I turn off Enable the Windows 10 System Media Service I no longer have this issue, but then I cannot play/pause or skip forward/backwards from other desktops on Windows 10 when using multiple desktops even when the program is in the system tray.

**Comment by trailblazer15** [comment]
I also am experiencing the double skips when I have the Windows 10 System Media Service enabled.  I have a Logitech G910 and do have the logitech gaming software installed but there is no way to control what it does with the media buttons.  It also doesn't make a difference if the gaming software is closed or not, it still double skips regardless.  I think there is something up with the Windows 10 System Media Service option in the Desktop Player app.

**Comment by MarshallOfSound** [comment]
Merging into https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/2364
