### ISSUE TITLE
UI elements do not fit in vertical screen.

### ISSUE THREAD

**Issue by xnick** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3015]
**OS:** Arch Linux, 
gpmdp-git 4.4.0.71.g125c233-1
**Issue Descriptions:** UI elements do not fit in vertical screen

**Steps to Reproduce:** Have a vertical screen @ 1050x1680 (I guess it would be fine at res higher than 1080p)

I know it's a very circumstantial problem,but it's bugging the hell out of me. The gist of it is that the thumbs up/down and triple dot menu icons are hiding the album field when I hover over the playbar. 
![gpmdp](https://user-images.githubusercontent.com/4283706/36301223-bd90a576-130c-11e8-8ac9-8456c926c08e.jpg)

The effect is less pronounced in the official webclient, but it's still there. 
![official](https://user-images.githubusercontent.com/4283706/36301016-1c735314-130c-11e8-8a63-95ff7a0c82ac.jpg)

I wouldn't really care, but this often stops me from being able to click on the album field (when the artist field is a bit longer). I can still get there through the queue, so it's not the end of the world. But it'd be nice to have.

Thanks!

**Comment by BrianAllred** [comment]
Can you verify this a problem in the latest version (4.5.0+)?

**Comment by xnick** [comment]
Confirmed in `gpmdp-git 4.5.0.3.gdf1c3cb-1`

**Comment by BrianAllred** [comment]
Alright, just checking.

**Comment by jostrander** [comment]
I don't really see the issue? Are you saying that smaller windows result in the info being covered up?

**Comment by xnick** [comment]
Idle:
![selection_005](https://user-images.githubusercontent.com/4283706/36318573-e639b2b0-1348-11e8-80eb-3b49390f5e38.jpg)

Mouse pointer anywhere on the bar:
![menu_006](https://user-images.githubusercontent.com/4283706/36318589-f53fb98a-1348-11e8-8535-52bc21c495a3.jpg)

In this case, the album's name is completely hidden, thus unclickable.
Maybe it could wrap below the artist name in this case?

**Comment by jostrander** [comment]
I think I have a solution via CSS, but it definitely needs some tweaks to work with the dark theme.
```
.now-playing-info-content:hover {
    z-index: 99999;
    width: 70%;
    position: absolute;
    background: white;
}```

**Comment by jostrander** [comment]
Give the above file a shot in the custom gpm styles, I just tested it and it works well for me.

**Comment by xnick** [comment]
Yup, works great! Thanks a lot!
