### ISSUE TITLE
App super slow after system standby

### ISSUE THREAD

**Issue by Stanzilla** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3016]
**OS:** Windows 10 1709

**Issue Descriptions:**
After resuming my PC from standby, the app is super slow/sluggish and you can barely do anything in it.
**Steps to Reproduce:**
I am not really sure what else is required apart from having the app open/a song on pause and putting you PC into standby and then resuming it. Today the PC was in standby for ~8h.

**Comment by jostrander** [comment]
Discord rich presence enabled?

**Comment by Stanzilla** [comment]
not currently but it might have been enabled but then disabled for a brief time during that session where I had the huge lags after standby.

**Comment by MarshallOfSound** [comment]
> Discord rich presence enabled?

This was probably it, just having it enabled for a short amount of time currently causes a massive memory leak.  Will work on a new release this weekend or next 😄
