### ISSUE TITLE
Player stops sending track position information when minimized

### ISSUE THREAD

**Issue by doyle524** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3018]
**OS:** Windows 10 1703

**Issue Descriptions:** When the player is minimized (both to tray and just to taskbar) it stops sending track position (elapsed time) through the WebSocket API. When the player is brought back to the screen, the position updates as normal, and it updates properly from a second virtual desktop as well.

**Steps to Reproduce:** Use a program that hooks into the WebSocket API, play a track, and minimize the player. The track position fails to update until the player is brought back to the window.

**Comment by jostrander** [comment]
GPMDP Version?

**Comment by doyle524** [comment]
4.5.0

**Comment by MZimmermann** [comment]
Same issue as in #2630. Applies to json-api as well.

**Comment by doyle524** [comment]
So it is (my fault, I should have been more thorough in my search), but it seems that issue was fixed, then resurfaced but was not reopened.

**Comment by PazerOP** [comment]
Potentially related, the track position indicator also does not update when the player is minimized.
![](https://puu.sh/zvGdP/c074980d87.png)

**Comment by jostrander** [comment]
Correct. The way we are getting the track position is through the gmusic.js API. That fetches the position from the track indicator on the page. That indicator updates through `requestAnimationFrame`. If anyone is familiar with web development you'll know that when the window isn't in view `requestAnimationFrame` stops firing to save CPU consumption. Unfortunately this is the most accurate point of getting that data currently, and until we can find an alternative solution there's not much we can do. This also effects anything that uses the time, including but not limited to the web socket API, the JSON api, the taskbar progress, and last.fm.

**Comment by PazerOP** [comment]
Is it not possible to get whatever value the page's track position indicator is pulling from directly?

**Comment by jostrander** [comment]
Unfortunately it's not easy. The audio elements on the page are streams so the time data is reset every time you seek and doesn't reset when switching tracks normally. There are also 3-4 audio elements the music switches between so you would have to keep track of which ones current. As far as peeking into the Javascript on the page that hasn't been too successful either for me anyway. I've done a lot of debugging and breakpoints and I understand some of the minified code but I cant make out where the current play data is stored.

**Comment by MZimmermann** [comment]
I made a suggestion for a dirty workaround last year in [this comment](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/2728#issuecomment-325453702).

It involves keeping tabs of the "current track progress" (which is actually accurate when interpreted as a "total playtime" rather than "current track progress") and deriving the actual current track time by subtracting the reported progress at the time of trackchange.
It's hacky, but since the current solutions are both broken (indefinitely climbing progress or no progress-change at all when minimized), I thought I bring it up again.

**Comment by SicariusNoctis** [comment]
Same with D-Bus.

```
qdbus org.mpris.MediaPlayer2.google-play-music-desktop-player \
      /org/mpris/MediaPlayer2 \
      org.mpris.MediaPlayer2.Player.Position
```

**Comment by MarshallOfSound** [comment]
Gonna lock this issue, a fix is in PR and endless "me too" comments don't add anything helpful to the discussion 😄

**Comment by jostrander** [comment]
Yes, anything based on playback time is broken pending a merge of a fix thanks to @marshallofsound. Please no one else chime in with "me too", we're aware. Patience. For those looking to track progress, see #3023.
