### ISSUE TITLE
Stuck in mini view

### ISSUE THREAD

**Issue by don-dev** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3020]
I am on kali linux, downloaded the latest. It was working fine until I tried out the mini player. The styles inside the container adjusted but the frame stuck. I am now in a state where, a refresh, toggling the states, and a complete uninstall and reinstall... the problem has stuck. See Attached

ctrl + r or refresh should refresh the styles for the container.
![screenshot from screencast_02-20-2018_06 58 05 pm webm](https://user-images.githubusercontent.com/6163393/36456002-be2ab000-1670-11e8-94ed-6c10117fa819.png)

**Comment by MarshallOfSound** [comment]
`Control + 0` should reset the zoom, otherwise delete the `settings.json` file in your appData directory (not sure where this is on your system) and everything should reset 👍
