### ISSUE TITLE
Implement Hotkey for lyrics

### ISSUE THREAD

**Issue by TSimkus** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3021]
Hey,

I feel like hotkey for lyrics would be nice, expecialy when you have dual monitors you cna do your work at one, and have lyrics on the other monitor. 

**OS:**

**Issue Descriptions:**

**Steps to Reproduce:**

**Comment by jostrander** [comment]
ctrl+shift+L?

**Comment by MarshallOfSound** [comment]
^^
