### ISSUE TITLE
Feature request: lyrics on mini-window.

### ISSUE THREAD

**Issue by phiterf** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3022]
It would be nice to have lyrics on the mini window. It would be even nicer if the lyrics would sync.

I used the musixmatch app on windows 10 to see Spotify lyrics, but it doesn't recognize GPMDP.

I saw that they even have an API, so maybe it could be used as well:

https://developer.musixmatch.com/

Thank you!

**Comment by phiterf** [comment]
Just noticed the musixmatch API is paid so forget about that one.

**Comment by MarshallOfSound** [comment]
The mini window is barely big enough IMO to fit the controls + album art let alone readable scrolling lyrics.  If you want to pull the lyrics into a different window we have an API for that or you can stay tuned on the plugin support issue 👍

**Comment by JustACuteGirlLookingForAManToFixHerBugs** [comment]
I have an objection, Your Honor!

The mini window's size is adjustable (and it's awesome), so if we place the lyrics inside the mini window, we'd have it alongside with controls.
