### ISSUE TITLE
Mini player's scroll wheel volume adjustment does not work when player controls are hidden

### ISSUE THREAD

**Issue by tromero** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3025]
**OS:**
Windows 10

**GPMDP Version:**
4.5.0?

**Issue Descriptions:**
The mini player's scroll wheel volume adjustment only works when player controls are visible, such as when mousing over the bottom 1/3 of the window, or enabling "always show song information"

**Steps to Reproduce:**
- Uncheck "always show song information"
- Mouse over the top 2/3 of the mini player and scroll. Nothing happens.
- Mouse over the bottom 1/3 of the mini player so the controls appear. Scrolling adjusts the volume as expected.

I expected mousing over any part of the window and scrolling to adjust the volume.

**Comment by MarshallOfSound** [comment]
> I expected mousing over any part of the window and scrolling to adjust the volume.

This change was made to stop users accidentally scrolling their volume up and demolishing their ear drums.  I prefer playing it safe and only allowing scrolling on certain parts of the UI that make sense instead of everywhere 👍
