### ISSUE TITLE
List of Albums do not match what is displayed in Web interface

### ISSUE THREAD

**Issue by ehlkej** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3027]
**OS:**
Mac OS 10.11.6

**GPMDP Version:**
4.5.0 (4.5.0)

**Issue Descriptions:**
An album ("Gates of Hell" by Sam Coffey and The Iron lungs) is appearing in my library. Any attempts to play or delete the album or any song in it result in an error message. I think this album used to be available on Google Play but might have been removed at some point. 

This album does *not* appear when I log in directly to Google Play Music via Chrome.

Similarly (but opposite situation) is that Babel (Deluxe version) by Mumford and Sons appears in the web interface, but does not appear in the app.

**Steps to Reproduce:**
Unsure. It just sort of ended up this way.

The album still appears after fully uninstalling, then reinstalling the app.

**Comment by ehlkej** [comment]
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/1764233/debug_info.zip)

**Comment by ehlkej** [comment]
![App screen shot 2018-02-27 at 10 30 38 am](https://user-images.githubusercontent.com/8039139/36747719-9be45066-1baa-11e8-80d5-220b687ff903.png)

![Web interface in Chrome screen shot 2018-02-27 at 10 30 35 am](https://user-images.githubusercontent.com/8039139/36747738-a5d86422-1baa-11e8-80d5-627af0c82655.png)

Both are image from the "Albums" tab.

**Comment by ehlkej** [comment]
What happens when trying to remove album

![screen shot 2018-02-27 at 10 41 27 am](https://user-images.githubusercontent.com/8039139/36747796-cf5b19ac-1baa-11e8-8d79-235ea0a973cb.png)

![screen shot 2018-02-27 at 10 41 22 am](https://user-images.githubusercontent.com/8039139/36747803-d1692a90-1baa-11e8-8739-0fd63c447450.png)

**Comment by MarshallOfSound** [comment]
I don't know how this is possible, we literally just portal you into the web interface.  Sounds like a caching / storage issue on Google's side

**Comment by ehlkej** [comment]
I regret donating money. You didn't even bother looking into it and I
literally sent you proof that it's happening.

**Comment by MarshallOfSound** [comment]
> You didn't even bother looking into it and I literally sent you proof that it's happening.

Proof that it's happening and it being my fault / something I can fix are two different things, as mentioned we do not adjust, intercept or otherwise modify the way google displays your list of albums.  What albums it shows and how it shows them is entirely googles code and logic, nothing to do with this player.  Therefore any bug in an album appearing when it shouldn't isn't caused by us.

To be clear, **choosing which albums to display is not our code**, this means it can't be our fault when Google displays an album you have deleted.  As mentioned I'm guessing it's a caching issue on Google's side.

**Comment by ehlkej** [comment]
A reasonable developer would was interested in solving problems and who
suspected a caching issue would direct their user to uninstall and
reinstall.

**Comment by ehlkej** [comment]
Choosing which albums to display or not display is literally a choice of
your software based on the parameters you send to their API. Just because
you are unaware of what parameters do what when using their URLs doesn't
mean it's not related to your software.

**Comment by MarshallOfSound** [comment]
> A reasonable developer would was interested in solving problems and who
suspected a caching issue would direct their user to uninstall and
reinstall.

But... A developer who understands their software would no that on the reported OS (macOS) there is no concept of uninstall / reinstall. The cache files are stored on in the users `~/Library` folder and are not affected by deleting the application that created them.

> Choosing which albums to display or not display is literally a choice of
your software based on the parameters you send to their API. 

Uh, what... We don't use **ANY** google play music API.  Let me quickly explain how GPMDP works 😄 

* We open a window pointing at `play.google.com/music/listen`
* We inject a bunch of JS and CSS to hooks events and change UI (theming)
* We run some native code that hooks into that JS (for things like media service integration)

At no point do we display the albums, or play music or access your account or list your songs or provide and additional player UX.

Regardless of all of the above, I'm just going to refer you to the [CONTRIBUTING](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/CONTRIBUTING.md) guidelines of this repository.

Please note that this isn't "my" software, this is an open source project whose code and output is provided AS-IS, without any guarantee of support, service or help.  I maintain this project (amongst countless others) in my free time in addition to working a full-time job and have done for the last 2 years.

**Comment by ehlkej** [comment]
Great. Thanks for figuring out that it was a problem with a cache folder
the Application created as part of install and not a Google side caching
problem as you earlier stated.

Next time you could provide users with helpful tips to troubleshoot instead
of closing tickets with no apparent investigation.


On Mar 4, 2018 2:31 AM, "Samuel Attard" <notifications@github.com> wrote:

A reasonable developer would was interested in solving problems and who
suspected a caching issue would direct their user to uninstall and
reinstall.

But... A developer who understands their software would no that on the
reported OS (macOS) there is no concept of uninstall / reinstall. The cache
files are stored on in the users ~/Library folder and are not affected by
deleting the application that created them.

Choosing which albums to display or not display is literally a choice of
your software based on the parameters you send to their API.

Uh, what... We don't use *ANY* google play music API. Let me quickly
explain how GPMDP works 😄

   - We open a window pointing at play.google.com/music/listen
   - We inject a bunch of JS and CSS to hooks events and change UI (theming)
   - We run some native code that hooks into that JS (for things like media
   service integration)

At no point do we display the albums, or play music or access your account
or list your songs or provide and additional player UX.

Regardless of all of the above, I'm just going to refer you to the
CONTRIBUTING
<https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/CONTRIBUTING.md>
guidelines of this repository.

Please note that this isn't "my" software, this is an open source project
whose code and output is provided AS-IS, without any guarantee of support,
service or help. I maintain this project (amongst countless others) in my
free time in addition to working a full-time job and have done for the last
2 years.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3027#issuecomment-370218338>,
or mute the thread

**Comment by MarshallOfSound** [comment]
I warned you before, if you aren't going to be polite and respectful in the issue tracker you aren't welcome in this repository.  As mentioned previously I think you should rethink your interactions with open source maintainers.
