### ISSUE TITLE
GPMDP depends on wget but doesn't specify it as a dependancy

### ISSUE THREAD

**Issue by arilotter** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3028]
**OS:** Arch Linux

**GPMDP Version:** 4.5.0-1

**Issue Descriptions:** GPMDP doesn't launch if wget isn't installed on the system

**Steps to Reproduce:** Remove wget, launch gpmdp

**Fix:** Install wget

**Comment by BrianAllred** [comment]
Good catch. Fixed in 4.5.0-2.
