### ISSUE TITLE
OS X: Hotkeys can't be set

### ISSUE THREAD

**Issue by udeyrishi** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#303]
Repress steps:

1. Go to settings -> "Hotkeys" tab.
2. Try setting any of the hotkeys, it won't work
3. Try resetting by hitting Esc as instructed, and try (2) again; still won't work.

**Comment by MarshallOfSound** [comment]
Try setting it to something like "Ctrl + Shift + P"

**Comment by udeyrishi** [comment]
Hmm, that works. Is their a restriction on these starting with Ctrl?

**Comment by MarshallOfSound** [comment]
I think so yes, I don't think I though about OSX when I wrote the shortcut parser.

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/inject/settings/hotkeys.js#L3

Looks like all we need to do is add the "Command" key to that list

**Comment by MarshallOfSound** [comment]
For reference it looks like we need to use keys 91 and 93

http://stackoverflow.com/questions/3902635/how-does-one-capture-a-macs-command-key-via-javascript

**Comment by udeyrishi** [comment]
I didn't look into it in more detail, but just making this change doesn't work:

```js
const ACCELERATOR_KEYS = {
  17: 'Ctrl',
  91: 'Cmd',
  93: 'Cmd'
};
```

**Comment by MarshallOfSound** [comment]
I'll look into it when I get back, those numbers may be wrong :/

**Comment by hashworks** [comment]
Also some key's aren't working, f.e. the german umlaut key `Ü`.

**Comment by baseballbrad3** [comment]
Looks like the number row and number pad aren't working either (although I believe there's something specific to Electron that prevents the number pad from working).

**Comment by MightyPork** [comment]
I've noticed this as well, in particular that F# keys don't work, which is what I used to have as media keys. But that may be an Electron restriction.

**Comment by MarshallOfSound** [comment]
Closing this in favor of #413
