### ISSUE TITLE
Feature Request: Adjust zoom level

### ISSUE THREAD

**Issue by HumboShot** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3030]
Hey

It would be cool if you could adjust your zoom level. Personally i think the default zoom level is too big, so i like to have mine on 90% scale. Would this be possible to implement?

Examples
[90% Zoom level](https://i.imgur.com/Hnd6Uk5.png)
[100% Zoom level](https://i.imgur.com/kkE4Eej.png)

**Comment by MarshallOfSound** [comment]
Standard zoom shortcuts work 😄

**Comment by HumboShot** [comment]
@MarshallOfSound I have now tried on two Windows PC's and one Mac, and i really can't get any zoom. I have tried CTRL++, CTRL+- and CTRL + Scrollwheel. None of those worked
