### ISSUE TITLE
GPMDP Continued Disk Usage

### ISSUE THREAD

**Issue by awatson87** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3032]
OS: Windows 10 Version	10.0.16299 Build 16299

GPMDP Version: 4.5.0

Issue Description: 

When accessing GPMDP, I noticed that anytime it was open, it was causing my mouse icon to display the loading wheel repeatedly.  It's been going on for awhile, and I decided to investigate. I traced this to disk usage, and checked Task Manager to find that GPMDP was continuously trying to write to the hard disk:

![image](https://user-images.githubusercontent.com/6669549/36920363-82520c98-1e2e-11e8-8994-5ed1cd9de5d0.png)

I looked in the debug info (generated by the application), and found the following error repeating constantly in my gpmdp.log file:

{"level":"error","message":"################### !! Update server down !! ##################","timestamp":"2018-03-02T19:52:07.663Z"}

I think this is likely the cause of the problem - GPMDP is trying to access a server that's down, or trying to run through a port that's inaccessible through my office network's configuration settings, and the server can't be reached.

However, I'm not sure what it's trying to update - my library currently functions fine (cross-checked adding/removing songs from Library on phone and GPMDP, verified changes reflected on each), and music plays with no issue. I did not check adding/uploading my personal music to My Library, however, as I don't currently have any files onhand.

Would it be possible to a) specify what update server and port this process is trying to access, b) prevent the application from continuously trying to access this update server (maybe limit the number of attempts at one time and/or delay further attempts until a considerable amount of time has passed), and c) maybe pass an error message to the user in addition to logging the details?  

Debug_info: [debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/1776545/debug_info.zip)

Steps to Reproduce:
1. Start the application
2. Observe mouse loading icon appearing and disappearing repeatedly, signifying nonstop disk access
3. Open Task Manager
4. Observe Google Play Desktop Music Player (32 bit) task accessing 0.10 MB/s of of the hard disk
5. Expand Google Play Desktop Music Player (32 bit) task
6. Observe single Google Play Desktop Music Player (32 bit) subtask continuously accessing 0.10 MB/s of of the hard disk

**Comment by MarshallOfSound** [comment]
> - GPMDP is trying to access a server that's down, or trying to run through a port that's inaccessible through my office network's configuration settings, and the server can't be reached.

This is an issue on your network, normally means we can't communicate with our update server `update.gpmdp.xyz`.  I'd recommend getting someone to unblock that 👍 

> When accessing GPMDP, I noticed that anytime it was open, it was causing my mouse icon to display the loading wheel repeatedly.

This is independent of this logging, the update server check is run every 2 minutes and the log file is only written when something is added.  Whatever is causing that spinning it isn't this log file 👍

**Comment by awatson87** [comment]
Hey, thanks for the quick response. 

So if the server issue isn't causing the constant HDD access, then what is? The spinning happens only when GPMDP is running, and the disk access from the subprocess mentioned is still a steady 0.1 MB/s, no matter how long the program is running. I'm assuming these two things are related.

And yeah, working with my office to get the port unblocked. Glad to know that's unrelated, at least. :)

**Comment by MarshallOfSound** [comment]
@awatson87 Turn off the PlaybackAPI maybe?  The JSON file that gets outputted could be the cause

**Comment by awatson87** [comment]
Ok. I'll try that and update, but it'll likely be sometime Monday. Thanks!

**Comment by awatson87** [comment]
Updating:

Disabled PlaybackAPI, restarted the program and then the PC.  If anything, it seems like it's accessing the disk more often than it was before, based on how fast the loading icon pops up and disappears and how often the HDD access light on the PC lights up.

I looked in Performance Monitor while GPMDP was running (no music playing), and found this:

![image](https://user-images.githubusercontent.com/6669549/36990953-3255dc5e-2074-11e8-80bb-4eb371caf98b.png)

The data files in the cache are continuously being written to, even when GPMDP is idling in the background for over 30 minutes.  This ends once I quit the program.  The data_3 file (under System image) in particular stands out, as the write speed never drops below 7 MB/s, but will jump over 10 MB/s 
 with regularity. The other three data files under the system image (data_0, data_1, data_2) do the same, but the speed is much lower - data_0 and data_1 will usually peak at just under 5 MB/s, then slow down.  

data_2 under the System image has way more Read activity than the rest.  It's the only one where the Read speed never drops to zero. Under the GPMDP image, data_2 and data_3 are almost constantly bring written to, with only data_2 dropping its Read speeds to the point where it occasionally disappears from the list.  

For the record, these are the disk writes that specifically list the GPMDP image:

![image](https://user-images.githubusercontent.com/6669549/36991876-12ca688e-2077-11e8-91c9-3f144e7d4c79.png)


I'm not entirely sure how helpful these metrics are to you, but I'm hoping they can provide some insight to this issue.  If there's anything in particular you need me to look at, let me know - otherwise I'm going to keep gathering information when/where I can to pinpoint the exact problem.

**Comment by MarshallOfSound** [comment]
Oh, you, unfortunately, have been the victim of a rather annoying Chrome bug to do with Audio streaming and cache 😄 Seen this before, basically, we need to get to C62 to fix it (off the top of my head).  Electron master is on C62 so a fixed version shouldn't be too far away 🤔

**Comment by MarshallOfSound** [comment]
Just to double verify this theory, if you open GPMDP and don't play any music the write speed should be 0

**Comment by awatson87** [comment]
These are my numbers after:
- Quitting GPMDP and Chrome completely
- Starting GPMDP, without playing any music
- Waiting about 2 minutes

The Write speeds look fairly similar to me, unfortunately; I'll try a full restart, just in case. 

![image](https://user-images.githubusercontent.com/6669549/36992759-f0bb1cea-2079-11e8-85b9-15b391f5d44b.png)

**Comment by awatson87** [comment]
And these are after a restart:

- Quitting GPMDP and Chrome completely
- Shutting down computer (using Start > Power > Shut down)
- Restarting computer
- Starting GPMDP, without playing any music
- Waiting about 2 minutes

Had to block some entries out due to work, but they're 100% unrelated, just FYI.

![image](https://user-images.githubusercontent.com/6669549/36993723-b9009264-207c-11e8-88c9-ac5070e98fd2.png)
