### ISSUE TITLE
Feature Request - Remote control FROM Windows

### ISSUE THREAD

**Issue by superelitist** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3033]
I'd like to run the player on my desktop computer, but control it from my laptop while I'm playing a fullscreen game.

Obviously, there's already an Android and IOS app for this, but there doesn't appear to be one for Windows.

Alternatively, if the player served a web page to control it from another device, this would also be quite adequate.

**Comment by jostrander** [comment]
You can use the websocket API to create this. I don't think any first party support would be coming this way however unless someone else adds it in. If someone wants to tackle this, chime in and I'll open it back up.
