### ISSUE TITLE
Crackling sounds coming out of headphones on windows 10

### ISSUE THREAD

**Issue by wilomgfx** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3035]
**OS:**
Windows 10 build Version	10.0.16299 Build 16299

**GPMDP Version:**
4.5.0
**Issue Descriptions:**
I hear crackling sounds coming out of the audio jack whilst listening to music.
Only happens on my windows 10 devices, macbooks are fine!
**Steps to Reproduce:**
Plug in a pair of headphones, start playing some sweet music and hear the weird crackling sounds. I currently listen trough the web version and i have no weird sound crackles issues :) !

**Comment by tohlenforst** [comment]
I'm having this issue as well. I notice the crackling to a much lesser degree in a chrome tab, but it is still there.

**Comment by wilomgfx** [comment]
@tohlenforst I managed to pretty much fix it with an audio driver, on my xps 13. Haven't tested on my job's xps 15.

**Comment by jostrander** [comment]
It may be an audio driver, it may be the 5.1 experimental audio, there's really no telling. The other alternative is the volume may just be too loud in the player and it's causing distortion/clipping. I know I have this problem with the DTS driver on the laptop I use, but I've tried fixing it to no avail. I just turn the volume down to ~85% in gpm and turn the master volume up in windows.
