### ISSUE TITLE
Cannot set hotkeys on Mac?

### ISSUE THREAD

**Issue by jacobgraf** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3036]
I am trying to set custom hotkeys on Mac. All of the hotkeys say "Not Set", but when I click on it to set it, I press some keys and nothing registers. I've rebooted, tried multiple times, multiple hotkeys, and nothing seems to work. Is there a known issue with setting hotkeys on the Mac version of the app? Thanks!

**Comment by jostrander** [comment]
Keys must contain a modifier key such as `ctrl`. This is an undocumented `feature` to keep people from binding 'space' and not being able to press space for any application except for GPMDP, as these hot keys take over the key binding exclusively.

**Comment by jacobgraf** [comment]
Yes, I get that. Nothing works including using a modifier (e.g. CMD+L or CMD-[)

**Comment by jostrander** [comment]
Hmm, GPMDP version?

**Comment by MarshallOfSound** [comment]
> CMD+L or CMD-[

You have to use `Cntrl`, macOS key listeners do not work super well with the Command key, so even on macOS shortcuts have to currently be bound using control

**Comment by jacobgraf** [comment]
Hmm ok. I’ll give it another shot! Thanks!

**Comment by MaybeGoogle** [comment]
Is a workaround for this possible? I know that some electron apps (e.g. atom) have cmd as a modifier. In addition, is it possible to use a function key? I originally wanted to use the music buttons on the top of my keyboard, but @jostrander 's explanation makes me think that it might not be possible, especially without a modifier key. Even so, ctrl/cmd + play/prev/next would be nice...

**Comment by eugenewrayburn** [comment]
Actually, I had to add a third key to make it work.  Like Ctrl+Shift+Right to make right arrow advance to Next Track. FYI, the setting disappeared after restarting the app.

**Comment by russellrain** [comment]
Also having the same issue where I can only save one binding at a time, have to restart app for each binding (thanks for that workaround eugenewrayburn)
