### ISSUE TITLE
Feature Request: Show songs in library in album view

### ISSUE THREAD

**Issue by gadeweever** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3037]
Hey Everyone,

Not new to GitHub, but new to contributing to open source and Electron. As such I thought I'd start with something I believe to be small.

When looking at an album, can an extra column be added to show songs that are currently in your library? It looks like there is a [PR ](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/2988)out for using the checkmark to show liked vs. disliked songs, so I'd probably go with the same aesthetic.

Why do I want this: So I can very quickly determine what songs I have missing from an album. It'll make it easier to manage my library that way. In the future this could also be extended to quickly remove a song from my library by clicking on the checkmark, but that's not necessary for this to be immediately useful.

![gphotoex](https://user-images.githubusercontent.com/3673488/37190563-625da768-230f-11e8-918b-86cf1d72671f.png)

**Comment by jostrander** [comment]
Unfortunately this isn't possible with our current integrations. There is no way for us to hook into the DOM and add that information as we only have that info on the currently playing track.

**Comment by gadeweever** [comment]
@jostrander I dont think I understand what you mean here. This information is already available in the app and no tracks are playing right now. The attached photo shows the subset of songs in my library, the first photo shows all the songs in the album.  What's the issue here?
![inlib jpg](https://user-images.githubusercontent.com/3673488/37426580-1e9b507e-2784-11e8-8273-e93a47b60021.png)

**Comment by jostrander** [comment]
So what you're seeing there is [Google Music](https://music.google.com) the web player. The GPMDP application is a third party (i.e. not made by Google) application that just wraps around that and has hooks into the web UI provided by Google to add functionality.  We don't have any way of accessing your library in it's entirety in order to add the check boxes to this page you are looking at. That's all done on Google's end.
