### ISSUE TITLE
Helper Using Too Many Resources

### ISSUE THREAD

**Issue by mike3run** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3038]
<img width="800" alt="screen shot 2018-03-09 at 3 38 49 pm" src="https://user-images.githubusercontent.com/7088511/37231339-68b34d4c-23b0-11e8-8cba-70753880a6d8.png">

<img width="995" alt="screen shot 2018-03-09 at 3 42 22 pm" src="https://user-images.githubusercontent.com/7088511/37231351-7a5c0b56-23b0-11e8-83c2-2063c90f64d3.png">

[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/1798534/debug_info.zip)

Lately I've noticed my machine fans running a bit harder than usual and checking the Activity Monitor I can see that the helper is taking almost the same resources as Chrome with many tabs open 🤔 

Next month I'll be replacing the thermal paste to discard that hardware option as well but this seems a bit odd to me so I thought about filing an issue. Seems like it has been asked about in the past but no satisfactory answer was given in there.

Anyways I hope this helps in some way to improve the app and I can provide with more info or help debug further if needed.

Thanks!!

**Comment by jostrander** [comment]
Discord rich presence enabled?

**Comment by fraserhaer** [comment]
Hey @jostrander good tip. It happens when discord is not running and rich presence is enabled. I guess it's polling infinitely or something? RAM usage just continually goes up. You can open discord and CPU usage goes down, RAM stops going up; then close discord and it goes back to high CPU and RAM increasing.

**Comment by mike3run** [comment]
@jostrander discord rich presence is NOT enabled on my machine but the issue still persists :((

**Comment by Kxze** [comment]
Can reproduce this as well. The app uses 100% of my CPU constantly.

**Comment by HNKNTA** [comment]
Can reproduce this too, this app enables coolers on my macbook.

**Comment by Janooba** [comment]
This happens upon startup of the application to me as well. The whole application is very unresponsive as this is happening. If left to run, it seems to resolve itself after 10-20 minutes or so.
Discord Rich Presence is Off.

Running Windows 7 (64bit)
Intel i7-2760QM
8GM RAM

![image](https://user-images.githubusercontent.com/17034238/37912964-f42141cc-30d0-11e8-88cc-1c4db9d13833.png)

**Comment by nezorflame** [comment]
Got the same on macOS 10.13.3.

**Comment by RogueScholar** [comment]
Grieved to say that I'm experiencing this as well on Windows 10 and Kubuntu Bionic Beaver Beta 1. Let me know what I can provide to help the triage of this foul curse.

**Comment by clayton-sayer-hs** [comment]
I am also experiencing this on my Mac on OSX 10.12.6. Discord rich presence is not enabled (don't have Discord). I tried enabling, then disabling Discord rich presence and the CPU usage dropped way down.

**Comment by mike3run** [comment]
@clayton-sayer-hs that worked for me as well also after reboots and so on
