### ISSUE TITLE
New Logo Designed Needed

### ISSUE THREAD

**Issue by MarshallOfSound** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3039]
Hey there folks,

Developments have come up that will require this project to get a new logo, our current logo is [here](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/tree/master/src/assets/icons/svg).

I am a terrible designer 😆 but this needs to get done so I'm raising this here in the hopes that one of you folks who use this app can come up a new logo infinitely better than anything I could come up with.

If anyone has any ideas, just post some rough sketches below or something and we can all get involved in getting a new logo 😀

**Comment by adammcarth** [comment]
Finally got that letter in the mail did we?

**Comment by JayToe** [comment]
I made a quick mockup ![here](https://user-images.githubusercontent.com/37263678/37252223-cefd42d8-251d-11e8-9f8c-4f71955ab009.png). I know it looks very messy but i made it in like 5 mins.

By the way, would it be difficult to add like and dislike buttons to the remote app? I'd really appreciate those

**Comment by MarshallOfSound** [comment]
@JayToe That's pretty sick 👍 💯 Could you perchance spin up a vector (SVG) version of that 😀

**Comment by JayToe** [comment]
@MarshallOfSound Yeah sure, I should have time for that on the weekend

**Comment by JayToe** [comment]
@MarshallOfSound Sent you an email

**Comment by MarshallOfSound** [comment]
A million internet points for @JayToe

**Comment by JayToe** [comment]
░█▀█▀█ █── ▄▀▄ █▄─█ █─▄▀──
──░█── █▀▄ █▀█ █─▀█ █▀▄───
─░▄█▄─ ▀─▀ ▀─▀ ▀──▀ ▀─▀▀──

░▀▄─────▄▀ ▄▀▄ █─█──
──░▀▄─▄▀── █─█ █─█──       ❤️
────░█──── ─▀─ ─▀───

**Comment by Syberiyxx** [comment]
Where can we find more of your designs @JayToe ? quick google didn't provide a twitter with your face

**Comment by JayToe** [comment]
My twitter handle would be @The_JayT
However, I don't use twitter a lot so if you want to add me on Discord you could do that as well because I'm way more active on there: Cloudyhair#5298

Until now I didn't really do a lot of graphic design which you can find on the internet (except for some small projects and school projects) but I'm planning on creating an icon pack for android in the summer because graphic design is really one of my greatest passions.

**Comment by JayToe** [comment]
@Syberiyxx Here's some geofilters for snapchat i made if you're interested: https://imgur.com/a/5p7Rs

**Comment by Stanzilla** [comment]
That looks a bit broken on Windows https://i.imgur.com/X1hEt3p.png
