### ISSUE TITLE
UI freezes on tiling WM

### ISSUE THREAD

**Issue by parkerlreed** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#304]
I see mentions of the next release using native window borders. I'm not sure if this is directly related.

Arch x86_64
https://aur.archlinux.org/packages/google-play-music-desktop-player-git/

Initial "Sign in" loads but stops right after.

https://my.mixtape.moe/qpwoci.mp4

Works in nested openbox. 
![1457322562](https://cloud.githubusercontent.com/assets/841440/13560531/4df89704-e3ee-11e5-9195-e14684d2a5e2.png)

**Comment by MarshallOfSound** [comment]
Try running with the `--disable-gpu` option

**Comment by parkerlreed** [comment]
Aha that worked. My GPU setup is

````
Graphics:  Card: Advanced Micro Devices [AMD/ATI] Bonaire XTX [Radeon R7 260X/360]
           Display Server: X.Org 1.18.1 driver: (unloaded: amdgpu) Resolution: 1920x1080@59.99hz
           GLX Renderer: Gallium 0.4 on AMD BONAIRE (DRM 2.43.0, LLVM 3.9.0)
           GLX Version: 3.0 Mesa 11.3.0-devel (git-1f862e9)
````

**Comment by MarshallOfSound** [comment]
For some reason GPU acceleration is brekaing things on linux.  I should add that to a FAQ somewhere

**Comment by parkerlreed** [comment]
Yeah GPU acceleration in general on Linux is a mess. Thanks for the response and this wonderful application!
