### ISSUE TITLE
Last.fm login failed with 403 (Forbidden)

### ISSUE THREAD

**Issue by spikespaz** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3040]
**OS:** Windows 10 Insiders Preview build 17074 (I think)

**GPMDP Version:** 4.5.0 (Latest as of writing)

**Issue Descriptions:**

![image](https://user-images.githubusercontent.com/12502988/37237236-3d8db968-23ce-11e8-9ba8-5be1f361d595.png)

**Steps to Reproduce:**

Open the "Desktop settings" > "LASTFM" > "LOG IN TO LAST.FM" > *enter creds* > "Let me in!"

**Comment by MarshallOfSound** [comment]
Last.FM is either erroneously blocking you or something on your network is trying to MITM you 😆 Just checked and this works for me on all three platforms so whatever's causing this is on your network.  Tbh it would probably work if you gave it another go today 😆
