### ISSUE TITLE
Ellipsis change color and don't match Home/Music library/Recents

### ISSUE THREAD

**Issue by charlesdurham** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3041]
**OS:** Elementary OS 0.4.1

**GPMDP Version:** 4.5.0

**Issue Descriptions:** The ellipsis color below Home/Music library/Recents changes when scrolling, seemingly to contrast the color of the background, but none of the other icons update.

![screenshot from 2018-03-09 21-19-38](https://user-images.githubusercontent.com/6540550/37238678-46636832-23e0-11e8-9902-493a4880c0a7.png)

**Comment by charlesdurham** [comment]
I saw https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/2759, should this be raised on the theme repository instead?

**Comment by jostrander** [comment]
please raise over on the theme repository. Thanks
