### ISSUE TITLE
Custom CSS for GPM not applying

### ISSUE THREAD

**Issue by spikespaz** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3042]
**OS:** Windows 10 Home Preview Build 17115 Preview

**GPMDP Version:** 4.5.0 (Lattest)

**Issue Descriptions:** Custom styles for Google Play Music not working at all

**Steps to Reproduce:**

Open sidebar > Click "Desktop settings" > "Custom Styles" tab> load file with the content mentioned below > "Reload Styles" > restart app just to be sure

This is my custom CSS, on the Google Play Music site, it works fine and hides the small side bar. I like it because it just allows the regular full side bar to be used.

```css
#quickNavContainer {
    display: none;
}
```

**Comment by JamTarty** [comment]
I'm having the exact same issue. I'm was going to attempt to make my own theme but it just won't apply.

**Comment by spikespaz** [comment]
@polyethene I noticed that GPM is just pretty terrible in terms of interface design altogether. Maybe it was two different people that didn't collaborate on the project? I looked at some of the other element names and IDs and they are all inconsistent.

**Comment by spikespaz** [comment]
Regardless of speculation, this issue is solved. I'm going to close it now, but it should be referenced in an FAQ or something.
