### ISSUE TITLE
When display scale is set to 125%, GPMDP experiences scaling issues

### ISSUE THREAD

**Issue by Tankatronic** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3044]
**OS:**
Windows 10
**GPMDP Version:**
4.5.0
**Issue Descriptions:**
I have a 3 monitor setup, where two of my monitors are identical (1680x1050) my third monitor is my laptop that is connected to a docking station. In order to see the laptop comfortably, I need to set its display scale to 125% (1920x1080 resolution). 

When I set the display to 125% and minimize GPMDP to the miniplayer, the miniplayer window slowly starts to expand in size in both directions on its own, becoming indefinitely larger. If you return to the main player from the same display, the scaling of the controls inside the window become larger and may not fit on the screen anymore. If you drag the miniplayer window to another monitor that is scaled 100%, it stops growing, however sometimes the scaling distortion prevents buttons from being accessible without an app restart or dragging the window borders far enough to reach them.

Setting the scale to 150% did not reproduce the issue. I did not try a custom scale or larger than 150%.

Images:

**Before switching to miniplayer, full screen 1920x1080, scaling 125%:**
![image](https://user-images.githubusercontent.com/4115700/37365500-b0db7e6e-26cb-11e8-910a-a8ec5c08f08c.png)

**Switching to miniplayer**
![scaling](https://user-images.githubusercontent.com/4115700/37365762-797d5342-26cc-11e8-8618-510fbbf12726.gif)

**After switching back from miniplayer to mainplayer, full screen 1920x1080 scaling 125%**
![image](https://user-images.githubusercontent.com/4115700/37365377-54431b8a-26cb-11e8-985b-0894081d9a7f.png)

**Steps to Reproduce:**
1. Open Display Settings
2. Under Scale and Layout, select 125% from the dropdown
3. Ensure GPMDP is on the monitor with the new scale setting
4. Select the minimize to miniplayer button

**Comment by vibhas77** [comment]
Hi, I have been facing the same issue with the Mini Player.

I have a three monitor setup and mini player does not scale properly in any of them as a result I do not use it.

**Comment by MarshallOfSound** [comment]
Merging into #2269
