### ISSUE TITLE
Very slow to load the screen, keeps in the lazy load for about 1 minute

### ISSUE THREAD

**Issue by ricardofunke** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3046]
**OS:** Arch Linux - Gnome 3.26

**GPMDP Version:** 4.5.0-2

**Issue Descriptions:** Very slow to load the screen, keeps showing the lazy load for almost one minute until finally show the google play music screen

**Steps to Reproduce:** Just run the app. I can open Google Play Music in the browser without any issues or slowness 

[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/1808905/debug_info.zip)

**Comment by MarshallOfSound** [comment]
The lazy loader is an invention of this app 😄 We keep that spinner there until GPM reports it is fully loaded.  If it is taking a long time on your network your network is slow for one or more requests coming from GPM.

If you hooked a `window.onload` listener in your browser when loading GPM you'd probably see the same thing 👍
