### ISSUE TITLE
Window issue: sometimes it starts weird and I cannot move or resize the window 

### ISSUE THREAD

**Issue by ricardofunke** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3047]
**OS:** Arch Linux - Gnome 3.26

**GPMDP Version:** 4.5.0-2

**Issue Descriptions:** Sometimes the app starts in a weird position in the screen and I cannot move the window or resize it. It looks like it can't get the window from the window manager, I don't know. But clicking in the gnome panel at the top and dragging down makes it resize from maximized to windowed and it fixes the app window. It may be related to the fact that I use two monitors, so fyi I have a hybrid Intel/ATI Graphic Card:

$ lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Thames [Radeon HD 7500M/7600M Series] (rev ff)

**Steps to Reproduce:** Start the app and see the app in a weird position, like it's maximized but positioned downright

**Comment by MarshallOfSound** [comment]
Fixed by #3045
