### ISSUE TITLE
[SUGGESTION] Custom Themes Resource

### ISSUE THREAD

**Issue by sks316** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3049]
First of all, I must say that you have a wonderful application here. GPMDP is very well made, and I'm glad to say that I will be using it nearly daily.
I have spent a while Googling for custom themes for this app, however all I have been able to find are themes that too closely resemble the built-in dark theme. I would like to suggest a place where people can upload all their themes for convenience or a place where people can request for a theme to be made. This would make it easier for users to find themes for the application and you could possibly integrate it within GPMDP in the future for ease of access.

**Comment by jostrander** [comment]
I would suggest making your theme a gist here on github and adding it to our wiki with a screenshot:

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/Themes

**Comment by MarshallOfSound** [comment]
This is not something we're going to build (a repository of themes), if you want to put your theme on the Wiki by all means do.
