### ISSUE TITLE
Uncaught Exception: The Internet connection appears to be offline.: (null)

### ISSUE THREAD

**Issue by anarchocurious** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#305]
An uncaught exception was reported.  
#### Info:
**OS:** darwin
**Arch:** x64
**GPMDP Version:** 3.0.0
**Time:** Mon Mar 07 2016 00:38:25 GMT-0600 (CST)

#### Error:
*The Internet connection appears to be offline.: (null)*
```js
Error: The Internet connection appears to be offline.: (null)
    at Error (native)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
Client side net issue, not internal
