### ISSUE TITLE
[SUGGESTION] Play/Pause from System Tray

### ISSUE THREAD

**Issue by sharkweek** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3052]
On Windows 10, I find that when using multiple desktops, it's a little bit of a hassle to always have to go back to the original desktop with the app open to play or pause a song. I realize there is the ability to create custom hotkeys, but I would like to suggest also adding play/pause functionality to a single left click on the system tray icon.

**Comment by MarshallOfSound** [comment]
> but I would like to suggest also adding play/pause functionality to a single left click on the system tray icon.

On 2 out of 3 OS's left clicking the tray icon opens the tray menu, this isn't something we can implement 👍
