### ISSUE TITLE
App does not start

### ISSUE THREAD

**Issue by UsersGhost** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3054]
**OS:**
Elementary OS
**GPMDP Version:**
4.5.0
**Issue Descriptions:**
I click on the icon in the menu or the dock bar and nothing happens.  The icon will react but the app never starts.
**Steps to Reproduce:**
I have restarted a few times, and nothing has changed.

**Comment by MarshallOfSound** [comment]
Can you launch from terminal and see what the output is?

**Comment by t-smirnov** [comment]
output of terminal is:
```
google-play-music-desktop-player: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory

```

**Comment by MarshallOfSound** [comment]
@t-smirnov I guess you need to install libgconf-2 then 😄 Can you give that a go

**Comment by tannishpage** [comment]
Hello I've got a similar problem when I open the program normally it loads but then displays this: https://pasteboard.co/HcYMsOn.png

This is the terminal output: 
```
error: Failed to load bonjour with error: {}
Bonjour is required to use Chromecast Support or to enable ZeroConf for the PlaybackAPI
On linux you need to install "avahi"
Failed to encode dictionary
Failed to encode reply value
Failed to encode dictionary
Failed to encode reply value
```
I am on Ubuntu 16.04 LTS

**Comment by BrianAllred** [comment]
All that means is that you need to install avahi and enable the avahi
service if you want Chromecast support.

**Comment by CalebQ42** [comment]
If your still having trouble, you can try to install the flatpak version which should have all dependencies automatically included. Follow these instructions then open up software, search for it, and install: https://flatpak.org/setup/Ubuntu/

**Comment by MarshallOfSound** [comment]
Closing this out as stale and almost certainly a user-end issue 👍
