### ISSUE TITLE
Use Genius API for lyrics

### ISSUE THREAD

**Issue by zanedb** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3055]
Could you possibly integrate with the Genius API for song lyrics? I've found the Google ones to be very inaccurate. Additionally, this could (possibly) provide annotations, but that's much more complicated.

https://docs.genius.com/
https://docs.genius.com/#songs-h2
https://docs.genius.com/#search-h2

Thanks!

**Comment by MarshallOfSound** [comment]
Genius is oAuth based so I can't make requests to it without a specific user being authenticated and logged in 😄 This is a pretty big change from how our lyrics currently work.

If someone wants to tackle this I'll review a PR for it but I personally won't be addressing this

**Comment by tf2manu994** [comment]
I mean you could add a log-in in settings, like for LastFM

**Comment by dwminer** [comment]
@MarshallOfSound I'm interested in contributing a PR for this. For the auth problem, would you consider it an acceptable solution to add a tab in the settings menu for a Genius API key, like we already do for ListenBrainz?

**Comment by jostrander** [comment]
@dwminer I would review a PR for this if it came through.
