### ISSUE TITLE
Can't play artist via WebSocket API

### ISSUE THREAD

**Issue by verbumfeit** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3057]
**OS:** Linux

**GPMDP Version:** 4.5.0

**Issue Descriptions:** I already raised this issue a week ago in the appropriate repository [here](https://github.com/gmusic-utils/gmusic-ui.js/issues/9) but for visibility I'll post it here again:
Playing an artist via the Web Socket API currently does not work. While tracks and albums can be played directly from the search result page by clicking on the small play button on the covers, artists thumbnails don't have that button. You would have to right-click the artist and select 'Shuffle artist' or open the artists page and click the play button to start play music by that artist.

I already created a [pull request](https://github.com/gmusic-utils/gmusic-ui.js/pull/10) to adress this issue.

**Steps to Reproduce:** Send an artist result object (with real data of course)
```
{
  "id": String,           // Unique ID for this artist
  "name": String,         // The name of the artist
  "image": String,        // URL to an image of this artist
}
```
to `search.playResult(result)` of `gmusic-ui.js` via the Web Socket API.

**Comment by MarshallOfSound** [comment]
> but for visibility I'll post it here again:

Please don't 😄 For context I get a stupid amount of notifications a day, I'll get to these things when I get to them 👍 I do try and deal with things quickly but for instance all of last week I was in tokyo 😄
