### ISSUE TITLE
GPMDP changing audio quality on bluetooth speaker

### ISSUE THREAD

**Issue by DMSavchik** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3060]
**OS:** macOS High Sierra Version 10.13.3 

**GPMDP Version:** Version 4.5.0 

**Issue Descriptions:** When I turning on bluetooth speaker and wanna listen the music. Quality of sound is very bad

**Steps to Reproduce:** Open GPMDP, play music, connect bluetooth device, done - you have a bad sound quality.

**Comment by MarshallOfSound** [comment]
Duplicate #2589
