### ISSUE TITLE
Different song totals in Web App and GPMDP

### ISSUE THREAD

**Issue by jtrobinson1993** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3062]
**OS:** MacOSX 10.13.3

**GPMDP Version:** 4.5.0

**Issue Descriptions:** The Google Play Web App displays 209 songs in my library. GPMDP displays 179 songs in my library. All of the missing songs seem to be by one artist, "A Day to Remember".

[Screenshot.](https://i.gyazo.com/2a96d009d15ac19e975060dc841a4e77.png)

**Steps to Reproduce:** Open GPMDP and the WebApp and click on "Music Library" in each. Compare song totals in top right. I restarted chrome refreshed the web page, and restart GPMDP and the totals stayed the same on both (209 vs. 179).

**Comment by jostrander** [comment]
close then Delete `%appdata\google Play Music desktop player\cache\` and reopen and see if its fixed.

**Comment by jostrander** [comment]
Ah crap, mac. I'm not sure where that path is on Mac 🙁

**Comment by jtrobinson1993** [comment]
@jostrander I found the equivalent on mac, deleted it, and reopened the program and it still said 179.

**Comment by jostrander** [comment]
The only thing I can think of is browser caching so to speak in GPMDP because we don't have any code that would modify that number or attempt to modify your library.

**Comment by jtrobinson1993** [comment]
@jostrander  Hah, actually it appears that your app is working better than Google Play Music. The songs that are missing on your app actually fail to play in the web app for some reason, I think this is an issue with Google Play, not you guys. Sorry to bother!.
