### ISSUE TITLE
Stop Discord from showing when hitting Stop

### ISSUE THREAD

**Issue by churchymayer** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3064]
I'm a big fan of the newly implemented Discord Rich Environment support. 

However, I miss an option so i can stop playback and Discord actually stops showing what music I'm playing. Right now it stays even when paused using my "Stop" hotkey, not even the pause one. If there is already some option to do that, for example by clearing my playlist then i'm not aware of that and would like to apologize in advance.

If not, adding an option to do this would be highly appreciated.

**Comment by MarshallOfSound** [comment]
`Stop` actually just pauses behind the scenes.  Reloading GPMDP or quitting it completely should clear the DRP 👍
