### ISSUE TITLE
Brew support 

### ISSUE THREAD

**Issue by zamai** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3065]
Hi, 
Thanks a lot for the player love it, using it every day!
I was wondering if there is a plan to support installation via homebrew/brew?

I've tried brew cask install google-play-music-desktop-player  <-- but this does not exist anymore.

Thanks!

**Comment by MarshallOfSound** [comment]
> I was wondering if there is a plan to support installation via homebrew/brew?

There is not, if someone wants to create / maintain a tap/cask for this then 👍 but it won't be officially supported by us 😄

**Comment by eth-p** [comment]
@zamai Here you go!

```shell
brew tap eth-p/homebrew-gpmdp
brew install gpmdp
```

I'll see what I can do about getting this merged in the official Homebrew cask repo, if possible.

**Comment by zamai** [comment]
@eth-p thanks!
