### ISSUE TITLE
Websocket interface: track, rating, and lyric messages sent twice in multiple scenarios

### ISSUE THREAD

**Issue by StephenGregory** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3066]
**OS:** Win 8.1 Pro

**GPMDP Version:** v4.5.0

**Issue Descriptions:** The "track", "lyrics", "rating" channel is broadcasted on twice (second should not occur) under certain scenarios.

**Steps to Reproduce:**

#### Prerequisite to each scenario
Create simple node app with a websocket implementation. I'll choose the [ws](https://www.npmjs.com/package/ws) package. Start GPDP, enable the playback API,  and run your node app:

```JavaScript
const WebSocket = require('ws');
let ws = new WebSocket('ws://localhost:5672');

ws.onmessage = e => {
    const data = JSON.parse(e.data);

    console.log(new Date(), data.channel);
};
```

#### Scenario 1

1. Play a song on a playlist or album.
2. Click next song.

Expected:

To receive messages on the "track", "rating", and "lyric" channels once for step 1 and once for step  2.

Actual:

Receive messages on the  "track", "rating", and "lyric" channels once for step 1 and twice for step 2 (one right after another).

#### Scenario 2

1. Play a song on a playlist or album.
2. Wait for song to be over and next song to start playing.

Expected:

To receive messages on the "track", "rating", and "lyric" channels once for step 1 and once for step 2.

Actual:

Receive messages on the  "track", "rating", and "lyric" channels once for step 1 and twice for step 2 (one right after another).

**If this does not occur, then scenario 3 will present itself**

#### Scenario 3

1. Play a song on a playlist or album.
2. Wait for song to be over and next song to start playing (you may skip ahead within the song in step 1)
3. Pause the song.

Expected:

To receive messages on the "track", "rating", and "lyric" channels once for step 1 and once for step 2, none for step 3. 

Actual:

Receive messages on the  "track", "rating", and "lyric" channels once for step 1 and once for step 2.  Also receive messages on these channels for the second song on step 3.Note that subsequent pausing and unpausing does not trigger more messages on these channels.

**Comment by MarshallOfSound** [comment]
We emit the event each time we get slightly more information (some parts of the GPM UI load asynchronously).  Handling duplicate messages should be something that clients have to handle.  In theory handling these messages simply updates a local store of GPMDP's "state" somewhere, so multiple messages shouldn't be an issue.

Let me know if I'm missing something here

**Comment by StephenGregory** [comment]
One detail I omitted is that the payload is the same, hence why I thought this was a bug.

In the [PlaybackAPI WebSocket](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/docs/PlaybackAPI_WebSocket.md) docs it mentions that events can be emitted multiple times with _different_ information, but no mention being sent with the same information.

If this is not a bug I think it might be worth updating the documentation to acknowledge that duplicate messages can be sent.
