### ISSUE TITLE
Equalizer feature request

### ISSUE THREAD

**Issue by StanevDev** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3067]
Please add equalizer to app, unfortunately not all platforms have it native by default.
For example AppleMusic on mac has equalizer in app, but not in mas os system for other apps.
Thanks!
<img width="447" alt="2018-03-27 18 16 07" src="https://user-images.githubusercontent.com/12533981/38024172-e0ed773e-328c-11e8-9855-67a108f968e4.png">

**Comment by MarshallOfSound** [comment]
It's in the code base but currently disabled, please check closed issues or the [FAQ](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ#what-happened-to-the-eq-the-feature-list-says-theres-an-eq) before raising issues.
