### ISSUE TITLE
Feature Request: Update Notification

### ISSUE THREAD

**Issue by jwhipp** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3070]
**OS:** . 

All Supported OSes.

**GPMDP Version:**

In use/as of this issue: 4.50

**Issue Descriptions:**

This is a feature request to get some sort of update notification when new versions of the app are available.  Currently, one needs to remember to periodically check the Github page or setup Github notifications.   It would be amazing if the app could notify the user of an update.

**Comment by MarshallOfSound** [comment]
On Windows and macOS we push out updates automatically and they come with notifications in-app that let you know there is a new update pending.  On debian if you install through the apt repo then you will get updates like anything else (by running `apt update`).
