### ISSUE TITLE
Music becomes unpaused when chromecast disconnects from inactivity

### ISSUE THREAD

**Issue by Trucido** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3071]
**OS:** Windows 10

**GPMDP Version:** 4.5.0

**Issue Descriptions:** Sorry to be brief here but wanted to bring this up before I forget.
*Issue:* GPMDP in paused mode resumes music by itself when a connected chromecast device times out and drops connection. This results in current playlist being resumed out of default audio output without me un-pausing playback.
In google-chrome, it is normal for a chromecast to time out and disconnect after a period of inactivity but it does not resume a paused playlist like i've noticed occurs in GPMDP. 
Not sure if related to the Windows integration, I do have that enabled and will follow up here if I can track down if any of the settings are related.
**Steps to Reproduce:**
1. Connect GPMDP to a chromecast
2. Start playing music
3. Pause music
4. Wait until inactivity timeout period for chromecast to disconnect
5. Run back to your computer to pause the music coming out of your default playback device which suddenly became unpaused (lol)

**Comment by MarshallOfSound** [comment]
Can you raise this on `GPMDP/electron-chromecast` I assume we're emitting the wrong event on disconnect

**Comment by Trucido** [comment]
Sure, Issue raised here: (also testing cross-repo issue referencing below, doesn't seem to be working with ```user/repo#issuenumber``` with the dash in your project name.
GPMDP/electron-chromecast#53
