### ISSUE TITLE
Making GPMDP for linux my default music player

### ISSUE THREAD

**Issue by gauravk97** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3073]
**OS:**
Elementary OS 0.4 loki (Based on Ubuntu 16.04 LTS)
**GPMDP Version:**

**Issue Descriptions:**

**Steps to Reproduce:**
I want to make GPMDP my default music player. But the application doesn't show up in the list of music players. 
![image](https://user-images.githubusercontent.com/13166768/38168963-3588c952-357a-11e8-92fd-49e2cb39314a.png)

**Comment by timoschwarzer** [comment]
Hmm, I think this isn't possible because GPMDP can't play files. (Yes, it is _possible_ but what's the benefit of having a music player opening when opening a file that can't play it?)

**Comment by jostrander** [comment]
This probably won't happen due to reasons mentioned by @timoschwarzer. The player won't play songs locally so there isn't a point in registering it as the default audio player. If you have a specific use case that makes sense reply or even better PR and we'll consider it for the future.
