### ISSUE TITLE
Glitched beeping sound when enabling experimental support for multiple audio channels

### ISSUE THREAD

**Issue by Dornisaurio** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3074]
I know this is an experimental feature but I was wondering if there is anything I can do to stop this from happening. 

Sometimes I can play well music using this feature and no glitched beeping sound happens. 

But when it happens (Sometimes just as soon as I open the player) the only way to make it stop is closing the player, but reopening it will bring the glitch again so I have to completely reboot my system. 

I was also wondering, is this setting nessesary for me if I already have a driver that handles the 5.1 audio? I don't know if it would convert the audio from chromium into 5.1 or if I need to enable this setting for better performance.

PS: Your software is everything I ever wanted! I hope google notices your hard job and hires you to bring this player forward!

**Comment by jostrander** [comment]
This option acts exactly the same as the chrome variant as they both rely on the same source. As far as the technicalities you may have to refer vague source info and google product forums to find out how to use it correctly and what it does exactly. We just pass this to the underlying chrome instance for people like you who are curious about trying it, but we don't have any more info on the subject. Best of luck!
