### ISSUE TITLE
Snap package google-play-music-desktop-player does not provide an application icon in GNOME on Ubuntu 18.04

### ISSUE THREAD

**Issue by dylanmtaylor** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3076]
Hello,

I installed the google-play-music-desktop-player package on Ubuntu 18.04 using the command `sudo snap install google-play-music-desktop-player` and it works well. The only issue I have is that the Application icon is generic instead of showing the logo.

**Comment by MarshallOfSound** [comment]
Although the snap metadata is in this repository it is not an officially supported installation method (in fact I have basically no idea how it works).  I'd take a PR to fix it but it's not something I can deal with

**Comment by amartos** [comment]
For those who still look for a local fix :
    wget https://raw.githubusercontent.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/master/src/assets/icons/svg/vector_logo.svg
    mv vector_logo.svg ~/.icons/google-play-music-desktop-player.svg

**Comment by s3huber** [comment]
The proposed fix with putting the icon to `~/.icons/google-play-music-desktop-player.svg` does not seem to work anymore. :slightly_frowning_face:

**Comment by troystauffer** [comment]
@s3huber odd, I just tried it and it's working for me. Same ubuntu and player version. I installed via Ubuntu Software manager, perhaps that makes a difference?

**Comment by BrMBr** [comment]
> For those who still look for a local fix :
> 
> ```
> wget https://raw.githubusercontent.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/master/src/assets/icons/svg/vector_logo.svg
> mkdir -p ~/.icons
> mv vector_logo.svg ~/.icons/google-play-music-desktop-player.svg
> ```

This worked for me. Thank you! (Linux Mint 19.1/Snap)
This bug is not occurring when installing using Flatpak.

**Comment by Tallicia** [comment]
wget solution to .icons is just great! Yay!  Still not sure why it isn't just mkdir and wget to the directory tho...

<code>
mkdir -p ~/.icons && wget -O ~/.icons/google-play-music-desktop-player.svg https://raw.githubusercontent.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/master/src/assets/icons/svg/vector_logo.svg
</code>
<p><p>
works great for ubuntu 19.04 disco dingo. -Hooowooooooeeeeeewll
