### ISSUE TITLE
Discord Rich Presence Title Customization

### ISSUE THREAD

**Issue by Cyndre76** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3077]
**OS:**
Microsoft Windows 10 Home (1709)
**GPMDP Version:**
4.5.0
**Issue Descriptions:**
Discord Rich Presence title is too long for use in Discord, reducing readability. Instead, the option should either accept the name given by the Discord client for the app or accept a field in settings for defining such name. Simplest solution is to use the abbreviated name of GPMDP instead or even just "Music"
**Steps to Reproduce:**
Enable Discord Rich Presence in GPMDP.
![image](https://user-images.githubusercontent.com/34636882/38338752-8a0bce08-3830-11e8-813b-626fc97e7327.png)

**Details**
![image](https://user-images.githubusercontent.com/34636882/38338589-bd72a1b4-382f-11e8-9028-f8e69dcfb07f.png)
As noted above the overflow menu is present when the Discord Rich Presence is enabled.
![image](https://user-images.githubusercontent.com/34636882/38338645-fe19f65e-382f-11e8-9e74-1c14a771e351.png)
Even when redefining the title of the "game" the title is still the same. 
![image](https://user-images.githubusercontent.com/34636882/38338703-45f5cafc-3830-11e8-84a9-678803f0f0c5.png)

**Comment by sam-cross** [comment]
AFAIK to get an app to work with Discord Rich Presence you have to register the name of the application with Discord themselves. So they couldn't use "Google Play Music" as it's not official, and "Music" may be too broad.

**Comment by Cyndre76** [comment]
The recommendation includes alternative names such as "GPMDP". (which is the alias given to the project)
"Music" was just a desirable name.

**Comment by Cyndre76** [comment]
Accidental closing on my part, apologies.

**Comment by sam-cross** [comment]
Actually, as another suggestion, simply "Play Music" would work. It's short enough and it's the same name as the app on Android!

**Comment by MarshallOfSound** [comment]
That name is the only thing we can use, it's the registered app name on Discord.  We can't use "Google Play Music" or "Play Music" for trademark reasons 👍

**Comment by Cyndre76** [comment]
What about the title "GPMDP"? It will fit and also resolve the original issue of overflow.
