### ISSUE TITLE
Playback Thread at High Priority

### ISSUE THREAD

**Issue by nathanila** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3078]
**OS:**

Windows

**GPMDP Version:**

Unknown

**Issue Descriptions:**

When playing music , the music will skip when the computer is busy.  Please run the playback thread at a higher priority so that the music never skips.

**Steps to Reproduce:**

Play music.  Run a program that uses all of the CPU.  Hear the music skip.

**Comment by MarshallOfSound** [comment]
> Please run the playback thread at a higher priority so that the music never skips.

This is not a thing we have control over, playback is done (afaik) on the UI thread inside chromium and will run whatever priority that has

**Comment by Trucido** [comment]
I know this is closed, but... Windows 10's new spring update now includes ability to set default priority for applications, though from my testing (on Linux anyways) chrom{e,ium} likes to set it's own priorities.

There's probably some flag switches that could be used, however.
