### ISSUE TITLE
cache location on arch linux

### ISSUE THREAD

**Issue by julianuu** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3079]
**OS:** arch linux

Hi, thanks for the good works first of all!

On my system, cache is written into `~/.config/Google Play Music Desktop Player/` while there already exists a folder `~/.cache` for cache. Is there a way to put it there?

**Comment by MarshallOfSound** [comment]
This is an upstream issue in Electron being discussed on that repo
