### ISSUE TITLE
Remove mention of the EQ on the website

### ISSUE THREAD

**Issue by tf2manu994** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#308]

**Comment by MarshallOfSound** [comment]
It is an unreleased feature, just going to leave it in for now.  It'll come out soon enough :+1:

**Comment by tf2manu994** [comment]
ah, the blizzard `SoonTM` approach.

:P

**Comment by MarshallOfSound** [comment]
`SOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOONNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN`

**Comment by Kukunin** [comment]
Almost three years have passed, there is still no EQ
