### ISSUE TITLE
Wrong language is displayed

### ISSUE THREAD

**Issue by KostyaBakay** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3082]
OS: Windows 10 x64
GPMDP Version: 4.5.0

Issue Descriptions:
GPMDP shows content in Russian language instead of English.
Language of Windows 10 - English (other apps work with English language).
My Google account language - English (but earlier it was Russian language).
Language of browser version Google Play Music - English.
Language of GPMDP in settings - English.
Displayed language of GPMDP - Russian.

![lang](https://user-images.githubusercontent.com/9611539/38495816-aa4558fc-3c03-11e8-9ab4-b57e88f5e55b.png)

Steps to Reproduce:
1. Download and install app.
2. Bug appears at the starting.

**Comment by MarshallOfSound** [comment]
> (but earlier it was Russian language)

This will be why, that text that is in Russian comes from Google's UI not us so they have determined (probably through your google account) that you want to see russian.  I'd search for every language option you can find in your google account 😀

**Comment by Soaku** [comment]
@MarshallOfSound If you append `?hl=en` to the URL it changes the language of GPM. I guess it is possible to add setting to it in GPMDP.

**Comment by lisovyk** [comment]
Have the same problem. All the same except i'm on macbook pro.
My google account settings probably were russian some time ago too, but are in english for a few years now for sure.

**Comment by lisovyk** [comment]
@KostyaBakay I found a solution: relog to your account through the player. On the logging screen choose english instead of russian. Voila, it works!

**Comment by Soaku** [comment]
@lisovyk Google yesterday requested a relogin on GPMDP. Today I was surprised to see a different language. So I guess that's the solution.

**Comment by KostyaBakay** [comment]
@lisovyk thank you, it works :+1:
