### ISSUE TITLE
Feature Request: Option to disable track notification

### ISSUE THREAD

**Issue by Taeon** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3083]
A quick request (I hope): I'd like to disable the pop-up notification that appears at the top-right of the screen whenever a new track starts playing. Or at the very least, be able to dismiss it somehow. I realise that hovering over it makes it fade, but I just plain don't like it and I'd rather not have it there at all.

![image](https://user-images.githubusercontent.com/12548334/38607110-b9c06a8e-3d6f-11e8-970d-19d9f17a3cba.png)

Thanks!

FYI I'm running on Ubuntu 16.04.

**Comment by MarshallOfSound** [comment]
You can disable this in Google Play Music's settings

**Comment by Taeon** [comment]
Ok, apologies for being stupid but I've looked and I can't see the option. What's it called?

**Comment by Taeon** [comment]
Ah - OK, it's under Google Settings (under Labs) rather than the Desktop Settings -- apologies for wasting anyone's time :)
