### ISSUE TITLE
Rich Presence Not Working

### ISSUE THREAD

**Issue by memoeries** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3085]
**OS:**
Windows 10
**GPMDP Version:**
4.5.0
**Issue Descriptions:**
After most recent discord update rich presence didn't show up
**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment]
You may need to restart GPMDP and/or discord. It definitely works because other issues have come in regarding how it works 👍
