### ISSUE TITLE
Gaps between songs?

### ISSUE THREAD

**Issue by luisvsilva** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3086]
Can gaps between songs be configured with a set time in settings? That would be awesome and I guess pretty simple to implement, Let me know and I can try to prepare a pull request.

**Comment by MarshallOfSound** [comment]
This is not _possible_ to implement, the songs are played by GPM using multiple audio elements on the page in order to provide gapless playback.  We have no idea with element is which part of what song so we don't know to pause / wait between songs until the next song has already started
