### ISSUE TITLE
Feature Request: Notification of Track 

### ISSUE THREAD

**Issue by TomasTomasTomas** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3090]
Hey,

Love this program, the one thing I really love is a notification that shows when a new song begins playing, detailing the song, one like ITunes uses.

Quick Mockup of how something like this would look:

![image](https://i.gyazo.com/9ec5047785c22e970f50824952559ccb.png)

**Comment by jostrander** [comment]
Already implemented. See Google's Play Music Settings and turn on Notifications.
