### ISSUE TITLE
In Mac, sometimes music stops suddenly

### ISSUE THREAD

**Issue by Bravosea** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3091]
**OS:**
MAC OSX 10.13.4 HIGH SIERRA
**GPMDP Version:**
4.5.0
**Issue Descriptions:**
Music stops always when you´re moving files, even if you have shortcuts disabled. 
Music sometimes stops without any reason
**Steps to Reproduce:**

**Comment by Hobbit** [comment]
I'm not able to reproduce this (Same OS and GPMDP Version)

Questions to hopefully flush out the issue:
------
What type of files are you moving? 
How many at one time?
How large are the files?
Are you moving them within the same storage volume or between separate volumes?

**Comment by MarshallOfSound** [comment]
As the reporter has not responded to the request for additional information this issue will be closed.  If further information can be provided at some point in the future, comment on this issue with the requested information and if appropriate the issue will be reopened.

**Comment by jscheel** [comment]
I am experiencing this now, pretty much every day. I'm not moving files, so I have no idea what that's about. Eventually though, the audio will cut out, even though the ui is still updating. A restart of the app always fixes it.
