### ISSUE TITLE
Feature request: Show track info in Macbook Touchbar 

### ISSUE THREAD

**Issue by jdyer09** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3092]
Hi!
I was thinking it would be awesome if the touchbar could show the track information, perhaps as grey text inside the the track progress bar, underneath the position indicator.  That said, the touchbar integration is pretty fantastic as is!

**OS:** High Sierra

**GPMDP Version:** 4.5.0

**Comment by phdoerfler** [comment]
> That said, the touchbar integration is pretty fantastic as is!

What touch bar integration? I'm also running 4.5.0 on High Sierra. No integration there.

**Comment by jdyer09** [comment]
Here's a demo of it working on mine:
https://imgur.com/bMwwIDi

**Comment by phdoerfler** [comment]
@jdyer09 Oh yes indeed now I recall having seen that before. For some reason it was not showing until I restarted. But now it's there in all its glory.

With this out of the way what I personally would like to see is a thumbs up and thumbs down control. Also the ability to customize the touchbar controls altogether. GPMDP is the only app I got that has touchbar controls without the View -> Customize Touch Bar… menu entry.
To me it seems as if what we are seeing is some sort of standard media playback touchbar controls from macOS itself if such a thing exists.

**Comment by jostrander** [comment]
According to @MarshallOfSound we just pass the information to the system, and the system devices what to display on the touch bar. We don't directly influence what shows up there. Currently it appears that track information is not rendered by the OS, even though we are passing it. 

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/2772#issuecomment-343711002

**Comment by MarshallOfSound** [comment]
Thanks @jostrander 👍 

Closing out
