### ISSUE TITLE
When paused the track number column is empty

### ISSUE THREAD

**Issue by ChildishGiant** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3098]
![image](https://user-images.githubusercontent.com/13716824/39099298-6c1c2f0c-4670-11e8-8d18-7ba0ae57b405.png)

Here's a few ideas as to what could be put there:

- A paused version of the playing animation
- A paused icon
- The track number

**Comment by MarshallOfSound** [comment]
This is a theming issue, please raise on the theming repo (if you disable the there something is in that spot)

**Comment by ChildishGiant** [comment]
Where's the theming repo located?

**Comment by MarshallOfSound** [comment]
This information is in the README
