### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by GalacticBacon** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3099]
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/1936365/debug_info.zip)

**OS: Windows 10**

**GPMDP Version: 4.5.0**

**Issue Descriptions: High CPU when in the foreground or playing music (25-50%). Log suggests that it is unable to connect to the update server. I am sitting behind a corporate proxy which would be blocking this. I have reinstalled the program which did not solve the issue. Switching to our guest network without the proxy reduced background playback to 3%, foreground playback is still ~25%
**

**Steps to Reproduce: Block connection to update server**

**Comment by MarshallOfSound** [comment]
Closing out as we've received several issues like this, every time it is GPM doing stupid stuff and using a lot of CPU.  You can try the tricks mentioned in the issue the bot linked above 👍
