### ISSUE TITLE
The icons are gone!

### ISSUE THREAD

**Issue by i-panov** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3102]
OS: Windows 10
GPMDP: 4.5.0
Issue Descriptions: Many of the songs in my playlist disappear icons. Sometimes they are restored after a while, but not always ... In the web version they are.
Steps to Reproduce: Just use it 😃

**Comment by MarshallOfSound** [comment]
This literally is the web version, if something is going wrong with that UI it's probably google A/B testing you
