### ISSUE TITLE
Google Play to be replaced by YouTube remix?

### ISSUE THREAD

**Issue by jacobslusser** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3103]
[https://www.droid-life.com/wp-content/cache/page_enhanced/www.droid-life.com/2018/04/24/youtube-remix-google-play-music/_index.html](https://www.droid-life.com/wp-content/cache/page_enhanced/www.droid-life.com/2018/04/24/youtube-remix-google-play-music/_index.html)

This article just came out today and implies that Google Play is going to be retired in favor of YouTube Remix - a forthcoming streaming platform. 

What will become of our beloved Desktop Player? I personally don't use it for streaming/radio... I upload my own MP3 library and don't want to go full streaming...

I feel like I just got punched in the gut...

**Comment by jostrander** [comment]
It really depends on what Google decides to do :man_shrugging:. If they keep Google Music the web interface then this project will live on. If they sunset it, we'll have to see if it's worth applying development efforts to the new player.

**Comment by MarshallOfSound** [comment]
We don't know what Google will do, neither do these people guessing what will happen when / if remix comes out.  I guess we'll cross that bridge when we get that far

**Comment by nklayman** [comment]
The new YouTube music is rolling out (I have it), and I think we should re-open this issue. It would be really nice to have something like this for YouTube music.

**Comment by MarshallOfSound** [comment]
I don't have access to YouTube music yet, if someone can get me access, lend me access or whatever I can look at supporting ytm in this app (it shouldn't actually be too hard to get basic support in)

**Comment by SolarLiner** [comment]
From what I read, the transition will be gradual, but Google Play Music is indeed on its death bed.
From a [Google statement](https://www.droid-life.com/2018/04/24/youtube-remix-google-play-music/) about YouTube Music:
> We’ve previously announced the combination of the YouTube Music and Google Play product teams — music is very important to Google so it’s critical we have one offering that meets the needs of consumers and artists. Nothing will change for users today and we’ll provide plenty of notice before any changes are made.

**Comment by MarshallOfSound** [comment]
Most things are working in the `ytm` branch, including a service switcher that lets you toggle between GPM and YTM.

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/tree/ytm

Still to do:

* [ ] Port `gmusic-ui.js`
* [ ] Port `gmusic-theme.js` (not super urgent, the default is dark mode on ytm)
* [ ] As yet undiscovered bugs

**Comment by MarshallOfSound** [comment]
Can some folks experienced with the codebase check it out and let me know if it breaks / works 😄 

cc @SolarLiner @jostrander

**Comment by SolarLiner** [comment]
Wait does that mean I'm supposed to be experienced with the codebase? 😅

I don't have access to YTM for now, since Europeans seem to be a second market for Google. Maybe there's something else I can do?

**Comment by MarshallOfSound** [comment]
@SolarLiner 🤔 I'm in Australia and just got it randomly today with no emails.

**Comment by SolarLiner** [comment]
Hm. You're getting me hyped there, I'll check it out tonight.

**Comment by nklayman** [comment]
I get this error when I run `npm install`:
[npm-error.log](https://github.com/nklayman/vue-cli-plugin-electron-builder/files/2095966/npm-error.log). If you post a prebuilt version I will happily test it out for you.

**Comment by SolarLiner** [comment]
I just got it here and so I'm readying to test the `ytm` branch.

**Comment by vertiman** [comment]
Tried out your branch, will use it as a daily driver for a bit (as an aside - thanks for making this!).
Couldn't figure out how to actually change the service via the UI, but I hacked it into the .settings file to get it working.
Lots of errors on app start in the console (let me know if you want them) - but the app itself seems to work anyhow.

**Comment by MarshallOfSound** [comment]
Most of the error are expected, the ytm API hacks I did aren't complete, you can switch services from the tray menu btw

**Comment by SolarLiner** [comment]
Okay so it didn't work the first time but that's because I'm an idiot who doesn't RTFM... :man_facepalming: 

After installing the system dependencies (btw, Ubuntu 18.04 can't find `lib32bz2-1.0`, but I could build without it, so is it really needed?), I got it to work. Surprised me to even have MPRIS working, that's very nice!

I'll report once I have spent the whole night using it, but so far so good!

**Comment by judge2020** [comment]
Might be a good idea to reserve youtubemusicdesktopplayer.com or something of the sorts.

**Comment by SolarLiner** [comment]
Well, I didn't pull an all-nighter but I did use YouTube music for a few hours, here's my observations:

- Cover art sent to MPRIS should be cropped because with Music being able to play videos, the aspect ratio isn't correct.
- Play status isn't reported to MPRIS - although signal sent by it are correctly interpreted by the player
- There's a double "mini player" button on the Google Play Music interface now

I'm really loving this! I'll be making a deb package and installing it over the 4.5.0 version.

**Comment by MarshallOfSound** [comment]
`4.6.0` will have ytm support in it, should be released some time this week
