### ISSUE TITLE
Provide option to hide menubar icon

### ISSUE THREAD

**Issue by 33b5e5** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3104]
**OS:** macOS 10.13.4
**GPMDP Version:** 4.5.0

Please consider providing an option to disable the menubar icon. I just started using GPMDP and I don't find the menubar icon useful at all. I get why it's on by default, but an option to remove/hide it would be nice.

**Comment by MarshallOfSound** [comment]
This has been requested many times and denied many times due to usability issues that removing the menubar icon would create.  Check closed issues before raising new ones 👍
