### ISSUE TITLE
Ubuntu 18.04 Issues

### ISSUE THREAD

**Issue by johndeaton** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3105]
Hello-

I've been using your app with Ubuntu 16.04 for some time now.  It was working great.  Nice job!

Unfortunately, now that I've upgraded to 18.04, it is very buggy (unable to click to start music, mouse clicks play random music, etc.).  I'm sorry that this isn't very descriptive, but there isn't one thing I can pinpoint.  Are you aware of issues with Ubuntu 18.04?

Thanks,
John

**Comment by jostrander** [comment]
Been using it on 18.04 beta for a few now. The only thing that I find that doesn't work is the media keys. Haven't had any other issues.

**Comment by o10g** [comment]
For me it just doesn't work. 
I've installed .deb package and when I run it - nothing happens. 
I tried to find where the logs are, but with no luck.
Does anybody has same problem with ubuntu 18.04?

**Comment by jostrander** [comment]
libgconf-2-4 is the solution here. Closing out.

**Comment by henriklb** [comment]
Thanks for this. May I suggest adding it to the FAQ?

**Comment by cassidyjames** [comment]
It should be added to the debian package's dependencies as well; that's the whole point of dependencies, and users shouldn't have to know or care what underlying libraries need to be installed.

**Comment by julian-alarcon** [comment]
This should be open. This issues is happening in Ubuntu 19.10 too.
