### ISSUE TITLE
Not really scrobbling

### ISSUE THREAD

**Issue by kpuljek** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3106]
**OS:** Ubuntu 16.04

**GPMDP Version:** 4.5.0

**Issue Descriptions:**
I've had some issue scrobbling to last.fm for the last few days. I tried scrobbling from both my phone and Firefox with the Web Scrobbler extension and scrobbling overall seems to be working fine, but GPMDP didn't scrobble most of the songs I listened to in the last days. It scrobbled a song or two and then just stopped, or skipped entire albums. I tried registering to listenbrainz today thinking it was last.fm's fault but songs are equally not scrobbled to both sources. (and equally are from my phone). 

I'd be happy to produce any logs or anything that can help, just let me know!

**Steps to Reproduce:**
Play music. It should scrobble, but after appearing in "now playing", it just doesn't stick to the list and instead just goes away.

**Comment by Fedik** [comment]
I have the same issue.

For info:
in Version 4.4.1 scrobbling works fine.
Version 4.5.0 didn't scrobble most of the songs.

**Comment by TGLumberjack** [comment]
I am having the same issue, also using v4.5.0. Some tracks will scrobble, but some show up as scrobbling while they're playing but then never get logged in my last.fm history.

**Comment by Cthulzilla** [comment]
I am having the same issue.

When I open my Last.FM profile page, it has the correct song "currently listening" (sometimes), but it doesn't log it and moves on to the next song (sometimes it doesn't always register the current song).

When I first installed GPMDP, it scrobbled two songs. Then it stopped.

**Comment by taxus13** [comment]
I have the same issue with Windows 10 and version 4.5.0. 

Today I have noticed that the last.fm 'currently listening' status is always updating, but the log is only working when the Desktop Player is not minimized. But if it not minimized it is using more cpu power:
* not minimized: 3-5%
* minimized: 0.1 - 0.3%
It would be nice to have a fix for this. I cannot imagine that drawing the ui is using so much power,

**Comment by Hushimitzu** [comment]
Same issue with Windows 10 and version 4.5.0.

**Comment by kpuljek** [comment]
Looks like it's scrobbling now in 4.6.0, tried with window minimized, window closed, window opened. Songs show up fine. I'll keep an eye on it.

**Comment by MarshallOfSound** [comment]
Fixed in >= 4.6

**Comment by mlms13** [comment]
Sadly, the probable-duplicate I experienced with the Chromecast (#3277) happened on 4.6.0, so either that's a separate issue or this one might still be happening.
