### ISSUE TITLE
"Program has stopped working" dialog when exiting with "X" (Windows Close) button

### ISSUE THREAD

**Issue by NetkoNefarious** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3107]
![error](https://user-images.githubusercontent.com/32903134/39399150-24317bc2-4b19-11e8-943b-39afd942a9c0.jpg)

The image is in Croatian, but it says: The program has stopped working. The problem was caused by irregular work of the program. Close the program. First option is to close and the second is to fix the errors in the program.

**OS:** Windows 10

**GPMDP Version:** 4.5.0

**Issue Descriptions:** When I exit the application by pressing X on the window while Minimize to Tray is off, the application seems to crash or not close properly (the "Program has stopped working" dialog appears). This doesn't happen when I exit using the tray icon or using the Quit button inside the program.

**Steps to Reproduce:**
1. Open the player
2. Untick Minimize to Tray in Desktop settings
3. Exit by pressing "X" in the top-right corner

**Comment by jhw866** [comment]
Can confirm this is an issue. Happens on some machines and not others.

**Comment by jhw866** [comment]
@jostrander, in my case discord rich presence is not enabled.
Also, I found out that after the app crashes, the app is unable to restart unless the machine is fully rebooted.

**Comment by NetkoNefarious** [comment]
In my case, the app can start again normally, but the problem persists.
Discord Rich presence is not enabled.

**Comment by jhw866** [comment]
@jostrander are there logs that I can add here to help you debug?

**Comment by NetkoNefarious** [comment]
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/2022335/debug_info.zip)

Here is the debug_info zip file. It's pretty long, so I will try to figure something out myself if I can later on.

**Comment by jhw866** [comment]
@NetkoNefarious, where can I find the logs? Can't seem to find them after a quick search

**Comment by NetkoNefarious** [comment]
They're in the zip file, or did I misunderstand the question? I made them with CTRL+SHIFT+G and typing DEBUG_INFO into the field. Is this how you're supposed to do it, or are the files way too long?

**Comment by jhw866** [comment]
@NetkoNefarious I am trying to how to get the debug logs from my personal machine so I can help @jostrander debug.

**Comment by NetkoNefarious** [comment]
Oh sorry, my mistake. In the program, press CTRL+Shift+G, type DEBUG_INFO and press Let's Go. The folder with the debug zip file should be opened automatically, but if it doesn't, it should be in %APPDATA%/Local/Temp/gpmdp_debug_info (be sure to go into AppData if you are in the Roaming folder instead)

**Comment by jhw866** [comment]
This seems to be fixed in the latest release

**Comment by MarshallOfSound** [comment]
> This seems to be fixed in the latest release

I'll take it 😆 👍 🎉
