### ISSUE TITLE
[Feature Request] Hot key support to focus search bar

### ISSUE THREAD

**Issue by atelic** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3110]
**OS:**
macOS High Sierra 10.13.4

**GPMDP Version:**
4.5.0

**Issue Descriptions:**
I would like to be able to focus the search bar with a hotkey. I have tried the usual shortcuts (⌘-F, ⌘-L) but they don't work. It would be nice to configure my own.

**Steps to Reproduce:**
Open GPMDP.
Navigate to Home or an Album or any screen with the search bar up top.
Hit ⌘-F or ⌘-L.
Expect the search bar to be in focus but this does not happen

**Comment by jostrander** [comment]
I believe Google's is `/` by default.

**Comment by atelic** [comment]
I wasn't aware of this one. Not bad but it'll just take some re-training. Thanks for the workaround.
