### ISSUE TITLE
Very slow and laggy on windows

### ISSUE THREAD

**Issue by fluorescentb** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3118]
**OS:**
Windows 10
**GPMDP Version:**
Can't open it, but re downloaded yesterday 
**Issue Descriptions:**
Every time I open it after a restart it works perfectly. But about 10 minutes in it gets very laggy and even just bringing the window up takes 30 seconds. Once the window opens it takes another 30 seconds for Windows to notice that the program Window is active
**Steps to Reproduce:**
open the software?

**Comment by dannybrussy** [comment]
Also experiencing this issue in the same timeframe. Started yesterday, I have updated and problem persists. Open program and in 2 minutes the program is VERY laggy. Seemingly progressing by a frame every 5 seconds. Music playback however is perfect. Desktop notifications are turned off (default in new v. anyway I think?)

**Comment by fluorescentb** [comment]
Another thing is that this has been occurring on multiple versions of the software. I keep coming back to it but it always has the same issue.

**Comment by jostrander** [comment]
System specs?

**Comment by Fluhzar** [comment]
I am also experiencing the same issue. V4.5.0, though it has been happening to me for several different version on both Linux (Kubuntu) and Windows 10. Even though the window is very slow to respond, I haven't experienced any skipping or buffering of the music as it plays. My computer specs:

Ryzen 1700X (stock clock)
16GB RAM
Booted off SSD
Nvidia GTX 980

Looking at Task Manager while this is happening, I see GPMDP is using 1,250MB of RAM, most of that coming from one process (TM shows 4 processes). Even opening the settings window (which I believe is its own process) and attempting to interact/move the window is very slow. Here's a list of the settings I have enabled:

Minimize to Tray
Keep album art static in visualizer
Dark Theme (w/ custom color)
JSON API
Playback API
Windows 10 System Media Service
Show track info in Win10 volume overlay
Discord Rich Presence

I didn't have Discord open when the GPMDP slow-down was happening. And now  I've just tested restarting GPMDP with Discord open and the slow-down is not as apparent, and the memory usage reported in TM is now at only 200MB. Perhaps there is something to be checked in regards to how often GPMDP polls Discord for a connection? Or some other inefficiency in regards to Discord Rich Presence?

**Comment by markgambardella** [comment]
Disabling Rich Presence seems to fix this problem, at least for me.

**Comment by fluorescentb** [comment]
same here

**Comment by fluorescentb** [comment]
same here, something to work on but the issue is fixed for now

**FIX**
When not using Discord, make sure to turn off Rich Presence and restart the program. When using Discord, using Rich Presence doesn't seem to have such a big effect.

**Comment by Fluhzar** [comment]
That's not a fix. That's a workaround. A fix happens when you fix the issue, a workaround is a temporary fix to make your software usable while you work on a fix. Don't just ignore your issues
