### ISSUE TITLE
Forward/backward shortcut

### ISSUE THREAD

**Issue by jancoow** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3122]
Hi,

A common used shortcut for moving backwards and forwards between pages is not implemented.
Forward: <kbd>alt</kbd> + <kbd>&rightarrow;</kbd>
Backwards: <kbd>alt</kbd> + <kbd>&leftarrow;</kbd>

This is for example used in Chrome, Firefox and Nautilus. It would be great if this could be implemented. 

**OS:**
Arch Linux

**GPMDP Version:**
4.5.0-2

**Comment by iangmaia** [comment]
This was actually working on Mac, but with cmd + -> / cmd + <-.
On the latest version, it unfortunately has been broken.

**Comment by xthom** [comment]
+1

Also the "<-" button dissapeared from the search input. No possibility to navigate through the UI :(

**Comment by TwitchyBeast** [comment]
Thought my mouse broke, but yeah, it definitely seems like forward and back are broken :[

**Comment by MarshallOfSound** [comment]
Duplicate, fixed in master

**Comment by jancoow** [comment]
Still not fixed. The XF86Back and XF86Forward (A.K.A. alt + left array and alt + right arrow) still not working. I mapped this to my mousepad gesture and it's working in almost every application, expect the gpmdp.
