### ISSUE TITLE
GPMDP is eating my RAM

### ISSUE THREAD

**Issue by TehCrazyCat** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3124]
**OS:**
Windows 10, 1709 (16299.431), 64 bits.

**GPMDP Version:**
Latest, v4.5.0

**Issue Descriptions:**
As soon as I open GPDMP, the app keeps getting slower until it stops responding. I had to close the program with Windows Program Administrator and then I realized it was using about 1.8 GB of RAM. Tried opening it again with WPA open, and GPMDP was increasing its RAM usage by aprox. 2 MB per second.
I didn't had this issue in the previous version. I used the Windows Store version before, but since I got a weird bug I reinstalled with the .exe version.

**Steps to Reproduce:**
Just... open the app... magic I guess?

**Comment by jostrander** [comment]
Discord rich presence enabled?

**Comment by TehCrazyCat** [comment]
Oh wow, it was on... I don't remember turning that on. Seems that was the problem, thanks.
