### ISSUE TITLE
Login Screen sandbox break

### ISSUE THREAD

**Issue by m10653** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3127]
Hello, so I found an issue with the login screen that first appears when you start the app. It allows you to break outside of the login screen and use the application as a web browser. This has some security implications of being able to make the application load arbitrary websites.

How to reproduce.

Start the app with no user logged in and press the login button.
When at the login screen click the found my account button.
Then click the Request google's help button.
Then in the top of the screen click the apps grid button and select search.
Boom you have a search engine.

Proposed fix to this is to whitelist allowed URLs.

**Comment by MarshallOfSound** [comment]
We can't whitelist urls as some people use SSO services to sign in to their Google accounts.  This issue only occurs if users do this to themselves and it isn't a major security issue (nodeIntegration is disabled in the renderer).  Users should know not to browse the web in a log in window :P

**Comment by m10653** [comment]
Glad you saw the humor in it. The only issue is there is no back button. So I have to restart the app the login. It's tragic.  You must be able just to blacklist the find my account link to fix the issue :P 

Thanks for the speedy response also nice little app!
