### ISSUE TITLE
Discord Rich Presence is far too long

### ISSUE THREAD

**Issue by markispro** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3130]
**GPMDP Version: 4.5.0**

Discord integration is cool! However, with the default width of the sidebar, information gets cut off a lot. 
The current integration prints out Album before the Album name, which also is confusing.

This is how it currently looks (the song is Lose It, by the artist Flume, from the album Skin)
![capture](https://user-images.githubusercontent.com/14097023/40291369-df8f7c10-5c81-11e8-820d-e67089cec96d.PNG)

My Suggestion
![capture2](https://user-images.githubusercontent.com/14097023/40291439-4f9326f6-5c82-11e8-8d8c-42bf0d9dab1b.PNG)

Or alternatively
![capture3](https://user-images.githubusercontent.com/14097023/40291479-79f398cc-5c82-11e8-86f1-94ff7242dad4.png)

**Comment by Evanito** [comment]
This was (very similarly) implemented almost **four** months ago in #2991, which is not in the most recent release.

So:
1) This issue should be closed but thank you for making it. ❤️ 
2) Core Devs, please release a new version for the love of god.

**Comment by jostrander** [comment]
@Evanito Trying to push for a release schedule, but I don't have access to the signing keys, or the servers, etc. see #3137. 
@markispro This has been fixed in master in #2991, but has not been published.
