### ISSUE TITLE
Indicator tray icon not showing in Ubuntu Bionic (18.04) 

### ISSUE THREAD

**Issue by celsoandrade** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3133]
Indicator tray icon not showing in Ubuntu Bionic (18.04) installed with snap

**Comment by Kandelai** [comment]
Just to note, this may not be a bug. If you want to see the Indicator tray icon in Ubuntu Bionic or any other distribution running Gnome, the Google Play Music indicator shows under the legacy indicators, meaning you need to install and activate the Gnome extension TopIcons Plus from [https://extensions.gnome.org/extension/1031/topicons/](url) . I am sure you missing several icons if you don't have this extension installed.

**Comment by MarshallOfSound** [comment]
As @Kandelai pointed out GPMDP uses the "legacy" appindictor style tray icons, you'll probably have to install appindicator or whatever other "legacy" gnome extensions you'll need to support this

**Comment by nottoseethesun** [comment]
I just needed to do `sudo apt install gnome-shell-extension-appindicator` and restart gnome.

**Comment by thvasilo** [comment]
Does anyone know of a solution for Unity? `sudo apt install gnome-shell-extension-appindicator` does not work in that case.
