### ISSUE TITLE
feature requst:Lyrics on full page

### ISSUE THREAD

**Issue by timmee2222** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3136]
In the future how would an option of the lyrics being static on one page? currently the scrolling doesn't match up with most of my songs
Cheers
Stephen

**Comment by jostrander** [comment]
This is already an option

**Comment by jostrander** [comment]
![image](https://user-images.githubusercontent.com/760989/40690709-2ee39666-6376-11e8-9df3-bd151e2a9bb9.png)

Disable scroll lyrics automatically if it is checked. That will stop the lyrics from auto scrolling and allow you to manually scroll them.

**Comment by timmee2222** [comment]
thanks - couldn't see for looking 8-)
