### ISSUE TITLE
Sign-in freezes before two-step verification window on Linux Mint

### ISSUE THREAD

**Issue by toscasound** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#314]
When you try to sign in with Linux Mint having two-step verification enabled for your Google account, the screen freezes before the two-step verification screen opens, with some grey squares appearing in the corners of the screen, but otherwise the content remains as the previous password enter screen (image 1). If I then resize the window for example, the other parts of the screen turn into black (image 2), but there seems to be no way of going forward from that point.

I tested this with OSX yesterday and the login worked fine with two-step verification enabled there.

![image](https://cloud.githubusercontent.com/assets/17698071/13563209/7ab4aad0-e448-11e5-9bd9-ea9f773f7ef1.png)

![image](https://cloud.githubusercontent.com/assets/17698071/13563278/1d288494-e449-11e5-8470-4e533990f6ab.png)

**Comment by MarshallOfSound** [comment]
On linux it appears the `--disable-gpu` is required for some flavors.

**Comment by MarshallOfSound** [comment]
Closed because I am like 100% that flag will work :+1:

**Comment by toscasound** [comment]
You're correct, it did work. Thanks for the quick help!
