### ISSUE TITLE
Weird superscript with lowercase s and t when using Windows 10 System Media Service

### ISSUE THREAD

**Issue by markispro** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3141]
**OS: Windows 10**

**GPMDP Version: 4.5.0**

**Issue Descriptions:** Weird text superscript on Windows 10 media integration when a song has a lowercase s and t next to each other

**Steps to Reproduce:**

 Find a song with a lowercase s and t next to each other.

Enable Windows 10 Media Integration

![image](https://user-images.githubusercontent.com/14097023/40802468-ea437ae0-64d2-11e8-9df1-ec14e2eed932.png)

![image](https://user-images.githubusercontent.com/14097023/40802801-e9ecc5dc-64d3-11e8-914f-6e80487a75c3.png)

![image](https://user-images.githubusercontent.com/14097023/40802969-6e8cc648-64d4-11e8-88da-52cfaebdf4af.png)

**Comment by jostrander** [comment]
What is your system language out of curiosity?

**Comment by markispro** [comment]
English (en-us)

I have changed my system font, but it doesn't seem to affect a lot of Windows 10 apps

**Comment by SolarLiner** [comment]
Does the st stuff happen somewhere else as well, in the "core" Windows 10 stuff? Does it happen anywhere else at all?
I'm thinking about this being a ligature more than a weird superscript, but that could also be some Unicode diacritics going wrong.

**Comment by markispro** [comment]
This is the first place I've seen it, but I'll keep an eye out

**Comment by jostrander** [comment]
Is this still an issue on 4.6.0?

**Comment by myfrom** [comment]
I had this bug previously but it seems to be fixed now. GPMDP 4.6.1, Windows 10 v1803

**Comment by markispro** [comment]
I forgot about this bug honestly (media integration broke on my machine for some reason) but with the latest version it appears to be fixed

![image](https://user-images.githubusercontent.com/14097023/44619057-ef88ee00-a83d-11e8-9c62-187cb8f2841b.png)

**Comment by SolarLiner** [comment]
It definitely looks like a different font. Really I'm not sure it would be related to the player. Does anyone know if we can push HTML or alike to the media controls on Windows?
