### ISSUE TITLE
Feature Request - allow offline mode for personal songs only

### ISSUE THREAD

**Issue by vityou** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3142]
I know that it isn't possible to download songs you don't own without there being an official API.  But if I understand correctly, you can still download songs you bought or uploaded yourself.  My feature request would be to have the option the make a playlist/album available offline, but only make songs that the user owns available offline.  There exists already a feature that lets you download individual songs, but this doesn't preserve playlist or album structure, and the songs cant be played within the player.  This would greatly help people who use google play music to upload their personal collection.

**Comment by jostrander** [comment]
This isn't going to happen unfortunately. We don't support any kind of offline playback within this application because it's simply a wrapper around the web version, which you need internet access for. We don't have access to the "api" needed to download and maintain a local copy of the music.

**Comment by ahmedhamdy90** [comment]
I just need to understand it clearly, you have no access to this API because you are unable to? Because this is an unofficial build, right? 
On Android, you can make a playlist offline. I just need to know what we can do to make this feature doable, I will help as much I can.

**Comment by jostrander** [comment]
Correct. We are just using the music.google.com site and adding our own themes and functionality where possible.

**Comment by ahmedhamdy90** [comment]
@jostrander Is there any way we can request the API usage from Google?

**Comment by jostrander** [comment]
No unfortunately. There is no public API.

**Comment by vityou** [comment]
Even if there was, they would have to implement a completely new app that works offline, as it is currently just a wrapper around the website.
