### ISSUE TITLE
Youtube Music Desktop App?

### ISSUE THREAD

**Issue by hiya-tiger** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3144]
Google is discontinuing Google Play Music, will there be a Youtube Music (music.youtube.com) Desktop Player?

**Comment by MarshallOfSound** [comment]
Duplicate #3103 

Pending access to youtube music

**Comment by jostrander** [comment]
I just got the email, you may soon as well, as my email says its available in NZ and AU @MarshallOfSound
