### ISSUE TITLE
../src/mdns.hpp:32:10: fatal error: dns_sd.h: No such file or directory  #include <dns_sd.h>

### ISSUE THREAD

**Issue by roberto68** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3148]
**OS:**
OS: Linux (fedora 28)
**version:**
vesrion 4.5.1

**Issue Descriptions:**
npm install error
`
> dbus@0.2.18 install /home/roberto/bin/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/dbus
> node-gyp configure build

Package dbus-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `dbus-1.pc'
to the PKG_CONFIG_PATH environment variable
Package 'dbus-1', required by 'virtual:world', not found
gyp: Call to 'pkg-config  --libs-only-l --libs-only-other dbus-1' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/roberto/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.16.13-300.fc28.x86_64
gyp ERR! command "/home/roberto/.nvm/versions/node/v8.11.2/bin/node" "/home/roberto/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/roberto/bin/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/dbus
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

> mdns@2.4.0 install /home/roberto/bin/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/mdns
> node-gyp rebuild

make: Entering directory '/home/roberto/bin/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:
../src/mdns.hpp:32:10: fatal error: dns_sd.h: No such file or directory
 #include <dns_sd.h>
          ^~~~~~~~~~
compilation terminated.
make: *** [dns_sd_bindings.target.mk:153: Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
make: Leaving directory '/home/roberto/bin/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/mdns/build'

`
I've checked this issue https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/1314 but it is not the problem I've avahi installed

**Steps to Reproduce:**
just run npm install

It is seems like a problem with dbus config path right?

**Comment by jostrander** [comment]
Do you have the dev dependencies installed?

**Comment by jostrander** [comment]
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/Development-FAQ

**Comment by jostrander** [comment]
Do you have avahi dev? It seems to be missing mdns_sd.h which is usually only supplied in the dev package.

**Comment by roberto68** [comment]
installed avahi-devel result still the same I cannot find dns_sd.h anywhere

**Comment by jostrander** [comment]
What about dbus devel?

**Comment by roberto68** [comment]
`
ok so I did
`
yum install avahi-compat-libdns_sd*.x86_64
`
yum groupinstall "X Software Development"
`
got couple of warnings but rebuild successful !!!

**Comment by stefan52a** [comment]
on ubuntu:
sudo apt install libavahi-compat-libdnssd-dev
worked for me
