### ISSUE TITLE
Very weird issue with windows mixer

### ISSUE THREAD

**Issue by Meegooo** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#315]
http://i.imgur.com/LxwtVNj.png
I am literally confused about what's going on. The slider, the text on the right and the icon are invisible. Slider still works btw, you just can't see it. 
I've never encountered this before and it would seem that this is windows bug that could randomly appear for any app. But it does that consistently and only with GMusic player. And only after the update to 3.0.0. 
I can't even think of anything that could've possibly caused that.

PS. Using Windows 10

**Comment by MarshallOfSound** [comment]
I've noticed this as well, I have honestly no idea how that is even a thing.  Could you please raise this as an issue against electron and see what they have to say.  I don't see how it can be down to my implementation :+1: 

Link back here if you do :+1:

**Comment by MarshallOfSound** [comment]
Closing as its an electron bug
