### ISSUE TITLE
Media keys proc twice if "Show track information in Windows 10 volume overlay" is enabled

### ISSUE THREAD

**Issue by CorruptComputer** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3156]
**OS:** Windows 10 build 17692

**GPMDP Version:** 1.5.0

**Issue Descriptions:** If you turn on "Show track information in Windows 10 volume overlay" as well as "Enable the Windows 10 System Media Service" the media keys will count twice and cause it to either skip 2 songs or instantly pause/play. 

**Steps to Reproduce:** ^

**Comment by MarshallOfSound** [comment]
Known and fixed in master

**Comment by CorruptComputer** [comment]
Any new on when we'll get the update? 1.5.0 has been out for months now.

**Comment by ddecator** [comment]
FYI, not sure if the fix should be in v4.6.0, but the problem still seems somewhat present. With both of those settings enabled, I don't get the double play/pause, but there is double track skipping on (at least on YTM). Disabling showing in the volume overlay fixes the problem.
