### ISSUE TITLE
Loud clicking

### ISSUE THREAD

**Issue by Scienceismahgame** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3157]
**Windows 10:**

**Control panel says 4.5.0:**

**Loud clicking noise issues when starting up and when attempting to play music:**

**closed the program, killed the processes and restarted the computer:**

**Comment by MarshallOfSound** [comment]
Any sound artifacts will be a result of either your drivers or chromium, not this player.

When we update Electron you may notice an improvement

**Comment by Scienceismahgame** [comment]
Alrighty I appreciate it. It just came outta nowhere so I was uncertain if there was a update conflict or what.
