### ISSUE TITLE
GPMDP is being extremely laggy.

### ISSUE THREAD

**Issue by SarahMaroon** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3163]
OS: Windows 10

GPMDP Version: v.4.5.0

Issue Descriptions: Program becomes extremely laggy and unusable after a few minutes of listening to music. I do not have the Desktop Notifications turned on. Not sure if this is just the Windows 10 bug that was talked about or something else. 

Steps to Reproduce:
1. Open GPDMP
2. Play a song from the Songs tab
3. Click off the program, then work in my art programs such as Photoshop as music plays in background
4. Click back on GPDMP after around 5 minutes and the program takes at least 30 seconds to respond to any action taken such as scrolling, clicking the Next button ect.

[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/2130115/debug_info.zip)

**Comment by jostrander** [comment]
Turn off discord rich presence, see issue #2969

**Comment by SarahMaroon** [comment]
Thank you very much!

**Comment by DGxInfinitY** [comment]
Same here on elementaryOS Loki(based on Ubuntu 16.04) with Kernel 4.17 and latest Gen Hardware. I get the exact same problem. I first thought it was an electron problem but later concluded after some testing that the problem goes away after disabling Discord Rich Presence Integration. It appears to be making way to many requests to hook into discord and causes the program to just lag.
