### ISSUE TITLE
Media controls not appearing on touch bar (macOS X)

### ISSUE THREAD

**Issue by samperlmutter** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3164]
**OS:**
macOS v10.13.4
**GPMDP Version:**
4.6.0
**Issue Descriptions:**
I have a Macbook Pro with a touch bar, and when you play music from any app, the system adds a persistent button to the touch bar that provides a scrubber and media controls (I've attached pictures). When updating from version 4.5.0 to version 4.6.0, these media controls never show up, but if I directly download version 4.6.0 from github, they do. The media controls are also always visible in version 4.6.0. I've attached debug zip files for the app when upgrading from 4.5.0 to 4.6.0 in case there's a difference.
**Steps to Reproduce:**
See above.
[debug_info_direct_download.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/2130536/debug_info_direct_download.zip)
[debug_info_from_updating.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/2130537/debug_info_from_updating.zip)
![img_20180624_022026](https://user-images.githubusercontent.com/6434256/41816594-42ada96c-7757-11e8-8672-fb95b14a2d22.jpg)
![img_20180624_022125](https://user-images.githubusercontent.com/6434256/41816595-42b743d2-7757-11e8-910c-e607282cf9df.jpg)

**Comment by MarshallOfSound** [comment]
This is strange because the update just replaced the application in place.  Can you update, then restart your machine and see if the issue persists?

**Comment by Lumpenstein** [comment]
Had the same problem, restarting the machine solved it. I doubt it is related to GPMDP, since I had the same issue for iTunes.

**Comment by MarshallOfSound** [comment]
Sounds like an OS issue or something, if this issue is more wide-spread or unfixable I'll reopen this

**Comment by Impakt** [comment]
@MarshallOfSound I'm trying to get similar functionality to this working on an app im currently adding features to. Can you shed some light on the APIs I need to use in order to report to MacOS the current playback position and add scrubber functionality to seek?
