### ISSUE TITLE
Unable to use back/forward mouse buttons for the history.

### ISSUE THREAD

**Issue by Gimbergsson** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3166]
**OS:** Windows 10 Pro, Version: 1803, Build: 17134.112

**GPMDP Version:** 4.6.0

**Issue Descriptions:** Unable to use mouse back/forward buttons to go back and forward in the history.

**Steps to Reproduce:** Install the latest version 4.6.0 and try using the back/forward mouse buttons.

**Comment by Gimbergsson** [comment]
Downgraded to 4.5.0 and the back/forward mouse buttons seems to be working fine there, so there must be something in 4.6.0 that causing that not to work.

**Comment by MarshallOfSound** [comment]
This is caused by an unhandled exception in the discord rich precense feature.  I'll look at fixing it tomorrow and releasing a patch
