### ISSUE TITLE
'back' button missing and duplicate 'mini player' button after updating

### ISSUE THREAD

**Issue by dags-** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3167]
**OS:**
macOS High Seirra - 10.13.6 Beta

**GPMDP Version:** 
4.6.0

**Issue Descriptions:**
Just noticed these ui bugs after updating to 4.6.0, not sure if they were present previously.

- 'back' nav button missing from search bar
![screen shot 2018-06-24 at 10 54 27](https://user-images.githubusercontent.com/4276064/41818011-2ffd6dc4-779e-11e8-8dee-31d93387901c.png)

- duplicate 'show mini player' button in controls bar
![screen shot 2018-06-24 at 10 44 34](https://user-images.githubusercontent.com/4276064/41818016-3cebc1de-779e-11e8-88a5-2deb957ae384.png)

**Steps to Reproduce:**
Open the app

**Comment by nooplak** [comment]
I'm having the same issues after the latest update running on Windows 10 - v. 1803 build 17134.112

Unfortunately the absence of a back button breaks this app for me, as I dive down a lot of rabbit holes to find new stuff.

**Comment by nickleur** [comment]
I'm having the same issue after the update to 4.6.0. 

In addition my thumbarbuttons are also missing after this update.

System is Windows 10 Pro - v. 1803 build 17134.112

**Comment by charlwillia6** [comment]
I also am confirming this is an issue in Linux also, Manjaro.

**Comment by jostrander** [comment]
Unrelated to platform, and it's already fixed.
