### ISSUE TITLE
Discord rich presence broken with newest update

### ISSUE THREAD

**Issue by Marshall126** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3170]
**OS:**
Windows 10 64
**GPMDP Version:**
4.6.0
**Issue Descriptions:**
Discord rich presence with GPMDP no longer works after the newest update, instead, the game playing shows as the artist of the song.
![screenshot 88](https://user-images.githubusercontent.com/34991562/41820419-387a492e-7797-11e8-8f10-31b8c9b44494.png)
For example, La Roux, the artist of the song I was currently listening to, is displayed as the name of the app in discord.
When selected, it looks like this
![screenshot 89](https://user-images.githubusercontent.com/34991562/41820433-75dc7fda-7797-11e8-9920-9861a0f7b0b4.png)
**Steps to Reproduce:**
Start playing a song in GPMDP and then add it as a game on Discord

**Comment by kroppt** [comment]
I also have this issue with the same version and OS. I enabled Discord Rich Presence integration in Desktop Settings, but it does not automatically hook into Discord.

I tried different permission levels (Admin vs User) in every combination with Discord and GMDP.

Disabling/enabling other API settings also does not make it work.

**Comment by yuukieve** [comment]
This issue is also present in the Fedora 64-bit build, Discord does not pick up GPMDP's Rich Presence support.

**Comment by NovaPhoenix** [comment]
Same issue here on Windows, it just doesn't connect at all

**Comment by outpoints** [comment]
Same :/

**Comment by Outsanity** [comment]
I can say I just recently updated it to the newest version today and the Discord info does not show. It stills shows on the older version which is still accessible on my PC.

**Comment by kroppt** [comment]
@Outsanity A fix seems to have been added, but we will have to wait for next release (>4.6.0) to use those changes.

**Comment by outpoints** [comment]
@Outsanity You can compile your own version and that will show up on Discord, but until then you'll have to wait
