### ISSUE TITLE
2-factor Authentication USB Token doesn't work

### ISSUE THREAD

**Issue by jchenVT** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3172]
**OS:**  
Windows 10
**GPMDP Version:**
4.6.0
**Issue Descriptions:**
2-Factor Authentication With USB token/key doesn't work.  When trying to use a key, inserting the key and pressing the button doesn't work.  Generally when the key is working, it will flash when it is prompted.  It does not do so however when logging in to GPMDP.
**Steps to Reproduce:**
Login to Google account with USB key set as primary 2-factor authentication in app
Once it asks to use the token, inserting the token and pressing the button doesn't work.

**Comment by MarshallOfSound** [comment]
This is a known upstream Electron issue, you should use the back up 2 factor code generator instead 👍
