### ISSUE TITLE
Cannot cast YouTube music (GPM casting works fine)

### ISSUE THREAD

**Issue by hailwood** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3173]
**OS:** Any

**GPMDP Version:** 4.6.0

**Issue Descriptions:**
Cannot cast YouTube music

**Steps to Reproduce:**
Launch GPMDP, Select YouTube Music from taskbar menu
Play a song
Look for cast button

**Additional:**
I understand this is an alpha version of YouTube Music support, consider this a feature request as the browser interface also doesn't have cast support unless you cast the tab :) (which could be a viable workaround if you can cast an electron window?)

**Comment by MarshallOfSound** [comment]
This will automatically start working once ytm has implemented cast support in their web version.

Our casting for gpm just provides the Google cast API to the website, doesn't actually call the logic.  The same will apply to ytm
