### ISSUE TITLE
Back button missing in 4.6.0

### ISSUE THREAD

**Issue by shadowboy813** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3176]
The app *really* needs forward/back navigation buttons.

How to navigate (specific example)
1: Select an artist
2: Go to albums (or library)
3: Choose an album
4: No go back to the albums (or library)

In order to achieve step #4 it takes multiple steps (you have to go back to step 1, whereas a back navigation button would directly take you back to step 2).

It makes navigating cumbersome to have to manually click links to cycle back to where you just were a second ago.

Secondary suggestion: Add an option to select to use either Google Play Music or YouTube Music (since GPM will eventually be dissolved).

**Comment by MarshallOfSound** [comment]
There is a back button but it's broken on the latest release.

**Comment by shadowboy813** [comment]
Ok, I knew there was one before, but I guessed it was removed for some reason. Thanks for the reply!

**Comment by TurbinoZ100000** [comment]
Alt + left arrow used to work as well in previous version, doesn't anymore.

**Comment by baseigneurie** [comment]
I just updated to 4.6.0 this morning (6/26) and I an now missing the back button (previously found in the search bar) too. 

1. Select Podcasts
2. Select "Your Podcasts"
3. Select podcast I want to listen to.
4. Play the episode.
5. If I want to go back to all of my podcasts, I have to start over from step 1.

Current OS: Windows 10 - Version	10.0.15063 Build 15063

**Comment by jostrander** [comment]
Yes. The back button will return. It was an oversight caused by a different bug. It will be fixed in the next patch release.

**Comment by altonius** [comment]
thanks @jostrander , looking forward to this being fixed too

**Comment by pieter-biesemans** [comment]
This issue is bigger than just the missing Back button, I'm guessing it's just a symptom. Before I could navigate just like in any browser (i.e. back button, custom mouse button, backspace, alt+left), but now none of these work. Hopefully full navigation possibilities will be restored in the next update.

**Comment by jostrander** [comment]
Yes, it's all related. None of the code for that was loaded in due to an exception that wasn't handled.

**Comment by Sven62** [comment]
Any idea when the fix will be released? I am not using it like it is.  Is there a way to go back to the previous version?

**Comment by jostrander** [comment]
The patch is pushed to master, just waiting for @MarshallOfSound to release.

**Comment by BatmanAoD** [comment]
@jostrander I know, hence my "release with the code in master" question. Looking at the release history, it appears that even patch releases are pretty few and far between.

**Comment by MarshallOfSound** [comment]
@BatmanAoD Releasing is Hard(tm).  Every update I push out I have to test locally on 3 platforms and 2 arches for each platform to be 100% that it doesn't put you into a bricked state.  This takes time and I have **a lot** of things on my plate right now, unfortunately this is not at the top of the list.  But it will get there.

**Comment by BatmanAoD** [comment]
Okay, fair enough. I'll try just building the `master` on my own and see how that goes.
