### ISSUE TITLE
Youtube Music button not visible for certain countries

### ISSUE THREAD

**Issue by Lumpenstein** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3178]
**OS:**
iOs High Sierra
**GPMDP Version:**
4.6.0
**Issue Descriptions:**
Can't see/find Youtube music button
**Steps to Reproduce:**
Being blind ? (Wasnt a clean install but I upgraded to the latest version)

Hello,

may it be that the youtube music button in the tray menu is hidden for countries where the service hasn't been launched yet (I'm from Luxembourg)  ? 

Best regards,
Lumpi

**Comment by Wolfscopez** [comment]
I'm from New Zealand and I'm also suffering the same issue, although YouTube Music has released in New Zealand.

**Comment by jespersh** [comment]
Visit https://music.youtube.com/ to see if it available in your country

**Comment by Lumpenstein** [comment]
@jespersh  I know YTM is not available in my country, just curious if the Button is supposed not to be displayed in this case or if it is a bug.

**Comment by MarshallOfSound** [comment]
The button should be displayed in all countries

**Comment by Lumpenstein** [comment]
![image](https://user-images.githubusercontent.com/20638284/41845370-901c84f8-7873-11e8-9a41-ace471d938fd.png)

**Comment by avgdev** [comment]
I am from India and I cannot see the Youtube Music icon as well.  Maybe I am not looking in the right place. Where on the UI should I see it

**Comment by stryju** [comment]
I have to say that it's either impossible to find on macOS, or it's really well hidden... I'm in UK, where the service is launched, so this doesn't seem to be a factor.

![screen shot 2018-06-26 at 4 33 06 pm](https://user-images.githubusercontent.com/25367/41923154-a74c0dba-795e-11e8-9983-9f4c72758114.png)
![screen shot 2018-06-26 at 4 33 58 pm](https://user-images.githubusercontent.com/25367/41923202-c0eb5ffa-795e-11e8-8be0-facf1a12d4bc.png)

**Comment by MarshallOfSound** [comment]
@stryju You aren't on the latest release 😄

**Comment by n8carrier** [comment]
The latest release is 4.6.0? I just got an update that said it included YouTube Music, but I also can't find it. My screens match those @stryju posted. I've clicked every link thinking I might just be blind...

**Comment by jerwarren** [comment]
I don't have any UI in the main window for YouTube Music either, but I did eventually find it in the system tray rightclick menu.  Where is it supposed to appear in-app?

**Comment by stryju** [comment]
I'm @ `4.6.0`, which seems to be the latest one?

![screen shot 2018-06-26 at 6 00 34 pm](https://user-images.githubusercontent.com/25367/41927709-d9550b02-796a-11e8-8ca6-8194fc0ef44d.png)

**Comment by jerwarren** [comment]
![screen shot 2018-06-26 at 10 01 24 am](https://user-images.githubusercontent.com/3248208/41927757-eeb53fb4-7927-11e8-84dd-b133166f1912.png)

**Comment by stryju** [comment]
@jerwarren I would've never found this icon... thanks!

**Comment by n8carrier** [comment]
Ooh that's where it is, thanks. Suggestion: Place a link in the sidebar where "Desktop Settings" is that says "Switch to YouTube Music".

**Comment by cpetzel** [comment]
I also could not figure out how to get into youtube music. Please add a menu item to get into the service!

**Comment by MarshallOfSound** [comment]
We probably will add a more prominent button to switch services once YouTube Music support is cleaned up and complete

**Comment by WhyBitcoinCash** [comment]
How can you switch to YT music on Linux? This button is not there (i'm in a YT music country)

**Comment by SeraphDosSantos** [comment]
I'm trying in Elementary OS and cannot see where to switch to YT Music. Can someone help?
