### ISSUE TITLE
Dependency updates

### ISSUE THREAD

**Issue by Stanzilla** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3181]
The project could use a lot of dependency updates, currently the Windows build does not even work. npm audit reports over 40 security vulnerabilities. Is that something you think you will work on in the near future?

**Comment by MarshallOfSound** [comment]
> currently the Windows build does not even work

The windows build does work, literally running it right now 😄 

> npm audit reports over 40 security vulnerabilities

`npm audit` is incredibly noisy, 99% of those "vulnerabilities" are from either dev dependencies or code paths that we literally don't even come close to hitting in a deployed version of GPMDP.

> Is that something you think you will work on in the near future?

This project is open source, PR's welcome 👍 Please be aware that we currently use a `yarn.lock` file to `npm audit` is likely to be inaccurate

**Comment by Stanzilla** [comment]
@MarshallOfSound Sorry, I meant the appveyor build, but that can probably be fixed by removing the installation of npm3 and a switch to a newer node version?

**Comment by MarshallOfSound** [comment]
@Stanzilla Probably 👍 I build the macOS and linux release on CI but the windows releases locally, so I haven't really given any love to the windows CI in a while

**Comment by vaindil** [comment]
I was trying to find the latest builds for Windows (I really want the Discord integration fix, heh), but AppVeyor doesn't have artifacts for any builds, and most of them fail anyway.
