### ISSUE TITLE
Back/Forward mouse buttons stopped working

### ISSUE THREAD

**Issue by PeterLustig** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3182]
**OS:** OS X 10.13.3

**GPMDP Version:** 4.6.0

**Issue Descriptions:** Since the update to 4.6.0, mouse buttons to go back- and forwards don't work anymore.

**Steps to Reproduce:** Update from an earlier version to 4.6.0

**Comment by i4ybrid** [comment]
I can confirm this is happening on my OSX 10.12.6. I'm using the Back/Forward buttons from SensibleSideButtons. It neither works in Youtube Music mode nor in GPM mode. The back button also no longer appears in the UI in the search box like it used to.

**Comment by MarshallOfSound** [comment]
Fixed in master
