### ISSUE TITLE
Missing "Back" Arrow

### ISSUE THREAD

**Issue by breon** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3184]
**OS:**
macOS

**GPMDP Version:**
4.6.0

**Issue Descriptions:**
The back arrow is no longer present in the search box. Users can no longer navigate backwards. They can only go forwards

**Steps to Reproduce:**
* Launch Google Play Music Desktop Player
* Search for a song, artist, album
* Select song, artist, album

**Expected** 
* Back arrow visible 🔙  in search bar

**Actual** 
* No back arrow

**Comment by tjkirch** [comment]
The 'back' hotkey no longer works for me in 4.6.0, either.  This is on Mac OS 10.12, using the command+[ hotkey, and the 'back' mouse button.

**Comment by vecst** [comment]
I'll third a no back arrow this is Windows 10, no back command works either.

**Comment by Fedik** [comment]
I have the same issue with GPMDP 4.6.0 on Ubuntu

**Comment by MarshallOfSound** [comment]
This is fixed in master

**Comment by orditeck** [comment]
@MarshallOfSound Cool stuff, what about a release?
