### ISSUE TITLE
Mini player popout button doesn't work

### ISSUE THREAD

**Issue by katlyn-edwards** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3185]
**OS:**
Linux
**GPMDP Version:**
Most recent - just downloaded it
**Issue Descriptions:**
Popout player button in the playerbar doesn't do anything
**Steps to Reproduce:**
See above

**Comment by MarshallOfSound** [comment]
There are two mini player buttons in this release, you need to click the bottom one.  The extra button will be fixed / removed in the next release
