### ISSUE TITLE
Keyboard shortcuts don't register F[1-9] keys

### ISSUE THREAD

**Issue by katlyn-edwards** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3186]
**OS:**
Linux
**GPMDP Version:**
Most recent
**Issue Descriptions:**
Tried to register the alt of  F3 as play/pause, which is the native play/pause on my keyboard, and it won't register. It looks like none of the F keys register. 
**Steps to Reproduce:**

**Comment by jespersh** [comment]
If it is a laptop, then try holding down fn/Fn key. Some keyboards default to Fn on instead of off

**Comment by jostrander** [comment]
I'm fairly certain that you need to use the modifier key ctrl to register _any and all_ keyboard shortcuts. The reasoning being that the key binds are global, in that you cannot use that key any longer for any other application while gpmdp is open.

**Comment by MarshallOfSound** [comment]
@jostrander is correct

**Comment by katlyn-edwards** [comment]
If you need the ctrl key, that should be mentioned somewhere on the page.
