### ISSUE TITLE
Please update Flatpak-App on Flathub 4.5.0-->4.6.0

### ISSUE THREAD

**Issue by Bohne13** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3187]
**OS:**
Ubuntu 18.04

**GPMDP Version:**
4.5.0

**Issue Descriptions:**
Please Update the Flatpak-App on Flathub! -Thank's!!!

**Steps to Reproduce:**
nothing

**Comment by jespersh** [comment]
Hi, raise the issue here: https://github.com/flathub/com.googleplaymusicdesktopplayer.GPMDP/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by jostrander** [comment]
Thanks @jespersh. Wasn't sure who was maintaining that so couldn't reference anyone as it's not maintained by us.
