### ISSUE TITLE
YTM how to open?

### ISSUE THREAD

**Issue by mu301nh** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3188]
How can to access YTM through the app?

**Comment by ShiroSHAN** [comment]
You can select it in the tray menu
![image](https://user-images.githubusercontent.com/18249551/41914200-ff1214ee-795a-11e8-91ac-1251091b4365.png)

**Comment by mu301nh** [comment]
Thanks on Mac though???

**Comment by jostrander** [comment]
Same thing. There is a tray icon in the upper menu bar.
