### ISSUE TITLE
No Back button

### ISSUE THREAD

**Issue by oliverharrison** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3193]
**OS:**
MacOS High Sierra 10.13.5

**GPMDP Version:**
4.6.0

**Issue Descriptions:**
Back button has disappeared (inside search bar) after update from 4.5.0
(not using any custom CSS)

**Steps to Reproduce:**
Update to 4.6.0. Look at Search box. Cry.

**Comment by jostrander** [comment]
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+back+button

**Comment by oliverharrison** [comment]
I did mean to check the closed issues tab and simply lost track of things as I posted this while at work.

Here's a tip: want less duplicates? Put this very obvious issue right in the ISSUES section on the main page (here: https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#issues) additionally, telling people about it in the popup in GPMDP *before* they update would be useful. 

Finally, if a functionality-breaking bug is present in a new version (that you intend to patch), I would recommend against releasing until it's fixed. Although I appreciate the software, this is simply bad for user experience.

**Comment by jostrander** [comment]
I agree that some wording should be added to the readme to let users know how the issue process works, and how to find their issue. 

As for everything else, I agree, but sometimes things slip through the cracks. With only one person responsible for releasing the software, and no QA other than the CI it's bound to happen. Hopefully we can push forward a patch release soon so that users can have better software.

**Comment by MarshallOfSound** [comment]
> Finally, if a functionality-breaking bug is present in a new version (that you intend to patch), I would recommend against releasing until it's fixed. Although I appreciate the software, this is simply bad for user experience.

It's not like we deliberately shipped something that was broken.... ❓ I didn't sit at home like "Ah yes,  we should release this now with X, Y and Z broken because YOLO" 😆
