### ISSUE TITLE
Missing back button

### ISSUE THREAD

**Issue by unterbdon** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3194]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

Windows 10

V4.6

I see no back button in the UI and the back button on my mouse is not working, either.

Link to Reddit thread with screenshot:

https://www.reddit.com/r/gpmdp/comments/8u3jga/back_button_not_working/

**Comment by MarshallOfSound** [comment]
> YOU SHOULD CHECK CLOSED ISSUES ASWELL

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues?q=is%3Aissue+Missing+back+button+is%3Aclosed

**Comment by unterbdon** [comment]
I see no fixes for the issues that have been posted, just but reports. No resolutions

**Comment by jostrander** [comment]
#3176 points to commit 4328b184acb1e879b3ede3497201876a5308a25e which fixes this issue.
