### ISSUE TITLE
2-steps verification

### ISSUE THREAD

**Issue by alaintxu** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#320]
Hi

I have the 2-steps verification activated in my Google account. I write my email and my password, but it does not appear the next step to insert the verification code. The code is sent to my phone but, as I cannot enter it in the app, I am unable to log in and play the music.

I am using the Linux 64 bit version on Ubuntu 14.04. Does anyone have the same problem?

**Comment by MarshallOfSound** [comment]
Please start the app with the `--disable-gpu` flag

**Comment by alaintxu** [comment]
Thank you, It worked!
