### ISSUE TITLE
Dock icon turns into question mark in MAcOS

### ISSUE THREAD

**Issue by getjams** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3200]
**Checklist:**

* [x ] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x ] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [ x] I have double checked and can reproduce the issue

**OS:** MacOS 10.12.6

**GPMDP Version:** 4.6.0

**Issue Descriptions:** Dock icon turns into a question mark and app won't launch

**Steps to Reproduce:**
1. Launch app
2. Right click dock icon and go to Options > Keep in Dock
3. Exit the app

ER: Icon stays in dock
AR: After a short time, the icon turns into a question mark and the app no longer launches when the question mark is clicked.

**Comment by MarshallOfSound** [comment]
Fixed in master
