### ISSUE TITLE
Play/Pause icons no longer displayed in Windows 10 Taskbar

### ISSUE THREAD

**Issue by roryhewitt** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3201]
On Windows 10, prior to the latest download (4.6.0), when I hovered the mouse over the link in my Taskbar, I would see the Aero popup with a Play/Pause and Next & Previous buttons.

Now, they have disappeared, so I have to actually click and open the GPMDP window to pause or skip a track:

![image](https://user-images.githubusercontent.com/11558891/41990536-8b6008e2-79f7-11e8-8ede-834e4e26b235.png)

**Comment by jostrander** [comment]
This is fixed in master and will be published in the next release.

**Comment by roryhewitt** [comment]
This just started happening again on 4.6.1... :(
