### ISSUE TITLE
No "Back" button after 4.6.0 release.

### ISSUE THREAD

**Issue by Amlor** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3202]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**
Arch Linux, 4.17.2 kernel

**GPMDP Version:**
4.6.0

**Issue Descriptions:**
Until 4.6.0 there was a "<-" button in the search field, which was great for quick navigation, now there is not. Please bring it back if possible.

**Steps to Reproduce:**
1. Try to open some album/artist etc.
2. There should be a back arrow in the search field, but there is not.

**Comment by slaviki** [comment]
I have the same on Windows.
Also key combination to go back doesn't work as well as mouse button

**Comment by MarshallOfSound** [comment]
> YOU SHOULD CHECK CLOSED ISSUES ASWELL

😉

**Comment by jbl0ndie** [comment]
Hey @MarshallOfSound, I see you're getting a lot of duplicates of this, how about setting an issue status that means this issue appears in the is:open list but is marked as resolved, or will be resolved in next release? Something that works for both the developers and the users, like yes you've fixed the code, no it hasn't been released just yet.

That should mean it appears in the default issue search that GitHub does. You'd probably end up with a bunch of "Me too!" posts in one issue but it would likely save you all the duplicate issues.
