### ISSUE TITLE
"Go To Previous Page ( CMD + [ )" is not working

### ISSUE THREAD

**Issue by paddy1228** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3205]
**OS:** Mac OS 10.13.5

**GPMDP Version:** Version: 4.6.0

**Issue Descriptions:** 
Hi There, 

With the most recent update, the "Go To Previous Page ( CMD + [ )" is not working. I usually use ( CMD + [ ), but I also tried "Previous Page" from the "View" menu with no luck there either.

**Steps to Reproduce:**
( CMD + [ ) or clicking on "Previous Page" from the "View" menu.

Thanks,

Patrick

**Comment by MarshallOfSound** [comment]
Fixed in master

**Comment by paddy1228** [comment]
Brilliant! Thanks

Patrick Nel
design@patricknel.com +4475 263 17400
patricknel.com [https://patricknel.com/] LinkedIn [https://www.linkedin.com/in/patrick-nel-51084111/]
On Thu, Jun 28, 2018 at 15:59, Samuel Attard <notifications@github.com> wrote:
Fixed in master
