### ISSUE TITLE
Feature Request: Like/Dislike entire band / album

### ISSUE THREAD

**Issue by RadGH** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3208]
* [x] I have checked that there are no issues with similar or the same content

**OS:** Windows 10
**GPMDP Version:** 4.6.0

I would find it very useful to dislike songs in bulk for the purpose of skipping them in generated stations. How it might work: Click on an artist, go to all songs, menu button to like/dislike all songs. Or that could exist on the main artist page, but it's a little more awkward there.

Without doing it in bulk, it's pretty tedious, as you can see here: https://s3-us-west-2.amazonaws.com/elasticbeanstalk-us-west-2-868470985522/ShareX/2018/06/2018-06-28_21-42-01.mp4

Plus if you miss the dislike button it starts playing the song and interrupts your station! Ugh! That's easy when disliking 100's of songs at once.

I've disliked about a dozen bands by clicking dislike one-by-one. I would love the ability to just right-click on a band or use the menu button and select "Dislike artist". And perhaps just by album, though disliking one album is not a big deal. I usually dislike an entire artist if I don't like them, I don't think I've ever disliked just one album.

This might be a pretty niche feature though. And I hope that Google Play Music adds the feature itself some day. But until then, I thought I would leave another feature request for the **awesome** desktop player!

If you choose not to add it, no big deal either.

Thanks!!

**Comment by jostrander** [comment]
I started to tinker with a way to do this, but there really isn't a worthwhile way to add this into the UI, and make it functional. If someone were to manage to add this I'm sure we'd consider a PR. Thanks for the request.
