### ISSUE TITLE
Manage order of podcast, and continuous-play behavior.

### ISSUE THREAD

**Issue by digitalextremist** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3209]
It would be nice if this could be configured per-podcast, like the native applications; rather than as a "Desktop Setting" applied to all podcasts in `Your Podcasts` but either would be better than neither:

- [ ] Allow sort order to be `oldest-to-newest` rather than the default only: `newest-to-oldest`
- [ ] Allow `continuous-play` to be turned off, so that the player doesn't move on to the next automatically.

**Comment by MarshallOfSound** [comment]
Neither of these are GPMDP features, you should give this feedback on Google Product Forums
