### ISSUE TITLE
Port Conflict - RabbitMQ

### ISSUE THREAD

**Issue by miking-the-viking** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3211]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [ ] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [ ] I have double checked and can reproduce the issue

**OS:**
High Sierra 10.13.5

**GPMDP Version:**

**Issue Descriptions:**

It seems that the default port of 5672 is the same default port used by RabbitMQ. Would it be possible to change the default port?

**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment]
No matter what port we choose it will conflict with something.  We aren't going to change the default port now as it would break a lot of things

**Comment by rsnyman** [comment]
That's a pity. I guess GPMDP has to go.
