### ISSUE TITLE
feature request: notifications / easier way of knowing which track /artist is playing

### ISSUE THREAD

**Issue by arooni** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3212]
**Checklist:**

* [ ] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [ ] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [ ] I have double checked and can reproduce the issue

**OS:** mac

**GPMDP Version:** latest stable

**Issue Descriptions:**

**Steps to Reproduce:**

So often a song is playing that i like; and i want to know what's playing; but because i put your app in a different virtual desktop i don't see the app or mini player.  anyway to add support of which track is playing into the os' notification manager?  i would prefer not seeing a popup for every song change.  

thanks for the great work!

**Comment by jostrander** [comment]
There is a keyboard shortcut to notify the current track if you're interested in that.

**Comment by MarshallOfSound** [comment]
As @jostrander said you can set up a custom global hotkey to display a OS notification for the currently playing track

**Comment by arooni** [comment]
thanks for the quick response; this works great on mac.  but on ubuntu 18.04; when i set a keyboard shortcut i don't see track info.

in addition when i like a track; i don't see any confirmation that the action was successful (ubuntu 18.04)

**Comment by jostrander** [comment]
You may need libindicator installed

**Comment by arooni** [comment]
i *think* its already installed;

[I]  ~  search libindicator
Sorting... Done
Full Text Search... Done
libindicator-dev/bionic 16.10.0+18.04.20180321.1-0ubuntu1 amd64
  panel indicator applet - library development files

libindicator3-7/bionic,now 16.10.0+18.04.20180321.1-0ubuntu1 amd64 [installed,automatic]
  panel indicator applet - shared library

libindicator3-dev/bionic 16.10.0+18.04.20180321.1-0ubuntu1 amd64
  panel indicator applet - library development files

libindicator3-tools/bionic 16.10.0+18.04.20180321.1-0ubuntu1 amd64
  Tools for libindicator

libindicator7/bionic,now 16.10.0+18.04.20180321.1-0ubuntu1 amd64 [installed,automatic]
  panel indicator applet - shared library

**Comment by jostrander** [comment]
What about libnotify4?

**Comment by arooni** [comment]
[I]  ~/.c/f/conf.d  search libnotify4
Sorting... Done
Full Text Search... Done
libnotify-doc/bionic,bionic 0.7.7-3 all
  sends desktop notifications to a notification daemon (Documentation)

libnotify4/bionic,now 0.7.7-3 amd64 [installed,automatic]
  sends desktop notifications to a notification daemon

**Comment by arooni** [comment]
is there some setting that perhaps i've mistakenly turned on that would prevent any and all desktop notifications on ubuntu?  i dont recall seeing one

on my mac everything works great ; issue is only on linux (go figure lol)

**Comment by jostrander** [comment]
Do you have notifications enabled in GPM settings?

**Comment by arooni** [comment]
are you talking about google play music settings, lab settings then

Desktop Notifications
Find out what's playing without having to switch back to your Google Play Music tab. A notification will appear at the start of each song with the song title, artist name, album title, and album cover. Support for this lab is still experimental, and it may not work in all cases.
?

**Comment by jostrander** [comment]
Yes, is that enabled? Just sanity checking to see if we can get notifications to appear at all. Also, are you using gnome on 18.04?

**Comment by arooni** [comment]
Well I just enabled it; and i dont' see any notifications whatsoever.  

and yes using gnome on 18.04; whatever the standard installation calls for (i think thats gnome-shell)

**Comment by jostrander** [comment]
What installation method did you use?

**Comment by arooni** [comment]
i dont remember 100% but pretty sure it was downloading a release from your github release area;

-rw-rw-r--  1 david  david     42M Jun 22 19:19  google-play-music-desktop-player_4.5.0_amd64.deb

**Comment by jostrander** [comment]
Ah, I know 4.6.0 has some other issues, but go ahead and try that one out and see if notifications work.

**Comment by arooni** [comment]
zomg!  it works great!  thanks so much for the rapid response time and the hand holding :). 

this is amazing software btw; i quit using spotify and prefer your app.  and cross platform support via electron.  amazinggggggggggggggggg
