### ISSUE TITLE
Navigation back button gone

### ISSUE THREAD

**Issue by jonokeefe** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3213]
**Checklist:**

* [X] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [X] I have double checked and can reproduce the issue

**OS:**
macOS 10.13.5
**GPMDP Version:**
v4.6.0
**Issue Descriptions:**
Navigation back button gone--no long able to navigate through navigation back stack
**Steps to Reproduce:**
1. Search for an artist
2. Click on a search result
Result: No back button available to return to previous screen (back button previously available within the search bar)

**Comment by BrianAllred** [comment]
> I have checked that there are no issues with similar or the same content

I don't believe you.

**Comment by draxcp6** [comment]
I can confirm for Windows 10 as well, with latest updated there is no way to go back.
