### ISSUE TITLE
GPMDP Remote

### ISSUE THREAD

**Issue by Jeffdog23** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3214]
So I've been trying to get the remote app to find my computer for about an hour, I've made sure the Playback API can bypass the firewall and the app itself can and I've entered my IPv4 address into the app but nothing works, nothing. I just really need a professionals help as I am a noob and have no idea how this works I just want to listen to music.

**Comment by MarshallOfSound** [comment]
We don't give out support in GitHub issues, we don't really give out support anywhere... 😄 

You should try our Gitter channel and ask there, someone might be able to help you out
