### ISSUE TITLE
Cast Icon not Showing

### ISSUE THREAD

**Issue by linusrinke** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3215]
**Checklist:**

* [x ] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x ] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [ x] I have double checked and can reproduce the issue

**OS:** Windows 10 64 Bit

**GPMDP Version:** 

**Issue Descriptions:** 4.6.0

I cannot get the cast icon to consistently display. 9/10 times the cast icon will not be there so I cannot use my Google Home speakers to play music. I've tried installing/uninstalling, resetting Google Home speakers, resetting the modem/router.

![image](https://user-images.githubusercontent.com/33470516/42127508-ba7364fc-7c5f-11e8-8e26-3db7309b7d9c.png)

![image](https://user-images.githubusercontent.com/33470516/42127511-c58577ae-7c5f-11e8-9657-482c71fde193.png)

**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment]
On windows you need to install Bonjour Print Services for casting to work (sounds weird but roll with it)
