### ISSUE TITLE
Windows 10 Volume OSD does not open GPMDP

### ISSUE THREAD

**Issue by TheTripleV** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3217]
OS: Windows 10 (Version 1803, Build 17134)

GPMDP Version: 4.6.0

Issue Descriptions:
Clicking on the Song Info in the Windows 10 Volume OSD does not open GPMDP. It instead makes every application window inactive. Ideal behavior would be making GPMDP show, come to the front, and be active. (The ideal behavior was determined using Groove Music and Movies & TV.)

Steps to Reproduce:
1. Launch GPMDP. (It does not matter if the application is currently windowed, minimized to the taskbar, or minimized to the tray. It does not matter if a track is playing, a track is paused, or no track is playing.)

2. Change the volume on the device to bring up the Volume OSD.

3. Click on the Album Cover image, the track title, or the track artist.

![issuer](https://user-images.githubusercontent.com/11065157/42143745-d70b1cf6-7d84-11e8-824f-f1e3f4f907af.png)

Debug Info: [debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/2153595/debug_info.zip)

**Comment by MarshallOfSound** [comment]
@TheTripleV I can't see an event for this in the docs for this feature on Windows Dev Center

https://docs.microsoft.com/en-us/uwp/api/windows.media.systemmediatransportcontrols

If someone finds the event I need to listen to I'll gladly address this, just @ mention me in a follow up

**Comment by TheTripleV** [comment]
@MarshallOfSound I couldn't find any documentation on this but I think that Windows just tries to activate the process that is tied with system media controls.

In Task Manager, GPMDP has 4 processes. I manually activated each one by PID using AutoHotkey. 1 PID activated GPMDP and brought it to focus. 2 PID's did nothing. The last PID reproduced the issue and made all windows inactive. So, I think that Windows is trying to activate the wrong process.

Note: Activating the gui process also fails and reproduces the issue if GPMDP is minimized to the tray. It only seems to work when the player is open but in the background or minimized to the taskbar.

Thanks!
