### ISSUE TITLE
Icon Issues

### ISSUE THREAD

**Issue by JayToe** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3218]
So I've come across a few issues with the new icon on 4.6.0.
For example: https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3200
And it looks like this on the windows taskbar: 
![98f66a42510e539dcce9c3a7c279d975](https://user-images.githubusercontent.com/37263678/42146047-7b086846-7dc5-11e8-8217-ed2d0e278c8c.png)

I guess it could have something to do with the fact that i exported it as an Inkscape-SVG and not in Illustrator.  I re-exported it in Illustrator here, maybe this will fix the issues:
https://drive.google.com/open?id=1kXbKwrTkIPcPJ3sVN4TJT8OAhXEggYNG

**Comment by MarshallOfSound** [comment]
@JayToe I've fixed these issues on master, cleaned up the SVG and switched to a different SVG->ICO converter.  The next release will contain these fixes

**Comment by ChildishGiant** [comment]
Does this also fix the icon in task manager?
![image](https://user-images.githubusercontent.com/13716824/42394281-7c76e7fe-8151-11e8-9d61-3721340d7d18.png)
