### ISSUE TITLE
Back button

### ISSUE THREAD

**Issue by abugintheground** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3219]
Forgive me if I'm doing something wrong, I'm new here.

It seems that with the latest update to both the Mac and Windows versions, the 'back' feature (either backspace or back shortcut on a mouse) no longer works, and so there's no way of navigating back through the interface

**Checklist:**

* [ ] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [ ] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [ ] I have double checked and can reproduce the issue

**OS:**

**GPMDP Version:**

**Issue Descriptions:**

**Steps to Reproduce:**

**Comment by jostrander** [comment]
This is fixed and not released.

**Comment by jostrander** [comment]
If you grab the latest package from CI then technically you already have it.
