### ISSUE TITLE
Icon glitches when GPMDP is pinned to Windows 10 taskbar

### ISSUE THREAD

**Issue by norweeg** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3222]
**OS:**
Windows 10 Pro 10.0.17134 and 10.0.15063
**GPMDP Version:**
4.6.0
**Issue Descriptions:**
When GPMDP is pinned to the windows taskbar, the top and bottom of the icon get a halo of glitched out black pixels.  I have confirmed this happens on 3 separate PCs.  I have tried un/reinstalling the application and get the same effect.  The glitch only happens if the application is pinned.  It goes away if you unpin the application.

Screenshot illustrating bug: 
![capture](https://user-images.githubusercontent.com/5969754/42220672-a35df486-7e9d-11e8-8adc-9059b515e77c.PNG) Pinned

![capture unpinned](https://user-images.githubusercontent.com/5969754/42220764-f711fb2c-7e9d-11e8-907a-6094abfd9462.PNG) Unpinned

**Steps to Reproduce:**
Open the application, right click its icon on the toolbar, select "Pin to Taskbar"
or
Find start menu shortcut, right click, select "Pin to Taskbar"

[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/2159322/debug_info.zip)

**Comment by MarshallOfSound** [comment]
> YOU SHOULD CHECK CLOSED ISSUES ASWELL

Duplicate, fixed in master
