### ISSUE TITLE
Version 4.6

### ISSUE THREAD

**Issue by bcuraboy** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3223]
Hiya. On version 4.5, the app runs amazing without any hiccups or bugs. 
But, every time it updates to 4.6, and when it reloads, it makes my machine almost inoperable. 
The dock lags, and it takes a long time to skip tracks, I mean like almost 5 seconds.
I have gone back to 4.5, but don't know how, the app keeps updating itself to 4.6
Couldn't find a setting to turn that off.
I'm more than pleased to stay in 4.5 because it just works, but on version 4.6 the system becames laggy. Seems like the app may be consuming more resources than ever, but truth being said, I only have like two or three apps open: Chrome, Play Music, and Franz, another electron app. 
i've tried running only Chrome and Play Music , but the issue persists. 
I'm running Mac Os High Sierra 10.13.5 and the specs of my machine are 12GB of Ram and 256Gb SSD. 
I believe that's plenty of resources to run whatever I need, right??
I forgot to mention: I have to force quit the app to make the system renderable again... 
That doesn't seem right. 
Steps to reproduce the bug: Just by opening the app, choosing an artist, start shuffling, and head back to Chrome. 
Thanks for the attention
 
![screen shot 2018-07-03 at 15 12 44](https://user-images.githubusercontent.com/38809963/42225152-c0d8df5e-7ed3-11e8-9184-baa21a34b280.png)

i have attached a screenshot, so that you can see the amount of memory RAM, that it was consuming...

**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**    Mac Os High Sierra 10.13.5

**GPMDP Version:** 4.6

**Issue Descriptions:**

**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment]
I'm sorry this isn't something we can look at right now, basically, it'll be a renderer issue on your specific hardware / OS configuration.  It will probably fix itself when we update Electron again 🤔
