### ISSUE TITLE
Back button missing on newest windows release

### ISSUE THREAD

**Issue by sccofer** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3224]
The back arrow is gone!  Screenshot attached...

**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**

**GPMDP Version:**

**Issue Descriptions:**

**Steps to Reproduce:**
![gpm_screenshot](https://user-images.githubusercontent.com/40799340/42225747-45b11fb2-7eab-11e8-8fe2-b667dad92379.jpg)

**Comment by jostrander** [comment]
Duplicate of #3176
