### ISSUE TITLE
Unable to switch back to Google Play Music after switching to Youtube Music

### ISSUE THREAD

**Issue by nowendwell** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3225]
**OS:** 
macOS High Sierra 10.13.4

**GPMDP Version:** 
4.6.0

**Issue Descriptions:**
Missing return to Google Play Music button/menu item after switching to Youtube Music

**Steps to Reproduce:**
Switch to Youtube Music via menu. Try switching back.

**Comment by MarshallOfSound** [comment]
On the tray menu there are two options, the YouTube music one you just clicked.  And the Google play music one.

**Comment by nowendwell** [comment]
Yikes. Appreciate it. My bad.
