### ISSUE TITLE
New app icon is messed up in taskbar

### ISSUE THREAD

**Issue by WELZ-gh** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3226]
It has all those weird black spots over it:

![image](https://user-images.githubusercontent.com/35234925/42234551-e911d8ce-7ec2-11e8-8ca2-b6cdf5c36d0e.png)

![image](https://user-images.githubusercontent.com/35234925/42234618-20ac5ade-7ec3-11e8-95f1-7f047e399e40.png)

Windows 10 Home 1709
____
I personally liked the old icon better, can there be an option where you can choose which one to use?

**Comment by jostrander** [comment]
The black spot issue is fixed in master. Duplicate #3218.  No unfortunately we can not use the old icon.
