### ISSUE TITLE
Google Advanced Protection

### ISSUE THREAD

**Issue by 1010bob** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3227]
I would like to see the addition of Google Advanced Protection Support, https://landing.google.com/advancedprotection/
I have almost all paid subscriptions to everything on Google and would like to listen to music easier on my desktop.
Thanks for your time!
- Blake B.

**Comment by MarshallOfSound** [comment]
We portal into the Google play music website, you aren't giving anyone access to your account other than Google itself

**Comment by 1010bob** [comment]
Yes Sir, I understand that, since I have Google Advanced Protection turned on, when I sign in I need to insert a USB key, and when I do that for the Desktop Player it doesn't recognize that the key is in.
