### ISSUE TITLE
Back button missing in search bar

### ISSUE THREAD

**Issue by dmillerzx** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3230]
The back button appears to now be missing within the search bar from version 4.6.0.

Windows 10

**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**

Windows 10

**GPMDP Version:**

4.6.0

**Issue Descriptions:**

**Steps to Reproduce:**

**Comment by jostrander** [comment]
Duplicate #3176
