### ISSUE TITLE
App gets stuck in Youtube Music page when starting up

### ISSUE THREAD

**Issue by rbrandao** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3231]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:** Windows 10 64-bit

**GPMDP Version:** 4.6.0

**Issue Descriptions:** The application gets stuck in an Youtube Music page when starting up. It doesn't load the player page, so the whole application is unusable. Although Youtube Music is not currently available in my country (Brazil), I've opted-in to a waiting list for news about it. When loading up it shows this page (attached image), stating "stay tuned for updates".

**Steps to Reproduce:** Just start the application (after opted-in for YM updates in a country it is not available yet)
![capture](https://user-images.githubusercontent.com/779451/42333219-88e5c570-8050-11e8-955e-8135754dd425.JPG)
.

**Comment by MarshallOfSound** [comment]
I don't see how this is stuck?  The tray menu will still be accessible for you to switch back to Google Play Music?
