### ISSUE TITLE
Extra Mouse Buttons Not Functioning

### ISSUE THREAD

**Issue by St0rmwindX** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3232]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**
Windows 10 64

**GPMDP Version:**
4.6.0

**Issue Descriptions:**
Cannot properly utilise additional (side) mouse buttons to browse backwards or forwards, as used to happen in previous versions.

**Steps to Reproduce:**

1: Please obtain/utilise a mouse with additional side buttons that have a normal, scripted browser function of back/forwards (returning to previous page; advancing to next);
2: Open app;
3: Enter an artist of choice (context: artist Orange Goblin);
4: Choose an album by aforementioned selected artist (context: album Wolf Bites Back);
5: Click side mouse button normally assigned to 'back' and observe how nothing happens, despite the action to return to the previous page happening on the previous version and on web browsers.

**Comment by MarshallOfSound** [comment]
Fixed in master

**Comment by St0rmwindX** [comment]
Thank you for getting back to me. Looking forward to this fix on the next version!
