### ISSUE TITLE
Dark text for "My Playlists" in dark ui

### ISSUE THREAD

**Issue by djh816** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3233]
**OS:10.12.6**

**GPMDP Version:4.6.0**

**Issue Descriptions:Though most of the labels are correctly showing as white on black for the dark theme the text "My Playlists" is not. Screenshot uploaded at https://i.imgur.com/XlScR57.png**

**Steps to Reproduce: Switch to playlists tab, scroll down to my playlists**

**Comment by MarshallOfSound** [comment]
Please raise theming issues on the [theming repository](https://github.com/gmusic-utils/gmusic-theme.js)
