### ISSUE TITLE
Media control keys on task bar thumbnail not showing

### ISSUE THREAD

**Issue by Camilo-Jones** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3234]
**OS:**
Windows 10

**GPMDP Version:**
4.6.0

**Issue Descriptions:**

Hello,
After 4.6.0 update, I'm unable to see the thumbnail media control keys (previous, pause, next) when hovering the icon in the taskbar. With version 4.5.0 this works, but the app automatically updates, and I can't find a way to disable updates.

Does anyone know what's going on?

Thank you!!!!

![image](https://user-images.githubusercontent.com/40901386/42399810-de1fe144-8134-11e8-854b-83e83934e876.png)

**Comment by jostrander** [comment]
This is fixed in master. Will be published next release.

**Comment by Camilo-Jones** [comment]
Thank you for your quick response.
Have a nice day!!!
