### ISSUE TITLE
Playlist syncing with Google account

### ISSUE THREAD

**Issue by achitena** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3235]
Hi,

I noticed that the playlists I create using the music.youtube.com site are not synced with your player and vice versa. Is it possible to create a unified experience where playlist data (among other things) is synced on an account level?

Otherwise, great app! Thank you!

Regards,

Alvin Chitena

**Comment by MarshallOfSound** [comment]
We literally just portal to the YouTube music site, if your playlists aren't appearing reload the app the refresh the UI and if that doesn't work Google is having issues not us.
