### ISSUE TITLE
Previous page/next page browsing broken on 4.6.0.

### ISSUE THREAD

**Issue by etrulls** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3237]
I upgraded to 4.6.0 (OSX) and neither the keyboard shortcut nor the menu item do anything. I downgraded to 4.5.0 and it's working fine again.

**Comment by Draethorian** [comment]
Yeah same with windows 10 and mouse buttons back/forth.  self explanatory regarding that bug report ;-)

**Comment by MarshallOfSound** [comment]
Fixed in master
