### ISSUE TITLE
Taskbar Hover Actions Gone & Icon Pixelated

### ISSUE THREAD

**Issue by brennaveen** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3238]
**OS:**

Windows 10 Pro Version 1803 OS build 17134.137

**GPMDP Version:**

4.6.0

**Issue Descriptions:**

1. Taskbar hover actions are no longer available - in the latest release, the hover window no longer contains action buttons allowing the user to quickly pause, go back, or skip.
![tempsnip](https://user-images.githubusercontent.com/10182193/42454650-a8171108-8355-11e8-89ba-a4a90acd5fda.png)

2. Icon is pixelated - in the latest release, the icon went from being crisp and clear to pixelated.

**Steps to Reproduce:**
Install GPMDP version 4.6.0 on OS listed above

**Comment by jostrander** [comment]
Fixed in master, should be released shortly.
