### ISSUE TITLE
Windows: Media keys appear not to work

### ISSUE THREAD

**Issue by ncthbrt** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#324]
Hi there,
On the Windows desktop client (v3.0.0 on Windows 10), media keys appear to not work. I have a Microsoft  Ergonomic Keyboard 4000. The keys work with the Google's miniplayer extension. 

Please let me know if you need any more information (or if I'm being dense and missing something obvious).

P.S. Thanks for the awesome work. It brings a bit of sanity back when I'm debugging on Chrome.

**Comment by MarshallOfSound** [comment]
Remove the google play music chrome extensions :+1: 

Google chrome extension steals the mini player shortcuts and doens't let any other app use them #greedygoogle

**Comment by ncthbrt** [comment]
Great thanks. That fixed it.
