### ISSUE TITLE
In-app media control keys doesn't work after switch from different app until manual 'click'

### ISSUE THREAD

**Issue by lundibundi** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3240]
**OS:** Linux neko 4.17.3-1-ARCH #1 SMP PREEMPT Tue Jun 26 04:42:36 UTC 2018 x86_64 GNU/Linux

**GPMDP Version:** gpmdp 4.6.0-2 (ArchLinux AUR)

**Issue Descriptions:** upon switch to the app via window switcher (alt+tab) or via clicking app icon in the dock (I use latte-dock) media control keys such as space, arrow buttons are not recognized (don't produce any result) until I manually click in the app window with mouse. 

**Steps to Reproduce:**
1. Open GPMGP
2. Start any song
3. Minimize the app/Switch to any other app
4. Switch back to GPMDP via alt+tab or dock
5. Press space/arrow keys

This is like 90% reproducible, there are times when they actually work, but I have no idea why. Probably some focus related issues on KDE.

Additional info
Qt: 5.11.1
KDE Frameworks: 5.47.0

Qt: 4.8.7
KDE Development Platform: 4.14.38

Thanks for the great app =).

**Comment by jostrander** [comment]
I think you are probably correct in that the window doesn't gain focus so you are unable to send keys to the window. However I'm fairly certain that's the responsibility of the window manager to focus the window on Alt+tab, etc. I'm not sure we can fix this behavior as the GPM keyboard shortcuts are bound to the window/document, which should be forwarded.

**Comment by lundibundi** [comment]
Hmm, @jostrander could you please point me at the code that does this, I may try to debug it if I have time, as gpmdp is the only app that have the problem.

**Comment by MarshallOfSound** [comment]
This works as expected on macOS and Windows, I'm going to put this down to a weird WM thing on your linux setup.

The closest thing we have to relevant code for this is our focus proxy logic:

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/82c84871163e0949172e6dde7550f6844fb88749/src/renderer/ui/pages/PlayerPage.js#L80
