### ISSUE TITLE
Request: Output current playing song to text file

### ISSUE THREAD

**Issue by breon** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3242]
### Description
I stream on Twitch and often use your app to play background intro/background music for my stream. I also use a bot that lets users run commands in my chat to do certain things; get my Discord info, find out how to tip and sub, and other fun commands. In the past, I used another bot to fetch my current playing song from last.fm. There was always a delay and sometimes it didn't work. My current bot can read local text files on my machine and display the text from that file in the command response. It would be awesome if Google Play Music Desktop Player would output the current song, artist (maybe album, link to Google Play to purchase) so that I can reference this text file with my bot commands.

### Preconditions
* Signed into Google Play Music
* Google Play Music Desktop Player open

### Steps
* User searches for song
* User clicks play button

### Expected
* Music starts playing
* GPMDP outputs song to text file
  * Format "`[artist]` - `[song]`"

### Errors
* If file doesn't exist, then create the file

### Notes
* When new song starts, overwrite all text in file
* Bonus points if the user can set the file location
* Bonus points++ if the user can set the output format with variables; i.e. {song}, {artist}, {album}, {url}, and anything else you can think of.
  * Example: `{artist}` :: `{song}` (`{album}`)
  * Output: Approaching Nirvana :: Fragments (Horizons)

**Comment by zwebb2** [comment]
You should be able to read this information from the json file generated by GPMDP. It's located at C:\Users\USERNAME\AppData\Roaming\Google Play Music Desktop Player\json_store\playback.json

You may need to write a script to convert the json to text, but all the information is in that file.

**Comment by jostrander** [comment]
All of this can be achieved using the playback.json file that's mentioned by @zwebb2.

**Comment by breon** [comment]
Welp. I guess that's that. While the json file exists, it's not what I was looking for.
