### ISSUE TITLE
Back button gone?

### ISSUE THREAD

**Issue by ryguy426** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3243]
**OS:**
Sierra
**GPMDP Version:**
Version 4.6.0 (4.6.0)
**Issue Descriptions:**
Feel free to ignore me if I am being dumb, but did the "back" button disappear in the latest update?
**Steps to Reproduce:**

**Comment by darnold** [comment]
I came here to complain about the same thing! Windows 10, latest GPMDP version.

**Comment by jostrander** [comment]
Fixed in master #3176
