### ISSUE TITLE
Why did you remove the back button??

### ISSUE THREAD

**Issue by maxpull** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3244]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

Navigating is now a huge waste of my time, I can no longer go back to the previous screen? I need to go to the Home page or to My library and start over every single time?

Am I missing something has it moved? is there a keyboard shortcut?

**OS:**
Windows 10
**GPMDP Version:**
4.6.0
**Issue Descriptions:**
No more back button
**Steps to Reproduce:**
Launch program, look for back button in search bar.

**Comment by bboles** [comment]
You should check #3176 .

**Comment by jostrander** [comment]
Yep #3176. Next release should be out soon.
