### ISSUE TITLE
GPMDP blocks allowing kernel extensions on MacOS

### ISSUE THREAD

**Issue by GWBasic** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3245]
**OS:**
MacOS 10.13.5

**GPMDP Version:**
4.6.0

**Issue Descriptions:**
GPMDP blocks allowing kernel extensions on MacOS. This is probably related to installing some kind of a keystroke logger, perhaps to capture media keypresses.

Background: Apple implemented a security feature to prevent malware from adding kernel extensions. Specifically, users must go into "System Preferences," select "Security & Privacy," and on the "General" tab, select "Allow"

Apple's new security feature requires that users push the "allow" button with the physical trackpad or mouse. The "allow" button can not be pressed through a screen sharing program, or through a software-based input controller. (This prevents malware from installing a kernel extension.)

When running GPMDP, the "allow" button does not work. Closing GPMDP resolves the problem.

For more information:

- https://apple.stackexchange.com/questions/323668/allow-button-not-working-in-system-preferences
- https://github.com/osxfuse/osxfuse/issues/437 (Look for comment with "As it turns out, I was running a copy of MagicPrefs"

**Steps to Reproduce:**

1. Start GPMDP
2. Install a product that requires a kernel extension. (VMWare Fusion, any MacFUSE based product)
3. The product's installer will prompt with "System Extension Blocked"
4. Click "Open System Preferences"
5. (Click the padlock if it's locked)
6. Attempt to click "Allow"
7. Observe that "Allow" doesn't respond
8. Quit GMDP
9. Observe that "Allow" responds

Note that if "allow" doesn't respond, you might have additional keystroke loggers installed.

**Comment by GWBasic** [comment]
Debug log

[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/2184569/debug_info.zip)

**Comment by jostrander** [comment]
I'm not familiar with how the OS X key bindings are handled, but I believe they are handled through Electron itself. It may be an upstream bug.

**Comment by jostrander** [comment]
Just checked, is in fact handled by https://github.com/electron/electron. You would probably be better off raising the issue there, as we are just using their GlobalShortcut API.
