### ISSUE TITLE
Option to turn off auto-update

### ISSUE THREAD

**Issue by SirDufus** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3249]
Ok, I tried this once and my issue got closed over semantics so let me try once more!

OS:
Windows 10

GPMDP Version:
Trying to use 4.5 but keeps auto updating to 4.6

Issue Descriptions:
Current version has features broken and when I downgrade to 4.5 so I can use those features, the software automatically updates itself to the new broken version. I just want to use the old version until the new patch is released, using the older version is good enough for me.

Please add an option to turn off auto update.

Steps to Reproduce:
I just installed an old version and it automatically updated itself without proper permission.

**Comment by jostrander** [comment]
It wasn't closed due to semantics, it was closed because there are previously closed issues including reasoning as to why this isn't an included option. See #1506, #1810, etc.

**Comment by tjkirch** [comment]
If you'd like to avoid questions about preventing auto-update, and prevent some of the duplicate issues for things like the broken back button, it may help to clarify the release process of GPMDP.  I've been following the issues for a couple weeks, and releases are promised soon, but I don't see a tracking issue or anything like that.  I also considered downgrading GPMDP and preventing auto-update just to get "back" back, and given the number of raised issues, it seems to be a major feature to many users.  I think clearer communication would help.

**Comment by SirDufus** [comment]
Agreed, I don't understand what the delay is all about to be honest. They have talked about it being patched already, they have promised to release a fix and yet they seem to spend so much time closing complaint after complaint that the back button isn't working anymore lol.

Insanity is doing the same thing over and over again expecting different results... Wouldn't it have been less time consuming to just release the fix already?

Also, they have a link to GitChat on their website but they never answer questions there either. Not sure why they feel to need to keep us in the dark over such a minor/trivial issue...

Hope it gets released soon, it's so tedious to use without that feature, never realised how much I depend on it until it went missing.

**Comment by BrianAllred** [comment]
Doesn't have anything to do with keeping users in the dark, but everything to do with the fact that supporting free software as a hobby sometimes can't be a priority. Some people are just really busy or have other things going on. It's not ideal, but it's the world we live in.

**Comment by MarshallOfSound** [comment]
> Reading comprehension, it's a thing!

Respect is also a thing, so is common politeness.

You seem to be laboring under two misimpressions, firstly that I, as the maintainer/creator of this project owe anyone anything.  I create this in my spare time, I maintain this in my spare time, I could be out right now having fun at the weekend.  Instead, I'm here replying to you...  Open source maintainers do what they do, for free, out of the goodness of their hearts.  Expecting, demanding or making assumptions of them is annoying at best and downright rude at worst.

Your second misimpressions is that releasing a new version of this application is one click of a button, I don't haphazardly release software to a quarter million people when I feel like it, I test every release to ensure it doesn't brick the update process on all 3 platforms and multiple archs, I have to prepare the release for multiple OS specific stores and have at least a 24 hour window where I would be free to handle major issues with the release after the release goes out.

I work a full-time job and maintain numerous open source projects, of which this isn't even the biggest.  I'd ask that you remember that when interacting with me and other people volunteering their time to work on open source.

**Comment by SirDufus** [comment]
Meh, I wasn't talking to you directly obviously since it seems you have many helpers on here but if you choose to be insulted by my impatience for others to understand what I was trying to say so be it. Not everyone has English as a first language and sometimes, maybe, just maybe not everyone is as good with words as they wish they could be.

Either way, it I only came back to reply to say thanks for posting the update and taking time to also chastise me, I won't bother you anymore...
