### ISSUE TITLE
Uncaught Exception: listen EADDRINUSE 0.0.0.0:5672

### ISSUE THREAD

**Issue by algerdby** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#325]
An uncaught exception was reported.  
#### Info:
**OS:** linux
**Arch:** x64
**GPMDP Version:** 3.0.0
**Time:** Mon Mar 07 2016 12:21:35 GMT 0300 (MSK)

#### Error:
*listen EADDRINUSE 0.0.0.0:5672*
```js
Error: listen EADDRINUSE 0.0.0.0:5672
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at doNTCallback3 (node.js:476:9)
    at process._tickCallback (node.js:382:17)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
Did you try to launch the PlaybackAPI?

**Comment by algerdby** [comment]
yes, i did.

**Comment by MarshallOfSound** [comment]
OK, so here is the question.  What do you have running on port 5672 :question:

**Comment by MarshallOfSound** [comment]
Or do you possibly have 2 instances running?

**Comment by algerdby** [comment]
sudo netstat -tulpn | grep :5672
tcp6       0      0 :::5672                 :::*                    LISTEN      4153/beam.smp 

Only one instance

**Comment by MarshallOfSound** [comment]
Are you running couchdb on your machine.

It looks like something else is running on the port we want

https://www.reddit.com/r/Ubuntu/comments/caae8/what_the_hell_is_beamsmb/

**Comment by algerdby** [comment]
I don't have couchdb.

**Comment by MarshallOfSound** [comment]
Well something else is running on that port :P

**Comment by MarshallOfSound** [comment]
Closing is very user specific and its due to another service running on my randomly chosen port

**Comment by wengole** [comment]
Can I suggest you not use this port? Or is it not up to you?

http://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=5672

This is the internationally recognised port number allocations.

**Comment by algerdby** [comment]
Thank you for link. I have had rabbitmq. Now, it's ok.

**Comment by Hiewxt** [comment]
Sorry for opening the new issue, I'm running virtual audio cable with my default audio source going there. It happened when choosing a different audio source. (other than my default)

**Comment by mlaccetti** [comment]
Should re-open this issue - port 5672 is used by RabbitMQ, which means when I fire up a Docker container and have the GPMDP enabled, complaints complaints complaints.
