### ISSUE TITLE
MacOS delete button does not return the the previous view

### ISSUE THREAD

**Issue by marquesarthur** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3251]
**OS:** MacOS 10.13.5

**GPMDP Version:** 4.6.0

**Issue Descriptions:** MacOS delete button does not return the the previous view

**Steps to Reproduce:** 
1. Go to an artist. 
2. select an album.
3. press delete to return to the artist view
4. Nothing happens.

____
Please note that I use GPMDPU both in a Fedora machine at work and a Mac at home and on Fedora, pressing the backspace button everything seems fine. So I believe this is a specific issue related to the OS.

**side note:** I've been trying to contribute with the project for quite a while and if this is a good first but, I would be glad to help with a patch.

**Comment by MarshallOfSound** [comment]
Fixed in master
