### ISSUE TITLE
Feature request: make it possible to go back/forward with either hotkeys or mouse navigation buttons

### ISSUE THREAD

**Issue by darkvertex** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3252]
**Checklist:**

* [X] I have checked that there are no issues with similar or the same content

* [X] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [X] I have double checked and can reproduce the issue

**OS:**

CentOS Linux release 7.4.1708 (Core)

**GPMDP Version:**

google-play-music-desktop-player-4.6.0-1.x86_64

**Issue Descriptions:**

There seems to be no way to navigate back (and forward for that matter) within the player. In the normal web browser version of Play Music (and I suspect YT Music also) you can use navigation buttons from the browser, Alt+Left/Right Arrow hotkey, or back/forward buttons from a mouse with navigational buttons on it. All of that works in a normal browser.

**Steps to Reproduce:**

If you have a mouse with "back & forward" navigation buttons, you could try them and they wouldn't work.

Alternatively, the standard hotkey of Alt+Left/Right Arrow to navigate back and forward that works in *any* common browser, does not work also.

In a few browsers, the Backspace key goes back one page. It doesn't do anything in the player.

**Comment by MarshallOfSound** [comment]
Fixed in master

**Comment by jostrander** [comment]
To follow up, this is all already implemented, but broken in 4.6.0. 4.6.1 will have this fixed.

**Comment by darkvertex** [comment]
Great! Looking forward to using it.
