### ISSUE TITLE
No system tray icon in my Linux so I can't try switching to the YTM beta mode :/

### ISSUE THREAD

**Issue by darkvertex** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3253]
**Checklist:**

* [X] I have checked that there are no issues with similar or the same content

* [X] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [X] I have double checked and can reproduce the issue

**OS:**

CentOS Linux release 7.4.1708 (Core)

**GPMDP Version:**

google-play-music-desktop-player-4.6.0-1.x86_64

**Issue Descriptions:**

Supposedly the 4.6.0 release introduces beta support for YTM (Youtube Music) by going to the system tray icon.

Sadly, not all Linux builds support systray icons. Mine is one of those, and I have no way to beta test YTM.

Would it be possible to sneak that into the Settings window somewhere? Then I could try it.

**Comment by MarshallOfSound** [comment]
Raised elsewhere, basically this will happen once we have proper UI injection support for YTM

**Comment by darkvertex** [comment]
Okay, thanks! I'll wait.

**Comment by argraur** [comment]
There is no way to enable YTM by editing GPMDP config files?
