### ISSUE TITLE
[4.6.0 Mac] "Go back" is gone in 4.6.0

### ISSUE THREAD

**Issue by khour** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3254]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [X] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [X] I have double checked and can reproduce the issue

**OS:** macOS 10.12.6

**GPMDP Version:** 4.6.0

**Issue Descriptions:** It's no longer possible to go page back. Back button arrow is gone, system "page back/page forward" gestures/shortcuts don't work anymore.

**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment]
> I have checked that there are no issues with similar or the same content

> YOU SHOULD CHECK CLOSED ISSUES ASWELL
