### ISSUE TITLE
Can no longer control player when minimized (pause, play)

### ISSUE THREAD

**Issue by Kickasstrophe** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3255]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**

**GPMDP Version:**

**Issue Descriptions:**

**Steps to Reproduce:**

**Comment by jostrander** [comment]
Thanks for the issue. This has more than likely been fixed and not yet released yet.
