### ISSUE TITLE
Can't disable youtube play music and go back to the original Google play music.

### ISSUE THREAD

**Issue by cadell** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3257]
**OS:** . MAC OS High Sierra

**GPMDP Version:** 4.6.0 

**Issue Descriptions:** I switched to youtube play music at some point to try it and haven't been able to switch back to google play music the menu option doesn't show up.

**Steps to Reproduce:**

**Comment by jostrander** [comment]
You don't have the option to select "Google Play Music" in  your tray menu?

**Comment by cadell** [comment]
<img width="1437" alt="screen shot 2018-07-13 at 8 44 23 pm" src="https://user-images.githubusercontent.com/9630440/42719040-c2665308-86dd-11e8-898f-26cb7fe0f2e0.png">

**Comment by jostrander** [comment]
The tray icon in the top near the clock is where the switcher is.

**Comment by cadell** [comment]
Man i spent the longest time ever trying to find that.. i guess it's not an issue. Thanks alot

**Comment by mebinum** [comment]
Man I spent forever trying to find this as well, would be good if this was in settings or something

**Comment by jespersh** [comment]
Just curious, where did you switch to Youtube music in the first place? Might be relevant to add a way back the same place

**Comment by thomascrha** [comment]
@jespersh I was like 'whats this - I'll click it' and then completely forgot how I did it. Thanks for this thread it took me too long to figure this out.
