### ISSUE TITLE
Searching for some artists results in infinite spinner

### ISSUE THREAD

**Issue by nolanblew** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3259]
**Checklist:**

* [ x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [ x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [ x] I have double checked and can reproduce the issue

**OS:** Windows

**GPMDP Version:** 4.6.0

**Issue Descriptions:** Unsure of the root cause, but attempting to search for some artists results in an infinite spinner

**Steps to Reproduce:**
1. Open GPMDP
0. Search for the artist `fhana`. This is the particular artist I've been having an issue with. She is indexed in GP Music but has no albums.
0. Watch how the endless spinner appears. The only way I've found to get rid of it is fully quit out of GPMDP and then start it again.

![gplay_artist_error](https://user-images.githubusercontent.com/1565705/42717491-3d4df198-86b6-11e8-9fa6-7211a7bb0ccc.gif)

Debug file:
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/2194414/debug_info.zip)

**Comment by jostrander** [comment]
I just tested this and didn't have the same issue. This is an ajax call on Google's end so more than likely something to do with your network connection and/or computer and not the application. We don't have any network related code in this app as we just wrap music.google.com so we wouldn't be able to fix this either way.

**Comment by nolanblew** [comment]
@jostrander hmm interesting. Doesn't seem to happen on any other artists or on web using chrome, edge, or firefox.
