### ISSUE TITLE
Version 4.6.1 - Patch Release

### ISSUE THREAD

**Issue by jostrander** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3260]
This issue is for tracking progress on the release process.

- [x] Update MR_CHANGELOG
- [x] Version patch
- [x] Push to master
- [x] Build all platforms on CI
- [x] Check release process on staging update server `staging.googleplaymusicdesktopplayer.com`
- [x] Check operational on Windows
- [x]  Check operational on OS X
- [x] Check operational on Linux
- [x] Make release on GitHub
- [ ] Upload to bintray
- [ ] Upload to WinStore
- [x] Watch the world burn :fire: :fire_engine: 

----
This patch release addresses issues pertaining to navigation (back button, mouse navigation, keyboard navigation) as well as a few other bugs. It will be released at the convenience of @MarshallOfSound when he has time to test and build packages for release. Any new issues related to the above fixed issues will be closed and referenced to this issue.

**Comment by sigma67** [comment]
Does this address the need to click twice in the search field before being able to enter anything? This only happens when using a different application and then directly clicking on the search field in the GPMD window. Didn't happen before 4.6

**Comment by z0rc** [comment]
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/releases/tag/v4.6.1 lists binaries with version 4.5.0 at least in name. I haven't tried to install to verify the actual version number.

**Comment by MarshallOfSound** [comment]
@z0rc Dropped the wrong ones in the folder, should be alg now 👍

**Comment by agnibha** [comment]
Hey @jostrander, the Mac App's icon is missing after the upgrade.

**Comment by MarshallOfSound** [comment]
@agnibha Your macOS icon cache will just be glitched out, quit the app and relaunch it and the icon should come back 👍 You may have to restart idk what resets that cache

**Comment by jimbob1001** [comment]
have the same issue with the macOS icon - it will not reset no matter what i do

**Comment by Stoppablemurph** [comment]
The icon updated for me initially after the update, but then a little while later the new icon went away and it's just the default mac "missing icon" app icon. I believe I have already rebooted and even tried reinstalling the app. I'm not positive about the reboot though. If I have time later I'll try rebooting again and report back.

**Comment by zerkz** [comment]
@Stoppablemurph I regenerated the icon and this seemed to fix the issue for me. 

You can build it on my fork / see the PR here : https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/pull/3278

**Comment by deuterium** [comment]
> The icon updated for me initially after the update, but then a little while later the new icon went away and it's just the default mac "missing icon" app icon. I believe I have already rebooted and even tried reinstalling the app. I'm not positive about the reboot though. If I have time later I'll try rebooting again and report back.
> 
> Edit: Still haven't restarted, but I did try some of the recommendations [here](https://gist.github.com/fabiofl/5873100) for refreshing the icon without any luck.
> 
> Edit 2: Weird, so I was listening to some music for a bit and the new circle icon showed up again, but as soon as I closed the app it's gone again. :(

Not sure if you're still experiencing this, but I have been for months with using external monitors. Fine on internal display on Retina MBP. I've finally fixed this using the "Get Info" method described here: https://gist.github.com/fabiofl/5873100#gistcomment-1240299
