### ISSUE TITLE
Youtube brand account

### ISSUE THREAD

**Issue by Alquimista** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3261]
**OS:**
Antergos Linux

**GPMDP Version:**
4.6.0-2

**Issue Descriptions:**
I have youtube premium but in an brand account, if I login with my credentials I'm logged to my normal account, Can I login to my brand youtube account?

**Steps to Reproduce:**

**Comment by jostrander** [comment]
You may be able to click on your account icon in the upper right and change accounts?

**Comment by wrathsoffire76** [comment]
Brand accounts aren't supported in YouTube Music at all.

**Comment by MarshallOfSound** [comment]
> Brand accounts aren't supported in YouTube Music at all.

😢

**Comment by Darknesskight** [comment]
Just chiming in here for people who run across this issue in the future. YouTube Music now supports brand accounts in the web version which means that this unofficial client works as well.

**Comment by RakouskyS** [comment]
> Just chiming in here for people who run across this issue in the future. YouTube Music now supports brand accounts in the web version which means that this unofficial client works as well.

How do I switch from my normal google account to my brand account, the client isn't giving me an option to switch to my brand account, like I usually do on the website.
