### ISSUE TITLE
Discord Rich Presence is broken

### ISSUE THREAD

**Issue by wrathsoffire76** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3262]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:** Windows 10

**GPMDP Version:** 4.6.0

**Issue Descriptions:** Discord won't load the Rich Presence for GPMDP and setting it in the games does nothing 

**Steps to Reproduce:** 1. Toggle Rich Presence
2. Open Discord client
3. Play music 
4. Nothing happens

I have tested this with both the stable and Canary builds of Discord, both yielding the same results.

**Comment by MarshallOfSound** [comment]
Fixed in master
