### ISSUE TITLE
New releases filter not visible anymore

### ISSUE THREAD

**Issue by jfcartier** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3270]
Version 4.6.1 (osx) 

New releases filter (by music styles) used to be visible, but seems hidden since 4.6 i believe. 

![screen shot 2018-07-16 at 3 48 36 pm](https://user-images.githubusercontent.com/3603641/42779972-f87b66d4-890f-11e8-96bd-4b46e9fbf6cd.png)

**Comment by RyanThaDude** [comment]
This isn't an issue with GPMDP, rather than Google removing it. If you browse the site in a normal browser it looks the same.

**Comment by jostrander** [comment]
Yep, good eye @RyanThaDude just confirmed this myself. Nothing we can do here unfortunately.
