### ISSUE TITLE
Dock Icon not showing on a second screen connected to macbook pro(10.12.6)

### ISSUE THREAD

**Issue by kapilpr** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3271]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**

**GPMDP Version:**

**Issue Descriptions:**

**Steps to Reproduce:**
![screen shot 2018-07-17 at 9 56 03 am](https://user-images.githubusercontent.com/30549956/42833190-4fde2144-89a8-11e8-80af-f952fe7847d6.png)

**Comment by icurate** [comment]
I am having the same issue since the most recent update. Running 10.11.6 on a MacPro with one 4k monitor. I tried reinstalling from the GPMDP website.

**Comment by zerkz** [comment]
Same thing, Macbook pro here, no 4k or anything, but it just seems that the Icon was set correctly for this build.

**Comment by zerkz** [comment]
This looks like it could possibly be the problem commit? 
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/commit/de1574b1357d237806bf9736de374756db0e746e

**Comment by MarshallOfSound** [comment]
As mentioned in another duplicate issue, basically this is a macOS icon cache issue.  Unpin the app from the dock, restart it and pin it again and the icon should fix itself.  If it doesn't you may have to restart your machine

**Comment by zerkz** [comment]
@MarshallOfSound  I restarted and it didn't fix it... I'll try redownloading, but could you reference me the other dupe issue incase I can find anymore details? Thanks for your hard work!

**Comment by kapilpr** [comment]
@MarshallOfSound Tried it but it didn't fix the issue. Tried reinstalling as well. But still no icon

**Comment by zerkz** [comment]
I opened this PR, whose contents ( a regenerated icns file ) fixed the issue for me. https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/pull/3278
