### ISSUE TITLE
doesn't play music on mac

### ISSUE THREAD

**Issue by unclesem** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3272]
**OS:**
macos 10.13.6

**GPMDP Version:**
4.6.1

**Issue Descriptions:**
GPMDP opens and load the library 
but if i select song to play , it's just skip to next song and do it over and over 
nothing is playing 
**Steps to Reproduce:**
install , login, play song

**Comment by jostrander** [comment]
I'm going to go out on a limb here and try the simple things like:
1. Is the volume in GPM turned up?
2. Is the system volume up and not muted? 
3. Are you trying to use a specific device? Does your default device output sound from other applications?

There's really not much to go on here.

**Comment by unclesem** [comment]
Hi
Volume is ok and i tried to see if right audio device is selected(  i use
build-in speakers)
It doesn't even try play the song . It's jump from one song to another in a
sec. Like it's can't decode or access it
Regards

**Comment by jostrander** [comment]
Ah, I misread that in your original info. General that's due to network issues. Do you have a network wide adblock or firewall? Does playing music on the web player work? (https://music.google.com) ?

**Comment by unclesem** [comment]
Hm
Idd could be network
after few reboots it started to work
but i remember for sure it was not working and at the same time i could
access it on web
any chance you have log file i could check if problems reappear ?

**Comment by MarshallOfSound** [comment]
As it is now working I'm gonna put this down to network issues and close it out.  If it happens again check our our GitHub Wiki page for how to get debugging information
