### ISSUE TITLE
Windows 10 Taskbar icon displays track playing as file downloading

### ISSUE THREAD

**Issue by roryhewitt** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3273]
Just upgraded to version 4.6.1.

When a track is playing, the Windows 10 Taskbar icon changes color as a track plays, just as it does when a large file is downloading on Chrome, with the icon turning green from left to right:

![image](https://user-images.githubusercontent.com/11558891/42850796-48404c74-89de-11e8-917c-26ca49950162.png)

**Comment by MarshallOfSound** [comment]
You will have turned this feature on in Desktop Settings, if you don't like it you can turn it back off again 😀
