### ISSUE TITLE
Switch back from Youtube to Google music mode

### ISSUE THREAD

**Issue by kirm84** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3274]
I am probably just being an idiot here but how do I switch back from the Youtube version to the Google music version? 

Tried the youtube version out but wasn't keen as non of my saved playlist were there.

**OS: Mac High Sierra

**GPMDP Version: 4.6.1

**Comment by kirm84** [comment]
where is the service tab? I cant find it anywhere on the mac version with youtube music to switch back to google play

**Comment by jostrander** [comment]
It's on the tray in the top bar.

**Comment by akinnee** [comment]
This took me too long to find as well. The app somehow switched to YouTube by itself.

**Comment by ThiccBoi1379** [comment]
I have the same issue but im on windows and i want to go to gpm to youtube music
