### ISSUE TITLE
Drag/Drop to playlist not working as intended

### ISSUE THREAD

**Issue by RyanThaDude** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3276]
Windows 10. In 4.6.0 and 4.6.1 there's an odd issue when dragging a song to a playlist. If you click, hold and drag the song a list of the playlists will appear on the right of the window. What should happen is a number in a red circle should appear on an album art thumbnail and when you release it on a playlist name it'll drop it in said playlist. However, it does not do this. What happens is that the album art doesn't move with the mouse and releasing the mouse button does nothing, but clicking the left mouse button (not hold) will attach the album art to the cursor to be dropped into a playlist. I've checked with Chrome and it continues to work as intended, but not in GPMDP.

**Comment by MarshallOfSound** [comment]
This will be an issue with webviews inside the version of Electron we started using in 4.6.0 . Unfortunately I don't have to time or resource to investigate this so I'm going to close it as wontfix
