### ISSUE TITLE
No scrobbling when playing via Chromecast

### ISSUE THREAD

**Issue by mlms13** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3277]
**OS:**
Ubuntu 18.04

**GPMDP Version:**
4.6.0

**Issue Descriptions:**
When GPMDP is connected to my Chromecast Audio, the currently-playing track shows up on Last.fm, but when the track finishes, no scrobble is recorded.

**Steps to Reproduce:**
Play music while connected to Last.fm and a Chromecast (Audio, but probably any Chromecast).

**Comment by mlms13** [comment]
Ah shoot, it looks like a couple scrobbles made it through, so maybe this is a duplicate of #3106.

**Comment by MarshallOfSound** [comment]
Duplicate of #3106 👍
