### ISSUE TITLE
Black screen of death - Persistant

### ISSUE THREAD

**Issue by walkerofmargins** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3279]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**
macOS High Sierra 10.13.5 (17F77)

**GPMDP Version:**
4.6.0
4.6.1

**Issue Descriptions:**

Black screen of death 
Since 4.6 update I cannot launch GPMDP 

**Steps to Reproduce:**
Please see issue raised 22 days ago
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3198
Logs attached
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/2209113/debug_info.zip)

**Comment by jostrander** [comment]
Please don't raise duplicates. Commenting on your previous with more details is sufficient.
