### ISSUE TITLE
Bringing the app forward from the tray icon.

### ISSUE THREAD

**Issue by t3mujin** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3281]
I think there's an usability/UX issue with systray icon, that's more visible since the introduction of the Service section.

First, if the app is minimized clicking the ray icon doesn't do anything, where the expected behavior might be to open the window.

Right clicking the tray icon shows the menu, and there the first option is Service -> Google Play Music. Clicking there will reload everything, even when Google Play was already running. Several times I reloaded everything when all I wanted was to bring the app up. 

I think this might need to be reviewed, from a UX perspective. Maybe if we click a service already enabled it won't refresh, maybe a simple click on the icon could bring the app forward, but at least the Show in the tray menu could be moved as the first option (this one seems the easiest fix).

Thanks!

OS: Windows 10
version: 4.6.1

**Comment by MarshallOfSound** [comment]
On windows 10 double clicking the icon will restore the app.  This is the Normal(tm) user experience on windows.  The behavior different across OS's to match OS standards
