### ISSUE TITLE
"Add to library" instead of "Remove from library" in queue item menu

### ISSUE THREAD

**Issue by alinpalade** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3282]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**
Linux Mint 64-bit.
**GPMDP Version:**
4.6.0.1
**Issue Descriptions:**
I see "Add to library" for items which were already in the library when the application started. I should be seeing "Remove from library". Everywhere else, the songs show the context menu correctly, not in the queue. The issue only applies to songs which were already in the library, newly added items show correctly (at least as far as I can tell, but maybe this is not the (only) reason).
Quitting and starting it again did not fix the issue.
**Steps to Reproduce:**
I think version 4.6.0.1 introduced this issue, because it has only been happening since today or last evening and I think I updated these last days (my memory is that bad). It worked the day before yesterday, I'm sure of that.
I installed the 4.6.1 version and the issue is gone. It is possible this was only an issue with a cache or something, I haven't checked on the Windows machine yet. I got the notice / welcome message for the new 4.6.1 version after starting it and I didn't need to log in again or anything. Glad it's fixed, but I'm posting the issue if it helps remove it if there's still some wrong code somewhere or anything.

**Comment by MarshallOfSound** [comment]
That UI comes from GPM itself, it probably was a bug and Google have already fixed it.

**Comment by alinpalade** [comment]
Thanks for replying.

Sorry if I'm reopening the issue, but I'm curious why it was only when I upgraded to the newer version that I got rid of this issue and how I should proceed in the future if something goes wrong, and, for instance, there's no newer version. I imagine maybe delete some hidden local folders and start fresh?

Side-note: I'll make sure and remember to donate a bit for this indispensable piece of software, at least for me - thank you for doing what Google wouldn't.

**Comment by alinpalade** [comment]
It started happening again with the newer version. I click "Add to library", but when I click it again, it still says "Add to library".

**Comment by alinpalade** [comment]
I noticed another thing - the playlist I saved contains added songs, but the ones from a few artists I added more recently to the queue before saving the playlist appear three times in the playlist, although I had added them one by one (from the artists' top 100 songs page). This may be related. One of the songs from another artist was even 4 times in the saved playlist. I didn't notice them having been added multiple times before saving, but they're too many (tens) for it to be a mis-click.

**Comment by MarshallOfSound** [comment]
All of the stuff you mentioned is part of GPM's web UI.  We don't change it but Google does, if their are issues there Google is causing them and Google will fix then

**Comment by alinpalade** [comment]
True I'm a recent GPM user, so it's very likely the issue is with their web app. Thank you for your time, Samuel. And thanks for investing in this beautiful app. I'll be thanking with more than words soon. I keep forgetting and I'm at work. Congratulations for realizing this project, I hope with all my heart we can keep it working.
