### ISSUE TITLE
Please fix your application to use the native API of Avahi!

### ISSUE THREAD

**Issue by Jigar29** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3283]
info: Application started.
error: Last.fm API keys have not been set!
*** WARNING *** The program 'electron' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=electron>
*** WARNING *** The program 'electron' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=electron&f=DNSServiceRegister>
Failed to encode dictionary
Failed to encode reply value
Failed to encode dictionary
Failed to encode reply value
debug: Renderer process logger initialized.
*** WARNING *** The program 'electron' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=electron>
*** WARNING *** The program 'electron' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=electron&f=DNSServiceRegister>
^Cinfo: Application exiting...
error: Uncaught Exception. message=Cannot read property 'disconnect' of undefined, stack=TypeError: Cannot read property 'disconnect' of undefined
    at App.<anonymous> (/home/management/Desktop/Google-Play-Music-Desktop-Player-UNOFFICIAL-/build/main/features/core/discordRichPresence.js:90:10)
    at emitOne (events.js:121:20)
    at App.emit (events.js:211:7)

**Comment by MarshallOfSound** [comment]
None of these logs are bad, the closest thing to a bad thing is the `disconnect` error message.  But that will be handled by something I've got working locally at the moment.  All the avahi logs are verbose, but expected.
