### ISSUE TITLE
[SUGGESTION] Discord Rich Presence Activity Type

### ISSUE THREAD

**Issue by Sominemo** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3284]
You can use activity type 2 (Listening) instead of 1 (Playing)
![image](https://user-images.githubusercontent.com/19842935/43039492-0df2d9f4-8d37-11e8-8107-3b6b111bef63.png)

**Comment by Thepenguin9** [comment]
I cannot find this line in [the relevant file](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/main/features/core/discordRichPresence.js) can you link the file you're suggesting on editing?

**Comment by Sominemo** [comment]
I think in should be **presence** constant, but I'm not sure. I borrowed this solution from https://github.com/AdrienC/discord-deezer-chrome/blob/61ca175150c15786e34dadf873c1b88d995278b7/src/DiscordGateway.js

**Comment by Thepenguin9** [comment]
Ahh, makes sense why I couldn't find it

**Comment by Alipoodle** [comment]
Not Possible!
talked about countless times within: #2978
> Stuff like Listening to Google Play Music Desktop Player... Is not possible due to using the Rich Presences API which only meant to be supported for Games (therefore playing)

Discord API does allow for you to change the type of what is shown... however the Rich Presences API doesn't allow for this.

**Comment by MarshallOfSound** [comment]
Not possible, as @Alipoodle mentioned
