### ISSUE TITLE
getting errors on npm install

### ISSUE THREAD

**Issue by hazre** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3286]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**
 Windows 10 home
**GPMDP Version:**
4.6.1
**Issue Descriptions:**
whenever I try to do npm install at the end I get this error

```
npm WARN optional Skipping failed optional dependency //electron-installer-debian:
npm WARN notsup Not compatible with your operating system or architecture: electron-installer-debian@0.4.0
npm WARN optional Skipping failed optional dependency //electron-installer-redhat:
npm WARN notsup Not compatible with your operating system or architecture: electron-installer-redhat@0.3.1
npm WARN optional Skipping failed optional dependency //appdmg:
npm WARN notsup Not compatible with your operating system or architecture: appdmg@0.4.5
npm WARN optional Skipping failed optional dependency //mouse-forward-back:
npm WARN notsup Not compatible with your operating system or architecture: mouse-forward-back@1.0.1
npm WARN optional Skipping failed optional dependency //dbus:
npm WARN notsup Not compatible with your operating system or architecture: dbus@0.2.18
npm WARN optional Skipping failed optional dependency /mpris-service/dbus:
npm WARN notsup Not compatible with your operating system or architecture: dbus@0.2.18
npm WARN material-ui@0.15.4 requires a peer of react-tap-event-plugin@^1.0.0 but none was installed.
npm WARN discord-rpc@3.0.0 requires a peer of register-scheme@github:devsnek/node-register-scheme but none was installed.
npm ERR! Windows_NT 10.0.17134
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE

npm ERR! mdns@2.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdns@2.4.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mdns
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\gpmdp\npm-debug.log
```

full log: https://gist.github.com/80510cc6362e8b09dbc794acb0d85c33
**Steps to Reproduce:**
git clone https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-.git gpmdp
cd gpmdp
npm install

**Comment by jostrander** [comment]
Do you have the development dependencies installed? The wiki has the dev info.

**Comment by hazre** [comment]
@jostrander yes im pretty sure I have

![](https://x.haz.re/ltMI8Jo.png)

![](https://x.haz.re/wtRgI9x.png)

![](https://x.haz.re/OHrOjcy.png)

**Comment by jostrander** [comment]
Try using `yarn` instead to install deps and run and build, etc as that will use the correct lock file.

**Comment by hazre** [comment]
@jostrander all good I just wanted to to edit some simple stuff I just extracted the app.asar and repacked the edited version, so I don't need to actually install it

**Comment by ssisaias** [comment]
> Try using `yarn` instead to install deps and run and build, etc as that will use the correct lock file.

I tried to use npm install with many node versions, I'm now using 6.2.2 without success as well. Already ran the powershell script provided in the wiki, nothingh helped so far. 
So i came across this thread, and when a I run yarn install at least I get a more straightfoward error message: 

```
λ yarn
yarn install v1.10.1
[1/4] Resolving packages...
[2/4] Fetching packages...
warning Pattern ["nan@latest"] is trying to unpack in the same destination "C:\\Users\\isaias.silva\\AppData\\Local\\Yarn\\Cache\\v2\\npm-nan-2.8.0-ed715f3fe9de02b57a5e6252d90a96675e1f085a" as pattern ["nan@2.x","nan@^2.3.2","nan@^2.4.0","nan@^2.1.0","nan@^2.6.2","nan@^2.2.0","nan@*","nan@^2.1.0"]. This could result in non-deterministic behavior, skipping.
error @slack/client@4.8.0: The engine "node" is incompatible with this module. Expected version ">= 6.9.0". Got "6.2.2"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Sorry if I should not re-open this thread, I can create a new issue if needed, but I think it is related. Anyways, am I missing something? been like 3 days I've been trying to run GPMDP to try to check #3383, but to no avail. 
System, OS and Node details are the same from @hazre
