### ISSUE TITLE
rebuild.sh complains about needing --module-dir

### ISSUE THREAD

**Issue by bashenk** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3287]
Attempting to build on Ubuntu 18.04, when it got to the the vendor/rebuild.sh, it gave an error to the extent of electron-rebuild not knowing where node_modules was and suggesting to specify it with `--module-dir`.

Was able to get it to work successfully by modifying the line to read
`.bin/electron-rebuild -f -e=electron --module-dir ..`

**Comment by MarshallOfSound** [comment]
Closing out as it is a development workflow thing rather than an actual issue with the app
