### ISSUE TITLE
Installing on machines with applocker?

### ISSUE THREAD

**Issue by TokenRing** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3288]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:** Windows 10 x64 1803

**GPMDP Version:** 4.6.0

**Issue Descriptions:** On machines that are setup with Microsoft's applocker restrictions, there's no way to install GPMDP, even when running as domain admin to try to circumvent. This is likely related to using squirrel installer, based on what I've found [here](https://github.com/Squirrel/Squirrel.Windows/issues/1128). Any other ways to install GPMDP so it can run from Program Files (which we have whitelisted for applocker, since you simply need to be an admin to install to there) or is squirrel -> appdata the only way this will work out?

**Steps to Reproduce:** Set up a computer with policies to block executables from launching from appdata (standard cryptolocker blocking procedure). Try to install GPMDP. Sadly, it will fail.

**Comment by MarshallOfSound** [comment]
>  is squirrel -> appdata the only way this will work out?

Yes
