### ISSUE TITLE
Uncaught Exception: The Internet connection appears to be offline.: (null)

### ISSUE THREAD

**Issue by stephancill** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#329]
An uncaught exception was reported.  
#### Info:
**OS:** darwin
**Arch:** x64
**GPMDP Version:** 3.0.0
**Time:** Mon Mar 07 2016 13:14:16 GMT 0200 (SAST)

#### Error:
*The Internet connection appears to be offline.: (null)*
```js
Error: The Internet connection appears to be offline.: (null)
    at Error (native)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MetalMatze** [comment]
I also got this right now.
It could be misleading to a user. Is it possible to not show the snackbar for this particularly error?

**Comment by MarshallOfSound** [comment]
Yeah, that's been fixed in maste

**Comment by MetalMatze** [comment]
:+1:
