### ISSUE TITLE
library namespace APIs for playing and pausing the song does not work

### ISSUE THREAD

**Issue by Jigar29** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3295]
I am using release 4.3.0 of GPMDP, I am interfacing my client with the web socket interface. But since in the beginning if there is no music, client can not control the playback. So in this case there has to be at least  one song in the queue. I am trying to put my album through Library namespace APIs and the APIs seems to not responding.

**Comment by MarshallOfSound** [comment]
4.3.0 is an old release and does not contain fixes in the later releases.
