### ISSUE TITLE
Logo in the Dock is not appropriate

### ISSUE THREAD

**Issue by nihanthd** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3296]
**OS:** Ubuntu 18.04 LTS

**GPMDP Version:** Cant find. Mostly 4.6.1

**Issue Descriptions:**The logo in the Dock is something that an application with no logo is present.

**Steps to Reproduce:**Install GPMDP. Launch the application & see the logo in Dock.
![screenshot from 2018-07-26 22-34-04](https://user-images.githubusercontent.com/6668844/43300311-0c552188-9124-11e8-9248-6dde1befdc96.png)

**Comment by MarshallOfSound** [comment]
The correct icon is definitely being set on works on my install of Ubuntu 18.04.  I'd suggest a bug in your WM or install has caused this.

**Comment by nihanthd** [comment]
@MarshallOfSound I will try to reinstall it. Thanks a lot.

**Comment by ericnicolaas** [comment]
@MarshallOfSound @nihanthd I'm seeing the same thing on Mac. However, the correct icon appears when viewing directly on my MacBook Pro's screen:

<img width="1280" alt="screenshot 2018-08-01 10 06 41" src="https://user-images.githubusercontent.com/676582/43494562-9b1b1c18-9572-11e8-887c-68f782ae4b01.png">

But when I plug into my monitor via HDMI, the icon is Mac's version of a fallback icon:

![screenshot 2018-08-01 10 07 39](https://user-images.githubusercontent.com/676582/43494593-c361214a-9572-11e8-9faa-39bb25784864.png)

The app's icon is the one at the far right.

**Comment by ericnicolaas** [comment]
FYI, here's my display info:

![screenshot 2018-08-01 10 11 38](https://user-images.githubusercontent.com/676582/43494732-656066a4-9573-11e8-9362-fcf925c6d2dd.png)

My monitor is this one: https://www.dell.com/en-us/shop/dell-27-monitor-se2717h/apd/210-aizr/monitor-accessories

**Comment by jespersh** [comment]
@ericnicolaas - your 2nd screenshot got cut off early it seems.

**Comment by khour** [comment]
Seems like a missing low-def (non-retina on mac) application icon.
I'm having same issue as @ericnicolaas: proper icon on MBPR display, mac default on the external full HD display.

**Comment by nihanthd** [comment]
On Macbook pro builtin display
<img width="1438" alt="screen shot 2018-08-06 at 11 04 40 am" src="https://user-images.githubusercontent.com/6668844/43727848-c1b21daa-9968-11e8-8e10-2e05dabbdea2.png">

On Mac Thunderbolt Display
![screen shot 2018-08-06 at 11 05 30 am](https://user-images.githubusercontent.com/6668844/43727925-08e316a2-9969-11e8-85a8-3c83090d84ac.png)
