### ISSUE TITLE
proxy setting

### ISSUE THREAD

**Issue by H0rstn** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#330]
is there a way to integrate a seperate proxy setting into the application? 
Maybe it would be helpfull for some people not to use the systems default proxy server. 

OS: Win7 / Win10
GPMDP Version: 3.0.0

**Comment by MarshallOfSound** [comment]
TLDR: Not really.

Javascript doesn't really have a concept of a proxy.  That is all handled by Chromium/Electron
