### ISSUE TITLE
Feature Request: Alarm Clock Support for System Format.

### ISSUE THREAD

**Issue by mcenal** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3300]
**Feature Request:** Setting Alarm Clock doesn't recognize system time settings. I always use 24 hour clock for everything when I get to the Alarm Clock it is not in the system time, and I think that makes sense since it is a locale feature for the local system.  (Even if it doesn't support reading the system time, being able to use a setting to set that would be cool.)

**Comment by MarshallOfSound** [comment]
Happy to take a PR for a feature like this but it's too complicated and too niche to be setting open on the issue tracker
