### ISSUE TITLE
4.6.1 Minimize to Tray

### ISSUE THREAD

**Issue by Ba11istix** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3303]
**OS**:
W7 Enterprise

**GPMDP Version**:
4.6.1

**Issue Descriptions**:
1. Minimizing minimizes GPMDP to the taskbar, not the tray even with the setting turned on. (Close closes to tray)
2. GPMDP is visible and can be switched to when Alt-Tabbing & Win-Tabbing when it is closed to the tray.

**Steps to Reproduce**:
1. Turn on Minimize to Tray in settings
2. Press minimize, app will minimize, not close to tray.
3. Maximise the app once more
4. Press close, app will minimise to tray (good)
5. Alt / Win Tab and it is still visible in the application list and can be launched despite being in the tray.

**Proposed solution**:
1. Fix tray - I belive the taskbar icon is being turned off, but the window is just minimized rather than going to the tray hence why it is still visible in the app switcher.
2. Add close to tray setting to compliment minimize to tray (m2t).

**Proposed behavior**:
m2t off, c2t off
Minimize: Minimize to taskbar icon, no tray icon shown at any point
Close: Close application

m2t on, c2t off
Minimize: Minimize to tray, remove taskbar icon
Close: Close application

m2t on, c2t on
Minimize: Minimize to tray, remove taskbar icon
Close: Minimize to tray, remove taskbar icon

m2t off, c2t on
Not selectable

**Comment by MarshallOfSound** [comment]
Minimize to tray takes affect when you click through close button

**Comment by Ba11istix** [comment]
Yes, the application does 'minimize to tray' - but it is not in the tray, only the taskbar icon disappears. Alt tab and you can bring the app back which should not be possible when truly in the tray.

![untitled](https://user-images.githubusercontent.com/31008127/43393566-8cc83abc-93ef-11e8-99da-4d7ce6982da5.png)

**Comment by Ba11istix** [comment]
In toggleMainWindow you have this:

```
global.wasMaximized = Settings.get('maximized', false);
win.minimize();
if (WindowManager.getWindowManagerName() === 'i3') {
    win.hide();
}
// Hide to tray, if configured
if (Settings.get('minToTray', true)) {
    win.setSkipTaskbar(true);
}
```

I'm not sure what i3 would be as a Window manager, but assuming it is not for a Windows base and minToTray is true the app gets minimized, and setSkipTaskbar is called with true (removing the taskbar icon) - but the app is still only minimized. I believe there should be a further `win.hide()` to hide the window as is it now in the tray only.

**Comment by Ba11istix** [comment]
@MarshallOfSound , not sure if you will still get notifications for this or not, found one more issue though

![2018-07-30 16_35_06-greenshot](https://user-images.githubusercontent.com/31008127/43407709-609c868c-9417-11e8-8ae6-bb1a39c14f0e.png)

This is the AltTab view (the one where I believe the window should not be shown when in the tray), the app is still selectable and will come to into focus, but because it has not been restored properly the taskbar icon is not displayed.

**Comment by e2t** [comment]
This problem is still relevant.
