### ISSUE TITLE
Cannot cancel creating accounts

### ISSUE THREAD

**Issue by yunosh** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3304]
**Checklist:**

* [X] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [X] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [X] I have double checked and can reproduce the issue

**OS:**

MacOS High Sierra

**GPMDP Version:**

4.6.1

**Issue Descriptions:**

If creating new account from the accounts button/popup, the process cannot be cancelled, and I cannot return back to the main view anymore. Even closing and restarting the player takes me back to the login form for Google accounts.

**Steps to Reproduce:**
* Click on accounts icon on top right.
* Click on menu item to create new accounts.
* Be locked in to the Google accounts login screen

**Comment by MarshallOfSound** [comment]
^^ deleting your settings cache will fix the issue 👍

**Comment by dzek69** [comment]
How about giving an option to reset the app just in case something goes wrong? I guess you are aware that this workaround can fix a lot of issues, so providing this as an option would make life easier for a lot of people - especially when all of them IIRC mentioned that they did a uninstall before reporting - so I guess they'd try reset option too (I'd make it an tray icon menu option).

BTW: As an alternative (or you can do both) could you please make the app clean up the data folder after uninstall?
