### ISSUE TITLE
Freezing and high hardware load

### ISSUE THREAD

**Issue by barbariska108** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3305]
**OS:**
KDE Neon(Ubuntu 16.04 LTS)
**GPMDP Version:**
4.6.1
**Issue Descriptions:**
Freeze and memory load
**Steps to Reproduce:**
![image](https://user-images.githubusercontent.com/11057396/43398918-18f5e5f8-9412-11e8-873b-03acb8808a52.png)
After install and start using GPMDP load CPU and RAM more highly.

**Comment by scj643** [comment]
Can confirm on
**OS:*
Fedora workstation 28 (VM Ware workstation)
**GPMDP VERSION:**
4.6.1

After first run it infinitely loads

**Comment by dk0r** [comment]
❤️GPMDP 4.6.1 but it makes my system unusably slow.

OS: macOS 10.13.6
System: Macbook Pro 2018 | 2.9GHz i9 | 32GB

![image](https://i.imgur.com/1XZecgJ.png)

**Comment by inibg** [comment]
Same issue here:

GPMDP Version:
4.6.1

![image](https://user-images.githubusercontent.com/5316741/43715045-82fac520-9955-11e8-9705-bcb5866da54f.png)


![image](https://user-images.githubusercontent.com/5316741/43715013-696f1872-9955-11e8-867a-b44641eb2d2b.png)

**Comment by Alipoodle** [comment]
You using any settings like Discord Rich Presences?
*as this has previously caused these issues*

**Comment by inibg** [comment]
Yes, I removed that option and now the CPU has values around 5.2%

**Comment by scj643** [comment]
In my case I don't have discord intigration enabled

**Comment by damiong28** [comment]
Can confirm, disabling Discord Rich Presence option and restarting the program solved the high CPU usage problem for me.

**Comment by maddanio** [comment]
here it was "system window borders". any idea what is causing it? it basically makes it useless as a music player for working along to for anyone actually needing most of her resources...

**Comment by Lite5h4dow** [comment]
Discord rich presence was the issue for me too, any ETA on a patch?

**Comment by MarshallOfSound** [comment]
Merging into #3332
