### ISSUE TITLE
Feature request: search in page

### ISSUE THREAD

**Issue by mkeedlinger** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3306]
**It would be amazing to be able to search in the page (similar to ctrl-f in Chrome and friends).** I keep a lot of songs in playlists, but when I want a specific song that is in a playlist, in can be a pain to search for it.

I would use the search bar, but sometimes there can be many versions of the same song, why search through that when I could just search in my playlist?

Note: wonderful app, I use it daily! Thanks 😊

<hr>

**Checklist:**

* I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL** (I did)
* I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* I have double checked and can reproduce the issue **(not a bug)**

**Comment by dzek69** [comment]
This is not possible to do. Verify it on browser. Remember first song on your long playlist (liked songs I guess). Scroll down a bit, trigger browser search and try searching for that song title. No matches.

Why?

It's a performance optimization (which sucks anyway on Google Music) - items that are not in view are removed from the page thus cannot be found. On my resolution Google keeps 42 elements of a list in memory only. Scrolling down removes these on top and adds new ones on bottom.

**Comment by mkeedlinger** [comment]
Wow, from what I remember you are totally right!

This will make it a lot more painful to implement, but since they must keep what songs are on the page stored somewhere, and must have some way of scrolling to a certain song (this happens when I search for a song later in an album), there's probably a way to make a feature like this anyways.

I have work right now, but hopefully in the next month or so I could implement this feature. Is it possible to assign this issue to me even though I don't have access to the repo? If not that's fine, I'll just put it on my to-do list.

**Comment by MarshallOfSound** [comment]
> This is not possible to do. Verify it on browser. Remember first song on your long playlist (liked songs I guess). Scroll down a bit, trigger browser search and try searching for that song title. No matches.

Yup, that's been the story for most of the features in this app.  We need a lot of UI hackery and reading GPM's internal state to figure out what's going on.  In this case you're right, we can't work around it
