### ISSUE TITLE
Stuck on a registration page after using VPN

### ISSUE THREAD

**Issue by TobiOsu** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3307]
**Checklist:**

* [ X] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [X ] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [X] I have double checked and can reproduce the issue

**OS:**
Windows
**GPMDP Version:**
V4.6.1
**Issue Descriptions:**
Swapping between Google play music and Youtube music while being connected to my VPN in Switzerland (Mullvad VPN), I'm now stuck in an infinite loop of this screen: https://imgur.com/a/cjjmF6W. Swapping back between the two players even after stopping the VPN and restarting my machine + reinstalling the app still gives me that screen.
**Steps to Reproduce:**
Connect to a VPN (I used Mullvad and a server in Switzerland) and swap between Google play music and Youtube Music from the hidden icons on the windows bar.

**Comment by MarshallOfSound** [comment]
^^ deleting your settings cache will fix the issue 👍
