### ISSUE TITLE
Unable to cast to chromecast in youtube music

### ISSUE THREAD

**Issue by jmmunger** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3310]
I know that the youtube music side is in alpha. 

I just wanted to point out that there is no way of casting to chromecast. I'm able to do if from the Google music UI.

It is likely that the cast icon is simply not in the UI of youtube but still it would be interesting if one could cast anyway.

**Comment by MarshallOfSound** [comment]
> It is likely that the cast icon is simply not in the UI of youtube music

This is currently the case, as soon as YTM implements chromecast this player's chromecast implementation will pick it up easily 👍
