### ISSUE TITLE
Core dump after 4.17.12 upgrade on Arch Linux

### ISSUE THREAD

**Issue by TheSorton** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3312]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**
Arch Linux
**GPMDP Version:**
4.6.1-1
**Issue Descriptions:**
Core dump after Linux 4.17.12 upgrade. Not other output is shown in the terminal.
`[1]    2067 segmentation fault (core dumped)  gpmdp`

**Steps to Reproduce:**
Upgrade to 4.17.12 on Arch Linux
Attempt to open gpmdp

**Comment by sztosz** [comment]
The same happens when I try to open slack, so I vaguely susspect electron here.

**Comment by polifolia** [comment]
Same error here

**Comment by BrianAllred** [comment]
Building from source results in the same.

I run Caprine, and it seems to be fine. Maybe not all electron apps?

**Comment by TheSorton** [comment]
Discord isnt having this issue either, so it's not *all* electron applications.

**Comment by BrianAllred** [comment]
Might actually be a bug upstream with glibc, Guitar Pro 6 is broken as well.

**Comment by TheSorton** [comment]
> Edit: Looks like it's glibc 2.28-1. Downgrading to 2.27-3 fixed it. According to these comments, you can patch the binary to work with the old glibc side-by-side with the new one.

The patch worked. Its a workaround for now at least.

**Comment by Amosar** [comment]
Another workaround is to install electron from the community repo and launch gpmdp with 
``electron --app=/usr/share/gpmdp/resources/app.asar``

workaround found here : https://aur.archlinux.org/packages/gpmdp/

**Comment by MarshallOfSound** [comment]
My understanding of this is that glibc broke a thing upstream as they are supposed to be 100% backwards compatible.  This should be tracked with glibc

**Comment by BrianAllred** [comment]
People are reporting success running with a newer version of electron, so I think it'll be fixed automatically whenever a release is made with updated dependencies.

**Comment by deanveloper** [comment]
Also broken now in Ubuntu Cosmic Cuttlefish (18.10)

**Comment by purpl3F0x** [comment]
Same problem here

```
$ google-play-music-desktop-player
    Segmentation fault (core dumped)
```

**Comment by jostrander** [comment]
Resolved in master
