### ISSUE TITLE
Client enters infinite loading state when navigating to specific artist page

### ISSUE THREAD

**Issue by alexismo** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3314]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:** Mac OS 10.13.6

**GPMDP Version:** 4.6.1

**Issue Descriptions:** Client enters infinite loading softlock (UI is no longer clickable) when trying to navigate to artist Angra (https://play.google.com/music/listen?u=0#/artist/Avoug7dbg4cjhoycszt25hjhuge/Angra on GPM)

Have reproduced several times over the course of 2 days, restarting the client between each use, validating that the Artist page is accessible on the web version of GPM.

**Steps to Reproduce:** 
Navigate to Angra artist page from anywhere (search, clicking album artist)
This is probably not the only artist page where this happens. I am reporting it as a starting point.

[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/2266424/debug_info.zip)

**Comment by WillPresley** [comment]
For what it's worth, I can get to that artist page without any issue, using latest official 4.6.1

**Comment by sitzmar** [comment]
Just upgraded to 4.6.1 today and immediately hit this issue. MacOS 10.13.4

**Comment by charlwillia6** [comment]
I have the same issue with 4.6.1.  And it is very slow loading, and very slow navigating to other pages.  Sometimes it just stops playing music too and I have to re-select a song to get it started again.  

This is happening on Windows 7 and Manjaro Linux 2018.08.06

**Comment by charlwillia6** [comment]
I notice now that this issue doesn't happen has often if I use the default GP theme, and I do not use the custom themes.

**Comment by MarshallOfSound** [comment]
Duplicate #3373
