### ISSUE TITLE
How to check current version installed?

### ISSUE THREAD

**Issue by silvernode** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3316]
I checked closed issues and didn't see this mentioned. 

I was trying to remember if I updated my player recently and was looking for a version number in the settings or maybe an "about" section of GPMDP but couldn't find anywhere that lists what version I have. 

Thanks for all the hard work.

**Comment by MarshallOfSound** [comment]
Thanks @jespersh
