### ISSUE TITLE
Cache music and set higher download priority

### ISSUE THREAD

**Issue by Draethorian** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3317]
Hey, I was wondering if you could cache the downloaded music somewhere and/or set a higher download priority, because obviously my internet connection kinda sucks and downloading photoshop while listening music constantly causes gpmdp to lag.

Is there something to set a priority to your router? that you need some data with a minimu speed of x KB/s something. that'd be great...

**Comment by MarshallOfSound** [comment]
> Hey, I was wondering if you could cache the downloaded music

Unfortunately no we can't
