### ISSUE TITLE
Taskbar hover text showing current song with previous songs artist

### ISSUE THREAD

**Issue by ASeale** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3318]
**OS:** 
Windows 10

**Issue Descriptions:** 
The hover text in the taskbar is showing the current song title with the previous songs artist. Example song Radioactive by Imagine Dragons, previous song Master of Tides by Lindsey Stirling, hover text shows "Radioactive - Lindsey Stirling"

**Steps to Reproduce:**
I'm not sure the steps to reproduce as I just happened to notice by accident, but all I did was restart my computer and the player continued where I left off. This was the first song (in the screenshot) that it played on restart but the next 2 songs (and that's the song I'm on now) continued with the issue. It's currently showing "Believer - Vance Joy". This is not reproducible by just closing and reopening the app as that puts the current song as the top item in the playlist (the hover text is correct from then on). It has to be something about restarting the system with the current song paused and several down in the list. Whatever triggers the list to not reset but just reload where it was.

![image](https://user-images.githubusercontent.com/21082704/43844114-fb5180a2-9af6-11e8-80c5-a3d1275a3675.png)

**Comment by MarshallOfSound** [comment]
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3180
