### ISSUE TITLE
Everything is really slow, compared to a browser

### ISSUE THREAD

**Issue by theLMGN** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3319]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [X] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [X] I have double checked and can reproduce the issue

**OS:** Windows 10 1803

**GPMDP Version:** 4.6.1

**Issue Descriptions:** Everything is way too load. It takes a long 60 seconds  load the app, and then another 1:30 load songs.

**Steps to Reproduce:** Just install it

It's not a network problem. It works fine in Chrome.

**Comment by theLMGN** [comment]
Also, on an unrelated note, it'd be nice to have a option to disable media keys.

**Comment by lguerard** [comment]
Can confirm that on Linux Mint 19 as well.

**Comment by Newgap** [comment]
You can check the version by right-clicking the icon in the clock tray, Help, About.

**Comment by theLMGN** [comment]
@Newgap Thanks, updated.

**Comment by hutchhicken** [comment]
I'm having the same experience on Ubuntu 18.04.

**Comment by lguerard** [comment]
Can also confirm it on Windows 10. Any ideas why this is like that ?

**Comment by Hedronmx** [comment]
Can confirm. Running 4.6.1 on Elementary os (Ubuntu based) and it becomes super slow after a couple of seconds of the app running.

**Comment by pieter-biesemans** [comment]
This is an Electron app. Electron is known or being slow. It doesn't help that Google builds the play music pages specifically to the latest Chrome builds, while Electron uses an older Blink engine. Please check [here](https://github.com/electron/electron/issues/5672) for more information on these Electron issues.

**Comment by hutchhicken** [comment]
Previously things worked fine. Using many electron apps, I know that there is a performance penalty to pay, but that has never meant full non-responsiveness and ultimate crashing on modern hardware when doing nothing but streaming audio, as is what is happening here.

**Comment by theLMGN** [comment]
I've only noticed it with chrome/chromium based apps (excluding discord for so me reason) recently, and only Windows.

**Comment by DaemosDaen** [comment]
Had this issue as well, re-installing the GPMDP and this resolved the issue. I think it has something to do with the buildup of cache. The app provides no way to clear it, it was not till I re-installed the app did I realize that this can be done in Edge, IE, or Chrome

**Comment by theLMGN** [comment]
@DaemosDaen I tried Arch yesterday for a bit and literally ass soon as it was installed it was lagging

**Comment by MarshallOfSound** [comment]
Quite a few performance improvements have landed recently and the upgraded Electron version will be a win in this area.  Gonna close this out for now as it turned into a catch all "something is slow" issue
