### ISSUE TITLE
Druplicate last.fm scrobbles

### ISSUE THREAD

**Issue by bricas** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3320]
**Checklist:**

* [X] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [X] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [X] I have double checked and can reproduce the issue

**OS:** Pop!_OS 18.04

**GPMDP Version:** 4.6.1

**Issue Descriptions:** I typically just play my "thumbs up" playlist on random at work. When i go back and look at my last.fm scrobbles, I'll see a few duplicates in the list. I haven't been able to find a pattern to the issue yet. I'll update the ticket if I see something.

**Steps to Reproduce:** Play songs for a while whilst scrobbling to last.fm

**Comment by bricas** [comment]
I should add that I typically use the mini player. Perhaps I'll try a day's worth of playing in the large player and see if it happens there.

**Comment by bricas** [comment]
Update: I had duplicate scrobbles today with the app in "full size player" mode

**Comment by MarshallOfSound** [comment]
Without a way to consistently reproduce this we can't look into fixing it
