### ISSUE TITLE
Bug: Player doesn't resize on vertical monitor

### ISSUE THREAD

**Issue by jbaruch76** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3322]
**OS:**
Windows 10

**GPMDP Version:**
4.6.1

**Issue Descriptions:**
On a vertical monitor set to 1080x1920 the player bar gets cut off
<img width="558" alt="capture" src="https://user-images.githubusercontent.com/5239206/43962512-dbe580ac-9c85-11e8-83b9-e447ab6b1d63.PNG">

**Comment by MarshallOfSound** [comment]
This min-width is set my google play music because their UI doesn't work at smaller widths 😢 out of our control on this one

**Comment by jbaruch76** [comment]
My apologies, thanks for your great work.
