### ISSUE TITLE
Can't open GPMDP on Ubuntu.

### ISSUE THREAD

**Issue by RasmusKallas** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3325]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL** For people who don't contribute to code Github should default the search to all issues...
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:** Ubuntu Budgie 18.04 LTS (Fresh install)

**GPMDP Version:** 4.6.1.

**Issue Descriptions:** When opening, no window shown, after some time it closes.

**Steps to Reproduce:** Install Ubuntu Budgie 18.04 LTS, go to https://www.googleplaymusicdesktopplayer.com/, download 64-bit debian package, install it, open it.

**Comment by RasmusKallas** [comment]
Note: before fresh install (few days ago) it was working fine. (Could be version change, then it didn't have a fancy icon)

**Comment by silvernode** [comment]
I just want to point out that while you wait for a reply that has a solution, in the meantime you can use the flatpak package which is up to date as of this writing (4.6.1). Flatpak is [easy to setup](https://flatpak.org/setup/Ubuntu/) on Ubuntu if you are unfamiliar and don't already have it installed. After following those instructions you can install GPMDP by running the following command:  
```
flatpak install flathub com.googleplaymusicdesktopplayer.GPMDP
```
Alternatively you can use the Gnome Software graphical tool then search for "google music" and install GPMDP that way once flatpak is set up from the instructions linked above.

Note: flatpak how I install GPMDP on new systems it works like a charm.

**Comment by RasmusKallas** [comment]
It appears that this is now fixed.
