### ISSUE TITLE
Add FAQ Entry for Mini-Player

### ISSUE THREAD

**Issue by abyss** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3326]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:** Windows 10

**GPMDP Version:** 4.6.1

**Issue Descriptions:**
When viewing at a smaller window size, the mini-player button doesn't appear. I'm aware this likely isn't something you can change (because I believe that's on Google's side) - but what I think you could do is add an FAQ entry to the effect of:

> How do I open the Mini-Player? 
> To open the mini-player, make sure the window is large enough (specify size?) and click this button here: (picture of the icon).

I actually couldn't figure it out, saw nothing in the FAQ, and ended up looking through the issues find what button it even was, and then realize I had to make the window larger for that button even to appear!

I could add it to the FAQ myself, if you're fine with that.

**Comment by jostrander** [comment]
Totally acceptable to add this to the FAQ. Feel free.
