### ISSUE TITLE
Open album art image when clicking art in bottom corner

### ISSUE THREAD

**Issue by omarzion** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3327]
This isn't a bug, just a feature request.
Currently to view album art in shadow box you have to go to the album then click the image at the top of the album.
I would like to be able to click the album art in the bottom corner (the art of the new playing) to get the same effect

When clicking album art in bottom corner
![image](https://user-images.githubusercontent.com/11347689/44169165-39810f80-a099-11e8-9f1d-f7eb742eae5c.png)
Open album art preview
![image](https://user-images.githubusercontent.com/11347689/44169198-4dc50c80-a099-11e8-85e8-afe0f3c33617.png)

**Comment by MarshallOfSound** [comment]
Google used to do this, now they don't, if you want it back you can give that feedback on their product forums.

**Comment by Ciatzo** [comment]
@MarshallOfSound Is this not something that the the desktop client could offer as an extra feature? The client offers a lot of functionality that google does not right?
As somebody who has the client open on a second monitor 90% of the time, this would be a very nice feature, although i understand it probably does not have a very high priority
