### ISSUE TITLE
OS X: UI not confroming to standards

### ISSUE THREAD

**Issue by stejmurphy** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#333]
Great application.

Under OS X, the orange UI bar has the generic min/expand/quit options on the far right. These should be the OS X Red/Yellow/Green standard and appear on the far left of the application window.

**Comment by kminehart** [comment]
I think there's already a pull request for using the native UI in OS X and Linux.

**Comment by MarshallOfSound** [comment]
There's an issue lying around somewhere.  I have completely lost track....  This repo only had 1 issue yesterday morning and it was "Release 3.0.0"......
