### ISSUE TITLE
Snap version is old?

### ISSUE THREAD

**Issue by ipkpjersi** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3331]
**Checklist:**

* [X] I have checked that there are no issues with similar or the same content

  * [X] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [X] I have double checked and can reproduce the issue

**OS:** Ubuntu 16.04

**GPMDP Version:** 4.5.0?

**Issue Descriptions:** I can't install the latest version of GPMDP using snaps. Here are the versions that are available to me: ![](https://i.imgur.com/O6RO4Iv.png)

**Comment by Alipoodle** [comment]
As mentioned in the [FAQ](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/Unofficial-Releases), 
> All unofficial releases, packages, and repositories are the responsibility of their respective maintainer.

You will need to go to Chris / [The snap page](https://launchpad.net/~raof/+snap/google-play-music-desktop-player) to ask for an update

**Comment by jostrander** [comment]
@RAOF Can you check into why gulp-cli is failing to install in the snap build?

**Comment by MarshallOfSound** [comment]
Closing out, feel free to use this issue thread to track it down though
