### ISSUE TITLE
Gnome integration

### ISSUE THREAD

**Issue by Magnera** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3333]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

Solus OS (Gnome 3.28.2)

GPMDP Version 4.6.1-9

Issue Descriptions: GPMDP integration with Gnome is broken

Steps to Reproduce: Just open GPMDP and the media keys shortcut does not work and the current track is not displayed in the notifications. (the taskbar icon shows correctly)

GPMDP integration with Gnome is broken after the last update to 4.6.1-9, i've tried to remove the program and installing again with no success. Anyone know how to fix this?

![captura de tela de 2018-08-22 15-51-04](https://user-images.githubusercontent.com/42620786/44485347-a9a60d00-a626-11e8-8eb9-e55573374439.png)

**Comment by MarshallOfSound** [comment]
Works for me on latest Ubuntu as well, guessing there's something going on specific to your WM / desktop environment setup

**Comment by Zeka13** [comment]
same shit in 2020

**Comment by jostrander** [comment]
@Zeka13 PR's are welcome 😄
