### ISSUE TITLE
Issue with Discord RPC

### ISSUE THREAD

**Issue by Jayden000** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3334]
**OS:  Windows**

**GPMDP Version: Latest**

**Issue Descriptions: Discord RPC - When it goes to the different song it updates the title but not the artist. Example: I am currently playing post malone I fall apart. Discord RPC is normal but then when it skips to the next song the RPC says the right song but post malone. Gif is attached**
![issue](https://user-images.githubusercontent.com/23621862/44613569-2aaa0380-a7e3-11e8-9be1-bcc70adf7549.gif)

**Comment by SolarLiner** [comment]
This looks like YouTube Music. On Linux, a similar issue happens where MPRIS doesn't receive the full updated metadata. I think this is a general issue rather than just a Discord RPC one.

**Comment by MarshallOfSound** [comment]
This is a known issue with our youtube music logic, there is an issue for it somewhere but I can't find it on my phone 😄
