### ISSUE TITLE
flatpak app name length can cause socket failures

### ISSUE THREAD

**Issue by tjkirch** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3335]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:** Ubuntu Linux 18.04.1

**GPMDP Version:** 4.6.1

**Issue Descriptions:** Linux, and other Unix-like OSes, only support socket paths of a certain length.  On my machine this is 108 characters.  Flatpak constructs a socket in your home directory containing the app name, which in this case is "com.googleplaymusicdesktopplayer.GPMDP", which is 38 characters.  There's also a chromium component which consumes 29 characters, and some other overhead.  This leaves 20 characters for $HOME when the limit is 108, and if you go over, the app will fail to start.

The socket length limit is baked into the OS, and users don't always have control over their $HOME path, so I'd like to suggest that we shorten the app name for flatpak distribution.

**Steps to Reproduce:**

* Have a $HOME longer than 20 characters
* `flatpak run com.googleplaymusicdesktopplayer.GPMDP`
```
[3:0828/133236.504752:FATAL:process_singleton_posix.cc(226)] Check failed: path.length() < arraysize(addr->sun_path). Socket path too long: /home/MY-CORP-DOMAIN/tjk/.var/app/com.googleplaymusicdesktopplayer.GPMDP/cache/.org.chromium.Chromium.LHMAd4/SS
```

If my $HOME is "/home/local/DOM/tjk" (19 characters) instead of "/home/MY-CORP-DOMAIN/tjk" (24 characters) then it works:
```
flatpak run com.googleplaymusicdesktopplayer.GPMDP
Starting Sentry
...
```

**Comment by tjkirch** [comment]
I had assumed the owners were the same, sorry.

**Comment by MarshallOfSound** [comment]
Should be tracked on the `flathub` issue
