### ISSUE TITLE
Status of the Android app

### ISSUE THREAD

**Issue by tjorim** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3336]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**
Android

**GPMDP Version:**
N/A

**Issue Descriptions:**
What is the status of the Android app, is it still maintained?
Looks like it was pulled from the Google Play Store:
play.google.com/store/apps/details?id=com.marshallofsound.gpmdp.remote

**Steps to Reproduce:**
1. Go to the homepage: https://www.googleplaymusicdesktopplayer.com/
2. Scroll down to "Mobile Remote Control" and click the button to "Get it on Google Play"
3. See the message "We're sorry, the requested URL was not found on this server."

**Possible Solution:**
If possible, check the reason it was pulled, work around it and publish again.
Otherwise, just remove the link from the homepage since it could confuse people.

Already opened an issue here: https://github.com/GPMDP/google-play-music-desktop-remote/issues/21, but thought for a second it was the wrong place (which might probably still be the correct place after all).

**Comment by MarshallOfSound** [comment]
It was pulled from the play store because I didn't click some red tape buttons around ratings and child content or something.  I'll fix it shortly

**Comment by rbsns** [comment]
Hi! It's still unavailable on Play Store:
https://play.google.com/store/apps/details?id=com.marshallofsound.gpmdp.remote
