### ISSUE TITLE
Chromecast Support removed?

### ISSUE THREAD

**Issue by combatratcat** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3337]
<!---

Missing the Chromecast Streaming Button, it says in FAQ it should be there and i believe it was... was it removed?

Greetings Marco

**Windows**

**Downloaded newest 29.08.2018**

**Chromecast Streaming Button missing**

**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment]
It's still there
