### ISSUE TITLE
Chromecast Streaming Button missing.

### ISSUE THREAD

**Issue by combatratcat** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3338]
As noted the Chromecast streaming button was not removed then id like to report this issue of the button not showing for me.

![2018-08-29 20_33_32-side effects feat emily warren - the chainsmokers](https://user-images.githubusercontent.com/6838119/44807830-d9c35200-abca-11e8-8b01-ffb583e3c3b1.png)

See Screenshot

Besides it seems i'm not the only one missing the button:
https://productforums.google.com/forum/#!msg/chromecast/acO5axWYUcU/FH71uifACAAJ

please help and not just close the issue.

greetings Marco

**Comment by MarshallOfSound** [comment]
You raised an issue with no body and just a title, I closed it, you then go and raise a duplicate asking me not to close it.  I'm sorry that's not how this works.

The thread you linked is from 2016 and entirely irrelevent to the way the app works today.  The best I can suggest if if you are on windows you need to install Bonjour for Chromecast to work
