### ISSUE TITLE
volume buttons in Wrong place on player

### ISSUE THREAD

**Issue by Deckee** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3339]
[* ] I have checked that there are no issues with similar or the same content
 [* ] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-
 [* ] I have double checked and can reproduce the issue

If you have done those 3 things go ahead and fill out the information below.
Once again, thanks for taking the time to submit an issue

If appropriate please attach the DEBUG information zip file that you can generate by following the instructions in the FAQ  
(https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/2334430/debug_info.zip)
)  

OS: ubuntu/kubuntu 18.04
GPMDP Version:4.6.1
![image](https://user-images.githubusercontent.com/8199121/44826749-dd100b00-abd5-11e8-8855-a544c7b4cbb8.png)

Issue Description: the volume and slider are way out of position 
Steps to Reproduce:open gpmdp, play song and hover over the volume slider on the ui.

**Comment by MarshallOfSound** [comment]
This is a UI glitch on Google's side, hopefully they fix it for you soon 👍
