### ISSUE TITLE
Snap and Release Repository Versions not up to date

### ISSUE THREAD

**Issue by FelixGail** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3340]
**OS:**
Ubuntu 18.04 64bit
**GPMDP Version:**
4.0
**Issue Descriptions:**
The version in the release repository does not seem to be up to date for ubuntu 18.04.
**Steps to Reproduce:**
Install the player from the release repository:
[https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/docs/Installation_On_Debian.md](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/docs/Installation_On_Debian.md)

**Comment by SolarLiner** [comment]
It's already been the case for quite some time, see #3007. Both the snap package and flatpak are active and up to date, though, and these newer formats are better suited and preferred.

**Comment by zyrorl** [comment]
What can we do to help get this happening?

**Comment by MarshallOfSound** [comment]
I don't maintain the snap or flatpak distribution, if they're out of date you need to follow up with the owners of those packages.

**Comment by GCorbel** [comment]
I have the same issue. The debian repo and the snap repo are not up to date. @MarshallOfSound You seems to be the owner of the debian repo. Do you plan to update it?

**Comment by blandin** [comment]
I installed 4.4.1 manually when this issue first presented itself, expecting it to get resolved at some point.

```
$ apt list google-play-music-desktop-player -a
Listing... Done
google-play-music-desktop-player/now 4.4.1-1 amd64 [installed,local]
google-play-music-desktop-player/debian 4.4.0-1 amd64
google-play-music-desktop-player/debian 4.2.0-1 amd64
google-play-music-desktop-player/debian 4.0.5-1 amd64
google-play-music-desktop-player/debian 4.0.3-1 amd64
google-play-music-desktop-player/debian 3.2.5-1 amd64
```

4.4.0 is still the latest version available in the repo. @MarshallOfSound is there any plan at all to address this?
