### ISSUE TITLE
AppleScript support

### ISSUE THREAD

**Issue by kazak1377** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3341]
Hello!

I am using better touch tool for scripting the touchbar on new MacBooks. And wanted to add support for controlling the GPMDP from Touch Bar buttons with changing buttons status (play/pause) and showing the current playing song. 

For iTunes I can use apple script like this:

```applescript
if application "iTunes" is running then
	tell application "iTunes"
		if player state is playing then return "pause"
	end tell
end if

return "play"
```

```applescript
if application "iTunes" is running then
	tell application "iTunes" to playpause
else
	tell application "iTunes" to activate
end if
```

And it would be great to be able to do something similar to GPMDP

I know about playback API, but can't use ws to control GPMDP from AppleScript

**OS:**
macOS 10.13.6

**GPMDP Version:**
4.6.1

**Comment by MarshallOfSound** [comment]
We have our playback API which spits out JSON metadata files and uses a websocket to do two way player control.

You just need to figure out how to do that wiring.  Also we do integrate with macOS's media service so the OS should know our app is playing music.

**Comment by andrewshipe** [comment]
Stumbled on this and I found a way to hook in through the app UI via AppleScript. This is working for me in a Keyboard Maestro macro:
`tell application "System Events"
tell process "Google Play Music Desktop Player" to click menu item "Play / Pause" of menu "Playback" of menu bar 1
end tell`
