### ISSUE TITLE
YouTube Music app/tray icon

### ISSUE THREAD

**Issue by krestaino** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3342]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**
elementary OS 0.4.1 Loki

**GPMDP Version:**
4.6.1

**Issue Descriptions:**
A feature suggestion, when using YouTube Music, change the icon to YouTube instead of GPM.

**Steps to Reproduce:**
N/A

**Comment by MarshallOfSound** [comment]
Not a fan of this idea personally, I want it to feel like a single player, not two players jammed into one application.
