### ISSUE TITLE
Playback buttons are laggy and even hangs the entire session

### ISSUE THREAD

**Issue by ndac-todoroki** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3344]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES AS WELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**
Ubuntu 18.04, GNOME3, Wayland

**GPMDP Version:**
4.6.1

**Issue Descriptions:**
UI elements that does playback (Play/Pause button, Previous button, Next button, pressing Play in the songs list view) lags pretty much,
and Play/Pause-ing via the space key hangs the application and the OS too.

The music it self stops without lag, but the GUI seems not responding quickly. Even the cursor stops from moving for about a second.

No other elements is laggy (Tried thumbs-up, menu buttons, and show-the-mini-player button).

I cannot reproduce this in Chromium (accessing GPM) nor vanilla Electron (`window.location = "https://play.google.com/music/listen#/now"`).

**Steps to Reproduce:**
1. Open GPMDP
2. Play some song (lags once)
3. Try to pause by pressing the P/P button (lags again)
4. Hit the space key (hangs up)

**Comment by timoschwarzer** [comment]
Same on Ubuntu 18.04 with `gnome-session` on X.Org with proprietary nvidia drivers.

**Comment by kode54** [comment]
Try replacing the Electron binaries? There were some issues with 4.6.1 on KDE where it would outright segfault on startup, so maybe that version of Electron is bugged on Gnome, too. If all else fails, update to git master and build your own 64 bit deb package with the scripts? The FAQ isn't too clear on that, you really only need the dev packages for the relevant libraries, and none of the gcc or multilib versions specified, as they've gone through several major versions since then.

**Comment by timoschwarzer** [comment]
I tackled the issue down to being the system tray's fault or better the way GPMDP sets the tray icon.

I forked the repo and fixed the issue by not setting the icon every time the menu changes. (I actually don't know the reason why this has been done.)
And I updated Electron to 3.X, too.

You can see the changes [here](https://github.com/timoschwarzer/gpmdp) and download the updated version [here](https://github.com/timoschwarzer/gpmdp/releases/tag/4.6.1-gnome-freeze-fix).

**Comment by MarshallOfSound** [comment]
This will be fixed in an upcoming Electron upgrade
