### ISSUE TITLE
Unable to sign in due to authenticator not loading in app

### ISSUE THREAD

**Issue by drksilenc** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3347]
**Checklist:**

* [ ] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [ ] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [ ] I have double checked and can reproduce the issue

**OS:**
Win 10 64 1803
**GPMDP Version:**
4.6.1
**Issue Descriptions:**
Unable to sign in now that i am using google Advanced protection platform
**Steps to Reproduce:**
click sign in, enter username and password. then the auth screen shows the u2f key. it never registers the u2f key.

**Comment by jostrander** [comment]
This was discussed just yesterday in #3343. It's not supported upstream so not implemented in the player.

**Comment by larsen161** [comment]
For those not also following #3343 security keys with electron is being done
https://gsuiteupdates.googleblog.com/2018/10/securely-log-in-to-hangouts-chat.html
