### ISSUE TITLE
Feature Request: Sync last.fm likes to Google Play Music "Thumbs Up"

### ISSUE THREAD

**Issue by liesnikov** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3348]
- [x] I have checked that there are no issues with similar or the same content  
        The only relevant I could find were:  #1799 #1599

As for now, app sends songs, which are "thumbed up" on google play music desktop player to last.fm.

Is it possible to do the reverse -- e.g. when gpmdp starts it checks last.fm likes (loves) and syncs them with google play music "thumbs up"?

**Comment by MarshallOfSound** [comment]
> Is it possible to do the reverse -- e.g. when gpmdp starts it checks last.fm likes (loves) and syncs them with google play music "thumbs up"?

Basically, no, liking a song in GPM is done by faking interaction with the UI, to like songs you aren't listening to currently we would have to navigate to the song, play it, like it and then repeat for any song loved on last.fm.
