### ISSUE TITLE
~/GPMDP_STORE folder in in linux distributions

### ISSUE THREAD

**Issue by hashworks** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#335]
Seems like there is a `~/GPMDP_STORE` folder created in linux distros. I think this is the wrong place for stuff like that since you're already using `~/.config/Google\ Play\ Music\ Desktop\ Player`. If you want to keep it there you should prefix it with a dot, otherwise people will likely always remove it when they see it.

![Image of folder](https://hash.works/img-2016-03-07-144730.png)

**Comment by MarshallOfSound** [comment]
There is an open Pull Request to fix this issue, and another issue somewhere.

#267 I think

**Comment by hashworks** [comment]
Ah, sorry.
