### ISSUE TITLE
Youtube Music - Rich Presence

### ISSUE THREAD

**Issue by Dianolve** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3350]
Not really an issue, just preference,for the discord rich presence, when its on YT Music mode for GPMDP it still shows up as "Google Play Music"  on discord
![sssssssssssssssss](https://user-images.githubusercontent.com/43133178/45332943-e70f1200-b5b6-11e8-8adf-7dcdb95723b0.PNG)

**Comment by simoniz0r** [comment]
It also seems to always be a song behind for the artist?
![image](https://user-images.githubusercontent.com/16279904/48929219-2b1e6d00-eeac-11e8-96d1-0c9fe63ea4af.png)
![image](https://user-images.githubusercontent.com/16279904/48929238-5ef99280-eeac-11e8-9a7b-307919ec2960.png)

**Comment by SquadCraftFTW** [comment]
Yeah this needs to be fixed

**Comment by MarshallOfSound** [comment]
It doesn't show up as "Google Play Music", it shows up as "Google Play Music Desktop Player" which is the current name of the app.  This may change as we head towards YouTube Music, but for now, that's still the name of this app.
