### ISSUE TITLE
Media Keys triggered twice - Win 7, Microsoft keyboard

### ISSUE THREAD

**Issue by Falthazar** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3351]
**OS:** Windows 7

**GPMDP Version:** 4.6.1

**Issue Descriptions:** Media keys are triggered twice, similar to issue #3293, #2107, etc., but this time due to Microsoft keyboard drivers.

**Steps to Reproduce:** Pressing Play/pause won't play or pause, just skips for a second. And next/previous goes forward/back two.

**Steps to Fix:** Disabling the media keys in the "Microsoft Mouse and Keyboard Center" fixes the issue.

Might want to have a note or something in the GPMDP settings to disable that?

**Comment by MarshallOfSound** [comment]
As referenced this is a duplicate

**Comment by Freakygnome** [comment]
Still having this issue with a non MS keyboard there for no way to disable media keys only work around is to disable Win 10 System Media Service in GPMDP however after that wireless headset buttons stop working
