### ISSUE TITLE
Linux Mint Cinnamon can't hide to tray

### ISSUE THREAD

**Issue by bitoolean** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3352]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:** Linux Mint 18 Cinnamon 3.0.7 64-bit

**GPMDP Version:** 4.6.1

**Issue Descriptions:** The hide to tray feature doesn't work (the taskbar / window button still shows, only the title changes to be enclosed between brackets).

**Steps to Reproduce:** Check "Minimize to tray" in desktop settings and click the main window minimize (_) or close (X) buttons. The window will still be represented by a button on the task bar as well as by an icon in the system tray, just as when the setting was unchecked. This feature never worked for me, although I've always had it checked.

On a side-note, Last.fm integration has worked without issue.

**Comment by MarshallOfSound** [comment]
This will be fixed in an upcoming Electron update
