### ISSUE TITLE
YTM: Ad personalization has been turned off

### ISSUE THREAD

**Issue by judge2020** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3353]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:** win32 10.0.17134

**GPMDP Version:** 4.6.1

**Issue Descriptions:**

NOTE: this is not an Adblock request 😉 

Recently, while in Youtube Music mode, I realized I was getting pretty crappy ads. At the next ad, I clicked the info button and saw this message:

![image](https://user-images.githubusercontent.com/8601934/45464290-e2914900-b6dd-11e8-8ca0-6f6715cfef3c.png)

The message states "you've turned off ad personalization", however, it is on when I visit adssettings.google.com (I am signed into the same account on GPMDP and Chrome). 

I was wondering if this may be related to some do-not-track request that GPMDP/electron may be sending.

**Steps to Reproduce:**

1. get an ad
2. click the `i` next to the ad countdown.

![image](https://user-images.githubusercontent.com/8601934/45464370-52073880-b6de-11e8-89d8-97682af3d24b.png)

**Comment by MarshallOfSound** [comment]
> I was wondering if this may be related to some do-not-track request that GPMDP/electron may be sending.

We don't send any specific do-not-track requests or mess with anything like that, that setting might be client side.  Can you turn it on in YTM settings in the app?
