### ISSUE TITLE
Filter New Releases by Genre

### ISSUE THREAD

**Issue by punkster555** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3354]
I used to be able filter (via dropdown menu) the New Releases by genre. Now when navigating to the New Release page I only see "New overall" in the upper left corner and cannot filter down to a specific category.
![screen shot 2018-09-17 at 8 45 53 am](https://user-images.githubusercontent.com/41298868/45623690-2675ac80-ba56-11e8-96aa-38f0bf71711e.png)

**Comment by jostrander** [comment]
Unfortunately this is an issue on Google's end that we have no control over. I miss this feature as well.
