### ISSUE TITLE
Play/Pause does not work properly, using EarPods control button on macOS.

### ISSUE THREAD

**Issue by ochechet** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3358]
Given:
use Google play music desktop player on Mac, with EarPods connected 

Steps to reproduce:
1) Start playing song
2) Press control button on EarPods

Expected result: 
Playback pauses

Actual result:
Playback pauses and plays further

**Comment by MarshallOfSound** [comment]
Duplicate #3006
