### ISSUE TITLE
Uncaught Exception: la connessione a Internet sembra non essere in linea.: (null)

### ISSUE THREAD

**Issue by draugvar** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#336]
An uncaught exception was reported.  
#### Info:
**OS:** darwin
**Arch:** x64
**GPMDP Version:** 3.0.0
**Time:** Mon Mar 07 2016 14:54:21 GMT 0100 (CET)

#### Error:
*la connessione a Internet sembra non essere in linea.: (null)*
```js
Error: la connessione a Internet sembra non essere in linea.: (null)
    at Error (native)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
Client side network issue
