### ISSUE TITLE
Last page is not opened, even though Setting is set

### ISSUE THREAD

**Issue by wa4557** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3362]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS: Ubuntu 16.04**

**GPMDP Version: 4.6.1**

**Issue Descriptions:** 
WHen using the "Automatically load last viewed page on startup" option, the app does not really start from that page, but regardless of my last page at: "https//play.google.com/music/listen#/wmp". 
I tried to track down the problem and it seems that [this](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/renderer/ui/pages/PlayerPage.js#L131) is the side it loads at startup. 

If I change that to:

```src={this.targetPage}```

it loads the correct one. I suppose that is not a proper fix though, so it would be cool if someone with more Electron experience could look into it. 

**Steps to Reproduce:** 
Open the app

**Comment by jostrander** [comment]
The code that does this is [here](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/61fb9ba98a9c75a8ed038f246f9138159900abd9/src/renderer/ui/pages/PlayerPage.js#L59). I'm not sure why it's not working as that didn't change with the YTM update.

**Comment by wa4557** [comment]
I'm not sure. As far as I can see `this.state.webviewTarget` (the site that is actually called in `render()`) is never reassigned to the proper site `this.targetPage`. The function you referred to, does everything correctly imo

**Comment by MarshallOfSound** [comment]
I can't reproduce this locally and the entire Electron webview impl got rewritten in Electron 3 (which we just upgraded to) so this is probably OK now 👍
