### ISSUE TITLE
2FA phone prompt cannot sign in

### ISSUE THREAD

**Issue by danielmoncada** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3365]
**OS:**
Windows 10

**GPMDP Version:**
4.6.1

**Issue Descriptions:**
When using Google's 2FA phone prompt, a notification will appear on your phone that will indicate whether or not you want to accept the log in. If you select Yes, GPMDP just stays on the sign on screen and doesn't proceed. 

see: https://support.google.com/accounts/answer/7026266?co=GENIE.Platform%3DAndroid&hl=en

What I had to do is select a 'different' way to login, and then use 2FA access code method instead.

**Steps to Reproduce:**
Log into your Google account with 2FA phone prompt as the primary method for 2FA.

**Comment by jespersh** [comment]
Maybe one of these issues will help you: https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+2fa
Be sure to check with closed issues

**Comment by MarshallOfSound** [comment]
@danielmoncada We don't do anything on Google's sign in screen, if it isn't working it will be an issue on their end.
