### ISSUE TITLE
Artist info displayed incorrectly

### ISSUE THREAD

**Issue by GabrielTK** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3367]
**OS: Windows 10**

**GPMDP Version: 4.6.1**

**Issue Descriptions: Reported data is very weird. [Take a look here.](https://imgur.com/a/BK6eEHG)**

**Steps to Reproduce: Play a song in YouTube Music. Problem exists in Rainmeter (3rd party) and Discord RPC. Seems to happen after you play a YT Video.**

I will take a better look and, If I can fix it, will submit a PR.

**Comment by MarshallOfSound** [comment]
Duplicate #3180
