### ISSUE TITLE
Forcing audio out default and not selected output section

### ISSUE THREAD

**Issue by Peligroso81** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3368]
I have noticed a bug. I have a 5.1 surround hooked up to my system and enabled the 5.1 support. The issue comes in when I plug in standard 3.5mm headphones and still have the sound output mapped to my physical jack but have USB set as default in my system it pushes sound out my default. If I disable the 5.1 support everything functions as it should. I suspect it may have to do with the fact that it is a 2 channel being plugged into the front where I have a 5.1 in the back so GPMDP is having an issue and just forces down the default channel.

**Comment by MarshallOfSound** [comment]
@Peligroso81 That 5.1 support option actually just enables an experimental flag inside Chromium that isn't stable yet.  It's quite likely that that flag is causing these issues however we can't fix them until we inherit the fixes from Chromium upstream
