### ISSUE TITLE
Support black version of mac menubar icon

### ISSUE THREAD

**Issue by elihorne** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#337]
Many apps chose a black/dark color menubar icon because it is less distracting (the focus should be on the application windows, not the menu bar).

Other apps that default to a color version will also offer an alternate black version. You can find an example of the alternate and preference setting example in Dropbox's sync client.

For what it's worth, from an non-objective, opinionated perspective - it would be nice if the icon had less detail (the atomic symbol is hard in a confined space), and if there was padding on the top and bottom.

See a screenshot of my current menu bar showing consistency in icon appearance and spacing.

![image](https://cloud.githubusercontent.com/assets/51566/13571499/6254ee8c-e443-11e5-86d2-97c44017c132.png)

**Comment by MarshallOfSound** [comment]
We have a black/white template icon in master thanks to a PR #228
