### ISSUE TITLE
Feature request: option to "SEE ALL" by default

### ISSUE THREAD

**Issue by heavywatal** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3371]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**
macOS

**GPMDP Version:**
4.6.1

**Issue Descriptions:**
When I go to "Music library > ARTISTS > some artist page", the app shows "All my songs", first three albums, and "SEE ALL" button. It needs one more click to see all the albums. I wish I could omit this extra step.

**Steps to Reproduce:**
Go to Music library > ARTISTS > some artist with more than three albums.

**Comment by MarshallOfSound** [comment]
This kind of major UI change is out of scope for this project, you should give this feedback on Google's product forums
