### ISSUE TITLE
Feature request: Integrate with Musixmatch for lyrics

### ISSUE THREAD

**Issue by jrfernandes** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3372]
Musixmatch provides an extensive list of song lyrics, as well a great API: https://developer.musixmatch.com/

**Comment by MarshallOfSound** [comment]
Not possible, it's a non-free api

**Comment by jrfernandes** [comment]
It's not that is not possible, it could allow the user to provide their own API key for the integration.

**Comment by MarshallOfSound** [comment]
I've had issues with musicxmatch before and I've refused to use their services or apis in any capacity ever since.

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/What-happened-with-3.2.5%3F

**Comment by jrfernandes** [comment]
Thank you for sharing. Yeah, that was a harsh email. I'm honestly surprised since they do have a public API, where in it's front page they even claim "Bring lyrics on your application with the Musixmatch API". 

My guess is that at the time that GPMDP had integration with Musixmatch it was probably using one single API key for everyone. I wonder if things are _done right_ (i.e. asking the end user to provide their API key) if things would be different.

Just my two cents. If you feel that Musixmatch is not a viable solution for lyrics, so be it.

Thank you.

**Comment by jostrander** [comment]
Even if you were to provide your own API key, I can't imagine anyone paying the minimum $1500/month to display lyrics with their own key. If you have a "free" API key you are only entitled to 30% of the lyrics per song and 2k requests per day. It just doesn't make sense from any perspective other than commercial.

**Comment by jrfernandes** [comment]
My apologies, I didn't notice the 30% limit for the free plan. Well, that does it then :)
