### ISSUE TITLE
Infinite loading 2

### ISSUE THREAD

**Issue by Wolfen113** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3373]
Continuing the theme. https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3302
OS: Arch Linux, Windows 10
GPMDP Version: 4.6.1

Issue Descriptions: Hangs up the music player when you start the first playlist. (endless download).
Earlier, I wrote about this problem, now the details of its occurrence are clearly clear.
Something is wrong with playlists when the system starts up and the player turns on. It freezes if a playlist has been enabled.
  If the player is loaded from the start window, then everything is fine.
If after the start window to go to any playlist or his or her workplaces, then this playlist will hang.

Steps to Reproduce: 1. Start the player from the session playlist. 2. Attempt to enter any playlist after the start.

Temporary solution: Always keep the music player in homepage mode.
The first to play a fake playlist, without going into it. 

On this topic, I have a question, as long as there is no correction, is it possible to include something like that so that the music player does not remember the last launched page when exiting. What would he always start from the main page? Sample image
Sorry I'm writing via Google translator
![image](https://user-images.githubusercontent.com/29464780/46362636-bfb4dd80-c668-11e8-9d28-da3cc460c059.png)

**Comment by Wolfen113** [comment]
Oops, it turns out that I asked the question in the settings already there, I did not notice.
Now to get around the problem will be easier. But I still hope that with future updates the problem will be solved and it will no longer need to be bypassed. 
![image](https://user-images.githubusercontent.com/29464780/46378144-a1fc6e00-c692-11e8-9d89-4d6b6605a0a2.png)

**Comment by MarshallOfSound** [comment]
That option is there for this exact case, sometimes going to an old or no longer valid URL will result in a client side infinite redirect.  By turning that option off temporarily the troublesome page won't be loaded
