### ISSUE TITLE
"Select Download Location" Unresponsive

### ISSUE THREAD

**Issue by Enigma0** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3375]
![image](https://user-images.githubusercontent.com/4528283/46513417-4b279d80-c826-11e8-8f3e-f68004c5cfed.png)

This isn't functioning for me. I can't click "Select Download Location" - nothing happens.

**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:** Windows 10

**GPMDP Version:** Latest official from site

**Comment by Amir142** [comment]
same here

**Comment by Amir142** [comment]
the FAQs say that offline storage is not supported yet though I don't know when those were last updated.
[here](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ#can-we-get-some-of-that-offline-storage-goodness-that-the-android-app-has) is the question I'm referring to.
Don't know what the intended behavior of that button is but it's also unresponsive on my machine (windows 10)

**Comment by jostrander** [comment]
The offline downloading requires a chrome extension that we don't supply in the desktop app, so this is not going to work. That whole section of settings should be hidden in the desktop app.

**Comment by Ryonez** [comment]
This option is still present. Please, if it's not actually support please remove the option.
Saying it's in the FAQ is pointless when you're looking at the options and can see them. People will come here with the issue, not the FAQ.
