### ISSUE TITLE
Certificate for googleplaymusicdesktopplayer.com has expired

### ISSUE THREAD

**Issue by ThePigsMud** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3376]
Certificate has expired today, and you receive a certificate error when trying to connect.
![cert_expired](https://user-images.githubusercontent.com/33440343/46577501-4130a680-c9ae-11e8-9cef-8cd8af222f3c.PNG)
![cert_2](https://user-images.githubusercontent.com/33440343/46577509-70dfae80-c9ae-11e8-9331-cee182d525fb.PNG)

**Comment by MarshallOfSound** [comment]
Fixed 😄 nginx doesn't seem to be restarting in my cron job 🤔 will see what I can do for next time
