### ISSUE TITLE
Unable to install Mini Player

### ISSUE THREAD

**Issue by g33k247** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3379]
Hi there. I'm unable to install the mini player. After starting GDMP, and clicking the 'install' button for the mini player, I'm stuck on the 'Setting up Google Play Music' screen with the spinning record icon. The issue seems to be a repeat of "Unable to install Mini Player #423" from 2016. I can get back to the player interface by clicking on the 'Google Play Music' hot area in the left corner. Clicking on the mini player icon in the lower right takes me right back to the 

I'm running Kubuntu 18.10, kernel 4.18.0-7-generic. I've uninstalled and reinstalled using snap. I've run the DEBUG_INFO command which seems to work but cannot locate the resultant zip file.

![screenshot_20181008_104537](https://user-images.githubusercontent.com/8498814/46615883-552bf380-cae7-11e8-957a-1ebb725690d1.png)

-->
**OS:**
Kubuntu 18.10, kernel 4.18.0-7-generic

**GPMDP Version:**

**Issue Descriptions:**

**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment]
You're clicking the wrong mini player button, idk how you managed to click that one but the built in mini player is triggered with the little arrow in the bottom right of the player controls.
