### ISSUE TITLE
Feature request: option to separate Last.fm love track button from thumbs up button of GPM and make separate button bidirectional for current track only.

### ISSUE THREAD

**Issue by AlexDEVpro** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3382]
The app is awesome. Just one suggestion for one more option for the Last.fm track love status integration. There is already an option so that when you press the thumb up button on Last.fm, a signal is sent to add a track to your favorites on Last.fm, or to exclude it from your favorites on Last.fm.

I want to suggest another option.
It would be great to have an additional option in the settings for adding a separate Last.fm track love button. When this option is enabled, the button in the form of a Last.fm heart can be placed next to the GPM thumbs up button at least on the main controls panel of current track only. This button will simply show the love status on Last.fm of the current song and allow editing it, without synchronization with fingers up in GPM. What do you think about this option?

_Originally posted by @AlexDEVpro in https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/1799#issuecomment-428925900_

**Comment by MarshallOfSound** [comment]
That kind of bi-directional sync is IMO out of scope of this project.  We'll send data out (E.g. to LastFM or anything listening on the Playback API) but importing information into GPM itself is a very complicated task to do using just UI automation
