### ISSUE TITLE
Play/Pause icons no longer displayed in Windows 10 Taskbar

### ISSUE THREAD

**Issue by roryhewitt** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3386]
See issue #3201. Just started happenign agian on 4.6.1.

**Comment by MarshallOfSound** [comment]
They are definitely there, I can see them on all my windows machines and confirmed with several colleagues on windows they can see the icons.  My guess is you somehow have an old version of GPMDP being launched.
