### ISSUE TITLE
Feature request: optional metadata columns in playlists

### ISSUE THREAD

**Issue by BatmanAoD** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3387]
**OS:** Windows

**GPMDP Version:** 4.6.1

It seems that the "album" view can display track info that isn't displayed in the "playlist" view. The example I've noticed is classical music with multiple composers, such as [this album](https://play.google.com/music/m/B6c3bayu2vz3ldmi4bkhwr43fby?t=Beethoven_Shubert__Grieg_Sonatas_for_Violin_and_Piano_-_Fritz_Kreisler). When looking at the track listing on the album, a "Composer" column is displayed, making it easy to determine which sonata is by which composer. However, when the tracks have been added to a playlist, the playlist track listing does *not* display the "Composer" field.

This behavior matches the official web-app behavior, but since the metadata is available, it would be nice if it were displayed. Is this possible? Can it be done with a custom CSS style?

**Comment by MarshallOfSound** [comment]
Large scale web-app modifications like this require the data to come from somewhere and we don't have access to it, you should ask for this on Google's product forums
