### ISSUE TITLE
Windows 10 volume overlay artist delay

### ISSUE THREAD

**Issue by fyildirim** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3388]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**
Windows 10 Home 1809, build 17763.55

**GPMDP Version:**
4.6.1

**Issue Descriptions:**
My issue is for the Youtube Music player of GPMDP.
The "Show track information in Windows 10 volume overlay" artist has a delay of 1 song. If I switch back and forth between two different songs they have the wrong artist, see the GIF for an example.

![GIF of artist delay](https://i.gyazo.com/998cda3d8d4060cfea15475f7578b48b.gif)

**Steps to Reproduce:**
- Play any song
- Change Windows volume with the vertical slider (so not the one in your taskbar) and look at the current song's artist, or use any playback keys you have on your keyboard that shows the track information if you press on it.
- Switch songs either through the player, through the track information playback buttons or the playback keys you have on your keyboard
- Change Windows volume with the vertical slider (so not the one in your taskbar) and look at the current song's artist, or use any playback keys you have on your keyboard that shows the track information if you press on it.

**Comment by MarshallOfSound** [comment]
Duplicate #3180
