### ISSUE TITLE
Volume normal on speakers but low on razer headset

### ISSUE THREAD

**Issue by CaptainJawZ** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3389]
Hello! I have this weird but where volume is like 50% lower than it should. 
If I set my device to my speakers, the volume is exactly as loud as the webpage
However, if I set the audio device to my razer headset the volume is very low
I already played with all the possible settings on the windows audio mixer as well as the mixer provided by razer and i can't figure out how to normalize the volume.

**Comment by MarshallOfSound** [comment]
@CaptainJawZ Make sure you don't have the 5.1 Surround Sound experiment enabled, that is probably what's causing this

**Comment by MarshallOfSound** [comment]
With no other reports of this issue I think it will be something specific to your hardware configuration / drivers.  If you are still experiencing this issue please update all your drivers and ensure you are on the latest versions of GPMDP and Windows
