### ISSUE TITLE
Unable to login. Clicking the Login button redirects back to the page with the Login button.

### ISSUE THREAD

**Issue by AlexDEVpro** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3390]
**OS:**
Windows 10 Home
**GPMDP Version:**
4.6.1
**Issue Descriptions:**
Clicking the Login button redirects back to the page with the Login button.
**Steps to Reproduce:**
Use your Google account in the app as usual. Then do not pay for Google Play Music on this account and use your another account. And then, one day, when you launch the player, there will be not a new account, but an old one, with a non-paid subscription to Google Play Music. You will be redirected to the page with the Login button. You will click the Login button and will redirect you to the same page again.
Then you restart the player and try to have time to click on the account icon and click the Logout button, but this will not work. You are stuck, you need to look for a place where the player saves its settings and delete them.

**Comment by MarshallOfSound** [comment]
> You are stuck, you need to look for a place where the player saves its settings and delete them.

It sounds like Google sent you to a page with a redirect loop, the only way out is to wipe GPMDP's settings and start again

**Comment by AlexDEVpro** [comment]
Thanks for the response!

Ok, I removed the "lastPage" parameter from the %APPDATA%\Google Play Music Desktop Player\json_store\.settings.json file. That was enough. When I launched the program, only one redirect occurred, after which I was able to press the sign out button and log in to my another account.
