### ISSUE TITLE
last.fm problems on linux

### ISSUE THREAD

**Issue by duke86fan** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3394]
**OS:**
Solus
**GPMDP Version:**
4.6.1
**Issue Descriptions:**
When i try to log in to last.fm scrobbling, it gives the authorization status but then doesn't open the window and says im logged out.
**Steps to Reproduce:**
download GPMDP from the solus repositories and try to log into last.fm

**Comment by MarshallOfSound** [comment]
@duke86fan If the GPMDP isn't coming from an official source (our website) it probably isn't being packaged correctly.  In this case it looks like the LASTFM API keys aren't included in the solus distribution so LASTFM support is not working.
