### ISSUE TITLE
Icon changes to generic Mac app icon when mirroring to display

### ISSUE THREAD

**Issue by wderganc** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3396]
**OS:**
mac 10.12.6

**GPMDP Version:**
4.6.1

**Issue Descriptions:**
GPMDP icon missing, shows generic Mac app icon

**Steps to Reproduce:**
Mirror Retina Macbook Pro with 1080p display, using the external display's best resolution setting. Fix by using rMBP's default resolution.

**Comment by MarshallOfSound** [comment]
Fixed in master
