### ISSUE TITLE
[YouTube Music] Wrong Artist and album in playback.json

### ISSUE THREAD

**Issue by ChTBoner** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3399]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:** Linux Ubuntu 18.04

**GPMDP Version:** 4.6.1

**Issue Descriptions:** artist and album name wrong in playback.json in Youtube Music Alpha

**Steps to Reproduce:**
Start a playlist in Youtube Music
First Track will have correct info in playback.json
Following tracks will have the "artist" and "album" fields with data from the previous song.

First song of the playlist: info is correct
![image](https://user-images.githubusercontent.com/14848356/47290699-057a1b80-d601-11e8-8ed4-2e6b32bdf0aa.png)

Second song: Artist and Album data is from first song
![image](https://user-images.githubusercontent.com/14848356/47290715-14f96480-d601-11e8-8b5f-41f365407c61.png)

Third song: Artist and album data is from second song.
![image](https://user-images.githubusercontent.com/14848356/47290923-f6e03400-d601-11e8-9e98-bb43dec20f74.png)

Evertyhing works as expected with with Google Play Music.

PS: Thank you for this wonderful tool.

**Comment by ChTBoner** [comment]
Please note also that if you hit the prevous song button, Artist and album info will be from the previously played song (so the next on the list).

**Comment by MarshallOfSound** [comment]
Duplicate #3180
