### ISSUE TITLE
Annoyance/Bug - hard to grab the scroll bar when a song is playing

### ISSUE THREAD

**Issue by snarkywolverine** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3402]
**OS:** Windows 10

**GPMDP Version:** Pretty sure it's latest released version, though I couldn't find the version in the "Desktop Settings" control :(

**Issue Descriptions:** 
I have a 1000-song playlist where I generally scroll to the bottom, and then try to grab the scrollbar to scroll up from there.  The problem is … if a song is either playing or paused when I attempt to grab said scrollbar, I usually end up fastforwarding to the end of the song (rather than grabbing the scrollbar).

**Steps to Reproduce:**
1. Create a sufficiently long playlist, and navigate to that playlist
2. Start to play a song (source doesn't matter)
3. Drag the scrollbar all the way to the bottom & release.
4. Now, try to drag the scrollbar up.
If the playlist is sufficiently large, and/or you grab near the very bottom of the scrollbar, you will see that the icon is a finger instead of a pointer. In my case, I only have a couple of pixels to actually grab the end of the scrollbar (and I almost always miss).

It makes some sense - the play marker does render over the scrollbar... it's just annoying that I can't actually click the scrollbar.  (I can workaround it by clicking elsewhere on the side bar to bring the scroll position up a page, then drag from there).
I am using the default white skin (with the orange trim).  I was trying to figure out how to solve this … perhaps a different skin with an enclosed play bar?  Or should the scrollbar end higher up?

![image](https://user-images.githubusercontent.com/22400231/47382621-901d5200-d6b7-11e8-8b9d-740ce35e646d.png)

**Comment by jostrander** [comment]
Check the version of the player, in the tray menu hit help then about. It will pop up in the player window with the version. Also did you install with the exe, or out of the windows store before that was removed?

**Comment by snarkywolverine** [comment]
It's version 4.6.1. I think I downloaded as a standalone exe and I know I've updated numerous times.

This issue isn't a regression, fwiw.

**Comment by MarshallOfSound** [comment]
This will be fixed by an upcoming Electron upgrade where the Overlay Scrollbar is much better and improved in Chromium
