### ISSUE TITLE
Two entries in Windows Volume Mixer with Win10 System Media Service enabled

### ISSUE THREAD

**Issue by bar-foo-x** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3405]
**OS:**
Windows 10 64-bit

**GPMDP Version:** 
4.6.1

**Issue Descriptions:**
GPMDP consistently produces two entries in the Windows volume mixer, of which only one seems to be functional. The second one controls the actual sound level and changes its name with each song. The first is always there but has no effect. This is largely an aesthetic issue but it would be preferable to have a single entry.

**Steps to Reproduce:**

1. Open GPMDP in Windows with Windows 10 System Media Service enabled
2. Open Volume Mixer (sometimes one entry is visible, sometimes two)
3. Play a song in GPMDP (second entry appears, or changes title to song title)

**Comment by MarshallOfSound** [comment]
This sounds like a Windows 10 bug as I can't reproduce it on any of my Windows machines / VMs, you probably got a bad insiders build or something similar
