### ISSUE TITLE
Incorrect artist on notification tray

### ISSUE THREAD

**Issue by tomeyro** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3406]
**OS:** Ubuntu 18.04

**GPMDP Version:** 4.6.1

**Issue Descriptions:** Notification tray shows the correct name of the song but the artist of the previous one.

**Steps to Reproduce:** Open youtube music from GPMDP and start a playlist.

![image](https://user-images.githubusercontent.com/8657959/47753166-3dfea280-dc5c-11e8-8393-327e93c75499.png)
![image](https://user-images.githubusercontent.com/8657959/47753168-3fc86600-dc5c-11e8-82e5-1beccdde1e82.png)

**Comment by jchenVT** [comment]
I've noticed this happens for youtube music but not gpm

**Comment by MarshallOfSound** [comment]
Duplicate #3180
