### ISSUE TITLE
An error appears when trying to authorize Last.fm in Linux Ubuntu 18.08

### ISSUE THREAD

**Issue by claudiutms** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3407]
**OS: Linux Ubuntu 18.04**

**GPMDP Version: 4.6.1**

**Issue Descriptions:**
When trying to authorize Last.fm from settings there is always an error stating: "**You appear to have left the authorization process, if this is a mistake, please try authorizing again**"

**Steps to Reproduce:**

1. Open GPDMP
2. Open Desktop Settings
3. Open the Last.fm tab
4. Click the link "Login to Last.fm"
5. Wait for the page to appear
6. Enter credentials
7. Press Login
8. Notice that an error appears

![screenshot from 2018-11-01 10-28-10](https://user-images.githubusercontent.com/33520766/47841061-03624a80-ddc1-11e8-847a-1fc51ae4dad2.png)

**Comment by tompassarelli** [comment]
I've having the same issue but on Windows 10, tested from https://www.googleplaymusicdesktopplayer.com/ as well as building it and putting my own API keys in the constants.js folder and still no luck. When I try to hit the button it just instantly kicks me before I can even put in my information. 
![issue](https://user-images.githubusercontent.com/6378995/48113599-a257ce00-e229-11e8-86ec-441dfad5b625.PNG)

**Comment by a-rmz** [comment]
Same issue while trying to login for the first time on Mac OS Mojave 10.14.1

<img width="582" alt="screen shot 2018-11-27 at 10 06 47" src="https://user-images.githubusercontent.com/15201480/49094594-3b2ba900-f22c-11e8-9666-1d9b594a5fb7.png">

**Comment by kamerat1** [comment]
Same thing is happening to me on Windows 10, just downloaded the app and tried connecting last.fm getting errors every time i press the "Let me in!" button.

**Comment by Daniel15** [comment]
I'm seeing the same thing on Windows 10.

**Comment by MarshallOfSound** [comment]
Duplicate #3486
