### ISSUE TITLE
Sefault while opening on Fedora 29

### ISSUE THREAD

**Issue by sycosyth** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3408]
After an OS upgrade to Fedora 29, everytime I open the GPMDP it segfauls
Info:
**OS:** Fedora Workstation 29

**GPMDP Version:** Latest available (4.6.1)

**Issue Descriptions:** Segfault on start
Logs: 
Nov 01 15:15:52  kernel: google-play-mus[968]: segfault at a4fa30 ip 0000000000a4fa30 sp 00007ffe8d697778 error 15 in Google Play Music Desktop Player[200000+1602000]
Nov 01 15:15:52  kernel: Code: da 9d ef 9d e6 9d f2 9d f8 9d 0c 9e fa 9d 1b 9e 64 76 58 76 67 76 02 76 46 76 47 76 49 76 1e 76 3b 76 6d 76 6e 76 69 76 72 76 <c7> 7a b6 7a 60 89 33 89 5d 89 47 89 >

Nov 01 15:15:52 systemd-coredump[974]: Process 968 (google-play-mus) of user 1000 dumped core.                                                   
                                                       Stack trace of thread 968:
                                                       #0  0x0000000000a4fa30 n/a (Google Play Music Desktop Player)

**Steps to Reproduce:** Open GPMDP

**Steps I've tried to fix issue:** Removing and reinstalling latest rpm

**Comment by chrissharp123** [comment]
This appears to be related to https://github.com/electron/electron/issues/13972, affecting electron-based apps on multiple linux distributions.

**Comment by MarshallOfSound** [comment]
This is fixed on master

**Comment by m-wynn** [comment]
What would it take to get another release?  It looks like there's a few pretty major fixes on master since 4.6.1

**Comment by chrissharp123** [comment]
@m-wynn I was able to pretty easily build an RPM from master following https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#development and https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/Development-FAQ.  Problem (locally) solved!

**Comment by agc93** [comment]
Any news on a new release? I haven't been able to get a local build environment working to build my own copy :(

It's been over 5 months since the last release (even F29 has been out for almost 2 months) and I really miss having a working GPMDP...
