### ISSUE TITLE
Stuck on Loading Music Library (where are temp files on Mac)

### ISSUE THREAD

**Issue by HostingNSB** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3409]
Good Afternoon, I am getting the blank loading screen on Loading Music Library, I know this is covered in other posts but I cant find one that tells me where to delete the temp files for Mac. I cannot find these folders, I've looked everywhere I can think of. Can you guide me in the right direction, thank you!

**Comment by joan38** [comment]
Same here!

**Comment by joan38** [comment]
I tried to `rm -rf ~/Library/Application\ Support/Google Play\ Play\ Music\ Desktop\ Player/` without luck

**Comment by spellanser** [comment]
> I tried to `rm -rf ~/Library/Application\ Support/Google Play\ Play\ Music\ Desktop\ Player/` without luck

This worked for me, but it removes all settings and you should re-login to your account.

**Comment by shosho27** [comment]
Find the application support folder, go into the Google Play Desktop Player folder and delete all the files in the cache folder Library/Application Support/Google Play Music Desktop Player/Cache

**Comment by MarshallOfSound** [comment]
Solution outlined above
