### ISSUE TITLE
Uncaught Exception: A server with the specified hostname could not be found.: (null)

### ISSUE THREAD

**Issue by davidbruce** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#341]
An uncaught exception was reported.  
#### Info:
**OS:** darwin
**Arch:** x64
**GPMDP Version:** 3.0.0
**Time:** Mon Mar 07 2016 11:18:59 GMT-0500 (EST)

#### Error:
*A server with the specified hostname could not be found.: (null)*
```js
Error: A server with the specified hostname could not be found.: (null)
    at Error (native)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
Client side network issues
