### ISSUE TITLE
Segfault on startup (Linux version)

### ISSUE THREAD

**Issue by blakkheimgw** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3410]
The current GPMDP version (v4.5.1) crashes when I launch it on my Fedora 29. According to multiple bug reports related to other Electron-based apps, this is due to this [issue](https://github.com/electron/electron/issues/13972)

Could you please update to Electron 2.0.8 in order to fix it ?

**Comment by MarshallOfSound** [comment]
This is fixed in master...

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/package.json#L65

**Comment by equilibrialthoughts** [comment]
@MarshallOfSound 

Hey, has the RPM been rebuilt on the main site yet? Otherwise, I'll compile. Just thought to ask.

Thanks!

**Comment by zerkz** [comment]
@equilibrialthoughts it has not. see https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3391 for how you can grab the latest build of master off of circle.
