### ISSUE TITLE
Bluetooth headset media buttons dont work

### ISSUE THREAD

**Issue by chertv** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3414]
Good day everyone
Please somebudy can help me with my trouble?
Using bluetooth headset and zenbook, 
so bluetooth media buttons (play/pause, next, prev) dont work in GPMDP.
HID Service is "On" in control panel Services,  media keys works perfectly in windows default Groove music player, but not in GPMDP

-->

**OS:**  Windows 10  1803

**GPMDP Version:** Latest 4.6.1

**Issue Descriptions:**  GPMDP dont react to bluetooth media buttons

**Steps to Reproduce:**  Just press any button on any connected bluetooth sound device

**Comment by abtechmg** [comment]
It works for me.

**Comment by chertv** [comment]
Update to Win10  1809 October  fixed this problem. Sorry and thanks.
