### ISSUE TITLE
App not loading at all

### ISSUE THREAD

**Issue by TheRealSebTombs** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3415]
Hello,

When launching the app, the window is stuck at 'loading  music library…' with the app icon above, and nothing happens. My Play Music account works fine through my mobile and the web page.

Any ideas?

Thank you!

**Checklist:**

* [ ] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [ ] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [ ] I have double checked and can reproduce the issue

**OS:**

**GPMDP Version:**

**Issue Descriptions:**

**Steps to Reproduce:**

**Comment by claduca** [comment]
I also tried wiping all the plist files (I am on Mac OS X, forgot to mention) to no avail.

Thank you.

**Comment by viroos** [comment]
Hi,
I have the same issue.
I see in logs:
{"level":"error","message":"################### !! Update server down !! ##################","timestamp":"2018-11-06T20:35:53.530Z"}
{"level":"error","message":"################### !! Update server down !! ##################","timestamp":"2018-11-06T20:37:56.619Z"}

**Comment by TheRealSebTombs** [comment]
Hello,

Just an update to say I wiped the app completely and reinstalled it and that did the trick. Weird.

Thank you.

**Comment by MimiSunPeanuts** [comment]
when you say wiped completely, is there more than deleting the app, emptying the trash, finding the cache files associated and deleting them permanently as well and downloading and reinstalling? I've done this although I'm not sure if I deleted every associated cache file. Please advise and thanks in advance.

**Comment by hendersonj** [comment]
This happened to me as well. I simply trashed everything in **Library > Application Support > Google Play Music Desktop Player** and restarted the app. Obviously had to sign in again but the app is working now.

**Comment by SimplyComplexable** [comment]
I'm getting this or a similar error. I tried to follow @hendersonj's suggestion, but that directory doesn't exist. Is there any other suggestions.

**Comment by sschueller** [comment]
I was able to get mine running again by clearing the cache folder located here:
```

**Comment by Nuzuzar** [comment]
I experienced the same issue on Windows. You can clear the cache on Window by deleting the contents of this folder:

`C:\Users\username\AppData\Roaming\Google Play Music Desktop Player\Cache`

**Comment by MarshallOfSound** [comment]
Sounds like the cache got corrupted / stuck in a locked state.  As mentioned above wiping the cache directory in most cases will get it working again

**Comment by lursel** [comment]
I deleted the cache and even uninstalled the player (Win10). When I install it and login, it gets stuck at loading library again. Anyone else?

**Comment by spiralizing** [comment]
I did everything (wiped completely) and it still gets stuck, any new ideas?

**Comment by riogezz** [comment]
same here. cleared cahce and even GPUcache. Nothing worked.
I can use YouTube Music (alpha feature) but GPM is stuck on "Loading Music Library"

**Comment by NightMan665** [comment]
Confirm two previous comments. I've tried to remove AppData\Roaming\Google Play Music Desktop Player, remove player at all and install from the scratch, but still stuck on the loading screen.
gpmdp.log contains next:

{"level":"info","message":"Application started.","timestamp":"2019-12-11T08:26:00.857Z"}
{"level":"error","message":"################### !! Update server down !! ##################","timestamp":"2019-12-11T08:26:01.578Z"}
{"level":"error","message":"################### !! Update server down !! ##################","timestamp":"2019-12-11T08:28:01.737Z"}
{"level":"error","message":"################### !! Update server down !! ##################","timestamp":"2019-12-11T08:30:01.918Z"}
{"level":"error","message":"################### !! Update server down !! ##################","timestamp":"2019-12-11T08:32:02.089Z"}

**Comment by jostrander** [comment]
This issue is over a year old and there is a pinned issue for this #3660.
