### ISSUE TITLE
GPMDP is ignoring dislike status on song

### ISSUE THREAD

**Issue by HawkeyePierce89** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3419]
**Checklist:**

* [*] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [*] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [*] I have double checked and can reproduce the issue

**OS:** macOS High Sierra 10.13.6 (17G3025)

**GPMDP Version:** 4.6.1

**Issue Descriptions:**
When I listening playlist with disliked songs this songs are played forcibly. GPMDP ignores dislike-status. 

**Steps to Reproduce:**
1. Set dislike on song in playlist
2. Run previous song
3. Disliked song will play.

Video: https://yadi.sk/i/EwDrVyXmikluSA

**Comment by jostrander** [comment]
I don't see the issue here, unless you have skip disliked songs enabled in settings. Can you confirm that's the issue? GPM doesn't skip those songs by default, that's an option in the player.

**Comment by HawkeyePierce89** [comment]
Sorry, I thought that default behavior. Thanks for help
