### ISSUE TITLE
Youtube Music not scrobbling to lastfm

### ISSUE THREAD

**Issue by bellini666** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3420]
The title says it all I think =P

**Comment by restinginlove** [comment]
It's been an issue since June :( https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3174

**Comment by bellini666** [comment]
@restinginlove OMG I didn't know that. In this case, sorry for opening a duplicated here
