### ISSUE TITLE
Crash every time you play a song.

### ISSUE THREAD

**Issue by deathspawn** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3422]
I am on Manjaro Linux and have gpmdp installed through AUR. I keep getting an error every time I play a song.

Trace/breakpoint trap (core dumped)

It also happens on another computer. It was working fine for a while.

**Comment by Circuitsoft** [comment]
I've started seeing this lately, but I'm just getting a hard lockup, not a segfault. When I play a song, CPU usage goes to 100% and the UI stops responding, but the song continues to play.

**Comment by Yamthief** [comment]
I'm having the same issue on a Mac. I've only noticed it happening very recently (over the past week or so).

**Comment by ayhoung** [comment]
same issue here!

**Comment by jostrander** [comment]
Duplicate of #3483
