### ISSUE TITLE
Discord Rich Presence doesn't work on Linux

### ISSUE THREAD

**Issue by Jade-TheCat** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3423]
**OS:** 
Ubuntu 18.10

**GPMDP Version:** 
4.6.1

**Issue Descriptions:** 
Discord RPC does not show, even after restarting GPMDP.

**Steps to Reproduce:**
1, Start GPMDP
2. Enable Discord Rich Presence
3. Restart GPMDP (even with killall Google\ Play\ Music\ Desktop\ Player)
4. Look at Discord

**Comment by Jade-TheCat** [comment]
I should have noted that I am using YouTube Music, but I just tested it and it doesn't work on Play Music either.

**Comment by Recycling-Bin** [comment]
Can confirm this on Ubuntu 18.04 LTS. But this also occurs with Visual Studio Code when installing via the Software Center. I believe it has to do when individual app permissions and the messed up way that the Software Center installs things. I have not gotten a chance (or the available free space left) to change the app permissions myself using the command line **so it would nice if someone else can reproduce this.**

**Comment by MarshallOfSound** [comment]
I'm guessing the snapcraft config needs to be updated to support inter-app communication between GPMDP and Discord.  I don't maintain the snapcraft config so I'd suggest following up upstream with that and figuring out how to make it work

**Comment by Restioson** [comment]
Hi, I'm experiencing this problem too. Is there any workaround I could implement or a follow-up upstream?
