### ISSUE TITLE
Feature Request: Keyboard Navigation

### ISSUE THREAD

**Issue by scals37** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3427]
Really enjoying this application. I was curious if there were plans to implement any keyboard navigation, for those that may want to use a remote in an HTPC setup. Since keyboard nav keys can be mimicked on a remote, that would be a fun addition to this.

**Comment by jostrander** [comment]
GPM and YTM technically already have keyboard navigation, using `?` you can bring up the commands.
