### ISSUE TITLE
Translation 

### ISSUE THREAD

**Issue by gannycya** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3428]
OS: Windows 10 Home

GPMDP Version: V4.6.1.

Issue Descriptions: There are no opportunity to change language on the Home Page of the GogglePlayMusicDesktop. 

Steps to Reproduce:
1. Open the desktop application "GooglePlayMusicPlayer"
2. Try to find options to change language

Expected result: There is button to change language in one of the pages corners

Actual result: You can change language just after log-ining and changing language in Program settings

**Comment by MarshallOfSound** [comment]
@gannycya You can change GPMDP's language from "Desktop Settings" which can be accessed from either the Google Play Music sidebar once you're signed in or the tray icon menu whether you are signed in or not.
