### ISSUE TITLE
RE-changing language

### ISSUE THREAD

**Issue by gannycya** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3429]
OS: Windows 10 Home

GPMDP Version: V4.6.1.

Issue Descriptions: When you re-change the language in Program Settings not all fields are displayed correctly 

Steps to Reproduce:
1. Open the application "GooglePlayMusicdesktopPlayer"
2. Log-in
3. Go to the Program Settings
4. On the General tab scroll down and find "Choose language"
5. Change language from English to Ukrainian, Russian, Hungarian
6.  Restart the application
7. Open application again
8. Go to the Program Settings - General tab - Choose language and back to English

Expected result:  All elements of the page will translate correctly in English

Actual result: Some elements of the page still are in Russian

![photo 24-11-2018 10 15 28](https://user-images.githubusercontent.com/45301266/48966507-ab8fbb80-efdb-11e8-8aa6-2363c93f25e0.jpg)
![photo 24-11-2018 10 24 14](https://user-images.githubusercontent.com/45301266/48966508-ab8fbb80-efdb-11e8-9291-4350e15982a4.jpg)
![photo 24-11-2018 10 25 20](https://user-images.githubusercontent.com/45301266/48966509-ab8fbb80-efdb-11e8-9ac2-846aa927a5ee.jpg)

**Comment by MarshallOfSound** [comment]
> Go to the Program Settings - General tab - Choose language and back to English

This setting is for your entire computer, not GPMDP.  You need to change the language of GPMDP separately back to English just like you changed it to Hungarian in your second picture.
