### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by gannycya** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3430]
OS: Windows 10 Home

GPMDP Version: V4.6.1.

Issue Descriptions: On the page with Program Settings there are a moment where tabs in such languages as Russian, Italian, Ukrainian and some others are hidden behind each other

Steps to Reproduce:

1. Open the desktop application "GooglePlayMusicPlayer"
2. Log in
3. Go to the Program Settings - General tab- "Choose language"
4. Change language from English to Ukrainian, Russian, Hungarian, Italian 
5. Restart the application
6. Open application again and Go to the Program Settings - General tab

Expected result: All tabs will be displayed correctly in selected language and they will be readable 
Actual result:  Tabs in such languages as Russian, Italian, Ukrainian and some others are hidden behind each other

![inkedphoto 24-11-2018 10 25 20_li](https://user-images.githubusercontent.com/45301266/48966658-a97b2c00-efde-11e8-889c-1ec369556c33.jpg)
![inkedphoto 24-11-2018 10 08 32_li](https://user-images.githubusercontent.com/45301266/48966671-01199780-efdf-11e8-9b1e-ff4a5951ea60.jpg)
![inkedphoto 24-11-2018 10 24 14_li](https://user-images.githubusercontent.com/45301266/48966672-01199780-efdf-11e8-89e2-1ab99560f8eb.jpg)

**Comment by MarshallOfSound** [comment]
Just as with any other application having a text overflow issue you can simply resize this window to make the text stop overflowing
