### ISSUE TITLE
Where can I get a list of keyboards shotcuts?

### ISSUE THREAD

**Issue by WELZ-gh** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3433]
Is there a wiki containing all of the keyboard shortcuts?

**Comment by jostrander** [comment]
Hitting `?` in GPM and YTM will produce their keyboard shortcuts. 
YTM
![image](https://user-images.githubusercontent.com/760989/48985432-841d1980-f0d5-11e8-9a5a-36b8df977bb9.png)
GPM
![image](https://user-images.githubusercontent.com/760989/48985439-9434f900-f0d5-11e8-8548-76a810108b09.png)
