### ISSUE TITLE
Lyrics are always displayed for currently playing song

### ISSUE THREAD

**Issue by tandr** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3435]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content
  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**
OSX 10.12.6 (Sierra)

**GPMDP Version:**
Version 4.6.1 (4.6.1)

**Issue Descriptions:**
No matter what song in a playlist do I use to select "Show Lyrics (Beta)", it is always showing lyrics for the current song. 
Or this menu item should behave as displaying lyrics for song I used a menu item, or it should be renamed to "Display Lyrics for currently playing", but then it does not make any sense to have it under other song's menu.

**Steps to Reproduce:**
1. Open any album that has lyrics (for example https://play.google.com/music/m/Bce5yfouky2o4gt7qdvbburbcau?t=Ride_The_Lightning_Remastered_-_Metallica ) 
2. Play first song
3. Try to select "Show Lyrics (Beta)" under second or third song.
4. Lyrics will be shown for the currently playing song

![lyrics-bad](https://user-images.githubusercontent.com/5227075/49126086-989d1580-f27f-11e8-87db-b1b272ef82dd.gif)

**Comment by jostrander** [comment]
Unfortunately we can't fetch the lyrics for the song other than what's currently playing, as we can't see which song was picked from the list. The menu in the player bar and the menu in the list are the same "menu" which is why it appears in both locations, and if we could differentiate between the two we could remove it from the improper locations.

**Comment by tandr** [comment]
(just a thought) These 2 menus (as whole) are different - they have some items in one case and not in another  another. Which means that there is a logic that allows to distinguish between them. Just maybe not from `this` qualifier...

**Comment by jostrander** [comment]
@tandr I created a PR to remove the extra menu items from the song menu to prevent this confusion in the future.
