### ISSUE TITLE
Playlists Created on GPMDP Don't Get Synced to Web or Mobile

### ISSUE THREAD

**Issue by NancysBrother** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3438]
Hello,

Edit: My Bad! I was in the YouTube Music window of GPMDP. When you create playlists there, it creates YouTube playlists. It appears that these are completely independent from Google Play Music playlists. (It also appears that you can't save a YouTube video to a Google Play Music playlist, at least I haven't been able to figure out how.) Perhaps this will help someone else who is experiencing the same confusion I was.

Sorry about that.

Here is my original issue:

Thank you for creating GPMDP. I use it a lot. I am using version 4.6.1 on Windows 10 Pro 64-bit 1809.

I create a new playlist in GPMDP and add some tracks. The playlist doesn't appear in the browser version of GPM or in the mobile (Android) version, even after several days.

I have tried Refreshing the library in the browser version, but that doesn't make any difference.

If I create a new playlist using the GPM Web version (I use Firefox), it immediately gets synced to the GPM Android app and is available to me there. However, it never appears in the GPMDP.

For some reason, it seems that the desktop app is not syncing in either direction.

It would be great if this feature could be fixed.

Thanks again,

Steven

**Comment by MarshallOfSound** [comment]
@NancysBrother This app at a high level just wraps the web client, anything not syncing is 100% on Google not this app

**Comment by Eli-Berkow** [comment]
Hi and thanks for the app.

I've noticed the same problem where I create playlists on my phone which syncs to the web as it should but not the app. Only after ending the task and reopening GPMD do they appear. Adding songs to the library, etc. works as expected.
