### ISSUE TITLE
Port to Carlo for reduced install size and improved security

### ISSUE THREAD

**Issue by eligrey** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3439]
Switching to Carlo would reduce our install size and improve the security of this app by not requiring new releases when Chrome updates are published.

**Comment by MarshallOfSound** [comment]
99% of this app would have to be rewritten and re-architectured for Carlo while Carlo brings users no tangible benefits aside from the Security aspects of using the local Chrome instance.

This isn't something I would work on, and tbh I'd probably never merge it even if someone did the work.  Things like testing, building, packaging, updating are solved and documented for Electron.  Carlo is new experimental tech with no large consumers and no support guarantees.

For transparency I'm also an Electron maintainer so this isn't going to happen for this project, Carlo has it's place but not for apps like this.
