### ISSUE TITLE
Windows: Not able to use mediakeys as hotkeys

### ISSUE THREAD

**Issue by brighthero** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#344]
**OS:**
Windows (10 x64)

**Issue Descriptions:**
Not able to use media keys as global shortcuts / hotkeys.

**Comment by moshec** [comment]
Same here.
windows 10 x 64

**Comment by sippi90** [comment]
Having the same problem with non-working mediakeys after updating to version 3.0.
Also uninstalled GPM chrome extension.
I figured out that when I start GPMDP with elevated rights I can use media keys but only if GPMDP is in focus if I minimize to tray -> It's still not working.

**Comment by primeinc** [comment]
same problem with Windows 8.1 x64

**Comment by MarshallOfSound** [comment]
OK, the work around at the moment is to remove the google play music chrome extension.

I'm working on a native module that handles shortcuts a bit better than electron does

**Comment by primeinc** [comment]
I can confirm removing the extension from chrome fixed the issue. Thanks!

**Comment by animusyosho** [comment]
I have this problem as well, but zapping the chrome extension did not resolve. This is on my windows 7 T440 x64.
My home PC on Windows 10 x64 has the same issue, though I have not tried removing the chrome extension yet there.

Love the app by the way! Google could not do much better themselves. :D

**Comment by moshec** [comment]
I didn't have the music app/extension installed on chrome in any way.
What I did notice is that the media keys work for me on my laptops built in keyboard, but not on the wireless keyboard I use all day.

**Comment by MarshallOfSound** [comment]
Logitech keyboard? @moshec

**Comment by moshec** [comment]
Microsoft, wireless 2000

**Comment by moshec** [comment]
It worked fine before, but I can look over my keyboard settings.

**Comment by sippi90** [comment]
I've also a Microsoft Keyboard (Sidewinder X4), nevertheless with 2.x everything worked just fine.

**Comment by tverhoeve** [comment]
Same. Media keys on Microsoft Sculpt Comfort Keyboard no longer work after update. Uninstalling chrome extension did not fix. Thanks.

**Comment by SimonKapl** [comment]
Got the same issue since the update

**Comment by rgoliveira** [comment]
Same issue here, although I use [Autohotkey](https://autohotkey.com/docs/AutoHotkey.htm) to emulate the media keys. Worked fine in the previous version, though.

**Comment by eladavron** [comment]
I MAY have found a workaround (not sure, needs more testing):

- Open Task Manager (CTRL+Shift+ESC)
- Under Process, find and kill "iType.exe"

That should do it.
I seem to remember having the same issue with the chrome extension back in the day - the iType (Microsoft's Keyboard software) pooched it.

**Comment by moshec** [comment]
killing itype fixed for me. I guess that'l do until this is fixed.

**Comment by sippi90** [comment]
killing itype fixed for me also. But I hope this get's fixed :+1:

**Comment by animusyosho** [comment]
Killing itype also fixed mine as a workaround

**Comment by eladavron** [comment]
A more permanent workaround, though a bit undesirable, is to completely uninstall the Microsoft Mouse and Keyboard software. Again, the same exact bug exists with the official Google Play Music Chrome Plugin, for what it's worth.

**Comment by moshec** [comment]
I hope there is a better solution than that.

**Comment by MarshallOfSound** [comment]
Hmmm, so `itype.exe` is a windows thing that is stealing the shortcuts :cry: 

I'm working on a c++ solution to low level key bindings that should fix this issue

**Comment by SimonKapl** [comment]
I can't find an itype.exe file, probably because i don't have an external keyboard.
Using a Dell XPS 15 9550 with Win10 x64.

**Comment by ckhericks** [comment]
Using 2 computers, media keys fails on both (Win 7x64, and Win 10x64).

Google Play Chrome is extension is installed on neither of them.

Just killed iType on the Win7 platform and the issue resolved. Will edit to update results for win10 when I get home.

**Comment by eladavron** [comment]
SimonKapl, see if Dell has some software active for OSD or media keys, and if so - try killing that.

**Comment by joelpereira** [comment]
Killing iType fixed it for me on v3.0 here too. However, I haven't made any changes on my computer and it used to work just fine in v2.x of this software.
Running on surface pro 2

**Comment by LovedByTheLord** [comment]
I discovered that if I run the desktop app "as administrator", the media keys work while the app is in focus.  If it focus on a different application in Windows, the media keys do not work.  This is the same behavior I get from the Google Play Music web player.

**Comment by MarshallOfSound** [comment]
Great news team.  I spent the last couple of days struggling through c++ docs just so I could make this module  

https://github.com/MarshallOfSound/node-lowlevel-keyboard-hook-win

So that I could fix this issue #youarewelcome :+1:

**Comment by LovedByTheLord** [comment]
@MarshallOfSound, is this fixed in 3.0.1?

**Comment by moshec** [comment]
Thanks! You are AWESOME!

**Comment by MarshallOfSound** [comment]
@LovedByTheLord Bearing in mind I closed this issue 2 hours ago but `3.0.1` was released over a day ago.... No... It is not in `3.0.1`

**Comment by lucasogodoy** [comment]
hey guys, sorry for the newbie question, but... how do I use this module? thanks!

**Comment by primeinc** [comment]
@lucasogodoy 

>This issue has been fixed and will be pushed out in 3.1.0

3.1.0 isn't out yet, so try one of the workarounds for now

**Comment by eugenio** [comment]
I still have this issue on 4.0.5, windows 10 pro , logitech K800 keyboard.

**Comment by oharrison72** [comment]
> I still have this issue on 4.0.5, windows 10 pro , logitech K800 keyboard.

Me too. Same keyboard. Removed the Chrome GPM extension, restarted. Still no media keys function.

**Comment by nielsbaan1992** [comment]
Hi there,

This is my first post, but i created a github account to post this.
I found that turning on these two options solved my problems, my media keys work. They work with Logitech Options as well, haven't tested Setpoint though. I will test that Tuesday at work.
![afbeelding](https://user-images.githubusercontent.com/37951470/38161206-bf8240c6-34ca-11e8-8a8c-4241a0e6eb0e.png)
(Works only in Windows I reckon.)
