### ISSUE TITLE
Unable To completely uninstall GPMDP

### ISSUE THREAD

**Issue by doomsec** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3442]
**Checklist:**

*  I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
*  I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
*  I have double checked and can reproduce the issue

**OS:** > windows

**GPMDP Version:** > 4.6.1

**Issue Descriptions:** > Unable to uninstall completely. After uninstallion i have tried deleting registry entries and deleting pending files and directories even CCleaner but, whenever i reinstall all previous settings and my account remained login.

**Steps to Reproduce:** 
setp1: install gpmdp
step2: login with google account
step3: uninstall
step4: clean
step5: install gpmdp
step6: -------( no login required already logged in into  my account  also all old setting are same )

**Comment by MarshallOfSound** [comment]
@doomsec The directory you probably want to delete is `%APPDATA%\Google Play Music Desktop Player`

**Comment by doomsec** [comment]
i did that on 4 different systems all windows 10 (ver 1809)
