### ISSUE TITLE
How to fix playback on Firefox?

### ISSUE THREAD

**Issue by catzybluphish** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3443]
I've always wanted to stream my uploaded music from the GPM site but had many issues when attempting so. However, when I use this program the playback is flawless. I'm using Arch so everthing is the latest and I built this package from the AUR. I don't believe the problem persists if I install install Chromium and the built in Google Play Music app but it just won't work for Firefox. Just wondering if you guys know a fix.
Cheers.

**Comment by jostrander** [comment]
Sorry, unfortunately I'm not familiar with why that would be the case. Best of luck!
