### ISSUE TITLE
192.168.2.8 Connection Prompt on OS X

### ISSUE THREAD

**Issue by craighooghiem** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3445]
**Checklist:**

* [ X ] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [ X ] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [ X ] I have double checked and can reproduce the issue

**OS:** OS X 10.14 / various versions

**GPMDP Version:** 4.6.1 / previous versions

**Issue Descriptions:** I am sure this is a simple thing, but I have tried uninstalling the application multiple times and still get the same issues. Each time I open the app, I have to wait 5-10 seconds before it open, because it is trying to connect to 192.168.2.8 - an OS X dialog pops up asking me for a username and password to connect to this source. I have no idea what it is trying to do, but everytime I close the app and open it again cold start it does the same thing.
The app will not open until I close this dialogue box.

<img width="457" alt="image" src="https://user-images.githubusercontent.com/1476306/49812659-e9a71200-fd33-11e8-88f8-f63517b33727.png">

**Steps to Reproduce:**
On my iMac, I close the app and open it again

**Comment by jostrander** [comment]
We make no connections to that address, only music.google.com and music.youtube.com. Do you have a corporate proxy or firewall?

**Comment by craighooghiem** [comment]
I'm at work, so that's possible.
Let me ask IT if they have any idea.

**Comment by craighooghiem** [comment]
This IP address belongs to a media server at work. I have no idea why this app continuously tries to connect to it (and won't open until I close this prompt), but I'll just deal with it.

**Comment by jostrander** [comment]
I'm going to take a wild stab in the dark. Does it implement mdns or cast API's?

**Comment by craighooghiem** [comment]
It might.. I can't confirm easily though. The popup still happens all the time.
I finally figured out what credentials it wanted and let it have them, so we'll see if it still comes back.
