### ISSUE TITLE
Stuck in splash screen

### ISSUE THREAD

**Issue by prithivraj** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3446]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:** Mac

**GPMDP Version:**  4.6.1 (4.6.1)

**Issue Descriptions:** App is stuck in the splash screen as below : 

![image](https://user-images.githubusercontent.com/3718984/49992048-eec0c700-ffa8-11e8-92ea-5d7205318e0c.png)

**Steps to Reproduce:** Open the app.

**Comment by Zindre** [comment]
This exact thing happens on my client also. I have used it for almost a year, this happened today. MacOS Mojave 10.14.2 / Google Play Music Desktop Player 4.6.1.

**Comment by mejiaro** [comment]
Happened to me to, I noticed it after upgrading to 10.14.2.

**Comment by jostrander** [comment]
I'd attempt to help figure this out but unfortunately I don't has macOS to test with. If anyone wants to check the console for errors that might help.

**Comment by mejiaro** [comment]
The console of the app right? How do I enable it?

**Comment by jostrander** [comment]
You may be able to still try and use <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>G</kbd> to open the URL picker and type in "DEV_MODE" and click "Let's go". That will restart into dev mode. Once you're there <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>I</kbd> should bring up the console. If that doesn't show any errors type `openGPMDevTools()` and check _that_ console. If that doesn't work I'll see if I can remember how to get into dev mode a different way.

**Comment by jostrander** [comment]
Just checked, if you can launch it from the command line the `--dev` flag should also work.

**Comment by mejiaro** [comment]
I got it. There's only a low priority warning.

<img width="1316" alt="screen shot 2018-12-24 at 12 20 21 pm" src="https://user-images.githubusercontent.com/6519196/50405171-63002500-0776-11e9-9c1e-1a9e411c5b6a.png">

**Comment by mejiaro** [comment]
oh sorry, there are a couple of errors in that console.
<img width="1249" alt="screen shot 2018-12-24 at 12 30 43 pm" src="https://user-images.githubusercontent.com/6519196/50405438-2e8e6800-077a-11e9-9a39-76b32cbac2c4.png">

**Comment by jostrander** [comment]
The content decoding error seems to be the issue here, but that's for a file on Google's server, so there's nothing we can do to fix that, that I'm aware of. However, you can try clearing the cache and checking to see if that fixes your issue. Try these paths:

```
~/Library/Cache/<app package name>
~/Library/Application\ Support/<app package name>
```
Where the app package is either GPMDP or Google Play Music Desktop Player.

**Comment by Zindre** [comment]
Hi jostrander. Thanks for the suggestion, clearing the application support indeed solved the issue on my system.  (I tried clearing the application caches first, that did not seem to have ant effect on its own.).

If anyone else who have the same problem reads this; the exact path is:

`~/Library/Application Support/Google Play Music Desktop Player/`

It is necessary to log in to your Google account again afterwards of course.

**Comment by jostrander** [comment]
I believe that may also clear your settings, you can preserve them by saving the json_store folder and restoring it after deleting everything else.

**Comment by Zindre** [comment]
I think my settings were deleted, but the most important  thing right now was to find a way to get it working again at all. 

Thanks for the suggestion. If it happens again I'll certainly make sure to save the json_store folder and see if problems are fixed also with settings preserved.

**Comment by prithivraj** [comment]
Hi, 

Clearing the app data fixed it for me. Thank you so much.
