### ISSUE TITLE
Issue with play/pause on he

### ISSUE THREAD

**Issue by Kydybets** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3448]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:** 
MacOS 10.14.1

**GPMDP Version:** 
4.6.1

**Issue Descriptions:**
I use my earpods for listen music.
When i click to raise or down the volume everything goes ok, but
if i click on play/pause the music is stoping for a half a second and then continue playing, and i need to hold this button for 2-3 second to payse or play music.

**Steps to Reproduce:**
described in issue

**Comment by samtstern** [comment]
Seems to be the same as https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3155
