### ISSUE TITLE
depedency problem on debian buster and segfault

### ISSUE THREAD

**Issue by dahabakuk** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3450]
**OS:**
debian buster (20181220)
**GPMDP Version:**
4.6.1
**Issue Descriptions:**
cannot start GPMDP because of missing libraries. and segfaults with them.
google-play-music-desktop-player: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory

after installing the package libgconf-2-4:amd64 that provides this, it segfaults:
(gdb) bt
#0  0x0000000000a4fa30 in ?? ()
#1  0x00007f0d7afd22b2 in node::http2::Http2Session::Callbacks::Callbacks(bool) ()
   from /usr/share/google-play-music-desktop-player/libnode.so
#2  0x00007f0d7afd2375 in ?? ()
   from /usr/share/google-play-music-desktop-player/libnode.so
#3  0x00007f0d7b22c39a in call_init (l=<optimized out>, argc=argc@entry=1, 
    argv=argv@entry=0x7ffc5f2632f8, env=env@entry=0x7ffc5f263308) at dl-init.c:72
#4  0x00007f0d7b22c496 in call_init (env=0x7ffc5f263308, argv=0x7ffc5f2632f8, argc=1, 
    l=<optimized out>) at dl-init.c:30
#5  _dl_init (main_map=0x7f0d7b246190, argc=1, argv=0x7ffc5f2632f8, env=0x7ffc5f263308)
    at dl-init.c:119
#6  0x00007f0d7b21e0ca in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#7  0x0000000000000001 in ?? ()
#8  0x00007ffc5f26438b in ?? ()
#9  0x0000000000000000 in ?? ()

**Steps to Reproduce:**
upgrade buster to latest version (all worked before at around october? sorry being this unclear)
install latest gmusic player
install libgconf-2-4:amd64 so no missing .so
start it and it segfaults.

**Comment by manicholls** [comment]
Pretty sure this is related to https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3391

**Comment by dahabakuk** [comment]
hm sounds like i have to wait for the next release then.
thanks - will wait for it and reopen if it still persists...

**Comment by manicholls** [comment]
There's a .deb in that URL that you can download and use for now.  I've been using it for a while now without any issues.
