### ISSUE TITLE
Device Selection does not work

### ISSUE THREAD

**Issue by Stanzilla** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3451]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:** Windows 10 1809

**GPMDP Version:** 4.6.1

**Issue Descriptions:** Audio selection does not work, always continues to play on "Default"

**Steps to Reproduce:** Change audio device to something else, hit play, music plays on default instead of new setting

Reloading or restarting the app does not fix it. The "other" device keeps being selected but sound plays on Default

![image](https://user-images.githubusercontent.com/75278/50400497-81225100-0787-11e9-8ef1-d99a32d3bd13.png)

**Comment by jostrander** [comment]
I just tested this and it seems to be working fine. I am using Ubuntu but the code is the same across the board unless something is broken upstream.

**Comment by Stanzilla** [comment]
As soon as a song started playing, switching devices does nothing anymore, no matter what you do, every future song will play on the old device

**Comment by Stanzilla** [comment]
Another thing, I changed the device, put my PC to standby, wake it a few hours later, it reverted to the old device.

**Comment by bennybenjaman** [comment]
If it means anything, I am also having a hard time selecting my audio device in GPM on Debian Buster. Under desktop settings >> playback >> Audio Devices.

I cannot hear any audio through my headset and when I go to Audio Devices my mouse changes to a block sign when hovered over the selection. It was working one day and the next I had no audio output. 

Should I open a separate issue?
