### ISSUE TITLE
Segment Fault on Parrot Linux

### ISSUE THREAD

**Issue by smrabelo** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3456]
**Checklist:**

* [X ] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [X ] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [X ] I have double checked and can reproduce the issue

**OS:** Parrot Linux

**GPMDP Version:** 4.6.1 Amd64

**Issue Descriptions:**
Afeter install, if go execute on terminal receive the errror "Segment Fault"
If I try execute on Menu just try open and close after.
On Ubuntu 18.04 LTS I install and open normal.

**Steps to Reproduce:**
$sudo gdebi google-play-music-desktop-player_4.6.1_amd64.deb .
$google-play-music-desktop-player 
Falha de segmentação

**Comment by jostrander** [comment]
Hey @smrabelo, this is a known issue with electron. See issue #3391. Closing this as a duplicate.

**Comment by smrabelo** [comment]
I tried the page that guided, but I could not make it work. I gave up.
I will use it via web or wait for a new version, thank you.
