### ISSUE TITLE
Persistent black screen always on load, new install Fedora 

### ISSUE THREAD

**Issue by AngelusDulcis** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3457]
**Checklist:**

* [X] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [ X] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [ X] I have double checked and can reproduce the issue

**OS: Fedora 29, 4.19.301 Kernel

**GPMDP Version: 4.6.1

**Issue Descriptions:
Starts up, I get a brief white screen with a circle, then it gets to a black screen and that's it. I can use the keyboard shortcut ctrl+shift+g to open, but since nothing is being rendered it's not the most helpful. 

google-play-music-desktop-player --disable-gpu
Starting Sentry
error: Failed to load bonjour with error: {}
Bonjour is required to use Chromecast Support or to enable ZeroConf for the PlaybackAPI
On linux you need to install "avahi"

I can navigate to the site, and play with a chromium browser with no issues. 

**Steps to Reproduce: Start the software.

**Comment by AngelusDulcis** [comment]
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/2721703/debug_info.zip)

**Comment by AppelonD** [comment]
I have the same problem, I really miss the App :-)
I have had it running on Fedora 29, but for some reason it suddenly went blackscreen on me

**Comment by archagy** [comment]
I have the same error on windows 10 with the "launch when **windows** start" option. it works after I re-launch the app manually.

**Comment by AppelonD** [comment]
I just build a RPM there works with Fedorta 29, please use 
`dnf copr enable appelond/google-play-music-desktop-player`
I'll try to keep up with the builds

**Comment by AngelusDulcis** [comment]
I enabled @AppelonD 's repo, the app is working a treat on Fedora 29 build. Thank you!

**Comment by MarshallOfSound** [comment]
Fixed in master, will be fixed in the next release
