### ISSUE TITLE
Uncaught Exception: The Internet connection appears to be offline.: (null)

### ISSUE THREAD

**Issue by b-lam** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#346]
An uncaught exception was reported.  
#### Info:
**OS:** darwin
**Arch:** x64
**GPMDP Version:** 3.0.0
**Time:** Mon Mar 07 2016 12:23:39 GMT-0500 (EST)

#### Error:
*The Internet connection appears to be offline.: (null)*
```js
Error: The Internet connection appears to be offline.: (null)
    at Error (native)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
Client side network issues
