### ISSUE TITLE
[FEATURE] Support low level audio hardware playback 

### ISSUE THREAD

**Issue by rijnhard** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3460]
I know this a bit niche, since GPM doesn't have lossless playback, but I'd like to have the ability to bypass PulseAudio in Linux and go straight to ALSA, since pulse can do some pretty nasty things with audio.

Essentially going to ALSA in Linux would allow us to play directly to the sound device and bypass pulse. The challenges are that Chrome (and by extension electron) is built to connect to pulse for compatibility, however when it comes to audio this can be negative because of the mixing that pulse does.

This would mean binding native modules and providing the ability to select the playback device, and I'm pretty sure it's going to be a PITA so I'm not getting my hopes up, but it would be nice for those who want to squeeze out whatever audio quality they can.

**Comment by rijnhard** [comment]
To be completely open.

I don't think it's worth it if Google doesn't have lossless.
With lossless I can tell the difference pretty easily between pulse and direct to ALSA, but I have a trained ear and most don't.

That being said, the Audiophile use case is the Audiophile use case, and that by its nature frets over the last 5% of factors that affect performance.

The best you can get with Pulse is to use the sox resampler if you are lucky enough to have it in your distro.

**Comment by MarshallOfSound** [comment]
This is something that Chromium would need to implement as a standard web API somehow in order for us (and GPM / YTM) to make use of it.  You should raise it with Chromium and / or the standards committees if you really want to see this happen.
