### ISSUE TITLE
When I hit my Media Keys it doubles the action, windows media service has been disabled

### ISSUE THREAD

**Issue by srobins6** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3462]
It's the exact issue mentioned on the FAQ but I have disabled windows media service, I think. I couldn't find anything explicitly called windows 10 media service but i disabled windows media player and the windows media network share. Is there something I'm missing?

**Comment by jostrander** [comment]
Are you looking in the application settings? Right click the tray and hit setting and disable windows 10 media integration.

**Comment by srobins6** [comment]
ohhh i didn't even see this desktop settings section. Thanks!
