### ISSUE TITLE
There's no way to prevent GPMDP from skipping songs in playlist if internet connection fails

### ISSUE THREAD

**Issue by xternal7** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3465]
**Checklist:**

* [ * ] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [ * ] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [ * ] I have double checked and can reproduce the issue

**OS:** Manjaro

**GPMDP Version:** 4.4.1

**Issue Descriptions:**

Sometimes my wifi connection goes out for a short while. When my wifi connection goes out and GPMDP tries to play songs, GPMDP will try to fetch songs. Because my wifi connection is out at the moment, GPMDP cannot fetch the songs, and because GPMDP can't fetch songs, it will blatantly skip a decent chunk of playlist.

I don't want GPMDP to skip songs when my internet is out. I understand why this 'skip problematic songs' exists, but having no option to stop GPMDP from attempting to play music when I know the wifi is temporarily down is getting really annoying.

**Steps to Reproduce:**

1. Play music
2. Disconnect from internet
3. Wait until current song ends
4. GPMDP will try to fetch a new song and fail because there's no internet connection

**Expected result**
5. While attempting to get a new song from google play music, GPMDP shows 'pause' button that would allow me to pause the program if I know my internet is off and thus prevent it from skipping songs.

**Actual result**
5. From this point forward, you cannot pause GPMDP, because GPMDP shows 'play' button instead of the 'pause' button, resulting in unnecessarily skipped songs.

**Comment by MarshallOfSound** [comment]
This UX and behavior comes straight from Google's GPM UX.  We can't really change it, if you'd like it changed I'd suggest raising it on Google's product forums
