### ISSUE TITLE
OSX Dock Icon shows OSX placeholder only when multiple displays connected

### ISSUE THREAD

**Issue by jaysonesmith** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3466]
**Checklist:**

* [X] I have checked that there are no issues with similar or the same content
* [X] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [ ] I have double checked and can reproduce the issue
    * **I don't have steps to reproduce unfortunately just experience the issue.**

**OS:** OSX 10.12.6 (though this has been happening for a bit)

**GPMDP Version:** Plist info below, but this has also been happening for a bit across versions.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>BuildMachineOSBuild</key>
    <string>16G1314</string>
    <key>CFBundleDisplayName</key>
    <string>Google Play Music Desktop Player</string>
    <key>CFBundleExecutable</key>
    <string>Google Play Music Desktop Player</string>
    <key>CFBundleIconFile</key>
    <string>electron.icns</string>
    <key>CFBundleIdentifier</key>
    <string>google-play-music-desktop-player</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>Google Play Music Desktop Player</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>4.6.1</string>
    <key>CFBundleVersion</key>
    <string>4.6.1</string>
    <key>DTSDKBuild</key>
    <string>14D125</string>
    <key>DTSDKName</key>
    <string>macosx10.1010.10</string>
    <key>DTXcode</key>
    <string>0833</string>
    <key>DTXcodeBuild</key>
    <string>8E3004b</string>
    <key>LSApplicationCategoryType</key>
    <string>public.app-category.music</string>
    <key>LSMinimumSystemVersion</key>
    <string>10.9.0</string>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>NSMainNibFile</key>
    <string>MainMenu</string>
    <key>NSPrincipalClass</key>
    <string>AtomApplication</string>
    <key>NSSupportsAutomaticGraphicsSwitching</key>
    <true/>
    <key>NSHumanReadableCopyright</key>
    <string>Copyright © 2018 Samuel Attard, All rights reserved.</string>
  </dict>
</plist>
```

**Issue Descriptions:** My dock and applications folder doesn't show the app's icon when multiple displays are connected, however when using **only** the laptop, it displays. 

I've attempted various icon resets that I've found while Googling and also have tried reinstalling the app, but haven't had much luck. Any info that might be available would be awesome. Also happy to put any solution we find into the FAQ or another troubleshooting doc!

Example:
* Multi
![dock](https://i.imgur.com/EUOK7gQ.png)
![finder](https://imgur.com/A6dBgla.png)

* Laptop
![example](https://imgur.com/zVNdNEU.png)
![finder](https://imgur.com/0tyEQsW.png)

**Steps to Reproduce:** Unknown. Sorry!

**Comment by ericnicolaas** [comment]
This is a duplicate of https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3296 — that's been marked as closed though the issue is still present.

**Comment by jaysonesmith** [comment]
Oh hey, thanks for the heads up! Bummer to hear that you're still experiencing it, too. :(

**Comment by jaysonesmith** [comment]
@MarshallOfSound I uninstalled, downloaded a new copy, and as soon as I unzipped the package the icon had trouble. Could this point to a way things are compiled for the OS by chance?

**Comment by jaysonesmith** [comment]
After installing Mojave this issue is no longer happening.
