### ISSUE TITLE
Airplay not visible

### ISSUE THREAD

**Issue by soubestre** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3467]
**Checklist:**

* [YES] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [ YES] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [ YES] I have double checked and can reproduce the issue

**OS:**  Mojave 10.14.2 

**GPMDP Version:** Version 4.6.1 (4.6.1)

**Issue Descriptions:** 
Dear

I love what you are doing end enjoy your product. I just have one issue concerning the Airplay integration. For some reason I ignore I can see my Fire Stick as an Airplay receiver but can't see my Apple TV which is the one connected to my Hi-Fi system.

I've tried several things but it's never visible while it is from iTunes.

I simply can't see the Apple TV as a possible Airplay receiver

Thanks a lot for your help.

Thierry

**Steps to Reproduce:**
Open the App. Nothing is visible.

![image](https://user-images.githubusercontent.com/437689/51086142-f9ef4a00-1742-11e9-9f7b-5325667bfc03.png)
...

**Comment by jostrander** [comment]
I don't believe we've ever integrated airplay, u less it follows the Chromecast protocols?

**Comment by soubestre** [comment]
My mistake then I saw Airplay somewhere, thought you implemented it.

Best regards


*Thierry Soubestre*

328 avenue de la Couronne, 1050 Bruxelles, Belgium

soubestre@gmail.com | + 32 496 16 41 08

**Comment by jostrander** [comment]
Does it work if you use the GPM site? If so that might be something we could add upstream.

**Comment by soubestre** [comment]
Nope that's the problem I encounter. It's a feature available only in
iTunes which I find really useful as it allows me to cast only my music and
not my whole Mac.

Thanks


*Thierry Soubestre*

328 avenue de la Couronne, 1050 Bruxelles, Belgium

soubestre@gmail.com | + 32 496 16 41 08

**Comment by jostrander** [comment]
Looked into some unofficial documentation for AirPlay and I don't think something like this would be possible currently. It requires sending the AirPlay server a URL where it can pull the stream from, and currently we don't have access to that.
