### ISSUE TITLE
Cannot enter directly to google play music

### ISSUE THREAD

**Issue by mcanobbio** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3469]
**OS:** macOS 10.14.2

**GPMDP Version:** 4.6.1

**Issue Descriptions:** I cannot enter directly to google play music, when I open the app takes me directly to youtube music, I even reinstall the app and I got the same result
If I go to View -> go to URL -> put **https://play.google.com/music/listen** I can enter to google play music but the keyboard controls (play, next, previous) don't work

**Comment by chris-hatton** [comment]
I have the same issue.  Steps to reproduce:
- Run the **Google Play Music Desktop Player** in its default state
- Observe that there is an option to choose either 'Google Play' or 'YouTube Music (Beta)' on either of the View/Window menus (I can't recall where exactly as this bug prevents me from accessing it again)
- Choose 'YouTube Music'
- Observe that the App switches state to 'YouTube Music'
- There is now no way to return to the default 'Google Play Music' state; the previous source selection option has disappeared and the 'YouTube Music' mode persists across App restarts and re-installation.

In effect; selecting the YouTube Music Beta mode just once, kills the App :-(

**Comment by jostrander** [comment]
The tray menu (on Mac the icon in the menu bar, not the dock) has the option to switch, as far as I know that's the only place to switch it other than manually changing the settings file.

**Comment by mcanobbio** [comment]
Thanks a lot @jostrander I didn't know about that options in the menu bar icon
