### ISSUE TITLE
More Options button does not appear

### ISSUE THREAD

**Issue by FintanH** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#347]
**OS:**
Mac OSX

**Issue Descriptions:**
The More Options button does not appear when scrolling through My Albums

**Steps to Reproduce:**
I have set the theme with the dark pink colour. Looking through My Albums section the aforementioned button (usually three vertical dots) does not appear. I am able to click the button but it is invisible.

**Comment by MarshallOfSound** [comment]
Please provide relevant screen shots

**Comment by MarshallOfSound** [comment]
Oops, wrong button

**Comment by jostrander** [comment]
With dark theme enabled:
![image](https://cloud.githubusercontent.com/assets/760989/13586384/8b10116c-e48e-11e5-9266-bcf295e3ff50.png)

Without:
![image](https://cloud.githubusercontent.com/assets/760989/13586370/74f66a8e-e48e-11e5-98d8-ea3aef3643e4.png)

**Comment by MarshallOfSound** [comment]
It's caled the "Sneaky Button™"

But in all seriousness can you raise this as an issue against https://github.com/gmusic-utils/gmusic-theme.js

**Comment by jostrander** [comment]
Already present as of 2 days ago: https://github.com/gmusic-utils/gmusic-theme.js/issues/12

But agreed, that thing is sneaky.
