### ISSUE TITLE
Use app password auth instead of embedded brauser

### ISSUE THREAD

**Issue by vasaka** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3471]
Using in-app browser for auth requires me to trust an app with password input which I can't. There is another way to do auth that is safe and does not rise all those security concerns is to use app passwords, which goes through standard browser.

**Comment by MarshallOfSound** [comment]
@vasaka You can sign in to your google account with an app password.  There is no other way for us to authenticate into GPM, there is no oAuth scope / API for it.

**Comment by Shadowpheonix** [comment]
I have this same issue.   Using an app password currently does not work.  When trying to login with one, it reports invalid password.  It is currently necessary to login with the normal password, granting full access to the entire account (including billing info as well as the ability to change account ownership & recovery info - an EXTREMELY risky proposition).
