### ISSUE TITLE
Not asking for LastFM credentials.

### ISSUE THREAD

**Issue by Felipowisky** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3478]
**OS:** 
Windows 10 64 bits

**GPMDP Version:**
4.6.1 (I guess! I can't find a way to show the running version, but I have just downloaded it from https://www.googleplaymusicdesktopplayer.com/)

**Issue Descriptions:**
When I click on the "LOG IN TO LAST.FM" (Desktop Settings/LASTFM/LOG IN TO LAST.FM) the message "Last.FM Status: Authorization In Progress" is displayed for ~21 seconds. There is no place to input my Last.FM credentials (none on the screen where I see the clickable " "LOG IN TO LAST.FM" message, no pop-up either). After the ~21 seconds the message "Last.FM Status: Not Authorized"  appears. 

I am using GPMD behind a proxy (have to, it is the company computer, using the company network). The proxy is configured at the system level and *most* software behave with no problem. 

**Steps to Reproduce:**
Install GPMD. Open GPMD for the first time ever. Log to your Google Account. Go to Desktop Settings/LASTFM click on the "LOG IN TO LAST.FM" text. Wait 21 seconds.

**Comment by gfairchild** [comment]
I'm getting a similar issue. For me, though, I see the message "Last.FM Status: Authorization In Progress" displayed for about half a second before it disappears. I am also behind a proxy at work.

**Comment by gfairchild** [comment]
FWIW, I brought my work laptop home today and was able to successfully log into Last.fm. But when I VPN into work (and am thus behind the firewall and need to use the proxy), no songs seem to get sent to Last.fm (they do when I'm not VPNed in).

If there's a place where debug logs are kept, I'm happy to look at them to provide more details.

**Comment by MarshallOfSound** [comment]
> I am using GPMD behind a proxy (have to, it is the company computer, using the company network).

Our last.fm integration currently does not work behind a proxy see #921
