### ISSUE TITLE
Site certificate expired

### ISSUE THREAD

**Issue by jespersh** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3480]
https://www.googleplaymusicdesktopplayer.com/

www.googleplaymusicdesktopplayer.com uses an invalid security certificate. The certificate expired on Sunday, February 3, 2019, 11:00:14 PM. The current time is February 4, 2019, 8:49 AM. Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by MarshallOfSound** [comment]
Can never make that stupid cron job work 😢 Fixed manually now
