### ISSUE TITLE
App don't dissapear from taskbar after click on close button after Mint update

### ISSUE THREAD

**Issue by alvarovelezgalvez** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3481]
**OS:** Linux Mint 19.1 Tessa

**GPMDP Version:** 4.6.1

**Issue Descriptions:** After update from Linux Mint from 19 to 19.1, GPMDP remains in taskbar and tray after clicking on close button

**Steps to Reproduce:** Open GPMDP, click on close button. GPMDP will appear both in taskbar and tray:
![screenshot_2019-02-07_11-14-52](https://user-images.githubusercontent.com/2486011/52404608-b382d600-2ac9-11e9-98ac-ce7e138e7092.png)

**Comment by MarshallOfSound** [comment]
You probably have `minimizeToTray` enabled and your window manager is also keeping that icon in the taskbar.  We can't support every combination of linux WM but if you can figure out how to fix it we would accept a PR
