### ISSUE TITLE
"I'm feeling lucky" hotkey doesn't work in YouTube Music

### ISSUE THREAD

**Issue by Bruno-Brant** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3482]
This is a feature request.

The "I'm feeling lucky" hotkey doesn't work on YouTube Music, although YTM has a similar functionality called "Your Mixtape". I believe users will find it pleasantly to use the same key for both functions.

**Comment by MarshallOfSound** [comment]
This should be raised and implemented in `ytm.js`
