### ISSUE TITLE
Heating battery of notebook

### ISSUE THREAD

**Issue by etomoinick** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3484]
**OS:**
Windows 10

**GPMDP Version:** 
4.6.1

**Issue Descriptions:**
Hi there, I am the user of Xiaomi notebook pro with i7 intel processor. After 15-20 minutes of listening to music in GPMDP, my batter heat to 70-75 С. coolers run at maximum speed. This is very annoying, also this issue drains my battery.

**Steps to Reproduce:**
I had reproduced this issue a few ways - when GPMDP run alone and with other apps. Every time GPMDP use processor more than other apps (even more than G Chrome).

**Comment by MarshallOfSound** [comment]
Duplicate of the other "high CPU usage" issues
