### ISSUE TITLE
app interface freezes after pressing play on Win 10 release 190205

### ISSUE THREAD

**Issue by eturk1** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3485]
**OS:**
windows 10 pro build 18334.1 (preview slow ring)
App has been working on every build up to now, the new build that came out last night.

**GPMDP Version:**
4.1.1

**Issue Descriptions:**
As soon as song starts to play interface freezes. Progress bar doesn't move. Clicking app lets us know it's frozen. First song will play, then a few seconds of next song, then no music.

**Steps to Reproduce:**
Open app, press play, freeze.
I did turn off "desktop notifications" in "Settings" (not "desktop settings"), as noted in some closed issues that sound similar from 2017, but that didn't help.

**Comment by MarshallOfSound** [comment]
Duplicate #3483
