### ISSUE TITLE
discord Rich presences and random crash

### ISSUE THREAD

**Issue by Millie290** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3488]
OS
**Manjaro:**
VER
**4.6.1:**

Hey i just want to know how to use discord rich présence with gpdmp cause idk how it work thanks

and i got a issue some random crash idk why

**Comment by jostrander** [comment]
Check the pinned issue for the crash. Turn on discord rich presence in desktop settings and it will connect to discord.
