### ISSUE TITLE
OSX: Menu Icon has no padding

### ISSUE THREAD

**Issue by hiddensanctum** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#349]
**OS:** Mac OSX 10.11.3

**Issue Descriptions:** This is just a minor cosmetic issue with the menu bar icon. There seems to be no padding for the icon making it look odd next to other icons.

**Steps to Reproduce:** Launch the app on Mac OSX

**Comment by MarshallOfSound** [comment]
Fixed in master. See #228
