### ISSUE TITLE
how to install google music player 4.6.1 Debian

### ISSUE THREAD

**Issue by batmanm0b1E** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3490]
I tried installing .deb google music player for 4.6.1 but it doesn't launch 

i get these upon install

Warning: mailcap line not starting with a media type in emerald
Problematic line:  application/x-emerald-theme; nametemplate=%s.emerald

and this when try to start it in terminal
Segmentation fault

please help thank you

**Comment by zerkz** [comment]
see - https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3391 

If you download the latest deb from master (via circle) it will probably work.

**Comment by batmanm0b1E** [comment]
I did that and it did not work. I got that error

**Comment by MarshallOfSound** [comment]
Fixed in master, will be fixed in the next release
