### ISSUE TITLE
Incorrect operation of multimedia keys (next or previous track)

### ISSUE THREAD

**Issue by GhostInq** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3491]
**OS:** Windows 10 x64 1809 (build 17763.292)

**GPMDP Version:** 4.6.1

**Issue Descriptions:** When using multimedia keys in Windows
version (go to the next track or go back to the previous one) switches over one track, rather than launching the next one in the list. I don’t know how in Google Music mode, but in YouTube Music mode, this problem definitely exists. As well, Win 10 media services incorrectly display the names of tracks and artists (the artist from the previous track, and the name of the track itself from the current one).

**Steps to Reproduce:** Both errors occur when using multimedia keys on the keyboard.

![screenshot_1](https://user-images.githubusercontent.com/18668333/52623752-bd377f80-2eb5-11e9-8e16-71381bb575b2.png)
![screenshot_2](https://user-images.githubusercontent.com/18668333/52623753-bd377f80-2eb5-11e9-9849-3bc7c545bdae.png)

**Comment by MarshallOfSound** [comment]
known and fixed in master
