### ISSUE TITLE
YouTube Music is not available in your area Even tho it is

### ISSUE THREAD

**Issue by TomasLaggeR** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3492]
**OS: Windows 10**

**GPMDP Version:4.6.1**

**Issue Descriptions: Youtube Music "is not available in my country" even tho it is (Im from spain) and it was working before but when i changed the timezone to thailand and used a proxy aswell it just stopped working, now im back without proxy and my timezone and still nothing**

**Steps to Reproduce: Not sure if changing time zones or using an ip address from a country without youtube music**

**Comment by NPW1** [comment]
I have the same problem. But the problem started when I disconnected from my VPN connection in Netherlands. I live in Sweden. I have not switched any time zones. the problem seems to only be related to switching IP addresses.

**Comment by MarshallOfSound** [comment]
If you switched countires / used a VPN and it still thinks it's not available I'd suggest completely deleting GPMDP's cache and starting again.

**Comment by merlyn333** [comment]
Greetings to all:

I am in China and I am connecting via ExpressVPN to a server in the United States.

I haven't been able to connect to YouTube Music for more than a week and I don't know how to solve it.

https://music.youtube.com/coming-soon/

I am using Windows 10 with Microsoft Edge 90.0.818.49 (64 bit).

I don't know what GPMDP's cache is.

Could you help me?

![msedge_tR7oKVRcvc](https://user-images.githubusercontent.com/361017/116513496-40f5af00-a8fc-11eb-8b02-f70e526b6d71.png)
