### ISSUE TITLE
Entire player freezes on listening to one specific song

### ISSUE THREAD

**Issue by Gyyyn** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3494]
**OS:** Windows 10

**GPMDP Version:** 4.6.1

**Issue Descriptions:** Entire player freezes on listening to one specific song. Probably something to do with the weird periods on the song name.

**Steps to Reproduce:** Listen to the specific song: Virtual Self - a.i.ngel (Become God)

**Comment by jostrander** [comment]
Duplicate of #3483
