### ISSUE TITLE
Stuck on fedora 26

### ISSUE THREAD

**Issue by Anton111111** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3497]
**OS:**
Fedora 26

**GPMDP Version:**
4.6.1

**Issue Descriptions:**
it stuck after some times on playing music and show black screen instead window content. And buttons play, next in tray doesn't work.
May be i can send some logs. Let's say me where i can see logs.

**Steps to Reproduce:**
Start play music and close app window. After several songs it stuck and show black screen if i try open app window.

**Comment by pbentkowski** [comment]
Hi Anton111111, are sure it's a different problem than the one reported here #3483 
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3483
?

**Comment by Anton111111** [comment]
HI @pbentkowski ! I think that my problem is another, because @segrived solution don't fix my problem.

**Comment by MarshallOfSound** [comment]
This is fixed in master and will be fixed in the next release
