### ISSUE TITLE
[Feature] App theme color based on album image

### ISSUE THREAD

**Issue by purpl3F0x** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3499]
It would be nice to have an option to make the color of the app borders etc.. based on the cover image of the song like the mobile app does. It would be very easy to do with something like this (https://github.com/lokesh/color-thief/).
I would have done it my self if I knew how the app is structured.

**Comment by MarshallOfSound** [comment]
This should be implemented / raised on `gmusic-theme.js`
