### ISSUE TITLE
Request: Show lyrics

### ISSUE THREAD

**Issue by SonicGD** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#35]
Please, add lyrics panel or something like [Lyrics Here plugin](https://chrome.google.com/webstore/detail/lyrics-here-by-rob-w/lifkpflabnobkgbjpcmocmgcajlecbcp).

**Comment by MarshallOfSound** [comment]
I'm going to put this in the "not really going to happen" basket as most lyrics API's cost money to use and that does not fit in to this app.  If someone can provide a reference to a free API that returns the entire set of lyrics I'll look into this, until then it is marked as invalid
