### ISSUE TITLE
Repeated scrobbles after playback hang (casting to chromecast)

### ISSUE THREAD

**Issue by doubleloop** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3500]
OS: Debian GNU/Linux buster/sid x86_64
GPMDP Version: 4.6.1

## Issue Descriptions

Some songs from my playlist where scrobbled by GPMDP over and over again  (sometimes 100+ times in a row). I noticed the issue occurred multiple times from 03/2017 till now. I definitely did not play this songs in a loop.

## Steps to Reproduce
I do not have reproduction procedure yet, working on this

**Comment by doubleloop** [comment]
I was able to reproduce the issue today, the result is that after song is finished, nothing is played but notice the playback time:

![screenshot from 2019-02-20 11-37-30](https://user-images.githubusercontent.com/2602750/53086139-cb644c00-3504-11e9-826f-8ab7b33676e7.png)

it is still increasing, and new scrobble is posted every song duration:

![screenshot from 2019-02-20 11-38-04](https://user-images.githubusercontent.com/2602750/53086141-cdc6a600-3504-11e9-8722-d0c12bcaa77a.png)

I checked the logs but I did not find any error there.
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/2884282/debug_info.zip)
(note: gpmdp_connect_email could be hidden by default when generating zip, I did manually hide it)

still working on reliable reproduction procedure

**Comment by MarshallOfSound** [comment]
Can you please raise this over on https://github.com/GPMDP/electron-chromecast
