### ISSUE TITLE
Ignore multimedia keys option

### ISSUE THREAD

**Issue by divi255** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3502]
Good day,

is it possible to implement configuration option to ignore multimedia keys? I have media keys bound on a complex macros which I use frequently.

Thanks

**Comment by michi-at** [comment]
> is it possible

Currently mediakeys binding is hardcoded in `main/features/core/keyboardShortcuts.js`

**Comment by MarshallOfSound** [comment]
This probably isn't something that we're going to do / make user customizable.

If you want to make a hidden setting flag to turn these off feel free to make a PR but this isn't something we can track
