### ISSUE TITLE
Where is lyrics displayed? Can't find it....

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3507]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**
opensuse 15 KDE
**GPMDP Version:**
4.6.1
**Issue Descriptions:**
I can't see where is lyrics displaying?  The UI looks like the official web page but there is no lyrics appearing everywhere and I can't find a button to start display lyrics... I only see in the settings about lyrics scrolling which I enabled already...
**Steps to Reproduce:**
Start the application and everything works except there's no lyrics anywhere.

**Comment by jostrander** [comment]
Lyrics are under the menu at the bottom in GPM but are not implemented in YTM yet. 

![image](https://user-images.githubusercontent.com/760989/53699234-1fe4b280-3db4-11e9-84cd-49f2eb60b5d4.png)

**Comment by GreatBigWhiteWorld** [comment]
Sorry about that. Really couldn't find it.

**Comment by jostrander** [comment]
No worries.
