### ISSUE TITLE
[Suggestion] Discord Chat

### ISSUE THREAD

**Issue by Alipoodle** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3509]
Hi there.
I wanted to make a suggestion more or less for the project as a whole.

Discord is becoming more popular and generally easier to access as you aren't required to create a account to access the server (depending on server security). As the program currently has Discord rich presences integration, and the widely growing popularity of it, I though that possibly having an alternative support/chat space on Discord might be appropriate. I still do agree that keeping the Gitter might be appropriate due to being linked with your GitHub account and being a quick access to a chat, 

Additionally the program can be put under the [Discord open source](https://discordapp.com/open-source) scheme which would allow for a Vanity Link *such as discord.gg/GPMDP* with a custom background. This can allow for it to be displayed on the page and possible grow some more people using and developing the program.

**Comment by jostrander** [comment]
I went ahead and made a new server, nothing special, but if discord is your thing: https://discord.gg/n2RDdVt

**Comment by MarshallOfSound** [comment]
Closing out as the chat was created
