### ISSUE TITLE
Cannot enlarge Mini-player

### ISSUE THREAD

**Issue by StephenBrown2** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#351]
I am trying to control my window sizes and locations, and would like the size of the Mini-player to be a little bigger, 350x350, but have found that I cannot do so.

I suspect it is due to the following hint that I found when running xprop on the mini-player:
```
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 1892, 169
		program specified maximum size: 310 by 310
```

I believe this should probably be setting the size (Preferred) or minimum size, not the max size, to allow for resizing of the mini player.

Reference: https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html#idm140200472494112
https://tronche.com/gui/x/icccm/sec-4.html#s-4.1.2.3
> The WM_SIZE_HINTS.flags bit definitions are as follows:
> Name	Value	Field
> ...
> PSize	8	Program-specified size

Additionally, it would be good to have some attribute, such as the Window title, to change when in Mini player mode, for easier controlling of the window by automated tools.

**OS:** Linux (Arch)

**Issue Description:** Mini-window cannot be resized greater than initial 310x310

**Steps to Reproduce:**
1. Start GPMDP
2. Send to Mini-Player mode
3. Attempt to resize window
4. Find that it cannot be bigger, but can be smaller than 310x310

**Comment by MarshallOfSound** [comment]
The mini is designed to be capped at the width, not only because it is a **"mini"** player but because the images (album artwork) are only going to appear at the resolution of 300/300

**Comment by amancevice** [comment]
Any way to increase the resolution on the artwork? Looks pretty rough on a retina display

**Comment by MarshallOfSound** [comment]
You can (I figured out that the URL includes the requested size) but the raw album art isn't HQ on google play music.  So it will more than likely just scale the images, not give you higher quality ones

**Comment by amancevice** [comment]
What about initializing the album-art vizualizer in the mini player instead of displaying the art from this URL? This seems to use a higher-rez version of the album art. Just a thought

**Comment by kalentia** [comment]
I would like to add that this issue causes some undesirable behavior in i3. If I switch to the mini player before first setting the window to floating mode, there is quite a bit of flashing and annoyance as i3 attempts to set the application size to one larger than it supports.

**Comment by MarshallOfSound** [comment]
@kalentia The I3 issue (amazing as it sounds) has been fixed.  Can you try updating to the latest version (Not sure what the process is for this on arch)

**Comment by tehoko** [comment]
To add to this, I can't make the mini player **smaller**. Resizing it makes it flicker, and the window doesn't really change its size.

[Here's a gif showing the window behavior.](http://i.imgur.com/pVTn3OO.gifv) (4.46 MiB)

Windows 10, GPMDP 3.0.1.

**Comment by MarshallOfSound** [comment]
@tehoko The result is not supposed to be a thing...  All album art is square, so the mini player should be square as well to fit it?

**Comment by tehoko** [comment]
@MarshallOfSound I understand, but that's just what I expected when I noticed it can be resized vertically. I feel the aspect ratio of album art shouldn't be the limiting factor when manipulating windows (it could be cropped instead of squished).

**Comment by MarshallOfSound** [comment]
OK, so final word on this is

I don't think the "mini" player should go bigger than 310x310 (That's a relatively standard mini player size)

In regards to @tehoko's request, follow #701
