### ISSUE TITLE
Media Keys not working on macOS Mojave (10.14.3) 

### ISSUE THREAD

**Issue by klouie-onelogin** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3510]
**OS:** 
macOS Mojave (10.14.3) 

**GPMDP Version:** 
4.6.1

**Issue Descriptions:**
The media keys on my Magic Keyboard does not work.   I do not have any other media players open or the Google extension.

**Steps to Reproduce:**
* Connect keyboard: 
** https://www.apple.com/shop/product/MLA22LL/A/magic-keyboard-us-english?fnode=56
* Open GPMDP
* Try using media keys

**Comment by barronlroth** [comment]
+1

Have MBP with Touchbar. The media keys in the touch bar accurately reflect the playing state (e.g. play/pause switches depending on the state of GPMDP), but tapping the buttons do nothing.

**Comment by breon** [comment]
Can confirm not working for 10.14.4. I'm using a wireless keyboard with physical media buttons.

**Comment by hob** [comment]
+1

**Comment by MarshallOfSound** [comment]
This binding issue was fixed a while back in Electron and should be fixed in an upcoming Electron update

**Comment by pkoenig10** [comment]
Are there plans to release a new version with the necessary Electron update?
