### ISSUE TITLE
Dock Icon disappeared from install Multiple Linux Flavors (still shows on listing in ubuntu software)

### ISSUE THREAD

**Issue by rgordon95** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3511]
**Checklist:**

* [ x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x ] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x ] I have double checked and can reproduce the issue

**OS:** Ubuntu 18.04 LTS

**GPMDP Version:** 4.6.1

**Issue Descriptions:** The icon is appearing as the default for no icon. It worked in previous versions

**Steps to Reproduce:** Just install it. I had it installed then one day it disappeared. Have un/reinstalled several times. There used to be one with the electron symbol in the icon and one with an orange slice circle type thing. The electron one is gone and this is the latter. It is a snap.

**Comment by rgordon95** [comment]
I was able to temporarily fix this by navigating to the application folder ~/snap/google-play-music-desktop-player/urrent/usr/bin/ right clicking google-play-music-desktop-player clicking properties and then dragging the svg file downloaded from the repo into the blank icon spot.

**Comment by blazingkin** [comment]
Can confirm this is happening on KDE Plasma too

**Comment by rgordon95** [comment]
updated title to reflect more widespread issue

**Comment by MADAOLEX** [comment]
There is no icon in tray too.
![1](https://user-images.githubusercontent.com/36064367/54740643-34171500-4be6-11e9-9e7f-d1fb58ab8733.png)
![2](https://user-images.githubusercontent.com/36064367/54740644-34171500-4be6-11e9-96d5-3780749e5f04.png)

**Comment by rgordon95** [comment]
can confirm latest (3/22) update does not fix

**Comment by MarshallOfSound** [comment]
This will be fixed in an upcoming Electron update
