### ISSUE TITLE
Unstripped RPMs or debuginfo?

### ISSUE THREAD

**Issue by ringerc** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3514]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:** Fedora 29 (but applies to all rpm-based and deb-based Linux)

**GPMDP Version:** 4.6.1-1 (but applies to all)

**Issue Descriptions:**

I was unable to locate any documented location for debuginfo packages for GPMDP, so when debugging a crash (#3391) I was unable to get a particularly useful backtrace. The binaries shipped are stripped, and there's no debuginfo rpm:

```
~$ file "/usr/share/google-play-music-desktop-player/Google Play Music Desktop Player"
/usr/share/google-play-music-desktop-player/Google Play Music Desktop Player: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, stripped
```

**Steps to Reproduce:**

* attach gdb to a core or running instance of gpmdp
* bt
* note lack of line number and argument information, stack frames that are not decoded, etc

**Proposed fix**:

I expect that you're probably already generating debuginfo rpms, since they're produced automatically. Please add them to releases.

If you're not producing debuginfos, let me know and I'll help out.

I'd also like to get a simple yum repo going for you if I can, so I don't have to chase the github releases.

**Comment by jostrander** [comment]
The issue in question is technically already fixed by upgrading the version of Electron we're using. Adding debuginfo binaries is way out of my wheelhouse as I believe it requires modifying upstream packagers and compilers within Electron, or setting  options when 'compiling' this program.

**Comment by ringerc** [comment]
Ah, so you're generating packages with tools that're part of the appdev framework, not your own specfile etc. That makes sense given the app's pseudo-web-based nature.

Good it's fixed upstream in the newer Electron. Link for reference? Any version info?

I wasn't able to quickly find anything on producing debuginfos with Electron. That definitely complicates things.  They have a [VS symbol server for Windows builds](https://github.com/electron/electron/issues/5876) but that's not much use.

rpm and deb builds of gpmdp appear to use https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/docker-compose-linux-build.yml but I wasn't able to trace that back as far as actual spec file generation, rpmbuild, etc.

Some notes [here](https://github.com/bbc/speculate/wiki/Packaging-a-Node.js-project-as-an-RPM-for-CentOS-7) suggest debuginfos can be produced for node projects. But while I know rpm, C, Fedora, etc, fairly well I'm lost with Node, Electron, etc, and I'm not sure how to dig through the layers of docker and wrappers and tools to find where and how your rpms are built.

**Comment by Walsen** [comment]
Hi,

Any news on this, I upgraded to FC 29 and gpmdp stopped working.

**Comment by MarshallOfSound** [comment]
Fixed in master and will be fixed in the next release.  The debug Electron symbols can be found in the Electron releases section on the electron repo
