### ISSUE TITLE
Version 4.6.1 - Double skip issue 

### ISSUE THREAD

**Issue by OppositeToUp** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3519]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:** Windows 10

**GPMDP Version:** 4.6.1

**Issue Descriptions:** When trying to skip forward or backwards it will skip twice when using media keys. I have reinstalled the program and it is still an issue, I have also disabled Razer synapse (As per FAQ), However that just stops the media keys from working at all - Even after trying to map the media keys within your app. 

Edit: They used to work, however I don' know if it was specifically the new update that caused it.

**Steps to Reproduce:** I try to skip a song with media keys.

**Comment by jostrander** [comment]
Hey @OppositeToUp thanks for opening an issue. This is actually already reported here: #2364
