### ISSUE TITLE
Is there a a way to use "audio only" in the youtube music side of app? Would be great.

### ISSUE THREAD

**Issue by pancaketimes** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3521]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**

**GPMDP Version:**

**Issue Descriptions:**

**Steps to Reproduce:**

**Comment by Eeemil** [comment]
@MarshallOfSound why did you close this? I would like "audio only youtube music" but can't seem to find it...

**Comment by tjkirch** [comment]
I'd like to know the plan here too, now that it's clear Google Play Music is starting to shut down in favor of YouTube Music.  (They're disabling all independent music at the end of this month.)

I definitely wouldn't want videos to play, just audio.

I searched around the issues and couldn't find anything that seemed like a duplicate.
