### ISSUE TITLE
API/ Tray Icon shows current song title but artist of previous song, when using Youtube Music.

### ISSUE THREAD

**Issue by Fwank49** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3523]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**
Windows 10 V1809
**GPMDP Version:**
4.6.1
**Issue Descriptions:**
When using Youtube Music, after a song ends, or a song is skipped, in both the tray icon and API (I'm using Cleartext for Rainmeter)  show that the song is by the previous artist. 

eg: If the first song you listen to is "Shake It Off" by Taylor Swift, then the next song is "Teenage Dream" by Katy Perry, but the tray icon and API both show the second song as "Teenage Dream" by Taylor Swift. Then the next song will have the correct title but have Katy Perry as the artist. 

Note: I've noticed that in Youtube Music when you press skip or the song ends, the title updates right away, but the artist takes around 0.25-1 second to update. Maybe if the check for updated song info was delayed by a second or so this would be resolved.
**Steps to Reproduce:**

1. Set GPMDP to Youtube Music mode. 
2. Play a song. 
3. See that the tray icon menu and api-connected apps show the correct artist and title. 
4. Wait for the song to end, or press skip or dislike.
5. See that in the tray icon It shows the correct song title but the artist of the previous song.

**Comment by jostrander** [comment]
This has been reported numerous times before and is fixed in master but not released yet.

**Comment by BananaLoaf** [comment]
> This has been reported numerous times before and is fixed in master but not released yet.

Has it been released yet?
