### ISSUE TITLE
No way to exit on Ubuntu with Gnome Shell

### ISSUE THREAD

**Issue by hackel** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3525]
**Checklist:**

* [×] I have checked that there are no issues with similar or the same content
* [×] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [×] I have double checked and can reproduce the issue

**OS:** Ubuntu 18.10

**GPMDP Version:** 4.6.1 (snap)

**Issue Description:** GPMDP is left running in the background after closing the window.  There is no way that I can find to actually exit the application other than manually killing the parent PID.  Whether closing the window using the native window controls, or right clicking on the dock icon and choosing "Quit," I can see the minimize animation, but the app icon disappears from the dock.  There is no tray icon visible.  I never even tried to log in.

**Steps to Reproduce:**
1. Install GPMDP: `snap install google-play-music-desktop-player`
2. Open GPMDP
3. Try to quit GPMDP

If I run with `XDG_CURRENT_DESKTOP=Unity`, then I get an *invisible* tray icon, and from there I can actually open Desktop Settings and disable "Minimize to Tray".  From this point, future launches (even without changing XDG_CURRENT_DESKTOP) exit successfully.

This is a known, long-standing bug with Electron apps (#3133, electron/electron#10427), so maybe you need some type of work-around for GNOME Shell like I see you're doing for i3 since it seems like this isn't going to be fixed any time soon.

Also note that "Invert Tray Icon Color" has no effect.  Even after a restart, the icon is still invisible.

**Comment by MarshallOfSound** [comment]
This should either be tracked in the Electron issue you linked or you can use the work around detailed in #3133
