### ISSUE TITLE
Chromecast not available with Snap package

### ISSUE THREAD

**Issue by hackel** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3526]
**Checklist:**

* [×] I have checked that there are no issues with similar or the same content
* [×] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [×] I have double checked and can reproduce the issue

**OS:** Ubuntu 18.10

**GPMDP Version:** 4.6.1 (snap)

**Issue Description:** There is no cast icon when running GPMDP.

**Steps to Reproduce:**
1. Install GPMDP.
2. Open GPMDP, log in, play.
3. No cast icon is visible.

I suspect that the snap needs to connect to the avahi-observe and/or avahi-control interfaces.

**Comment by MarshallOfSound** [comment]
I don't officially maintain/support that snap package and I'm beyond unclear on what would be missing / required to make it work.  Happy to accept PRs to fix it but I don't want to leave this one open 👍
