### ISSUE TITLE
Feature Request: Auto Youtube Music

### ISSUE THREAD

**Issue by Dyskal** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3528]
Hey, can you add a possibility to launch automatically youtube music instead of Play Music ? Something like a shortcut or an command line argument.
Thanks !

**Comment by MarshallOfSound** [comment]
@Dyskal GPMDP will remember the last service you used/launched and will automatically use that one the next time you open it.
