### ISSUE TITLE
OSX: accidentally closed window - can't re-open.

### ISSUE THREAD

**Issue by hpeyerl** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3531]
OSX 10.13.6 (High Sierra).   GPMDP: 4.6.1.

Occasionally I will inadvertently press Propellor-W to close a browser tab forgetting that GPMDP is the current application.  So the player window closes but music is still playing and the app responds fine at the menus.  Unrelated issue: I can't get media keys to do anything.

Once the window is closed,  I can't seem to get it to re-open.  Tried activating mini-player and fullsize player and "bring all to front".  My only recourse seems to be to quit and restart which has its own unpleasantries.

**Comment by MarshallOfSound** [comment]
Clicking the GPMDP application on the dock will trigger an `activate` event an focus the main window again.
