### ISSUE TITLE
Crash 4.6.1-1 on opensuse Tumbleweed

### ISSUE THREAD

**Issue by maxxsch28** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3532]
**OS:** openSUSE Tumbleweed

**GPMDP Version:** 4.6.1

**Issue Descriptions:** The app crashes when try to start. On cli says:
`~> google-play-music-desktop-player`
`Violación de segmento ('core' generado)`
I don't known how to get better info about this issue, if you can give me some instruction I'll try to get more info.

**Steps to Reproduce:** Start my computer, try to start GPMDP.

**Comment by davidv171** [comment]
Look through #3391 #3400 . The same issue happens on Ubuntu 18.10 as I had run that as my main distro about 3 weeks ago. So in general, you're going to want to look through CircleCI and download an older version of the binary.

**Comment by maxxsch28** [comment]
@davidv171, thanks! I downloaded the RPM from #3391 and it's works as a charm.
