### ISSUE TITLE
Hotkeys are based on hardware keys

### ISSUE THREAD

**Issue by sfried8** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3533]
**OS:** macOS 10.14.3

**GPMDP Version:** 4.6.1

**Issue Descriptions:** I use a QWERTY keyboard, but I have it mapped to use the Colemak keyboard layout. The 'R' key on my keyboard, for example, types a 'P'. When setting a hotkey with GPMDP, if I press the control key and the 'R' key, the shortcut shows as 'Ctrl+P' as expected. However, pressing the same keys does not trigger the hotkey shortcut. Instead, in order to trigger that shortcut, I need to press the physical 'P' key (which normally functions as the semicolon key). It's a little bit odd that setting the hotkey works as expected but the hotkey is only listening for the hardware keys.

**Steps to Reproduce:** Using a Mac with a keyboard layout different from the physical keyboard:
1) Create a hotkey which should reflect the alternate keyboard layout
2) Save the hotkey
3) Press the same key combination. Observe that the shortcut does not trigger
4) Press the hardware equivalent of the key combination. Observe that the shortcut now triggers

**Comment by MarshallOfSound** [comment]
Please try reproduce this upstream with Electron itself as if this is an issue it will be caused upstream there.
