### ISSUE TITLE
Empty Tray Icon

### ISSUE THREAD

**Issue by MKuranowski** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3534]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content:
  seems silimar to #1057, but that issue is with KDE, I'm running GNOME.
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:** Ubuntu 18.04.2 LTS, AMD64 (Gnome)
**GPMDP Version:** 4.6.1
**Issue Descriptions:** The tray icon is invisible/empty (the underlined tray "icon"
 should show the GPMDP icon)  
![GPMDP-EmptyTrayIcon](https://user-images.githubusercontent.com/16469272/55274687-37438c80-52db-11e9-8ecc-4e71f4c8c724.png)
**Steps to Reproduce:** Install GPMDP, no steps required

To clarify: the "icon" is there, and I can click it, just there's no actual icon.
Disabling Dash to Panel doesn't change anything.

Workoaround described in #3133 and/or reverting the icon tray colors aren't working.

**Comment by Faults** [comment]
Hey, I have the same issue with Ubuntu 19.04 Beta.


![google-music](https://user-images.githubusercontent.com/31610325/55785595-6320f800-5abb-11e9-9e15-c4c0b2abf72d.png)

![app indicators](https://user-images.githubusercontent.com/31610325/55785607-69af6f80-5abb-11e9-9c68-243fe7e5ef8c.png)

**Comment by MKuranowski** [comment]
I found this while messing in syslog:
```
Apr 20 14:42:19 orion gnome-shell[3244]: [AppIndicatorSupport-DEBUG] Registering StatusNotifierItem :1.351/org/ayatana/NotificationItem/Google_Play_Music_Desktop_Player1
Apr 20 14:42:19 orion gnome-shell[3244]: [AppIndicatorSupport-FATAL] unable to lookup icon for Google Play Music Desktop Player1_1
```

**Comment by MarshallOfSound** [comment]
This should be fixed as part of the Electron update rolling through soon
