### ISSUE TITLE
don't run on raspberry pi

### ISSUE THREAD

**Issue by nanzexu** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3537]
pi@raspberrypi:~/electron-quick-start $ npm start

> electron-quick-start@1.0.0 start /home/pi/electron-quick-start
> electron .

/home/pi/electron-quick-start/node_modules/electron/dist/electron: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.27' not found (required by /home/pi/electron-quick-start/node_modules/electron/dist/electron)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-quick-start@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-04-07T16_07_38_351Z-debug.log

**Comment by nanzexu** [comment]
pi@raspberrypi:~/electron-quick-start $ npm start

> electron-quick-start@1.0.0 start /home/pi/electron-quick-start
> electron .

/home/pi/electron-quick-start/node_modules/electron/dist/electron: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.27' not found (required by /home/pi/electron-quick-start/node_modules/electron/dist/electron)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-quick-start@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-04-07T16_07_38_351Z-debug.log

**Comment by jespersh** [comment]
You might need to install `glibc-arm-linux-gnu` package

**Comment by MarshallOfSound** [comment]
The raspberry pi is not an officially support platform here.  Happy for folks to help you out in this thread but this isn't something we can track
