### ISSUE TITLE
Google Music Player Not Playing Any Sound in Windows 10

### ISSUE THREAD

**Issue by SwiftyStorm** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3539]
So in my Google Play Music client, it appears as music is playing, but no sound is being played.
I have checked if I was using the correct audio device both in control panel and in the tray icon.
Audio works everywhere else except in the Google Play Music Client.

**Comment by theinvestigamer** [comment]
This is happening for me too. The app is loading very slowly, album covers wont load, and when I play a song there's no audio

**Comment by MarshallOfSound** [comment]
Ensure that the experimental 5.1 sound option is disabled and that you completely reset your client.  If that doesn't help the incoming Electron update will probably help resolve your issue
