### ISSUE TITLE
Songs wont load

### ISSUE THREAD

**Issue by theinvestigamer** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3544]
OS: Windows 10
Version: Latest (4.6.1)

Logging in is very slow, account in top right corner shows a loading bar continuously, shows my songs but when I try to play them the bar doesn't play and no music comes out. I've uninstalled and reinstalled a half dozen times, tried downgrading to 4.6.0, nothing seems to work. This app worked incredible on my old PC, always loved it. Just upgraded to new Ryzen CPU with new PC build and just simply will not work on this PC

**Comment by theinvestigamer** [comment]
Sadly that doesn't fix the problem, although looking at this "SquirrelSetup" file I'm seeing logs of "500 Internal Server Error" when trying to check for updates or something?

`8 16:44:21> FileDownloader: Downloading url: https://update.gpmdp.xyz/update/win/4.6.1/RELEASES?id=GPMDP_3&localVersion=4.6.1&arch=amd64
2019-04-18 16:44:22> IEnableLogger: Failed to download url: https://update.gpmdp.xyz/update/win/4.6.1/RELEASES?id=GPMDP_3&localVersion=4.6.1&arch=amd64: System.Net.WebException: The remote server returned an error: (500) Internal Server Error.`

**Comment by theinvestigamer** [comment]
Ive tried these suggestions already, still doesn't work even after clearing cash, uninstall/reinstall, trying different internet connection, etc. Any suggestions anyone?

**Comment by theinvestigamer** [comment]
OK I've noticed it continually says "Loading Devices..." if I hover over "Audio Devices" in the GPMDP taskbar icon, and when I look at Desktop settings it doesn't show any audio devices, just "..."

The only audio device I have on this system is NVIDIA audio through my speakers, what could be causing it to hang on that and not load songs?

**Comment by theinvestigamer** [comment]
WELP I went to the Google Music settings in-browser and deleted song recommendations and boom it's fixed now. No idea why that is the case but I'll leave this here for future users in peril.

**Comment by theinvestigamer** [comment]
Was some kind of conflict with the rainmeter plugin, deleted the plugin reinstalled including the rmskin and works now

**Comment by MarshallOfSound** [comment]
If the rainmeter plugin is locking the PlaybackAPI.json file I can see how it would be causing this issue, given removing the plugin fixed the issue I'm going to close this out as an issue with that plugin
