### ISSUE TITLE
Broken Windows Build

### ISSUE THREAD

**Issue by Stanzilla** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3547]
I am sure you are aware but the Windows build has been broken for over a months now, is there anything we can do to help fix it?

**Comment by MarshallOfSound** [comment]
This is one of those "works on my machine" scenarios. It's just CI that is failing for unknown reasons

**Comment by Stanzilla** [comment]
Awesome, thank you :)
