### ISSUE TITLE
Youtube Music: button to switch disappeared after upgrading to 4.6.1

### ISSUE THREAD

**Issue by Moliholy** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3549]
**Checklist:**

* [X] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [X] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [X] I have double checked and can reproduce the issue

**OS:** macOS Mojave (10.14.4)

**GPMDP Version:** 4.6.1

**Issue Descriptions:** After updating from 4.6.0 to 4.6.1 on mac I was unable to use Youtube Music. I managed to fix the issue using the exact same method as [in linux](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/Enabling-YouTube-Music-under-Linux). There was no button to switch between GPMDP and Youtube Music in the UI.

It is also worth mentioning that I was using Youtube Music from the beginning in 4.6.0 and it switched to the GPMDP interface after upgrading.

**Steps to Reproduce:** Update from 4.6.0 to 4.6.1 on mac.

**Comment by jostrander** [comment]
There was never a button to begin with, it was always in the tray icon.

**Comment by magnoleal** [comment]
@jostrander where is? i can't find it.

**Comment by cable729** [comment]
Is it possible to switch to youtube music on a mac? I can't find an option anywhere. Note: I am also running Mojave (10.14.6) and GPMDP 4.6.1. If so, could someone provide a screenshot of where it is? I can then add it to the FAQs. Saying "it's on the tray icon" doesn't help btw. I think I'm clicking the tray icon, but I don't see an option.

**Comment by jostrander** [comment]
Tray Icon in mac is the icon on the application bar at the top of the screen, to the right side. I don't have a mac or I'd send a screenshot.

**Comment by ThisIsIvan** [comment]
Can someone tell me where I can find the button on Windows?

**Comment by jostrander** [comment]
Generally in the lower right hand corner, next to the clock in the tray icon section. Sometimes hidden into the overflow tray (the up arrow). Right click the gpmdp icon and select YouTube Music.

**Comment by jostrander** [comment]
Closing this as invalid, however I recently opened a PR to add a button to the UI #3647
