### ISSUE TITLE
[ubuntu 19.04] YouTube Music: notifications list has Unknown Artist

### ISSUE THREAD

**Issue by cyndre** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3552]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:** Ubuntu 19.04
**GPMDP Version:** 4.6.1
**Issue Descriptions:**
The YouTube Music service does not show the artist of the song in the notifications list. The song in question has its own album and I have Autoplay disabled. This is to minimize potential sources of the issue.
![image](https://user-images.githubusercontent.com/34636882/56778206-c8066e80-679a-11e9-8968-4058c884698b.png)

This is similar to https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3180 in that there is a mismatch/error in the song information but YouTube Music or the notifications list appears to fail to send or retrieve the artist entirely.

Expected behavior (`"service": "google-play-music"`)
![image](https://user-images.githubusercontent.com/34636882/56777845-19156300-6799-11e9-87a5-79a33bb6d170.png)
Actual behavior (`"service": "youtube-music"`)
![image](https://user-images.githubusercontent.com/34636882/56777547-cab39480-6797-11e9-8110-9eef900e5b63.png)

**Steps to Reproduce:**
1. Open GPMDP and play a song from YouTube Music.
2. Open Notifications List (default: Super + V) and check artist.

**Comment by MarshallOfSound** [comment]
Can you try the builds in https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3548

**Comment by cyndre** [comment]
This has been resolved with the supplied build.
![image](https://user-images.githubusercontent.com/34636882/56778756-9347e680-679d-11e9-9f88-14db327a6277.png)
Thank you, I hope to see this build released to the Ubuntu Software app in the near future.

**Comment by cyndre** [comment]
Hmm. After a restart GPMDP does not seem to even create a notification.
![image](https://user-images.githubusercontent.com/34636882/56780701-f8073f00-67a5-11e9-94ba-946c93713a4e.png)

**Comment by Alia5** [comment]
On Windows with the preview build there is also no notification.
Additionaly, the window Title now doesn't only have the Artist from the previous Song, but also the Song Title

**Comment by robbob4** [comment]
This is also a problem in the tooltip for the Tray icon, and in the context menu for the Tray icon: 
![image](https://user-images.githubusercontent.com/3117490/59394640-457b4380-8d35-11e9-8c4b-fc829622426d.png) (Version 4.6.1 on Windows) and isn't just this song from this artist.

**Comment by jostrander** [comment]
Fix incoming, just testing it currently.
