### ISSUE TITLE
After travelling to Belarussia says the service is not available in my country - though it is

### ISSUE THREAD

**Issue by shoguevara** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3554]
**OS: macOS 10.14.4**

**GPMDP Version: 4.6.1 (4.6.1)**

Issue Description: 
I'm living in Russia and YouTube Music is available here. Also I do have Youtube Premium subscription. Till latest I successfully and joyfully (<- this means "Thanks a lot for the job you've done to create this product!") used GPMDP as my default desktop music player.
Not so far ago I traveled to Belorussia for a couple of days, and there I tried to access the service and I got a disclaimer saying just that.
But now I'm in Russia again and the player still says that's it's not accesible in my cauntry and also the disclaimer in Belorussian.
I tried reinstalling the player, but it'd didn't help.
For now I'm looking for any configuration folder which could've cached some network priorities since my trip.
Help is strongly appreciated.

**Steps to Reproduce:
Trip to the country where the service is not available (i.e. virtually via VPN service) and try to listen to some music**
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/3136133/debug_info.zip)
<img width="716" alt="Screenshot 2019-05-02 at 00 43 22" src="https://user-images.githubusercontent.com/7438784/57045171-73209780-6c75-11e9-8b1c-6a2f741db957.png">
<img width="279" alt="Screenshot 2019-05-02 at 00 43 35" src="https://user-images.githubusercontent.com/7438784/57045172-73209780-6c75-11e9-9306-9027b6569556.png">

**Comment by shoguevara** [comment]
After deleting all config and log files using AppCleaner - everything works well again. BUt anyway it is the issue which should be addressed.

**Comment by jespersh** [comment]
Could it have been that you just needed to relog for Google to detect your new location?

**Comment by MarshallOfSound** [comment]
^^ Google caches this stuff, you need to relogin / clear that cache for it to recalculate your location
