### ISSUE TITLE
Missing thumbs down option in Youtube Music mode?

### ISSUE THREAD

**Issue by hildebrau** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3557]
Google Play Music Desktop Player
Version: 4.6.1
I'm in Youtube Music mode (trying it out)

I see no way to thumbs down a song.  Am I just blind?

**Comment by jostrander** [comment]
They are definitely there, unless you can provide a screenshot where they are not. I'm going to close this as unverified.
