### ISSUE TITLE
GPDMP crashing on launch in Fedora

### ISSUE THREAD

**Issue by Cyvain87** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3558]
**OS:**
Fedora Workstation 30

**GPMDP Version:**
4.6.1

**Issue Descriptions:**
Immediate crash on launch
RPM specifies segmentation fault when run via terminal
Flatpak gives missing modules error via terminal

**Steps to Reproduce:**
Install and try to run from flatpak, snap or rpm

**Comment by Cyvain87** [comment]
Update: Doing a completely clean install make it work in the end. Some config files somewhere must have been affecting it.

**Comment by mock** [comment]
@cyvain87: When you say you did a clean install, are you saying you built from source after cleaning out all the old code or did you delete the rpm and install new?

I am having the same Segmentation fault, and I have tried to clean rpm install it. That didn't work. Latest (4.6.1) still faults. I tried to build using npm install, but there are errors when trying to do that.

```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.1.6-300.fc30.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/mock/Projects/github/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/mdns
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
```

Please adivse.
