### ISSUE TITLE
Yubikey Support

### ISSUE THREAD

**Issue by davidkassa** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3559]
**OS:** Windows

**GPMDP Version:** 4.6.1

**Issue Descriptions:** 
Yubikey does not work when authenticating. This is an old issue (#268 #925), but it looks like it is now supported with Electron 4. 

https://github.com/electron/electron/issues/3226#issuecomment-433541540

**Comment by MarshallOfSound** [comment]
If it works in Electron 4 it will work when we update to that version
