### ISSUE TITLE
Uses insecure http for lyrics.wikia.com

### ISSUE THREAD

**Issue by fastcat** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3561]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:** Linux (Debian Buster x86_64)

**GPMDP Version:** Latest CI build as of 2019-05-01

**Issue Descriptions:**
GPMDP uses an insecure `http` connection for loading lyrics from `lyrics.wikia.com`, exposing the name of every track listened to anyone able to sniff the network, _even when the lyrics aren't being displayed_.

AFAICT the requests it issues would work fine over `https`.

Not loading lyrics until they are displayed would be even better.

**Steps to Reproduce:**
* Run GPMDP
* Run wireshark filtered to `port 80`
* Play some music and watch

**Comment by MarshallOfSound** [comment]
Thanks for the report, no idea why it was `http` 🤷‍♂ easy fix
