### ISSUE TITLE
Youtube Music: Skip ads

### ISSUE THREAD

**Issue by GeraldNDA** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3562]
I've seen that it's ad blocking functionality (#2941) is not on the plan however, skipping ads for YT Music is very difficult. This is mostly because you have to open the app window in order to skip the ad. I think it would be useful to either do it automatically (via config) or add a skip ad keyboard shortcut so that you don't have to open the window

**Comment by MarshallOfSound** [comment]
Same answer as #2941 we aren't going to anger the giant, no ad-blocking coming to this player

**Comment by GeraldNDA** [comment]
I don't think I'm asking for ad-blocking ... I want to be able to click "Skip Ad" without opening the window. Having it happen automatically might anger the giant but I feel like a keyboard shortcut should be ok ... just a thought.
