### ISSUE TITLE
Discord Rich Presence : Allow rich presence even if discord game activity is disabled

### ISSUE THREAD

**Issue by Sorok-Dva** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3574]
Hi everyone !

Before starting my suggestion I want to thanks the work and the quality of the desktop player.

I would like to the discord rich presence be improve. Actually it is considered as a game.

![image](https://user-images.githubusercontent.com/15158794/58748132-6bbafc80-8474-11e9-9f51-575975a7b439.png)

But to enable this rich presence we have to allow game activity in discord settings. And I don't use this option (and I don't want to). So is there any luck to improve it like Spotify rich presence as it's considered as a music and not a game

![image](https://user-images.githubusercontent.com/15158794/58748162-b76da600-8474-11e9-830d-13db1d44ff24.png)

In this way I don't have to enable game activity so my games won't appear when I open a game but the rich presence of GPMDP will.

Thanks

**Comment by jostrander** [comment]
Unfortunately the only tie-in we have with Discord is the Game Rich Presense. Spotify and Discord partners to create the Spotify card you see, and we don't have that option because while GPMDP is ours, the underlying GPM service is not. Unfortunately that makes this issue a non-starter. Sorry!
