### ISSUE TITLE
Problem: I carnt find some settings

### ISSUE THREAD

**Issue by josh-65** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3576]
**OS:**
Windows 10 pro - build 1809 vir. 17763.504 - 64 bit

**GPMDP Version:**
4.7.0

**Issue Descriptions:**
Can't find the EQ or the cast feature.

**Comment by jostrander** [comment]
EQ has been disabled for a long time due to a bug with Chromium/Electron which causes only the output device or EQ to be active at once. The cast feature requires your firewall to be open on port 5353 UDP, as far as I recall.
