### ISSUE TITLE
Where to get the latest build artifacts?

### ISSUE THREAD

**Issue by flxfxp** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3578]
I'm looking for the latest OSX artifact.
Supposedly there is an "Assets" tab that I should be able to find when I click on a build at https://circleci.com/gh/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-

However, I do not see this tab. Where can I get the latest build artifacts?

**Comment by jostrander** [comment]
You need to be logged in to see the artifacts tab unfortunately.

**Comment by flxfxp** [comment]
Gotcha! The problem was that I was logged in, but didn't have my email address verified. Hopefully knowing this will help someone in the future :)
