### ISSUE TITLE
Uncaught Exception: SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by AzuuraD** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#358]
**OS:** Windows 10 64-bit

**Issue Descriptions:**  
When installing GPMDP i get the above message

**Steps to Reproduce**:  
Run the windows x64 installer

**Comment by MarshallOfSound** [comment]
Which language is your windows?

**Comment by AzuuraD** [comment]
English

**Comment by MarshallOfSound** [comment]
Is there a stack trace in the message?

**Comment by AzuuraD** [comment]
no, this is the message i get http://i.imgur.com/2wVBxf8.png

**Comment by MarshallOfSound** [comment]
Can you try going through #200 and seeing if that fixes your issue

**Comment by AzuuraD** [comment]
Tried the workaround in that guide (renaming the file in %localappdata%/GPMDP_3/app-3.0.0/ to something simple and running it as an admin) but that didn't work, still getting the same error. also get 2 processes appearing in task manager

**Comment by MarshallOfSound** [comment]
Can you try running the development version so we can get an actual stack trace?

**Comment by AzuuraD** [comment]
Can you link me to the development version. not a programmer myself and i'm new to git

**Comment by MarshallOfSound** [comment]
You are literally on the repository :+1: 

Just follow the development steps in the readme

**Comment by AzuuraD** [comment]
Getting the exact same thing when going through the development version, no stack trace either

http://i.imgur.com/4Sna5s0.png

**Comment by AzuuraD** [comment]
Weird thing is it was working fine, then i had a driver failure while updatiing my video drivers and windows wouldn't start, after removing them in safe mode and re-booting then re-installing the video drivers and restarting, the app stopped working

**Comment by MarshallOfSound** [comment]
Sounds like your graphics is screwed :100: 

Not much I can do about it if you think the graphics is the problem

Try asking for help over at `atom/electron`
