### ISSUE TITLE
Discord Rich Presence is wonky

### ISSUE THREAD

**Issue by somebirby** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3580]
**OS:**
Windows 10 x64
**GPMDP Version:**
4.6.0
**Issue Descriptions:**
Discord Rich Presence haven't been working great more me ever since it's implementation.
It often gets stuck between tracks, or sometimes doesn't start at all.
Got a friend also using this feature, with the same issues.

Is this a known thing? Got weirded out when I came here and say nothing about it (expect issue#3262 last year).

**Comment by Leozn17** [comment]
I have faced the same problem a few days ago, but I believe the team is already working on a solution.

**Comment by alexfonseka** [comment]
It breaks for me if I update Discord while GPMDP is running in the background. A quick restart always fixes things though.

**Comment by Alipoodle** [comment]
This issue has to do with GPMDP not hooking onto Discord's RPC connection after it has failed once.
It will only check if it can hook onto Discord's RPC connection on Start up. if Discord doesn't exist then don't do anything.
On stuff like Updates for Discord, GPMDP will disconnect from RPC and not reconnect afterwards.

**Comment by eVen-gits** [comment]
On linux, it seems to be stuck on the same song that was played during setup of the module.

**Comment by krazyito65** [comment]
does not work for me on ubuntu 19 using the debian build 4.7.1

**Comment by darkvertex** [comment]
Does not work for me either. I'm on Ubuntu 16.04 debian build 4.7.1

**Comment by darkvertex** [comment]
So I found out recently that the "snap" version does not allow the Discord rich presence communication, but the non-snap Linux build actually works.
