### ISSUE TITLE
Youtube Music mode does not have Downloads (PC / Desktop)

### ISSUE THREAD

**Issue by explodoboy** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3582]
I cannot seem to find a download feature for the Youtube Music setting, despite me already having a Youtube Premium (bundled with Youtube Music) membership. Is this just not added yet, or something else? My computer is running windows 10 if anyone is curious.

**Comment by jostrander** [comment]
I don't think Youtube Music will have a download feature, ever, since you can't upload your own music to it. However that is my outside opinion on the topic. You'd have to check Google's product forums for this kind of request.
