### ISSUE TITLE
Flat Black/White Menubar Icon for OS X

### ISSUE THREAD

**Issue by mdellabitta** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#359]
All my menubar icons are monochrome except for this app (see attached).
<img width="706" alt="screenshot 2016-03-07 20 39 04" src="https://cloud.githubusercontent.com/assets/925372/13589286/c33ed954-e4a4-11e5-918e-dcd091e9b8c8.png">

I know this is a small issue, but I figured I'd ask at least.

**Comment by MarshallOfSound** [comment]
It's been fixed :+1: 

We now have a template black/white icon
