### ISSUE TITLE
Missing fonts for CJK chars in YT Music

### ISSUE THREAD

**Issue by MKuranowski** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3594]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:** Ubuntu 18.04

**GPMDP Version:** 4.6.1

**Issue Descriptions:** The YT Music flavor of GPMDP is missing fonts for CJK chars.

**Steps to Reproduce:** Switch to YT Music, try to search for:
- 방탄소년단
- 剣士米酢
- まふまふ

![image](https://user-images.githubusercontent.com/16469272/60167893-49fb2e00-9804-11e9-8385-4692516baeb6.png)

**Comment by jostrander** [comment]
Is this an issue in the browser as well?

**Comment by MKuranowski** [comment]
No, Google Chrome works fine
![image](https://user-images.githubusercontent.com/16469272/64479382-bc01d300-d1b6-11e9-95ea-b2b5d13ac9c7.png)

**Comment by jostrander** [comment]
Hmm. It may already be fixed in master, or something else may be happening here.

![image](https://user-images.githubusercontent.com/760989/64479544-a8d70f00-d186-11e9-899b-a06b5db34ed5.png)

Also on ubuntu 18.0.4.2 myself.

**Comment by MKuranowski** [comment]
Unfortunately, I can't get GPMDP to build (an issue with babel-register and gulp build).  
I would like to say that if everything works in master, then it should be fine in the next release — but considering that 4.6.1 was released over a year ago, it might not ber able to prove it in a timely fashion.

**Comment by MKuranowski** [comment]
Nevermind, got it.  
Confirmed, everything looks fine when building from `master`.
