### ISSUE TITLE
Mini player - Persistent Title and Controls

### ISSUE THREAD

**Issue by DecoyJoe** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#36]
Is it possible to have a setting to keep the Mini player's song info and controls always visible rather than just on a mouse over? Sometimes I like to recall what song is currently playing but having to mouse over the mini player after I focus it is an annoying extra step, especially if I just use alt-tab to switch focus.

Great work by the way!

**Comment by MarshallOfSound** [comment]
Simple enough, will work on for next release
