### ISSUE TITLE
Change clicking on taskbar icon to open the player window instead of a menu. [OSX]

### ISSUE THREAD

**Issue by yamz66** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#360]
I keep clicking on it hoping it will open the play window rather than making me click on the icon and then clicking show. after I get it set up I won't need quick access to Settings anymore, and almost never will I need to change the audio output.

**Comment by MarshallOfSound** [comment]
I think this is a limitation of OSX, you can't have a context menu and have a separate onclick action.  I will look into it though :+1:

**Comment by MarshallOfSound** [comment]
Oops

**Comment by MightyPork** [comment]
I tried to do this in #297, was told it's not possible on OSX. 
So it's now only for Linux - well, when it's finally merged.

If it turns out to be possible, we should totally have it!

**Comment by MarshallOfSound** [comment]
Closing due to #297 merging.

No other app on OSX (that I can think of) activates upon single click of the tray icon.

Skype -> Context menu
System Tools (Wifi, Bluetooth) -> Context Menu
Chrome -> Context Menu

Etc...

**Comment by yamz66** [comment]
The Twitter Mac app has this as an option in the settings to either show the context menu or open the app: https://www.dropbox.com/s/2dvfha2519c278x/Screenshot%202016-03-09%2009.06.44.png?dl=0

**Comment by MarshallOfSound** [comment]
1. You can upload screenshots straight to github :+1: 
2. Interesting, but there is no way to have both.  I.e. Left click toggle app, right click show context menu?

There always needs to be a way to get to the context menu and on mac it looks like you can't do both

**Comment by yamz66** [comment]
1. (I'm a github n00b)
2. No, it's one or the other. But I feel I would more frequently need to just open the app than the context menu. And everything in the context menu is still accessible via just opening the Settings window from within the app.

**Comment by MarshallOfSound** [comment]
Yes, but the reasoning people are giving to make the icon instantly show the app is to make it one click less...

But you think its reasonable to make the user click the icon, click the 3 bars to open the side nav, scroll down to desktop settings, click the desktop settings button, click on the "Audio" tab, click on the dropdown, click on the one they want and then close the desktop settings window.  Instead of just clicking on the icon and choosing from the context menu?

It's a lot to lose for a little to gain.  Also the core "show" button kind of relies on the context menu :+1:

**Comment by yamz66** [comment]
I guess that depends on how frequently people are changing the audio settings. I personally would set it once (or never since the default is correct) and never touch it again.

Also, those settings are quicker accessible by clicking on the App name in the menu bar and clicking "Preferences" or even quicker, but hitting ⌘, which automatically opens that same window.

**Comment by MarshallOfSound** [comment]
But the fact that we can't speak for all users and their habits / usage styles (I personally change audio output quite frequently as my headset is USB audio but my speakers are 3.5mm) means that we have to take the best compromise.  Which in this case is the quickest usage for each action.  One extra click for one method (show) and no extra clicks for any other method.

It has the least possible impact on the user regardless of how they use the app

**Comment by yamz66** [comment]
Fair enough. It's your app so you get to be boss. It's still miles better than any other solution I've seen out there. Thanks for the replies! :)
