### ISSUE TITLE
Unable To Exit GPMDP (Chrome OS Linux Container)

### ISSUE THREAD

**Issue by sammypanda** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3600]
**OS:** Chrome OS

**GPMDP Version:** 4.6.1

**Issue Descriptions:** The application does not shut down when exited

**Steps to Reproduce:** 
1. Boot Chrome OS
2. Set Up Linux VM
3. Download GPMDP
4. Start GPMDP
5. Attempt To Exit GPMDP

**Comment by jostrander** [comment]
This is fairly specific, and we don't really support Chrome OS directly. What install method are you using?

**Comment by Samdvich** [comment]
> This is fairly specific, and we don't really support Chrome OS directly. What install method are you using?

The Debian package found on the website, 64-bit version.

**Comment by jostrander** [comment]
I'm not sure specifically why it would be broken. Try launching from terminal and see if you get anything besides the avahi warnings when you try to close.

**Comment by Samdvich** [comment]
The issue should be renamed (or closed and opened as a separate issue) to something along the lines of "**Can't access tray functions on Chrome OS**", the application can exit now from the collapsible menu on Chrome OS after a reinstall. 

Also, since you can't access the tray functions, it means (if the tray is the only place you're able to do it) you can't swap to YT Music

**Comment by jostrander** [comment]
I see the circumstance you are describing is troublesome. Unfortunately this project doesn't specifically support Chrome OS at the moment. I assume the setting you had to change was minimize to tray on close? We could possible force this option as disabled on Chrome OS given the right information to narrow down the running environment.

Also, feel free to open a new issue to have an option to switch between services outside of the tray.

**Comment by Patricol** [comment]
I've also had this problem in Arch Linux; for about as long as this issue has existed. (suggesting a regression)

When trying to exit; nothing prints to stdout/stderr.

To reproduce in a docker container:
- `sudo docker --rm -it -e RDP_OR_VNC="VNC" -e PASSWORD="desired_vnc_password" -p 5900:5900 patricol/gui_base:arch`
- Use VNC and desired_vnc_password to connect.
- Click the terminal icon to open a terminal.
- `yay -Syu --answerdiff None --noconfirm gpmdp`
- `gpmdp`
- Then attempt to close the window by:
  - middle-clicking its title (the text in the center of the top bar on the screen) or typing `Alt+Shift+Q`, when gpmdp is the active (outlined in white) window.
  - using gpmdp's hotkey `Ctrl+Q`
  - tapping `Alt` and manually choosing `Close` in gpmdp's menu.

**Comment by sammypanda** [comment]
inactive
