### ISSUE TITLE
Ubuntu 18.04.02 on X, cannot move the window after minimize/restore

### ISSUE THREAD

**Issue by sirber** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3601]
**Checklist:**

* [/] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [/] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [/] I have double checked and can reproduce the issue

**OS:**
Ubuntu 18.04.2 LTS x64 on X session
**GPMDP Version:**
4.6.2
**Issue Descriptions:**
can move the window after minimize / restore 
**Steps to Reproduce:**
- launch
- minimize window
- restore it
- cant move it, must quit and relaunch

**Comment by jostrander** [comment]
I can't reproduce this on Gnome X on 18.04.2. Do you have native window borders enabled or disabled?

**Comment by sirber** [comment]
tried both, same issue

**Comment by jostrander** [comment]
If anyone else chimes in with this problem I may be able to hopefully get enough details to troubleshoot, but until then I can't confirm it's an issue.

**Comment by sirber** [comment]
I currently cannot test, the app don't launch in ubuntu running hyper-v. wil try at work tomorrow

**Comment by sirber** [comment]
Could not reproduce the issue with Ubuntu 18.04 using XOrg and latest Nvidia drivers.
