### ISSUE TITLE
Mouse don't display for scale 300% for large screen

### ISSUE THREAD

**Issue by xidoc** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3603]
Hi !
The mouse don't display for scale for large screen.

I have Ubuntu on a smart TV, and the mouse is very small.

**Comment by jostrander** [comment]
I'm not sure that this falls within the scope. The mouse is usually handled at the OS level for scaling. I've marked this as no fix unless there's something reasonable we can do here.
