### ISSUE TITLE
Certificate date issue on main site

### ISSUE THREAD

**Issue by longtomjr** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3604]
Good day.

The certificate on the site does not return valid. 
FF: ```Firefox Developer Edition detected an issue and did not continue to www.googleplaymusicdesktopplayer.com. The website is either misconfigured or your computer clock is set to the wrong time.```

Chrome  `NET::ERR_CERT_DATE_INVALID`

@MarshallOfSound 

Kind Regards

**Comment by MarshallOfSound** [comment]
Fixed
