### ISSUE TITLE
Uploads songs

### ISSUE THREAD

**Issue by emudojo** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3607]
Currently I dn't see an option to upload music

![image](https://user-images.githubusercontent.com/445995/63528835-e4a08200-c4c0-11e9-9217-dfc8df0b1c47.png)

is this intended behavior, or actually somethng thath can only be done from the official chrokme plugin ?

**Comment by jostrander** [comment]
It can only be done with Chrome
