### ISSUE TITLE
Failing to build

### ISSUE THREAD

**Issue by SolarAquarion** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3611]
3/4] Linking dependencies...
warning "discord-rich-presence > discord-rpc@3.0.2" has unmet peer dependency "register-scheme@github:devsnek/node-register-scheme".
warning " > material-ui@0.15.4" has incorrect peer dependency "react-tap-event-plugin@^1.0.0".
[4/4] Rebuilding all packages...
[1/12] ⢀ mdns
[2/12] ⢀ runas
[8/12] ⢀ electron-chromedriver
[4/12] ⢀ electron
error /home/solaraquarion/build/gpmdp-git/src/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/gpmdp-electron-winstaller: Command failed.
Exit code: 1
Command: node lib/fetch-vendor.js
Arguments: 
Directory: /home/solaraquarion/build/gpmdp-git/src/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/gpmdp-electron-winstaller
Output:
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/home/solaraquarion/build/gpmdp-git/src/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/home/solaraquarion/build/gpmdp-git/src/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/home/solaraquarion/build/gpmdp-git/src/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/unzip/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)

warning Error running install script for optional dependency: "/home/solaraquarion/build/gpmdp-git/src/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/mouse-forward-back: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/solaraquarion/build/gpmdp-git/src/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/mouse-forward-back
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.2
gyp info using node@12.9.0 | linux | x64
gyp info find Python using Python version 2.7.16 found at \"/usr/bin/python2.7\"
gyp info spawn /usr/bin/python2.7
gyp info spawn args [
gyp info spawn args   '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/solaraquarion/build/gpmdp-git/src/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/mouse-forward-back/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/solaraquarion/.cache/node-gyp/12.9.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/solaraquarion/.cache/node-gyp/12.9.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/solaraquarion/.cache/node-gyp/12.9.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/solaraquarion/build/gpmdp-git/src/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/mouse-forward-back',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/solaraquarion/build/gpmdp-git/src/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/mouse-forward-back/build'
  CXX(target) Release/obj.target/mouse-forward-back/mouse-forward-back.o
In file included from ../mouse-forward-back.cc:1:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2298:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
 2298 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
../mouse-forward-back.cc: In function ‘void events_callback(uv_async_t*)’:
../mouse-forward-back.cc:61:63: error: no matching function for call to ‘v8::Function::Call(v8::Local<v8::Object>, const unsigned int&, v8::Local<v8::Value> [1])’
   61 |     f->Call(isolate->GetCurrentContext()->Global(), argc, argv);
      |                                                               ^
In file included from /home/solaraquarion/.cache/node-gyp/12.9.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../mouse-forward-back.cc:1:
/home/solaraquarion/.cache/node-gyp/12.9.0/include/node/v8.h:4161:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*)’
 4161 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Call(Local<Context> context,
      |                                           ^~~~
/home/solaraquarion/.cache/node-gyp/12.9.0/include/node/v8.h:4161:43: note:   candidate expects 4 arguments, 3 provided
../mouse-forward-back.cc: In function ‘void RunCallback(const v8::FunctionCallbackInfo<v8::Value>&)’:
../mouse-forward-back.cc:77:5: error: ‘Handle’ was not declared in this scope
   77 |     Handle<Function> cb = Handle<Function>::Cast(args[0]);
      |     ^~~~~~
../mouse-forward-back.cc:77:20: error: expected primary-expression before ‘>’ token
   77 |     Handle<Function> cb = Handle<Function>::Cast(args[0]);
      |                    ^
../mouse-forward-back.cc:77:22: error: ‘cb’ was not declared in this scope
   77 |     Handle<Function> cb = Handle<Function>::Cast(args[0]);
      |                      ^~
../mouse-forward-back.cc:77:42: error: expected primary-expression before ‘>’ token
   77 |     Handle<Function> cb = Handle<Function>::Cast(args[0]);
      |                                          ^
../mouse-forward-back.cc:77:45: error: ‘::Cast’ has not been declared
   77 |     Handle<Function> cb = Handle<Function>::Cast(args[0]);
      |                                             ^~~~
In file included from ../../nan/nan.h:54,
                 from ../mouse-forward-back.cc:1:
../mouse-forward-back.cc: At global scope:
/home/solaraquarion/.cache/node-gyp/12.9.0/include/node/node.h:556:43: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  556 |       (node::addon_register_func) (regfunc),                          \\\n      |                                           ^
/home/solaraquarion/.cache/node-gyp/12.9.0/include/node/node.h:590:3: note: in expansion of macro ‘NODE_MODULE_X’
  590 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../mouse-forward-back.cc:101:1: note: in expansion of macro ‘NODE_MODULE’
  101 | NODE_MODULE(mouse, init)
      | ^~~~~~~~~~~
In file included from /home/solaraquarion/.cache/node-gyp/12.9.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../mouse-forward-back.cc:1:
/home/solaraquarion/.cache/node-gyp/12.9.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/home/solaraquarion/.cache/node-gyp/12.9.0/include/node/node_object_wrap.h:84:78:   required from here
/home/solaraquarion/.cache/node-gyp/12.9.0/include/node/v8.h:9893:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
 9893 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/solaraquarion/.cache/node-gyp/12.9.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../nan/nan_object_wrap.h:65:61:   required from here
/home/solaraquarion/.cache/node-gyp/12.9.0/include/node/v8.h:9893:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
make: *** [mouse-forward-back.target.mk:105: Release/obj.target/mouse-forward-back/mouse-forward-back.o] Error 1
make: Leaving directory '/home/solaraquarion/build/gpmdp-git/src/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/mouse-forward-back/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:190:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.2.9-zen1-1-zen
gyp ERR! command \"/usr/bin/node\" \"/usr/bin/node-gyp\" \"rebuild\"
gyp ERR! cwd /home/solaraquarion/build/gpmdp-git/src/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/mouse-forward-back
gyp ERR! node -v v12.9.0
gyp ERR! node-gyp -v v5.0.2
gyp ERR! not ok"

**Comment by jostrander** [comment]
@SolarAquarion I would open a new issue for that, with specific details of what you may be using and what git hash you built from. Be sure to use the issue template. Closing this as I've offered a solution for the build problem.

**Comment by ngseer** [comment]
> Node v12 doesn't compile with the version of electron in the app, as well as most of the modules. I believe the latest that will work is either 8 or 10.

Sorry for leaving that on the closed issue.
FWIW, I was able to build the app from master with Node 11.15.0 on Linux and OS X just fine so it seems that only 12.* is affected.

@jostrander how about adding this info to the Readme? Now it's not really clear for those who are going to build it.
