### ISSUE TITLE
Google wont let me sign in, says app or browser unsafe

### ISSUE THREAD

**Issue by molldoll354** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3613]
**Checklist:**

* [ x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [ x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [ x] I have double checked and can reproduce the issue

**OS:**
Windows
**GPMDP Version:**
4.6.1
**Issue Descriptions:**
Google wont let me sign in, any attempt to sign in is met with the same error saying the browser or app I'm trying to use won't "keep my account safe" and refuses to let me log in. I've adjusted all my Google security settings and it still won't allow me to log in
**Steps to Reproduce:**
Open app, put in log in info, get error.

**Comment by MarshallOfSound** [comment]
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3545
