### ISSUE TITLE
Google Play Music restarts when selected from Service list in tray

### ISSUE THREAD

**Issue by spencermathews** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3614]
**OS:**
macOS Mojave 10.14.6

**GPMDP Version:**
4.6.1

**Issue Descriptions:**
When I am already listening to GPMDP and the window is in any state (open, minimized, or minimized to tray, or mini) and I select Google Play Music from the Service menu from the Tray icon the desktop player is restarted and any music currently playing is abruptly cut off. The expected behavior would be that if Google Play Music is already active then selecting it from the Service list would simply bring the active window back into focus, as per Show.

I see several (not mutually exclusive) solutions for this confusing behavior:

1) Move the Service section of the Tray menu down toward the bottom so users are less likely to choose it, since the other items are presumably more common actions.

2) Implement the expected behavior mentioned above, i.e. don't restart Google Play Music if it is already active. It would probably be nice to offer some confirmation about switching service too, especially if the current one is actively playing. I'll also note my queue is wiped out when restarted. It would be great to have some preservation of state between service switches, if not between between restarts of GPMDP itself.

**Steps to Reproduce:**
See above.

**Comment by jostrander** [comment]
PR awaiting approval.
