### ISSUE TITLE
Login not authorized

### ISSUE THREAD

**Issue by aviputri** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3615]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there

**OS:** Mac

**GPMDP Version:** V4.6.1

**Issue Descriptions:** After I login with my username+password, this message appears:

> You are trying to sign in from a browser or app that doesn't allow us to keep your account secure.
> 
> Try using a different browser.

I found out [here](https://support.google.com/accounts/answer/7675428?hl=en-GB) that Google only authorizes login on the following browsers:

> **Sign in with a supported browser**
> To help protect your account, Google doesn’t let you sign in from some browsers. Google might stop sign-ins from browsers that:
> - Don’t support JavaScript or have Javascript turned off.
> - Have unsecure or unsupported extensions added.
> - Use automation testing frameworks.
> - Are embedded in a different application.
> 
> **1. Use a supported browser**
> These and other browsers support JavaScript:
> - Chrome
> - Safari
> - Firefox
> - Opera
> - Internet Explorer
> - Edge

I couldn't find the solution to this issue. I read some people were prompted to give security tokens and such but in my case, nothing can be done after I receive the login message.

**Comment by MarshallOfSound** [comment]
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3545
