### ISSUE TITLE
Google Authentication Failure

### ISSUE THREAD

**Issue by coherent-software** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3616]
![Capture](https://user-images.githubusercontent.com/54870925/64215671-b29d0180-ce6a-11e9-9f79-cb03a9bcf1a5.PNG)

I don't believe anything has changed recently with my google account. I had the player installed about a month ago with no authentication issue.

Let me know if I can provide any other info.

Thanks,
Ryan

**Comment by MarshallOfSound** [comment]
Duplicate https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3545

**Comment by coherent-software** [comment]
Yeah I found that issue after creating this.
Fast fix: install from this link:
https://ci.appveyor.com/project/MarshallOfSound/google-play-music-desktop-player-unofficial/branch/master/artifacts

**Comment by Mushy-Snugglebites-badonkadonk** [comment]
Why the cross-site link? How do we know it's legit?

**Comment by jespersh** [comment]
@Mushy-Snugglebites-badonkadonk  
> Why the cross-site link? How do we know it's legit?

You can find the same link here in the readme https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#continuous-integration

**Comment by Mushy-Snugglebites-badonkadonk** [comment]
> @Mushy-Snugglebites-badonkadonk
> 
> > Why the cross-site link? How do we know it's legit?
> 
> You can find the same link here in the readme https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#continuous-integration

I see said the blind man. Thank you so much for posting this. I wouldn't have put 2 + 2 together without your tidbit. 

@coherent-software Forgive me! Disregard my previous post.
