### ISSUE TITLE
[Feature] Audio only in youtube music services?

### ISSUE THREAD

**Issue by linux858** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3620]
Hello Samuel 

Is there a way to make youtube music service play only audio and not showing videos in music player?

Thanks

**Comment by jostrander** [comment]
YouTube heavily relies on the video tag for playback, instead of the audio tag like in GPM. I'm not sure something like this is feasible. You could hide the video element with CSS if that's your concern, but switching the underlying audio source out isn't possible.

**Comment by jostrander** [comment]
Recently dove into the code, and this is likely _really_ no possible.
