### ISSUE TITLE
Media Keys and Hotkeys don't Work in YouTube Music on GPMDP v4.7.0 on Windows 10

### ISSUE THREAD

**Issue by Fwank49** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3625]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**
windows 10
**GPMDP Version:**
4.7.0
**Issue Descriptions:**
Media keys and custom hotkeys don't work in youtube music. They do nothing when pressed. They work in 4.6.1 or in 4.7.0 in google play music
**Steps to Reproduce:**
open GPMDP 4.7.0, switch to youtube music, start playing something. Try to use your media keys (play/pause/skip etc) or even the system tray controls. See that they don't do anything.

**Comment by jostrander** [comment]
This should be, and might already be reported on that issue. Closing this as a duplicate, because every native module appears to be broken in the 4.7.0 unrelease.
