### ISSUE TITLE
Accessibility of Youtube Music mode

### ISSUE THREAD

**Issue by gsunit** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3627]
It was very difficult to find the option to switch to Youtube Music in Ubuntu 18.04. I searched through the whole application, only to later find it in a dropdown in the newly appeared icon besides the accesibility icon on the Ubuntu Topbar. It would be better to also have a button to swtich to YT Music inside the application itself.

**Comment by nbicalcarata** [comment]
Currently in Fedora 30 there's no system tray, so i am unable to switch to Youtube Music
