### ISSUE TITLE
Website certificate expired on 2019-10-02

### ISSUE THREAD

**Issue by sk33z3r** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3639]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**Issue Descriptions:**
SSL certificate is expired for 5 days on the website

**Steps to Reproduce:**
1. Go to https://www.googleplaymusicdesktopplayer.com
2. Observe

Security warning is presented, and checking the certificate confirms it is expired.

![image](https://user-images.githubusercontent.com/20587571/66344799-aea64880-e91c-11e9-9a1b-befe9d1da61a.png)

It appears this happens quite often considering the previous issues submitted in this tracker. You can avoid this by automating the certificate renewal and also restarting the HTTP server every time.

https://certbot.eff.org/docs/using.html?highlight=renew#automated-renewals

**Comment by dobesv** [comment]
Looks like this has been fixed.

**Comment by 1legality** [comment]
Certificate expired again this morning...
