### ISSUE TITLE
Authentication hangs when google sends the verification code text message.

### ISSUE THREAD

**Issue by charnode** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#364]
**OS:**
Linux Mint 17.3

**Issue Descriptions:**
The app hangs after entering the password. I never get a chance to enter the verification code. Resizing of the window then paints a black cross over the application.

**Steps to Reproduce:**
1) Open App
2) Klick "Login" ("Anmelden")
3) Enter username
4) Enter password
5) Hang
6) Resize to have a black cross painted over the applications content.

**Comment by jostrander** [comment]
Try using the disable-gpu flag:

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ#i-am-part-of-the-glorious-linux-master-race-and-it-doesnt-go-past-the-sign-in-screen

**Comment by MarshallOfSound** [comment]
@jostrander Is correct

Also I didn't put that Issue Template and the FAQ up for nothing, please use them
