### ISSUE TITLE
Loading Music Library

### ISSUE THREAD

**Issue by Hareuhal** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3649]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content
I've searched through everything.
  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:** Windows 10

**GPMDP Version:** 4.6.1

**Issue Descriptions:** Stuck on loading music library, it happened randomly.

**Steps to Reproduce:** Open the app and try to sign in.

I've tried deleting everything related to GPMDP in %APPDATA% as well as %LOCALAPPDATA%. I've uninstalled, redownloaded and reinstalled multiple times.

One thing I noticed is when I right click on the tray icon > Audio Devices > it says "Loading Devices..." although I'm not sure if it's always said that?

I looked through old issues about audio devices and didn't find solutions - only comments about people having theirs saying "Loading Devices" and that it was going to be fixed in an upcoming release.

Thanks for your assistance.

**Comment by Vendrean** [comment]
Hi there. 
I am having the same issue. 
Every time I start the Desktop Player, it's stuck on loading the library. 
Deleted user files already and Google play music works fine in browser or via Station (another service for grabbing the play music service from the internet,)

**Comment by eythian** [comment]
Double check the first of your checklist :)

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3640

**Comment by Hareuhal** [comment]
I'm not sure how I missed that through all my searching, but this solution isn't working for me. I've tried opening the file in 7zip (and winrar) and get an error.

![image](https://user-images.githubusercontent.com/20357652/67574452-79656d00-f708-11e9-93fd-ba0fc5b8d43c.png)

**Comment by eythian** [comment]
I had the same thing with 7zip, I think it's a special form that needs a plugin. In the end I used the zip version on the other issue.

**Comment by neptunecentury** [comment]
I noticed this issue today. I restarted my PC and when I opened the app, it's stuck on loading library. I tried reinstalling the app and that didn't work either.

If I switch the service to YouTube music, it loads. (Right click on tray icon)
![image](https://user-images.githubusercontent.com/3356091/67578840-4d9ab500-f711-11e9-8c1a-3a33a1bf802c.png)

**Comment by Hareuhal** [comment]
> 
> 
> I had the same thing with 7zip, I think it's a special form that needs a plugin. In the end I used the zip version on the other issue.

I tried using the zipped one someone else provided and got errors when I launched GPMDP. Wouldn't even launch. :(

**Comment by Hareuhal** [comment]
> 
> 
> I noticed this issue today. I restarted my PC and when I opened the app, it's stuck on loading library. I tried reinstalling the app and that didn't work either.
> 
> If I switch the service to YouTube music, it loads. (Right click on tray icon)
> ![image](https://user-images.githubusercontent.com/3356091/67578840-4d9ab500-f711-11e9-8c1a-3a33a1bf802c.png)

This solves it for me, except for the awful YT Music UI. Maybe now is the time to just get used to it before they kill off Google Music?

**Comment by MikeKing67** [comment]
> I noticed this issue today. I restarted my PC and when I opened the app, it's stuck on loading library. I tried reinstalling the app and that didn't work either.
> 
> If I switch the service to YouTube music, it loads. (Right click on tray icon)
> ![image](https://user-images.githubusercontent.com/3356091/67578840-4d9ab500-f711-11e9-8c1a-3a33a1bf802c.png)

I am having the same issue.  Google Play Music will not load.  I can open YouTube Music, but then I don't have all the content and play lists I created in Google Play Music.

**Comment by dobesv** [comment]
See https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3640

**Comment by Hareuhal** [comment]
> 
> 
> See #3640

Been there, didn't help.

**Comment by jostrander** [comment]
Closing in favor of #3640. Please discuss there.

**Comment by MikeKing67** [comment]
> See #3640

I looked through #3640 and copied the app.asar zip file that [crayfishuk](https://github.com/crayfishuk) posted in that thread and it resolved my issue.

Thanks for the hlep

**Comment by Hareuhal** [comment]
> 
> 
> > See #3640
> 
> I looked through #3640 and copied the app.asar zip file that [crayfishuk](https://github.com/crayfishuk) posted in that thread and it resolved my issue.
> 
> Thanks for the hlep

I tried copying that file and it didn't help me at all unfortunately.

**Comment by doomcreeper** [comment]
Will there be a working program for windows 10 to install and use?
