### ISSUE TITLE
No Chromecast button

### ISSUE THREAD

**Issue by bjb1959** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3650]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS: Ubuntu 19.10**

**GPMDP Version: 4.6.1**

**Issue Descriptions: No Chromecast Button**

**Steps to Reproduce:**
Start the google desktop player installed from the google music desktop player snap for ubuntu 19.10 and it does not have a chromecast button on the bottom but the chrome web player does.

**Comment by jostrander** [comment]
Chromecast requires `libavahi-compat-libdnssd`. Unfortunately its not bundled with this application so it has to be installed separately.

**Comment by bjb1959** [comment]
libavahi-compat-libdnssd1 is installed but still no button

**Comment by bjb1959** [comment]
also, this is a snap so shouldn't all the libraries I need be included?

**Comment by bjb1959** [comment]
Here is a screenshot
[image: image.png]

**Comment by jostrander** [comment]
That would be a better question for @RAOF, however I looked at the snap config and it appears to have required avahi so that should be good. Do you have a strict firewall? I know that avahi needs port 5353 UDP open in order to function.

**Comment by bjb1959** [comment]
I don't specifically have firewall software set up. I use a mesh wifi which
acts as a firewall and have certain ports open for some software I use.
however, the web player on google play works has the chromecast button and
the desktop player I used in Ubuntu 19.04 which I installed from a PPA
worked as it should. it is only with Ubuntu 19.10 that it doesn't have
chromecast ability. I supposed I could try building it from source to see
if it changes anything but since the web player works I don't know if I
want to go through all of that.

**Comment by bjb1959** [comment]
the flatpak works as it should so the issue is in the deb package and the
snap package. I will use the flatpak version

**Comment by RAOF** [comment]
Hm. The snap probably needs the `avahi-observe` interface in order to actually see the Chromecast. I can make that happen!

**Comment by bjb1959** [comment]
Thanks for all the effort. let me know if I can help by testing anything

**Comment by RAOF** [comment]
I shall push a build that *should* fix this to the `edge` channel tomorrow. I'll update this bug with testing instructions then.

**Comment by RAOF** [comment]
GPMDP v4.6.1-61-gaa96c2a, which I *think* should fix the Chromecast issue, is now available in the snapcraft `edge` channel.
`snap refresh --edge google-play-music-desktop-player` should install the candidate package. Please note that the desktop file icon is broken in this build; I'll fix that before pushing to `stable`.
