### ISSUE TITLE
Won't run on Manjaro after latest updates

### ISSUE THREAD

**Issue by matrixhalpia** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3652]
I have four different laptops all running Manjaro. After updating this week of 10/28/2019, GPMDP will not run on any of them. It was already installed and working fine on all of them.

**Comment by MarshallOfSound** [comment]
Fixed in master

**Comment by de-don** [comment]
When will the release with the fix?
