### ISSUE TITLE
Pock does not show correct song on YTM

### ISSUE THREAD

**Issue by erasmuswill** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3658]
**Checklist:**

* [X] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [X] I have double checked and can reproduce the issue

**OS:**
MacOS
**GPMDP Version:**
4.6.1
**Issue Descriptions:**
When using Pock (a touchbar dock) the Now Playing song name does not update. When using GPM it updates but not with YTM.
**Steps to Reproduce:**
Install Pock and add the Now Playing widget. Try to play music and skip a song on YTM.

**Comment by jostrander** [comment]
I'm thinking this may already be fixed in master. YTmusic.js was out of date so I fixed it and brought it in. Will leave open until the next release to confirm.

**Comment by erasmuswill** [comment]
@jostrander That sounds great. Any idea when the next release will be? I keep on checking the site :P

**Comment by delhara** [comment]
Hello, friends!
@jostrander 
@erasmuswill
**OS:**
macOS Catalina 
10.15.1 (19B88)
**GPMDP Version:**
4.6.1

In "Now Playing" Notification Center widget has an incorrect song name and time.
The song title is only updated if you switch to gpm and back to ytm. Song playback time is reset if you pause and continue playing.

Sorry google translate

<img width="1440" alt="Снимок экрана 2019-11-17 в 23 24 22" src="https://user-images.githubusercontent.com/57875555/69013763-d1546400-0994-11ea-9fd2-4c01a5be7d21.png">

**Comment by erasmuswill** [comment]
@delhara I'm pretty sure this is the same issue I'm experiencing. Hope the next release fixes it :) Kinda considering building from source to try it out.

**Comment by rayl3r** [comment]
@erasmuswill you can download latest builds for OS X from [here](https://circleci.com/gh/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-).

**Comment by GhostInq** [comment]
> @erasmuswill you can download latest builds for OS X from [here](https://circleci.com/gh/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-).

Tell me, please, how to download the latest build? I don’t see or simply don’t understand how to do this, due to the lack of experience with the service.

**Comment by erasmuswill** [comment]
@rayl3r I have no idea how to get at the artifacts either :(

**Comment by rayl3r** [comment]
@erasmuswill @GhostInq  for OS X this link should work : https://3667-40008106-gh.circle-artifacts.com/0/home/circleci/project/dist/installers/darwin/Google%20Play%20Music%20Desktop%20Player.zip

**Comment by jostrander** [comment]
This should be fixed with 4.7.1. Comment if its not.
