### ISSUE TITLE
v 4.7 youtube music daemon not closing

### ISSUE THREAD

**Issue by Befo** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3666]
Hi,
I am checking out the app on Debian 10 and whenever I close it the underlying daemon streaming music does not close. It seems like the x button only closes the GUI. I am using the youtube music service on GNOME 3.34.1

OS: Debian 10
GPMDP version: 4.7.? (I believe 1)

**Comment by jostrander** [comment]
This is a setting in the application. You may want to uncheck minimize on close if its checked.

**Comment by Befo** [comment]
> This is a setting in the application. You may want to uncheck minimize on close if its checked.
Dang it, that may be a problem. I cannot find the setting anywhere, therefore I assume it is only accessible from the tray and I am on GNOME.
Do you know what property I can add to the .settings.json ?

**Comment by Befo** [comment]
> This is a setting in the application. You may want to uncheck minimize on close if its checked.

This is a setting in the application. You may want to uncheck minimize on close if its checked.
Dang it, that may be a problem. I cannot find the setting anywhere, therefore I assume it is only accessible from the tray and I am on GNOME.
Do you know what property I can add to the .settings.json ?

**Comment by Befo** [comment]
Workaround with https://extensions.gnome.org/extension/615/appindicator-support/
