### ISSUE TITLE
Hotkeys don't work if Chrome is focused

### ISSUE THREAD

**Issue by eygraber** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#367]
**OS:** 
Windows 10 64 bit

**Issue Descriptions:**
If Chrome has focus, hotkeys don't work.

**Steps to Reproduce:**
 1. Set a hotkey
 2. Give Chrome focus
 3. Try to use the hotkey

I've deleted the Google Play Music Chrome extension as described [here](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/344), but that didn't fix the issue.

**Comment by MarshallOfSound** [comment]
You might have to go to `chrome://restart`

**Comment by eygraber** [comment]
I tried that and restarted the computer. Still has the issue.

**Comment by MarshallOfSound** [comment]
Do you have any other applications that could be stealing the media keys?

Logitech drivers?  Music players?

**Comment by eygraber** [comment]
I don't believe so. I suppose it's possible, although the hotkeys work fine unless Chrome is the top-most focused window.

**Comment by MarshallOfSound** [comment]
Final question before I close for it not being reproducable :+1: 

What version of chrome are you running?

**Comment by eygraber** [comment]
48.0.2564.116 (Official Build) m (64-bit)

I also have 3 monitors (not sure if that makes a difference or not).

**Comment by eygraber** [comment]
I just ran Chrome with all extensions and plugins disabled, and the issue is still there.

**Comment by MarshallOfSound** [comment]
Closing as can't replicate, probably a chrome plugin (vs extension) or bad garbage collection by another program

**Comment by dst33nburgh** [comment]
This is a long shot given that you mentioned you've rebooted your PC, but have you tried restarting GPMDP instead?

**Comment by eygraber** [comment]
@dst33nburgh tried that and still a no go. Will keep trying things.

**Comment by eygraber** [comment]
FWIW 3.1.0 fixed this issue.

**Comment by MarshallOfSound** [comment]
@eygraber That was the plan :+1:
