### ISSUE TITLE
Can't add my music, link is unclickable

### ISSUE THREAD

**Issue by mrhat2** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3670]
**OS:** Windows 10

**GPMDP Version:** 4.6.1

**Issue Descriptions:** Trying to click 'Add your music' results in nothing. Mousing over it doesn't have the normal cursor that shows up for links, instead it's the one for selecting text, though the link for the GPM trial also has that cursor and is clickable.

**Steps to Reproduce:** Start GPMDP > click music library in the sidebar > click 'Add your music'

**Comment by jostrander** [comment]
For what its worth this link is meant to be hidden, and for some reason it recently became visible. The proper fix is to hide this again, as the "add your music" function only works with the desktop software or chrome extension.
