### ISSUE TITLE
On mac OS I can’t find where to switch to YTM

### ISSUE THREAD

**Issue by GhostInq** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3678]
On mac OS I can’t find where to switch to YTM. Clambered all the menus. Tell me where you can switch, preferably with screenshots.

**Comment by matthewnlee** [comment]
Not sure if this is the only way to access YTM, but I've been using the menu that drops down from the icons by the wifi/clock.

![Screen Shot 2019-11-18 at 10 06 32 AM](https://user-images.githubusercontent.com/24398709/69063981-6a15ce80-09eb-11ea-97b1-6af642671036.png)

**Comment by jostrander** [comment]
That's the only way on the last release to access it. Future versions have a button inside the web app.
