### ISSUE TITLE
Unable to control playback with stream deck on latest build.

### ISSUE THREAD

**Issue by Maskime** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3682]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**
Windows 10
**GPMDP Version:**
Build 1.0.2818 on AppVeyor (https://ci.appveyor.com/api/buildjobs/nmusqdjuh0pkitbc/artifacts/dist%2Finstallers%2Fwin32%2FGoogle%20Play%20Music%20Desktop%20PlayerSetup.exe)

**Issue Descriptions:**
I'm using the BarRaider app to control GPMDP from my stream deck, I still get the info on it (like the name of the song, the image of the album and the current time) but the play feature (as well as next and previous song) don't work anymore. I know that this is not a final release that I'm using, I'm just reporting the issue so that you can track it.
On a quick note: I installed the latest build because I had the #3660 issue.
Should I open an issue on the BarRaider GitHub so that they update their API client ?

**Steps to Reproduce:**
Install latest build and try to control GPMDP with the BarRaider application.

Thanks for your work.

**Comment by jostrander** [comment]
Nothing has changed in the API from what I can tell, so I'm not sure what would have caused this. Can you determine if it's for a specific service, either YTM or GPM?

**Comment by Maskime** [comment]
I was about, to update on this.
But I don't know why, I did the pairing (again) of the Stream Deck app with GPMDP and I got it working again.Sorry about the confusion, I think that for now, you can close this one...
