### ISSUE TITLE
Application not loading

### ISSUE THREAD

**Issue by AhmedDaou** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3685]
It stopped working a few days ago.

It is stuck at `Loading Music Library`

![image](https://user-images.githubusercontent.com/3523488/69577006-74ac0700-0f9b-11ea-83dc-3ea4fc6d9349.png)

It happens on both linux and microsoft.

I tried re installing the latest release but didnt help

**Comment by jostrander** [comment]
Duplicate of #3660

**Comment by AhmedDaou** [comment]
my bad
