### ISSUE TITLE
GDMP 4.6.1 Failing to Load on Windows 10 Pro x64

### ISSUE THREAD

**Issue by studiumcirclus** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3687]
Hi guys. I am having problems launching and entering (my music library) - GDMP 4.6.1 on W10 64-bit. I have tried reading through some prior posts but couldn't find my exact issue (many apologies if I missed something, I don't use GitHub much and may have gone blind...)

I have a suspicion about what the problem might be (since I occasionally get the same thing with Chrome, where I occasionally have to delete a certain folder containing my user data or it won't open)

**OS:** Windows 10 Pro x64

**GPMDP Version:** 4.6.1

**Issue Descriptions:** When I open GDMP it gets stuck on "Loading Music Library". The loading progress bar remains at 0% and never increases

**Steps to Reproduce:** Open GDMP 4.6.1 on Windows 10 Pro x64 (sorry, that's all I got!)

**What I Tried:** Uninstalling GDMP via add/remove programs then re-installing and re-launching. Setting all EXE files to 'Run as Administrator'. Nothing works

**Suspected Issue:** I noticed upon reinstall that GDMP didn't prompt me to login again, so it obviously stores my Google login info somewhere which is not cleansed when the app is uninstalled. Maybe there's some kind of cache which is to do with my user-data, which has become corrupted. I want to try hard-erasing it (to force login prompt) but I can't find where this is stored...

**Comment by ruslankrivoshein** [comment]
I have the trouble in Maxthon browser as well. I watch console and see
```
Uncaught TypeError: window.customElements.upgrade is not a function
    at RF (listen_v2.js:1136)
    at iLa.init (listen_v2.js:3360)
    at listen_v2.js:3372
    at HTMLScriptElement.onScriptLoad (listen:559)
```
I hope, it helps for solving.

**Comment by rayl3r** [comment]
Maybe the same issue as #3660 ?

**Comment by studiumcirclus** [comment]
> Maybe the same issue as #3660 ?

Not the same issue, as this issue is for the W10 build and that issue was for the MacOS build (though the issues may be strongly related, but I have no knowledge to support that). That being said; the comments on that issue (3660) factually did resolve this problem for me (which is a good bit of luck!)

In 3660, Gibbel91 said:

> I have the same issue on Windows 10.

There was a response from jfries289 which stated:

> You can find the latest windows build to download at https://ci.appveyor.com/project/MarshallOfSound/google-play-music-desktop-player-unofficial/build/artifacts
> 
> I believe it has the fix for this in it.

This proved to be the correct fix and I can categorically state, it did work for me. The reason I didn't find the advice was that, I hadn't looked far back enough in the archive - and also the issues was tagged as MacOS. We could leave these as distinct threads for people performing Google searches, or they could be merged (or one could be deleted)

Thank you to everyone who has commented and helped :) problem solved

**Comment by jarayama** [comment]
Removing C:\Users\%username%\AppData\Roaming\Google Play Music Desktop Player folder and entering the login information again worked for me, tried the developments versions but the UI keeps hanged after the loading library screen.

**Comment by ferpujol** [comment]
I'm having the same issue here. I just tried what @jarayama proposed and still it does not work for me. Any other ideas?

**Comment by jostrander** [comment]
Absolutely the same issue as #3660.
