### ISSUE TITLE
Playback API not working

### ISSUE THREAD

**Issue by RikuBS** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3691]
**Checklist:**

* [X] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [X] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [X] I have double checked and can reproduce the issue

**OS:**
Windows
**GPMDP Version:**
4.6.1
**Issue Descriptions:**
The playback api json updates the first time you play a song/playlist, but never updates again when the song changes.
**Steps to Reproduce:**
Play any playlist.
Check playback.json file.
Skip to next song.
Json file not updated.

**Comment by jostrander** [comment]
Does this only happen in YTM or GPMDP? I believe this may be fixed already but not released.

**Comment by RikuBS** [comment]
It happens when I use YTM, haven't checked if it does the same for GPMDP

**Comment by RikuBS** [comment]
After testing, the playback json works fine for GPMDP but doesn't for YTM

**Comment by jostrander** [comment]
This is fixed in master, we are just waiting on a release for it to be live.

**Comment by dashifen-gu** [comment]
Not to raise this thread from the dead, but I'm seeing something similar - using GPMDP it is updating when I move from track-to-track, but the `playing` flag is always `true.`  In the past, it used to toggle between `true` and `false`.  I can tell if a song is playing using the `time.current` value (i.e., if it's changing then a song is playing) but the `true`/`false` toggle was a little easier to work with.  

Is this related to the above discussed and fixed bug?
