### ISSUE TITLE
Feature Request: Google Podcast integration. 

### ISSUE THREAD

**Issue by SomeKittyCat** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3695]
Hello,

First of I am not sure how fencible this request is so feel free to right out say no if this is not possible.

Anyway,
My request is to add a tab to the Google Desktop Player that connects not to your Google Music but to your [Google Podcast](https://play.google.com/store/apps/details?id=com.google.android.apps.podcasts&hl=en) library . I am aware that you can search podcasts in Play Music already bit that feature is currently only available in the US and Canada and there is no knowing how long it will take for this to move over to other regions. 
Furthermore there is no Desktop _real_ version of Google Podcast, not even a real Web version. The only thing that exists on PC is a barebones web version which you can only access if you share a podcast link via the app version ([example here](https://podcasts.google.com/?feed=aHR0cHM6Ly9qdXN0cm9sbHdpdGhpdC5wb2RiZWFuLmNvbS9mZWVkLnhtbA)). 
My idea is that if someone would have the knowhow, he could port over the Web version over to GPMDP and if possible maybe port over the search function from the App version.

**Comment by jostrander** [comment]
This is a great idea, but unfortunately I think it's out of scope. I'd be interested to see how feasible this would be given there is no web interface for podcasts currently. Maybe this is something that could be accomplished in another project.

**Comment by SeeminglyScience** [comment]
Looks like there is a web interface now.  With Google Play Music going away and YouTube Music not supporting podcasts afaik, is this being considered at all?
