### ISSUE TITLE
Can't access Last.FM option on Linux

### ISSUE THREAD

**Issue by raulcraveiro** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3698]
**Checklist:**

* [X] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [X] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [X] I have double checked and can reproduce the issue

**OS:** Pop!_OS 19.10

**GPMDP Version:** 4.6.1-1

**Issue Descriptions:** Pop!_OS doesn't have tray icons, so I can't access the app configurations to connect Last.FM

**Steps to Reproduce:** I've installed the .deb from CircleCI (because the .deb on the website simply doesn't start) and logged in, nothing else.

**Comment by jostrander** [comment]
You can access the settings menu from the left bar in GPM. There is no way to access it in YTM, but once you've set it up I believe it will work for YTM.

**Comment by raulcraveiro** [comment]
It worked! Thank you so much :)
