### ISSUE TITLE
"You are trying to sign in from a browser or app that doesn't allow us to keep your account secure."

### ISSUE THREAD

**Issue by deadpahn** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3699]
**OS:**
WINDOWS
**GPMDP Version:**
LATEST
**Issue Descriptions:**
"Couldn't sign you in
You are trying to sign in from a browser or app that doesn't allow us to keep your account secure.
Try using a different browser. Learn more"
**Steps to Reproduce:**
Was forced to log out.

**Comment by Cthulzilla** [comment]
Ditto.

I'm having the same issue.

**OS:**
WINDOWS
**GPMDP Version:**
LATEST
**Issue Descriptions:**
When trying to sign in, I'm getting:
"You are trying to sign in from a browser or app that doesn't allow us to keep your account secure.
Try using a different browser. Learn more"

**Comment by jostrander** [comment]
Please read and follow the issue template before creating issues. This is a duplicate of #3545 which is pinned.
