### ISSUE TITLE
Feature Request: Make the Global hotkeys customizable

### ISSUE THREAD

**Issue by baleksey** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#37]
It would be great if users will be able to control music player with global keyboard shortcuts (for those who don't have media keys) which can be customized. For example, Google Chrome allows to set keyboard shortcuts for extensions but they are very limited as user can't set just "F11" or "Ctrl+F9".

It could be done from some sort of setting menu or editing some config file (in order to add this feature faster and make it configurable from the app later).

**Here are the main player function for hotkeys:**
- Play/Pause (one shortcut for switching these two states)
- Next song
- Previous song
- Volume Up
- Volume Down
- Mute Volume

**Less important but can be useful:**
- "Like" current song. In order to add it to users library without opening the player. It would be good to  show confirmation popup as feedback to user like action.
- "Add to playlist" current song. On this action player should open with playlist selector. 
- Open player (just maximize it and send on top of all windows)

**Comment by MarshallOfSound** [comment]
So I've spent a while thinking about this, and I think I'm going to have to put this way down on the backlog for a few reasons  
* Global hotkeys are simple, combinations not so much
* Detecting if a combination is used by another program or not is virtually impossible and I don't want to break other programs
* You can't do certain key combinations in chrome for a reason.  Check the chrome bug report (can't remember the number just google it :P)

Moving to `fn + f1-12` might be a switchable options (Use media keys or function keys) but full customization and user selection I think is off the table at this point

**Comment by baleksey** [comment]
Samuel, you've mentioned good points and I understand them but you probably missed the most important one. I believe that global keyboard shortcuts should be the first priority task for this player and I'll explain why.

First of the ability of fast, remote control of any media player is one of the most important factor. I believe that over 90% of people who already have their favorite playlists will use such controls (volume, play/pause, next song) majority of time and opening player every time is very uncomfortable.
Imagine, you've bought a great TV, with smart functions, many channels and other cool features but without remote controls. And every time you need to interact with it (switch channel or adjust volume) you have to stand up from you comfortable couch. walk through your room and click something on TV. 
It's just a hell if you can't do that remotely. This is the same thing as global shortcuts for Google Music Player for 90%+ people.

Second of all, you said that you should detect keys combinations for other programs. You not only have to do that but it's highly not recommended at all. The keys you've set must be global and OVERRIDE all other shortcuts from any programs. This is behavior people expecting from global keyboard shortcuts. This is how many global programs actually work. For example screen recorders and other music players. Do you know one of the best music player Foobar 2000? It has options to set keyboard shortcuts and make them local (works only in active player) or global which overrides everything else as expected. This is very cool feature and it will greatly fit your great application.

So, we've found that remote control is one of the most usable feature for media application and shortcuts must be global and have the highest priority as other similar application do. I hope it makes you reconsider your initial thoughts and add this feature in the next update. Thank you!

**Comment by MarshallOfSound** [comment]
You make some interesting points, I'll look around and see what the best way forward is

**Comment by darnold** [comment]
I second this. I use the Prime Player google extension solely because of the shortcuts it lets me use in chrome to control my player. https://chrome.google.com/webstore/detail/prime-player-for-google-p/npngaakpdgeaajbnidkkginekmnaejbi

**Comment by superjase** [comment]
this is such an important feature! being able to control my media without having to open the player on the screen is mandatory!

**Comment by MarshallOfSound** [comment]
@superjase Their are global hotkeys, they are set to the standard play/pause, previous and next track buttons.

If you want to customize them, for now you can use something like AutoHotkey to map keys to other keys

**Comment by DecoyJoe** [comment]
@superjase This is what I do with AutoHotkey to make global shortcuts (My keyboard doesn't even have media keys)

```
;Custom media key shortucts
!d::Send {Media_Play_Pause}
!f::Send {Media_Next}
!a::Send {Media_Prev}
```

**Comment by TeamTorch5942** [comment]
Maybe this is a separate issue, but my keyboard media keys don't work at all. I have a logitech k330 wireless keyboard, and have never had issues with another application.

**Comment by MarshallOfSound** [comment]
@TeamTorch5942 Your issue is because logitech trys to be fancy and fails miserably... :smile: 

Read #90 for info on how to fix

**Comment by superjase** [comment]
i confirm that [#90](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/90) solved my logitech issues. it's the setpoint software that causes the problem. my logitech keyboard now works perfectly with all media buttons, and all other custom buttons, too.

**Comment by MarshallOfSound** [comment]
@baleksey Good news, this is implemented in `3.0.0` stay tuned for that release

**Comment by MarshallOfSound** [comment]
The ones I have implemented are

* Media PlayPause
* Media NextTrack
* Media PrevTrack
* Media Stop
* Thumbs Up
* Thumbs Down


I didn't do volume controls because volume controls should be handled by your OS volume not a shortcut for the GPM volume :+1:

**Comment by baleksey** [comment]
Hey, Samuel,

Great news, thank you! 

As for player volume it also pretty important feature for us without special media keys or easy/fast access to volume. Here is how it works on my PC: I set global OS volume to the comfortable level for all OS sounds, default video players on the web, Skype etc, and I adjust it pretty rarely after that. When I do - it often do the mess (for example extra loud flash video in the middle of the night). Thats why Google Plyer volume I do directly from player and not globally in order to keep dosens of other sounds on the same predictable level. On the other side many songs from GPM are not equilized to the same volume level and they need volume adjustments much more often.

I would be greatful if you add also volume controls to your awesome app. Anyway those who don't need them will just ignore.

**Comment by MarshallOfSound** [comment]
Hey @baleksey 

Thanks for the additional feedback but I still don't think I will implement volume hotkeys.  This is due to a multitude of reasons

1. I am trying to reach feature parity with other major media players (Spotify, WM and Media Monkey are those that I have looked at for ideas) and none of them implement volume hotkeys
2. Your GPM volume should remain constant and be "in balance" with the rest of your system. If you have to change the volume of GPM for some reason your audio setup is wrong.  Something like `Sound Blaster 2` will handle volume levelling for you if it is a big problem
3. I am trying to keep the player both feature rich and simple.  And a line has to be drawn somewhere, unfortunately that line is here
