### ISSUE TITLE
Will not load play music library for a few weeks now. It just shows loading music library and the bar never moves.

### ISSUE THREAD

**Issue by Nepgyaaa** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3700]
**Checklist:**

* [/ ] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [0 ] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [0 ] I have double checked and can reproduce the issue

**OS:** Windows 10 64bit

**GPMDP Version:** I dont know where to go to find the version.
![Capture](https://user-images.githubusercontent.com/58497559/70109187-be869400-1610-11ea-9ddb-1b286ccc4d5f.PNG)

**Issue Descriptions:** Will not load play music library for a few weeks now. It just shows loading music library and the bar never moves. Youtube music still loads, but I use gp music

**Steps to Reproduce:** open the app

**Comment by Nepgyaaa** [comment]
I found another closed thread with the fix.

**Comment by liquiddusty** [comment]
> I found another closed thread with the fix.

Please include the link here in this thread so future people running into this issue can resolve it

**Comment by jostrander** [comment]
It's pinned. #3660
