### ISSUE TITLE
Google Login Broken

### ISSUE THREAD

**Issue by nsaud01** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3702]
Google login is broken for me and I'm logged into google on every browser I own. Here's the screen I get:

![image](https://user-images.githubusercontent.com/1648297/70198834-00c9d700-16de-11ea-8978-c7063d0172c8.png)

I'm on v4.6.1
Thanks!

**Comment by iamzloff** [comment]
How was this resolved?

**Comment by tbertrand7** [comment]
Duplicate of #3545
