### ISSUE TITLE
Unable to login after clearing cache

### ISSUE THREAD

**Issue by Zl0n1k** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3705]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**

* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there

* [x] I have double checked and can reproduce the issue

**OS:** MacOSX Mojave 10.14.6(18G1012)

**GPMDP Version:** 4.6.1 (4.6.1)

**Issue Descriptions: **
I had the same issue that described in #3660 (can't load library).
After error  i reinstalled the app, and cleared cache manually.
And when i tried to log in, google returned the message:
'You are trying to sign in from a browser or app that doesn't allow us to keep your account secure.'
P.S: I also tried to login with "Application password" created in the google account, no luck. 

**Steps to Reproduce:**

Clear cache:

```
rm -Rv ./Library/ApplicationSupport/Google\ Play\ Music\ Desktop\ Player/*
```

GPMDP version(Ticket #3660):
https://3727-40008106-gh.circle-artifacts.com/0/home/circleci/project/dist/installers/darwin/Google%20Play%20Music%20Desktop%20Player.zip

Open app.

Enter login/passwd

Response:

```
You are trying to sign in from a browser or app that doesn't allow us to keep your account secure.
```

**Comment by jostrander** [comment]
This is the other pinned issue, #3545
