### ISSUE TITLE
GUI not opening on Windows 10

### ISSUE THREAD

**Issue by billypfeiffer** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3706]
**OS:**
Win10
**GPMDP Version:**
4.6.1
**Issue Descriptions:**
GUI not opening when starting.  The app shows up on the task bar but I can not see the GUI.
**Steps to Reproduce:**
Just open app

**Comment by lostcoaster** [comment]
It seems Google Music Manager (official) has the same problem (for me and [some others](https://www.androidpolice.com/2019/12/06/google-play-musics-desktop-uploader-music-manager-is-down-for-many-users/), maybe google just messed up with their API.

**Comment by httpSteve** [comment]
![image](https://user-images.githubusercontent.com/17752473/70377433-5e2e7580-18e2-11ea-8bf5-04d95371f2e3.png)

**Comment by sli** [comment]
Links for a more recent build that fixes this are in #3660.

**Comment by marquesarthur** [comment]
Same problem happens on MacOS Mojave

**Comment by sadminriley** [comment]
Same issue with Windows 10 here.

**Comment by sadminriley** [comment]
> 
> 
> Same issue with Windows 10 here.

FYI I've also tried both 4.6.0 and 4.5.0 and got the same results

**Comment by who0ps** [comment]
Same. 
Clearing `%\AppData\Roaming\Google Play Music Desktop Player\` and re-login doesn`t help.

**Comment by jostrander** [comment]
See #3660
