### ISSUE TITLE
Windows Media Overlay Doesn't Update With Tracks

### ISSUE THREAD

**Issue by jekthewarrior** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3708]
**Checklist:**

* [X] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [X] I have double checked and can reproduce the issue

**OS: Windows 10**

**GPMDP Version: 4.6.1**

**Issue Descriptions: Doesn't update with the tracks.**

**Steps to Reproduce: Press the button for Windows Media Ovelay in the GPMDP options and play a playlist and skip to the next track. When the overlay is activated, the track listed is the first song played when GPMDP is opened.**

**Comment by jostrander** [comment]
Is this specific to YTM?

**Comment by jekthewarrior** [comment]
Yeah, it is. I apologize for not putting it in the issue description. Should I edit the issue and add it to the title and/or description?

**Comment by jostrander** [comment]
This is already fixed in master. There was a problem/bug in YTM where it would fail to fetch new track info and I patched it.

**Comment by jekthewarrior** [comment]
Will it be released with the next release of GPMDP? Or is it already in 4.6.1?

**Comment by jostrander** [comment]
The next version, not 4.6.1.
