### ISSUE TITLE
Unable to log into last.fm when starting up via terminal

### ISSUE THREAD

**Issue by chrismou** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#371]
Checking out `master`, and following your instructions to get started (ending in running `npm start`) I'm not able to log in to last.fm.   Clicking the "LOG IN TO LAST.FM" button changes the test to `...` briefly, then it switches back.  Nothing is output to console.

I managed to log in OK using the 3.0.0 OSX binary.  Just seems to be when I run the master branch from terminal.

**Comment by chrismou** [comment]
Just to add to it, I've just flicked back to the 3.0.0 version and it's logged me out.  Though clicking the button and reauthorizing works fine.

**Comment by MarshallOfSound** [comment]
When you start via terminal you should get an error saying some LASTFM api keys aren't set.  They need to be set for lastfm functionality to work

**Comment by MarshallOfSound** [comment]
If the error isn't appearing then that is a bug

**Comment by MarshallOfSound** [comment]
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/main/constants.js

**Comment by chrismou** [comment]
Ah, so if I'm booting up a non compiled version I need to use my own API keys?

**Comment by MarshallOfSound** [comment]
:+1:  the API keys aren't in the repository

**Comment by chrismou** [comment]
Gotcha. Now you say it, that makes perfect sense.

Any idea why jumping between binary and `master` would deauthorize me?

**Comment by chrismou** [comment]
Sorry, I mean from binary, to `master` then back to binary

**Comment by MarshallOfSound** [comment]
Probably tried to authorize, failed, and set the lastfm key to be a null / empty value.  So your token was deleted

**Comment by chrismou** [comment]
OK cool. Am trying out a couple of tweaks to your last.fm implementation, if you were wondering. Am currently stuck on getting it to pick up my API key, but then I am at work and trying it in between test suite runs.  I'll puzzle it out later tonight  ;-)
