### ISSUE TITLE
GPMDP does not work

### ISSUE THREAD

**Issue by PixelMass** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3710]
I go into the program, and there is an endless download of the library, tried to reinstall, it  did not help (
Help me please.

**Comment by jostrander** [comment]
Hey @PixelMass this is fixed in master, see the pinned issue #3660. There are pre-release builds available in the comments if you want to try those, otherwise you'll have to wait until the next release is out.
