### ISSUE TITLE
Stopped working on Windows 10

### ISSUE THREAD

**Issue by buzzik** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3717]
Yesterday has Stopped working on both windows 10 PC's
Freezing on "Loading library" screen.

![1738](https://user-images.githubusercontent.com/6613424/70601052-ec17a280-1bf9-11ea-9882-33530188bdae.png)
![1739](https://user-images.githubusercontent.com/6613424/70601053-ec17a280-1bf9-11ea-839c-2c838f88955e.png)

P.S. Asked my friends, they have same problem.
P.P.S About one week earlier started another bug, after few minutes of working app just freezes in the middle of the song (random song)

**Comment by WebFactoryLtd** [comment]
Unfortunately, I can confirm. Exactly the same issue as described above. Worked for me yesterday, today just loads.

**Comment by Alena1985** [comment]
The same for me too (

**Comment by ddanjou** [comment]
same here - stopped working a few days ago.

**Comment by johnsreid** [comment]
I've been unable to use the app for about a week or so.

I've tried to delete the folder in the %APPDATA% folder on Windows 10 and it still hangs once it gets to the Loading Library… screen. Now I've reset the app and tried again, here's the debug info.

[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/3949097/debug_info.zip)

**Comment by andrui** [comment]
#3660

**Comment by andrui** [comment]
#3660

**Comment by TheMostCreative** [comment]
Same thing here, bro

**Comment by buzzik** [comment]
Found link to sucsessfull [fixed build](https://ci.appveyor.com/project/MarshallOfSound/google-play-music-desktop-player-unofficial/builds/29394771/artifacts) hope this would help

**Comment by melnichevv** [comment]
it doesn't work for me in PopOS based on Ubuntu too :/

**Comment by postscripter** [comment]
same issue for me, on latest windows 10 version

**Comment by robertcv** [comment]
Same issue on Ubuntu 18.04

**Comment by Zakini** [comment]
Same issue on macOS 10.14.6

**Comment by codymiller360** [comment]
same here windows 10

**Comment by andrii-usmanaiev** [comment]
Same issue Windows 10. Library just doesn`t load
![image](https://user-images.githubusercontent.com/53050910/70611665-373bb080-1c0e-11ea-9280-64c8a8a29759.png)

**Comment by pbaliuk** [comment]
Same issue on ubuntu 18.04

**Comment by Landen13** [comment]
Stopped working on Windows 10, but Youtube pre-alpha works

**Comment by OleksiiAndroid** [comment]
Same issue Windows 10

**Comment by 3driy** [comment]
Same thing. Stopped working today

**Comment by Jlomaka** [comment]
Same issue Ubuntu 18.04

**Comment by TheMcSebi** [comment]
Same issue on Windows 10 1809

**Comment by RaceTF** [comment]
same issue on Windows 10

**Comment by Shebo** [comment]
Same issue win10

**Comment by arcoldwell** [comment]
Same issue here with Windows 10.

**Comment by sharp-axe** [comment]
same issue Windows 10

**Comment by jostrander** [comment]
#3660

**Comment by buzzik** [comment]
@jostrander
 Why tou are closing this issue? #3660 is closed to, but there is no new realese yet. People will create new issues with same problem

**Comment by arcoldwell** [comment]
@buzzik, he must be considering that build you linked to the solution?

It'd be nice if that was linked more prominently somewhere.
