### ISSUE TITLE
Support on Mac OS X 10.8?

### ISSUE THREAD

**Issue by slayer925** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#372]
**OS:** Mac OS X 10.8.5

**Issue Descriptions:** It requires 10.9.0 or later

**Steps to Reproduce:** Download, unzip, try to open

If it doesn't support on 10.8.* just change the README.md file

Thanks for the project <3

**Comment by MarshallOfSound** [comment]
It does appear that the min version is `10.9`

https://github.com/atom/electron/blob/master/docs/tutorial/supported-platforms.md#os-x
