### ISSUE TITLE
Stuck on "Loading Music Library…"

### ISSUE THREAD

**Issue by pdario** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3721]
Hello, yesterday I canceled my paid subscription to Play Music "premium" and it will cease on the 28th.

Since then, GPMD does not load anymore, it's stuck con "Loading Music Library…".

Is this due to my cancellation?
What can I do?

**Comment by pdario** [comment]
PS: switching to YT Music works; GPM not.

**Comment by pdario** [comment]
I tried logging out from Google using YTM interface; then I tried to login again into GPM and now it says "the browser is not supported". What?

**Comment by pdario** [comment]
Duplicate of https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3660

**Comment by doomcreeper** [comment]
I have the same problem, gpmd does not start. there is an endless download of the library. program version 4.6.1, windows 10
