### ISSUE TITLE
Can't login: browser not safe

### ISSUE THREAD

**Issue by pdario** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3722]
Hello, after I was stuck on "loading music library", I signed out of Google and tried to sign in again; now Google says I can't because my browser is not safe.

I tried installing v4.7 but nothing changed, apart from the visuals of the message.

What can I do?

**Comment by mrjameshamilton** [comment]
Same problem here.

**Comment by NiborIS** [comment]
Same problem here

Google Play Music Desktop Player v4.6.1
Windows 10.0.19037.1

Thanks.

**Comment by pellomik** [comment]
Two days with the same issue. 
Version: 4.6.1
Ubuntu 18.04

**Comment by tauil** [comment]
Same problem

**Comment by jespersh** [comment]
Is it just Google Play Music that isn't working? Mine doesn't load either, but YouTube Music (which I switched to few months ago) works

**Comment by tauil** [comment]
Google Play Music for me.

**Comment by nebojsac** [comment]
Same problem here

**Comment by gonzalomarcote** [comment]
Seems that this is a common issue since 2 days ago regardless the distro. Google could have changed something to login from his side. 
Same problem using Debian 10 Buster and install Google Play Music with flatpak

**Comment by Vusys** [comment]
Same. macOS 10.14.6.

I tried logging out then logging in. I don't get a browser not safe message, but I do get hanging on "Loading music library..."

**Comment by sidle21** [comment]
'Browser not safe' message for me, using the latest windows version

**Comment by inacionery** [comment]
Google Play Music for me, Youtube Music is working.

**Comment by cosmincrihan** [comment]
Same issue both on Debian and Windows

**Comment by ajithhub** [comment]
Win10, I was having the "Loading music library..." issue, then I uninstalled and deleted all the %APPDATA%.  Now I can't sign in.

I tried youtube Music and it lets me switch, but I'm still not able to log in.   The YT interface has stuff I can play without signing in.

**Comment by jostrander** [comment]
Duplicate of #3545
