### ISSUE TITLE
Last.fm Not Consitently Scrobbling on Track Completion

### ISSUE THREAD

**Issue by AquaMorph** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3727]
**OS:** Fedora 30 and Windows 10

**GPMDP Version:** bb123156a7b05706e4f0ebd8d237dc8de0248ea0

**Issue Descriptions:** This issue is similar to #2967 Tracks will be marked as scrobbling now when played but is not marked as completed. This I have found to work sometimes but not reliably. I have tried all version of the app from when the login was fixed until the latest and the problem is in all of them.

**Steps to Reproduce:** 
1) Login to Last.fm
2) Listen to an album
3) Check Last.fm page

**Comment by jostrander** [comment]
Is this only on YTM or in GPM as well?

**Comment by AquaMorph** [comment]
I only have tested GPM. I thought TYM wasn't yet fully supported

**Comment by vegeta897** [comment]
Happening to me as well. While listening to a song (GPM) I will see it scrobbling on my last.fm page, but when it's done it doesn't actually save to my scrobble history.

**Comment by spyn** [comment]
I'm getting this happen with ListenBrainz and Last.fm. It'll show now playing, but not actually save the song after it's been completed.

**Comment by titomb345** [comment]
I am also seeing this issue. As a 13 year last.fm user, this is devastating, haha. I'm being dramatic, but yeah, I see the songs listed as "scrobbling now" but they do not actually save to my last.fm history.

**Comment by Landen13** [comment]
+1

**Comment by AquaMorph** [comment]
I have found a version that this is not an issue and the login issue is fixed [a3b5409](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/commit/a3b540950ff4b94f5f843d52fc1df0610e6d3c2c). Using this version as a temporary work around.

**Comment by gdjohnson** [comment]
+1

**Comment by vegeta897** [comment]
Seems to be working in the 4.7.0 build posted here: https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3761#issuecomment-569455691

**Comment by AquaMorph** [comment]
Yeah seems to also be working for me on Fedora 31

**Comment by AquaMorph** [comment]
Newest releases also fixes the problem on Windows 10
