### ISSUE TITLE
do not loading

### ISSUE THREAD

**Issue by FarRider-tech** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3730]
Hello!
The app worked well. Thanks you!
But recently, the application has stopped working. I overdue my subscription payment on Google Play Music and now when I open the application I see the inscription "loading library". And nothing else happens. I uninstalled the application and installed it again - but everything repeats. Although the subscription has already been paid, the library is not loading. Please help - now listening to music through the browser is a real punishment for me :)
![Clip2net_191216110330](https://user-images.githubusercontent.com/58934679/70893425-be649c00-1ff3-11ea-854b-bfd23f068fd9.png)

**Comment by vegeta897** [comment]
This just started happening for me as well.

**Comment by FarRider-tech** [comment]
Sorry. 
Found this problem in [3660](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3660)
I installed a [fix](https://ci.appveyor.com/api/buildjobs/amjhy1vx6gjpf31k/artifacts/dist%2Finstallers%2Fwin32%2FGoogle%20Play%20Music%20Desktop%20PlayerSetup.exe) from there and it all worked for me.
Thanks!
