### ISSUE TITLE
Stuck on rotating circular progressbar in Windows 7 x64 (Warning: "Accessing PropTypes ...")

### ISSUE THREAD

**Issue by Iowerth** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3731]
Hi. I faced with error described in https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3640. I tried two variants:
1. Editing `index.js` (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3640#issuecomment-543863416)
2. Installing a newer version of GPMDP with fixed `index.js` (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3640#issuecomment-562376367)

No one of these variants was helpful. GPMDP stucks on rotating circular progressbar - https://i.imgur.com/bE3riMO.jpg

UPD1: but if I switch to YouTube Music - it works. Then I switch to Google Play Music - and it stucks on rotating circular progressbar again.

UPD2: if dev mode enabled then next warning presents:
`C:\Users\username\AppData\Local\GPMDP_3\app-4.6.1\resources\app.asar\node_modules\react\lib\lowPriorityWarning.js:38 Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
printWarning @ C:\Users\username\AppData\Local\GPMDP_3\app-4.6.1\resources\app.asar\node_modules\react\lib\lowPriorityWarning.js:38`
Screenshot of this warning - https://i.imgur.com/jPDj8uo.jpg

UPD3: nothing changed with 4.7.1 - https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3731#issuecomment-572450483

**Comment by callmeberzerker** [comment]
Same here on MacOS Mojave 10.14.6.

**Comment by Squintz82** [comment]
Not sure if it's the same issue, but I get stuck on "Loading Music Library" after opening the app. I haven't been able to reach my music since last Thursday.

**Comment by Iowerth** [comment]
> 
> 
> Not sure if it's the same issue, but on v4.6.1 and MacOS 10.14.6, I get stuck on "Loading Music Library" after opening the app. I haven't been able to reach my music since last Thursday.

Issue you are talking about is here - https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3640
And here's solution - https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3640#issuecomment-562376367

But my issue is another.

**Comment by Squintz82** [comment]
@Iowerth Yes, thank you!

**Comment by callmeberzerker** [comment]
@Iowerth yep that does it. Thanks!

**Comment by johanpza** [comment]
Same here, issue seems to be "API rate limit exceeded for user ID 46******"
on: https://update.gpmdp.xyz/update/win/4.6.1/RELEASES?id=GPMDP_3&localVersion=4.6.1&arch=amd64

**Comment by jostrander** [comment]
Press `CTRL` `ALT` `G` and type `DEV_MODE` press go, accept, and restart. Open the developer tools  (`CTRL` `SHIFT` `i`) and take a screenshot of the console tab. Errors in red are what you are looking for.

**Comment by Iowerth** [comment]
> 
> 
> Press `CTRL` `ALT` `G` and type `DEV_MODE` press go, accept, and restart. Open the developer tools (`CTRL` `SHIFT` `i`) and take a screenshot of the console tab. Errors in red are what you are looking for.

`CTRL` `ALT` `G` doesn't work.

I've updated my first comment:
But if I switch to YouTube Music - it works. Then I switch to Google Play Music - and it stucks on rotating circular progressbar again.

**Comment by dcferreira** [comment]
It's CTRL+SHIFT+G.

**Comment by Vmastery** [comment]
No errors in console. just 1 warning

> Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

**Comment by Iowerth** [comment]
First post update

If dev mode enabled then next warning presents:
`C:\Users\username\AppData\Local\GPMDP_3\app-4.6.1\resources\app.asar\node_modules\react\lib\lowPriorityWarning.js:38 Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
printWarning @ C:\Users\username\AppData\Local\GPMDP_3\app-4.6.1\resources\app.asar\node_modules\react\lib\lowPriorityWarning.js:38`
Screenshot of this warning - https://i.imgur.com/jPDj8uo.jpg

**Comment by jostrander** [comment]
Whoops, wrong short cut. You can also type `ope GPMDevTools()` in the conse
Ole and press enter. That should bring up any errors in the web view that might be causing it to fail.

**Comment by Vmastery** [comment]
Here's result of openGPMDevTools()
3 errors, 5 warnings

http://prntscr.com/qcjrx8

**Comment by Iowerth** [comment]
> 
> 
> Here's result of openGPMDevTools()
> 3 errors, 5 warnings
> 
> http://prntscr.com/qcjrx8

Issue you are talking about is here - https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3640
And here's solution - https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3640#issuecomment-562376367

But my issue is another.

**Comment by jostrander** [comment]
@Iowerth Were you able to run `openGPMDevTools()` ?

**Comment by Iowerth** [comment]
> 
> 
> @Iowerth Were you able to run `openGPMDevTools()` ?

How can I run it? I don't know.

**Comment by jostrander** [comment]
Open the console as instructed above, then type that in and press enter. Another console will open, with hopefully an error message.

**Comment by Iowerth** [comment]
> 
> 
> Open the console as instructed above, then type that in and press enter. Another console will open, with hopefully an error message.

I've pressed `CTRL+SHIFT+G` and entered `openGPMDevTools()` and pressed `Enter`. Nothing happened.

**Comment by jostrander** [comment]
Any luck with the 4.7.0 RC that was recently posted @Iowerth ?

**Comment by killwort** [comment]
I'm having the same issue under windows 10. Reproduced in 4.6.1 and 4.7.1. Also reproduced in CI builds.
DEV_MODE console shows only one warning.
![image](https://user-images.githubusercontent.com/4142887/72042149-a284ab00-32be-11ea-80f9-1061d4b886dd.png)

**Comment by Iowerth** [comment]
> 
> 
> Any luck with the 4.7.0 RC that was recently posted @Iowerth ?

Sorry for late answer. Nothing changed even with 4.7.1. Seems developer doesn't read our issues.

**Comment by Iowerth** [comment]
@MarshallOfSound could you please help with this issue?

**Comment by Iowerth** [comment]
@MarshallOfSound could you please help with this issue?
