### ISSUE TITLE
Player stuck on initial 'Loading Music Library' screen

### ISSUE THREAD

**Issue by carloladuca** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3732]
**OS: macOS 10.15.1**

**GPMDP Version:  4.6.1**

**Issue Descriptions: Every now and then (say after a month or so), player gets stuck on Loading Music Library. Tried clearing pref files, uninstalling completely, logging out and back in, everything. Last time it happened it didn't work for a while (a few weeks) and then it started working again.**

**Steps to Reproduce: Open the app.**

**Comment by VladimirTolmachev1** [comment]
Hi, I have the same problem with Linux.
I had tested on Linux Mint 18.3 Sylvia and Ubuntu 18.04
I'm just launching the application and that's all, the app trying to load the library and nothing happened.
Please check my screenshot:
http://pix.toile-libre.org/upload/original/1576493978.png

**Comment by davidlinse** [comment]
Facing the same issue on OXS `10.13.6 (17G65)` and Player `Version 4.6.1 (4.6.1)`

**Comment by scaytrase** [comment]
Same here, win10 + GPMDP 4.6.1. Music in browser opens OK

**Comment by lostcoaster** [comment]
This issues has been raised on #3660 , temporary fixes are in that issue. Just wondering when there will be an official release.

**Comment by Vidark-Wyrd** [comment]
Hello
Same problem for me, win10 + GPMDP 4.6.1.

**Comment by tkalee** [comment]
I'm also stuck on the loading screen: Windows 10, with GPMDP 4.6.1
