### ISSUE TITLE
Cannot switch back to GPM after trying YTM (Beta)

### ISSUE THREAD

**Issue by HPSeeEmilyPlay** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3735]
[x] I have checked that there are no issues with similar or the same content

[x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
[x] I have double checked and can reproduce the issue

OS: Windows 10 64bit

GPMDP Version: 4.6.1

Issue Descriptions: I clicked the "Switch to YTM (Beta)" button and now cannot switch back to GPM in the GPMDP

Steps to Reproduce: 
1. Click "Switch to YTM (Beta)" in top RH corner. No options to switch back to GPM
2. Uninstalled GPMDP
3. Cleared cookies/history
4. Reinstalled GPMDP

Always loads YTM in the GPMDP now and I don't see any options to switch back to GPM in the app.

**Comment by siddardhaks** [comment]
Looks like this is related to #3640 , try https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3640#issuecomment-562376367

**Comment by HPSeeEmilyPlay** [comment]
> Looks like this is related to #3640 , try [#3640 (comment)](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3640#issuecomment-562376367)

oh thank you so much. I downloaded the Windows version from that thread and it has the option to select "Switch to GPM", and now it's all working again.
Cheers!
