### ISSUE TITLE
Latest Windows 10 updates from 12/11 seemed to have broken GPMDP

### ISSUE THREAD

**Issue by edaxme** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3736]
**OS:** Windows 10 x64

**GPMDP Version:** 4.6.1

**Issue Descriptions:** The latest Windows 10 update (KB4539684 and/or KB4533002, installed on 12/11) seems to have broken GPMDP. It's not stuck on the "Loading your music library" screen.

**Steps to Reproduce:** Open the app with the latest Windows 10 updates, I guess.

**Comment by jostrander** [comment]
Coincidental, this is actually #3660
