### ISSUE TITLE
(google-play-music-desktop-player:8454): Gtk-WARNING **: 10:34:57.633: cannot open display: :0

### ISSUE THREAD

**Issue by d-kay23** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3738]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**
Ubuntu 18.04
**GPMDP Version:**
latest/stable | 4.6.1
**Issue Descriptions:**
I've installed https://snapcraft.io/google-play-music-desktop-player When I run it, there is the error in syslog:
(google-play-music-desktop-player:8454): Gtk-WARNING **: 10:34:57.633: cannot open display: :0
Other snap applications work without any problem, does anybody know how to fix the problem?
gnome-shell --version
GNOME Shell 3.28.4
**Steps to Reproduce:**
Install and run snap application on Ubuntu 18.04

Edit: deb package works, but snap package doesn't.

**Comment by jostrander** [comment]
Try snap's edge channel `snap refresh <package name> --edge`

**Comment by d-kay23** [comment]
I get the same error:
```
snap info google-play-music-desktop-player
name:      google-play-music-desktop-player
summary:   Standalone player for Google Play Music
publisher: Chris Halse Rogers (cooperteam)
contact:   https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues
license:   unset
description: |
  This Google Play Music player provides desktop integration - with music
  hotkeys and the sound indicator via an MPRIS interface, the abiliy to use
  custom colours and load custom themes, a remote-control interface, and
  lower resource consumption than a full-blown browser tab.
  .
  This is *not* an official Google project.
commands:
  - google-play-music-desktop-player
snap-id:      4Y41wz5UioPArGBhEyQaO1DkY5pfUEpa
tracking:     edge
refresh-date: today at 10:05 EET
channels:
  stable:    4.6.1              2019-09-13 (72) 116MB -
  candidate: 4.6.1              2019-09-13 (72) 116MB -
  beta:      4.6.1              2019-09-13 (72) 116MB -
  edge:      v4.6.1-63-g4445ffa 2019-12-09 (77)  98MB -
installed:   v4.6.1-63-g4445ffa            (77)  98MB -
```

```
google-play-music-desktop-player

(google-play-music-desktop-player:16035): Gtk-WARNING **: 10:09:12.697: cannot open display: :0
```

**Comment by jostrander** [comment]
@RAOF Any idea here?

**Comment by RAOF** [comment]
Huh, interesting!

It's not entirely clear to me what's happening here, but it seems that there's some confusion (between Electron & GTK?) in the process as to which display connection to use.

For me, `env DISABLE_WAYLAND=1 google-play-music-desktop-player` works. I should be able to set this in the `snapcraft.yaml` settings, so I'll see if I can do that…

**Comment by RAOF** [comment]
Huh, interesting!

It's not entirely clear to me what's happening here, but it seems that there's some confusion (between Electron & GTK?) in the process as to which display connection to use.

For me, `env DISABLE_WAYLAND=1 google-play-music-desktop-player` works. I should be able to set this in the `snapcraft.yaml` settings, so I'll see if I can do that…

v4.7.1 revision 80 (available in all the snap channels as of now) should fix this!

**Comment by d-kay23** [comment]
@RAOF 
Yes, this fix works. Thank you.
