### ISSUE TITLE
"Couldn't sign you in"

### ISSUE THREAD

**Issue by Mainian** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3739]
Ubuntu 19.10
4.6.1 - Installed via snap, strict confinement

After installing, I can't sign in to google.

I'm speculating [this](https://www.omgubuntu.co.uk/2019/12/couldnt-sign-you-in-google-browser-error-linux) is the real reason. I haven't tried a classic confinement yet.

**Comment by jostrander** [comment]
No, its similar though. See #3545 for that. Although if you are using snap you can install the master revision with the --edge channel.

**Comment by donaldrowens** [comment]
Same issue running Windows 10 version 1903, build 18362.535. 
Full error is:
```
Couldn't sign you in
This browser or app may not be secure. 
Learn more

Try using a different browser. 
If you’re already using a supported browser, 
you can refresh your screen and try again to sign in.
```

"Learn more" above links to https://support.google.com/accounts/answer/7675428?hl=en
