### ISSUE TITLE
After resuming from sleep get this exception.

### ISSUE THREAD

**Issue by cj-zeiger** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#374]
It doesn't break anything, but it did ask me to report it so here it is:

An uncaught exception was reported.  
#### Info:
**OS:** darwin
**Arch:** x64
**GPMDP Version:** 3.0.0
**Time:** Tue Mar 08 2016 09:59:51 GMT-0500 (EST)

#### Error:
*The Internet connection appears to be offline.: (null)*
```js
Error: The Internet connection appears to be offline.: (null)
    at Error (native)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
Client side network issues

**Comment by cj-zeiger** [comment]
Then why show vague exception and ask to report it? Can't this be handled gracefully with a message that doesn't involve asking the user to report it on github?

**Comment by MarshallOfSound** [comment]
@cj-zeiger To explain why this error appears and is not caught.  I was the only person working on this version, I put the error handler and the "report to github" link there so I could see the errors that occur when thousands of people use it.  Some errors I wouldn't be able to create if I tried.

Each of these errors that appear I am putting in custom catching code as they are reported.  They will not pop up for these errors in the next version
