### ISSUE TITLE
GMDP freezes at the first stage of updating the library

### ISSUE THREAD

**Issue by TomMaSS** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3741]
When i start player it's freezes at the first stage -  on updating the library. Nothing happening. it's just hung 

**OS:MacOS Catalina**

**GPMDP Version:v4.6.1**

**Issue Descriptions:freezes at the first stage of updating the library**

**Steps to Reproduce:**

**Comment by Satalink** [comment]
same here..

**Comment by JPvRiel** [comment]
Duplicates #3545?

**Comment by TomMaSS** [comment]
#3545 and #3660 not working for me

Cache dirs already removed

Bild with fix can't be installed in Catalina

**Comment by JPvRiel** [comment]
> #3545 and #3660 not working for me

Have you tried build 3751?

On #3660, https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3660#issuecomment-566217068 , build 3751 from master works for me.

To see all Linux and OSX builds:

```
curl -s "https://circleci.com/api/v1.1/project/github/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/3751/artifacts" | grep -o 'https://[^"]*'
```

For Linux I did:

```
curl -LOJ https://3751-40008106-gh.circle-artifacts.com/0/home/circleci/project/dist/installers/debian/google-play-music-desktop-player_4.6.1_amd64.deb
```

For OSX, the link would be: <https://3751-40008106-gh.circle-artifacts.com/0/home/circleci/project/dist/installers/darwin/Google%20Play%20Music%20Desktop%20Player.zip>

**Comment by TomMaSS** [comment]
That's was that build what i'm tried to use

Can't open, cause apple can't check for malwares
https://prnt.sc/qd2dee

**Comment by JPvRiel** [comment]
Okay, not an OSX user, but it seems while the library load issue is fixed in newer builds, maybe another issue is the builds are not notarized" for OSX? Maybe that only happens with official releases. With Catalina, you might have to wait for the next release.

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3610#issuecomment-550255818 modified an app file, which could be a hack around it, but didn't say which version of OSX. I doubt Apple's security would let app context be changed post install if they now insist on checking for notarized apps.

Incidentally, virustotal doesn't match any known malware: 

- URL: <https://www.virustotal.com/gui/url/30804f1ff31b85b8451b3d8b0a4265c016d6c3e689419fe46a3e69d99d2bb1bb/detection>
- File: <https://www.virustotal.com/gui/file/597a704d7058ad5f3c4f274246d7a1bf1714ce5a78daf88696746778f88f8a93/detection>

As a side-note, thanks to Google pushing YMP as a primary service, GMP software like this is likely to see less effort if it's heading to the end of the road for the service.

**Comment by jonnyruzek** [comment]
I'm also on macOS Catalina 10.15.2 , with a clean install of GMDP, and get the same thing:
<img width="1312" alt="Screen Shot 2019-12-19 at 9 56 27 AM" src="https://user-images.githubusercontent.com/39252765/71197452-e1d75300-224e-11ea-9b21-1cfdc17889ce.png">

**Comment by jakemco** [comment]
Not sure this is MacOS specific, I'm seeing the same screen as @jonnyruzek on Windows 10.

**Comment by wzub** [comment]
+1 on Windows 10

**Comment by KyleStaves** [comment]
+1 on Windows 10

**Comment by anthonysbrown** [comment]
Same here on windows 10

**Comment by JPvRiel** [comment]
@anthonysbrown , @KyleStaves and @wzub , tired the latest stable windows build from master?

Build 3751 also not working on Windows?

See: https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3660#issuecomment-566173496

**Comment by wzub** [comment]
> 
> 
> @jakemco, @anthonysbrown , @KyleStaves and @wzub , tired the latest stable windows build from master?
> 
> Build 3751 also not working on Windows?
> 
> See: [#3660 (comment)](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3660#issuecomment-566173496)

[Build 2827](https://ci.appveyor.com/project/MarshallOfSound/google-play-music-desktop-player-unofficial/builds/29394771/artifacts) fixed it for me on Windows 10.

**Comment by notMateo** [comment]
can also confirm, on two machines both running Windows 10

**Comment by hstaab87** [comment]
Also not working on Windows 10, new install.

**Comment by xneg** [comment]
@TomMaSS build 3751 provided by @JPvRiel works for me. You can run it without check for malwares with Ctrl + click -> Open.

**Comment by Oxnitron** [comment]
I have the same problem on Windows 10 (in Luxembourg if that matters)

**Comment by ParkhutRoman** [comment]
![зображення](https://user-images.githubusercontent.com/12161245/71255703-5685bc80-2337-11ea-8e0f-c72a5b6b95dd.png)
the same

**Comment by plasmicknight** [comment]
Also happening on Win7.

**Comment by KyleStaves** [comment]
@wzub following the post you linked and downloading the build here works for me:
https://ci.appveyor.com/project/MarshallOfSound/google-play-music-desktop-player-unofficial/builds/29394771/artifacts

**Comment by plasmicknight** [comment]
> @wzub following the post you linked and downloading the build here works for me:
> https://ci.appveyor.com/project/MarshallOfSound/google-play-music-desktop-player-unofficial/builds/29394771/artifacts

This works for me. Thanks!

**Comment by jmateusms** [comment]
> > @jakemco, @anthonysbrown , @KyleStaves and @wzub , tired the latest stable windows build from master?
> > Build 3751 also not working on Windows?
> > See: [#3660 (comment)](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3660#issuecomment-566173496)
> 
> [Build 2827](https://ci.appveyor.com/project/MarshallOfSound/google-play-music-desktop-player-unofficial/builds/29394771/artifacts) fixed it for me on Windows 10.

Works for me, too, on Windows 10

**Comment by TomMaSS** [comment]
still not work on catalina
