### ISSUE TITLE
Bitdefender thinks Player is infected

### ISSUE THREAD

**Issue by TrekMD** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3749]
I just installed the latest update to Google Play Music Desktop Player to address the problem with it being stuck and not loading the music list.  It worked fine one time and then Bitdefender started treating it like it has a virus and removed it.  I downloaded the installer from a link provided in the thread that addressed the prior issue I mentioned, so the file should be clean.  Any recommendations?  Thank you.

**Comment by jostrander** [comment]
This is probably because the RC and CI built packages for windows are not signed. This shouldn't be an issue once the main version is released.
