### ISSUE TITLE
Google won't let me log in anymore

### ISSUE THREAD

**Issue by TinyMysteries** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3751]
I noticed I wasn't getting scrobbles on last.fm, so I logged out.
But, then it wouldn't let me log back in. I just get this now.
I've uninstalled, reinstalled, and even tried older versions. Nothin'.

Then I made another gmail account to see if it would work.
I got through the motions, but then when it tried loading my library it was just stuck on loading.
I feel like there isn't anything else I can do and I feel so frustrated :<
![google sucks](https://user-images.githubusercontent.com/59193294/71399772-b956ac80-25f2-11ea-98a2-a4b0340eaeeb.png)

**Comment by lorddex** [comment]
> I noticed I wasn't getting scrobbles on last.fm, so I logged out.
> But, then it wouldn't let me log back in. I just get this now.
> I've uninstalled, reinstalled, and even tried older versions. Nothin'.
> 
> Then I made another gmail account to see if it would work.
> I got through the motions, but then when it tried loading my library it was just stuck on loading.
> I feel like there isn't anything else I can do and I feel so frustrated :<
> ![google sucks](https://user-images.githubusercontent.com/59193294/71399772-b956ac80-25f2-11ea-98a2-a4b0340eaeeb.png)

same here, probably it's something related to the version of the browser used in the application

**Comment by sylleryum** [comment]
same here

**Comment by Epithumia** [comment]
Same here, it's stuck on "loading music library".

**Comment by jostrander** [comment]
See pinned issues.

**Comment by mjaverto** [comment]
I had no idea this existed until I had this issue today: https://ci.appveyor.com/project/MarshallOfSound/google-play-music-desktop-player-unofficial

You can get the latest build from master there.
