### ISSUE TITLE
Tried YTM, but wanted to go back to normal google play, can't figure out how?

### ISSUE THREAD

**Issue by NextRaven** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3755]
**WIndows 10:**

**4.6.1**

**Cannot figure out how to revert back to google play music from youtube music:

I've uninstalled and reinstalled multiple times, cannot seem to revert back to google play music.**

**Click on YTM beta:**

-=EDIT=-

NVM was downloaded an older version by mistake, Downloaded new version added the switch back button.

**Comment by jostrander** [comment]
Use the tray icon, right click and hit Goole Play Music

**Comment by svoboda-rabstvo** [comment]
@jostrander doesn't work  for me 
OS: Windows 10 
Version: 4.7.0

**Comment by jostrander** [comment]
You right clicked the tray icon and switched back to GPMDP? Send a screenshot of the menu

**Comment by svoboda-rabstvo** [comment]
@jostrander thanks a lot, Its works :) My mistake
I hope that case will be fixed soon
