### ISSUE TITLE
Can not login. Untrusted browser.

### ISSUE THREAD

**Issue by radjah** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3757]
**OS:** Windows 10 x64 Pro 10.0.18363

**GPMDP Version:** 4.6.1

**Issue Descriptions:** Can not login to my account.

**Steps to Reproduce:**
1) Delete "c:\Users\\[login]\AppData\Roaming\Google Play Music Desktop Player\"
2) Launch application
3) Try to login
4) 
![изображение](https://user-images.githubusercontent.com/1141613/71482603-93105700-2814-11ea-9196-2bff6bec7504.png)

> Возможно, этот браузер или приложение небезопасны. Подробнее…
> 
> Попробуйте сменить браузер. Если вы уже используете поддерживаемый браузер, обновите страницу и попробуйте войти ещё раз.

[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/4002966/debug_info.zip)

**Comment by jostrander** [comment]
Duplicate of #3545
