### ISSUE TITLE
Get stuck on Loading Music Library on Mac Catalina 10.15.2 (19C57)

### ISSUE THREAD

**Issue by dgutie10** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3758]
**Checklist:**

* [ ] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x ] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [ ] I have double checked and can reproduce the issue

**OS:**
MacOS Catalina 10.15.2 (19C57)
**GPMDP Version:**
4.6.1
**Issue Descriptions:**
When launching the app it gets stuck on  loading music library
**Steps to Reproduce:**
Download version on PC
Launch app

![Screen Shot 2019-12-26 at 3 50 02 PM](https://user-images.githubusercontent.com/6596516/71490151-67cb3f00-27f7-11ea-8dd0-e41539c0d06f.png)

**Comment by jostrander** [comment]
Hello, see #3660
