### ISSUE TITLE
Browser not supported

### ISSUE THREAD

**Issue by mfallen** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3759]
Hi there,

started the app (Win10) after a long time again...now I get error saying browser not supprted after login with my google account.

Installed latest version (4.6.1), does not help.

Attached my debug info.

Maybe I made a mistake... ;-)

Thanks
Michael 
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/4005046/debug_info.zip)

**Comment by Ash2412** [comment]
Also getting the same issue, I've turned on allow less secure apps on my google account but still no luck.
![image](https://user-images.githubusercontent.com/10847854/71519954-986faf00-28b1-11ea-840d-0aecea58396a.png)

**Comment by g2p** [comment]
This seems to be #3545

**Comment by Ash2412** [comment]
> 
> 
> This seems to be #3545

Maybe but it only started happening a few days ago after reinstalling win10, didn't have an issue before that.

**Comment by jostrander** [comment]
Correct is #3545
