### ISSUE TITLE
Uncaught Exception: The Internet connection appears to be offline.: (null)

### ISSUE THREAD

**Issue by kjc1** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#376]
An uncaught exception was reported.  
#### Info:
**OS:** darwin
**Arch:** x64
**GPMDP Version:** 3.0.0
**Time:** Tue Mar 08 2016 15:40:08 GMT 0000 (GMT)

#### Error:
*The Internet connection appears to be offline.: (null)*
```js
Error: The Internet connection appears to be offline.: (null)
    at Error (native)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
Client side network issues
