### ISSUE TITLE
Unable to load music library

### ISSUE THREAD

**Issue by JasperSurmont** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3769]
Hey!

I am currently unable to load the app, it's stuck on Loading music library. I looked at [this](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3640) issue, but when entering DEV_MODE and looking at the console I have no error whatsoever.

Log file is in attachments; it says something about: "Failed to load bonjour with error: {}"

[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/4022670/debug_info.zip)

**OS:**
Windows 10
**GPMDP Version:**
V4.6.1

**Comment by jostrander** [comment]
Hello, #3660 is what you were looking for but there is an RC out with a fix #3761

**Comment by JasperSurmont** [comment]
Thanks for the fast response, my filter was set to open issues only, my bad.
