### ISSUE TITLE
Stuck in "Loading Music Library" after signing-in

### ISSUE THREAD

**Issue by TheArgentinian** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3779]
**OS:** Windows 10

**GPMDP Version:** 4.6.1

[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/4078906/debug_info.zip)

**Comment by Dazzel** [comment]
Update to 4.7.1. You may need to download it manually form [here](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/releases/tag/v4.7.1)

Its an known and fixed issue #3660

**Comment by jostrander** [comment]
Correct
