### ISSUE TITLE
OSX: Pressing the "X" to close the window exits the app instead of hiding it

### ISSUE THREAD

**Issue by scarroll825** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#378]
**OS:** OS X

**Issue Descriptions:** Normal OS X behavior is that "x-ing out" the window hides the window without exiting the application. When you do this with this app the application quits leaving only the status bar icon active.

**Steps to Reproduce:** Hit X in top right of window bar. Application quits and is removed from dock (if you don't have "Keep in dock" selected).

**Comment by MarshallOfSound** [comment]
I do not believe this is the case, unless you have unticked "minimize to task bar" and even then the app shouldn't quit, can you upload a screencast of the process you go through?

**Comment by chrismou** [comment]
I'm seeing something similar (possibly the same?).  It's actually really weird. I click the X and get this popup:

```
Just a heads up
Closing the main player window (what you just tried to do) will actually minimize the player to the System Tray. If you want to change this behaviour it can be changed in the "Desktop Settings" window.
```

But the white dot disappears from underneath the dock icon.  Clicking the icon again does nothing. The only way to get the player back for me was to click the status bar icon and select "show".

**Comment by MarshallOfSound** [comment]
Are running master or latest release?  I'm pretty sure I'm listening to the OS X dock "activate" signal and popping the player back up.

**Comment by chrismou** [comment]
3.0.0 binary, downloaded from the website

I could do you a screencast later when I'm home if it helps.

**Comment by chrismou** [comment]
Had a quick check and it _does_ seem to work with the master branch, though I don't have the icon pinned to dock so the circumstances are a little different.  Not sure that would make a difference though.

**Comment by MarshallOfSound** [comment]
Appeàrs that I fixed it after release

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/commit/454fc0a4a0345acf7891b9de557ab34c211d2274

**Comment by scarroll825** [comment]
Just downloaded the latest master release and it is working. However, "x-ing" out still stops the music while hiding with "CMD+H" does not.
