### ISSUE TITLE
Audio playblack randomly stops on macOS Catalina

### ISSUE THREAD

**Issue by jscheel** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3784]
**OS:**
macOS 10.15.2

**GPMDP Version:**
 4.7.1

**Issue Descriptions:**
Audio randomly stops, though the UI (usually) continues to update the progress bar. If I wait long enough, it will sometimes start back up (maybe by changing tracks). If I quit and restart the app, the audio will immediately work.

**Steps to Reproduce:**
Listen to music for a few minutes.

**Comment by jscheel** [comment]
I've restarted in dev mode and opened dev tools to see if anything seems out of place. Will report back shortly.

**Comment by jscheel** [comment]
Hmm, nothing obvious that I see. Any ideas why this might be happening? Any other logging I can do?

**Comment by jscheel** [comment]
I've played three songs. Of those three, one stopped in the middle, then started back up eventually. The two songs that played fine loaded their playback data through the google music api (the mplay endpoint) only once. The track that paused loaded the same play information 4 different times.

**Comment by sunpech** [comment]
I'm also having this issue. I've uninstalled/reinstalled the app and the issue still persists. I even removed ~/Library/Application Support/Google Play Music Desktop Player.

I did notice that before this issue started to occur, that my Internet connection was down for a bit. Perhaps it's related and there's some kind of corrupt cache?

**Comment by jscheel** [comment]
So, interestingly, I've been able to replicate the issue outside of this application, so I think it may be a problem with Google. If I open google music on Firefox, it throws a media decoding error when the music stops. I presented a ton of info to google's support chat, but they just ended up going around in circles with me for half and hour, asking me to re-install chrome four times _after_ I told them it was happening across all browsers and applications 🤦‍♂.

**Comment by jscheel** [comment]
Ok, I have interesting new information. When it happens, I can open my sound preferences and change the audio device to the internal speakers and the music will be playing. I can change to the external headphone port and the audio is not playing. Other audio (outside of application) plays on both. I happened to have Discord open when it happened last, and Discord thought a new audio device (MacBook Pro Speakers) had been discovered. It's almost like the audio devices are getting screwed up in macOS, and then Electron doesn't know what audio device to use.
