### ISSUE TITLE
Sorry, YouTube Music requires an Internet connection.

### ISSUE THREAD

**Issue by ondrejholy** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3787]
**OS:** up-to-date Fedora 31

**GPMDP Version:** 4.7.1 from flathub

**Issue Descriptions:** When I start GPMDP, "Sorry, YouTube Music requires an Internet connection." is shown. However, I am connected and https://music.youtube.com/ works properly in a browser. GPMDP worked nicely for me before few days as well. I am not aware of any network-related changes, but I run "flatpak update" and "dnf update" several times during the last days...

**Steps to Reproduce:**
 - `flatpak run com.googleplaymusicdesktopplayer.GPMDP`
 -  GPMDP window is shown with "Sorry, YouTube Music requires an Internet connection." 

I see the following output:
```
$ flatpak run com.googleplaymusicdesktopplayer.GPMDP 
Starting Sentry
error: Failed to load bonjour with error: {}
Bonjour is required to use Chromecast Support or to enable ZeroConf for the PlaybackAPI
On linux you need to install "avahi"
Error 10 (BadAccess (attempt to access private resource denied)): request 28.0
Error 10 (BadAccess (attempt to access private resource denied)): request 28.0
```

**Comment by jespersh** [comment]
Might want to raise it with https://github.com/flathub/com.googleplaymusicdesktopplayer.GPMDP/ if non-flatpak works

**Comment by ondrejholy** [comment]
I haven't been aware that also rpm packages are available, [google-play-music-desktop-player-4.7.1.x86_64.rpm](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/releases/download/v4.7.1/google-play-music-desktop-player-4.7.1.x86_64.rpm) seems to work properly. Can some of the admins transfer the issue there, please?

**Comment by ondrejholy** [comment]
I've tried to reinstall the flatpak the following way and now it shows just empty window :-(
```
flatpak uninstall --delete-data com.googleplaymusicdesktopplayer.GPMDP
flatpak install com.googleplaymusicdesktopplayer.GPMDP
```

**Comment by ondrejholy** [comment]
After some system updates and rebooting it started working again, so closing.
