### ISSUE TITLE
TLS Certificate Expired

### ISSUE THREAD

**Issue by DanielJStevens** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3789]
Let's Encrypt certificate has expired (as of today) 31/01/2020 (GMT).
https://www.googleplaymusicdesktopplayer.com/

You should consider automating the renewal (this is possible Let's Encrypt).

Looking through the issues, this has happened in the past before.

**Comment by MarshallOfSound** [comment]
It's running on a server that is very overloaded, sometimes the renew job fails 🤷‍♂

**Comment by DanielJStevens** [comment]
When is it renewing? Once just before expiry?

See this:
https://community.letsencrypt.org/t/why-is-certbot-attmepting-renewal-daily/37795

> Part of the functionality of certbot renew is to attempt to renew only those certificates that are less than 30 days away from expiry. The default behavior is certbot renew --keep-until-expiring, which does not attempt to renew every certificate on your system; that would be the behavior of the alternative form certbot renew --force-renewal, which is not recommended under most circumstances.
> 
> Because of this, we feel comfortable recommending that certbot renew be run twice per day so that renewal attempts happen promptly when certificates reach 30 days from expiry. However, if you have a specific reason why you don’t want this check to happen this often, that’s fine, of course. I just want to make sure that it’s clear that under normal circumstances this is not going to renew every certificate every day.

This is from an old post but still applies? I still don't see why the certificate **_should_** expire at all unless the server is so overloaded the renewal attempts fail all the way through to the expiry date.
