### ISSUE TITLE
Couldn't Fetch Recommendations. Please Try Again

### ISSUE THREAD

**Issue by chrisporter415** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3792]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:** Windows 10

**GPMDP Version:**  V4.7.1

**Issue Descriptions:** Anytime I try to use the home button or the Browse Stations button, I get the message "Couldn't Fetch Recommendations. Please Try Again".  This only occurs on my PC using the desktop app, but not when I go to google play music in a browser or on my phone.
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/4187429/debug_info.zip)

**Steps to Reproduce:**

**Comment by ericralph** [comment]
Same issue here, been happening for the last week or so. Unclear when it started but I think it began independently of any particular update.

**Comment by MitchellMcCluskey** [comment]
I found that switching to YTM it asked my to sign in again, I signed in and then switching back to GPM solved this issue for me.

**Comment by ericralph** [comment]
Thanks, Mitchell. That did somehow fix it!

**Comment by jayjb** [comment]
Signing in and out of the app fixed it for me.

**Comment by chrisporter415** [comment]
Signing in and out in YTM and then switching back to GPM seems to have fixed it for me too!  Thank you

**Comment by AnnanFay** [comment]
Please reopen the issue.

It's still an issue affecting other people even if there is a workaround. Closing it implies it's no longer an issue and doesn't need to be fixed.

At the very least this fix should be added to the FAQ before closing the issue.
