### ISSUE TITLE
Enable/disable song name popup

### ISSUE THREAD

**Issue by baleksey** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#38]
It should be option to disable song popup (at the bottom right corner of the screen) because It distracts (I got mail messages there, for example) and I don't want to know each time what song is playing right now as I'm listening to known music and already know them all.

But the main complain about distraction which I can't turn off.

**Comment by MarshallOfSound** [comment]
This is a duplicate of #23 

This is in master and will be in the next release
