### ISSUE TITLE
Rename GPDMD_STORE on Linux

### ISSUE THREAD

**Issue by davorb** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#380]
On Linux, the settings are stored in ```~/GPMDP_STORE/.settings.json```. 

It would be much better if you stored them in ```.GPMDP_STORE``` instead, so that the folder isn't cluttering up my home folder. Or maybe even move it to ```~/.local/share/gpmdp```.

**Comment by MarshallOfSound** [comment]
There are PR's (2) I think open to fix this issue.  And an issue somewhere else aswell See #267
