### ISSUE TITLE
Login link that redirects to browser

### ISSUE THREAD

**Issue by leetNightshade** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3801]
Point blank: I don't trust entering my password into your app. I'm not going to comb the source code to see what you do with it.

I personally would prefer a sign in link that redirects to my default browser of my choice.

Just voicing my thought. Thanks.

**Comment by MarshallOfSound** [comment]
> I personally would prefer a sign in link that redirects to my default browser of my choice.

This is not possible, their is no oauth or token based sign in flow for GPM or YTM.  We don't do anything with your password, we literally just load the google sign in page and let you do your thing 🤷‍♂ 

What you do is up to you though, but there is no other way we can do this
