### ISSUE TITLE
Lyrics scrolling even when "Scroll lyrics" is turned off

### ISSUE THREAD

**Issue by RadGH** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3805]
**Checklist:**

* [X] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there

* [X] I have double checked and can reproduce the issue

**Debug info:
[**debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/4285033/debug_info.zip)

**OS:** win10 64bit

**GPMDP Version:** 
I don't know how to check. I assume it is the latest (it updated in january)

**Issue Descriptions:** 
I have lyric scrolling turned off. Sometimes they scroll anyway. That's not too bad except I like to scroll through them myself. It hijacks my mouse scroll and stutters, sending me back to where it thinks the lyrics are playing.

Note that the lyrics are also way off sometimes, where I'm listening to words that are still off screen. That's another problem but I don't care about that. Pretty sure that's just from some songs having long intros or outros.

**Steps to Reproduce:** 
Unfortunately this may not be easy. Turn lyric scrolling off, it works as intended for awhile. I don't check lyrics often but I leave the player running all the time. At a certain point it scrolls by default (even if you check/uncheck the option) until you fully restart the program. This may be a long term thing by putting my computer in sleep mode at night and leaving it on most of the time, so the program is running for days at a time.

Anyway, moving the scrollbar works but you have to hold your mouse button down. If you let go it resets position. You can middle click to scroll but that just flickers and constantly resets scroll position.

Here is a video of the issue: https://radleysustaire.com/s3/d72534/ I try turning the option on and off and you can see the feature is just buggy in both modes. Note that my video only captures at 15fps so the stuttering when trying to scroll doesn't show very well. It's bad though, can't read the text.

ALSO the scrollbar disappears after about 2 seconds if you don't move your mouse. It does not reappear. So you have to be quick and start scrolling immediately if you want to scroll manually. And still you have to hold your mouse button down. It's just really, really clunky.

**Comment by kirwinia** [comment]
We also have this problem. We've tried going into settings, enabling scrolling, closing, re-opening settings, turning it off again and then viewing lyrics... and it still does it.

Even adding an app restart to the steps only SOMETIMES fixes it.

A very weird intermittent bug, hoping it gets whacked soon.

**Comment by MarshallOfSound** [comment]
Fixed in #3830
