### ISSUE TITLE
OSX monochrome menu bar icon option

### ISSUE THREAD

**Issue by ajacobson** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#381]
**OS:**
Mac OS X

**Issue Description:**
It would be nice to have an option for the menu bar icon to be monochromatic.  The current menu bar icon style doesn't match several other menu bar icons I have:

![screen shot 2016-03-08 at 11 35 23 am](https://cloud.githubusercontent.com/assets/617552/13608516/21f7c9f0-e523-11e5-931e-1a35047e0ac4.png)
![screen shot 2016-03-08 at 11 41 35 am](https://cloud.githubusercontent.com/assets/617552/13608517/21fb5c50-e523-11e5-82ba-a011381a3c6b.png)

**Comment by chrismou** [comment]
FYI it looks like this has been implemented on the master branch, so you'll probably see it in the next release

**Comment by chrismou** [comment]
<img width="127" alt="screenshot 2016-03-08 18 00 35" src="https://cloud.githubusercontent.com/assets/319883/13610891/c25071e8-e557-11e5-957b-910d1bb776d5.png">

:-)

**Comment by MarshallOfSound** [comment]
@ajacobson What @chrismou said.  It's in master and will be in the next release

**Comment by Nxt3** [comment]
I'm not seeing this on 3.0.1.
