### ISSUE TITLE
Alt forward/back no longer navigates pages

### ISSUE THREAD

**Issue by Slapbox** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3811]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue (at least on my own machine...)

**OS:** Windows 7

**GPMDP Version:** Shockingly cannot find this... Where do I look?

**Issue Descriptions:** <kbd>Alt+Left</kbd> & <kbd>Alt+Right</kbd>

**Steps to Reproduce:** Navigate through pages with mouse and then try to go back using <kbd>Alt+Left</kbd>

**Comment by fjwbarnard** [comment]
> **GPMDP Version:** Shockingly cannot find this... Where do I look?

`Right-Click` the tray icon then navigate to Help -> About and you should see the version: 
![image](https://user-images.githubusercontent.com/20688586/79001415-b99d9800-7b4e-11ea-8fff-3d518722f176.png)

**Comment by Slapbox** [comment]
Thanks for the tip! Surprisingly, on Windows 7 that just makes the app window appear, but does nothing else. 

I do see from the folder structure though that I'm on `4.7.1`

**Comment by Slapbox** [comment]
Mysteriously working again in `4.7.1`. Very strange. The issue persisted through reboots and regardless of other apps I had open that had any sort of global hotkey handling, but now just works. Will re-open if this issue reoccurs.
