### ISSUE TITLE
Certificate https://www.googleplaymusicdesktopplayer.com/ expired

### ISSUE THREAD

**Issue by Jeltel** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3812]
@MarshallOfSound The Certificate of https://www.googleplaymusicdesktopplayer.com/ has expired at the end of March.

![afbeelding](https://user-images.githubusercontent.com/1732436/78233290-caf2fe80-74d5-11ea-9a83-712ab6d620ea.png)

Please fix that to be able to share this application to other people :)

**Comment by stgarf** [comment]
It looks as if this cert was properly updated on 29 March 2020 PDT:

![Screen Shot 2020-04-02 at 11 59 16](https://user-images.githubusercontent.com/1694002/78290959-6f2a7480-74d9-11ea-9db1-a2c4ba25da31.png)

This can probably be closed.

**Comment by Jeltel** [comment]
Correct. Works now :)
