### ISSUE TITLE
App Won't Completely Launch

### ISSUE THREAD

**Issue by Soxcks** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3814]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**
Mac 10.15.4

**GPMDP Version:**
Version 4.7.1 (4.7.1)

**Issue Descriptions:**
On initial launch, the app hangs on the multi-coloured spinner animation with a white background. My CPU jumps to 100% in the Mac Activity Monitor.

**Steps to Reproduce:**
Using jenv, set your JVM to OpenJDK 11.0.6
```bash
jenv verions    # Note the 11.0.6 version
jenv global ${version_name}
```
Now run the GPMDP app, and the problem will occur. The app will not launch.
Changing the JDK back to version 8 (release 241) fixes the issue.
```bash
jenv global 1.8.0.241
```

**Comment by jostrander** [comment]
That is an extremely strange bug. This app doesn't use JVM for anything at all as far as I'm aware on any platform. Is there something else going on with jenv that might be causing side effects to the system as a whole?

**Comment by Soxcks** [comment]
@jostrander I thought the same regarding Node/JVM. Maybe NodeJS makes lower level calls to some JAVA API's on Mac? Does this app directly use the `java` package anywhere? Sounds silly but I don't know what else would cause the problem. 

Can I coillect some logs for you? How do I do that?

**Comment by jostrander** [comment]
Not that I'm aware of. The app does call out to bonjour for chromecast on mac, and has some native modules for the touch bar etc, but nothing that touches the JVM. If you run the app in developer mode you can open the console with cmd shift I and read the logs there. To get into dev mode you can launch the go to url (cmd shift g?) and type "DEV_MODE" and hit go.

**Comment by Soxcks** [comment]
... I now for the life of me cannot re-produce the issue. I had tried opening it several times and got the issue. I downloaded a fresh copy and ran it without copying to `/Applications`. Always the same. The moment changed my JVM with jenv, all was fine.

I tried using the OpenJDK 11.0.6 (LTS) and also the latest OpenJDK 13 just now and it's working fine.

Sorry to waste your time!

**Comment by jostrander** [comment]
No worries.
