### ISSUE TITLE
Can't load the program

### ISSUE THREAD

**Issue by mrdudu** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3815]
I can't get the program to open. It gets stuck on this screen below.
It passes the "Loading music library" screen, but then it gets stuck on this screen.

ps. I've tried: 
- ensuring that windows firewall has given it an exception to pass
- the solution from ddsol in: Stuck on "Loading music library" #3640

![gp](https://user-images.githubusercontent.com/2381683/79034704-b44a5700-7bfb-11ea-9907-cee157de999a.jpg)

**OS:**
Win 10
LENOVO Yoga Laptop

**GPMDP Version:**
V4.7.1

**Comment by mrdudu** [comment]
I would love an urgent answer to this question as I now have to use Zoom for my work. I am really keen to use this app and pay a donation, but I can't get it to open.

**Comment by jostrander** [comment]
Donation not neccessary, but try deleting your GPMDP or Google Play Music folder under `%appdata%` and `%localappdata%`.

**Comment by mrdudu** [comment]
Thanks @jostrander, so that just seemed to delete it off my computer altogether. I went back to the setup file and it still does the same loop.
I then deleted it again from the appdata/local dir, and then uninstalled it from Control Panel, and have now downloaded it again and reinstalled it. Exactly the same thing is happening. I get through the Loading Music Library screen and then I get the screenshot above indefinitely.

**Comment by jostrander** [comment]
Try opening the "go to" window with CTRL+SHIFT+G and type in "DEV_MODE" and press go. It will ask you if you want to restart, go ahead and do that. When it loads back up you should be able to open the console with `CTRL + SHIFT + I`. Take a screen shot of any issues you may have there.

**Comment by jostrander** [comment]
You can also try the debug info method:

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ#how-do-i-generate-this-debug-zip-file

**Comment by mrdudu** [comment]
Thanks @jostrander . I did what you said but I wasn't able to open the console with CTRL + SHIFT + I after doing the DEV-Mode thing. It just returned to the same screen I had before.

I've got the debug zip folder now. What do I do with it?

**Comment by jostrander** [comment]
Drag it into the text thing here and comment with it

**Comment by mrdudu** [comment]
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/4490170/debug_info.zip)
Thanks Jesse @jostrander

**Comment by jostrander** [comment]
No extra information in there unfortunately.

When you launch in DEV_MODE it won't look or act any different, but there will be additional functionality that _should_ be available. Once you open in dev mode you should be able to use the ctrl shift I shortcut or use the menu bar (you may have to press alt?) and hit, help then Toggle Developer Tools. If you can't get to the menu bar, try enabling system borders. You'll have to right click the tray icon down in the lower right corner (next to the clock) and hit settings and change it there, then restart.

**Comment by mrdudu** [comment]
OK I got to it @jostrander . Here is the screenshot

![g1](https://user-images.githubusercontent.com/2381683/79518250-f1976480-8093-11ea-8a98-0e733b6868ef.jpg)

**Comment by jostrander** [comment]
Almost there. See the console tab at the top? That will have more info, but I can see that there isn't going to be a whole lot in there, so there is actually _another_ layer deep to go to. I wish the debug tool would fetch the contents of these windows but unfortunately it doesnt. Anyway:

Hit console at the top, type `openGPMDevTools()` (it should start to show up when you type) and then press enter. Another window will show up. See if _that_ console window has any red or yellow messages and screenshot those.

**Comment by mrdudu** [comment]
thanks for your help @jostrander 

![g2](https://user-images.githubusercontent.com/2381683/79518600-dd079c00-8094-11ea-8aa1-57b146283a60.jpg)

**Comment by jostrander** [comment]
Well, I guess one more, Hit the arrow next to zA and take another screenshot.

**Comment by mrdudu** [comment]
Here you go @jostrander 
![g3](https://user-images.githubusercontent.com/2381683/79519557-88195500-8097-11ea-815f-9ff80df3bd8e.jpg)

**Comment by mrdudu** [comment]
Here's the full text that is hidden

cause
:
TypeError: Cannot read property 'localeCompare' of undefined at C:\Users\dnndn\AppData\Local\GPMDP_3\app-4.7.1\resources\app.asar\node_modules\gmusic-ui.js\dist\gmusic-ui.js:121:25 at Array.sort (native) at C:\Users\dnndn\AppData\Local\GPMDP_3\app-4.7.1\resources\app.asar\node_modules\gmusic-ui.js\dist\gmusic-ui.js:120:34 at Array.map (<anonymous>) at LibraryNamespace.getArtists (C:\Users\dnndn\AppData\Local\GPMDP_3\app-4.7.1\resources\app.asar\node_modules\gmusic-ui.js\dist\gmusic-ui.js:119:35) at LibraryNamespace.getLibrary (C:\Users\dnndn\AppData\Local\GPMDP_3\app-4.7.1\resources\app.asar\node_modules\gmusic-ui.js\dist\gmusic-ui.js:100:23) at C:\Users\dnndn\AppData\Local\GPMDP_3\app-4.7.1\resources\app.asar\node_modules\gmusic-ui.js\dist\gmusic-ui.js:92:57 at lO.o.dispatchEvent (C:\Users\dnndn\AppData\Local\GPMDP_3\app-4.7.1\resources\app.asar\node_modules\gmusic-ui.js\dist\gmusic-ui.js:956:8) at lO.o.dispatchEvent (C:\Users\dnndn\AppData\Local\GPMDP_3\app-4.7.1\resources\app.asar\node_modules\gmusic-ui.js\dist\gmusic-ui.js:957:63) at lO.o.dispatchEvent (C:\Users\dnndn\AppData\Local\GPMDP_3\app-4.7.1\resources\app.asar\node_modules\gmusic-ui.js\dist\gmusic-ui.js:957:63)
message
:
"Error in protected function: Cannot read property 'localeCompare' of undefined"
stack
:
"TypeError: Cannot read property 'localeCompare' of undefined↵    at C:\Users\dnndn\AppData\Local\GPMDP_3\app-4.7.1\resources\app.asar\node_modules\gmusic-ui.js\dist\gmusic-ui.js:121:25↵    at Array.sort (native)↵    at C:\Users\dnndn\AppData\Local\GPMDP_3\app-4.7.1\resources\app.asar\node_modules\gmusic-ui.js\dist\gmusic-ui.js:120:34↵    at Array.map (<anonymous>)↵    at LibraryNamespace.getArtists (C:\Users\dnndn\AppData\Local\GPMDP_3\app-4.7.1\resources\app.asar\node_modules\gmusic-ui.js\dist\gmusic-ui.js:119:35)↵    at LibraryNamespace.getLibrary (C:\Users\dnndn\AppData\Local\GPMDP_3\app-4.7.1\resources\app.asar\node_modules\gmusic-ui.js\dist\gmusic-ui.js:100:23)↵    at C:\Users\dnndn\AppData\Local\GPMDP_3\app-4.7.1\resources\app.asar\node_modules\gmusic-ui.js\dist\gmusic-ui.js:92:57↵    at lO.o.dispatchEvent (C:\Users\dnndn\AppData\Local\GPMDP_3\app-4.7.1\resources\app.asar\node_modules\gmusic-ui.js\dist\gmusic-ui.js:956:8)↵    at lO.o.dispatchEvent (C:\Users\dnndn\AppData\Local\GPMDP_3\app-4.7.1\resources\app.asar\node_modules\gmusic-ui.js\dist\gmusic-ui.js:957:63)↵    at lO.o.dispatchEvent (C:\Users\dnndn\AppData\Local\GPMDP_3\app-4.7.1\resources\app.asar\node_modules\gmusic-ui.js\dist\gmusic-ui.js:957:63)"
__proto__
:
$a

**Comment by jostrander** [comment]
Just out of curiosity, do you have another account you can try? You'll probably have to delete the two folders again and reinstall if you do. You have a localized version of Google Play, so I can't test directly, but I'm thinking there is an error in a track in a playlist you have.

**Comment by mrdudu** [comment]
I'll try when I get home shortly.
I have downloaded some of my own edited music to Google Play. Not sure if
those tracks are the problem? I do need them though as part of my work.

Cheers,
David

**Comment by mrdudu** [comment]
I tried with a new google account - I switched my gmail and google play music to the new google account in Chrome - is that what you mean? I also went to the main Google account page in Chrome and also signed in with the new account.

I reinstalled the app (after deleting the app>local folder).
It is still doing the same thing, however the google account logo in the top right corner of GPMDP is the logo from my previous google account, not the new google account. So I'm not sure how else to get it to recognise a diff google account?

**Comment by PLPeeters** [comment]
I have been having a similar issue since yesterday and finally managed to fix it. In my case, when opening the client, it was stuck in the loading state forever (the one before you even see the menus, with the circular multi-color loader). The error in the GPM dev tools was this:

<img width="796" alt="Screenshot 2020-04-17 at 09 20 07" src="https://user-images.githubusercontent.com/3260909/79542991-f573b880-808c-11ea-93de-958cc94f7aa0.png">

The full URL of the file that fails to load is https://www.google.com/js/bg/8I8Z3wELRgTel2-lhKD1Oru5BR-ljaMim1LAbhzxuu8.js, which [seems to be some kind of anti-bot script](https://stackoverflow.com/questions/21762076/why-does-gmail-use-eval).

The way I fixed it:

1. Reopen GPMDP in dev mode by pressing CTRL/CMD + SHIFT + G and typing in DEV_MODE
2. When it reopens, press, CTRL/CMD + ALT + I to open the dev tools
3. Go to the Console tab, type `openGPMDevTools()`
4. In the new inspector that opened, go to the Network tab and check the "Disable cache" checkbox

For me GPMDP loaded as soon as the checkbox was checked, no other action required. I then unchecked the box and restarted GPMDP and now it works like a charm.

(this is on macOS with the latest version (4.7.1); I wasn't sure if this warranted a new issue or not as this does seem somewhat related even though the error message is different)

**Comment by mrdudu** [comment]
Thanks @PLPeeters. I tried all of that, and nothing happened when checked the "Disable cache" checkbox. Perhaps this is a different issue?

**Comment by jostrander** [comment]
You need to delete the other folder as well, the AppData\Roaming\ one. Either GPMDP_3 or Google Play Music Desktop Player, I can never remember which is in which folder. You are still signed into the original account in the player.

**Comment by mrdudu** [comment]
@jostrander I tried that and it worked. So it looks like the program works with the new google account. So how can I get it to work with my main account?

**Comment by jostrander** [comment]
It looks like you might have a track that doesn't have an artist maybe in your library? I know that sounds vague but that's all I can gather from the error. I might be able to reproduce, but it'll take me a few.

**Comment by mrdudu** [comment]
@jostrander BREAKTHROUGH!!
I went through and found tracks that I had added and gave them a dummy Artist/Album Artist/Album. And now it is opening properly. I only did it to half of them but it seems to be enough to make it work!

Now I'm trying to get the remote control app to work. Can you please send the link to the instructions about that. I can't find them anywhere. Thanks,D.

**Comment by jonathanhle** [comment]
@PLPeeters thank you so much!  I had the exact same issue.  toggling "Disable cache" worked like a charm.  

What put me into the weird loading state was trying out YT Music then trying to switch back to Play.

**Comment by mrdudu** [comment]
sorted
