### ISSUE TITLE
Can't open the program

### ISSUE THREAD

**Issue by mrdudu** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3816]
Hi guys, I'm really desperate to get this program working as my work is moving online and I need this to be able to DJ on zoom. I get past the music library page, but then it gets stuck on this page below.

I've tried deleting my GPMDP or Google Play Music folder under %appdata% and %localappdata%. and reinstalling but I keep getting the same problem

![gp](https://user-images.githubusercontent.com/2381683/79513932-62d11a80-8088-11ea-944d-8c06d81c86da.jpg)

**OS:**
Windows 10

**GPMDP Version:**
V4.7.1

**Comment by jostrander** [comment]
It's good etiquette to not open multiple issues on Github for a singular issue, closing in favor of your previous issue.
