### ISSUE TITLE
YTM Feature Request: Playlist Sorting and Filtering

### ISSUE THREAD

**Issue by lanespade** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3853]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES AS WELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**

macOS Catalina

**GPMDP Version:**

4.7.1, Youtube Music Desktop Player (Beta)

**Issue Descriptions:**

Unable to sort / filter songs in my playlist, would be super valuable

**Steps to Reproduce:**

1. Open GPM / YTM (BETA)
2. Switch to YTM (BETA) if necessary
3. Select any playlist (create one if necessary and add 2 songs)
4. No text box to filter, no headers to sort, only able to drag and drop to re-order

**Comment by jostrander** [comment]
Major UI modifications like this are generally a non-starter due to the nature of the language in which YTM is actually written in. They use polymer, and hooking into polymer to add these features is a huge pain, and if possible, next to impossible to maintain.

**Comment by lanespade** [comment]
Thanks for responding @jostrander! Huh, not sure I would consider sorting and filtering major UI modifications... and I am not familiar with Polymer, but it looks like it has built-in support in [V3](https://polymer-library.polymer-project.org/3.0/docs/devguide/templates#filtering-and-sorting-lists) and even [V1](https://polymer-library.polymer-project.org/1.0/docs/devguide/templates#filtering-and-sorting-lists)...

**Comment by jostrander** [comment]
Under normal circumstances I would agree. If we had the source for the YTM website it would be fairly trivial. However we are doing it after the fact, and the YTM is a SPA interface built on Polymer, so its not like we can simply reorder the data and redraw the html. The underlying data source would need to be modified and then poylmer would need to recognize that data change and re-render the list. I'm not saying its impossible, just a maintenance nightmare, as any changes to the source may render our addon unusable, or maybe even break the player for all involved.

**Comment by lanespade** [comment]
Ah, OK... well I hope they add this basic functionality soon then 🤞
