### ISSUE TITLE
how to add local media?

### ISSUE THREAD

**Issue by Emilinrose** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3855]
I've moved all my music and playlists from my phone to computer, how do i make it read them?

**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES AS WELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**

**GPMDP Version:**

**Issue Descriptions:**

**Steps to Reproduce:**

**Comment by Its-treason** [comment]
You need to use Chrome. Open [Google Play Music](https://play.google.com/music/listen?u=0) and drag your music into the Chrome window. You also need to install a Chrome extension, but the website will guide on how to do that.

**Comment by jostrander** [comment]
Yes, music can only be added from Chrome. This app can't implement that feature unfortunately.
