### ISSUE TITLE
Rammsteins albums and songs doesnt show up.

### ISSUE THREAD

**Issue by kfk2312** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3865]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES AS WELL**
* [ ] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [ ] I have double checked and can reproduce the issue

First off. Thanks for your work! much appreciated! like really, THANK YOU!

**OS:** Windows 10 pro

**GPMDP Version:** latest 20/7/2020 (sry cant find)

**Issue Descriptions:** Rammsteins albums, and there for, songs/collection doesnt show up in desktop player, but are available in browser.

**Steps to Reproduce:** search Rammstein.

best wishes!

**Comment by aeantipov** [comment]
AFAIK, this is a licensing issue of Google Music and has nothing to do with the app. It is available through youtube music beta.

**Comment by jostrander** [comment]
Sounds right, definitely a licensing issue.
