### ISSUE TITLE
YTM JSON API links to low resolution file for album art

### ISSUE THREAD

**Issue by dr808** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3869]
**Checklist:**

* [X] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES AS WELL**
* [X] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [X] I have double checked and can reproduce the issue

**OS:** macOS

**GPMDP Version:** 4.7.1

**Issue Descriptions:** Output of JSON API,`playback.json`, under `song.albumArt`, album art links to a small/low-res file when using YTM.  Unlike GPM, where it links to a larger/high(er)-res file.

**Steps to Reproduce:** 
 0 Use YTM
 1 Play song with JSON API enabled
 2 open `playback.json`
 3 Download file at location `song.albumArt`
 4 see lowres file
 5 be sad
vs GPM:
 0 Use GPM
 1 repeat steps 1-3 from above
 2 see higher-res file
 3 be happy

**Comment by ai9-** [comment]
Hey @jostrander , hope I'm not just missing something obvious but your fix doesn't seem to work? The `.replace` operation you added also doesn't seem to work if I throw it into other JS interpreters like the chrome/firefox console.

**Comment by jostrander** [comment]
You are right, I accidentally added quotes to the regex. I'll push an update.

**Comment by ai9-** [comment]
Right, I knew it was something kind of obvious. I really missed it though 😂
