### ISSUE TITLE
Taskbar no longer shows Artist/track info on hover

### ISSUE THREAD

**Issue by roryhewitt** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#387]
OS: Windows 7 Enterprise (64-bit) SP1

Issue: Taskbar no longer shows Artist/track info on hover

Steps to Reproduce: Hover over the taskbar icon. The tooltip (including the previous/pause/next controls) displays, but rather than the artist/track info, just the "Google Play Music Desktop Player" text appears. I have the "Show song information always" setting checked. No hotkeys specified. Minimize to Tray is not set either.

![gpmdp](https://cloud.githubusercontent.com/assets/11558891/13613925/f92f9bc4-e522-11e5-9f53-a148239e7b8a.png)

**Comment by MarshallOfSound** [comment]
Can you explain why you need/want this.  It was reported somewhere as bad practice for your app to have a title other than your apps name.

If someone went through task manager and saw an app called "Justin Beiber - Sorry" they would cry murder and have no idea what it is.

So yeah, why do you want this?

**Comment by glundgren93** [comment]
I'm not sure whether it's bad practice or not. But I can tell you that Spotify shows Artist/track info on hover. 

![capture](https://cloud.githubusercontent.com/assets/3113318/13623038/48467ebc-e582-11e5-9902-f0ed17987ec2.png)

**Comment by MarshallOfSound** [comment]
I believe that is so that other apps can read the currently playing song.  We have the JSON and WebSocket API for that?

**Comment by rgoliveira** [comment]
I can undestand changing the title of the app as being a bad practice, but this was a nice thing to have.

When I'm listening to a radio, for instance, sometimes I just want to check the current song title and artist. Just hovering over the taskbar is a nice way to do that.

Maybe make this as an option (off by default)?

**Comment by MarshallOfSound** [comment]
@rgoliveira There is a point when it comes to options that I simply have to draw the line.  I don't what the app to become a whole load of

```js
if (Settings.get('shouldDoThisObscureThing') {
    doTheThing();
}
```

It's supposed to be simply and easy to maintain and making small options for things that only one platform and at that only a few people on that platform will use / even notice just doesn't seem worth the code smell to me

**Comment by roryhewitt** [comment]
Samuel,

The only reason I raised this as an issue is because prior to the latest
upgrade, I thought it used to display the artist/title. Am I wrong?

FWIW, I'm pretty sure that many other audio players display this info add a
tooltip. I know Winamp does...

But I totally get that this is a nice-to-have rather than a requirement...

Like @rgoliveira, I just like to quickly be able to see the track info,
without needing to open the window. If you can add it as an option, that
would be cool. But completely understand if you don't want to spend time
adding bloat.

**Comment by Sensei-Hanzo** [comment]
I would also like to show my support for this feature. I used it a lot when it was in the old version and was disappointed to see it removed. I kind of get what you mean about it being "bad practice", but personally that's not something that bothers me; the convenience of being able to mouseover the taskbar icon to view the currently playing track far outweighs that. Alternatively, is there any way you could have the track info show in the window that pops up without changing what's in the title bar?

**Comment by MarshallOfSound** [comment]
I'm going to close this for the following reasons.

1. Yes, this was in the old app.  The old app however was exclusively using a custom window frame.  This meant that the app's title could be whatever i wanted and it wouldn't show up anywhere apart from the taskbar popup.  This is no longer the case, on OS X and Linux the actual window title would change and this is not a good UX.
2. As mentioned before, it is an anti-pattern (at least IMO)
3. It would break things in the works like the Chromecast implementation (*winks*)

If someone wants to implement a secret setting to change this behavior by all means PR it and I'll consider.  But I don't see enough of a reason to implement this.

I'll leave it open for 24hours and let people have a pot shot at those 3 points and we'll see how it goes.

**Comment by jostrander** [comment]
Implemented it as a secret setting. I do agree with all three of your points, but I would personally find something like this useful. I would have done it via Tooltip only, but electron doesn't implement any way to make this happen on any OS.

**Comment by roryhewitt** [comment]
@jostrander since you implemented this as a secret setting, does this mean that in order to be able to see it, I have to download the source and build it on my machine?

**Comment by rgoliveira** [comment]
@roryhewitt no. That only means there's no visual option in the app. You have to set it by hand on the config file (on Windows it's `%USERPROFILE%\AppData\Roaming\Google Play Music Desktop Player\json_store\.settings.json`).

**Comment by roryhewitt** [comment]
@rgoliveira 

Groovy :)

**Comment by rgoliveira** [comment]
It'll look like this:
![image](https://cloud.githubusercontent.com/assets/1731173/14257727/6ec29f96-fa75-11e5-8ae6-1a9e6d7578de.png)

**Comment by roryhewitt** [comment]
Works for me. I am a happy bunny :)
