### ISSUE TITLE
Certificate for googleplaymusicdesktopplayer.com expired (2020-07-29)

### ISSUE THREAD

**Issue by OrBin** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3870]
Same as #3812 and #3847, but on July 29.

Expired: Thursday, July 29, 2020 at 21:06:46 UTC.

BTW, if the certificates are issues by LetsEncrypt, why won't you use [certbot](https://certbot.eff.org/)? It can handle automatic renewal on time quite easily.

**Comment by jostrander** [comment]
IIRC, and I have no access to this, the cert is certbot, but I think the issue is the cert is applied and nginx doesn't restart, so it still serves the old cert.

**Comment by OrBin** [comment]
I'm not sure this should be an issue. AFAIK certbot should handle
everything that's required for the update.

**Comment by devksingh4** [comment]
Issue no longer present, new cert expires on Sunday, September 27, 2020.
