### ISSUE TITLE
YTM Playback.json Song info NULL

### ISSUE THREAD

**Issue by VFSniper** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3881]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES AS WELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**
Windows 10 1909
**GPMDP Version:**
4.7.1
**Issue Descriptions:**
Playback.json is not populating fields for song and rating info correctly when using YTM 

Also can be seen as GPMDP isn't displaying Song/Artist on at the top of the window

**Steps to Reproduce:**

1. Select YTM
2. Play a song
3. Check playback.json file. Notice that song and rating sections are not updated correctly. 

![image](https://user-images.githubusercontent.com/25626557/91864583-fa996480-ec35-11ea-87ae-186e38e42405.png)

![image](https://user-images.githubusercontent.com/25626557/91867448-4a2d5f80-ec39-11ea-8eb6-b46dc5f54190.png)

**Comment by TheDailyWaffle** [comment]
It also doesn't work with Last.fm because of this.

**Comment by jakobbsm** [comment]
Oddly enough it seemed to work with YouTube Music when I was messing around with it a few days ago. Today it was left with null. Using Google Play Music updates the song values, but changing back to YouTube music leaves it hanging with the old song. Playing, time and volume seems to update in any case.

**Comment by minipasila** [comment]
> Oddly enough it seemed to work with YouTube Music when I was messing around with it a few days ago. Today it was left with null. Using Google Play Music updates the song values, but changing back to YouTube music leaves it hanging with the old song. Playing, time and volume seems to update in any case.

Yesterday I had a similar problem though I haven't used Google Play Music for a few months now since I transitioned to YouTube Music and suddenly it started only scrobbling an old song while I was playing new music so I decided to restart the app and now it doesn't scrobble anything at all nor does Discord Rich Presence work anymore. And I also checked the playback.json and it showed the same thing that VFSniper had.

**Comment by moeffju** [comment]
#3888 is related (likely a duplicate)

**Comment by spavolko** [comment]
Something similar seems to be happening with both GPM and YTM again; Discord Rich Presence integration is not working with either, and YTM shows Unknown Artist - Unknown Song for everything it is playing.

**Comment by tom-james-watson** [comment]
This was fixed in https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3888. We're waiting for a new release to be made for this to get pushed out.

**Comment by jostrander** [comment]
Indeed, closing in favor of #3888.
