### ISSUE TITLE
No sound during playback on Arch Linux

### ISSUE THREAD

**Issue by pd5rm** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#389]
**OS:**
Arch Linux 
google-play-music-desktop-player-git 3.0.0.68.ge77e060-1
I installed via AUR (yaourt -S google-play-music-desktop-player-git)

**Issue Descriptions:**
I get no sound at all during playback.

**Steps to Reproduce:**
Start app, try to play a song, no sound.

I try changing  my audio device settings in (right click > audio device)
I made sure to toggle (line line) mute on/off from keyboard controls, and to slide the volume all bar in UI all the way up.
I can play the audio fine in both Chrome and Nuvola app (another standalone app).

**Workaround**
After debugging, I discovered the Pulse audio "sink" was muted.

1. Use 'pacmd list-sink-inputs' to list sinks. Find the corresponding one to google-play-music app.
2. Unmute the corresponding index using 'pacmd set-sink-input-mute <index> false

**Comment by MarshallOfSound** [comment]
Hmmmm, doesn't sound like something the program can handle internally.  Can you add a bit to the bottom of the FAQ wiki.  Something like

## No audio output on Arch?
1.  Steps here to fix

**Comment by pd5rm** [comment]
Sure, I can do that. Also, mentioned it on https://aur.archlinux.org/packages/google-play-music-desktop-player-git/ in case it's a package/distro issue.
