### ISSUE TITLE
Expired SSL Cert on https://www.googleplaymusicdesktopplayer.com/

### ISSUE THREAD

**Issue by arb362** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3890]
**Checklist:**

* [ x] I have checked that there are no issues with similar or the same content

The website https://www.googleplaymusicdesktopplayer.com/ has an expired ssl cert.

![image](https://user-images.githubusercontent.com/6188411/94504907-88ce1f80-01cf-11eb-90b5-344076e04f99.png)

**Comment by Block81838** [comment]
I got the same issue

**Comment by jostrander** [comment]
@MarshallOfSound Any chance you can kick this server?

**Comment by arb362** [comment]
Given that the certificate is now valid I believe the server has been sufficiently kicked
