### ISSUE TITLE
No metadata provided to the system on macOS Big Sur

### ISSUE THREAD

**Issue by hacker1024** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3891]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES AS WELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:** macOS 11 Big Sur Developer Beta 9 (20A5384c)

**GPMDP Version:** 4.7.1

**Issue Descriptions:** macOS Big Sur introduces a media control centre that displays album art and other track info. This is all set to "undefined" in GPMDP.

Here's GPMDP compared to my own Pandora client, Epimetheus:

![image](https://user-images.githubusercontent.com/20849728/95038362-a04e6080-0719-11eb-8995-cd892011061f.png)

**Steps to Reproduce:**
- Play some music on macOS Big Sur

**Comment by timtmok** [comment]
Looks like the same issue as #3881 and #3888

**Comment by hacker1024** [comment]
Ah yep, looks like #3888 describes this exact issue. #3881 is probably related. Closing.
