### ISSUE TITLE
Will the features in gpmdp migrate to youtube music

### ISSUE THREAD

**Issue by Block81838** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3894]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES AS WELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [ ] I have double checked and can reproduce the issue

**OS:**
Archlinux
**GPMDP Version:**
4.7.1-1
**Issue Descriptions:**
Will the features in gpmdp migrate to youtube music
**Steps to Reproduce:**

**Comment by jostrander** [comment]
All I can say at this time is that the features that _can_ migrate to YTM will be migrated. There are some features that I don't think will make the cut due to technical reasons, or amount of work required. I'm going to close this but feel free to discuss further.
