### ISSUE TITLE
Scrobbling stopped working with YouTube Music

### ISSUE THREAD

**Issue by hotmule** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3895]
OS: Fedora 32

GPMDP Version: 4.7.1 from Flatpack

Issue Descriptions: Recently scrobbling has stopped working with YouTube Music beta

Steps to Reproduce: Tried to log out/in to Last.fm account, tried to reinstall the app - nothing helps

**Comment by SparkOfChaosdareal** [comment]
same for me on windows

**Comment by lesthack** [comment]
Yes i confirm it.

OS: Elementary OS Hera (Ubuntu 18.04)
GPMDP Version: 4.7.1 from Debian packages on release
