### ISSUE TITLE
Seperate 32bit and 64bit update streams

### ISSUE THREAD

**Issue by MarshallOfSound** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#39]
Change the updater logic to download 64bit / 32bit builds depending on the current install.  Related to #16

**Comment by MTRougeau** [comment]
Has the 64 bit version gone live yet? When I download 1.8.0 fresh from GitHub, I'm still running the 32 bit version.

**Comment by MarshallOfSound** [comment]
Not yet, its a multi stage process.  1.8.0 has some of the underlying logic in the updater to allow for multiple build uploads.  Next update will check for x86/x64 and the update after that will actually have x86/x64 releases.  It's the simplest way I could come up with to move from a single update stream to 2

**Comment by MTRougeau** [comment]
Awesome, thanks so much!
