### ISSUE TITLE
Hotkeys not working for Thumbs Up/Down in YT Music

### ISSUE THREAD

**Issue by CydeSwype** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3901]
Hotkeys don't trigger Thumbs Up/Down in YT Music

OS: macOS 10.15.7 (19H2)
Application Version: 4.7.1 (4.7.1)

A summary of the issue. If suitable, include the steps required to reproduce the bug.

1. Switch to Youtube Music version of the app.
1. Assign a hotkey to thumbs up or thumbs down (if not already assigned)
1. Play music as normal
1. Use assigned hotkey to initiate thumbs up/down

Expected result: Thumbs up/down is triggered and saved

Actual result: No effect (no highlighted thumb icon, thumbs down doesn't skip track, etc.)

Note that this issue doesn't appear to be present in Google Play Music version of the app, hotkeys work there for thumbs up/down as normal.

Per @jostrander :

There seems to be some kind of disconnect between the hot keys and ytmusic.js, but it ytmusic.js has it implemented, so it should be fine in future builds once that's resolved. A separate issue would be fine.

_Originally posted by @jostrander in https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3892#issuecomment-709627659_

**Comment by jostrander** [comment]
Do you happen to also have the 'Unknown Artist' problem in YTM as seen in #3888?

**Comment by CydeSwype** [comment]
Ahh, yes I do have that issue!  I hadn't even noticed that.

**Comment by CydeSwype** [comment]
I'll build from source to see if that resolves the issue.

**Comment by jostrander** [comment]
I believe that its resolved with 6.2.2 then, I had accidentally went back to the wrong patch when testing.

**Comment by CydeSwype** [comment]
Confirmed!  Building from source solved this issue, so your theory on the update for ytmusic.js is correct.

**Comment by jostrander** [comment]
I'm going to close this out then, as its already resolved in master.
