### ISSUE TITLE
Can't switch to YouTube Music Player

### ISSUE THREAD

**Issue by equiman** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3904]
**Checklist:**

* [X] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES AS WELL**
* [X] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [X] I have double checked and can reproduce the issue

**OS:** macOS Catalina 10.15.7 (19H2)

**GPMDP Version:**  Version 4.7.1 (4.7.1)

**Issue Descriptions:**

Today was closed my access to Goole Play Music, but on this new webpage, I can't switch to YouTube Music, because there is no button.

**Steps to Reproduce:**

Open GPMDP and show this screen.

<img width="1074" alt="Screen Shot 2020-10-22 at 10 26 01" src="https://user-images.githubusercontent.com/933393/96894184-1577a080-1451-11eb-8807-68f144df78b4.png">

**Comment by jostrander** [comment]
Use the tray icon on the top bar in Mac.

**Comment by equiman** [comment]
Done! Thanks!

<img width="365" alt="Screen Shot 2020-10-22 at 10 49 57" src="https://user-images.githubusercontent.com/933393/96897594-61781480-1454-11eb-8edd-b400e0148388.png">

**Comment by Razzeee** [comment]
You can also click `Transfer to youtube music` then you get to a side, where you can pick if you actually want to transfer or skip.

The downside is, that the application will ask you again on next start, as it thinks you want gmusic to start.

**Comment by tekfranz** [comment]
> Use the tray icon on the top bar in Mac.

Worked for me. Thanks!

**Comment by jason-mehmel** [comment]
Any options for those of us using Linux?

**Comment by alerque** [comment]
The same "transfer" button *or* tray icon selector as mentioned for macOS work fine for me on Linux to get into YT music mode.

It would be nice if somebody sent in a PR to make this the default/only mode now that we don't have other options.

**Comment by Razzeee** [comment]
I had to install a gnome extension, that enables tray icons, switch the app over and Uninstaller the extension

**Comment by jason-mehmel** [comment]
That worked for me!
