### ISSUE TITLE
MacOS Media Center Support

### ISSUE THREAD

**Issue by domoritz** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3909]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES AS WELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:** MacOS 11

**GPMDP Version:** Version 4.7.1 (4.7.1)

**Issue Descriptions:**

The media center only partially works with YouTube Music. I expect to see the album art and the artist and title. 

<img width="306" alt="Screen Shot 2020-11-01 at 16 35 37" src="https://user-images.githubusercontent.com/589034/97819941-9a886400-1c60-11eb-9a61-002e846df9e2.png">

**Steps to Reproduce:**

* Switch to YT Music
* Play music

**Comment by jostrander** [comment]
#3888

**Comment by domoritz** [comment]
Ahh, thanks. I built my own version from master just now and now I see the artist/album. Still, no album art but this is much better. 

<img width="301" alt="Screen Shot 2020-11-01 at 16 45 25" src="https://user-images.githubusercontent.com/589034/97820173-c1936580-1c61-11eb-90e8-862fc4ed43d6.png">
