### ISSUE TITLE
Question: Hide menu bar?

### ISSUE THREAD

**Issue by jacobmischka** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#391]
I've looked through the open issues and searched the closed ones and didn't see anything mentioning this, is there a way to hide the menu bar I can't find? It's particularly distracting when using the mini player in my opinion. 
![image](https://cloud.githubusercontent.com/assets/3939997/13624676/e379894a-e575-11e5-942c-7e3b9846e54c.png)

**Comment by MarshallOfSound** [comment]
You are on master :+1: 

It is unstable :+1: 

This will be fixed soon :+1:

**Comment by jacobmischka** [comment]
:+1:

**Comment by MarshallOfSound** [comment]
:+1:
