### ISSUE TITLE
Song preview lists "Unknown Song - Unknown Artist"

### ISSUE THREAD

**Issue by OfficialMaxBox** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3910]
**Checklist:**

* [X] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES AS WELL**
* [X] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [X] I have double checked and can reproduce the issue

**OS:** Windows 10

**GPMDP Version:** 4.7.1

**Issue Descriptions:** On the hover-over of the taskbar icon, the window lists "Unknown Song - Unknown Artist". This also seems to modify what my music-display app SMG can read, as all it can detect is the same unknown message. 

**Steps to Reproduce:** N/A, I'm simply using the YouTube Music app. Issue persisted after a reinstall. 

![Bigc97Dg4d](https://user-images.githubusercontent.com/16658918/98459213-860b0680-214d-11eb-9a59-3b22c6bd6106.png)
![SMG_mMXLUXMQe6](https://user-images.githubusercontent.com/16658918/98459214-86a39d00-214d-11eb-9085-b2552eaed4c9.png)

[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/5505943/debug_info.zip)

**Comment by jostrander** [comment]
See #3888
