### ISSUE TITLE
https://www.googleplaymusicdesktopplayer.com/ Certificate Expired Nov 26, 2020

### ISSUE THREAD

**Issue by ericop** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3912]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES AS WELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:** Win10 (Firefox and Chromium Edge)

**GPMDP Version:**
n/a

**Issue Descriptions:**
www.googleplaymusicdesktopplayer.com needs its certificate updated

**Steps to Reproduce:**
- Visit https://www.googleplaymusicdesktopplayer.com/
- See error

```
NET::ERR_CERT_DATE_INVALID
Subject: googleplaymusicdesktopplayer.com

Issuer: Let's Encrypt Authority X3

Expires on: Nov 26, 2020
```

**Comment by duke-janrain** [comment]
This is a bit scary, given GPM is on the verge of being completely dead. That said, I understand the maintainer of this application has added a YTM interface, and it's worked pretty darn well so far. 

Anyway, I also came to this repository to report the expired SSL certificate and to see if maintainer has released an update to the OSX client (currently 4.7.1). Let's hope they post an update soon, as there are no other standalone client options for Youtube Music on desktop!

**Comment by MarshallOfSound** [comment]
SSL reloaded

**Comment by yuliu** [comment]
Hi there, @MarshallOfSound ! It might need another certification reloading. The cert is expired today.

**Comment by strigona-worksight** [comment]
@MarshallOfSound Certificate is expired again.
