### ISSUE TITLE
googleplaymusicdesktopplayer.com cert expired Jan 25th 2021

### ISSUE THREAD

**Issue by gunslingerfry** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3917]
That's all. I don't know how to tell @MarshallOfSound except like this.

**Comment by tekfranz** [comment]
> That's all. I don't know how to tell @MarshallOfSound except like this.

Yes, i just noticed myself while trying to download fresh copy.

**Comment by MarshallOfSound** [comment]
Reloaded cert
