### ISSUE TITLE
Application stopped working on OSX

### ISSUE THREAD

**Issue by DanDobrick** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3941]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES AS WELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**
macOS Big Sur 11.6 (20G165)

**GPMDP Version:**
Version 4.7.1 (4.7.1)

**Issue Descriptions:**
Opening the app results in a black screen with nothing loading

![Screen Shot 2021-11-30 at 12 06 25 PM](https://user-images.githubusercontent.com/17708093/144111764-53c92340-2380-4bad-b166-a309b4131bf1.png)

**Steps to Reproduce:**
Open the application.

**Comment by DanDobrick** [comment]
After checking out a bunch of other issues, I'm convinced that this project has been abandoned and I decided to move to [ytmusicdesktop](https://github.com/ytmdesktop/ytmdesktop)

**Comment by EDIflyer** [comment]
Thanks for the heads up - I just found the same issue and have moved to YTMD too!
