### ISSUE TITLE
No sign in screen with standard xorg ati driver

### ISSUE THREAD

**Issue by texstar** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#399]
I could not get the sign in screen using the standard xorg ati driver. I switched to the fglrx driver and the sign in screen was operational. 

xorg-1.17.4
x11-driver-video-ati-7.6.1
mesa-11.1.2
kernel 4.4.4

OS: PCLinuxOS 64

**Comment by MarshallOfSound** [comment]
Use the startup command `--disable-gpu`

**Comment by MarshallOfSound** [comment]
Also, this is on the FAQ

**Comment by texstar** [comment]
Thank you! I did not find a "faq" in the deb file. :(

**Comment by MarshallOfSound** [comment]
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ
