### ISSUE TITLE
Now Playing list text colour

### ISSUE THREAD

**Issue by chrismou** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#400]
https://github.com/gmusic-utils/gmusic-theme.js/issues/15

Sorry dude, aimed to investigate/fix this myself, but struggling getting the theming library set up and I've just got to the office so I'm going to struggle to find any time over the next hour or so.

**Comment by MarshallOfSound** [comment]
All good.  I can't replicate though so it's going to be down to you/someone else.  If you need help getting the theming library / this set up in a dev env you can ping me on gitter

**Comment by MarshallOfSound** [comment]
Fixed in theming library
