### ISSUE TITLE
Request - Add liked/disliked info to playback.json

### ISSUE THREAD

**Issue by spedrickson** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#403]
This would be very convenient for simple external programs like Rainmeter. Just a simple liked true/false and disliked true/false would be perfect.

Thanks!

**Comment by MarshallOfSound** [comment]
For anyone wanting / willing to tackle this, it would be as simple as adding a couple of event listeners on the global `GPM` object inside `GPMInject` and firing events up to the PlaybackAPI.

An example is how the current implementation of `time` works
