### ISSUE TITLE
Uncaught Exception: The Internet connection appears to be offline.

### ISSUE THREAD

**Issue by josep2** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#407]
Not sure this is worthwhile to report but there was an option to do so. I was offline shortly and it threw the error which seems like expected behavior. Anyway, feel free to close it if its a non issue.

An uncaught exception was reported.  
#### Info:
**OS:** darwin
**Arch:** x64
**GPMDP Version:** 3.0.0
**Time:** Wed Mar 09 2016 08:23:46 GMT-0700 (MST)

#### Error:
*The Internet connection appears to be offline.: (null)*
```js
Error: The Internet connection appears to be offline.: (null)
    at Error (native)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
It's a non-issue.  The error will not be reported in the next release :+1:
