### ISSUE TITLE
Uncaught Exception: The request timed out.: (null)

### ISSUE THREAD

**Issue by JeffreyWilcox** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#409]
An uncaught exception was reported.  
#### Info:
**OS:** darwin
**Arch:** x64
**GPMDP Version:** 3.0.0
**Time:** Wed Mar 09 2016 08:14:05 GMT-0800 (PST)

#### Error:
*The request timed out.: (null)*
```js
Error: The request timed out.: (null)
    at Error (native)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by JeffreyWilcox** [comment]
Nothing seems to have actually broken, just got an error msg with a link to submit it.

**Comment by MarshallOfSound** [comment]
Yep, this is a standard ish update server connection issue thingy :+1: 

This error will not be reported in the next release (It means nothing) :smile:

**Comment by JeffreyWilcox** [comment]
:+1:
