### ISSUE TITLE
Feature Request: Scalable Text/UI

### ISSUE THREAD

**Issue by thesmall** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#41]
I'd like to make a feature request: Much in the same way that you can use Control+Scroll Wheel to increase or reduce the font size (and UI scaling) in the browser when you are visiting Google Play Music, it would be very awesome if you could scale the font and UI in this application. I find the default text size a bit too big and so I usually reduce the scaling to 75%. Not only is the text smaller, but you can fit more content on the screen. More albums to browse, more music to choose from. Seeing as how there is no context menu or any application-specific menus, this might need to be implemented only as a keyboard shortcut initially. 

Cheers!

**Comment by MarshallOfSound** [comment]
Note: `Ctrl + +` and `Ctrl + -` are in CefSharp but aren't enabled.  I believe we have to map the keypress method on the form to the ZoomStep methods in Cef

**Comment by MarshallOfSound** [comment]
I have implemented Ctrl Plus, Ctrl Minus and Ctrl 0.  They each respectively do the following

* Ctrl Plus --> Zoom in by a factor of 1.2
* Ctrl Minus --> Zoom out by a factor of 1.2
* Ctrl 0 --> Reset zoom to default level
