### ISSUE TITLE
The Queue list is not styled correctly with Dark Theme

### ISSUE THREAD

**Issue by Pacane** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#411]
**OS:**
Arch Linux

**Issue Descriptions:**
The Queue list items aren't styled propertly in the Dark Theme.

![image](https://cloud.githubusercontent.com/assets/2762440/13644937/586e3fcc-e5f6-11e5-9ed7-66cb5a5f24f5.png)

**Steps to Reproduce:**
Open the queue list with Dark theme set.

**Comment by sylmarien** [comment]
Just as a complement : I have the same problem on Windows 10. (64 bits if that matters)

**Comment by Nxt3** [comment]
Same here.

Is there a way to theme the accent color of the player while keeping light mode enabled?

**Comment by MarshallOfSound** [comment]
This has been fixed in the theming library and will be pushed next release.  It looks like it affects < 5% of people though.  Google is A/B testing
