### ISSUE TITLE
[enhancement] Back/Forward Button

### ISSUE THREAD

**Issue by LiquidMechanix** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#412]
**OS:** Windows

**Issue Descriptions:** Not an issue but an enhancement request. I would love to see a back button and a forward button like on a browser. One that is on the play itself, maybe up by the search bar. Backspace would also trigger the back command and the side mouse button. 

I often go down music rabbit holes, going from one band to another based on the similar bands section. Without a back button, I have to start over or remember what other bands I want to listen to. So being able to back and forward from screen to screen like being in the browser would be awesome.

**Steps to Reproduce:**

**Comment by MightyPork** [comment]
There now _is_ a back button - but I guess you are using one of the release packages, so you don't have it yet.

If you want the latest cool stuff, run it from source.

**Comment by MightyPork** [comment]
@MarshallOfSound seems something with the issue template didn't quite work out .....

**Comment by MarshallOfSound** [comment]
Yeah, I just editing this issue to fix.  No one else has had a problem though (yet).  I'll test it out a bit

But @LiquidMechanix there is a back button in master, will be pushed out in the next release

**Comment by greenwald** [comment]
I'm running 3.0.1 on a Mac (10.11.2) and I don't see the back button, though the release notes state "There is now a back button in the UI #easynavigation" --- is this not in all versions for all systems?

**Comment by MightyPork** [comment]
@greenwald the button is hidden on the front page, it'll appear when you go anywhere. It should, anyway.

![screenshot_2016-03-14_00-49-05](https://cloud.githubusercontent.com/assets/2041118/13732252/918d2e72-e97e-11e5-94f6-8e6d8467dc7c.png)

@MarshallOfSound just realized a possible gotcha with the button - it hides on the front page, but that is detected by the URL. As per 23dbf721e83c24b4471478262bcabaf5c2af2f50 the first page (with no history) is not fixed (if I read it right). So the auto-hiding will not behave right. - tbh. the page saving idea sounds dumb to me, but it's your choice.

iirc I tried using history.length or something like that instead, but that didn't work well.

**Comment by greenwald** [comment]
That doesn't show up for me. Navigation without a back button is very annoying (but that's 99% Google's fault).

![3 0 1](https://cloud.githubusercontent.com/assets/2571281/13732622/40e5f018-e987-11e5-8a1b-b62c20cf8b53.jpg)

**Comment by MightyPork** [comment]
@greenwald You'd better make a new issue for this, and write your version Nr, OS etc there. You can link to this so no need to repost the screenshot etc...

Personally I'm on Linux and also running from Git because the "linux" release is only for ubuntu, so can't test this.
