### ISSUE TITLE
Uncaught Exception: The Internet connection appears to be offline.: (null)

### ISSUE THREAD

**Issue by nvadave** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#416]
An uncaught exception was reported.  
#### Info:
**OS:** darwin
**Arch:** x64
**GPMDP Version:** 3.0.0
**Time:** Wed Mar 09 2016 15:38:00 GMT-0500 (EST)

#### Error:
*The Internet connection appears to be offline.: (null)*
```js
Error: The Internet connection appears to be offline.: (null)
    at Error (native)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by nvadave** [comment]
My internet connection wasn't actually down.

**Comment by MarshallOfSound** [comment]
Client side network issue

Will not be reported in `3.1.0`

Your internet may not have been down, but you would have just resumed from sleep or something similar and OS X network connections don't persist through sleep to save battery.  So there would be a small amount of time where you weren't connected
