### ISSUE TITLE
Voice Controls not working.

### ISSUE THREAD

**Issue by Reckless5040** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#417]
OS: Windows 10 Pro

Issue Descriptions: Getting no response whatsoever from voice controls

Steps to Reproduce: Install version 3.0. Enable Voice Control. Issue Commands.

**Comment by Nxt3** [comment]
Same on OSX (10.11.3).

Nothing happens--I don't even know if it's hearing me; but I've tried in quiet environments and even turned the music down.

**Comment by MarshallOfSound** [comment]
It looks like the API key electron uses it being rate limited and my app blew the limit out of the water.  It keeps returning voice network errors.  I'm looking in to it

**Comment by MarshallOfSound** [comment]
My voice controls are back working again and it looks like other's are aswell

**Comment by MiguelLarios** [comment]
Mine not.

**Comment by Dukko** [comment]
Still not working here on OSX :(

**Comment by hawkins** [comment]
Windows 10 Pro user here, voice controls are unresponsive. Cannot tell that anything is happening. Same repro steps as in the original post here.

**Comment by phishy** [comment]
Haven't gotten this to work at all. If it truly is an API key issue, we should look into allowing the user to enter their own.
