### ISSUE TITLE
Uncaught Exception: Update check failed: (null)

### ISSUE THREAD

**Issue by duckinferno** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#418]
An uncaught exception was reported.  
#### Info:
**OS:** darwin
**Arch:** x64
**GPMDP Version:** 3.0.0
**Time:** Thu Mar 10 2016 12:06:47 GMT 1300 (NZDT)

#### Error:
*Update check failed: (null)*
```js
Error: Update check failed: (null)
    at Error (native)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
Client side network issue

Will not be reported in `3.1.0`
