### ISSUE TITLE
Uncaught Exception: Update check failed: (null)

### ISSUE THREAD

**Issue by fraserwatson** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#420]
An uncaught exception was reported.  
#### Info:
**OS:** darwin
**Arch:** x64
**GPMDP Version:** 3.0.0
**Time:** Wed Mar 09 2016 16:42:21 GMT-0700 (MST)

#### Error:
*Update check failed: (null)*
```js
Error: Update check failed: (null)
    at Error (native)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
Client side network issue

Will not be reported in `3.1.0`
