### ISSUE TITLE
History controls doesnt work

### ISSUE THREAD

**Issue by VitorVRS** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#421]
**OS:** Linux Ubuntu 14.04

**Issue Descriptions:** Enable history controls on application

**Steps to Reproduce:** Open the application, navigate between albums and try "Go Back" history control. (My mouse have history control button).
Without this feature i have to click on bands name, then click on albums, then choose another album.

**Comment by MarshallOfSound** [comment]
This is implemented in master and will be pushed during next release
