### ISSUE TITLE
last.fm link resetting, new authorization needed

### ISSUE THREAD

**Issue by BalzGuenat** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#422]
**OS:** Windows 10

**Issue Descriptions:** I keep getting logged out of last.fm. I then have to go through the authorization process again.

**Steps to Reproduce:** I have not yet noticed a regularity of when this happens because I don't necessarily notice it immediately after it happens. I have to go to the settings menu to check if I'm still logged in with last.fm.

**Comment by Meegooo** [comment]
I believe last.fm had some issues and maybe it still has. [Link](https://getsatisfaction.com/lastfm/topics/website-update-9th-march)
2 days ago I couldn't log in at all, it either gave me an error (API key expired or something) or just said "Not Authorized". And for 5% of the time that I got lucky and it actually said Authorized, it would ask me to authorize again once next song started and I would get same errors.
Yesterday sometimes (like once every 2-3 songs) it would just log out on itself, but I could authorize back without any problems

And now, after like 12 hours I checked and scrobbling works and I'm not getting logged out.

**Comment by MarshallOfSound** [comment]
Yep, radiant player is having some last.fm issues https://github.com/radiant-player/radiant-player-mac/issues/513

As am I, it looks like we are just going to have to wait out the API fix :+1:

**Comment by MarshallOfSound** [comment]
FYI @chrismou

**Comment by Meegooo** [comment]
Whelp, still not completely fixed. Had to authorize again now.

**Comment by chrismou** [comment]
The last.fm API is a bit ropey at the moment. There's been a lot of API downtime over the last few days (https://getsatisfaction.com/lastfm/topics/and-scrobbling-stopped-working-again), though I'm not sure if that would deauthorize a token.

TBH, that issue you linked to in Radiant, my current theory is that last.fm prevent posting the same scrobble in succession within a certain time frame to stop dupes and spamming, so I'm not sure it's related.  Haven't 100% tested that theory yet though.

**Comment by MarshallOfSound** [comment]
Ah lol, just blame all last.fm related things on them :+1: 

That's my plan, I implemented their API perfectly (even the wait half way through the song before scrobbling nonsense) so they just need to fix their API :smile:

**Comment by chrismou** [comment]
Might it be worth deleting the entire GPMDP config folder and start again? Any chance of some lingering caching issue?

**Comment by wadegbow** [comment]
This pops up for me about every 10-15 minutes and I have to authorize the app again: http://i.imgur.com/s5DVeff.png

Haven't been having problems with other Last.fm implementations like Wail + Google Music (Android) or mpd + mpdscribble (osx).

**Comment by chrismou** [comment]
It could be unrelated to this issue, but the last.fm API is actually down right now: http://www.downforeveryoneorjustme.com/http://ws.audioscrobbler.com/2.0/

**Comment by chrismou** [comment]
Although interestingly, this guy is actually talking about the official last.fm app: https://getsatisfaction.com/lastfm/topics/authorization-9m504nla7x1jg

**Comment by wadegbow** [comment]
Deleted my previous comment because it does just look like Last.fm is on fire. Why do I still use this trash heap of a service?

**Comment by chrismou** [comment]
They've struggled a bit since their redesign, that's for sure.  The authorization thing is annoying, because it seems to affect certain people on certain apps with no real pattern.  I've not really been affected at all, but I've seen people swear blind they haven't been able to scrobble from anywhere for months.

**Comment by LordCatzorz** [comment]
> Deleted my previous comment because it does just look like Last.fm is on fire. Why do I still use this trash heap of a service?

We probably use it because of statistics. We all love statistics. 

Last.fm has a lot, a LOT of problems. They are drowning and are struggling to catch some air. Their team has probably been cut down to the bare minimum. They do not have much of a marketing plan and so, are doomed to die.

I'm really sad of this eventuality. I have tried Libre.fm, but the lack of supports of players is a huge down for it.

**Comment by MarshallOfSound** [comment]
I'm actually going to close this unless someone can provide conclusive proof that it is our implementation breaking as opposed to last.fm's shoddy API
