### ISSUE TITLE
Unable to install Mini Player

### ISSUE THREAD

**Issue by javiapi** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#423]
Unable to install the Mini Player, the app remains in a "Setting Up Google Play Music" splash screen. Can't click elsewhere but music playback never stops tho, I have hotkeys enabled. 

I'm running Win10 in a Lenovo S415

**Comment by MarshallOfSound** [comment]
Fixed in master

Will be pushed in the next release
