### ISSUE TITLE
The Start Menu folder is just called "Samuel Attard"

### ISSUE THREAD

**Issue by hoferrier** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#424]
Why

**Comment by MarshallOfSound** [comment]
Because that's me?

Start menu shortcuts are stored in `author/application` format.  I am the registered author so that's where the shortcut ends up

**Comment by hoferrier** [comment]
Lame

**Comment by MarshallOfSound** [comment]
So the standards are lame?  That's nice...
