### ISSUE TITLE
Pressing "Show mini player" enters unexitable splash screen

### ISSUE THREAD

**Issue by ywecur** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#425]
**OS X 10.11.3**

**Pressing "Show mini player" enters unexitable splash screen where you are presented with a download option. I'd suggest you remove that element from the program**

**Press the "three dots icon" to the left of the thumbs up button and choose show mini player.**

**Comment by MarshallOfSound** [comment]
Fixed in master.

Will be pushed in next release
