### ISSUE TITLE
Add editorconfig file to project

### ISSUE THREAD

**Issue by N0ps32** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#426]
**OS:**
All

**Issue Descriptions:**
I would like to ask if it's possible to add an editorconfig: http://editorconfig.org/ file to the project. My IDE keeps complaining because the project doesn't match my global formatting settings. 

While I can just re-configure my IDE with a per-project setting this would solve it for every future developer as well.

There are also [tools](https://www.npmjs.com/package/grunt-lintspaces) that can consume editorconfig files to enforce correct whitespace rules.

**Steps to Reproduce:**
Open a file in an IDE like Intellij IDEA Pro

**Comment by MarshallOfSound** [comment]
Sounds fair enough, looks like there is a plugin for `editorconfig` files in atom so I can make one and push to the repo.  Just figuring out how to make it match the syntax requirements of my linting config
