### ISSUE TITLE
Feature Request: Show currently playing song in the Windows mini preview window

### ISSUE THREAD

**Issue by amoerie** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#43]
It would be nice to hover over the icon in the taskbar and see the name of the band and song in that little preview window. I'm afraid you won't have much control over what's shown in there, but maybe you can change the title of the window and it will show up?

**Comment by MarshallOfSound** [comment]
Yup, I should be able to change the title of the window.  Can't guarantee how much of the song title will be visible though (I do have little control down there) but the suggestion appears to mirror what players like VLC and Spotify do.

**Comment by amoerie** [comment]
Sure, I'm confident that Windows will just ellipsize (append ... at the end) or cut off the text where necessary. Best solution would be some sort of "marquee" animation, where the text scrolls horizontally so you CAN read the full artist & song name if you wait a bit, but that's definitely not something worth spending a lot of time on.

**Comment by MarshallOfSound** [comment]
Well this is in my queue for the 1.9 release, just polishing the last.fm stuff off and I'll get onto the smaller tasks like this one

**Comment by amoerie** [comment]
Thanks, and thanks for the great app!

**Comment by mstrelan** [comment]
Is this working? My task bar just says "Google Play Music Desktop Player". I'm on the latest version.

**Comment by MarshallOfSound** [comment]
@mstrelan This commit is from the old version (the c# version of GPMDP)

Nothing to do with the current version.  Anything before Jan can be ignored
