### ISSUE TITLE
Control buttons in task bar are gone

### ISSUE THREAD

**Issue by Meegooo** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#430]
![gnpnpjc 1](https://cloud.githubusercontent.com/assets/3753828/13663391/102a38ce-e6c3-11e5-8c6c-f5916718ec77.png)

Using Windows 10.
I thought this was a common bug and would be fixed in the next version (or Soon™, since it's kinda apparent, like back/forward buttons), but it looks like other people have them (for example #387). Might be OS problem, I dunno.

**Comment by MarshallOfSound** [comment]
It's an electron bug, I reported it so we just need to wait for them to fix it. 

They will stay around until you minimize/restore from taskbar
