### ISSUE TITLE
Uncaught Exception: Zeitüberschreitung bei der Anforderung.: (null)

### ISSUE THREAD

**Issue by dkohtes** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#433]
An uncaught exception was reported.  
#### Info:
**OS:** darwin
**Arch:** x64
**GPMDP Version:** 3.0.0
**Time:** Thu Mar 10 2016 12:35:02 GMT 0100 (CET)

#### Error:
*Zeitüberschreitung bei der Anforderung.: (null)*
```js
Error: Zeitüberschreitung bei der Anforderung.: (null)
    at Error (native)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
Client side network issue

Will not be reported in `3.1.0`
