### ISSUE TITLE
Uncaught Exception: The request timed out.: (null)

### ISSUE THREAD

**Issue by mdellabitta** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#437]
Only reporting this because you probably want to add a handler to display a error to the user rather than having them report it to GitHub when they're on crappy wireless. :)

An uncaught exception was reported.  
#### Info:
**OS:** darwin
**Arch:** x64
**GPMDP Version:** 3.0.0
**Time:** Thu Mar 10 2016 10:47:22 GMT-0500 (EST)

#### Error:
*The request timed out.: (null)*
```js
Error: The request timed out.: (null)
    at Error (native)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
Client side network issues.

Will not be reported in `3.1.0`
