### ISSUE TITLE
Minor thing: After installation.

### ISSUE THREAD

**Issue by XDRosenheim** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#44]
Why describe it, when you can screenshot it.
All I did was to install it, nothing else.
![Screenshot](http://i.imgur.com/VD5uLkc.png)

**Comment by MarshallOfSound** [comment]
Putting it out there, the installer is nothing to do with me :P  It's an open source installer utility I use to make the installer for this program.  I'll raise an issue with it over there :D

**Comment by MarshallOfSound** [comment]
Oops, forgot to close this one.  As I said above, nothing I can do to fix this :sob:

**Comment by XDRosenheim** [comment]
Fair enough, just wanted you to know, in case you could do anything.
