### ISSUE TITLE
Uncaught Exception: The Internet connection appears to be offline.: (null)

### ISSUE THREAD

**Issue by cryptobird** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#441]
An uncaught exception was reported.  
#### Info:
**OS:** darwin
**Arch:** x64
**GPMDP Version:** 3.0.0
**Time:** Thu Mar 10 2016 11:03:43 GMT-0700 (MST)

#### Error:
*The Internet connection appears to be offline.: (null)*
```js
Error: The Internet connection appears to be offline.: (null)
    at Error (native)
```
This issue was created automatically inside the `uncaughtException` handler

Apparently the program throws an error if there's no internet connection. Might be better to display a message like "Hey, connect to the internet to keep blasting sweet tunes into your head!"

**Comment by MarshallOfSound** [comment]
Client side network issues.

Will not be reported in `3.1.0`
