### ISSUE TITLE
Mouse back buttons, middle mouse scrolling

### ISSUE THREAD

**Issue by ThurnisH41ey** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#442]
**OS: Arch Linux (kernel 4.4.4)**

**Issue Descriptions: pressing mouse buttons 4/5 do not go back/forward. Holding middle mouse button and moving the mouse does not scroll.**

**Steps to Reproduce: press mouse buttons 4/5, hold middle mouse button.**

**Comment by MarshallOfSound** [comment]
The mouse button 4 and 5 issue is fixed in master.  The mouse button 5 is an electron thing and something I can't fix.
