### ISSUE TITLE
Feature request: Stop playing after current song

### ISSUE THREAD

**Issue by oscarfroberg** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#445]
This is something I really miss from practically all players that don't have it, and I would love to see it here, and I'm more hopeful that you'll listen to my wishes than Google. :)

Maybe through a menu by holding the pause-button? Or just somewhere else, doesn't really matter. There are just so many times that you want to finish listening to the current track but then stop after that. It can be circumvented by deleting everything afterwards in the current queue, but a dedicated function would be so much better.

**Comment by kminehart** [comment]
I'll give this one a shot.

**Comment by MCManuelLP** [comment]
#909 should do it...

**Comment by MarshallOfSound** [comment]
Handled in #909
