### ISSUE TITLE
Song title / artist is unreadable in the queue window while theme is enabled (OSX 10.11)

### ISSUE THREAD

**Issue by merdre** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#450]
**OS:** Mac OSX 10.11.3

**Issue Descriptions:**
I recently updated to 10.11.3 from 10.9.x, and noticed a new cosmetic issue (still important) when looking at playlists and queues in the queue pop-up window in the bottom right-- the song's artist/title text is virtually the same shade of gray as the background, making them unreadable. This doesn't seem to apply to the regular browsing interface or the mini-player, only the queue window, and only when the Theme Enabled box is ticked. I personally really prefer the dark scheme of the themed window, so this is a pretty big deal for me. 

**Steps to Reproduce:**
Run Mac OS X 10.11.3, enable themes, open a playlist in the queue window.

**Comment by MarshallOfSound** [comment]
This is issue has been fixed and a bug patch fix thing is being prepared for release today

**Comment by merdre** [comment]
wonderful news, thank you!
