### ISSUE TITLE
Uncaught Exception: Update check failed: (null)

### ISSUE THREAD

**Issue by CommandoSanta** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#453]
An uncaught exception was reported.  
#### Info:
**OS:** darwin
**Arch:** x64
**GPMDP Version:** 3.0.0
**Time:** Thu Mar 10 2016 20:56:54 GMT-0500 (EST)

#### Error:
*Update check failed: (null)*
```js
Error: Update check failed: (null)
    at Error (native)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
This one was my bad, had to restart the update server.
