### ISSUE TITLE
Dark theme doesn't correctly display song titles in queue

### ISSUE THREAD

**Issue by kalentia** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#459]
**OS:** Arch Linux

**Issue:** When using the dark theme, song titles in the queue remain black, making them unreadable.

**Steps to Reproduce:** Activate the dark theme and open the queue.

**Comment by MarshallOfSound** [comment]
Arch linux users are different but an update has been released that fixes this issue.

You should ask if the person who handles the arch package can update it
