### ISSUE TITLE
Feature request: Last.fm scrobbling

### ISSUE THREAD

**Issue by VladimirAmiorkov** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#46]
Hi,

I will also give it try to implement Last.fm scrobbling but wanted to throw this feature request out there if someone more skilled (or with more free time) wants to implement it before me :)

**Comment by MarshallOfSound** [comment]
This is a duplicate of #3 which very recently went into master.  Last.fm scrobbling and now playing will be in the next release!!!!
