### ISSUE TITLE
Uncaught Exception: Command failed: 4294967295

### ISSUE THREAD

**Issue by ThomasLewis1028** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#462]
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.0
**Time:** Thu Mar 10 2016 22:15:41 GMT-0600 (Central Standard Time)

#### Error:
*Command failed: 4294967295*
```js
Error: Command failed: 4294967295
System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__4d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.FileDownloader.<DownloadFile>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwait
...Some of the stack is missing
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
This issue has been fixed, please update when the notification appears

**Comment by ThomasLewis1028** [comment]
It seems to be dropping me from the Last.FM authentication.  It also happened on my Linux laptop but I wasn't sure what happened.

Also this thing: http://i.imgur.com/adkKK5y.png  Never noticed that before.

**Comment by MarshallOfSound** [comment]
As mentioned before, an update has been released that fixes a lot of these issues.  Can you please update when the notification appears :+1:

**Comment by ThomasLewis1028** [comment]
Alright cool!  Yeah I sent that message and looked up to see you had responded already.  Thanks for the insanely quick responses!

**Comment by MarshallOfSound** [comment]
On another note though @ThomasLewis1028 can you tell me if / when you get the update pop up.  Just making sure everyone is getting it :+1:

**Comment by ThomasLewis1028** [comment]
Yup, just got it a couple seconds ago.  I restarted the app, started some music and right as I hit play I got the update notification.  On another note, is there an easy way to check and see what version number I'm on?  Just in case an update does go out and I can't tell if I've got it or not.

**Comment by MarshallOfSound** [comment]
Not a super easy way at the moment, but you can check the version number in control panel :+1:

**Comment by ThomasLewis1028** [comment]
Alright thanks!  Again thanks for the quick responses, definitely nice when a dev responds almost instantly!
