### ISSUE TITLE
Desktop Notifications Not Appearing

### ISSUE THREAD

**Issue by cnscollon** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#467]
**OS:** Windows 10 (64 bit)

**Issue Descriptions:** I recently installed this music player and love it, but I don't appear to have desktop notifications. I have poked through the settings and haven't found an option to enable or disable them. Perhaps I'm just missing something?

**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment]
Are they turned on in the actual Google Play Music settings?  Not the desktop settings but the normal settings?

**Comment by cnscollon** [comment]
Aha! As I figured, I'm a dunce and missed that altogether. Issue closed, sorry for wasting your time and thanks for the insanely fast response!
