### ISSUE TITLE
Uncaught Exception: Attempting to call a function in a renderer window that has been closed or released. Function provid

### ISSUE THREAD

**Issue by raphaelcastaneda** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#470]
This occured after selecting a "listen now" category, then hitting the "back" button on my mouse.

An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.1
**Time:** Fri Mar 11 2016 00:13:29 GMT-0800 (Pacific Standard Time)

#### Error:
*Attempting to call a function in a renderer window that has been closed or released. Function provid*
```js
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: Object.<anonymous> (C:\Users\Raphael\AppData\Local\GPMDP_3\app-3.0.1\resources\app\build\inject\GPMInject\interface\mouseButtonNavigation.js:8:8.
    at BrowserWindow.callIntoRenderer (C:\Users\Raphael\AppData\Local\GPMDP_3\app-3.0.1\resources\atom.asar\browser\lib\rpc-server.js:201:19)
    at emitTwo (events.js:92:20)
    at BrowserWindow.emit (events.js:172:7)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
Woo hoo, an error caught by the report to github feature THAT IS ACTUALLY USEFUL :+1: :+1: 

I'll try reproduce it

**Comment by Diablo-D3** [comment]
You might want to push a new release that fixes this ;)

**Comment by MarshallOfSound** [comment]
Holding out for the `3.1.0` release.  Should fix a lot of big things, just doing some testing and cleanup

**Comment by J-M-Ward** [comment]
OK, glad you know about it, I'll cease reporting it.  I like the program, by the way.

JMW

**Comment by maxlefou** [comment]
Just to mention the problem doesn't occur anymore if you use system window borders. I put this here for the future users while waiting for the update ;p

**Comment by timnolte** [comment]
+1

**Comment by Diablo-D3** [comment]
@MarshallOfSound It's been two weeks, where is the awesome new release? :D

**Comment by MarshallOfSound** [comment]
@Diablo-D3 All going to plan, check your client in about 30 minutes :D :D :D 

`3.1.0` HERE WE COME :+1:

**Comment by MarshallOfSound** [comment]
@Diablo-D3 Ta da

**Comment by Diablo-D3** [comment]
Ahh, I can set colors on the light theme now. Neat.
