### ISSUE TITLE
Feature suggestion: Allow entering URL of songs/albums/playlists somewhere

### ISSUE THREAD

**Issue by spedrickson** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#475]
One of the best things about GPM is the ability to link songs or albums or playlists directly to friends, for sharing music. However I can't find any way to enter a URL I have been linked in the desktop player. 

My suggestion (if I haven't just missed how to do this) is to load the page for URLs pasted into the search bar, or have some sort of popup that you can just paste URLs into. 

Thanks!

**Comment by JeffreyWilcox** [comment]
+1

**Comment by MarshallOfSound** [comment]
In the next release there will be a menu option and a shortcut to do this.

"Control / Command + Shift + G"

**Comment by spedrickson** [comment]
Hey, excellent news! 

When you say menu option, does that mean like an option to change the keyboard shortcut? Ctrl+Shift+G is a bit odd, I love would to be able to rebind it to a more standard shortcut like Alt+D or Ctrl+L

Thanks a bunch for implementing this so quickly!

**Comment by MarshallOfSound** [comment]
Ctrl+Shift+G is the stand "go to" shortcut.  (At least that's what my experience has been).  Neither "Alt+D" or "Ctrl+L" make any sense to me?  Accelerators (shortcuts) make more sense to users if the letter they are pushing is relevant to the command.  So **G**oto uses G
