### ISSUE TITLE
Annoying error message whenever my laptop is offline.

### ISSUE THREAD

**Issue by johnmcdonnell** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#477]
An uncaught exception was reported.  
#### Info:
**OS:** darwin
**Arch:** x64
**GPMDP Version:** 3.0.0
**Time:** Fri Mar 11 2016 03:46:38 GMT-0800 (PST)

#### Error:
*The Internet connection appears to be offline.: (null)*
```js
Error: The Internet connection appears to be offline.: (null)
    at Error (native)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
Please accept the update notification and this error will go away
