### ISSUE TITLE
Feature Request: Portable Version

### ISSUE THREAD

**Issue by Devo7v** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#48]
If possible it would be nice to have a portable version of this program that could be installed and store it's settings on a flash drive.  It looks like the user settings file is the only file stored outside of the installation directory.  Maybe this could be an option in the installer.

If a portable installation is selected I don't think the installer would require admin rights either which would be helpful for those on locked down computers.

It also may be possible to install a portable version of flash for this program, similar to [what was done for Firefox](http://portableapps.com/node/15501) over at PortableApps.com.

**Comment by MarshallOfSound** [comment]
Portable version of flash is possible, but possible a security risk (not sure really) as it would lock the user to one version of flash which can only be updated through new releases of the whole app.

Portable installation doesn't seem much to ask by itself though (just a zip instead of an installer)

**Comment by MarshallOfSound** [comment]
Moving this to 2.0 because the current update code won't allow a portable release upload this time round

**Comment by MarshallOfSound** [comment]
Related to #64 and #44 

If you read #64, when I get that license I am waiting for I will be able to configure the installer to install to a local directory instead of an admin protected one if admin rights can't be acquired.

That would seem to deal with your problem.  Closing as it is kinda invalid at the moment, but as soon as I get my hands on the Open Source license for the installer I will up date you here to let you know that it will be availible in the next release

**Comment by Devo7v** [comment]
I understand you will be able to make this more configurable when you implement the new installer, but one thing that is very important that I don't want to get lost is the fact that the settings need to be portable as well.  Right now the way the program works, I can install it to any path I would like, but the settings always end up in the %USERNAME%/AppData/Roaming/GPMDP folder.  If I install this to a flash drive and take it to another computer, then I have lost all my settings.

It is important that if you're going to implement a portable version, then you need to make sure the settings are portable as well because as it is implemented right now, they are not.

**Comment by MarshallOfSound** [comment]
From memory, (I haven't touched the settings stuff much it's mostly handled by Visual Studio) your personal settings are stored in `%APPDATA%/Local Settings` and the browser cookies / cache that GPM uses is stored in `%APPDATA%/Roaming/GPMDP`.  The second one I get to choose the first one I don't think I do.

The problem is I can't generically store settings and the browser store in the same folder as the install as if it is installed to `Program Files` while elevated to admin you will need to elevate to admin every time you run it to get write access to a settings file in the `Program Files`.  That is an unacceptable hassle, when compared to the limited use case of a install to a USB drive.  Having to log in again on each computer might just be a sad necessity for anyone installing onto a USB stick.

**Comment by Devo7v** [comment]
That is my point, you can choose where to store the browser cookies/cache.  So if the user chooses a portable installation (on to a flash drive for instance) then the browser cookies / cache should be stored on the flash drive as well and the program should know to look for the cookies / cache there instead of %APPDATA%/Roaming/GPMDP.

I understand that you don't want the program to require admin rights every time it is run, but it should be intelligent enough to look for the cookies / cache folder  in the program folder first (portable installation) and if it can't find it then it should look in %APPDATA%/Roaming/GPMDP (local installation).

Hopefully this is simple and makes sense.  Another option is to create a portable launcher per the PortableApps.com specification.  This is something I create for you if you would like. Basically the cookies/cache folder would be stored on the flash drive.  WHen the launcher is run, it will copy the cookies/cache folder to %APPDATA%/Roaming/GPMDP and then run Google Play Music.exe.  Once the user closes Google Play Music.exe, the launcher will copy the %APPDATA%Roaming/GPMDP folder back to the flash drive and delete it from the local machine.  As long as flash is installed on the local machine, GPMDP will work and nearly everything will be portable.  Let me know if this is something you'd like help with.

**Comment by Devo7v** [comment]
Also, it should be noted that on Windows 7 I don't have a %APPDATA%/Local Settings folder, everything is stored in %APPDATA%/Roaming/GPMDP.  I think that's a Windows XP legacy folder.

**Comment by MarshallOfSound** [comment]
I'm going to have to think about this, there is also the security concern of having unencrypted cookies that give access to your google account on a USB stick.

You make some good points but there is still a bit to think though

**Comment by Devo7v** [comment]
So I went ahead and created a PortableApps launcher for GPMDP.  The launcher contains all the files (including source) needed to properly execute GPMDP and move the %APPDATA% files from the flash drive to the computer and back again as described above.  The only thing that is not included are the program files, these files will need to be copied to ..\GPMDPPortable\App\GPMDP\ (see the attached screenshot).

I'm linking to the launcher installer [here](https://drive.google.com/file/d/0B7MdeKOH-_AkZC1ySjZBdjlqZTQ/view?usp=sharing) if you would like do download it and check it out.  The installer will allow you to select where you would like the program installed to (a flash drive).  It also has the capability of downloading your installer exe and extracting it to the proper directory, but I couldn't figure out how to extract your exe so I've left that functionality out.  For now you'll have to copy the program files to the appropriate directory.

Take a look at it and let me know what you think.  I will not be posting this anywhere else without your consent but I will be using it for personal use until another solution arises.
![screenshot](https://cloud.githubusercontent.com/assets/15945504/11506278/b092e32e-981c-11e5-8ae8-32403671bb28.jpg)

**Comment by Devo7v** [comment]
Would you be willing to upload a zip version of the files in addition to the current installer?  I would then be able to use the PortableApps installer to install the app directly as well as to update it without having to copy and move files.

**Comment by MarshallOfSound** [comment]
Sorry, I kind of forgot to mention this but I have come up with a "compromise" for anyone who wants a portable installer.  Their is a zip file you can download from (here)[https://ci.appveyor.com/project/MarshallOfSound/google-play-music-desktop-player-unofficial/build/job/mtomsxikdi1skyst/artifacts]

A zip file is generated there every time I commit to master so it will always be the latest version

**Comment by Devo7v** [comment]
Thanks for the response.  Maybe I'm dense, but I can't seem to find a link to download the zip?  Is there a public link to it or do I need to create an account in order to access the downloads?
![untitled](https://cloud.githubusercontent.com/assets/15945504/11790033/afa2b264-a267-11e5-8151-03953d592846.png)

**Comment by MarshallOfSound** [comment]
@Devo7v 
You have to follow a link path from that latest build, to the x86 build to the artifacts page.

Which you will find here
https://ci.appveyor.com/project/MarshallOfSound/google-play-music-desktop-player-unofficial/build/job/cqm9v3kt96b832w0/artifacts

**Comment by Devo7v** [comment]
Sorry I was so dense, I got it figured out.  I've also updated the portable installer so that it will download the files and extract them to the appropriate directory.  This only works for one specific download link, so if the link changes I will need to update the installer.  Typically it would be better to just include all the program files inside the installer, but since you are not officially supporting this I assume it would be better to just have the installer download and extract them.

Here's [a link the portable installer](https://drive.google.com/file/d/0B7MdeKOH-_AkbE9TN2pNVUlZVDQ/view?usp=sharing) which includes the source code.  If you have any questions or would like to work towards making this part of the official release, please let me know I'd be glad to help.

**Comment by Devo7v** [comment]
I've been working more on this to try to improve the usability for the end user.  One of the issues I'm running in to is that the GPMDP folder in C:\Users\USERNAME\AppData\Roaming gets larger and larger the more you use GPMDP, right now my folder is at 345MB.  The way the portable launcher works is it moves the GPMDP folder from the portable directory to C:\Users\USERNAME\AppData\Roaming when launched and back when closed.  As you can imagine depending on the size of that directory and the speed of the system it can take a long time to open and close the program.

My question/request is would it be possible for the program to support passing command line parameters so that I can specify the location of the GPMDP folder?  That way it won't have to be copied back and forth and should save significant time opening and closing the portable version.

I understand that this would not be supported which is why I'm asking to be able to specify a command line parameter rather than having it added to the GUI.  A comment either way would be helpful to let me improve the portable launcher.

**Comment by Devo7v** [comment]
The zip files are failing to build on appveyor, any chance you can take a look at it so I can create my portable version?

**Comment by rlabrecque** [comment]
Have you been keeping the portable version up to date @Devo7v? I understand that this issue is closed but I just wanted to voice my support for it regardless. Having a self contained portable version of GPMDP would be excellent.

**Comment by TEdgeNYC** [comment]
Plus 1
