### ISSUE TITLE
Dark theme error

### ISSUE THREAD

**Issue by JimSP76** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#49]
When using the dark theme the curated playlists (top of listen now page) have white text on white background, you can only see them when you mouse over.

Really like the program though, Google should have done this a long time ago.

![capture image-dark theme error](https://cloud.githubusercontent.com/assets/16022140/11407301/918a35d0-9377-11e5-97db-fb2b09a79806.png)

**Comment by MarshallOfSound** [comment]
I'll add that to my list of pages to test, google makes CSS changes far too often.  I'll fix this to go out with the next release.  Sorry bout that :cat:

**Comment by JimSP76** [comment]
No worries, I don't really even use that feature. I just noticed it when I was playing around after I'd installed it.  Keep up the good work.

**Comment by Devo7v** [comment]
Why not implement a way for the user to add their own css?  Userstyles.org has plenty of css styles that are kept up to date, it would be one less thing for you to maintain.

**Comment by Devo7v** [comment]
I also noticed that when implementing the Dark Theme and choosing a custom accent color, that color gets applied everywhere properly except for the work "Music" in Google Play Music, it remains green.

In addition to the color picker, would it be possible to enter a custom rgb or hex color code as well?

**Comment by MarshallOfSound** [comment]
I actually style this in a funky way, not too happy with it but it's how I decided to do it (for some unknown reason :P).  I generate the styles in JS at run time based on selectors.  Adding custom user stylesheets although possible doesn't fit in to the current way I do things.

Custom Hex codes I could do yeah, open it up as a separate issue @Devo7v and I'll tag it for milestone 1.9 with everything else :D
