### ISSUE TITLE
Feature Request: Media Keys and Window Snap Feature

### ISSUE THREAD

**Issue by berryelectronics** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#490]
I think that the keyboard media keys should be set as standard control keys. I personally love that f.ex. the steam client can "snap" on the side of your screen, that its bezel is ligned up with the screen boarders.

**Comment by MarshallOfSound** [comment]
What OS are you on?

Media keys are already by default active?

**Comment by berryelectronics** [comment]
I am running the latest version of it on Windows. Just saw that it says
that they are set as default. However, im using a windows sidewinder x4 and
it seems that they dont work with it. but they work with other things like
vlc media player.

Samuel Attard <notifications@github.com> schrieb am Fr., 11. März 2016 um
16:49 Uhr:

**Comment by PlasmaEye** [comment]
I found that I have to be logged into Chrome for the media keys to work.

**Comment by berryelectronics** [comment]
@PlasmaEye currently im logged in into chrome, i thing its still open. not
sure why its not working. dont different keyboard manufacturers use
different hex codes for the media keys? or is the media key scanning
handled differently?


PlasmaEye <notifications@github.com> schrieb am Fr., 11. März 2016 um
17:59 Uhr:

**Comment by EvanC4** [comment]
I have this same problem. I'm on Windows 10 with a Microsoft Natural 4000 keyboard. I tried both with and without the "Microsoft Keyboard and Mouse Center" drivers installed.

I made a little sample C# app and was able to catch it in WndProc as a WM_APPCOMMAND message with an lParam value of 917504. Apparently that's some kind of generic media key value from the WindowsSDK.

**Comment by MarshallOfSound** [comment]
Closing as the windows "snapping" feature is already implemented and the media key issue is open elsewhere
