### ISSUE TITLE
Cannot go back from mini player to full size

### ISSUE THREAD

**Issue by olembe** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#492]
**OS:**
Ubuntu 15.10

**Issue Descriptions:**
Once mini player is activated, the controls do not display properly, meaning there is no way to get out of the mini player! Screenshot attached to show how it appears to me. 

![screenshot from 2016-03-11 15-53-17](https://cloud.githubusercontent.com/assets/17786085/13707484/cc10d690-e7a1-11e5-998e-18584bae91f9.png)

(Incidentally, I also can't find any sort of keyboard shortcut to get out of the mini player either)

**Steps to Reproduce:**

Activate the mini player.

**Comment by MarshallOfSound** [comment]
This has been fixed in the latest release, ubuntu doesn't have an auto update process so you will have to do it manually

**Comment by olembe** [comment]
No, I'm afraid it's still doing this in 3.0.1. I have to kill it from the command line and relaunch to get a useable player again

**Comment by MarshallOfSound** [comment]
@olembe Sorry mate, but it has.  I just tested it myself on ubuntu.  Can you try completely removing your install and adding it again.  Maybe you updated badly?

**Comment by olembe** [comment]
Ah, right, that's fixed it. Sorry!

**Comment by TravellingGuy** [comment]
This seems to still be an issue.

I'm a brand new user of the desktop player and just installed 3.0.1 (64-bit Debian package) and am experiencing this problem. It only happens if you have the left side-bar menu opened up and you then go to the mini player, this issue occurs. If you don't have the left side-bar menu open up, then the mini player works as expected.

**Comment by MarshallOfSound** [comment]
Maybe my `3.0.1` package is busted :cry: I'll take another quick look

**Comment by MarshallOfSound** [comment]
This is definitely fixed in `3.1.0`
