### ISSUE TITLE
Location issue with 2nd Monitor

### ISSUE THREAD

**Issue by NorberMDP** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#493]
Hi there
I notice that if I have player window in a second monitor, shut down the computer and power on again without a second monitor plugged in, the player "remember" the position and is not visible. Also can't move the windows with hotkeys (WIN + SHIFT + L or R ARROW) and window menu that allows to Move, Restore, etc didn't pop out if right click in the window preview at the task panel.
Thanks for this amazing app.

**Comment by MarshallOfSound** [comment]
Interesting, I'll look into this
