### ISSUE TITLE
Mini player volume control should be configurable

### ISSUE THREAD

**Issue by scottbarrow** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#494]
**OS:**
10.11.3
**Issue Descriptions:**
Mini player settings: should have option to disable "mouse scroll changes player volume"
**Steps to Reproduce:**
* start a track
* launch mini player
* scroll mouse

**Comment by MarshallOfSound** [comment]
I'm just going to ask why?  It's not like you can accidentally scroll on a window...?

**Comment by scottbarrow** [comment]
It would be nice to disable it. It's very sensitive and it's also ignores system scroll direction settings.  On a magic mouse it's easy roll the volume right up.  With earphones this is dangerous and should be configurable.

**Comment by MarshallOfSound** [comment]
I'll be interested in what other people think of this.  I don't want to make every feature in this app optional.  That would turn the entire code base into if statements, so I'd rather not make this an option but if it is annoying to others as well I will consider it

**Comment by scottbarrow** [comment]
Maybe a better approach is a volume slider or to sync with system volume and disable the volume change on mouse scroll.

**Comment by MarshallOfSound** [comment]
The reason it is currently set to scroll to change volume to because there is physically no space for a volume slider.

And syncing with system volume goes against the current design of GPM (Using HTML5 audios volume controls).  Not sure how that would sit with others aswell, I for one like my music quite loud coming out of my SPDIF audio out, and everything else quiet out of my headphones.  Syncing with system volume wouldn't allow that.  

Like I said, I'll let others chime in here and we'll see where it goes

**Comment by cnanney** [comment]
I like the ability to control the volume from the mini player, independent of system volume. I don't care whether it's via scrolling or a separate bar, but it is useful to me.

**Comment by jostrander** [comment]
I can say that the scrolling direction could be cumbersome. Also accidental scrolling is not as uncommon as you might think. The window doesn't have to be activated in order for the volume change to work, so someone who has their windows overlapping might accidentally max out the volume in one flick. An option to disable the scroll volume might not be a bad idea, but ideally it should be a visible component of the web player. I didn't even know scroll volume was available before reading this issue.

**Comment by garzo** [comment]
> It's not like you can accidentally scroll on a window...?

Well, with the Apple Magic mouse where an entire portion of the input source registers the scroll action, this can actually happen inadvertently.  In fact, I only even showed up in the issues section here to mention exactly this and then I saw this issue open.

**Comment by scottbarrow** [comment]
Not to be a alarmist but the only reason I raise this issue with such importance is this unintended action can easily and very quickly change the volume.  Which for IEM users is a serious concern. 
I'm withholding my use of the mini player until this issue is resolved.

**Comment by hndmrsh** [comment]
Casting my vote for this also - I just had the exact issue described, whereby I accidentally scrolled over the mini player with my Magic Mouse, and now my ears hurt. Personally I think changing the volume by scrolling is not the right way to go, as it is completely hidden. I would maybe consider dropping the repeat and shuffle buttons and replacing them with a volume button (which expands into a vertical slider)? I don't think you need to have every button on the mini player (in fact, I would question whether you even need to adjust the volume from the mini player at all).
