### ISSUE TITLE
Thumbs Up/Thumbs Down

### ISSUE THREAD

**Issue by scottbarrow** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#495]
**OS:**
10.11.4

**Issue Descriptions:**
Mini player should display thumbs up and thumbs down options available in the google chrome extension mini player
**Steps to Reproduce:**
* Open mini player

**Comment by MarshallOfSound** [comment]
Looks like a bug in my mini player library.  Can you go raise this issue on that please :+1:
