### ISSUE TITLE
Instant crash on startup on Windows 10

### ISSUE THREAD

**Issue by Alexandroid99** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#50]
It doesn't start up properly and a debug.log won't even be created in the first place. I've tried setting the compatibility mode to Windows 7 but it didn't work. Any other ways of debugging that would help you?

**Comment by MarshallOfSound** [comment]
The windows event log will have a few Exceptions in it probably.  But it is probably due to no installation of the "Visual Studio C++ 2012 Redist x86" pack from Microsoft.  Just google that name and download the official one.  Should work perfectly after that :D

**Comment by Alexandroid99** [comment]
Hmm I was pretty sure I had it installed. Maybe add a warning that it's missing or something. Anyway, thanks for helping.

**Comment by MarshallOfSound** [comment]
Yeah, I'm planning on packaging the redist with the installer in the next release to stop this problem.  Can you confirm it now works @Alexandroid99 ?

**Comment by Alexandroid99** [comment]
Yupp, confirmed. Very nice app! Keep it up.
