### ISSUE TITLE
YouTube icon shows above mini player controls

### ISSUE THREAD

**Issue by cnanney** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#500]
**OS:**
Windows 7 x64

**Issue Descriptions:**
The YouTube icon shows above mini player controls for songs that have a link to YouTube video.

![image](https://cloud.githubusercontent.com/assets/195134/13710256/fdd64da0-e77d-11e5-9316-021e8bf67068.png)

Not sure if supposed to be there or not, but since it's partially overlapping the thumbs up button, I assumed it's a glitch.

**Comment by MarshallOfSound** [comment]
There is open PR on the mini player repository to fix this

**Comment by ScottBeeson** [comment]
Why hasn't this been fixed yet?
