### ISSUE TITLE
Windows: Media Keys can't get hotkey'd 

### ISSUE THREAD

**Issue by adajan** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#502]
Hey,

I've been trying to set the hotkeys to my media keys on my keyboard, yet it won't set. Any normal keyboard key gets set. Previous version worked.

**Comment by LovedByTheLord** [comment]
This is probably a duplicate of https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/344.
