### ISSUE TITLE
Thumbs up and thumbs down indicators are missing from the playlist view.

### ISSUE THREAD

**Issue by dst33nburgh** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#51]
Here's a side-by-side comparison of google play music in browser and in the desktop app.
![capture](https://cloud.githubusercontent.com/assets/9411156/11415320/20144986-93c7-11e5-827e-348d8bcbf15d.PNG)

**Comment by MarshallOfSound** [comment]
Ooooh, good catch.  Small UI differences like these are like playing spot the difference on extreme difficulty :P
Easy fix, will be in next release :DD

Edit: Just saw your PR, will look at it when I get back

**Comment by MarshallOfSound** [comment]
@dst33nburgh Don't suppose you want to figure out the CSS fix for #49 as well by any change :smile:

**Comment by dst33nburgh** [comment]
I have very little free time right now as I'm in college, but against my better judgement I think I'll have a go at it!

**Comment by MarshallOfSound** [comment]
@dst33nburgh Lol, anything to get out of doing school work, amirite :100:
