### ISSUE TITLE
Uncaught Exception: Update check failed: (null)

### ISSUE THREAD

**Issue by georgebohnisch** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#513]
An uncaught exception was reported.  
#### Info:
**OS:** darwin
**Arch:** x64
**GPMDP Version:** 3.0.0
**Time:** Fri Mar 11 2016 18:36:26 GMT-0600 (CST)

#### Error:
*Update check failed: (null)*
```js
Error: Update check failed: (null)
    at Error (native)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
Restart the app and accept the update.

This error will not appear again
