### ISSUE TITLE
All I did was login for the first time after installing. :(

### ISSUE THREAD

**Issue by xnaas** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#516]
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.1
**Time:** Fri Mar 11 2016 21:27:47 GMT-0600 (Central Standard Time)

#### Error:
*Attempting to call a function in a renderer window that has been closed or released. Function provid*
```js
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: Object.<anonymous> (C:\Users\lwate\AppData\Local\GPMDP_3\app-3.0.1\resources\app\build\inject\GPMInject\interface\mouseButtonNavigation.js:8:8.
    at BrowserWindow.callIntoRenderer (C:\Users\lwate\AppData\Local\GPMDP_3\app-3.0.1\resources\atom.asar\browser\lib\rpc-server.js:201:19)
    at emitTwo (events.js:92:20)
    at BrowserWindow.emit (events.js:172:7)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
Please do not change the title for an automatic issue report, it messes up my handling of these issues.

This issue has been fixed in #370

**Comment by xnaas** [comment]
Sorry. It was cut off so I figured it wouldn't matter. :/

**Comment by MarshallOfSound** [comment]
I am currently in the process of writing a bot to handle lots of these automatic issues.  If you start changing the name it makes it a lot harder :smile:

**Comment by xnaas** [comment]
I see. Apologies! I will remember next time. :)
