### ISSUE TITLE
Customizable theme color

### ISSUE THREAD

**Issue by Sensei-Hanzo** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#518]
The old version had a color wheel where you could select whatever highlight color you wanted for the dark theme, and now there are only presets. Would it be possible to put the color selector back in?

**Comment by kayakyakr** [comment]
In that vein, with the dark theme, the playlist default color is a dark link, making it not visible unless I hover.

**Comment by MarshallOfSound** [comment]
To make something clear, there is no concept of "put it back in".  This is a completely new app, running on a completely new framework, with a brand new code base.  If you look for the commit you will see everything gets deleted and new code is added.

With that said, I can not currently find a color picker written in vanilla JS that I like the look of or does the actions I need it to.  Therefore I am in the process of writing one myself.  This is a slow process and it's slotting in amongst the ever increasing number of things I need to handle.

PR's are welcome :+1:

**Comment by Sensei-Hanzo** [comment]
Thanks for the explanation and sorry if it's frustrating to see questions like this. I wasn't aware of everything that was going on code-wise with the new version and just wanted to provide some feedback based on my usage. I hope you (or someone else) will be able to figure out a way to implement this.

**Comment by eXtreme** [comment]
> With that said, I can not currently find a color picker written in vanilla JS that I like the look of or does the actions I need it to. Therefore I am in the process of writing one myself. This is a slow process and it's slotting in amongst the ever increasing number of things I need to handle.

@MarshallOfSound Why can't you use `<input type="color" />`? [It should work](https://github.com/atom/electron/pull/777) in electron and show a native system color picker window.
