### ISSUE TITLE
Does not respond to media keys

### ISSUE THREAD

**Issue by s0urc3d3v3l0pm3nt** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#521]
**OS:**
OSX 10.11.2 & Windows 10 pro
**Issue Descriptions:**
Media keys (forward, previous, play/pause toggle) are not responded to by the app.  
**Steps to Reproduce:**
1. Play a album/radio station and try on of the following pressing the media forward, previous, or play/pause keys

**Notes**
This issue was not present on the windows app before the 3.0 release

**Comment by MarshallOfSound** [comment]
Have you read the [FAQ](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ)

**Comment by unknownv2** [comment]
I don't have the chrome extension but the media keys don't work. They work in version 2.1.1 though.

I have an ISIGNIA keyboard.

**Comment by MarshallOfSound** [comment]
Closing as duplicate of #344
