### ISSUE TITLE
Back/Forward detection sketchy on Linux

### ISSUE THREAD

**Issue by kayakyakr** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#523]
### OS:

Linux/?

### Issue Descriptions:

I noticed in 3.0.1 the back/forward buttons should be working, but, unfortunately, they are not. I was hoping it was a matter of you finding a way to detect button and setting it to 4 & 5, ignoring the fancy all button mice (I've got 10), but it looks like you're relying on this app-command event, and that seems like it'll be a pain to track down.

One of these days I'll have the time to sit down and help debug some of this stuff... One of the days...

**Comment by MarshallOfSound** [comment]
This is an electron framework limitation, not much I can do in regards to this.
