### ISSUE TITLE
Custom theme setting no more accessible since 1.8.0

### ISSUE THREAD

**Issue by Leogiciel** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#54]
In settings, custom theme and custom color settings can't be found.

**Comment by MarshallOfSound** [comment]
Since 1.8.0 they have moved to their own dedicated settings option.  You can open the dedicated settings window by clicking on the "Desktop Settings" option underneath the normal "Settings" option in the slide out menu on the left.

**Comment by Leogiciel** [comment]
The "Desktop settings" option cannot be found either !
![capture](https://cloud.githubusercontent.com/assets/1555868/11422947/7e39343a-9440-11e5-995b-a743028b50bb.PNG)

**Comment by MarshallOfSound** [comment]
That's possibly a known bug due to a non English language, reopening to track that issue.  As a temporary work around.  Switch to english US

**Comment by MarshallOfSound** [comment]
Reopened my reporter in #58
