### ISSUE TITLE
Application Reconfigurations

### ISSUE THREAD

**Issue by ERev74** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#543]
Hi. Love the app! Thanks for making it!    With the latest version - when I open it a whole bunch of entries are created in my reliability monitor.  I am running Windows 10 64bit.

![capture](https://cloud.githubusercontent.com/assets/17811428/13728874/c4eea444-e8e3-11e5-83f4-a7270e8c099c.PNG)

**Comment by MarshallOfSound** [comment]
What am I looking at here?

What is a "reliability monitor"?

What is the issue?

**Comment by ERev74** [comment]
In Windows 10 - Here is a more precise screenshot:

![capture](https://cloud.githubusercontent.com/assets/17811428/13729009/365b73d4-e8e7-11e5-9cf8-f5b5ecaf6cae.PNG)

**Comment by MarshallOfSound** [comment]
I'm sorry but I'm closing this.  You have provided a screenshot of a bunch of "Informational" events which as far as I can tell have NOTHING to do with this app...

How is this even a problem?  They are INFO events?

**Comment by ERev74** [comment]
Hi. Sorry. Let me clarify. Yes these are info events and they are only created and generated when I open the music player.  They appear in the reliability monitor right after the music player is opened.

**Comment by MarshallOfSound** [comment]
Still don't see how this is an issue with this app, so far I can see that some applications "reconfigure" when the app is opened.  (Only on your PC apparently as I checked this section of control panel and it doesn't on mine)

This doesn't appear to be an issue at all, it could be these apps reacting to any number of things (new shortcuts, a new port being used, a random thing it is detecting, literally ANYTHING)

But as said before, I don't see how this is an issue....

**Comment by ERev74** [comment]
Its not an issue with the app. Just strange how the other apps in my system react to it.

Thanks for taking a look.

**Comment by MarshallOfSound** [comment]
@ERev74 To be honest that statement is infuriating

> Its not an issue with the app

You literally raised this as an **issue** if it's not an issue, don't waste my time please
