### ISSUE TITLE
Closing main window no longer minimizes to tray

### ISSUE THREAD

**Issue by MightyPork** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#544]
I just updated to the latest master, and closing the main window no longer closes the player to tray.

I'll try to find what commit caused it (but it can also be caused by an Electron update).

**Comment by MightyPork** [comment]
aha, got it. That was easy.

It started after the very latest commit: 3597d506005bbefedc751c8befad665432b9b110

Got to revert that for my fork ....

**Comment by MarshallOfSound** [comment]
Ahh, sorry, this issue is currently fixed in my local changes.  I'll push it tomorrow morning (about to sleep now)
