### ISSUE TITLE
Exception thrown when trying to use "back" button on mouse

### ISSUE THREAD

**Issue by Mastergalen** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#545]
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.1
**Time:** Sun Mar 13 2016 16:01:52 GMT 0000 (GMT Standard Time)

#### Error:
*Attempting to call a function in a renderer window that has been closed or released. Function provid*
```js
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: Object.<anonymous> (C:\Users\Mastergalen\AppData\Local\GPMDP_3\app-3.0.1\resources\app\build\inject\GPMInject\interface\mouseButtonNavigation.js:8:8.
    at BrowserWindow.callIntoRenderer (C:\Users\Mastergalen\AppData\Local\GPMDP_3\app-3.0.1\resources\atom.asar\browser\lib\rpc-server.js:201:19)
    at emitTwo (events.js:92:20)
    at BrowserWindow.emit (events.js:172:7)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
Closing as fixed duplicate, please don't change the title in an automatic report so my system can catch it
