### ISSUE TITLE
Upload music not found

### ISSUE THREAD

**Issue by JuanTomasVillegas** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#55]
What about the upload music menu? It´s no possible get it?

**Comment by MarshallOfSound** [comment]
Short answer no.  It would involve customly implementing the file drag and drop API's along with the file open API and a bunch of other stuff that seemed overly complex at the time.  For now, uploading music should be done through Google's "Music Manager" application (by far better than dragging and dropping into a website)

**Comment by MarshallOfSound** [comment]
The won't fix tag is temporary, this might be implemented at some point, but not any time soon.  (At least not by me, anyone else feel free to give it a shot) :smile_cat:

**Comment by JuanTomasVillegas** [comment]
Hi Samuel!!

Thanks a lot for your fast answer from the antipodes (Basque Country)! 

And thanks a lot for your work!

**Comment by MarshallOfSound** [comment]
No problem, thanks for using it :P

For anyone else having similar questions to this "where is feature blah blah blah, from the web version".  Basic rule is, if you can't see it, I hid it, because it doesn't work :+1:
