### ISSUE TITLE
Pauses music when closing the window

### ISSUE THREAD

**Issue by Nxt3** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#554]
**OS:** OS X v10.11.3

**Issue Descriptions:** On version 3.0, when you were listening to music and you closed the window, the music would continue playing and the app could minimized to the tray. Now, when you are playing music and you perform the same actions--the music pauses. Using the "Play" media key starts the music again.

**Steps to Reproduce:** Listen to music, then close the window.

**Comment by MarshallOfSound** [comment]
It sounds like you have disabled the option "minimize to taskbar".  Can you make sure that option is ticked

**Comment by Sidnicious** [comment]
Same issue here, that option *is* ticked. I'm running v3.0.1 on OS X.

**Comment by MarshallOfSound** [comment]
OK, so maybe OS X is borked in this regard, I'll look into it :+1:

**Comment by jostrander** [comment]
Having the same issue on Linux. :+1:

**Comment by MightyPork** [comment]
@jostrander That was introduced in a recent commit, but Marshall meanwhile fixed it (I think, guessing from the commit diff).
That issue is here: https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/544

Before that commit it works fine for me. Haven't tried latest master yet.

**Comment by MarshallOfSound** [comment]
@jostrander I have fixed the closing entirely issue, that was some bad code on my part :cactus: 

Still looking into this issue

**Comment by Nxt3** [comment]
This is still broken on v3.1.0.
