### ISSUE TITLE
Update Checks are performed via plain HTTP

### ISSUE THREAD

**Issue by ctrezevant** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#556]
**OS:** OS X and Linux, but presumably all.

**Issue Descriptions:** 

GPMDP's update mechanism is based on [Squirrel](https://github.com/Squirrel/Squirrel.Windows), which checks for updates by making an http call to a JSON feed. This feed will return a JSON response containing update information if the requested version exists. For example, GPMDP's feed (located at http://update.googleplaymusicdesktopplayer.com/update/{platform}/{versionnumber}) currently looks like this:

    {  
       "url":"http://update.googleplaymusicdesktopplayer.com/download/version/3.0.1/osx_64?filetype=zip",
       "name":"3.0.1",
       "notes":"This is a bugfix release of...",
       "pub_date":"2016-03-11T02:53:45.000Z"
    }

Because this call is performed via plain http, an attacker can perform a man-in-the-middle attack to push a malicious update to unsuspecting users. Compounding this, not only is the API endpoint HTTP only- the url property, which contains the download link, is plain HTTP as well!

In fact, I was able to create my own imitation update server that successfully triggered an update on 2 different macs after changing the IP of update.googleplaymusicdesktopplayer.com in my router's config (simulating DNS poisoning): 

![mac 1](https://cloud.githubusercontent.com/assets/7227500/13732169/57e2c76c-e952-11e5-85cb-09ff08f19508.png)

![mac 2](https://cloud.githubusercontent.com/assets/7227500/13732173/6dd26d20-e952-11e5-8a33-f91428d7481a.png)

**Steps to Reproduce:** 

My web server configuration and false JSON response can be found in [this gist](https://gist.github.com/ctrezevant/cdcf8a9f89b40304d6c9). This also contains an excerpt from my web server logs showing the behavior of GPMDP as it parses the fake update information I served.

**Suggested fixes:**

All of the Squirrel API endpoints for googleplaymusicdesktopplayer.com should be served over HTTPS. As it currently sits, the domain has [no HTTPS support at all whatsoever](https://www.ssllabs.com/ssltest/analyze.html?d=update.googleplaymusicdesktopplayer.com&latest). 

Once HTTPS has been implemented, [autoUpdater.js](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/main/features/core/autoUpdater.js) should be updated (heh) to reflect the changes.

**Comment by MarshallOfSound** [comment]
OK so let's tackle this one point at a time

1.  I am aware of this, the problem is actually that no one wants to give me an SSL certificate for a domain with the word "Google" in it
2. Although you triggered an update popup, on OS X and Windows the update will not install due to the codesign verification failing.

That said, I am working on aliasing the update server to https://update.gpmdp.xyz and that should go live shortly.

Thanks for pointing this out

**Comment by ctrezevant** [comment]
Awesome, thanks for the great app!

**Comment by MarshallOfSound** [comment]
SSL is live on https://update.gpmdp.xyz/api/versions

**Comment by MarshallOfSound** [comment]
Just waiting for DNS to propagate before changing the URL in the app

**Comment by MarshallOfSound** [comment]
SSL pushed to master
