### ISSUE TITLE
Need to setup the Wiki

### ISSUE THREAD

**Issue by MarshallOfSound** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#56]
There a quite a few questions on Reddit and even some raised as issues here which have very simple and somewhat obvious solutions.  These questions and answers should be put in some sort of basic userguide in the Wiki so that **hopefully** they don't get asked too much anymore.

*Even if they do get asked, I'd just link the wiki and run* :smile_cat:

**Comment by MarshallOfSound** [comment]
If anyone wants to help with this, commenting below a set of basic instructions for performing a task, accompanied with screenshots would be very helpful.  Just choose a task (like changing the setting, for some reason people can't find it) and go for it. :tada:

**Comment by davidchill** [comment]
Hey, I'd be more than help to write-up some how-to's and tutorials for just a basic FAQ page for you. I'm very good at writing training material, so I can make it easy for people to understand.
