### ISSUE TITLE
Add "Show full player" and "Show mini player" options to tray menu

### ISSUE THREAD

**Issue by tehoko** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#565]
**OS:** Windows 7

**Issue Descriptions:** The mini player window sometimes gets glitched, and controls are not accessible. Unable to move back to full window mode, since the button is unreachable.

![image](https://cloud.githubusercontent.com/assets/2924029/13738366/c7ac684c-e9c4-11e5-87ec-687c18fc28a7.png)

**Steps to Reproduce:** Unknown. It happened to me twice on one PC within a few minutes, but didn't appear on another (Windows 10). The one that had this issue has three monitors, if that changes anything (though the window was minified on the same screen as the full player was on).

**Suggestion**: Please add a "Show full player window" option to the tray menu, so that it's possible to go back in case of something like this without needing to close the player completely.

**Comment by MarshallOfSound** [comment]
You haven't updated.  If you didn't get the update notification can you please download the latest release manually and install it.

This issue was fixed in `3.0.1`
