### ISSUE TITLE
Greater hotkey flexibility

### ISSUE THREAD

**Issue by SicariusNoctis** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#566]
The choice of hotkeys seems limited. On my "old" music player, I had Ctrl+Shift+Space set to Play/Pause. Now, I can only set it to Ctrl+Shift+C, which is difficult to get used to.

Is there a reason behind this particular limitation? Can it be removed?

**Comment by MarshallOfSound** [comment]
Not a limitation to be removed, rather additional functionality to be implemented.

My current hotkey javascript needs improving, there is an issue #413
