### ISSUE TITLE
Back and forward buttons on mouse do not function.

### ISSUE THREAD

**Issue by AsgerSommer** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#57]
I've grown quite accustomed to using my back/forward mouse buttons to navigate back and forth in browsers, especially when using Google Music, but I can't in this application. Is this a bug or just unsupported in the application?

**Comment by MarshallOfSound** [comment]
Unsupported hotkeys, I've tried and failed to get them working.  If you wanna have a go by all means

**Comment by MarshallOfSound** [comment]
Related to #19
