### ISSUE TITLE
"About" in Ubuntu

### ISSUE THREAD

**Issue by greenwald** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#578]
OS: Ubuntu 14.04.4
Version 3.0.1-1

There's no way---as far as I can see---to get information about the version of the player since there's no menu bar in Ubuntu as one might have on Windows or Mac OS X. You may think to add an "about" tab to the settings menu, or to the right-click menu on the tray icon. (Or a flag to the terminal command: "--version".)

**Comment by MarshallOfSound** [comment]
Have you tried the `--version` command or `-v`, I wouldn't be surprised if one of them worked.

Not saying one of them should, but electron might have implemented it :+1:

**Comment by greenwald** [comment]
Neither command works. Nor does `--help`

**Comment by MarshallOfSound** [comment]
*sighs* Guess I'll have to do it myself or something then :cry:

**Comment by jostrander** [comment]
I'll tackle this I suppose, what are we looking for here, a command line switch or an About dialog in the menu bar?

**Comment by MarshallOfSound** [comment]
A command line switch would be non intuitive (as in it's actual use as any command has to be passed in with a double `-` preceding it`

E.g. The `-v` switch would need `-- -v`
