### ISSUE TITLE
Uncaught Exception: The request timed out.: (null)

### ISSUE THREAD

**Issue by jakswa** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#582]
Occurred sometime between closing my laptop on Friday and going to use it again today (Monday). Looks like networking-related issue, I'm on wifi so it might've took a minute to connect after re-opening the laptop.

An uncaught exception was reported.  
#### Info:
**OS:** darwin
**Arch:** x64
**GPMDP Version:** 3.0.0
**Time:** Mon Mar 14 2016 12:02:08 GMT-0400 (EDT)

#### Error:
*The request timed out.: (null)*
```js
Error: The request timed out.: (null)
    at Error (native)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
You still haven't got the update to `3.0.1`?  Can you please restart the app and will the gods of updates that you get it :+1:

**Comment by MarshallOfSound** [comment]
Oh yeah, forgot to mention.  This is fixed in the new update

**Comment by jakswa** [comment]
:+1: closed and reopened, got the update
