### ISSUE TITLE
Wrong Logo displayed in Ubuntu Dock

### ISSUE THREAD

**Issue by mspl13** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#590]
**OS:** Ubuntu 14.04.4 LTS

**Issue Descriptions:** After installation I started the player for the first time and everything was fine. After I restarted my computer and started the player again, the google logo (maybe from the login page?) appeared in my dock (see the screenshot below).
![screenshot from 2016-03-14 18 51 11](https://cloud.githubusercontent.com/assets/8393513/13754239/8a7a4636-ea16-11e5-8696-f7e99de9b60a.png)

**Steps to Reproduce:** For me, just starting the player.

**Comment by MarshallOfSound** [comment]
Well it kinda looks like a google logo? :+1: 

But yeah, soemthings gone wrong there

**Comment by SolarPolarMan** [comment]
I'm on eOS which is based on Deb and this isn't a problem for me

**Comment by mspl13** [comment]
Is there some way I could provide a debug log? Couldn't find a way so far...

**Comment by MarshallOfSound** [comment]
This is quite possibly a bug in electron, I will have to test around.

There is not currently any debug logs stored anywhere.  (Maybe something else I should change)

**Comment by jostrander** [comment]
@mspl13 can you run this command in your terminal? Might be able to get more of a hint at what's going on here.

```
locate google-play-music-desktop-player.desktop | xargs cat
```

**Comment by mspl13** [comment]
Of course. I'm not sure that this output is somehow valuable, but here you go:

```
[Desktop Entry]
Name=Google Play Music Desktop Player
Comment=An electron wrapper for Google Play Music
GenericName=Google Play Music Desktop Player
Exec=google-play-music-desktop-player %U
Icon=google-play-music-desktop-player
Type=Application
StartupNotify=true
Categories=GNOME;GTK;Utility;
MimeType=text/plain;
```

**Comment by jostrander** [comment]
Not as valuable as I'd hoped. Does the icon persist if you remove it from the dock and repin it, or is it there from when you start initially? Does reinstalling fix the issue?

**Comment by mspl13** [comment]
@jostrander Nope, it didn't. But I found another interesting behavior: If I launch the application from the terminal, the wrong icon is displayed. If I launch it from the unity launcher the right icon shows up.

**Comment by MarshallOfSound** [comment]
This is sounding more and more like an electron bug.  Can you raise this over at `atom/electron` and see what they have to see about it.

Include the information that starting from terminal = wrong icon but starting from launcher = right icon

**Comment by mspl13** [comment]
Just for your information and an update on this issue:
According to the electron team this is a bug in Unity itself, not electron (see [here](https://github.com/atom/electron/issues/4878)) and is maybe already fixed in newer versions.
