### ISSUE TITLE
Media Keys in Windows stoped working after update

### ISSUE THREAD

**Issue by bobloadmire** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#591]
Can't get media keys to work anymore. They worked perfectly pre-update. I closed chrome because I read that could hijack the media keys, but that didn't help. Also I can't get the custom short cut page to take any keys either.

Windows 10
latest update

**Comment by MightyPork** [comment]
what update? "3.0.0" -> "3.0.1" ?

**Comment by MarshallOfSound** [comment]
From the sounds of it @MightyPork it would be "2.x" -> "3.0.1".

Media keys will be 100% fixed in `3.1.0` release

**Comment by bobloadmire** [comment]
yes I went straight from 2.x to 3.0.1

**Comment by MarshallOfSound** [comment]
@bobloadmire Media keys will be fixed in `3.1.0` in the meantime if you read the FAQ page in the wiki there are solutions to get them working
