### ISSUE TITLE
Feature request: Support for desktop notifications

### ISSUE THREAD

**Issue by hndmrsh** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#6]
When using Google Play Music in Chrome, a desktop notification appears when the track changes. This would be a super useful feature, especially if it used the new notifications in Windows 10.

**Comment by MarshallOfSound** [comment]
This is currently in progress, working on displaying album art in the notification

**Comment by MarshallOfSound** [comment]
Feature in master, awaiting 1.4 release
