### ISSUE TITLE
npm install fails on Fedora 23

### ISSUE THREAD

**Issue by brunofin** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#603]
**OS:** Fedora 23 64-bits (uname -a: Linux verde-laptop 4.3.5-300.fc23.x86_64 #1 SMP Mon Feb 1 03:18:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux)

**Issue Descriptions:**

When I run `npm install` after a fresh clone of the git repository, I get the following error:

```bash
[verde@verde-laptop Google-Play-Music-Desktop-Player-UNOFFICIAL-]$ npm install
npm http GET https://registry.npmjs.org/ll-keyboard-hook-win
npm http 304 https://registry.npmjs.org/ll-keyboard-hook-win
npm WARN optional dep failed, continuing ll-keyboard-hook-win@2.0.2

> google-play-music-desktop-player@3.0.1 postinstall /home/verde/git/Google-Play-Music-Desktop-Player-UNOFFICIAL-
> node vendor/rebuild.js


/home/verde/git/Google-Play-Music-Desktop-Player-UNOFFICIAL-/vendor/rebuild.js:9
build.stdout.on('data', (data) => {
                                ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
npm ERR! weird error 8
npm ERR! not ok code 0
```

**Steps to Reproduce:**
1. Open a terminal;
2. Run these commands:
```bash
cd git
git clone https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-.git
cd Google-Play-Music-Desktop-Player-UNOFFICIAL-
npm install
```

**Comment by MarshallOfSound** [comment]
There are dev dependencies listed in the README.

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#dev-requirements

Looks like you have an old version of node

**Comment by brunofin** [comment]
You're absolutely right. I apologize for wasting your time.
For some reason Fedora's package manager contains a very old version of NodeJS.

Just as a reference for future readers (and I see that I wasn't the first to open an issue for the same problem), I easily updated my NodeJS following this guide: http://tecadmin.net/upgrade-nodejs-via-npm/#

I didn't need to make the symbolic link as in the last step though.
