### ISSUE TITLE
Uncaught Exception: Update download failed: (null)

### ISSUE THREAD

**Issue by ixnu** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#606]
An uncaught exception was reported.  
#### Info:
**OS:** darwin
**Arch:** x64
**GPMDP Version:** 3.0.0
**Time:** Tue Mar 15 2016 07:40:26 GMT-0400 (EDT)

#### Error:
*Update download failed: (null)*
```js
Error: Update download failed: (null)
    at Error (native)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
Well that sucks, no idea what would cause that.  Maybe a proxy or dodgy network?

Try restarting the app and it will try download again.  Otherwise download the latest release manually
