### ISSUE TITLE
Ubuntu: Cannot quit program when "Minimize to Tray" is enabled

### ISSUE THREAD

**Issue by AGummyBear** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#608]
**OS:**
Ubuntu 14.04.4 LTS

**Issue Descriptions:**
Unable to quit program when "Minimize to Tray" setting is enabled.

**Steps to Reproduce:**
- Enable "Minimize to Tray" setting
- Click X to close program => Minimizes to Launcher as expected
- Right click on Launcher icon, select "Quit" => Nothing happens

- Enable "Minimize to Tray" setting
- With program open, right click on Launcher icon, select "Quit" => Minimizes to Launcher

Disabling "Minimize to Tray" works as expected and closes the program.

**Comment by MarshallOfSound** [comment]
Does the quit option from the tray menu work?

**Comment by AGummyBear** [comment]
Yes, the quit option from the tray appears to function properly. Both are labeled as "Quit" but performing this from the Launcher right click menu has the same function as clicking the X button on the window.

**Comment by jostrander** [comment]
As far as I can tell, the quit in the dock is the same as pressing the X in the title bar, so even though this could be considered a bug, I'd say it's just a side effect of having the minimize option on. The only alternative I can think of here would be to have a check to see if its already minimized when being closed and then close if it is.

**Comment by MarshallOfSound** [comment]
My research implies what @jostrander has said, the "quit" option in the launcher is actually the equivalent of "closing" the window, so the app receives the `close` event instead of the `quit` event.  

There is nothing I can do about this as it is core design of the OS rather than implementation on my side
