### ISSUE TITLE
On OS X, menu bar icon is low-res on retina screens.

### ISSUE THREAD

**Issue by nthapaliya** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#609]
Version 3.0.1 of this app, downloaded from the github releases page. I'm on El Capitan if that helps.

I searched through closed and open issues to see if this is a duplicate. I didn't find anything so I'm opening one now.

See attached screenshot.

<img width="139" alt="screen shot 2016-03-15 at 8 18 45 am" src="https://cloud.githubusercontent.com/assets/4131655/13780888/d45e4cc8-ea86-11e5-95cb-a79170d7738c.png">

**Comment by jostrander** [comment]
@MarshallOfSound all that's needed here is an image that's 2x the normal size, and then the file name needs to be appended with `@2x`. If I had the sources for the graphics I'd make them but I can't upscale the current template logo. [see here](https://github.com/atom/electron/blob/master/docs/api/native-image.md#high-resolution-image)

**Comment by jostrander** [comment]
I don't have mac to test these out, but if anyone wants to try them:

![mactemplate 5x](https://cloud.githubusercontent.com/assets/760989/13871101/1b5c6fbe-ecb8-11e5-9714-896be7b0bbed.png) `@5x`
![mactemplate 2x](https://cloud.githubusercontent.com/assets/760989/13871100/1b5bf3e0-ecb8-11e5-91c6-fcf92a2944b5.png) `@2x`
![mactemplate](https://cloud.githubusercontent.com/assets/760989/13871102/1b5cb9b0-ecb8-11e5-8bbb-efc426e7e4e8.png)

**Comment by MarshallOfSound** [comment]
@jostrander I believe the current template images are just greyscale of the full size logo of which there is a 256x256 in the repo

**Comment by amweiss-pki** [comment]
It looks like the sizes are a bit off so things are pixelated in some displays.
It should be the standard 16, 32, etc. sizes whereas they are currently quite odd sizes (19, 38, 95).

Do you have a vector image version somewhere? If so I can create the appropriate sizes.  Otherwise I can work from the 256 version to scale down to the correct sizes but they will still be pixelated.

**Comment by MarshallOfSound** [comment]
No vector version's unfortunately, I might look into recreating it as a vector.

Best we have at the moment is the 256 one
