### ISSUE TITLE
Highlight color only applys on dark theme.

### ISSUE THREAD

**Issue by SolarPolarMan** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#620]
**OS:**Elementary OS (Debian)

**Issue Descriptions:** see title.

**Steps to Reproduce:**Make sure you have dark theme off. Attempt to set a highlight color. Note it does nothing. Feel sad.

This may just be a non existent feature but the app doesn't really make it seem so.

**Comment by SolarPolarMan** [comment]
Also I feel there should be a little border around your selected highlight color because right now I feel there's not enough user feedback.

**Comment by MightyPork** [comment]
It's indeed non-existent, there's a ticket for it in the theme.js repo, IIRC.
Graying out the colours in light theme sounds like a cool idea (or some other effect).

**Comment by MarshallOfSound** [comment]
There is actually a PR in the theming repo that is currently being reviewed to enable "light" theming I guess you would call it

**Comment by MarshallOfSound** [comment]
Closing as it belongs in the theming repo (where a ticket already exists)

**Comment by SolarPolarMan** [comment]
link to the theming repo?

**Comment by MightyPork** [comment]
here, made you a clicking tutorial :P

1)
![screenshot_2016-03-16_17-17-22](https://cloud.githubusercontent.com/assets/2041118/13819786/0d0fc488-eb9b-11e5-8f5c-bd678eaf3461.png)

2)
![screenshot_2016-03-16_17-17-30](https://cloud.githubusercontent.com/assets/2041118/13819792/0f3a98d2-eb9b-11e5-82e7-aad47691adc2.png)
