### ISSUE TITLE
Feature Request: Bluetooth headset input controls

### ISSUE THREAD

**Issue by outcast** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#626]
It would be nice to be able to use the controls that are on my bluetooth headset similar to the way the media keys work.

**Comment by MarshallOfSound** [comment]
This is currently not physically possible as far as I am aware.  Unless there is an actual key event being fired when you push the bluetooth headset buttons

**Comment by jostrander** [comment]
I've heard it will fire keyboard codes, but it's very OS dependant if I'm not mistaken.

**Comment by MarshallOfSound** [comment]
On windows I can pick up ANY keyboard code if it fires one.  Not sure what I would do about linux/OS X

**Comment by outcast** [comment]
understood. I think there will be more options with new os x libraries that are coming out. I think it sucks 
that apple has not unified this between iOS and OS X.

**Comment by LordCatzorz** [comment]
On Windows, it seems possible.
WinAmp is somewhat responsive to my Sony headset bluetooth media button. The "play/pause" seems sadly mapped as "stop", but I can change track.
I have not fully looked into what's going on.

**Comment by MarshallOfSound** [comment]
I don't have a bluetooth headset peoples so if someone that does could check this out and see if it fires any key events. :+1:

**Comment by MarshallOfSound** [comment]
If anyone does want to pick this up the best place to start is checking if MediaPlayPause is fired in the `app-command` channel when pushing the buttons on your headset

https://github.com/atom/electron/blob/master/docs/api/browser-window.md

**Comment by bagedevimo** [comment]
I'll give this a go today all going to plan with the time and schedule.

**Comment by MCManuelLP** [comment]
In Linux, these are the informations for each of those buttons I got from xev: keycode 208 (XF86AudioPlay), keycode 209 (XF86AudioPause), keycode 171 (XF86AudioNext), keycode 173 (XF86AudioPrev)... So it seems like they should be the same as other kinds of media keys but for me only previous and next actually works...

**Comment by bagedevimo** [comment]
Are those the keycodes from a bluetooth device?

**Comment by MCManuelLP** [comment]
Yes. Specifically the Phillips SHB5500.

**Comment by outcast** [comment]
Can't get any information from OS X :( tried with KitSound KSMHDTBK.

**Comment by bagedevimo** [comment]
So there is a tool that exists for OSX that servers to retransmit keydown from bluetooth devices into media keydown's, see: https://github.com/jguice/mac-bt-headset-fix/blob/master/Spotify%20Bluetooth%20Headset%20Listener/KDMAppDelegate.m#L40-L65

I'll have to go hunting and figure out if Electron has a way of listening to events from a addGlobalMonitorForEventsMatchingMask call.

**Comment by MarshallOfSound** [comment]
@bagedevimo It'll probably end up being a native module in cpp.  I doubt electron has bluetooth functionality

**Comment by jostrander** [comment]
@bagedevimo wouldn't running the software you linked allow you to map your bluetooth keys to your keyboard media keys for any application?

**Comment by bagedevimo** [comment]
Yeah, it runs fine & works fine with Google Play Music Desktop Player. :) -
I just thought first class support would be nice. That utility i linked
above has the downside in that is is sometimes very slow, 3-5s between
pressing pause and the music pausing, sometimes.

**Comment by RazvanRotari** [comment]
For me on Linux it the keys from the headset work only if I focus the "Desktop settings" window. I've tried with Play, Next and previous.  

It is possible to make them global? I know that nuvola player has this functionality and it's really great.(For normal key at least)

The headset is PHILIPS SHB3060BK/00
OS:14.04.1-Ubuntu

**Comment by knightcrusader** [comment]
I want to add in Windows, Bluetooh controls should be converted to keyboard media controls automatically. At least it all my other apps in Windows (VLC, Winamp, etc) will respond to the bluetooth headset controls when keyboard control hotkeys are enabled. This worked for me in XP, 7, and 8.1

**Comment by jostrander** [comment]
Just as a recap:

### Windows
Bluetooth headsets should work on windows when they send the correct media keyboard events as key presses, without the help of extra software.

### OS X
Not Possible without third party software or writing a custom node module on OS X that will re-transmit the events to our electron app.

### Linux 
As long as the media keyboard events are fired from the headset it should be picked up in gnome and mate based window managers via dbus media key listener. If there are others that work similarly but have a different name that needs to be added, it can be added here:

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/main/features/linux/mediaKeysDBus.js

**Comment by MarshallOfSound** [comment]
Thanks for the run down @jostrander 

From what you've said and my research

Windows = Fine
Linux = Fine
OS X = Impossible (OS X is hardcoded to send bluetooth keys to itunes and quicktime)

For those using OS X you can change this behaviour with third party tools like.

https://github.com/JamesFator/BTHSControl

**Comment by ben-edgar** [comment]
BTHSControl didn't work for me (on OSX 10.11 with Sony MDR100-abn), but https://github.com/jguice/mac-bt-headset-fix did

**Comment by oscarfroberg** [comment]
Cheers ben-edgar! Confirmed working with Sony MDR 1000X as well.

**Comment by vincentkam** [comment]
Another datapoint: I was able to get playback controls working with my Sony 100ABN on Windows only after I enabled the "Windows 10 System Media Service" and restarted the application.
