### ISSUE TITLE
Win7 x64 not opening

### ISSUE THREAD

**Issue by morganlowe** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#63]
The program does not launch on my system. It does on a 32 bit system I have though. There's no logs generated that I can find.

**Comment by MarshallOfSound** [comment]
Please ensure that "Visual Studio C++ Redist x86" from microsoft is installed on your system

**Comment by morganlowe** [comment]
I installed the one for Visual Studio 2015, seems to not have made a difference.  Any particular one I should be using?

**Comment by MarshallOfSound** [comment]
Has to be the 2012 one, sorry, should have clarified that.  Also it has to be the x86 version if you are running the 32bit version of this app.  Or the x64 version if you are running the 64 bit version of the app.  Easiest thing to do is to install both x86 and x64 2012 redists :)

**Comment by morganlowe** [comment]
That got it! Thank you so much!

**Comment by MarshallOfSound** [comment]
No problem.  It really should be caught as an error in the code, but I can't find a way to catch it before it wants it....

**Comment by LabLayers** [comment]
I had the same issue, but installing Visual Studio C++ Redist 2012 fixed it for me. :+1:

This should be included as a prerequisite in the Readme.md file.
