### ISSUE TITLE
The Highlight color isn't applied to the volume slider.

### ISSUE THREAD

**Issue by SolarPolarMan** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#632]
The back part of the slider is colored but the knob is orange. In the online app both are orange.

**Comment by MarshallOfSound** [comment]
App version?
Platform /  OS?
Screenshot?

**Comment by MarshallOfSound** [comment]
:cactus: bump

**Comment by MarshallOfSound** [comment]
Closing as can't replicate and no additional info provided.  Assuming @SolarPolarMan is running an old version of the player
