### ISSUE TITLE
Type to search

### ISSUE THREAD

**Issue by SicariusNoctis** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#639]
Homescreen
   -> Typing searches using search bar
   -> Hitting enter searches using standard Google Play search

My library
   -> Typing fuzzy filter-searches through artists/genre/whatever you're on
   -> This is done in real-time
   -> Hitting enter selects the topmost result

**Comment by MarshallOfSound** [comment]
What is this?   
An issue?  
A feature request?

What you have typed makes no sense?

**Comment by SicariusNoctis** [comment]
Apologies; I couldn't find a way to tag this. This is a feature request. I was thinking of ways to make navigation easier/faster on the PC, and minimizing the need to use the mouse.

Essentially, the search bar could be automatically selected, so that any keystrokes would be redirected to it. Just like [Google Search](https://www.google.com/).

![type to search](https://cloud.githubusercontent.com/assets/721196/13910201/863492f6-eedb-11e5-9114-5984a0dbcb25.png)

When looking at My Library, I would like a way to quickly filter through all the artists. So, typing would run a real-time filter-search through the My Library page.

**Comment by MarshallOfSound** [comment]
Type to search I can do, but the real time search of the "My Library" page is a no go.

**Comment by MarshallOfSound** [comment]
Actually I can't do this because Google has a lot of "hotkey" one letter keyboard shortcuts.  This means that there are like 12 keys that shouldn't auto start searching which leaves a 50% success rate.  This seems like bad UX so I'm closing this as wontfix :+1:

**Comment by SicariusNoctis** [comment]
Is it possible to put the cursor on the search box at startup?

    homepage.onLoad({
        searchBox.select();
    });

Or perhaps bind a keyboard shortcut (Ctrl+F) to the search box?

Thanks
