### ISSUE TITLE
Use correct install path when updating

### ISSUE THREAD

**Issue by Zazama** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#64]
Hey,

I've installed the GPMDP on my D: drive, because my C: is an SSD and it's very small. The thing is, every time I update, I have to manually choose the install path that I've chosen at the first install. It would be really nice to have the used install path automatically loaded into the installer.

**Comment by MarshallOfSound** [comment]
Hey,

This is related to #44 

I have very little control over the installer, it is basically a self extracting zip file.  I am trying to get an Open Source license to use some software called "Advanced Installer" (you can google that to see what it is).  Which will allow me to implement features such as the one you suggest.

Until I get that license though, it's stuck how it is.  As soon as I get that license I'll update you here, but for now I'll close the issue as their really is nothing I can do
