### ISSUE TITLE
FEATURE REQUEST: Proxy Connections

### ISSUE THREAD

**Issue by sybexs** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#648]
Would it be possible to add in proxy/connection settings. Right now it uses the proxy settings from the system and there is no way to bypass it or connect directly to the internet.

The idea setting options would be:
No proxy
Auto detect
Use System Proxy settings
Manual Proxy Config

**Comment by jostrander** [comment]
I know in electron you can pass `--no-proxy-server` and the underlying library will bypass proxies, but as far as making it built in I don't see any API's to change it on the fly.

**Comment by MarshallOfSound** [comment]
From memory Electron has a Session API that handles things like proxy settings, but I don't know if this kind of thing is in scope for this application or should really be in scope for any application.  What are you reasons for wanted a proxy connection different to your system one

**Comment by sybexs** [comment]
The network i am on uses a system proxy that blocks www.play.google.com. To get around this in Firefox and IE i set my browsers to no proxy and it goes around it and connects to google music with no issue. I was hoping there would be a way to do it with the application.

**Comment by MarshallOfSound** [comment]
I think you can start the application with the flag

`-- --no-proxy-server`

and it will start without proxy

**Comment by sybexs** [comment]
That will work in Windows 7?

**Comment by MarshallOfSound** [comment]
Pretty sure (I have no proxy so I can't test)

Just find the `.exe` file and start with the arguments

**Comment by sybexs** [comment]
doesn't seem to work, i tried all of the following
update.exe --processStart Google%20Play%20Music%20Desktop%20Player.exe -- --no-proxy-server
update.exe --processStart Google%20Play%20Music%20Desktop%20Player.exe --no-proxy-server

update.exe --processStart Google%20Play%20Music%20Desktop%20Player.exe --proxy-server="0.0.0.0:80"

**Comment by MarshallOfSound** [comment]
You can try starting this exe directly with the args?

Google%20Play%20Music%20Desktop%20Player.exe

**Comment by sybexs** [comment]
Frigging awesome! that worked!seems like the arguments cant get through the updated.exe

Thank you sooo much!

**Comment by MarshallOfSound** [comment]
Sweet

**Comment by tipar** [comment]
I was going to propose the inbuilt proxy server so I can bypass the country restriction from the app. It is the only thing that is keeping me from using the app.

**Comment by jostrander** [comment]
Probably wouldn't happen. Adds more technical debt that it would be worth unfortunately.
