### ISSUE TITLE
App won't accept Flash as updated and enabled

### ISSUE THREAD

**Issue by DoctorOak** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#65]
Flash is up to date and enabled in my actual version of Chrome (though it was previously disabled after yet another massive security hole a few weeks ago). The app continues to insist that Flash needs updated/installed, though, so it won't do anything. 

It seems that to have this Chromium bundle work at all anyway that Flash would therefore have to be installed and enabled permanently on your main Chrome browser, which just isn't worth the risk, so I'm going to have to uninstall anyway, but I think it's still worth logging this bug as I'm unlikely to be the only one caught out by it still not working despite Flash being available.

**Comment by MarshallOfSound** [comment]
You forgot one small thing regarding this "issue", chrome uses it's own embedded flash player "pepper flash" whereas any other browser (Firefox, IE, and this embedded browser) require NPAPI flash.  If you download and install NPAPI flash from adobes website it will work properly, there is not possible way for CEF (The browser used in this app) to recognise chromes pepper flash and use it.
