### ISSUE TITLE
Move uncaught exception notifier.

### ISSUE THREAD

**Issue by MK3GTX** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#653]
The uncaught exception notifier is extremely invasive. It should be moved past the controls as it covers the song title and information. It should also be dismissable. 

[Screenshot](http://i.imgur.com/8nWrP22.jpg)
[Proposed area](http://i.imgur.com/zyxh2tQ.jpg)

- [Move notification somewhere less invasive] 
- [Allow users to close it]

**Comment by MK3GTX** [comment]
[http://imgur.com/8nWrP22](Screenshot)

**Comment by MarshallOfSound** [comment]
On my computer and many others I have tested on the alert pops up in the area you have marked as "proposed".  Not sure what's going on with your GPM but everyone else's alerts popup in the nice place :+1: 

Closing until it's reproducible
