### ISSUE TITLE
JavaScript error

### ISSUE THREAD

**Issue by ThurnisH41ey** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#658]
```
Uncaught Exception:
TypeError: Cannot read property '0' of null
    at /usr/share/google-play-music-desktop-player/resources/app/build/index.js:97:19
    at Array.forEach (native)
    at EventEmitter.<anonymous> (/usr/share/google-play-music-desktop-player/resources/app/build/index.js:96:39)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
```
Happening on a fresh install of Arch Linux.

**Comment by MarshallOfSound** [comment]
This error has been fixed, are you sure you are pulling latest?

**Comment by ThurnisH41ey** [comment]
I just ran pacaur -S google-play-music-desktop-player-git; it says version 3.0.1.20.g49d108b-1. I installed Arch not 2 hours ago on this machine.

**Comment by MarshallOfSound** [comment]
Hmmm
I have no idea how / what arch pulls, all I know is that the issue is fixed in master and there a no release versions with this bug

**Comment by BrianAllred** [comment]
Use package gpmdp from the AUR, it's the stable version. I'm going to fix the git package tonight.

**Comment by ThurnisH41ey** [comment]
Ahhh. Thank you Brian.
