### ISSUE TITLE
Support for moving window with Windows+arrow keys

### ISSUE THREAD

**Issue by hndmrsh** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#661]
**OS:**
Windows 10

**Issue Descriptions:**
Currently, Win+arrow keys does not move the window around the screen. This is an issue in situations where the program starts with the window offscreen (e.g. in multi-monitor setups) as there is no way of getting the window back.

**Steps to Reproduce:**
1) Hold Windows key and use arrow keys to move the window around
2) Nothing happens.

**Comment by MarshallOfSound** [comment]
This support is already here, I have tested on Windows 7, 8 and 10.  Which OS are you running?

**Comment by hndmrsh** [comment]
Ah yes, you're right, it is working in most cases. However, it's broken in the case where the window is being rendered offscreen due to changing desktop configurations. I've managed to work out how to reproduce the issue:

1) Set up 2 displays, such that display 1 is to the left of display 2. Display 1 is the primary display.
2) Open the application, and move it to display 2.
3) Close the application.
4) Change your display configuration so that display 2 is the primary display (the position of the displays should not change; i.e. display 1 is still to the left of display 2.
5) Open the application. It should appear in the taskbar of display 2 (if you have taskbar buttons set to only appear on the display where the window is open), but the window is rendered offscreen.
6) Windows+arrow keys does not move the display back onscreen.

I assume what's happening is the window geometry is being saved/restored based on its position relative to the primary display. When the primary display changes, this causes the window geometry to be invalid. Is there a way to invalidate the window geometry if the display configuration has changed since the last time the application was opened?

(For what it's worth, now that I realise what's going on, I think this is a very low priority issue).

**Comment by MarshallOfSound** [comment]
Oh, that "positioning off screen" issue has been fixed in master.  So I'm guessing this won't happen in the next release
