### ISSUE TITLE
Font color in queue is too dark in dark theme.

### ISSUE THREAD

**Issue by antoineallard** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#662]
**OS:**
Ubuntu 14.04
**Issue Descriptions:**
The font color of the queue stays the same whether using the dark theme or not. It is therefore too dark to read the name of songs etc. under the dark theme.
**Steps to Reproduce:**
Hmm... 1) Select the dark theme under the Desktop menu. 2) Pick a random station or album. 3) Look at the queue. 4) ? 5) Profit, and eventually solve this minor issue.

Thanks for the great app by the way !

**Comment by MarshallOfSound** [comment]
This is fixed in `3.0.1`, it sounds like you haven't updated (Ubuntu doesn't have an auto update)

**Comment by antoineallard** [comment]
Do I need to reinstall a new version of the application every time I want to update it ?

**Comment by MarshallOfSound** [comment]
Just tried my install on Ubuntu 14.04 and it looks correct. can you provide a screenshot of what you are seeing?

**Comment by antoineallard** [comment]
Sure. The highlighted song (Summertime) is due to mouseover.

![screenshot](https://cloud.githubusercontent.com/assets/7593247/13877062/b282d766-ed08-11e5-8a57-5cfcb853b747.png)

**Comment by antoineallard** [comment]
Sure, the highlighted song (Summertime) is due to mouseover.

![screenshot](https://cloud.githubusercontent.com/assets/7593247/13877143/3f40b93e-ed09-11e5-9ead-1fc22978ce81.png)

**Comment by MarshallOfSound** [comment]
That's like, really strange.  You have the back button from `3.0.1` but the text is still buggered......  Google might be A/B testing again, I guess I'll just have to wait and see.

It might be worth you doing a clean install as well (if you ever had `3.0.0`)

**Comment by antoineallard** [comment]
I just did a clean install with the same results. As you said, maybe we'll have to wait and see. Anyhow, thanks for your help !

**Comment by antoineallard** [comment]
Just a quick followup in case you are interested. I just installed version 3.2.4 and the bug I had is solved.
