### ISSUE TITLE
Hangs on login

### ISSUE THREAD

**Issue by j-arnaiz** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#663]
Hello and thanks for this app.

I Installed the 64 bit version on ubuntu 15.10 but it hangs on login.

Although i test it in other ubuntu with the same config and it worked.

It just hang on login after enter my password.

Two factor auth should be displayed but the app just hangs and can not continue.
Maybe is some kind of login cache or cookie don't know.

Is there any log I could see to check the problem?

**Comment by MarshallOfSound** [comment]
Nope

What you can do though is read the FAQ as the issue template says

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ
