### ISSUE TITLE
Scroll bar does not work properly under Linux

### ISSUE THREAD

**Issue by ZenHarbinger** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#665]
**OS:**
Ubuntu 16.04 64-bit
Node.js 5.9.0

**Issue Descriptions:**
In the main window (right hand panel), I can scroll using the mouse wheel and by clicking above/below the scroll bar position widget.  But I cannot grab the widget to scroll the window up or down.

**Steps to Reproduce:**
Try to scroll on Linux w/o using mouse wheel or screen jumping.

**Other:**
This functionality DOES work on Windows 7 as expected.

**Comment by MarshallOfSound** [comment]
This sounds like a chromium / electron bug.  Not much I can do about it here.  I would suggest raising it on `atom/electron`
