### ISSUE TITLE
Feature Request: Ability for mini player to stay on top

### ISSUE THREAD

**Issue by ceryen** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#67]
I think it would be awesome if the mini player had the option to stay on top of other windows.  There are numerous Windows utilities that can be used to achieve this, but when using these utilities to keep the mini player on top, when switching back to the full player, the full player also stays on top.  I think a native option that is specific to the mini player would be nice

Keep up the good work!

**Comment by MarshallOfSound** [comment]
I was originally planning on doing this but I didn't have a nice way for the user to choose whether they wanted this enabled or disabled.  Now I have implemented the settings menu it shouldn't be too tricky :cactus:
