### ISSUE TITLE
Notification Error Request

### ISSUE THREAD

**Issue by tehloxely** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#670]
Would it be possible to put a 'Close' box for the error notifications? Also, perhaps a different spot for it (upper right)? It covers the music information.

Windows 7 32bit
Google Music Player 3.0.1
![error](https://cloud.githubusercontent.com/assets/1208778/13884758/cc14400a-ed05-11e5-99ed-b5e877d3efb4.png)

**Comment by MarshallOfSound** [comment]
This is a rare case due to the nature of the current errors.  It doesn't appear down there normally and there is a close button now in master
