### ISSUE TITLE
Could not go further installation screen for Adobe flash

### ISSUE THREAD

**Issue by antonydeepak** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#68]
The player requests me to update flash but then it doesn't go anywhere from there. Attaching the screenshot where I am stuck. The prompt for download does not appear in the webview(I guess) you are rendering. All my browsers are up-to date with flash and hence none of them suggests me to upgrade when trying to do it through browser.

![image](https://cloud.githubusercontent.com/assets/1146580/11524247/04da6964-987e-11e5-969e-4338d9454b86.png)

**Comment by MarshallOfSound** [comment]
Duplicates of #65 and #30 

Basically follow the link in the readme (http://get.adobe.com/flashplayer/)
And follow the instructions to download the system wide version of flash player (also known as NPAPI)
