### ISSUE TITLE
Cannot use default hotkeys

### ISSUE THREAD

**Issue by Melloorr** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#680]
**OS:** Windows 10

**Issue Descriptions:** Ever since 3.0.0 my default play/pause and skip track hotkeys on my keyboard no longer work.

**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment]
You can follow the fix instructions in the FAQ or wait for the fix in `3.1.0`
