### ISSUE TITLE
Auto stopping music because you were "away"

### ISSUE THREAD

**Issue by highstrike** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#682]
Hey, so... I like my music on all the time, even when i sleep.... however google music has this stupid "feature" that stops your music and puts a dialog about "music stopped due to inactivity, click here to resume" and it really pisses me off.

The way it works is if the music is started and you leave the computer unattended, after 6 hours you see that annoying pop-up on the web and even on your desktop app (which i know is the web as well)

So what can be done about this?

Well maybe put an option in the settings or wherever and when this option is checked it will simulate a click somewhere inside the app. You can use something like `window.setInterval` and set it to do this every 5 hours. I'm not sure if this will work or not but it's worth a try.

Another thing is to prevent idling to sleep (like in windows advanced power options - multimedia settings). Basically when i watch a move, the computer never goes to sleep. I don't know how this would be implemented but just wake up the computer every 5 hours to prevent google from pausing my music.

Here are my power options for reference to the scenarios below
http://i.imgur.com/PUZRLp8.png

Scenario -----
10 pm -> music starts, computer goes afk
1 am -> i go to bed
4 am -> music stops .... :angry: 
9 am -> I wake up, music no longer playing :sob: 

Desired effect -----
10 pm -> music starts, computer goes afk
1 am -> i go to bed
3 am -> screen comes on because computer is no longer idle
3:05 am -> screen goes dark
4 am -> nothing happens, music keeps playing :innocent: 
8 am -> screen comes on because computer is no longer idle
8:05 am -> screen goes dark
9 am -> I wake up, music still playing :wink: 
....... etc.......

I really don't understand why google is doing this, it's not like they don't have the bandwith for it.... Deezer never stopped my music EVER and they are not a giant like Google.

I would appreciate any help regarding this.
Thanks!

**Comment by MarshallOfSound** [comment]
Hmmm, I think I've come across this once but there is no real way for me to test / implement this.  Each proposed solution will take 6 hours to test :cry: 

I'll give it a go, but no promises

**Comment by highstrike** [comment]
Thanks for looking into this. I know testing this is going to be time consuming but if you want I can help you with it. If you implement something that might get rid of that message you can send me the experimental build and I will tell you if it works or not :+1: 

BTW - this is the actual message :cry: 

![pqknyee](https://cloud.githubusercontent.com/assets/2379538/13904494/37667b4c-eeab-11e5-8049-ce3dfacae12f.png)

**Comment by MarshallOfSound** [comment]
Step one is figuring out how Google determines you are "inactive".  It could be a number of things but my first guess is mouse movement but then that would only detect mouse movement inside the GPM browser window, not the entire system.

I'm probably going to have to go code diving at some point :cry:

**Comment by highstrike** [comment]
Thanks man, I really appreciate all your hard work. Hope you can figure this one out because it's driving me crazy!

**Comment by jostrander** [comment]
@MarshallOfSound maybe have a look at what they implemented here to save some time and effort:

https://github.com/svenackermann/Prime-Player-Google-Play-Music/issues/165

**Comment by highstrike** [comment]
Awesome!

Can't wait to try this out, waiting for the 3.0.2 release :heart:

**Comment by MarshallOfSound** [comment]
You can wait for the `3.0.2` release if you want.  But I'll be tagging the `3.1.0` release :+1: :laughing:

**Comment by highstrike** [comment]
:heart::heart::heart:

**Comment by highstrike** [comment]
I'm sorry to say the proposed solution isn't working :sob:

**Comment by highstrike** [comment]
:cry: :cry: :cry:
