### ISSUE TITLE
Bug: Autohide Controls MiniPlayer

### ISSUE THREAD

**Issue by Devo7v** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#69]
I have the controls set to autohide in the mini player.  The problem is if I open GPMDP, start playing music, and hit the button for the mini player, the controls remain visible.  If I move my mouse cursor over the mini player and then away, the controls autohide as expected.

This bug seems to only occur the first time the mini player is selected.  I can reproduce it every time I hit the miniplayer button.

**Comment by MarshallOfSound** [comment]
I thought I fixed this bug, apparently I did not :cactus:

**Comment by Devo7v** [comment]
This bug exists again with the latest 2.0 release.  I've performed a clean install just to make sure it wasn't a legacy issue.  There's also a new issue that the "Controls Always Visible in Mini Player" setting doesn't function.  The controls always auto-hide no matter what.

**Comment by MarshallOfSound** [comment]
Hmm, this appears to be a bug with the new extracted library https://github.com/MarshallOfSound/gmusic-mini-player.js  I''ll take a look at it later today
