### ISSUE TITLE
Feature request: Mini player

### ISSUE THREAD

**Issue by hndmrsh** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#7]
GPM in Chrome uses a Chrome app as a mini player of sorts; it's not particularly good, but it does the job for people like me who love using mini players! I would love to see this app with an even better mini player implementation than the official Google one.

**Comment by MarshallOfSound** [comment]
What exactly do you want this mini player to do that the Chrome one does not?
Mirroring the functioanlity of the chrome mini player seems a reasonably simple task but I am un sure as to how you want to improve on it?

**Comment by hndmrsh** [comment]
The Chrome mini player is more-or-less functionally complete, but some of the design choices I'm not that fond of personally. I love the iTunes album art mini player (at least, the way it works on Windows 8 - it's buggy on 10), in that it only shows album art and displays the track information and media controls only on mouse over. It would also be nice to be able to see the queued tracks from the mini player. It would also be nice to have the mini player and the full site in the same window (again, similar to the iTunes player); the way the Chrome mini player is implemented, it runs as a separate app, so the web player still has to be open in a Chrome tab.

**Comment by MarshallOfSound** [comment]
Mini player is functional
Bug testing over the next couple of days to make sure there are no side effects :smiley_cat:

**Comment by MarshallOfSound** [comment]
Introduced in version 1.5.0
You should recieve an update notification in your current install :smile:

**Comment by hndmrsh** [comment]
Awesome stuff, I look forward to checking it out! :smile:

**Comment by nintyuk** [comment]
I know this may sound like a dumb question but how do I access this mini player on windows 10?

**Comment by MarshallOfSound** [comment]
@nintyuk There is a button in the bottom right of the player controls

**Comment by nintyuk** [comment]
@MarshallOfSound For some reason It didn't show up on first launch. Probably because I has to log in or something.

**Comment by MarshallOfSound** [comment]
@nintyuk Interesting, sounds like a bug all by itself.  I'll look into it
