### ISSUE TITLE
Flash player disabled

### ISSUE THREAD

**Issue by Isaact94** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#70]
I previously installed this program a few months ago and it worked great, however, after reinstalling windows and thus the program the Flash player is somehow disabled - I can't play music...
As this is part of chrome I am not sure how to re-enable it.

**Comment by MarshallOfSound** [comment]
Duplicate #68 

Follow the instructions there

**Comment by Isaact94** [comment]
Thank you guys.
I have never used GitHub so I am learning how it works, sorry about that
