### ISSUE TITLE
Window doesn't play well with being killed on Linux

### ISSUE THREAD

**Issue by martinantoine** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#704]
**OS:**
Linux

**Issue Descriptions:**
Trying to close the window in i3wm with the kill shortcut doesn't do anything, it just won't close. Only program to do that

**Steps to Reproduce:**
I don't know about other window managers, but in i3, just use the kill shortcut (usually $mod+Shift+q) ; the window doesn't react, it just stays as is (not frozen either, I can still use it)

**Comment by MarshallOfSound** [comment]
This will come down to i3 "closing" the window instead of "quitting" the application and you will have "minimize to tray" turned on in the settings.

Turn that setting off and i3 should handle it correctly.
