### ISSUE TITLE
Feature Request/Issue: Mini Player window position funkiness

### ISSUE THREAD

**Issue by toekneebullard** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#709]
**OS:**
Windows 10

**Issue Descriptions:**

Currently, the Mini Player collapses into, and expands from, the top left corner of the main app window. I generally place the Mini Player in the lower right-hand corner of my screen. So every time I open the app, I activate the Mini Player, and then I have to position it. Then, if I have to do anything like adjust the volume or search for new music, etc, I expand it, and have to move the window AGAIN, reactivate the mini player, and position it again, etc. 

Perfect scenario, the two different windows remember their last used position, so switching back and forth gives the user a consistent, pleasing, and expected action. 

**Steps to Reproduce:**
Use the Mini player.
Move it to the bottom corner of the screen
Click the "enlarge" button
Be annoyed by the position of the enlarged window.

**Comment by Kun2210** [comment]
I think it's already done&merged in #232

**Comment by MarshallOfSound** [comment]
@Kun2210 is correct, this was merged in and will be pushed in the next release `3.1.0`
