### ISSUE TITLE
Feature Request: Chromecast functionality

### ISSUE THREAD

**Issue by taoizt** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#72]
The chromecast functionality of the Chrome tab is not available, is it possible to implement it or is this too hard to implement?

**Comment by MarshallOfSound** [comment]
At the moment, ridiculously difficult as the ChromeCast API is not 100% open, I am always looking into this though as ChromeCast is a nice bit of functionality to have :)

If at some point it becomes easier to implement it will definitely go onto my ToDo pile, but at the moment.  It's definitely only on my wish list :cactus:

**Comment by stgarf** [comment]
https://chromeunboxed.com/chromecast-support-gaining-steam-on-macos-airfoil-adds-google-cast-support/
