### ISSUE TITLE
The NTVDM CPU has encountered an illegal instruction

### ISSUE THREAD

**Issue by ZeroTheSavior** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#721]
**OS:**
Windows 8.1 x86
**Issue Descriptions:**
updater crashes with this message.
**Steps to Reproduce:**
Run installer. It will crash immedately.

I have tried redownloading it and got the same result.

Screenshot: http://i.imgur.com/DwB5IXK.png

**Comment by MarshallOfSound** [comment]
Can you please raise this as an issue on https://github.com/atom/grunt-electron-installer

**Comment by MarshallOfSound** [comment]
(Only closing because it is not an issue with this player, rather an issue with the installer user)
