### ISSUE TITLE
Mini player controls offset if hamburger menu left open

### ISSUE THREAD

**Issue by charles-ritchie** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#728]
**OS:** Ubuntu 15.10

**Issue Descriptions:** Open sidebar offsets controls when going to mini player mode.

**Steps to Reproduce:** 
1. Play a song
2. Open sidebar using hamburger menu
3. With menu still open go to mini player mode
4. The controls will be offset by the width of the sidebar

**Comment by MarshallOfSound** [comment]
Duplicate of #492
