### ISSUE TITLE
Feature Request: Auto Updater

### ISSUE THREAD

**Issue by xaviergonz** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#73]
Support auto-updates (or at least checking if a new release is available and letting you go to the download page)

Also a way to see the currently installed version (probably inside desktop settings?) would be nice.

**Comment by MarshallOfSound** [comment]
Already exists and in here, check out https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/Google%20Play%20Music/CoreMusicApp.UpdateChecker.cs
