### ISSUE TITLE
Feature Request: Bring back dragging of mini player by holding album art.

### ISSUE THREAD

**Issue by nermolov** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#731]
**OS:** Arch Linux

**Issue Descriptions:** In older versions you could drag around the mini player by holding down the album art, this has now been removed

**Steps to Reproduce:** Turn on mini player, try moving window by holding the album art and dragging.

I am using the i3 window manager and have turned off title bars on windows, but in the newest update of the player I can no longer drag around the mini player without the bars turned on (I turned them back on just to move around the mini player).
![Here is what I am referencing, the bar on top used to not be present.](https://cloud.githubusercontent.com/assets/6175137/13970590/c1b79b34-f057-11e5-94f4-3784328eebe2.png) 
(Here is what I am referencing, the bar on top used to not be present.)

Is it possible to bring back the old dragging interface?

**Comment by MarshallOfSound** [comment]
You can bring back the old dragging interface by disabling the "native window frame" option in the app settings.

**Comment by nermolov** [comment]
Thanks
