### ISSUE TITLE
Desktop Settings showing empty

### ISSUE THREAD

**Issue by xaviergonz** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#74]
v1.9.1, Windows 10 x64, en-us, the desktop settings button, while it shows, it shows only the icon (gear) and centered.

![screenshot 2015-12-03 16 06 57](https://cloud.githubusercontent.com/assets/6306796/11564181/2f667974-99d8-11e5-9dff-e9926b26ed83.png)

**Comment by MarshallOfSound** [comment]
Theres a fix in master for problems related to the desktop settings button.  I believe that it would fix this issue
