### ISSUE TITLE
Uncaught Exception: Attempting to call a function in a renderer window that has been closed or released.

### ISSUE THREAD

**Issue by butteredtoast** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#743]
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.1
**Time:** Wed Mar 23 2016 19:36:51 GMT 0300 (E. Africa Standard Time)

#### Error:
*Attempting to call a function in a renderer window that has been closed or released. Function provid*
```js
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: Object.<anonymous> (C:\Users\<user>\AppData\Local\GPMDP_3\app-3.0.1\resources\app\build\inject\GPMInject\interface\mouseButtonNavigation.js:8:8.
    at BrowserWindow.callIntoRenderer (C:\Users\<user>\AppData\Local\GPMDP_3\app-3.0.1\resources\atom.asar\browser\lib\rpc-server.js:201:19)
    at emitTwo (events.js:92:20)
    at BrowserWindow.emit (events.js:172:7)
```
This issue was created automatically inside the `uncaughtException` handler

See attached:

![error](https://cloud.githubusercontent.com/assets/3799898/13992911/0084b78e-f12f-11e5-81d7-d1ff1d741020.png)

**Comment by MarshallOfSound** [comment]
Duplicate.  Fixed in master
