### ISSUE TITLE
Feature Request: Make error reporting popup dismissable

### ISSUE THREAD

**Issue by bjohnso5** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#748]
When GPMDP catches an error, the popup that is used to file an issue automatically cannot be dismissed without clicking the link to create the issue. Since I filed an issue that was already closed as a duplicate, I don't want to have to keep clicking the link and then cancelling the report just to dismiss the error popup in the UI.

**Comment by MarshallOfSound** [comment]
Will do :+1:

**Comment by exhuma** [comment]
Additionally, this pop-up covers the song menu and thumbs up/down buttons. So you actually have to dismiss it somehow to access all functionality.

I don't want to spam the issues with the auto-generated tickets, so currently I get around this by switching to the mini-player to vote on a song and then switch back.

**Comment by MarshallOfSound** [comment]
Fixed in #772
