### ISSUE TITLE
Drag Count Indicator & Upgrade Button Should be Recolored in Dark Mode

### ISSUE THREAD

**Issue by LabLayers** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#750]
Title says it all. Let me know what you think.

![image](https://cloud.githubusercontent.com/assets/607807/14000414/8c722f14-f117-11e5-98d6-62190ed8b3e6.png)

**Comment by MarshallOfSound** [comment]
Solid catches.  Can you please raise this issue on the theming repository.  `gmusic-utils/gmusic-theme `
