### ISSUE TITLE
CPU pegged at 100%

### ISSUE THREAD

**Issue by amancevice** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#751]
**OS:** OS X

**Issue Descriptions:** App consuming CPU

**Steps to Reproduce:** Play for ~45min

Not a great "Steps to Reproduce" description, but I'm finding after using the app for extended periods of time my fan kicks on and the app appears to be consuming 100%+ of the CPU.

**Comment by MarshallOfSound** [comment]
I use the app 24/7 pretty much and it never goes really above 2%

Can you try track down either an exact time or an exact action that causes this spike

**Comment by amancevice** [comment]
Sure, if I can't pin something down in a few days I will close the issue.

**Comment by cheald** [comment]
It's not pegging for me, but just idling, it routinely consumes 3-8% CPU. A Google Music tab open in Chrome doesn't have the same issue, so it's probably something in the app chrome itself.

![CPU usage when idle](https://i.imgur.com/0ex67RR.png)

**Comment by MarshallOfSound** [comment]
Might be something chromium specific in that release, I can't replicate higher CPU on any of the devices I have availible.  The best I can say is wait for the next release and see if it gets better, normally this kind of thing can be fixed by an Electron version bump

**Comment by amancevice** [comment]
Here's a screenshot of the issue happening. Not sure what I did. I have been listening all morning with occasional pausing and headphone insertion/extraction (ie, picking my laptop up and walking around the office)
<img width="726" alt="screen shot 2016-03-29 at 11 34 29 am" src="https://cloud.githubusercontent.com/assets/157711/14113806/7a485efa-f5a2-11e5-8226-0f2c2af250be.png">
