### ISSUE TITLE
Uncaught Exception: Attempting to call a function in a renderer window that has been closed or released. Function provided

### ISSUE THREAD

**Issue by mz2212** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#758]
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.1
**Time:** Wed Mar 23 2016 23:13:27 GMT-0600 (Mountain Daylight Time)

#### Error:
*Attempting to call a function in a renderer window that has been closed or released. Function provid*
```js
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: Object.<anonymous> (C:\Users\{User}\AppData\Local\GPMDP_3\app-3.0.1\resources\app\build\inject\GPMInject\interface\mouseButtonNavigation.js:8:8.
    at BrowserWindow.callIntoRenderer (C:\Users\{User}\AppData\Local\GPMDP_3\app-3.0.1\resources\atom.asar\browser\lib\rpc-server.js:201:19)
    at emitTwo (events.js:92:20)
    at BrowserWindow.emit (events.js:172:7)
```
This issue was created automatically inside the `uncaughtException` handler

This popped up a couple of times, once when I was maximizing the window, and a second time when I was fiddling with the volume buttons on my keyboard. If it helps at all, I was watching the particles visualizer the second time it happened.

After some testing, it happens every time the little volume box pops up, though not when GPMDP isn't selected.

Running Windows 10 Pro x64.

Edit: Grammar

**Comment by MarshallOfSound** [comment]
Duplicate, not sure why the unicorn didn't auto close this

BAD UNICORN :laughing:
