### ISSUE TITLE
OS X: Radio won't play

### ISSUE THREAD

**Issue by kselby** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#764]
**OS:**
OS X El Capitan V. 10.11.3
**Issue Descriptions:**
I am having trouble starting radio stations. I click the play button that appears on top of the radio artwork and it loads for a second and then nothing plays. Same thing happens when I go into the radio station page and click the play button there. 
**Steps to Reproduce:**
Open GPMDP
Locate a radio station
Click play

**Comment by MarshallOfSound** [comment]
Try going into settings and enabled HTML5 Audio.  You might need to enable it manually

**Comment by kselby** [comment]
I went into settings and under labs I see the choice to switch to HTML5 Audio but it is grayed out for some reason and won't let me select it. 
![screen shot 2016-03-24 at 5 37 11 pm](https://cloud.githubusercontent.com/assets/18060040/14035100/82c94fa8-f1e7-11e5-8b98-47123ec04f0c.png)

**Comment by MarshallOfSound** [comment]
OK, then that shouldn't be a problem.  Can you play any music at all or is it jsut radio that doesn't work?

**Comment by kselby** [comment]
Music plays fine, just the radio part that doesn't work. The weird thing is that it works if I go back to the song and press the three dots option button on the song and say start radio from there. If I try to play the actual radio on its own after that it doesn't work.

**Comment by MarshallOfSound** [comment]
This sounds like a Google Play Music bug rather than a bug caused by the player.  Hopefully it's something Google are aware of and they will fix it :+1:
