### ISSUE TITLE
Uncaught Exception: The request timed out.: (null)

### ISSUE THREAD

**Issue by eboye** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#770]
An uncaught exception was reported.  
#### Info:
**OS:** darwin
**Arch:** x64
**GPMDP Version:** 3.0.0
**Time:** Fri Mar 25 2016 17:00:29 GMT 0100 (CET)

#### Error:
*The request timed out.: (null)*
```js
Error: The request timed out.: (null)
    at Error (native)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by GPMDP-Magical-Unicorn** [comment]
Closing this automatically reported issue as a duplicate of #235
