### ISSUE TITLE
About window

### ISSUE THREAD

**Issue by SicariusNoctis** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#777]
Perhaps an About tab to the settings to allow for checking the version number, a "check for updates" button, and to give yourself some credit? ;)

**Comment by jostrander** [comment]
There is an about window in the menu with the version number. Could probably be improved with some more information though.

**Comment by MarshallOfSound** [comment]
On Mac OS X there is the default about menu, and in the next version a PR has already been merged that adds an "About" page to the tray menu
