### ISSUE TITLE
Feature request: enable Bluetooth avrcp support

### ISSUE THREAD

**Issue by mase1981** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#78]
Is it please possible to consider support for Bluetooth a2dp avrcp protocol. So we can play pause and seek tracks using bt headsets.... 
Thank you

**Comment by MarshallOfSound** [comment]
Urgh, I looked into this a while back and it is the worst documented functionality ever....  The extend of the MSDN documentation on this is here https://msdn.microsoft.com/en-us/library/aa916569.aspx

I'll leave this open, but bearing in mind I don't have a bluetooth headset to test with there is no real way to test anything I implement.

I'll tag this as help wanted and hopefully someone will look into it

**Comment by mase1981** [comment]
Appreciate you looking into this man....  Hopefully one day :) great app!

**Comment by MarshallOfSound** [comment]
For now it might be worth you looking into seeing if something like AutoHotkey has this already implemented so you can map your bluetooth buttons to the equivalent keyboard buttons.  Hacky work around I know but at least it would work :)

**Comment by mase1981** [comment]
That's actually a good idea! I've been searching like crazy inside Microsoft documentation and api's.... as u mentioned earlier, it's a mess lol....  I'll look into autohotkey

**Comment by mase1981** [comment]
Hi, just wanted to give an update....
Done some investigation last night.... 
here is what i found
if you are using windows 10 and your BT headphones are version 4.1 (doesn't matter LE or not) with AVRCP 1.3 minimum AVRCP will work on this app flawlessly. 
Tested in windows 10 and i am able to successfully control the music (play/pause/back/fw). 
Tested with JBL everest elite 700
 :) 

You can mark this as resolved with minimum requirements as:
Windows 10
BT Headphones with BT 4.0 Minimum & AVRCP 1.3

**Comment by MarshallOfSound** [comment]
That's good news, Microsoft finally implemented something correctly :)

**Comment by st33ly** [comment]
@mase1981 @MarshallOfSound

Hi Guys, I have a similar issue with my bluetooth headset and hoping you can help? I have a set of Plantronics Backbeat Pros which dont seem to play well with play/pause. I'm unclear on whether they meets your minimum requirements? Specs on the site: 
"Bluetooth v4.0 + EDR - A2DP for audio streaming, AVRCP for music controls, Hands-free v1.6 for wideband, and Headset v1.2"

I guess I could give the autohotkey workaround a try so if you have any pointers I'd appreciate it!

**Comment by jostrander** [comment]
The conversation here is discussing the viability of Bluetooth headsets with the old version of the app (pre-3.0). There have been varying reports of Bluetooth headsets working on 3.0+, but only due to the headsets successfully (or unsuccessfully) sending media key keyboard commands.
