### ISSUE TITLE
google profile picture cut off in some window sizes

### ISSUE THREAD

**Issue by cboseak** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#79]
not sure if this was is a bug or if it is intentional because of limited window real estate but in some situations where the window is resized below a certain size
![capture](https://cloud.githubusercontent.com/assets/9941734/11606376/c14aafba-9ae4-11e5-9c20-896871d71ed7.PNG)

**Comment by MarshallOfSound** [comment]
That's actually Google CSS forcing a min width on the body of the page.  I could override it but they put it there for a reason :D

#googlesproblem #wontfix
