### ISSUE TITLE
Share option to Facebook and Twitter to do function

### ISSUE THREAD

**Issue by lbtaylor1984** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#796]
Windows 10 Pro
**OS:**

**Issue Descriptions:**
As per title
**Steps to Reproduce:**
Click share option then FB or Twit, nothing happens Google+ is working

**Comment by MarshallOfSound** [comment]
This issue is fixed in master due to my polyfilling of `window.open`

Fill be fixed in `3.1.0`
