### ISSUE TITLE
[Enhancement] Mini Player - Thumbs Up/Down

### ISSUE THREAD

**Issue by mlattanzi** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#816]
**OS:** OS X 10.11.2

**Issue Descriptions:** Requesting the addition of thumbs up/down buttons on the mini player. Currently they exist in the full screen as well as drop down options task tray, but it would be convenient to be able to use them directly from the mini interface as well.

**Comment by MarshallOfSound** [comment]
Thumbs up and down are present when you are listening to a "radio".  They are replaced with shuffle and repeat buttons when listening to  a set playlist / album / queue
