### ISSUE TITLE
Request: Could we cache Albums/Playlists on demand (like on the Android app)?

### ISSUE THREAD

**Issue by sorif** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#82]
Look, I realize 100% that a feature like this is a huge addition to the existing, simpler, client you've created. But I have been dealing with a clunky web connection at home this past week, it would be interesting to add something like that. I suppose most people wouldn't be interested in it, and with good reason. Also, to my knowledge it should be really hard to implement.

But I don't know everything, and the internet is full of wonderful people.

So, I'm just putting it out there. And if I'm right and it can't be done, I'd like to read why as well.

**Comment by MarshallOfSound** [comment]
It already has more aggressive caching than the web version (in regards to static resources) but the music is stored in a flash container and j can't touch it / save it / cache it.

Refer to #80
