### ISSUE TITLE
Not getting desktop notifications

### ISSUE THREAD

**Issue by shalomh** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#822]
**OS:** Windows 7

**Issue Descriptions:** Just installed and love it, especially the dark theme. Is it my imagination or is the audio quality better than on chrome? Only problem is I'm not getting notification pop-ups when a song starts. I don't see anything in settings about notifications.  Am I missing something? Thanks. 
 
**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment]
It's in the normal google play music settings.  All I have done is polyfill the default desktop notifications.

**Comment by shalomh** [comment]
Hi Samuel,, thanks for the response. Yes notifications are on in the google
play music settings. They work fine when I'm using it on chrome.  But it
doesn't work when using the desktop.

Any ideas?


--

Shalom Helman
M:+972 52 477-6275
E: shalom.helman@gmail.com
