### ISSUE TITLE
Media keys not working in Google Play Music Desktop Player

### ISSUE THREAD

**Issue by DerProfessor** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#826]
I have an error occurring everytime I try to use any media key on my keyboard like skipping to the next titel in a list. A dialog pops up saying an uncaught error has occurred inside GPMDP. The same error occurs also using chrome instead of the Desktop Player. Media act normal when using them in Windows Media Player, VLC, etc.
When I uninstall the keyboard driver and use the standard windows driver instead, media keys work normal in chrome, but not in Google Player Desktop Player, Windows Media Player or VLC.

Keyboard: Microsoft Sidewinder X4 (Driver 9.7.132.0)
OS: Windows 10 Pro (Build 10586.164)

#### Generated Bug Report

An uncaught exception was reported.  

#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.1
**Time:** Tue Mar 29 2016 14:58:03 GMT 0200 (Mitteleuropäische Sommerzeit)

#### Error:
*Attempting to call a function in a renderer window that has been closed or released. Function provid*
```js
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: Object.<anonymous> (C:\Users\danie\AppData\Local\GPMDP_3\app-3.0.1\resources\app\build\inject\GPMInject\interface\mouseButtonNavigation.js:8:8.
    at BrowserWindow.callIntoRenderer (C:\Users\danie\AppData\Local\GPMDP_3\app-3.0.1\resources\atom.asar\browser\lib\rpc-server.js:201:19)
    at emitTwo (events.js:92:20)
    at BrowserWindow.emit (events.js:172:7)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
Duplicate

All windows related media key issues will be fixed in the next release.  For now the temporary fix is to remove the Google Play Music chrome extension
