### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by azureharri** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#83]
When prompted to enter my e-mail at login, i cannot type in the text field. I couldn't copy/paste into the text field either. If it helps, I'm using an Asus Transformer Book T100TA with a 32-bit copy of Windows 10.
Really looking forward to using this app!
It's a really good idea, and the pictures look amazing.

azureharri

**Comment by MarshallOfSound** [comment]
I can not replicate this issue (I actually have a mate with a Transformer Book), can you try closing everything, rebooting, reinstalling and trying again.  Maybe even plug in a external keyboard or something?

**Comment by azureharri** [comment]
Yeah reinstalling worked. Don't know why I didn't try that in the first
place.
Thanks
