### ISSUE TITLE
Installed on date (Windows)

### ISSUE THREAD

**Issue by mikeytusa** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#833]
**OS:**
Windows 10

**Issue Descriptions:**
In the Control Panel, this application is listed as being installed in September of 2016.

**Steps to Reproduce:**
View the program in Uninstall or change a program section of the Control Panel on Windows.

![explorer_2016-03-29_12-42-57](https://cloud.githubusercontent.com/assets/1264829/14119541/daf57d60-f5ab-11e5-9cba-14a5eb463959.png)

**Comment by MarshallOfSound** [comment]
OK, I have no idea how this app could cause this and it appears under the correct date on my machines.  I would suggest this is a bug in windows or possibly your computers date/time glitched out :+1: 

This date is handled by core windows installer API's and not set by me :smile:

**Comment by mikeytusa** [comment]
Very strange.  Definitely not my system and its the only app on my PC reflecting the wrong date.

**Comment by MarshallOfSound** [comment]
@mikeytusa You can peruse through the code if you want, I don't think I even reference a date object once :laughing: 

It's probably just a symptom of 1 of thousands of windows bugs :cactus:

**Comment by mikeytusa** [comment]
No worries.  I'm not throwing blame.  Just hopefully helping to squash bugs.  Loving the project, great job! :)
