### ISSUE TITLE
Uncaught error on any keyboard media key press

### ISSUE THREAD

**Issue by nicusorbinovate** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#837]
**OS:** Windows 10

**Issue Descriptions:** Unable to use media keys with the player

**Steps to Reproduce:**
Start playing any song using the player >> press play/pause or previous or next media key >> uncaught error occurs:
Also the submit error doesn't work redirects to the unicorn page saying the page takes too long to load here is the url of the uncaught error:
`https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/new?title=Uncaught%20Exception:%20Attempting%20to%20call%20a%20function%20in%20a%20renderer%20window%20that%20has%20been%20closed%20or%20released.%20Function%20provid&body=An%20uncaught%20exception%20was%20reported.%20%20%0A%23%23%23%23%20Info:%0A**OS:**%20win32%0A**Arch:**%20ia32%0A**GPMDP%20Version:**%203.0.1%0A**Time:**%20Wed%20Mar%2030%202016%2000:19:25%20GMT+0300%20(GTB%20Daylight%20Time)%0A%0A%23%23%23%23%20Error:%0A*Attempting%20to%20call%20a%20function%20in%20a%20renderer%20window%20that%20has%20been%20closed%20or%20released.%20Function%20provid*%0A```js%0AError:%20Attempting%20to%20call%20a%20function%20in%20a%20renderer%20window%20that%20has%20been%20closed%20or%20released.%20Function%20provided%20here:%20Object.%3Canonymous%3E%20(C:\Users\XXXXXX\AppData\Local\GPMDP_3\app-3.0.1\resources\app\build\inject\GPMInject\interface\mouseButtonNavigation.js:8:8.%0A%20%20%20%20at%20BrowserWindow.callIntoRenderer%20(C:\Users\XXXXXX\AppData\Local\GPMDP_3\app-3.0.1\resources\atom.asar\browser\lib\rpc-server.js:201:19)%0A%20%20%20%20at%20emitTwo%20(events.js:92:20)%0A%20%20%20%20at%20BrowserWindow.emit%20(events.js:172:7)%0A```%0AThis%20issue%20was%20created%20automatically%20inside%20the%20`uncaughtException`%20handler`

**Comment by MarshallOfSound** [comment]
This has been fixed in master, the unicorn appears to be due to a certain browser opening the link and is in fact a github issue not me :+1:  (it works fine in chrome)
