### ISSUE TITLE
Small tray icon in HiDPI Gnome environment

### ISSUE THREAD

**Issue by BrianAllred** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#844]
**OS:** Arch Linux 64-bit on MBP 13" Retina

**Issue Description:** Tray icon is not scaled properly for HiDPI displays. In attached screenshot, compare against Steam, Redshift, and QSyncThing tray icons that are scaled properly (though Redshift's is super ugly) versus Chome, Hangouts, and Dropbox icons that are not.

**Steps to Reproduce:** Run app, check tray icon.

![icon](https://cloud.githubusercontent.com/assets/5847511/14132569/e1999fa0-f60c-11e5-86ad-b4f2e0949cbf.jpg)

**Comment by BrianAllred** [comment]
I'm willing to try debug builds or build from source myself to help fix the issue. I'm also willing to attempt code debugging. I'm a professional software engineer, though with very little Javascript experience. Still, if I can help, let me know!

**Comment by MarshallOfSound** [comment]
If you can build from source, can you try building from source with this line

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/main/features/core/tray.js#L19

changed from `main_tray.png` to just `main.png` and see how it looks?

**Comment by BrianAllred** [comment]
Worked great!

![screenshot from 2016-03-30 01-58-27](https://cloud.githubusercontent.com/assets/5847511/14134209/f83d05ae-f61a-11e5-897a-61e24cf832b9.png)

**Comment by MarshallOfSound** [comment]
Lol, solid guess :+1: 

Only problem is that having an icon that is that size breaks it on other platforms.  I'll look into smart ways to detect which icon to use

**Comment by zabri** [comment]
Slightly off-topic (no Linux here), but since you wrote about icons braking on other platforms anyway, I don't want to start a new topic.

Both taskbar and tray icons are also having issues on Windows 10 Pro x64. They're not small, just ugly. :) They look like they're being upscaled from a lower resolution. See the attached images.

![taskbar](https://cloud.githubusercontent.com/assets/18167148/14143342/10235428-f68b-11e5-9c91-3d3525a4bc98.png)
![tray](https://cloud.githubusercontent.com/assets/18167148/14143343/1024789e-f68b-11e5-99ee-c40045cca0c1.png)

**Comment by jostrander** [comment]
Can we use `scaleFactor` from the screen API to figure out which icon to use? The only issue I can think of is someone having a secondary screen that doesn't match DPI.

**Comment by MarshallOfSound** [comment]
@zabri The tray icon on windows issue is electron based and you can track that here

https://github.com/electron/electron/issues/5062#issuecomment-207153874

**Comment by MarshallOfSound** [comment]
@jostrander Not necessarily, for instance on OS X if you give it an incorrectly sized image it doesn't auto scale it to fit it just crops it.  I am not sure if some linux OS's do this as well (Windows doesn't).

I'm wondering if electron will respect the @2x and @5x images for HiDPI linux environments.

**Comment by jostrander** [comment]
I highly doubt it, as an alternative can we use a linux only conditional as well as scaleFactor in order to provide a high DPI tray icon?

**Comment by MarshallOfSound** [comment]
After quite a lot of testing, I realized the only platform that needs small icon files is OS X.  And OS X uses template images so other platforms can just use the HD icons :+1: 

Fixed in master
