### ISSUE TITLE
GPMDP entry in windows 10 volume mixer is misformatted

### ISSUE THREAD

**Issue by amgrider** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#848]
Windows 10

Unable to adjust the applications volume in the windows sound mixer panel. Display of the item is cut off and does not display the volume bar. Random clicking in the empty space will eventually let you adjust the invisible slider. 

Right click system volume icon, open volume mixer. Find the entry listed as:
   Go
Musi

It will have no volume slider. Pic attached.
![2016-03-30 2](https://cloud.githubusercontent.com/assets/18173281/14151373/68266e4a-f662-11e5-8974-c01b175b7772.png)

**Comment by gganno** [comment]
I can confirm this issue is present for me, On older versions and the newest version.

**Comment by amgrider** [comment]
Did some playing around and was able to get the gpmdp entry to not be the last entry and the display is still incorrect.

**Comment by MarshallOfSound** [comment]
This is actually a bug in electron / windows that we are experiencing.  I raised this with electron here https://github.com/atom/electron/issues/4838  and they put the blame firmly on a buggy win32 API.

Not much I can do here but wait for Microsoft or Electron to fix.  Sorry guys.
