### ISSUE TITLE
Player consistently freezes OS while changing songs

### ISSUE THREAD

**Issue by stevenolsen** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#85]
When playing songs from a playlist or radio station, the player freezes the entire OS. Mouse movement ceases. Not difficult to reproduce as it tends to happen ~80% of the time. Happens with the December 8 commit and at least one prior to this. The freezing lasts for ~3 seconds, the next song does start playing, but the rest of the system appears unresponsive. Intel i7 4770k (not overclocked), 8 GB RAM. Windows 10.0.10586, x64.

**Comment by MarshallOfSound** [comment]
I'm not sure what to tag this with :confused: 

I'm tempted to tag invalid and call it a system specific bug (possibly an OpenGL rendering bug or a Flash Player bug.  Can you try monitoring CPU usage around the freeze point (changing songs) and see if it spikes in a particular application.  Focus on `flashplayer`, `CefBrowser.SubProcess` and `Google Play Music Desktop Player`.  One of them will be causing it but I don't think it would be mine. :cactus: 

Could you also go back to version 1.6.0 and work your way up till it starts happening (1.6.0 was an older version of Cef from memory)

**Comment by stevenolsen** [comment]
I haven't been able to catch the culprit in action with the task manager open, however I've noticed the halt happens exactly between the event of a new song starting and the desktop notification appearing. Oddly enough, if I try to disable desktop notifications, they still appear even after restarting the app.

**Comment by MarshallOfSound** [comment]
Is this on the latest release 1.9.2?? (a few hours ago)

**Comment by stevenolsen** [comment]
Not sure where to check the version if I'm not compiling it. Properties on the executable hasn't been set and the version is not printed in the settings. It did ask me to update a few hours ago so maybe? I also restarted the app and it did not ask to update. I disabled desktop notifications in settings, not desktop settings. Once I did that I haven't had it freeze on me when changing songs but my time to test was quite small.

**Comment by MarshallOfSound** [comment]
Do you have last.fm turned on?

**Comment by stevenolsen** [comment]
I do not. I've never used that service.

**Comment by MarshallOfSound** [comment]
Do you have a GPU?  Maybe the fading is too intensive for your CPU?

**Comment by stevenolsen** [comment]
I do not at the moment, it is out for repair/replacement. Intel video is quite good though. If it can't handle fading that's likely a driver issue, not hardware. It's an Intel i4770k that isn't overclocked. Don't the notifications just use Windows 10 notification system? No other notifications cause my mouse to hang.

**Comment by Stevoni** [comment]
I just experienced my mouse stuttering when the notification form was opening. I unfortunately cannot recreate it but I do have last.fm turned on. 

Specs: 
- Intel i7 4770k overclocked (4.2-4.4?)
- 32 GB RAM
- GTX 980
- Win 10.

My notification is appearing on a video card monitor not the processor monitor.

**Comment by MarshallOfSound** [comment]
I believe this should be fixed in master, you can check it out in the next release
