### ISSUE TITLE
Uncaught Exception: Cannot read property 'close' of null

### ISSUE THREAD

**Issue by FreshieGeek** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#850]
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.1.0
**Time:** Wed Mar 30 2016 15:47:52 GMT-0400 (Eastern Daylight Time)

#### Error:
*Cannot read property 'close' of null*
```js
TypeError: Cannot read property 'close' of null
    at EventEmitter.<anonymous> (C:\Users\fresh\AppData\Local\GPMDP_3\app-3.1.0\resources\app\build\main\features\core\controlBar.js:17:42)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.<anonymous> (C:\Users\fresh\AppData\Local\GPMDP_3\app-3.1.0\resources\atom.asar\browser\api\web-contents.js:134:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
@FreshieGeek This is an interesting one, do you remember how you made this one appear or which window you were trying to close at the time?

**Comment by FreshieGeek** [comment]
I had changed to the light theme and selected a custom colour highlight.
I didn't like coloured border of the miniplayer so I chose #1e1e25. It threw the error when I closed the window. NOT the colour picker window... the Desktop Settings afterwards.

**Comment by MarshallOfSound** [comment]
Did the desktop settings window actually close?

**Comment by FreshieGeek** [comment]
It doubled the titlebar, and the lower of the two worked to close the window.
The top bar showed the cursor as waiting.
I didn't need to close the program though. It's still running now after that incident. I haven't restarted it although I've changed a few stations.

**Comment by FreshieGeek** [comment]
It just happened again. As I closed the colour picker circle window the settings window border doubled, and threw the error.
![capture](https://cloud.githubusercontent.com/assets/18175874/14192949/e8cf0f68-f76e-11e5-9be8-e39b3d575951.PNG)

**Comment by MarshallOfSound** [comment]
I don't see how that double border is possible... :cactus: 

I think you somehow broke electron.....  I'll leave this open and see if anyone else hits this issue

**Comment by christopherrobin** [comment]
I attempted to reproduce on OSX without luck, if anyone finds a reliable way to throw this error let me know please, thanks
