### ISSUE TITLE
Play/Pause Hotkey Rapidly Cycles

### ISSUE THREAD

**Issue by eygraber** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#851]
**OS:** Windows 10

**Issue Descriptions:**
 After updating to 3.1.0, my play/pause hotkey rapidly cycles when I press it, but only sometimes. For example, I have music playing, and I press the hotkey. The music pauses, but immediately starts playing again. If I do that a few times, it eventually pauses, and stays paused.

 Additionally, and I'm not sure if this is related, but my music has been randomly started or stopped when not pressing hotkeys. For example, last night I updated to 3.1.0, and experienced the issue I described above. I eventually paused the music, and went to sleep. A few hours later the music started playing by itself (scaring the hell out of me in the process). After having the issue above again today, my music randomly started pausing while it was playing.

**Comment by MarshallOfSound** [comment]
Sounds like your keyboard has a dodgy key and is firing multiple keypresses and "phantom" keypresses.  Can you somehow verify this isn't a hardware problem (Maybe try a different keyboard for a while)

**Comment by eygraber** [comment]
I've tried two keyboards so far, and have had the issue with both.

**Comment by MarshallOfSound** [comment]
@eygraber Possibly your keyboard drivers or a rogue program simulating key events globally?  I'm jus trying to come up with an idea that fits your description and the fact that others (me included) don't have this phantom keypress issue.

**Comment by eygraber** [comment]
I will try running it in safe mode when I get a chance, and report back.

**Comment by JohnBorgen** [comment]
I've had the problem before. It occurred when I had more than one extension installed and active that handled Google Music media keys. I would suggest you look for a similar condition and disable the other extension (should you find one installed).

**Comment by jostrander** [comment]
If you have keyboard software that also sends media key output to windows that might be causing the issue, do you have Logitech setpoint or anything installed?

**Comment by eygraber** [comment]
I uninstalled the Google Play Music extension, and I don't have setpoint installed, but I do have Intellitype. I mapped my media key to Ctl+Shft+Alt+P and that's what I set the play/pause hotkey in Google Play Music Desktop.

**Comment by jostrander** [comment]
Intelliatype is known for hijacking media keys. Can you disable it and see if it fixes the issue?

**Comment by eygraber** [comment]
That looks like it might have done the trick. I'll update if it starts happening again.
