### ISSUE TITLE
Creative Studio Pro - Toggling output halts playback

### ISSUE THREAD

**Issue by kfrankic** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#852]
**OS:** 
Windows

**Issue Descriptions:** 
Creative Soundblaster software allows for easy toggling of sound output from speakers to headphones and vice versa.  When toggling from one to the other (doesn't matter which is first) the player immediately quits playing music.  Songs or albums can be changed, however no music will ever be played again until the app is reopened.  This is the exact issue I experience with [this chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=169846).

My work-around (because it's not really a solution) when using Chrome was to open it's Task manager, end the process "Background Page: Google Play Music", and finally reload the page.  I say this, because adding a refresh button my be the easiest route to a temporary fix

**Steps to Reproduce:**
Open GPMDP.  Play any music.  Using Creative's Pro Studio software, toggle the sound output.

**Comment by MarshallOfSound** [comment]
Have you tried using the tray icon of the player to switch audio output device.  Right click on the tray, hover over audio output, and choose the device you want.

You can avoid the creative software glitch entirely

**Comment by kfrankic** [comment]
The tray icon always gives me access to the following options:
System Default
System Default Communications
SPDIF-Out
Speakers

Unfortunately, swapping between these doesn't activate headphones at anytime.

**Comment by MarshallOfSound** [comment]
Oh, you have 2 3.5mm ports and the creative software switches which port it uses....

As much as I hate to say it this has to be an issue with there output switching program.  Possibly to do with DRM audio streams
