### ISSUE TITLE
Linux build uses wrong category in the .desktop file

### ISSUE THREAD

**Issue by aouelete** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#853]
This is just a proposal to change the application category from Utilities to Multimedia (which I think makes more sense) in the .desktop file for the Linux build.

**Comment by jostrander** [comment]
:+1: I noticed this but couldn't find anywhere in the current build tooling
to specify it, but I didn't look too hard.

**Comment by jostrander** [comment]
Pushed a PR with the proposed change for this, just waiting for it to pass CI.

**Comment by aouelete** [comment]
Thanks!
