### ISSUE TITLE
Feature Request: HotKeys for Mini and Large Player

### ISSUE THREAD

**Issue by Alipoodle** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#857]
You could add a Hotkey which would allow people to open the program back up from the tray, either in the Mini or Large Player.

**Comment by jostrander** [comment]
As in, "Show Mini Player", "Show full player" in the system tray?

**Comment by Alipoodle** [comment]
Yes! This could either be Hot Keys or just in the menu from the System Tray

**Comment by MarshallOfSound** [comment]
I've mentioned in other issues the tray menu is already a bit bloated.  Is there any major UX reason why using the button in the existing UI is harder / unreasonable to use?

**Comment by Alipoodle** [comment]
I personally prefer to go into my system tray and have to open the menu up. That's why i thought of an idea for a hotkey to open in full  / mini player. The idea for adding it into the system tray kind of came from jostrander.

**Comment by ajacobson** [comment]
On OS X this could work like iTunes via the "Window" menu in the menubar.  I don't know how feasible this approach would be on other platforms.  Even if this shortcut isn't visible from any menu, it would be great if there was a keyboard shortcut to toggle between the two modes.

![screen shot 2016-04-05 at 1 01 50 pm](https://cloud.githubusercontent.com/assets/617552/14290939/11660710-fb2f-11e5-8a11-271f4aaac055.png)
![screen shot 2016-04-05 at 1 02 02 pm](https://cloud.githubusercontent.com/assets/617552/14290940/1166b886-fb2f-11e5-8632-58d32651c971.png)

**Comment by Alipoodle** [comment]
I Was thinking of something similar to that.
