### ISSUE TITLE
Add more theming options? 

### ISSUE THREAD

**Issue by SweBeat** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#86]
I like the idea of being able to theme Google Play Music to a color of my choice. However, I wish I could also change the main color that you use in the dark version. Is it possible to add control over that as well? So I can change both the orange to whatever I want and also the dark that you picked to anything I want?

**Comment by MarshallOfSound** [comment]
This is related to https://github.com/twolfson/google-music.js/issues/13

There is a massive push by a few people in this GPM player space to get libraries made for things like that, monitor that repo and progress their for progress on this issue
