### ISSUE TITLE
The website doesn't offer RPM packages

### ISSUE THREAD

**Issue by bugaevc** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#862]
**OS:**
Fedora 23 x64

**Issue Descriptions:**
The official website doesn't provide a way to download an RPM packages, although they seem to exist, according to #244 & #288

**Steps to Reproduce:**
* Go to the http://www.googleplaymusicdesktopplayer.com/
* Click that gorgeous Material _Download_ button
* It would prompt you to choose your platform -- pick _Linux 64-bit_
* It would automatically start to download a `.deb`, as if you were on Ubuntu or Debian.

... Ideally you should provide a COPR & a PPA for automatic updates.

**Comment by jostrander** [comment]
The RPM's are released on the releases tab here on github, and the website is just grabbing the information from the releases tab here.

RPM packages are at the top here:
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/releases/tag/v3.1.0

**Comment by bugaevc** [comment]
Thanks, I know they exist. The issue is that the site assumes I'm on Ubuntu, while I'm not. Not everybody cares enough to make it all the way to GitHub releases tab. For less tech-savvy people, it would all be like "ah! the player wouldn't install" -- they may know what distro they're running, some basic terminal commands and how to copy-paste more complex ones -- but have no idea what format their package manager uses.

Maybe the right way is to have just the _Linux_ option that would ask the visitor to choose the desired architecture and format.

By the way, both the OS and the architecture can be easily extracted from User-Agent, greatly simplifying the experience.

**Comment by jostrander** [comment]
I think the website could use a face lift for the download options considering there are more than 4 released options, so I agree on that front. The OS sniffing is good for differentiating between mac/win/linux and 32/64, but won't show the different distros in linux. On that front I think it would be better to have a drop down with 4 options, the 2 deb packages and the 2 rpm packages. 

I considered trying to import this repo into a ppa, but it's way out of my league considering launchpad requires everything to be built from source on their servers and packaged there. There was a a large discussion about tha on one of the reddit threads a while back, but I don't think it ended up anywhere.

**Comment by bugaevc** [comment]
> The OS sniffing is good for differentiating between mac/win/linux and 32/64, but won't show the different distros in linux.
I didn't mean it, but now that you're mention it -- actually, on Fedora Firefox & Chrome have an extension pre-installed that adds `Fedora` to User-Agent.

**Comment by bugaevc** [comment]
Thanks ;)
