### ISSUE TITLE
Add play/back/forward buttons to the Windows taskbar preview

### ISSUE THREAD

**Issue by Fsmv** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#864]
**OS:** Windows 7/8/10

**Feature Description:** Windows allows applications to add buttons to the preview window that appears when you hover over the application icon in the task bar. GPMDP should, like nearly every other media player application, show Play, Back, and Forward buttons there.

While you're at it, it might be better to use the album cover image as the preview image instead of the default screenshot of the application.

Example (VLC):
![Taskbar preview](http://i.imgur.com/b8df2X7.png)

Windows Documentation for this feature: [MSDN Thumbnail Toolbars](https://msdn.microsoft.com/en-us/library/windows/desktop/dd378460%28v=vs.85%29.aspx#thumbbars)

**Comment by jostrander** [comment]
This is already implemented using electron's API here:

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/main/features/win32/thumbbarButtons.js

Are they not showing when you are playing music?

**Comment by Fsmv** [comment]
They are not; I'm on Windows 10. I get nothing regardless of whether I'm playing radio or a single. Here's what I get:
![](http://i.imgur.com/R1gRzBb.png)

**Comment by jostrander** [comment]
I'm able to reproduce this. I'm not sure what is causing it yet though.

**Comment by jostrander** [comment]
Do you have native window borders enabled or disabled?

**Comment by Fsmv** [comment]
They're not enabled.

**Comment by jostrander** [comment]
If you quit the application and load it up, do they show up on launch?

**Comment by Fsmv** [comment]
They do! It seems the problem is re-opening the window after minimizing to the tray.

**Comment by jostrander** [comment]
That's what I found as well. @MarshallOfSound will probably know more about this, or if it's an electron bug as he develops on windows primarily.

**Comment by MarshallOfSound** [comment]
Can confirm, this is a known electron bug.

I have raised it in their repository and it remains open

**Comment by MarshallOfSound** [comment]
The issue is when you minimize to task bar and reopen the buttons appear to vanish

**Comment by Fsmv** [comment]
Can you send a link to the electron issue?

**Comment by MarshallOfSound** [comment]
https://github.com/atom/electron/issues/4514
