### ISSUE TITLE
Missing tray icon - elementary os

### ISSUE THREAD

**Issue by Thomas-O** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#865]
The player's sys tray icon is missing on my Elementary Freya. As neither the launcher nor the listing in the sound menu indicator will recall the player I have no means of showing the minimised window. However, I can still control playback from the sound indicator menu.

The tray icon is present and works just fine on my Ubuntu 14.04. Though I frequently mistake it for the near-identical Google Music Manager icon. Might it be a good idea to give the user the option to change the colour of the player's icon?

**Comment by MarshallOfSound** [comment]
Can you please raise this as a generic "tray icon doesn't work on Elementary Freya" issue on https://github.com/atom/electron/issues

**Comment by GreyAsteroid** [comment]
This issue has been fixed by this PR https://github.com/electron/electron/pull/7319 merged into the newest version of electron https://github.com/electron/electron/releases/tag/v1.4.2
