### ISSUE TITLE
Build fails dbus-1 not found

### ISSUE THREAD

**Issue by F3TTT** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#867]
**OS:**  Fedora 21 Desktop

**Issue Descriptions:**
Can't build.  I see quite a few errors during npm install about dbus-1 not found is the first one.  I can reproduce the issue as I tried cloning 2x and building again.  Nothing in FAQ.

Package dbus-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `dbus-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'dbus-1' found
gyp: Call to 'pkg-config  --libs-only-l --libs-only-other dbus-1' returned exit status 1. while trying to load binding.gyp
npm http 200 https://registry.npmjs.org/mkdirp/0.3.0
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:428:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
npm http 200 https://registry.npmjs.org/commander/0.6.1
gyp ERR! System Linux 4.1.13-100.fc21.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /root/projects/googlePlayMusicManager/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/dbus
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok 

**Steps to Reproduce:**
mkdir googleMusic
git clone https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-.git
npm install
[npm-debug.log.gz](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/199690/npm-debug.log.gz)

**Comment by MarshallOfSound** [comment]
Can can find linux build dependencies in the CI build YML file

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/circle.yml#L8
