### ISSUE TITLE
Install version 3.1.0 fails on Windows 8.1

### ISSUE THREAD

**Issue by ddanjou** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#868]
**OS:**
WIndows 8.1

**Issue Descriptions:**
Cannot install - get animated splash screen for several seconds followed by 
:"Installation has failed. There was an error while installing the application. Check the setup log for more information and contact the author."
log attached
[GDMP-Failed_Setup-20176-04-01-win81-SquirrelSetup.log.txt](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/199896/GDMP-Failed_Setup-20176-04-01-win81-SquirrelSetup.log.txt)

Tried again running as adminisitrator resulting in:
A JavaScipt error occured in the main process. 
Unvcaught Exception:
SyntaxError: Unexpected Token

**Steps to Reproduce:**
uninstall previous version (I have had them since the the first release)
run installer Google.Play.Music.Desktop.Player.x64.exe version 3.1.0.0

**Comment by MarshallOfSound** [comment]
OK, so it sounds like somehow some funky installer things have happened.  Resetting your install should get everything working again.

Delete the follow folders
* `%APPDATA%\Google Play Music Desktop Player`
* `%LOCALAPPDATA%\GPMDP_3`

Then ensure both versions of GPMDP have been uninstalled from control panel.  Then try installing `3.1.0` again

**Comment by ddanjou** [comment]
Awesome. Done. Fixed.
MERCI!!!

 

    On Friday, April 1, 2016 11:51 AM, Samuel Attard <notifications@github.com> wrote:
 
 

 OK, so it sounds like somehow some funky installer things have happened. Resetting your install should get everything working again.Delete the follow folders   
   - %APPDATA%\Google Play Music Desktop Player
   - %LOCALAPPDATA%\GPMDP_3
Then ensure both versions of GPMDP have been uninstalled from control panel. Then try installing 3.1.0 again—
