### ISSUE TITLE
Bug: Scroll Bar Remains when Fullscreen

### ISSUE THREAD

**Issue by Devo7v** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#87]
When the normal window is open, if you open the GPM sidebar while music is playing and select the album art in the lower left corner to make it full screen, the scroll bar for the sidebar as well as the scroll bar for the main window is overlaid on the album art visualization.  This occurs with both the light and dark theme.  See the attached screenshot.
![untitled](https://cloud.githubusercontent.com/assets/15945504/11696771/03764de8-9e84-11e5-9ece-42e57553f006.png)

**Comment by MarshallOfSound** [comment]
I've noticed this for a while and I am under the firm impression that it is a CEF bug.  I will monitor the situation with CEF and see if I can implement a workaround, but probably just a rendering glitch that won't be fixed till CEF pushes their next major

**Comment by Devo7v** [comment]
I also just realized that the scroll bars also show up on the miniplayer as well.  I've noticed them for awhile now, but couldn't figure out what the dark boxes were.  See attached.
![untitled](https://cloud.githubusercontent.com/assets/15945504/11746234/07915e32-9feb-11e5-91b7-183d979eb3e6.png)

**Comment by MarshallOfSound** [comment]
With the new theming library I created in `gmusic-utils` this issue does not appear to be present anymore on my local

**Comment by Devo7v** [comment]
I'm still seeing this on the latest 2.0 release.
