### ISSUE TITLE
Pause music on screen lock

### ISSUE THREAD

**Issue by shakehar** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#871]
**OS:** Windows

**Issue Descriptions:** It would be really nice if the app would pause music when the screen is locked.  

**Steps to Reproduce:** n/a

**Comment by jostrander** [comment]
Something like this would be almost impossible to implement cross platform, especially since there's no API in electron to listen for that type of event.

**Comment by MarshallOfSound** [comment]
What @jostrander said :)

Also it's very subjective I like to lock my computer and have music playing while I work nearby.  I don't believe other music players (WPM) do this either

**Comment by shakehar** [comment]
Amazon music player for windows does this. @jostrander It never occurred to me that electron might not expose such an event. @MarshallOfSound if possible this could be a setting that the user can toggle of/on
