### ISSUE TITLE
Last.fm login not working

### ISSUE THREAD

**Issue by timp3289** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#876]
Hi
**OS: arch linux x64**
**Description**
When I click the login to last.fm button, the status changes to "authorization in progress" and the button says "..." Then the status changes to "not authorised"
There is no login box / username prompt or anything

**Steps to reproduce:**
Open app 
Go to settings
Click log in to last.fm

**Comment by MarshallOfSound** [comment]
This is due to how your AUR package works I believe.  Because it builds from source the last.fm API keys that I distribute with all the other packages aren't set.

You can register your own API keys and set the correct environment variables if you want to use them :+1:

**Comment by hydandata** [comment]
@MarshallOfSound I tried what you suggest: 

```
export GPMDP_LASTFM_API_KEY="..."
export GPMDP_LASTFM_API_SECRET="..."
```
and it still gets stuck the same way, I launched from cli as well, and don't see any Last.fm related messages there.

**Comment by jostrander** [comment]
You'd need to set those before building the package in order for them to be baked in.
