### ISSUE TITLE
Issue: 2FA Option to "Install Plugin" Causes Inability to Navigate App

### ISSUE THREAD

**Issue by MetaMonk** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#877]
OS: Windows 7

Issue Descriptions: When using 2FA with a Yubi key, there is an option to install the Yubi key plugin that the instance of GPDMP doesn't have. Clicking install (I was curious :persevere:) takes you to the Chrome Web Store, from which you can't navigate backwards. Uninstalling the update and ten re-updating and using another 2FA method works fine.

Steps to Reproduce:
1. Click yes when asked to update
2. When updated app opens, begin the re-authentication process
3. With 2FA turned on and while using hardware 2FA, Google Auth will ask you first ask you to install a plugin so it can read the 2FA hardware
4. Click Install Plugin
5. Get redirected to Chrome Web Store, from which you can't navigate backwards, even after closing the application.

**Comment by MarshallOfSound** [comment]
This is what I would describe as a "DSTGSR" thing.  (I use that acronym far too much)

Do Silly Things, Get Silly Results :+1: :laughing: 

I guess I could try prevent that link being clicked.  But I also want to maintain user trust by not injecting ANY code into the authentication page.

So TLDR clicking the link is a funky thing to do.  The bug where it makes the app unusable is a separate thing and fixable. :+1: 

But I'm not going to hide the link or anything like that. :smile: :laughing:
