### ISSUE TITLE
Feature Request: Ability to download a song an unlimited number of times, like in Chrome

### ISSUE THREAD

**Issue by adinklotz** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#879]
In Google Chrome, Google Play Music allows you to download a song or album as mp3 any number of times, provided you have the Play Music extension.  In any other browser, and in GPM Desktop Player, there is a limit of 2 downloads per song.  If possible, it would be nice to remove that limit for the desktop player.  [(Here's what Google says about music downloads)](https://support.google.com/googleplay/answer/1250232?hl=en)

**Comment by jostrander** [comment]
Just out of curiosity, what is the use case for this?

**Comment by adinklotz** [comment]
You can listen offline, or you can transfer the files to an mp3 player that doesn't have Play Music. Maybe other uses, but those are the 1st that come to mind

**Comment by jostrander** [comment]
The likelihood of this being implemented is pretty slim, it's not a simple flag that can be switched on the GPM page. The chrome extension loads in the native binaries for music manager and quite a bit of code in order to make this happen which would be tough to reimplement.

**Comment by MarshallOfSound** [comment]
@adinklotz As has been pointed out by @jostrander there is a whole load of compiled code that is part of that chrome extension and unfortunately I can't replicate it.
