### ISSUE TITLE
Installation Failed on Fedora 23

### ISSUE THREAD

**Issue by DanielWEWO** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#883]
**OS:**
Fedora 23 
4.4.6-300.fc23.x86_64

**Issue Descriptions:**
Installation through software center fails with error message "Sorry, this did not work; Installation of An electron wrapper for Google Play Music failed."

**Steps to Reproduce:**

Download 64 bit .rpm from https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/releases, double click to attempt to install with software center

Would be awesome to be able to use this! This works great on my laptop on Ubuntu.

Also, attempting to install with dnf

`sudo dnf install google-play-music-desktop-player-3.1.0.amd64.rpm 
[sudo] password for dlynch: 
Error: package google-play-music-desktop-player-3.1.0-1.amd64 is not installable
(try to add '--allowerasing' to command line to replace conflicting packages)
[dlynch@localhost Downloads]$ sudo dnf install google-play-music-desktop-player-3.1.0.amd64.rpm --allowerasing
Error: package google-play-music-desktop-player-3.1.0-1.amd64 is not installable
`

**Comment by MarshallOfSound** [comment]
Did you try installing with the `--allowerasing` flag as the error suggests?

I think I've seen this before and that flag fixed it.

**Comment by DanielWEWO** [comment]
Yeah, if you look closer you can see that I tried it again with that flag, sorry for the bad formatting.

`[dlynch@localhost Downloads]$ sudo dnf install google-play-music-desktop-player-3.1.0.amd64.rpm --allowerasing Error: package google-play-music-desktop-player-3.1.0-1.amd64 is not installable`

**Comment by jostrander** [comment]
I mean quite honestly it's a pretty vague error, what's it conflicting with? FWIW, triple back ticks on the line before and after will avoid line breaks. 

```
[dlynch@localhost Downloads]$ sudo dnf install google-play-music-desktop-player-3.1.0.amd64.rpm --allowerasing Error: package google-play-music-desktop-player-3.1.0-1.amd64 is not installable
```

**Comment by DanielWEWO** [comment]
Thanks. Yeah, it is really vague and I'm not sure what's conflicting it's actually a relatively new Fedora installation. I tried installing with the verbose option and it didn't give any more information.

**Comment by jostrander** [comment]
Can you try running with `--verbose` ?

**Comment by DanielWEWO** [comment]
Other than my issues with repos lol, the output is the same.


```[dlynch@localhost Downloads]$ sudo dnf install -v google-play-music-desktop-player-3.1.0.amd64.rpm --allowerasing
cachedir: /var/cache/dnf
Loaded plugins: Query, debuginfo-install, needs-restarting, protected_packages, reposync, playground, config-manager, generate_completion_cache, copr, noroot, builddep, download
DNF version: 1.1.7
repo: using cache for: rommon-telegram
not found deltainfo for: Copr repo for telegram owned by rommon
not found updateinfo for: Copr repo for telegram owned by rommon
Failed to synchronize cache for repo 'Dropbox' from 'http://linux.dropbox.com/fedora/23/': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried, disabling.
repo: using cache for: fedora
not found deltainfo for: Fedora 23 - x86_64
not found updateinfo for: Fedora 23 - x86_64
repo: using cache for: rpmfusion-nonfree
not found deltainfo for: RPM Fusion for Fedora 23 - Nonfree
not found updateinfo for: RPM Fusion for Fedora 23 - Nonfree
repo: using cache for: updates
repo: using cache for: rpmfusion-free
not found deltainfo for: RPM Fusion for Fedora 23 - Free
not found updateinfo for: RPM Fusion for Fedora 23 - Free
repo: using cache for: rpmfusion-free-updates-testing
not found deltainfo for: RPM Fusion for Fedora 23 - Free - Test Updates
not found updateinfo for: RPM Fusion for Fedora 23 - Free - Test Updates
repo: using cache for: rpmfusion-nonfree-updates-testing
not found deltainfo for: RPM Fusion for Fedora 23 - Nonfree - Test Updates
not found updateinfo for: RPM Fusion for Fedora 23 - Nonfree - Test Updates
repo: using cache for: google-chrome
not found deltainfo for: google-chrome
not found updateinfo for: google-chrome
rommon-telegram: using metadata from Fri Mar 18 13:32:56 2016.
fedora: using metadata from Sat Oct 31 10:34:41 2015.
rpmfusion-nonfree: using metadata from Sun Oct 11 08:50:38 2015.
updates: using metadata from Sat Apr  2 12:19:05 2016.
rpmfusion-free: using metadata from Sun Oct 11 09:43:19 2015.
rpmfusion-free-updates-testing: using metadata from Sun Mar 20 03:24:00 2016.
rpmfusion-nonfree-updates-testing: using metadata from Sun Mar 20 03:30:01 2016.
google-chrome: using metadata from Wed Mar 30 11:17:34 2016.
Last metadata expiration check: 2:13:36 ago on Sat Apr  2 20:13:15 2016.
--> Starting dependency resolution
--> Finished dependency resolution
Error: package google-play-music-desktop-player-3.1.0-1.amd64 is not installable
```

**Comment by jostrander** [comment]
I'm not an expert in fedora, but doesn't dnf get packages from repositorys and `rpm -i` installs them?

**Comment by DanielWEWO** [comment]
dnf should work for local files, but I just tried with rpm -i and it worked! Thanks guys. I don't know why dnf wouldn't work though.

**Comment by MarshallOfSound** [comment]
**Mystical ways of linuxy things*

**Comment by dhollinger** [comment]
DNF and/or YUM are the preferred way to handle the installation of RPM packages as they will also handle the issues related to "Dependency Hell". Something that rpm -i doesn't manage. As part of the RHCSA and RHCE training we are taught both methods, but using rpm -i and rpm -e are both strongly discouraged.

Point is, DNF and YUM provide checks to ensure that an RPM is properly built. If DNF or YUM are unable to install the rpm, but rpm -i can, that means there is something wrong with the package itself.

**Comment by jostrander** [comment]
@dhollinger As stated, I'm by no means an expert with fedora or enterprise linux systems, yum, DNF, etc. I was relating the tools at hand to apt-get vs dpkg in debian. If you see something wrong with the RPM packages please feel free to submit an Issue or even better a pull request on how it can be fixed. However also please note the RPM is packaged via https://github.com/unindented/electron-installer-redhat from the binaries created by https://github.com/electron-userland/electron-packager.
