### ISSUE TITLE
Thanks for the suggestion. But I have an issue with a white screen.

### ISSUE THREAD

**Issue by norenkonikita** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#885]
Linux Mint 17.3

I downloaded the .deb package with this githab. Install and open the player, I introduced the e-mail, password, and after my phone came sms with the code is authenticated two-stage player screen just white. 

You can see my player on the screenshot. By the way, this bug appeared only in the new version, a week ago it worked.
#
![screen](https://cloud.githubusercontent.com/assets/13417937/14233786/a8a34936-f9da-11e5-8103-a5bc804bfc96.png)

**Comment by jostrander** [comment]
So I'm assuming  you did try the `--disable-gpu` flag?

**Comment by norenkonikita** [comment]
Thanks, it helped me. Everything is working.
