### ISSUE TITLE
Is it possible to integrate ublock origin ?

### ISSUE THREAD

**Issue by pgera** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#889]
ublock origin is a wide spectrum blocker with extensions for chromium and firefox. Are chromium and electron's APIs similar enough that it can be ported to work with this ?

**Comment by MarshallOfSound** [comment]
My question here is why?  It's not like Google Play Music has ads on it?

**Comment by MarshallOfSound** [comment]
Oops, misclick

**Comment by pgera** [comment]
It does. Perhaps you are using a pro account ?

**Comment by MarshallOfSound** [comment]
Hmmmm, interesting.  I do indeed have an All Access account and perhaps that is killing the ads for me.

As for integrating uBlock origin, unfortunately the chrome extension API's and electron API's are incompatible.  I would suggest using a system level ad blocker if blocking these ads is a major thing for you.
