### ISSUE TITLE
feature request: add "I'm Feeling Lucky" button to mini player (like the official mini player)

### ISSUE THREAD

**Issue by smiller171** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#891]
**OS:**
OSX

**Issue Descriptions:**
When in the mini player, there is no "I'm Feeling Lucky" Button. I often use this in the official mini player and would like to have the feature in your app.

**Steps to Reproduce:**
Go to mini player, witness that there is no "I'm Feeling Lucky" button

**Comment by MarshallOfSound** [comment]
Please raise this over at https://github.com/MarshallOfSound/gmusic-mini-player.js/issues

**Comment by smiller171** [comment]
Thanks. Didn't realize there were two repos

**Comment by smiller171** [comment]
Issue moved to [MarshallOfSound/gmusic-mini-player.js #6](https://github.com/MarshallOfSound/gmusic-mini-player.js/issues/6) via [**ZenHub.io**](https://www.zenhub.io/)
