### ISSUE TITLE
Error when opening the installer

### ISSUE THREAD

**Issue by theforkofyork** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#893]
**OS:**
Windows 7 64 Bit
**Issue Descriptions:**
When opening the installer there's an error which is:

A JavaScript error occured in the main process
Uncaught Exception:
SyntaxError: Unexpected Token

**Steps to Reproduce:**
Open the V3.1.0 installer

**Comment by jostrander** [comment]
Are you running it as administrator? 
Do you have a previous installation of gpmdp?
Do you have UAC enabled? 

Can you gather the full log from `%LOCALAPPDATA%/GPMDP_3` ?

If all else fails, can you try deleting the following folders and attempt to reinstall?

* %APPDATA%\Google Play Music Desktop Player
* %LOCALAPPDATA%\GPMDP_3

**Comment by theforkofyork** [comment]
Deleting the %APPDATA%\Google Play Music Desktop Player and %LOCALAPPDATA%\GPMDP_3 files fixed it, thanks.
