### ISSUE TITLE
Feature Request: Background Audio

### ISSUE THREAD

**Issue by maxiSchaeff** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#896]
Hi, is there a way to keep the music playing in connected standby when the screen is turned off? :)
In Chrome this is possible by running the program with the -enable-exclusive-audio flag.
Thank you!:D

**Comment by MarshallOfSound** [comment]
The only workaround for this (I have looked into this before) is to use the `enable-exclusive-audio` flag but that flag blocks other programs from using the audio device which is not something you really want a music player to do.

So not really, no :cry:
