### ISSUE TITLE
Mic is always open and app is uploading at about 16KB/s !!

### ISSUE THREAD

**Issue by bencprezola** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#897]
**OS:**
Linux

**Issue Descriptions:**
My mic is my webcam, and I noticed that whilst the app is running, the LED is on. Turns out GPMDP is using the mic for some reason. Also just as worrying, there is a consistent upload of 16KB/s whilst the app is running. This screams security issue.

**Steps to Reproduce:**
Run the app on linux and watch network and mic usage.

**Comment by MarshallOfSound** [comment]
Have you got voice controls turned on?

**Comment by bencprezola** [comment]
Yep. Sorry to have wasted your time and called this out as a security issue. Feel quite stupid now :P

**Comment by MarshallOfSound** [comment]
Looool its ok.  Just blame it on the cat next door and have an :eggplant:
