### ISSUE TITLE
Can't set hotkeys in Ubuntu

### ISSUE THREAD

**Issue by greenwald** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#898]
OS: Ubuntu 14.04.4

In the setting menu under Hotkeys I cannot actually set the hotkeys. I can seemingly select which one I want to set (the text highlights), but there is no response to typing.

**Comment by MarshallOfSound** [comment]
Click in the hotkey box you want to set.  Try performing the hotkey.

An example is "Cntrl + Shift + E".  I know this works on Ubuntu because I have tested it :+1:

**Comment by greenwald** [comment]
Ah, yes, indeed. Sorry. So I take it one cannot use the F# keys as hotkeys, nor function + (something) keys? It seems to only respond to ctrl + (something).

**Comment by MarshallOfSound** [comment]
Yeah, there are some limitations at the moment.  See #413
