### ISSUE TITLE
Error when starting GPMDP (also after fresh install of it)

### ISSUE THREAD

**Issue by berryelectronics** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#899]
[Link of an Image of the error](http://puu.sh/o79vP/76ebd854a3.png)

So i tried to start GPMDP again aand got this error message saying that there is an error with javascript. deinstalled it, deleted the appdata folder of GPMDP and installed it again. same error

OS: Windows 10

Dont know how to reproduce, not sure what the problem is.

**Comment by MarshallOfSound** [comment]
Could be a permissions error / bad install.  Can you redownload the installer from https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/releases and try a clean install

**Comment by berryelectronics** [comment]
thanks. deleted roaming and local appdata folders of it and reinstalled the
3.1 version. works now. thank you :)
~berrylectronics

Samuel Attard <notifications@github.com> schrieb am Mi., 6. Apr. 2016 um
03:39 Uhr:
