### ISSUE TITLE
[ArchLinux] Error when Login

### ISSUE THREAD

**Issue by stasfilin** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#900]
OS: ArchLinux
Application Version: installed: 3.1.0.29.gbbe5111-1

Hi, so I have a blank screen when I try to login to the program.
Maybe it's 'cause I'm using 2-Step Verification?

A summary of the issue:

1. Start Program
2. Click login button
3. Use my email
4. Use my password
5. Then i have white screen, but google send me sms code.

**Comment by jostrander** [comment]
Try with --disable-gpu

**Comment by stasfilin** [comment]
@jostrander thanks, It's working for me
