### ISSUE TITLE
Universal Windows App being considered?

### ISSUE THREAD

**Issue by gustavowd** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#902]
Have you ever considered to implement a universal app for google music player? Windows 10 mobile lacks a good google music client. An universal app could fulfil this gap, as well as produce a universal app for PCs, tablets and smartphones.

**Comment by MarshallOfSound** [comment]
I believe there was an issue raised for this somewhere else.  But the TLDR is that the framework we use (electron) does not support UWA
