### ISSUE TITLE
Feature Request: Cache playlists/albums, similar to the android app

### ISSUE THREAD

**Issue by mikelcarr92** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#903]
The little orange tick!

**Comment by jostrander** [comment]
Unfortunately this is not something that can be done on desktop period. There is no API for it. @MarshallOfSound this should be added to the FAQ.

**Comment by MarshallOfSound** [comment]
@jostrander Indeed it should :+1:
