### ISSUE TITLE
Unable to adjust individual volume settings in Windows Volume Mixer

### ISSUE THREAD

**Issue by HeyItsJono** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#904]
**OS:** Windows 8.1

**Issue Descriptions:** The option for GPMDP in the Windows Volume Mixer is incorrectly displayed and doesn't have a slider to adjust the volume. [Screenshot.](http://i.imgur.com/9Tbp3Rr.png)

**Steps to Reproduce:** Simply open the Windows Volume Mixer from the system tray and scroll to the GPMDP option.

**Comment by jostrander** [comment]
Known issue, see #848.

**Comment by HeyItsJono** [comment]
Oops, my bad, didn't see that.
