### ISSUE TITLE
Show play status in tray icon

### ISSUE THREAD

**Issue by Dazzel** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#905]
It would be great if the tray icon changes based up on the current state of the player:

* playing
* paused
* stopped

**Comment by jostrander** [comment]
Just need new tray icons to be made with the overlay, assuming playing/paused only and stopped would be the normal icon.

**Comment by MarshallOfSound** [comment]
I looked into this when I just updated the players icon and unfortunately (on windows at least) the tray icon is too low fidelity (this is a known electron bug) so that adding play/paused state icons simply weren't noticable
