### ISSUE TITLE
Cinnamon sound applet shows "Unknown" for track information

### ISSUE THREAD

**Issue by wengole** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#906]
**OS:**
Arch Linux - Cinnamon DE

**Issue Descriptions:**
Although the cinnamon sound applet recognises GPMDP is playing music, and the controls work, the track information is missing. See screenshot
![menu_008](https://cloud.githubusercontent.com/assets/383857/14314504/7ba6d422-fbef-11e5-9578-b599891927b2.png)

**Steps to Reproduce:**
Using cinnamon DE, enable Playback API and start music. Notifications work, as does music controls in the sound applet, but the track information is missing

**Comment by MarshallOfSound** [comment]
@jostrander Not sure what could be going on here

**Comment by jostrander** [comment]
@wengole Can you verify the info is available over dbus with the following command:

**Comment by wengole** [comment]
```
signal time=1459956550.276808 sender=:1.953 -> destination=(null destination) serial=660 path=/org/mpris/MediaPlayer2; interface=org.freedesktop.DBus.Properties; member=PropertiesChanged
   string "org.mpris.MediaPlayer2.Player"
   array [
      dict entry(
         string "Metadata"
         variant             array [
               dict entry(
                  string "mpris:artUrl"
                  variant                      string "https://lh3.googleusercontent.com/1ssBVflQhWLzn_XG2XVdZGN-LO0ol9s5trcCFMiZ_Hb6c61AOqZbAIwrqIqoPn130vYtDEa9dA=s90-c-e100"
               )
               dict entry(
                  string "xesam:asText"
                  variant                      string ""
               )
               dict entry(
                  string "xesam:title"
                  variant                      string "II. Andante"
               )
               dict entry(
                  string "xesam:album"
                  variant                      string "Schubert: Symphonies Nos. 1-6, 8 & 9"
               )
               dict entry(
                  string "xesam:artist"
                  variant                      string "Sir Colin Davis"
               )
               dict entry(
                  string "mpris:length"
                  variant                      uint32 412000000
               )
            ]
      )
   ]
   array [
   ]
```

So yes the data is coming through. As I mentioned, the notifications on track change work and have album art and track info, it's just the applet, but to be fair I've never used the applet with any other media players, but it does seem unlikely it doesn't work at all :P

**Comment by jostrander** [comment]
It's not the first time I've seen the cinnamon applet failing to work... I
would verify other players show data and make sure your up to date. I know
there was a "better sound applet" floating around that had a lot of bugs
squashed that was a direct replacement, maybe that one will work correctly.

**Comment by wengole** [comment]
So it works with Banshee
![menu_009](https://cloud.githubusercontent.com/assets/383857/14323360/2324f936-fc18-11e5-84f1-b3490f62964a.png)
I did try [this](https://cinnamon-spices.linuxmint.com/applets/view/150) but although it worked, the controls were unusable.

**Comment by wengole** [comment]
If it helps, this is the dbus output from Banshee switching tracks

```
signal time=1459958234.419598 sender=:1.1493 -> destination=(null destination) serial=105 path=/org/mpris/MediaPlayer2; interface=org.freedesktop.DBus.Properties; member=PropertiesChanged
   string "org.mpris.MediaPlayer2.Player"
   array [
      dict entry(
         string "Metadata"
         variant             array [
               dict entry(
                  string "mpris:trackid"
                  variant                      object path "/org/bansheeproject/Banshee/Track/8349"
               )
               dict entry(
                  string "mpris:length"
                  variant                      int64 142568000
               )
               dict entry(
                  string "xesam:url"
                  variant                      string "file:///home/ben/Dropbox/the_witcher_3_wild_hunt_-_official_soundtrack__mp3/the_witcher_3_wild_hunt_-_official_soundtrack__mp3/02%20Geralt%20of%20Rivia.mp3"
               )
               dict entry(
                  string "xesam:title"
                  variant                      string "Geralt of Rivia"
               )
               dict entry(
                  string "xesam:album"
                  variant                      string "The Witcher 3: Wild Hunt - Official Soundtrack"
               )
               dict entry(
                  string "xesam:artist"
                  variant                      array [
                        string "Marcin Przybyłowicz"
                     ]
               )
               dict entry(
                  string "xesam:albumArtist"
                  variant                      array [
                        string "Marcin Przybyłowicz, Mikolai Stroinski"
                     ]
               )
               dict entry(
                  string "xesam:genre"
                  variant                      array [
                        string "Soundtrack"
                     ]
               )
               dict entry(
                  string "xesam:trackNumber"
                  variant                      int32 2
               )
               dict entry(
                  string "mpris:artUrl"
                  variant                      string "file:///home/ben/.cache/media-art/album-027fe3fb1d62eb38b14c15e725362a62.jpg"
               )
            ]
      )
   ]
   array [
   ]
```

**Comment by wengole** [comment]
The only difference I can see is that artist and albumArtist are arrays from Banshee (and that there's no albumArtist in GPMDP)

**Comment by jostrander** [comment]
Good eye, listed here in the spec it is supposed to be an array:

https://www.freedesktop.org/wiki/Specifications/mpris-spec/metadata/#index6h4

I bet the JS in the applet is attempting to iterate over the string via loop and its breaking. I'll see if I can fix this and have a change pushed shortly.

**Comment by wengole** [comment]
In fairness, I put it through a diff tool which helped :package: 

Awesome if you can fix it soon, I can pull and test straight away

**Comment by jostrander** [comment]
Looks like I might have an upstream issue to fix ith how arrays of strings are handled. This is more than a 30 second fix. :snail: In the mean time I will push my branch up to my repo and you can see if the current output works for you, but it broke my artist entry.

**Comment by jostrander** [comment]
Actually, @wengole can you see if the fix-mpris-artist branch on my repo works for you? Here's what I'm getting in dbus when changing to an array:

```
               dict entry(
                  string "xesam:artist"
                  variant                      array [
                        variant                            string "The Glitch Mob"
                     ]
               )
```

and I think the variant type is causing an issue in gnome, but maybe it won't in cinnamon.

**Comment by wengole** [comment]
This is what I'm getting now
```
signal time=1459962612.155035 sender=:1.1583 -> destination=(null destination) serial=37 path=/org/mpris/MediaPlayer2; interface=org.freedesktop.DBus.Properties; member=PropertiesChanged
   string "org.mpris.MediaPlayer2.Player"
   array [
      dict entry(
         string "Metadata"
         variant             array [
               dict entry(
                  string "mpris:artUrl"
                  variant                      string "https://lh6.ggpht.com/bEmFWvymGBqDCMi9pgL_1GUcRFmCw6zeEIan58VNd7QBuapGxasDJuVg7eZ6WGoksBB_BsHOKA=s90-c-e100"
               )
               dict entry(
                  string "xesam:asText"
                  variant                      string ""
               )
               dict entry(
                  string "xesam:title"
                  variant                      string "Don Quixote Suite, Don Quixote At Rest: Vivace"
               )
               dict entry(
                  string "xesam:album"
                  variant                      string "Telemann: Don Quixote Suite"
               )
               dict entry(
                  string "xesam:artist"
                  variant                      array [
                        variant                            string "Elisabeth Mann"
                     ]
               )
               dict entry(
                  string "mpris:length"
                  variant                      uint32 66000000
               )
            ]
      )
   ]
   array [
   ]
```
And this is how the applet looks
![menu_010](https://cloud.githubusercontent.com/assets/383857/14325795/e1744180-fc22-11e5-8c30-30f6af39e395.png)

Weird that it's showing almost everything, but still complaining on the artist

**Comment by wengole** [comment]
Also track progress is missing, and may be another issue with wrong type. You're sending a uint32 whereas Banshee was just using a int32, but let's focus on one thing at a time ;)

**Comment by jostrander** [comment]
Heh, yeah its because variant is actually marshalled (encoded) to an object of sorts, so the underlying library is taking this:
```javascript
{
artist: [song.arist] // where song.artist is a string
}
```

```
               dict entry(
                  string "xesam:artist"
                  variant                      array [
                        variant                         string "The Glitch Mob"
                     ]
               )
```
instead of 
```
               dict entry(
                  string "xesam:artist"
                  variant                      array [
                        string "The Glitch Mob"
                     ]
               )
```

Currently were using emersion/node-mpris, which is fine, but the underlying dbus library is the one at fault here, and its all written in CC since its native. There is a pure JS dbus library, but I'm not sure if its drop-in capable and/or if it would work better in this case. Some testing is in order...

**Comment by wengole** [comment]
Well I'm happy to run your branches if you need a tester. Figured out how to point PKGBUILD at a branch, and it's all good :smile:

**Comment by jostrander** [comment]
I'm going to file a issue in the original dbus package, dbus-native is not a drop in replacement unfortunately and I don't want to have to rewrite the node-mpris module to make it work.

**Comment by jostrander** [comment]
Issue raised: https://github.com/Shouqun/node-dbus/issues/120

**Comment by BrianAllred** [comment]
@wengole I maintain the Arch packages, if you need help with the pkgbuild at all, shoot me a mention.

@jostrander @MarshallOfSound  Let me know if I can help at all. Also, if there's a way to auto-mention someone by keywords, I'm more than willing to get auto-notified of Arch bugs since they could definitely be related to my pkgbuilds.

**Comment by jostrander** [comment]
This has a PR upstream and should be fixed as soon as its merged, provided node-mpris package (or @MarshallOfSound's clone) gets updated to use the new version.

**Comment by MarshallOfSound** [comment]
@jostrander Can you link the upstream PR so I can follow it's progress

**Comment by jostrander** [comment]
https://github.com/Shouqun/node-dbus/pull/121

**Comment by MarshallOfSound** [comment]
@jostrander I have just updated my fork with that PR.  Deleting that node module and reinstalling on your machine should fetch the latest version :+1:

**Comment by jostrander** [comment]
@wengole, can you confirm the above PR works for you?

**Comment by wengole** [comment]
@jostrander That works, thanks all.

What I did was fork your fork @jostrander then rebase it off @MarshallOfSound's master, then rebuild the Arch package off my fork. Fun times. But it's working now.
