### ISSUE TITLE
[Enhancement] Keep search bar in focus upon auto-searching

### ISSUE THREAD

**Issue by SpectralKH** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#907]
So, if you wait long enough, and you have some text in the search field, GPM will automatically search for you. When that happens, the search field gets out of focus - Which seems impractical. It doesn't look like there's any hotkey functions to execute once you've searched anyway. So having it focused would be useful, for example when I'm browsing through a podcast, checking if I've got all the songs from it - Then I've got a list in front of me, with stuff to write and search for there; Having to click again and again and again is pretty inefficient.

**Comment by jostrander** [comment]
If I'm not mistaken about what you're saying you can either use the / key
or ctrl+f (cmd f) to refocus the search field without having to click.

**Comment by MarshallOfSound** [comment]
Both `Control + F` and `/` will focus the search box again.  I've discussed modification to the search box behavior in other issues.  Basically its a no go :+1:  Use the shortcuts :smile:

**Comment by SpectralKH** [comment]
@jostrander I originally assumed that CMD+F worked, but nothing happens when I use it. / does not work either, as it opens a keybord shortcuts cheat sheet.

**Comment by jostrander** [comment]
The forward slash shouldn't bring up the menu unless you're holding shift.
As far as command F that should be working. Can you send a screen shot of
what's loaded when you try either?

**Comment by MarshallOfSound** [comment]
@jostrander Thinking about it "Command + F" is implemented in master not in a release version yet :cry:

**Comment by jostrander** [comment]
Ah yep. Confusing at times when there are multiple release patterns for each OS. So no command+f yet. Sorry @SpectralKH. However as stated `/` should work as its a native GPM key.

**Comment by SpectralKH** [comment]
@jacobmischka @MarshallOfSound Awh, that sucks, got any ETA on the next release then?
However, / does not work for me. It just opens this menu here, which ironically also shows the search shortcut being /.
![screen shot 2016-04-06 at 18 27 21](https://cloud.githubusercontent.com/assets/11315492/14324476/39170ee8-fc25-11e5-803e-fdf58cc4651e.png)

**Comment by SpectralKH** [comment]
@MarshallOfSound @jostrander Just by the way, do you know if the built-in media shortcuts for Previous Track/Pause are implemented, cause it doesn't seem like they do to me? I have a standard Apple keyboard, whereas only the "Next Track" media key works. This is kind of a bummer as someone with a gaming mouse with 6 keys used for music/volume :p

**Comment by MarshallOfSound** [comment]
Those media keys are definitely implemented and definitely work on OS X.  Do those media keys work in any other application (thinking it could be a hardware issue)?

**Comment by SpectralKH** [comment]
@MarshallOfSound Actually, no. I should've checked beforehand. Will have to look into it myself :)
