### ISSUE TITLE
Spinning Circle (Will not load Certain Artist)

### ISSUE THREAD

**Issue by IceKreem** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#91]
When I click on Chase & Status (Artist) it loads the artist and shows their songs etc. .If I back out (go to Listen Now) and click Chase & Status again all I get is a spinning circle. I noticed that it only happens to this Artist. It will not work again unless I quit the app and re launch and then the same occurrence again and again.

![1](https://cloud.githubusercontent.com/assets/15200832/11768669/eea0eef0-a1cb-11e5-90be-05d5a142c79e.JPG)
![2](https://cloud.githubusercontent.com/assets/15200832/11768670/eea342b8-a1cb-11e5-8c81-c67fabc8e236.JPG)

**Comment by MarshallOfSound** [comment]
That sounds like a Google Play Music bug, can you check if the same thing happens in a browser

**Comment by IceKreem** [comment]
Yeah your right. Sorry completely forgot to check the browser (that's how good your app is :P) .

**Comment by MarshallOfSound** [comment]
No problem, maybe try raising it with Google support, they might be interested :)
