### ISSUE TITLE
Video button lays on top of thumbs up button in mini player

### ISSUE THREAD

**Issue by bencmeyer** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#911]
Windows 10 64 bit Build 10586

When in the mini player, if the music playing has a video option, the video button lays over the thumbs up button regardless of size.

Play song that has a music video option.

![desktop player video icon](https://cloud.githubusercontent.com/assets/11997284/14336969/ffcbb0a8-fc2e-11e5-8449-a1991c710735.PNG)

**Comment by bencmeyer** [comment]
I guess another issue is, if you click the video button... it starts playing within the app, but you can't control it from the mini player. Interesting.

**Comment by MarshallOfSound** [comment]
There is an open issue for this one on the mini player repository
