### ISSUE TITLE
Uncaught Exception: Attempting to call a function in a renderer window that has been closed or released. Function provid

### ISSUE THREAD

**Issue by Yages** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#912]
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.1
**Time:** Thu Apr 07 2016 13:39:20 GMT 1000 (AUS Eastern Standard Time)

#### Error:
*Attempting to call a function in a renderer window that has been closed or released. Function provid*
```js
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: Object.<anonymous> (C:\Users\Lucas\AppData\Local\GPMDP_3\app-3.0.1\resources\app\build\inject\GPMInject\interface\mouseButtonNavigation.js:8:8.
    at BrowserWindow.callIntoRenderer (C:\Users\Lucas\AppData\Local\GPMDP_3\app-3.0.1\resources\atom.asar\browser\lib\rpc-server.js:201:19)
    at emitTwo (events.js:92:20)
    at BrowserWindow.emit (events.js:172:7)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by GPMDP-Magical-Unicorn** [comment]
Closing this automatically reported issue as a duplicate of #470

**Comment by MarshallOfSound** [comment]
@Yages Can you please send me a copy of your squirrel log file found at

`%LOCALAPPDATA%\GPMDP_3`

**Comment by Yages** [comment]
Sure can, just tacked .txt on the end to keep GitHub happy.  I also noticed it had an update available when I restarted.
[SquirrelSetup.log.txt](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/207710/SquirrelSetup.log.txt)

**Comment by GPMDP-Magical-Unicorn** [comment]
Closing this automatically reported issue as a duplicate of #470

**Comment by jostrander** [comment]
The unicorn was not happy.
