### ISSUE TITLE
WebSocket API should implement some kind of zeroconf

### ISSUE THREAD

**Issue by MarshallOfSound** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#913]
Looking at something like https://www.npmjs.com/package/polo

**Comment by mmazzarolo** [comment]
I'm at work right now so I can't investigate further but it seems that the polo package uses dependencies not available in React-Native (`request` is node-only for example, just like `http`).

**Comment by MarshallOfSound** [comment]
@mmazzarolo I just got back to looking into this and it appears there are React native modules that fill in those node gaps.  For instance 

`dgram` = https://github.com/tradle/react-native-udp
`net` = https://www.npmjs.com/package/react-native-tcp
`http` = https://github.com/tradle/react-native-http

**Comment by mmazzarolo** [comment]
Ops, didn't see the notification, I'll take a look in my free time, thanks :)

**Comment by MarshallOfSound** [comment]
@mmazzarolo The current zero conf implementation is through the bonjour standard

It looks like you can use https://www.npmjs.com/package/react-native-bonjour

I'll document the service config soon
