### ISSUE TITLE
Media keys do nothing MATE

### ISSUE THREAD

**Issue by mattcfox** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#915]
**ENV:**
Fedora 23 MATE spin
MATE 1.12.1
Player verison 3.1.0
**Issue Descriptions:**
The media keys, they do nothing.   I don't believe I've got Chrome hogging them.

I was able to work around this issue by mapping the keys to dbus methods.
ex.
`dbus-send --session --type=method_call --dest=org.mpris.MediaPlayer2.google-play-music-desktop-player /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause
`

**Comment by MarshallOfSound** [comment]
Just going to ping the residential linuxy dbus person @jostrander

**Comment by mattcfox** [comment]
FYI, this is the dbus signal for Play/Pause on MATE
```
signal time=1460075014.792564 sender=:1.27 -> destination=(null destination) serial=82 path=/org/mate/SettingsDaemon/MediaKeys; interface=org.mate.SettingsDaemon.MediaKeys; member=MediaPlayerKeyPressed
   string "MsdMpris"
   string "Play"
```

**Comment by jostrander** [comment]
Thanks @mattcfox. I'm going to take a look and see if mate follows the same syntax as gnome, and if so figure out how to pick up which one is available currently and forward the right Dbus info. Currently keys are only available for gnome desktop over dbus.

**Comment by mattcfox** [comment]
@jostrander, I think that PR will solve it.
