### ISSUE TITLE
Feature Request: How about an ARM version?

### ISSUE THREAD

**Issue by TheDJ42** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#918]
Hey there, I absolutely love this. I've been using it both on a personal machine running Linux and a machine that I use for a computer programming class running Windows. At home I have a Raspberry Pi 2 running Ubuntu Mate, It's connected to my TV and I thought it would be cool to use this player because clearly a browser is not an option. And I'm not a terribly large fan of downloading a bunch of MP3 files. I tried building from source on my Pi and got several errors before the build eventually failed. I know but a little about compiling from source, but I'm assuming that the build failed because I was building X86 code on an ARM System. If nobody else is interested then this can be dropped, but I think that this would fit right in on the Raspberry Pi.

**Comment by MarshallOfSound** [comment]
I don't see why the code won't compile on a raspberry pi.  What commands did you run to try get it working?

Unfortunately my raspberry pi is in a different country right now :cry: so I can't test this myself.  Unless there is a raspian VM :+1:

**Comment by jostrander** [comment]
Travis has arm builds I think, something we can possibly use?

**Comment by TheDJ42** [comment]
I used NPM like it said in the README. I'm not familiar with npm like I am with GCC and mono so I couldn't tell you why it failed.

**Comment by MarshallOfSound** [comment]
This seems relevant https://github.com/electron/electron/issues/5069

**Comment by TheDJ42** [comment]
It might be relevant. Do you want me to upload the build logs? Also important: I'm not using Raspbian, I'm using Ubuntu Mate 15.10

**Comment by MarshallOfSound** [comment]
Yes please, upload them and I'll see what's going on :+1:

**Comment by TheDJ42** [comment]
[Here is the build log](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/210971/npmlog.txt)

**Comment by MarshallOfSound** [comment]
This bit right here is your problem

```js
gyp ERR! node -v v0.10.25
```

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/Development-FAQ#all-platforms

We require node `4.4.1`

**Comment by MarshallOfSound** [comment]
The easiest way for you to get up to date is to install [nvm](https://github.com/creationix/nvm)

**Comment by TheDJ42** [comment]
There does not appear to be an ARM version of nvm in the Ubuntu Mate Repos. Is there source code I can build from?

**Comment by MarshallOfSound** [comment]
Try running 

`curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash`

**Comment by MarshallOfSound** [comment]
@TheDJ42 Any work on this, can I close this issue as a node version issue?

**Comment by TheDJ42** [comment]
I haven't been able to compile recently due to technical difficulties. I
will be able to tell you later today.

On Sun, Apr 10, 2016 at 9:30 AM, Samuel Attard <notifications@github.com>
wrote:

> @TheDJ42 <https://github.com/TheDJ42> Any work on this, can I close this
> issue as a node version issue?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/918#issuecomment-207999961>
>



-- 
--

Dylan Johnson

**Comment by TheDJ42** [comment]
As of right now I'm getting the same build errors that I was getting before. (Node errors.)

**Comment by TheDJ42** [comment]
After updating node I got the first step, however when running 'npm run build' I get this:

dylan@System-4:~/src/Google-Play-Music-Desktop-Player-UNOFFICIAL-$ npm run build

> google-play-music-desktop-player@3.1.0 build /home/dylan/src/Google-Play-Music-Desktop-Player-UNOFFICIAL-
> gulp build

[17:21:49] Requiring external module babel-register
module.js:327
    throw err;
    ^

Error: Cannot find module './lodash'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/dylan/src/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/lodash/index.js:1:80)
    at Module._compile (module.js:409:26)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/dylan/src/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/babel-register/lib/node.js:134:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

npm ERR! Linux 4.1.15-v7+
npm ERR! argv "/home/dylan/.nvm/versions/node/v4.4.1/bin/node" "/home/dylan/.nvm/versions/node/v4.4.1/bin/npm" "run" "build"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! google-play-music-desktop-player@3.1.0 build: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the google-play-music-desktop-player@3.1.0 build script 'gulp build'.
npm ERR! This is most likely a problem with the google-play-music-desktop-player package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs google-play-music-desktop-player
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls google-play-music-desktop-player
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dylan/src/Google-Play-Music-Desktop-Player-UNOFFICIAL-/npm-debug.log

**Comment by MarshallOfSound** [comment]
Did you run `npm install`

**Comment by TheDJ42** [comment]
Yes I did.

**Comment by MarshallOfSound** [comment]
Can you post the output of `ls node_modules`

**Comment by TheDJ42** [comment]
`babel-preset-es2015        electron-packager     gmusic-mini-player.js     gulp-clean     gulp-replace                    md5                 npm-debug.log      winston
babel-register             electron-prebuilt     gmusic-theme.js           gulp-concat    html-entities                   mkdirp              pre-commit         ws
chai                       electron-rebuild      grunt                     gulp-cssmin    jquery                          mocha               pretty-colorwheel  xss
dbus                       electron-winstaller   grunt-cli                 gulp-electron  lastfm                          mocha-sinon         request            yargs
electron-installer-debian  eslint                grunt-electron-installer  gulp-grunt     lodash                          mouse-forward-back  semver
electron-installer-redhat  eslint-config-airbnb  gulp                      gulp-less      material-design-icons-iconfont  mpris-service       sinon
electron-mocha             gmusic.js             gulp-babel                gulp-rename    materialize-css                 node-fetch          sinon-chai
`

**Comment by MarshallOfSound** [comment]
Try running `npm i -g npm`

Then delete the `node_modules` folder

Then run `npm install`

**Comment by MarshallOfSound** [comment]
There are quite a few electron issues with running on Raspberry Pi's, I'm going to close this as an upstream issue
