### ISSUE TITLE
JavaScript exception on launch

### ISSUE THREAD

**Issue by RemeJuan** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#923]
**OS:**
Windows 10 Pro
**Issue Descriptions:**
When Launching the application I am thrown an error :

'A JavaScript error occurred in the main process.

Uncaught Exception:
SyntaxError: Unexpected token

**Steps to Reproduce:**
Happens on launch every single time, have reinstalled the application, disabled AV, run as admin, uninstalled/reinstalled.

**Comment by jostrander** [comment]
Can you delete the `%localappdata%\GPMDP_3` folder and reinstall?

**Comment by MarshallOfSound** [comment]
What @jostrander said is the known fix for this issue.

**Comment by RemeJuan** [comment]
I did that, 3 times before posting this, deleting files is part of the uninstall process, it does not work, it fixes nothing.

I just did it once again rite now, deleted the files, redownloaded the installer, reinstalled, aaand error.

**Comment by MarshallOfSound** [comment]
@RemeJuan There are quite a few folders and not all are deleted during uninstall.

`%LOCALAPPDATA%\GPMDP_3`  
`%APPDATA%\Google Play Music Desktop Player`
`%LOCALAPPDATA%\Google Play Music Desktop Player`

All 3 folders might need to be manually deleted

**Comment by RemeJuan** [comment]
Aha, thanks, that third one however I did not have, there was a GPMDP in AppData\Roaming though which I deleted anyway.
