### ISSUE TITLE
Zooming out mulitple times makes the interface disappear permanently 

### ISSUE THREAD

**Issue by Noobevil** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#924]
**OS:** OS X 10.11.14

**Issue Descriptions:** When zoomed out too much the screen goes black and then there is no way to go back.

**Steps to Reproduce:** Zoom out all the way.

**Comment by MarshallOfSound** [comment]
That's an interesting bug, but, you can get back by zooming back in or resetting the zoom with Control + 0  (it might be Command + 0 on mac)

**Comment by Noobevil** [comment]
Thanks, I've tried zooming back out and its not doing anything, same with Command + 0, usually it works but I was in fullscreen at the time. Is there a way to delete settings file to reset saved settings of the program to get back to default settings ?

**Comment by MarshallOfSound** [comment]
Yep, you just need to find the `settings.json` file and modify the "zoom" settings.  Strange that you can't reset with the shortcut though.  I just testing and it works :cry:

**Comment by Noobevil** [comment]
Thats strange, I was just testing how far it goes (usually i can get back) but this time I was in fullscreen mode and the whole screen is black. I can open the settings panel but nothing else is showing.
