### ISSUE TITLE
Stuck on web store after clicking 2 factor extension link

### ISSUE THREAD

**Issue by Pjstaab** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#925]
I have my yubikey setup as one of my 2 factor methods to login. It was the first method it asked for when logging in and it complained about a missing extension and gave a link to the chrome web store. After clicking the link I'm now stuck at the web store and can't get back to google music. Something like a home button would be nice when you get stuck on a page that isn't google music.

**Comment by MarshallOfSound** [comment]
Yeah this is annoying. The workaround currently is too delete the settings file and not go there again and the issue has been fixed in master
