### ISSUE TITLE
Adjust show funtionality

### ISSUE THREAD

**Issue by rgavs** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#927]
**OS:** Archlinux
Window Manager: Openbox
GPMDP version: 3.1.0.29.gbbe5111-1
**Issue Descriptions:**
In the tray, when selecting "Show" it simply unminimizes the window, that however is less helpful if it is not on the current desktop. If "Show" could be made into a hook for the desktop environment/window manager it would be far more helpful.

**Comment by jostrander** [comment]
Can you explain in a little bit more detail what you're looking for as far as a hook goes?

**Comment by rgavs** [comment]
Actually, hook is not the right term.

What I mean to say is when using a desktop environment with multiple virtual desktops, it doesn't work as well if `Show` is clicked from another virtual desktop. So I would want the option to either open the window in the current virtual desktop or to switch to the one the window is located. There's a few X utils like xprop or xdpyinfo/xwininfo that get that sort of information- I forget which exactly.

I'll look into it myself at some point anyway to see if I can figure out the implementation.

**Comment by MarshallOfSound** [comment]
So I've given this one a bit of thought and I've come to a personal conclusion that this should be something that electron should handle (and an issue should be raised with them).

My basic reasoning for this is that on Windows 10 it switches virtual desktops to the app when I call `show`.  And on OS X it switches through screens to the app when you call `show`.

I'm interested as to what you think @rgavs @jostrander

**Comment by rgavs** [comment]
That sounds entirely reasonable- I'm exactly very concerned with how the implementation might but that definitely fits the description of what I would like. I'll take a look into electron to see how that might work.

**Comment by jostrander** [comment]
Can we close this an an upstream issue? I don't see this being something that we can fix independently in this project.

**Comment by MarshallOfSound** [comment]
Yeah, was just confirming opinions
