### ISSUE TITLE
Feature Request: Keyboard command to Find

### ISSUE THREAD

**Issue by hschneidman** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#93]
I often use Ctrl+F to find a song or artist from a long list. Would be nice if it was possible to do in the app. It doesn't need to be mapped to Ctrl+F necessarily.

**Comment by FuzzAU** [comment]
I'm submitted a pull request #103 for this feature, I thought it was a good idea

**Comment by MarshallOfSound** [comment]
@FuzzAU next time in your PR description say "Fixes #93" then when it gets merged this issue will automatically close :+1:
