### ISSUE TITLE
Keeps pausing/resuming based on clicks to any item

### ISSUE THREAD

**Issue by LiamDawe** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#930]
On Ubuntu Linux 16.04, any time it's playing music, if I click any other item the music will pause (or play if paused).

It's making using the app impossible to use.

Version 3.1 downloaded direct from website.

**Comment by jostrander** [comment]
While I'm not running 16.04, I am running 14.04 and 15.10 and I don't have this issue, can you explain in more detail what's happening?

**Comment by MarshallOfSound** [comment]
@LiamDawe I had this issue yesterday for a brief period of time.  It appears to have been a bug in Google Play Music as a simple restart of the app fixed the issue

**Comment by LiamDawe** [comment]
Weird, I did quit and restart a few times, but it's fine today.
