### ISSUE TITLE
Enable playback of local files

### ISSUE THREAD

**Issue by aouelete** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#932]
Hi, I'm just wondering if there is any possibility to add support for the playback of local files.

Thanks for the great work so far!

**Comment by MarshallOfSound** [comment]
I'm sorry but this isn't something that is possible for this player

**Comment by aouelete** [comment]
Ok

**Comment by BenjaminHCCarr** [comment]
Thanks, if that ever becomes possible that would be great. As I don't always have wifi, and have found that CogX has gotten really long in the tooth (and have reverted to mpv.io). If the Android App can have offline, I am hoping it is a possibility in the future through some library-wizardry that we may be able to play local files, even of we have to resync them from uploaded library? Is it possible to change this from closed to long term goal? I can't remember the github tags.

**Comment by jostrander** [comment]
Unfortunately that would require a lot of overhead and maintenance and it wouldn't be something in the scope of this project, which is to make the online Google music interface more bearable. Why not use a  different player for your local files?

**Comment by BenjaminHCCarr** [comment]
I used https://cogx.org/ for a decade, but it has basically been abandoned:
https://bitbucket.org/mamburu/cog/

But as it was GPL, I went searching and came up with a maintained fork:
https://gitlab.kode54.net/kode54/Cog#
Very lightweight, supports last.fm, output direction, etc.
