### ISSUE TITLE
Unable to change audio device

### ISSUE THREAD

**Issue by Grega216** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#934]
**OS:** Windows 10 (10586.164) Pro and Education 64-bit

**Issue Descriptions:** Cannot change audio device, it just loads ("Loading Devices..."), this problem is affected both of the Windows 10 machines I have tried (school and home)

**Steps to Reproduce:** Right click GPMDP in the notification area and hold over "Audio Device"
![skjermbilde 2016-04-12 11 40 07](https://cloud.githubusercontent.com/assets/12673790/14456096/7af7bb8c-00a3-11e6-95c8-012dbe62d632.png)

**Comment by MarshallOfSound** [comment]
This is a bug that has been fixed in master.  The workaround is go open the settings window and change the audio device from there.  Or just open the settings window and then try changing the audio device from that menu.

TY for the bug report :+1:
