### ISSUE TITLE
Can the player be installed on CentOS 6.7?

### ISSUE THREAD

**Issue by MidnightJava** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#935]
I tried to install the rpm on CentOS 6.7. I have 2.6.32-573.22.1.el6.x86_64 and it said "wrong architecture" when I tried to install the 64-bit Fedora RPM. So I installed the 32-bit Fedora rpm successfully. But after installing 32-bit dependencies one at a time based on "missing library" messages when trying to run the player, I reached the error

google-play-music-desktop-player: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /usr/share/google-play-music-desktop-player/libnode.so)

There doesn't seem to be any way to satisfy that, as I have the latest versions of libstdc++ and glibc installed. I can try building it from source, but I assume I'm going to run into the same issue.

**Comment by jostrander** [comment]
It looks like its a known issue among electron based apps. See https://github.com/Microsoft/vscode/issues/1056 and https://github.com/Microsoft/vscode/issues/3603

I would try compiling from source and see if that fixes your library errors.

**Comment by MidnightJava** [comment]
Thanks. I think it's the same issue that prevented me from installing the atom editor last week. I gave that a good effort and it proved impossible with CentOS 6, so I assume the same will be true here. I'll have to wait until I'm able to move to CentOS 7.

**Comment by jostrander** [comment]
Yeah it's something to do with the c++ version not being latest. You might have luck with source, but only if you can get node/npm running initially.

**Comment by MidnightJava** [comment]
I have installed node v4.4.2 and npm v3.86. npm install completes successfully, but running `npm start` gives the error below. I have `atom-1.6.1-0.1.fc21.x86_64` installed, and it provides libnotify at 
`/usr/share/atom/libnotify.so.4`

```
/opt/git/Google-Play-Music-Desktop-Player-UNOFFICIAL-/node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libnotify.so.4: cannot open shared object file: No such file or directory

npm ERR! Linux 2.6.32-573.22.1.el6.x86_64
npm ERR! argv "/opt/node-v4.4.2-linux-x64/bin/node" "/usr/bin/npm" "start"
npm ERR! node v4.4.2
npm ERR! npm  v3.8.6
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! google-play-music-desktop-player@3.1.0 start: `electron . --dev`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the google-play-music-desktop-player@3.1.0 start script 'electron . --dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the google-play-music-desktop-player package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron . --dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs google-play-music-desktop-player
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls google-play-music-desktop-player
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/git/Google-Play-Music-Desktop-Player-UNOFFICIAL-/npm-debug.log```

**Comment by MarshallOfSound** [comment]
Almost certainly due to the electron prebuilts not working on CENTOS, there is an open issue on the electron repository for fixing certain linux builds.  Unfortunately not much I can do :cry:

**Comment by jostrander** [comment]
Do you have an entry for that directory inside your `ld.so.conf` configuration? `/etc/ld.so.conf.d/` should have something like `atom.conf` since atom is providing that library. 

I would check by grepping the directory for `/usr/share/atom/` via 
```
grep -r '/usr/share/atom' /etc/ld.so.conf.d/
```
That should tell you if you have that library registered with ld, which assuming by that error, it is not.

**Comment by MidnightJava** [comment]
Thanks for the suggestion, but unfotuntaely it didn't solve it. I didn't have any file with a `/usr/share/atom` entry. so I added one, and re-ran `npm run build`, and `npm start` still fails with the same message.

**Comment by jostrander** [comment]
You'd have to run `ldconfig -v` as root in order for the cache to be updated. Also assuming you created a file called (for eg.) `atom.conf` with contents `/usr/share/atom`.

**Comment by MidnightJava** [comment]
Yes I created a file in `/etc/ld.so.conf.d/` with a single entry `usr/share/atom` and ran `ldconfig -v`.

**Comment by jostrander** [comment]
Yeah then the underlying issue is still probably the electron prebuilt binaries. :-1: Sorry, wish I had a solution.
