### ISSUE TITLE
Search Function Within The App Doesnt Work

### ISSUE THREAD

**Issue by sh8v** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#939]
OS: Windows 10

When using the windows 10 desktop app the search function does not allow the user to search through their own music library. When entering text within the 'search music' field located at the top, a loading circle appears and then a subsequent blank screen. No results appear

**Comment by jostrander** [comment]
Screenshot? Have you tried restarting the app, what version are you on?

**Comment by sh8v** [comment]
I'm using Version 3.1.0. I have restarted the app on numerous occasions and the problem still persists.
I have attached tw
![screenshot 1](https://cloud.githubusercontent.com/assets/18438398/14488264/3d1a0b14-015f-11e6-8b6e-7bec72166938.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/18438398/14488265/3d1b1306-015f-11e6-93c7-e612666950e1.png)

o screenshots, Screenshot 1 shows that i do indeed have some drake songs in my library, but when i search for 'drake' in the search field, no search results appear (screenshot 2)

**Comment by MarshallOfSound** [comment]
This would appear to be either a network issue or an issue internally inside Google Play Music itself.  We do not control or influence this functionality in any way.  I would recommend restarting the app and/or testing the search in a real browser.

**Comment by SolarPolarMan** [comment]
I got this today and can confirm it doesn't work on my webbrowser. It may be to do with electron not having flash, as google music is now asking me to get flash.

**Comment by MarshallOfSound** [comment]
@SolarPolarMan Can you explain more in depth your comment, it appears to contradict itself :confused: 

1. Does the search function work in the Desktop Player?
2. Does the search function work in Google Chrome?
3. Does the Desktop Player ask you to install Flash?
4. Does google chrome ask you to install flash?
5. Does music still play in the Desktop Player?
6. Does music still play in chrome?

**Comment by SolarPolarMan** [comment]
1. Not for me.
2. Not on my chromium browser or in firefox.
3. It did after their update but I dismissed it.
4. It did after their update but I dismissed it.
5. Yes
6. Yes

**Comment by MarshallOfSound** [comment]
@SolarPolarMan Thanks for the responses.  It looks like Google messed up quite a few users in a recent round of A/B testing.  All I can say is I hope google fixes these issues for you soon
