### ISSUE TITLE
Next/previous view navigation

### ISSUE THREAD

**Issue by rgavs** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#942]
OS: Arch linux

I am unsure if this what is meant by "ways to go forward and backward" in #941 or if this should be in #413- in either case go ahead and close this. Otherwise, I have seen a number of instances discussing hotkeys but they seem to be primarily concerned with playback. I am interested in standard browser-like forward/backward navigation as in ALT-left or ALT+right within a view stack.

**Comment by MarshallOfSound** [comment]
@rgavs We currently support  a wide variety of keyboard and UI control for forward/back navigation.

* Mouse button 4 & 5 (Windows and Linux)
* UI Back Button (All Platforms)
* The "backspace" key (All Platforms)
* 3 Finger Swipe (OS X)

Do you still feel that the hotkey "Alt + Left" and "Alt + Right" fill a gap in this list?

**Comment by rgavs** [comment]
Ah, I had not realized backspace serves that functionality. Sorry I thought I had done exhaustive searching.

But of my personal opinion, I would like "Alt + Left" & "Alt + Right" as it mirrors the standard configuration on most web browsers. So I just think that the addition of those two keybindings would make for a more seamless transition for users having traditionally used a browser.

**Comment by rgavs** [comment]
I would also add, which I just realized, that I had not created an issue for this purpose earlier because I have two devices- a desktop and laptop, both Archlinux- where I had been utilizing the Mouse 4 & 5 button control without thinking about it.

So this is just to specify that the requested keybinding stems most from minor differences in my accustomed workflow on a laptop vs desktop with mouse.
