### ISSUE TITLE
When changing track, a popup shows instead of notification

### ISSUE THREAD

**Issue by ryanguy426** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#947]
**OS:**
Ubuntu 16.04 Beta 2 (all updates)

**Issue Descriptions:**
On version below 16.04 (15.10 for example, tested), it'll show a notification with Notify-OSD when the song changes. On 16.04, it'll show a popop ([as shown in this screenshot](https://i.imgur.com/lpi1fDf.png)).

**Steps to Reproduce:**
* Install Ubuntu 16.04 Beta 2 (my install is fully updated)
* Install the amazing GPM app you've created
* Play anything that requires the player to switch songs (playlist, album, radio)
* Wait for it to switch songs
* Look, a popup! And it has your eyes!

*Update: If you do not close the popup, another will stack on the next song change, and so on*
*Update 2: It minimizes fullscreen apps*

**Notes:**
I'm fully aware I'm running a pre-release Operating System. I know to expect bugs and issues, and that's exactly why I'm running it. So I can report any issues to developers (such as you) so it can be fixed before the public release.

**Comment by jostrander** [comment]
There is an upstream issue that has been fixed, that should be in the next release that isn't present in the current release.

**Comment by MarshallOfSound** [comment]
As @jostrander mentioned this bug was fixed in the latest release of electron.  

https://github.com/electron/electron/releases/tag/v0.37.6

The next release of GPMDP (which you can track here #941 will include this updated version of electron and therefore fix this issue
