### ISSUE TITLE
Uncaught Exception: Update download failed: (null)

### ISSUE THREAD

**Issue by namgdev** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#948]
An uncaught exception was reported.  
#### Info:
**OS:** darwin
**Arch:** x64
**GPMDP Version:** 3.0.0
**Time:** Sat Apr 16 2016 18:47:36 GMT 0100 (BST)

#### Error:
*Update download failed: (null)*
```js
Error: Update download failed: (null)
    at Error (native)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by GPMDP-Magical-Unicorn** [comment]
Closing this automatically reported issue as a duplicate of #606
