### ISSUE TITLE
OS X wrong shortcuts

### ISSUE THREAD

**Issue by SpectralKH** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#949]
Lots of shortcuts here are using CTRL instead of CMD, like search should be CMD+F, zoom should be CMD++/CMD+-,

**Comment by SpectralKH** [comment]
CMD also does not work in the hotkey configurations

**Comment by MarshallOfSound** [comment]
@SpectralKH The hotkey config has its own issue #413
