### ISSUE TITLE
GPDMP refuses to open on my Surface Pro 3 w/ up-to-date Windows 10

### ISSUE THREAD

**Issue by ericralph** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#95]
I love this app and use it all the time on my desktop running Windows 8.1. I would love to use it on my SP3 as well but it simply refuses to open :( I've tried the current version (1.9.2) and two most recent previous builds both in x86 and x64 and neither have worked. I have the most recent version of Flash installed, btw. 

Let me know how I might help you get to the bottom of this issue, as I'd love to use your great app.

**Comment by MarshallOfSound** [comment]
Easy: Download either the x86 or x64 version of this https://www.microsoft.com/en-nz/download/details.aspx?id=30679

if you get the x86 version you need the x86 version of this app, if you get x64, you need the x64 version of this app.

Have fun :smile_cat:
