### ISSUE TITLE
Add support for spacebar in windows hotkeys

### ISSUE THREAD

**Issue by toddmedema** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#950]
**OS:**

Windows 10

**Issue Descriptions:**

Cannot create hotkeys that utilizes the spacebar, such as ctrl + shift + space to pause

**Steps to Reproduce:**

Try to create a hotkey with ctrl + shift + space

**Comment by MarshallOfSound** [comment]
Can you please add this as a comment to #413
