### ISSUE TITLE
OS X: Icon changed to the default electron icon after update to 3.2.0

### ISSUE THREAD

**Issue by udeyrishi** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#952]
OS: OS X El Capitan v10.11.4
Issue Description: The merged google play-electron icon is no longer being displayed; instead it's the default electron icon (see image attachment).
Steps to Reproduce: Upgrade to the latest version 3.2.0
Comments: Not sure if this is an intentional change. Please ignore if it is.

<img width="245" alt="screen shot 2016-04-17 at 12 06 30 pm" src="https://cloud.githubusercontent.com/assets/4692593/14589003/d68e65be-0494-11e6-8da5-6e40f3466d96.png">

**Comment by MarshallOfSound** [comment]
Can't believe I missed this...

Fixed in 1faa02569e659da32f2fa3c478d3b2bfc1f55503
