### ISSUE TITLE
OSX Gesture navigation not working

### ISSUE THREAD

**Issue by Nxt3** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#954]
**OS:** OSX 10.11.3

**Issue Descriptions:** Three finger swipe doesn't work; also, it should be a two finger swipe as three finger swipe interferes with switching between desktop spaces.

**Steps to Reproduce:** Try to swipe back

**Comment by MarshallOfSound** [comment]
Yeah, I totally didn't test this.  I just implemented the method (I don't have a mac).  From what I can tell you need certain settings turned on in System Preferences.

You can read more about that here https://github.com/electron/electron/pull/4843

As for two finger swiping, that's a different story.  I can look into it but it is hard to test code without a mac

**Comment by hugomd** [comment]
@MarshallOfSound I'm happy to test it on mine if you want to send me beta builds.

**Comment by MarshallOfSound** [comment]
@hugomd It's the kind of thing that you need to muck around with numbers for.  Electron doesn't actually support a "2 finger" swipe event.  The way others have implemented it is to listen for the `wheel` event on the window.  https://developer.mozilla.org/en-US/docs/Web/Events/wheel

And then use to calculate horizontal scroll velocity, determine if it should be considered a swipe, and if so use the scroll touch events in electron [down](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#event-scroll-touch-begin-os-x) and [up](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#event-scroll-touch-end-os-x) do determine when to consider it an actual 2 finger swipe.

That velocity calculation is something that will take a lot of trial and error :+1:

**Comment by Nxt3** [comment]
Not sure if this is possible, but if you were to implement the code, I could fix the plugging/chugging of numbers and fix it for you.

**Comment by MarshallOfSound** [comment]
@hugomd @Nxt3 I got my hands on a mac laptop and implemented this, if either of you are running the dev version can you pull the latest master and make sure you're OK with how it works 👍

**Comment by PierBover** [comment]
Um doesn't work for me.

I'm on 4.0.5.

**Comment by MarshallOfSound** [comment]
> Sorry, it does work, but it requires a really fast swipe compared to other apps like Chrome or Safari.

Gotta get some exercise 😆 It depends on scroll speed settings I think so it varies from device to device 😢

**Comment by PierBover** [comment]
What about implementing a setting to allow users to change the speed threshold in the prefs pane?

**Comment by MarshallOfSound** [comment]
@PierBover I don't think MUI has a slider or anything to fill that role but if someone wants to PR in something to fill that role I would consider it.  Mostly I just want to avoid cluttering up the settings window so as long as whatever it is fits in nicely, doesn't take up to much space and clearly follows MDG I'll probably take it 👍
