### ISSUE TITLE
Issue of launching app in windows 10

### ISSUE THREAD

**Issue by adifbbk1** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#957]
All issue are shown in .zip file
[https://mega.nz/#!As0hULoJ!6FRf9HFg3q2gKcrTXxm6c4meGJqthJm7euseEuG1w34](URL)

The app does not just open(in windows 10)

Here is my computer information
[DxDiaguseredited.txt](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/223426/DxDiaguseredited.txt)

**Comment by MarshallOfSound** [comment]
First off, that's quite a cool recording step thingy :+1: 

Secondly, it looks like Google Play Music itself is blocked on your network so it is not loading?  This could be due to a VPN or system level proxy

**Comment by adifbbk1** [comment]
I am having problem in internet only on internet explorer and Microsoft edge that can be fixed by turning off proxy auto-detect
Is this app uses internet explorer plugin?

The steps recording feature is preloaded in windows 10

**Comment by adifbbk1** [comment]
Now, the app was working
Thank You
