### ISSUE TITLE
Now it shows another bug

### ISSUE THREAD

**Issue by adifbbk1** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#958]
![image](https://cloud.githubusercontent.com/assets/18526984/14600103/accafb68-0578-11e6-87d3-20707337a52b.png)

I am from India and this player should show local mp3 in PC instead of google play music website as in mobile app

**Comment by MarshallOfSound** [comment]
This is out of my control.  There are other issues on this repo explaining why
