### ISSUE TITLE
WebSocket API should provide complete status on connect

### ISSUE THREAD

**Issue by LoKaDah** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#959]
Howdy! First of all, props on a fantastic job on this project! You're the whole reason I've even decided to use GPM again. 

As a legacy user of a Logitech G15 keyboard, I decided to jump in and port the SpotifyStatusApplet plugin that displays playback info on the keyboard's LCD over to your program. So far it works pretty well if the player is playing, however I've noticed that there's no method of getting the WebSocket to provide current song info through the API if the app connects while the player is paused. Just wondering if you could change the on connect handler to send all of the channels when the WebSocket gets a connection regardless of the status of the player so I have something to display on the LCD if it's paused.

I must say the API is pretty slick regardless of this issue! I have some plans to use the GMusic API returns to do some fun stuff with controlling rating and repeat/shuffle via the soft buttons on the LCD display.

Thanks again for all you've done with this project!

**Comment by MarshallOfSound** [comment]
Hmm, that's an interesting flaw in the internal `PlaybackAPI` looks like my internal method `getCurrentSong()` returns `null` if the player is paused.

**Comment by kratos1212** [comment]
@LoKaDah Will be your GM plugin released publicly?

**Comment by LoKaDah** [comment]
@kratos1212 That's the plan. There's a few things that need doing before I put it up somewhere but you'll probably see it in the next couple of weeks.
