### ISSUE TITLE
Back/forward shortcuts interfering with

### ISSUE THREAD

**Issue by SpectralKH** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#960]
OS X

Click a song, press E, and click on a text field. Then, navigate through the text using ALT (That jumps the "cursor" word-by-word. When you do this, it both triggers that AND page navigation; ALT + <- gets you back to your previous page. Because of that, the text input field also gets out of focus. This might apply to other scenarios too?

**Comment by MarshallOfSound** [comment]
OK, I know what the issue is here.  I'll fix it tomorrow :+1:  #tired
