### ISSUE TITLE
When GPMDP updates, it creates a desktop shortcut

### ISSUE THREAD

**Issue by rgoliveira** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#962]
**OS:** Windows 10 (64 bits)

**Issue Descriptions:** Everytime GPMDP updates, it creates a desktop shortcut.

**Steps to Reproduce:** With GPMDP installed and no shortcut to it on the desktop, let it update to a new version. A shortcut will be created without asking.

**Comment by MarshallOfSound** [comment]
Looks like this https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/squirrel.js#L31 should be moved from the update handler to the install handler
