### ISSUE TITLE
Feature request: use Windows 10s colors

### ISSUE THREAD

**Issue by Grega216** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#964]
**OS:** Windows 10

Is there possible to make an option for Windows 10 user that uses the colors and dark mode from the new Windows 10 theme and automaticly applies them?

**Comment by jostrander** [comment]
The API for this would be something either provided by electron or a native module, neither which currently exist to my knowledge. Not to mention the "Dark mode" is a registry hack currently is it not? That would require reading values directly from the registry, which in some versions of windows requires elevated privileges.

**Comment by Grega216** [comment]
In the newest Insider Preview they have made the Dark Mode a option in the Settings program

**Comment by maarten1055** [comment]
Dark mode is only for UWP (metro) apps, so this will probably not work natively.

**Comment by MarshallOfSound** [comment]
This is tricky in the sense that reading both dark mode and the custom color will require reading the registry.  On some systems that might require admin priviledges and from a users perspective, if the turn on the dark theme and it asks for admin control, you would be super suspicious... 

I'll see if there are fancy ways to do this without reading the registry but I'm not in the mood at the moment to write a native c++ module

**Comment by MarshallOfSound** [comment]
The darkMode c++ API and the color API do not appear to have native hooks only fetching methods.  This means that detecting changes without restart will be tricky, nasty and inefficient.  Closing this as there is not a nice way to do this at the moment.
