### ISSUE TITLE
Update the icon to match the new GPM logo

### ISSUE THREAD

**Issue by pcjl** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#965]
For reference: http://officialandroid.blogspot.ca/2016/04/a-new-look-for-google-play-family-of-apps.html

**Comment by MarshallOfSound** [comment]
I considered updating the icon, but personally I don't really like the new one :laughing: 

What do you think of this one?

![play_music_triangle 2](https://cloud.githubusercontent.com/assets/6634592/14627277/2017d560-0636-11e6-87d8-ac04dfca2c96.png)

**Comment by MarshallOfSound** [comment]
New icon added
