### ISSUE TITLE
Ignores Denied Update

### ISSUE THREAD

**Issue by Preston159** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#966]
Unfortunately, because this issue is with the software updater, I will never be able to check that the issue still exists in the latest version (as it doesn't prompt for an update when it is up-to-date).  That being said, I'm currently running 3.2.1, the issue still existed in 3.2.0, and there was no related change in the update log, so I'm assuming the problem still exists in 3.2.1.

**OS:** Windows 8.1

**Issue Descriptions:** When the program prompts for an update, denying the update only lasts for approximately 10 seconds before the program prompts for update again, and it won't stop until you allow the update.

**Steps to Reproduce:** Wait for a new version to be available, deny update, wait for dialog to reappear.

**Comment by MarshallOfSound** [comment]
Oops, looks like I missed a few 0's in my code.  It's set to `12000` milliseconds.  Pretty sure I meant `1200000` milliseconds...
