### ISSUE TITLE
Orange accent in 3.2.1

### ISSUE THREAD

**Issue by RodolfoSan** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#967]
OS: Windows 8/10.

Issue Descriptions: The orange accent is still present even when changing the theme to custom. Is there any way to fix this?

**Comment by jostrander** [comment]
Duplicate of #953

**Comment by RodolfoSan** [comment]
@jostrander It may be, thanks for the help.

**Comment by jostrander** [comment]
If I could reproduce I'd try to help further, but it appears it only happens occasionally. It may already be fixed in master however.

**Comment by MarshallOfSound** [comment]
@jostrander It comes down to load speed of the webview compared to load speed of the local DOM.  There is a race condition that was introduced in electron `0.37.4+` and fixed in master a few days ago
