### ISSUE TITLE
Continue to run on windows 10 with screen off?

### ISSUE THREAD

**Issue by ghostryder13** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#97]
Is there a way to have the program continue playing music with the screen off on Windows 10,

Thanks for the hard work by the way

**Comment by MarshallOfSound** [comment]
What do you mean by screen off?  I can turn my monitors off and it keeps playing perfectly

**Comment by ghostryder13** [comment]
So on my laptop, which is a 2 in 1, as the screen goes to sleep to save
battery music stops playing, unless I am using windows native music
player.  It is not a necessity as for the mean time I just alter the screen
timeout to 5 hrs while playing music.  I was just curious if it was a
possibility.  Thanks for the hard work, it is nice to have a program for
play music.

Thanks

Jim

On Fri, Dec 18, 2015 at 12:22 AM, Samuel Attard <notifications@github.com>
wrote:

> What do you mean by screen off? I can turn my monitors off and it keeps
> playing perfectly
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/97#issuecomment-165699993>
> .
>



-- 
Jim Engelman

**Comment by MarshallOfSound** [comment]
I have looked into this, and unfortunately Microsft do not publish how to do this publicly, it might even just be a side effect of your power settings

**Comment by ghostryder13** [comment]
Fair enough

Thank you
