### ISSUE TITLE
Google accounts with two-factor authentication not working

### ISSUE THREAD

**Issue by DavidDohmen** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#970]
**OS:**
Ubuntu 14.04 (elementary OS)

**Issue Descriptions:**
I know you mention 2 factor authentication but login doesn't work for me with it.

**Steps to Reproduce:**
When using my standard password, Google sends me an SMS with the code but the Google Play Music Desktop Player hangs up. Can kill it but not open it anymore until I restart my computer.
When I try to set up an app-password, the login interface tells me to use my normal login (which doesn't work). So none of the login ways are working and I really don't want to go back to the non-two-factor thing.

Maybe you can look into that, would be greatly appreciated!

**Comment by MarshallOfSound** [comment]
Ta da

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ#i-am-part-of-the-glorious-linux-master-race-and-it-doesnt-go-past-the-sign-in-screen

**Comment by DavidDohmen** [comment]
Ah sorry for bothering! Didn't get this connection!

2016-04-20 13:09 GMT+02:00 Samuel Attard <notifications@github.com>:

> Closed #970
> <https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/970>
> .
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/970#event-634373394>
>



-- 



Schornstr. 6
81669 München



Mobile: +49 - (0)172 - 718 2337

Tel.: +49 - (0)89 - 44 829 12

Fax: +49 - (0)89 - 244 16 160
