### ISSUE TITLE
Window not opening

### ISSUE THREAD

**Issue by samtfischer** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#973]
**OS:**
10.11.4 OSX

**Issue Descriptions:**
When I launch the app, nothing happens. The program launches, but the window doesn't appear.
I tried reinstalling, but that didn't fix the issue

**Steps to Reproduce:**
Launching the app.

**Comment by MarshallOfSound** [comment]
Does the tray icon appear?

If so try using that tray icon to show the window

**Comment by samtfischer** [comment]
The tray icon appears as well as the icon on the dock. I can pull up the settings window through the tray icon, but not the main window.

**Comment by samtfischer** [comment]
The tray icon appears as well as the icon on the dock. I can pull up the
settings window through the tray icon, but not the main window.

Thanks,
Sam Fischer
samtfischer.com

**Comment by MarshallOfSound** [comment]
@samtfischer Hmmm, this is very interesting.  Can you try downloading the code and running it in development mode to see if we can get it to actually spit out an error.

**Comment by samtfischer** [comment]
How do I download the code and run it in development mode?

**Comment by MarshallOfSound** [comment]
So the super simple steps are this

1. Download the [zip file](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/archive/master.zip)
2. Install [NVM](https://github.com/creationix/nvm) on your mac
3. Run `nvm install 4.4.1`
4. Run `nvm use 4.4.1`
5. Run the commands found [here](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#development)

**Comment by samtfischer** [comment]
Sorry for not understanding. How do I actually run nvm install 4.4.1 or any of the other commands? I have the two files downloaded from steps 1 and 2.

**Comment by MarshallOfSound** [comment]
You use terminal, it is in the utilities folder on your mac

**Comment by samtfischer** [comment]
It's telling me that the command isn't found when I run it in terminal

**Comment by MarshallOfSound** [comment]
Did you install NVM with the CURL command in the README of that repository?

**Comment by samtfischer** [comment]
I just installed it with that method. I tried running npm install and it gave me this error: 
![image](https://cloud.githubusercontent.com/assets/18582444/14696478/5720a956-0749-11e6-8c9c-d0cbd8a33b15.png)

**Comment by MarshallOfSound** [comment]
Use the `cd` command to navigate to the folder where use extracted the ZIP file you downloaded in step 1

**Comment by samtfischer** [comment]
Ok I ran the commands on that page and Terminal is showing this: 
![image](https://cloud.githubusercontent.com/assets/18582444/14696695/4205aa88-074b-11e6-8b43-f0d54041dacb.png)

**Comment by MarshallOfSound** [comment]
OK that all looks good, does the player not appear?

What happens when you click on the tray icon and click "Show"

**Comment by samtfischer** [comment]
Nothing happens. Same as if I'm running the app normally.

**Comment by samtfischer** [comment]
Could it have anything to do with Chrome/Chrome extensions?

**Comment by MarshallOfSound** [comment]
No errors appear in the console?

**Comment by samtfischer** [comment]
Nope. What you see in that picture is all that's showing in terminal

**Comment by MarshallOfSound** [comment]
@samtfischer Give me a sec, just finding the path to our error log file.  We can check that in a sec.

**Comment by samtfischer** [comment]
Not a problem

**Comment by samtfischer** [comment]
The settings window still comes up like normal the same way it did in the normal app

**Comment by MarshallOfSound** [comment]
In terminal run

```bash
open ~/Library/Application\ Support/Google\ Play\ Music\ Desktop\ Player
```

Then upload the `gpmdc.log` file to this comment thread

**Comment by samtfischer** [comment]
[gpmdc.log.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/229134/gpmdc.log.zip)

**Comment by MarshallOfSound** [comment]
Hmmmm, there are no usable errors in that log file.  Unfortunately there is not much I can do as I can't replicate this issue and no one else has reported it.

Can you think of ANYTHING that might make your setup unique in any way. (Strange network configuration, using a proxy, using a VPN, strange file system permissions Etc.)

**Comment by samtfischer** [comment]
The only things I can think of is that it's POSSIBLY a permissions issue as I've had issues with permissions on this computer in the past. I also use an app called Bartender that helps organize the tray icons, but I can't imagine that would affect the functionality of the app. I can try checking the permissions in the applications folder as well as the app itself. I've been using the app for a while now and the past versions worked just fine, I think this only started happening when I updated it to the newest version. Is there a way I can install the previous version if no other troubleshooting steps work?

**Comment by MarshallOfSound** [comment]
Yes, you can download the old version from the releases section on github, but it will auto update.  Let me examine the changes between the latest versions to see what might have broken.

**Comment by samtfischer** [comment]
I just fixed the permissions on the applications folder and the application support folder, reinstalled the app and got this error window: 
![image](https://cloud.githubusercontent.com/assets/18582444/14697035/6e74ebd0-074e-11e6-845a-37119438283a.png)

**Comment by MarshallOfSound** [comment]
Delete the app from your applications folder.  And run

```bash
rm -rf ~/Library/Application\ Support/Google\ Play\ Music\ Desktop\ Player
```

**Comment by samtfischer** [comment]
After I click 'OK', the icon appears in the dock and the menubar changes to the app name, but it only gives me the option to quit the app. The tray icon doesn't appear either. 
![image](https://cloud.githubusercontent.com/assets/18582444/14697073/ae2aeae0-074e-11e6-9dfe-b77e967cf23e.png)

**Comment by MarshallOfSound** [comment]
Then re install the app

**Comment by samtfischer** [comment]
Success!
![image](https://cloud.githubusercontent.com/assets/18582444/14697099/e3763038-074e-11e6-95d8-400dd8b1fa18.png)

**Comment by MarshallOfSound** [comment]
So looks like it was all some funky permissions problem :+1:

**Comment by samtfischer** [comment]
Thank you!

**Comment by krainboltgreene** [comment]
I'm having the same issue but it's definitely not a permissions issue.

When I click the mac dock "Show all windows" it appears as a tiny dot.

**Comment by krainboltgreene** [comment]
It appears to have happened because I put the window on my second monitor and my second monitor (my laptop monitor) was off (the laptop was closed).

Opening the macbook and restarting the application shows the window.

**Comment by krainboltgreene** [comment]
Looks like this describes the situation: https://github.com/mawie81/electron-window-state/issues/1

**Comment by MarshallOfSound** [comment]
@krainboltgreene Your inference is incorrect I believe.  I have code that checks if the position / screen is still available before attempting to position it there https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/index.js#L90

**Comment by krainboltgreene** [comment]
@MarshallOfSound Well it seems to not be working because I just spent 10 minutes looking at an empty screen until I opened up my macbook.

**Comment by krainboltgreene** [comment]
Or rather, perhaps Electron is lying to your logic?

**Comment by MarshallOfSound** [comment]
I have tested the logic on a Mac and a Windows machine and the logic works.  This is almost certainly a separate issue.  Possibly something to do with the way that secondary monitors are rendered on OS X.  The GPU is forced on for chromium windows on a secondary display (don't know why) and this could be causing rendering bugs...

But this is almost certainly nothing to do with the re-positioning of windows.

**Comment by krainboltgreene** [comment]
wat

**Comment by jostrander** [comment]
I can't replicate this, however I'm not on OS X. I put the window on a monitor, quit, disabled the monitor and opened the app. App always ended up on an active screen when reopened. Tried with two monitors and laptop screen, toggling one off as well as different monitor layouts.

**Comment by jostrander** [comment]
If you want to help provide debugging information, grab the .settings.json file before, when its open and not showing, as well as after you get it showing. At least then we can see some numbers on where it thinks it should be, etc.
