### ISSUE TITLE
Details show up incorrectly in Windows mixer

### ISSUE THREAD

**Issue by roryhewitt** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#974]
**OS:**

Windows 7 Enterprise

**Issue Descriptions:**

When I open the volume control in the taskbar and click the Mixer link, the SndVol.exe application incorrectly shows the GPMDP application, with almost no data. Even though I can't see the volume slider or the mute button, I can click where they SHOULD be, and they work).

![sndvol](https://cloud.githubusercontent.com/assets/11558891/14691327/77d8cb0e-0705-11e6-88e0-037b39e0a4ad.png)

It LOOKS like the orange triangular image in the lower-right corner is the top-left corner of the GPMDP logo, so perhaps it's 'simply' a scaling issue?

**Steps to Reproduce:**

Start GPMPD and then run SndVol.exe to bring up the mixer.

**Comment by MarshallOfSound** [comment]
This is a known issue with electron and we are waiting for it to be fixed upstream (probably in chromium)

https://github.com/electron/electron/issues/4838
