### ISSUE TITLE
How about to connect "Thumbs" buttons and last.fm loved tracks?

### ISSUE THREAD

**Issue by kilometrix** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#975]
Hi! 

I think that everyone who uses last.fm wants to quickly manage his "loved songs" list with "Thumbs Up" and "Thumbs Down" buttons in player. So...
:+1:  to add track to loved songs on last.fm, :-1:  to remove. Is that function possible?

**Comment by aouelete** [comment]
If possible, I would suggest adding a separate button for last.fm. I use thumbs up/down to refine Google's music suggestions and not all of those songs are worthy of being "loved". 
This is just my opinion.

**Comment by MarshallOfSound** [comment]
I don't see this fitting in with any pre-existing concepts in Google Play Music.  The thumbs up / down don't indiciate like/unlike they indicate like/dislike.  This is a rather significant difference.

I'm not for adding too many buttons to the UI either as it is just asking for trouble.
