### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by M3talArm5** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#976]
Hi There,

I am using Windows 10 Home 64 bit and have downloaded the install from your website but whenever i double click it to install it i get "The installation has failed. Failed to extract installer". I have tried to run it as administrator but that didn't make a difference. I also have tried to download another copy but this didn't work either.

Let me know if you need anything more from me.

**Comment by MarshallOfSound** [comment]
Do you get a SquirrelSetup.log file in `%LOCALAPPDATA%\GPMDP_3`

**Comment by M3talArm5** [comment]
Hi,

Thanks for the reply. I realised as i was looking for the file this morning that it was my anti virus blocking it for some reason. I turned it off and the install went through no problems. 

Thanks again for the program and support.
