### ISSUE TITLE
Went to another webpage, can't get back to player.

### ISSUE THREAD

**Issue by Krojack** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#980]
Need help. Uninstall doesn't seem to clear all settings from the system.

**OS:**
Windows 10

**Issue Descriptions:**
After installing, went to log into my Google account and clicked a link that took me to some other google website within the program.  Now I can't get back to the login or to the Google play where the music is.  I tried uninstalled, removing any registry reference I could find and lingering directories where it gets installed.  After re-install and opening the program it returns to this other web page.  

**Steps to Reproduce:**

**Comment by jostrander** [comment]
Your settings file has the last stored page in it, I believe on windows it's under %localappdata%\GPMDP_3 or %appdata%\google-play-music-desktop-player. Check for a .settings.json file in there and remove the url from in between the quotes, or delete the file if you don't mind losing settings.

**Comment by MarshallOfSound** [comment]
@Krojack This issue has been fixed in master.  The easy work around at the moment is to use the shortcut.

"Control + Shift + G" and enter the url

```bash
https://play.google.com/music/listen#/now
```

This will take you back to Google Play Music
