### ISSUE TITLE
FR: UWP4Win

### ISSUE THREAD

**Issue by MaxRink** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#982]
hi, a port over to UWP for Win would be great as UWP-Apps can use Backgroundaudio which works in connected standby (would be great for notebooks)

**Comment by jostrander** [comment]
Currently this is a limitation of the framework electron which thisbis
built on.

**Comment by j2ghz** [comment]
http://electron.atom.io/docs/tutorial/windows-store-guide/

**Comment by MakuSensei** [comment]
tambien me interesaria ver una version para windows 10 store :3
