### ISSUE TITLE
Three dots menus with dark theme

### ISSUE THREAD

**Issue by shaffe-fr** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#983]
**OS:** any OS.

**Issue Descriptions:** When using the dark theme, three dots menus are not visible on album cards.

**Steps to Reproduce:** Go to Desktop Settings, activate the dark theme, roll over any album card, the three dots menu won't be visible on album cards.

**Comment by MarshallOfSound** [comment]
Fixed upstream

https://github.com/gmusic-utils/gmusic-theme.js/issues/31
