### ISSUE TITLE
Adding a shortcut to the "thumbs up" playlist

### ISSUE THREAD

**Issue by pmsaue0** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#987]
Hello,

I am wanting to add a global keyboard shortcut to navigate to the "thumbs up" playlist.  I think I would like to use:
`.executeJavaScript('document.querySelector(\'a[data-id="auto-playlist-thumbs-up"]\').click();');`

But I'm not sure where to put this code if I want to bind it to F6, for example.

Thanks!
Phillip

**Comment by MarshallOfSound** [comment]
Unfortunately, navigating to playlists through the method you mention results in several internal GPM errors and is not possible at this time
