### ISSUE TITLE
Suggestion: Option to keep left menu always open

### ISSUE THREAD

**Issue by jakelauer** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#988]
I like to keep the menu on the left open all the time. It'd be great if there were an option to keep it open at all times!

**Comment by MarshallOfSound** [comment]
If you simply open the menu once it never closes?  I don't see this as being a widely requested feature and as mentioned in other issues, modifying googles UI is risky at the best of times (UI glitches)
