### ISSUE TITLE
Narrow screen width hides some controls

### ISSUE THREAD

**Issue by tuur29** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#99]
I use my secondary monitor in portrait mode, but it's only 768px wide/high. Apparently Google decided that this screensize isn't important anymore. The global minimum width seems to be around 980px, while the controlbar minimum width is around 850px.
Result: you have to horizontally scroll to see playtimes and the queue and miniplayer buttons are completely hidden. This is the default behaviour on the normal web player as well.
Perhaps you could change this behaviour by removing the album art or scaling the controls?
A simpler option would be to allow us to set a default zoom level.

**Comment by MarshallOfSound** [comment]
I'm working on documentation for this but you can actually set a zoom level (woo hoo).  Just use the shortcuts you would use in any other browser

Ctrl + --> Zooms in
Ctrl - --> Zooms out
Ctrl 0 ---> Resets Zoom
