### ISSUE TITLE
volume controls do not display properly in Volume Mixer on Windows

### ISSUE THREAD

**Issue by ryanrms** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#992]
**OS:**
Windows 10 64 bit - x86 OR x64 version
**Issue Descriptions:**
App isn't shown properly in Volume Mixer in Windows 10.  you can still set the volume for this app separately but it doesn't display properly
**Steps to Reproduce:**
Install either Windows version on Windows 10
Start playback
Open Volume Mixer
Screenshot:  
<img width="344" alt="play music app volume issue" src="https://cloud.githubusercontent.com/assets/2936638/14873837/aea6467c-0cb7-11e6-8fa7-e423e888cfc4.png">

This is the x86 version, but something very similar happens on the x64 version i have on my desktop.

**Comment by jostrander** [comment]
Holy ****, is this because of the tray icon being so huge?! @MarshallOfSound

**Comment by MarshallOfSound** [comment]
@jostrander Yeah, I figured that out a few days ago.  I almost cried....

it's fixed in master
