### ISSUE TITLE
GPMDP toggles pause/play with new pages loading?

### ISSUE THREAD

**Issue by paulietheboss** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#995]
I've noticed that since the most recent update, GPMDP seems to be playing/pausing strangely through use of the back button? For example, I'll go into my library, artists, find an artist, open albums, open an album, play the album. First song plays.

Press back to go to albums, song pauses. Back again, see artist page, song plays. Back again to all artists, song pauses. Same thing happens if I click my library at any point, or do a search. It seems like loading any new page will toggle play/pause. 

I've also noticed that if I have the player minimised and paused it will now seemingly play at random intervals, but won't ever pause when playing in the same situation. This doesn't seem to be tied into any keyboard shortcut I use.

**Comment by MarshallOfSound** [comment]
This is a bug in google play music itself, I thought they fixed it a few days ago, maybe you are still getting the bad files from them.  Regardless, it isn't the apps fault :cry:

**Comment by paulietheboss** [comment]
Ok - sorry about that I just thought I'd bring it to your attention in case it was the app. Thanks for the quick response and update (alos GPMDP is badass!)

**Comment by MarshallOfSound** [comment]
:+1:
