### ISSUE TITLE
orange borders after reboots

### ISSUE THREAD

**Issue by ivesen** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#997]
Windows 10 pro 64-bit

the borders of the music player (both the mini player and the bigger one) are orange the first time I run it each boot.

simply reboot and open the program.

image for reference: http://puu.sh/ozZqJ/0ed7f45e56.jpg

**Comment by MarshallOfSound** [comment]
Fixed in master
