### ISSUE TITLE
Dark theme podcast image has white background

### ISSUE THREAD

**Issue by collinjackson93** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#998]
**OS:** Windows 10 Education 64-bit

**Issue Descriptions:** Dark theme has an issue displaying the podcast image on the "Listen Now" page.

![image](https://cloud.githubusercontent.com/assets/5580739/14933026/7573fb24-0e47-11e6-93ed-bc84626c83ec.png)

**Comment by MarshallOfSound** [comment]
This technically belongs over at https://github.com/gmusic-utils/gmusic-theme.js but I'll eave it here because these issues get more traffic.

Can someone in US who knows how find the CSS selectors for that podcast button.  Unfortunately being from NZ/AUS I can't use podcasts yet.

**Comment by collinjackson93** [comment]
```
<iron-icon icon="sj:podcast" class="podcast-badge x-scope iron-icon-1" title="Has podcasts">
<svg viewBox="0 0 24 24" preserveAspectRatio="xMidYMid meet" class="style-scope iron-icon" style="pointer-events: none; display: block; width: 100%; height: 100%;">
<g class="style-scope iron-icon">
  <path d="M21.2,18.8a11.44,11.44,0,1,0-18.39,0l1.4-1.26a9.56,9.56,0,1,1,15.59,0Z" class="style-scope iron-icon"></path>
  <path d="M18.39,16.27a7.69,7.69,0,1,0-12.79,0L7,15a5.81,5.81,0,1,1,10,0Z" class="style-scope iron-icon"></path>
  <path d="M6,20.5V24H18V20.5c0-2.22-3.78-3.33-6-3.33S6,18.28,6,20.5Zm6-4.83A3.67,3.67,0,1,0,8.33,12,3.67,3.67,0,0,0,12,15.67Z" class="style-scope iron-icon"></path>
</g>
</svg>
</iron-icon>
```

It looks like this is the relevant code. The `iron-icon` element is making the white background. I would be happy to look into the issue further, but I'm in the midst of final exams, so I wouldn't be able to get to it for a few days.

**Comment by eric116** [comment]
I have only a slight familiarity with CSS, but hopefully this helps:

In Chromium's Developer Tools, I added the following style rule to change the podcast badge to white on black.

`.material-card[data-type="situations"][data-is-podlist-situation="true"] .podcast-badge {
    color: #ffffff;
    background-color: #000000;
}`

![screenshot from 2016-05-07 20-54-34](https://cloud.githubusercontent.com/assets/10640906/15095763/eb60bb56-1496-11e6-9788-85ca6bad9c81.png)

This is the file the default properties come from:
https://play-music.gstatic.com/fe/552427ac60e491f579959852e6b4a115/listenstyles_extended_80d882f312bf67807b5b6042e9718ae316b77d10.css

**Comment by BrianAllred** [comment]
I'm getting some decent CSS skill under my belt at work and was going to take a crack at this. Except I have no idea how npm works. I forked the gmusic repo and made some CSS changes, but I don't know how to get that into a custom GPMDP build.

**Comment by MarshallOfSound** [comment]
@BrianAllred There is a [Dev FAQ](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/Development-FAQ)

But basically `npm install && npm run build && npm start` will get a dev version up and running

**Comment by BrianAllred** [comment]
Right, I've got GPMDP cloned and built, and I've also got gmusic-theme cloned and modified, I'm just not sure how to get my gmusic changes into the GPMDP I've built on my system.

**Comment by jostrander** [comment]
I'll preface this with: I'm sure there is a much better way...

You'll need to test by requiring your local copy in package.json instead of
the github version. So what i do is just have the package in a sibling
folder and change the required version to ../package and delete the github
version from node_modules and rerun npm install, start etc. To retest I
remove the package again and reinstall.

Excuse formatting, on mobile. But that's the gist of it.

**Comment by MarshallOfSound** [comment]
@BrianAllred @jostrander The easiest way I found to do it is to modify this line

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/gulpfile.babel.js#L22

To point to your local version of `gmusic-theme`

**Comment by jostrander** [comment]
Well in this particular case that works better, however for some other
native packages that won't work obviously.. Good for future reference
though.

**Comment by jostrander** [comment]
@thedeany has published a PR over here that should fix this: https://github.com/gmusic-utils/gmusic-theme.js/pull/40
